FairRoot: FairUrqmdGenerator Class Reference
FairUrqmdGenerator Class Reference
#include <FairUrqmdGenerator.h>
Public Member Functions
FairUrqmdGenerator ()
FairUrqmdGenerator (const char *fileName)
~FairUrqmdGenerator ()
Bool_t ReadEvent (FairPrimaryGenerator *primGen)
Bool_t SkipEvents (Int_t count)
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
ClassDef (FairGenerator, 1)
Private Member Functions
void ReadConversionTable ()
Input file name.
void CheckReturnValue (Int_t retval)
FairUrqmdGenerator (const FairUrqmdGenerator &)
FairUrqmdGenerator & operator= (const FairUrqmdGenerator &)
ClassDef (FairUrqmdGenerator, 1)
Private Attributes
FILE * fInputFile
std::map< Int_t, Int_t > fParticleTable
Input file.
const Char_t * fFileName
Map from UrQMD PID to PDGPID.
Detailed Description
Definition at line 38 of file FairUrqmdGenerator.h.
Constructor & Destructor Documentation
FairUrqmdGenerator::FairUrqmdGenerator ()
Default constructor without arguments should not be used.
Definition at line 30 of file FairUrqmdGenerator.cxx.
   :FairGenerator(),
    fInputFile(NULL),
    fParticleTable(),
    fFileName(NULL)
 {
 }
FairUrqmdGenerator::FairUrqmdGenerator (const char * fileName)
Standard constructor.
Parameters
fileName The input file name
Definition at line 42 of file FairUrqmdGenerator.cxx.
References FairLogger::endl(), FATAL, fFileName, fInputFile, INFO, LOG, and ReadConversionTable().
   :FairGenerator(),
    fInputFile(NULL),
    fParticleTable(),
    fFileName(fileName)
 {
   //  fFileName = fileName;
   LOG(INFO) << "FairUrqmdGenerator: Opening input file "
             << fileName << FairLogger::endl;
   fInputFile = fopen(fFileName, "r");
   if ( ! fInputFile ) {
     LOG(FATAL) << "Cannot open input file."
                << FairLogger::endl;
   }
   ReadConversionTable();
 }
FairUrqmdGenerator::~FairUrqmdGenerator ()
Destructor.
Definition at line 63 of file FairUrqmdGenerator.cxx.
References fInputFile, and fParticleTable.
 {
   //  LOG(DEBUG) << "Enter Destructor of FairUrqmdGenerator"
   //             << FairLogger::endl;
   if ( fInputFile ) {
     fclose(fInputFile);
     fInputFile = NULL;
   }
   fParticleTable.clear();
   //  LOG(DEBUG) << "Leave Destructor of FairUrqmdGenerator"
   //             << FairLogger::endl;
 }
FairUrqmdGenerator::FairUrqmdGenerator (const FairUrqmdGenerator &) private
Member Function Documentation
void FairUrqmdGenerator::CheckReturnValue (Int_t retval) private
Check return value from fscanf call
Definition at line 348 of file FairUrqmdGenerator.cxx.
References FairLogger::endl(), ERROR, and LOG.
Referenced by ReadEvent(), and SkipEvents().
 {
   if (1 != retval) {
     LOG(ERROR) << "Error when reading variable from input file"
                << FairLogger::endl;
   }
 }
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
FairUrqmdGenerator::ClassDef (FairUrqmdGenerator , 1) private
FairGenerator * FairGenerator::CloneGenerator () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
 {
   Fatal("CloneGenerator","Has to be overriden in multi-threading applications.");
   return 0;
 }
virtual Bool_t FairGenerator::Init () inline virtual inherited
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
 { return kTRUE;}
FairUrqmdGenerator& FairUrqmdGenerator::operator= (const FairUrqmdGenerator &) private
void FairUrqmdGenerator::ReadConversionTable () private
Input file name.
Private method ReadConversionTable. Reads the conversion table from UrQMD particle code to PDG particle code and fills the conversion map. Is called from the constructor.
Definition at line 318 of file FairUrqmdGenerator.cxx.
References FairLogger::endl(), FATAL, fParticleTable, INFO, and LOG.
Referenced by FairUrqmdGenerator().
 {
   TString work      = getenv("VMCWORKDIR");
   TString fileName  = work + "/input/urqmd_pdg.dat";
   std::ifstream* pdgconv = new std::ifstream(fileName.Data());
   if (!pdgconv->good()) {
     LOG(FATAL) << "Could not open Urqmd->PDG input file "
                << fileName << FairLogger::endl;
   }
   Int_t index = 0;
   Int_t pdgId = 0;
   while ( ! pdgconv->eof() ) {
     index =pdgId =0 ;
     *pdgconv >> index >> pdgId ;
     fParticleTable[index] = pdgId;
   }
   pdgconv->close();
   delete pdgconv;
   LOG(INFO) << "FairUrqmdGenerator: Particle table for conversion from "
             << "UrQMD loaded" <<  FairLogger::endl;
 }
Bool_t FairUrqmdGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Reads on event from the input file and pushes the tracks onto the stack. Abstract method in base class.
Parameters
pStack pointer to the stack
ver not used
Implements FairGenerator.
Definition at line 80 of file FairUrqmdGenerator.cxx.
References FairPrimaryGenerator::AddTrack(), CheckReturnValue(), FairLogger::endl(), ERROR, fInputFile, fParticleTable, FairPrimaryGenerator::GetEvent(), INFO, LOG, FairMCEventHeader::SetEventID(), and WARNING.
 {
   // ---> Check for input file
   if ( ! fInputFile ) {
     LOG(ERROR) << "FairUrqmdGenerator: Input file not open! "
                << FairLogger::endl;
     return kFALSE;
   }
   // ---> Check for primary generator
   if ( ! primGen ) {
     LOG(ERROR) << "FairUrqmdGenerator::ReadEvent: "
                << "No PrimaryGenerator!" << FairLogger::endl;
     return kFALSE;
   }
   // ---> Define event variables to be read from file
   int evnr=0, ntracks=0, aProj=0, zProj=0, aTarg=0, zTarg=0;
   float b = 0., ekin = 0.;
   int ityp=0, i3=0, ichg=0, pid=0;
   float ppx=0., ppy=0., ppz=0., m=0.;
   // ---> Read and check first event header line from input file
   char read[200];
   fgets(read, 200, fInputFile);
   if ( feof(fInputFile) ) {
     LOG(INFO) << "FairUrqmdGenerator : End of input file reached."
               << FairLogger::endl;
     fclose(fInputFile);
     fInputFile = NULL;
     return kFALSE;
   }
   if ( read[0] != 'U' ) {
     LOG(ERROR) << "FairUrqmdGenerator: Wrong event header"
                << FairLogger::endl;
     return kFALSE;
   }
   Int_t retval = 0;
   // ---> Read rest of event header
   fgets(read, 26, fInputFile);
   retval = fscanf(fInputFile, "%d", &aProj);
   CheckReturnValue(retval);
   retval = fscanf(fInputFile, "%d", &zProj);
   CheckReturnValue(retval);
   fgets(read, 25, fInputFile);
   retval = fscanf(fInputFile, "%d", &aTarg);
   CheckReturnValue(retval);
   retval = fscanf(fInputFile, "%d", &zTarg);
   CheckReturnValue(retval);
   fgets(read, 200, fInputFile);
   fgets(read, 200, fInputFile);
   fgets(read, 36, fInputFile);
   retval = fscanf(fInputFile, "%f", &b);
   CheckReturnValue(retval);
   fgets(read, 200, fInputFile);
   fgets(read, 39, fInputFile);
   retval = fscanf(fInputFile, "%e", &ekin);
   CheckReturnValue(retval);
   fgets(read, 200, fInputFile);
   fgets(read, 7, fInputFile);
   retval = fscanf(fInputFile, "%d", &evnr);
   CheckReturnValue(retval);
   fgets(read, 200, fInputFile);
   for (int iline=0; iline<8; iline++)  { fgets(read, 200,fInputFile); }
   retval = fscanf(fInputFile, "%d", &ntracks);
   CheckReturnValue(retval);
   fgets(read, 200, fInputFile);
   fgets(read, 200, fInputFile);
   // ---> Calculate beta and gamma for Lorentztransformation
   TDatabasePDG* pdgDB = TDatabasePDG::Instance();
   TParticlePDG* kProton = pdgDB->GetParticle(2212);
   Double_t kProtonMass=kProton->Mass();
   Double_t eBeam   = ekin + kProtonMass;
   Double_t pBeam   = TMath::Sqrt(eBeam*eBeam - kProtonMass*kProtonMass);
   Double_t betaCM  = pBeam / (eBeam + kProtonMass);
   Double_t gammaCM = TMath::Sqrt( 1. / ( 1. - betaCM*betaCM) );
   LOG(INFO) << "FairUrqmdGenerator: Event " << evnr << ",  b = " << b
             << " fm,  multiplicity " << ntracks  << ", ekin: "
             << ekin << FairLogger::endl;
   // Set event id and impact parameter in MCEvent if not yet done
   FairMCEventHeader* event = primGen->GetEvent();
   if ( event && (! event->IsSet()) ) {
     event->SetEventID(evnr);
     event->SetB(b);
     event->MarkSet(kTRUE);
   }
   // ---> Loop over tracks in the current event
   for(int itrack=0; itrack<ntracks; itrack++) {
     // Read momentum and PID from file
     fgets(read, 81, fInputFile);
     retval = fscanf(fInputFile, "%e", &ppx);
     CheckReturnValue(retval);
     retval = fscanf(fInputFile, "%e", &ppy);
     CheckReturnValue(retval);
     retval = fscanf(fInputFile, "%e", &ppz);
     CheckReturnValue(retval);
     retval = fscanf(fInputFile, "%e", &m);
     CheckReturnValue(retval);
     retval = fscanf(fInputFile, "%d", &ityp);
     CheckReturnValue(retval);
     retval = fscanf(fInputFile, "%d", &i3);
     CheckReturnValue(retval);
     retval = fscanf(fInputFile, "%d", &ichg);
     CheckReturnValue(retval);
     fgets(read, 200, fInputFile);
     // Convert UrQMD type and charge to unique pid identifier
     if (ityp >= 0) { pid =  1000 * (ichg+2) + ityp; }
     else { pid = -1000 * (ichg+2) + ityp; }
     // Convert Unique PID into PDG particle code
     if (fParticleTable.find(pid) == fParticleTable.end()) {
       LOG(WARNING) << "FairUrqmdGenerator: PID " << ityp << " charge "
                    << ichg << " not found in table (" << pid << ")"
                    << FairLogger::endl;
       continue;
     }
     Int_t pdgID = fParticleTable[pid];
     // Lorentztransformation to lab
     Double_t mass = Double_t(m);
     Double_t px   = Double_t(ppx);
     Double_t py   = Double_t(ppy);
     Double_t pz   = Double_t(ppz);
     Double_t e    = sqrt( mass*mass + px*px + py*py + pz*pz );
     pz = gammaCM * ( pz + betaCM * e );
     Double_t ee = sqrt( mass*mass + px*px + py*py + pz*pz );
     TVector3 aa(px,py,pz);
     TLorentzVector pp;
     pp.SetPx( px );
     pp.SetPy( py );
     pp.SetPz( pz);
     pp.SetE( ee );
     // Give track to PrimaryGenerator
     primGen->AddTrack(pdgID, px, py, pz, 0., 0., 0.);
   }
   return kTRUE;
 }
Bool_t FairUrqmdGenerator::SkipEvents (Int_t count)
Skip defined number of events in file
Definition at line 237 of file FairUrqmdGenerator.cxx.
References CheckReturnValue(), FairLogger::endl(), ERROR, fInputFile, INFO, and LOG.
 {
   if (count<=0) { return kTRUE; }
   for(Int_t ii=0; ii<count; ii++) {
     // ---> Check for input file
     if ( ! fInputFile ) {
       LOG(ERROR) << "FairUrqmdGenerator: Input file not open! "
                  << FairLogger::endl;
       return kFALSE;
     }
     // ---> Define event variables to be read from file
     int evnr=0, ntracks=0, aProj=0, zProj=0, aTarg=0, zTarg=0;
     float b = 0., ekin = 0.;
     // ---> Read and check first event header line from input file
     char read[200];
     fgets(read, 200, fInputFile);
     if ( feof(fInputFile) ) {
       LOG(INFO) << "FairUrqmdGenerator : End of input file reached."
                 << FairLogger::endl;
       fclose(fInputFile);
       fInputFile = NULL;
       return kFALSE;
     }
     if ( read[0] != 'U' ) {
       LOG(ERROR) << "FairUrqmdGenerator: Wrong event header"
                  << FairLogger::endl;
       return kFALSE;
     }
     Int_t retval = 0;
     // ---> Read rest of event header
     fgets(read, 26, fInputFile);
     retval = fscanf(fInputFile, "%d", &aProj);
     CheckReturnValue(retval);
     retval = fscanf(fInputFile, "%d", &zProj);
     CheckReturnValue(retval);
     fgets(read, 25, fInputFile);
     retval = fscanf(fInputFile, "%d", &aTarg);
     CheckReturnValue(retval);
     retval = fscanf(fInputFile, "%d", &zTarg);
     CheckReturnValue(retval);
     fgets(read, 200, fInputFile);
     fgets(read, 200, fInputFile);
     fgets(read, 36, fInputFile);
     retval = fscanf(fInputFile, "%f", &b);
     CheckReturnValue(retval);
     fgets(read, 200, fInputFile);
     fgets(read, 39, fInputFile);
     retval = fscanf(fInputFile, "%e", &ekin);
     CheckReturnValue(retval);
     fgets(read, 200, fInputFile);
     fgets(read, 7, fInputFile);
     retval = fscanf(fInputFile, "%d", &evnr);
     CheckReturnValue(retval);
     fgets(read, 200, fInputFile);
     for (int iline=0; iline<8; iline++)  { fgets(read, 200,fInputFile); }
     retval = fscanf(fInputFile, "%d", &ntracks);
     CheckReturnValue(retval);
     fgets(read, 200, fInputFile);
     fgets(read, 200, fInputFile);
     LOG(INFO) << "FairUrqmdGenerator: Event " << evnr << " skipped!"
               << FairLogger::endl;
     // ---> Loop over tracks in the current event
     for(int itrack=0; itrack<ntracks; itrack++) {
       // Read momentum and PID from file
       fgets(read, 81, fInputFile);
       fgets(read, 200, fInputFile);
     }
   }
   return kTRUE;
 }
Member Data Documentation
const Char_t* FairUrqmdGenerator::fFileName private
Map from UrQMD PID to PDGPID.
Definition at line 73 of file FairUrqmdGenerator.h.
Referenced by FairUrqmdGenerator().
FILE* FairUrqmdGenerator::fInputFile private
Definition at line 69 of file FairUrqmdGenerator.h.
Referenced by FairUrqmdGenerator(), ReadEvent(), SkipEvents(), and ~FairUrqmdGenerator().
std::map<Int_t,Int_t> FairUrqmdGenerator::fParticleTable private
Input file.
Definition at line 71 of file FairUrqmdGenerator.h.
Referenced by ReadConversionTable(), ReadEvent(), and ~FairUrqmdGenerator().
The documentation for this class was generated from the following files:
FairUrqmdGenerator.h
FairUrqmdGenerator.cxx