FairRroot: FairTestDetectorContFact Class Reference
FairTestDetectorContFact Class Reference
#include <FairTestDetectorContFact.h>
Public Member Functions
FairTestDetectorContFact ()
~FairTestDetectorContFact ()
FairParSet * createContainer (FairContainer *)
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual void activateParIo (FairParIo *)
Protected Member Functions
const char * getActualContext (const char *name)
Protected Attributes
TList * containers
FairLogger * fLogger
Private Member Functions
void setAllContainers ()
Detailed Description
Definition at line 17 of file FairTestDetectorContFact.h.
Constructor & Destructor Documentation
FairTestDetectorContFact::FairTestDetectorContFact ()
Constructor (called when the library is loaded)
Definition at line 23 of file FairTestDetectorContFact.cxx.
References FairRuntimeDb::addContFactory(), FairParSet::fName, FairParSet::fTitle, and FairRuntimeDb::instance().
     : FairContFact()
 {
     fName = "FairTestDetectorContFact";
     fTitle = "Factory for parameter containers in libFairTestDetector";
     setAllContainers();
     FairRuntimeDb::instance()->addContFactory(this);
 }
FairTestDetectorContFact::~FairTestDetectorContFact () inline
Definition at line 24 of file FairTestDetectorContFact.h.
     {
     }
Member Function Documentation
virtual void FairContFact::activateParIo (FairParIo *) inline virtual inherited
Definition at line 57 of file FairContFact.h.
Referenced by FairRuntimeDb::activateParIo().
 {}
Bool_t FairContFact::addContext (const char * name) inherited
Definition at line 159 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::setActualContext().
Referenced by FairRuntimeDb::addParamContext().
 {
   // Set the actual context in all containers, which accept this context
   FairContainer* c=0;
   Bool_t found=kFALSE;
   TIter next(containers);
   while ((c=(FairContainer*)next())) {
     if (c->setActualContext(name)) { found=kTRUE; }
   }
   return found;
 }
FairParSet * FairTestDetectorContFact::createContainer (FairContainer * c) virtual
Calls the constructor of the corresponding parameter container. For an actual context, which is not an empty string and not the default context of this container, the name is concatinated with the context.
Reimplemented from FairContFact.
Definition at line 50 of file FairTestDetectorContFact.cxx.
References FairContainer::getConcatName(), and FairContainer::getContext().
 {
     const char* name = c->GetName();
     FairParSet* p = NULL;
     if (strcmp(name, "FairTestDetectorGeoPar") == 0)
     {
         p = new FairTestDetectorGeoPar(c->getConcatName().Data(), c->GetTitle(), c->getContext());
     }
     if (strcmp(name, "FairConstPar") == 0)
     {
         p = new FairConstPar(c->getConcatName().Data(), c->GetTitle(), c->getContext());
     }
     return p;
 }
const char* FairContFact::getActualContext (const char * name) inline protected inherited
Definition at line 61 of file FairContFact.h.
{
       return ((FairContainer*)containers->FindObject(name))->getActualContext();
     }
FairParSet * FairContFact::getContainer (const char * name) inherited
Definition at line 171 of file FairContFact.cxx.
References FairRuntimeDb::addContainer(), FairContFact::containers, FairContFact::createContainer(), FairRuntimeDb::findContainer(), FairContainer::getActualContext(), FairContainer::getConcatName(), FairContainer::getDefaultContext(), FairRuntimeDb::instance(), and FairContainer::setActualContext().
Referenced by FairRuntimeDb::getContainer().
 {
   // Returns the pointer to the parameter container in the runtime database
   // If this parameter container does not yet exit, it calls the function
   // createContainer(FairContainer*), which is implemented in the derived classes
   // and calls the corresponding constructor. Then the pointer it added in the
   // runtime database.
   FairContainer* c=(FairContainer*)(containers->FindObject(name));
   FairParSet* cont=0;
   if (c) {
     TString cn=c->getConcatName();
     FairRuntimeDb* rtdb = FairRuntimeDb::instance();
     if (!(cont=rtdb->findContainer(c->getConcatName().Data()))) {
       if (strlen(c->getActualContext())==0) { c->setActualContext(c->getDefaultContext()); }
       cont=createContainer(c);
       if (cont) { rtdb->addContainer(cont); }
     }
   }
   return cont;
 }
void FairContFact::print () inherited
Definition at line 193 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::print().
Referenced by FairRuntimeDb::printParamContexts().
 {
   // Loops over all containers in the list and calls their print() function
   cout<<"---------------------------------------------------------------------------"<<"\n";
   cout<<GetName()<<":  "<<GetTitle()<<"\n";
   cout<<"---------------------------------------------------------------------------"<<"\n";
   FairContainer* c;
   TIter next(containers);
   while ((c=(FairContainer*)next())) { c->print(); }
 }
void FairTestDetectorContFact::setAllContainers () private
Creates the Container objects with all accepted contexts and adds them to the list of containers for the FairTestDetector library.
Definition at line 33 of file FairTestDetectorContFact.cxx.
References FairContainer::addContext(), and FairContFact::containers.
 {
     FairContainer* p = new FairContainer("FairTestDetectorGeoPar", "FairTestDetector Geometry Parameters", "TestDefaultContext");
     p->addContext("TestNonDefaultContext");
     FairContainer* p1 = new FairContainer("FairConstPar", "Constant Field Parameters", "TestDefaultContext");
     p1->addContext("TestNonDefaultContext");
     containers->Add(p);
     containers->Add(p1);
 }
Member Data Documentation
TList* FairContFact::containers protected inherited
Definition at line 60 of file FairContFact.h.
Referenced by FairContFact::addContext(), FairContFact::getContainer(), FairContFact::print(), FairTutorialDet2ContFact::setAllContainers(), NewDetectorContFact::setAllContainers(), setAllContainers(), FairTutorialDet4ContFact::setAllContainers(), FairTutorialDet1ContFact::setAllContainers(), FairRutherfordContFact::setAllContainers(), FairBaseContFact::setAllContainers(), and FairContFact::~FairContFact().
FairLogger* FairContFact::fLogger protected inherited
Fair Logger
Definition at line 65 of file FairContFact.h.
The documentation for this class was generated from the following files:
FairTestDetectorContFact.h
FairTestDetectorContFact.cxx