FairRroot: FairGenericParAsciiFileIo Class Reference
FairGenericParAsciiFileIo Class Reference
#include <FairGenericParAsciiFileIo.h>
Public Member Functions
FairGenericParAsciiFileIo (fstream *f=0)
~FairGenericParAsciiFileIo ()
Bool_t init (FairParSet *)
Int_t write (FairParSet *)
void setInputNumber (Int_t n)
Int_t getInputNumber ()
Protected Member Functions
Bool_t findContainer (const Text_t *name)
pointer to ascii file
Bool_t checkAllFound (Int_t *, Int_t)
void writeHeader (const Text_t *, const Text_t *context="", const Text_t *author="", const Text_t *description="")
void writeComment (FairParSet *)
void readComment (const Char_t *, FairParSet *)
Protected Attributes
TString fHeader
TString sepLine
header of container output in file
fstream * pFile
comment line
Int_t inputNumber
Private Member Functions
ClassDef (FairGenericParAsciiFileIo, 0) Bool_t readGenericSet(FairParGenericSet *pPar)
Int_t writeGenericSet (FairParGenericSet *pPar)
template<class type >
const UChar_t * readData (type, const Char_t *, TString &, Int_t &)
template<class type >
void writeData (type *, Int_t)
Detailed Description
Definition at line 22 of file FairGenericParAsciiFileIo.h.
Constructor & Destructor Documentation
FairGenericParAsciiFileIo::FairGenericParAsciiFileIo (fstream * f = 0)
FairGenericParAsciiFileIo::~FairGenericParAsciiFileIo () inline
Definition at line 26 of file FairGenericParAsciiFileIo.h.
 {}
Member Function Documentation
Bool_t FairDetParAsciiFileIo::checkAllFound (Int_t * set, Int_t setSize) protected inherited
Definition at line 63 of file FairDetParAsciiFileIo.cxx.
 {
   // checks if all modules have been initialized
   Bool_t allFound=kTRUE;
   for(Int_t i=0; i<setSize; i++) {
     if (set[i]==999) {
       set[i]=0;
       printf(" %i",i);
     }
     if (set[i]) { allFound=kFALSE; }
   }
   printf("\n");
   return allFound;
 }
FairGenericParAsciiFileIo::ClassDef (FairGenericParAsciiFileIo , 0) private
Bool_t FairDetParAsciiFileIo::findContainer (const Text_t * name) protected inherited
pointer to ascii file
Definition at line 42 of file FairDetParAsciiFileIo.cxx.
References FairDetParAsciiFileIo::pFile.
 {
   // searches the container in the file
   const Int_t maxbuf=4000;
   Text_t buf[maxbuf];
   Text_t buf2[maxbuf];
   sprintf(buf2,"%s%s%s","[",name,"]");
   //cout << " buf2 " <<  buf2 << endl;
   pFile->clear();
   pFile->seekg(0,ios::beg);
   while (!pFile->eof()) {
     pFile->getline(buf,maxbuf);
     if (buf[0]!='[') { continue; }
     //cout << " buf: " <<  buf << endl;
     if (!strncmp(buf,buf2,strlen(buf2))) { break; }
   }
   if (pFile->eof()) { return kFALSE; }
   return kTRUE;
 }
Int_t FairDetParIo::getInputNumber () inline inherited
Definition at line 29 of file FairDetParIo.h.
References FairDetParIo::inputNumber.
 {return inputNumber;}
Bool_t FairGenericParAsciiFileIo::init (FairParSet * pPar) virtual
Reimplemented from FairDetParIo.
Definition at line 44 of file FairGenericParAsciiFileIo.cxx.
References FairParSet::GetName(), and FairDetParAsciiFileIo::pFile.
{
   // initializes the parameter container from ASCII file
   if (!pFile) {
     return kFALSE;
   }
   if (pPar->InheritsFrom("FairParGenericSet")) {
     return readGenericSet((FairParGenericSet *)pPar);
   }
   Error("init(FairParSet*)", "%s does not inherit from FairParGenericSet",
         pPar->GetName());
   return kFALSE;
 }
void FairDetParAsciiFileIo::readComment (const Char_t * lastBuf, FairParSet * pPar) protected inherited
Definition at line 100 of file FairDetParAsciiFileIo.cxx.
References FairDetParAsciiFileIo::pFile, FairParSet::setAuthor(), and FairParSet::setDescription().
 {
   // reads the author or the description
   const Int_t maxbuf=4000;
   Text_t buf[maxbuf];
   TString s=lastBuf;
   TString pName, pVal;
   Ssiz_t n=s.First(':');
   Ssiz_t m=s.Last('\\');
   pName=s(0,n);
   if (m>0) { pVal=s(n+1,m-n-1); }
   else { pVal=s(n+1,s.Length()-n-1); }
   pVal=pVal.Strip(pVal.kLeading);
   while (m>0) {
     pVal+="\n";
     pFile->getline(buf,maxbuf);
     if (buf[0]!='/') {
       s=buf;
       m=s.Last('\\');
       if (m>0) { pVal+=s(0,m); }
       else { pVal+=s; }
     }
   }
   if (pName.CompareTo("author")==0) { pPar->setAuthor(pVal.Data()); }
   else if ( pName.CompareTo("description")==0) { pPar->setDescription(pVal.Data()); }
 }
template<class type > const UChar_t * FairGenericParAsciiFileIo::readData (type t, const Char_t * format, TString & line, Int_t & length) private
Definition at line 73 of file FairGenericParAsciiFileIo.cxx.
References FairDetParAsciiFileIo::pFile.
{
   // reads c-type single data and arrays
   const Int_t st = sizeof(t);
   const Int_t maxbuf = 8000;
   const Int_t bufSizeExt = 10000 * st;
   const Char_t d[] = " ";
   Text_t buf[maxbuf];
   TString s;
   Int_t l = 0, bufSize = bufSizeExt;
   UChar_t *val = new UChar_t[bufSize];
   Ssiz_t m = line.Last('\\');
   if (m < 0) {
     sscanf(line.Data(), format, &t);
     memcpy(&val[l], &t, st);
     length = st;
   } else {
     do {
       pFile->getline(buf, maxbuf);
       if (buf[0] != '/' && buf[0] != '#') {
         s = buf;
         m = s.Last('\\');
         if (m > 0) {
           s = s(0, s.Length() - 2);
         }
         if ((bufSize - 1000) < l) {
           bufSize += bufSizeExt;
           UChar_t *va = new UChar_t[bufSize];
           memcpy(va, val, l);
           delete[] val;
           val = va;
         }
         Char_t *ss = strtok((Char_t *)s.Data(), d);
         while (ss != 0) {
           sscanf(ss, format, &t);
           memcpy(&val[l], &t, st);
           l += st;
           ss = strtok(NULL, d);
         }
       }
     } while (buf[0] != '#' && !pFile->eof() && m > 0);
     length = l;
   }
   return val;
 }
void FairDetParIo::setInputNumber (Int_t n) inline inherited
Definition at line 26 of file FairDetParIo.h.
Referenced by FairParIo::setInputNumber().
 {inputNumber=n;}
Int_t FairGenericParAsciiFileIo::write (FairParSet * pPar) virtual
Reimplemented from FairDetParIo.
Definition at line 59 of file FairGenericParAsciiFileIo.cxx.
References FairParSet::GetName(), FairDetParAsciiFileIo::pFile, and writeGenericSet().
{
   // writes the parameter container to ASCII file
   if (!pFile) {
     return -1;
   }
   if (pPar->InheritsFrom("FairParGenericSet")) {
     return writeGenericSet((FairParGenericSet *)pPar);
   }
   Error("write(FairParSet*)", "%s does not inherit from FairParGenericSet",
         pPar->GetName());
   return -1;
 }
void FairDetParAsciiFileIo::writeComment (FairParSet * pPar) protected inherited
Definition at line 127 of file FairDetParAsciiFileIo.cxx.
References FairParSet::getAuthor(), FairParSet::getDescription(), and FairDetParAsciiFileIo::pFile.
Referenced by writeGenericSet().
 {
   TString t=pPar->getAuthor();
   if (!t.IsNull()) { *pFile<<"author:      "<<t<<"\n"; }
   t=pPar->getDescription();
   if (!t.IsNull()) {
     t=t.ReplaceAll("\n"," \\\n");
     *pFile<<"description: "<<t<<"\n";
   }
 }
template<class type > void FairGenericParAsciiFileIo::writeData (type * val, Int_t nParams) private
Definition at line 121 of file FairGenericParAsciiFileIo.cxx.
References FairDetParAsciiFileIo::pFile.
Referenced by writeGenericSet().
{
   // writes c-type arrays
   Int_t i = 0, k = 0;
   while (k < nParams) {
     if (i == 10) {
       *pFile << " \\\n  ";
       i = 0;
     }
     *pFile << val[k] << " ";
     i++;
     k++;
   }
   *pFile << std::endl;
 }
Int_t FairGenericParAsciiFileIo::writeGenericSet (FairParGenericSet * pPar) private
Definition at line 274 of file FairGenericParAsciiFileIo.cxx.
References FairParamObj::getLength(), FairParamList::getList(), FairParSet::GetName(), FairParamObj::getNumParams(), FairParSet::getParamContext(), FairParamObj::getParamType(), FairParamObj::getParamValue(), FairParamObj::isBasicType(), FairDetParAsciiFileIo::pFile, FairParGenericSet::putParams(), FairDetParAsciiFileIo::sepLine, FairParSet::setChanged(), FairDetParAsciiFileIo::writeComment(), and writeData().
Referenced by write().
{
   // writes condition-stype parameter containers to ASCII file
   if (pFile) {
     //   Int_t version=1;
     const Text_t *name = pPar->GetName();
     const Text_t *context = pPar->getParamContext();
     *pFile << sepLine;
     *pFile << "# Class:   " << name << "\n# Context: " << context << "\n";
     *pFile << sepLine;
     *pFile << "[" << name << "]\n";
     writeComment(pPar);
     *pFile << "//-----------------------------------------------------------"
               "-----------------\n";
     FairParamList *paramList = new FairParamList;
     pPar->putParams(paramList);
     TList *pList = paramList->getList();
     TIter next(pList);
     FairParamObj *po;
     while ((po = (FairParamObj *)next())) {
       const Char_t *pType = po->getParamType();
       UChar_t *pValue = po->getParamValue();
       if (po->isBasicType() && strcmp(pType, "UChar_t") != 0) {
         if (strcmp(pType, "Text_t") == 0) {
           TString val((Char_t *)pValue, po->getLength());
           val.ReplaceAll("\n", " \\\n");
           *pFile << po->GetName() << ":  " << pType << " \\\n  " << val.Data()
                  << std::endl;
         } else {
           Int_t nParams = po->getNumParams();
           if (nParams == 1) {
             *pFile << po->GetName() << ":  " << pType << "  ";
           } else {
             *pFile << po->GetName() << ":  " << pType << " \\\n  ";
           }
           if (strcmp(pType, "Char_t") == 0) {
             writeData((Char_t *)pValue, nParams);
           } else if (strcmp(pType, "Int_t") == 0) {
             writeData((Int_t *)pValue, nParams);
           } else if (strcmp(pType, "Float_t") == 0) {
             writeData((Float_t *)pValue, nParams);
           } else if (strcmp(pType, "Double_t") == 0) {
             writeData((Double_t *)pValue, nParams);
           }
         }
       } else {
         Error("writeCond(FairParGenericSet*)",
               "Type %s of parameter %s not supported by ASCII I/O", pType,
               po->GetName());
         //       version=-1;
       }
     }
     *pFile << sepLine;
     delete paramList;
     pPar->setChanged(kFALSE);
     return 1;
   }
   Error("writeCond(FairParGenericSet*)", "Output is not writable");
   return -1;
 }
void FairDetParAsciiFileIo::writeHeader (const Text_t * name, const Text_t * context = "", const Text_t * author = "", const Text_t * description = "") protected inherited
Definition at line 79 of file FairDetParAsciiFileIo.cxx.
References FairDetParAsciiFileIo::fHeader, FairDetParAsciiFileIo::pFile, and FairDetParAsciiFileIo::sepLine.
 {
   // calls the function putAsciiHeader(...) of the parameter container
   // class and writes the header to the file
   pFile->write(sepLine,strlen(sepLine));
   pFile->write(fHeader.Data(),fHeader.Length());
   pFile->write(sepLine,strlen(sepLine));
   *pFile<<"["<<name<<"]\n";
   if (strlen(context)>0) { *pFile<<"// Parameter Context: "<<context<<"\n"; }
   if (strlen(author)>0) { *pFile<<"author:      "<<author<<"\n"; }
   TString t=description;
   if (!t.IsNull()) {
     t=t.ReplaceAll("\n"," \\\n");
     *pFile<<"description: "<<t<<"\n";
   }
   *pFile<<"//-----------------------------------------------------------"
         "-----------------\n";
 }
Member Data Documentation
TString FairDetParAsciiFileIo::fHeader protected inherited
Definition at line 24 of file FairDetParAsciiFileIo.h.
Referenced by FairDetParAsciiFileIo::writeHeader().
Int_t FairDetParIo::inputNumber protected inherited
Definition at line 20 of file FairDetParIo.h.
Referenced by FairDetParRootFileIo::findInputVersion(), FairDetParIo::getInputNumber(), and FairDetParRootFileIo::read().
fstream* FairDetParAsciiFileIo::pFile protected inherited
comment line
Definition at line 26 of file FairDetParAsciiFileIo.h.
Referenced by FairDetParAsciiFileIo::findContainer(), init(), FairDetParAsciiFileIo::readComment(), readData(), write(), FairDetParAsciiFileIo::writeComment(), writeData(), writeGenericSet(), and FairDetParAsciiFileIo::writeHeader().
TString FairDetParAsciiFileIo::sepLine protected inherited
header of container output in file
Definition at line 25 of file FairDetParAsciiFileIo.h.
Referenced by writeGenericSet(), and FairDetParAsciiFileIo::writeHeader().
The documentation for this class was generated from the following files:
FairGenericParAsciiFileIo.h
FairGenericParAsciiFileIo.cxx