FairRroot: FairEventBuilderManager Class Reference
FairEventBuilderManager Class Reference abstract
#include <FairEventBuilderManager.h>
Public Member Functions
FairEventBuilderManager ()
FairEventBuilderManager (const char *name, Int_t iVerbose=1)
virtual ~FairEventBuilderManager ()
virtual void Exec (Option_t *opt)
virtual void AddEventBuilder (FairEventBuilder *eventBuilder)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual Double_t FillEventVectors ()
virtual void AnalyzeAndExtractEvents (Double_t maxEventTimeAllowed)=0
virtual void CreateAndFillEvent (FairRecoEventHeader *recoEvent)
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
std::vector< FairEventBuilder * > fEventBuilders
std::vector< std::vector
< std::pair< double,
FairRecoEventHeader * > > > fPossibleEvents
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void Finish ()
ClassDef (FairEventBuilderManager, 1)
Detailed Description
Definition at line 47 of file FairEventBuilderManager.h.
Constructor & Destructor Documentation
FairEventBuilderManager::FairEventBuilderManager ()
Default constructor
Definition at line 61 of file FairEventBuilderManager.cxx.
   : FairTask("FairEventBuilderManager", 0),
     fEventBuilders  (),
     fPossibleEvents()
 {
 }
FairEventBuilderManager::FairEventBuilderManager (const char * name, Int_t iVerbose = 1)
Constructor with task name
Definition at line 70 of file FairEventBuilderManager.cxx.
   : FairTask(name, iVerbose),
     fEventBuilders  (),
     fPossibleEvents()
 {
 }
FairEventBuilderManager::~FairEventBuilderManager () virtual
Destructor
Definition at line 81 of file FairEventBuilderManager.cxx.
 {
 }
Member Function Documentation
void FairEventBuilderManager::AddEventBuilder (FairEventBuilder * eventBuilder) virtual
Adding FairEventBuilder
Definition at line 161 of file FairEventBuilderManager.cxx.
References fEventBuilders, and fPossibleEvents.
 {
   fEventBuilders  .push_back(eventBuilder);
   std::vector<std::pair<double,FairRecoEventHeader*> > tcArray;
   fPossibleEvents.push_back(tcArray);
   //  if ( fVerbose )
   cout << "*** FairEventBuilderManager. Registered " << eventBuilder->GetName() << endl;
 }
virtual void FairEventBuilderManager::AnalyzeAndExtractEvents (Double_t maxEventTimeAllowed) protected pure virtual
Analyze and extract events - experiment specific
Referenced by Exec(), and Finish().
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairEventBuilderManager::ClassDef (FairEventBuilderManager , 1) private
void FairEventBuilderManager::CreateAndFillEvent (FairRecoEventHeader * recoEvent) protected virtual
Create output tree structure
Definition at line 143 of file FairEventBuilderManager.cxx.
References fEventBuilders, FairRootManager::Fill(), and FairRootManager::Instance().
 {
   for ( Int_t ieb = 0 ; ieb < fEventBuilders.size() ; ieb++ ) {
     fEventBuilders[ieb]->StoreEventData(recoEvent);
     fEventBuilders[ieb]->WriteOutAllDeadTimeData();
   }
   FairRootManager::Instance()->Fill();
   for ( Int_t ieb = 0 ; ieb < fEventBuilders.size() ; ieb++ ) {
     fEventBuilders[ieb]->DeleteOldData();
   }
 }
void FairEventBuilderManager::Exec (Option_t * opt) virtual
Execution
Definition at line 87 of file FairEventBuilderManager.cxx.
References AnalyzeAndExtractEvents(), FillEventVectors(), and FairTask::fVerbose.
 {
   if ( fVerbose ) {
     cout << "FairEventBuilderManager::Exec() begin" << endl;
   }
   Double_t maxEventTimeAllowed = FillEventVectors();
   if ( fVerbose ) {
     cout << "++ CAN CREATE EVENTS THAT ARE SMALLER THAN " << maxEventTimeAllowed << " ns" << endl;
   }
   // AnalyzeAndExtractEvents function:
   // - works on fEventBuilders[ieb]
   // - should extract possible events
   // - is implemented by different experiments
   AnalyzeAndExtractEvents(maxEventTimeAllowed);
   return;
 }
Double_t FairEventBuilderManager::FillEventVectors () protected virtual
Fill events from various builders
Definition at line 110 of file FairEventBuilderManager.cxx.
References fEventBuilders, fPossibleEvents, and FairTask::fVerbose.
Referenced by Exec().
 {
   // for ( std::vector<FairEventBuilder*>::iterator it = fEventBuilders.begin() ; it != fEventBuilders.end() ; ++it ) {
   //   *it.FindEvents();
   // }
   Double_t maxEventTimeAllowed = 10.e6;
   for ( Int_t ieb = 0 ; ieb < fEventBuilders.size() ; ieb++ ) {
     if ( fVerbose ) { cout << "***** " << fEventBuilders[ieb]->GetName() << " *****" << endl; }
     if ( fVerbose ) { cout << "  there are " << fPossibleEvents[ieb].size() << " possible events" << endl; }
     std::vector<std::pair<double,FairRecoEventHeader*> > tempBuilder = fEventBuilders[ieb]->FindEvents();
     if ( fVerbose ) {
       cout << "  event buffer " << fEventBuilders[ieb]->GetName() << " found " << tempBuilder.size() << " events" << endl;
     }
     std::pair<double,FairRecoEventHeader*> tempPair;
     for ( Int_t ipair = 0 ; ipair < tempBuilder.size() ; ipair++ ) {
       fPossibleEvents[ieb].push_back(tempBuilder[ipair]);
       if ( fVerbose )
         cout << "    added event " << fPossibleEvents[ieb][fPossibleEvents[ieb].size()-1].second
              << " at " << fPossibleEvents[ieb][fPossibleEvents[ieb].size()-1].second->GetEventTime() << " ns." << endl;
     }
     if ( fVerbose ) {
       cout << "  and now " << fPossibleEvents[ieb].size() << " possible events" << endl;
     }
     if ( fEventBuilders[ieb]->AllowedTime() < maxEventTimeAllowed ) {
       maxEventTimeAllowed = fEventBuilders[ieb]->AllowedTime();
     }
   }
   return maxEventTimeAllowed;
 }
void FairEventBuilderManager::Finish () private virtual
Finish at the end of each event
Reimplemented from FairTask.
Definition at line 213 of file FairEventBuilderManager.cxx.
References AnalyzeAndExtractEvents(), and fEventBuilders.
 {
   AnalyzeAndExtractEvents(-1.);
   cout << "==================== " << fName.Data() << " : Summary ========================" << endl;
   for ( Int_t ieb = 0 ; ieb < fEventBuilders.size() ; ieb++ ) {
     fEventBuilders[ieb]->Finish();
   }
   cout << "=====================================================================" << endl;
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
InitStatus FairEventBuilderManager::Init () private virtual
Intialisation
Reimplemented from FairTask.
Definition at line 187 of file FairEventBuilderManager.cxx.
References fEventBuilders, FairRootManager::Instance(), and kSUCCESS.
 {
   // Get input array
   FairRootManager* ioman = FairRootManager::Instance();
   if ( ! ioman ) { Fatal("Init", "No FairRootManager"); }
   cout << "*** FairEventBuilderManager. " << fEventBuilders.size() << " event builders registered." << endl;
   for ( Int_t ieb = 0 ; ieb < fEventBuilders.size() ; ieb++ ) {
     fEventBuilders[ieb]->SetIdentifier(TMath::Power(2,ieb));
     fEventBuilders[ieb]->Init();
   }
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
InitStatus FairEventBuilderManager::ReInit () private virtual
Reinitialisation
Reimplemented from FairTask.
Definition at line 205 of file FairEventBuilderManager.cxx.
References kSUCCESS.
 {
   return kSUCCESS;
 }
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairEventBuilderManager::SetParContainers () private virtual
Get parameter containers
Reimplemented from FairTask.
Definition at line 172 of file FairEventBuilderManager.cxx.
References FairRun::GetRuntimeDb(), and FairRunAna::Instance().
 {
   // Get run and runtime database
   FairRunAna* run = FairRunAna::Instance();
   if ( ! run ) {
     Fatal("SetParContainers", "No analysis run");
   } else {
     FairRuntimeDb* db = run->GetRuntimeDb();
     if ( ! db ) { Fatal("SetParContainers", "No runtime database"); }
   }
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
std::vector<FairEventBuilder*> FairEventBuilderManager::fEventBuilders protected
Definition at line 74 of file FairEventBuilderManager.h.
Referenced by AddEventBuilder(), CreateAndFillEvent(), FillEventVectors(), Finish(), and Init().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
std::vector<std::vector<std::pair<double,FairRecoEventHeader*> > > FairEventBuilderManager::fPossibleEvents protected
Definition at line 75 of file FairEventBuilderManager.h.
Referenced by AddEventBuilder(), and FillEventVectors().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairEventBuilderManager.h
FairEventBuilderManager.cxx