FairRroot: FairDoubleHit Class Reference
FairDoubleHit Class Reference abstract
#include <FairDoubleHit.h>
Public Member Functions
FairDoubleHit ()
virtual ~FairDoubleHit ()
virtual void Print (const Option_t *opt=0) const =0
virtual void SetDetectorID (Int_t chamb)=0
virtual void SetPos_in (TVector3 xyz)=0
virtual void SetDPos_in (TVector3 xyz)=0
virtual void SetPos_out (TVector3 xyz)=0
virtual void SetDPos_out (TVector3 xyz)=0
virtual void SetRefIndex (Int_t index)=0
virtual Int_t GetDetectorID ()=0
virtual Int_t GetRefIndex ()=0
virtual TVector3 GetPos_in ()=0
virtual TVector3 GetDPos_in ()=0
virtual TVector3 GetPos_out ()=0
virtual TVector3 GetDPos_out ()=0
virtual Double_t x_in ()=0
virtual Double_t y_in ()=0
virtual Double_t z_in ()=0
virtual Double_t dx_in ()=0
virtual Double_t dy_in ()=0
virtual Double_t dz_in ()=0
virtual Double_t x_out ()=0
virtual Double_t y_out ()=0
virtual Double_t z_out ()=0
virtual Double_t dx_out ()=0
virtual Double_t dy_out ()=0
virtual Double_t dz_out ()=0
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual FairLink GetEntryNr () const
gives back the entryNr
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetInsertHistory (Bool_t val)
Toggles if history of a link is inserted or not.
virtual void SetEntryNr (FairLink entry)
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void InsertHistory (FairLink link)
Adds the FairLinks of the inserted link to the set of links of this object.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
std::ostream & Print (std::ostream &out=std::cout) const
Output.
Protected Member Functions
virtual void SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t bypass, Float_t mult)
ClassDef (FairMultiLinkedData, 4)
Protected Attributes
Int_t fRefIndex
Int_t fDetectorID
TVector3 fPosition_in
TVector3 fPositionError_in
TVector3 fPosition_out
TVector3 fPositionError_out
std::set< FairLink > fLinks
FairLink fEntryNr
Bool_t fPersistanceCheck
Bool_t fInsertHistory
Int_t fVerbose
Int_t fDefaultType
Detailed Description
Definition at line 17 of file FairDoubleHit.h.
Constructor & Destructor Documentation
FairDoubleHit::FairDoubleHit ()
Definition at line 12 of file FairDoubleHit.cxx.
                             :
   fRefIndex(-1),
   fDetectorID(-1),
   fPosition_in(),
   fPositionError_in(),
   fPosition_out(),
   fPositionError_out()
 {
 }
FairDoubleHit::~FairDoubleHit () virtual
Definition at line 23 of file FairDoubleHit.cxx.
 {
 }
Member Function Documentation
void FairMultiLinkedData::AddAllWeights (Double_t weight) virtual inherited
Adds weight to all Links.
Definition at line 299 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::fLinks, FairLink::GetWeight(), and FairLink::SetWeight().
Referenced by FairMCDataCrawler::GetNextStage(), and FairMCMatch::GetNextStage().
 {
   std::set<FairLink> tempLinks;
   for (std::set<FairLink>::iterator it = fLinks.begin(); it != fLinks.end(); it++) {
     FairLink tempLink = *it;
     tempLink.SetWeight(weight + tempLink.GetWeight());
     tempLinks.insert(tempLink);
   }
   fLinks = tempLinks;
 }
void FairMultiLinkedData::AddLink (FairLink link, Bool_t bypass = kFALSE, Float_t mult = 1.0) virtual inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
Definition at line 112 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::AddLinks(), FairRootManager::CheckBranch(), FairMultiLinkedData::fInsertHistory, FairMultiLinkedData::fPersistanceCheck, FairMultiLinkedData::fVerbose, FairRootManager::GetBranchId(), FairRootManager::GetBranchName(), FairLink::GetIndex(), FairMultiLinkedData::GetNLinks(), FairRootManager::GetObject(), FairLink::GetType(), FairLink::GetWeight(), FairMultiLinkedData::InsertHistory(), FairMultiLinkedData::InsertLink(), FairRootManager::Instance(), and FairLink::SetWeight().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData::AddLinks(), FairMCDataCrawler::AddToFinalStage(), FairMCMatch::AddToFinalStage(), FairMCMatch::FindStagesPointingToLinks(), FairMCMatch::GetMCInfoForwardSingle(), FairMCObject::PosInList(), FairMCObject::SetEntry(), and FairMultiLinkedData::SetLink().
 {
   Float_t weight = link.GetWeight() * mult;
   link.SetWeight(weight);
   //std::cout << fVerbose << std::endl;
   FairRootManager* ioman = FairRootManager::Instance();
   if (ioman == 0) {
     std::cout << "-W- no IOManager present!" << std::endl;
     fPersistanceCheck = kFALSE;
   }
   if (fVerbose > 1) {
     std::cout << "Add FairLink: " << link << std::endl;
   }
   if (fPersistanceCheck == kFALSE ||
       link.GetIndex() < 0 ||
       ioman->CheckBranch(ioman->GetBranchName(link.GetType())) == 0) {
     InsertLink(link);
     if (fInsertHistory == kTRUE)
         InsertHistory(link);
     return;
   }
   if (bypass == kFALSE) {
     if (fVerbose > 1) {
       std::cout << "BranchName " << ioman->GetBranchName(link.GetType()) << " checkStatus: " <<  ioman->CheckBranch(ioman->GetBranchName(link.GetType())) << std::endl;
     }
     if (link.GetType() > ioman->GetBranchId("MCTrack") && ioman->CheckBranch(ioman->GetBranchName(link.GetType())) != 1) {
       if (fVerbose > 1) {
         std::cout << "BYPASS!" << std::endl;
       }
 //      bypass = kTRUE;
     }
   }
   if (bypass == kTRUE) {
     //FairRootManager* ioman = FairRootManager::Instance();
     if (link.GetType() > ioman->GetBranchId("MCTrack")) {
       TClonesArray* array = (TClonesArray*)ioman->GetObject(ioman->GetBranchName(link.GetType()));
       if (fVerbose > 1) {
         std::cout << "Entries in " << ioman->GetBranchName(link.GetType()) << " Array: " << array->GetEntries() << std::endl;
       }
       FairMultiLinkedData* links = (FairMultiLinkedData*)array->At(link.GetIndex());
       if (fVerbose > 1) {
         std::cout << "FairMultiLinkedData has " << links->GetNLinks() << " Entries: " << std::endl;
         std::cout << *links << std::endl;
       }
       AddLinks(*links, mult);
       return;
     } else {
       InsertLink(link);
       if (fInsertHistory == kTRUE)
           InsertHistory(link);
     }
   } else {
     InsertLink(link);
     if (fInsertHistory == kTRUE)
         InsertHistory(link);
   }
 }
void FairMultiLinkedData::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual inherited
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
Definition at line 102 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData::GetLinks(), FairLink::GetWeight(), and FairLink::SetWeight().
Referenced by FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMCMatch::FindLinksToStage(), FairMCMatch::FindStagesPointingToLink(), FairMCObject::GetLinksWithType(), and FairMultiLinkedData::SetLinks().
 {
   std::set<FairLink> myLinks = links.GetLinks();
   for (std::set<FairLink>::iterator it = myLinks.begin(); it != myLinks.end(); it++) {
     FairLink myLink = *it;
     myLink.SetWeight(myLink.GetWeight()*mult);
     AddLink(myLink);
   }
 }
FairMultiLinkedData::ClassDef (FairMultiLinkedData , 4) protected inherited
virtual void FairMultiLinkedData::DeleteLink (FairLink link) inline virtual inherited
Deletes a link ouf of fLinks.
Definition at line 75 of file FairMultiLinkedData.h.
References FairMultiLinkedData::DeleteLink(), FairLink::GetIndex(), and FairLink::GetType().
Referenced by FairMultiLinkedData::DeleteLink().
void FairMultiLinkedData::DeleteLink (Int_t type, Int_t index) virtual inherited
Deletes a link ouf of fLinks.
Definition at line 251 of file FairMultiLinkedData.cxx.
 {
   /*  Int_t pos = LinkPosInList(type, index);
     if (pos < 0) return;
     else{
       fLinks.erase(fLinks.begin()+pos);
     }*/
 }
virtual Double_t FairDoubleHit::dx_in () pure virtual
virtual Double_t FairDoubleHit::dx_out () pure virtual
virtual Double_t FairDoubleHit::dy_in () pure virtual
virtual Double_t FairDoubleHit::dy_out () pure virtual
virtual Double_t FairDoubleHit::dz_in () pure virtual
virtual Double_t FairDoubleHit::dz_out () pure virtual
TObject * FairMultiLinkedData::GetData (FairLink & myLink) inherited
Get the TObject the Link is pointing to.
Definition at line 272 of file FairMultiLinkedData.cxx.
References FairRootManager::CheckBranch(), FairRootManager::GetBranchName(), FairLink::GetIndex(), FairRootManager::GetObject(), FairLink::GetType(), and FairRootManager::Instance().
 {
   FairRootManager* ioman = FairRootManager::Instance();
   TString branchName = ioman->GetBranchName(myLink.GetType());
   if (ioman->CheckBranch(branchName) > 0) {
     TClonesArray* myArray = (TClonesArray*)ioman->GetObject(branchName);
     if (myArray != 0) {
       if (myArray->GetEntries() > myLink.GetIndex()) {
         return myArray->At(myLink.GetIndex());
       } else { std::cout << "-E- FairMultiLinkedData::GetData index out of bounds" << std::endl; }
     } else { std::cout << "-E- FairMultiLinkedData::GetData no TClonesArray" << std::endl; }
   } else { std::cout << "-E- FairMultiLinkedData::GetData Branch does not exist in Memory" << std::endl; }
   return 0;
 }
virtual Int_t FairMultiLinkedData::GetDefaultType () inline virtual inherited
Definition at line 46 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fDefaultType.
 { return fDefaultType;}
virtual Int_t FairDoubleHit::GetDetectorID () pure virtual
virtual TVector3 FairDoubleHit::GetDPos_in () pure virtual
virtual TVector3 FairDoubleHit::GetDPos_out () pure virtual
virtual FairLink FairMultiLinkedData::GetEntryNr () const inline virtual inherited
gives back the entryNr
Definition at line 41 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fEntryNr.
Referenced by FairMultiLinkedData_Interface::GetEntryNr(), and FairMultiLinkedData::Print().
FairLink FairMultiLinkedData::GetLink (Int_t pos) const virtual inherited
returns the FairLink at the given position
Definition at line 74 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::fLinks.
Referenced by FairMCMatch::CreateArtificialStage(), FairMCMatch::FindStagesPointingToLinks(), FairMultiLinkedData_Interface::GetLink(), FairMCDataCrawler::GetNextStage(), FairMCMatch::GetNextStage(), and FairMultiLinkedData::Print().
 {
   if (pos < (Int_t)fLinks.size()) {
     std::set<FairLink>::iterator it = fLinks.begin();
     for (int i = 0; i < pos; i++) { it++; }
     return *it;
   } else {
     std::cout << "-E- FairMultiLinkedData:GetLink(pos) pos " << pos << " outside range " << fLinks.size() << std::endl;
     return FairLink();
   }
 }
virtual std::set<FairLink> FairMultiLinkedData::GetLinks () const inline virtual inherited
returns stored links as FairLinks
Definition at line 40 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fLinks.
Referenced by FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData::InsertHistory(), and FairMCObject::SetEntry().
FairMultiLinkedData FairMultiLinkedData::GetLinksWithType (Int_t type) const virtual inherited
Gives you a list of links which contain the given type.
Definition at line 260 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::fLinks, and FairMultiLinkedData::InsertLink().
Referenced by FairMultiLinkedData_Interface::GetLinksWithType().
 {
   FairMultiLinkedData result;
   for (std::set<FairLink>::iterator it = fLinks.begin(); it != fLinks.end(); it++) {
     if (it->GetType() == type) {
       FairLink myLink = *it;
       result.InsertLink(myLink);
     }
   }
   return result;
 }
virtual Int_t FairMultiLinkedData::GetNLinks () const inline virtual inherited
returns the number of stored links
Definition at line 42 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fLinks.
Referenced by FairMultiLinkedData::AddLink(), FairMCMatch::CreateArtificialStage(), FairMCMatch::FindStagesPointingToLinks(), FairMCDataCrawler::GetNextStage(), FairMCMatch::GetNextStage(), FairMultiLinkedData_Interface::GetNLinks(), and FairMultiLinkedData::Print().
Bool_t FairMultiLinkedData::GetPersistanceCheck () inline inherited
Returns the value of PersistanceCheck.
Definition at line 47 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fPersistanceCheck.
virtual TVector3 FairDoubleHit::GetPos_in () pure virtual
virtual TVector3 FairDoubleHit::GetPos_out () pure virtual
virtual Int_t FairDoubleHit::GetRefIndex () pure virtual
Int_t FairMultiLinkedData::GetVerbose () inline inherited
Returns the verbosity level.
Definition at line 48 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fVerbose.
void FairMultiLinkedData::InsertHistory (FairLink link) virtual inherited
Adds the FairLinks of the inserted link to the set of links of this object.
Definition at line 195 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::fVerbose, FairRootManager::GetBranchId(), FairRootManager::GetBranchName(), FairLink::GetEntry(), FairRootManager::GetEntryNr(), FairLink::GetIndex(), FairMultiLinkedData::GetLinks(), FairRootManager::GetObject(), FairLink::GetType(), FairMultiLinkedData::InsertLink(), and FairRootManager::Instance().
Referenced by FairMultiLinkedData::AddLink().
 {
         FairRootManager* ioman = FairRootManager::Instance();
         FairMultiLinkedData* pointerToLinks = 0;
         if (fVerbose > 1)
                 std::cout << "FairMultiLinkedData::InsertHistory for Link " << link << " Type: " << ioman->GetBranchName(link.GetType()) << std::endl;
         if (link.GetType() < 0)
                 return;
         if (link.GetType() == ioman->GetBranchId("MCTrack"))
                 return;
         if(ioman->GetBranchName(link.GetType()).Contains("."))
                 return;
         if(link.GetEntry() != -1 && link.GetEntry() != ioman->GetEntryNr())
                 return;
         if (link.GetIndex() < 0) { //if index is -1 then this is not a TClonesArray so only the Object is returned
                 FairMultiLinkedData_Interface* interface = (FairMultiLinkedData_Interface*) ioman->GetObject(ioman->GetBranchName(link.GetType()));
                 pointerToLinks = interface->GetPointerToLinks();
         } else {
                 TClonesArray* dataArray = (TClonesArray*) ioman->GetObject(ioman->GetBranchName(link.GetType()));
                 if (link.GetIndex() < dataArray->GetEntriesFast()) {
                         FairMultiLinkedData_Interface* interface = (FairMultiLinkedData_Interface*) dataArray->At(link.GetIndex());
                         pointerToLinks = interface->GetPointerToLinks();
                 }
         }
         if (pointerToLinks != 0){
                 std::set<FairLink> linkSet = pointerToLinks->GetLinks();
                 for (std::set<FairLink>::const_iterator iter = linkSet.begin(); iter!= linkSet.end(); iter++){
                         if (fVerbose > 1)
                                 std::cout << "FairMultiLinkedData::InsertHistory inserting " << *iter << std::endl;
                     InsertLink(*iter);
                 }
         }
 }
void FairMultiLinkedData::InsertLink (FairLink link) virtual inherited
Inserts a link into the list of links without persistance checking.
Definition at line 177 of file FairMultiLinkedData.cxx.
References FairLink::AddWeight(), FairMultiLinkedData::fLinks, FairLink::GetType(), FairLink::GetWeight(), and FairLinkManager::Instance().
Referenced by FairMultiLinkedData::AddLink(), FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData::InsertHistory().
 {
   if (FairLinkManager::Instance()->IsIgnoreType(link.GetType())){
         return;
   }
   std::set<FairLink>::iterator it = fLinks.find(link);
   if (it != fLinks.end()) {
     FairLink myTempLink = *it;
     myTempLink.AddWeight(link.GetWeight());
     fLinks.erase(it);
     fLinks.insert(myTempLink);
   } else {
     fLinks.insert(link);
   }
   return;
 }
virtual Bool_t FairMultiLinkedData::IsLinkInList (FairLink link) inline virtual inherited
Test if a given link is in fLinks.
Definition at line 70 of file FairMultiLinkedData.h.
References FairLink::GetIndex(), FairLink::GetType(), and FairMultiLinkedData::IsLinkInList().
Referenced by FairMultiLinkedData::IsLinkInList().
Bool_t FairMultiLinkedData::IsLinkInList (Int_t type, Int_t index) virtual inherited
Same as IsLinkInList(FairLink) just with type and index given separately.
Definition at line 234 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::LinkPosInList().
 {
   if (LinkPosInList(type, index) > -1) {
     return kTRUE;
   }
   return kFALSE;
 }
virtual Int_t FairMultiLinkedData::LinkPosInList (FairLink link) inline virtual inherited
returns position of link in fLinks. If it is not in the list -1 is returned
Definition at line 72 of file FairMultiLinkedData.h.
References FairLink::GetIndex(), FairLink::GetType(), and FairMultiLinkedData::LinkPosInList().
Referenced by FairMultiLinkedData::IsLinkInList(), and FairMultiLinkedData::LinkPosInList().
Int_t FairMultiLinkedData::LinkPosInList (Int_t type, Int_t index) virtual inherited
Same as LinkPosInList(FairLink)
Definition at line 242 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::fLinks.
 {
   std::set<FairLink>::iterator it = std::find(fLinks.begin(), fLinks.end(), FairLink(type, index));
   if (it != fLinks.end()) {
     return std::distance(fLinks.begin(), it);
   }
   return -1;
 }
void FairMultiLinkedData::MultiplyAllWeights (Double_t weight) virtual inherited
Multiplies all Links with weight.
Definition at line 310 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::fLinks, FairLink::GetWeight(), and FairLink::SetWeight().
Referenced by FairMCMatch::GetMCInfoBackwardSingle(), FairMCDataCrawler::GetNextStage(), and FairMCMatch::GetNextStage().
 {
   std::set<FairLink> tempLinks;
   for (std::set<FairLink>::iterator it = fLinks.begin(); it != fLinks.end(); it++) {
     FairLink tempLink = *it;
     tempLink.SetWeight(weight * tempLink.GetWeight());
     tempLinks.insert(tempLink);
   }
   fLinks = tempLinks;
 }
virtual void FairDoubleHit::Print (const Option_t * opt = 0) const pure virtual
std::ostream& FairMultiLinkedData::Print (std::ostream & out = std::cout) const inline inherited
Output.
Definition at line 82 of file FairMultiLinkedData.h.
References FairMultiLinkedData::GetEntryNr(), FairMultiLinkedData::GetLink(), FairMultiLinkedData::GetNLinks(), and FairLink::Print().
Referenced by FairMultiLinkedData_Interface::Print().
virtual void FairMultiLinkedData::Reset () inline virtual inherited
Definition at line 78 of file FairMultiLinkedData.h.
References FairMultiLinkedData::ResetLinks().
Referenced by FairMCMatch::ClearFinalStage().
 {ResetLinks();}
virtual void FairMultiLinkedData::ResetLinks () inline virtual inherited
Clears fLinks.
Definition at line 79 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fLinks.
Referenced by FairMCDataCrawler::GetInfo(), FairMultiLinkedData::Reset(), and FairMultiLinkedData_Interface::ResetLinks().
void FairMultiLinkedData::SetAllWeights (Double_t weight) virtual inherited
Sets a common weight for Links.
Definition at line 288 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::fLinks, and FairLink::SetWeight().
 {
   std::set<FairLink> tempLinks;
   for (std::set<FairLink>::iterator it = fLinks.begin(); it != fLinks.end(); it++) {
     FairLink tempLink = *it;
     tempLink.SetWeight(weight);
     tempLinks.insert(tempLink);
   }
   fLinks = tempLinks;
 }
virtual void FairMultiLinkedData::SetDefaultType (Int_t type) inline virtual inherited
Definition at line 49 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fDefaultType.
 {  fDefaultType = type;}
virtual void FairDoubleHit::SetDetectorID (Int_t chamb) pure virtual
virtual void FairDoubleHit::SetDPos_in (TVector3 xyz) pure virtual
virtual void FairDoubleHit::SetDPos_out (TVector3 xyz) pure virtual
virtual void FairMultiLinkedData::SetEntryNr (FairLink entry) inline virtual inherited
Definition at line 54 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fEntryNr.
Referenced by FairMultiLinkedData_Interface::SetEntryNr().
 { fEntryNr = entry;}
virtual void FairMultiLinkedData::SetInsertHistory (Bool_t val) inline virtual inherited
Toggles if history of a link is inserted or not.
Definition at line 52 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fInsertHistory.
Referenced by FairMultiLinkedData_Interface::SetInsertHistory().
void FairMultiLinkedData::SetLink (FairLink link, Bool_t bypass = kFALSE, Float_t mult = 1.0) virtual inherited
Sets the Links with a single FairLink.
Definition at line 93 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData::fLinks, FairLink::GetWeight(), and FairLink::SetWeight().
Referenced by FairMCMatch::CreateArtificialStage(), and FairMultiLinkedData_Interface::SetLink().
 {
   fLinks.clear();
   Float_t weight = link.GetWeight() * mult;
   link.SetWeight(weight);
   AddLink(link, bypass);
 }
void FairMultiLinkedData::SetLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 86 of file FairMultiLinkedData.cxx.
References FairMultiLinkedData::AddLinks(), and FairMultiLinkedData::fLinks.
Referenced by FairMCMatch::GetMCInfoBackwardSingle(), FairMCMatch::GetMCInfoForwardSingle(), and FairMultiLinkedData_Interface::SetLinks().
 {
   fLinks.clear();
   AddLinks(links, mult);
 }
virtual void FairMultiLinkedData::SetPersistanceCheck (Bool_t check) inline virtual inherited
Controls if a persistance check of a link is done or not.
Definition at line 50 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fPersistanceCheck.
Referenced by FairMCObject::AdoptSize(), FairMCMatch::CreateArtificialStage(), FairMCEntry::FairMCEntry(), FairMCMatch::FairMCMatch(), FairMCMatch::FindLinksToStage(), FairMCMatch::FindStagesPointingToLink(), FairMCMatch::FindStagesPointingToLinks(), FairMCMatch::GetMCInfoForwardSingle(), FairMCObject::PosInList(), and FairMCObject::SetEntry().
virtual void FairDoubleHit::SetPos_in (TVector3 xyz) pure virtual
virtual void FairDoubleHit::SetPos_out (TVector3 xyz) pure virtual
virtual void FairDoubleHit::SetRefIndex (Int_t index) pure virtual
virtual void FairMultiLinkedData::SetVerbose (Int_t level) inline virtual inherited
Sets the verbosity level.
Definition at line 51 of file FairMultiLinkedData.h.
References FairMultiLinkedData::fVerbose.
virtual void FairMultiLinkedData::SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t bypass, Float_t mult) inline protected virtual inherited
Definition at line 105 of file FairMultiLinkedData.h.
Referenced by FairMultiLinkedData::FairMultiLinkedData().
{
       for (UInt_t i = 0; i < links.size(); i++) {
         fLinks.insert(FairLink(fileId, evtId, dataType, links[i]));
       }
     }
virtual Double_t FairDoubleHit::x_in () pure virtual
virtual Double_t FairDoubleHit::x_out () pure virtual
virtual Double_t FairDoubleHit::y_in () pure virtual
virtual Double_t FairDoubleHit::y_out () pure virtual
virtual Double_t FairDoubleHit::z_in () pure virtual
virtual Double_t FairDoubleHit::z_out () pure virtual
Member Data Documentation
Int_t FairMultiLinkedData::fDefaultType protected inherited
Definition at line 110 of file FairMultiLinkedData.h.
Referenced by FairMultiLinkedData::GetDefaultType(), and FairMultiLinkedData::SetDefaultType().
Int_t FairDoubleHit::fDetectorID protected
Definition at line 21 of file FairDoubleHit.h.
FairLink FairMultiLinkedData::fEntryNr protected inherited
Definition at line 100 of file FairMultiLinkedData.h.
Referenced by FairMultiLinkedData::GetEntryNr(), and FairMultiLinkedData::SetEntryNr().
Bool_t FairMultiLinkedData::fInsertHistory protected inherited
Definition at line 102 of file FairMultiLinkedData.h.
Referenced by FairMultiLinkedData::AddLink(), and FairMultiLinkedData::SetInsertHistory().
std::set<FairLink> FairMultiLinkedData::fLinks protected inherited
Definition at line 99 of file FairMultiLinkedData.h.
Referenced by FairMultiLinkedData::AddAllWeights(), FairMultiLinkedData::GetLink(), FairMultiLinkedData::GetLinks(), FairMultiLinkedData::GetLinksWithType(), FairMultiLinkedData::GetNLinks(), FairMultiLinkedData::InsertLink(), FairMultiLinkedData::LinkPosInList(), FairMultiLinkedData::MultiplyAllWeights(), FairMCEntry::RemoveType(), FairMultiLinkedData::ResetLinks(), FairMultiLinkedData::SetAllWeights(), FairMultiLinkedData::SetLink(), and FairMultiLinkedData::SetLinks().
Bool_t FairMultiLinkedData::fPersistanceCheck protected inherited
Definition at line 101 of file FairMultiLinkedData.h.
Referenced by FairMultiLinkedData::AddLink(), FairMultiLinkedData::GetPersistanceCheck(), and FairMultiLinkedData::SetPersistanceCheck().
TVector3 FairDoubleHit::fPosition_in protected
Definition at line 22 of file FairDoubleHit.h.
TVector3 FairDoubleHit::fPosition_out protected
Definition at line 24 of file FairDoubleHit.h.
TVector3 FairDoubleHit::fPositionError_in protected
Definition at line 23 of file FairDoubleHit.h.
TVector3 FairDoubleHit::fPositionError_out protected
Definition at line 25 of file FairDoubleHit.h.
Int_t FairDoubleHit::fRefIndex protected
Definition at line 20 of file FairDoubleHit.h.
Int_t FairMultiLinkedData::fVerbose protected inherited
Definition at line 103 of file FairMultiLinkedData.h.
Referenced by FairMultiLinkedData::AddLink(), FairMultiLinkedData::GetVerbose(), FairMultiLinkedData::InsertHistory(), and FairMultiLinkedData::SetVerbose().
The documentation for this class was generated from the following files:
FairDoubleHit.h
FairDoubleHit.cxx