FairRoot: runTestDetectorSamplerBin.cxx File Reference
Tutorial6/run/runTestDetectorSamplerBin.cxx File Reference
#include <iostream>
#include <csignal>
#include "FairMQLogger.h"
#include "FairMQSampler.h"
#include "zeromq/FairMQTransportFactoryZMQ.h"
#include "TestDetectorDigiLoader.h"
#include "FairTestDetectorPayload.h"
#include "FairTestDetectorDigi.h"
Typedefs
typedef FairTestDetectorDigi TDigi
typedef TestDetectorPayload::Digi TPayloadOut
typedef TestDetectorDigiLoader< TDigi, TPayloadOut > TLoader
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
int main (int argc, char **argv)
Variables
FairMQSampler< TLoader > sampler
Typedef Documentation
typedef FairTestDetectorDigi TDigi
Definition at line 37 of file Tutorial6/run/runTestDetectorSamplerBin.cxx.
typedef TestDetectorDigiLoader<TDigi, TPayloadOut> TLoader
Definition at line 39 of file Tutorial6/run/runTestDetectorSamplerBin.cxx.
typedef TestDetectorPayload::Digi TPayloadOut
Definition at line 38 of file Tutorial6/run/runTestDetectorSamplerBin.cxx.
Function Documentation
int main (int argc, char ** argv)
Definition at line 65 of file Tutorial6/run/runTestDetectorSamplerBin.cxx.
References FairMQStateMachine::ChangeState(), ERROR, INFO, LOG, s_catch_signals(), FairMQSampler< Loader >::SetContinuous(), FairMQSampler< Loader >::SetProperty(), and FairMQDevice::SetTransport().
 {
     if (argc != 11)
     {
         cout << "Usage: testDetectorSampler \tID inputFile parameterFile\n"
              << "\t\tbranch eventRate numIoTreads\n"
              << "\t\toutputSocketType outputSndBufSize outputMethod outputAddress\n" << endl;
         return 1;
     }
     s_catch_signals();
     LOG(INFO) << "PID: " << getpid();
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     sampler.SetTransport(transportFactory);
     int i = 1;
     sampler.SetProperty(FairMQSampler<TLoader>::Id, argv[i]);
     ++i;
     sampler.SetProperty(FairMQSampler<TLoader>::InputFile, argv[i]);
     ++i;
     sampler.SetProperty(FairMQSampler<TLoader>::ParFile, argv[i]);
     ++i;
     sampler.SetProperty(FairMQSampler<TLoader>::Branch, argv[i]);
     ++i;
     int eventRate;
     stringstream(argv[i]) >> eventRate;
     sampler.SetProperty(FairMQSampler<TLoader>::EventRate, eventRate);
     ++i;
     int numIoThreads;
     stringstream(argv[i]) >> numIoThreads;
     sampler.SetProperty(FairMQSampler<TLoader>::NumIoThreads, numIoThreads);
     ++i;
     sampler.SetProperty(FairMQSampler<TLoader>::NumInputs, 0);
     sampler.SetProperty(FairMQSampler<TLoader>::NumOutputs, 1);
     sampler.ChangeState(FairMQSampler<TLoader>::INIT);
     // INPUT: 0 - command
     // sampler.SetProperty(FairMQSampler::InputSocketType, ZMQ_SUB, 0);
     // sampler.SetProperty(FairMQSampler::InputRcvBufSize, 1000, 0);
     // sampler.SetProperty(FairMQSampler::InputAddress, "tcp://localhost:5560", 0);
     // OUTPUT: 0 - data
     sampler.SetProperty(FairMQSampler<TLoader>::OutputSocketType, argv[i], 0);
     ++i;
     int outputSndBufSize;
     stringstream(argv[i]) >> outputSndBufSize;
     sampler.SetProperty(FairMQSampler<TLoader>::OutputSndBufSize, outputSndBufSize, 0);
     ++i;
     sampler.SetProperty(FairMQSampler<TLoader>::OutputMethod, argv[i], 0);
     ++i;
     sampler.SetProperty(FairMQSampler<TLoader>::OutputAddress, argv[i], 0);
     ++i;
     // Add a continuous mode for the Sampler
     sampler.SetContinuous(true);
     // OUTPUT: 1 - logger
     // sampler.SetProperty(FairMQSampler::OutputSocketType, ZMQ_PUB, 1);
     // sampler.SetProperty(FairMQSampler::OutputSndBufSize, 1000, 1);
     // sampler.SetProperty(FairMQSampler::OutputAddress, "tcp://*:5561", 1);
     sampler.ChangeState(FairMQSampler<TLoader>::SETOUTPUT);
     sampler.ChangeState(FairMQSampler<TLoader>::SETINPUT);
     sampler.ChangeState(FairMQSampler<TLoader>::BIND);
     sampler.ChangeState(FairMQSampler<TLoader>::CONNECT);
     // sampler.ChangeState(FairMQSampler<TLoader>::RUN);
     try
     {
         sampler.ChangeState(FairMQSampler<TLoader>::RUN);
     }
     catch (boost::archive::archive_exception& e)
     {
         LOG(ERROR) << e.what();
     }
     // TODO: get rid of this hack!
     char ch;
     cin.get(ch);
     sampler.ChangeState(FairMQSampler<TLoader>::STOP);
     sampler.ChangeState(FairMQSampler<TLoader>::END);
     return 0;
 }
static void s_catch_signals (void) static
Definition at line 55 of file Tutorial6/run/runTestDetectorSamplerBin.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 44 of file Tutorial6/run/runTestDetectorSamplerBin.cxx.
References FairMQStateMachine::ChangeState().
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     sampler.ChangeState(FairMQSampler<TLoader>::STOP);
     sampler.ChangeState(FairMQSampler<TLoader>::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
FairMQSampler<TLoader> sampler
Definition at line 41 of file Tutorial6/run/runTestDetectorSamplerBin.cxx.