// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FairTestDetectorPayload.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "FairTestDetectorPayload.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace TestDetectorProto {

namespace {

const ::google::protobuf::Descriptor* Digi_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Digi_reflection_ = NULL;
const ::google::protobuf::Descriptor* Hit_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Hit_reflection_ = NULL;
const ::google::protobuf::Descriptor* DigiPayload_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DigiPayload_reflection_ = NULL;
const ::google::protobuf::Descriptor* HitPayload_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HitPayload_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_FairTestDetectorPayload_2eproto() {
  protobuf_AddDesc_FairTestDetectorPayload_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "FairTestDetectorPayload.proto");
  GOOGLE_CHECK(file != NULL);
  Digi_descriptor_ = file->message_type(0);
  static const int Digi_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
  };
  Digi_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Digi_descriptor_,
      Digi::default_instance_,
      Digi_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Digi));
  Hit_descriptor_ = file->message_type(1);
  static const int Hit_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
  };
  Hit_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Hit_descriptor_,
      Hit::default_instance_,
      Hit_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Hit));
  DigiPayload_descriptor_ = file->message_type(2);
  static const int DigiPayload_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
  };
  DigiPayload_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DigiPayload_descriptor_,
      DigiPayload::default_instance_,
      DigiPayload_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DigiPayload));
  HitPayload_descriptor_ = file->message_type(3);
  static const int HitPayload_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
  };
  HitPayload_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HitPayload_descriptor_,
      HitPayload::default_instance_,
      HitPayload_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HitPayload));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_FairTestDetectorPayload_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Digi_descriptor_, &Digi::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Hit_descriptor_, &Hit::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DigiPayload_descriptor_, &DigiPayload::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HitPayload_descriptor_, &HitPayload::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto() {
  delete Digi::default_instance_;
  delete Digi_reflection_;
  delete Hit::default_instance_;
  delete Hit_reflection_;
  delete DigiPayload::default_instance_;
  delete DigiPayload_reflection_;
  delete HitPayload::default_instance_;
  delete HitPayload_reflection_;
}

void protobuf_AddDesc_FairTestDetectorPayload_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035FairTestDetectorPayload.proto\022\021TestDet"
    "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
    "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
    "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
    "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
    "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
    "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
    "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
    "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
    ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
    "etectorProto.Hit", 416);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
  Digi::default_instance_ = new Digi();
  Hit::default_instance_ = new Hit();
  DigiPayload::default_instance_ = new DigiPayload();
  HitPayload::default_instance_ = new HitPayload();
  Digi::default_instance_->InitAsDefaultInstance();
  Hit::default_instance_->InitAsDefaultInstance();
  DigiPayload::default_instance_->InitAsDefaultInstance();
  HitPayload::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FairTestDetectorPayload_2eproto {
  StaticDescriptorInitializer_FairTestDetectorPayload_2eproto() {
    protobuf_AddDesc_FairTestDetectorPayload_2eproto();
  }
} static_descriptor_initializer_FairTestDetectorPayload_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Digi::kFXFieldNumber;
const int Digi::kFYFieldNumber;
const int Digi::kFZFieldNumber;
const int Digi::kFTimeStampFieldNumber;
const int Digi::kFTimeStampErrorFieldNumber;
#endif  // !_MSC_VER

Digi::Digi()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Digi::InitAsDefaultInstance() {
}

Digi::Digi(const Digi& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Digi::SharedCtor() {
  _cached_size_ = 0;
  fx_ = 0;
  fy_ = 0;
  fz_ = 0;
  ftimestamp_ = 0;
  ftimestamperror_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Digi::~Digi() {
  SharedDtor();
}

void Digi::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Digi::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Digi::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Digi_descriptor_;
}

const Digi& Digi::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FairTestDetectorPayload_2eproto();
  return *default_instance_;
}

Digi* Digi::default_instance_ = NULL;

Digi* Digi::New() const {
  return new Digi;
}

void Digi::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    fx_ = 0;
    fy_ = 0;
    fz_ = 0;
    ftimestamp_ = 0;
    ftimestamperror_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Digi::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 fX = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fx_)));
          set_has_fx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_fY;
        break;
      }

      // optional int32 fY = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_fY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fy_)));
          set_has_fy();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_fZ;
        break;
      }

      // optional int32 fZ = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_fZ:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fz_)));
          set_has_fz();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(33)) goto parse_fTimeStamp;
        break;
      }

      // optional double fTimeStamp = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_fTimeStamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ftimestamp_)));
          set_has_ftimestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(41)) goto parse_fTimeStampError;
        break;
      }

      // optional double fTimeStampError = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_fTimeStampError:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ftimestamperror_)));
          set_has_ftimestamperror();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Digi::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 fX = 1;
  if (has_fx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->fx(), output);
  }

  // optional int32 fY = 2;
  if (has_fy()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->fy(), output);
  }

  // optional int32 fZ = 3;
  if (has_fz()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->fz(), output);
  }

  // optional double fTimeStamp = 4;
  if (has_ftimestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->ftimestamp(), output);
  }

  // optional double fTimeStampError = 5;
  if (has_ftimestamperror()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->ftimestamperror(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Digi::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 fX = 1;
  if (has_fx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->fx(), target);
  }

  // optional int32 fY = 2;
  if (has_fy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->fy(), target);
  }

  // optional int32 fZ = 3;
  if (has_fz()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->fz(), target);
  }

  // optional double fTimeStamp = 4;
  if (has_ftimestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->ftimestamp(), target);
  }

  // optional double fTimeStampError = 5;
  if (has_ftimestamperror()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->ftimestamperror(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Digi::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 fX = 1;
    if (has_fx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fx());
    }

    // optional int32 fY = 2;
    if (has_fy()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fy());
    }

    // optional int32 fZ = 3;
    if (has_fz()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fz());
    }

    // optional double fTimeStamp = 4;
    if (has_ftimestamp()) {
      total_size += 1 + 8;
    }

    // optional double fTimeStampError = 5;
    if (has_ftimestamperror()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Digi::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Digi* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Digi*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Digi::MergeFrom(const Digi& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_fx()) {
      set_fx(from.fx());
    }
    if (from.has_fy()) {
      set_fy(from.fy());
    }
    if (from.has_fz()) {
      set_fz(from.fz());
    }
    if (from.has_ftimestamp()) {
      set_ftimestamp(from.ftimestamp());
    }
    if (from.has_ftimestamperror()) {
      set_ftimestamperror(from.ftimestamperror());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Digi::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Digi::CopyFrom(const Digi& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Digi::IsInitialized() const {

  return true;
}

void Digi::Swap(Digi* other) {
  if (other != this) {
    std::swap(fx_, other->fx_);
    std::swap(fy_, other->fy_);
    std::swap(fz_, other->fz_);
    std::swap(ftimestamp_, other->ftimestamp_);
    std::swap(ftimestamperror_, other->ftimestamperror_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Digi::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Digi_descriptor_;
  metadata.reflection = Digi_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Hit::kDetIDFieldNumber;
const int Hit::kMcindexFieldNumber;
const int Hit::kPosXFieldNumber;
const int Hit::kPosYFieldNumber;
const int Hit::kPosZFieldNumber;
const int Hit::kDposXFieldNumber;
const int Hit::kDposYFieldNumber;
const int Hit::kDposZFieldNumber;
const int Hit::kFTimeStampFieldNumber;
const int Hit::kFTimeStampErrorFieldNumber;
#endif  // !_MSC_VER

Hit::Hit()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Hit::InitAsDefaultInstance() {
}

Hit::Hit(const Hit& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Hit::SharedCtor() {
  _cached_size_ = 0;
  detid_ = 0;
  mcindex_ = 0;
  posx_ = 0;
  posy_ = 0;
  posz_ = 0;
  dposx_ = 0;
  dposy_ = 0;
  dposz_ = 0;
  ftimestamp_ = 0;
  ftimestamperror_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Hit::~Hit() {
  SharedDtor();
}

void Hit::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Hit::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Hit::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Hit_descriptor_;
}

const Hit& Hit::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FairTestDetectorPayload_2eproto();
  return *default_instance_;
}

Hit* Hit::default_instance_ = NULL;

Hit* Hit::New() const {
  return new Hit;
}

void Hit::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    detid_ = 0;
    mcindex_ = 0;
    posx_ = 0;
    posy_ = 0;
    posz_ = 0;
    dposx_ = 0;
    dposy_ = 0;
    dposz_ = 0;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    ftimestamp_ = 0;
    ftimestamperror_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Hit::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 detID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &detid_)));
          set_has_detid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_mcindex;
        break;
      }

      // optional int32 mcindex = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_mcindex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mcindex_)));
          set_has_mcindex();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(25)) goto parse_posX;
        break;
      }

      // optional double posX = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_posX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &posx_)));
          set_has_posx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(33)) goto parse_posY;
        break;
      }

      // optional double posY = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_posY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &posy_)));
          set_has_posy();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(41)) goto parse_posZ;
        break;
      }

      // optional double posZ = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_posZ:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &posz_)));
          set_has_posz();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(49)) goto parse_dposX;
        break;
      }

      // optional double dposX = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_dposX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dposx_)));
          set_has_dposx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(57)) goto parse_dposY;
        break;
      }

      // optional double dposY = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_dposY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dposy_)));
          set_has_dposy();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(65)) goto parse_dposZ;
        break;
      }

      // optional double dposZ = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_dposZ:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dposz_)));
          set_has_dposz();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(73)) goto parse_fTimeStamp;
        break;
      }

      // optional double fTimeStamp = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_fTimeStamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ftimestamp_)));
          set_has_ftimestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(81)) goto parse_fTimeStampError;
        break;
      }

      // optional double fTimeStampError = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_fTimeStampError:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ftimestamperror_)));
          set_has_ftimestamperror();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Hit::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 detID = 1;
  if (has_detid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->detid(), output);
  }

  // optional int32 mcindex = 2;
  if (has_mcindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->mcindex(), output);
  }

  // optional double posX = 3;
  if (has_posx()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->posx(), output);
  }

  // optional double posY = 4;
  if (has_posy()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->posy(), output);
  }

  // optional double posZ = 5;
  if (has_posz()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->posz(), output);
  }

  // optional double dposX = 6;
  if (has_dposx()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->dposx(), output);
  }

  // optional double dposY = 7;
  if (has_dposy()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->dposy(), output);
  }

  // optional double dposZ = 8;
  if (has_dposz()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->dposz(), output);
  }

  // optional double fTimeStamp = 9;
  if (has_ftimestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->ftimestamp(), output);
  }

  // optional double fTimeStampError = 10;
  if (has_ftimestamperror()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->ftimestamperror(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Hit::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 detID = 1;
  if (has_detid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->detid(), target);
  }

  // optional int32 mcindex = 2;
  if (has_mcindex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->mcindex(), target);
  }

  // optional double posX = 3;
  if (has_posx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->posx(), target);
  }

  // optional double posY = 4;
  if (has_posy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->posy(), target);
  }

  // optional double posZ = 5;
  if (has_posz()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->posz(), target);
  }

  // optional double dposX = 6;
  if (has_dposx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->dposx(), target);
  }

  // optional double dposY = 7;
  if (has_dposy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->dposy(), target);
  }

  // optional double dposZ = 8;
  if (has_dposz()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->dposz(), target);
  }

  // optional double fTimeStamp = 9;
  if (has_ftimestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->ftimestamp(), target);
  }

  // optional double fTimeStampError = 10;
  if (has_ftimestamperror()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->ftimestamperror(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Hit::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 detID = 1;
    if (has_detid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->detid());
    }

    // optional int32 mcindex = 2;
    if (has_mcindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->mcindex());
    }

    // optional double posX = 3;
    if (has_posx()) {
      total_size += 1 + 8;
    }

    // optional double posY = 4;
    if (has_posy()) {
      total_size += 1 + 8;
    }

    // optional double posZ = 5;
    if (has_posz()) {
      total_size += 1 + 8;
    }

    // optional double dposX = 6;
    if (has_dposx()) {
      total_size += 1 + 8;
    }

    // optional double dposY = 7;
    if (has_dposy()) {
      total_size += 1 + 8;
    }

    // optional double dposZ = 8;
    if (has_dposz()) {
      total_size += 1 + 8;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional double fTimeStamp = 9;
    if (has_ftimestamp()) {
      total_size += 1 + 8;
    }

    // optional double fTimeStampError = 10;
    if (has_ftimestamperror()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Hit::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Hit* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Hit*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Hit::MergeFrom(const Hit& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_detid()) {
      set_detid(from.detid());
    }
    if (from.has_mcindex()) {
      set_mcindex(from.mcindex());
    }
    if (from.has_posx()) {
      set_posx(from.posx());
    }
    if (from.has_posy()) {
      set_posy(from.posy());
    }
    if (from.has_posz()) {
      set_posz(from.posz());
    }
    if (from.has_dposx()) {
      set_dposx(from.dposx());
    }
    if (from.has_dposy()) {
      set_dposy(from.dposy());
    }
    if (from.has_dposz()) {
      set_dposz(from.dposz());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_ftimestamp()) {
      set_ftimestamp(from.ftimestamp());
    }
    if (from.has_ftimestamperror()) {
      set_ftimestamperror(from.ftimestamperror());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Hit::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Hit::CopyFrom(const Hit& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Hit::IsInitialized() const {

  return true;
}

void Hit::Swap(Hit* other) {
  if (other != this) {
    std::swap(detid_, other->detid_);
    std::swap(mcindex_, other->mcindex_);
    std::swap(posx_, other->posx_);
    std::swap(posy_, other->posy_);
    std::swap(posz_, other->posz_);
    std::swap(dposx_, other->dposx_);
    std::swap(dposy_, other->dposy_);
    std::swap(dposz_, other->dposz_);
    std::swap(ftimestamp_, other->ftimestamp_);
    std::swap(ftimestamperror_, other->ftimestamperror_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Hit::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Hit_descriptor_;
  metadata.reflection = Hit_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int DigiPayload::kDigiFieldNumber;
#endif  // !_MSC_VER

DigiPayload::DigiPayload()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DigiPayload::InitAsDefaultInstance() {
}

DigiPayload::DigiPayload(const DigiPayload& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DigiPayload::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DigiPayload::~DigiPayload() {
  SharedDtor();
}

void DigiPayload::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DigiPayload::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DigiPayload::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DigiPayload_descriptor_;
}

const DigiPayload& DigiPayload::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FairTestDetectorPayload_2eproto();
  return *default_instance_;
}

DigiPayload* DigiPayload::default_instance_ = NULL;

DigiPayload* DigiPayload::New() const {
  return new DigiPayload;
}

void DigiPayload::Clear() {
  digi_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DigiPayload::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .TestDetectorProto.Digi digi = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_digi:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_digi()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_digi;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DigiPayload::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .TestDetectorProto.Digi digi = 1;
  for (int i = 0; i < this->digi_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->digi(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DigiPayload::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .TestDetectorProto.Digi digi = 1;
  for (int i = 0; i < this->digi_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->digi(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DigiPayload::ByteSize() const {
  int total_size = 0;

  // repeated .TestDetectorProto.Digi digi = 1;
  total_size += 1 * this->digi_size();
  for (int i = 0; i < this->digi_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->digi(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DigiPayload::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DigiPayload* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DigiPayload*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DigiPayload::MergeFrom(const DigiPayload& from) {
  GOOGLE_CHECK_NE(&from, this);
  digi_.MergeFrom(from.digi_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DigiPayload::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DigiPayload::CopyFrom(const DigiPayload& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DigiPayload::IsInitialized() const {

  return true;
}

void DigiPayload::Swap(DigiPayload* other) {
  if (other != this) {
    digi_.Swap(&other->digi_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DigiPayload::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DigiPayload_descriptor_;
  metadata.reflection = DigiPayload_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int HitPayload::kHitFieldNumber;
#endif  // !_MSC_VER

HitPayload::HitPayload()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void HitPayload::InitAsDefaultInstance() {
}

HitPayload::HitPayload(const HitPayload& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void HitPayload::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HitPayload::~HitPayload() {
  SharedDtor();
}

void HitPayload::SharedDtor() {
  if (this != default_instance_) {
  }
}

void HitPayload::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HitPayload::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HitPayload_descriptor_;
}

const HitPayload& HitPayload::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FairTestDetectorPayload_2eproto();
  return *default_instance_;
}

HitPayload* HitPayload::default_instance_ = NULL;

HitPayload* HitPayload::New() const {
  return new HitPayload;
}

void HitPayload::Clear() {
  hit_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HitPayload::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .TestDetectorProto.Hit hit = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_hit:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_hit()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_hit;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void HitPayload::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .TestDetectorProto.Hit hit = 1;
  for (int i = 0; i < this->hit_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->hit(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* HitPayload::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .TestDetectorProto.Hit hit = 1;
  for (int i = 0; i < this->hit_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->hit(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int HitPayload::ByteSize() const {
  int total_size = 0;

  // repeated .TestDetectorProto.Hit hit = 1;
  total_size += 1 * this->hit_size();
  for (int i = 0; i < this->hit_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->hit(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HitPayload::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HitPayload* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HitPayload*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HitPayload::MergeFrom(const HitPayload& from) {
  GOOGLE_CHECK_NE(&from, this);
  hit_.MergeFrom(from.hit_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HitPayload::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HitPayload::CopyFrom(const HitPayload& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HitPayload::IsInitialized() const {

  return true;
}

void HitPayload::Swap(HitPayload* other) {
  if (other != this) {
    hit_.Swap(&other->hit_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HitPayload::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HitPayload_descriptor_;
  metadata.reflection = HitPayload_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace TestDetectorProto

// @@protoc_insertion_point(global_scope)
