FairRroot: FairMQMessageZMQ Class Reference
FairMQMessageZMQ Class Reference
#include <FairMQMessageZMQ.h>
Public Member Functions
FairMQMessageZMQ ()
FairMQMessageZMQ (size_t size)
FairMQMessageZMQ (void *data, size_t size, fairmq_free_fn *ffn=&CleanUp, void *hint=NULL)
virtual void Rebuild ()
virtual void Rebuild (size_t size)
virtual void Rebuild (void *data, size_t size, fairmq_free_fn *ffn=&CleanUp, void *hint=NULL)
virtual void * GetMessage ()
virtual void * GetData ()
virtual size_t GetSize ()
virtual void SetMessage (void *data, size_t size)
virtual void CloseMessage ()
virtual void Copy (FairMQMessage *msg)
virtual ~FairMQMessageZMQ ()
Static Public Member Functions
static void CleanUp (void *data, void *hint)
Private Attributes
zmq_msg_t fMessage
Detailed Description
FairMQMessageZMQ.h
Since
2014-01-17
Author
A. Rybalchenko
Definition at line 24 of file FairMQMessageZMQ.h.
Constructor & Destructor Documentation
FairMQMessageZMQ::FairMQMessageZMQ ()
FairMQMessageZMQ.cxx
Since
2012-12-05
Author
D. Klein, A. Rybalchenko, N. Winckler
Definition at line 21 of file FairMQMessageZMQ.cxx.
References ERROR, fMessage, and LOG.
 {
     int rc = zmq_msg_init(&fMessage);
     if (rc != 0)
     {
         LOG(ERROR) << "failed initializing message, reason: " << zmq_strerror(errno);
     }
 }
FairMQMessageZMQ::FairMQMessageZMQ (size_t size)
Definition at line 30 of file FairMQMessageZMQ.cxx.
References ERROR, fMessage, and LOG.
 {
     int rc = zmq_msg_init_size(&fMessage, size);
     if (rc != 0)
     {
         LOG(ERROR) << "failed initializing message with size, reason: " << zmq_strerror(errno);
     }
 }
FairMQMessageZMQ::FairMQMessageZMQ (void * data, size_t size, fairmq_free_fn * ffn = &CleanUp, void * hint = NULL)
Definition at line 39 of file FairMQMessageZMQ.cxx.
References CleanUp(), ERROR, fMessage, and LOG.
 {
     int rc = zmq_msg_init_data(&fMessage, data, size, ffn ? ffn : &CleanUp, hint);
     if (rc != 0)
     {
         LOG(ERROR) << "failed initializing message with data, reason: " << zmq_strerror(errno);
     }
 }
FairMQMessageZMQ::~FairMQMessageZMQ () virtual
Definition at line 129 of file FairMQMessageZMQ.cxx.
References ERROR, fMessage, and LOG.
 {
     int rc = zmq_msg_close(&fMessage);
     if (rc != 0)
     {
         LOG(ERROR) << "failed closing message with data, reason: " << zmq_strerror(errno);
     }
 }
Member Function Documentation
void FairMQMessageZMQ::CleanUp (void * data, void * hint) static
Definition at line 124 of file FairMQMessageZMQ.cxx.
Referenced by FairMQMessageZMQ(), and Rebuild().
 {
     free(data);
 }
void FairMQMessageZMQ::CloseMessage () inline virtual
Implements FairMQMessage.
Definition at line 115 of file FairMQMessageZMQ.cxx.
References ERROR, fMessage, and LOG.
Referenced by Rebuild().
 {
     int rc = zmq_msg_close(&fMessage);
     if (rc != 0)
     {
         LOG(ERROR) << "failed closing message, reason: " << zmq_strerror(errno);
     }
 }
void FairMQMessageZMQ::Copy (FairMQMessage * msg) virtual
Implements FairMQMessage.
Definition at line 98 of file FairMQMessageZMQ.cxx.
References ERROR, fMessage, FairMQMessage::GetMessage(), and LOG.
 {
     // Shares the message buffer between msg and this fMessage.
     int rc = zmq_msg_copy(&fMessage, (zmq_msg_t*)msg->GetMessage());
     if (rc != 0)
     {
         LOG(ERROR) << "failed copying message, reason: " << zmq_strerror(errno);
     }
     // Alternatively, following code does a hard copy of the message, which allows to modify the original after making a copy, without affecting the new msg.
     // CloseMessage();
     // size_t size = msg->GetSize();
     // zmq_msg_init_size(&fMessage, size);
     // std::memcpy(zmq_msg_data(&fMessage), msg->GetData(), size);
 }
void * FairMQMessageZMQ::GetData () virtual
Implements FairMQMessage.
Definition at line 83 of file FairMQMessageZMQ.cxx.
References fMessage.
 {
     return zmq_msg_data(&fMessage);
 }
void * FairMQMessageZMQ::GetMessage () virtual
Implements FairMQMessage.
Definition at line 78 of file FairMQMessageZMQ.cxx.
References fMessage.
 {
     return &fMessage;
 }
size_t FairMQMessageZMQ::GetSize () virtual
Implements FairMQMessage.
Definition at line 88 of file FairMQMessageZMQ.cxx.
References fMessage.
 {
     return zmq_msg_size(&fMessage);
 }
void FairMQMessageZMQ::Rebuild () virtual
Implements FairMQMessage.
Definition at line 48 of file FairMQMessageZMQ.cxx.
References CloseMessage(), ERROR, fMessage, and LOG.
 {
     CloseMessage();
     int rc = zmq_msg_init(&fMessage);
     if (rc != 0)
     {
         LOG(ERROR) << "failed initializing message, reason: " << zmq_strerror(errno);
     }
 }
void FairMQMessageZMQ::Rebuild (size_t size) virtual
Implements FairMQMessage.
Definition at line 58 of file FairMQMessageZMQ.cxx.
References CloseMessage(), ERROR, fMessage, and LOG.
 {
     CloseMessage();
     int rc = zmq_msg_init_size(&fMessage, size);
     if (rc != 0)
     {
         LOG(ERROR) << "failed initializing message with size, reason: " << zmq_strerror(errno);
     }
 }
void FairMQMessageZMQ::Rebuild (void * data, size_t size, fairmq_free_fn * ffn = &CleanUp, void * hint = NULL) virtual
Implements FairMQMessage.
Definition at line 68 of file FairMQMessageZMQ.cxx.
References CleanUp(), CloseMessage(), ERROR, fMessage, and LOG.
 {
     CloseMessage();
     int rc = zmq_msg_init_data(&fMessage, data, size, ffn ? ffn : &CleanUp, hint);
     if (rc != 0)
     {
         LOG(ERROR) << "failed initializing message with data, reason: " << zmq_strerror(errno);
     }
 }
void FairMQMessageZMQ::SetMessage (void * data, size_t size) virtual
Implements FairMQMessage.
Definition at line 93 of file FairMQMessageZMQ.cxx.
 {
     // dummy method to comply with the interface. functionality not allowed in zeromq.
 }
Member Data Documentation
zmq_msg_t FairMQMessageZMQ::fMessage private
Definition at line 49 of file FairMQMessageZMQ.h.
Referenced by CloseMessage(), Copy(), FairMQMessageZMQ(), GetData(), GetMessage(), GetSize(), Rebuild(), and ~FairMQMessageZMQ().
The documentation for this class was generated from the following files:
FairMQMessageZMQ.h
FairMQMessageZMQ.cxx