FairRoot: FairParRootFileIo Class Reference
FairParRootFileIo Class Reference
#include <FairParRootFileIo.h>
Public Member Functions
FairParRootFileIo ()
FairParRootFileIo (Bool_t merged)
~FairParRootFileIo ()
Bool_t open (const Text_t *fname, Option_t *option="READ", const Text_t *ftitle="", Int_t compress=1)
Bool_t open (const TList *fnamelist, Option_t *option="READ", const Text_t *ftitle="", Int_t compress=1)
void close ()
void print ()
FairParRootFile * getParRootFile ()
void readVersions (FairRtdbRun *)
TList * getKeys ()
Bool_t check ()
void cd ()
Bool_t open (TFile *f)
void setMerging (Bool_t io)
virtual FairDetParIo * getDetParIo (const Text_t *)
virtual void setDetParIo (FairDetParIo *)
virtual void setDetParIo (Text_t *)
virtual void removeDetParIo (Text_t *)
void setInputNumber (Int_t)
const char * getFilename ()
void setAutoWritable (Bool_t f=kTRUE)
Bool_t isAutoWritable ()
Protected Attributes
FairParRootFile * file
Bool_t fMerging
TList * detParIoList
Bool_t autoWritable
TString filename
Private Member Functions
FairParRootFileIo (const FairParRootFileIo &)
FairParRootFileIo & operator= (const FairParRootFileIo &)
Detailed Description
Definition at line 55 of file FairParRootFileIo.h.
Constructor & Destructor Documentation
FairParRootFileIo::FairParRootFileIo ()
Definition at line 103 of file FairParRootFileIo.cxx.
   :FairParIo(),
    file(NULL),
    fMerging(kFALSE)
 {
   // constructor
   //  file=0;
   //  fMerging=kFALSE;
 }
FairParRootFileIo::FairParRootFileIo (Bool_t merged)
Definition at line 115 of file FairParRootFileIo.cxx.
   :FairParIo(),
    file(NULL),
    fMerging(merged)
 {
   // constructor
   //  file=0;
   //  fMerging=merged;
 }
FairParRootFileIo::~FairParRootFileIo ()
Definition at line 128 of file FairParRootFileIo.cxx.
References close().
 {
   // destructor closes an open file
   close();
 }
FairParRootFileIo::FairParRootFileIo (const FairParRootFileIo &) private
Member Function Documentation
void FairParRootFileIo::cd () inline virtual
Reimplemented from FairParIo.
Definition at line 78 of file FairParRootFileIo.h.
References FairParRootFile::cd().
               {
       // sets the global ROOT file pointer gFile
       if (file) { file->cd(); }
     }
Bool_t FairParRootFileIo::check () inline virtual
Reimplemented from FairParIo.
Definition at line 73 of file FairParRootFileIo.h.
References FairParRootFile::IsOpen().
                    {
       // returns kTRUE if file is open
       if (file) { return file->IsOpen(); }
       else { return kFALSE; }
     }
void FairParRootFileIo::close () virtual
Reimplemented from FairParIo.
Definition at line 248 of file FairParRootFileIo.cxx.
References FairParRootFile::Close(), FairParIo::detParIoList, and file.
Referenced by open(), and ~FairParRootFileIo().
 {
   // closes an open ROOT file and deletes the detector I/Os
   if (file) {
     file->Close();
     delete file;
     file=0;
   }
   if (detParIoList) {
     detParIoList->Delete();
   }
 }
FairDetParIo * FairParIo::getDetParIo (const Text_t * detName) virtual inherited
Definition at line 69 of file FairParIo.cxx.
Referenced by FairRuntimeDb::activateParIo(), and FairParGenericSet::write().
 {
   // returns pointer to input/output class for a detector
   //std::cout << " DetParIO # " << detName << detParIoList->GetEntries()  <<  std::endl;
   return ((FairDetParIo*)detParIoList->FindObject(detName));
 }
const char* FairParIo::getFilename () inline inherited
Definition at line 36 of file FairParIo.h.
Referenced by FairRunAnaProof::RunOnProof().
 {return filename.Data();}
TList * FairParRootFileIo::getKeys ()
Definition at line 302 of file FairParRootFileIo.cxx.
References file, and FairParRootFile::GetListOfKeys().
 {
   // returns the list of keys found in the ROOT file
   if (file) {
     return file->GetListOfKeys();
   }
   return 0;
 }
FairParRootFile * FairParRootFileIo::getParRootFile ()
Definition at line 283 of file FairParRootFileIo.cxx.
References file.
 {
   // returns a pointer to the current ROOT file
   return file;
 }
Bool_t FairParIo::isAutoWritable () inline inherited
Definition at line 58 of file FairParIo.h.
References FairParIo::autoWritable.
Referenced by FairRuntimeDb::closeOutput(), and FairRuntimeDb::writeContainer().
 {return autoWritable;}
Bool_t FairParRootFileIo::open (const Text_t * fname, Option_t * option = "READ", const Text_t * ftitle = "", Int_t compress = 1)
Definition at line 136 of file FairParRootFileIo.cxx.
References FairRuntimeDb::activateParIo(), close(), file, FairParIo::filename, fMerging, FairRuntimeDb::instance(), and FairParRootFile::IsOpen().
Referenced by FairAnaSelector::Init(), and open().
 {
   // It opens a ROOT file (default option "READ"). An open file will be closed.
   // The detector I/Os for all detectors defined in the setup are activated.
   //DB, lock file for NFS in case of mulitple access
   //gDirectory->ReadKeys();
   close();
   if (fMerging ) {
     // used test merging
     std::fstream* f = new std::fstream(fname);
     if (f->good()) {
       // check if file already exists
       option = "UPDATE";
     } else {
       // if file doesn't exist recreate option is used
       option = "RECREATE";
     }
     f->close();
     delete f;
   }
   file=new FairParRootFile(fname,option,ftitle,compress);
   if (file && file->IsOpen()) {
     filename = fname;
     FairRuntimeDb::instance()->activateParIo(this);
     return kTRUE;
   }
   cerr << "-E- Could not open input file " << fname << endl;
   Fatal("open","Could not open input file");
   return kFALSE;
 }
Bool_t FairParRootFileIo::open (const TList * fnamelist, Option_t * option = "READ", const Text_t * ftitle = "", Int_t compress = 1)
Definition at line 173 of file FairParRootFileIo.cxx.
References open().
 {
   TDatime currentDate;
   TString newParFileName = "";
   TFile*  newParFile=0;
   TObjString* string;
   TListIter myIter(fnamelist);
   TKey* inpKey;
   TFile*  inFile;
   Int_t nofFiles = 0;
   while((string = (TObjString*)myIter.Next())) {
     inFile = TFile::Open(string->GetString().Data());
     if ( !inFile ) {
       cout << "-W- File \"" << string->GetString().Data() << "\" does not exist" << endl;
       continue;
     }
     if ( nofFiles == 0 ) {
       newParFileName = string->GetString();
       newParFileName.Replace(newParFileName.Last('/')+1,
                              newParFileName.Length(),"");
       newParFileName = Form("%sallParams_%d_%d.root",
                             newParFileName.Data(),
                             currentDate.GetDate(),
                             currentDate.GetTime());
       newParFile = new TFile(newParFileName.Data(),"RECREATE");
     }
     TList* inputKeys = (TList*)inFile->GetListOfKeys();
     TListIter keyIter(inputKeys);
     while((inpKey = (TKey*)keyIter.Next())) {
       TObject* tempObj = inFile->Get(inpKey->GetName());
       newParFile->cd();
       tempObj->Write();
     }
     inFile->Close();
     nofFiles++;
   }
   if(newParFile!=0){
     newParFile->Close();
   }else{
     std::cout << "****NO file to close file = \"" << std::endl;
   }
   std::cout << "**** merged file = \"" << newParFileName.Data() << "\"" << std::endl;
   return this->open(newParFileName,option,ftitle,compress);
 }
Bool_t FairParRootFileIo::open (TFile * f)
Open an existing root file for IO
Definition at line 232 of file FairParRootFileIo.cxx.
References FairRuntimeDb::activateParIo(), file, FairParIo::filename, FairRuntimeDb::instance(), and FairParRootFile::IsOpen().
 {
   // It opens a ROOT file (default option "READ"). An open file will be closed.
   // The detector I/Os for all detectors defined in the setup are activated.
 //  close();
   file=new FairParRootFile(f);
   if (file && file->IsOpen()) {
     filename = file->GetName();
     FairRuntimeDb::instance()->activateParIo(this);
     return kTRUE;
   }
   return kFALSE;
 }
FairParRootFileIo& FairParRootFileIo::operator= (const FairParRootFileIo &) private
void FairParRootFileIo::print () virtual
Reimplemented from FairParIo.
Definition at line 263 of file FairParRootFileIo.cxx.
References FairParIo::detParIoList, and file.
 {
   // prints the content of a open ROOT file and the list of detector I/Os
   if (file) {
     file->ls();
     TIter next(detParIoList);
     FairDetParIo* io;
     cout<<"Root file I/O "<<file->GetName()<<" is open\n";
     cout<<"detector I/Os: ";
     while ((io=(FairDetParIo*)next())) {
       cout<<" "<<io->GetName();
     }
     cout<<'\n';
   } else {
     cout<<"No ROOT file open\n";
   }
 }
void FairParRootFileIo::readVersions (FairRtdbRun * currentRun) virtual
Reimplemented from FairParIo.
Definition at line 291 of file FairParRootFileIo.cxx.
References file, and FairParRootFile::readVersions().
 {
   // reads the parameter container versions for the current run from
   // the ROOT file
   if (file) {
     file->readVersions(currentRun);
   }
 }
void FairParIo::removeDetParIo (Text_t * detName) virtual inherited
Definition at line 76 of file FairParIo.cxx.
 {
   // removes input/output class for a detector
   TObject* p=detParIoList->FindObject(detName);
   if (p) {
     delete p;
     p=0;
   }
 }
void FairParIo::setAutoWritable (Bool_t f = kTRUE) inline inherited
Definition at line 57 of file FairParIo.h.
 {autoWritable=f;}
void FairParIo::setDetParIo (FairDetParIo * detParIo) virtual inherited
Definition at line 51 of file FairParIo.cxx.
Referenced by FairRuntimeDb::activateParIo().
 {
   // stores pointer of the input/output class for a detector
   // used for I/O from ROOT file or Ascii file
   Text_t* detName=(char*)detParIo->GetName();
   if (!detParIoList->FindObject(detName)) { detParIoList->Add(detParIo); }
 }
virtual void FairParIo::setDetParIo (Text_t *) inline virtual inherited
Definition at line 41 of file FairParIo.h.
 {;}
void FairParIo::setInputNumber (Int_t num) inherited
Definition at line 59 of file FairParIo.cxx.
References FairDetParIo::setInputNumber().
Referenced by FairRuntimeDb::setFirstInput(), and FairRuntimeDb::setSecondInput().
 {
   // sets in all detector I/Os the number of the input
   TIter next(detParIoList);
   FairDetParIo* io;
   while ((io=(FairDetParIo*)next())) {
     io->setInputNumber(num);
   }
 }
void FairParRootFileIo::setMerging (Bool_t io) inline
Definition at line 86 of file FairParRootFileIo.h.
 { fMerging=io;}
Member Data Documentation
Bool_t FairParIo::autoWritable protected inherited
Definition at line 24 of file FairParIo.h.
Referenced by FairParIo::isAutoWritable().
TList* FairParIo::detParIoList protected inherited
Definition at line 23 of file FairParIo.h.
Referenced by FairParAsciiFileIo::close(), close(), FairParAsciiFileIo::print(), and print().
FairParRootFile* FairParRootFileIo::file protected
Definition at line 58 of file FairParRootFileIo.h.
Referenced by close(), getKeys(), getParRootFile(), open(), print(), and readVersions().
TString FairParIo::filename protected inherited
Definition at line 25 of file FairParIo.h.
Referenced by FairParAsciiFileIo::close(), FairParAsciiFileIo::open(), open(), and FairParAsciiFileIo::print().
Bool_t FairParRootFileIo::fMerging protected
Definition at line 59 of file FairParRootFileIo.h.
Referenced by open().
The documentation for this class was generated from the following files:
FairParRootFileIo.h
FairParRootFileIo.cxx