FairRoot: FairMCTracks Class Reference
FairMCTracks Class Reference
#include <FairMCTracks.h>
Public Member Functions
FairMCTracks ()
FairMCTracks (const char *name, Int_t iVerbose=1)
virtual ~FairMCTracks ()
void SetVerbose (Int_t iVerbose)
virtual void Exec (Option_t *option)
virtual InitStatus Init ()
virtual void SetParContainers ()
virtual void Finish ()
void Reset ()
TEveTrackList * GetTrGroup (TParticle *P)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
TClonesArray * fTrackList
TEveTrackPropagator * fTrPr
FairEventManager * fEventManager
TObjArray * fEveTrList
TString fEvent
TEveTrackList * fTrList
Double_t MinEnergyLimit
Double_t MaxEnergyLimit
Double_t PEnergy
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairMCTracks (const FairMCTracks &)
FairMCTracks & operator= (const FairMCTracks &)
ClassDef (FairMCTracks, 1)
Detailed Description
Definition at line 36 of file FairMCTracks.h.
Constructor & Destructor Documentation
FairMCTracks::FairMCTracks ()
Default constructor
Definition at line 35 of file FairMCTracks.cxx.
   : FairTask("FairMCTracks", 0),
     fTrackList(NULL),
     fTrPr(NULL),
     fEventManager(NULL),
     fEveTrList(NULL),
     fEvent(""),
     fTrList(NULL),
     MinEnergyLimit(-1.),
     MaxEnergyLimit(-1.),
     PEnergy(-1.)
 {
 }
FairMCTracks::FairMCTracks (const char * name, Int_t iVerbose = 1)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 52 of file FairMCTracks.cxx.
   : FairTask(name, iVerbose),
     fTrackList(NULL),
     fTrPr(NULL),
     fEventManager(NULL),
     fEveTrList(new TObjArray(16)),
     fEvent(""),
     fTrList(NULL),
     MinEnergyLimit(-1.),
     MaxEnergyLimit(-1.),
     PEnergy(-1.)
 {
 }
FairMCTracks::~FairMCTracks () virtual
Destructor
Definition at line 148 of file FairMCTracks.cxx.
 {
 }
FairMCTracks::FairMCTracks (const FairMCTracks &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairMCTracks::ClassDef (FairMCTracks , 1) private
void FairMCTracks::Exec (Option_t * option) virtual
Executed task
Definition at line 87 of file FairMCTracks.cxx.
References FairEventManager::Color(), DEBUG1, DEBUG3, DEBUG4, FairLogger::endl(), fEventManager, fEveTrList, fTrackList, fTrList, fTrPr, FairEventManager::GetCurrentPDG(), FairEventManager::GetMaxEnergy(), FairEventManager::GetMinEnergy(), GetTrGroup(), FairEventManager::IsPriOnly(), LOG, MaxEnergyLimit, MinEnergyLimit, PEnergy, Reset(), FairEventManager::SetEvtMaxEnergy(), and FairEventManager::SetEvtMinEnergy().
 {
   if (IsActive()) {
     LOG(DEBUG1) << " FairMCTracks::Exec "<< FairLogger::endl;
     TGeoTrack* tr;
     const Double_t* point;
     Reset();
     for (Int_t i=0; i<fTrackList->GetEntriesFast(); i++)  {
       LOG(DEBUG3) << "FairMCTracks::Exec "<< i << FairLogger::endl;
       tr=(TGeoTrack*)fTrackList->At(i);
       TParticle* P=(TParticle*)tr->GetParticle();
       PEnergy=P->Energy();
       MinEnergyLimit=TMath::Min(PEnergy,MinEnergyLimit) ;
       MaxEnergyLimit=TMath::Max(PEnergy,MaxEnergyLimit) ;
       LOG(DEBUG3)<< "MinEnergyLimit " << MinEnergyLimit << " MaxEnergyLimit " << MaxEnergyLimit << FairLogger::endl;
       if (fEventManager->IsPriOnly() && P->GetMother(0)>-1) { continue; }
       if(fEventManager->GetCurrentPDG()!=0 && fEventManager->GetCurrentPDG()!= tr->GetPDG()) { continue; }
       LOG(DEBUG3) << "PEnergy " << PEnergy << " Min "  << fEventManager->GetMinEnergy() << " Max " << fEventManager->GetMaxEnergy() << FairLogger::endl;
       if( (PEnergy<fEventManager->GetMinEnergy()) || (PEnergy >fEventManager->GetMaxEnergy())) { continue; }
       Int_t Np=tr->GetNpoints();
       fTrList= GetTrGroup(P);
       TEveTrack* track= new TEveTrack(P, tr->GetPDG(), fTrPr);
       track->SetLineColor(fEventManager->Color(tr->GetPDG()));
       for (Int_t n=0; n<Np; n++) {
         point=tr->GetPoint(n);
         track->SetPoint(n,point[0],point[1],point[2]);
         TEveVector pos= TEveVector(point[0], point[1],point[2]);
         TEvePathMark* path = new TEvePathMark();
         path->fV=pos ;
         path->fTime= point[3];
         if(n==0) {
           TEveVector Mom= TEveVector(P->Px(), P->Py(),P->Pz());
           path->fP=Mom;
         }
         LOG(DEBUG4) << "Path marker added " << path << FairLogger::endl;
         track->AddPathMark(*path);
         LOG(DEBUG4) << "Path marker added " << path << FairLogger::endl;
         delete path;
       }
       fTrList->AddElement(track);
       LOG(DEBUG3) << "track added " << track->GetName() << FairLogger::endl;
     }
     for (Int_t i=0; i<fEveTrList->GetEntriesFast(); i++) {
       // TEveTrackList *TrListIn=( TEveTrackList *) fEveTrList->At(i);
       //TrListIn->FindMomentumLimits(TrListIn, kFALSE);
     }
     fEventManager->SetEvtMaxEnergy(MaxEnergyLimit);
     fEventManager->SetEvtMinEnergy(MinEnergyLimit);
     gEve->Redraw3D(kFALSE);
   }
 }
void FairMCTracks::Finish () virtual
Action after each event
Reimplemented from FairTask.
Definition at line 158 of file FairMCTracks.cxx.
 {
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
TEveTrackList * FairMCTracks::GetTrGroup (TParticle * P)
Definition at line 172 of file FairMCTracks.cxx.
References FairEventManager::Color(), fEventManager, fEveTrList, fTrList, and fTrPr.
Referenced by Exec().
 {
   fTrList=0;
   for (Int_t i=0; i<fEveTrList->GetEntriesFast(); i++) {
     TEveTrackList* TrListIn=( TEveTrackList*) fEveTrList->At(i);
     if ( strcmp(TrListIn->GetName(),P->GetName())==0 ) {
       fTrList= TrListIn;
       break;
     }
   }
   if(fTrList ==0) {
     fTrPr=new TEveTrackPropagator();
     fTrList= new  TEveTrackList(P->GetName(),fTrPr );
     fTrList->SetMainColor(fEventManager->Color(P->GetPdgCode()));
     fEveTrList->Add(fTrList);
     gEve->AddElement( fTrList ,fEventManager );
     fTrList->SetRnrLine(kTRUE);
   }
   return fTrList;
 }
InitStatus FairMCTracks::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 66 of file FairMCTracks.cxx.
References DEBUG, DEBUG1, FairLogger::endl(), ERROR, fEvent, fEventManager, fTrackList, FairEventManager::GetEvtMaxEnergy(), FairEventManager::GetEvtMinEnergy(), FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), kERROR, kSUCCESS, LOG, MaxEnergyLimit, MinEnergyLimit, and PEnergy.
 {
   LOG(DEBUG) <<  "FairMCTracks::Init()" << FairLogger::endl;
   FairRootManager* fManager = FairRootManager::Instance();
   fTrackList = (TClonesArray*)fManager->GetObject("GeoTracks");
   if(fTrackList==0) {
     LOG(ERROR) << "FairMCTracks::Init()  branch " << GetName() << " Not found! Task will be deactivated "<< FairLogger::endl;
     SetActive(kFALSE);
   }
   LOG(DEBUG1) <<  "FairMCTracks::Init() get track list" << fTrackList << FairLogger::endl;
   LOG(DEBUG1) <<  "FairMCTracks::Init()  create propagator" << FairLogger::endl;
   fEventManager =FairEventManager::Instance();
   LOG(DEBUG1) <<  "FairMCTracks::Init() get instance of FairEventManager " << FairLogger::endl;
   fEvent = "Current Event";
   MinEnergyLimit=fEventManager->GetEvtMinEnergy();
   MaxEnergyLimit=fEventManager->GetEvtMaxEnergy();
   PEnergy=0;
   if(IsActive()) { return kSUCCESS; }
   else { return kERROR; }
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairMCTracks& FairMCTracks::operator= (const FairMCTracks &) private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairMCTracks::Reset ()
Definition at line 163 of file FairMCTracks.cxx.
References fEventManager, and fEveTrList.
Referenced by Exec().
 {
   for (Int_t i=0; i<fEveTrList->GetEntriesFast(); i++) {
     TEveTrackList*  ele=( TEveTrackList*) fEveTrList->At(i);
     gEve->RemoveElement(ele,fEventManager);
   }
   fEveTrList->Clear();
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairMCTracks::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 152 of file FairMCTracks.cxx.
 {
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairMCTracks::SetVerbose (Int_t iVerbose) inline
Set verbosity level. For this task and all of the subtasks.
Definition at line 55 of file FairMCTracks.h.
References FairTask::fVerbose.
 {fVerbose = iVerbose;}
Member Data Documentation
TString FairMCTracks::fEvent protected
Definition at line 73 of file FairMCTracks.h.
Referenced by Init().
FairEventManager* FairMCTracks::fEventManager protected
Definition at line 71 of file FairMCTracks.h.
Referenced by Exec(), GetTrGroup(), Init(), and Reset().
TObjArray* FairMCTracks::fEveTrList protected
Definition at line 72 of file FairMCTracks.h.
Referenced by Exec(), GetTrGroup(), and Reset().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
TClonesArray* FairMCTracks::fTrackList protected
Definition at line 69 of file FairMCTracks.h.
Referenced by Exec(), and Init().
TEveTrackList* FairMCTracks::fTrList protected
Definition at line 74 of file FairMCTracks.h.
Referenced by Exec(), and GetTrGroup().
TEveTrackPropagator* FairMCTracks::fTrPr protected
Definition at line 70 of file FairMCTracks.h.
Referenced by Exec(), and GetTrGroup().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), SetVerbose(), and FairTask::SetVerbose().
Double_t FairMCTracks::MaxEnergyLimit protected
Definition at line 78 of file FairMCTracks.h.
Referenced by Exec(), and Init().
Double_t FairMCTracks::MinEnergyLimit protected
Definition at line 77 of file FairMCTracks.h.
Referenced by Exec(), and Init().
Double_t FairMCTracks::PEnergy protected
Definition at line 79 of file FairMCTracks.h.
Referenced by Exec(), and Init().
The documentation for this class was generated from the following files:
FairMCTracks.h
FairMCTracks.cxx