FairRroot: FairParticle Class Reference
FairParticle Class Reference
#include <FairParticle.h>
Public Member Functions
FairParticle (Int_t id, TParticle *particle)
FairParticle (Int_t id, TParticle *particle, FairParticle *mother)
FairParticle (const char *name, Int_t z, Int_t a, Int_t s, Double_t mass, Int_t q, Bool_t stable, Double_t decaytime)
FairParticle (const char *name, Int_t z, Int_t a, Double_t mass, Int_t q, Bool_t stable, Double_t decaytime)
FairParticle (Int_t pdg, const TString name, TMCParticleType mcType, Double_t mass, Double_t charge, Double_t lifetime, const TString pType="Ion", Double_t width=0, Int_t iSpin=0, Int_t iParity=0, Int_t iConjugation=0, Int_t iIsospin=0, Int_t iIsospinZ=0, Int_t gParity=0, Int_t lepton=0, Int_t baryon=0, Bool_t stable=kFALSE)
FairParticle ()
virtual ~FairParticle ()
void SetMother (FairParticle *particle)
void AddDaughter (FairParticle *particle)
virtual void Print (Option_t *option="") const
void PrintDaughters () const
Int_t GetPDG () const
TParticle * GetParticle () const
FairParticle * GetMother () const
Int_t GetNofDaughters () const
FairParticle * GetDaughter (Int_t i) const
virtual const char * GetName () const
TMCParticleType GetMCType ()
Double_t GetMass ()
Double_t GetCharge ()
Double_t GetDecayTime ()
const TString & GetPType ()
Double_t GetWidth ()
Int_t GetSpin ()
Int_t GetiParity ()
Int_t GetConjugation ()
Int_t GetIsospin ()
Int_t GetIsospinZ ()
Int_t GetgParity ()
Int_t GetLepton ()
Int_t GetBaryon ()
Bool_t IsStable ()
Private Member Functions
FairParticle (const FairParticle &P)
FairParticle & operator= (const FairParticle &)
Private Attributes
Int_t fpdg
TParticle * fParticle
TRef fMother
TRefArray fDaughters
const TString fname
TMCParticleType fmcType
Double_t fmass
Double_t fcharge
Double_t fDecayTime
const TString fpType
Double_t fwidth
Int_t fiSpin
Int_t fiParity
Int_t fiConjugation
Int_t fiIsospin
Int_t fiIsospinZ
Int_t fgParity
Int_t flepton
Int_t fbaryon
Bool_t fstable
Detailed Description
Definition at line 27 of file FairParticle.h.
Constructor & Destructor Documentation
FairParticle::FairParticle (Int_t id, TParticle * particle)
FairParticle::FairParticle (Int_t id, TParticle * particle, FairParticle * mother)
Definition at line 174 of file FairParticle.cxx.
   : TObject(),
     fpdg(id),
     fParticle(particle),
     fMother(mother),
     fDaughters(),
     fname(particle->GetName()),
     fmcType (kPTIon),
     fmass  (0),
     fcharge(0),
     fDecayTime(0),
     fpType("Ion"),
     fwidth(0),
     fiSpin(0),
     fiParity(0),
     fiConjugation(0),
     fiIsospin(0),
     fiIsospinZ(0),
     fgParity(0),
     flepton(0),
     fbaryon(0),
     fstable(kTRUE)
 {
 //
 }
FairParticle::FairParticle (const char * name, Int_t z, Int_t a, Int_t s, Double_t mass, Int_t q, Bool_t stable, Double_t decaytime)
Definition at line 57 of file FairParticle.cxx.
References fbaryon, fcharge, fDecayTime, fgParity, fiConjugation, fiIsospin, fiIsospinZ, fiParity, fiSpin, flepton, fmass, fmcType, fParticle, fpdg, fstable, and fwidth.
   :  TObject(),
      fpdg(1000000000+10000000*s+10000* z +10 * a),
      fParticle(0),
      fMother(0),
      fDaughters(0),
      fname(name),
      fmcType(kPTIon),
      fmass(0),
      fcharge(0),
      fDecayTime(decaytime),
      fpType("Ion"),
      fwidth(0),
      fiSpin(0),
      fiParity(0),
      fiConjugation(0),
      fiIsospin(0),
      fiIsospinZ(0),
      fgParity(0),
      flepton(0),
      fbaryon(0),
      fstable(stable)
 {
   TDatabasePDG* pdgDB = TDatabasePDG::Instance();
   if (!pdgDB->GetParticle(fpdg)) {
     if(mass == 0 ) {
       TParticlePDG* kProton = pdgDB->GetParticle(2212);
       Double_t kProtonMass=kProton->Mass();
       mass = a*kProtonMass;
     }
     pdgDB->AddParticle(name, name, mass, stable, 0, q, "kPTHadron", fpdg);
   }
   fParticle = new TParticle();
   fParticle->SetPdgCode(fpdg);
   fmcType= kPTHadron;
   fmass= mass;
   fcharge= fParticle->GetPDG()->Charge();
   fDecayTime=decaytime ;
   fwidth=   fParticle->GetPDG()->Width();
   fiSpin=   (Int_t)fParticle->GetPDG()->Spin();
   fiParity=  fParticle->GetPDG()->Parity();
   fiConjugation= 0;
   fiIsospin= (Int_t) fParticle->GetPDG()->Isospin();
   fiIsospinZ= 0;
   fgParity= 0;
   flepton=  0;
   fbaryon=  0;
   fstable= fParticle->GetPDG()->Stable();
 }
FairParticle::FairParticle (const char * name, Int_t z, Int_t a, Double_t mass, Int_t q, Bool_t stable, Double_t decaytime)
Definition at line 114 of file FairParticle.cxx.
References fbaryon, fcharge, fDecayTime, fgParity, fiConjugation, fiIsospin, fiIsospinZ, fiParity, fiSpin, flepton, fmass, fmcType, fParticle, fpdg, fstable, and fwidth.
   :  TObject(),
      fpdg(10000000+10000* z +10 * a),
      fParticle(0),
      fMother(0),
      fDaughters(0),
      fname(name),
      fmcType(kPTIon),
      fmass(0),
      fcharge(0),
      fDecayTime(decaytime),
      fpType("Ion"),
      fwidth(0),
      fiSpin(0),
      fiParity(0),
      fiConjugation(0),
      fiIsospin(0),
      fiIsospinZ(0),
      fgParity(0),
      flepton(0),
      fbaryon(0),
      fstable(stable)
 {
   //  fpdg= 10000000+10000* z +10 * a;
   //  fDecayTime= decaytime;
   TDatabasePDG* pdgDB = TDatabasePDG::Instance();
   if (!pdgDB->GetParticle(fpdg)) {
     if(mass == 0 ) {
       TParticlePDG* kProton = pdgDB->GetParticle(2212);
       Double_t kProtonMass=kProton->Mass();
       mass = a*kProtonMass;
     }
     pdgDB->AddParticle(name, name, mass, stable, 0, q, "kPTHadron", fpdg);
   }
   fParticle = new TParticle();
   fParticle->SetPdgCode(fpdg);
   fmcType= kPTHadron;
   fmass= mass;
   fcharge= fParticle->GetPDG()->Charge();
   fDecayTime=decaytime ;
   fwidth=   fParticle->GetPDG()->Width();
   fiSpin=   (Int_t)fParticle->GetPDG()->Spin();
   fiParity=  fParticle->GetPDG()->Parity();
   fiConjugation= 0;
   fiIsospin= (Int_t) fParticle->GetPDG()->Isospin();
   fiIsospinZ= 0;
   fgParity= 0;
   flepton=  0;
   fbaryon=  0;
   fstable= fParticle->GetPDG()->Stable();
 }
FairParticle::FairParticle (Int_t pdg, const TString name, TMCParticleType mcType, Double_t mass, Double_t charge, Double_t lifetime, const TString pType = "Ion", Double_t width = 0, Int_t iSpin = 0, Int_t iParity = 0, Int_t iConjugation = 0, Int_t iIsospin = 0, Int_t iIsospinZ = 0, Int_t gParity = 0, Int_t lepton = 0, Int_t baryon = 0, Bool_t stable = kFALSE)
Definition at line 202 of file FairParticle.cxx.
References fcharge, fmass, fname, fParticle, fpdg, fstable, fwidth, and GetParticle().
   : TObject(),
     fpdg  (pdg),
     fParticle( new TParticle()),
     fMother(0),
     fDaughters(0),
     fname(name),
     fmcType (mcType),
     fmass  (mass),
     fcharge( charge),
     fDecayTime( lifetime),
     fpType(   pType),
     fwidth(   width),
     fiSpin(  iSpin),
     fiParity(   iParity),
     fiConjugation( iConjugation),
     fiIsospin(   iIsospin),
     fiIsospinZ(  iIsospinZ),
     fgParity( gParity),
     flepton(  lepton),
     fbaryon(  baryon),
     fstable(  stable)
 {
   if (!TDatabasePDG::Instance()->GetParticle(fpdg)) {
     TDatabasePDG::Instance()
     ->AddParticle(fname, fname, fmass, fstable, fwidth,fcharge ,pType, fpdg);
   }
   fParticle->SetPdgCode(fpdg);
 }
FairParticle::FairParticle ()
Definition at line 253 of file FairParticle.cxx.
   : TObject(),
     fpdg(0),
     fParticle(0),
     fMother(0),
     fDaughters(),
     fname("ion"),
     fmcType (kPTIon),
     fmass  (0),
     fcharge(0),
     fDecayTime(0),
     fpType("Ion"),
     fwidth(0),
     fiSpin(0),
     fiParity(0),
     fiConjugation(0),
     fiIsospin(0),
     fiIsospinZ(0),
     fgParity(0),
     flepton(0),
     fbaryon(0),
     fstable(kTRUE)
 {
 //
 }
FairParticle::~FairParticle () virtual
Definition at line 280 of file FairParticle.cxx.
References fParticle.
 {
 //
   delete fParticle;
 }
FairParticle::FairParticle (const FairParticle & P) private
Member Function Documentation
void FairParticle::AddDaughter (FairParticle * particle)
Definition at line 300 of file FairParticle.cxx.
References fDaughters.
 {
 // Adds particles daughter
 // ---
   fDaughters.Add(particle);
 }
Int_t FairParticle::GetBaryon () inline
Definition at line 69 of file FairParticle.h.
References fbaryon.
Referenced by FairMCApplication::AddParticles().
 {return fbaryon;}
Double_t FairParticle::GetCharge () inline
Definition at line 58 of file FairParticle.h.
References fcharge.
Referenced by FairMCApplication::AddParticles().
 {return fcharge;}
Int_t FairParticle::GetConjugation () inline
Definition at line 64 of file FairParticle.h.
References fiConjugation.
Referenced by FairMCApplication::AddParticles().
 {return fiConjugation;}
FairParticle * FairParticle::GetDaughter (Int_t i) const
Definition at line 380 of file FairParticle.cxx.
References fDaughters, and GetNofDaughters().
Referenced by PrintDaughters().
 {
 // Returns i-th daughter.
 // ---
   if (i < 0 || i >= GetNofDaughters()) {
     Fatal("GetDaughter", "Index out of range");
   }
   return (FairParticle*) fDaughters.At(i);
 }
Double_t FairParticle::GetDecayTime () inline
Definition at line 59 of file FairParticle.h.
References fDecayTime.
Referenced by FairMCApplication::AddParticles().
 {return fDecayTime;}
Int_t FairParticle::GetgParity () inline
Definition at line 67 of file FairParticle.h.
References fgParity.
Referenced by FairMCApplication::AddParticles().
 {return fgParity;}
Int_t FairParticle::GetiParity () inline
Definition at line 63 of file FairParticle.h.
References fiParity.
Referenced by FairMCApplication::AddParticles().
 {return fiParity;}
Int_t FairParticle::GetIsospin () inline
Definition at line 65 of file FairParticle.h.
References fiIsospin.
Referenced by FairMCApplication::AddParticles().
 {return fiIsospin;}
Int_t FairParticle::GetIsospinZ () inline
Definition at line 66 of file FairParticle.h.
References fiIsospinZ.
Referenced by FairMCApplication::AddParticles().
 {return fiIsospinZ;}
Int_t FairParticle::GetLepton () inline
Definition at line 68 of file FairParticle.h.
References flepton.
Referenced by FairMCApplication::AddParticles().
 {return flepton;}
Double_t FairParticle::GetMass () inline
Definition at line 57 of file FairParticle.h.
References fmass.
Referenced by FairMCApplication::AddParticles().
 {return fmass;}
TMCParticleType FairParticle::GetMCType () inline
Definition at line 56 of file FairParticle.h.
References fmcType.
Referenced by FairMCApplication::AddParticles().
 {return fmcType;}
FairParticle * FairParticle::GetMother () const
Definition at line 362 of file FairParticle.cxx.
References fMother.
Referenced by Print().
 {
 // Returns particle definition (TParticle).
 // ---
   return (FairParticle*) fMother.GetObject();
 }
virtual const char* FairParticle::GetName () const inline virtual
Definition at line 55 of file FairParticle.h.
References fname.
Referenced by FairMCApplication::AddParticles().
 {return fname.Data();}
Int_t FairParticle::GetNofDaughters () const
Definition at line 371 of file FairParticle.cxx.
References fDaughters.
Referenced by GetDaughter(), Print(), and PrintDaughters().
 {
 // Returns number of daughters.
 // ---
   return fDaughters.GetEntriesFast();
 }
TParticle * FairParticle::GetParticle () const
Definition at line 353 of file FairParticle.cxx.
References fParticle.
Referenced by FairIonGenerator::FairIonGenerator(), FairParticle(), and Print().
 {
 // Returns particle definition (TParticle).
 // ---
   return fParticle;
 }
Int_t FairParticle::GetPDG () const
Definition at line 343 of file FairParticle.cxx.
References fpdg.
Referenced by FairMCApplication::AddParticles(), and Print().
 {
 // Returs particle ID.
 // ---
   return fpdg;
 }
const TString& FairParticle::GetPType () inline
Definition at line 60 of file FairParticle.h.
References fpType.
Referenced by FairMCApplication::AddParticles().
 {return fpType;}
Int_t FairParticle::GetSpin () inline
Definition at line 62 of file FairParticle.h.
References fiSpin.
Referenced by FairMCApplication::AddParticles().
 {return fiSpin;}
Double_t FairParticle::GetWidth () inline
Definition at line 61 of file FairParticle.h.
References fwidth.
Referenced by FairMCApplication::AddParticles().
 {return fwidth;}
Bool_t FairParticle::IsStable () inline
Definition at line 70 of file FairParticle.h.
References fstable.
Referenced by FairMCApplication::AddParticles().
 {return fstable;}
FairParticle& FairParticle::operator= (const FairParticle &) inline private
Definition at line 75 of file FairParticle.h.
 {return *this;}
void FairParticle::Print (Option_t * option = "") const virtual
Definition at line 309 of file FairParticle.cxx.
References fParticle, fpdg, GetMother(), GetNofDaughters(), GetParticle(), and GetPDG().
Referenced by PrintDaughters().
 {
 // Prints particle properties.
 // ---
 //  return;
   cout << "Particle: " << fParticle->GetName()  << "  with ID:  " << fpdg << endl;
   // fParticle->Print();
   if (GetMother()) {
     cout << "Mother:    " << GetMother()->GetParticle()->GetName()
          << "  with ID: " << GetMother()->GetPDG() << endl;
   } else {
     cout << "Primary    " << endl;
   }
   cout << "Number of daughters: " << GetNofDaughters() << endl;
   cout << endl;
 }
void FairParticle::PrintDaughters () const
Definition at line 331 of file FairParticle.cxx.
References GetDaughter(), GetNofDaughters(), and Print().
 {
 // Prints particles daughters.
 // ---
   for (Int_t i=0; i<GetNofDaughters(); i++)  {
     cout << i << "th daughter: " << endl;
     GetDaughter(i)->Print();
   }
 }
void FairParticle::SetMother (FairParticle * particle)
Definition at line 291 of file FairParticle.cxx.
References fMother.
 {
 // Adds particles daughter
 // ---
   fMother.SetObject(particle);
 }
Member Data Documentation
Int_t FairParticle::fbaryon private
Definition at line 95 of file FairParticle.h.
Referenced by FairParticle(), and GetBaryon().
Double_t FairParticle::fcharge private
Definition at line 84 of file FairParticle.h.
Referenced by FairParticle(), and GetCharge().
TRefArray FairParticle::fDaughters private
Definition at line 80 of file FairParticle.h.
Referenced by AddDaughter(), GetDaughter(), and GetNofDaughters().
Double_t FairParticle::fDecayTime private
Definition at line 85 of file FairParticle.h.
Referenced by FairParticle(), and GetDecayTime().
Int_t FairParticle::fgParity private
Definition at line 93 of file FairParticle.h.
Referenced by FairParticle(), and GetgParity().
Int_t FairParticle::fiConjugation private
Definition at line 90 of file FairParticle.h.
Referenced by FairParticle(), and GetConjugation().
Int_t FairParticle::fiIsospin private
Definition at line 91 of file FairParticle.h.
Referenced by FairParticle(), and GetIsospin().
Int_t FairParticle::fiIsospinZ private
Definition at line 92 of file FairParticle.h.
Referenced by FairParticle(), and GetIsospinZ().
Int_t FairParticle::fiParity private
Definition at line 89 of file FairParticle.h.
Referenced by FairParticle(), and GetiParity().
Int_t FairParticle::fiSpin private
Definition at line 88 of file FairParticle.h.
Referenced by FairParticle(), and GetSpin().
Int_t FairParticle::flepton private
Definition at line 94 of file FairParticle.h.
Referenced by FairParticle(), and GetLepton().
Double_t FairParticle::fmass private
Definition at line 83 of file FairParticle.h.
Referenced by FairParticle(), and GetMass().
TMCParticleType FairParticle::fmcType private
Definition at line 82 of file FairParticle.h.
Referenced by FairParticle(), and GetMCType().
TRef FairParticle::fMother private
Definition at line 79 of file FairParticle.h.
Referenced by GetMother(), and SetMother().
const TString FairParticle::fname private
Definition at line 81 of file FairParticle.h.
Referenced by FairParticle(), and GetName().
TParticle* FairParticle::fParticle private
Definition at line 78 of file FairParticle.h.
Referenced by FairParticle(), GetParticle(), Print(), and ~FairParticle().
Int_t FairParticle::fpdg private
Definition at line 77 of file FairParticle.h.
Referenced by FairParticle(), GetPDG(), and Print().
const TString FairParticle::fpType private
Definition at line 86 of file FairParticle.h.
Referenced by GetPType().
Bool_t FairParticle::fstable private
Definition at line 96 of file FairParticle.h.
Referenced by FairParticle(), and IsStable().
Double_t FairParticle::fwidth private
Definition at line 87 of file FairParticle.h.
Referenced by FairParticle(), and GetWidth().
The documentation for this class was generated from the following files:
FairParticle.h
FairParticle.cxx