FairRroot: MyRingSorter Class Reference
MyRingSorter Class Reference
#include <MyRingSorter.h>
Public Member Functions
MyRingSorter (int size=100, double width=10)
virtual ~MyRingSorter ()
virtual FairTimeStamp * CreateElement (FairTimeStamp *data)
ClassDef (MyRingSorter, 1)
virtual void AddElement (FairTimeStamp *digi, double timestamp)
virtual void WriteOutElements (int index)
writes out the entries from LowerBoundPointer up to index
virtual void WriteOutElement (int index)
writes out the entry at the index and clears it
virtual void WriteOutAll ()
virtual double GetBufferSize ()
virtual std::vector
< FairTimeStamp * > GetOutputData ()
virtual void DeleteOutputData ()
virtual void SetLowerBound (double timestampOfHitToWrite)
virtual void print (std::ostream &out=std::cout)
Detailed Description
Definition at line 20 of file MyRingSorter.h.
Constructor & Destructor Documentation
MyRingSorter::MyRingSorter (int size = 100, double width = 10) inline
Definition at line 23 of file MyRingSorter.h.
       : FairRingSorter(size, width) {};
MyRingSorter::~MyRingSorter () virtual
Definition at line 18 of file MyRingSorter.cxx.
 {
 }
Member Function Documentation
void FairRingSorter::AddElement (FairTimeStamp * digi, double timestamp) virtual inherited
Definition at line 23 of file FairRingSorter.cxx.
References FairRingSorter::CalcIndex(), FairRingSorter::CreateElement(), FairRingSorter::fLowerBoundPointer, FairRingSorter::fRingBuffer, FairRingSorter::fVerbose, FairRingSorter::GetBufferSize(), FairTimeStamp::Print(), FairRingSorter::SetLowerBound(), FairRingSorter::WriteOutAll(), and FairRingSorter::WriteOutElements().
Referenced by FairRingSorterTask::Exec(), and FairRingSorterTask::FinishTask().
 {
   FairTimeStamp* newElement = CreateElement(digi);
   if (timestamp < fLowerBoundPointer.second) {
     std::cout << "-E- Timestamp " << timestamp << " below lower bound " << fLowerBoundPointer.second << std::endl;
     newElement->Print();
     return;
   }
   int index = CalcIndex(timestamp);
   if (timestamp >= fLowerBoundPointer.second + (2 * GetBufferSize())) {
     if (fVerbose > 0) {
       std::cout << "-I- FairRingSorterT::AddElement : Timestamp "
                 << timestamp << " larger than 2 * bufferspace: " << fLowerBoundPointer.second + GetBufferSize() << " writing out " << index+1 << std::endl;
     }
     WriteOutAll();
     SetLowerBound(timestamp);
   } else if (timestamp >= fLowerBoundPointer.second + GetBufferSize()) {
     if (fVerbose > 0) {
       std::cout << "-I- FairRingSorterT::AddElement :Timestamp "
                 << timestamp << " larger than bufferspace: "
                 << fLowerBoundPointer.second + GetBufferSize() << " writing out " << index+1 << std::endl;
     }
     WriteOutElements(index+1);
     SetLowerBound(timestamp);
   }
   fRingBuffer[index].insert(std::pair<double, FairTimeStamp*> (timestamp, newElement));
 }
MyRingSorter::ClassDef (MyRingSorter , 1)
FairTimeStamp * MyRingSorter::CreateElement (FairTimeStamp * data) virtual
Reimplemented from FairRingSorter.
Definition at line 22 of file MyRingSorter.cxx.
 {
   return new MyDataClass(*(MyDataClass*)data);
 }
virtual void FairRingSorter::DeleteOutputData () inline virtual inherited
Definition at line 54 of file FairRingSorter.h.
References FairRingSorter::fOutputData.
Referenced by FairRingSorterTask::Exec(), and FairRingSorterTask::FinishTask().
 {fOutputData.clear(); }
virtual double FairRingSorter::GetBufferSize () inline virtual inherited
Definition at line 49 of file FairRingSorter.h.
References FairRingSorter::fCellWidth, and FairRingSorter::fRingBuffer.
Referenced by FairRingSorter::AddElement(), and FairRingSorter::SetLowerBound().
 {return fCellWidth * fRingBuffer.size();}
virtual std::vector<FairTimeStamp*> FairRingSorter::GetOutputData () inline virtual inherited
Definition at line 50 of file FairRingSorter.h.
References FairRingSorter::fOutputData.
Referenced by FairRingSorterTask::Exec(), and FairRingSorterTask::FinishTask().
{
       return fOutputData;
     }
virtual void FairRingSorter::print (std::ostream & out = std::cout) inline virtual inherited
Definition at line 57 of file FairRingSorter.h.
References FairRingSorter::fCellWidth, FairRingSorter::fLowerBoundPointer, and FairRingSorter::fRingBuffer.
{
       out << "RingSorter: Size " << fRingBuffer.size() << " CellWidth: " << fCellWidth << std::endl;
       out << "LowerBoundPointer at index: " << fLowerBoundPointer.first << " Time: " << fLowerBoundPointer.second << std::endl;
       out << "| ";
       for (int i = 0; i < fRingBuffer.size(); i++) {
         out << fRingBuffer[i].size() << " |";
       }
       out << std::endl;
     }
void FairRingSorter::SetLowerBound (double timestampOfHitToWrite) virtual inherited
Definition at line 52 of file FairRingSorter.cxx.
References FairRingSorter::CalcIndex(), FairRingSorter::fCellWidth, FairRingSorter::fLowerBoundPointer, FairRingSorter::fVerbose, and FairRingSorter::GetBufferSize().
Referenced by FairRingSorter::AddElement().
 {
   int index = CalcIndex(timestampOfHitToWrite + fCellWidth);
   int cellValue = (int)(timestampOfHitToWrite / fCellWidth);
   fLowerBoundPointer.second = ((cellValue + 1) * fCellWidth) - GetBufferSize();
   fLowerBoundPointer.first = index;
   if (fVerbose > 0) { std::cout << "-I- FairRingSorter::SetLowerBound " << index << " / " << fLowerBoundPointer.second << std::endl; }
 }
virtual void FairRingSorter::WriteOutAll () inline virtual inherited
Definition at line 46 of file FairRingSorter.h.
References FairRingSorter::fLowerBoundPointer, and FairRingSorter::WriteOutElements().
Referenced by FairRingSorter::AddElement(), and FairRingSorterTask::FinishTask().
{
       WriteOutElements(fLowerBoundPointer.first);
     }
void FairRingSorter::WriteOutElement (int index) virtual inherited
writes out the entry at the index and clears it
Definition at line 87 of file FairRingSorter.cxx.
References FairRingSorter::fOutputData, FairRingSorter::fRingBuffer, and FairRingSorter::fVerbose.
Referenced by FairRingSorter::WriteOutElements().
 {
   std::multimap<double, FairTimeStamp*>* myDataField = &fRingBuffer.at(index);
   std::multimap<double, FairTimeStamp*>::iterator it;
   if (!myDataField->empty()) {
     if (fVerbose > 1) { ; }
     std::cout << "-I- FairRingSorterT:WriteOutElement ";
     myDataField->begin()->second->Print();
     std::cout << std::endl;
     for (it = myDataField->begin(); it != myDataField->end(); it++) {
       fOutputData.push_back(it->second);
     }
     myDataField->clear();
   }
 }
void FairRingSorter::WriteOutElements (int index) virtual inherited
writes out the entries from LowerBoundPointer up to index
Definition at line 63 of file FairRingSorter.cxx.
References FairRingSorter::fLowerBoundPointer, FairRingSorter::fOutputData, FairRingSorter::fRingBuffer, FairRingSorter::fVerbose, and FairRingSorter::WriteOutElement().
Referenced by FairRingSorter::AddElement(), and FairRingSorter::WriteOutAll().
 {
   if (fLowerBoundPointer.first >= index) {
     for (int i = fLowerBoundPointer.first; i < fRingBuffer.size(); i++) {
       WriteOutElement(i);
     }
     for (int i = 0; i < index; i++) {
       WriteOutElement(i);
     }
   } else {
     for (int i = fLowerBoundPointer.first; i < index; i++) {
       WriteOutElement(i);
     }
   }
   if (fVerbose > 1) {
     std::cout << "-I- FairRingSorter::WriteOutElements: Size of Output-Array: " << fOutputData.size() << std::endl;
     for (int i = 0; i < fOutputData.size(); i++) {
       fOutputData[i]->Print();
       std::cout << " | ";
     }
     std::cout << std::endl;
   }
 }
The documentation for this class was generated from the following files:
MyRingSorter.h
MyRingSorter.cxx