FairRroot: FairParamList Class Reference
FairParamList Class Reference
#include <FairParamList.h>
Classes
class FairParamTFile
Public Member Functions
FairParamList ()
~FairParamList ()
void add (FairParamObj &)
void add (const Text_t *, const Text_t *)
void add (const Text_t *, Int_t)
void add (const Text_t *, Float_t)
void add (const Text_t *, Double_t)
void add (const Text_t *, TArrayI &)
void add (const Text_t *, TArrayC &)
void add (const Text_t *, TArrayF &)
void add (const Text_t *, TArrayD &)
void add (const Text_t *, const UChar_t *, const Int_t)
void add (const Text_t *, const Int_t *, const Int_t)
void add (const Text_t *, const Float_t *, const Int_t)
void add (const Text_t *, const Double_t *, const Int_t)
void addObject (const Text_t *, TObject *)
Bool_t fill (const Text_t *, Text_t *, const Int_t)
Bool_t fill (const Text_t *, Int_t *, const Int_t nValues=1)
Bool_t fill (const Text_t *, Float_t *, const Int_t nValues=1)
Bool_t fill (const Text_t *, Double_t *, const Int_t nValues=1)
Bool_t fill (const Text_t *, UChar_t *, const Int_t nValues=1)
Bool_t fill (const Text_t *, TArrayI *)
Bool_t fill (const Text_t *, TArrayC *)
Bool_t fill (const Text_t *, TArrayF *)
Bool_t fill (const Text_t *, TArrayD *)
Bool_t fillObject (const Text_t *, TObject *)
void print ()
FairParamObj * find (const Text_t *name)
TList * getList ()
Protected Attributes
TList * paramList
FairLogger * fLogger
Private Member Functions
FairParamList (const FairParamList &)
FairParamList & operator= (const FairParamList &)
Detailed Description
Definition at line 77 of file FairParamList.h.
Constructor & Destructor Documentation
FairParamList::FairParamList ()
Definition at line 435 of file FairParamList.cxx.
   :TObject(),
    paramList(new TList()),
    fLogger(FairLogger::GetLogger())
 {
   // Constructor
   //  paramList=new TList;
 }
FairParamList::~FairParamList ()
Definition at line 444 of file FairParamList.cxx.
References paramList.
 {
   // Destructor
   if (paramList) {
     paramList->Delete();
     delete paramList;
     paramList=0;
   }
 }
FairParamList::FairParamList (const FairParamList &) private
Member Function Documentation
void FairParamList::add (FairParamObj & p)
Definition at line 454 of file FairParamList.cxx.
References paramList.
Referenced by FairTutorialDet4MisalignPar::putParams(), FairConstPar::putParams(), MyFieldPar::putParams(), FairBaseParSet::putParams(), FairDbTutPar2::putParams(), FairDbTutPar::putParams(), FairTutorialDet2DigiPar::putParams(), and FairDbTutParBin::putParams().
 {
   // Adds a FairParamObj object to the list
   paramList->Add(new FairParamObj(p));
 }
void FairParamList::add (const Text_t * name, const Text_t * value)
Definition at line 460 of file FairParamList.cxx.
References paramList.
 {
   // Adds a string parameter to the list
   // name  = name of the parameter
   // value = string value
   paramList->Add(new FairParamObj(name,value));
 }
void FairParamList::add (const Text_t * name, Int_t value)
Definition at line 468 of file FairParamList.cxx.
References paramList.
 {
   // Adds a parameter of type Int_t to the list
   paramList->Add(new FairParamObj(name,value));
 }
void FairParamList::add (const Text_t * name, Float_t value)
Definition at line 474 of file FairParamList.cxx.
References paramList.
 {
   // Adds a parameter of type Float_t to the list
   paramList->Add(new FairParamObj(name,value));
 }
void FairParamList::add (const Text_t * name, Double_t value)
Definition at line 480 of file FairParamList.cxx.
References paramList.
 {
   // Adds a parameter of type Double_t to the list
   paramList->Add(new FairParamObj(name,value));
 }
void FairParamList::add (const Text_t * name, TArrayI & value)
Definition at line 486 of file FairParamList.cxx.
References paramList.
 {
   // Adds a parameter of type TArrayI to the list
   paramList->Add(new FairParamObj(name,value.GetArray(),value.GetSize()));
 }
void FairParamList::add (const Text_t * name, TArrayC & value)
Definition at line 492 of file FairParamList.cxx.
References paramList.
 {
   // Adds a parameter of type TArrayC  to the list
   paramList->Add(new FairParamObj(name,value.GetArray(),value.GetSize()));
 }
void FairParamList::add (const Text_t * name, TArrayF & value)
Definition at line 498 of file FairParamList.cxx.
References paramList.
 {
   // Adds a parameter of type TArrayF to the list
   paramList->Add(new FairParamObj(name,value.GetArray(),value.GetSize()));
 }
void FairParamList::add (const Text_t * name, TArrayD & value)
Definition at line 504 of file FairParamList.cxx.
References paramList.
 {
   // Adds a parameter of type TArrayD to the list
   paramList->Add(new FairParamObj(name,value.GetArray(),value.GetSize()));
 }
void FairParamList::add (const Text_t * name, const UChar_t * values, const Int_t nValues)
Definition at line 510 of file FairParamList.cxx.
References paramList.
 {
   // Adds a binary array of size nValues to the list
   paramList->Add(new FairParamObj(name,values,nValues));
 }
void FairParamList::add (const Text_t * name, const Int_t * values, const Int_t nValues)
Definition at line 516 of file FairParamList.cxx.
References paramList.
 {
   // Adds an array of type Int_t and of size nValues as binary to the list
   paramList->Add(new FairParamObj(name,values,nValues));
 }
void FairParamList::add (const Text_t * name, const Float_t * values, const Int_t nValues)
Definition at line 522 of file FairParamList.cxx.
References paramList.
 {
   // Adds an array of type Float_t and of size nValues as binary to the list
   paramList->Add(new FairParamObj(name,values,nValues));
 }
void FairParamList::add (const Text_t * name, const Double_t * values, const Int_t nValues)
Definition at line 528 of file FairParamList.cxx.
References paramList.
 {
   // Adds an array of type Double_t and of size nValues as binary to the list
   paramList->Add(new FairParamObj(name,values,nValues));
 }
void FairParamList::addObject (const Text_t * name, TObject * obj)
Definition at line 534 of file FairParamList.cxx.
References buffer, paramList, FairParamObj::setClassVersion(), FairParamObj::setParamType(), FairParamObj::setParamValue(), and FairParamObj::setStreamerInfo().
Referenced by FairGeoPassivePar::putParams(), NewDetectorGeoPar::putParams(), FairTutorialDet2GeoPar::putParams(), FairTestDetectorGeoPar::putParams(), FairTutorialDet4GeoPar::putParams(), FairRutherfordGeoPar::putParams(), FairTutorialDet1GeoPar::putParams(), FairGeoParSet::putParams(), and FairBaseParSet::putParams().
 {
   // Adds a TObject to the list, sets the class version and the streamer info for
   // ROOT classes
   if (!obj) { return; }
   FairParamObj* o=new FairParamObj(name);
   o->setParamType(obj->IsA()->GetName());
   o->setClassVersion(obj->IsA()->GetClassVersion());
   TFile* filesave=gFile;
   FairParamTFile* paramFile=new FairParamTFile();
   gFile=paramFile;
   const Int_t bufsize=10000;
   TBufferFile* buffer=new TBufferFile(TBuffer::kWrite,bufsize);
   buffer->SetParent(paramFile);
   buffer->MapObject(obj);
   obj->Streamer(*buffer);
   Int_t len=buffer->Length();
   Char_t* buf=new char[len];
   memcpy(buf,buffer->Buffer(),len);
   o->setParamValue((UChar_t*)buf,len);
   TArrayC* fClassIndex=paramFile->GetClassIndex();
   if (fClassIndex&&fClassIndex->fArray[0] != 0) {
     TIter next(gROOT->GetListOfStreamerInfo());
     TStreamerInfo* info;
     TList list;
     while ((info=(TStreamerInfo*)next())) {
       Int_t uid=info->GetNumber();
       if (fClassIndex->fArray[uid]) { list.Add(info); }
     }
     if (list.GetSize()>0) {
       list.Sort();
       fClassIndex->fArray[0]=2; //to prevent adding classes in TStreamerInfo::TagFile
       TBufferFile* infoBuffer=new TBufferFile(TBuffer::kWrite,bufsize);
       infoBuffer->MapObject(&list);
       list.Streamer(*infoBuffer);
       Int_t infolen=infoBuffer->Length();
       Char_t* infobuf=new char[infolen];
       memcpy(infobuf,infoBuffer->Buffer(),infolen);
       o->setStreamerInfo((UChar_t*)infobuf,infolen);
       delete infoBuffer;
     } else {
       o->setStreamerInfo(0,0);
     }
   }
   fClassIndex->fArray[0]=0;
   delete paramFile;
   paramList->Add(o);
   delete buffer;
   gFile=filesave;
 }
Bool_t FairParamList::fill (const Text_t * name, Text_t * value, const Int_t length)
Definition at line 597 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
Referenced by FairTutorialDet4MisalignPar::getParams(), FairConstPar::getParams(), MyFieldPar::getParams(), FairDbTutPar2::getParams(), FairDbTutPar::getParams(), FairBaseParSet::getParams(), FairTutorialDet2DigiPar::getParams(), and FairDbTutParBin::getParams().
 {
   // Copies the data from the list object into the parameter value of type string
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (value==0) { return kFALSE; }
   if (o!=0 && strcmp(o->getParamType(),"Text_t")==0) {
     Int_t l=o->getLength();
     if (l<length-1) {
       memcpy(value,(Char_t*)o->getParamValue(),l);
       value[l]='\0';
       return kTRUE;
     } else {
       fLogger->Error(MESSAGE_ORIGIN,"char array too small");
       //      Error("FairParamList::fill(const Text_t*,Text_t*)","char array too small");
     }
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fill (const Text_t * name, Int_t * values, const Int_t nValues = 1)
Definition at line 641 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getNumParams(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
 {
   // Copies the data from the list object into the parameter array of type Int_t.
   // The function returns an error, if the array size of the list object is not equal
   // to nValues.
   if (values==0) { return kFALSE; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),"Int_t")==0) {
     Int_t l=o->getLength();
     Int_t n=o->getNumParams();
     if (n==nValues) {
       memcpy(values,o->getParamValue(),l);
       return kTRUE;
     } else {
       fLogger->Error(MESSAGE_ORIGIN,"Different array sizes for parameter %s",name);
       //      Error("FairParamList::fill \nDifferent array sizes for parameter %s",name);
       return kFALSE;
     }
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fill (const Text_t * name, Float_t * values, const Int_t nValues = 1)
Definition at line 665 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getNumParams(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
 {
   // Copies the data from the list object into the parameter array of type Float_t.
   // The function returns an error, if the array size of the list object is not equal
   // to nValues.
   if (values==0) { return kFALSE; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),"Float_t")==0) {
     Int_t l=o->getLength();
     Int_t n=o->getNumParams();
     if (n==nValues) {
       memcpy(values,o->getParamValue(),l);
       return kTRUE;
     } else {
       fLogger->Error(MESSAGE_ORIGIN,"Different array sizes for parameter %s",name);
       //      Error("FairParamList::fill \nDifferent array sizes for parameter %s",name);
       return kFALSE;
     }
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fill (const Text_t * name, Double_t * values, const Int_t nValues = 1)
Definition at line 689 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getNumParams(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
 {
   // Copies the data from the list object into the parameter array of type Double_t.
   // The function returns an error, if the array size of the list object is not equal
   // to nValues.
   if (values==0) { return kFALSE; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),"Double_t")==0) {
     Int_t l=o->getLength();
     Int_t n=o->getNumParams();
     if (n==nValues) {
       memcpy(values,o->getParamValue(),l);
       return kTRUE;
     } else {
       fLogger->Error(MESSAGE_ORIGIN,"Different array sizes for parameter %s",name);
       //      Error("FairParamList::fill \nDifferent array sizes for parameter %s",name);
       return kFALSE;
     }
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fill (const Text_t * name, UChar_t * values, const Int_t nValues = 1)
Definition at line 618 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
 {
   // Copies the data from the list object into the parameter array of type UChar_t of size nValues.
   // The function returns an error, if the array size of the list object is not equal
   // to nValues.
   if (values==0) { return kFALSE; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),"UChar_t")==0) {
     Int_t n=o->getLength();
     if (n==nValues) {
       memcpy(values,o->getParamValue(),n);
       return kTRUE;
     } else {
       fLogger->Error(MESSAGE_ORIGIN,"Different array sizes for parameter %s",name);
       //      Error("FairParamList::fill \nDifferent array sizes for parameter %s",name);
       return kFALSE;
     }
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fill (const Text_t * name, TArrayI * value)
Definition at line 713 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getNumParams(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
 {
   // Copies the data from the list object into the parameter value of type TArrayI
   // The array is resized, if the number of data is different.
   if (value==0) { return kFALSE; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),"Int_t")==0) {
     Int_t l=o->getLength();
     Int_t n=o->getNumParams();
     if (value->GetSize()!=n) { value->Set(n); }
     memcpy(value->GetArray(),o->getParamValue(),l);
     return kTRUE;
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fill (const Text_t * name, TArrayC * value)
Definition at line 731 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
 {
   // Copies the data from the list object into the parameter value of type TArrayC
   // The array is resized, if the number of data is different.
   if (value==0) { return kFALSE; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),"Char_t")==0) {
     Int_t l=o->getLength();
     if (value->GetSize()!=l) { value->Set(l); }
     memcpy(value->GetArray(),o->getParamValue(),l);
     return kTRUE;
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fill (const Text_t * name, TArrayF * value)
Definition at line 748 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getNumParams(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
 {
   // Copies the data from the list object into the parameter value of type TArrayF
   // The array is resized, if the number of data is different.
   if (value==0) { return kFALSE; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),"Float_t")==0) {
     Int_t l=o->getLength();
     Int_t n=o->getNumParams();
     if (value->GetSize()!=n) { value->Set(n); }
     memcpy(value->GetArray(),o->getParamValue(),l);
     return kTRUE;
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fill (const Text_t * name, TArrayD * value)
Definition at line 766 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getLength(), FairParamObj::getNumParams(), FairParamObj::getParamType(), FairParamObj::getParamValue(), MESSAGE_ORIGIN, and paramList.
 {
   // Copies the data from the list object into the parameter value of type TArrayD
   // The array is resized, if the number of data is different.
   if (value==0) { return kFALSE; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),"Double_t")==0) {
     Int_t l=o->getLength();
     Int_t n=o->getNumParams();
     if (value->GetSize()!=n) { value->Set(n); }
     memcpy(value->GetArray(),o->getParamValue(),l);
     return kTRUE;
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return kFALSE;
 }
Bool_t FairParamList::fillObject (const Text_t * name, TObject * obj)
Definition at line 784 of file FairParamList.cxx.
References FairLogger::Error(), fLogger, FairParamObj::getClassVersion(), FairParamObj::getLength(), FairParamObj::getParamType(), FairParamObj::getParamValue(), FairParamObj::getStreamerInfo(), FairParamObj::getStreamerInfoSize(), MESSAGE_ORIGIN, paramList, and FairLogger::Warning().
Referenced by FairGeoPassivePar::getParams(), NewDetectorGeoPar::getParams(), FairTutorialDet2GeoPar::getParams(), FairTestDetectorGeoPar::getParams(), FairTutorialDet4GeoPar::getParams(), FairRutherfordGeoPar::getParams(), FairTutorialDet1GeoPar::getParams(), FairGeoParSet::getParams(), and FairBaseParSet::getParams().
 {
   // Fills the object obj (must exist!) via the Streamer and returns the class version.
   // Prints a warning if the class version in the list objects differs from the actual
   // class version.
   if (!obj) { return 0; }
   FairParamObj* o=(FairParamObj*)paramList->FindObject(name);
   if (o!=0 && strcmp(o->getParamType(),obj->IsA()->GetName())==0) {
     if (o->getClassVersion()!=obj->IsA()->GetClassVersion()) {
       fLogger->Warning(MESSAGE_ORIGIN,"Read Class Version = %i does not match actual version = %i",o->getClassVersion(),obj->IsA()->GetClassVersion());
     }
     //      Warning("FairParamList::fill",
     //              "\n       Read Class Version = %i does not match actual version = %i",
     //              o->getClassVersion(),obj->IsA()->GetClassVersion());
     TFile* filesave=gFile;
     gFile=0;
     TBufferFile* buf=0;
     Int_t len=o->getStreamerInfoSize();
     if (len>0&&o->getStreamerInfo()!=0) {
       buf=new TBufferFile(TBuffer::kRead,len);
       memcpy(buf->Buffer(),(Char_t*)o->getStreamerInfo(),len);
       buf->SetBufferOffset(0);
       TList list;
       buf->MapObject(&list);
       list.Streamer(*buf);
       delete buf;
       TStreamerInfo* info;
       TIter next(&list);
       while ((info = (TStreamerInfo*)next())) {
         if (info->IsA() != TStreamerInfo::Class()) {
           fLogger->Warning(MESSAGE_ORIGIN,"Not a TStreamerInfo object");
           //          Warning("FairParamList::fill","not a TStreamerInfo object");
           continue;
         }
         info->BuildCheck();
       }
       list.Clear();  //this will delete all TStreamerInfo objects with kCanDelete
     }
     len=o->getLength();
     buf=new TBufferFile(TBuffer::kRead,len);
     memcpy(buf->Buffer(),(Char_t*)o->getParamValue(),len);
     buf->SetBufferOffset(0);
     buf->MapObject(obj);
     obj->Streamer(*buf);
     delete buf;
     gFile=filesave;
     return len;
   }
   fLogger->Error(MESSAGE_ORIGIN,"Could not find parameter %s", name);
   //  Error("FairParamList::fill \nNot found: %s",name);
   return 0;
 }
FairParamObj* FairParamList::find (const Text_t * name) inline
Definition at line 124 of file FairParamList.h.
{
       return (FairParamObj*)paramList->FindObject(name);
     }
TList* FairParamList::getList () inline
Definition at line 127 of file FairParamList.h.
References paramList.
Referenced by FairGenericParAsciiFileIo::writeGenericSet().
 { return paramList; }
FairParamList& FairParamList::operator= (const FairParamList &) private
void FairParamList::print ()
Definition at line 589 of file FairParamList.cxx.
References paramList, and FairParamObj::print().
Referenced by FairParGenericSet::printParams().
 {
   // Prints the parameter list including values
   TIter next(paramList);
   FairParamObj* o;
   while ((o=(FairParamObj*)next())!=0) { o->print(); }
 }
Member Data Documentation
FairLogger* FairParamList::fLogger protected
Definition at line 81 of file FairParamList.h.
Referenced by fill(), and fillObject().
TList* FairParamList::paramList protected
Definition at line 80 of file FairParamList.h.
Referenced by add(), addObject(), fill(), fillObject(), getList(), print(), and ~FairParamList().
The documentation for this class was generated from the following files:
FairParamList.h
FairParamList.cxx