FairRoot: FairLogger.cxx File Reference
FairLogger.cxx File Reference
#include "FairLogger.h"
#include "Riosfwd.h"
#include "TString.h"
#include "TSystem.h"
#include <stddef.h>
#include <stdio.h>
#include <sys/select.h>
#include <time.h>
#include <cstdlib>
#include <iomanip>
#include <iostream>
Variables
FairLogger * gLogger = FairLogger::GetLogger()
Variable Documentation
FairLogger* gLogger = FairLogger::GetLogger()
Definition at line 29 of file FairLogger.cxx.
Referenced by FairModule::ConstructGDMLGeometry(), logToLoggerPrintf(), FairTrackPar::Print(), FairStack::Print(), _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues(), TEST(), TEST_F(), and TEST_P().