FairRoot: runTestDetectorProcessorBin.cxx File Reference
Tutorial3/run/runTestDetectorProcessorBin.cxx File Reference
#include <iostream>
#include <csignal>
#include "boost/program_options.hpp"
#include "FairMQLogger.h"
#include "FairMQProcessor.h"
#include "zeromq/FairMQTransportFactoryZMQ.h"
#include "FairTestDetectorMQRecoTask.h"
#include "FairTestDetectorHit.h"
#include "FairTestDetectorDigi.h"
#include "FairTestDetectorPayload.h"
Classes
struct DeviceOptions
Typedefs
typedef FairTestDetectorDigi TDigi
typedef FairTestDetectorHit THit
typedef TestDetectorPayload::Digi TPayloadIn
typedef TestDetectorPayload::Hit TPayloadOut
typedef FairTestDetectorMQRecoTask< TDigi, THit, TPayloadIn, TPayloadOut > TProcessorTask
typedef struct DeviceOptions DeviceOptions_t
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
bool parse_cmd_line (int _argc, char *_argv[], DeviceOptions *_options)
int main (int argc, char **argv)
Variables
FairMQProcessor processor
Typedef Documentation
typedef struct DeviceOptions DeviceOptions_t
typedef FairTestDetectorDigi TDigi
Definition at line 37 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
typedef FairTestDetectorHit THit
Definition at line 38 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
typedef TestDetectorPayload::Digi TPayloadIn
Definition at line 39 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
typedef TestDetectorPayload::Hit TPayloadOut
Definition at line 40 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
typedef FairTestDetectorMQRecoTask<TDigi, THit, TPayloadIn, TPayloadOut> TProcessorTask
Definition at line 41 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
Function Documentation
int main (int argc, char ** argv)
Definition at line 154 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
References FairMQStateMachine::BIND, FairMQStateMachine::ChangeState(), FairMQStateMachine::CONNECT, FairMQStateMachine::END, ERROR, FairMQStateMachine::fRunningCondition, FairMQStateMachine::fRunningFinished, FairMQStateMachine::fRunningMutex, FairMQDevice::Id, DeviceOptions::id, INFO, FairMQStateMachine::INIT, FairMQDevice::InputAddress, DeviceOptions::inputAddress, DeviceOptions::inputBufSize, FairMQDevice::InputMethod, DeviceOptions::inputMethod, FairMQDevice::InputRcvBufSize, FairMQDevice::InputSocketType, DeviceOptions::inputSocketType, DeviceOptions::ioThreads, LOG, FairMQDevice::NumInputs, FairMQDevice::NumIoThreads, FairMQDevice::NumOutputs, FairMQDevice::OutputAddress, DeviceOptions::outputAddress, DeviceOptions::outputBufSize, FairMQDevice::OutputMethod, DeviceOptions::outputMethod, FairMQDevice::OutputSndBufSize, FairMQDevice::OutputSocketType, DeviceOptions::outputSocketType, parse_cmd_line(), DeviceOptions::processorTask, FairMQStateMachine::RUN, s_catch_signals(), FairMQStateMachine::SETINPUT, FairMQStateMachine::SETOUTPUT, FairMQDevice::SetProperty(), FairMQProcessor::SetTask(), FairMQDevice::SetTransport(), and FairMQStateMachine::STOP.
 {
     s_catch_signals();
     DeviceOptions_t options;
     try
     {
         if (!parse_cmd_line(argc, argv, &options))
             return 0;
     }
     catch (exception& e)
     {
         LOG(ERROR) << e.what();
         return 1;
     }
     LOG(INFO) << "PID: " << getpid();
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     processor.SetTransport(transportFactory);
     processor.SetProperty(FairMQProcessor::Id, options.id);
     processor.SetProperty(FairMQProcessor::NumIoThreads, options.ioThreads);
     if (strcmp(options.processorTask.c_str(), "FairTestDetectorMQRecoTask") == 0)
     {
         TProcessorTask* task = new TProcessorTask();
         processor.SetTask(task);
     }
     else
     {
         LOG(ERROR) << "task not supported.";
         exit(1);
     }
     processor.SetProperty(FairMQProcessor::NumInputs, 1);
     processor.SetProperty(FairMQProcessor::NumOutputs, 1);
     processor.ChangeState(FairMQProcessor::INIT);
     processor.SetProperty(FairMQProcessor::InputSocketType, options.inputSocketType);
     processor.SetProperty(FairMQProcessor::InputRcvBufSize, options.inputBufSize);
     processor.SetProperty(FairMQProcessor::InputMethod, options.inputMethod);
     processor.SetProperty(FairMQProcessor::InputAddress, options.inputAddress);
     processor.SetProperty(FairMQProcessor::OutputSocketType, options.outputSocketType);
     processor.SetProperty(FairMQProcessor::OutputSndBufSize, options.outputBufSize);
     processor.SetProperty(FairMQProcessor::OutputMethod, options.outputMethod);
     processor.SetProperty(FairMQProcessor::OutputAddress, options.outputAddress);
     processor.ChangeState(FairMQProcessor::SETOUTPUT);
     processor.ChangeState(FairMQProcessor::SETINPUT);
     processor.ChangeState(FairMQProcessor::BIND);
     processor.ChangeState(FairMQProcessor::CONNECT);
     processor.ChangeState(FairMQProcessor::RUN);
     // wait until the running thread has finished processing.
     boost::unique_lock<boost::mutex> lock(processor.fRunningMutex);
     while (!processor.fRunningFinished)
     {
         processor.fRunningCondition.wait(lock);
     }
     processor.ChangeState(FairMQProcessor::STOP);
     processor.ChangeState(FairMQProcessor::END);
     return 0;
 }
bool parse_cmd_line (int _argc, char * _argv[], DeviceOptions * _options) inline
Definition at line 86 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
References DeviceOptions::id, INFO, DeviceOptions::inputAddress, DeviceOptions::inputBufSize, DeviceOptions::inputMethod, DeviceOptions::inputSocketType, DeviceOptions::ioThreads, LOG, DeviceOptions::outputAddress, DeviceOptions::outputBufSize, DeviceOptions::outputMethod, DeviceOptions::outputSocketType, and DeviceOptions::processorTask.
Referenced by main().
 {
     if (_options == NULL)
         throw std::runtime_error("Internal error: options' container is empty.");
     namespace bpo = boost::program_options;
     bpo::options_description desc("Options");
     desc.add_options()
         ("id", bpo::value<string>()->required(), "Device ID")
         ("io-threads", bpo::value<int>()->default_value(1), "Number of I/O threads")
         ("processor-task", bpo::value<string>()->default_value("FairTestDetectorMQRecoTask"), "Name of the Processor Task")
         ("input-socket-type", bpo::value<string>()->required(), "Input socket type: sub/pull")
         ("input-buff-size", bpo::value<int>()->required(), "Input buffer size in number of messages (ZeroMQ)/bytes(nanomsg)")
         ("input-method", bpo::value<string>()->required(), "Input method: bind/connect")
         ("input-address", bpo::value<string>()->required(), "Input address, e.g.: \"tcp://localhost:5555\"")
         ("output-socket-type", bpo::value<string>()->required(), "Output socket type: pub/push")
         ("output-buff-size", bpo::value<int>()->required(), "Output buffer size in number of messages (ZeroMQ)/bytes(nanomsg)")
         ("output-method", bpo::value<string>()->required(), "Output method: bind/connect")
         ("output-address", bpo::value<string>()->required(), "Output address, e.g.: \"tcp://localhost:5555\"")
         ("help", "Print help messages");
     bpo::variables_map vm;
     bpo::store(bpo::parse_command_line(_argc, _argv, desc), vm);
     if ( vm.count("help") )
     {
         LOG(INFO) << "FairMQ Test Detector Processor" << endl << desc;
         return false;
     }
     bpo::notify(vm);
     if ( vm.count("id") )
         _options->id = vm["id"].as<string>();
     if ( vm.count("io-threads") )
         _options->ioThreads = vm["io-threads"].as<int>();
     if ( vm.count("processor-task") )
         _options->processorTask = vm["processor-task"].as<string>();
     if ( vm.count("input-socket-type") )
         _options->inputSocketType = vm["input-socket-type"].as<string>();
     if ( vm.count("input-buff-size") )
         _options->inputBufSize = vm["input-buff-size"].as<int>();
     if ( vm.count("input-method") )
         _options->inputMethod = vm["input-method"].as<string>();
     if ( vm.count("input-address") )
         _options->inputAddress = vm["input-address"].as<string>();
     if ( vm.count("output-socket-type") )
         _options->outputSocketType = vm["output-socket-type"].as<string>();
     if ( vm.count("output-buff-size") )
         _options->outputBufSize = vm["output-buff-size"].as<int>();
     if ( vm.count("output-method") )
         _options->outputMethod = vm["output-method"].as<string>();
     if ( vm.count("output-address") )
         _options->outputAddress = vm["output-address"].as<string>();
     return true;
 }
static void s_catch_signals (void) static
Definition at line 56 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 45 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, and FairMQStateMachine::STOP.
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     processor.ChangeState(FairMQProcessor::STOP);
     processor.ChangeState(FairMQProcessor::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
FairMQProcessor processor
Definition at line 43 of file Tutorial3/run/runTestDetectorProcessorBin.cxx.