FairRoot: FairGeoNode Class Reference
FairGeoNode Class Reference
#include <FairGeoNode.h>
Public Member Functions
FairGeoNode ()
FairGeoNode (FairGeoNode &)
virtual ~FairGeoNode ()
void AddDaughter (FairGeoNode *fNode)
TObjArray * GetListOfDaughters ()
EFairGeoNodeType getVolumeType ()
Bool_t isTopNode ()
Bool_t isRefNode ()
Bool_t isKeepin ()
Bool_t isModule ()
Int_t getCopyNo ()
FairGeoBasicShape * getShapePointer ()
FairGeoNode * getMotherNode ()
FairGeoMedium * getMedium ()
Bool_t isActive ()
FairGeoTransform & getCenterPosition ()
TArrayD * getParameters ()
FairGeoTransform * getPosition ()
FairGeoTransform * getLabTransform ()
FairGeoNode * getCopyNode ()
TGeoVolume * getRootVolume ()
TList * getTree ()
Bool_t isSensitive ()
Bool_t isCreated ()
void setCreated ()
void setName (const Text_t *s)
void setVolumeType (EFairGeoNodeType t)
void setVolumePar (FairGeoNode &)
void setShape (FairGeoBasicShape *s)
void setMother (FairGeoNode *s)
void setMedium (FairGeoMedium *med)
void setActive (Bool_t a=kTRUE)
void setCenterPosition (const FairGeoTransform &t)
void setCopyNode (FairGeoNode *p)
void setRootVolume (TGeoVolume *p)
FairGeoTransform * calcLabTransform ()
void setLabTransform (FairGeoTransform &)
Bool_t calcModuleTransform (FairGeoTransform &)
Bool_t calcRefPos (FairGeoVector &)
void clear ()
void print ()
Bool_t write (std::fstream &)
Int_t compare (FairGeoNode &)
void setTruncName (const char *aName)
const char * getTruncName ()
const TString & getName () const
const TString & getShape () const
const TString & getMother () const
FairGeoTransform & getTransform ()
Int_t getNumPoints ()
FairGeoVector * getPoint (const Int_t n)
void setVolumePar (FairGeoVolume &)
void setShape (const Text_t *s)
void setMother (const Text_t *s)
void createPoints (const Int_t)
void setPoint (const Int_t, const Double_t, const Double_t, const Double_t)
void setPoint (const Int_t, const FairGeoVector &)
virtual void setHadFormat (Int_t i)
Double_t getVolParameter (Int_t nPoint, Int_t pos)
Int_t getMCid ()
void setMCid (Int_t MCid)
Protected Attributes
Bool_t active
FairGeoTransform center
EFairGeoNodeType volumeType
Bool_t created
FairGeoNode * copyNode
TGeoVolume * rootVolume
FairGeoBasicShape * pShape
FairGeoNode * pMother
FairGeoMedium * medium
/** pointer to the mother volume */
FairGeoTransform * labTransform
TObjArray * fDaughterList
TString fTruncName
TString shape
TString mother
TObjArray * points
FairGeoTransform transform
FairGeoTransform fLabTransform
FairGeoMedium fMedium
Int_t nPoints
Int_t fHadFormat
Int_t fgMCid
Private Member Functions
FairGeoNode (const FairGeoNode &)
FairGeoNode & operator= (const FairGeoNode &)
Detailed Description
basic geometry parameters of a volume
Author
Ilse koenig
Definition at line 42 of file FairGeoNode.h.
Constructor & Destructor Documentation
FairGeoNode::FairGeoNode (const FairGeoNode &) private
FairGeoNode::FairGeoNode ()
FairGeoNode::FairGeoNode (FairGeoNode & r)
Definition at line 55 of file FairGeoNode.cxx.
References active, created, isActive(), isCreated(), FairGeoVolume::nPoints, FairGeoVolume::points, and setVolumePar().
   :FairGeoVolume(r),
    active(kFALSE),
    center(r.getCenterPosition()),
    volumeType(r.getVolumeType()),
    created(kFALSE),
    copyNode(r.getCopyNode()),
    rootVolume(r.getRootVolume()),
    pShape(NULL),
    pMother(NULL),
    medium(NULL),
    labTransform(new FairGeoTransform(*(r.getLabTransform()))),
    fDaughterList(new TObjArray(*(r.GetListOfDaughters()))),
    fTruncName(r.getTruncName())
 {
   // Copy constructor
   points=0;
   nPoints = 0;
   fName=r.GetName();
   setVolumePar(r);
   if (r.isActive()) { active=kTRUE; }
   if (r.isCreated()) { created=kTRUE; }
 }
FairGeoNode::~FairGeoNode () virtual
Definition at line 80 of file FairGeoNode.cxx.
References fDaughterList, labTransform, FairGeoVolume::nPoints, and FairGeoVolume::points.
 {
   // Destructor
   if (points) {
     for (Int_t i=0; i<nPoints; i++) { points->RemoveAt(i); }
     delete points;
     points=0;
   }
   if (labTransform) {
     delete labTransform;
     labTransform=0;
   }
   if(fDaughterList) {
     fDaughterList->Delete();
     delete   fDaughterList;
   }
 }
Member Function Documentation
void FairGeoNode::AddDaughter (FairGeoNode * fNode) inline
Definition at line 65 of file FairGeoNode.h.
Referenced by setMother().
 {fDaughterList->AddLast(fNode);}
FairGeoTransform * FairGeoNode::calcLabTransform ()
Definition at line 256 of file FairGeoNode.cxx.
References FairGeoVolume::fLabTransform, FairGeoVolume::fMedium, getLabTransform(), isTopNode(), labTransform, medium, pMother, FairGeoVolume::transform, and FairGeoTransform::transFrom().
Referenced by getLabTransform(), and FairModule::ProcessNodes().
 {
   // Calculates the lab transformation
   labTransform=new FairGeoTransform(transform);
   if (!isTopNode()) {
     if (!pMother) {
       Error("calcLabTransform()","Mother volume of %s not found!",GetName());
       delete labTransform;
       return 0;
     }
     FairGeoTransform* tm=pMother->getLabTransform();
     if (!tm) {
       ;
       Error("calcLabTransform()",
             "Lab Transformation of mother volume of %s not found!",GetName());
       delete labTransform;
       return 0;
     }
     labTransform->transFrom(*tm);
   }
   fLabTransform = *labTransform;
   fMedium = *medium;
   return labTransform;
 }
Bool_t FairGeoNode::calcModuleTransform (FairGeoTransform & modTransform)
Definition at line 308 of file FairGeoNode.cxx.
References getMotherNode(), FairGeoVolume::getTransform(), isModule(), isTopNode(), FairGeoVolume::transform, and FairGeoTransform::transFrom().
 {
   // Calculates the transformation relative to the detectors coordinate system
   FairGeoNode* node=this;
   modTransform=transform;
   while (node&&!node->isModule()) {
     FairGeoNode* pm=node->getMotherNode();
     if (!pm) {
       Error("calcModuleTransform","Mother volume of %s not found!",node->GetName());
       return kFALSE;
     }
     modTransform.transFrom(pm->getTransform());
     node=pm;
   }
   if (isTopNode()) { return kFALSE; }
   else { return kTRUE; }
 }
Bool_t FairGeoNode::calcRefPos (FairGeoVector & refPos)
Definition at line 326 of file FairGeoNode.cxx.
References center, getMotherNode(), FairGeoVolume::getTransform(), FairGeoTransform::getTransVector(), isModule(), isTopNode(), and FairGeoTransform::transFrom().
 {
   // Calculates the position in the detectors coordinate system
   FairGeoNode* node=this;
   refPos=center.getTransVector();
   do {
     refPos=node->getTransform().transFrom(refPos);
     node=node->getMotherNode();
     if (!node) {
       Error("calcModuleTransform","Mother of volume %s not found!",GetName());
       return kFALSE;
     }
   } while (node&&!node->isModule());
   if (isTopNode()) { return kFALSE; }
   else { return kTRUE; }
 }
void FairGeoNode::clear (void) virtual
Reimplemented from FairGeoVolume.
Definition at line 110 of file FairGeoNode.cxx.
References FairGeoVolume::clear(), and labTransform.
 {
   // Clears the volume and deletes the points
   /*  pMother=0;
     medium=0;
     pShape=0;
     volumeType=kFairGeoElement;
     active=kFALSE;
     created=kFALSE;
     copyNode=0;
     rootVolume=0;
   */
   if (labTransform) {
     delete labTransform;
     labTransform=0;
   }
   FairGeoVolume::clear();
 }
Int_t FairGeoNode::compare (FairGeoNode & rn)
Definition at line 343 of file FairGeoNode.cxx.
References getMedium(), FairGeoVolume::getMother(), FairGeoVolume::getNumPoints(), FairGeoVolume::getPoint(), FairGeoTransform::getRotMatrix(), FairGeoVolume::getShape(), FairGeoVolume::getTransform(), FairGeoTransform::getTransVector(), medium, FairGeoVolume::mother, FairGeoVolume::nPoints, FairGeoVolume::points, FairGeoVolume::shape, and FairGeoVolume::transform.
Referenced by FairGeoSet::compare().
 {
   // Compares the volume with the volume rn and prints the diagnose
   // Returns kTRUE if the volume parameters are the same
   Int_t diff[]= {0,0,0,0,0,0};
   Int_t n=0;
   cout<<fName<<'\t';
   if (mother.CompareTo(rn.getMother())!=0) {
     diff[0]=1;
     n++;
   }
   if (medium&&rn.getMedium()) {
     TString med=medium->GetName();
     if (med.CompareTo(rn.getMedium()->GetName())!=0) {
       diff[1]=1;
       n++;
     }
   } else {
     diff[1]=1;
     n++;
   }
   if (shape.CompareTo(rn.getShape())!=0) {
     diff[2]=1;
     n++;
   }
   Int_t np=rn.getNumPoints();
   if (points&&nPoints==np) {
     for (Int_t i=0; i<np; i++) {
       FairGeoVector v1=*(getPoint(i));
       FairGeoVector v2=*(rn.getPoint(i));
       if (fabs(v1(0)-v2(0))>=0.001||fabs(v1(1)-v2(1))>=0.001||fabs(v1(1)-v2(1))>=0.001) {
         diff[3]=1;
         n++;
         break;
       }
     }
   } else {
     diff[3]=1;
     n++;
   }
   FairGeoVector v1=transform.getTransVector();
   FairGeoVector v2=rn.getTransform().getTransVector();
   if (fabs(v1(0)-v2(0))>=0.001||fabs(v1(1)-v2(1))>=0.001||fabs(v1(1)-v2(1))>=0.001) {
     diff[4]=1;
     n++;
   }
   FairGeoRotation r1=transform.getRotMatrix();
   FairGeoRotation r2=rn.getTransform().getRotMatrix();
   for (Int_t i=0; i<9; i++) {
     if (fabs(r1(i)-r2(i))>=1.e-7) {
       diff[5]=1;
       n++;
       break;
     }
   }
   if (n>0) {
     for (Int_t i=0; i<6; i++) { cout<<"    "<<diff[i]<<"  "; }
     cout<<'\n';
   } else { cout<<" same\n"; }
   return n;
 }
void FairGeoVolume::createPoints (const Int_t n) inherited
Definition at line 68 of file FairGeoVolume.cxx.
References FairGeoVolume::nPoints, and FairGeoVolume::points.
Referenced by FairGeoOldAsciiIo::calculateShapePoints(), FairGeoTorus::readPoints(), FairGeoTubs::readPoints(), FairGeoTube::readPoints(), FairGeoCons::readPoints(), FairGeoSphe::readPoints(), FairGeoPcon::readPoints(), FairGeoCone::readPoints(), FairGeoEltu::readPoints(), FairGeoPgon::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), and setVolumePar().
 {
   // Creates n Points (objects of class FairGeoVector).
   // If the array exists already and the size is different from n it is
   // deleted and recreated with the new size n.
   // If n==0 the points are deleted.
   if (n!=nPoints) {
     nPoints=n;
     if (n>0) {
       if (points!=0) {
         points->Delete();
         delete points;
       }
       points=new TObjArray(n);
       for(Int_t i=0; i<n; i++) { points->AddAt(new FairGeoVector(),i); }
     } else {
       if (points) { points->Delete(); }
       delete points;
       points=0;
     }
   }
 }
FairGeoTransform& FairGeoNode::getCenterPosition () inline
Definition at line 77 of file FairGeoNode.h.
References center.
Referenced by FairGeoSet::create(), and getPosition().
 {return center;}
Int_t FairGeoNode::getCopyNo ()
Definition at line 129 of file FairGeoNode.cxx.
References FairGeoVolume::fHadFormat.
Referenced by FairGeoRootBuilder::createNode(), and FairModule::ProcessNodes().
 {
   // Returns the copy number
   Int_t n=0;
   if (fHadFormat == 1 ) {
     Int_t l=fName.Length();
     if (l>4) {
       TString s(fName);
       s.Remove(0,4);
       sscanf(s.Data(),"%i",&n);
     }
   } else {
     Ssiz_t l=fName.Last('#');
     if (l>0) {
       TString s(fName);
       s.Remove(0,l+1);
       sscanf(s.Data(),"%i",&n);
     }
   }
   return n;
 }
FairGeoNode* FairGeoNode::getCopyNode () inline
Definition at line 81 of file FairGeoNode.h.
References copyNode.
Referenced by FairGeoRootBuilder::createNode().
 {return copyNode;}
FairGeoTransform * FairGeoNode::getLabTransform ()
Definition at line 249 of file FairGeoNode.cxx.
References calcLabTransform(), and labTransform.
Referenced by calcLabTransform(), and setLabTransform().
 {
   // Returns the lab transformation
   if (labTransform) { return labTransform; }
   else { return calcLabTransform(); }
 }
TObjArray* FairGeoNode::GetListOfDaughters () inline
Definition at line 66 of file FairGeoNode.h.
References fDaughterList.
 {return fDaughterList;}
Int_t FairGeoVolume::getMCid () inline inherited
Definition at line 65 of file FairGeoVolume.h.
References FairGeoVolume::fgMCid.
Referenced by FairModule::ProcessNodes().
 {return fgMCid;}
FairGeoMedium* FairGeoNode::getMedium () inline
Definition at line 75 of file FairGeoNode.h.
References medium.
Referenced by compare(), FairGeoRootBuilder::createNode(), FairGeoCave::print(), MyGeoCave::print(), FairGeoSet::readVolumeParams(), setVolumePar(), FairGeoCave::write(), and MyGeoCave::write().
 {return medium;}
const TString& FairGeoVolume::getMother () const inline inherited
Definition at line 48 of file FairGeoVolume.h.
References FairGeoVolume::mother.
Referenced by compare(), and FairGeoVolume::setVolumePar().
 { return mother; }
FairGeoNode* FairGeoNode::getMotherNode () inline
Definition at line 74 of file FairGeoNode.h.
References pMother.
Referenced by calcModuleTransform(), calcRefPos(), FairGeoRootBuilder::createNode(), getTree(), FairModule::ProcessNodes(), and setVolumePar().
 {return pMother;}
const TString& FairGeoVolume::getName () const inline inherited
Definition at line 46 of file FairGeoVolume.h.
 { return fName; }
Int_t FairGeoVolume::getNumPoints () inline inherited
Definition at line 52 of file FairGeoVolume.h.
References FairGeoVolume::nPoints.
Referenced by FairGeoPcon::calcVoluParam(), FairGeoPgon::calcVoluParam(), compare(), FairGeoPcon::printPoints(), FairGeoPgon::printPoints(), FairGeoBasicShape::printPoints(), FairGeoTube::readPoints(), FairGeoTubs::readPoints(), FairGeoTorus::readPoints(), FairGeoCons::readPoints(), FairGeoEltu::readPoints(), FairGeoSphe::readPoints(), FairGeoPcon::readPoints(), FairGeoCone::readPoints(), FairGeoPgon::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), setVolumePar(), FairGeoPcon::writePoints(), FairGeoPgon::writePoints(), and FairGeoBasicShape::writePoints().
 { return nPoints;}
TArrayD * FairGeoNode::getParameters ()
Definition at line 154 of file FairGeoNode.cxx.
References FairGeoBasicShape::calcVoluParam(), and pShape.
Referenced by FairGeoRootBuilder::createNode().
 {
   // Returns the parameters to create a GEANT/ROOT volume
   if (pShape) { return pShape->calcVoluParam(this); }
   return 0;
 }
FairGeoVector * FairGeoVolume::getPoint (const Int_t n) inline inherited
Definition at line 88 of file FairGeoVolume.h.
References FairGeoVolume::nPoints, and FairGeoVolume::points.
Referenced by FairGeoBrik::calcVoluParam(), FairGeoTube::calcVoluParam(), FairGeoTorus::calcVoluParam(), FairGeoTubs::calcVoluParam(), FairGeoTrd1::calcVoluParam(), FairGeoTrap::calcVoluParam(), FairGeoCons::calcVoluParam(), FairGeoEltu::calcVoluParam(), FairGeoCone::calcVoluParam(), FairGeoPcon::calcVoluParam(), FairGeoPgon::calcVoluParam(), FairGeoSphe::calcVoluParam(), FairGeoBrik::calcVoluPosition(), FairGeoTube::calcVoluPosition(), FairGeoTubs::calcVoluPosition(), FairGeoTrap::calcVoluPosition(), FairGeoTrd1::calcVoluPosition(), FairGeoCons::calcVoluPosition(), FairGeoEltu::calcVoluPosition(), FairGeoCone::calcVoluPosition(), compare(), FairGeoTorus::printPoints(), FairGeoAssembly::printPoints(), FairGeoTube::printPoints(), FairGeoTubs::printPoints(), FairGeoCons::printPoints(), FairGeoSphe::printPoints(), FairGeoEltu::printPoints(), FairGeoPcon::printPoints(), FairGeoPgon::printPoints(), FairGeoCone::printPoints(), FairGeoBasicShape::printPoints(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), setVolumePar(), FairGeoTorus::writePoints(), FairGeoAssembly::writePoints(), FairGeoTube::writePoints(), FairGeoTubs::writePoints(), FairGeoCons::writePoints(), FairGeoPcon::writePoints(), FairGeoEltu::writePoints(), FairGeoSphe::writePoints(), FairGeoCone::writePoints(), FairGeoPgon::writePoints(), and FairGeoBasicShape::writePoints().
 {
   if (points && n<nPoints) { return (FairGeoVector*)points->At(n); }
   else { return 0; }
 }
FairGeoTransform * FairGeoNode::getPosition ()
Definition at line 161 of file FairGeoNode.cxx.
References FairGeoBasicShape::calcVoluPosition(), center, FairGeoBasicShape::getCenterPosition(), getCenterPosition(), FairGeoBasicShape::getVoluPosition(), pMother, pShape, and FairGeoTransform::setTransform().
Referenced by FairGeoRootBuilder::createNode().
 {
   // Returns the transformation to position a volume in GEANT/ROOT
   if (pShape&&pMother) {
     pShape->calcVoluPosition(this,pMother->getCenterPosition());
     center.setTransform(*(pShape->getCenterPosition()));
     return pShape->getVoluPosition();
   }
   return 0;
 }
TGeoVolume* FairGeoNode::getRootVolume () inline
Definition at line 82 of file FairGeoNode.h.
References rootVolume.
Referenced by FairGeoSet::create(), and FairGeoRootBuilder::createNode().
 {return rootVolume;}
const TString& FairGeoVolume::getShape () const inline inherited
Definition at line 47 of file FairGeoVolume.h.
References FairGeoVolume::shape.
Referenced by compare(), FairGeoRootBuilder::createNode(), FairGeoShapes::selectShape(), and FairGeoVolume::setVolumePar().
 { return shape; }
FairGeoBasicShape* FairGeoNode::getShapePointer () inline
Definition at line 73 of file FairGeoNode.h.
References pShape.
Referenced by FairGeoOldAsciiIo::calculateShapePoints(), FairGeoCave::print(), MyGeoCave::print(), FairGeoSet::readVolumeParams(), setVolumePar(), FairGeoCave::write(), and MyGeoCave::write().
 { return pShape; }
FairGeoTransform& FairGeoVolume::getTransform () inline inherited
Definition at line 49 of file FairGeoVolume.h.
References FairGeoVolume::transform.
Referenced by calcModuleTransform(), calcRefPos(), FairGeoBasicShape::calcVoluPosition(), compare(), FairGeoOldAsciiIo::read(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), and setVolumePar().
 { return transform; }
TList * FairGeoNode::getTree ()
Definition at line 235 of file FairGeoNode.cxx.
References getMotherNode(), and isTopNode().
 {
   // Returns the tree of the mother volumes
   TList* tree=new TList();
   FairGeoNode* v=this;
   FairGeoNode* lmother;
   do {
     lmother=v->getMotherNode();
     if (lmother) { tree->Add(lmother); }
     v=lmother;
   } while (v&&!v->isTopNode());
   return tree;
 }
const char* FairGeoNode::getTruncName () inline
Definition at line 108 of file FairGeoNode.h.
Referenced by FairModule::ProcessNodes().
{
       if (fTruncName.Length()>0) { return fTruncName.Data(); }
       else { return GetName(); }
     }
Double_t FairGeoVolume::getVolParameter (Int_t nPoint, Int_t pos) inherited
Definition at line 141 of file FairGeoVolume.cxx.
References FairGeoVector::getValues(), and FairGeoVolume::points.
 {
   FairGeoVector* vec = (FairGeoVector*) points->At( nPoint );
   if ( vec ) { return vec->getValues( pos ); }
   else { return -1; }
 }
EFairGeoNodeType FairGeoNode::getVolumeType () inline
Definition at line 67 of file FairGeoNode.h.
References volumeType.
 { return volumeType; }
Bool_t FairGeoNode::isActive () inline
Definition at line 76 of file FairGeoNode.h.
References active.
Referenced by FairGeoSet::create(), FairGeoNode(), and FairGeoSet::readVolumeParams().
 {return active;}
Bool_t FairGeoNode::isCreated () inline
Definition at line 85 of file FairGeoNode.h.
References created.
Referenced by FairGeoNode().
 {return created;}
Bool_t FairGeoNode::isKeepin () inline
Definition at line 70 of file FairGeoNode.h.
References kFairGeoKeepin.
Referenced by FairGeoSet::readVolumeParams().
 { return (Bool_t)(volumeType == kFairGeoKeepin);}
Bool_t FairGeoNode::isModule () inline
Definition at line 71 of file FairGeoNode.h.
References kFairGeoModule.
Referenced by calcModuleTransform(), calcRefPos(), FairGeoRootBuilder::createNode(), and FairGeoSet::readVolumeParams().
 { return (Bool_t)(volumeType == kFairGeoModule);}
Bool_t FairGeoNode::isRefNode () inline
Definition at line 69 of file FairGeoNode.h.
References kFairGeoRefNode.
Referenced by FairGeoSet::create().
 { return (Bool_t)(volumeType == kFairGeoRefNode);}
Bool_t FairGeoNode::isSensitive () inline
Definition at line 144 of file FairGeoNode.h.
References FairGeoMedium::isSensitive(), and medium.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), and FairModule::ProcessNodes().
 {
   if (medium) { return medium->isSensitive(); }
   else { return kFALSE; }
 }
Bool_t FairGeoNode::isTopNode () inline
Definition at line 68 of file FairGeoNode.h.
References kFairGeoTopNode.
Referenced by calcLabTransform(), calcModuleTransform(), calcRefPos(), FairGeoSet::create(), FairGeoRootBuilder::createNode(), getTree(), and setLabTransform().
 { return (Bool_t)(volumeType == kFairGeoTopNode);}
FairGeoNode& FairGeoNode::operator= (const FairGeoNode &) private
void FairGeoNode::print () virtual
Reimplemented from FairGeoVolume.
Definition at line 172 of file FairGeoNode.cxx.
References FairGeoVolume::print().
Referenced by FairGeoSet::print(), and FairGeoOldAsciiIo::read().
 {
   // Prints all parameters of a volume
   cout<<"//----------------------------------------------------------\n";
   FairGeoVolume::print();
   cout<<"//----------------------------------------------------------\n";
   return;
   /*
   cout<<((const char*)fName)<<'\n';
   if (pMother) { cout<<((const char*)mother)<<'\n'; }
   else { cout<<"-- unknown mother --\n"; }
   if (!copyNode) {
     if (pShape) { cout<<((const char*)shape)<<'\n'; }
     else { cout<<"-- unknown shape --\n"; }
     if (medium) { cout<<medium->GetName()<<'\n'; }
     else { cout<<"-- unknown medium --\n"; }
     if (points && pShape) { pShape->printPoints(this); }
     else { cout<<"-- no points --\n"; }
   }
   transform.getTransVector().print();
   transform.getRotMatrix().print();
   cout<<"//----------------------------------------------------------\n";
   */
 }
void FairGeoNode::setActive (Bool_t a = kTRUE) inline
Definition at line 93 of file FairGeoNode.h.
Referenced by FairGeoCave::read(), MyGeoCave::read(), FairGeoSet::readModule(), and FairGeoSet::readVolumeParams().
 {active=a;}
void FairGeoNode::setCenterPosition (const FairGeoTransform & t) inline
Definition at line 94 of file FairGeoNode.h.
Referenced by FairGeoSet::create().
 {center=t;}
void FairGeoNode::setCopyNode (FairGeoNode * p) inline
Definition at line 95 of file FairGeoNode.h.
Referenced by FairGeoSet::readVolumeParams().
 {copyNode=p;}
void FairGeoNode::setCreated () inline
Definition at line 86 of file FairGeoNode.h.
Referenced by FairGeoRootBuilder::createNode().
 {created=kTRUE;}
virtual void FairGeoVolume::setHadFormat (Int_t i) inline virtual inherited
Definition at line 63 of file FairGeoVolume.h.
Referenced by FairGeoRootBuilder::createNode().
 { fHadFormat=i;}
void FairGeoNode::setLabTransform (FairGeoTransform & t)
Definition at line 284 of file FairGeoNode.cxx.
References getLabTransform(), isTopNode(), labTransform, pMother, FairGeoTransform::setTransform(), FairGeoVolume::transform, and FairGeoTransform::transTo().
 {
   // Sets the lab transformation
   if (!isTopNode()) {
     if (labTransform) { labTransform->setTransform(t); }
     else { labTransform=new FairGeoTransform(t); }
     if (!pMother) {
       Error("calcLabTransform()","Mother volume of %s not found!",GetName());
       delete labTransform;
       return;
     }
     FairGeoTransform* tm=pMother->getLabTransform();
     if (!tm) {
       ;
       Error("calcLabTransform()",
             "Lab Transformation of mother volume of %s not found!",GetName());
       delete labTransform;
       return;
     }
     transform=t;
     transform.transTo(*tm);
   }
 }
void FairGeoVolume::setMCid (Int_t MCid) inline inherited
Definition at line 66 of file FairGeoVolume.h.
Referenced by FairDetector::Initialize().
 {fgMCid=MCid;}
void FairGeoNode::setMedium (FairGeoMedium * med) inline
Definition at line 92 of file FairGeoNode.h.
Referenced by FairGeoCave::read(), MyGeoCave::read(), FairGeoOldAsciiIo::read(), and FairGeoSet::readVolumeParams().
 {medium=med; }
void FairGeoVolume::setMother (const Text_t * s) inline inherited
Definition at line 106 of file FairGeoVolume.h.
References FairGeoVolume::mother.
 {
   mother=s;
   mother.ToUpper();
 }
void FairGeoNode::setMother (FairGeoNode * s) inline
Definition at line 134 of file FairGeoNode.h.
References AddDaughter(), FairGeoVolume::mother, and pMother.
Referenced by FairGeoOldAsciiIo::read(), FairGeoSet::readVolumeParams(), and setVolumePar().
 {
   // Sets the mother of the volume
   if (moth) {
     pMother=moth;
     mother=pMother->GetName();
     pMother->AddDaughter(this);
   }
 }
void FairGeoNode::setName (const Text_t * s) inline
Definition at line 118 of file FairGeoNode.h.
 {
   // Sets the name of the volume
   fName=s;
   fName.ToUpper();
 }
void FairGeoVolume::setPoint (const Int_t n, const Double_t x, const Double_t y, const Double_t z) inherited
Definition at line 91 of file FairGeoVolume.cxx.
References FairGeoVolume::nPoints, FairGeoVolume::points, FairGeoVector::setX(), FairGeoVector::setY(), and FairGeoVector::setZ().
Referenced by FairGeoOldAsciiIo::calculateShapePoints(), FairGeoTorus::readPoints(), FairGeoTubs::readPoints(), FairGeoTube::readPoints(), FairGeoCons::readPoints(), FairGeoSphe::readPoints(), FairGeoPcon::readPoints(), FairGeoCone::readPoints(), FairGeoEltu::readPoints(), FairGeoPgon::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), and setVolumePar().
 {
   // set the 3 values of the point with index n
   if (points && n<nPoints) {
     FairGeoVector* v=(FairGeoVector*)points->At(n);
     v->setX(x);
     v->setY(y);
     v->setZ(z);
   }
 }
void FairGeoVolume::setPoint (const Int_t n, const FairGeoVector & p) inherited
Definition at line 103 of file FairGeoVolume.cxx.
References FairGeoVolume::nPoints, and FairGeoVolume::points.
 {
   // sets point with index n by copying the 3 components of point p
   if (points && n<nPoints) {
     FairGeoVector& v=*((FairGeoVector*)points->At(n));
     v=p;
   }
 }
void FairGeoNode::setRootVolume (TGeoVolume * p) inline
Definition at line 96 of file FairGeoNode.h.
Referenced by FairGeoSet::create(), and FairGeoRootBuilder::createNode().
 {rootVolume=p;}
void FairGeoVolume::setShape (const Text_t * s) inline inherited
Definition at line 100 of file FairGeoVolume.h.
References FairGeoVolume::shape.
 {
   shape=s;
   shape.ToUpper();
 }
void FairGeoNode::setShape (FairGeoBasicShape * s) inline
Definition at line 125 of file FairGeoNode.h.
References pShape, and FairGeoVolume::shape.
Referenced by FairGeoCave::read(), MyGeoCave::read(), FairGeoOldAsciiIo::read(), FairGeoSet::readVolumeParams(), and setVolumePar().
 {
   // Sets the shape of the volume
   if (s) {
     pShape=s;
     shape=pShape->GetName();
   }
 }
void FairGeoNode::setTruncName (const char * aName) inline
Definition at line 107 of file FairGeoNode.h.
 { fTruncName = aName;}
void FairGeoVolume::setVolumePar (FairGeoVolume & r) inherited
Definition at line 57 of file FairGeoVolume.cxx.
References FairGeoVolume::createPoints(), FairGeoVolume::getMother(), FairGeoVolume::getNumPoints(), FairGeoVolume::getPoint(), FairGeoVolume::getShape(), FairGeoVolume::getTransform(), FairGeoVolume::mother, FairGeoVolume::nPoints, FairGeoVolume::setPoint(), FairGeoVolume::shape, and FairGeoVolume::transform.
 {
   // copies all volume parameters except the name
   shape=r.getShape();
   mother=r.getMother();
   Int_t n=r.getNumPoints();
   createPoints(n);
   for (Int_t i=0; i<nPoints; i++) { setPoint(i,*(r.getPoint(i))); }
   transform=r.getTransform();
 }
void FairGeoNode::setVolumePar (FairGeoNode & r)
Definition at line 98 of file FairGeoNode.cxx.
References FairGeoVolume::createPoints(), getMedium(), getMotherNode(), FairGeoVolume::getNumPoints(), FairGeoVolume::getPoint(), getShapePointer(), FairGeoVolume::getTransform(), medium, FairGeoVolume::nPoints, setMother(), FairGeoVolume::setPoint(), setShape(), and FairGeoVolume::transform.
Referenced by FairGeoNode().
 {
   // Copies all volume parameters except the name
   setMother(r.getMotherNode());
   medium=r.getMedium();
   setShape(r.getShapePointer());
   Int_t n=r.getNumPoints();
   createPoints(n);
   for (Int_t i=0; i<nPoints; i++) { setPoint(i,*(r.getPoint(i))); }
   transform=r.getTransform();
 }
void FairGeoNode::setVolumeType (EFairGeoNodeType t) inline
Definition at line 88 of file FairGeoNode.h.
Referenced by FairGeoCave::read(), MyGeoCave::read(), FairGeoSet::readKeepIn(), and FairGeoSet::readModule().
 {volumeType=t;}
Bool_t FairGeoNode::write (std::fstream & fout)
Definition at line 198 of file FairGeoNode.cxx.
References copyNode, FairGeoTransform::getRotMatrix(), FairGeoTransform::getTransVector(), medium, FairGeoVolume::mother, pMother, FairGeoVolume::points, pShape, FairGeoVolume::shape, FairGeoVolume::transform, and FairGeoBasicShape::writePoints().
Referenced by FairGeoSet::write().
 {
   // Writes all parameters of a volume to file
   fout<<fName.Data()<<'\n';
   if (pMother) { fout<<((const char*)mother)<<'\n'; }
   else {
     Error("write","Unknown mother for %s\n",fName.Data());
     return kFALSE;
   }
   if (!copyNode) {
     if (pShape) { fout<<((const char*)shape)<<'\n'; }
     else {
       Error("write","Unknown shape for %s\n",fName.Data());
       return kFALSE;
     }
     if (medium) { fout<<medium->GetName()<<'\n'; }
     else {
       Error("write","Unknown medium for %s\n",fName.Data());
       return kFALSE;
     }
     if (points && pShape) { pShape->writePoints(&fout,this); }
     else {
       Error("write","No points for %s\n",fName.Data());
       return kFALSE;
     }
   }
   const FairGeoRotation& r=transform.getRotMatrix();
   const FairGeoVector& v=transform.getTransVector();
   fout.precision(3);
   fout<<v(0)<<" "<<v(1)<<" "<<v(2)<<'\n';
   fout.precision(7);
   for(Int_t i=0; i<9; i++) { fout<<r(i)<<"  "; }
   fout<<'\n';
   fout<<"//----------------------------------------------------------\n";
   return kTRUE;
 }
Member Data Documentation
Bool_t FairGeoNode::active protected
Definition at line 48 of file FairGeoNode.h.
Referenced by FairGeoNode(), and isActive().
FairGeoTransform FairGeoNode::center protected
in/out flag for creation
Definition at line 49 of file FairGeoNode.h.
Referenced by calcRefPos(), getCenterPosition(), and getPosition().
FairGeoNode* FairGeoNode::copyNode protected
Flag set kTRUE after creation of volume
Definition at line 52 of file FairGeoNode.h.
Referenced by getCopyNode(), and write().
Bool_t FairGeoNode::created protected
type of volume
Definition at line 51 of file FairGeoNode.h.
Referenced by FairGeoNode(), and isCreated().
TObjArray* FairGeoNode::fDaughterList protected
Transformation to the LAB system
Definition at line 58 of file FairGeoNode.h.
Referenced by GetListOfDaughters(), and ~FairGeoNode().
Int_t FairGeoVolume::fgMCid protected inherited
Definition at line 40 of file FairGeoVolume.h.
Referenced by FairGeoVolume::getMCid().
Int_t FairGeoVolume::fHadFormat protected inherited
number of points
Definition at line 39 of file FairGeoVolume.h.
Referenced by getCopyNo().
FairGeoTransform FairGeoVolume::fLabTransform protected inherited
transformation relative to the mother system
Definition at line 36 of file FairGeoVolume.h.
Referenced by calcLabTransform(), FairGeoVolume::getLabTransform(), and FairGeoVolume::print().
FairGeoMedium FairGeoVolume::fMedium protected inherited
transformation to the LAB system;
Definition at line 37 of file FairGeoVolume.h.
Referenced by calcLabTransform(), and FairGeoVolume::getMedium().
TString FairGeoNode::fTruncName protected
List of daughter Nodes
Definition at line 60 of file FairGeoNode.h.
FairGeoTransform* FairGeoNode::labTransform protected
pointer to medium
Definition at line 57 of file FairGeoNode.h.
Referenced by calcLabTransform(), clear(), getLabTransform(), setLabTransform(), and ~FairGeoNode().
FairGeoMedium* FairGeoNode::medium protected
/** pointer to the mother volume */
Definition at line 56 of file FairGeoNode.h.
Referenced by calcLabTransform(), compare(), getMedium(), isSensitive(), setVolumePar(), and write().
TString FairGeoVolume::mother protected inherited
eant shape of the volume
Definition at line 33 of file FairGeoVolume.h.
Referenced by FairGeoVolume::clear(), compare(), FairGeoVolume::getMother(), FairGeoVolume::print(), FairGeoVolume::setMother(), setMother(), FairGeoVolume::setVolumePar(), and write().
Int_t FairGeoVolume::nPoints protected inherited
medium properties
Definition at line 38 of file FairGeoVolume.h.
Referenced by FairGeoVolume::clear(), compare(), FairGeoVolume::createPoints(), FairGeoNode(), FairGeoVolume::getNumPoints(), FairGeoVolume::getPoint(), FairGeoVolume::print(), FairGeoVolume::setPoint(), FairGeoVolume::setVolumePar(), setVolumePar(), and ~FairGeoNode().
FairGeoNode* FairGeoNode::pMother protected
pointer to the shape
Definition at line 55 of file FairGeoNode.h.
Referenced by calcLabTransform(), getMotherNode(), getPosition(), setLabTransform(), setMother(), and write().
TObjArray* FairGeoVolume::points protected inherited
Name of the mother volume
Definition at line 34 of file FairGeoVolume.h.
Referenced by FairGeoVolume::clear(), compare(), FairGeoVolume::createPoints(), FairGeoNode(), FairGeoVolume::getPoint(), FairGeoVolume::getVolParameter(), FairGeoVolume::print(), FairGeoVolume::setPoint(), write(), ~FairGeoNode(), and FairGeoVolume::~FairGeoVolume().
FairGeoBasicShape* FairGeoNode::pShape protected
pointer to the ROOT node
Definition at line 54 of file FairGeoNode.h.
Referenced by getParameters(), getPosition(), getShapePointer(), setShape(), and write().
TGeoVolume* FairGeoNode::rootVolume protected
pointer to the reference volume for a copy
Definition at line 53 of file FairGeoNode.h.
Referenced by getRootVolume().
TString FairGeoVolume::shape protected inherited
Definition at line 32 of file FairGeoVolume.h.
Referenced by FairGeoVolume::clear(), compare(), FairGeoVolume::getShape(), FairGeoVolume::print(), FairGeoVolume::setShape(), setShape(), FairGeoVolume::setVolumePar(), and write().
FairGeoTransform FairGeoVolume::transform protected inherited
array of points (type FairGeoVector)
Definition at line 35 of file FairGeoVolume.h.
Referenced by calcLabTransform(), calcModuleTransform(), FairGeoVolume::clear(), compare(), FairGeoVolume::getTransform(), setLabTransform(), FairGeoVolume::setVolumePar(), setVolumePar(), and write().
EFairGeoNodeType FairGeoNode::volumeType protected
position of the GEANT/ROOT center
Definition at line 50 of file FairGeoNode.h.
Referenced by getVolumeType().
The documentation for this class was generated from the following files:
FairGeoNode.h
FairGeoNode.cxx