FairRroot: FairMockVirtualMC Class Reference
FairMockVirtualMC Class Reference
#include <FairMockVirtualMC.h>
Public Member Functions
FairMockVirtualMC ()
FairMockVirtualMC (const char *title, Int_t nwgeant=0)
virtual ~FairMockVirtualMC ()
Int_t VolId (const Text_t *name) const
void SetRootGeometry ()
void StopExecution () const
void Material (Int_t &, const char *, Double_t, Double_t, Double_t, Double_t, Double_t, Float_t *, Int_t)
void Material (Int_t &, const char *, Double_t, Double_t, Double_t, Double_t, Double_t, Double_t *, Int_t)
void Mixture (Int_t &, const char *, Float_t *, Float_t *, Double_t, Int_t, Float_t *)
void Mixture (Int_t &, const char *, Double_t *, Double_t *, Double_t, Int_t, Double_t *)
void Medium (Int_t &, const char *, Int_t, Int_t, Int_t, Double_t, Double_t, Double_t, Double_t, Double_t, Double_t, Float_t *, Int_t)
virtual void Medium (Int_t &, const char *, Int_t, Int_t, Int_t, Double_t, Double_t, Double_t, Double_t, Double_t, Double_t, Double_t *, Int_t)
virtual void Matrix (Int_t &, Double_t, Double_t, Double_t, Double_t, Double_t, Double_t)
virtual void Gstpar (Int_t, const char *, Double_t)
virtual Int_t Gsvolu (const char *, const char *, Int_t, Float_t *, Int_t)
virtual Int_t Gsvolu (const char *, const char *, Int_t, Double_t *, Int_t)
virtual void Gsdvn (const char *, const char *, Int_t, Int_t)
virtual void Gsdvn2 (const char *, const char *, Int_t, Int_t, Double_t, Int_t)
virtual void Gsdvt (const char *, const char *, Double_t, Int_t, Int_t, Int_t)
virtual void Gsdvt2 (const char *, const char *, Double_t, Int_t, Double_t, Int_t, Int_t)
virtual void Gfmate (Int_t, char *, Float_t &, Float_t &, Float_t &, Float_t &, Float_t &, Float_t *, Int_t &)
virtual void Gfmate (Int_t, char *, Double_t &, Double_t &, Double_t &, Double_t &, Double_t &, Double_t *, Int_t &)
virtual void Gckmat (Int_t, char *)
virtual void Gsord (const char *, Int_t)
virtual void Gspos (const char *, Int_t, const char *, Double_t, Double_t, Double_t, Int_t, const char *)
virtual void Gsposp (const char *, Int_t, const char *, Double_t, Double_t, Double_t, Int_t, const char *, Float_t *, Int_t)
virtual void Gsposp (const char *, Int_t, const char *, Double_t, Double_t, Double_t, Int_t, const char *, Double_t *, Int_t)
virtual void Gsbool (const char *, const char *)
virtual void SetCerenkov (Int_t, Int_t, Float_t *, Float_t *, Float_t *, Float_t *)
virtual void SetCerenkov (Int_t, Int_t, Double_t *, Double_t *, Double_t *, Double_t *)
virtual void DefineOpSurface (const char *, EMCOpSurfaceModel, EMCOpSurfaceType, EMCOpSurfaceFinish, Double_t)
virtual void SetBorderSurface (const char *, const char *, int, const char *, int, const char *)
virtual void SetSkinSurface (const char *, const char *, const char *)
virtual void SetMaterialProperty (Int_t, const char *, Int_t, Double_t *, Double_t *)
virtual void SetMaterialProperty (Int_t, const char *, Double_t)
virtual void SetMaterialProperty (const char *, const char *, Int_t, Double_t *, Double_t *)
virtual Bool_t GetTransformation (const TString &, TGeoHMatrix &)
virtual Bool_t GetShape (const TString &, TString &, TArrayD &)
virtual Bool_t GetMaterial (const TString &, TString &, Int_t &, Double_t &, Double_t &, Double_t &, Double_t &, Double_t &, TArrayD &)
virtual Bool_t GetMedium (const TString &, TString &, Int_t &, Int_t &, Int_t &, Int_t &, Double_t &, Double_t &, Double_t &, Double_t &, Double_t &, Double_t &, TArrayD &)
virtual void WriteEuclid (const char *, const char *, Int_t, Int_t)
virtual void SetUserParameters (Bool_t)
virtual const char * VolName (Int_t) const
virtual Int_t MediumId (const char *) const
virtual Int_t NofVolumes () const
virtual Int_t VolId2Mate (Int_t) const
virtual Int_t NofVolDaughters (const char *) const
virtual const char * VolDaughterName (const char *, Int_t) const
virtual Int_t VolDaughterCopyNo (const char *, Int_t) const
virtual Bool_t SetCut (const char *, Double_t)
virtual Bool_t SetProcess (const char *, Int_t)
virtual Bool_t DefineParticle (Int_t, const char *, TMCParticleType, Double_t, Double_t, Double_t)
virtual Bool_t DefineParticle (Int_t, const char *, TMCParticleType, Double_t, Double_t, Double_t, const TString &, Double_t, Int_t, Int_t, Int_t, Int_t, Int_t, Int_t, Int_t, Int_t, Bool_t, Bool_t, const TString &, Int_t, Double_t, Double_t)
virtual Bool_t DefineIon (const char *, Int_t, Int_t, Int_t, Double_t, Double_t)
virtual Bool_t SetDecayMode (Int_t, Float_t *, Int_t(*)[3])
virtual Double_t Xsec (char *, Double_t, Int_t, Int_t)
virtual Int_t IdFromPDG (Int_t) const
virtual Int_t PDGFromId (Int_t) const
virtual TString ParticleName (Int_t) const
virtual Double_t ParticleMass (Int_t) const
virtual Double_t ParticleCharge (Int_t) const
virtual Double_t ParticleLifeTime (Int_t) const
virtual TMCParticleType ParticleMCType (Int_t) const
virtual void StopTrack ()
virtual void StopEvent ()
virtual void StopRun ()
virtual void SetMaxStep (Double_t)
virtual void SetMaxNStep (Int_t)
virtual void SetUserDecay (Int_t)
virtual void ForceDecayTime (Float_t)
virtual Int_t CurrentVolID (Int_t &) const
virtual Int_t CurrentVolOffID (Int_t, Int_t &) const
virtual const char * CurrentVolName () const
virtual const char * CurrentVolOffName (Int_t) const
virtual const char * CurrentVolPath ()
virtual Int_t CurrentMaterial (Float_t &, Float_t &, Float_t &, Float_t &, Float_t &) const
virtual Int_t CurrentMedium () const
virtual Int_t CurrentEvent () const
virtual void Gmtod (Float_t *, Float_t *, Int_t)
virtual void Gmtod (Double_t *, Double_t *, Int_t)
virtual void Gdtom (Float_t *, Float_t *, Int_t)
virtual void Gdtom (Double_t *, Double_t *, Int_t)
virtual Double_t MaxStep () const
virtual Int_t GetMaxNStep () const
virtual void TrackPosition (TLorentzVector &) const
virtual void TrackPosition (Double_t &, Double_t &, Double_t &) const
virtual void TrackMomentum (TLorentzVector &) const
virtual void TrackMomentum (Double_t &, Double_t &, Double_t &, Double_t &) const
virtual Double_t TrackStep () const
virtual Double_t TrackLength () const
virtual Double_t TrackTime () const
virtual Double_t Edep () const
virtual Int_t TrackPid () const
virtual Double_t TrackCharge () const
virtual Double_t TrackMass () const
virtual Double_t Etot () const
virtual Bool_t IsNewTrack () const
virtual Bool_t IsTrackInside () const
virtual Bool_t IsTrackEntering () const
virtual Bool_t IsTrackExiting () const
virtual Bool_t IsTrackOut () const
virtual Bool_t IsTrackDisappeared () const
virtual Bool_t IsTrackStop () const
virtual Bool_t IsTrackAlive () const
virtual Int_t NSecondaries () const
virtual void GetSecondary (Int_t, Int_t &, TLorentzVector &, TLorentzVector &)
virtual TMCProcess ProdProcess (Int_t) const
virtual Int_t StepProcesses (TArrayI &) const
virtual Bool_t SecondariesAreOrdered () const
virtual void Init ()
virtual void BuildPhysics ()
virtual void ProcessEvent ()
virtual Bool_t ProcessRun (Int_t)
virtual void InitLego ()
virtual void SetCollectTracks (Bool_t)
virtual Bool_t IsCollectTracks () const
Protected Attributes
TGeoMCGeometry * fMCGeo
Bool_t fImportRootGeometry
FairLogger * fLogger
Detailed Description
Definition at line 15 of file FairMockVirtualMC.h.
Constructor & Destructor Documentation
FairMockVirtualMC::FairMockVirtualMC ()
Definition at line 13 of file FairMockVirtualMC.cxx.
   : TVirtualMC(),
     fMCGeo(new TGeoMCGeometry("MCGeo", "TGeo Implementation of VirtualMCGeometry")),
     fLogger(FairLogger::GetLogger())
 {
 }
FairMockVirtualMC::FairMockVirtualMC (const char * title, Int_t nwgeant = 0)
Definition at line 20 of file FairMockVirtualMC.cxx.
   : TVirtualMC("FairMockVirtualMC",title, kFALSE),
     fMCGeo(new TGeoMCGeometry("MCGeo", "TGeo Implementation of VirtualMCGeometry")),
     fLogger(FairLogger::GetLogger())
 {
 }
FairMockVirtualMC::~FairMockVirtualMC () virtual
Definition at line 27 of file FairMockVirtualMC.cxx.
 {
 }
Member Function Documentation
virtual void FairMockVirtualMC::BuildPhysics () inline virtual
Definition at line 134 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::CurrentEvent () const inline virtual
Definition at line 101 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::CurrentMaterial (Float_t & , Float_t & , Float_t & , Float_t & , Float_t &) const inline virtual
Definition at line 99 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::CurrentMedium () const inline virtual
Definition at line 100 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
Int_t FairMockVirtualMC::CurrentVolID (Int_t & copy) const virtual
Definition at line 52 of file FairMockVirtualMC.cxx.
Referenced by CurrentVolOffID().
 {
   //
   // Returns the current volume ID and copy number
   //
   if (gGeoManager->IsOutside()) { return 0; }
   TGeoNode* node = gGeoManager->GetCurrentNode();
   copy = node->GetNumber();
   Int_t id = node->GetVolume()->GetNumber();
   return id;
 }
virtual const char* FairMockVirtualMC::CurrentVolName () const inline virtual
Definition at line 96 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
Int_t FairMockVirtualMC::CurrentVolOffID (Int_t off, Int_t & copy) const virtual
Definition at line 65 of file FairMockVirtualMC.cxx.
References CurrentVolID().
 {
   //
   // Return the current volume "off" upward in the geometrical tree
   // ID and copy number
   //
   if (off<0 || off>gGeoManager->GetLevel()) { return 0; }
   if (off==0) { return CurrentVolID(copy); }
   TGeoNode* node = gGeoManager->GetMother(off);
   if (!node) { return 0; }
   copy = node->GetNumber();
   return node->GetVolume()->GetNumber();
 }
virtual const char* FairMockVirtualMC::CurrentVolOffName (Int_t) const inline virtual
Definition at line 97 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual const char* FairMockVirtualMC::CurrentVolPath () inline virtual
Definition at line 98 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::DefineIon (const char * , Int_t , Int_t , Int_t , Double_t , Double_t) inline virtual
Definition at line 77 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::DefineOpSurface (const char * , EMCOpSurfaceModel , EMCOpSurfaceType , EMCOpSurfaceFinish , Double_t) inline virtual
Definition at line 54 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::DefineParticle (Int_t , const char * , TMCParticleType , Double_t , Double_t , Double_t) inline virtual
Definition at line 75 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::DefineParticle (Int_t , const char * , TMCParticleType , Double_t , Double_t , Double_t , const TString & , Double_t , Int_t , Int_t , Int_t , Int_t , Int_t , Int_t , Int_t , Int_t , Bool_t , Bool_t , const TString & , Int_t , Double_t , Double_t) inline virtual
Definition at line 76 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::Edep () const inline virtual
Definition at line 115 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::Etot () const inline virtual
Definition at line 119 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::ForceDecayTime (Float_t) inline virtual
Definition at line 93 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gckmat (Int_t , char *) inline virtual
Definition at line 46 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gdtom (Float_t * , Float_t * , Int_t) inline virtual
Definition at line 104 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gdtom (Double_t * , Double_t * , Int_t) inline virtual
Definition at line 105 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::GetMaterial (const TString & , TString & , Int_t & , Double_t & , Double_t & , Double_t & , Double_t & , Double_t & , TArrayD &) inline virtual
Definition at line 62 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::GetMaxNStep () const inline virtual
Definition at line 107 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::GetMedium (const TString & , TString & , Int_t & , Int_t & , Int_t & , Int_t & , Double_t & , Double_t & , Double_t & , Double_t & , Double_t & , Double_t & , TArrayD &) inline virtual
Definition at line 63 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::GetSecondary (Int_t , Int_t & , TLorentzVector & , TLorentzVector &) inline virtual
Definition at line 129 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::GetShape (const TString & , TString & , TArrayD &) inline virtual
Definition at line 61 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::GetTransformation (const TString & , TGeoHMatrix &) inline virtual
Definition at line 60 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gfmate (Int_t , char * , Float_t & , Float_t & , Float_t & , Float_t & , Float_t & , Float_t * , Int_t &) inline virtual
Definition at line 44 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gfmate (Int_t , char * , Double_t & , Double_t & , Double_t & , Double_t & , Double_t & , Double_t * , Int_t &) inline virtual
Definition at line 45 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gmtod (Float_t * , Float_t * , Int_t) inline virtual
Definition at line 102 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gmtod (Double_t * , Double_t * , Int_t) inline virtual
Definition at line 103 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gsbool (const char * , const char *) inline virtual
Definition at line 51 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gsdvn (const char * , const char * , Int_t , Int_t) inline virtual
Definition at line 40 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gsdvn2 (const char * , const char * , Int_t , Int_t , Double_t , Int_t) inline virtual
Definition at line 41 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gsdvt (const char * , const char * , Double_t , Int_t , Int_t , Int_t) inline virtual
Definition at line 42 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gsdvt2 (const char * , const char * , Double_t , Int_t , Double_t , Int_t , Int_t) inline virtual
Definition at line 43 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gsord (const char * , Int_t) inline virtual
Definition at line 47 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gspos (const char * , Int_t , const char * , Double_t , Double_t , Double_t , Int_t , const char *) inline virtual
Definition at line 48 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gsposp (const char * , Int_t , const char * , Double_t , Double_t , Double_t , Int_t , const char * , Float_t * , Int_t) inline virtual
Definition at line 49 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gsposp (const char * , Int_t , const char * , Double_t , Double_t , Double_t , Int_t , const char * , Double_t * , Int_t) inline virtual
Definition at line 50 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Gstpar (Int_t , const char * , Double_t) inline virtual
Definition at line 37 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::Gsvolu (const char * , const char * , Int_t , Float_t * , Int_t) inline virtual
Definition at line 38 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::Gsvolu (const char * , const char * , Int_t , Double_t * , Int_t) inline virtual
Definition at line 39 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::IdFromPDG (Int_t) const inline virtual
Definition at line 80 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Init () inline virtual
Definition at line 133 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::InitLego () inline virtual
Definition at line 137 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsCollectTracks () const inline virtual
Definition at line 139 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsNewTrack () const inline virtual
Definition at line 120 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsTrackAlive () const inline virtual
Definition at line 127 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsTrackDisappeared () const inline virtual
Definition at line 125 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsTrackEntering () const inline virtual
Definition at line 122 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsTrackExiting () const inline virtual
Definition at line 123 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsTrackInside () const inline virtual
Definition at line 121 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsTrackOut () const inline virtual
Definition at line 124 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::IsTrackStop () const inline virtual
Definition at line 126 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
void FairMockVirtualMC::Material (Int_t & , const char * , Double_t , Double_t , Double_t , Double_t , Double_t , Float_t * , Int_t) inline
Definition at line 30 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
void FairMockVirtualMC::Material (Int_t & , const char * , Double_t , Double_t , Double_t , Double_t , Double_t , Double_t * , Int_t) inline
Definition at line 31 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Matrix (Int_t & , Double_t , Double_t , Double_t , Double_t , Double_t , Double_t) inline virtual
Definition at line 36 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::MaxStep () const inline virtual
Definition at line 106 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
void FairMockVirtualMC::Medium (Int_t & , const char * , Int_t , Int_t , Int_t , Double_t , Double_t , Double_t , Double_t , Double_t , Double_t , Float_t * , Int_t) inline
Definition at line 34 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::Medium (Int_t & , const char * , Int_t , Int_t , Int_t , Double_t , Double_t , Double_t , Double_t , Double_t , Double_t , Double_t * , Int_t) inline virtual
Definition at line 35 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::MediumId (const char *) const inline virtual
Definition at line 67 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
void FairMockVirtualMC::Mixture (Int_t & , const char * , Float_t * , Float_t * , Double_t , Int_t , Float_t *) inline
Definition at line 32 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
void FairMockVirtualMC::Mixture (Int_t & , const char * , Double_t * , Double_t * , Double_t , Int_t , Double_t *) inline
Definition at line 33 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::NofVolDaughters (const char *) const inline virtual
Definition at line 70 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::NofVolumes () const inline virtual
Definition at line 68 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::NSecondaries () const inline virtual
Definition at line 128 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::ParticleCharge (Int_t) const inline virtual
Definition at line 84 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::ParticleLifeTime (Int_t) const inline virtual
Definition at line 85 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::ParticleMass (Int_t) const inline virtual
Definition at line 83 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual TMCParticleType FairMockVirtualMC::ParticleMCType (Int_t) const inline virtual
Definition at line 86 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual TString FairMockVirtualMC::ParticleName (Int_t) const inline virtual
Definition at line 82 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::PDGFromId (Int_t) const inline virtual
Definition at line 81 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::ProcessEvent () inline virtual
Definition at line 135 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::ProcessRun (Int_t) inline virtual
Definition at line 136 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual TMCProcess FairMockVirtualMC::ProdProcess (Int_t) const inline virtual
Definition at line 130 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::SecondariesAreOrdered () const inline virtual
Definition at line 132 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetBorderSurface (const char * , const char * , int , const char * , int , const char *) inline virtual
Definition at line 55 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetCerenkov (Int_t , Int_t , Float_t * , Float_t * , Float_t * , Float_t *) inline virtual
Definition at line 52 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetCerenkov (Int_t , Int_t , Double_t * , Double_t * , Double_t * , Double_t *) inline virtual
Definition at line 53 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetCollectTracks (Bool_t) inline virtual
Definition at line 138 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::SetCut (const char * , Double_t) inline virtual
Definition at line 73 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::SetDecayMode (Int_t , Float_t * , Int_t(*) [3]) inline virtual
Definition at line 78 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetMaterialProperty (Int_t , const char * , Int_t , Double_t * , Double_t *) inline virtual
Definition at line 57 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetMaterialProperty (Int_t , const char * , Double_t) inline virtual
Definition at line 58 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetMaterialProperty (const char * , const char * , Int_t , Double_t * , Double_t *) inline virtual
Definition at line 59 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetMaxNStep (Int_t) inline virtual
Definition at line 91 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetMaxStep (Double_t) inline virtual
Definition at line 90 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Bool_t FairMockVirtualMC::SetProcess (const char * , Int_t) inline virtual
Definition at line 74 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
void FairMockVirtualMC::SetRootGeometry ()
Definition at line 31 of file FairMockVirtualMC.cxx.
References fImportRootGeometry.
 {
   // Notify Geant3 about use of TGeo geometry.
   // The materials and tracking medias will be imported from
   // TGeo at FinishGeometry().
   fImportRootGeometry = kTRUE;
 }
virtual void FairMockVirtualMC::SetSkinSurface (const char * , const char * , const char *) inline virtual
Definition at line 56 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetUserDecay (Int_t) inline virtual
Definition at line 92 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::SetUserParameters (Bool_t) inline virtual
Definition at line 65 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::StepProcesses (TArrayI &) const inline virtual
Definition at line 131 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::StopEvent () inline virtual
Definition at line 88 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
void FairMockVirtualMC::StopExecution () const
Definition at line 79 of file FairMockVirtualMC.cxx.
References FairLogger::Fatal(), fLogger, and MESSAGE_ORIGIN.
Referenced by BuildPhysics(), CurrentEvent(), CurrentMaterial(), CurrentMedium(), CurrentVolName(), CurrentVolOffName(), CurrentVolPath(), DefineIon(), DefineOpSurface(), DefineParticle(), Edep(), Etot(), ForceDecayTime(), Gckmat(), Gdtom(), GetMaterial(), GetMaxNStep(), GetMedium(), GetSecondary(), GetShape(), GetTransformation(), Gfmate(), Gmtod(), Gsbool(), Gsdvn(), Gsdvn2(), Gsdvt(), Gsdvt2(), Gsord(), Gspos(), Gsposp(), Gstpar(), Gsvolu(), IdFromPDG(), Init(), InitLego(), IsCollectTracks(), IsNewTrack(), IsTrackAlive(), IsTrackDisappeared(), IsTrackEntering(), IsTrackExiting(), IsTrackInside(), IsTrackOut(), IsTrackStop(), Material(), Matrix(), MaxStep(), Medium(), MediumId(), Mixture(), NofVolDaughters(), NofVolumes(), NSecondaries(), ParticleCharge(), ParticleLifeTime(), ParticleMass(), ParticleMCType(), ParticleName(), PDGFromId(), ProcessEvent(), ProcessRun(), ProdProcess(), SecondariesAreOrdered(), SetBorderSurface(), SetCerenkov(), SetCollectTracks(), SetCut(), SetDecayMode(), SetMaterialProperty(), SetMaxNStep(), SetMaxStep(), SetProcess(), SetSkinSurface(), SetUserDecay(), SetUserParameters(), StepProcesses(), StopEvent(), StopRun(), StopTrack(), TrackCharge(), TrackLength(), TrackMass(), TrackMomentum(), TrackPid(), TrackPosition(), TrackStep(), TrackTime(), VolDaughterCopyNo(), VolDaughterName(), VolId2Mate(), VolName(), WriteEuclid(), and Xsec().
 {
   fLogger->Fatal(MESSAGE_ORIGIN,"This function is not yet implemented.");
 }
virtual void FairMockVirtualMC::StopRun () inline virtual
Definition at line 89 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::StopTrack () inline virtual
Definition at line 87 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::TrackCharge () const inline virtual
Definition at line 117 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::TrackLength () const inline virtual
Definition at line 113 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::TrackMass () const inline virtual
Definition at line 118 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::TrackMomentum (TLorentzVector &) const inline virtual
Definition at line 110 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::TrackMomentum (Double_t & , Double_t & , Double_t & , Double_t &) const inline virtual
Definition at line 111 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::TrackPid () const inline virtual
Definition at line 116 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::TrackPosition (TLorentzVector &) const inline virtual
Definition at line 108 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::TrackPosition (Double_t & , Double_t & , Double_t &) const inline virtual
Definition at line 109 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::TrackStep () const inline virtual
Definition at line 112 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::TrackTime () const inline virtual
Definition at line 114 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Int_t FairMockVirtualMC::VolDaughterCopyNo (const char * , Int_t) const inline virtual
Definition at line 72 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual const char* FairMockVirtualMC::VolDaughterName (const char * , Int_t) const inline virtual
Definition at line 71 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
Int_t FairMockVirtualMC::VolId (const Text_t * name) const
Definition at line 39 of file FairMockVirtualMC.cxx.
References fMCGeo.
 {
   //
   // Return the unique numeric identifier for volume name
   //
   char sname[20];
   Int_t len = strlen(name)-1;
   if (name[len] != ' ') { return fMCGeo->VolId(name); }
   strncpy(sname, name, len);
   sname[len] = 0;
   return fMCGeo->VolId(sname);
 }
virtual Int_t FairMockVirtualMC::VolId2Mate (Int_t) const inline virtual
Definition at line 69 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual const char* FairMockVirtualMC::VolName (Int_t) const inline virtual
Definition at line 66 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual void FairMockVirtualMC::WriteEuclid (const char * , const char * , Int_t , Int_t) inline virtual
Definition at line 64 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
virtual Double_t FairMockVirtualMC::Xsec (char * , Double_t , Int_t , Int_t) inline virtual
Definition at line 79 of file FairMockVirtualMC.h.
References StopExecution().
 {StopExecution();}
Member Data Documentation
Bool_t FairMockVirtualMC::fImportRootGeometry protected
Definition at line 143 of file FairMockVirtualMC.h.
Referenced by SetRootGeometry().
FairLogger* FairMockVirtualMC::fLogger protected
Definition at line 144 of file FairMockVirtualMC.h.
Referenced by StopExecution().
TGeoMCGeometry* FairMockVirtualMC::fMCGeo protected
Definition at line 142 of file FairMockVirtualMC.h.
Referenced by VolId().
The documentation for this class was generated from the following files:
FairMockVirtualMC.h
FairMockVirtualMC.cxx