FairRoot: FairTestNewOutputHandler Class Reference
FairTestNewOutputHandler Class Reference
#include <FairTestNewOutputHandler.h>
Public Member Functions
FairTestNewOutputHandler (bool captureStdErr=true, bool captureStdOut=false)
~FairTestNewOutputHandler ()
std::string GetCaptureLine (int line)
int GetNumberOfLines ()
Private Member Functions
void Split ()
Private Attributes
std::streambuf * old_cout
std::streambuf * old_cerr
boost::test_tools::output_test_stream output
std::vector< std::string > fLineVector
bool fCaptureEnded
bool fCaptureStdOut
bool fCaptureStdErr
Detailed Description
Definition at line 16 of file FairTestNewOutputHandler.h.
Constructor & Destructor Documentation
FairTestNewOutputHandler::FairTestNewOutputHandler (bool captureStdErr = true, bool captureStdOut = false)
Definition at line 14 of file FairTestNewOutputHandler.cxx.
References fCaptureStdErr, fCaptureStdOut, and output.
   : old_cout(std::cout.rdbuf()),  // backup orig cout streambuf in any case
     old_cerr(std::cerr.rdbuf()),  // backup orig cout streambuf in any case
     output(),
     fLineVector(),
     fCaptureEnded(false),
     fCaptureStdOut(captureStdOut),
     fCaptureStdErr(captureStdErr)
 {
   if (fCaptureStdOut) {
     std::cout.rdbuf(output.rdbuf());  // assign boost test streambuf to cout
   }
   if (fCaptureStdErr) {
     std::cerr.rdbuf(output.rdbuf());  // assign boost test streambuf to cout
   }
 }
FairTestNewOutputHandler::~FairTestNewOutputHandler ()
Definition at line 32 of file FairTestNewOutputHandler.cxx.
References old_cerr, and old_cout.
 {
   std::cout.rdbuf(old_cout);         // reset original cout streambuf
   std::cerr.rdbuf(old_cerr);         // reset original cerr streambuf
 }
Member Function Documentation
std::string FairTestNewOutputHandler::GetCaptureLine (int line)
Definition at line 38 of file FairTestNewOutputHandler.cxx.
References fLineVector, and Split().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckScreenOutput(), and TEST().
 {
   Split();
   return fLineVector[line];
 }
int FairTestNewOutputHandler::GetNumberOfLines ()
Definition at line 44 of file FairTestNewOutputHandler.cxx.
References fLineVector, and Split().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckScreenOutput(), and TEST().
 {
   Split();
   return fLineVector.size()-1;
 }
void FairTestNewOutputHandler::Split () private
Definition at line 50 of file FairTestNewOutputHandler.cxx.
References fCaptureEnded, fLineVector, old_cerr, old_cout, and output.
Referenced by GetCaptureLine(), and GetNumberOfLines().
 {
   if (!fCaptureEnded) {
     std::cout.rdbuf(old_cout); // when capturing cout and cerr is finished
     std::cerr.rdbuf(old_cerr); // reset original setting
     // split the string buffer on new lines
     std::string s = output.str();
     boost::split(fLineVector, s, boost::algorithm::is_any_of("\n"));
     fCaptureEnded=true;
   }
 }
Member Data Documentation
bool FairTestNewOutputHandler::fCaptureEnded private
Definition at line 36 of file FairTestNewOutputHandler.h.
Referenced by Split().
bool FairTestNewOutputHandler::fCaptureStdErr private
Definition at line 38 of file FairTestNewOutputHandler.h.
Referenced by FairTestNewOutputHandler().
bool FairTestNewOutputHandler::fCaptureStdOut private
Definition at line 37 of file FairTestNewOutputHandler.h.
Referenced by FairTestNewOutputHandler().
std::vector< std::string > FairTestNewOutputHandler::fLineVector private
Definition at line 34 of file FairTestNewOutputHandler.h.
Referenced by GetCaptureLine(), GetNumberOfLines(), and Split().
std::streambuf* FairTestNewOutputHandler::old_cerr private
Definition at line 30 of file FairTestNewOutputHandler.h.
Referenced by Split(), and ~FairTestNewOutputHandler().
std::streambuf* FairTestNewOutputHandler::old_cout private
Definition at line 29 of file FairTestNewOutputHandler.h.
Referenced by Split(), and ~FairTestNewOutputHandler().
boost::test_tools::output_test_stream FairTestNewOutputHandler::output private
Definition at line 32 of file FairTestNewOutputHandler.h.
Referenced by FairTestNewOutputHandler(), and Split().
The documentation for this class was generated from the following files:
FairTestNewOutputHandler.h
FairTestNewOutputHandler.cxx