FairRoot: FairAnaSelector Class Reference
FairAnaSelector Class Reference
#include <FairAnaSelector.h>
Public Member Functions
FairAnaSelector (TTree *=0)
virtual ~FairAnaSelector ()
virtual Int_t Version () const
virtual void Begin (TTree *tree)
virtual void SlaveBegin (TTree *tree)
virtual void Init (TTree *tree)
virtual Bool_t Notify ()
virtual Bool_t Process (Long64_t entry)
virtual Int_t GetEntry (Long64_t entry, Int_t getall=0)
virtual void SetOption (const char *option)
virtual void SetObject (TObject *obj)
virtual void SetInputList (TList *input)
virtual TList * GetOutputList () const
virtual void SlaveTerminate ()
virtual void Terminate ()
void SetFairRunAnaProof (FairRunAnaProof *runAna)
Public Attributes
TProofOutputFile * fProofFile
TFile * fFile
TTree * fChain
FairRunAnaProof * fRunAna
pointer to the analyzed TTree or TChain
Protected Attributes
FairLogger * fLogger
Private Member Functions
FairAnaSelector (const FairAnaSelector &)
FairAnaSelector operator= (const FairAnaSelector &)
ClassDef (FairAnaSelector, 0)
Detailed Description
Definition at line 35 of file FairAnaSelector.h.
Constructor & Destructor Documentation
FairAnaSelector::FairAnaSelector (TTree * = 0) inline
Definition at line 43 of file FairAnaSelector.h.
 : fLogger(FairLogger::GetLogger()), fProofFile(0), fFile(0), fChain(0), fRunAna(NULL) { }
virtual FairAnaSelector::~FairAnaSelector () inline virtual
Definition at line 44 of file FairAnaSelector.h.
 { }
FairAnaSelector::FairAnaSelector (const FairAnaSelector &) private
Member Function Documentation
void FairAnaSelector::Begin (TTree * tree) virtual
Definition at line 165 of file FairAnaSelector.cxx.
References FairLogger::endl(), INFO, and LOG.
 {
   // The Begin() function is called at the start of the query.
   // When running with PROOF Begin() is only called on the client.
   // The tree argument is deprecated (on PROOF 0 is passed).
   LOG(INFO) << "FairAnaSelector::Begin()" << FairLogger::endl;
 }
FairAnaSelector::ClassDef (FairAnaSelector , 0) private
virtual Int_t FairAnaSelector::GetEntry (Long64_t entry, Int_t getall = 0) inline virtual
Definition at line 53 of file FairAnaSelector.h.
{
       return fChain ? fChain->GetTree()->GetEntry(entry, getall) : 0;
     }
virtual TList* FairAnaSelector::GetOutputList () const inline virtual
Definition at line 65 of file FairAnaSelector.h.
{
       return fOutput;
     }
void FairAnaSelector::Init (TTree * tree) virtual
Definition at line 34 of file FairAnaSelector.cxx.
References FairLogger::endl(), fFile, fRunAna, FairRunAna::GetContainerStatic(), INFO, FairRunAna::InitContainers(), LOG, FairParAsciiFileIo::open(), FairParRootFileIo::open(), FairRuntimeDb::setFirstInput(), FairRunAnaProof::SetInTree(), FairRuntimeDb::setSecondInput(), and WARNING.
 {
   // The Init() function is called when the selector needs to initialize
   // a new tree or chain. Typically here the branch addresses and branch
   // pointers of the tree will be set.
   // It is normally not necessary to make changes to the generated
   // code, but the routine can be extended by the user if needed.
   // Init() will be called many times when running on PROOF
   // (once per file to be processed).
   if (!tree) {
     LOG(WARNING) << "FairAnaSelector::Init(): There is no tree." << FairLogger::endl;
     return;
   } else {
     LOG(INFO) << "FairAnaSelector::Init(): Got tree     : \"" << tree << "\"" << FairLogger::endl;
     LOG(INFO) << "FairAnaSelector::Init(): Tree name    : \"" << tree->GetName() << "\"" << FairLogger::endl;
     LOG(INFO) << "FairAnaSelector::Init(): Tree title   : \"" << tree->GetTitle() << "\"" << FairLogger::endl;
     LOG(INFO) << "FairAnaSelector::Init(): Tree filename: \"" << tree->GetCurrentFile()->GetName() << "\"" << FairLogger::endl;
   }
   if ( fRunAna ) {
     LOG(INFO) << "FairAnaSelector::Init(): Already have fRunAna." << FairLogger::endl;
     LOG(INFO) << "FairAnaSelector::Init(): SetInTree(" << tree << ")" << FairLogger::endl;
     fRunAna->SetInTree(tree);
     LOG(INFO) << "FairAnaSelector::Init(): SetInTree done" << FairLogger::endl;
     LOG(INFO) << "FairAnaSelector::Init(): Containers static? " << (fRunAna->GetContainerStatic()?"YES":"NO") << FairLogger::endl;
     if ( !fRunAna->GetContainerStatic() ) {
       fRunAna->InitContainers();
     }
   } else {
     LOG(INFO) << "FairAnaSelector::Init(): Have to create fRunAna." << FairLogger::endl;
     TString vmcPath = gSystem->Getenv("VMCWORKDIR");
     TNamed* contStat    = (TNamed*) fInput->FindObject("FAIRRUNANA_fContainerStatic");
     TNamed* outStat     = (TNamed*) fInput->FindObject("FAIRRUNANA_fProofOutputStatus");
     TNamed* outFile     = (TNamed*) fInput->FindObject("FAIRRUNANA_fOutputFileName");
     TNamed* outDir      = (TNamed*) fInput->FindObject("FAIRRUNANA_fOutputDirectory");
     TNamed* par1Name    = (TNamed*) fInput->FindObject("FAIRRUNANA_fParInput1FName");
     TNamed* par2Name    = (TNamed*) fInput->FindObject("FAIRRUNANA_fParInput2FName");
     TString containerS  = contStat->GetTitle();
     TString outputStat  = outStat->GetTitle();
     TString par1Str     = par1Name->GetTitle();
     TString par2Str     = par2Name->GetTitle();
     TString outFileName = outFile->GetTitle();
     TString outDirName  = outDir->GetTitle();
     LOG(INFO) << "FairAnaSelector::Init(): out status   : \"" << outputStat.Data() << "\"" << FairLogger::endl;
     LOG(INFO) << "FairAnaSelector::Init(): par1 file    : \"" << par1Str.Data() << "\"" << FairLogger::endl;
     LOG(INFO) << "FairAnaSelector::Init(): par2 file    : \"" << par2Str.Data() << "\"" << FairLogger::endl;
     LOG(INFO) << "FairAnaSelector::Init(): OutputFile option \"" << outputStat.Data() << "\" RECOGNIZED" << FairLogger::endl;
     outFileName.Remove(outFileName.Length()-5);
     TString outputFileName = Form("%s/%s_worker_%s.root",outDirName.Data(),outFileName.Data(),gProofServ->GetOrdinal());
     LOG(INFO) << "FairAnaSelector::Init(): output will go to file: \"" << outputFileName.Data() << "\"" << FairLogger::endl;
     fFile = TFile::Open(outputFileName.Data(),"RECREATE");
     fRunAna = new FairRunAnaProof("RunOnProofWorker");
     LOG(INFO) << "FairAnaSelector::Init(): SetInTree(" << tree << ")" << FairLogger::endl;
     fRunAna->SetInTree(tree);
     LOG(INFO) << "FairAnaSelector::Init(): SetInTree done" << FairLogger::endl;
     fRunAna->SetOutputFile(fFile);
     if ( containerS == "kTRUE" ) {
       fRunAna->SetContainerStatic(kTRUE);
     } else {
       fRunAna->SetContainerStatic(kFALSE);
     }
     // -----  Parameter database   --------------------------------------------
     FairRuntimeDb* rtdb = fRunAna->GetRuntimeDb();
     if ( par1Str.Contains(".root") ) {
       FairParRootFileIo* parInput1 = new FairParRootFileIo();
       parInput1->open(par1Str.Data());
       rtdb->setFirstInput (parInput1);
     }
     if ( par1Str.Contains(".par") ) {
       FairParAsciiFileIo* parInput1 = new FairParAsciiFileIo();
       parInput1->open(par1Str.Data(),"in");
       rtdb->setFirstInput (parInput1);
     }
     if ( par2Str.Contains(".root") ) {
       FairParRootFileIo* parInput2 = new FairParRootFileIo();
       parInput2->open(par2Str.Data());
       rtdb->setSecondInput(parInput2);
     }
     if ( par2Str.Contains(".par") ) {
       FairParAsciiFileIo* parInput2 = new FairParAsciiFileIo();
       parInput2->open(par2Str.Data(),"in");
       rtdb->setSecondInput(parInput2);
     }
     // ------------------------------------------------------------------------
     FairTask* fairTaskList = dynamic_cast<FairTask*>(fInput->FindObject("FairTaskList"));
     if ( fairTaskList != 0 ) {
       LOG(INFO) << "FairAnaSelector::Init(): FairTask = \"" << fairTaskList << "\"" << FairLogger::endl;
       fRunAna->SetTask(fairTaskList);
     }
     LOG(INFO) << "FairAnaSelector::Init(): vvvvv fRunAna->Init() vvvvv" << FairLogger::endl;
     fRunAna->Init();
     LOG(INFO) << "FairAnaSelector::Init(): ^^^^^ fRunAna->Init() ^^^^^" << FairLogger::endl;
   }
 }
Bool_t FairAnaSelector::Notify () virtual
Definition at line 151 of file FairAnaSelector.cxx.
References FairLogger::endl(), INFO, and LOG.
 {
   // The Notify() function is called when a new file is opened. This
   // can be either for a new TTree in a TChain or when when a new TTree
   // is started when using PROOF. It is normally not necessary to make changes
   // to the generated code, but the routine can be extended by the
   // user if needed. The return value is currently not used.
   LOG(INFO) << "FairAnaSelector::Notify()" << FairLogger::endl;
   return kTRUE;
 }
FairAnaSelector FairAnaSelector::operator= (const FairAnaSelector &) private
Bool_t FairAnaSelector::Process (Long64_t entry) virtual
Definition at line 191 of file FairAnaSelector.cxx.
References fRunAna, and FairRunAnaProof::RunOneEvent().
 {
   // The Process() function is called for each entry in the tree (or possibly
   // keyed object in the case of PROOF) to be processed. The entry argument
   // specifies which entry in the currently loaded tree is to be processed.
   // It can be passed to either FairAnaSelector::GetEntry() or TBranch::GetEntry()
   // to read either all or the required parts of the data. When processing
   // keyed objects with PROOF, the object is already loaded and is available
   // via the fObject pointer.
   //
   // This function should contain the "body" of the analysis. It can contain
   // simple or elaborate selection criteria, run algorithms on the data
   // of the event and typically fill histograms.
   //
   // The processing can be stopped by calling Abort().
   //
   // Use fStatus to set the return value of TTree::Process().
   //
   // The return value is currently not used.
   //  LOG(INFO) << "FairAnaSelector::Process(): Proceeding to analyze event " << entry << "." << FairLogger::endl;
   fRunAna->RunOneEvent(entry);
   //  LOG(INFO) << "FairAnaSelector::Process(): Event " << entry << " analyzed." << FairLogger::endl;
   return kTRUE;
 }
void FairAnaSelector::SetFairRunAnaProof (FairRunAnaProof * runAna) inline
Definition at line 71 of file FairAnaSelector.h.
{
       fRunAna = runAna;
     }
virtual void FairAnaSelector::SetInputList (TList * input) inline virtual
Definition at line 62 of file FairAnaSelector.h.
{
       fInput = input;
     }
virtual void FairAnaSelector::SetObject (TObject * obj) inline virtual
Definition at line 59 of file FairAnaSelector.h.
{
       fObject = obj;
     }
virtual void FairAnaSelector::SetOption (const char * option) inline virtual
Definition at line 56 of file FairAnaSelector.h.
{
       fOption = option;
     }
void FairAnaSelector::SlaveBegin (TTree * tree) virtual
Definition at line 176 of file FairAnaSelector.cxx.
References FairLogger::endl(), INFO, and LOG.
 {
   // The SlaveBegin() function is called after the Begin() function.
   // When running with PROOF SlaveBegin() is called on each slave server.
   // The tree argument is deprecated (on PROOF 0 is passed).
   LOG(INFO) << "FairAnaSelector::SlaveBegin(): Tree address   : \"" << tree << "\"" << FairLogger::endl;
   // useless, because have no tree anyways in slavebegin, init will be anyways called whenever a new tree comes
   //  Init(tree);
   LOG(INFO) << "FairAnaSelector::SlaveBegin(): finishing" << FairLogger::endl;
 }
void FairAnaSelector::SlaveTerminate () virtual
Definition at line 220 of file FairAnaSelector.cxx.
References FairLogger::endl(), fFile, fProofFile, fRunAna, INFO, LOG, and FairRunAna::TerminateRun().
 {
   // The SlaveTerminate() function is called after all entries or objects
   // have been processed. When running with PROOF SlaveTerminate() is called
   // on each slave server.
   if ( !fRunAna ) {
     return;
   }
   if ( !fProofFile ) {
     LOG(INFO) << "FairAnaSelector::SlaveTerminate(): Calling fRunAna->TerminateRun()" << FairLogger::endl;
     fRunAna->TerminateRun();
   }
   LOG(INFO) << "FairAnaSelector::SlaveTerminate(): fProofFile = \"" << fProofFile << "\"" << FairLogger::endl;
   LOG(INFO) << "FairAnaSelector::SlaveTerminate():      fFile = \"" << fFile << "\"" << FairLogger::endl;
   LOG(INFO) << "FairAnaSelector::SlaveTerminate(): WorkingDirectory = \"" << gSystem->WorkingDirectory() << "\"" << FairLogger::endl;
   if ( fProofFile ) {
     // fOutput->ls();
     // fOutput->Print();
     // fProofFile->Print();
     LOG(INFO) << "FairAnaSelector::SlaveTerminate(): fOutput->Add(fProofFile);" << FairLogger::endl;
     fOutput->Add(fProofFile);
     //    fProofFile->Print();
     LOG(INFO) << "FairAnaSelector::SlaveTerminate(): fFile->Close();" << FairLogger::endl;
     fRunAna->TerminateRun();
     //    fFile->Close();
   }
   LOG(INFO) << "FairAnaSelector::SlaveTerminate(): Finishing..." << FairLogger::endl;
 }
void FairAnaSelector::Terminate () virtual
Definition at line 260 of file FairAnaSelector.cxx.
References FairLogger::endl(), INFO, and LOG.
 {
   // The Terminate() function is the last function to be called during
   // a query. It always runs on the client, it can be used to present
   // the results graphically or save the results to file.
   LOG(INFO) << "FairAnaSelector::Terminate(): fOutput->ls()" << FairLogger::endl;
   fOutput->ls();
   LOG(INFO) << "FairAnaSelector::Terminate(): -------------" << FairLogger::endl;
 }
virtual Int_t FairAnaSelector::Version () const inline virtual
Definition at line 45 of file FairAnaSelector.h.
{
       return 1;
     }
Member Data Documentation
TTree* FairAnaSelector::fChain
Definition at line 40 of file FairAnaSelector.h.
TFile* FairAnaSelector::fFile
Definition at line 39 of file FairAnaSelector.h.
Referenced by Init(), and SlaveTerminate().
FairLogger* FairAnaSelector::fLogger protected
Fair Logger
Definition at line 77 of file FairAnaSelector.h.
TProofOutputFile* FairAnaSelector::fProofFile
Definition at line 38 of file FairAnaSelector.h.
Referenced by SlaveTerminate().
FairRunAnaProof* FairAnaSelector::fRunAna
pointer to the analyzed TTree or TChain
Definition at line 41 of file FairAnaSelector.h.
Referenced by Init(), Process(), and SlaveTerminate().
The documentation for this class was generated from the following files:
FairAnaSelector.h
FairAnaSelector.cxx