FairRroot: FairRuntimeDb Class Reference
FairRuntimeDb Class Reference
list of container factories
#include <FairRuntimeDb.h>
Public Member Functions
~FairRuntimeDb (void)
Bool_t addParamContext (const char *)
void printParamContexts ()
void addContFactory (FairContFact *)
FairContFact * getContFactory (const Text_t *)
Bool_t addContainer (FairParSet *)
FairParSet * getContainer (const Text_t *)
FairParSet * findContainer (const char *)
void removeContainer (Text_t *)
void removeAllContainers (void)
Bool_t initContainers (Int_t runId, Int_t refId=-1, const Text_t *fileName="")
void setContainersStatic (Bool_t f=kTRUE)
Bool_t writeContainers (void)
Bool_t writeContainer (FairParSet *, FairRtdbRun *, FairRtdbRun *refRun=0)
FairRtdbRun * addRun (Int_t runId, Int_t refId=-1)
FairRtdbRun * getRun (Int_t)
FairRtdbRun * getRun (Text_t *)
FairRtdbRun * getCurrentRun (void)
Text_t const * getCurrentFileName ()
void clearRunList (void)
void removeRun (Text_t *)
Bool_t setInputVersion (Int_t run, Text_t *container, Int_t version, Int_t inputNumber)
Bool_t setRootOutputVersion (Int_t run, Text_t *container, Int_t version)
void setVersionsChanged (Bool_t f=kTRUE)
void resetInputVersions (void)
void resetOutputVersions (void)
void resetAllVersions (void)
Bool_t readAll (void)
void writeVersions (void)
void saveOutput (void)
Bool_t setFirstInput (FairParIo *)
Bool_t setSecondInput (FairParIo *)
Bool_t setOutput (FairParIo *)
FairParIo * getFirstInput (void)
FairParIo * getSecondInput (void)
FairParIo * getOutput (void)
void closeFirstInput (void)
void closeSecondInput (void)
void closeOutput (void)
void activateParIo (FairParIo *)
TList * getListOfContainers ()
void print (void)
Int_t findOutputVersion (FairParSet *)
Static Public Member Functions
static FairRuntimeDb * instance (void)
Protected Types
enum ParamIOType { UNKNOWN_Type = 0, AsciiFileOutput = 1, RootFileOutput = 2, RootTSQLOutput = 3 }
Protected Member Functions
FairRuntimeDb (void)
Protected Attributes
TList * containerList
TList * runs
FairParIo * firstInput
FairParIo * secondInput
FairParIo * output
FairRtdbRun * currentRun
TString currentFileName
Bool_t versionsChanged
Bool_t isRootFileOutput
FairLogger * fLogger
ParamIOType ioType
Private Member Functions
FairRuntimeDb (const FairRuntimeDb &M)
FairRuntimeDb & operator= (const FairRuntimeDb &)
Bool_t initContainers (void)
Static Private Attributes
static FairRuntimeDb * gRtdb
Detailed Description
list of container factories
Definition at line 25 of file FairRuntimeDb.h.
Member Enumeration Documentation
enum FairRuntimeDb::ParamIOType protected
Select which IO type to use.
Enumerator
UNKNOWN_Type
AsciiFileOutput
RootFileOutput
RootTSQLOutput
Definition at line 47 of file FairRuntimeDb.h.
                  {
       UNKNOWN_Type    = 0,
       AsciiFileOutput = 1, // Ascii in-out-put
       RootFileOutput  = 2, // Root Files
       RootTSQLOutput  = 3  // Use a TSQL db
     } ParamIOType;
Constructor & Destructor Documentation
FairRuntimeDb::FairRuntimeDb (void) protected
Definition at line 65 of file FairRuntimeDb.cxx.
References gRtdb.
   :TObject(),
    containerList(new TList()),
    runs(new TList()),
    firstInput(NULL),
    secondInput(NULL),
    output(NULL),
    currentRun(NULL),
    currentFileName(""),
    versionsChanged(kFALSE),
    isRootFileOutput(kFALSE),
    fLogger(FairLogger::GetLogger()),
    ioType(UNKNOWN_Type)
 {
   gRtdb=this;
 }
FairRuntimeDb::~FairRuntimeDb (void)
Definition at line 82 of file FairRuntimeDb.cxx.
References closeFirstInput(), closeOutput(), closeSecondInput(), containerList, FairParSet::GetName(), gRtdb, FairParSet::isOwned(), removeContainer(), and runs.
 {
   // destructor
   // deletes the list of runs and all containers
   closeFirstInput();
   closeSecondInput();
   closeOutput();
   if (containerList) {
     TIter next(containerList);
     FairParSet* cont;
     while ((cont=(FairParSet*)next())) {
       Text_t* name=(char*)cont->GetName();
       if (!cont->isOwned()) { removeContainer(name); }
     }
     delete containerList;
   }
   if (runs) {
     runs->Delete();
     delete runs;
   }
   gRtdb=0;
 }
FairRuntimeDb::FairRuntimeDb (const FairRuntimeDb & M) private
Member Function Documentation
void FairRuntimeDb::activateParIo (FairParIo * io)
Definition at line 795 of file FairRuntimeDb.cxx.
References FairContFact::activateParIo(), contFactories, FairParIo::getDetParIo(), and FairParIo::setDetParIo().
Referenced by FairParAsciiFileIo::open(), and FairParRootFileIo::open().
 {
   // activates the detector I/O
   const char* ioName=io->IsA()->GetName();
   FairDetParIo* po=io->getDetParIo("FairGenericParIo");
   if (!po) {
     if (strcmp(ioName,"FairParRootFileIo")==0) {
       FairDetParRootFileIo* pn=
         new FairGenericParRootFileIo(((FairParRootFileIo*)io)->getParRootFile());
       io->setDetParIo(pn);
     } else if (strcmp(ioName,"FairParAsciiFileIo")==0) {
       FairDetParAsciiFileIo* pn=
         new FairGenericParAsciiFileIo(((FairParAsciiFileIo*)io)->getFile());
       io->setDetParIo(pn);
     }
     // else if(strcmp(ioName,"FairParTSQLIo") == 0) {
     //  std::cout << "\n\n\n\t TSQL versie is called en nu de rest \n\n";
     //  FairDetParTSQLIo* pn = new FairGenericParTSQLIo();
     //  io->setDetParIo(pn);
     //}
   }
   TIter next(&contFactories);
   FairContFact* fact;
   while((fact=(FairContFact*)next())) {
     fact->activateParIo(io);
   }
 }
Bool_t FairRuntimeDb::addContainer (FairParSet * container)
Definition at line 142 of file FairRuntimeDb.cxx.
References FairRtdbRun::addParVersion(), containerList, FairParSet::GetName(), FairRtdbRun::getParVersion(), and runs.
Referenced by FairContFact::getContainer().
 {
   // adds a container to the list of containers
   //cout << "-I- name parset # " << container->GetName()<< endl;
   Text_t* name=(char*)container->GetName();
   if (!containerList->FindObject(name)) {
     containerList->Add(container);
     TIter next(runs);
     FairRtdbRun* run;
     FairParVersion* vers;
     while ((run=(FairRtdbRun*)next())) {
       if (!run->getParVersion(name)) {
         vers=new FairParVersion(name);
         run->addParVersion(vers);
       }
     }
     //cout << "-I- RTDB entries in list# " <<  containerList->GetEntries() <<"\n" ;
     return kTRUE;
   }
   Warning("addContainer(FairParSet*)","Container %s already exists!",name);
   return kFALSE;
 }
void FairRuntimeDb::addContFactory (FairContFact * fact)
Definition at line 105 of file FairRuntimeDb.cxx.
References contFactories, FairLogger::Debug(), fLogger, and MESSAGE_ORIGIN.
Referenced by FairBaseContFact::FairBaseContFact(), FairDbTutContFact::FairDbTutContFact(), FairDbTutContFact2::FairDbTutContFact2(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet2ContFact::FairTutorialDet2ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), MyPassiveContFact::MyPassiveContFact(), and NewDetectorContFact::NewDetectorContFact().
 {
   // Adds a container factory to the list of factories
   if (!(contFactories.FindObject(fact->GetName()))) {
     fLogger->Debug( MESSAGE_ORIGIN,"- RTDB container factory %s \n",fact->GetName() );
     contFactories.Add(fact);
   }
 }
Bool_t FairRuntimeDb::addParamContext (const char * context)
Definition at line 119 of file FairRuntimeDb.cxx.
References FairContFact::addContext(), and contFactories.
 {
   // Sets via the container factories the context of all parameter containers,
   // which accept this context
   Bool_t found=kFALSE;
   TIter next(&contFactories);
   FairContFact* fact;
   while((fact=(FairContFact*)next())) {
     if (fact->addContext(context)) { found=kTRUE; }
   }
   Error("addParamContext(const char*)","Unknown context");
   return found;
 }
FairRtdbRun * FairRuntimeDb::addRun (Int_t runId, Int_t refId = -1)
Definition at line 216 of file FairRuntimeDb.cxx.
References FairRtdbRun::addParVersion(), containerList, currentRun, FairParSet::GetName(), getRun(), and runs.
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), and initContainers().
 {
   // adds a run at the end of the list of runs
   // returns a pointer to the run newly added
   FairRtdbRun* run;
   if (refId!=-1) {
     run=getRun(refId);
     if (!run) { addRun(refId); }
   }
   run=getRun(runId);
   if (!run) {
     run=new FairRtdbRun(runId,refId);
     TIter next(containerList);
     FairParSet* cont;
     FairParVersion* vers;
     while ((cont=(FairParSet*)next())) {
       vers=new FairParVersion(((char*)cont->GetName()));
       run->addParVersion(vers);
     }
     runs->Add(run);
     currentRun=run;
   } else { Warning("addRun(Int_t,Int_t)","Run already exists"); }
   return run;
 }
void FairRuntimeDb::clearRunList (void)
Definition at line 266 of file FairRuntimeDb.cxx.
References runs.
 {
   runs->Delete();
 }
void FairRuntimeDb::closeFirstInput (void)
Definition at line 755 of file FairRuntimeDb.cxx.
References FairParIo::cd(), FairParIo::close(), and firstInput.
Referenced by ~FairRuntimeDb().
 {
   if (firstInput) {
     firstInput->cd();
     firstInput->close();
     firstInput=0;
   }
 }
void FairRuntimeDb::closeOutput (void)
Definition at line 783 of file FairRuntimeDb.cxx.
References FairParIo::close(), FairParIo::isAutoWritable(), isRootFileOutput, output, resetOutputVersions(), and saveOutput().
Referenced by ~FairRuntimeDb().
 {
   // calls saveOutput() and deletes then the output
   if (output) {
     if (output->isAutoWritable()) { saveOutput(); }
     output->close();
     resetOutputVersions();
     output=0;
     isRootFileOutput=kFALSE;
   }
 }
void FairRuntimeDb::closeSecondInput (void)
Definition at line 764 of file FairRuntimeDb.cxx.
References FairParIo::cd(), FairParIo::close(), and secondInput.
Referenced by ~FairRuntimeDb().
 {
   if (secondInput) {
     secondInput->cd();
     secondInput->close();
     secondInput=0;
   }
 }
FairParSet * FairRuntimeDb::findContainer (const char * name)
Definition at line 192 of file FairRuntimeDb.cxx.
References containerList.
Referenced by FairContFact::getContainer().
 {
   // returns a pointer to the container called by name
   // The name is the original name of the parameter container eventually concatinated with
   // a non-default context.
   return (FairParSet*)(containerList->FindObject(name));
 }
Int_t FairRuntimeDb::findOutputVersion (FairParSet * cont)
Definition at line 305 of file FairRuntimeDb.cxx.
References currentRun, firstInput, FairParVersion::getInputVersion(), FairParSet::getInputVersion(), FairParSet::GetName(), FairRtdbRun::getParVersion(), FairParVersion::getRootVersion(), FairParSet::hasChanged(), output, and runs.
Referenced by writeContainer().
 {
   Int_t in1=cont->getInputVersion(1);
   Int_t in2=cont->getInputVersion(2);
   FairRtdbRun* run;
   FairParVersion* vers;
   Text_t* name=(char*)cont->GetName();
   Int_t v=0;
   if (in1==-1 && in2==-1) {
     if (cont->hasChanged()) { return 0; }
     else {
       Int_t i=runs->IndexOf(currentRun); //FIXME: This can be optimized with a backwards iter.
       while (i>=0) {
         run=(FairRtdbRun*)runs->At(i);
         vers=run->getParVersion(name);
         if (vers->getInputVersion(1)==in1 && vers->getInputVersion(2)==in2) {
           if ((v=vers->getRootVersion())!=0) { return v; }
         }
         --i;
       }
       return 0;
     }
   }
   if ((firstInput==output) && (in1>0 && in2==-1)) { return in1; }
   TIter next(runs);
  // v=0;
   while ((run=(FairRtdbRun*)next())) {
     vers=run->getParVersion(name);
     if (vers->getInputVersion(1)==in1 && vers->getInputVersion(2)==in2) {
       if ((v=vers->getRootVersion())!=0) { return v; }
     }
   }
   return 0;
 }
FairParSet * FairRuntimeDb::getContainer (const Text_t * name)
Definition at line 173 of file FairRuntimeDb.cxx.
References contFactories, and FairContFact::getContainer().
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairPipe::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairConstField::FillParContainer(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), NewDetector::Initialize(), FairTestDetector::Initialize(), FairTutorialDet2::Initialize(), FairTutorialDet1::Initialize(), FairRutherford::Initialize(), FairTutorialDet4::Initialize(), FairModule::ProcessNodes(), FairTutorialDet2Digitizer::ReInit(), FairTutorialDet4HitProducerIdealMisalign::ReInit(), FairDbTutAccessRtdbTask::SetParContainers(), FairTutorialDet2Digitizer::SetParContainers(), FairTutorialDet4HitProducerIdealMisalign::SetParContainers(), FairTutorialDet4::SetParContainers(), and MyFieldCreator::SetParm().
 {
   // The function loops over the container factories to find the corresponding container
   // with the give name and its context.
   // The name is the original name of the parameter container without the concatination
   // with the context.
   // The factory checks, if the container exists already in the runtime database. Otherwise
   // it will be created and added by the factory.
   // The function returns a pointer to the container or NULL, if not created.
   TIter next(&contFactories);
   FairContFact* fact;
   FairParSet* c=0;
   while(!c && (fact=(FairContFact*)next())) {
     c=fact->getContainer(name);
   }
   if (!c) { Error("getContainer(Text_t*)","Container %s not created!",name); }
   return c;
 }
FairContFact * FairRuntimeDb::getContFactory (const Text_t * FactName)
Definition at line 114 of file FairRuntimeDb.cxx.
References contFactories.
 {
   return ((FairContFact*)contFactories.FindObject(FactName));
 }
Text_t const* FairRuntimeDb::getCurrentFileName () inline
Definition at line 78 of file FairRuntimeDb.h.
 {return currentFileName.Data();}
FairRtdbRun* FairRuntimeDb::getCurrentRun (void) inline
Definition at line 77 of file FairRuntimeDb.h.
References currentRun.
Referenced by FairDetParRootFileIo::findInputVersion().
 {return currentRun;}
FairParIo * FairRuntimeDb::getFirstInput (void)
Definition at line 734 of file FairRuntimeDb.cxx.
Referenced by FairParSet::init(), and FairRunAnaProof::RunOnProof().
 {
   // return a pointer to the first input
   if (firstInput) { firstInput->cd(); }
   return firstInput;
 }
TList* FairRuntimeDb::getListOfContainers () inline
Definition at line 105 of file FairRuntimeDb.h.
References containerList.
Referenced by FairRunOnline::Init(), and FairRunSim::Init().
 {return containerList;}
FairParIo * FairRuntimeDb::getOutput (void)
Definition at line 748 of file FairRuntimeDb.cxx.
References FairParIo::cd(), and output.
Referenced by readAll(), FairParSet::write(), writeContainer(), and writeVersions().
 {
   // return a pointer to the output
   if (output) { output->cd(); }
   return output;
 }
FairRtdbRun * FairRuntimeDb::getRun (Int_t id)
Definition at line 241 of file FairRuntimeDb.cxx.
References runs.
Referenced by addRun(), initContainers(), setInputVersion(), and setRootOutputVersion().
 {
   // returns a pointer to the run called by the run id
   char name[255];
   sprintf(name,"%i",id);
   return (FairRtdbRun*)(runs->FindObject(name));
 }
FairRtdbRun * FairRuntimeDb::getRun (Text_t * name)
Definition at line 249 of file FairRuntimeDb.cxx.
References runs.
 {
   // returns a pointer to the run called by name
   return (FairRtdbRun*)(runs->FindObject(name));
 }
FairParIo * FairRuntimeDb::getSecondInput (void)
Definition at line 741 of file FairRuntimeDb.cxx.
References FairParIo::cd(), and secondInput.
Referenced by FairParSet::init(), and FairRunAnaProof::RunOnProof().
 {
   // return a pointer to the second input
   if (secondInput) { secondInput->cd(); }
   return secondInput;
 }
Bool_t FairRuntimeDb::initContainers (Int_t runId, Int_t refId = -1, const Text_t * fileName = "")
Definition at line 476 of file FairRuntimeDb.cxx.
References addRun(), currentFileName, currentRun, getRun(), FairRtdbRun::getRunId(), initContainers(), FairRtdbRun::setRefRun(), and writeContainers().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunOnline::Reinit(), FairRunAna::Reinit(), and FairMCApplication::SetParTask().
 {
   // loops over the list of containers and calls the init() function of each
   // container if it is not static
   // (typically called by Hades::eventLoop(...))
   if (currentRun && currentRun->getRunId()!=runId) { writeContainers(); }
   FairRtdbRun* run=getRun(runId);
   if (!run) { run=addRun(runId,refId); }
   else {
     run->setRefRun(refId);
     if (refId!=-1 && !getRun(refId)) { addRun(refId); }
   }
   currentRun=run;
   currentFileName=fileName;
   return initContainers();
 }
Bool_t FairRuntimeDb::initContainers (void) private
Definition at line 516 of file FairRuntimeDb.cxx.
References containerList, currentFileName, currentRun, firstInput, FairParSet::GetName(), FairRtdbRun::getRefRun(), getRun(), FairParSet::init(), FairParSet::isStatic(), FairParIo::readVersions(), and secondInput.
Referenced by initContainers(), and readAll().
 {
   // private function
   Text_t* refRunName=(char*)currentRun->getRefRun();
   Int_t len=strlen(refRunName);
   if (len<1) {
     if (firstInput) { firstInput->readVersions(currentRun); }
     if (secondInput) { secondInput->readVersions(currentRun); }
   } else {
     FairRtdbRun* refRun=getRun(refRunName);
     if (firstInput) { firstInput->readVersions(refRun); }
     if (secondInput) { secondInput->readVersions(refRun); }
   }
   TIter next(containerList);
   FairParSet* cont;
   Bool_t rc=kTRUE;
   cout<<'\n'<<"************************************************************* "<<'\n';
   if (currentFileName.IsNull()) {
     cout<<"     initialisation for run id "<<currentRun->GetName();
   } else {
     cout<<"     initialisation for event file "<<currentFileName.Data()<<'\n';
     cout<<"     run id "<<currentRun->GetName();
   }
   if (len>0) { cout << " --> " << refRunName; }
   cout<<'\n'<<"************************************************************* "<<'\n';
   while ((cont=(FairParSet*)next())) {
     cout << "-I- FairRunTimeDB::InitContainer() " << cont->GetName() << endl;
     if (!cont->isStatic()) { rc=cont->init() && rc; }
   }
   if (!rc) { Error("initContainers()","Error occured during initialization"); }
   return rc;
 }
static FairRuntimeDb* FairRuntimeDb::instance (void) static
Referenced by FairBaseContFact::FairBaseContFact(), FairDbTutContFact::FairDbTutContFact(), FairDbTutContFact2::FairDbTutContFact2(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet2ContFact::FairTutorialDet2ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), FairDetParRootFileIo::findInputVersion(), FairContFact::getContainer(), FairTestDetectorRecoTask::GetRtdb(), FairParSet::init(), MyPassiveContFact::MyPassiveContFact(), NewDetectorContFact::NewDetectorContFact(), FairParAsciiFileIo::open(), FairParRootFileIo::open(), FairDetParRootFileIo::write(), and FairParSet::write().
FairRuntimeDb& FairRuntimeDb::operator= (const FairRuntimeDb &) inline private
Definition at line 112 of file FairRuntimeDb.h.
 {return *this;}
void FairRuntimeDb::print (void)
Definition at line 596 of file FairRuntimeDb.cxx.
References containerList, firstInput, FairParSet::GetName(), FairParSet::GetTitle(), output, FairParIo::print(), FairRtdbRun::print(), runs, and secondInput.
 {
   // prints the list of the actual containers, the list of the
   // runs/versions and information about input/output
   cout<<"--------------------------------------------------------------------------------\n";
   cout<<"--------------  actual containers in runtime database  -------------------------\n";
   TIter nextCont(containerList);
   FairParSet* cont;
   cout.setf(ios::left,ios::adjustfield);
   while((cont=(FairParSet*)nextCont())) {
     cout<<setw(45)<<cont->GetName()<<"  "<<cont->GetTitle()<<'\n';
   }
   TIter next(runs);
   FairRtdbRun* run;
   cout<<"--------------  runs, versions  ------------------------------------------------\n";
   cout<<"run id\n";
   cout<<"  "<<setw(45)<<"container";
   cout.setf(ios::right,ios::adjustfield);
   cout<<setw(11)<<"1st-inp"
       <<setw(11)<<" 2nd-inp"
       <<setw(11)<<" output\n";
   while ((run=(FairRtdbRun*)next())) {
     run->print();
   }
   cout<<"--------------  input/output  --------------------------------------------------\n";
   if (firstInput) {
     cout<<"first Input:\n";
     firstInput->print();
   } else { cout<<"first input: none"<<'\n'; }
   if (secondInput) {
     cout<<"second Input:\n";
     secondInput->print();
   } else { cout<<"second input: none"<<'\n'; }
   if (output) {
     cout<<"output:\n";
     output->print();
   } else { cout<<"output: none"<<'\n'; }
 }
void FairRuntimeDb::printParamContexts ()
Definition at line 133 of file FairRuntimeDb.cxx.
References contFactories, and FairContFact::print().
 {
   // Prints the context of all parameter containers, which can be created by
   // the container factories
   TIter next(&contFactories);
   FairContFact* fact;
   while((fact=(FairContFact*)next())) { fact->print(); }
 }
Bool_t FairRuntimeDb::readAll (void)
Definition at line 494 of file FairRuntimeDb.cxx.
References FairParIo::check(), currentRun, getOutput(), initContainers(), output, runs, saveOutput(), and writeContainers().
 {
   // reads all containers with all versions for all runs and writes the
   // containers, the setup information and the version table to the output
   if (!(getOutput() && output->check())) {
     cout<<"***********************************************************"<<endl;
     cout<<"*********************  W A R N I N G  *********************"<<endl;
     cout<<"*********************   no output !   *********************"<<endl;
     cout<<"***********************************************************"<<endl;
   }
   currentRun=0;
   Bool_t rc=kTRUE;
   TIter next(runs);
   while ((currentRun=(FairRtdbRun*)next())!=0) {
     rc=initContainers() && rc;
     writeContainers();
   }
   saveOutput();
   currentRun=0;
   return kTRUE;
 }
void FairRuntimeDb::removeAllContainers (void)
Definition at line 210 of file FairRuntimeDb.cxx.
References containerList.
 {
   // removes all containers from the list and deletes them
   containerList->Delete();
 }
void FairRuntimeDb::removeContainer (Text_t * name)
Definition at line 200 of file FairRuntimeDb.cxx.
References containerList.
Referenced by ~FairRuntimeDb().
 {
   // removes the container from the list and deletes it
   TObject* c=containerList->FindObject(name);
   if (c) {
     containerList->Remove(c);
     delete c;
   }
 }
void FairRuntimeDb::removeRun (Text_t * name)
Definition at line 255 of file FairRuntimeDb.cxx.
References currentRun, and runs.
 {
   // removes the run from the list and deletes it
   TObject* c=runs->FindObject(name);
   if (c) {
     runs->Remove(c);
     delete c;
     if(c==currentRun) { currentRun=0; }
   }
 }
void FairRuntimeDb::resetAllVersions (void)
Definition at line 663 of file FairRuntimeDb.cxx.
References resetInputVersions(), and resetOutputVersions().
 {
   // resets all input and output versions in the list of runs
   // and in all containers which are not static
   resetInputVersions();
   resetOutputVersions();
 }
void FairRuntimeDb::resetInputVersions (void)
Definition at line 635 of file FairRuntimeDb.cxx.
References containerList, FairParSet::isStatic(), FairParSet::resetInputVersions(), FairRtdbRun::resetInputVersions(), and runs.
Referenced by resetAllVersions(), setFirstInput(), and setSecondInput().
 {
   // resets all input versions in the list of runs and in all containers which are not static
   // is called each time a new input is set
   TIter nextRun(runs);
   FairRtdbRun* run;
   while ((run=(FairRtdbRun*)nextRun())) {
     run->resetInputVersions();
   }
   TIter nextCont(containerList);
   FairParSet* cont;
   while ((cont=(FairParSet*)nextCont())) {
     if (!cont->isStatic()) { cont->resetInputVersions(); }
   }
 }
void FairRuntimeDb::resetOutputVersions (void)
Definition at line 651 of file FairRuntimeDb.cxx.
References FairRtdbRun::resetOutputVersions(), and runs.
Referenced by closeOutput(), resetAllVersions(), setFirstInput(), setOutput(), and setSecondInput().
 {
   // resets all output versions in the list of runs
   // is called each time a new output is set
   // is called also each time a new input is set which is not identical with the output
   TIter next(runs);
   FairRtdbRun* run;
   while ((run=(FairRtdbRun*)next())) {
     run->resetOutputVersions();
   }
 }
void FairRuntimeDb::saveOutput (void)
Definition at line 773 of file FairRuntimeDb.cxx.
References currentRun, writeContainers(), and writeVersions().
Referenced by closeOutput(), and readAll().
 {
   // writes the versions and the containers (if not yet written out)
   // without the version information the containers cannot be read from a ROOT file!
   Bool_t rc=kTRUE;
   if (currentRun!=0) { rc=writeContainers(); }
   writeVersions();
   if (!rc) { Error("saveOutput()","Error occured during write"); }
 }
void FairRuntimeDb::setContainersStatic (Bool_t f = kTRUE)
Definition at line 549 of file FairRuntimeDb.cxx.
References containerList, and FairParSet::setStatic().
 {
   // sets the status flag in all containers
   // flag kTRUE sets all 'static'
   // flag kFALSE sets all 'not static'
   TIter next(containerList);
   FairParSet* cont;
   while ((cont=(FairParSet*)next())) {
     cont->setStatic(flag);
   }
 }
Bool_t FairRuntimeDb::setFirstInput (FairParIo * inp1)
Definition at line 671 of file FairRuntimeDb.cxx.
References FairParIo::check(), firstInput, output, resetInputVersions(), resetOutputVersions(), and FairParIo::setInputNumber().
Referenced by FairAnaSelector::Init().
 {
   // sets the first input pointer
   firstInput=inp1;
   if (inp1->check()==kTRUE) {
     inp1->setInputNumber(1);
     resetInputVersions();
     if (output && firstInput!=output) { resetOutputVersions(); }
     return kTRUE;
   } else { Error("setFirstInput(FairParIo*)","no connection to input"); }
   return kFALSE;
 }
Bool_t FairRuntimeDb::setInputVersion (Int_t run, Text_t * container, Int_t version, Int_t inputNumber)
Definition at line 561 of file FairRuntimeDb.cxx.
References FairRtdbRun::getParVersion(), getRun(), and FairParVersion::setInputVersion().
 {
   // sets the input version of a container defined by its name and a
   // run defined by its id taken from input with inputNumber inp
   // (1 for first input and 2 for second input)
   FairRtdbRun* r=getRun(run);
   if (r) {
     FairParVersion* v=r->getParVersion(container);
     if (v) {
       v->setInputVersion(version,inp);
       return kTRUE;
     } else { Error("setInputVersion","Container not found"); }
   } else { Error("setInputVersion","Run not found"); }
   return kFALSE;
 }
Bool_t FairRuntimeDb::setOutput (FairParIo * op)
Definition at line 714 of file FairRuntimeDb.cxx.
References AsciiFileOutput, FairParIo::check(), ioType, isRootFileOutput, output, resetOutputVersions(), RootFileOutput, and RootTSQLOutput.
 {
   // sets the output pointer
   output = op;
   if (output->check() == kTRUE) {
     resetOutputVersions();
     if (strcmp(output->IsA()->GetName(), "FairParRootFileIo") == 0) {
       ioType = RootFileOutput;
       isRootFileOutput=kTRUE;
     } else if (strcmp(output->IsA()->GetName(), "FairParTSQLIo") == 0) {
       ioType = RootTSQLOutput;
     } else { //ASCII
       ioType = AsciiFileOutput;
     }
     return kTRUE;
   } else { Error("setOutput(FairParIo*)","no connection to output"); }
   return kFALSE;
 }
Bool_t FairRuntimeDb::setRootOutputVersion (Int_t run, Text_t * container, Int_t version)
Definition at line 579 of file FairRuntimeDb.cxx.
References FairRtdbRun::getParVersion(), getRun(), and FairParVersion::setRootVersion().
 {
   // sets the Root file output version of a container defined by its name
   // and a run defined by its id
   // should only be used after initialization 'by hand' on the interpreter level
   FairRtdbRun* r=getRun(run);
   if (r) {
     FairParVersion* v=r->getParVersion(container);
     if (v) {
       v->setRootVersion(version);
       return kTRUE;
     } else { Error("setRootOutputVersion","Container not found"); }
   } else { Error("setRootOutputVersion","Run not found"); }
   return kFALSE;
 }
Bool_t FairRuntimeDb::setSecondInput (FairParIo * inp2)
Definition at line 684 of file FairRuntimeDb.cxx.
References FairParIo::check(), firstInput, output, resetInputVersions(), resetOutputVersions(), secondInput, and FairParIo::setInputNumber().
Referenced by FairAnaSelector::Init().
 {
   // sets the second input pointer
   secondInput=inp2;
   if (inp2->check()==kTRUE) {
     inp2->setInputNumber(2);
     resetInputVersions();
     if (output && firstInput!=output) { resetOutputVersions(); }
     return kTRUE;
   } else { Error("setSecondInput(FairParIo*)","no connection to input"); }
   return kFALSE;
 }
void FairRuntimeDb::setVersionsChanged (Bool_t f = kTRUE) inline
Definition at line 86 of file FairRuntimeDb.h.
Referenced by FairDetParRootFileIo::write().
 {versionsChanged=f;}
Bool_t FairRuntimeDb::writeContainer (FairParSet * cont, FairRtdbRun * run, FairRtdbRun * refRun = 0)
Definition at line 399 of file FairRuntimeDb.cxx.
References AsciiFileOutput, FairParIo::check(), FairLogger::Debug(), findOutputVersion(), fLogger, FairParSet::getInputVersion(), FairParSet::GetName(), getOutput(), FairRtdbRun::getParVersion(), FairParVersion::getRootVersion(), FairParSet::hasChanged(), FairLogger::Info(), ioType, FairParIo::isAutoWritable(), MESSAGE_ORIGIN, output, FairParSet::print(), RootFileOutput, RootTSQLOutput, FairParSet::setChanged(), FairParVersion::setInputVersion(), FairParVersion::setRootVersion(), and FairParSet::write().
Referenced by writeContainers().
 {
   // std::cout << "\n -I FairRuntimeDB Using DB mode \n";
   // writes a container to the output if the containers has changed
   // The output might be suppressed if the changes is due an initialisation from a
   //   ROOT file which serves also as output or if it was already written
   Text_t* c = (char*)cont->GetName();
   fLogger->Debug( MESSAGE_ORIGIN,"RuntimeDb: write container : %s ", cont->GetName());
   FairParVersion* vers = run->getParVersion(c);
   Bool_t rc = kTRUE;
   Int_t cv = 0;
   if (getOutput() && output->check() && output->isAutoWritable()) {
     switch (ioType) {
     case RootFileOutput: // RootFile
       if (cont->hasChanged()) {
         cv = findOutputVersion(cont);
         if (cv == 0) {
           cv = cont->write(output);
           if (cv>0) {
             fLogger->Info(MESSAGE_ORIGIN,"***  %s written to ROOT file   version: %i ", c, cv);
           } else if (cv==-1) {
             return kFALSE;
           }
           // -1 indicates and error during write
           // 0 is allowed for all containers which have no write function
         }
         vers->setRootVersion(cv);
       } else {
         if (vers->getRootVersion() == 0) {
           cv = findOutputVersion(cont);
           vers->setRootVersion(cv);
         }
       }
       break;// End of rootfile IO
     case RootTSQLOutput://TSQL
       if (cont->hasChanged()) {
         cv = findOutputVersion(cont);
         if(cv == 0) {
           //std::cout << "-I- FairRuntimeDB: SQL write() called 1 = "<< cont->GetName() << "\n";
           cont->print();
           /*Int_t test = */
           cont->write(output);
           //std::cout << "-I- FairRuntimeDB: SQL write() called 2 =  \n";
         }
       }
       break;//End of TSQL IO
     case AsciiFileOutput:// might be Ascii I/O
       if(cont->hasChanged()) {
         cv = cont->write(output);
         if(cv <0) {
           return kFALSE;
         }
         cout << "***  " << c << " written to output" << '\n';
         vers->setRootVersion(cv);
       }
       break;// End of Ascii IO
     default: // Unknown IO
       Error("writeContainer()","Unknown output file type.");
       break;
     }
   }
   vers->setInputVersion(cont->getInputVersion(1),1);
   vers->setInputVersion(cont->getInputVersion(2),2);
   cont->setChanged(kFALSE);
   if (refRun) {
     FairParVersion* refVers=refRun->getParVersion(c);
     if (refVers) {
       refVers->setInputVersion(cont->getInputVersion(1),1);
       refVers->setInputVersion(cont->getInputVersion(2),2);
       refVers->setRootVersion(cv);
     }
   }
   return rc;
 }
Bool_t FairRuntimeDb::writeContainers (void)
Definition at line 283 of file FairRuntimeDb.cxx.
References containerList, currentRun, FairRtdbRun::getRefRun(), runs, and writeContainer().
Referenced by initContainers(), readAll(), and saveOutput().
 {
   // writes all containers to the output
   // loops over the list of containers and calls for each the
   // function writeContainer(...)
   TIter next(containerList);
   FairParSet* cont;
   Bool_t rc=kTRUE;
   FairRtdbRun* refRun=0;
   if (currentRun) {
     const char* refRunName=currentRun->getRefRun();
     if (strlen(refRunName)>0) {
       refRun=(FairRtdbRun*)(runs->FindObject(refRunName));
     }
     while ((cont=(FairParSet*)next())) {
       rc=writeContainer(cont,currentRun,refRun) && rc;
     }
   }
   if (!rc) { Error("writeContainers()","Error in write of containers to output"); }
   return rc;
 }
void FairRuntimeDb::writeVersions (void)
Definition at line 271 of file FairRuntimeDb.cxx.
References FairParIo::cd(), FairParIo::check(), getOutput(), isRootFileOutput, output, runs, and versionsChanged.
Referenced by saveOutput().
 {
   // writes the parameter versions for all runs to the output
   if (getOutput() && output->check()) {
     if (versionsChanged && isRootFileOutput) {
       output->cd();
       if (gFile->IsWritable()) { runs->Write();}
       versionsChanged=kFALSE;
     }
   }
 }
Member Data Documentation
TList* FairRuntimeDb::containerList protected
Definition at line 32 of file FairRuntimeDb.h.
Referenced by addContainer(), addRun(), findContainer(), getListOfContainers(), initContainers(), print(), removeAllContainers(), removeContainer(), resetInputVersions(), setContainersStatic(), writeContainers(), and ~FairRuntimeDb().
TString FairRuntimeDb::currentFileName protected
Definition at line 38 of file FairRuntimeDb.h.
Referenced by initContainers().
FairRtdbRun* FairRuntimeDb::currentRun protected
Definition at line 37 of file FairRuntimeDb.h.
Referenced by addRun(), findOutputVersion(), getCurrentRun(), initContainers(), readAll(), removeRun(), saveOutput(), and writeContainers().
FairParIo* FairRuntimeDb::firstInput protected
Definition at line 34 of file FairRuntimeDb.h.
Referenced by closeFirstInput(), findOutputVersion(), initContainers(), print(), setFirstInput(), and setSecondInput().
FairLogger* FairRuntimeDb::fLogger protected
Fair Logger
Definition at line 42 of file FairRuntimeDb.h.
Referenced by addContFactory(), and writeContainer().
FairRuntimeDb* FairRuntimeDb::gRtdb static private
Definition at line 28 of file FairRuntimeDb.h.
Referenced by FairRuntimeDb(), and ~FairRuntimeDb().
ParamIOType FairRuntimeDb::ioType protected
Definition at line 53 of file FairRuntimeDb.h.
Referenced by setOutput(), and writeContainer().
Bool_t FairRuntimeDb::isRootFileOutput protected
Definition at line 40 of file FairRuntimeDb.h.
Referenced by closeOutput(), setOutput(), and writeVersions().
FairParIo* FairRuntimeDb::output protected
Definition at line 36 of file FairRuntimeDb.h.
Referenced by closeOutput(), findOutputVersion(), getOutput(), print(), readAll(), setFirstInput(), setOutput(), setSecondInput(), writeContainer(), and writeVersions().
TList* FairRuntimeDb::runs protected
Definition at line 33 of file FairRuntimeDb.h.
Referenced by addContainer(), addRun(), clearRunList(), findOutputVersion(), getRun(), print(), readAll(), removeRun(), resetInputVersions(), resetOutputVersions(), writeContainers(), writeVersions(), and ~FairRuntimeDb().
FairParIo* FairRuntimeDb::secondInput protected
Definition at line 35 of file FairRuntimeDb.h.
Referenced by closeSecondInput(), getSecondInput(), initContainers(), print(), and setSecondInput().
Bool_t FairRuntimeDb::versionsChanged protected
Definition at line 39 of file FairRuntimeDb.h.
Referenced by writeVersions().
The documentation for this class was generated from the following files:
FairRuntimeDb.h
FairRuntimeDb.cxx