FairRoot: FairTrackParP Class Reference
FairTrackParP Class Reference
#include <FairTrackParP.h>
Public Member Functions
FairTrackParP ()
FairTrackParP (Double_t v, Double_t w, Double_t Tv, Double_t Tw, Double_t qp, Double_t CovMatrix[15], TVector3 o, TVector3 dj, TVector3 dk)
FairTrackParP (Double_t v, Double_t w, Double_t Tv, Double_t Tw, Double_t qp, Double_t CovMatrix[15], TVector3 o, TVector3 dj, TVector3 dk, Double_t spu)
FairTrackParP (TVector3 pos, TVector3 Mom, TVector3 posErr, TVector3 MomErr, Int_t q, TVector3 o, TVector3 dj, TVector3 dk)
FairTrackParP (TVector3 pos, TVector3 Mom, Double_t covMARS[6][6], Int_t q, TVector3 o, TVector3 dj, TVector3 dk)
FairTrackParP (FairTrackParH *helix, TVector3 dj, TVector3 dk, Int_t &ierr)
virtual ~FairTrackParP ()
virtual void Print (Option_t *option="") const
void SetTrackPar (Double_t X, Double_t Y, Double_t Z, Double_t Px, Double_t Py, Double_t Pz, Int_t Q, Double_t CovMatrix[15], TVector3 o, TVector3 di, TVector3 dj, TVector3 dk)
void SetTrackPar (Double_t v, Double_t w, Double_t Tv, Double_t Tw, Double_t qp, Double_t CovMatrix[15], TVector3 o, TVector3 di, TVector3 dj, TVector3 dk, Double_t spu)
void SetTV (Double_t tv)
void SetTW (Double_t tw)
void Reset ()
ClassDef (FairTrackParP, 1)
void GetMARSCov (Double_t Cov66[6][6])
Double_t * GetCov ()
void GetCov (Double_t *Cov)
void GetCovQ (Double_t *CovQ)
Double_t GetV ()
Double_t GetW ()
Double_t GetTV ()
Double_t GetTW ()
Double_t GetDV ()
Double_t GetDW ()
Double_t GetDTV ()
Double_t GetDTW ()
TVector3 GetSDMomentum ()
TVector3 GetOrigin ()
TVector3 GetIVer ()
TVector3 GetJVer ()
TVector3 GetKVer ()
void SetPlane (TVector3 o, TVector3 dj, TVector3 dk)
Double_t GetSPU ()
void SetTransportMatrix (Double_t mat[5][5])
void GetTransportMatrix (Double_t mat[5][5])
virtual TVector3 GetPosition () const
virtual Double_t GetX ()
virtual Double_t GetY ()
virtual Double_t GetZ ()
Int_t GetQ () const
virtual Double_t GetDX () const
virtual Double_t GetDY () const
virtual Double_t GetDZ () const
virtual TVector3 GetMomentum () const
virtual Double_t GetPx () const
virtual Double_t GetPy () const
virtual Double_t GetPz () const
virtual Double_t GetQp () const
virtual Double_t GetDPx () const
virtual Double_t GetDPy () const
virtual Double_t GetDPz () const
virtual Double_t GetDQp () const
virtual void SetX (Double_t x)
virtual void SetY (Double_t y)
virtual void SetZ (Double_t z)
virtual void SetDX (Double_t dx)
virtual void SetDY (Double_t dy)
virtual void SetDZ (Double_t dz)
virtual void SetPx (Double_t px)
virtual void SetPy (Double_t py)
virtual void SetPz (Double_t pz)
virtual void SetDPx (Double_t dpx)
virtual void SetDPy (Double_t dpy)
virtual void SetDPz (Double_t dpz)
void SetQp (Double_t qp)
Protected Member Functions
ClassDef (FairTrackPar, 2)
Protected Attributes
Double_t fX
Double_t fY
Double_t fZ
Double_t fDX
Double_t fDY
Double_t fDZ
Double_t fPx
Double_t fPy
Double_t fPz
Double_t fDPx
Double_t fDPy
Double_t fDPz
Double_t fQp
Double_t fDQp
Int_t fq
Private Member Functions
void CalCov ()
Private Attributes
Double_t fU
Double_t fV
Double_t fW
Double_t fTV
Double_t fTW
Double_t fPx_sd
Double_t fPy_sd
Double_t fPz_sd
Double_t fDU
Double_t fDV
Double_t fDW
Double_t fDTV
Double_t fDTW
Double_t fCovMatrix [15]
Double_t fCovMatrix66 [6][6]
TVector3 forigin
TVector3 fiver
TVector3 fjver
TVector3 fkver
Double_t fDI [3]
Double_t fDJ [3]
Double_t fDK [3]
Double_t fSPU
Double_t ftrmat [5][5]
Detailed Description
Definition at line 27 of file FairTrackParP.h.
Constructor & Destructor Documentation
FairTrackParP::FairTrackParP ()
Constructor
FairTrackParP::FairTrackParP (Double_t v, Double_t w, Double_t Tv, Double_t Tw, Double_t qp, Double_t CovMatrix[15], TVector3 o, TVector3 dj, TVector3 dk)
Constructor with all track variables in SD
Definition at line 70 of file FairTrackParP.cxx.
References fCovMatrix, fCovMatrix66, fDJ, fDK, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, fDTV, fDTW, fDV, fDW, FairTrackPar::fDX, FairTrackPar::fDY, FairTrackPar::fDZ, fiver, fjver, fkver, forigin, FairTrackPar::fPx, fPx_sd, FairTrackPar::fPy, fPy_sd, FairTrackPar::fPz, fPz_sd, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromSDToMars(), FairGeaneUtil::FromSDToMARSCoord(), fSPU, fTV, fTW, fU, fV, fW, FairTrackPar::fX, FairTrackPar::fY, FairTrackPar::fZ, FairRunAna::GetField(), FairRunAna::Instance(), and SetPlane().
   : FairTrackPar(),
     fU (0.),
     fV (v),
     fW (w),
     fTV(Tv),
     fTW(Tw),
     fPx_sd(0.),
     fPy_sd(0.),
     fPz_sd(0.),
     fDU(0.),
     fDV(0.),
     fDW(0.),
     fDTV(0.),
     fDTW(0.),
     forigin(TVector3(0,0,0)),
     fiver(TVector3(0,0,0)),
     fjver(TVector3(0,0,0)),
     fkver(TVector3(0,0,0)),
     fSPU(0.)
 {
 // Reset();
   SetPlane(o, dj, dk);
 // fV = v;
 // fW = w;
 //  fTV = Tv;
 //  fTW = Tw;
   fQp = qp;
   Double_t P  = TMath::Abs(1/fQp);
   //fq= int (P * fQp);
   fq = (int)TMath::Sign(1.0, fQp);
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=CovMatrix[i];
   }
   fPx_sd = TMath::Sqrt( P*P / ( fTV*fTV + fTW*fTW + 1 ) );
   fPy_sd = fTV * fPx_sd;
   fPz_sd = fTW * fPx_sd;
 // fU = 0.;
   FairGeaneUtil util;
   TVector3 position = util.FromSDToMARSCoord(TVector3(fU, fV, fW), forigin, fiver, fjver, fkver);
   fX = position.X();
   fY = position.Y();
   fZ = position.Z();
   fDQp  = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDTV  = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDTW  = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDV   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDW   = TMath::Sqrt(fabs(fCovMatrix[14]));
   Double_t PD[3],RD[6][6],H[3],PC[3],RC[15], SP1;
   Int_t CH;
   PC[0]   = fQp;
   PC[1]   = fTV;
   PC[2]   = fTW;
   for(Int_t i=0; i<15; i++)  {
     RC[i]=fCovMatrix[i];
   }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   TVector3 momsd = TVector3(fPx_sd,fPy_sd,fPz_sd);
   SP1 = (momsd.Dot(fjver.Cross(fkver)))/TMath::Abs(momsd.Dot(fjver.Cross(fkver)));
   fSPU=SP1;
   util.FromSDToMars(PC, RC, H, CH, SP1, fDJ, fDK, PD, RD);
   fPx = PD[0];
   fPy = PD[1];
   fPz = PD[2];
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
   fDPx = TMath::Sqrt(fabs(RD[0][0]));
   fDPy = TMath::Sqrt(fabs(RD[1][1]));
   fDPz = TMath::Sqrt(fabs(RD[2][2]));
   fDX  = TMath::Sqrt(fabs(RD[3][3]));
   fDY  = TMath::Sqrt(fabs(RD[4][4]));
   fDZ  = TMath::Sqrt(fabs(RD[5][5]));
 }
FairTrackParP::FairTrackParP (Double_t v, Double_t w, Double_t Tv, Double_t Tw, Double_t qp, Double_t CovMatrix[15], TVector3 o, TVector3 dj, TVector3 dk, Double_t spu)
Definition at line 172 of file FairTrackParP.cxx.
References fCovMatrix, fCovMatrix66, fDJ, fDK, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, fDTV, fDTW, fDV, fDW, FairTrackPar::fDX, FairTrackPar::fDY, FairTrackPar::fDZ, fiver, fjver, fkver, forigin, FairTrackPar::fPx, fPx_sd, FairTrackPar::fPy, fPy_sd, FairTrackPar::fPz, fPz_sd, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromSDToMars(), FairGeaneUtil::FromSDToMARSCoord(), fSPU, fTV, fTW, fU, fV, fW, FairTrackPar::fX, FairTrackPar::fY, FairTrackPar::fZ, FairRunAna::GetField(), FairRunAna::Instance(), and SetPlane().
   : FairTrackPar(),
     fU (0.),
     fV (v),
     fW (w),
     fTV(Tv),
     fTW(Tw),
     fPx_sd(0.),
     fPy_sd(0.),
     fPz_sd(0.),
     fDU(0.),
     fDV(0.),
     fDW(0.),
     fDTV(0.),
     fDTW(0.),
     forigin(TVector3(0,0,0)),
     fiver(TVector3(0,0,0)),
     fjver(TVector3(0,0,0)),
     fkver(TVector3(0,0,0)),
     fSPU(spu)
 {
 //  Reset();
   SetPlane(o, dj, dk);
 //  fV = v;
 //  fW = w;
 //  fTV = Tv;
 //  fTW = Tw;
   fQp = qp;
 //  fSPU = spu;
   Double_t P=0;
   if(0!=fQp) {
     P = TMath::Abs(1/fQp);
     fq = (int)TMath::Sign(1.0, fQp);
     //fq= int (P * fQp);
   } else { fq=1; }
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=CovMatrix[i];
   }
   fPx_sd = fSPU*TMath::Sqrt( P*P / ( fTV*fTV + fTW*fTW + 1 ) );
   fPy_sd = fTV * fPx_sd;
   fPz_sd = fTW * fPx_sd;
 //  fU = 0.;
   FairGeaneUtil util;
   TVector3 position = util.FromSDToMARSCoord(TVector3(fU, fV, fW), forigin, fiver, fjver, fkver);
   fX = position.X();
   fY = position.Y();
   fZ = position.Z();
   fDQp  = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDTV  = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDTW  = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDV   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDW   = TMath::Sqrt(fabs(fCovMatrix[14]));
   Double_t PD[3],RD[6][6],H[3],PC[3],RC[15], SP1;
   Int_t CH;
   PC[0]   = fQp;
   PC[1]   = fTV;
   PC[2]   = fTW;
   for(Int_t i=0; i<15; i++)  {
     RC[i]=fCovMatrix[i];
   }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   TVector3 momsd = TVector3(fPx_sd,fPy_sd,fPz_sd);
   //  SP1 = (momsd.Dot(fjver.Cross(fkver)))/TMath::Abs(momsd.Dot(fjver.Cross(fkver)));
   SP1 = fSPU; // correct calculation of SP1
   util.FromSDToMars(PC, RC, H, CH, SP1, fDJ, fDK, PD, RD);
   fPx = PD[0];
   fPy = PD[1];
   fPz = PD[2];
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
   fDPx = TMath::Sqrt(fabs(RD[0][0]));
   fDPy = TMath::Sqrt(fabs(RD[1][1]));
   fDPz = TMath::Sqrt(fabs(RD[2][2]));
   fDX  = TMath::Sqrt(fabs(RD[3][3]));
   fDY  = TMath::Sqrt(fabs(RD[4][4]));
   fDZ  = TMath::Sqrt(fabs(RD[5][5]));
 }
FairTrackParP::FairTrackParP (TVector3 pos, TVector3 Mom, TVector3 posErr, TVector3 MomErr, Int_t q, TVector3 o, TVector3 dj, TVector3 dk)
Constructor with position and momentum track in LAB
Definition at line 276 of file FairTrackParP.cxx.
References fCovMatrix, fCovMatrix66, fDJ, fDK, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, fDTV, fDTW, fDV, fDW, FairTrackPar::fDX, FairTrackPar::fDY, FairTrackPar::fDZ, fiver, fjver, fkver, forigin, FairTrackPar::fPx, fPx_sd, FairTrackPar::fPy, fPy_sd, FairTrackPar::fPz, fPz_sd, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromMarsToSD(), FairGeaneUtil::FromMARSToSDCoord(), fSPU, fTV, fTW, fU, fV, fW, FairTrackPar::fX, FairTrackPar::fY, FairTrackPar::fZ, FairRunAna::GetField(), FairRunAna::Instance(), SetPlane(), FairTrackPar::SetPx(), FairTrackPar::SetPy(), FairTrackPar::SetPz(), FairTrackPar::SetX(), FairTrackPar::SetY(), and FairTrackPar::SetZ().
   : FairTrackPar(pos.x(),pos.y(),pos.z(),Mom.x(),Mom.y(),Mom.z(),Q),
     fU (0.),
     fV (0),
     fW (0),
     fTV(0),
     fTW(0),
     fPx_sd(0.),
     fPy_sd(0.),
     fPz_sd(0.),
     fDU(0.),
     fDV(0.),
     fDW(0.),
     fDTV(0.),
     fDTW(0.),
     forigin(TVector3(0,0,0)),
     fiver(TVector3(0,0,0)),
     fjver(TVector3(0,0,0)),
     fkver(TVector3(0,0,0)),
     fSPU(0.)
 {
 // Reset();
   SetPlane(o, dj, dk);
   SetPx(Mom.x());
   SetPy(Mom.y());
   SetPz(Mom.z());
   SetX(pos.x()); //x (lab)
   SetY(pos.y()); //y (lab)
   SetZ(pos.z()); //z (lab)
   Double_t P = TMath::Sqrt(fPx*fPx +fPy*fPy +fPz*fPz );
   if(Q!=0) { fq= Q/TMath::Abs(Q); }
   FairGeaneUtil util;
   TVector3 positionsd = util.FromMARSToSDCoord(TVector3(fX, fY, fZ), forigin, fiver, fjver, fkver);
   fU = positionsd.X();
   fV = positionsd.Y();
   fW = positionsd.Z();
   fQp = fq/P;
   fDPx = MomErr.x(); //dpx
   fDPy = MomErr.y(); //dpy
   fDPz = MomErr.z(); //dpz
   fDX  = posErr.x(); //dpx
   fDY  = posErr.y(); //dpy
   fDZ  = posErr.z(); //dpz
   Double_t PD[3], RD[6][6], H[3], SP1, PC[3], RC[15];
   Int_t CH, IERR;
   PD[0] = fPx;
   PD[1] = fPy;
   PD[2] = fPz;
   for(int i = 0; i < 6; i++)  for(int j = 0; j < 6; j++) { RD[i][j] = 0.; }
   RD[0][0] = fDPx * fDPx;
   RD[1][1] = fDPy * fDPy;
   RD[2][2] = fDPz * fDPz;
   RD[3][3] = fDX * fDX;
   RD[4][4] = fDY * fDY;
   RD[5][5] = fDZ * fDZ;
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   util.FromMarsToSD(PD, RD, H, CH, fDJ, fDK, IERR, SP1, PC, RC);
   for(Int_t i=0; i<15; i++) { fCovMatrix[i] = RC[i]; }
   fTV = PC[1];
   fTW = PC[2];
   fDQp  = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDTV  = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDTW  = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDV   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDW   = TMath::Sqrt(fabs(fCovMatrix[14]));
   fSPU = SP1;
   fPx_sd = fSPU*TMath::Sqrt( P*P / ( fTV*fTV + fTW*fTW + 1 ) );
   fPy_sd = fTV * fPx_sd;
   fPz_sd = fTW * fPx_sd;
 }
FairTrackParP::FairTrackParP (TVector3 pos, TVector3 Mom, Double_t covMARS[6][6], Int_t q, TVector3 o, TVector3 dj, TVector3 dk)
Definition at line 380 of file FairTrackParP.cxx.
References fCovMatrix, fCovMatrix66, fDJ, fDK, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, fDTV, fDTW, fDV, fDW, FairTrackPar::fDX, FairTrackPar::fDY, FairTrackPar::fDZ, fiver, fjver, fkver, forigin, FairTrackPar::fPx, fPx_sd, FairTrackPar::fPy, fPy_sd, FairTrackPar::fPz, fPz_sd, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromMarsToSD(), FairGeaneUtil::FromMARSToSDCoord(), fSPU, fTV, fTW, fU, fV, fW, FairTrackPar::fX, FairTrackPar::fY, FairTrackPar::fZ, FairRunAna::GetField(), FairRunAna::Instance(), SetPlane(), FairTrackPar::SetPx(), FairTrackPar::SetPy(), FairTrackPar::SetPz(), FairTrackPar::SetX(), FairTrackPar::SetY(), and FairTrackPar::SetZ().
   : FairTrackPar(pos.x(),pos.y(),pos.z(),Mom.x(),Mom.y(),Mom.z(),Q),
     fU (0.),
     fV (0),
     fW (0),
     fTV(0),
     fTW(0),
     fPx_sd(0.),
     fPy_sd(0.),
     fPz_sd(0.),
     fDU(0.),
     fDV(0.),
     fDW(0.),
     fDTV(0.),
     fDTW(0.),
     forigin(TVector3(0,0,0)),
     fiver(TVector3(0,0,0)),
     fjver(TVector3(0,0,0)),
     fkver(TVector3(0,0,0)),
     fSPU(0.)
 {
 //  Reset();
   SetPlane(o, dj, dk);
   SetPx(Mom.x());
   SetPy(Mom.y());
   SetPz(Mom.z());
   SetX(pos.x()); //x (lab)
   SetY(pos.y()); //y (lab)
   SetZ(pos.z()); //z (lab)
   Double_t P = TMath::Sqrt(fPx*fPx +fPy*fPy +fPz*fPz );
   if(Q!=0) { fq= Q/TMath::Abs(Q); }
   FairGeaneUtil util;
   TVector3 positionsd = util.FromMARSToSDCoord(TVector3(fX, fY, fZ), forigin, fiver, fjver, fkver);
   fU = positionsd.X();
   fV = positionsd.Y();
   fW = positionsd.Z();
   fQp = fq/P;
   fDPx = TMath::Sqrt(fabs(covMARS[0][0])); //dpx
   fDPy = TMath::Sqrt(fabs(covMARS[1][1])); //dpy
   fDPz = TMath::Sqrt(fabs(covMARS[2][2])); //dpz
   fDX  = TMath::Sqrt(fabs(covMARS[3][3])); //dpx
   fDY  = TMath::Sqrt(fabs(covMARS[4][4])); //dpy
   fDZ  = TMath::Sqrt(fabs(covMARS[5][5])); //dpz
   Double_t PD[3], RD[6][6], H[3], SP1, PC[3], RC[15];
   Int_t IERR, CH;
   PD[0] = fPx;
   PD[1] = fPy;
   PD[2] = fPz;
   for(int i = 0; i < 6; i++)  for(int j = 0; j < 6; j++) { RD[i][j] = covMARS[i][j]; }
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   util.FromMarsToSD(PD, RD, H, CH, fDJ, fDK, IERR, SP1, PC, RC);
   for(Int_t i=0; i<15; i++) { fCovMatrix[i] = RC[i]; }
   fTV = PC[1];
   fTW = PC[2];
   fDQp  = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDTV  = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDTW  = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDV   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDW   = TMath::Sqrt(fabs(fCovMatrix[14]));
   fSPU = SP1;
   fPx_sd = fSPU*TMath::Sqrt( P*P / ( fTV*fTV + fTW*fTW + 1 ) );
   fPy_sd = fTV * fPx_sd;
   fPz_sd = fTW * fPx_sd;
 }
FairTrackParP::FairTrackParP (FairTrackParH * helix, TVector3 dj, TVector3 dk, Int_t & ierr)
Definition at line 478 of file FairTrackParP.cxx.
References FairGeaneUtil::FromMARSToSDCoord(), FairGeaneUtil::FromSCToSD(), FairTrackParH::GetCov(), FairRunAna::GetField(), FairTrackParH::GetLambda(), FairTrackParH::GetPhi(), FairTrackPar::GetQ(), FairTrackPar::GetQp(), FairTrackParH::GetX(), FairTrackParH::GetY(), FairTrackParH::GetZ(), FairRunAna::Instance(), and SetTrackPar().
   : FairTrackPar(),
     fU (0.),
     fV (0),
     fW (0),
     fTV(0),
     fTW(0),
     fPx_sd(0.),
     fPy_sd(0.),
     fPz_sd(0.),
     fDU(0.),
     fDV(0.),
     fDW(0.),
     fDTV(0.),
     fDTW(0.),
     forigin(TVector3(0,0,0)),
     fiver(TVector3(0,0,0)),
     fjver(TVector3(0,0,0)),
     fkver(TVector3(0,0,0)),
     fSPU(0.)
 {
   // q/p, lambda, phi --> q/p, v', w'
   Double_t PC[3] = {helix->GetQp(), helix->GetLambda(), helix->GetPhi()};
   Double_t RC[15];
   helix->GetCov(RC);
   // retrieve field
   TVector3 xyz(helix->GetX(), helix->GetY(), helix->GetZ());
   Double_t H[3], pnt[3];
   pnt[0] = xyz.X();
   pnt[1] = xyz.Y();
   pnt[2] = xyz.Z();
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   Int_t CH  = helix->GetQ();
   Double_t DJ[3] = {dj.X(), dj.Y(), dj.Z()};
   Double_t DK[3] = {dk.X(), dk.Y(), dk.Z()};
   Int_t IERR = 0;
   Double_t SPU = 0;
   Double_t PD[3], RD[15];
   FairGeaneUtil util;
   util.FromSCToSD(PC, RC, H, CH, DJ, DK,
                   IERR, SPU, PD, RD);
   ierr = IERR;
   // MARS coordinates
   TVector3 o(xyz.X(), xyz.Y(), xyz.Z());
   TVector3 di = dj.Cross(dk);
   TVector3 uvm = util.FromMARSToSDCoord(xyz, o, di, dj, dk);
   if(ierr == 0)  SetTrackPar(uvm.Y(), uvm.Z(),
                                PD[1], PD[2], PD[0],
                                RD,
                                o, di, dj, dk, SPU);
   else { cout << "FairTrackParP(FairTrackParH *) contructor ERROR: CANNOT convert helix to parabola" << endl; }
 }
FairTrackParP::~FairTrackParP () virtual
Destructor
Definition at line 717 of file FairTrackParP.cxx.
 {}
Member Function Documentation
void FairTrackParP::CalCov () private
Calculate the cov. mat. for this helix
Definition at line 710 of file FairTrackParP.cxx.
 {
   //not needed
 }
FairTrackParP::ClassDef (FairTrackParP , 1)
FairTrackPar::ClassDef (FairTrackPar , 2) protected inherited
Double_t* FairTrackParP::GetCov () inline
Definition at line 106 of file FairTrackParP.h.
References fCovMatrix.
Referenced by FairTrackParH::FairTrackParH().
 {return fCovMatrix;};
void FairTrackParP::GetCov (Double_t * Cov) inline
Definition at line 107 of file FairTrackParP.h.
References fCovMatrix.
 {for(Int_t i=0; i<15; i++) { Cov[i]=fCovMatrix[i]; }}
void FairTrackParP::GetCovQ (Double_t * CovQ)
Definition at line 901 of file FairTrackParP.cxx.
References fCovMatrix, and FairTrackPar::fq.
Referenced by FairGeanePro::Propagate().
 {
   // return error matrix in 1/p instead of q/p
   for(int i = 0; i < 15; i++) {
     CovQ[i] = fCovMatrix[i];
     if(fq!=0) {
       if(i == 0) { CovQ[i] = CovQ[i] / (fq * fq); }
       if(i > 0 && i < 5) { CovQ[i] = CovQ[i] / fq; }
     }
   }
 }
virtual Double_t FairTrackPar::GetDPx () const inline virtual inherited
Definition at line 78 of file FairTrackPar.h.
References FairTrackPar::fDPx.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), and FairTrackParH::SetTrackPar().
{
       return fDPx;
     };
virtual Double_t FairTrackPar::GetDPy () const inline virtual inherited
Definition at line 81 of file FairTrackPar.h.
References FairTrackPar::fDPy.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), and FairTrackParH::SetTrackPar().
{
       return fDPy;
     };
virtual Double_t FairTrackPar::GetDPz () const inline virtual inherited
Definition at line 84 of file FairTrackPar.h.
References FairTrackPar::fDPz.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), and FairTrackParH::SetTrackPar().
{
       return fDPz;
     };
virtual Double_t FairTrackPar::GetDQp () const inline virtual inherited
Definition at line 87 of file FairTrackPar.h.
References FairTrackPar::fDQp.
{
       return fDQp;
     };
Double_t FairTrackParP::GetDTV ()
Definition at line 763 of file FairTrackParP.cxx.
References fDTV.
 {
   return fDTV;
 }
Double_t FairTrackParP::GetDTW ()
Definition at line 767 of file FairTrackParP.cxx.
References fDTW.
 {
   return fDTW;
 }
Double_t FairTrackParP::GetDV ()
Definition at line 754 of file FairTrackParP.cxx.
References fDV.
 {
   return fDV;
 }
Double_t FairTrackParP::GetDW ()
Definition at line 759 of file FairTrackParP.cxx.
References fDW.
 {
   return fDW;
 }
virtual Double_t FairTrackPar::GetDX () const inline virtual inherited
Definition at line 51 of file FairTrackPar.h.
References FairTrackPar::fDX.
Referenced by FairTrackParH::FairTrackParH().
{
       return fDX;
     };
virtual Double_t FairTrackPar::GetDY () const inline virtual inherited
Definition at line 54 of file FairTrackPar.h.
References FairTrackPar::fDY.
Referenced by FairTrackParH::FairTrackParH().
{
       return fDY;
     };
virtual Double_t FairTrackPar::GetDZ () const inline virtual inherited
Definition at line 57 of file FairTrackPar.h.
References FairTrackPar::fDZ.
Referenced by FairTrackParH::FairTrackParH().
{
       return fDZ;
     };
TVector3 FairTrackParP::GetIVer ()
Definition at line 810 of file FairTrackParP.cxx.
References fiver.
 {
   return fiver;
 }
TVector3 FairTrackParP::GetJVer ()
Definition at line 814 of file FairTrackParP.cxx.
References fjver.
Referenced by FairTrackParH::FairTrackParH(), and FairGeanePro::Propagate().
 {
   return fjver;
 }
TVector3 FairTrackParP::GetKVer ()
Definition at line 819 of file FairTrackParP.cxx.
References fkver.
Referenced by FairTrackParH::FairTrackParH(), and FairGeanePro::Propagate().
 {
   return fkver;
 }
void FairTrackParP::GetMARSCov (Double_t Cov66[6][6]) inline
Accessors
Definition at line 103 of file FairTrackParP.h.
References fCovMatrix66.
 {for(Int_t i=0; i<6; i++) for(Int_t j=0; j<6; j++) { Cov66[i][j] = fCovMatrix66[i][j]; }  }
virtual TVector3 FairTrackPar::GetMomentum () const inline virtual inherited
Definition at line 61 of file FairTrackPar.h.
References FairTrackPar::fPx, FairTrackPar::fPy, and FairTrackPar::fPz.
{
       return TVector3(fPx, fPy, fPz);
     };
TVector3 FairTrackParP::GetOrigin ()
Definition at line 806 of file FairTrackParP.cxx.
References forigin.
 {
   return forigin;
 }
virtual TVector3 FairTrackPar::GetPosition () const inline virtual inherited
Accessors
Definition at line 34 of file FairTrackPar.h.
References FairTrackPar::fX, FairTrackPar::fY, and FairTrackPar::fZ.
{
       return TVector3(fX, fY, fZ);
     };
virtual Double_t FairTrackPar::GetPx () const inline virtual inherited
Definition at line 65 of file FairTrackPar.h.
References FairTrackPar::fPx.
Referenced by FairTrackParH::FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fPx;
     };
virtual Double_t FairTrackPar::GetPy () const inline virtual inherited
Definition at line 68 of file FairTrackPar.h.
References FairTrackPar::fPy.
Referenced by FairTrackParH::FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fPy;
     };
virtual Double_t FairTrackPar::GetPz () const inline virtual inherited
Definition at line 71 of file FairTrackPar.h.
References FairTrackPar::fPz.
Referenced by FairTrackParH::FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fPz;
     };
Int_t FairTrackPar::GetQ () const inline inherited
Definition at line 47 of file FairTrackPar.h.
References FairTrackPar::fq.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), and FairGeanePro::Propagate().
{
       return fq;
     };
virtual Double_t FairTrackPar::GetQp () const inline virtual inherited
Definition at line 74 of file FairTrackPar.h.
References FairTrackPar::fQp.
Referenced by FairTrackParH::FairTrackParH(), and FairTrackParP().
{
       return fQp;
     };
TVector3 FairTrackParP::GetSDMomentum () inline
Definition at line 119 of file FairTrackParP.h.
References fPx_sd, fPy_sd, and fPz_sd.
 {return TVector3(fPx_sd, fPy_sd, fPz_sd);}
Double_t FairTrackParP::GetSPU () inline
Definition at line 129 of file FairTrackParP.h.
References fSPU.
Referenced by FairTrackParH::FairTrackParH().
 {return fSPU;};
void FairTrackParP::GetTransportMatrix (Double_t mat[5][5])
Definition at line 896 of file FairTrackParP.cxx.
References ftrmat.
 {
   for(int i = 0; i < 5; i++) for(int j = 0; j < 5; j++) { mat[i][j] = ftrmat[i][j]; }
 }
Double_t FairTrackParP::GetTV ()
Definition at line 746 of file FairTrackParP.cxx.
References fTV.
Referenced by FairTrackParH::FairTrackParH().
 {
   return fTV;
 }
Double_t FairTrackParP::GetTW ()
Definition at line 750 of file FairTrackParP.cxx.
References fTW.
Referenced by FairTrackParH::FairTrackParH().
 {
   return fTW;
 }
Double_t FairTrackParP::GetV ()
Definition at line 737 of file FairTrackParP.cxx.
References fV.
 {
   return fV;
 }
Double_t FairTrackParP::GetW ()
Definition at line 742 of file FairTrackParP.cxx.
References fW.
 {
   return fW;
 }
virtual Double_t FairTrackPar::GetX () inline virtual inherited
Reimplemented in FairTrackParH.
Definition at line 38 of file FairTrackPar.h.
References FairTrackPar::fX.
Referenced by FairTrackParH::FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fX;
     };
virtual Double_t FairTrackPar::GetY () inline virtual inherited
Reimplemented in FairTrackParH.
Definition at line 41 of file FairTrackPar.h.
References FairTrackPar::fY.
Referenced by FairTrackParH::FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fY;
     };
virtual Double_t FairTrackPar::GetZ () inline virtual inherited
Reimplemented in FairTrackParH.
Definition at line 44 of file FairTrackPar.h.
References FairTrackPar::fZ.
Referenced by FairTrackParH::FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fZ;
     };
void FairTrackParP::Print (Option_t * option = "") const virtual
copy Constructor Output to screen
Reimplemented from FairTrackPar.
Definition at line 721 of file FairTrackParP.cxx.
References FairTrackPar::fQp, fTV, fTW, FairTrackPar::fX, FairTrackPar::fY, and FairTrackPar::fZ.
 {
   cout << "Position : (";
   cout.precision(2);
   cout << fX << ", " << fY << ", " << fZ << ")" << endl;
   cout << "Slopes : dx/dz = " << fTV << ", dy/dz = " << fTW << endl;
   cout << "q/p = " << fQp << endl;
 }
void FairTrackParP::Reset ()
Definition at line 826 of file FairTrackParP.cxx.
References fCovMatrix, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, fDTV, fDTW, fDV, fDW, FairTrackPar::fDX, FairTrackPar::fDY, FairTrackPar::fDZ, FairTrackPar::fPx, fPx_sd, FairTrackPar::fPy, fPy_sd, FairTrackPar::fPz, fPz_sd, FairTrackPar::fq, FairTrackPar::fQp, fTV, fTW, fU, fV, fW, FairTrackPar::fX, FairTrackPar::fY, and FairTrackPar::fZ.
Referenced by SetTrackPar().
 {
   fU   = 0.;
   fV   = 0.;
   fW   = 0.;
   fTV  = 0.;
   fTW  = 0.;
   fDV  = 0.;
   fDW  = 0.;
   fDTV = 0.;
   fDTW = 0.;
   for(Int_t i= 0; i<15; i++)  { fCovMatrix[i] = 0.; }
   fPx_sd = 0.;
   fPy_sd = 0.;
   fPz_sd = 0.;
   //base class members
   fX   = fY   = fZ   = 0.;
   fDX  = fDY  = fDZ  = 0.;
   fPx  = fPy  = fPz  = 0.;
   fDPx = fDPy = fDPz = 0.;
   fQp  = fDQp = fq   = 0;
 }
virtual void FairTrackPar::SetDPx (Double_t dpx) inline virtual inherited
Definition at line 123 of file FairTrackPar.h.
References FairTrackPar::fDPx.
{
       fDPx = dpx;
     };
virtual void FairTrackPar::SetDPy (Double_t dpy) inline virtual inherited
Definition at line 126 of file FairTrackPar.h.
References FairTrackPar::fDPy.
{
       fDPy = dpy;
     };
virtual void FairTrackPar::SetDPz (Double_t dpz) inline virtual inherited
Definition at line 129 of file FairTrackPar.h.
References FairTrackPar::fDPz.
{
       fDPz = dpz;
     };
virtual void FairTrackPar::SetDX (Double_t dx) inline virtual inherited
Definition at line 103 of file FairTrackPar.h.
References FairTrackPar::fDX.
{
       fDX  = dx;
     };
virtual void FairTrackPar::SetDY (Double_t dy) inline virtual inherited
Definition at line 106 of file FairTrackPar.h.
References FairTrackPar::fDY.
{
       fDY  = dy;
     };
virtual void FairTrackPar::SetDZ (Double_t dz) inline virtual inherited
Definition at line 109 of file FairTrackPar.h.
References FairTrackPar::fDZ.
{
       fDZ  = dz;
     };
void FairTrackParP::SetPlane (TVector3 o, TVector3 dj, TVector3 dk)
Definition at line 852 of file FairTrackParP.cxx.
References fDI, fDJ, fDK, fiver, fjver, fkver, and forigin.
Referenced by FairTrackParP(), and SetTrackPar().
 {
   // origin
   forigin = TVector3(o.X(), o.Y(), o.Z());
   // check unity
   j.SetMag(1.);
   k.SetMag(1.);
   // check orthogonality
   if(j* k != 0) {
     k = (j.Cross(k)).Cross(j);
   }
   // plane
   // i
   TVector3 i = j.Cross(k);
   i.SetMag(1.);
   fDI[0] = i.X();
   fDI[1] = i.Y();
   fDI[2] = i.Z();
   fiver = TVector3(fDI[0],fDI[1],fDI[2]);
   // j
   fDJ[0] = j.X();
   fDJ[1] = j.Y();
   fDJ[2] = j.Z();
   fjver = TVector3(fDJ[0],fDJ[1],fDJ[2]);
   // k
   fDK[0] = k.X();
   fDK[1] = k.Y();
   fDK[2] = k.Z();
   fkver = TVector3(fDK[0],fDK[1],fDK[2]);
 }
virtual void FairTrackPar::SetPx (Double_t px) inline virtual inherited
Definition at line 113 of file FairTrackPar.h.
References FairTrackPar::fPx.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), SetTrackPar(), and FairTrackParH::SetTrackPar().
{
       fPx = px;
     };
virtual void FairTrackPar::SetPy (Double_t py) inline virtual inherited
Definition at line 116 of file FairTrackPar.h.
References FairTrackPar::fPy.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), SetTrackPar(), and FairTrackParH::SetTrackPar().
{
       fPy = py;
     };
virtual void FairTrackPar::SetPz (Double_t pz) inline virtual inherited
Definition at line 119 of file FairTrackPar.h.
References FairTrackPar::fPz.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), SetTrackPar(), and FairTrackParH::SetTrackPar().
{
       fPz = pz;
     };
void FairTrackPar::SetQp (Double_t qp) inline inherited
Definition at line 133 of file FairTrackPar.h.
References FairTrackPar::fQp.
{
       fQp = qp;
     };
void FairTrackParP::SetTrackPar (Double_t X, Double_t Y, Double_t Z, Double_t Px, Double_t Py, Double_t Pz, Int_t Q, Double_t CovMatrix[15], TVector3 o, TVector3 di, TVector3 dj, TVector3 dk)
Definition at line 542 of file FairTrackParP.cxx.
References fCovMatrix, fCovMatrix66, fDJ, fDK, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, fDTV, fDTW, fDV, fDW, FairTrackPar::fDX, FairTrackPar::fDY, FairTrackPar::fDZ, fiver, fjver, fkver, forigin, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromMarsToSD(), FairGeaneUtil::FromMARSToSDCoord(), FairGeaneUtil::FromSDToMars(), fSPU, fTV, fTW, fU, fV, fW, FairTrackPar::fX, FairTrackPar::fY, FairTrackPar::fZ, FairRunAna::GetField(), FairRunAna::Instance(), Reset(), SetPlane(), FairTrackPar::SetPx(), FairTrackPar::SetPy(), FairTrackPar::SetPz(), FairTrackPar::SetX(), FairTrackPar::SetY(), and FairTrackPar::SetZ().
Referenced by FairTrackParP(), and FairGeanePro::Propagate().
 {
   Reset();
   SetPlane(o, dj, dk);
   Double_t P =TMath::Sqrt(Px*Px+Py*Py+Pz*Pz);
   if (Q!=0) { fq = TMath::Abs(Q)/Q; }
   fQp    = fq/P;
   SetX(X);
   SetY(Y);
   SetZ(Z);
   SetPx(Px);
   SetPy(Py);
   SetPz(Pz);
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=CovMatrix[i];
   }
   FairGeaneUtil util;
   TVector3 positionsd = util.FromMARSToSDCoord(TVector3(fX, fY, fZ), forigin, fiver, fjver, fkver);
   fU = positionsd.X();
   fV = positionsd.Y();
   fW = positionsd.Z();
   fQp = fq/P;
   Double_t PD[3], RD[6][6], H[3], SP1, PC[3], RC[15];
   Int_t IERR, CH;
   PD[0] = Px;
   PD[1] = Py;
   PD[2] = Pz;
   for(int i = 0; i < 6; i++)  for(int j = 0; j < 6; j++) { RD[i][j] = 0.; }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   util.FromMarsToSD(PD, RD, H, CH, fDJ, fDK, IERR, SP1, PC, RC);
   fTV = PC[1];
   fTW = PC[2];
   fDQp  = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDTV  = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDTW  = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDV   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDW   = TMath::Sqrt(fabs(fCovMatrix[14]));
   for(Int_t i=0; i<15; i++) { RC[i] = fCovMatrix[i]; }
   util.FromSDToMars(PC, RC, H, CH, SP1, fDJ, fDK, PD, RD);
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
   fDPx = TMath::Sqrt(fabs(RD[0][0]));
   fDPy = TMath::Sqrt(fabs(RD[1][1]));
   fDPz = TMath::Sqrt(fabs(RD[2][2]));
   fDX = TMath::Sqrt(fabs(RD[3][3]));
   fDY = TMath::Sqrt(fabs(RD[4][4]));
   fDZ = TMath::Sqrt(fabs(RD[5][5]));
   fSPU = SP1;
 }
void FairTrackParP::SetTrackPar (Double_t v, Double_t w, Double_t Tv, Double_t Tw, Double_t qp, Double_t CovMatrix[15], TVector3 o, TVector3 di, TVector3 dj, TVector3 dk, Double_t spu)
Definition at line 628 of file FairTrackParP.cxx.
References fCovMatrix, fCovMatrix66, fDJ, fDK, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, fDTV, fDTW, fDV, fDW, FairTrackPar::fDX, FairTrackPar::fDY, FairTrackPar::fDZ, fiver, fjver, fkver, forigin, FairTrackPar::fPx, fPx_sd, FairTrackPar::fPy, fPy_sd, FairTrackPar::fPz, fPz_sd, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromSDToMars(), FairGeaneUtil::FromSDToMARSCoord(), fSPU, fTV, fTW, fU, fV, fW, FairTrackPar::fX, FairTrackPar::fY, FairTrackPar::fZ, FairRunAna::GetField(), FairRunAna::Instance(), Reset(), and SetPlane().
 {
   Reset();
   SetPlane(o, dj, dk);
   fU = 0;
   fV = v;
   fW = w;
   fTV = Tv;
   fTW = Tw;
   fQp = qp;
   fSPU = spu;
   Double_t P  = TMath::Abs(1/fQp);
   //fq= int (P * fQp);
   fq = (int)TMath::Sign(1.0, fQp);
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=CovMatrix[i];
   }
   fPx_sd = fSPU*TMath::Sqrt( P*P / ( fTV*fTV + fTW*fTW + 1 ) );
   fPy_sd = fTV * fPx_sd;
   fPz_sd = fTW * fPx_sd;
   FairGeaneUtil util;
   TVector3 position = util.FromSDToMARSCoord(TVector3(fU, fV, fW), forigin, fiver, fjver, fkver);
   fX = position.X();
   fY = position.Y();
   fZ = position.Z();
   fDQp = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDTV = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDTW = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDV  = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDW  = TMath::Sqrt(fabs(fCovMatrix[14]));
   Double_t PD[3],RD[6][6],H[3],PC[3],RC[15], SP1;
   Int_t CH;
   PC[0]   = fQp;
   PC[1]   = fTV;
   PC[2]   = fTW;
   for(Int_t i=0; i<15; i++)  {
     RC[i]=fCovMatrix[i];
   }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   TVector3 momsd = TVector3(fPx_sd,fPy_sd,fPz_sd);
   // SP1 = (momsd.Dot(fjver.Cross(fkver)))/TMath::Abs(momsd.Dot(fjver.Cross(fkver)));
   SP1=fSPU;
   util.FromSDToMars(PC, RC, H, CH, SP1, fDJ, fDK, PD, RD);
   fPx = PD[0];
   fPy = PD[1];
   fPz = PD[2];
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
   fDPx = TMath::Sqrt(fabs(RD[0][0]));
   fDPy = TMath::Sqrt(fabs(RD[1][1]));
   fDPz = TMath::Sqrt(fabs(RD[2][2]));
   fDX  = TMath::Sqrt(fabs(RD[3][3]));
   fDY  = TMath::Sqrt(fabs(RD[4][4]));
   fDZ  = TMath::Sqrt(fabs(RD[5][5]));
 }
void FairTrackParP::SetTransportMatrix (Double_t mat[5][5])
Definition at line 890 of file FairTrackParP.cxx.
References ftrmat.
 {
   for(int i = 0; i < 5; i++) for(int j = 0; j < 5; j++) { ftrmat[i][j] = mat[i][j]; }
 }
void FairTrackParP::SetTV (Double_t tv) inline
Modifiers
Definition at line 82 of file FairTrackParP.h.
References fTV.
 { fTV = tv; };
void FairTrackParP::SetTW (Double_t tw) inline
Definition at line 83 of file FairTrackParP.h.
References fTW.
 { fTW = tw; };
virtual void FairTrackPar::SetX (Double_t x) inline virtual inherited
Definition at line 93 of file FairTrackPar.h.
References FairTrackPar::fX.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), SetTrackPar(), and FairTrackParH::SetTrackPar().
{
       fX  = x;
     };
virtual void FairTrackPar::SetY (Double_t y) inline virtual inherited
Definition at line 96 of file FairTrackPar.h.
References FairTrackPar::fY.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), SetTrackPar(), and FairTrackParH::SetTrackPar().
{
       fY  = y;
     };
virtual void FairTrackPar::SetZ (Double_t z) inline virtual inherited
Definition at line 99 of file FairTrackPar.h.
References FairTrackPar::fZ.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), SetTrackPar(), and FairTrackParH::SetTrackPar().
{
       fZ  = z;
     };
Member Data Documentation
Double_t FairTrackParP::fCovMatrix[15] private
Covariant matrix
Definition at line 145 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetCov(), GetCovQ(), Reset(), and SetTrackPar().
Double_t FairTrackParP::fCovMatrix66[6][6] private
Definition at line 147 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetMARSCov(), and SetTrackPar().
Double_t FairTrackParP::fDI[3] private
Definition at line 157 of file FairTrackParP.h.
Referenced by SetPlane().
Double_t FairTrackParP::fDJ[3] private
Definition at line 158 of file FairTrackParP.h.
Referenced by FairTrackParP(), SetPlane(), and SetTrackPar().
Double_t FairTrackParP::fDK[3] private
Definition at line 159 of file FairTrackParP.h.
Referenced by FairTrackParP(), SetPlane(), and SetTrackPar().
Double_t FairTrackPar::fDPx protected inherited
Error in momentum [GeV]
Definition at line 150 of file FairTrackPar.h.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetDPx(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetDPx(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDPy protected inherited
Definition at line 150 of file FairTrackPar.h.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetDPy(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetDPy(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDPz protected inherited
Definition at line 150 of file FairTrackPar.h.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetDPz(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetDPz(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDQp protected inherited
Error in charge over momentum [1/GeV]
Definition at line 156 of file FairTrackPar.h.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetDQp(), Reset(), FairTrackParH::Reset(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackParP::fDTV private
Definition at line 142 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetDTV(), Reset(), and SetTrackPar().
Double_t FairTrackParP::fDTW private
Definition at line 142 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetDTW(), Reset(), and SetTrackPar().
Double_t FairTrackParP::fDU private
Errors in SD system
Definition at line 142 of file FairTrackParP.h.
Double_t FairTrackParP::fDV private
Definition at line 142 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetDV(), Reset(), and SetTrackPar().
Double_t FairTrackParP::fDW private
Definition at line 142 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetDW(), Reset(), and SetTrackPar().
Double_t FairTrackPar::fDX protected inherited
Error in position of track [cm]
Definition at line 144 of file FairTrackPar.h.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetDX(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetDX(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDY protected inherited
Definition at line 144 of file FairTrackPar.h.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetDY(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetDY(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDZ protected inherited
Definition at line 144 of file FairTrackPar.h.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetDZ(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetDZ(), SetTrackPar(), and FairTrackParH::SetTrackPar().
TVector3 FairTrackParP::fiver private
Definition at line 154 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetIVer(), SetPlane(), and SetTrackPar().
TVector3 FairTrackParP::fjver private
Definition at line 155 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetJVer(), SetPlane(), and SetTrackPar().
TVector3 FairTrackParP::fkver private
Definition at line 156 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetKVer(), SetPlane(), and SetTrackPar().
TVector3 FairTrackParP::forigin private
Definition at line 153 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetOrigin(), SetPlane(), and SetTrackPar().
Double_t FairTrackPar::fPx protected inherited
momentum [GeV]
Definition at line 147 of file FairTrackPar.h.
Referenced by FairTrackParH::CalCov(), FairTrackPar::FairTrackPar(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetMomentum(), FairTrackPar::GetPx(), FairTrackPar::Print(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetPx(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackParP::fPx_sd private
momentum id SD
Definition at line 140 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetSDMomentum(), Reset(), and SetTrackPar().
Double_t FairTrackPar::fPy protected inherited
Definition at line 147 of file FairTrackPar.h.
Referenced by FairTrackParH::CalCov(), FairTrackPar::FairTrackPar(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetMomentum(), FairTrackPar::GetPy(), FairTrackPar::Print(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetPy(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackParP::fPy_sd private
Definition at line 140 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetSDMomentum(), Reset(), and SetTrackPar().
Double_t FairTrackPar::fPz protected inherited
Definition at line 147 of file FairTrackPar.h.
Referenced by FairTrackParH::CalCov(), FairTrackPar::FairTrackPar(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetMomentum(), FairTrackPar::GetPz(), FairTrackPar::Print(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetPz(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackParP::fPz_sd private
Definition at line 140 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetSDMomentum(), Reset(), and SetTrackPar().
Int_t FairTrackPar::fq protected inherited
charge
Definition at line 159 of file FairTrackPar.h.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackParH::GetCovQ(), GetCovQ(), FairTrackPar::GetQ(), Reset(), FairTrackParH::Reset(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fQp protected inherited
Charge over momentum [1/GeV]
Definition at line 153 of file FairTrackPar.h.
Referenced by FairTrackPar::FairTrackPar(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetQp(), FairTrackParH::Print(), Print(), Reset(), FairTrackParH::Reset(), FairTrackPar::SetQp(), SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackParP::fSPU private
Definition at line 161 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetSPU(), and SetTrackPar().
Double_t FairTrackParP::ftrmat[5][5] private
Definition at line 163 of file FairTrackParP.h.
Referenced by GetTransportMatrix(), and SetTransportMatrix().
Double_t FairTrackParP::fTV private
Definition at line 138 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetTV(), Print(), Reset(), SetTrackPar(), and SetTV().
Double_t FairTrackParP::fTW private
Definition at line 138 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetTW(), Print(), Reset(), SetTrackPar(), and SetTW().
Double_t FairTrackParP::fU private
Points coordinates in SD system
Definition at line 138 of file FairTrackParP.h.
Referenced by FairTrackParP(), Reset(), and SetTrackPar().
Double_t FairTrackParP::fV private
Definition at line 138 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetV(), Reset(), and SetTrackPar().
Double_t FairTrackParP::fW private
Definition at line 138 of file FairTrackParP.h.
Referenced by FairTrackParP(), GetW(), Reset(), and SetTrackPar().
Double_t FairTrackPar::fX protected inherited
Position of track [cm]
Definition at line 135 of file FairTrackPar.h.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetPosition(), FairTrackPar::GetX(), FairTrackParH::GetX(), FairTrackPar::Print(), FairTrackParH::Print(), Print(), Reset(), FairTrackParH::Reset(), SetTrackPar(), FairTrackParH::SetTrackPar(), and FairTrackPar::SetX().
Double_t FairTrackPar::fY protected inherited
Definition at line 135 of file FairTrackPar.h.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetPosition(), FairTrackPar::GetY(), FairTrackParH::GetY(), FairTrackPar::Print(), FairTrackParH::Print(), Print(), Reset(), FairTrackParH::Reset(), SetTrackPar(), FairTrackParH::SetTrackPar(), and FairTrackPar::SetY().
Double_t FairTrackPar::fZ protected inherited
Definition at line 135 of file FairTrackPar.h.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP(), FairTrackPar::GetPosition(), FairTrackPar::GetZ(), FairTrackParH::GetZ(), FairTrackPar::Print(), FairTrackParH::Print(), Print(), Reset(), FairTrackParH::Reset(), SetTrackPar(), FairTrackParH::SetTrackPar(), and FairTrackPar::SetZ().
The documentation for this class was generated from the following files:
FairTrackParP.h
FairTrackParP.cxx