FairRoot: TestDetectorProto::Hit Class Reference
TestDetectorProto::Hit Class Reference
#include <FairTestDetectorPayload.pb.h>
Public Member Functions
Hit ()
virtual ~Hit ()
Hit (const Hit &from)
Hit & operator= (const Hit &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Hit *other)
Hit * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Hit &from)
void MergeFrom (const Hit &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_detid () const
void clear_detid ()
inline::google::protobuf::int32 detid () const
void set_detid (::google::protobuf::int32 value)
bool has_mcindex () const
void clear_mcindex ()
inline::google::protobuf::int32 mcindex () const
void set_mcindex (::google::protobuf::int32 value)
bool has_posx () const
void clear_posx ()
double posx () const
void set_posx (double value)
bool has_posy () const
void clear_posy ()
double posy () const
void set_posy (double value)
bool has_posz () const
void clear_posz ()
double posz () const
void set_posz (double value)
bool has_dposx () const
void clear_dposx ()
double dposx () const
void set_dposx (double value)
bool has_dposy () const
void clear_dposy ()
double dposy () const
void set_dposy (double value)
bool has_dposz () const
void clear_dposz ()
double dposz () const
void set_dposz (double value)
bool has_ftimestamp () const
void clear_ftimestamp ()
double ftimestamp () const
void set_ftimestamp (double value)
bool has_ftimestamperror () const
void clear_ftimestamperror ()
double ftimestamperror () const
void set_ftimestamperror (double value)
Hit ()
virtual ~Hit ()
Hit (const Hit &from)
Hit & operator= (const Hit &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Hit *other)
Hit * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Hit &from)
void MergeFrom (const Hit &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_detid () const
void clear_detid ()
inline::google::protobuf::int32 detid () const
void set_detid (::google::protobuf::int32 value)
bool has_mcindex () const
void clear_mcindex ()
inline::google::protobuf::int32 mcindex () const
void set_mcindex (::google::protobuf::int32 value)
bool has_posx () const
void clear_posx ()
double posx () const
void set_posx (double value)
bool has_posy () const
void clear_posy ()
double posy () const
void set_posy (double value)
bool has_posz () const
void clear_posz ()
double posz () const
void set_posz (double value)
bool has_dposx () const
void clear_dposx ()
double dposx () const
void set_dposx (double value)
bool has_dposy () const
void clear_dposy ()
double dposy () const
void set_dposy (double value)
bool has_dposz () const
void clear_dposz ()
double dposz () const
void set_dposz (double value)
bool has_ftimestamp () const
void clear_ftimestamp ()
double ftimestamp () const
void set_ftimestamp (double value)
bool has_ftimestamperror () const
void clear_ftimestamperror ()
double ftimestamperror () const
void set_ftimestamperror (double value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Hit & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const Hit & default_instance ()
Static Public Attributes
static const int kDetIDFieldNumber = 1
static const int kMcindexFieldNumber = 2
static const int kPosXFieldNumber = 3
static const int kPosYFieldNumber = 4
static const int kPosZFieldNumber = 5
static const int kDposXFieldNumber = 6
static const int kDposYFieldNumber = 7
static const int kDposZFieldNumber = 8
static const int kFTimeStampFieldNumber = 9
static const int kFTimeStampErrorFieldNumber = 10
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_detid ()
void clear_has_detid ()
void set_has_mcindex ()
void clear_has_mcindex ()
void set_has_posx ()
void clear_has_posx ()
void set_has_posy ()
void clear_has_posy ()
void set_has_posz ()
void clear_has_posz ()
void set_has_dposx ()
void clear_has_dposx ()
void set_has_dposy ()
void clear_has_dposy ()
void set_has_dposz ()
void clear_has_dposz ()
void set_has_ftimestamp ()
void clear_has_ftimestamp ()
void set_has_ftimestamperror ()
void clear_has_ftimestamperror ()
void InitAsDefaultInstance ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_detid ()
void clear_has_detid ()
void set_has_mcindex ()
void clear_has_mcindex ()
void set_has_posx ()
void clear_has_posx ()
void set_has_posy ()
void clear_has_posy ()
void set_has_posz ()
void clear_has_posz ()
void set_has_dposx ()
void clear_has_dposx ()
void set_has_dposy ()
void clear_has_dposy ()
void set_has_dposz ()
void clear_has_dposz ()
void set_has_ftimestamp ()
void clear_has_ftimestamp ()
void set_has_ftimestamperror ()
void clear_has_ftimestamperror ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::int32 detid_
::google::protobuf::int32 mcindex_
double posx_
double posy_
double posz_
double dposx_
double dposy_
double dposz_
double ftimestamp_
double ftimestamperror_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(10+31)/32]
Static Private Attributes
static Hit * default_instance_ = NULL
Friends
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
Detailed Description
Definition at line 165 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Constructor & Destructor Documentation
TestDetectorProto::Hit::Hit ()
Definition at line 570 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References SharedCtor().
Referenced by New().
   : ::google::protobuf::Message() {
   SharedCtor();
 }
TestDetectorProto::Hit::~Hit () virtual
Definition at line 599 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References SharedDtor().
           {
   SharedDtor();
 }
TestDetectorProto::Hit::Hit (const Hit & from)
Definition at line 578 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References MergeFrom(), and SharedCtor().
   : ::google::protobuf::Message() {
   SharedCtor();
   MergeFrom(from);
 }
TestDetectorProto::Hit::Hit ()
virtual TestDetectorProto::Hit::~Hit () virtual
TestDetectorProto::Hit::Hit (const Hit & from)
Member Function Documentation
int TestDetectorProto::Hit::ByteSize () const
Definition at line 946 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, _has_bits_, detid(), has_detid(), has_dposx(), has_dposy(), has_dposz(), has_ftimestamp(), has_ftimestamperror(), has_mcindex(), has_posx(), has_posy(), has_posz(), mcindex(), and unknown_fields().
{
   int total_size = 0;
   if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     // optional int32 detID = 1;
     if (has_detid()) {
       total_size += 1 +
         ::google::protobuf::internal::WireFormatLite::Int32Size(
           this->detid());
     }
     // optional int32 mcindex = 2;
     if (has_mcindex()) {
       total_size += 1 +
         ::google::protobuf::internal::WireFormatLite::Int32Size(
           this->mcindex());
     }
     // optional double posX = 3;
     if (has_posx()) {
       total_size += 1 + 8;
     }
     // optional double posY = 4;
     if (has_posy()) {
       total_size += 1 + 8;
     }
     // optional double posZ = 5;
     if (has_posz()) {
       total_size += 1 + 8;
     }
     // optional double dposX = 6;
     if (has_dposx()) {
       total_size += 1 + 8;
     }
     // optional double dposY = 7;
     if (has_dposy()) {
       total_size += 1 + 8;
     }
     // optional double dposZ = 8;
     if (has_dposz()) {
       total_size += 1 + 8;
     }
   }
   if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
     // optional double fTimeStamp = 9;
     if (has_ftimestamp()) {
       total_size += 1 + 8;
     }
     // optional double fTimeStampError = 10;
     if (has_ftimestamperror()) {
       total_size += 1 + 8;
     }
   }
   if (!unknown_fields().empty()) {
     total_size +=
       ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
         unknown_fields());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
int TestDetectorProto::Hit::ByteSize () const
void TestDetectorProto::Hit::Clear ()
void TestDetectorProto::Hit::Clear ()
Definition at line 629 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _has_bits_, detid_, dposx_, dposy_, dposz_, ftimestamp_, ftimestamperror_, mcindex_, mutable_unknown_fields(), posx_, posy_, and posz_.
Referenced by CopyFrom().
                 {
   if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     detid_ = 0;
     mcindex_ = 0;
     posx_ = 0;
     posy_ = 0;
     posz_ = 0;
     dposx_ = 0;
     dposy_ = 0;
     dposz_ = 0;
   }
   if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
     ftimestamp_ = 0;
     ftimestamperror_ = 0;
   }
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
   mutable_unknown_fields()->Clear();
 }
void TestDetectorProto::Hit::clear_detid () inline
Definition at line 636 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_detid(), and detid_.
{
   detid_ = 0;
   clear_has_detid();
 }
void TestDetectorProto::Hit::clear_detid () inline
void TestDetectorProto::Hit::clear_dposx () inline
Definition at line 746 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_dposx(), and dposx_.
{
   dposx_ = 0;
   clear_has_dposx();
 }
void TestDetectorProto::Hit::clear_dposx () inline
void TestDetectorProto::Hit::clear_dposy () inline
void TestDetectorProto::Hit::clear_dposy () inline
Definition at line 768 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_dposy(), and dposy_.
{
   dposy_ = 0;
   clear_has_dposy();
 }
void TestDetectorProto::Hit::clear_dposz () inline
void TestDetectorProto::Hit::clear_dposz () inline
Definition at line 790 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_dposz(), and dposz_.
{
   dposz_ = 0;
   clear_has_dposz();
 }
void TestDetectorProto::Hit::clear_ftimestamp () inline
void TestDetectorProto::Hit::clear_ftimestamp () inline
Definition at line 812 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_ftimestamp(), and ftimestamp_.
{
   ftimestamp_ = 0;
   clear_has_ftimestamp();
 }
void TestDetectorProto::Hit::clear_ftimestamperror () inline
void TestDetectorProto::Hit::clear_ftimestamperror () inline
Definition at line 834 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_ftimestamperror(), and ftimestamperror_.
{
   ftimestamperror_ = 0;
   clear_has_ftimestamperror();
 }
void TestDetectorProto::Hit::clear_has_detid () inline private
Definition at line 633 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_detid().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void TestDetectorProto::Hit::clear_has_detid () inline private
void TestDetectorProto::Hit::clear_has_dposx () inline private
Definition at line 743 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_dposx().
{
   _has_bits_[0] &= ~0x00000020u;
 }
void TestDetectorProto::Hit::clear_has_dposx () inline private
void TestDetectorProto::Hit::clear_has_dposy () inline private
Definition at line 765 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_dposy().
{
   _has_bits_[0] &= ~0x00000040u;
 }
void TestDetectorProto::Hit::clear_has_dposy () inline private
void TestDetectorProto::Hit::clear_has_dposz () inline private
Definition at line 787 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_dposz().
{
   _has_bits_[0] &= ~0x00000080u;
 }
void TestDetectorProto::Hit::clear_has_dposz () inline private
void TestDetectorProto::Hit::clear_has_ftimestamp () inline private
void TestDetectorProto::Hit::clear_has_ftimestamp () inline private
Definition at line 809 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_ftimestamp().
{
   _has_bits_[0] &= ~0x00000100u;
 }
void TestDetectorProto::Hit::clear_has_ftimestamperror () inline private
Definition at line 831 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_ftimestamperror().
{
   _has_bits_[0] &= ~0x00000200u;
 }
void TestDetectorProto::Hit::clear_has_ftimestamperror () inline private
void TestDetectorProto::Hit::clear_has_mcindex () inline private
Definition at line 655 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_mcindex().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void TestDetectorProto::Hit::clear_has_mcindex () inline private
void TestDetectorProto::Hit::clear_has_posx () inline private
Definition at line 677 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_posx().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void TestDetectorProto::Hit::clear_has_posx () inline private
void TestDetectorProto::Hit::clear_has_posy () inline private
Definition at line 699 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_posy().
{
   _has_bits_[0] &= ~0x00000008u;
 }
void TestDetectorProto::Hit::clear_has_posy () inline private
void TestDetectorProto::Hit::clear_has_posz () inline private
Definition at line 721 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_posz().
{
   _has_bits_[0] &= ~0x00000010u;
 }
void TestDetectorProto::Hit::clear_has_posz () inline private
void TestDetectorProto::Hit::clear_mcindex () inline
void TestDetectorProto::Hit::clear_mcindex () inline
Definition at line 658 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_mcindex(), and mcindex_.
{
   mcindex_ = 0;
   clear_has_mcindex();
 }
void TestDetectorProto::Hit::clear_posx () inline
Definition at line 680 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_posx(), and posx_.
{
   posx_ = 0;
   clear_has_posx();
 }
void TestDetectorProto::Hit::clear_posx () inline
void TestDetectorProto::Hit::clear_posy () inline
Definition at line 702 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_posy(), and posy_.
{
   posy_ = 0;
   clear_has_posy();
 }
void TestDetectorProto::Hit::clear_posy () inline
void TestDetectorProto::Hit::clear_posz () inline
Definition at line 724 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_posz(), and posz_.
{
   posz_ = 0;
   clear_has_posz();
 }
void TestDetectorProto::Hit::clear_posz () inline
void TestDetectorProto::Hit::CopyFrom (const ::google::protobuf::Message & from)
void TestDetectorProto::Hit::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1069 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void TestDetectorProto::Hit::CopyFrom (const Hit & from)
Definition at line 1075 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Clear(), and MergeFrom().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void TestDetectorProto::Hit::CopyFrom (const Hit & from)
const Hit & TestDetectorProto::Hit::default_instance () static
Definition at line 618 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References default_instance_, and protobuf_AddDesc_FairTestDetectorPayload_2eproto.
{
   if (default_instance_ == NULL) protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   return *default_instance_;
 }
static const Hit& TestDetectorProto::Hit::default_instance () static
const ::google::protobuf::Descriptor * TestDetectorProto::Hit::descriptor () static
Definition at line 613 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   return Hit_descriptor_;
 }
static const ::google::protobuf::Descriptor* TestDetectorProto::Hit::descriptor () static
google::protobuf::int32 TestDetectorProto::Hit::detid () const inline
Definition at line 640 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References detid_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return detid_;
 }
inline ::google::protobuf::int32 TestDetectorProto::Hit::detid () const
double TestDetectorProto::Hit::dposx () const inline
double TestDetectorProto::Hit::dposx () const inline
Definition at line 750 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References dposx_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return dposx_;
 }
double TestDetectorProto::Hit::dposy () const inline
double TestDetectorProto::Hit::dposy () const inline
Definition at line 772 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References dposy_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return dposy_;
 }
double TestDetectorProto::Hit::dposz () const inline
double TestDetectorProto::Hit::dposz () const inline
Definition at line 794 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References dposz_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return dposz_;
 }
double TestDetectorProto::Hit::ftimestamp () const inline
double TestDetectorProto::Hit::ftimestamp () const inline
Definition at line 816 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References ftimestamp_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return ftimestamp_;
 }
double TestDetectorProto::Hit::ftimestamperror () const inline
double TestDetectorProto::Hit::ftimestamperror () const inline
Definition at line 838 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References ftimestamperror_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return ftimestamperror_;
 }
int TestDetectorProto::Hit::GetCachedSize () const inline
Definition at line 206 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _cached_size_.
 { return _cached_size_; }
int TestDetectorProto::Hit::GetCachedSize () const inline
Definition at line 206 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _cached_size_.
 { return _cached_size_; }
google::protobuf::Metadata TestDetectorProto::Hit::GetMetadata () const
Definition at line 1104 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::Metadata metadata;
   metadata.descriptor = Hit_descriptor_;
   metadata.reflection = Hit_reflection_;
   return metadata;
 }
::google::protobuf::Metadata TestDetectorProto::Hit::GetMetadata () const
bool TestDetectorProto::Hit::has_detid () const inline
Definition at line 627 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool TestDetectorProto::Hit::has_detid () const inline
bool TestDetectorProto::Hit::has_dposx () const inline
Definition at line 737 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
bool TestDetectorProto::Hit::has_dposx () const inline
bool TestDetectorProto::Hit::has_dposy () const inline
bool TestDetectorProto::Hit::has_dposy () const inline
Definition at line 759 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000040u) != 0;
 }
bool TestDetectorProto::Hit::has_dposz () const inline
bool TestDetectorProto::Hit::has_dposz () const inline
Definition at line 781 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000080u) != 0;
 }
bool TestDetectorProto::Hit::has_ftimestamp () const inline
bool TestDetectorProto::Hit::has_ftimestamp () const inline
Definition at line 803 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000100u) != 0;
 }
bool TestDetectorProto::Hit::has_ftimestamperror () const inline
bool TestDetectorProto::Hit::has_ftimestamperror () const inline
Definition at line 825 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000200u) != 0;
 }
bool TestDetectorProto::Hit::has_mcindex () const inline
Definition at line 649 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool TestDetectorProto::Hit::has_mcindex () const inline
bool TestDetectorProto::Hit::has_posx () const inline
bool TestDetectorProto::Hit::has_posx () const inline
Definition at line 671 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool TestDetectorProto::Hit::has_posy () const inline
Definition at line 693 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool TestDetectorProto::Hit::has_posy () const inline
bool TestDetectorProto::Hit::has_posz () const inline
Definition at line 715 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool TestDetectorProto::Hit::has_posz () const inline
void TestDetectorProto::Hit::InitAsDefaultInstance () private
Definition at line 575 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto().
{
 }
void TestDetectorProto::Hit::InitAsDefaultInstance () private
bool TestDetectorProto::Hit::IsInitialized () const
bool TestDetectorProto::Hit::IsInitialized () const
Definition at line 1081 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   return true;
 }
inline ::google::protobuf::int32 TestDetectorProto::Hit::mcindex () const
google::protobuf::int32 TestDetectorProto::Hit::mcindex () const inline
Definition at line 662 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References mcindex_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return mcindex_;
 }
void TestDetectorProto::Hit::MergeFrom (const ::google::protobuf::Message & from)
void TestDetectorProto::Hit::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1018 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by CopyFrom(), and Hit().
{
   GOOGLE_CHECK_NE(&from, this);
   const Hit* source =
     ::google::protobuf::internal::dynamic_cast_if_available<const Hit*>(
       &from);
   if (source == NULL) {
     ::google::protobuf::internal::ReflectionOps::Merge(from, this);
   } else {
     MergeFrom(*source);
   }
 }
void TestDetectorProto::Hit::MergeFrom (const Hit & from)
Definition at line 1030 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _has_bits_, detid(), dposx(), dposy(), dposz(), ftimestamp(), ftimestamperror(), has_detid(), has_dposx(), has_dposy(), has_dposz(), has_ftimestamp(), has_ftimestamperror(), has_mcindex(), has_posx(), has_posy(), has_posz(), mcindex(), mutable_unknown_fields(), posx(), posy(), posz(), set_detid(), set_dposx(), set_dposy(), set_dposz(), set_ftimestamp(), set_ftimestamperror(), set_mcindex(), set_posx(), set_posy(), set_posz(), and unknown_fields().
{
   GOOGLE_CHECK_NE(&from, this);
   if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     if (from.has_detid()) {
       set_detid(from.detid());
     }
     if (from.has_mcindex()) {
       set_mcindex(from.mcindex());
     }
     if (from.has_posx()) {
       set_posx(from.posx());
     }
     if (from.has_posy()) {
       set_posy(from.posy());
     }
     if (from.has_posz()) {
       set_posz(from.posz());
     }
     if (from.has_dposx()) {
       set_dposx(from.dposx());
     }
     if (from.has_dposy()) {
       set_dposy(from.dposy());
     }
     if (from.has_dposz()) {
       set_dposz(from.dposz());
     }
   }
   if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
     if (from.has_ftimestamp()) {
       set_ftimestamp(from.ftimestamp());
     }
     if (from.has_ftimestamperror()) {
       set_ftimestamperror(from.ftimestamperror());
     }
   }
   mutable_unknown_fields()->MergeFrom(from.unknown_fields());
 }
void TestDetectorProto::Hit::MergeFrom (const Hit & from)
bool TestDetectorProto::Hit::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool TestDetectorProto::Hit::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 648 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References detid_, DO_, dposx_, dposy_, dposz_, ftimestamp_, ftimestamperror_, mcindex_, mutable_unknown_fields(), posx_, posy_, posz_, set_has_detid(), set_has_dposx(), set_has_dposy(), set_has_dposz(), set_has_ftimestamp(), set_has_ftimestamperror(), set_has_mcindex(), set_has_posx(), set_has_posy(), and set_has_posz().
{
 #define DO_(EXPRESSION) if (!(EXPRESSION)) return false
   ::google::protobuf::uint32 tag;
   while ((tag = input->ReadTag()) != 0) {
     switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
       // optional int32 detID = 1;
       case 1: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, &detid_)));
           set_has_detid();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(16)) goto parse_mcindex;
         break;
       }
       // optional int32 mcindex = 2;
       case 2: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          parse_mcindex:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, &mcindex_)));
           set_has_mcindex();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(25)) goto parse_posX;
         break;
       }
       // optional double posX = 3;
       case 3: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_posX:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &posx_)));
           set_has_posx();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(33)) goto parse_posY;
         break;
       }
       // optional double posY = 4;
       case 4: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_posY:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &posy_)));
           set_has_posy();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(41)) goto parse_posZ;
         break;
       }
       // optional double posZ = 5;
       case 5: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_posZ:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &posz_)));
           set_has_posz();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(49)) goto parse_dposX;
         break;
       }
       // optional double dposX = 6;
       case 6: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_dposX:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &dposx_)));
           set_has_dposx();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(57)) goto parse_dposY;
         break;
       }
       // optional double dposY = 7;
       case 7: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_dposY:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &dposy_)));
           set_has_dposy();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(65)) goto parse_dposZ;
         break;
       }
       // optional double dposZ = 8;
       case 8: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_dposZ:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &dposz_)));
           set_has_dposz();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(73)) goto parse_fTimeStamp;
         break;
       }
       // optional double fTimeStamp = 9;
       case 9: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_fTimeStamp:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &ftimestamp_)));
           set_has_ftimestamp();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(81)) goto parse_fTimeStampError;
         break;
       }
       // optional double fTimeStampError = 10;
       case 10: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_fTimeStampError:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &ftimestamperror_)));
           set_has_ftimestamperror();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectAtEnd()) return true;
         break;
       }
       default: {
       handle_uninterpreted:
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
           return true;
         }
         DO_(::google::protobuf::internal::WireFormat::SkipField(
               input, tag, mutable_unknown_fields()));
         break;
       }
     }
   }
   return true;
 #undef DO_
 }
inline ::google::protobuf::UnknownFieldSet* TestDetectorProto::Hit::mutable_unknown_fields () inline
Definition at line 181 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
{
     return &_unknown_fields_;
   }
inline ::google::protobuf::UnknownFieldSet* TestDetectorProto::Hit::mutable_unknown_fields () inline
Definition at line 181 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
{
     return &_unknown_fields_;
   }
Hit* TestDetectorProto::Hit::New () const
Hit * TestDetectorProto::Hit::New () const
Definition at line 625 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Hit().
                     {
   return new Hit;
 }
Hit& TestDetectorProto::Hit::operator= (const Hit & from) inline
Definition at line 172 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
Hit& TestDetectorProto::Hit::operator= (const Hit & from) inline
Definition at line 172 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
double TestDetectorProto::Hit::posx () const inline
Definition at line 684 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References posx_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return posx_;
 }
double TestDetectorProto::Hit::posx () const inline
double TestDetectorProto::Hit::posy () const inline
Definition at line 706 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References posy_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return posy_;
 }
double TestDetectorProto::Hit::posy () const inline
double TestDetectorProto::Hit::posz () const inline
Definition at line 728 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References posz_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return posz_;
 }
double TestDetectorProto::Hit::posz () const inline
void TestDetectorProto::Hit::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 829 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References detid(), dposx(), dposy(), dposz(), ftimestamp(), ftimestamperror(), has_detid(), has_dposx(), has_dposy(), has_dposz(), has_ftimestamp(), has_ftimestamperror(), has_mcindex(), has_posx(), has_posy(), has_posz(), mcindex(), posx(), posy(), posz(), and unknown_fields().
{
   // optional int32 detID = 1;
   if (has_detid()) {
     ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->detid(), output);
   }
   // optional int32 mcindex = 2;
   if (has_mcindex()) {
     ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->mcindex(), output);
   }
   // optional double posX = 3;
   if (has_posx()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->posx(), output);
   }
   // optional double posY = 4;
   if (has_posy()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->posy(), output);
   }
   // optional double posZ = 5;
   if (has_posz()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->posz(), output);
   }
   // optional double dposX = 6;
   if (has_dposx()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->dposx(), output);
   }
   // optional double dposY = 7;
   if (has_dposy()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->dposy(), output);
   }
   // optional double dposZ = 8;
   if (has_dposz()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->dposz(), output);
   }
   // optional double fTimeStamp = 9;
   if (has_ftimestamp()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->ftimestamp(), output);
   }
   // optional double fTimeStampError = 10;
   if (has_ftimestamperror()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->ftimestamperror(), output);
   }
   if (!unknown_fields().empty()) {
     ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
         unknown_fields(), output);
   }
 }
void TestDetectorProto::Hit::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
google::protobuf::uint8 * TestDetectorProto::Hit::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 887 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References detid(), dposx(), dposy(), dposz(), ftimestamp(), ftimestamperror(), has_detid(), has_dposx(), has_dposy(), has_dposz(), has_ftimestamp(), has_ftimestamperror(), has_mcindex(), has_posx(), has_posy(), has_posz(), mcindex(), posx(), posy(), posz(), and unknown_fields().
{
   // optional int32 detID = 1;
   if (has_detid()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->detid(), target);
   }
   // optional int32 mcindex = 2;
   if (has_mcindex()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->mcindex(), target);
   }
   // optional double posX = 3;
   if (has_posx()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->posx(), target);
   }
   // optional double posY = 4;
   if (has_posy()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->posy(), target);
   }
   // optional double posZ = 5;
   if (has_posz()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->posz(), target);
   }
   // optional double dposX = 6;
   if (has_dposx()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->dposx(), target);
   }
   // optional double dposY = 7;
   if (has_dposy()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->dposy(), target);
   }
   // optional double dposZ = 8;
   if (has_dposz()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->dposz(), target);
   }
   // optional double fTimeStamp = 9;
   if (has_ftimestamp()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->ftimestamp(), target);
   }
   // optional double fTimeStampError = 10;
   if (has_ftimestamperror()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->ftimestamperror(), target);
   }
   if (!unknown_fields().empty()) {
     target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
         unknown_fields(), target);
   }
   return target;
 }
::google::protobuf::uint8* TestDetectorProto::Hit::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
void TestDetectorProto::Hit::set_detid (::google::protobuf::int32 value) inline
Definition at line 643 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References detid_, and set_has_detid().
Referenced by MergeFrom().
{
   set_has_detid();
   detid_ = value;
 }
void TestDetectorProto::Hit::set_detid (::google::protobuf::int32 value) inline
void TestDetectorProto::Hit::set_dposx (double value) inline
void TestDetectorProto::Hit::set_dposx (double value) inline
Definition at line 753 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References dposx_, and set_has_dposx().
Referenced by MergeFrom().
{
   set_has_dposx();
   dposx_ = value;
 }
void TestDetectorProto::Hit::set_dposy (double value) inline
void TestDetectorProto::Hit::set_dposy (double value) inline
Definition at line 775 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References dposy_, and set_has_dposy().
Referenced by MergeFrom().
{
   set_has_dposy();
   dposy_ = value;
 }
void TestDetectorProto::Hit::set_dposz (double value) inline
void TestDetectorProto::Hit::set_dposz (double value) inline
Definition at line 797 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References dposz_, and set_has_dposz().
Referenced by MergeFrom().
{
   set_has_dposz();
   dposz_ = value;
 }
void TestDetectorProto::Hit::set_ftimestamp (double value) inline
void TestDetectorProto::Hit::set_ftimestamp (double value) inline
Definition at line 819 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References ftimestamp_, and set_has_ftimestamp().
Referenced by MergeFrom().
{
   set_has_ftimestamp();
   ftimestamp_ = value;
 }
void TestDetectorProto::Hit::set_ftimestamperror (double value) inline
Definition at line 841 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References ftimestamperror_, and set_has_ftimestamperror().
Referenced by MergeFrom().
{
   set_has_ftimestamperror();
   ftimestamperror_ = value;
 }
void TestDetectorProto::Hit::set_ftimestamperror (double value) inline
void TestDetectorProto::Hit::set_has_detid () inline private
void TestDetectorProto::Hit::set_has_detid () inline private
Definition at line 630 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_detid().
{
   _has_bits_[0] |= 0x00000001u;
 }
void TestDetectorProto::Hit::set_has_dposx () inline private
Definition at line 740 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_dposx().
{
   _has_bits_[0] |= 0x00000020u;
 }
void TestDetectorProto::Hit::set_has_dposx () inline private
void TestDetectorProto::Hit::set_has_dposy () inline private
void TestDetectorProto::Hit::set_has_dposy () inline private
Definition at line 762 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_dposy().
{
   _has_bits_[0] |= 0x00000040u;
 }
void TestDetectorProto::Hit::set_has_dposz () inline private
void TestDetectorProto::Hit::set_has_dposz () inline private
Definition at line 784 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_dposz().
{
   _has_bits_[0] |= 0x00000080u;
 }
void TestDetectorProto::Hit::set_has_ftimestamp () inline private
Definition at line 806 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_ftimestamp().
{
   _has_bits_[0] |= 0x00000100u;
 }
void TestDetectorProto::Hit::set_has_ftimestamp () inline private
void TestDetectorProto::Hit::set_has_ftimestamperror () inline private
void TestDetectorProto::Hit::set_has_ftimestamperror () inline private
Definition at line 828 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_ftimestamperror().
{
   _has_bits_[0] |= 0x00000200u;
 }
void TestDetectorProto::Hit::set_has_mcindex () inline private
Definition at line 652 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_mcindex().
{
   _has_bits_[0] |= 0x00000002u;
 }
void TestDetectorProto::Hit::set_has_mcindex () inline private
void TestDetectorProto::Hit::set_has_posx () inline private
Definition at line 674 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_posx().
{
   _has_bits_[0] |= 0x00000004u;
 }
void TestDetectorProto::Hit::set_has_posx () inline private
void TestDetectorProto::Hit::set_has_posy () inline private
void TestDetectorProto::Hit::set_has_posy () inline private
Definition at line 696 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_posy().
{
   _has_bits_[0] |= 0x00000008u;
 }
void TestDetectorProto::Hit::set_has_posz () inline private
Definition at line 718 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_posz().
{
   _has_bits_[0] |= 0x00000010u;
 }
void TestDetectorProto::Hit::set_has_posz () inline private
void TestDetectorProto::Hit::set_mcindex (::google::protobuf::int32 value) inline
Definition at line 665 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References mcindex_, and set_has_mcindex().
Referenced by MergeFrom().
{
   set_has_mcindex();
   mcindex_ = value;
 }
void TestDetectorProto::Hit::set_mcindex (::google::protobuf::int32 value) inline
void TestDetectorProto::Hit::set_posx (double value) inline
Definition at line 687 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References posx_, and set_has_posx().
Referenced by MergeFrom().
{
   set_has_posx();
   posx_ = value;
 }
void TestDetectorProto::Hit::set_posx (double value) inline
void TestDetectorProto::Hit::set_posy (double value) inline
void TestDetectorProto::Hit::set_posy (double value) inline
Definition at line 709 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References posy_, and set_has_posy().
Referenced by MergeFrom().
{
   set_has_posy();
   posy_ = value;
 }
void TestDetectorProto::Hit::set_posz (double value) inline
void TestDetectorProto::Hit::set_posz (double value) inline
Definition at line 731 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References posz_, and set_has_posz().
Referenced by MergeFrom().
{
   set_has_posz();
   posz_ = value;
 }
void TestDetectorProto::Hit::SetCachedSize (int size) const private
void TestDetectorProto::Hit::SetCachedSize (int size) const private
Definition at line 608 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_.
{
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
 }
void TestDetectorProto::Hit::SharedCtor () private
void TestDetectorProto::Hit::SharedCtor () private
Definition at line 584 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, _has_bits_, detid_, dposx_, dposy_, dposz_, ftimestamp_, ftimestamperror_, mcindex_, posx_, posy_, and posz_.
Referenced by Hit().
                      {
   _cached_size_ = 0;
   detid_ = 0;
   mcindex_ = 0;
   posx_ = 0;
   posy_ = 0;
   posz_ = 0;
   dposx_ = 0;
   dposy_ = 0;
   dposz_ = 0;
   ftimestamp_ = 0;
   ftimestamperror_ = 0;
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
 }
void TestDetectorProto::Hit::SharedDtor () private
void TestDetectorProto::Hit::SharedDtor () private
Definition at line 603 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References default_instance_.
Referenced by ~Hit().
                      {
   if (this != default_instance_) {
   }
 }
void TestDetectorProto::Hit::Swap (Hit * other)
void TestDetectorProto::Hit::Swap (Hit * other)
Definition at line 1086 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, detid_, dposx_, dposy_, dposz_, ftimestamp_, ftimestamperror_, mcindex_, posx_, posy_, and posz_.
{
   if (other != this) {
     std::swap(detid_, other->detid_);
     std::swap(mcindex_, other->mcindex_);
     std::swap(posx_, other->posx_);
     std::swap(posy_, other->posy_);
     std::swap(posz_, other->posz_);
     std::swap(dposx_, other->dposx_);
     std::swap(dposy_, other->dposy_);
     std::swap(dposz_, other->dposz_);
     std::swap(ftimestamp_, other->ftimestamp_);
     std::swap(ftimestamperror_, other->ftimestamperror_);
     std::swap(_has_bits_[0], other->_has_bits_[0]);
     _unknown_fields_.Swap(&other->_unknown_fields_);
     std::swap(_cached_size_, other->_cached_size_);
   }
 }
const ::google::protobuf::UnknownFieldSet& TestDetectorProto::Hit::unknown_fields () const inline
Definition at line 177 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
{
     return _unknown_fields_;
   }
const ::google::protobuf::UnknownFieldSet& TestDetectorProto::Hit::unknown_fields () const inline
Definition at line 177 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
     return _unknown_fields_;
   }
Friends And Related Function Documentation
void protobuf_AddDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by default_instance().
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void protobuf_AddDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto () friend
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto () friend
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
Member Data Documentation
int TestDetectorProto::Hit::_cached_size_ mutable private
Definition at line 325 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
google::protobuf::uint32 TestDetectorProto::Hit::_has_bits_ private
Definition at line 326 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by ByteSize(), Clear(), clear_has_detid(), clear_has_dposx(), clear_has_dposy(), clear_has_dposz(), clear_has_ftimestamp(), clear_has_ftimestamperror(), clear_has_mcindex(), clear_has_posx(), clear_has_posy(), clear_has_posz(), has_detid(), has_dposx(), has_dposy(), has_dposz(), has_ftimestamp(), has_ftimestamperror(), has_mcindex(), has_posx(), has_posy(), has_posz(), MergeFrom(), set_has_detid(), set_has_dposx(), set_has_dposy(), set_has_dposz(), set_has_ftimestamp(), set_has_ftimestamperror(), set_has_mcindex(), set_has_posx(), set_has_posy(), set_has_posz(), SharedCtor(), and Swap().
google::protobuf::UnknownFieldSet TestDetectorProto::Hit::_unknown_fields_ private
Definition at line 312 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
static Hit * TestDetectorProto::Hit::default_instance_ = NULL static private
Definition at line 333 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by default_instance(), TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto(), TestDetectorProto::protobuf_AssignDesc_FairTestDetectorPayload_2eproto(), TestDetectorProto::protobuf_ShutdownFile_FairTestDetectorPayload_2eproto(), and SharedDtor().
google::protobuf::int32 TestDetectorProto::Hit::detid_ private
Definition at line 314 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_detid(), detid(), MergePartialFromCodedStream(), set_detid(), SharedCtor(), and Swap().
double TestDetectorProto::Hit::dposx_ private
Definition at line 319 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_dposx(), dposx(), MergePartialFromCodedStream(), set_dposx(), SharedCtor(), and Swap().
double TestDetectorProto::Hit::dposy_ private
Definition at line 320 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_dposy(), dposy(), MergePartialFromCodedStream(), set_dposy(), SharedCtor(), and Swap().
double TestDetectorProto::Hit::dposz_ private
Definition at line 321 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_dposz(), dposz(), MergePartialFromCodedStream(), set_dposz(), SharedCtor(), and Swap().
double TestDetectorProto::Hit::ftimestamp_ private
Definition at line 322 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_ftimestamp(), ftimestamp(), MergePartialFromCodedStream(), set_ftimestamp(), SharedCtor(), and Swap().
double TestDetectorProto::Hit::ftimestamperror_ private
Definition at line 323 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_ftimestamperror(), ftimestamperror(), MergePartialFromCodedStream(), set_ftimestamperror(), SharedCtor(), and Swap().
static const int TestDetectorProto::Hit::kDetIDFieldNumber = 1 static
Definition at line 222 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kDposXFieldNumber = 6 static
Definition at line 257 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kDposYFieldNumber = 7 static
Definition at line 264 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kDposZFieldNumber = 8 static
Definition at line 271 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kFTimeStampErrorFieldNumber = 10 static
Definition at line 285 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kFTimeStampFieldNumber = 9 static
Definition at line 278 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kMcindexFieldNumber = 2 static
Definition at line 229 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kPosXFieldNumber = 3 static
Definition at line 236 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kPosYFieldNumber = 4 static
Definition at line 243 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Hit::kPosZFieldNumber = 5 static
Definition at line 250 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
google::protobuf::int32 TestDetectorProto::Hit::mcindex_ private
Definition at line 315 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_mcindex(), mcindex(), MergePartialFromCodedStream(), set_mcindex(), SharedCtor(), and Swap().
double TestDetectorProto::Hit::posx_ private
Definition at line 316 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_posx(), MergePartialFromCodedStream(), posx(), set_posx(), SharedCtor(), and Swap().
double TestDetectorProto::Hit::posy_ private
Definition at line 317 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_posy(), MergePartialFromCodedStream(), posy(), set_posy(), SharedCtor(), and Swap().
double TestDetectorProto::Hit::posz_ private
Definition at line 318 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_posz(), MergePartialFromCodedStream(), posz(), set_posz(), SharedCtor(), and Swap().
The documentation for this class was generated from the following files:
Tutorial3/data/FairTestDetectorPayload.pb.h
Tutorial3/data/FairTestDetectorPayload.pb.cc