FairRoot: FairMCTracksEditor.cxx File Reference
FairMCTracksEditor.cxx File Reference
#include "FairMCTracksEditor.h"
#include "FairEventManager.h"
#include "FairRootManager.h"
#include "FairRunAna.h"
#include "TChain.h"
#include "TFile.h"
#include "TGLabel.h"
#include "TGLayout.h"
#include "TString.h"
#include <stddef.h>
Functions
ClassImp (FairMCTracksEditor) FairMCTracksEditor
Function Documentation
ClassImp (FairMCTracksEditor)
Definition at line 31 of file FairMCTracksEditor.cxx.
References FairRootManager::GetInChain(), FairRunAna::getRunId(), FairRunAna::Instance(), and FairRootManager::Instance().
   : TGedFrame(p, width, height, options | kVerticalFrame, back),
     fObject(NULL),
     fManager(FairEventManager::Instance())
 {
   // Resize(width, height);
   //  fManager= FairEventManager::Instance();
   MakeTitle("FairEventManager  Editor");
   TGVerticalFrame*      fInfoFrame= CreateEditorTabSubFrame("Info");
   TGCompositeFrame* title1 = new TGCompositeFrame(fInfoFrame, 180, 10,
       kVerticalFrame |
       kLHintsExpandX   |
       kFixedWidth      |
       kOwnBackground);
   TString Infile= "Input File : ";
 //  TFile* file =FairRunAna::Instance()->GetInputFile();
   TFile* file =FairRootManager::Instance()->GetInChain()->GetFile();
   Infile+=file->GetName();
   TGLabel* TFName=new TGLabel(title1, Infile.Data());
   title1->AddFrame(TFName);
   UInt_t RunId= FairRunAna::Instance()->getRunId();
   TString run= "Run Id : ";
   run += RunId;
   TGLabel* TRunId=new TGLabel(title1, run.Data());
   title1->AddFrame( TRunId);
   fInfoFrame->AddFrame(title1, new TGLayoutHints(kLHintsTop, 0, 0, 2, 0));
 }