FairRroot: Create_Tutorial4_Geometry.C File Reference
Create_Tutorial4_Geometry.C File Reference
#include "TSystem.h"
#include "TGeoManager.h"
#include "TGeoVolume.h"
#include "TGeoMaterial.h"
#include "TGeoMedium.h"
#include "TGeoPgon.h"
#include "TGeoMatrix.h"
#include "TGeoCompositeShape.h"
#include "TFile.h"
#include "TString.h"
#include "TList.h"
#include "TROOT.h"
#include <iostream>
Functions
void create_materials_from_media_file ()
TGeoVolume * create_detector ()
void position_detector ()
void add_alignable_volumes ()
void Create_Tutorial4_Geometry ()
Variables
const TString geoVersion = "tutorial4"
const TString FileName = geoVersion + ".root"
const TString FileName1 = geoVersion + "_geomanager.root"
const TString KeepingVolumeMedium = "air"
const TString BoxVolumeMedium = "silicon"
const Float_t First_Z_Position = 10
const Float_t Z_Distance = 10
const Float_t Module_Size_X = 80.
const Float_t Module_Size_Y = 80.
const Float_t Module_Size_Z = .04
TGeoManager * gGeoMan = NULL
TGeoVolume * gModules
Function Documentation
void add_alignable_volumes ()
Definition at line 161 of file Create_Tutorial4_Geometry.C.
References gGeoMan.
Referenced by Create_Tutorial4_Geometry().
 {
   TString volPath;
   TString symName;
   TString detStr   = "Tutorial4/det";
   TString volStr   = "/TOP_1/tutorial4_1/tut4_det_";
   for (Int_t detectorPlanes = 0; detectorPlanes < 40; detectorPlanes++) {
     volPath  = volStr;
     volPath += detectorPlanes;
     symName  = detStr;
     symName += Form("%02d",detectorPlanes);
     cout<<"Path: "<<volPath<<", "<<symName<<endl;
 //    gGeoMan->cd(volPath);
     gGeoMan->SetAlignableEntry(symName.Data(),volPath.Data());
   }
     cout<<"Nr of alignable objects: "<<gGeoMan->GetNAlignable()<<endl;
 }
TGeoVolume * create_detector ()
Definition at line 127 of file Create_Tutorial4_Geometry.C.
References BoxVolumeMedium, gGeoMan, Module_Size_X, Module_Size_Y, and Module_Size_Z.
Referenced by Create_Tutorial4_Geometry().
 {
   // needed materials
   TGeoMedium* SiliconVolMed   = gGeoMan->GetMedium(BoxVolumeMedium);
   // Single detector_layer
   TGeoBBox* det_plane = new TGeoBBox("", Module_Size_X/2., Module_Size_Y/2., Module_Size_Z/2.);
   TGeoVolume* det_plane_vol =
     new TGeoVolume("tut4_det", det_plane, SiliconVolMed);
   det_plane_vol->SetLineColor(kBlue); // set line color
   det_plane_vol->SetTransparency(70); // set transparency
   TGeoTranslation* det_plane_trans
     = new TGeoTranslation("", 0., 0., 0.);
   return det_plane_vol;
 }
void create_materials_from_media_file ()
Definition at line 104 of file Create_Tutorial4_Geometry.C.
References FairGeoBuilder::createMedium(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairGeoInterface::getMedia(), FairGeoMedia::getMedium(), FairGeoInterface::readMedia(), and FairGeoInterface::setMediaFile().
Referenced by Create_Tutorial4_Geometry().
 {
   // Use the FairRoot geometry interface to load the media which are already defined
   FairGeoLoader* geoLoad = new FairGeoLoader("TGeo", "FairGeoLoader");
   FairGeoInterface* geoFace = geoLoad->getGeoInterface();
   TString geoPath = gSystem->Getenv("VMCWORKDIR");
   TString geoFile = geoPath + "/geometry/media.geo";
   geoFace->setMediaFile(geoFile);
   geoFace->readMedia();
   // Read the required media and create them in the GeoManager
   FairGeoMedia* geoMedia = geoFace->getMedia();
   FairGeoBuilder* geoBuild = geoLoad->getGeoBuilder();
   FairGeoMedium* air              = geoMedia->getMedium("air");
   FairGeoMedium* silicon          = geoMedia->getMedium("silicon");
   // include check if all media are found
   geoBuild->createMedium(air);
   geoBuild->createMedium(silicon);
 }
void Create_Tutorial4_Geometry ()
Definition at line 54 of file Create_Tutorial4_Geometry.C.
References add_alignable_volumes(), basiclibs(), create_detector(), create_materials_from_media_file(), FileName, FileName1, geoVersion, gGeoMan, gModules, and position_detector().
{
   // Load the necessary FairRoot libraries
   gROOT->LoadMacro("$VMCWORKDIR/gconfig/basiclibs.C");
   basiclibs();
   gSystem->Load("libGeoBase");
   gSystem->Load("libParBase");
   gSystem->Load("libBase");
   // Load needed material definition from media.geo file
   create_materials_from_media_file();
   // Get the GeoManager for later usage
   gGeoMan = (TGeoManager*) gROOT->FindObject("FAIRGeom");
   gGeoMan->SetVisLevel(7);
   // Create the top volume
   TGeoVolume* top = new TGeoVolumeAssembly("TOP");
   gGeoMan->SetTopVolume(top);
   TGeoVolume* tut4 = new TGeoVolumeAssembly(geoVersion);
   top->AddNode(tut4, 1);
   gModules = create_detector();
   position_detector();
   cout<<"Voxelizing."<<endl;
   top->Voxelize("");
   gGeoMan->CloseGeometry();
   add_alignable_volumes();
   gGeoMan->CheckOverlaps(0.001);
   gGeoMan->PrintOverlaps();
   gGeoMan->Test();
   TFile* outfile = new TFile(FileName,"RECREATE");
   top->Write();
   outfile->Close();
   TFile* outfile = new TFile(FileName1,"RECREATE");
   gGeoMan->Write();
   outfile->Close();
   //  top->Draw("ogl");
   //top->Raytrace();
 }
void position_detector ()
Definition at line 146 of file Create_Tutorial4_Geometry.C.
References First_Z_Position, geoVersion, gGeoMan, gModules, and Z_Distance.
Referenced by Create_Tutorial4_Geometry().
 {
   TGeoTranslation* det_trans=NULL;
   Int_t numDets=0;
   for (Int_t detectorPlanes = 0; detectorPlanes < 40; detectorPlanes++) {
     det_trans
       = new TGeoTranslation("", 0., 0., First_Z_Position+(numDets*Z_Distance));
     gGeoMan->GetVolume(geoVersion)->AddNode(gModules, numDets, det_trans);
     numDets++;
   }
 }
Variable Documentation
const TString BoxVolumeMedium = "silicon"
Definition at line 33 of file Create_Tutorial4_Geometry.C.
Referenced by create_detector().
const TString FileName = geoVersion + ".root"
Definition at line 27 of file Create_Tutorial4_Geometry.C.
Referenced by Create_Tutorial4_Geometry().
const TString FileName1 = geoVersion + "_geomanager.root"
Definition at line 28 of file Create_Tutorial4_Geometry.C.
Referenced by Create_Tutorial4_Geometry().
const Float_t First_Z_Position = 10
Definition at line 36 of file Create_Tutorial4_Geometry.C.
Referenced by position_detector().
const TString geoVersion = "tutorial4"
Definition at line 26 of file Create_Tutorial4_Geometry.C.
Referenced by Create_Tutorial4_Geometry(), and position_detector().
TGeoManager* gGeoMan = NULL
Definition at line 45 of file Create_Tutorial4_Geometry.C.
Referenced by add_alignable_volumes(), create_detector(), Create_Tutorial4_Geometry(), and position_detector().
TGeoVolume* gModules
Definition at line 46 of file Create_Tutorial4_Geometry.C.
Referenced by Create_Tutorial4_Geometry(), and position_detector().
const TString KeepingVolumeMedium = "air"
Definition at line 32 of file Create_Tutorial4_Geometry.C.
const Float_t Module_Size_X = 80.
Definition at line 40 of file Create_Tutorial4_Geometry.C.
Referenced by create_detector().
const Float_t Module_Size_Y = 80.
Definition at line 41 of file Create_Tutorial4_Geometry.C.
Referenced by create_detector().
const Float_t Module_Size_Z = .04
Definition at line 42 of file Create_Tutorial4_Geometry.C.
Referenced by create_detector().
const Float_t Z_Distance = 10
Definition at line 37 of file Create_Tutorial4_Geometry.C.
Referenced by position_detector().