set(CTEST_PROJECT_NAME "FairRoot")
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "fairroot.gsi.de")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=FairRoot")
set(CTEST_DROP_SITE_CDASH TRUE)

set(CTEST_TESTING_TIMEOUT 180)
