FairRroot: cxx11-test-constexpr.cpp File Reference
cxx11-test-constexpr.cpp File Reference
Functions
constexpr int square (int x)
constexpr int the_answer ()
int main ()
Function Documentation
int main (void)
Definition at line 11 of file cxx11-test-constexpr.cpp.
References square(), and the_answer().
 {
         int test_arr[square(3)];
         bool ret = (
                 (square(the_answer()) == 1764) &&
                 (sizeof(test_arr)/sizeof(test_arr[0]) == 9)
         );
         return ret ? 0 : 1;
 }
constexpr int square (int x)
Definition at line 1 of file cxx11-test-constexpr.cpp.
Referenced by main().
 {
         return x*x;
 }
constexpr int the_answer ()
Definition at line 6 of file cxx11-test-constexpr.cpp.
Referenced by main().
 {
         return 42;
 }