FairRoot: FairTimeStamp Class Reference
FairTimeStamp Class Reference
#include <FairTimeStamp.h>
Public Member Functions
FairTimeStamp ()
FairTimeStamp (Double_t time)
FairTimeStamp (Double_t time, Double_t timeerror)
virtual ~FairTimeStamp ()
virtual Double_t GetTimeStamp () const
virtual Double_t GetTimeStampError () const
virtual FairLink GetEntryNr () const
virtual void SetTimeStamp (Double_t t)
virtual void SetTimeStampError (Double_t t)
virtual void SetEntryNr (FairLink entry)
virtual Int_t Compare (const TObject *obj) const
virtual std::ostream & Print (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
virtual bool operator< (const FairTimeStamp *rValue) const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
virtual FairMultiLinkedData * GetPointerToLinks () const
virtual void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link)
Sets the Links with a single FairLink.
virtual void SetInsertHistory (Bool_t val)
virtual void SetPointerToLinks (FairMultiLinkedData *links)
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
virtual void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
virtual void AddInterfaceData (FairMultiLinkedData_Interface *data)
virtual void ResetLinks ()
Protected Member Functions
ClassDef (FairTimeStamp, 3)
indicates where the data is stored in the branch
FairMultiLinkedData * CreateFairMultiLinkedData ()
ClassDef (FairMultiLinkedData_Interface, 5)
Protected Attributes
Double_t fTimeStamp
Double_t fTimeStampError
FairLink fEntryNr
Int_t fVerbose
FairMultiLinkedData * fLink
Friends
class boost::serialization::access
std::ostream & operator<< (std::ostream &out, const FairTimeStamp &link)
Detailed Description
Base class for Time stamp information Aug. 2010
Author
M.Al-Turany m.al-.nosp@m.tura.nosp@m.ny@gs.nosp@m.i.de
Definition at line 34 of file FairTimeStamp.h.
Constructor & Destructor Documentation
FairTimeStamp::FairTimeStamp ()
Default constructor
Definition at line 11 of file FairTimeStamp.cxx.
   : FairMultiLinkedData_Interface(),
     fTimeStamp(-1),
     fTimeStampError(-1),
     fEntryNr()
 {
 }
FairTimeStamp::FairTimeStamp (Double_t time)
Constructor with time
Definition at line 19 of file FairTimeStamp.cxx.
   : FairMultiLinkedData_Interface(),
     fTimeStamp(time),
     fTimeStampError(-1),
     fEntryNr()
 {
 }
FairTimeStamp::FairTimeStamp (Double_t time, Double_t timeerror)
Constructor with time and time error
Definition at line 27 of file FairTimeStamp.cxx.
   : FairMultiLinkedData_Interface(),
     fTimeStamp(time),
     fTimeStampError(timeerror),
     fEntryNr()
 {
 }
FairTimeStamp::~FairTimeStamp () virtual
Destructor
Definition at line 36 of file FairTimeStamp.cxx.
 {
 }
Member Function Documentation
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) virtual inherited
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
 {
         SetInsertHistory(kFALSE); //todo add previous history value
         if (data->GetEntryNr().GetType() != -1)
                 AddLink(data->GetEntryNr());
         else
                 std::cout
                                 << "-E- FairMultiLinkedData_Interface::AddInterfaceData EntryNr == "
                                 << data->GetEntryNr() << std::endl;
         if (data->GetPointerToLinks() != 0) {
                 AddLinks(*data->GetPointerToLinks());
         }
         SetInsertHistory(kTRUE);
 }
void FairMultiLinkedData_Interface::AddLink (FairLink link) virtual inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 154 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLink(link);
         }
 }
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 146 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLinks(links, mult);
         }
 }
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
FairTimeStamp::ClassDef (FairTimeStamp , 3) protected
indicates where the data is stored in the branch
virtual Int_t FairTimeStamp::Compare (const TObject * obj) const inline virtual
Definition at line 54 of file FairTimeStamp.h.
References fTimeStamp, fTimeStampError, GetTimeStamp(), and GetTimeStampError().
{
       if (this == obj) { return 0; }
       FairTimeStamp* tsobj = (FairTimeStamp*)obj;
       Double_t ts = tsobj->GetTimeStamp();
       Double_t tserror = tsobj->GetTimeStampError();
       if (fTimeStamp < ts) { return -1; }
       else if (fTimeStamp == ts && fTimeStampError < tserror) { return -1; }
       else if (fTimeStamp == ts && fTimeStampError == tserror) { return 0; }
       else { return 1; }
     }
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 62 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
 {
         if (FairRootManager::Instance()->GetUseFairLinks()){
                 if (fLink == 0){
                         fLink = new FairMultiLinkedData();
                 }
                 return fLink;
         }
         return 0;
 }
virtual bool FairTimeStamp::equal (FairTimeStamp * data) inline virtual
Reimplemented in FairTestDetectorDigi, FairTestDetectorDigi, and MyDigi.
Definition at line 70 of file FairTimeStamp.h.
References fTimeStamp, fTimeStampError, GetTimeStamp(), and GetTimeStampError().
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
{
       return (fTimeStamp == data->GetTimeStamp() && fTimeStampError == data->GetTimeStampError());
     }
virtual FairLink FairTimeStamp::GetEntryNr () const inline virtual
Reimplemented from FairMultiLinkedData_Interface.
Definition at line 49 of file FairTimeStamp.h.
References fEntryNr.
 {return fEntryNr;}
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const virtual inherited
returns the FairLink at the given position
Definition at line 92 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLink(pos);
         } else {
                 FairLink emptyLink;
                 return emptyLink;
         }
 }
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const virtual inherited
returns stored links as FairLinks
Definition at line 73 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinks();
         } else {
                 std::set<FairLink> emptySet;
                 return emptySet;
         }
 }
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const virtual inherited
returns all FairLinks with the corresponding type
Definition at line 112 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinksWithType(type);
         } else {
                 FairMultiLinkedData emptyLinks;
                 return emptyLinks;
         }
 }
Int_t FairMultiLinkedData_Interface::GetNLinks () const virtual inherited
returns the number of stored links
Definition at line 83 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetNLinks();
         } else {
                 return 0;
         }
 }
virtual FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline virtual inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::Print(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
 {       return fLink;}
virtual Double_t FairTimeStamp::GetTimeStamp () const inline virtual
Accessors
Definition at line 47 of file FairTimeStamp.h.
References fTimeStamp.
Referenced by StopTime::Call(), TimeGap::Call(), Compare(), equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), FairRingSorterTask::Exec(), FairTSBufferFunctional::GetData(), FairTimeStampPointDraw::GetValue(), operator<(), Print(), FairWriteoutBuffer::PrintData(), FairWriteoutBuffer::PrintStartTimeMap(), and FairTestDetectorDigi::ToString().
 { return fTimeStamp; };
virtual Double_t FairTimeStamp::GetTimeStampError () const inline virtual
Definition at line 48 of file FairTimeStamp.h.
References fTimeStampError.
Referenced by Compare(), equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), and Print().
 { return fTimeStampError;};
virtual Bool_t FairTimeStamp::IsSortable () const inline virtual
Definition at line 67 of file FairTimeStamp.h.
 { return kTRUE;};
virtual bool FairTimeStamp::operator< (const FairTimeStamp * rValue) const inline virtual
Definition at line 79 of file FairTimeStamp.h.
References GetTimeStamp().
{
         if (GetTimeStamp() < rValue->GetTimeStamp())
                 return true;
         else
                 return false;
     }
std::ostream & FairTimeStamp::Print (std::ostream & out = std::cout) const virtual
Definition at line 42 of file FairTimeStamp.cxx.
References fEntryNr, GetTimeStamp(), GetTimeStampError(), and FairMultiLinkedData_Interface::Print().
Referenced by FairRingSorter::AddElement(), FairRingSorterTask::Exec(), and FairWriteoutBuffer::FillDataToDeadTimeMap().
 {
   out << "EntryNr of Data: " << fEntryNr << " TimeStamp: " << GetTimeStamp() << " +/- " << GetTimeStampError() << std::endl;
   FairMultiLinkedData_Interface::Print(out);
   return out;
 }
void FairMultiLinkedData_Interface::ResetLinks () virtual inherited
Definition at line 185 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
 {
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->ResetLinks();
         }
 }
template<class Archive > void FairTimeStamp::serialize (Archive & ar, const unsigned int version) inline
Definition at line 88 of file FairTimeStamp.h.
References fTimeStamp, and fTimeStampError.
     {
         //ar & boost::serialization::base_object<FairMultiLinkedData>(*this);
         ar & fTimeStamp;
         ar & fTimeStampError;
     }
virtual void FairTimeStamp::SetEntryNr (FairLink entry) inline virtual
Reimplemented from FairMultiLinkedData_Interface.
Definition at line 53 of file FairTimeStamp.h.
References fEntryNr.
Referenced by FairRingSorterTask::Exec().
 {fEntryNr = entry;}
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) virtual inherited
Definition at line 178 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         if (GetPointerToLinks() != 0) {
                 GetPointerToLinks()->SetInsertHistory(val);
         }
 }
void FairMultiLinkedData_Interface::SetLink (FairLink link) virtual inherited
Sets the Links with a single FairLink.
Definition at line 130 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetectorTimeRecoTask::Exec(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLink(link);
         }
 }
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) virtual inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 122 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLinks(links);
         }
 }
virtual void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline virtual inherited
Definition at line 53 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
 {fLink = links;}
virtual void FairTimeStamp::SetTimeStamp (Double_t t) inline virtual
Modifiers
Definition at line 51 of file FairTimeStamp.h.
References fTimeStamp.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
 { fTimeStamp = t; }
virtual void FairTimeStamp::SetTimeStampError (Double_t t) inline virtual
Definition at line 52 of file FairTimeStamp.h.
References fTimeStampError.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
 {fTimeStampError = t;}
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 99 of file FairTimeStamp.h.
std::ostream& operator<< (std::ostream & out, const FairTimeStamp & link) friend
Definition at line 74 of file FairTimeStamp.h.
{
       link.Print(out);
       return out;
     }
Member Data Documentation
FairLink FairTimeStamp::fEntryNr protected
Error on time stamp
Definition at line 104 of file FairTimeStamp.h.
Referenced by GetEntryNr(), Print(), and SetEntryNr().
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
Double_t FairTimeStamp::fTimeStamp protected
Definition at line 102 of file FairTimeStamp.h.
Referenced by Compare(), equal(), GetTimeStamp(), serialize(), and SetTimeStamp().
Double_t FairTimeStamp::fTimeStampError protected
Time of digit or Hit [ns]
Definition at line 103 of file FairTimeStamp.h.
Referenced by Compare(), equal(), GetTimeStampError(), serialize(), and SetTimeStampError().
Int_t FairMultiLinkedData_Interface::fVerbose protected inherited
Definition at line 78 of file FairMultiLinkedData_Interface.h.
The documentation for this class was generated from the following files:
FairTimeStamp.h
FairTimeStamp.cxx