FairRoot: FairGeoMatrix Class Reference
FairGeoMatrix Class Reference
#include <FairGeoMatrix.h>
Public Member Functions
FairGeoMatrix (void)
~FairGeoMatrix (void)
Double_t & operator() (Int_t i, Int_t j)
Double_t det (void)
FairGeoVector operator* (FairGeoVector &v)
FairGeoMatrix & operator/= (Double_t d)
Protected Attributes
Double_t fM [9]
Detailed Description
Author
Ilse koenig
Definition at line 20 of file FairGeoMatrix.h.
Constructor & Destructor Documentation
FairGeoMatrix::FairGeoMatrix (void)
Definition at line 25 of file FairGeoMatrix.cxx.
References fM.
   :TObject()
 {
   // Initializes the matrix to 0
   for (int i=0; i<9; i++) { fM[i]=0.0; }
 }
FairGeoMatrix::~FairGeoMatrix (void)
Definition at line 32 of file FairGeoMatrix.cxx.
 {
 }
Member Function Documentation
Double_t FairGeoMatrix::det (void)
Definition at line 36 of file FairGeoMatrix.cxx.
References fM.
 {
   // Computes de determinat of the 3D matrix
   return (fM[0] * fM[4] * fM[8] + fM[1] * fM[5] * fM[6] + fM[3] *fM[7] * fM[2] -
           fM[2] * fM[4] * fM[6] - fM[1] * fM[3] * fM[8] - fM[5] *fM[7] * fM[0]);
 }
Double_t& FairGeoMatrix::operator() (Int_t i, Int_t j) inline
Definition at line 27 of file FairGeoMatrix.h.
 { return fM[i*3+j]; }
FairGeoVector FairGeoMatrix::operator* (FairGeoVector & v)
Definition at line 43 of file FairGeoMatrix.cxx.
References fM, FairGeoVector::getX(), FairGeoVector::getY(), FairGeoVector::getZ(), FairGeoVector::setX(), FairGeoVector::setY(), and FairGeoVector::setZ().
 {
   // Matrix multiplication
   FairGeoVector vo;
   vo.setX(fM[0] * v.getX() + fM[1] * v.getY() + fM[2] * v.getZ());
   vo.setY(fM[3] * v.getX() + fM[4] * v.getY() + fM[5] * v.getZ());
   vo.setZ(fM[6] * v.getX() + fM[7] * v.getY() + fM[8] * v.getZ());
   return vo;
 }
FairGeoMatrix & FairGeoMatrix::operator/= (Double_t d)
Definition at line 53 of file FairGeoMatrix.cxx.
References fM.
 {
   // Matrix division by a constant. Divides each element on the
   //matrix by the constant "d"
   for (int i=0; i<9; i++) { fM[i]/=d; }
   return *this;
 }
Member Data Documentation
Double_t FairGeoMatrix::fM[9] protected
Definition at line 23 of file FairGeoMatrix.h.
Referenced by det(), FairGeoMatrix(), operator*(), and operator/=().
The documentation for this class was generated from the following files:
FairGeoMatrix.h
FairGeoMatrix.cxx