FairRoot: FairStack Class Reference
FairStack Class Reference
#include <FairStack.h>
Public Member Functions
FairStack (Int_t size=100)
virtual ~FairStack ()
virtual void PushTrack (Int_t toBeDone, Int_t parentID, Int_t pdgCode, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t time, Double_t polx, Double_t poly, Double_t polz, TMCProcess proc, Int_t &ntr, Double_t weight, Int_t is)
virtual void PushTrack (Int_t toBeDone, Int_t parentID, Int_t pdgCode, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t time, Double_t polx, Double_t poly, Double_t polz, TMCProcess proc, Int_t &ntr, Double_t weight, Int_t is, Int_t secondParentId)
virtual TParticle * PopNextTrack (Int_t &iTrack)
virtual TParticle * PopPrimaryForTracking (Int_t iPrim)
virtual void SetCurrentTrack (Int_t iTrack)
virtual Int_t GetNtrack () const
virtual Int_t GetNprimary () const
virtual TParticle * GetCurrentTrack () const
virtual Int_t GetCurrentTrackNumber () const
virtual Int_t GetCurrentParentTrackNumber () const
virtual void AddParticle (TParticle *part)
virtual void FillTrackArray ()
virtual void UpdateTrackIndex (TRefArray *detArray=0)
virtual void Reset ()
virtual void Register ()
virtual void Print (Int_t iVerbose=0) const
void StoreSecondaries (Bool_t choice=kTRUE)
void SetMinPoints (Int_t min)
void SetEnergyCut (Double_t eMin)
void StoreMothers (Bool_t choice=kTRUE)
void AddPoint (DetectorId iDet)
void AddPoint (DetectorId iDet, Int_t iTrack)
TParticle * GetParticle (Int_t trackId) const
TClonesArray * GetListOfParticles ()
virtual FairGenericStack * CloneStack () const
void SetDetArrayList (TRefArray *detArray)
virtual void Print (Option_t *option="") const
Protected Attributes
FairLogger * fLogger
TRefArray * fDetList
TIterator * fDetIter
Int_t fVerbose
Private Member Functions
void SelectTracks ()
FairStack (const FairStack &)
FairStack & operator= (const FairStack &)
Private Attributes
std::stack< TParticle * > fStack
TClonesArray * fParticles
TClonesArray * fTracks
std::map< Int_t, Bool_t > fStoreMap
std::map< Int_t, Bool_t >::iterator fStoreIter
std::map< Int_t, Int_t > fIndexMap
std::map< Int_t, Int_t >::iterator fIndexIter
std::map< std::pair< Int_t, Int_t >, Int_t > fPointsMap
Int_t fCurrentTrack
Int_t fNPrimaries
Index of current track.
Int_t fNParticles
Number of primary particles.
Int_t fNTracks
Number of entries in fParticles.
Int_t fIndex
Number of entries in fTracks.
Bool_t fStoreSecondaries
Used for merging.
Int_t fMinPoints
Double32_t fEnergyCut
Bool_t fStoreMothers
Detailed Description
Definition at line 55 of file FairStack.h.
Constructor & Destructor Documentation
FairStack::FairStack (Int_t size = 100)
Default constructor param size Estimated track number
Definition at line 35 of file FairStack.cxx.
Referenced by CloneStack().
   : FairGenericStack(),
     fStack(),
     fParticles(new TClonesArray("TParticle", size)),
     fTracks(new TClonesArray("FairMCTrack", size)),
     fStoreMap(),
     fStoreIter(),
     fIndexMap(),
     fIndexIter(),
     fPointsMap(),
     fCurrentTrack(-1),
     fNPrimaries(0),
     fNParticles(0),
     fNTracks(0),
     fIndex(0),
     fStoreSecondaries(kTRUE),
     fMinPoints(1),
     fEnergyCut(0.),
     fStoreMothers(kTRUE)
 {
 }
FairStack::~FairStack () virtual
Destructor
Definition at line 62 of file FairStack.cxx.
References fParticles, and fTracks.
 {
   if (fParticles) {
     fParticles->Delete();
     delete fParticles;
   }
   if (fTracks) {
     fTracks->Delete();
     delete fTracks;
   }
 }
FairStack::FairStack (const FairStack &) private
Member Function Documentation
void FairStack::AddParticle (TParticle * part) virtual
Add a TParticle to the fParticles array
Definition at line 208 of file FairStack.cxx.
References fIndex, and fParticles.
 {
   TClonesArray& array = *fParticles;
   TParticle* newPart = new(array[fIndex]) TParticle(*oldPart);
   newPart->SetWeight(oldPart->GetWeight());
   newPart->SetUniqueID(oldPart->GetUniqueID());
   fIndex++;
 }
void FairStack::AddPoint (DetectorId iDet)
Increment number of points for the current track in a given detector
Parameters
iDet Detector unique identifier
Definition at line 381 of file FairStack.cxx.
References fCurrentTrack, and fPointsMap.
Referenced by FairTestDetector::ProcessHits(), FairTutorialDet2::ProcessHits(), NewDetector::ProcessHits(), FairRutherford::ProcessHits(), FairTutorialDet1::ProcessHits(), and FairTutorialDet4::ProcessHits().
 {
   Int_t iDet = detId;
 // cout << "Add point for Detektor" << iDet << endl;
   pair<Int_t, Int_t> a(fCurrentTrack, iDet);
   if ( fPointsMap.find(a) == fPointsMap.end() ) { fPointsMap[a] = 1; }
   else { fPointsMap[a]++; }
 }
void FairStack::AddPoint (DetectorId iDet, Int_t iTrack)
Increment number of points for an arbitrary track in a given detector
Parameters
iDet Detector unique identifier
iTrack Track number
Definition at line 394 of file FairStack.cxx.
References fPointsMap.
 {
   if ( iTrack < 0 ) { return; }
   Int_t iDet = detId;
   pair<Int_t, Int_t> a(iTrack, iDet);
   if ( fPointsMap.find(a) == fPointsMap.end() ) { fPointsMap[a] = 1; }
   else { fPointsMap[a]++; }
 }
virtual FairGenericStack* FairStack::CloneStack () const inline virtual
Clone this object (used in MT mode only)
Reimplemented from FairGenericStack.
Definition at line 206 of file FairStack.h.
References FairStack().
 { return new FairStack(); }
void FairStack::FillTrackArray () virtual
Fill the MCTrack output array, applying filter criteria
Reimplemented from FairGenericStack.
Definition at line 221 of file FairStack.cxx.
References DEBUG, FairLogger::endl(), FATAL, fIndexMap, fNParticles, fNTracks, fPointsMap, fStoreIter, fStoreMap, GetParticle(), kREF, kSTOPHERE, LOG, SelectTracks(), and FairMCTrack::SetNPoints().
 {
   LOG(DEBUG) << "Filling MCTrack array..." << FairLogger::endl;
   // --> Reset index map and number of output tracks
   fIndexMap.clear();
   fNTracks = 0;
   // --> Check tracks for selection criteria
   SelectTracks();
   // --> Loop over fParticles array and copy selected tracks
   for (Int_t iPart=0; iPart<fNParticles; iPart++) {
     Bool_t store = kFALSE;
     fStoreIter = fStoreMap.find(iPart);
     if (fStoreIter == fStoreMap.end() ) {
       LOG(FATAL) << "Particle " << iPart << " not found in storage map! "
                 <<FairLogger::endl;
     } else {
       store = (*fStoreIter).second;
     }
     if (store) {
       FairMCTrack* track =
         new( (*fTracks)[fNTracks]) FairMCTrack(GetParticle(iPart));
       fIndexMap[iPart] = fNTracks;
       // --> Set the number of points in the detectors for this track
       for (Int_t iDet=kREF; iDet<kSTOPHERE; iDet++) {
         pair<Int_t, Int_t> a(iPart, iDet);
         track->SetNPoints(iDet, fPointsMap[a]);
       }
       fNTracks++;
     } else {
       fIndexMap[iPart] = -2;
     }
   }
   // --> Map index for primary mothers
   fIndexMap[-1] = -1;
   // --> Screen output
   //Print(1);
 }
Int_t FairStack::GetCurrentParentTrackNumber () const virtual
Get the track number of the parent of the current track Declared in TVirtualMCStack
Reimplemented from FairGenericStack.
Definition at line 408 of file FairStack.cxx.
References GetCurrentTrack().
 {
   TParticle* currentPart = GetCurrentTrack();
   if ( currentPart ) { return currentPart->GetFirstMother(); }
   else { return -1; }
 }
TParticle * FairStack::GetCurrentTrack () const virtual
Get the current track's particle Declared in TVirtualMCStack
Reimplemented from FairGenericStack.
Definition at line 194 of file FairStack.cxx.
References FairLogger::endl(), fCurrentTrack, GetParticle(), LOG, and WARNING.
Referenced by GetCurrentParentTrackNumber().
 {
   TParticle* currentPart = GetParticle(fCurrentTrack);
   if ( ! currentPart) {
     LOG(WARNING) << "Current track not found in stack!"
                  << FairLogger::endl;
   }
   return currentPart;
 }
virtual Int_t FairStack::GetCurrentTrackNumber () const inline virtual
Get the number of the current track Declared in TVirtualMCStack
Reimplemented from FairGenericStack.
Definition at line 146 of file FairStack.h.
References fCurrentTrack.
 { return fCurrentTrack; }
TClonesArray* FairStack::GetListOfParticles () inline virtual
Reimplemented from FairGenericStack.
Definition at line 203 of file FairStack.h.
References fParticles.
 { return fParticles; }
virtual Int_t FairStack::GetNprimary () const inline virtual
Get number of primary tracks Declared in TVirtualMCStack
Reimplemented from FairGenericStack.
Definition at line 134 of file FairStack.h.
References fNPrimaries.
 { return fNPrimaries; }
virtual Int_t FairStack::GetNtrack () const inline virtual
Get total number of tracks Declared in TVirtualMCStack
Reimplemented from FairGenericStack.
Definition at line 128 of file FairStack.h.
References fNParticles.
 { return fNParticles; }
TParticle * FairStack::GetParticle (Int_t trackId) const virtual
Accessors
Reimplemented from FairGenericStack.
Definition at line 419 of file FairStack.cxx.
References FairLogger::endl(), FATAL, fNParticles, fParticles, and LOG.
Referenced by FillTrackArray(), GetCurrentTrack(), and SelectTracks().
 {
   if (trackID < 0 || trackID >= fNParticles) {
     LOG(FATAL) << "Particle index " << trackID << " out of range."
                << FairLogger::endl;
   }
   return (TParticle*)fParticles->At(trackID);
 }
FairStack& FairStack::operator= (const FairStack &) private
TParticle * FairStack::PopNextTrack (Int_t & iTrack) virtual
Get next particle for tracking from the stack. Declared in TVirtualMCStack
Parameters
iTrack index of popped track (return)
Returns
Pointer to the TParticle of the track
Reimplemented from FairGenericStack.
Definition at line 137 of file FairStack.cxx.
References fCurrentTrack, and fStack.
 {
   // If end of stack: Return empty pointer
   if (fStack.empty()) {
     iTrack = -1;
     return NULL;
   }
   // If not, get next particle from stack
   TParticle* thisParticle = fStack.top();
   fStack.pop();
   if ( !thisParticle) {
     iTrack = 0;
     return NULL;
   }
   fCurrentTrack = thisParticle->GetStatusCode();
   iTrack = fCurrentTrack;
   return thisParticle;
 }
TParticle * FairStack::PopPrimaryForTracking (Int_t iPrim) virtual
Get primary particle by index for tracking from stack Declared in TVirtualMCStack
Parameters
iPrim index of primary particle
Returns
Pointer to the TParticle of the track
Reimplemented from FairGenericStack.
Definition at line 166 of file FairStack.cxx.
References FairLogger::endl(), FATAL, fNPrimaries, fParticles, and LOG.
 {
   // Get the iPrimth particle from the fStack TClonesArray. This
   // should be a primary (if the index is correct).
   // Test for index
   if (iPrim < 0 || iPrim >= fNPrimaries) {
     LOG(FATAL) << "Primary index out of range!" << iPrim
                << FairLogger::endl;
   }
   // Return the iPrim-th TParticle from the fParticle array. This should be
   // a primary.
   TParticle* part = (TParticle*)fParticles->At(iPrim);
   if ( ! (part->GetMother(0) < 0) ) {
     LOG(FATAL) << "Not a primary track!" << iPrim
                << FairLogger::endl;
   }
   return part;
 }
void FairGenericStack::Print (Option_t * option = "") const virtual inherited
Output to screen
Parameters
iVerbose 0=events summary, 1=track info
Definition at line 136 of file FairGenericStack.cxx.
 {
 }
void FairStack::Print (Int_t iVerbose = 0) const virtual
Output to screen
Parameters
iVerbose 0=events summary, 1=track info
Definition at line 362 of file FairStack.cxx.
References DEBUG1, FairLogger::endl(), fNParticles, fNPrimaries, fNTracks, fTracks, gLogger, INFO, FairLogger::IsLogNeeded(), and LOG.
 {
   LOG(INFO) << "FairStack: Number of primaries        = "
             << fNPrimaries << FairLogger::endl;
   LOG(INFO) << "              Total number of particles  = "
             << fNParticles << FairLogger::endl;
   LOG(INFO) << "              Number of tracks in output = "
             << fNTracks << FairLogger::endl;
   if (gLogger->IsLogNeeded(DEBUG1)) {
     for (Int_t iTrack=0; iTrack<fNTracks; iTrack++) {
       ((FairMCTrack*) fTracks->At(iTrack))->Print(iTrack);
     }
   }
 }
void FairStack::PushTrack (Int_t toBeDone, Int_t parentID, Int_t pdgCode, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t time, Double_t polx, Double_t poly, Double_t polz, TMCProcess proc, Int_t & ntr, Double_t weight, Int_t is) virtual
Add a TParticle to the stack. Declared in TVirtualMCStack
Parameters
toBeDone Flag for tracking
parentID Index of mother particle
pdgCode Particle type (PDG encoding)
px,py,pz Momentum components at start vertex [GeV]
e Total energy at start vertex [GeV]
vx,vy,vz Coordinates of start vertex [cm]
time Start time of track [s]
polx,poly,polz Polarisation vector
proc Production mechanism (VMC encoding)
ntr Track number (filled by the stack)
weight Particle weight
is Generation status code (whatever that means)
Reimplemented from FairGenericStack.
Definition at line 75 of file FairStack.cxx.
 {
   PushTrack( toBeDone, parentId, pdgCode,
              px,  py,  pz,
              e,  vx,  vy,  vz,
              time,  polx,  poly,
              polz, proc, ntr,
              weight, is, -1);
 }
void FairStack::PushTrack (Int_t toBeDone, Int_t parentID, Int_t pdgCode, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t time, Double_t polx, Double_t poly, Double_t polz, TMCProcess proc, Int_t & ntr, Double_t weight, Int_t is, Int_t secondparentID) virtual
Virtual method PushTrack. Add a TParticle to the stack.
Parameters
toBeDone Flag for tracking
parentID Index of mother particle
pdgCode Particle type (PDG encoding)
px,py,pz Momentum components at start vertex [GeV]
e Total energy at start vertex [GeV]
vx,vy,vz Coordinates of start vertex [cm]
time Start time of track [s]
polx,poly,polz Polarisation vector
proc Production mechanism (VMC encoding)
ntr Track number (filled by the stack)
weight Particle weight
is Generation status code (whatever that means)
secondparentID used fot the index of mother of primery in the list
Reimplemented from FairGenericStack.
Definition at line 97 of file FairStack.cxx.
References fNParticles, fNPrimaries, fParticles, and fStack.
 {
   // --> Get TParticle array
   TClonesArray& partArray = *fParticles;
   // --> Create new TParticle and add it to the TParticle array
   Int_t trackId = fNParticles;
   Int_t nPoints = 0;
   Int_t daughter1Id = -1;
   Int_t daughter2Id = -1;
   TParticle* particle =
     new(partArray[fNParticles++]) TParticle(pdgCode, trackId, parentId,
         nPoints, daughter1Id,
         daughter2Id, px, py, pz, e,
         vx, vy, vz, time);
   particle->SetPolarisation(polx, poly, polz);
   particle->SetWeight(weight);
   particle->SetUniqueID(proc);
   // --> Increment counter
   if (parentId < 0) { fNPrimaries++; }
   // --> Set argument variable
   ntr = trackId;
   // --> Push particle on the stack if toBeDone is set
   if (toBeDone == 1) { fStack.push(particle); }
 }
void FairStack::Register () virtual
Register the MCTrack array to the Root Manager
Reimplemented from FairGenericStack.
Definition at line 353 of file FairStack.cxx.
References fTracks, FairRootManager::Instance(), and FairRootManager::Register().
 {
   FairRootManager::Instance()->Register("MCTrack", "Stack", fTracks,kTRUE);
 }
void FairStack::Reset () virtual
Resets arrays and stack and deletes particles and tracks
Reimplemented from FairGenericStack.
Definition at line 338 of file FairStack.cxx.
References fCurrentTrack, fIndex, fNParticles, fNPrimaries, fNTracks, fParticles, fPointsMap, fStack, and fTracks.
 {
   fIndex = 0;
   fCurrentTrack = -1;
   fNPrimaries = fNParticles = fNTracks = 0;
   while (! fStack.empty() ) { fStack.pop(); }
   fParticles->Clear();
   fTracks->Clear();
   fPointsMap.clear();
 }
void FairStack::SelectTracks () private
Mark tracks for output using selection criteria
Definition at line 432 of file FairStack.cxx.
References fEnergyCut, fMinPoints, fNParticles, fPointsMap, fStoreMap, fStoreMothers, fStoreSecondaries, GetParticle(), kREF, and kSTOPHERE.
Referenced by FillTrackArray().
 {
   // --> Clear storage map
   fStoreMap.clear();
   // --> Check particles in the fParticle array
   for (Int_t i=0; i<fNParticles; i++) {
     TParticle* thisPart = GetParticle(i);
     Bool_t store = kTRUE;
     // --> Get track parameters
     Int_t iMother   = thisPart->GetMother(0);
     TLorentzVector p;
     thisPart->Momentum(p);
     Double_t energy = p.E();
     Double_t mass   = p.M();
 //    Double_t mass   = thisPart->GetMass();
     Double_t eKin = energy - mass;
     // --> Calculate number of points
     Int_t nPoints = 0;
     for (Int_t iDet=kREF; iDet<kSTOPHERE; iDet++) {
       pair<Int_t, Int_t> a(i, iDet);
       if ( fPointsMap.find(a) != fPointsMap.end() ) {
         nPoints += fPointsMap[a];
       }
     }
     // --> Check for cuts (store primaries in any case)
     if (iMother < 0) { store = kTRUE; }
     else {
       if (!fStoreSecondaries) { store = kFALSE; }
       if (nPoints < fMinPoints) { store = kFALSE; }
       if (eKin < fEnergyCut) { store = kFALSE; }
     }
     // --> Set storage flag
     fStoreMap[i] = store;
   }
   // --> If flag is set, flag recursively mothers of selected tracks
   if (fStoreMothers) {
     for (Int_t i=0; i<fNParticles; i++) {
       if (fStoreMap[i]) {
         Int_t iMother = GetParticle(i)->GetMother(0);
         while(iMother >= 0) {
           fStoreMap[iMother] = kTRUE;
           iMother = GetParticle(iMother)->GetMother(0);
         }
       }
     }
   }
 }
virtual void FairStack::SetCurrentTrack (Int_t iTrack) inline virtual
Set the current track number Declared in TVirtualMCStack
Parameters
iTrack track number
Reimplemented from FairGenericStack.
Definition at line 122 of file FairStack.h.
References fCurrentTrack.
 { fCurrentTrack     = iTrack; }
void FairGenericStack::SetDetArrayList (TRefArray * detArray) inherited
Set the list of detectors to be used for filltering the stack
Definition at line 108 of file FairGenericStack.cxx.
References FairGenericStack::fDetIter, and FairGenericStack::fDetList.
Referenced by FairMCApplication::RunMC().
 {
   fDetList=detArray;
   if(fDetList!=0) { fDetIter=fDetList->MakeIterator(); }
 }
void FairStack::SetEnergyCut (Double_t eMin) inline
Definition at line 184 of file FairStack.h.
References fEnergyCut.
 { fEnergyCut        = eMin;   }
void FairStack::SetMinPoints (Int_t min) inline
Definition at line 183 of file FairStack.h.
References fMinPoints.
 { fMinPoints        = min;    }
void FairStack::StoreMothers (Bool_t choice = kTRUE) inline
Definition at line 185 of file FairStack.h.
References fStoreMothers.
 { fStoreMothers     = choice; }
void FairStack::StoreSecondaries (Bool_t choice = kTRUE) inline
Modifiers
Definition at line 182 of file FairStack.h.
References fStoreSecondaries.
 { fStoreSecondaries = choice; }
void FairStack::UpdateTrackIndex (TRefArray * detArray = 0) virtual
Update the track index in the MCTracks and MCPoints
Reimplemented from FairGenericStack.
Definition at line 274 of file FairStack.cxx.
References DEBUG, FairLogger::endl(), FATAL, FairGenericStack::fDetIter, FairGenericStack::fDetList, fIndexIter, fIndexMap, fNTracks, fTracks, FairDetector::GetCollection(), FairMCTrack::GetMotherId(), FairMCPoint::GetTrackID(), LOG, FairMultiLinkedData_Interface::SetLink(), FairMCTrack::SetMotherId(), and FairMCPoint::SetTrackID().
 {
   LOG(DEBUG) << "Updating track indizes..." << FairLogger::endl;
   Int_t nColl = 0;
   // First update mother ID in MCTracks
   for (Int_t i=0; i<fNTracks; i++) {
     FairMCTrack* track = (FairMCTrack*)fTracks->At(i);
     Int_t iMotherOld = track->GetMotherId();
     fIndexIter = fIndexMap.find(iMotherOld);
     if (fIndexIter == fIndexMap.end()) {
       LOG(FATAL) << "Particle index " << iMotherOld << " not found in index map!"
                 <<FairLogger::endl;
     } else {
       track->SetMotherId( (*fIndexIter).second );
     }
   }
   if(fDetList==0) {
     // Now iterate through all active detectors
     fDetIter = detList->MakeIterator();
     fDetIter->Reset();
   } else {
     fDetIter->Reset();
   }
   FairDetector* det = NULL;
   while( (det = (FairDetector*)fDetIter->Next() ) ) {
     // --> Get hit collections from detector
     Int_t iColl = 0;
     TClonesArray* hitArray;
     while ( (hitArray = det->GetCollection(iColl++)) ) {
       nColl++;
       Int_t nPoints = hitArray->GetEntriesFast();
       // --> Update track index for all MCPoints in the collection
       for (Int_t iPoint=0; iPoint<nPoints; iPoint++) {
         FairMCPoint* point = (FairMCPoint*)hitArray->At(iPoint);
         Int_t iTrack = point->GetTrackID();
         fIndexIter = fIndexMap.find(iTrack);
         if (fIndexIter == fIndexMap.end()) {
           LOG(FATAL) << "Particle index " << iTrack << " not found in index map!"
                      << FairLogger::endl;
         } else {
           point->SetTrackID((*fIndexIter).second);
           point->SetLink(FairLink("MCTrack", (*fIndexIter).second));
         }
       }
     }   // Collections of this detector
   }     // List of active detectors
   LOG(DEBUG) << "...stack and  " << nColl << " collections updated."
              << FairLogger::endl;
 }
Member Data Documentation
Int_t FairStack::fCurrentTrack private
Some indizes and counters
Definition at line 238 of file FairStack.h.
Referenced by AddPoint(), GetCurrentTrack(), GetCurrentTrackNumber(), PopNextTrack(), Reset(), and SetCurrentTrack().
TIterator* FairGenericStack::fDetIter protected inherited
Iterator for the detector list
Definition at line 174 of file FairGenericStack.h.
Referenced by FairGenericStack::operator=(), FairGenericStack::SetDetArrayList(), MyProjStack::UpdateTrackIndex(), and UpdateTrackIndex().
TRefArray* FairGenericStack::fDetList protected inherited
List of detectors registering hits in the simulation
Definition at line 171 of file FairGenericStack.h.
Referenced by FairGenericStack::operator=(), FairGenericStack::SetDetArrayList(), MyProjStack::UpdateTrackIndex(), and UpdateTrackIndex().
Double32_t FairStack::fEnergyCut private
Definition at line 248 of file FairStack.h.
Referenced by SelectTracks(), and SetEnergyCut().
Int_t FairStack::fIndex private
Number of entries in fTracks.
Definition at line 242 of file FairStack.h.
Referenced by AddParticle(), and Reset().
std::map<Int_t, Int_t>::iterator FairStack::fIndexIter private
Definition at line 230 of file FairStack.h.
Referenced by UpdateTrackIndex().
std::map<Int_t, Int_t> FairStack::fIndexMap private
STL map from particle index to track index
Definition at line 229 of file FairStack.h.
Referenced by FillTrackArray(), and UpdateTrackIndex().
FairLogger* FairGenericStack::fLogger protected inherited
Fair Logger
Definition at line 168 of file FairGenericStack.h.
Referenced by FairGenericStack::operator=().
Int_t FairStack::fMinPoints private
Definition at line 247 of file FairStack.h.
Referenced by SelectTracks(), and SetMinPoints().
Int_t FairStack::fNParticles private
Number of primary particles.
Definition at line 240 of file FairStack.h.
Referenced by FillTrackArray(), GetNtrack(), GetParticle(), Print(), PushTrack(), Reset(), and SelectTracks().
Int_t FairStack::fNPrimaries private
Index of current track.
Definition at line 239 of file FairStack.h.
Referenced by GetNprimary(), PopPrimaryForTracking(), Print(), PushTrack(), and Reset().
Int_t FairStack::fNTracks private
Number of entries in fParticles.
Definition at line 241 of file FairStack.h.
Referenced by FillTrackArray(), Print(), Reset(), and UpdateTrackIndex().
TClonesArray* FairStack::fParticles private
Array of TParticles (contains all TParticles put into or created by the transport
Definition at line 216 of file FairStack.h.
Referenced by AddParticle(), GetListOfParticles(), GetParticle(), PopPrimaryForTracking(), PushTrack(), Reset(), and ~FairStack().
std::map<std::pair<Int_t, Int_t>, Int_t> FairStack::fPointsMap private
STL map from track index and detector ID to number of MCPoints
Definition at line 234 of file FairStack.h.
Referenced by AddPoint(), FillTrackArray(), Reset(), and SelectTracks().
std::stack<TParticle*> FairStack::fStack private
STL stack (FILO) used to handle the TParticles for tracking
Definition at line 210 of file FairStack.h.
Referenced by PopNextTrack(), PushTrack(), and Reset().
std::map<Int_t, Bool_t>::iterator FairStack::fStoreIter private
Definition at line 225 of file FairStack.h.
Referenced by FillTrackArray().
std::map<Int_t, Bool_t> FairStack::fStoreMap private
STL map from particle index to storage flag
Definition at line 224 of file FairStack.h.
Referenced by FillTrackArray(), and SelectTracks().
Bool_t FairStack::fStoreMothers private
Definition at line 249 of file FairStack.h.
Referenced by SelectTracks(), and StoreMothers().
Bool_t FairStack::fStoreSecondaries private
Used for merging.
Variables defining the criteria for output selection
Definition at line 246 of file FairStack.h.
Referenced by SelectTracks(), and StoreSecondaries().
TClonesArray* FairStack::fTracks private
Array of FairMCTracks containg the tracks written to the output
Definition at line 220 of file FairStack.h.
Referenced by Print(), Register(), Reset(), UpdateTrackIndex(), and ~FairStack().
Int_t FairGenericStack::fVerbose protected inherited
Verbosity level
Definition at line 177 of file FairGenericStack.h.
Referenced by FairGenericStack::operator=().
The documentation for this class was generated from the following files:
FairStack.h
FairStack.cxx