FairRroot: FairGeoTransform Class Reference
FairGeoTransform Class Reference
#include <FairGeoTransform.h>
Public Member Functions
FairGeoTransform ()
FairGeoTransform (const FairGeoTransform &t)
~FairGeoTransform ()
FairGeoTransform & operator= (const FairGeoTransform &t)
const FairGeoRotation & getRotMatrix () const
const FairGeoVector & getTransVector () const
void setRotMatrix (const FairGeoRotation &r)
void setRotMatrix (const Double_t *a)
void setRotMatrix (const Float_t *a)
void setTransVector (const FairGeoVector &t)
void setTransVector (const Double_t *a)
void setTransVector (const Float_t *a)
FairGeoVector transFrom (const FairGeoVector &p) const
FairGeoVector transTo (const FairGeoVector &p) const
void transFrom (const FairGeoTransform &)
void transTo (const FairGeoTransform &)
void invert (void)
void clear ()
void print ()
const FairGeoVector & getTranslation ()
const FairGeoRotation & getRotation () const
void setTransform (const FairGeoTransform &t)
Protected Attributes
FairGeoRotation rot
FairGeoVector trans
FairGeoVector trans_cm
Detailed Description
basic geometry transformation class
Author
Ilse koenig
Definition at line 21 of file FairGeoTransform.h.
Constructor & Destructor Documentation
FairGeoTransform::FairGeoTransform ()
translation vector, describing the position in cm
FairGeoTransform::FairGeoTransform (const FairGeoTransform & t) inline
Definition at line 59 of file FairGeoTransform.h.
   : TObject(t),
     rot(t.getRotMatrix()),
     trans(t.getTransVector()),
     trans_cm(FairGeoVector(0,0,0))
 {
 }
FairGeoTransform::~FairGeoTransform () inline
Definition at line 30 of file FairGeoTransform.h.
 {}
Member Function Documentation
void FairGeoTransform::clear (void)
Definition at line 124 of file FairGeoTransform.cxx.
References FairGeoVector::clear(), rot, FairGeoRotation::setUnitMatrix(), and trans.
Referenced by FairGeoBrik::calcVoluPosition(), FairGeoTube::calcVoluPosition(), FairGeoTubs::calcVoluPosition(), FairGeoCons::calcVoluPosition(), FairGeoSphe::calcVoluPosition(), FairGeoCone::calcVoluPosition(), FairGeoPcon::calcVoluPosition(), FairGeoEltu::calcVoluPosition(), FairGeoPgon::calcVoluPosition(), and FairGeoVolume::clear().
 {
   trans.clear();
   rot.setUnitMatrix();
 }
const FairGeoRotation& FairGeoTransform::getRotation () const inline
Definition at line 53 of file FairGeoTransform.h.
References rot.
 { return rot; }
const FairGeoRotation& FairGeoTransform::getRotMatrix () const inline
Definition at line 32 of file FairGeoTransform.h.
References rot.
Referenced by FairGeoNode::compare(), FairGeoRootBuilder::createNode(), operator=(), FairGeoBasicShape::posInMother(), FairGeoNode::print(), setTransform(), transFrom(), transTo(), and FairGeoNode::write().
 { return rot; }
const FairGeoVector& FairGeoTransform::getTranslation () inline
Definition at line 47 of file FairGeoTransform.h.
References trans.
{
       const double fac = 10.;
       trans_cm=trans;
       return (trans_cm/=fac);
     }
const FairGeoVector& FairGeoTransform::getTransVector () const inline
Definition at line 33 of file FairGeoTransform.h.
References trans.
Referenced by FairGeoNode::calcRefPos(), FairGeoNode::compare(), FairGeoRootBuilder::createNode(), operator=(), FairGeoBasicShape::posInMother(), FairGeoNode::print(), setTransform(), transFrom(), transTo(), and FairGeoNode::write().
 { return trans; }
void FairGeoTransform::invert (void)
Definition at line 136 of file FairGeoTransform.cxx.
References FairGeoRotation::invert(), rot, and trans.
 {
   rot.invert();
   trans = rot*trans;
   trans *= -1.;
 }
FairGeoTransform & FairGeoTransform::operator= (const FairGeoTransform & t)
Definition at line 63 of file FairGeoTransform.cxx.
References getRotMatrix(), getTransVector(), rot, and trans.
 {
   rot=t.getRotMatrix();
   trans=t.getTransVector();
   return *this;
 }
void FairGeoTransform::print ()
Definition at line 130 of file FairGeoTransform.cxx.
References FairGeoRotation::print(), FairGeoVector::print(), rot, and trans.
Referenced by FairGeoVolume::print().
 {
   rot.print();
   trans.print();
 }
void FairGeoTransform::setRotMatrix (const FairGeoRotation & r) inline
Definition at line 34 of file FairGeoTransform.h.
Referenced by FairGeoTrap::calcVoluPosition(), FairGeoTrd1::calcVoluPosition(), FairGeoBasicShape::posInMother(), FairGeoOldAsciiIo::read(), and FairGeoSet::readTransform().
 { rot=r; }
void FairGeoTransform::setRotMatrix (const Double_t * a) inline
Definition at line 35 of file FairGeoTransform.h.
References FairGeoRotation::setMatrix().
 { rot.setMatrix(a); }
void FairGeoTransform::setRotMatrix (const Float_t * a) inline
Definition at line 36 of file FairGeoTransform.h.
References FairGeoRotation::setMatrix().
 { rot.setMatrix(a); }
void FairGeoTransform::setTransform (const FairGeoTransform & t) inline
Definition at line 69 of file FairGeoTransform.h.
References getRotMatrix(), getTransVector(), rot, and trans.
Referenced by FairGeoNode::getPosition(), and FairGeoNode::setLabTransform().
 {
   rot=t.getRotMatrix();
   trans=t.getTransVector();
 }
void FairGeoTransform::setTransVector (const FairGeoVector & t) inline
Definition at line 37 of file FairGeoTransform.h.
Referenced by FairGeoBrik::calcVoluPosition(), FairGeoTubs::calcVoluPosition(), FairGeoTorus::calcVoluPosition(), FairGeoAssembly::calcVoluPosition(), FairGeoTube::calcVoluPosition(), FairGeoTrap::calcVoluPosition(), FairGeoTrd1::calcVoluPosition(), FairGeoCons::calcVoluPosition(), FairGeoEltu::calcVoluPosition(), FairGeoCone::calcVoluPosition(), FairGeoBasicShape::posInMother(), FairGeoOldAsciiIo::read(), and FairGeoSet::readTransform().
 { trans=t; }
void FairGeoTransform::setTransVector (const Double_t * a) inline
Definition at line 38 of file FairGeoTransform.h.
References FairGeoVector::setVector().
 { trans.setVector(a); }
void FairGeoTransform::setTransVector (const Float_t * a) inline
Definition at line 39 of file FairGeoTransform.h.
References FairGeoVector::setVector().
 { trans.setVector(a); }
FairGeoVector FairGeoTransform::transFrom (const FairGeoVector & p) const
Definition at line 72 of file FairGeoTransform.cxx.
References rot, and trans.
Referenced by FairGeoNode::calcLabTransform(), FairGeoNode::calcModuleTransform(), FairGeoNode::calcRefPos(), and FairGeoBasicShape::posInMother().
 {
   // Transforms a vector (point) given in its own coordinate
   // system (2) into the reference coordinate system (1)
   // e.g. v2 is a vector (point) in the detector coordinate system;
   // it can be transformed to a vector v2 the lab system with
   //    FairGeoVector v2=mo.transFrom(v1)
   // where mo is the coordinate system of the mother
   return rot*p+trans;
 }
void FairGeoTransform::transFrom (const FairGeoTransform & s)
Definition at line 111 of file FairGeoTransform.cxx.
References getRotMatrix(), getTransVector(), rot, trans, and FairGeoRotation::transform().
 {
   // Transforms the coordinate system described by s into the local
   // coordinate system
   // This function is e.g. used to transform a daughter coordinate system
   // with a transformation relative to its mother into the lab system.
   // e.g. daughterDetTransform.transFrom(motherLabTransform)
   const FairGeoRotation& r=s.getRotMatrix();
   rot.transform(r);
   trans=r*trans;
   trans+=s.getTransVector();
 }
FairGeoVector FairGeoTransform::transTo (const FairGeoVector & p) const
Definition at line 83 of file FairGeoTransform.cxx.
References FairGeoRotation::inverse(), rot, and trans.
Referenced by FairGeoBasicShape::posInMother(), and FairGeoNode::setLabTransform().
 {
   // Transforms a vector (point) given in the reference system (1)
   // into the local coordinate system (2)
   // e.g. v1 is a vector (point) in the lab system; it can be transformed to
   // a vector v2 the detector coordinate system with
   //    FairGeoVector v2=mo.transTo(v1)
   // where mo is the coordinate system of the mother
   return rot.inverse()*(p-trans);
 }
void FairGeoTransform::transTo (const FairGeoTransform & s)
Definition at line 94 of file FairGeoTransform.cxx.
References FairGeoRotation::diff2(), getRotMatrix(), getTransVector(), FairGeoRotation::inverse(), rot, FairGeoRotation::setUnitMatrix(), trans, and FairGeoRotation::transform().
 {
   // Transforms the coordinate system into the coordinate system
   // described by s. Both transformations must have the same reference
   // system e.g. the lab system
   // This function is e.g. used to transform a daughter coordinate system
   // with a transformation relative to the lab into the detector coordinate
   // system.
   const FairGeoRotation& rm=s.getRotMatrix();
   FairGeoRotation rt(rm.inverse());
   if (rm.diff2(rot)<0.000001) { rot.setUnitMatrix(); }
   else { rot.transform(rt); }
   trans-=s.getTransVector();
   trans=rt*trans;
   //  trans.round(3); // rounds to 3 digits (precision 1 micrometer)
 }
Member Data Documentation
FairGeoRotation FairGeoTransform::rot protected
Definition at line 24 of file FairGeoTransform.h.
Referenced by clear(), getRotation(), getRotMatrix(), invert(), operator=(), print(), setTransform(), transFrom(), and transTo().
FairGeoVector FairGeoTransform::trans protected
rotation matrix, describing the orientation
Definition at line 25 of file FairGeoTransform.h.
Referenced by clear(), getTranslation(), getTransVector(), invert(), operator=(), print(), setTransform(), transFrom(), and transTo().
FairGeoVector FairGeoTransform::trans_cm protected
translation vector, describing the position
Definition at line 26 of file FairGeoTransform.h.
The documentation for this class was generated from the following files:
FairGeoTransform.h
FairGeoTransform.cxx