FairRroot: RootSerializer Class Reference
RootSerializer Class Reference
#include <RootSerializer.h>
Public Member Functions
RootSerializer ()
~RootSerializer ()
void InitContainer (const std::string &ClassName)
void InitContainer (TClonesArray *array)
virtual void DoSerialization (TClonesArray *array)
virtual FairMQMessage * SerializeMsg (TClonesArray *array)
void SetMessage (FairMQMessage *msg)
FairMQMessage * GetMessage ()
Protected Attributes
TClonesArray * fContainer
FairMQMessage * fMessage
int fNumInput
Detailed Description
Definition at line 38 of file RootSerializer.h.
Constructor & Destructor Documentation
RootSerializer::RootSerializer () inline
Definition at line 43 of file RootSerializer.h.
 : fContainer(nullptr), fMessage(nullptr), fNumInput(0) {}
RootSerializer::~RootSerializer () inline
Definition at line 44 of file RootSerializer.h.
 {}
Member Function Documentation
virtual void RootSerializer::DoSerialization (TClonesArray * array) inline virtual
Definition at line 60 of file RootSerializer.h.
References fMessage, free_tmessage(), and FairMQMessage::Rebuild().
Referenced by SerializeMsg().
     {
         TMessage* tm = new TMessage(kMESS_OBJECT);
         tm->WriteObject(array);
         //fMessage = fTransportFactory->CreateMessage(tm->Buffer(), tm->BufferSize(), free_tmessage, tm);
         fMessage->Rebuild(tm->Buffer(), tm->BufferSize(), free_tmessage, tm);
     }
FairMQMessage* RootSerializer::GetMessage () inline
Definition at line 83 of file RootSerializer.h.
References fMessage.
     {
         return fMessage;
     }
void RootSerializer::InitContainer (const std::string & ClassName) inline
Definition at line 46 of file RootSerializer.h.
References fContainer.
     {
         fContainer = new TClonesArray(ClassName.c_str());
     }
void RootSerializer::InitContainer (TClonesArray * array) inline
Definition at line 51 of file RootSerializer.h.
References fContainer.
     {
         fContainer = array;
     }
virtual FairMQMessage* RootSerializer::SerializeMsg (TClonesArray * array) inline virtual
Definition at line 70 of file RootSerializer.h.
References DoSerialization(), and fMessage.
     {
         DoSerialization(array);
         return fMessage;
     }
void RootSerializer::SetMessage (FairMQMessage * msg) inline
Definition at line 78 of file RootSerializer.h.
References fMessage.
     {
         fMessage=msg;
     }
Member Data Documentation
TClonesArray* RootSerializer::fContainer protected
Definition at line 92 of file RootSerializer.h.
Referenced by InitContainer().
FairMQMessage* RootSerializer::fMessage protected
Definition at line 93 of file RootSerializer.h.
Referenced by DoSerialization(), GetMessage(), SerializeMsg(), and SetMessage().
int RootSerializer::fNumInput protected
Definition at line 94 of file RootSerializer.h.
The documentation for this class was generated from the following file:
RootSerializer.h