FairRoot: TestDetectorProto::Digi Class Reference
TestDetectorProto::Digi Class Reference
#include <FairTestDetectorPayload.pb.h>
Public Member Functions
Digi ()
virtual ~Digi ()
Digi (const Digi &from)
Digi & operator= (const Digi &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Digi *other)
Digi * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Digi &from)
void MergeFrom (const Digi &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_fx () const
void clear_fx ()
inline::google::protobuf::int32 fx () const
void set_fx (::google::protobuf::int32 value)
bool has_fy () const
void clear_fy ()
inline::google::protobuf::int32 fy () const
void set_fy (::google::protobuf::int32 value)
bool has_fz () const
void clear_fz ()
inline::google::protobuf::int32 fz () const
void set_fz (::google::protobuf::int32 value)
bool has_ftimestamp () const
void clear_ftimestamp ()
double ftimestamp () const
void set_ftimestamp (double value)
bool has_ftimestamperror () const
void clear_ftimestamperror ()
double ftimestamperror () const
void set_ftimestamperror (double value)
Digi ()
virtual ~Digi ()
Digi (const Digi &from)
Digi & operator= (const Digi &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Digi *other)
Digi * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Digi &from)
void MergeFrom (const Digi &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_fx () const
void clear_fx ()
inline::google::protobuf::int32 fx () const
void set_fx (::google::protobuf::int32 value)
bool has_fy () const
void clear_fy ()
inline::google::protobuf::int32 fy () const
void set_fy (::google::protobuf::int32 value)
bool has_fz () const
void clear_fz ()
inline::google::protobuf::int32 fz () const
void set_fz (::google::protobuf::int32 value)
bool has_ftimestamp () const
void clear_ftimestamp ()
double ftimestamp () const
void set_ftimestamp (double value)
bool has_ftimestamperror () const
void clear_ftimestamperror ()
double ftimestamperror () const
void set_ftimestamperror (double value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Digi & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const Digi & default_instance ()
Static Public Attributes
static const int kFXFieldNumber = 1
static const int kFYFieldNumber = 2
static const int kFZFieldNumber = 3
static const int kFTimeStampFieldNumber = 4
static const int kFTimeStampErrorFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_fx ()
void clear_has_fx ()
void set_has_fy ()
void clear_has_fy ()
void set_has_fz ()
void clear_has_fz ()
void set_has_ftimestamp ()
void clear_has_ftimestamp ()
void set_has_ftimestamperror ()
void clear_has_ftimestamperror ()
void InitAsDefaultInstance ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_fx ()
void clear_has_fx ()
void set_has_fy ()
void clear_has_fy ()
void set_has_fz ()
void clear_has_fz ()
void set_has_ftimestamp ()
void clear_has_ftimestamp ()
void set_has_ftimestamperror ()
void clear_has_ftimestamperror ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::int32 fx_
::google::protobuf::int32 fy_
double ftimestamp_
double ftimestamperror_
::google::protobuf::int32 fz_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(5+31)/32]
Static Private Attributes
static Digi * default_instance_ = NULL
Friends
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
Detailed Description
Definition at line 43 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Constructor & Destructor Documentation
TestDetectorProto::Digi::Digi ()
Definition at line 201 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References SharedCtor().
Referenced by New().
   : ::google::protobuf::Message() {
   SharedCtor();
 }
TestDetectorProto::Digi::~Digi () virtual
Definition at line 225 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References SharedDtor().
             {
   SharedDtor();
 }
TestDetectorProto::Digi::Digi (const Digi & from)
Definition at line 209 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References MergeFrom(), and SharedCtor().
   : ::google::protobuf::Message() {
   SharedCtor();
   MergeFrom(from);
 }
TestDetectorProto::Digi::Digi ()
virtual TestDetectorProto::Digi::~Digi () virtual
TestDetectorProto::Digi::Digi (const Digi & from)
Member Function Documentation
int TestDetectorProto::Digi::ByteSize () const
Definition at line 435 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, _has_bits_, fx(), fy(), fz(), has_ftimestamp(), has_ftimestamperror(), has_fx(), has_fy(), has_fz(), and unknown_fields().
{
   int total_size = 0;
   if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     // optional int32 fX = 1;
     if (has_fx()) {
       total_size += 1 +
         ::google::protobuf::internal::WireFormatLite::Int32Size(
           this->fx());
     }
     // optional int32 fY = 2;
     if (has_fy()) {
       total_size += 1 +
         ::google::protobuf::internal::WireFormatLite::Int32Size(
           this->fy());
     }
     // optional int32 fZ = 3;
     if (has_fz()) {
       total_size += 1 +
         ::google::protobuf::internal::WireFormatLite::Int32Size(
           this->fz());
     }
     // optional double fTimeStamp = 4;
     if (has_ftimestamp()) {
       total_size += 1 + 8;
     }
     // optional double fTimeStampError = 5;
     if (has_ftimestamperror()) {
       total_size += 1 + 8;
     }
   }
   if (!unknown_fields().empty()) {
     total_size +=
       ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
         unknown_fields());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
int TestDetectorProto::Digi::ByteSize () const
void TestDetectorProto::Digi::Clear ()
void TestDetectorProto::Digi::Clear ()
Definition at line 255 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _has_bits_, ftimestamp_, ftimestamperror_, fx_, fy_, fz_, and mutable_unknown_fields().
Referenced by CopyFrom().
                  {
   if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     fx_ = 0;
     fy_ = 0;
     fz_ = 0;
     ftimestamp_ = 0;
     ftimestamperror_ = 0;
   }
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
   mutable_unknown_fields()->Clear();
 }
void TestDetectorProto::Digi::clear_ftimestamp () inline
Definition at line 588 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_ftimestamp(), and ftimestamp_.
{
   ftimestamp_ = 0;
   clear_has_ftimestamp();
 }
void TestDetectorProto::Digi::clear_ftimestamp () inline
void TestDetectorProto::Digi::clear_ftimestamperror () inline
Definition at line 610 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_ftimestamperror(), and ftimestamperror_.
{
   ftimestamperror_ = 0;
   clear_has_ftimestamperror();
 }
void TestDetectorProto::Digi::clear_ftimestamperror () inline
void TestDetectorProto::Digi::clear_fx () inline
void TestDetectorProto::Digi::clear_fx () inline
Definition at line 522 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_fx(), and fx_.
{
   fx_ = 0;
   clear_has_fx();
 }
void TestDetectorProto::Digi::clear_fy () inline
void TestDetectorProto::Digi::clear_fy () inline
Definition at line 544 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_fy(), and fy_.
{
   fy_ = 0;
   clear_has_fy();
 }
void TestDetectorProto::Digi::clear_fz () inline
Definition at line 566 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References clear_has_fz(), and fz_.
{
   fz_ = 0;
   clear_has_fz();
 }
void TestDetectorProto::Digi::clear_fz () inline
void TestDetectorProto::Digi::clear_has_ftimestamp () inline private
Definition at line 585 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_ftimestamp().
{
   _has_bits_[0] &= ~0x00000008u;
 }
void TestDetectorProto::Digi::clear_has_ftimestamp () inline private
void TestDetectorProto::Digi::clear_has_ftimestamperror () inline private
Definition at line 607 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_ftimestamperror().
{
   _has_bits_[0] &= ~0x00000010u;
 }
void TestDetectorProto::Digi::clear_has_ftimestamperror () inline private
void TestDetectorProto::Digi::clear_has_fx () inline private
Definition at line 519 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_fx().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void TestDetectorProto::Digi::clear_has_fx () inline private
void TestDetectorProto::Digi::clear_has_fy () inline private
Definition at line 541 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_fy().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void TestDetectorProto::Digi::clear_has_fy () inline private
void TestDetectorProto::Digi::clear_has_fz () inline private
void TestDetectorProto::Digi::clear_has_fz () inline private
Definition at line 563 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by clear_fz().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void TestDetectorProto::Digi::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 516 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void TestDetectorProto::Digi::CopyFrom (const ::google::protobuf::Message & from)
void TestDetectorProto::Digi::CopyFrom (const Digi & from)
Definition at line 522 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Clear(), and MergeFrom().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void TestDetectorProto::Digi::CopyFrom (const Digi & from)
const Digi & TestDetectorProto::Digi::default_instance () static
Definition at line 244 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References default_instance_, and protobuf_AddDesc_FairTestDetectorPayload_2eproto.
{
   if (default_instance_ == NULL) protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   return *default_instance_;
 }
static const Digi& TestDetectorProto::Digi::default_instance () static
const ::google::protobuf::Descriptor * TestDetectorProto::Digi::descriptor () static
Definition at line 239 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   return Digi_descriptor_;
 }
static const ::google::protobuf::Descriptor* TestDetectorProto::Digi::descriptor () static
double TestDetectorProto::Digi::ftimestamp () const inline
Definition at line 592 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References ftimestamp_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return ftimestamp_;
 }
double TestDetectorProto::Digi::ftimestamp () const inline
double TestDetectorProto::Digi::ftimestamperror () const inline
Definition at line 614 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References ftimestamperror_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return ftimestamperror_;
 }
double TestDetectorProto::Digi::ftimestamperror () const inline
inline ::google::protobuf::int32 TestDetectorProto::Digi::fx () const
google::protobuf::int32 TestDetectorProto::Digi::fx () const inline
Definition at line 526 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References fx_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return fx_;
 }
inline ::google::protobuf::int32 TestDetectorProto::Digi::fy () const
google::protobuf::int32 TestDetectorProto::Digi::fy () const inline
Definition at line 548 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References fy_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return fy_;
 }
google::protobuf::int32 TestDetectorProto::Digi::fz () const inline
Definition at line 570 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References fz_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return fz_;
 }
inline ::google::protobuf::int32 TestDetectorProto::Digi::fz () const
int TestDetectorProto::Digi::GetCachedSize () const inline
Definition at line 84 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _cached_size_.
 { return _cached_size_; }
int TestDetectorProto::Digi::GetCachedSize () const inline
Definition at line 84 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _cached_size_.
 { return _cached_size_; }
::google::protobuf::Metadata TestDetectorProto::Digi::GetMetadata () const
google::protobuf::Metadata TestDetectorProto::Digi::GetMetadata () const
Definition at line 546 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::Metadata metadata;
   metadata.descriptor = Digi_descriptor_;
   metadata.reflection = Digi_reflection_;
   return metadata;
 }
bool TestDetectorProto::Digi::has_ftimestamp () const inline
Definition at line 579 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool TestDetectorProto::Digi::has_ftimestamp () const inline
bool TestDetectorProto::Digi::has_ftimestamperror () const inline
Definition at line 601 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool TestDetectorProto::Digi::has_ftimestamperror () const inline
bool TestDetectorProto::Digi::has_fx () const inline
bool TestDetectorProto::Digi::has_fx () const inline
Definition at line 513 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool TestDetectorProto::Digi::has_fy () const inline
bool TestDetectorProto::Digi::has_fy () const inline
Definition at line 535 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool TestDetectorProto::Digi::has_fz () const inline
bool TestDetectorProto::Digi::has_fz () const inline
Definition at line 557 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
void TestDetectorProto::Digi::InitAsDefaultInstance () private
void TestDetectorProto::Digi::InitAsDefaultInstance () private
Definition at line 206 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto().
{
 }
bool TestDetectorProto::Digi::IsInitialized () const
bool TestDetectorProto::Digi::IsInitialized () const
Definition at line 528 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   return true;
 }
void TestDetectorProto::Digi::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 482 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by CopyFrom(), and Digi().
{
   GOOGLE_CHECK_NE(&from, this);
   const Digi* source =
     ::google::protobuf::internal::dynamic_cast_if_available<const Digi*>(
       &from);
   if (source == NULL) {
     ::google::protobuf::internal::ReflectionOps::Merge(from, this);
   } else {
     MergeFrom(*source);
   }
 }
void TestDetectorProto::Digi::MergeFrom (const ::google::protobuf::Message & from)
void TestDetectorProto::Digi::MergeFrom (const Digi & from)
void TestDetectorProto::Digi::MergeFrom (const Digi & from)
Definition at line 494 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _has_bits_, ftimestamp(), ftimestamperror(), fx(), fy(), fz(), has_ftimestamp(), has_ftimestamperror(), has_fx(), has_fy(), has_fz(), mutable_unknown_fields(), set_ftimestamp(), set_ftimestamperror(), set_fx(), set_fy(), set_fz(), and unknown_fields().
{
   GOOGLE_CHECK_NE(&from, this);
   if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     if (from.has_fx()) {
       set_fx(from.fx());
     }
     if (from.has_fy()) {
       set_fy(from.fy());
     }
     if (from.has_fz()) {
       set_fz(from.fz());
     }
     if (from.has_ftimestamp()) {
       set_ftimestamp(from.ftimestamp());
     }
     if (from.has_ftimestamperror()) {
       set_ftimestamperror(from.ftimestamperror());
     }
   }
   mutable_unknown_fields()->MergeFrom(from.unknown_fields());
 }
bool TestDetectorProto::Digi::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool TestDetectorProto::Digi::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 267 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References DO_, ftimestamp_, ftimestamperror_, fx_, fy_, fz_, mutable_unknown_fields(), set_has_ftimestamp(), set_has_ftimestamperror(), set_has_fx(), set_has_fy(), and set_has_fz().
{
 #define DO_(EXPRESSION) if (!(EXPRESSION)) return false
   ::google::protobuf::uint32 tag;
   while ((tag = input->ReadTag()) != 0) {
     switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
       // optional int32 fX = 1;
       case 1: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, &fx_)));
           set_has_fx();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(16)) goto parse_fY;
         break;
       }
       // optional int32 fY = 2;
       case 2: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          parse_fY:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, &fy_)));
           set_has_fy();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(24)) goto parse_fZ;
         break;
       }
       // optional int32 fZ = 3;
       case 3: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          parse_fZ:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, &fz_)));
           set_has_fz();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(33)) goto parse_fTimeStamp;
         break;
       }
       // optional double fTimeStamp = 4;
       case 4: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_fTimeStamp:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &ftimestamp_)));
           set_has_ftimestamp();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(41)) goto parse_fTimeStampError;
         break;
       }
       // optional double fTimeStampError = 5;
       case 5: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_fTimeStampError:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &ftimestamperror_)));
           set_has_ftimestamperror();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectAtEnd()) return true;
         break;
       }
       default: {
       handle_uninterpreted:
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
           return true;
         }
         DO_(::google::protobuf::internal::WireFormat::SkipField(
               input, tag, mutable_unknown_fields()));
         break;
       }
     }
   }
   return true;
 #undef DO_
 }
inline ::google::protobuf::UnknownFieldSet* TestDetectorProto::Digi::mutable_unknown_fields () inline
Definition at line 59 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
{
     return &_unknown_fields_;
   }
inline ::google::protobuf::UnknownFieldSet* TestDetectorProto::Digi::mutable_unknown_fields () inline
Definition at line 59 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
{
     return &_unknown_fields_;
   }
Digi * TestDetectorProto::Digi::New () const
Definition at line 251 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Digi().
                       {
   return new Digi;
 }
Digi* TestDetectorProto::Digi::New () const
Digi& TestDetectorProto::Digi::operator= (const Digi & from) inline
Definition at line 50 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
Digi& TestDetectorProto::Digi::operator= (const Digi & from) inline
Definition at line 50 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
void TestDetectorProto::Digi::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void TestDetectorProto::Digi::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 368 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References ftimestamp(), ftimestamperror(), fx(), fy(), fz(), has_ftimestamp(), has_ftimestamperror(), has_fx(), has_fy(), has_fz(), and unknown_fields().
{
   // optional int32 fX = 1;
   if (has_fx()) {
     ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->fx(), output);
   }
   // optional int32 fY = 2;
   if (has_fy()) {
     ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->fy(), output);
   }
   // optional int32 fZ = 3;
   if (has_fz()) {
     ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->fz(), output);
   }
   // optional double fTimeStamp = 4;
   if (has_ftimestamp()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->ftimestamp(), output);
   }
   // optional double fTimeStampError = 5;
   if (has_ftimestamperror()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->ftimestamperror(), output);
   }
   if (!unknown_fields().empty()) {
     ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
         unknown_fields(), output);
   }
 }
::google::protobuf::uint8* TestDetectorProto::Digi::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
google::protobuf::uint8 * TestDetectorProto::Digi::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 401 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References ftimestamp(), ftimestamperror(), fx(), fy(), fz(), has_ftimestamp(), has_ftimestamperror(), has_fx(), has_fy(), has_fz(), and unknown_fields().
{
   // optional int32 fX = 1;
   if (has_fx()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->fx(), target);
   }
   // optional int32 fY = 2;
   if (has_fy()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->fy(), target);
   }
   // optional int32 fZ = 3;
   if (has_fz()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->fz(), target);
   }
   // optional double fTimeStamp = 4;
   if (has_ftimestamp()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->ftimestamp(), target);
   }
   // optional double fTimeStampError = 5;
   if (has_ftimestamperror()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->ftimestamperror(), target);
   }
   if (!unknown_fields().empty()) {
     target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
         unknown_fields(), target);
   }
   return target;
 }
void TestDetectorProto::Digi::set_ftimestamp (double value) inline
Definition at line 595 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References ftimestamp_, and set_has_ftimestamp().
Referenced by MergeFrom().
{
   set_has_ftimestamp();
   ftimestamp_ = value;
 }
void TestDetectorProto::Digi::set_ftimestamp (double value) inline
void TestDetectorProto::Digi::set_ftimestamperror (double value) inline
void TestDetectorProto::Digi::set_ftimestamperror (double value) inline
Definition at line 617 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References ftimestamperror_, and set_has_ftimestamperror().
Referenced by MergeFrom().
{
   set_has_ftimestamperror();
   ftimestamperror_ = value;
 }
void TestDetectorProto::Digi::set_fx (::google::protobuf::int32 value) inline
void TestDetectorProto::Digi::set_fx (::google::protobuf::int32 value) inline
Definition at line 529 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References fx_, and set_has_fx().
Referenced by MergeFrom().
{
   set_has_fx();
   fx_ = value;
 }
void TestDetectorProto::Digi::set_fy (::google::protobuf::int32 value) inline
void TestDetectorProto::Digi::set_fy (::google::protobuf::int32 value) inline
Definition at line 551 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References fy_, and set_has_fy().
Referenced by MergeFrom().
{
   set_has_fy();
   fy_ = value;
 }
void TestDetectorProto::Digi::set_fz (::google::protobuf::int32 value) inline
void TestDetectorProto::Digi::set_fz (::google::protobuf::int32 value) inline
Definition at line 573 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References fz_, and set_has_fz().
Referenced by MergeFrom().
{
   set_has_fz();
   fz_ = value;
 }
void TestDetectorProto::Digi::set_has_ftimestamp () inline private
Definition at line 582 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_ftimestamp().
{
   _has_bits_[0] |= 0x00000008u;
 }
void TestDetectorProto::Digi::set_has_ftimestamp () inline private
void TestDetectorProto::Digi::set_has_ftimestamperror () inline private
void TestDetectorProto::Digi::set_has_ftimestamperror () inline private
Definition at line 604 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_ftimestamperror().
{
   _has_bits_[0] |= 0x00000010u;
 }
void TestDetectorProto::Digi::set_has_fx () inline private
void TestDetectorProto::Digi::set_has_fx () inline private
Definition at line 516 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_fx().
{
   _has_bits_[0] |= 0x00000001u;
 }
void TestDetectorProto::Digi::set_has_fy () inline private
Definition at line 538 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_fy().
{
   _has_bits_[0] |= 0x00000002u;
 }
void TestDetectorProto::Digi::set_has_fy () inline private
void TestDetectorProto::Digi::set_has_fz () inline private
Definition at line 560 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_fz().
{
   _has_bits_[0] |= 0x00000004u;
 }
void TestDetectorProto::Digi::set_has_fz () inline private
void TestDetectorProto::Digi::SetCachedSize (int size) const private
Definition at line 234 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_.
{
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
 }
void TestDetectorProto::Digi::SetCachedSize (int size) const private
void TestDetectorProto::Digi::SharedCtor () private
Definition at line 215 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, _has_bits_, ftimestamp_, ftimestamperror_, fx_, fy_, and fz_.
Referenced by Digi().
                       {
   _cached_size_ = 0;
   fx_ = 0;
   fy_ = 0;
   fz_ = 0;
   ftimestamp_ = 0;
   ftimestamperror_ = 0;
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
 }
void TestDetectorProto::Digi::SharedCtor () private
void TestDetectorProto::Digi::SharedDtor () private
Definition at line 229 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References default_instance_.
Referenced by ~Digi().
                       {
   if (this != default_instance_) {
   }
 }
void TestDetectorProto::Digi::SharedDtor () private
void TestDetectorProto::Digi::Swap (Digi * other)
Definition at line 533 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, ftimestamp_, ftimestamperror_, fx_, fy_, and fz_.
{
   if (other != this) {
     std::swap(fx_, other->fx_);
     std::swap(fy_, other->fy_);
     std::swap(fz_, other->fz_);
     std::swap(ftimestamp_, other->ftimestamp_);
     std::swap(ftimestamperror_, other->ftimestamperror_);
     std::swap(_has_bits_[0], other->_has_bits_[0]);
     _unknown_fields_.Swap(&other->_unknown_fields_);
     std::swap(_cached_size_, other->_cached_size_);
   }
 }
void TestDetectorProto::Digi::Swap (Digi * other)
const ::google::protobuf::UnknownFieldSet& TestDetectorProto::Digi::unknown_fields () const inline
Definition at line 55 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
     return _unknown_fields_;
   }
const ::google::protobuf::UnknownFieldSet& TestDetectorProto::Digi::unknown_fields () const inline
Definition at line 55 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
{
     return _unknown_fields_;
   }
Friends And Related Function Documentation
void protobuf_AddDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by default_instance().
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void protobuf_AddDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto () friend
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto () friend
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
Member Data Documentation
int TestDetectorProto::Digi::_cached_size_ mutable private
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
google::protobuf::uint32 TestDetectorProto::Digi::_has_bits_ private
Definition at line 154 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by ByteSize(), Clear(), clear_has_ftimestamp(), clear_has_ftimestamperror(), clear_has_fx(), clear_has_fy(), clear_has_fz(), has_ftimestamp(), has_ftimestamperror(), has_fx(), has_fy(), has_fz(), MergeFrom(), set_has_ftimestamp(), set_has_ftimestamperror(), set_has_fx(), set_has_fy(), set_has_fz(), SharedCtor(), and Swap().
google::protobuf::UnknownFieldSet TestDetectorProto::Digi::_unknown_fields_ private
Definition at line 145 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
static Digi * TestDetectorProto::Digi::default_instance_ = NULL static private
Definition at line 161 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by default_instance(), TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto(), TestDetectorProto::protobuf_AssignDesc_FairTestDetectorPayload_2eproto(), TestDetectorProto::protobuf_ShutdownFile_FairTestDetectorPayload_2eproto(), and SharedDtor().
double TestDetectorProto::Digi::ftimestamp_ private
Definition at line 149 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_ftimestamp(), ftimestamp(), MergePartialFromCodedStream(), set_ftimestamp(), SharedCtor(), and Swap().
double TestDetectorProto::Digi::ftimestamperror_ private
Definition at line 150 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_ftimestamperror(), ftimestamperror(), MergePartialFromCodedStream(), set_ftimestamperror(), SharedCtor(), and Swap().
google::protobuf::int32 TestDetectorProto::Digi::fx_ private
Definition at line 147 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_fx(), fx(), MergePartialFromCodedStream(), set_fx(), SharedCtor(), and Swap().
google::protobuf::int32 TestDetectorProto::Digi::fy_ private
Definition at line 148 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_fy(), fy(), MergePartialFromCodedStream(), set_fy(), SharedCtor(), and Swap().
google::protobuf::int32 TestDetectorProto::Digi::fz_ private
Definition at line 151 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), clear_fz(), fz(), MergePartialFromCodedStream(), set_fz(), SharedCtor(), and Swap().
static const int TestDetectorProto::Digi::kFTimeStampErrorFieldNumber = 5 static
Definition at line 128 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Digi::kFTimeStampFieldNumber = 4 static
Definition at line 121 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Digi::kFXFieldNumber = 1 static
Definition at line 100 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Digi::kFYFieldNumber = 2 static
Definition at line 107 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
static const int TestDetectorProto::Digi::kFZFieldNumber = 3 static
Definition at line 114 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
The documentation for this class was generated from the following files:
Tutorial3/data/FairTestDetectorPayload.pb.h
Tutorial3/data/FairTestDetectorPayload.pb.cc