FairRoot: FairTestDetectorDigi Class Reference
FairTestDetectorDigi Class Reference
#include <FairTestDetectorDigi.h>
Public Member Functions
FairTestDetectorDigi ()
FairTestDetectorDigi (Int_t x, Int_t y, Int_t z, Double_t timeStamp)
virtual ~FairTestDetectorDigi ()
void SetXYZ (Int_t x, Int_t y, Int_t z)
void SetX (Int_t x)
void SetY (Int_t y)
void SetZ (Int_t z)
Int_t GetX () const
Int_t GetY () const
Int_t GetZ () const
virtual bool equal (FairTimeStamp *data)
virtual bool operator< (const FairTestDetectorDigi &myDigi) const
template<class T >
std::string ToString (const T &value)
std::string ToString ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
FairTestDetectorDigi ()
FairTestDetectorDigi (Int_t x, Int_t y, Int_t z, Double_t timeStamp)
virtual ~FairTestDetectorDigi ()
void SetXYZ (Int_t x, Int_t y, Int_t z)
void SetX (Int_t x)
void SetY (Int_t y)
void SetZ (Int_t z)
Int_t GetX () const
Int_t GetY () const
Int_t GetZ () const
virtual bool equal (FairTimeStamp *data)
virtual bool operator< (const FairTestDetectorDigi &myDigi) const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
virtual Double_t GetTimeStamp () const
virtual Double_t GetTimeStampError () const
virtual FairLink GetEntryNr () const
virtual void SetTimeStamp (Double_t t)
virtual void SetTimeStampError (Double_t t)
virtual void SetEntryNr (FairLink entry)
virtual Int_t Compare (const TObject *obj) const
virtual std::ostream & Print (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool operator< (const FairTimeStamp *rValue) const
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
virtual FairMultiLinkedData * GetPointerToLinks () const
virtual void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link)
Sets the Links with a single FairLink.
virtual void SetInsertHistory (Bool_t val)
virtual void SetPointerToLinks (FairMultiLinkedData *links)
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
virtual void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
virtual void AddInterfaceData (FairMultiLinkedData_Interface *data)
virtual void ResetLinks ()
Protected Member Functions
ClassDef (FairTimeStamp, 3)
indicates where the data is stored in the branch
ClassDef (FairMultiLinkedData_Interface, 5)
FairMultiLinkedData * CreateFairMultiLinkedData ()
Protected Attributes
Double_t fTimeStamp
Double_t fTimeStampError
FairLink fEntryNr
Int_t fVerbose
FairMultiLinkedData * fLink
Private Member Functions
ClassDef (FairTestDetectorDigi, 1)
ClassDef (FairTestDetectorDigi, 1)
Private Attributes
Int_t fX
Int_t fY
Int_t fZ
Friends
class boost::serialization::access
std::ostream & operator<< (std::ostream &out, FairTestDetectorDigi &digi)
std::ostream & operator<< (std::ostream &out, FairTestDetectorDigi &digi)
Detailed Description
Definition at line 32 of file Tutorial3/data/FairTestDetectorDigi.h.
Constructor & Destructor Documentation
FairTestDetectorDigi::FairTestDetectorDigi ()
Definition at line 18 of file Tutorial3/data/FairTestDetectorDigi.cxx.
     : FairTimeStamp()
     , fX(0)
     , fY(0)
     , fZ(0)
 {
 }
FairTestDetectorDigi::FairTestDetectorDigi (Int_t x, Int_t y, Int_t z, Double_t timeStamp)
Definition at line 26 of file Tutorial3/data/FairTestDetectorDigi.cxx.
     : FairTimeStamp(timeStamp)
     , fX(x)
     , fY(y)
     , fZ(z)
 {
 }
FairTestDetectorDigi::~FairTestDetectorDigi () virtual
Definition at line 34 of file Tutorial3/data/FairTestDetectorDigi.cxx.
 {
 }
FairTestDetectorDigi::FairTestDetectorDigi ()
FairTestDetectorDigi::FairTestDetectorDigi (Int_t x, Int_t y, Int_t z, Double_t timeStamp)
virtual FairTestDetectorDigi::~FairTestDetectorDigi () virtual
Member Function Documentation
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) virtual inherited
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
 {
         SetInsertHistory(kFALSE); //todo add previous history value
         if (data->GetEntryNr().GetType() != -1)
                 AddLink(data->GetEntryNr());
         else
                 std::cout
                                 << "-E- FairMultiLinkedData_Interface::AddInterfaceData EntryNr == "
                                 << data->GetEntryNr() << std::endl;
         if (data->GetPointerToLinks() != 0) {
                 AddLinks(*data->GetPointerToLinks());
         }
         SetInsertHistory(kTRUE);
 }
void FairMultiLinkedData_Interface::AddLink (FairLink link) virtual inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 154 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLink(link);
         }
 }
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 146 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLinks(links, mult);
         }
 }
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
FairTimeStamp::ClassDef (FairTimeStamp , 3) protected inherited
indicates where the data is stored in the branch
FairTestDetectorDigi::ClassDef (FairTestDetectorDigi , 1) private
FairTestDetectorDigi::ClassDef (FairTestDetectorDigi , 1) private
virtual Int_t FairTimeStamp::Compare (const TObject * obj) const inline virtual inherited
Definition at line 54 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
{
       if (this == obj) { return 0; }
       FairTimeStamp* tsobj = (FairTimeStamp*)obj;
       Double_t ts = tsobj->GetTimeStamp();
       Double_t tserror = tsobj->GetTimeStampError();
       if (fTimeStamp < ts) { return -1; }
       else if (fTimeStamp == ts && fTimeStampError < tserror) { return -1; }
       else if (fTimeStamp == ts && fTimeStampError == tserror) { return 0; }
       else { return 1; }
     }
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 62 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
 {
         if (FairRootManager::Instance()->GetUseFairLinks()){
                 if (fLink == 0){
                         fLink = new FairMultiLinkedData();
                 }
                 return fLink;
         }
         return 0;
 }
virtual bool FairTestDetectorDigi::equal (FairTimeStamp * data) inline virtual
Reimplemented from FairTimeStamp.
Definition at line 70 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fX, fY, fZ, GetX(), GetY(), and GetZ().
     {
         FairTestDetectorDigi* myDigi = dynamic_cast<FairTestDetectorDigi*>(data);
         if (myDigi != 0)
         {
             if (fX == myDigi->GetX())
                 if (fY == myDigi->GetY())
                     if (fZ == myDigi->GetZ())
                     {
                         return true;
                     }
         }
         return false;
     }
virtual bool FairTestDetectorDigi::equal (FairTimeStamp * data) inline virtual
Reimplemented from FairTimeStamp.
Definition at line 72 of file Tutorial3/data/FairTestDetectorDigi.h.
References fX, fY, fZ, GetX(), GetY(), and GetZ().
     {
         FairTestDetectorDigi* myDigi = dynamic_cast<FairTestDetectorDigi*>(data);
         if (myDigi != 0)
         {
             if (fX == myDigi->GetX())
                 if (fY == myDigi->GetY())
                     if (fZ == myDigi->GetZ())
                     {
                         return true;
                     }
         }
         return false;
     }
virtual FairLink FairTimeStamp::GetEntryNr () const inline virtual inherited
Reimplemented from FairMultiLinkedData_Interface.
Definition at line 49 of file FairTimeStamp.h.
References FairTimeStamp::fEntryNr.
 {return fEntryNr;}
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const virtual inherited
returns the FairLink at the given position
Definition at line 92 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLink(pos);
         } else {
                 FairLink emptyLink;
                 return emptyLink;
         }
 }
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const virtual inherited
returns stored links as FairLinks
Definition at line 73 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinks();
         } else {
                 std::set<FairLink> emptySet;
                 return emptySet;
         }
 }
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const virtual inherited
returns all FairLinks with the corresponding type
Definition at line 112 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinksWithType(type);
         } else {
                 FairMultiLinkedData emptyLinks;
                 return emptyLinks;
         }
 }
Int_t FairMultiLinkedData_Interface::GetNLinks () const virtual inherited
returns the number of stored links
Definition at line 83 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetNLinks();
         } else {
                 return 0;
         }
 }
virtual FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline virtual inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::Print(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
 {       return fLink;}
virtual Double_t FairTimeStamp::GetTimeStamp () const inline virtual inherited
Accessors
Definition at line 47 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by StopTime::Call(), TimeGap::Call(), FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), FairRingSorterTask::Exec(), FairTSBufferFunctional::GetData(), FairTimeStampPointDraw::GetValue(), FairTimeStamp::operator<(), FairTimeStamp::Print(), FairWriteoutBuffer::PrintData(), FairWriteoutBuffer::PrintStartTimeMap(), and ToString().
 { return fTimeStamp; };
virtual Double_t FairTimeStamp::GetTimeStampError () const inline virtual inherited
Definition at line 48 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), and FairTimeStamp::Print().
 { return fTimeStampError;};
Int_t FairTestDetectorDigi::GetX () const inline
Definition at line 56 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fX.
     {
         return fX;
     }
Int_t FairTestDetectorDigi::GetX () const inline
Definition at line 58 of file Tutorial3/data/FairTestDetectorDigi.h.
References fX.
Referenced by equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), operator<(), and ToString().
     {
         return fX;
     }
Int_t FairTestDetectorDigi::GetY () const inline
Definition at line 60 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fY.
     {
         return fY;
     }
Int_t FairTestDetectorDigi::GetY () const inline
Definition at line 62 of file Tutorial3/data/FairTestDetectorDigi.h.
References fY.
Referenced by equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), operator<(), and ToString().
     {
         return fY;
     }
Int_t FairTestDetectorDigi::GetZ () const inline
Definition at line 64 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fZ.
     {
         return fZ;
     }
Int_t FairTestDetectorDigi::GetZ () const inline
Definition at line 66 of file Tutorial3/data/FairTestDetectorDigi.h.
References fZ.
Referenced by equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), operator<(), and ToString().
     {
         return fZ;
     }
virtual Bool_t FairTimeStamp::IsSortable () const inline virtual inherited
Definition at line 67 of file FairTimeStamp.h.
 { return kTRUE;};
virtual bool FairTimeStamp::operator< (const FairTimeStamp * rValue) const inline virtual inherited
Definition at line 79 of file FairTimeStamp.h.
References FairTimeStamp::GetTimeStamp().
{
         if (GetTimeStamp() < rValue->GetTimeStamp())
                 return true;
         else
                 return false;
     }
virtual bool FairTestDetectorDigi::operator< (const FairTestDetectorDigi & myDigi) const inline virtual
Definition at line 85 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fX, fY, fZ, GetX(), GetY(), and GetZ().
     {
         if (fX < myDigi.GetX())
         {
             return true;
         }
         else if (fX > myDigi.GetX())
         {
             return false;
         }
         if (fY < myDigi.GetY())
         {
             return true;
         }
         else if (fY > myDigi.GetY())
         {
             return false;
         }
         if (fZ < myDigi.GetZ())
         {
             return true;
         }
         else if (fZ > myDigi.GetZ())
         {
             return false;
         }
         return false;
     }
virtual bool FairTestDetectorDigi::operator< (const FairTestDetectorDigi & myDigi) const inline virtual
Definition at line 87 of file Tutorial3/data/FairTestDetectorDigi.h.
References fX, fY, fZ, GetX(), GetY(), and GetZ().
     {
         if (fX < myDigi.GetX())
         {
             return true;
         }
         else if (fX > myDigi.GetX())
         {
             return false;
         }
         if (fY < myDigi.GetY())
         {
             return true;
         }
         else if (fY > myDigi.GetY())
         {
             return false;
         }
         if (fZ < myDigi.GetZ())
         {
             return true;
         }
         else if (fZ > myDigi.GetZ())
         {
             return false;
         }
         return false;
     }
std::ostream & FairTimeStamp::Print (std::ostream & out = std::cout) const virtual inherited
Definition at line 42 of file FairTimeStamp.cxx.
References FairTimeStamp::fEntryNr, FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), and FairMultiLinkedData_Interface::Print().
Referenced by FairRingSorter::AddElement(), FairRingSorterTask::Exec(), and FairWriteoutBuffer::FillDataToDeadTimeMap().
 {
   out << "EntryNr of Data: " << fEntryNr << " TimeStamp: " << GetTimeStamp() << " +/- " << GetTimeStampError() << std::endl;
   FairMultiLinkedData_Interface::Print(out);
   return out;
 }
void FairMultiLinkedData_Interface::ResetLinks () virtual inherited
Definition at line 185 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
 {
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->ResetLinks();
         }
 }
template<class Archive > void FairTestDetectorDigi::serialize (Archive & ar, const unsigned int version) inline
Definition at line 123 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fX, fY, and fZ.
     {
         ar& boost::serialization::base_object<FairTimeStamp>(*this);
         ar& fX;
         ar& fY;
         ar& fZ;
     }
template<class Archive > void FairTestDetectorDigi::serialize (Archive & ar, const unsigned int version) inline
Definition at line 144 of file Tutorial3/data/FairTestDetectorDigi.h.
References fX, fY, and fZ.
     {
         ar& boost::serialization::base_object<FairTimeStamp>(*this);
         ar& fX;
         ar& fY;
         ar& fZ;
     }
virtual void FairTimeStamp::SetEntryNr (FairLink entry) inline virtual inherited
Reimplemented from FairMultiLinkedData_Interface.
Definition at line 53 of file FairTimeStamp.h.
References FairTimeStamp::fEntryNr.
Referenced by FairRingSorterTask::Exec().
 {fEntryNr = entry;}
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) virtual inherited
Definition at line 178 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         if (GetPointerToLinks() != 0) {
                 GetPointerToLinks()->SetInsertHistory(val);
         }
 }
void FairMultiLinkedData_Interface::SetLink (FairLink link) virtual inherited
Sets the Links with a single FairLink.
Definition at line 130 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetectorTimeRecoTask::Exec(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLink(link);
         }
 }
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) virtual inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 122 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLinks(links);
         }
 }
virtual void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline virtual inherited
Definition at line 53 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
 {fLink = links;}
virtual void FairTimeStamp::SetTimeStamp (Double_t t) inline virtual inherited
Modifiers
Definition at line 51 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
 { fTimeStamp = t; }
virtual void FairTimeStamp::SetTimeStampError (Double_t t) inline virtual inherited
Definition at line 52 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
 {fTimeStampError = t;}
void FairTestDetectorDigi::SetX (Int_t x) inline
Definition at line 43 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fX.
     {
         fX = x;
     }
void FairTestDetectorDigi::SetX (Int_t x) inline
Definition at line 45 of file Tutorial3/data/FairTestDetectorDigi.h.
References fX.
Referenced by SetXYZ().
     {
         fX = x;
     }
void FairTestDetectorDigi::SetXYZ (Int_t x, Int_t y, Int_t z) inline
Definition at line 37 of file Tutorial6/sim/FairTestDetectorDigi.h.
References SetX(), SetY(), and SetZ().
     {
         SetX(x);
         SetY(y);
         SetZ(z);
     }
void FairTestDetectorDigi::SetXYZ (Int_t x, Int_t y, Int_t z) inline
Definition at line 39 of file Tutorial3/data/FairTestDetectorDigi.h.
References SetX(), SetY(), and SetZ().
     {
         SetX(x);
         SetY(y);
         SetZ(z);
     }
void FairTestDetectorDigi::SetY (Int_t y) inline
Definition at line 47 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fY.
     {
         fY = y;
     }
void FairTestDetectorDigi::SetY (Int_t y) inline
Definition at line 49 of file Tutorial3/data/FairTestDetectorDigi.h.
References fY.
Referenced by SetXYZ().
     {
         fY = y;
     }
void FairTestDetectorDigi::SetZ (Int_t z) inline
Definition at line 51 of file Tutorial6/sim/FairTestDetectorDigi.h.
References fZ.
     {
         fZ = z;
     }
void FairTestDetectorDigi::SetZ (Int_t z) inline
Definition at line 53 of file Tutorial3/data/FairTestDetectorDigi.h.
References fZ.
Referenced by SetXYZ().
     {
         fZ = z;
     }
template<class T > std::string FairTestDetectorDigi::ToString (const T & value) inline
Definition at line 127 of file Tutorial3/data/FairTestDetectorDigi.h.
     {
       std::stringstream ss;
       ss.precision(5);
       ss << value;
       return ss.str();
     }
std::string FairTestDetectorDigi::ToString () inline
Definition at line 135 of file Tutorial3/data/FairTestDetectorDigi.h.
References FairTimeStamp::GetTimeStamp(), GetX(), GetY(), and GetZ().
     {
       std::string out = "FairTestDetectorDigi at: (" + ToString(GetX())
             + "/" + ToString(GetY()) + "/" + ToString(GetZ())
             + ") " + " with TimeStamp: " + ToString(GetTimeStamp());
       return out;
     }
Friends And Related Function Documentation
boost::serialization::access friend
Definition at line 154 of file Tutorial3/data/FairTestDetectorDigi.h.
std::ostream& operator<< (std::ostream & out, FairTestDetectorDigi & digi) friend
Definition at line 114 of file Tutorial6/sim/FairTestDetectorDigi.h.
     {
         out << "FairTestDetectorDigi at:"
             << " (" << digi.GetX() << "/" << digi.GetY() << "/" << digi.GetZ() << ") "
             << " with TimeStamp: " << digi.GetTimeStamp() << std::endl;
         return out;
     }
std::ostream& operator<< (std::ostream & out, FairTestDetectorDigi & digi) friend
Definition at line 118 of file Tutorial3/data/FairTestDetectorDigi.h.
     {
         out << "FairTestDetectorDigi at:"
             << " (" << digi.GetX() << "/" << digi.GetY() << "/" << digi.GetZ() << ") "
             << " with TimeStamp: " << digi.GetTimeStamp() << std::endl;
         return out;
     }
Member Data Documentation
FairLink FairTimeStamp::fEntryNr protected inherited
Error on time stamp
Definition at line 104 of file FairTimeStamp.h.
Referenced by FairTimeStamp::GetEntryNr(), FairTimeStamp::Print(), and FairTimeStamp::SetEntryNr().
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
Double_t FairTimeStamp::fTimeStamp protected inherited
Definition at line 102 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStamp(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStamp().
Double_t FairTimeStamp::fTimeStampError protected inherited
Time of digit or Hit [ns]
Definition at line 103 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStampError(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStampError().
Int_t FairMultiLinkedData_Interface::fVerbose protected inherited
Definition at line 78 of file FairMultiLinkedData_Interface.h.
Int_t FairTestDetectorDigi::fX private
Definition at line 158 of file Tutorial3/data/FairTestDetectorDigi.h.
Referenced by equal(), GetX(), operator<(), serialize(), and SetX().
Int_t FairTestDetectorDigi::fY private
Definition at line 159 of file Tutorial3/data/FairTestDetectorDigi.h.
Referenced by equal(), GetY(), operator<(), serialize(), and SetY().
Int_t FairTestDetectorDigi::fZ private
Definition at line 160 of file Tutorial3/data/FairTestDetectorDigi.h.
Referenced by equal(), GetZ(), operator<(), serialize(), and SetZ().
The documentation for this class was generated from the following files:
Tutorial3/data/FairTestDetectorDigi.h
Tutorial3/data/FairTestDetectorDigi.cxx