FairRoot: FairRootManager Class Reference
FairRootManager Class Reference
#include <FairRootManager.h>
Public Member Functions
FairRootManager ()
virtual ~FairRootManager ()
void AddSignalFile (TString name, UInt_t identifier)
void AddBackgroundFile (TString name)
Bool_t AllDataProcessed ()
Int_t AddBranchToList (const char *name)
Int_t CheckBranch (const char *BrName)
void CloseOutFile ()
void CreateGeometryFile (const char *geofile)
Bool_t DataContainersEmpty ()
Bool_t DataContainersFilled ()
void Fill ()
void ForceFill ()
void LastFill ()
TClonesArray * ForceGetDataContainer (TString branchName)
TClonesArray * GetEmptyTClonesArray (TString branchName)
TClonesArray * GetTClonesArray (TString branchName)
TClonesArray * GetDataContainer (TString branchName)
TString GetBranchName (Int_t id)
Int_t GetBranchId (TString BrName)
TList * GetBranchNameList ()
TChain * GetBGChain ()
TChain * GetSignalChainNo (UInt_t i)
TTree * GetOutTree ()
TFile * GetOutFile ()
TObject * GetObject (const char *BrName)
TObject * GetObjectFromInTree (const char *BrName)
Double_t GetEventTime ()
TObject * GetCloneOfLinkData (const FairLink link)
TClonesArray * GetCloneOfTClonesArray (const FairLink link)
TClonesArray * GetData (TString branchName, BinaryFunctor *function, Double_t parameter)
TClonesArray * GetData (TString branchName, BinaryFunctor *startFunction, Double_t startParameter, BinaryFunctor *stopFunction, Double_t stopParameter)
void RegisterTSBuffer (TString branchName, FairTSBufferFunctional *functionalBuffer)
FairTSBufferFunctional * GetTSBuffer (TString branchName)
Bool_t OpenBackgroundChain ()
Bool_t OpenSignalChain ()
TFile * OpenOutFile (const char *fname="cbmsim.root")
TFile * OpenOutFile (TFile *f)
void ReadBKEvent (Int_t i)
void ReadEvent (Int_t i)
void ReadBranchEvent (const char *BrName)
Bool_t ReadNextEvent (Double_t dt)
void Register (const char *name, const char *Foldername, TNamed *obj, Bool_t toFile)
void Register (const char *name, const char *Foldername, TCollection *obj, Bool_t toFile)
TClonesArray * Register (TString branchName, TString className, TString folderName, Bool_t toFile)
FairWriteoutBuffer * RegisterWriteoutBuffer (TString branchName, FairWriteoutBuffer *buffer)
void RunWithTimeStamps ()
void SetSignalFile (TString name, UInt_t identifier)
void SetBackgroundFile (TString name)
void SetEvtHeaderNew (Bool_t Status)
Bool_t IsEvtHeaderNew ()
void SetBranchNameList (TList *list)
void SetCompressData (Bool_t val)
void SetInputFile (TString name)
void SetOutTree (TTree *fTree)
void SetLastFill (Bool_t val=kTRUE)
void TruncateBranchNames (TBranch *b, TString ffn)
void TruncateBranchNames (TTree *fTree, const char *folderName)
Int_t Write (const char *name=0, Int_t option=0, Int_t bufsize=0)
void WriteGeometry ()
void WriteFileHeader (FairFileHeader *f)
void WriteFolder ()
void SetEventTimeInterval (Double_t min, Double_t max)
void SetEventMeanTime (Double_t mean)
void SetBeamTime (Double_t beamTime, Double_t gapTime)
void SetEventTime ()
Double_t GetDeltaEventTime ()
void SetFileHeader (FairFileHeader *f)
void BGWindowWidthNo (UInt_t background, UInt_t Signalid)
void BGWindowWidthTime (Double_t background, UInt_t Signalid)
Int_t CheckMaxEventNo (Int_t EvtEnd=0)
void StoreWriteoutBufferData (Double_t eventTime)
void StoreAllWriteoutBufferData ()
void DeleteOldWriteoutBufferData ()
Int_t GetEntryNr ()
void SetEntryNr (Int_t val)
void SetUseFairLinks (Bool_t val)
Bool_t GetUseFairLinks () const
void SetMixAllInputs (Bool_t Status)
const TFile * GetRootFile ()
void AddFriend (TString FileName)
void AddFile (TString FileName)
void PrintFriendList ()
Bool_t CompareBranchList (TFile *fileHandle, TString inputLevel)
void CheckFriendChains ()
void CreateNewFriendChain (TString inputFile, TString inputLevel)
Bool_t InitSource ()
TTree * GetInTree ()
TChain * GetInChain ()
TFile * GetInFile ()
void CloseInFile ()
void SetInTree (TTree *tempTree)
Static Public Member Functions
static FairRootManager * Instance ()
Private Member Functions
FairRootManager (const FairRootManager &)
FairRootManager & operator= (const FairRootManager &)
TObject * ActivateBranch (const char *BrName)
TObject * ActivateBranchInInTree (const char *BrName)
void AddFriends ()
void AddMemoryBranch (const char *, TObject *)
void AssignTClonesArrays ()
void AssignTClonesArray (TString branchName)
Int_t CheckBranchSt (const char *BrName)
void CreatePerMap ()
TObject * GetMemoryBranch (const char *)
void SaveAllContainers ()
void ReadMixedEvent (Int_t i)
FairWriteoutBuffer * GetWriteoutBuffer (TString branchName)
Private Attributes
Int_t fOldEntryNr
TFolder * fCbmout
TFolder * fCbmroot
Double_t fCurrentTime
TFile * fOutFile
TTree * fOutTree
TObject ** fObj2
Int_t fNObj
std::map< TString, TObject * > fMap
TTree * fPtrTree
Int_t fCurrentEntries
Int_t fBranchSeqId
TList * fBranchNameList
std::map< TString, std::queue< TClonesArray * > > fDataContainer
std::map< TString, TClonesArray * > fActiveContainer
std::map< TString, FairTSBufferFunctional * > fTSBufferMap
std::map< TString, FairWriteoutBuffer * > fWriteoutBufferMap
std::map< Int_t, TBranch * > fInputBranchMap
Bool_t fCompressData
//Map of input branch ID with TBranch pointer
Bool_t fTimeStamps
Bool_t fBranchPerMap
std::map< TString, Int_t > fBrPerMap
std::map< TString, Int_t >::iterator fBrPerMapIter
std::list< TString > fFriendFileList
Bool_t fMixAllInputs
Bool_t fMixedInput
UInt_t fActualSignalIdentifier
UInt_t fNoOfSignals
std::list< TString > * fSignalChainList
TChain * fBackgroundChain
TFile * fBackgroundFile
std::map< UInt_t, FairFileSource * > fSignalTypeList
Double_t fEventTimeMin
Double_t fEventTimeMax
Double_t fEventTime
Double_t fBeamTime
Double_t fGapTime
Double_t fEventMeanTime
TF1 * fTimeProb
FairMCEventHeader * fMCHeader
FairEventHeader * fEvtHeader
FairFileHeader * fFileHeader
std::map< UInt_t, Double_t > fSignalBGN
Bool_t fEventTimeInMCHeader
Bool_t fSBRatiobyN
Bool_t fSBRatiobyT
UInt_t fCurrentEntryNo
UInt_t fTimeforEntryNo
UInt_t fNoOfBGEntries
std::map< UInt_t, UInt_t > fCurrentEntry
Bool_t fEvtHeaderIsNew
Bool_t fFillLastData
Int_t fEntryNr
FairFileSource * fRootFileSource
FairFileSource * fRootFileSourceSignal
FairFileSource * fRootFileSourceBKG
Bool_t fUseFairLinks
Static Private Attributes
static TMCThreadLocal FairRootManager * fgInstance = 0
Detailed Description
I/O Manager class
Author
M. Al-Turany, Denis Bertini
Version
0.1
Since
12.01.04
Definition at line 53 of file FairRootManager.h.
Constructor & Destructor Documentation
FairRootManager::FairRootManager ()
ctor
Definition at line 77 of file FairRootManager.cxx.
References fgInstance.
   : TObject(),
     fOldEntryNr(-1),
     fCbmout(0),
     fCbmroot(0),
     fCurrentTime(0),
     fOutFile(NULL),
     fOutTree(NULL),
     fObj2(new TObject*[1000]),
     fNObj(-1),
     fMap(),
     fPtrTree(NULL),
     fCurrentEntries(0),
     fBranchSeqId(0),
     fBranchNameList(new TList()),
     fDataContainer(),
     fActiveContainer(),
     fTSBufferMap(),
     fWriteoutBufferMap(),
     fInputBranchMap(),
     fCompressData(kFALSE),
     fTimeStamps(kFALSE),
     fBranchPerMap(kFALSE),
     fBrPerMap(),
     fBrPerMapIter(),
     fFriendFileList(),
     fMixAllInputs(kFALSE),
     fMixedInput(kFALSE),
     fActualSignalIdentifier(0),
     fNoOfSignals(0),
     fSignalChainList(NULL),
     fBackgroundChain(NULL),
     fBackgroundFile(NULL),
     fSignalTypeList(),
     fEventTimeMin(0.),
     fEventTimeMax(0.),
     fEventTime(0.),
     fEventMeanTime(0.),
     fBeamTime(-1.),
     fGapTime(-1.),
     fTimeProb(0),
     fMCHeader(0),
     fEvtHeader(0),
     fFileHeader(0),
     fSignalBGN(),
     fEventTimeInMCHeader(kTRUE),
     fSBRatiobyN(kFALSE),
     fSBRatiobyT(kFALSE),
     fCurrentEntryNo(0),
     fTimeforEntryNo(0),
     fNoOfBGEntries(0),
     fCurrentEntry(),
     fEvtHeaderIsNew(kFALSE),
     fFillLastData(kFALSE),
     fUseFairLinks(kFALSE),
     fEntryNr(0),
     fRootFileSource(0),
     fRootFileSourceSignal(0),
     fRootFileSourceBKG(0)
 {
   if (fgInstance) {
     Fatal("FairRootManager", "Singleton instance already exists.");
     return;
   }
   fgInstance = this;
 }
FairRootManager::~FairRootManager () virtual
dtor
Definition at line 146 of file FairRootManager.cxx.
References DEBUG, FairLogger::endl(), fBranchNameList, fgInstance, fObj2, fOutFile, fOutTree, and LOG.
 {
 //
   LOG(DEBUG) << "Enter Destructor of FairRootManager" << FairLogger::endl;
   if(fOutTree) {
     delete fOutTree;
   }
   if(fOutFile) {
     fOutFile->cd();
     delete fOutFile;
   }
   //  fObj2->Delete();
   delete fObj2;
 // if(fPtrTree)delete fPtrTree;
   fBranchNameList->Delete();
   delete fBranchNameList;
   fgInstance = 0;
   LOG(DEBUG) << "Leave Destructor of FairRootManager" << FairLogger::endl;
 }
FairRootManager::FairRootManager (const FairRootManager &) private
private methods
Member Function Documentation
TObject * FairRootManager::ActivateBranch (const char * BrName) private
Set the branch address for a given branch name and return a TObject pointer, the user have to cast this pointer to the right type.
Private functions
Set the branch address for a given branch name and return a TObject pointer, the user have to cast this pointer to the right type. The function has been revisited ! Now it test if in the task init() mutilple calls to activate branch is done , and then just forward the pointer. <DB>
try to find the object decribing the branch in the folder structure in file
if we do not find an object corresponding to the branch in the folder structure then we have no idea about what type of object is this and we cannot set the branch address
All branches has the same types in background and signal chains, thus we can set the branch address to al of them with one TClonesarray and then we call the proper fill in the read (event) entry
Definition at line 1293 of file FairRootManager.cxx.
References AddMemoryBranch(), DEBUG, DEBUG2, FairLogger::endl(), fMixedInput, fNObj, fObj2, fRootFileSource, fRootFileSourceBKG, fSignalTypeList, FairFileSource::GetInChain(), FairFileSource::GetListOfFolders(), GetMemoryBranch(), INFO, and LOG.
Referenced by GetObject(), and GetObjectFromInTree().
 {
   TObjArray *fListFolder;
   if(fRootFileSource) {
       fListFolder = fRootFileSource->GetListOfFolders();
   } else if (fRootFileSourceBKG) {
       fListFolder = fRootFileSourceBKG->GetListOfFolders();
   } else {
     return NULL;
   }
   fNObj++;
   fObj2[fNObj]  =  GetMemoryBranch ( BrName );
   if ( fObj2[fNObj]   ) {
     return  fObj2[fNObj];
   }
   LOG(DEBUG) << "Try to find an object "
               << BrName << " describing the branch in the folder structure in file"
               << FairLogger::endl;
   for(Int_t i=0; i<fListFolder->GetEntriesFast(); i++) {
     TFolder* fold = (TFolder*) fListFolder->At(i);
     fObj2[fNObj] = fold->FindObjectAny(BrName);
     if (fObj2[fNObj] ) {
       LOG(DEBUG) << "Object "
                  << BrName << " describing the branch in the folder structure was found" << FairLogger::endl;
       break;
     }
   }
   if(!fObj2[fNObj]) {
     LOG(INFO) << " Branch: " << BrName << " not found in Tree."
               << FairLogger::endl;
     //Fatal(" No Branch in the tree", BrName );
     return 0;
   } else {
     if(fMixedInput) {
       LOG(DEBUG2) << "Set the Branch address for background branch "
                   << BrName << FairLogger::endl;
       fRootFileSourceBKG->GetInChain()->SetBranchStatus(BrName,1);
       fRootFileSourceBKG->GetInChain()->SetBranchAddress(BrName,&fObj2[fNObj]);
       std::map<UInt_t, FairFileSource*>::const_iterator iter;
       Int_t no=0;
       for(iter = fSignalTypeList.begin(); iter != fSignalTypeList.end(); iter++) {
         LOG(DEBUG2) << "Set the Branch address for signal file number "
                     << no++ << " and branch " << BrName
                     <<FairLogger::endl;
         FairFileSource *signal=iter->second;
         cout << "------------------------------" << signal<< endl;
         TChain* currentChain=signal->GetInChain();
         currentChain->SetBranchStatus(BrName,1);
         currentChain->SetBranchAddress(BrName,&fObj2[fNObj]);
       }
     } else {
       if (fRootFileSource) {
         TChain *fInChain=fRootFileSource->GetInChain();
         if (fInChain) {
           fInChain->SetBranchStatus(BrName,1);
           fInChain->SetBranchAddress(BrName,&fObj2[fNObj]);
         } else {
           return NULL;
         }
       } else {
         return NULL;
       }
     }
   }
   AddMemoryBranch( BrName , fObj2[fNObj] );
   return  fObj2[fNObj];
 }
TObject * FairRootManager::ActivateBranchInInTree (const char * BrName) private
if we do not find an object corresponding to the branch in the folder structure then we have no idea about what type of object is this and we cannot set the branch address
Definition at line 1388 of file FairRootManager.cxx.
References AddMemoryBranch(), FairLogger::endl(), fNObj, fObj2, fRootFileSource, FairFileSource::GetInTree(), FairFileSource::GetListOfFolders(), INFO, and LOG.
Referenced by GetObjectFromInTree().
 {
   TTree *fInTree =fRootFileSource->GetInTree();
   TObjArray *fListFolder=fRootFileSource->GetListOfFolders();
   fNObj++;
   for(Int_t i=0; i<fListFolder->GetEntriesFast(); i++) {
     TFolder* fold = (TFolder*) fListFolder->At(i);
     fObj2[fNObj] = fold->FindObjectAny(BrName);
     if (fObj2[fNObj] ) {
       break;
     }
   }
   if(!fObj2[fNObj]) {
     LOG(INFO) << "Branch: " << BrName << " not found in Tree."
               << FairLogger::endl;
     //Fatal(" No Branch in the tree", BrName );
     return 0;
   } else {
     fInTree->SetBranchStatus (BrName,1);
     fInTree->SetBranchAddress(BrName,&fObj2[fNObj]);
   }
   AddMemoryBranch( BrName , fObj2[fNObj] );
   return  fObj2[fNObj];
 }
void FairRootManager::AddBackgroundFile (TString name)
Add input background file by name
Definition at line 240 of file FairRootManager.cxx.
References FairFileSource::AddFile(), FairFileHeader::AddInputFile(), FairLogger::endl(), FATAL, fFileHeader, fRootFileSourceBKG, FairFileSource::GetInChain(), FairFileSource::GetInFile(), INFO, and LOG.
Referenced by FairRunAna::AddBackgroundFile().
 {
   if (name.IsNull() ) {
     LOG(INFO) << "No background file defined." << FairLogger::endl;
   }
   if(fRootFileSourceBKG!=0) {
      fRootFileSourceBKG->AddFile(name.Data());
      TObjArray* fileElements=fRootFileSourceBKG->GetInChain()->GetListOfFiles();
      fFileHeader->AddInputFile(fRootFileSourceBKG->GetInFile(),0, fileElements->GetEntries());
   } else {
     LOG(FATAL) << "Use SetBackGroundFile first, then add files to background"
                << FairLogger::endl;
   }
 }
Int_t FairRootManager::AddBranchToList (const char * name)
Add a branch name to the Branchlist and give it an id
Definition at line 470 of file FairRootManager.cxx.
References fBranchNameList, and fBranchSeqId.
Referenced by FairFileSource::CreateNewFriendChain(), FairFileSource::Init(), and Register().
 {
     if(fBranchNameList->FindObject(name)==0) {
         fBranchNameList->AddLast(new TObjString(name));
         fBranchSeqId++;
     }
     return fBranchSeqId;
 }
void FairRootManager::AddFile (TString FileName) inline
Add ROOT file to input, the file will be chained to already added files
Definition at line 252 of file FairRootManager.h.
References FairFileSource::AddFile(), and fRootFileSource.
Referenced by FairRunAna::AddFile().
 {fRootFileSource->AddFile(FileName);}
void FairRootManager::AddFriend (TString FileName) inline
Add a friend file (input) by name)
Definition at line 250 of file FairRootManager.h.
References FairFileSource::AddFriend(), and fRootFileSource.
Referenced by FairRunAna::AddFriend().
 {fRootFileSource->AddFriend(FileName);}
void FairRootManager::AddFriends () private
void FairRootManager::AddMemoryBranch (const char * fName, TObject * pObj) private
Add a branch to memory, it will not be written to the output files
branch will be available ionly in Memory, will not be written to disk
Definition at line 1423 of file FairRootManager.cxx.
References fMap.
Referenced by ActivateBranch(), ActivateBranchInInTree(), and Register().
 {
   map < TString, TObject*>::iterator p;
   TString BrName=fName;
   p=fMap.find(BrName);
   if(p!=fMap.end()) {
   } else {
     fMap.insert(pair<TString, TObject*> (BrName, pObj));
   }
 }
void FairRootManager::AddSignalFile (TString name, UInt_t identifier)
Definition at line 206 of file FairRootManager.cxx.
References SetSignalFile().
Referenced by FairRunAna::AddSignalFile(), and FairRunAna::SetSignalFile().
 {
   SetSignalFile(name, identifier);
 }
Bool_t FairRootManager::AllDataProcessed ()
Definition at line 678 of file FairRootManager.cxx.
References fTSBufferMap.
Referenced by FairRunAna::RunTSBuffers().
 {
   for(std::map<TString, FairTSBufferFunctional*>::iterator it = fTSBufferMap.begin(); it != fTSBufferMap.end(); it++) {
     if (it->second->AllDataProcessed() == kFALSE && it->second->TimeOut() == kFALSE) {
       return kFALSE;
     }
   }
   return kTRUE;
 }
void FairRootManager::AssignTClonesArray (TString branchName) private
Definition at line 1444 of file FairRootManager.cxx.
References ForceGetDataContainer(), and GetObject().
Referenced by AssignTClonesArrays().
 {
   TClonesArray* output = (TClonesArray*)GetObject(branchName);
   TClonesArray* input = ForceGetDataContainer(branchName);
   output->Clear();
   if (input != 0) {
     output->AbsorbObjects(input, 0, input->GetEntries() - 1);
   }
 }
void FairRootManager::AssignTClonesArrays () private
Definition at line 1437 of file FairRootManager.cxx.
References AssignTClonesArray(), and fDataContainer.
Referenced by Fill(), and SaveAllContainers().
 {
   for(std::map<TString, std::queue<TClonesArray*> >::iterator it = fDataContainer.begin(); it != fDataContainer.end(); it++) {
     AssignTClonesArray(it->first);
   }
 }
void FairRootManager::BGWindowWidthNo (UInt_t background, UInt_t Signalid)
Set the signal to background ratio in event units
Parameters
background : Number of background Events for one signal
Signalid : Signal file Id, used when adding (setting) the signal file
Definition at line 1657 of file FairRootManager.cxx.
References FairLogger::endl(), FATAL, fSBRatiobyN, fSBRatiobyT, fSignalBGN, INFO, and LOG.
Referenced by FairRunAna::BGWindowWidthNo().
 {
   LOG(INFO) << "SetSignal rate for signal "
             << Signalid << " : " << background
             << FairLogger::endl;
   fSBRatiobyN=kTRUE;
   if(fSBRatiobyT) {
     LOG(FATAL) << "Signal rate already set by TIME!!" << FairLogger::endl;
   }
   Double_t value=1.0/background;
   if(background!=0) {
     fSignalBGN[Signalid]=value;
   } else {
     LOG(FATAL) << "Background cannot be Zero when setting the signal rate!!"
                << FairLogger::endl;
   }
 }
void FairRootManager::BGWindowWidthTime (Double_t background, UInt_t Signalid)
Set the signal to background rate in time units
Parameters
background : Time of background Events before one signal
Signalid : Signal file Id, used when adding (setting) the signal file
convert to number of event by dividing by the mean time
Definition at line 1677 of file FairRootManager.cxx.
References FairLogger::endl(), FATAL, fEventMeanTime, fEventTimeInMCHeader, fSBRatiobyN, fSBRatiobyT, fSignalBGN, and LOG.
Referenced by FairRunAna::BGWindowWidthTime().
 {
   fSBRatiobyT=kTRUE;
   if(fSBRatiobyN) {
     LOG(FATAL) << "Signal rate already set by NUMBER!!" << FairLogger::endl;
   }
   if(fEventTimeInMCHeader) {
     LOG(FATAL) << "You have to Set the Event mean time before using SetSignalRateTime!" << FairLogger::endl;
   }
   if(fEventMeanTime==0) {
     LOG(FATAL) << "Event mean time cannot be zero when using signal rate with time"
                << FairLogger::endl;
   }
   Double_t value=fEventMeanTime/background;
   if(background!=0) {
     fSignalBGN[Signalid]=value;
   } else {
     LOG(FATAL) << "Background cannot be Zero when setting the signal rate!!"
                << FairLogger::endl;
   }
 }
Int_t FairRootManager::CheckBranch (const char * BrName)
Check if Branch persistence or not (Memory branch) return value: 1 : Branch is Persistance 2 : Memory Branch 0 : Branch does not exist
The first time this method is called the map is generated and then used
Definition at line 1258 of file FairRootManager.cxx.
References CheckBranchSt(), CreatePerMap(), fBranchPerMap, fBrPerMap, and fBrPerMapIter.
Referenced by FairMultiLinkedData::AddLink(), FairTask::CheckInputPersistance(), FairMultiLinkedData::GetData(), and FairMCMatch::InitStage().
 {
   if(!fBranchPerMap) {
     CreatePerMap();
     return CheckBranchSt(BrName);
   } else {
     fBrPerMapIter=fBrPerMap.find(BrName);
     if(fBrPerMapIter!=fBrPerMap.end()) {
       return fBrPerMapIter->second;
     } else {
       return 0;
     }
   }
 }
Int_t FairRootManager::CheckBranchSt (const char * BrName) private
Internal Check if Branch persistence or not (Memory branch) return value: 1 : Branch is Persistance 2 : Memory Branch 0 : Branch does not exist
1 : Branch is Persistance 2 : Memory Branch 0 : Branch does not exist
Definition at line 1454 of file FairRootManager.cxx.
References fCbmout, fCbmroot, fRootFileSource, FairFileSource::GetListOfFolders(), and GetMemoryBranch().
Referenced by CheckBranch(), and CreatePerMap().
 {
  // cout <<"FairRootManager::CheckBranchSt  :  " << BrName << endl;
   Int_t returnvalue=0;
   TObject* Obj1 =NULL;
   TObjArray *fListFolder=0;
   if(fRootFileSource!=0){
     fListFolder=fRootFileSource->GetListOfFolders();
   }else{
     fListFolder = new TObjArray(16);
   }
   //cout <<"FairRootManager::CheckBranchSt  :  " <<fCbmroot << endl;
   if (fCbmroot) {
     fListFolder->Add(fCbmroot);
     Obj1 = fCbmroot->FindObjectAny(BrName);
   }
   if(fCbmout && !Obj1) {
     fListFolder->Add(fCbmout);
     Obj1 = fCbmout->FindObjectAny(BrName);  //Branch in output folder
   }
   if(!Obj1) {
     for(Int_t i=0; i<fListFolder->GetEntriesFast(); i++) {
      // cout << "Search in Folder: " << i << "  " <<  fListFolder->At(i) << endl;
       TFolder* fold = dynamic_cast<TFolder*> (fListFolder->At(i));
       if(fold!=0) {
         Obj1= fold->FindObjectAny(BrName);
       }
       if (Obj1) {
         break;
       }
     }
   }
   TObject* Obj2 =NULL;
   Obj2=GetMemoryBranch(BrName);  // Branch in Memory
   if (Obj1!=0) {
     returnvalue=1;
   } else if(Obj2!=0) {
     returnvalue=2;
   } else {
     returnvalue= 0;
   }
   return returnvalue;
 }
void FairRootManager::CheckFriendChains () inline
Definition at line 255 of file FairRootManager.h.
References FairFileSource::CheckFriendChains(), and fRootFileSource.
 {fRootFileSource->CheckFriendChains();}
Int_t FairRootManager::CheckMaxEventNo (Int_t EvtEnd = 0)
Check the maximum event number we can run to
Definition at line 1703 of file FairRootManager.cxx.
References FairLogger::endl(), fMixedInput, fRootFileSource, fRootFileSourceBKG, fSignalBGN, fSignalTypeList, FairFileSource::GetInChain(), INFO, LOG, and WARNING.
Referenced by FairRunAna::RunMixed().
 {
   LOG(INFO) << "Maximum No of Event was set manually to :  "
             << EvtEnd << ", we will check if there is enough entries for this!! "
             << FairLogger::endl;
   Int_t MaxEventNo=0;
   if(EvtEnd!=0) {
     MaxEventNo=EvtEnd;
   }
   Int_t localMax=0;
   if(!fMixedInput) {
     TChain *fInChain =fRootFileSource->GetInChain();
     MaxEventNo=fInChain->GetEntries();
   } else {
     Int_t MaxBG=fRootFileSourceBKG->GetInChain()->GetEntries();
     Int_t MaxS=0;
     Double_t ratio=0.;
     std::map<UInt_t, Double_t>::const_iterator iterN;
     for(iterN = fSignalBGN.begin(); iterN != fSignalBGN.end(); iterN++) {
       TChain* chain = fSignalTypeList[iterN->first]->GetInChain();
       MaxS=chain->GetEntries();
       LOG(INFO) << "Signal chain No "
                 << iterN->first << " has: " <<  MaxS << FairLogger::endl;
       ratio=iterN->second;
      // cout<< " ratio = "<< ratio <<  "floor(MaxS/ratio) "<<floor(MaxS/ratio) << "  MaxBG = " << MaxBG  << endl;
       if(floor(MaxS/ratio) > MaxBG) {
         localMax=MaxBG+(Int_t)floor(MaxBG*ratio);
         LOG(WARNING) << "No of Event in Background chain is not enough for all signals in chain " << iterN->first << FairLogger::endl;
       } else {
         localMax=(Int_t)floor(MaxS/ratio);
         LOG(WARNING) << "No of Event in signal chain "
                      << iterN->first << " is not enough, the maximum event number will be reduced to: " << localMax << FairLogger::endl;
       }
       if(MaxEventNo==0 || MaxEventNo > localMax) {
         MaxEventNo=localMax;
       }
     }
     LOG(INFO) << "Maximum No of Event will be set to: " << MaxEventNo
               << FairLogger::endl;
   }
   return MaxEventNo;
 }
void FairRootManager::CloseInFile () inline
Definition at line 263 of file FairRootManager.h.
References FairFileSource::CloseInFile(), and fRootFileSource.
 {fRootFileSource->CloseInFile(); }
void FairRootManager::CloseOutFile () inline
Definition at line 75 of file FairRootManager.h.
References fOutFile.
Referenced by FairRunOnline::Finish(), OpenOutFile(), FairRunAnaProof::RunOnProof(), FairMCApplication::StopRun(), and FairRunAna::TerminateRun().
 { if(fOutFile) { fOutFile->Close(); }}
Bool_t FairRootManager::CompareBranchList (TFile * fileHandle, TString inputLevel) inline
Definition at line 254 of file FairRootManager.h.
References FairFileSource::CompareBranchList(), and fRootFileSource.
Referenced by OpenSignalChain().
 {return fRootFileSource->CompareBranchList(fileHandle, inputLevel);}
void FairRootManager::CreateGeometryFile (const char * geofile)
Create a new file and save the current TGeoManager object to it
Writes the geometry in a separate file. This is only to have a file which can be read without the framework. The geomanager used by the framework is still stored in the parameter file or database
Definition at line 762 of file FairRootManager.cxx.
Referenced by FairRun::CreateGeometryFile().
 {
   TFile* oldfile=gFile;
   TFile* file=new TFile(geofile,"RECREATE");
   file->cd();
   gGeoManager->Write();
   file->Close();
   file->Delete();
   gFile=oldfile;
 }
void FairRootManager::CreateNewFriendChain (TString inputFile, TString inputLevel) inline
Definition at line 256 of file FairRootManager.h.
References FairFileSource::CreateNewFriendChain(), and fRootFileSource.
 {fRootFileSource->CreateNewFriendChain(inputFile, inputLevel);}
void FairRootManager::CreatePerMap () private
Create the Map for the branch persistency status
Definition at line 1507 of file FairRootManager.cxx.
References CheckBranchSt(), fBranchNameList, fBranchPerMap, fBranchSeqId, and fBrPerMap.
Referenced by CheckBranch().
 {
 //   cout << " FairRootManager::CreatePerMap() " << endl;
   fBranchPerMap=kTRUE;
   for (Int_t i=0; i<fBranchSeqId; i++) {
     TObjString* name= (TObjString*)(fBranchNameList->At(i));
 //    cout << " FairRootManager::CreatePerMap() Obj At " << i << "  is "  << name->GetString() << endl;
     TString BrName=name->GetString();
     fBrPerMap.insert(pair<TString, Int_t> (BrName, CheckBranchSt(BrName.Data())));
   }
 }
Bool_t FairRootManager::DataContainersEmpty ()
Definition at line 362 of file FairRootManager.cxx.
References fDataContainer.
Referenced by SaveAllContainers().
 {
   for(std::map<TString, std::queue<TClonesArray*> >::iterator it = fDataContainer.begin(); it != fDataContainer.end(); it++) {
     if (it->second.empty() == false) {
       return kFALSE;
     }
   }
   return kTRUE;
 }
Bool_t FairRootManager::DataContainersFilled ()
Definition at line 374 of file FairRootManager.cxx.
References fDataContainer.
Referenced by Fill(), and GetDataContainer().
 {
   for(std::map<TString, std::queue<TClonesArray*> >::iterator it = fDataContainer.begin(); it != fDataContainer.end(); it++) {
     if (it->second.empty() == true) {
       return kFALSE;
     }
   }
   return kTRUE;
 }
void FairRootManager::DeleteOldWriteoutBufferData ()
Definition at line 1798 of file FairRootManager.cxx.
References fWriteoutBufferMap.
Referenced by FairRunOnline::EventLoop(), FairRunAna::Run(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   for(std::map<TString, FairWriteoutBuffer*>::const_iterator iter = fWriteoutBufferMap.begin(); iter != fWriteoutBufferMap.end(); iter++) {
     iter->second->DeleteOldData();
   }
 }
void FairRootManager::Fill ()
Definition at line 690 of file FairRootManager.cxx.
References AssignTClonesArrays(), DataContainersFilled(), fCompressData, and ForceFill().
Referenced by FairEventBuilderManager::CreateAndFillEvent(), FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), LastFill(), FairRunAna::Run(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), and FairRunAna::RunTSBuffers().
 {
 // Fills the tree.
 // ---
   if (fCompressData) {
     if (DataContainersFilled()) {
       AssignTClonesArrays();
       ForceFill();
     }
   } else {
     ForceFill();
   }
 }
void FairRootManager::ForceFill ()
Definition at line 706 of file FairRootManager.cxx.
References FairLogger::endl(), fOutTree, INFO, and LOG.
Referenced by Fill(), and SaveAllContainers().
 {
   if (fOutTree != 0) {
     fOutTree->Fill();
   } else {
     LOG(INFO) << " No Output Tree" << FairLogger::endl;
   }
 }
TClonesArray * FairRootManager::ForceGetDataContainer (TString branchName)
Definition at line 609 of file FairRootManager.cxx.
References fDataContainer.
Referenced by AssignTClonesArray().
 {
   TClonesArray* result = 0;
   if (fDataContainer.find(branchName)!= fDataContainer.end()) {
     if (!fDataContainer[branchName].empty()) {
       result = fDataContainer[branchName].front();
       fDataContainer[branchName].pop();
     }
   }
   return result;
 }
TChain* FairRootManager::GetBGChain () inline
Definition at line 94 of file FairRootManager.h.
References fBackgroundChain.
Referenced by GetCloneOfLinkData(), and GetCloneOfTClonesArray().
 { return  fBackgroundChain;}
Int_t FairRootManager::GetBranchId (TString BrName)
Return Id of a branch named
Return the branch id from the name
Definition at line 637 of file FairRootManager.cxx.
References fBranchNameList.
Referenced by FairMultiLinkedData::AddLink(), FairMCMatch::CreateArtificialStage(), FairMCDataCrawler::GetInfo(), FairMCMatch::GetMCInfo(), FairMCMatch::GetMCInfoSingle(), FairMCMatch::GetMCStageType(), FairMCDataCrawler::GetNextStage(), FairMCMatchSelectorTask::Init(), FairMCMatch::InitStage(), FairMultiLinkedData::InsertHistory(), and Register().
 {
   TObjString* ObjStr;
   Int_t Id=-1;
   for(Int_t t=0; t<fBranchNameList->GetEntries(); t++) {
     ObjStr= (TObjString*) fBranchNameList->At(t);
     if(BrName==ObjStr->GetString()) {
       Id=t;
       break;
     }
   }
   return Id;
 }
TString FairRootManager::GetBranchName (Int_t id)
Return branch name by Id
Return the branch name from the id
Definition at line 623 of file FairRootManager.cxx.
References fBranchNameList, and fBranchSeqId.
Referenced by FairMultiLinkedData::AddLink(), GetCloneOfLinkData(), GetCloneOfTClonesArray(), FairMultiLinkedData::GetData(), FairMCDataCrawler::GetInfo(), and FairMultiLinkedData::InsertHistory().
 {
   if(id < fBranchSeqId) {
     TObjString* ObjStr= (TObjString*) fBranchNameList->At(id);
     return ObjStr->GetString();
   } else {
     TString NotFound("Branch not found");
     return NotFound;
   }
 }
TList* FairRootManager::GetBranchNameList () inline
Return a TList of TObjString of branch names
Definition at line 92 of file FairRootManager.h.
References fBranchNameList.
 {return fBranchNameList;}
TObject * FairRootManager::GetCloneOfLinkData (const FairLink link)
Returns a clone of the data object the link is pointing to. The clone has to be deleted in the calling code!
Definition at line 988 of file FairRootManager.cxx.
References fInputBranchMap, GetBGChain(), GetBranchName(), FairLink::GetEntry(), GetEntryNr(), FairLink::GetFile(), FairLink::GetIndex(), GetInTree(), GetObject(), GetSignalChainNo(), and FairLink::GetType().
Referenced by FairMCDataCrawler::GetEntry().
 {
   TObject* result = 0;
 //  std::cout << "GetCloneOfLinkData: Link " << link << std::endl;
   Int_t fileId = link.GetFile();
   Int_t entryNr = link.GetEntry();
   Int_t type = link.GetType();
   Int_t index = link.GetIndex();
   Int_t oldEntryNr = GetEntryNr();
 //  std::cout << "OldEntryNr: " << GetEntryNr();
 //  std::cout << "GetLinkData: " << link << std::endl;
   TTree* dataTree;          //get the correct Tree
   if (fileId < 0) {
     dataTree = GetInTree();
   } else if (fileId == 0) {
     dataTree = GetBGChain();
   } else {
     dataTree = GetSignalChainNo(fileId);
   }
   if (dataTree == 0) {
     dataTree = GetInTree();
   }
   if (type < 0) {
     return 0;
   }
   TBranch* dataBranch = 0;
 //  std::cout << "DataType: " << GetBranchName(type) << std::endl;
   if (fileId < 0 && fInputBranchMap[type] != 0) {
     dataBranch = fInputBranchMap[type];
   } else if (fileId < 0) {
     fInputBranchMap[type] = dataTree->GetBranch(GetBranchName(type));
     dataBranch = fInputBranchMap[type];
   } else {
     dataBranch = dataTree->GetBranch(GetBranchName(type));
   }
   if (dataBranch == 0) {
     return 0;
   }
   if (entryNr > -1) {         //get the right entry (if entryNr < 0 then the current entry is taken
     if (entryNr < dataBranch->GetEntries()) {
       dataBranch->GetEntry(entryNr);
     } else {
       return 0;
     }
   } else {        //the link entry nr is negative --> take the actual one
 //    std::cout << "EntryNr: " << GetEntryNr() << std::endl;
 //    dataBranch->GetEntry(GetEntryNr());
   }
   if (index < 0) {                //if index is -1 then this is not a TClonesArray so only the Object is returned
     result = GetObject(GetBranchName(type))->Clone();
   } else {
     TClonesArray* dataArray = (TClonesArray*)GetObject(GetBranchName(type));
 //    std::cout << "dataArray size: " << dataArray->GetEntriesFast() << std::endl;
     if (index < dataArray->GetEntriesFast()) {
 //      std::cout << "DataArray at index " << index << " has Link: " << ((FairMultiLinkedData*)dataArray->At(index))->GetNLinks() << std::cout;
       result = dataArray->At(index)->Clone();
 //      std::cout << "Result: " << *((FairMultiLinkedData*)result) << std::endl;
     }
   }
   if (entryNr > -1) {
     dataBranch->GetEntry(oldEntryNr);  //reset the dataBranch to the original entry
   }
   return result;
 }
TClonesArray * FairRootManager::GetCloneOfTClonesArray (const FairLink link)
Get the data of the given branch name, this method runs over multiple entries of the tree and selects the data according to the function and the parameter given.
Definition at line 1070 of file FairRootManager.cxx.
References fInputBranchMap, GetBGChain(), GetBranchName(), FairLink::GetEntry(), GetEntryNr(), FairLink::GetFile(), FairLink::GetIndex(), GetInTree(), GetObject(), GetSignalChainNo(), and FairLink::GetType().
 {
   TClonesArray* result = 0;
   //  std::cout << "GetCloneOfLinkData: Link " << link << std::endl;
   Int_t fileId = link.GetFile();
   Int_t entryNr = link.GetEntry();
   Int_t type = link.GetType();
   Int_t index = link.GetIndex();
   Int_t oldEntryNr = GetEntryNr();
   //  std::cout << "OldEntryNr: " << GetEntryNr();
   //  std::cout << "GetLinkData: " << link << std::endl;
   TTree* dataTree;          //get the correct Tree
   if (fileId < 0) {
     dataTree = GetInTree();
   } else if (fileId == 0) {
     dataTree = GetBGChain();
   } else {
     dataTree = GetSignalChainNo(fileId);
   }
   if (dataTree == 0) {
     dataTree = GetInTree();
   }
   if (type < 0) {
     return 0;
   }
   TBranch* dataBranch = 0;
   //  std::cout << "DataType: " << GetBranchName(type) << std::endl;
   if (fileId < 0 && fInputBranchMap[type] != 0) {
     dataBranch = fInputBranchMap[type];
   } else if (fileId < 0) {
     fInputBranchMap[type] = dataTree->GetBranch(GetBranchName(type));
     dataBranch = fInputBranchMap[type];
   } else {
     dataBranch = dataTree->GetBranch(GetBranchName(type));
   }
   if (dataBranch == 0) {
     return 0;
   }
   if (entryNr > -1) { //get the right entry (if entryNr < 0 then the current entry is taken
     if (entryNr < dataBranch->GetEntries()) {
       dataBranch->GetEntry(entryNr);
     } else {
       return 0;
     }
   } else {        //the link entry nr is negative --> take the actual one
     //    std::cout << "EntryNr: " << GetEntryNr() << std::endl;
     //    dataBranch->GetEntry(GetEntryNr());
   }
   if (index < 0) { //if index is -1 then this is not a TClonesArray so only the Object is returned
     result = 0;
   } else {
     result = (TClonesArray*) GetObject(GetBranchName(type))->Clone();
   }
   if (entryNr > -1) {
     dataBranch->GetEntry(oldEntryNr); //reset the dataBranch to the original entry
   }
   return result;
 }
TClonesArray * FairRootManager::GetData (TString branchName, BinaryFunctor * function, Double_t parameter)
Definition at line 655 of file FairRootManager.cxx.
References fTSBufferMap, and GetInTree().
Referenced by FairTestDetectorTimeRecoTask::Exec(), and FairBoxSetDraw::Exec().
 {
   if (fTSBufferMap[branchName] == 0) {
     fTSBufferMap[branchName] = new FairTSBufferFunctional(branchName, GetInTree(), function);
   }
   fTSBufferMap[branchName]->SetStopFunction(function);
   return fTSBufferMap[branchName]->GetData(parameter);
 }
TClonesArray * FairRootManager::GetData (TString branchName, BinaryFunctor * startFunction, Double_t startParameter, BinaryFunctor * stopFunction, Double_t stopParameter)
Definition at line 666 of file FairRootManager.cxx.
References fTSBufferMap, and GetInTree().
 {
   if (fTSBufferMap[branchName] == 0) {
     fTSBufferMap[branchName] = new FairTSBufferFunctional(branchName, GetInTree(), stopFunction, startFunction);
   }
   fTSBufferMap[branchName]->SetStopFunction(stopFunction);
   fTSBufferMap[branchName]->SetStartFunction(startFunction);
   return fTSBufferMap[branchName]->GetData(startParameter, stopParameter);
 }
TClonesArray * FairRootManager::GetDataContainer (TString branchName)
Definition at line 599 of file FairRootManager.cxx.
References DataContainersFilled(), and fDataContainer.
 {
   if (DataContainersFilled()) {
     return fDataContainer[branchName].front();
   }
   return 0;
 }
Double_t FairRootManager::GetDeltaEventTime ()
Definition at line 1640 of file FairRootManager.cxx.
References DEBUG, FairLogger::endl(), fEventTimeMax, fEventTimeMin, fTimeProb, and LOG.
Referenced by SetEventTime().
 {
   Double_t deltaTime = 0;
   if (fTimeProb != 0) {
     deltaTime = fTimeProb->GetRandom();
     LOG(DEBUG) << "Time set via sampling method : " <<  deltaTime
                << FairLogger::endl;
   } else {
     deltaTime = gRandom->Uniform(fEventTimeMin, fEventTimeMax);
     LOG(DEBUG) << "Time set via Uniform Random : "
                << deltaTime << FairLogger::endl;
   }
   return deltaTime;
 }
TClonesArray * FairRootManager::GetEmptyTClonesArray (TString branchName)
Definition at line 549 of file FairRootManager.cxx.
References FairLogger::endl(), fActiveContainer, fCompressData, fDataContainer, INFO, and LOG.
Referenced by FairRingSorterTask::Exec(), and FairRingSorterTask::FinishTask().
 {
   if (fActiveContainer.find(branchName) != fActiveContainer.end()) {          //if a TClonesArray is registered in the active container
     if (fActiveContainer[branchName] == 0) {                      //the address of the TClonesArray is still valid
       std::cout << "-E- FairRootManager::GetEmptyTClonesArray: Container deleted outside FairRootManager!" << std::endl;
     } else if (!fCompressData) {                          //if the data is not compressed the existing TClonesArray is just emptied
       fActiveContainer[branchName]->Delete();
     } else if (fActiveContainer[branchName]->GetEntries() > 0) {    //if the container is not empty push it into the DataContainer storage and create a new one
       fDataContainer[branchName].push(fActiveContainer[branchName]);
       LOG(INFO) << "GetEmptyTClonesArray moved "
                 << branchName.Data() << " with "
                 << fActiveContainer[branchName]->GetEntries()
                 << "to data container." << FairLogger::endl;
       fActiveContainer[branchName] = new TClonesArray(fActiveContainer[branchName]->GetClass()->GetName());
     } else {
       LOG(INFO) << "GetEmptyTClonesArray not moved "
                 << branchName.Data() << " "
                 <<  fActiveContainer[branchName] << " with "
                 << fActiveContainer[branchName]->GetEntries()
                 << " to data container." << FairLogger::endl;
     }
     return fActiveContainer[branchName];                        // return the container
   } else {
     std::cout << "-E- Branch: " << branchName << " not registered!" << std::endl;  // error if the branch is not registered
   }
   return 0;
 }
Int_t FairRootManager::GetEntryNr () inline
Definition at line 232 of file FairRootManager.h.
References fEntryNr.
Referenced by GetCloneOfLinkData(), GetCloneOfTClonesArray(), and FairMultiLinkedData::InsertHistory().
 {return fEntryNr;}
Double_t FairRootManager::GetEventTime ()
Definition at line 1549 of file FairRootManager.cxx.
References DEBUG, FairLogger::endl(), fCurrentEntryNo, fEventTime, fEventTimeInMCHeader, fEvtHeader, fEvtHeaderIsNew, fMCHeader, fTimeforEntryNo, FairEventHeader::GetEventTime(), FairMCEventHeader::GetT(), LOG, and SetEventTime().
Referenced by FairTestDetectorDigiTask::CalcTimeStamp(), FairTestDetectorTimeDigiTask::CalcTimeStamp(), FairRunOnline::EventLoop(), FairTestDetectorTimeDigiTask::Exec(), FairBoxSetDraw::Exec(), ReadEvent(), ReadMixedEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), and FairRunAnaProof::RunOneEvent().
 {
   LOG(DEBUG) << "-- Get Event Time --" << FairLogger::endl;
   if(!fEvtHeaderIsNew && fEvtHeader!=0) {
     Double_t EvtTime=fEvtHeader->GetEventTime();
     if( !(EvtTime<0)) {
       return   EvtTime;
     }
   }
   if (fEventTimeInMCHeader && !fMCHeader) {
     LOG(DEBUG) << "No MCEventHeader, time is set to 0" << FairLogger::endl;
     return 0;
   } else if(fEventTimeInMCHeader && fMCHeader) {
     fEventTime=fMCHeader->GetT();
     LOG(DEBUG) << "Get event time from MCEventHeader : "
                << fEventTime << " ns" << FairLogger::endl;
     return fEventTime;
   } else {
     if(fTimeforEntryNo!=fCurrentEntryNo) {
       SetEventTime();
     }
     LOG(DEBUG) << "Calculate event time from user input : "
                << fEventTime << " ns" << FairLogger::endl;
     return fEventTime;
   }
 }
TChain* FairRootManager::GetInChain () inline
Definition at line 261 of file FairRootManager.h.
References fRootFileSource, and FairFileSource::GetInChain().
Referenced by ClassImp(), FairMCApplication::GetChain(), FairRunAnaProof::Init(), FairRunAna::Init(), FairEventManagerEditor::Init(), FairRunAna::Run(), FairRunAna::RunEventReco(), and FairRunAnaProof::RunOnProof().
 {return fRootFileSource->GetInChain();}
TFile* FairRootManager::GetInFile () inline
Definition at line 262 of file FairRootManager.h.
References fRootFileSource, and FairFileSource::GetInFile().
Referenced by FairRunAnaProof::Init().
 {return  fRootFileSource->GetInFile();}
TTree* FairRootManager::GetInTree () inline
Definition at line 260 of file FairRootManager.h.
References fRootFileSource, and FairFileSource::GetInTree().
Referenced by GetCloneOfLinkData(), GetCloneOfTClonesArray(), GetData(), and FairRunAna::RunTSBuffers().
 {return fRootFileSource->GetInTree();}
TObject * FairRootManager::GetMemoryBranch (const char * fName) private
Definition at line 1522 of file FairRootManager.cxx.
References fMap.
Referenced by ActivateBranch(), CheckBranchSt(), and GetObject().
 {
 //return fMap[BrName];
   TString BrName=fName;
   map < TString, TObject*>::iterator p;
   p=fMap.find(BrName);
   if(p!=fMap.end()) {
     return p->second;
   } else {
     return 0;
   }
 }
TObject * FairRootManager::GetObject (const char * BrName)
Get the Object (container) for the given branch name, this method can be used to access the data of a branch that was created from a different analysis task, and not written in the tree yet. the user have to cast this pointer to the right type. Return a pointer to the object (collection) saved in the fInChain branch named BrName
Get Data object by name
Try to find the object in the folder structure, object already activated by other task or call
if the object does not exist then it could be a memory branch
if the object does not exist then look in the input tree
there is an input tree and the object was not in memory
Definition at line 918 of file FairRootManager.cxx.
References ActivateBranch(), DEBUG2, FairLogger::endl(), fCbmout, fCbmroot, GetMemoryBranch(), and LOG.
Referenced by FairMultiLinkedData::AddLink(), AssignTClonesArray(), FairTSBufferFunctional::FairTSBufferFunctional(), GetCloneOfLinkData(), GetCloneOfTClonesArray(), FairMultiLinkedData::GetData(), GetObjectFromInTree(), FairTestDetectorDigiTask::Init(), FairTestDetectorHitProducerSmearing::Init(), FairTestDetectorTimeDigiTask::Init(), FairTestDetectorRecoTask::Init(), FairTestDetectorTimeRecoTask::Init(), FairRunAnaProof::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTutorialDet4MilleWriter::Init(), FairMQSamplerTask::Init(), FairTutorialDet2Digitizer::Init(), FairMCMatchLoaderTask::Init(), FairRunAna::Init(), FairMCMatchSelectorTask::Init(), FairTutorialDet4HitProducerIdealMisalign::Init(), FairMCTracks::Init(), FairMCStack::Init(), FairPointSetDraw::Init(), FairBoxSetDraw::Init(), FairMCMatchCreatorTask::InitBranches(), FairMultiLinkedData::InsertHistory(), ReadEvent(), and ReadMixedEvent().
 {
   TObject* Obj =NULL;
   LOG(DEBUG2) << " Try to find if the object "
               << BrName << " is already activated by another task or call"
               << FairLogger::endl;
   if(fCbmout) {
     Obj = fCbmout->FindObjectAny(BrName);
     if (Obj) {
       LOG(DEBUG2) <<"Object "
                   << BrName << " was already activated by another task"
                   << FairLogger::endl;
     }
   }
   if(!Obj) {
     LOG(DEBUG2) << "Try to find if the object "
                 << BrName << " is a memory branch" << FairLogger::endl;
     Obj=GetMemoryBranch(BrName);
     if (Obj) {
       LOG(DEBUG2) << "Object "
                   << BrName << " is a memory branch" << FairLogger::endl;
     }
   }
   if(fCbmroot && !Obj) {
     LOG(DEBUG2) << "Object "
                 << BrName << " is not a memory branch and not yet activated, try the Input Tree (Chain)" << FairLogger::endl;
     Obj=fCbmroot->FindObjectAny(BrName);
     Obj=ActivateBranch(BrName);
   }
   if(!Obj) {
     Obj=ActivateBranch(BrName);
   }
   return Obj;
 }
TObject * FairRootManager::GetObjectFromInTree (const char * BrName)
Return a pointer to the object (collection) saved in the fInTree branch named BrName
Get Data object by name
Try to find the object in the folder structure, object already activated by other task or call
if the object does not exist then look in the input tree
there is an input tree and the object was not in memory
Definition at line 960 of file FairRootManager.cxx.
References ActivateBranch(), ActivateBranchInInTree(), DEBUG2, FairLogger::endl(), fCbmroot, fRootFileSource, FairFileSource::GetInTree(), GetObject(), and LOG.
Referenced by FairRunOnline::InitContainers(), and FairRunAna::InitContainers().
 {
    TTree *fInTree =fRootFileSource->GetInTree();
   if ( !fInTree ) {
     return GetObject(BrName);
   }
   TObject* Obj =NULL;
   LOG(DEBUG2) << "Try to find if the object "
               << BrName << " already activated by other task or call"
               << FairLogger::endl;
   if(fCbmroot && !Obj) {
     LOG(DEBUG2) << "Object "
                 << BrName << " is not a memory branch and not yet activated, try the Input Tree (Chain)" << FairLogger::endl;
     Obj=fCbmroot->FindObjectAny(BrName);
     Obj=ActivateBranchInInTree(BrName);
   }
   if(!Obj) {
     Obj=ActivateBranch(BrName);
   }
   return Obj;
 }
TFile* FairRootManager::GetOutFile () inline
Definition at line 97 of file FairRootManager.h.
References fOutFile.
Referenced by FairMCApplication::FinishRun(), FairRunAnaProof::RunOnProof(), and FairRunAna::TerminateRun().
 {return  fOutFile;}
TTree* FairRootManager::GetOutTree () inline
Definition at line 96 of file FairRootManager.h.
References fOutTree.
 {return fOutTree;}
const TFile* FairRootManager::GetRootFile () inline
These methods have been moved to the FairFileSource
Definition at line 248 of file FairRootManager.h.
References fRootFileSource, and FairFileSource::GetRootFile().
 {return fRootFileSource->GetRootFile();}
TChain * FairRootManager::GetSignalChainNo (UInt_t i)
Definition at line 213 of file FairRootManager.cxx.
References FairLogger::endl(), fNoOfSignals, fSignalTypeList, FairFileSource::GetInChain(), INFO, and LOG.
Referenced by GetCloneOfLinkData(), and GetCloneOfTClonesArray().
 {
   if(i<<fNoOfSignals) {
     FairFileSource *fRootFileSourceS=fSignalTypeList[i];
     return fRootFileSourceS->GetInChain();
   } else {
     LOG(INFO) << "Error signal identifier " << i << " does not exist."
               << FairLogger::endl;
     return 0;
   }
 }
TClonesArray * FairRootManager::GetTClonesArray (TString branchName)
if a TClonesArray is registered in the active container
if the container is not empty push it into the DataContainer storage and create a new one
Definition at line 579 of file FairRootManager.cxx.
References FairLogger::endl(), fActiveContainer, fCompressData, fDataContainer, INFO, and LOG.
Referenced by MyWriteoutBuffer::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), FairTestDetectorDigiWriteoutBuffer::AddNewDataToTClonesArray(), FairRingSorterTask::AddNewDataToTClonesArray(), FairWriteoutBuffer::DeleteOldData(), FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairEventBuilder::WriteOutAllDeadTimeData(), FairWriteoutBuffer::WriteOutData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
 {
   if (fActiveContainer.find(branchName) != fActiveContainer.end()) {
     if (fCompressData && fActiveContainer[branchName]->GetEntries() > 0) {
       fDataContainer[branchName].push(fActiveContainer[branchName]);
       fActiveContainer[branchName] = new TClonesArray(fActiveContainer[branchName]->GetClass()->GetName());
     }
     return fActiveContainer[branchName]; // return the container
   } else {
     LOG(INFO) << "Branch: " << branchName.Data()
               << " not registered!" << FairLogger::endl ;
   }
   // error if the branch is not registered
   return 0;
 }
FairTSBufferFunctional* FairRootManager::GetTSBuffer (TString branchName) inline
Definition at line 121 of file FairRootManager.h.
References fTSBufferMap.
 {return fTSBufferMap[branchName];}
Bool_t FairRootManager::GetUseFairLinks () const inline
Definition at line 236 of file FairRootManager.h.
References fUseFairLinks.
 {return fUseFairLinks;};
FairWriteoutBuffer * FairRootManager::GetWriteoutBuffer (TString branchName) private
Definition at line 1764 of file FairRootManager.cxx.
References fWriteoutBufferMap.
 {
   if (fWriteoutBufferMap.count(branchName) > 0) {
     return fWriteoutBufferMap[branchName];
   } else {
     return 0;
   }
 }
Bool_t FairRootManager::InitSource ()
Definition at line 271 of file FairRootManager.cxx.
References FairFileSource::AddFriendsToChain(), fCbmroot, fMixedInput, fRootFileSource, fRootFileSourceBKG, FairFileSource::GetBranchDescriptionFolder(), and FairFileSource::Init().
Referenced by FairRunAnaProof::Init(), and FairRunAna::Init().
{
     Bool_t retBool=kFALSE;
     if(!fMixedInput) {
       retBool = fRootFileSource->Init();
       fCbmroot = fRootFileSource->GetBranchDescriptionFolder();
       fRootFileSource->AddFriendsToChain();
     }else{
       // In the mixed input the source is initialized immediatly when it is added
       // We need only to check that the BK source exist and we can return true.
       if(fRootFileSourceBKG!=0) retBool=kTRUE;
     }
     return retBool;
 }
FairRootManager * FairRootManager::Instance () static
static access method
Definition at line 68 of file FairRootManager.cxx.
References fgInstance.
Referenced by FairMultiLinkedData::AddLink(), MyWriteoutBuffer::AddNewDataToTClonesArray(), FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairTestDetectorDigiWriteoutBuffer::AddNewDataToTClonesArray(), FairRingSorterTask::AddNewDataToTClonesArray(), FairTestDetectorDigiTask::CalcTimeStamp(), FairTestDetectorTimeDigiTask::CalcTimeStamp(), FairTask::CheckInputPersistance(), ClassImp(), FairEventBuilderManager::CreateAndFillEvent(), FairMCMatch::CreateArtificialStage(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairFileSource::CreateNewFriendChain(), FairWriteoutBuffer::DeleteOldData(), FairTestDetectorTimeDigiTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), FairBoxSetDraw::Exec(), FairRingSorterTask::Exec(), FairMCApplication::FairMCApplication(), FairMultiLinkedData::FairMultiLinkedData(), FairTSBufferFunctional::FairTSBufferFunctional(), FairWriteoutBuffer::FairWriteoutBuffer(), FairRingSorterTask::FinishTask(), FairMultiLinkedData::GetData(), FairMCDataCrawler::GetEntry(), FairMCMatch::GetMCInfo(), FairMCMatch::GetMCInfoSingle(), FairMCMatch::GetMCStageType(), FairMCDataCrawler::GetNextStage(), FairTestDetectorDigiTask::Init(), FairTestDetectorHitProducerSmearing::Init(), FairTestDetectorRecoTask::Init(), FairTestDetectorTimeDigiTask::Init(), FairTestDetectorTimeRecoTask::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTutorialDet4MilleWriter::Init(), FairFileSource::Init(), FairMQSamplerTask::Init(), FairMCMatchLoaderTask::Init(), FairTutorialDet2Digitizer::Init(), FairMCMatchCreatorTask::Init(), FairEventManagerEditor::Init(), FairMCMatchSelectorTask::Init(), FairTutorialDet4HitProducerIdealMisalign::Init(), FairMCTracks::Init(), FairMCStack::Init(), FairPointSetDraw::Init(), FairRingSorterTask::Init(), FairBoxSetDraw::Init(), FairRadLenManager::Init(), FairEventBuilderManager::Init(), FairRadMapManager::Init(), FairTrajFilter::Init(), FairMCMatchCreatorTask::InitBranches(), FairMCMatch::InitStage(), FairMultiLinkedData::InsertHistory(), FairTSBufferFunctional::ReadInEntry(), NewDetector::Register(), FairTutorialDet2::Register(), FairTestDetector::Register(), FairTutorialDet1::Register(), FairRutherford::Register(), FairTutorialDet4::Register(), FairEventHeader::Register(), FairMCEventHeader::Register(), MyProjStack::Register(), FairStack::Register(), FairEventManagerEditor::SelectEvent(), FairEventBuilder::WriteOutAllDeadTimeData(), FairWriteoutBuffer::WriteOutData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
 {
 // Returns singleton instance.
 // ---
   return fgInstance;
 }
Bool_t FairRootManager::IsEvtHeaderNew () inline
Definition at line 173 of file FairRootManager.h.
References fEvtHeaderIsNew.
Referenced by FairRunAna::Run(), and FairRunAna::RunEventReco().
 {return fEvtHeaderIsNew;}
void FairRootManager::LastFill ()
Definition at line 717 of file FairRootManager.cxx.
References fFillLastData, and Fill().
Referenced by FairRunOnline::Finish(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if (fFillLastData) {
     Fill();
   }
 }
Bool_t FairRootManager::OpenBackgroundChain ()
Definition at line 289 of file FairRootManager.cxx.
Referenced by FairRunAnaProof::Init().
 {
  /* // Get the folder structure from file which describes the input tree.
   // There are two different names possible, so check both.
   fCbmroot= dynamic_cast <TFolder*> (fBackgroundFile->Get("cbmroot"));
   if(!fCbmroot) {
     fCbmroot= dynamic_cast <TFolder*> (fBackgroundFile->Get("cbmout"));
     if(!fCbmroot) {
       fCbmroot= gROOT->GetRootFolder()->AddFolder("cbmroot", "Main Folder");
     } else {
       fCbmroot->SetName("cbmroot");
     }
   }
   // Get The list of branches from the input file and add it to the
   // actual list of existing branches.
   // Add this list of branches also to the map of input trees, which
   // stores the information which branches belong to which input tree.
   // There is at least one primary input tree, but there can be many
   // additional friend trees.
   // This information is needed to add new files to the correct friend
   // tree. With this information it is also possible to check if the
   // input files which are added to the input chain all have the same
   // branch structure. Without this check it is possible to add trees
   // with a different branch structure but the same tree name. ROOT
   // probably only checks if the name of the tree is the same.
   TList* list= dynamic_cast <TList*> (fBackgroundFile->Get("BranchList"));
   TString chainName = "BGInChain";
   fInputLevel.push_back(chainName);
   fCheckInputBranches[chainName] = new std::list<TString>;
   if(list) {
     TObjString* Obj=0;
     for(Int_t i =0; i< list->GetEntries(); i++) {
       Obj=dynamic_cast <TObjString*> (list->At(i));
       fCheckInputBranches[chainName]->push_back(Obj->GetString().Data());
       if(fBranchNameList->FindObject(Obj->GetString().Data())==0) {
         fBranchNameList->AddLast(Obj);
         fBranchSeqId++;
       }
     }
   }
   gROOT->GetListOfBrowsables()->Add(fCbmroot);
   fListFolder.Add( fCbmroot );
 */
   return kTRUE;
 }
TFile * FairRootManager::OpenOutFile (const char * fname = "cbmsim.root")
Definition at line 411 of file FairRootManager.cxx.
References CloseOutFile(), DEBUG, FairLogger::endl(), fOutFile, INFO, and LOG.
Referenced by FairRun::SetOutputFile().
 {
   LOG(DEBUG) << "Opening output file, " << fname << FairLogger::endl;
   if(fOutFile) {
     CloseOutFile();
   }
   LOG(INFO) << "FairRootManager::OpenOutFile(\"" << fname << "\")" << FairLogger::endl;
   fOutFile = new TFile(fname, "recreate");
   return OpenOutFile(fOutFile);
 }
TFile * FairRootManager::OpenOutFile (TFile * f)
Check the output file, if anything wronge with it exit!
Check if a simulation run!
Definition at line 386 of file FairRootManager.cxx.
References DEBUG, FairLogger::endl(), FATAL, fCbmout, fCbmroot, fOutFile, FairRun::Instance(), FairRun::IsAna(), and LOG.
 {
   LOG(DEBUG) << "Check the output file" << FairLogger::endl;
   fOutFile=f;
   if (fOutFile->IsZombie()) {
     LOG(FATAL) << "FairRootManager: Error opening output file "
                << FairLogger::endl;
     exit(-1);
   }
   FairRun* fRun = FairRun::Instance();
   if(!fRun->IsAna()) {
     fCbmroot= gROOT->GetRootFolder()->AddFolder("cbmroot", "Main Folder");
     gROOT->GetListOfBrowsables()->Add(fCbmroot);
   } else {
     fCbmout= gROOT->GetRootFolder()->AddFolder("cbmout", "Main Output Folder");
     gROOT->GetListOfBrowsables()->Add(fCbmout);
   }
   return fOutFile;
 }
Bool_t FairRootManager::OpenSignalChain ()
Definition at line 340 of file FairRootManager.cxx.
References CompareBranchList(), FairLogger::endl(), FATAL, fSignalTypeList, FairFileSource::GetInChain(), and LOG.
Referenced by FairRunAnaProof::Init().
 {
   std::map<UInt_t, FairFileSource*>::const_iterator iter;
   for(iter = fSignalTypeList.begin(); iter != fSignalTypeList.end(); iter++) {
     FairFileSource *SignalFile=iter->second;
     TChain* currentChain=SignalFile->GetInChain();
     // cout << "Signal chain is : " << currentChain->GetName()<< endl;
     //   currentChain->Dump();
     TFile* ChainFirstFile = currentChain->GetFile();
     //cout << "First file in signal chain is : " << ChainFirstFile << endl;
     // Check if the branchlist is the same as for the first input file.
     Bool_t isOk = CompareBranchList(ChainFirstFile,"BGInChain");
     if ( !isOk ) {
       LOG(FATAL) << "Branch structure of the signal chain is different than the back ground one" << FairLogger::endl;
     }
   }
   return kTRUE;
 }
FairRootManager& FairRootManager::operator= (const FairRootManager &) private
void FairRootManager::PrintFriendList () inline
Definition at line 253 of file FairRootManager.h.
References fRootFileSource, and FairFileSource::PrintFriendList().
 {fRootFileSource->PrintFriendList();}
void FairRootManager::ReadBKEvent (Int_t i)
Read a single entry from background chain
Definition at line 895 of file FairRootManager.cxx.
References FairLogger::endl(), fMixedInput, fRootFileSourceBKG, FairFileSource::GetInChain(), INFO, LOG, and FairFileSource::ReadEvent().
Referenced by FairRunAnaProof::Init(), and FairRunAna::Init().
 {
   if(fMixedInput) {
     if(0==i) {
       Int_t totEnt = fRootFileSourceBKG->GetInChain()->GetEntries();
       LOG(INFO) << "The number of entries in background chain is "
                 << totEnt << FairLogger::endl;
     }
     fRootFileSourceBKG->ReadEvent(i);
   }
 }
void FairRootManager::ReadBranchEvent (const char * BrName)
Read the tree entry on one branch
fill the object with content if the other branches in this tree entry were already read
Definition at line 1807 of file FairRootManager.cxx.
References fEntryNr, fEvtHeader, fMixedInput, fRootFileSource, fSignalTypeList, FairFileSource::GetInChain(), FairEventHeader::GetInputFileId(), FairFileSource::GetInTree(), and FairEventHeader::GetMCEntryNumber().
 {
     TTree *fInTree =fRootFileSource->GetInTree();
     TChain *fInChain =fRootFileSource->GetInChain();
   if(fEvtHeader == 0) { return; } //No event header, Reading will start later
   if ( fInTree ) {
     fInTree->FindBranch(BrName)->GetEntry(fEntryNr);
     return;
   }
   if(!fMixedInput) {
     if(!fInChain) { return; }
     fInChain->FindBranch(BrName)->GetEntry(fEntryNr);
     return;
   } else {
     TChain* chain = fSignalTypeList[fEvtHeader->GetInputFileId()]->GetInChain();
     if(!chain) { return; }
     chain->FindBranch(BrName)->GetEntry(fEvtHeader->GetMCEntryNumber());
     return;
   }
   return;
 }
void FairRootManager::ReadEvent (Int_t i)
For mixed input use the ReadMixedEvent method
Check if the source is not zero, it is zero if we use the mixed input (bk and sg)
special action needed for the first entry
After the first entry we are here
Definition at line 794 of file FairRootManager.cxx.
References FairLogger::endl(), fCurrentEntryNo, fEvtHeader, fMixedInput, fRootFileSource, FairFileSource::GetEntries(), GetEventTime(), GetObject(), INFO, LOG, FairFileSource::ReadEvent(), ReadMixedEvent(), SetEntryNr(), FairEventHeader::SetEventTime(), SetEventTime(), FairEventHeader::SetInputFileId(), and FairEventHeader::SetMCEntryNumber().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
     SetEntryNr(i);
     if(fMixedInput) {
       LOG(INFO) << "Read mixed event number " << i << FairLogger::endl;
         ReadMixedEvent(i);
     }else{
         if ( fRootFileSource!=0) {
             if(0==fCurrentEntryNo) {
                 Int_t totEnt =  fRootFileSource->GetEntries();
                 LOG(INFO) << "The number of entries in the tree is "
                           << totEnt << FairLogger::endl;
                 LOG(INFO) << "FairRootManager::ReadEvent(" << i << "): The tree has " << totEnt << " entries" << FairLogger::endl;
                 fEvtHeader = (FairEventHeader*) GetObject("EventHeader.");
                 if(fEvtHeader ==0) {
                   LOG(INFO) << "No event Header was found!!!" << FairLogger::endl;
                     return;
                 }
                 SetEventTime();
             }
             fCurrentEntryNo=i;
             fRootFileSource->ReadEvent(i);
             fEvtHeader->SetMCEntryNumber(i);
             fEvtHeader->SetEventTime(GetEventTime());
             fEvtHeader->SetInputFileId(0);
         }
     }
 }
void FairRootManager::ReadMixedEvent (Int_t i) private
Read a single entry
Privat method used for event mixing
Check for fCurrentEntryNo because it always starts from Zero, i could have any value!
Definition at line 832 of file FairRootManager.cxx.
References DEBUG, FairLogger::endl(), fCurrentEntry, fCurrentEntryNo, fEvtHeader, fRootFileSourceBKG, fSBRatiobyN, fSBRatiobyT, fSignalBGN, fSignalTypeList, GetEventTime(), GetObject(), LOG, FairFileSource::ReadEvent(), FairEventHeader::SetEventTime(), SetEventTime(), FairEventHeader::SetInputFileId(), and FairEventHeader::SetMCEntryNumber().
Referenced by ReadEvent().
 {
   if(0==fCurrentEntryNo) {
     fEvtHeader = (FairEventHeader*) GetObject("EventHeader.");
     SetEventTime();
   }
   Double_t SBratio=gRandom->Uniform(0,1);
   Bool_t GetASignal=kFALSE;
   if(fSBRatiobyN || fSBRatiobyT ) {
     std::map<UInt_t, Double_t>::const_iterator iterN;
     Double_t ratio=0;
     if(fCurrentEntryNo==0) {
       for(iterN = fSignalBGN.begin(); iterN != fSignalBGN.end(); iterN++) {
         ratio+=iterN->second;
         fSignalBGN[iterN->first]=ratio;
         LOG(DEBUG) << "--------------Set signal no. "
                    << iterN->first << " weight " << ratio << FairLogger::endl;
       }
     }
     ratio=0;
     for(iterN = fSignalBGN.begin(); iterN != fSignalBGN.end(); iterN++) {
       ratio=iterN->second;
       LOG(DEBUG) << "---Check signal no. "
                  << iterN->first << " SBratio "
                  << SBratio << " :  ratio "
                  <<ratio << FairLogger::endl;
       if(SBratio <=ratio) {
         TChain* chain = fSignalTypeList[iterN->first]->GetInChain();
         UInt_t entry = fCurrentEntry[iterN->first];
         chain->GetEntry(entry);
         fEvtHeader->SetMCEntryNumber(entry);
         fEvtHeader->SetInputFileId(iterN->first);
         fEvtHeader->SetEventTime(GetEventTime());
         GetASignal=kTRUE;
         fCurrentEntry[iterN->first]=entry+1;
         LOG(DEBUG) << "---Get entry No. "
                      << entry << " from signal chain number --- "
                      << iterN->first << " ---" << FairLogger::endl;
         break;
       }
     }
     if(!GetASignal) {
       fRootFileSourceBKG->ReadEvent(i);
       fEvtHeader->SetMCEntryNumber(i);
       fEvtHeader->SetInputFileId(0); //Background files has always 0 as Id
       fEvtHeader->SetEventTime(GetEventTime());
       LOG(DEBUG) << "---Get entry from background chain  --- " << FairLogger::endl;
     }
   }
   fCurrentEntryNo=i;
   fEvtHeader->SetEventTime(GetEventTime());
   LOG(DEBUG) << "--Event number --- "
              << fCurrentEntryNo << " with time ---- "
              << GetEventTime() << FairLogger::endl;
 }
Bool_t FairRootManager::ReadNextEvent (Double_t dt)
Read all entries from input tree(s) with time stamp from current time to dt (time in ns)
TODO
Definition at line 909 of file FairRootManager.cxx.
Referenced by FairRunAna::Run().
 {
   Bool_t readentry=kFALSE;
   return readentry;
 }
void FairRootManager::Register (const char * name, const char * Foldername, TNamed * obj, Bool_t toFile)
create a new branch in the output tree
Parameters
name Name of the branch to create
Foldername Folder name containing this branch (e.g Detector name)
obj Pointer of type TNamed (e.g. MCStack object)
toFile if kTRUE, branch will be saved to the tree
Write the Object to the Tree
Definition at line 424 of file FairRootManager.cxx.
References AddBranchToList(), FairLinkManager::AddIgnoreType(), AddMemoryBranch(), FairLogger::endl(), FATAL, fCbmout, fCbmroot, GetBranchId(), FairLinkManager::Instance(), and LOG.
Referenced by FairWriteoutBuffer::FairWriteoutBuffer(), FairTestDetectorDigiTask::Init(), FairTestDetectorHitProducerSmearing::Init(), FairTestDetectorRecoTask::Init(), FairTestDetectorTimeRecoTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairMCMatchLoaderTask::Init(), FairRunOnline::Init(), FairMCMatchCreatorTask::Init(), FairTutorialDet4HitProducerIdealMisalign::Init(), FairRingSorterTask::Init(), FairRadLenManager::Init(), FairRadMapManager::Init(), FairTrajFilter::Init(), FairRunOnline::InitContainers(), FairTutorialDet2::Register(), FairTestDetector::Register(), NewDetector::Register(), FairRutherford::Register(), FairTutorialDet1::Register(), FairTutorialDet4::Register(), FairEventHeader::Register(), FairMCEventHeader::Register(), Register(), MyProjStack::Register(), and FairStack::Register().
 {
   // Security check. If the the name is equal the folder name there are problems with reading
   // back the data. Instead of the object inside the folder the RootManger will return a pointer
   // to the folder. To avoid such problems we check here if both strings are equal and stop the
   // execution with some error message if this is the case.
   if (strcmp (name, folderName) == 0 ) {
     LOG(FATAL) << "The names for the object name "
                << name << " and the folder name "
                << folderName <<" are equal. This isn't allowed. So we stop the execution at this point. Pleae change either the name or the folder name."
                << FairLogger::endl;
   }
   if(toFile) {
     TFolder* folder=0;
     TFolder* f=0;
     if(fCbmout==0) {
       f=(TFolder*)fCbmroot->FindObjectAny(folderName);
       if(f==0) {
         folder= fCbmroot->AddFolder(folderName,folderName);
       } else {
         folder=f;
       }
     } else {
       f=(TFolder*)fCbmout->FindObjectAny(folderName);
       if(f==0) {
         folder= fCbmout->AddFolder(folderName,folderName);
       } else {
         folder=f;
       }
     }
     obj->SetName(name);
     folder->Add(obj);
   }
   AddMemoryBranch(name, obj );
   //cout << " FairRootManager::Register Adding branch:(Obj) " << name << " In folder : " << folderName << endl;
   AddBranchToList(name);
   if (toFile == kFALSE) {
           FairLinkManager::Instance()->AddIgnoreType(GetBranchId(name));
    }
 }
void FairRootManager::Register (const char * name, const char * Foldername, TCollection * obj, Bool_t toFile)
create a new branch in the output tree
Parameters
name Name of the branch to create
Foldername Folder name containing this branch (e.g Detector name)
obj Pointer of type TCollection (e.g. TClonesArray of hits, points)
toFile if kTRUE, branch will be saved to the tree
This method do exactly the same as the one before but for TCollection which is a TObject and not a TNamed (MT)
Write the Object to the Tree
Keep the Object in Memory, and do not write it to the tree
Definition at line 481 of file FairRootManager.cxx.
References AddBranchToList(), FairLinkManager::AddIgnoreType(), AddMemoryBranch(), FairLogger::endl(), FATAL, fCbmout, fCbmroot, GetBranchId(), FairLinkManager::Instance(), and LOG.
 {
   // Security check. If the the name is equal the folder name there are problems with reading
   // back the data. Instead of the object inside the folder the RootManger will return a pointer
   // to the folder. To avoid such problems we check here if both strings are equal and stop the
   // execution with some error message if this is the case.
   if (strcmp (name, Foldername) == 0 ) {
     LOG(FATAL) << "The names for the object name "
                << name << " and the folder name "
                << Foldername << " are equal. This isn't allowed. So we stop the execution at this point. Pleae change either the name or the folder name."
                <<FairLogger::endl;
   }
   if(toFile) {
     TFolder* folder=0;
     TFolder* f=0;
     if(fCbmout==0) {
       f=(TFolder*)fCbmroot->FindObjectAny(Foldername);
       if(f==0) {
         folder= fCbmroot->AddFolder(Foldername,Foldername);
       } else {
         folder=f;
       }
     } else {
       f=(TFolder*)fCbmout->FindObjectAny(Foldername);
       if(f==0) {
         folder= fCbmout->AddFolder(Foldername,Foldername);
       } else {
         folder=f;
       }
     }
     obj->SetName(name);
     folder->Add(obj);
   }
   AddMemoryBranch(name, obj );
   AddBranchToList(name);
   if (toFile == kFALSE) {
           FairLinkManager::Instance()->AddIgnoreType(GetBranchId(name));
   }
 }
TClonesArray * FairRootManager::Register (TString branchName, TString className, TString folderName, Bool_t toFile)
Definition at line 531 of file FairRootManager.cxx.
References fActiveContainer, fCompressData, fDataContainer, and Register().
 {
   TClonesArray* outputArray;
   if (fActiveContainer.find(branchName) == fActiveContainer.end()) {
     fActiveContainer[branchName] = new TClonesArray(className);
     if (fCompressData) {
       std::queue<TClonesArray*> myQueue;
       fDataContainer[branchName] = myQueue;
       outputArray = new TClonesArray(className);
     } else {
       outputArray = fActiveContainer[branchName];
     }
     Register(branchName, folderName, outputArray, toFile);
   }
   return fActiveContainer[branchName];
 }
void FairRootManager::RegisterTSBuffer (TString branchName, FairTSBufferFunctional * functionalBuffer) inline
Definition at line 120 of file FairRootManager.h.
References fTSBufferMap.
 {fTSBufferMap[branchName] = functionalBuffer;}
FairWriteoutBuffer * FairRootManager::RegisterWriteoutBuffer (TString branchName, FairWriteoutBuffer * buffer)
Register a new PndWriteoutBuffer to the map. If a Buffer with the same map key already exists the given buffer will be deleted and the old will be returned!
Definition at line 1748 of file FairRootManager.cxx.
References buffer, FairLogger::endl(), fWriteoutBufferMap, LOG, and WARNING.
Referenced by FairTestDetectorTimeDigiTask::Init().
 {
   if (fWriteoutBufferMap[branchName] == 0) {
     fWriteoutBufferMap[branchName] = buffer;
   } else {
     LOG(WARNING) << "Branch "
                  << branchName.Data()
                  << " is already registered in WriteoutBufferMap"
                  << FairLogger::endl;
     delete buffer;
   }
   return fWriteoutBufferMap[branchName];
 }
void FairRootManager::RunWithTimeStamps () inline
Use time stamps to read data and not tree entries
Definition at line 154 of file FairRootManager.h.
References fTimeStamps.
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), and FairRunAna::RunWithTimeStamps().
 {fTimeStamps = kTRUE;}
void FairRootManager::SaveAllContainers () private
Definition at line 1539 of file FairRootManager.cxx.
References AssignTClonesArrays(), DataContainersEmpty(), and ForceFill().
Referenced by Write().
 {
   while(!DataContainersEmpty()) {
     AssignTClonesArrays();
     ForceFill();
   }
 }
void FairRootManager::SetBackgroundFile (TString name)
Set the input background file by name
Definition at line 227 of file FairRootManager.cxx.
References FairFileHeader::AddInputFile(), FairLogger::endl(), fFileHeader, fRootFileSourceBKG, FairFileSource::GetInFile(), INFO, FairFileSource::Init(), and LOG.
Referenced by FairRunAna::SetBackgroundFile().
 {
   if (name.IsNull() ) {
     LOG(INFO) << "No background file defined." << FairLogger::endl;
   }else{
     fRootFileSourceBKG = new FairFileSource(&name, "Background");
     fRootFileSourceBKG->Init();
     fFileHeader->AddInputFile(fRootFileSourceBKG->GetInFile(),0,0 );
   }
 }
void FairRootManager::SetBeamTime (Double_t beamTime, Double_t gapTime)
Set the repetition time of the beam when it can interact (beamTime) and when no interaction happen (gapTime). The total repetition time is beamTime + gapTime
Definition at line 1615 of file FairRootManager.cxx.
References fBeamTime, and fGapTime.
Referenced by FairRunAna::SetBeamTime().
 {
         fBeamTime = beamTime;
         fGapTime = gapTime;
 }
void FairRootManager::SetBranchNameList (TList * list)
Set the branch name list
Definition at line 1276 of file FairRootManager.cxx.
References fBranchNameList.
 {
   for(Int_t t=0; t<list->GetEntries(); t++) {
     fBranchNameList->AddAt(list->At(t),t);
   }
 }
void FairRootManager::SetCompressData (Bool_t val) inline
Definition at line 177 of file FairRootManager.h.
References fCompressData.
Referenced by FairRunAna::CompressData().
 {fCompressData = val;}
void FairRootManager::SetEntryNr (Int_t val) inline
Definition at line 233 of file FairRootManager.h.
References fEntryNr.
Referenced by ReadEvent().
 {fEntryNr = val;}
void FairRootManager::SetEventMeanTime (Double_t mean)
Set the mean time for the event in ns
Definition at line 1599 of file FairRootManager.cxx.
References fEventMeanTime, fEventTimeInMCHeader, and fTimeProb.
Referenced by FairRunAna::SetEventMeanTime().
 {
   fEventMeanTime =mean;
   TString form="(1/";
   form+= mean;
   form+=")*exp(-x/";
   form+=mean;
   form+=")";
   fTimeProb= new TF1("TimeProb.", form.Data(), 0., mean*10);
   fTimeProb->GetRandom();
   fEventTimeInMCHeader=kFALSE;
 }
void FairRootManager::SetEventTime ()
Definition at line 1621 of file FairRootManager.cxx.
References DEBUG, FairLogger::endl(), fBeamTime, fCurrentEntryNo, fEventTime, fGapTime, fTimeforEntryNo, GetDeltaEventTime(), and LOG.
Referenced by GetEventTime(), ReadEvent(), and ReadMixedEvent().
 {
   LOG(DEBUG) << "Set event time for Entry = "
              << fTimeforEntryNo << " , where the current entry is "
              << fCurrentEntryNo << " and eventTime is "
              << fEventTime << FairLogger::endl;
   if (fBeamTime < 0){
           fEventTime += GetDeltaEventTime();
   } else {
           do {
                   fEventTime += GetDeltaEventTime();
           } while( fmod(fEventTime, fBeamTime + fGapTime) > fBeamTime );
   }
   LOG(DEBUG) << "New time = " << fEventTime << FairLogger::endl;
   fTimeforEntryNo=fCurrentEntryNo;
 }
void FairRootManager::SetEventTimeInterval (Double_t min, Double_t max)
Set the min and max limit for event time in ns
Definition at line 1589 of file FairRootManager.cxx.
References fEventMeanTime, fEventTimeInMCHeader, fEventTimeMax, and fEventTimeMin.
Referenced by FairRunAna::SetEventTimeInterval().
 {
   fEventTimeMin=min;
   fEventTimeMax=max;
   fEventMeanTime=(fEventTimeMin+fEventTimeMax)/2;
   fEventTimeInMCHeader=kFALSE;
 }
void FairRootManager::SetEvtHeaderNew (Bool_t Status) inline
Add signal file to input
Parameters
name : signal file name
identifier : Unsigned integer which identify the signal file to which this signal should be added Set the status of the EvtHeader
Status True: The header was creatged in this session and has to be filled FALSE: We use an existing header from previous data level
Definition at line 172 of file FairRootManager.h.
References fEvtHeaderIsNew.
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), and FairRunAna::InitContainers().
 {fEvtHeaderIsNew = Status;}
void FairRootManager::SetFileHeader (FairFileHeader * f) inline
Definition at line 211 of file FairRootManager.h.
References fFileHeader.
Referenced by FairRun::FairRun().
 {fFileHeader =f;}
void FairRootManager::SetInputFile (TString name)
Set the name of the input file
Definition at line 258 of file FairRootManager.cxx.
References fMixedInput, and fRootFileSource.
Referenced by FairRunAna::SetInputFile().
 {
   if(!fMixedInput) {
     //fInputFileName=name;
     fRootFileSource = new FairFileSource(&name);
     // fRootFileSource->Init();
     // fCbmroot = fRootFileSource->GetBranchDescriptionFolder();
   }
 }
void FairRootManager::SetInTree (TTree * tempTree) inline
Set the input tree when running on PROOF worker
Definition at line 265 of file FairRootManager.h.
References fRootFileSource, and FairFileSource::SetInTree().
Referenced by FairRunAnaProof::SetInTree().
{
       if ( fRootFileSource ) {
         fRootFileSource->SetInTree(tempTree);
       }
       else {
         fRootFileSource = new FairFileSource(tempTree->GetCurrentFile());
       }
     }
void FairRootManager::SetLastFill (Bool_t val = kTRUE) inline
Enables a last Fill command after all events are processed to store any data which is still in Buffers
Definition at line 186 of file FairRootManager.h.
References fFillLastData.
Referenced by FairRingSorterTask::FinishTask().
 { fFillLastData=val;}
void FairRootManager::SetMixAllInputs (Bool_t Status) inline
Parameters
Status : if true all inputs are mixed, i.e: each read event will take one entry from each input and put them in one big event and send it to the next step
Definition at line 242 of file FairRootManager.h.
References fMixAllInputs.
Referenced by FairRunAna::SetMixAllInputs().
{
        fMixAllInputs=kTRUE;
     }
void FairRootManager::SetOutTree (TTree * fTree) inline
Set the output tree pointer
Definition at line 183 of file FairRootManager.h.
References fOutTree.
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), and FairMCApplication::InitGeometry().
 { fOutTree=fTree;}
void FairRootManager::SetSignalFile (TString name, UInt_t identifier)
Set the input signal file
Parameters
name : signal file name
identifier : Unsigned integer which identify the signal file
Create a new source for signal
The first file create a new source for signal
we have to inialize it to check the file and get/ create the chain from the input tree(s)
Definition at line 168 of file FairRootManager.cxx.
References FairFileSource::AddFile(), FairFileHeader::AddInputFile(), FairLogger::endl(), fActualSignalIdentifier, fCurrentEntry, fFileHeader, fMixedInput, fNoOfSignals, fRootFileSourceSignal, fSignalTypeList, FairFileSource::GetInChain(), FairFileSource::GetInFile(), INFO, FairFileSource::Init(), and LOG.
Referenced by AddSignalFile().
 {
     if(fSignalTypeList[identifier]==0) {
       fRootFileSourceSignal = new FairFileSource(&name, "SignalSource", identifier);
       fRootFileSourceSignal->Init();
       fCurrentEntry[identifier]= 0;
       fNoOfSignals++;
       fActualSignalIdentifier= identifier;
       fSignalTypeList[identifier]=fRootFileSourceSignal;
       fFileHeader->AddInputFile(fRootFileSourceSignal->GetInFile(), identifier, 0);
       LOG(INFO) << "Add new signal from file "
                 << name.Data() << " with identifier "
                 << identifier << " and file number "
                 << fNoOfSignals << FairLogger::endl;
     }else{
       FairFileSource *fRootFileSourceS=fSignalTypeList[identifier];
       fRootFileSourceS->AddFile(name);
       TChain* CurrentChain=fRootFileSourceS->GetInChain();
       TObjArray* fileElements=CurrentChain->GetListOfFiles();
       fFileHeader->AddInputFile(fRootFileSourceSignal->GetInFile(), identifier, fileElements->GetEntries());
       LOG(INFO) << "Add existing signal from file "
                 << name.Data() << " with identifier "
                 << identifier << " and file number "
                 << fNoOfSignals << FairLogger::endl;
     }
     fMixedInput=kTRUE;
 }
void FairRootManager::SetUseFairLinks (Bool_t val) inline
Definition at line 235 of file FairRootManager.h.
References fUseFairLinks.
Referenced by FairRun::SetUseFairLinks().
 {fUseFairLinks = val;};
void FairRootManager::StoreAllWriteoutBufferData ()
Definition at line 1784 of file FairRootManager.cxx.
References fFillLastData, and fWriteoutBufferMap.
Referenced by FairRunAna::Run(), FairRunOnline::Run(), FairRunAna::RunMixed(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   Bool_t dataInBuffer = kFALSE;
   for(std::map<TString, FairWriteoutBuffer*>::const_iterator iter = fWriteoutBufferMap.begin(); iter != fWriteoutBufferMap.end(); iter++) {
     if (iter->second->GetNData() > 0) {
       dataInBuffer = kTRUE;
     }
     iter->second->WriteOutAllData();
   }
   fFillLastData = dataInBuffer;
 }
void FairRootManager::StoreWriteoutBufferData (Double_t eventTime)
Definition at line 1775 of file FairRootManager.cxx.
References fWriteoutBufferMap.
Referenced by FairRunOnline::EventLoop(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), and FairRunAnaProof::RunOneEvent().
 {
   for(std::map<TString, FairWriteoutBuffer*>::const_iterator iter = fWriteoutBufferMap.begin(); iter != fWriteoutBufferMap.end(); iter++) {
     iter->second->WriteOutData(eventTime);
   }
 }
void FairRootManager::TruncateBranchNames (TBranch * b, TString ffn)
When creating TTree from TFolder the fullpath of the objects is used as branch names this method truncate the full path from the branch names
Get the branch name from the branch object, remove common and wrong part of the name and and set branch name to the new corrected name. This has to be done recursivly for all subbranches/leaves Remove wrong part of branch name
Definition at line 1230 of file FairRootManager.cxx.
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitGeometry(), and TruncateBranchNames().
 {
   TObject* BrObj;
   TString nn= b->GetName();
   //  cout<<"nn.Data before: "<<nn.Data()<<endl;
   nn.ReplaceAll(ffn.Data(),"");
   //  cout<<"nn.Data after: "<<nn.Data()<<endl;
   //  cout <<"##################"<<endl;
   b->SetName(nn.Data());
   TObjArray* Br= b->GetListOfBranches();
   TIterator* BrIter= Br->MakeIterator();
   BrIter->Reset();
   while((BrObj=BrIter->Next())) {
     TBranch* bb=(TBranch*)BrObj;
     TruncateBranchNames(bb, ffn);
   }
   delete  BrIter;
 }
void FairRootManager::TruncateBranchNames (TTree * fTree, const char * folderName)
When creating TTree from TFolder the fullpath of the objects is used as branch names this method truncate the full path from the branch names
If a object is created in a folder the corresponding branch in the tree is crated with a wrong name. The name of the branch is created as follows mainFolder.subFolder.nameOfStoredObject e.g. cbmroot.Event.ExampleClass. The name which is wanted is only nameOfStoredObject e.g. ExampleClass. This is corrected in this function If the folder does not exist don't do anything
correct branch names in all folders below the main output folder
Create TString with the part of the branch name which should be removed. This is mainFolderName.folderName. e.g. cbmroot.Event. This part of the branch name is obsolete, so it is removed from the branch name.
Correct name of all branches and leaves which correspond to the subfolder. To do so loop over all branches and check if the branch corresponds with the folder. If it corresponds correct the branch names of all sub branches. Only correct branch names for up to now uncorrected branches.
Definition at line 1145 of file FairRootManager.cxx.
References TruncateBranchNames().
 {
   TFolder* cbm=(TFolder*)gROOT->FindObjectAny(folderName);
   if(cbm) {
     TCollection* lf=cbm->GetListOfFolders();
     TIterator* iter= lf->MakeIterator();
     TObjArray* Br= fTree->GetListOfBranches();
     TIterator* BrIter= Br->MakeIterator();
     TObject* obj;
     TObject* BrObj;
     while((obj=iter->Next())) {
       TString ffn=cbm->GetName();
       ffn=ffn+".";
       ffn=ffn+obj->GetName();
       ffn=ffn+".";
       BrIter->Reset();
       while((BrObj=BrIter->Next())) {
         TBranch* b=(TBranch*)BrObj;
         TruncateBranchNames(b, ffn);
       }
     }
     // Remove all occurence of FairMCEventHeader and   from
     // all branches containing that string.
     // This is not the correct way to do it, but up tonow we don't understand
     // why this part comes in when storing a derrived class from
     // FairMCEventHeader or FairEventHeader.
     iter->Reset();
     while((obj=iter->Next())) {
       TString ffn=".FairMCEventHeader";
       BrIter->Reset();
       while((BrObj=BrIter->Next())) {
         TBranch* b=(TBranch*)BrObj;
         TruncateBranchNames(b, ffn);
       }
     }
     iter->Reset();
     while((obj=iter->Next())) {
       TString ffn=".FairEventHeader";
       BrIter->Reset();
       while((BrObj=BrIter->Next())) {
         TBranch* b=(TBranch*)BrObj;
         TruncateBranchNames(b, ffn);
       }
     }
     delete  iter;
     delete  BrIter;
   }
 }
Int_t FairRootManager::Write (const char * name = 0, Int_t option = 0, Int_t bufsize = 0)
Writes the tree in the file.
Get the file handle to the current output file from the tree. If ROOT splits the file (due to the size of the file) the file handle fOutFile is lost and the program crash while writing the last part of the last file.
Definition at line 726 of file FairRootManager.cxx.
References FairLogger::endl(), fCompressData, fOutFile, fOutTree, INFO, LOG, and SaveAllContainers().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), FairMCApplication::StopRun(), and FairRunAna::TerminateRun().
 {
   if (fCompressData) {
     SaveAllContainers();
   }
   if(fOutTree!=0) {
     fOutFile = fOutTree->GetCurrentFile();
     fOutFile->cd();
     fOutTree->Write();
   } else {
     LOG(INFO) << "No Output Tree" << FairLogger::endl;
   }
   return 0;
 }
void FairRootManager::WriteFileHeader (FairFileHeader * f)
Write the file header object to the output file
Definition at line 1580 of file FairRootManager.cxx.
References fOutFile.
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), and FairRunSim::Init().
 {
   fOutFile->cd();
   f->SetName(fOutFile->GetName());
   f->Write("FileHeader", TObject::kSingleKey);
 }
void FairRootManager::WriteFolder ()
Write the folder structure used to create the tree to the output file
Definition at line 780 of file FairRootManager.cxx.
References fBranchNameList, fCbmout, fCbmroot, fOutFile, and fRootFileSource.
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), and FairMCApplication::InitGeometry().
 {
   fOutFile->cd();
   if(fCbmroot!=0 && fRootFileSource==0) {
     fCbmroot->Write();
   }
   if(fCbmout!=0) {
     fCbmout->Write();
   }
   fBranchNameList->Write("BranchList", TObject::kSingleKey);
 }
void FairRootManager::WriteGeometry ()
Write the current TGeoManager to file
Writes the geometry in the current output file.
Definition at line 749 of file FairRootManager.cxx.
References fOutFile, and fOutTree.
 {
   if(fOutTree!=0) {
     fOutFile = fOutTree->GetCurrentFile();
     fOutFile->cd();
     gGeoManager->Write();
   }
 }
Member Data Documentation
std::map<TString, TClonesArray*> FairRootManager::fActiveContainer private
Internally used to compress empty slots in data buffer
Definition at line 337 of file FairRootManager.h.
Referenced by GetEmptyTClonesArray(), GetTClonesArray(), and Register().
UInt_t FairRootManager::fActualSignalIdentifier private
Actual identifier of the added signals, this is used to identify how many signals are added
Definition at line 360 of file FairRootManager.h.
Referenced by SetSignalFile().
TChain* FairRootManager::fBackgroundChain private
Chain containing the background
Definition at line 366 of file FairRootManager.h.
Referenced by GetBGChain().
TFile* FairRootManager::fBackgroundFile private
Definition at line 367 of file FairRootManager.h.
Double_t FairRootManager::fBeamTime private
Time of particles in beam (ns)
Definition at line 377 of file FairRootManager.h.
Referenced by SetBeamTime(), and SetEventTime().
TList* FairRootManager::fBranchNameList private
List of branch names as TObjString
Definition at line 333 of file FairRootManager.h.
Referenced by AddBranchToList(), CreatePerMap(), GetBranchId(), GetBranchName(), GetBranchNameList(), SetBranchNameList(), WriteFolder(), and ~FairRootManager().
Bool_t FairRootManager::fBranchPerMap private
Flag for creation of Map for branch persistency list
Definition at line 348 of file FairRootManager.h.
Referenced by CheckBranch(), and CreatePerMap().
Int_t FairRootManager::fBranchSeqId private
Branch id for this run
Definition at line 331 of file FairRootManager.h.
Referenced by AddBranchToList(), CreatePerMap(), and GetBranchName().
std::map< TString , Int_t > FairRootManager::fBrPerMap private
Map for branch persistency list
Definition at line 350 of file FairRootManager.h.
Referenced by CheckBranch(), and CreatePerMap().
std::map< TString, Int_t>::iterator FairRootManager::fBrPerMapIter private
Iterator for the fBrPerMap Map
Definition at line 352 of file FairRootManager.h.
Referenced by CheckBranch().
TFolder* FairRootManager::fCbmout private
private Members folder structure of output
Definition at line 309 of file FairRootManager.h.
Referenced by CheckBranchSt(), GetObject(), OpenOutFile(), Register(), and WriteFolder().
TFolder* FairRootManager::fCbmroot private
folder structure of input
Definition at line 311 of file FairRootManager.h.
Referenced by CheckBranchSt(), GetObject(), GetObjectFromInTree(), InitSource(), OpenOutFile(), Register(), and WriteFolder().
Bool_t FairRootManager::fCompressData private
//Map of input branch ID with TBranch pointer
if kTRUE the entries of a branch are filled from the beginning –> no empty entries
Definition at line 344 of file FairRootManager.h.
Referenced by Fill(), GetEmptyTClonesArray(), GetTClonesArray(), Register(), SetCompressData(), and Write().
Int_t FairRootManager::fCurrentEntries private
Definition at line 322 of file FairRootManager.h.
std::map<UInt_t, UInt_t> FairRootManager::fCurrentEntry private
Hold the current entry for each input chain
Definition at line 408 of file FairRootManager.h.
Referenced by ReadMixedEvent(), and SetSignalFile().
UInt_t FairRootManager::fCurrentEntryNo private
for internal use, to return the same event time for the same entry
Definition at line 402 of file FairRootManager.h.
Referenced by GetEventTime(), ReadEvent(), ReadMixedEvent(), and SetEventTime().
Double_t FairRootManager::fCurrentTime private
current time in ns
Definition at line 313 of file FairRootManager.h.
std::map<TString, std::queue<TClonesArray*> > FairRootManager::fDataContainer private
Internally used to compress empty slots in data buffer
Definition at line 335 of file FairRootManager.h.
Referenced by AssignTClonesArrays(), DataContainersEmpty(), DataContainersFilled(), ForceGetDataContainer(), GetDataContainer(), GetEmptyTClonesArray(), GetTClonesArray(), and Register().
Int_t FairRootManager::fEntryNr private
Definition at line 415 of file FairRootManager.h.
Referenced by GetEntryNr(), ReadBranchEvent(), and SetEntryNr().
Double_t FairRootManager::fEventMeanTime private
EventMean time used (P(t)=1/fEventMeanTime*Exp(-t/fEventMeanTime)
Definition at line 381 of file FairRootManager.h.
Referenced by BGWindowWidthTime(), SetEventMeanTime(), and SetEventTimeInterval().
Double_t FairRootManager::fEventTime private
Time of event since th start (ns)
Definition at line 375 of file FairRootManager.h.
Referenced by GetEventTime(), and SetEventTime().
Bool_t FairRootManager::fEventTimeInMCHeader private
This is true if the event time used, came from simulation
Definition at line 396 of file FairRootManager.h.
Referenced by BGWindowWidthTime(), GetEventTime(), SetEventMeanTime(), and SetEventTimeInterval().
Double_t FairRootManager::fEventTimeMax private
max time for one Event (ns)
Definition at line 373 of file FairRootManager.h.
Referenced by GetDeltaEventTime(), and SetEventTimeInterval().
Double_t FairRootManager::fEventTimeMin private
min time for one event (ns)
Definition at line 371 of file FairRootManager.h.
Referenced by GetDeltaEventTime(), and SetEventTimeInterval().
FairEventHeader* FairRootManager::fEvtHeader private
Event Header
Definition at line 388 of file FairRootManager.h.
Referenced by GetEventTime(), ReadBranchEvent(), ReadEvent(), and ReadMixedEvent().
Bool_t FairRootManager::fEvtHeaderIsNew private
This flag is true if the event header was created in this session otherwise it is false which means the header was created in a previous data level and used here (e.g. in the digi)
Definition at line 413 of file FairRootManager.h.
Referenced by GetEventTime(), IsEvtHeaderNew(), and SetEvtHeaderNew().
FairFileHeader* FairRootManager::fFileHeader private
File Header
Definition at line 391 of file FairRootManager.h.
Referenced by AddBackgroundFile(), SetBackgroundFile(), SetFileHeader(), and SetSignalFile().
Bool_t FairRootManager::fFillLastData private
Definition at line 414 of file FairRootManager.h.
Referenced by LastFill(), SetLastFill(), and StoreAllWriteoutBufferData().
std::list<TString> FairRootManager::fFriendFileList private
List of all files added with AddFriend
Definition at line 354 of file FairRootManager.h.
Double_t FairRootManager::fGapTime private
Time without particles in beam (gap) (ns)
Definition at line 379 of file FairRootManager.h.
Referenced by SetBeamTime(), and SetEventTime().
TMCThreadLocal FairRootManager * FairRootManager::fgInstance = 0 static private
Singleton instance
Definition at line 325 of file FairRootManager.h.
Referenced by FairRootManager(), Instance(), and ~FairRootManager().
std::map<Int_t, TBranch*> FairRootManager::fInputBranchMap private
Definition at line 341 of file FairRootManager.h.
Referenced by GetCloneOfLinkData(), and GetCloneOfTClonesArray().
std::map< TString , TObject* > FairRootManager::fMap private
Definition at line 320 of file FairRootManager.h.
Referenced by AddMemoryBranch(), and GetMemoryBranch().
FairMCEventHeader* FairRootManager::fMCHeader private
MC Event header
Definition at line 385 of file FairRootManager.h.
Referenced by GetEventTime().
Bool_t FairRootManager::fMixAllInputs private
Mix all inputs, i.e: read one entry from each input and add them together
Definition at line 356 of file FairRootManager.h.
Referenced by SetMixAllInputs().
Bool_t FairRootManager::fMixedInput private
True if signal and background mixing is used
Definition at line 358 of file FairRootManager.h.
Referenced by ActivateBranch(), CheckMaxEventNo(), InitSource(), ReadBKEvent(), ReadBranchEvent(), ReadEvent(), SetInputFile(), and SetSignalFile().
Int_t FairRootManager::fNObj private
Definition at line 319 of file FairRootManager.h.
Referenced by ActivateBranch(), and ActivateBranchInInTree().
UInt_t FairRootManager::fNoOfBGEntries private
No of entries in BG Chain
Definition at line 406 of file FairRootManager.h.
UInt_t FairRootManager::fNoOfSignals private
Total number of signals added (Types and not files!)
Definition at line 362 of file FairRootManager.h.
Referenced by GetSignalChainNo(), and SetSignalFile().
TObject** FairRootManager::fObj2 private
Definition at line 318 of file FairRootManager.h.
Referenced by ActivateBranch(), ActivateBranchInInTree(), and ~FairRootManager().
Int_t FairRootManager::fOldEntryNr private
Definition at line 305 of file FairRootManager.h.
TFile* FairRootManager::fOutFile private
Output file
Definition at line 315 of file FairRootManager.h.
Referenced by CloseOutFile(), GetOutFile(), OpenOutFile(), Write(), WriteFileHeader(), WriteFolder(), WriteGeometry(), and ~FairRootManager().
TTree* FairRootManager::fOutTree private
Output tree
Definition at line 317 of file FairRootManager.h.
Referenced by ForceFill(), GetOutTree(), SetOutTree(), Write(), WriteGeometry(), and ~FairRootManager().
TTree* FairRootManager::fPtrTree private
Definition at line 321 of file FairRootManager.h.
FairFileSource* FairRootManager::fRootFileSource private
Definition at line 416 of file FairRootManager.h.
Referenced by ActivateBranch(), ActivateBranchInInTree(), AddFile(), AddFriend(), CheckBranchSt(), CheckFriendChains(), CheckMaxEventNo(), CloseInFile(), CompareBranchList(), CreateNewFriendChain(), GetInChain(), GetInFile(), GetInTree(), GetObjectFromInTree(), GetRootFile(), InitSource(), PrintFriendList(), ReadBranchEvent(), ReadEvent(), SetInputFile(), SetInTree(), and WriteFolder().
FairFileSource* FairRootManager::fRootFileSourceBKG private
Definition at line 418 of file FairRootManager.h.
Referenced by ActivateBranch(), AddBackgroundFile(), CheckMaxEventNo(), InitSource(), ReadBKEvent(), ReadMixedEvent(), and SetBackgroundFile().
FairFileSource* FairRootManager::fRootFileSourceSignal private
Definition at line 417 of file FairRootManager.h.
Referenced by SetSignalFile().
Bool_t FairRootManager::fSBRatiobyN private
True for background window in entry units
Definition at line 398 of file FairRootManager.h.
Referenced by BGWindowWidthNo(), BGWindowWidthTime(), and ReadMixedEvent().
Bool_t FairRootManager::fSBRatiobyT private
True for background window in time units (ns)
Definition at line 400 of file FairRootManager.h.
Referenced by BGWindowWidthNo(), BGWindowWidthTime(), and ReadMixedEvent().
std::map<UInt_t, Double_t> FairRootManager::fSignalBGN private
holds the SB ratio by number
Definition at line 394 of file FairRootManager.h.
Referenced by BGWindowWidthNo(), BGWindowWidthTime(), CheckMaxEventNo(), and ReadMixedEvent().
std::list<TString>* FairRootManager::fSignalChainList private
list of chains which has to be created for the different signals
Definition at line 364 of file FairRootManager.h.
std::map<UInt_t, FairFileSource*> FairRootManager::fSignalTypeList private
Definition at line 368 of file FairRootManager.h.
Referenced by ActivateBranch(), CheckMaxEventNo(), GetSignalChainNo(), OpenSignalChain(), ReadBranchEvent(), ReadMixedEvent(), and SetSignalFile().
UInt_t FairRootManager::fTimeforEntryNo private
for internal use, to return the same event time for the same entry
Definition at line 404 of file FairRootManager.h.
Referenced by GetEventTime(), and SetEventTime().
TF1* FairRootManager::fTimeProb private
used to generate random numbers for event time;
Definition at line 383 of file FairRootManager.h.
Referenced by GetDeltaEventTime(), and SetEventMeanTime().
Bool_t FairRootManager::fTimeStamps private
if kTRUE Read data according to time and not entries
Definition at line 346 of file FairRootManager.h.
Referenced by RunWithTimeStamps().
std::map<TString, FairTSBufferFunctional*> FairRootManager::fTSBufferMap private
Internally used to read time ordered data from branches
Definition at line 339 of file FairRootManager.h.
Referenced by AllDataProcessed(), GetData(), GetTSBuffer(), and RegisterTSBuffer().
Bool_t FairRootManager::fUseFairLinks private
Definition at line 420 of file FairRootManager.h.
Referenced by GetUseFairLinks(), and SetUseFairLinks().
std::map<TString, FairWriteoutBuffer* > FairRootManager::fWriteoutBufferMap private
Definition at line 340 of file FairRootManager.h.
Referenced by DeleteOldWriteoutBufferData(), GetWriteoutBuffer(), RegisterWriteoutBuffer(), StoreAllWriteoutBufferData(), and StoreWriteoutBufferData().
The documentation for this class was generated from the following files:
FairRootManager.h
FairRootManager.cxx