FairRroot: FairEventManagerEditor Class Reference
FairEventManagerEditor Class Reference
#include <FairEventManagerEditor.h>
Public Member Functions
FairEventManagerEditor (const TGWindow *p=0, Int_t width=170, Int_t height=30, UInt_t options=kChildFrame, Pixel_t back=GetDefaultFrameBackground())
virtual ~FairEventManagerEditor ()
void SetModel (TObject *obj)
virtual void SelectEvent ()
virtual void SelectPDG ()
void DoVizPri ()
virtual void MaxEnergy ()
virtual void MinEnergy ()
virtual void Init ()
ClassDef (FairEventManagerEditor, 0)
Protected Attributes
TObject * fObject
FairEventManager * fManager
TGNumberEntry * fCurrentEvent
TGNumberEntry * fCurrentPDG
TGCheckButton * fVizPri
TEveGValuator * fMinEnergy
TEveGValuator * fMaxEnergy
TGLabel * fEventTime
Private Member Functions
FairEventManagerEditor (const FairEventManagerEditor &)
FairEventManagerEditor & operator= (const FairEventManagerEditor &)
Detailed Description
Definition at line 29 of file FairEventManagerEditor.h.
Constructor & Destructor Documentation
FairEventManagerEditor::FairEventManagerEditor (const FairEventManagerEditor &) private
FairEventManagerEditor::FairEventManagerEditor (const TGWindow * p = 0, Int_t width = 170, Int_t height = 30, UInt_t options = kChildFrame, Pixel_t back = GetDefaultFrameBackground())
virtual FairEventManagerEditor::~FairEventManagerEditor () inline virtual
Definition at line 44 of file FairEventManagerEditor.h.
 {}
Member Function Documentation
FairEventManagerEditor::ClassDef (FairEventManagerEditor , 0)
void FairEventManagerEditor::DoVizPri ()
Definition at line 171 of file FairEventManagerEditor.cxx.
References fManager, fVizPri, and FairEventManager::SetPriOnly().
 {
   if (fVizPri->IsOn()) { fManager->SetPriOnly(kTRUE); }
   else { fManager->SetPriOnly(kFALSE); }
 }
void FairEventManagerEditor::Init () virtual
Definition at line 56 of file FairEventManagerEditor.cxx.
References fCurrentEvent, fCurrentPDG, fEventTime, fManager, fMaxEnergy, fMinEnergy, fVizPri, FairRootManager::GetInChain(), FairRunAna::getRunId(), FairRunAna::Instance(), FairRootManager::Instance(), MAXE, and FairEventManager::SetMaxEnergy().
 {
   FairRootManager* fRootManager=FairRootManager::Instance();
   TChain* chain =fRootManager->GetInChain();
   Int_t Entries= chain->GetEntriesFast();
   MakeTitle("FairEventManager  Editor");
   TGVerticalFrame*      fInfoFrame= CreateEditorTabSubFrame("Info");
   TGCompositeFrame* title1 = new TGCompositeFrame(fInfoFrame, 250, 10,
       kVerticalFrame | kLHintsExpandX |
       kFixedWidth    | kOwnBackground);
   TString Infile= "Input file : ";
 //  TFile* file =FairRunAna::Instance()->GetInputFile();
   TFile* file =FairRootManager::Instance()->GetInChain()->GetFile();
   Infile+=file->GetName();
   TGLabel* TFName=new TGLabel(title1, Infile.Data());
   title1->AddFrame(TFName);
   UInt_t RunId= FairRunAna::Instance()->getRunId();
   TString run= "Run Id : ";
   run += RunId;
   TGLabel* TRunId=new TGLabel(title1, run.Data());
   title1->AddFrame( TRunId);
   TString nevent= "No of events : ";
   nevent +=Entries ;
   TGLabel* TEvent=new TGLabel(title1, nevent.Data());
   title1->AddFrame(TEvent);
   Int_t nodes= gGeoManager->GetNNodes();
   TString NNodes= "No. of Nodes : ";
   NNodes += nodes;
   TGLabel* NoNode=new TGLabel(title1, NNodes.Data());
   title1->AddFrame( NoNode);
   TGHorizontalFrame* f = new TGHorizontalFrame(title1);
   TGLabel* l = new TGLabel(f, "Current Event:");
   f->AddFrame(l, new TGLayoutHints(kLHintsLeft | kLHintsCenterY, 1, 2, 1, 1));
   fCurrentEvent = new TGNumberEntry(f, 0., 6, -1,
                                     TGNumberFormat::kNESInteger, TGNumberFormat::kNEANonNegative,
                                     TGNumberFormat::kNELLimitMinMax, 0, Entries);
   f->AddFrame(fCurrentEvent, new TGLayoutHints(kLHintsLeft, 1, 1, 1, 1));
   fCurrentEvent->Connect("ValueSet(Long_t)","FairEventManagerEditor", this, "SelectEvent()");
   title1->AddFrame(f);
   TGHorizontalFrame* f2 = new TGHorizontalFrame(title1);
   TGLabel* EventTimeLabel = new TGLabel(f2, "Event Time: ");
   fEventTime = new TGLabel(f2,"");
   f2->AddFrame(EventTimeLabel);
   f2->AddFrame(fEventTime);
   title1->AddFrame(f2);
   fVizPri = new TGCheckButton(title1, "Primary Only");
   AddFrame(fVizPri, new TGLayoutHints(kLHintsTop, 3, 1, 1, 0));
   fVizPri->Connect("Toggled(Bool_t)", "FairEventManagerEditor", this, "DoVizPri()");
   title1->AddFrame(fVizPri);
   TGHorizontalFrame* f1 = new TGHorizontalFrame(title1);
   TGLabel* L1 = new TGLabel(f1, "Select PDG :");
   f1->AddFrame(L1, new TGLayoutHints(kLHintsLeft | kLHintsCenterY, 1, 2, 1, 1));
   fCurrentPDG = new TGNumberEntry(f1, 0., 12, -1,
                                   TGNumberFormat::kNESInteger, TGNumberFormat::kNEAAnyNumber,
                                   TGNumberFormat::kNELNoLimits, 0, 1);
   f1->AddFrame(fCurrentPDG, new TGLayoutHints(kLHintsLeft, 1, 1, 1, 1));
   fCurrentPDG->Connect("ValueSet(Long_t)","FairEventManagerEditor", this, "SelectPDG()");
   title1->AddFrame(f1);
   fMinEnergy = new TEveGValuator(title1, "Min Energy:", 90, 0);
   fMinEnergy->SetNELength(5);
   fMinEnergy->SetLabelWidth(80);
   fMinEnergy->Build();
   fMinEnergy->SetLimits(0, MAXE, 2501, TGNumberFormat::kNESRealOne);
   fMinEnergy->SetToolTip("Minimum energy of displayed track.");
   fMinEnergy->Connect("ValueSet(Double_t)", "FairEventManagerEditor",this, "MinEnergy()");
   title1->AddFrame(fMinEnergy, new TGLayoutHints(kLHintsTop, 1, 1, 1, 0));
   fMaxEnergy = new TEveGValuator(title1, "Max Energy:", 90, 0);
   fMaxEnergy->SetNELength(5);
   fMaxEnergy->SetLabelWidth(80);
   fMaxEnergy->Build();
   fMaxEnergy->SetLimits(0, MAXE, 2501, TGNumberFormat::kNESRealOne);
   fMaxEnergy->SetToolTip("Maximum energy of displayed track.");
   fMaxEnergy->SetValue(MAXE);
   fMaxEnergy->Connect("ValueSet(Double_t)", "FairEventManagerEditor",this, "MaxEnergy()");
   title1->AddFrame(fMaxEnergy, new TGLayoutHints(kLHintsTop, 1, 1, 1, 0));
   TGTextButton* fUpdate = new TGTextButton(title1, "Update");
   title1->AddFrame(fUpdate, new TGLayoutHints(kLHintsRight | kLHintsExpandX, 5,5,1,1));
   fUpdate->Connect("Clicked()", "FairEventManagerEditor", this, "SelectEvent()");
   fInfoFrame->AddFrame(title1, new TGLayoutHints(kLHintsTop, 0, 0, 2, 0));
   fManager->SetMaxEnergy(MAXE);
 }
void FairEventManagerEditor::MaxEnergy () virtual
Definition at line 158 of file FairEventManagerEditor.cxx.
References fManager, fMaxEnergy, and FairEventManager::SetMaxEnergy().
 {
   fManager->SetMaxEnergy(fMaxEnergy->GetValue());
 }
void FairEventManagerEditor::MinEnergy () virtual
Definition at line 164 of file FairEventManagerEditor.cxx.
References fManager, fMinEnergy, and FairEventManager::SetMinEnergy().
 {
   fManager->SetMinEnergy(fMinEnergy->GetValue());
 }
FairEventManagerEditor& FairEventManagerEditor::operator= (const FairEventManagerEditor &) private
void FairEventManagerEditor::SelectEvent () virtual
Definition at line 183 of file FairEventManagerEditor.cxx.
References fCurrentEvent, fEventTime, fManager, fMaxEnergy, fMinEnergy, FairEventManager::GetEvtMaxEnergy(), FairEventManager::GetEvtMinEnergy(), FairEventManager::GotoEvent(), and FairRootManager::Instance().
 {
   fManager->GotoEvent(fCurrentEvent->GetIntNumber());
   TString time;
 // time+=(FairRootManager::Instance()->GetEventTime());
   time.Form("%.2f", FairRootManager::Instance()->GetEventTime());
   time += " ns";
   fEventTime->SetText(time.Data());
   fMinEnergy->SetLimits(fManager->GetEvtMinEnergy(), fManager->GetEvtMaxEnergy(), 100);
   fMinEnergy->SetValue(fManager->GetEvtMinEnergy());
   fMaxEnergy->SetLimits(fManager->GetEvtMinEnergy(), fManager->GetEvtMaxEnergy(), 100);
   fMaxEnergy->SetValue( fManager->GetEvtMaxEnergy());
   Update();
 }
void FairEventManagerEditor::SelectPDG () virtual
Definition at line 177 of file FairEventManagerEditor.cxx.
References fCurrentPDG, fManager, and FairEventManager::SelectPDG().
 {
   fManager->SelectPDG(fCurrentPDG->GetIntNumber());
 }
void FairEventManagerEditor::SetModel (TObject * obj)
Definition at line 201 of file FairEventManagerEditor.cxx.
References fObject.
 {
   fObject     = obj;
 }
Member Data Documentation
TGNumberEntry* FairEventManagerEditor::fCurrentEvent protected
Definition at line 37 of file FairEventManagerEditor.h.
Referenced by Init(), and SelectEvent().
TGNumberEntry * FairEventManagerEditor::fCurrentPDG protected
Definition at line 37 of file FairEventManagerEditor.h.
Referenced by Init(), and SelectPDG().
TGLabel* FairEventManagerEditor::fEventTime protected
Definition at line 40 of file FairEventManagerEditor.h.
Referenced by Init(), and SelectEvent().
FairEventManager* FairEventManagerEditor::fManager protected
Definition at line 36 of file FairEventManagerEditor.h.
Referenced by DoVizPri(), Init(), MaxEnergy(), MinEnergy(), SelectEvent(), and SelectPDG().
TEveGValuator * FairEventManagerEditor::fMaxEnergy protected
Definition at line 39 of file FairEventManagerEditor.h.
Referenced by Init(), MaxEnergy(), and SelectEvent().
TEveGValuator* FairEventManagerEditor::fMinEnergy protected
Definition at line 39 of file FairEventManagerEditor.h.
Referenced by Init(), MinEnergy(), and SelectEvent().
TObject* FairEventManagerEditor::fObject protected
Definition at line 35 of file FairEventManagerEditor.h.
Referenced by SetModel().
TGCheckButton* FairEventManagerEditor::fVizPri protected
Definition at line 38 of file FairEventManagerEditor.h.
Referenced by DoVizPri(), and Init().
The documentation for this class was generated from the following files:
FairEventManagerEditor.h
FairEventManagerEditor.cxx