FairRroot: run_tutorial1.C File Reference
run_tutorial1.C File Reference
Functions
void run_tutorial1 (Int_t nEvents=10, TString mcEngine="TGeant3")
Function Documentation
void run_tutorial1 (Int_t nEvents = 10, TString mcEngine = "TGeant3")
Definition at line 8 of file run_tutorial1.C.
References FairPrimaryGenerator::AddGenerator(), FairRunSim::AddModule(), FairRun::CreateGeometryFile(), FairRun::GetRuntimeDb(), FairRunSim::Init(), FairParRootFileIo::open(), FairRuntimeDb::print(), FairRunSim::Run(), FairRuntimeDb::saveOutput(), FairBoxGenerator::SetDebug(), FairRunSim::SetGenerator(), FairModule::SetGeometryFileName(), FairRunSim::SetMaterials(), FairRuntimeDb::setOutput(), FairRun::SetOutputFile(), FairBoxGenerator::SetPhiRange(), FairBoxGenerator::SetPRange(), and FairBoxGenerator::SetThetaRange().
 {
   TString dir = getenv("VMCWORKDIR");
   TString tutdir = dir + "/Tutorial1";
   TString tut_geomdir = dir + "/geometry";
   gSystem->Setenv("GEOMPATH",tut_geomdir.Data());
   TString tut_configdir = dir + "/gconfig";
   gSystem->Setenv("CONFIG_DIR",tut_configdir.Data());
   TString partName[] = {"pions","eplus","proton"};
   Int_t   partPdgC[] = {    211,     11,    2212};
   Int_t chosenPart  = 0;
   Double_t momentum = 2.;
   Double_t theta    = 0.;
   TString outDir = "./";
   // Output file name
   TString outFile = Form("%s/tutorial1_%s_%s.mc_p%1.3f_t%1.0f_n%d.root",
                          outDir.Data(),
                          mcEngine.Data(),
                          partName[chosenPart].Data(),
                          momentum,
                          theta,
                          nEvents);
   // Parameter file name
   TString parFile = Form("%s/tutorial1_%s_%s.params_p%1.3f_t%1.0f_n%d.root",
                          outDir.Data(),
                          mcEngine.Data(),
                          partName[chosenPart].Data(),
                          momentum,
                          theta,
                          nEvents);
   // In general, the following parts need not be touched
   // ========================================================================
   // ----    Debug option   -------------------------------------------------
   gDebug = 0;
   // ------------------------------------------------------------------------
   // -----   Timer   --------------------------------------------------------
   TStopwatch timer;
   timer.Start();
   // ------------------------------------------------------------------------
   // -----   Create simulation run   ----------------------------------------
   FairRunSim* run = new FairRunSim();
   run->SetName(mcEngine);              // Transport engine
   run->SetOutputFile(outFile);          // Output file
   FairRuntimeDb* rtdb = run->GetRuntimeDb();
   // ------------------------------------------------------------------------
   // -----   Create media   -------------------------------------------------
   run->SetMaterials("media.geo");       // Materials
   // ------------------------------------------------------------------------
   // -----   Create geometry   ----------------------------------------------
   FairModule* cave= new FairCave("CAVE");
   cave->SetGeometryFileName("cave_vacuum.geo");
   run->AddModule(cave);
   FairDetector* tutdet = new FairTutorialDet1("TUTDET", kTRUE);
   tutdet->SetGeometryFileName("double_sector.geo");
   run->AddModule(tutdet);
   // ------------------------------------------------------------------------
   // -----   Create PrimaryGenerator   --------------------------------------
   FairPrimaryGenerator* primGen = new FairPrimaryGenerator();
   FairBoxGenerator* boxGen = new FairBoxGenerator(partPdgC[chosenPart], 1);
   boxGen->SetThetaRange (   theta,   theta+0.01);
   boxGen->SetPRange     (momentum,momentum+0.01);
   boxGen->SetPhiRange   (0.,360.);
   boxGen->SetDebug(kTRUE);
   primGen->AddGenerator(boxGen);
   run->SetGenerator(primGen);
   // ------------------------------------------------------------------------
   // -----   Initialize simulation run   ------------------------------------
   run->Init();
   // ------------------------------------------------------------------------
   // -----   Runtime database   ---------------------------------------------
   Bool_t kParameterMerged = kTRUE;
   FairParRootFileIo* parOut = new FairParRootFileIo(kParameterMerged);
   parOut->open(parFile.Data());
   rtdb->setOutput(parOut);
   rtdb->saveOutput();
   rtdb->print();
   // ------------------------------------------------------------------------
   // -----   Start run   ----------------------------------------------------
   run->Run(nEvents);
   run->CreateGeometryFile("geofile_full.root");
   // ------------------------------------------------------------------------
   // -----   Finish   -------------------------------------------------------
   timer.Stop();
   Double_t rtime = timer.RealTime();
   Double_t ctime = timer.CpuTime();
   cout << endl << endl;
   cout << "Macro finished succesfully." << endl;
   cout << "Output file is "    << outFile << endl;
   cout << "Parameter file is " << parFile << endl;
   cout << "Real time " << rtime << " s, CPU time " << ctime
        << "s" << endl << endl;
   // ------------------------------------------------------------------------
 }