FairRroot: MyDigiDeSerializer< PodType, DigiType > Class Template Reference
MyDigiDeSerializer< PodType, DigiType > Class Template Reference
#include <MyDigiSerializer.h>
Public Member Functions
MyDigiDeSerializer ()
~MyDigiDeSerializer ()
virtual void DoDeSerialization (FairMQMessage *msg)
virtual TClonesArray * DeSerializeMsg (FairMQMessage *msg)
void InitContainer (const std::string &ClassName)
void InitContainer (TClonesArray *array)
void GetPayload (FairMQMessage *msg)
void SetMessage (FairMQMessage *msg)
FairMQMessage * GetMessage ()
Protected Attributes
TClonesArray * fContainer
PodType * fPayload
FairMQMessage * fMessage
int fNumInput
Detailed Description
template<typename PodType, typename DigiType>
class MyDigiDeSerializer< PodType, DigiType >
Definition at line 84 of file MyDigiSerializer.h.
Constructor & Destructor Documentation
template<typename PodType , typename DigiType > MyDigiDeSerializer< PodType, DigiType >::MyDigiDeSerializer () inline
Definition at line 93 of file MyDigiSerializer.h.
 : BinaryBaseClassSerializer<PodType>(), fContainer(nullptr) {}
template<typename PodType , typename DigiType > MyDigiDeSerializer< PodType, DigiType >::~MyDigiDeSerializer () inline
Definition at line 94 of file MyDigiSerializer.h.
References MyDigiDeSerializer< PodType, DigiType >::fContainer.
     {
         if(fContainer)
             delete fContainer;
         fContainer=nullptr;
     }
Member Function Documentation
template<typename PodType , typename DigiType > virtual TClonesArray* MyDigiDeSerializer< PodType, DigiType >::DeSerializeMsg (FairMQMessage * msg) inline virtual
Definition at line 120 of file MyDigiSerializer.h.
References MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyDigiDeSerializer< PodType, DigiType >::fContainer.
     {
         DoDeSerialization(msg);
         return fContainer;
     }
template<typename PodType , typename DigiType > virtual void MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization (FairMQMessage * msg) inline virtual
Definition at line 101 of file MyDigiSerializer.h.
References ERROR, MyDigiDeSerializer< PodType, DigiType >::fContainer, BinaryBaseClassSerializer< PodType >::fNumInput, BinaryBaseClassSerializer< PodType >::fPayload, fX, fY, fZ, BinaryBaseClassSerializer< PodType >::GetPayload(), and MQLOG.
Referenced by MyDigiDeSerializer< PodType, DigiType >::DeSerializeMsg().
     {
         GetPayload(msg);
         if(fContainer)
         {
             fContainer->Delete();
             for (Int_t i = 0; i < fNumInput; ++i)
             {
                 new ((*fContainer)[i]) DigiType(fPayload[i].fX, fPayload[i].fY, fPayload[i].fZ, fPayload[i].fTimeStamp);
             }
             if (fContainer->IsEmpty())
             {
                 MQLOG(ERROR) << "MyDigiDeSerializer::message(): No Output array!";
             }
         }
     }
FairMQMessage* BinaryBaseClassSerializer< PodType >::GetMessage () inline inherited
Definition at line 37 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fMessage.
     {
         return fMessage;
     }
void BinaryBaseClassSerializer< PodType >::GetPayload (FairMQMessage * msg) inline inherited
Definition at line 24 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fNumInput, BinaryBaseClassSerializer< TPayload >::fPayload, FairMQMessage::GetData(), and FairMQMessage::GetSize().
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
     {
         int inputSize = msg->GetSize();
         if(inputSize>0)
             fNumInput = inputSize / sizeof(TPayload);
         fPayload = static_cast<TPayload*>(msg->GetData());
     }
template<typename PodType , typename DigiType > void MyDigiDeSerializer< PodType, DigiType >::InitContainer (const std::string & ClassName) inline
Definition at line 127 of file MyDigiSerializer.h.
References MyDigiDeSerializer< PodType, DigiType >::fContainer.
     {
         fContainer = new TClonesArray(ClassName.c_str());
     }
template<typename PodType , typename DigiType > void MyDigiDeSerializer< PodType, DigiType >::InitContainer (TClonesArray * array) inline
Definition at line 132 of file MyDigiSerializer.h.
References MyDigiDeSerializer< PodType, DigiType >::fContainer.
     {
         fContainer = array;
     }
void BinaryBaseClassSerializer< PodType >::SetMessage (FairMQMessage * msg) inline inherited
Definition at line 32 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fMessage.
     {
         fMessage=msg;
     }
Member Data Documentation
template<typename PodType , typename DigiType > TClonesArray* MyDigiDeSerializer< PodType, DigiType >::fContainer protected
Definition at line 139 of file MyDigiSerializer.h.
Referenced by MyDigiDeSerializer< PodType, DigiType >::DeSerializeMsg(), MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), MyDigiDeSerializer< PodType, DigiType >::InitContainer(), and MyDigiDeSerializer< PodType, DigiType >::~MyDigiDeSerializer().
FairMQMessage* BinaryBaseClassSerializer< PodType >::fMessage protected inherited
Definition at line 46 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiSerializer< PodType, DigiType >::DoSerialization(), MyHitSerializer< PodType, HitType >::DoSerialization(), MyDigiSerializer< PodType, DigiType >::SerializeMsg(), and MyHitSerializer< PodType, HitType >::SerializeMsg().
int BinaryBaseClassSerializer< PodType >::fNumInput protected inherited
Definition at line 47 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
PodType * BinaryBaseClassSerializer< PodType >::fPayload protected inherited
Definition at line 45 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
The documentation for this class was generated from the following file:
MyDigiSerializer.h