FairRroot: FairMCMatchSelectorTask Class Reference
FairMCMatchSelectorTask Class Reference
#include <FairMCMatchSelectorTask.h>
Public Member Functions
FairMCMatchSelectorTask ()
FairMCMatchSelectorTask (TString start, TString stop)
FairMCMatchSelectorTask (Int_t start, Int_t stop)
virtual ~FairMCMatchSelectorTask ()
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
virtual void Finish ()
virtual void SetStart (Int_t type)
virtual void SetStop (Int_t type)
virtual void SetAllWeights (Float_t weight)
virtual void SetWeightStage (Int_t type, Float_t weight)
virtual void SetWeights ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
void Register ()
void Reset ()
void ProduceHits ()
FairMCMatchSelectorTask (const FairMCMatchSelectorTask &)
FairMCMatchSelectorTask & operator= (const FairMCMatchSelectorTask &)
ClassDef (FairMCMatchSelectorTask, 1)
Private Attributes
FairMCMatch * fMCMatch
Int_t fStart
Int_t fStop
TString fStartString
TString fStopString
std::vector< std::pair< Int_t,
Float_t > > fStageWeights
Float_t fCommonWeight
Detailed Description
Definition at line 34 of file FairMCMatchSelectorTask.h.
Constructor & Destructor Documentation
FairMCMatchSelectorTask::FairMCMatchSelectorTask ()
Default constructor
Definition at line 25 of file FairMCMatchSelectorTask.cxx.
   : FairTask("Creates FairMCMatch"),
     fMCMatch(NULL),
     fStart(-1),
     fStop(-1),
     fStartString(""),
     fStopString(""),
     fStageWeights(),
     fCommonWeight(0)
 {
 }
FairMCMatchSelectorTask::FairMCMatchSelectorTask (TString start, TString stop)
Definition at line 38 of file FairMCMatchSelectorTask.cxx.
   : FairTask("Creates FairMCMatch"),
     fMCMatch(NULL),
     fStart(-1),
     fStop(-1),
     fStartString(start),
     fStopString(stop),
     fStageWeights(),
     fCommonWeight(0)
 {
 }
FairMCMatchSelectorTask::FairMCMatchSelectorTask (Int_t start, Int_t stop)
Definition at line 50 of file FairMCMatchSelectorTask.cxx.
   : FairTask("Creates FairMCMatch"),
     fMCMatch(NULL),
     fStart(start),
     fStop(stop),
     fStartString(""),
     fStopString(""),
     fStageWeights(),
     fCommonWeight(0)
 {
 }
FairMCMatchSelectorTask::~FairMCMatchSelectorTask () virtual
Destructor
Definition at line 63 of file FairMCMatchSelectorTask.cxx.
 {
 }
FairMCMatchSelectorTask::FairMCMatchSelectorTask (const FairMCMatchSelectorTask &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairMCMatchSelectorTask::ClassDef (FairMCMatchSelectorTask , 1) private
void FairMCMatchSelectorTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 99 of file FairMCMatchSelectorTask.cxx.
References FairMCMatch::CreateArtificialStage(), fMCMatch, fStart, fStop, FairMCMatch::GetMCInfo(), and SetWeights().
 {
   std::cout << "Output Selector: " << std::endl;
   SetWeights();
   fMCMatch->CreateArtificialStage("MCTrack");
   std::cout << fMCMatch->GetMCInfo(fStart, fStop);
   std::cout << std::endl;
 }
void FairMCMatchSelectorTask::Finish () virtual
Action after each event. To be implemented in the derived class
Reimplemented from FairTask.
Definition at line 116 of file FairMCMatchSelectorTask.cxx.
 {
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
InitStatus FairMCMatchSelectorTask::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 68 of file FairMCMatchSelectorTask.cxx.
References fMCMatch, fStart, fStartString, fStop, fStopString, FairRootManager::GetBranchId(), FairRootManager::GetObject(), FairRootManager::Instance(), kFATAL, and kSUCCESS.
 {
   FairRootManager* ioman = FairRootManager::Instance();
   if (!ioman) {
     std::cout << "-E- FairMCMatchSelectorTask::Init: "
               << "RootManager not instantiated!" << std::endl;
     return kFATAL;
   }
   fMCMatch = (FairMCMatch*)ioman->GetObject("MCMatch");
   if (fStart < 0 && fStop < 0) {
     fStart = ioman->GetBranchId(fStartString);
     fStop = ioman->GetBranchId(fStopString);
     std::cout << fStartString << ": " << fStart << " / " << fStopString << ": " << fStop << std::endl;
   }
   std::cout << "-I- FairMCMatchSelectorTask::Init: Initialization successfull" << std::endl;
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairMCMatchSelectorTask& FairMCMatchSelectorTask::operator= (const FairMCMatchSelectorTask &) private
void FairMCMatchSelectorTask::ProduceHits () private
void FairMCMatchSelectorTask::Register () private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairMCMatchSelectorTask::Reset () private
virtual void FairMCMatchSelectorTask::SetAllWeights (Float_t weight) inline virtual
Definition at line 62 of file FairMCMatchSelectorTask.h.
References fCommonWeight.
 {fCommonWeight = weight;}
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairMCMatchSelectorTask::SetParContainers () virtual
Virtual method Init
Reimplemented from FairTask.
Definition at line 93 of file FairMCMatchSelectorTask.cxx.
 {
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
virtual void FairMCMatchSelectorTask::SetStart (Int_t type) inline virtual
Definition at line 59 of file FairMCMatchSelectorTask.h.
References fStart.
 {fStart = type;}
virtual void FairMCMatchSelectorTask::SetStop (Int_t type) inline virtual
Definition at line 60 of file FairMCMatchSelectorTask.h.
References fStop.
 {fStop = type;}
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
void FairMCMatchSelectorTask::SetWeights () virtual
Definition at line 108 of file FairMCMatchSelectorTask.cxx.
References fCommonWeight, fMCMatch, fStageWeights, FairMCMatch::GetMCStageType(), FairMCMatch::SetCommonWeightStages(), and FairMCStage::SetWeight().
Referenced by Exec().
 {
   fMCMatch->SetCommonWeightStages(fCommonWeight);
   for (int i = 0; i < fStageWeights.size(); i++) {
     fMCMatch->GetMCStageType(fStageWeights[i].first)->SetWeight(fStageWeights[i].second);
   }
 }
virtual void FairMCMatchSelectorTask::SetWeightStage (Int_t type, Float_t weight) inline virtual
Definition at line 63 of file FairMCMatchSelectorTask.h.
References fStageWeights.
{
       fStageWeights.push_back(std::pair<Int_t, Float_t>(static_cast<Int_t>(type), weight));
     }
Member Data Documentation
Float_t FairMCMatchSelectorTask::fCommonWeight private
Definition at line 78 of file FairMCMatchSelectorTask.h.
Referenced by SetAllWeights(), and SetWeights().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
FairMCMatch* FairMCMatchSelectorTask::fMCMatch private
Definition at line 70 of file FairMCMatchSelectorTask.h.
Referenced by Exec(), Init(), and SetWeights().
std::vector<std::pair<Int_t, Float_t> > FairMCMatchSelectorTask::fStageWeights private
Definition at line 77 of file FairMCMatchSelectorTask.h.
Referenced by SetWeights(), and SetWeightStage().
Int_t FairMCMatchSelectorTask::fStart private
Definition at line 71 of file FairMCMatchSelectorTask.h.
Referenced by Exec(), Init(), and SetStart().
TString FairMCMatchSelectorTask::fStartString private
Definition at line 74 of file FairMCMatchSelectorTask.h.
Referenced by Init().
Int_t FairMCMatchSelectorTask::fStop private
Definition at line 72 of file FairMCMatchSelectorTask.h.
Referenced by Exec(), Init(), and SetStop().
TString FairMCMatchSelectorTask::fStopString private
Definition at line 75 of file FairMCMatchSelectorTask.h.
Referenced by Init().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairMCTracks::Exec(), FairMCStack::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairMCTracks::Init(), FairMCStack::Init(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairMCMatchSelectorTask.h
FairMCMatchSelectorTask.cxx