FairRoot: FairShieldGenerator Class Reference
FairShieldGenerator Class Reference
#include <FairShieldGenerator.h>
Public Member Functions
FairShieldGenerator ()
FairShieldGenerator (const char *fileName)
virtual ~FairShieldGenerator ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
ClassDef (FairGenerator, 1)
Private Member Functions
void CloseInput ()
PDG database.
Int_t RegisterIons ()
FairShieldGenerator (const FairShieldGenerator &)
FairShieldGenerator & operator= (const FairShieldGenerator &)
ClassDef (FairShieldGenerator, 1)
Private Attributes
std::ifstream * fInputFile
const Char_t * fFileName
Input file stream.
TDatabasePDG * fPDG
Input file Name.
std::map< TString, FairIon * > fIonMap
Detailed Description
Definition at line 45 of file FairShieldGenerator.h.
Constructor & Destructor Documentation
FairShieldGenerator::FairShieldGenerator ()
Default constructor without arguments should not be used.
Definition at line 28 of file FairShieldGenerator.cxx.
   :FairGenerator(),
    fInputFile(NULL),
    fFileName(NULL),
    fPDG(NULL),
    fIonMap()
 {
 }
FairShieldGenerator::FairShieldGenerator (const char * fileName)
Standard constructor.
Parameters
fileName The input file name
Definition at line 41 of file FairShieldGenerator.cxx.
References CloseInput(), FairLogger::endl(), FATAL, fFileName, fInputFile, INFO, LOG, and RegisterIons().
   :FairGenerator(),
    fInputFile(NULL),
    fFileName(fileName),
    fPDG(TDatabasePDG::Instance()),
    fIonMap()
 {
   LOG(INFO) << "FairShieldGenerator: Opening input file "
             << fileName << FairLogger::endl;
   fInputFile = new std::ifstream(fFileName);
   if ( ! fInputFile->is_open() ) {
     LOG(FATAL) << "Cannot open input file." << FairLogger::endl;
   }
   LOG(INFO) << "FairShieldGenerator: Looking for ions..."
             << FairLogger::endl;
   Int_t nIons = RegisterIons();
   LOG(INFO) << "FairShieldGenerator: " << nIons << " ions registered."
             << FairLogger::endl;
   CloseInput();
   LOG(INFO) << "FairShieldGenerator: Reopening input file "
             << fileName << FairLogger::endl;
   fInputFile = new std::ifstream(fFileName);
 }
FairShieldGenerator::~FairShieldGenerator () virtual
Destructor.
Definition at line 70 of file FairShieldGenerator.cxx.
References CloseInput().
 {
   CloseInput();
 }
FairShieldGenerator::FairShieldGenerator (const FairShieldGenerator &) private
Member Function Documentation
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
FairShieldGenerator::ClassDef (FairShieldGenerator , 1) private
FairGenerator * FairGenerator::CloneGenerator () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
 {
   Fatal("CloneGenerator","Has to be overriden in multi-threading applications.");
   return 0;
 }
void FairShieldGenerator::CloseInput () private
PDG database.
Private method CloseInput. Just for convenience. Closes the input file properly. Called from destructor and from ReadEvent.
Definition at line 153 of file FairShieldGenerator.cxx.
References FairLogger::endl(), fFileName, fInputFile, INFO, and LOG.
Referenced by FairShieldGenerator(), ReadEvent(), and ~FairShieldGenerator().
 {
   if ( fInputFile ) {
     if ( fInputFile->is_open() ) {
       LOG(INFO) << "FairShieldGenerator: Closing input file "
                 << fFileName << FairLogger::endl;
       fInputFile->close();
     }
     delete fInputFile;
     fInputFile = NULL;
   }
 }
virtual Bool_t FairGenerator::Init () inline virtual inherited
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
 { return kTRUE;}
FairShieldGenerator& FairShieldGenerator::operator= (const FairShieldGenerator &) private
Bool_t FairShieldGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Reads on event from the input file and pushes the tracks onto the stack. Abstract method in base class.
Parameters
primGen pointer to the FairPrimaryGenerator
Implements FairGenerator.
Definition at line 79 of file FairShieldGenerator.cxx.
References FairPrimaryGenerator::AddTrack(), CloseInput(), FairLogger::endl(), ERROR, fInputFile, fPDG, INFO, LOG, and WARNING.
 {
   // Check for input file
   if ( ! fInputFile->is_open() ) {
     LOG(ERROR) << "FairShieldGenerator: Input file not open!"
                << FairLogger::endl;
     return kFALSE;
   }
   // Define event variable to be read from file
   Int_t    eventId = 0;
   Int_t    nTracks = 0;
   Double_t pBeam   = 0.;
   Double_t b       = 0.;
   // Define track variables to be read from file
   Int_t    iPid    = 0;
   Int_t    iMass   = 0;
   Int_t    iCharge = 0;
   Double_t px      = 0.;
   Double_t py      = 0.;
   Double_t pz      = 0.;
   Int_t    pdgType = 0;
   // Read event header line from input file
   *fInputFile >> eventId >> nTracks >> pBeam >> b;
   // If end of input file is reached : close it and abort run
   if ( fInputFile->eof() ) {
     LOG(INFO) << "FairShieldGenerator: End of input file reached "
               << FairLogger::endl;
     CloseInput();
     return kFALSE;
   }
   LOG(INFO) << "FairShieldGenerator: Event " << eventId << ",  pBeam = "
             << pBeam << "GeV, b = " << b << " fm, multiplicity " << nTracks
             << FairLogger::endl;
   // Loop over tracks in the current event
   for (Int_t itrack=0; itrack<nTracks; itrack++) {
     // Read PID and momentum from file
     *fInputFile >> iPid >> iMass >> iCharge >> px >> py >> pz;
     // Case ion
     if ( iPid == 1000 ) {
       char ionName[20];
       sprintf(ionName, "Ion_%d_%d", iMass, iCharge);
       TParticlePDG* part = fPDG->GetParticle(ionName);
       if ( ! part ) {
         LOG(WARNING) << "FairShieldGenerator::ReadEvent: Cannot find "
                      << ionName << " in database!"
                      << FairLogger::endl;
         continue;
       }
       pdgType = part->PdgCode();
     } else { pdgType = fPDG->ConvertGeant3ToPdg(iPid); } // "normal" particle
     // Give track to PrimaryGenerator
     primGen->AddTrack(pdgType, px, py, pz, 0., 0., 0.);
   }
   return kTRUE;
 }
Int_t FairShieldGenerator::RegisterIons () private
Private method RegisterIons. Goes through the input file and registers any ion needed.
Definition at line 170 of file FairShieldGenerator.cxx.
References FairRunSim::AddNewIon(), buffer, fInputFile, fIonMap, and FairRunSim::Instance().
Referenced by FairShieldGenerator().
 {
   Int_t nIons = 0;
   Int_t eventId, nTracks, iPid, iMass, iCharge;
   Double_t pBeam, b, px, py, pz;
   fIonMap.clear();
   while ( ! fInputFile->eof()) {
     *fInputFile >> eventId >> nTracks >> pBeam >> b;
     if ( fInputFile->eof() ) { continue; }
     for (Int_t iTrack=0; iTrack<nTracks; iTrack++) {
       *fInputFile >> iPid >> iMass >> iCharge >> px >> py >> pz;
       if ( iPid == 1000 ) { // ion
         char buffer[20];
         sprintf(buffer, "Ion_%d_%d", iMass, iCharge);
         TString ionName(buffer);
         if ( fIonMap.find(ionName) == fIonMap.end() ) { // new ion
           FairIon* ion = new FairIon(ionName, iCharge, iMass, iCharge);
           fIonMap[ionName] = ion;
           nIons++;
         }  // new ion
       }    // ion
     }      // track loop
   }        // event loop
   FairRunSim* run = FairRunSim::Instance();
   map<TString, FairIon*>::iterator mapIt;
   for (mapIt=fIonMap.begin(); mapIt!=fIonMap.end(); mapIt++) {
     FairIon* ion = (*mapIt).second;
     run->AddNewIon(ion);
   }
   return nIons;
 }
Member Data Documentation
const Char_t* FairShieldGenerator::fFileName private
Input file stream.
Definition at line 75 of file FairShieldGenerator.h.
Referenced by CloseInput(), and FairShieldGenerator().
std::ifstream* FairShieldGenerator::fInputFile private
Definition at line 74 of file FairShieldGenerator.h.
Referenced by CloseInput(), FairShieldGenerator(), ReadEvent(), and RegisterIons().
std::map<TString, FairIon*> FairShieldGenerator::fIonMap private
STL map from ion name to FairIon
Definition at line 91 of file FairShieldGenerator.h.
Referenced by RegisterIons().
TDatabasePDG* FairShieldGenerator::fPDG private
Input file Name.
Definition at line 76 of file FairShieldGenerator.h.
Referenced by ReadEvent().
The documentation for this class was generated from the following files:
FairShieldGenerator.h
FairShieldGenerator.cxx