FairRoot: FairIonGenerator Class Reference
FairIonGenerator Class Reference
#include <FairIonGenerator.h>
Public Member Functions
FairIonGenerator ()
FairIonGenerator (const Char_t *ionName, Int_t mult, Double_t px, Double_t py, Double_t pz, Double_t vx=0, Double_t vy=0, Double_t vz=0)
FairIonGenerator (Int_t z, Int_t a, Int_t q, Int_t mult, Double_t px, Double_t py, Double_t pz, Double_t vx=0, Double_t vy=0, Double_t vz=0)
virtual ~FairIonGenerator ()
void SetCharge (Int_t charge)
void SetExcitationEnergy (Double_t eExc)
void SetMass (Double_t mass)
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
ClassDef (FairGenerator, 1)
Private Member Functions
FairIonGenerator (const FairIonGenerator &)
FairIonGenerator & operator= (const FairIonGenerator &)
Private Attributes
Int_t fMult
Number of the instance of this class.
Double_t fPx
Double_t fPy
Double_t fPz
Double_t fVx
Double_t fVy
Double_t fVz
FairIon * fIon
Int_t fQ
Static Private Attributes
static Int_t fgNIon = 0
Detailed Description
Definition at line 27 of file FairIonGenerator.h.
Constructor & Destructor Documentation
FairIonGenerator::FairIonGenerator ()
Default constructor
Definition at line 35 of file FairIonGenerator.cxx.
   :FairGenerator(),
    fMult(0),
    fPx(0), fPy(0), fPz(0),
    fVx(0), fVy(0), fVz(0),
    fIon(NULL),  fQ(0)
 {
 //  LOG(WARNING) << "FairIonGenerator: "
 //               << " Please do not use the default constructor! "
 //               << FairLogger::endl;
 }
FairIonGenerator::FairIonGenerator (const Char_t * ionName, Int_t mult, Double_t px, Double_t py, Double_t pz, Double_t vx = 0, Double_t vy = 0, Double_t vz = 0)
Constructor with ion name For the generation of ions with pre-defined FairIon By default, the excitation energy is zero. This can be changed with the respective modifiers.
Parameters
ionName Ion name
mult Number of ions per event
px,py,pz Momentum components [GeV] per nucleon!
vx,vy,vz Vertex coordinates [cm]
Definition at line 48 of file FairIonGenerator.cxx.
References FairLogger::endl(), FATAL, fgNIon, fIon, fMult, fPx, fPy, fPz, fVx, fVy, fVz, FairIon::GetA(), FairParticle::GetParticle(), FairRunSim::GetUserDefIons(), FairRunSim::GetUserDefParticles(), FairRunSim::Instance(), and LOG.
   :FairGenerator(),
    fMult(mult),
    fPx(px), fPy(py), fPz(pz),
    fVx(vx), fVy(vy), fVz(vz),
    fIon(NULL),  fQ(0)
 {
   FairRunSim* fRun=FairRunSim::Instance();
   TObjArray* UserIons=fRun->GetUserDefIons();
   TObjArray* UserParticles=fRun->GetUserDefParticles();
   FairParticle* part=0;
   fIon =(FairIon*) UserIons->FindObject(ionName);
   if(fIon) {
     fgNIon++;
     fMult = mult;
     fPx   = Double_t(fIon->GetA()) * px;
     fPy   = Double_t(fIon->GetA()) * py;
     fPz   = Double_t(fIon->GetA()) * pz;
     fVx   = vx;
     fVy   = vy;
     fVz   = vz;
   } else {
     part= (FairParticle*)UserParticles->FindObject(ionName);
     if(part) {
       fgNIon++;
       TParticle* particle=part->GetParticle();
       fMult = mult;
       fPx   = Double_t(particle->GetMass()/0.92827231) * px;
       fPy   = Double_t(particle->GetMass()/0.92827231) * py;
       fPz   = Double_t(particle->GetMass()/0.92827231) * pz;
       fVx   = vx;
       fVy   = vy;
       fVz   = vz;
     }
   }
   if(fIon==0 && part==0 ) {
     LOG(FATAL) << "Ion or Particle is not defined !"
                << FairLogger::endl;
   }
 }
FairIonGenerator::FairIonGenerator (Int_t z, Int_t a, Int_t q, Int_t mult, Double_t px, Double_t py, Double_t pz, Double_t vx = 0, Double_t vy = 0, Double_t vz = 0)
Default constructor For the generation of ions with atomic number z and mass number a. By default, the mass equals a times the proton mass and the excitation energy is zero. This can be changed with the respective modifiers.
Parameters
z Atomic number
a Atomic mass
q Electric charge [e]
mult Number of ions per event
px,py,pz Momentum components [GeV] per nucleon!
vx,vy,vz Vertex coordinates [cm]
Definition at line 99 of file FairIonGenerator.cxx.
References FairRunSim::AddNewIon(), buffer, FairLogger::endl(), ERROR, fgNIon, fIon, FairRunSim::Instance(), and LOG.
   :FairGenerator(),
    fMult(mult),
    fPx(Double_t(a)*px), fPy(Double_t(a)*py), fPz(Double_t(a)*pz),
    fVx(vx), fVy(vy), fVz(vz),
    fIon(NULL),  fQ(0)
 {
   fgNIon++;
   /*
   fMult = mult;
   fPx   = Double_t(a) * px;
   fPy   = Double_t(a) * py;
   fPz   = Double_t(a) * pz;
   fVx   = vx;
   fVy   = vy;
   fVz   = vz;
   */
   char buffer[20];
   sprintf(buffer, "FairIon%d", fgNIon);
   fIon= new FairIon(buffer, z, a, q);
   FairRunSim* run = FairRunSim::Instance();
   if ( ! run ) {
     LOG(ERROR) << "No FairRun instantised!"
                << FairLogger::endl;
   } else {
     run->AddNewIon(fIon);
   }
 }
FairIonGenerator::~FairIonGenerator () virtual
Destructor
Definition at line 135 of file FairIonGenerator.cxx.
 {
 // if (fIon) delete fIon;
 }
FairIonGenerator::FairIonGenerator (const FairIonGenerator &) private
Member Function Documentation
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
FairGenerator * FairGenerator::CloneGenerator () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
 {
   Fatal("CloneGenerator","Has to be overriden in multi-threading applications.");
   return 0;
 }
virtual Bool_t FairGenerator::Init () inline virtual inherited
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
 { return kTRUE;}
FairIonGenerator& FairIonGenerator::operator= (const FairIonGenerator &) private
Bool_t FairIonGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Method ReadEvent Generates <mult> of the specified ions and hands hem to the FairPrimaryGenerator.
Implements FairGenerator.
Definition at line 162 of file FairIonGenerator.cxx.
References FairPrimaryGenerator::AddTrack(), FairLogger::endl(), fIon, fMult, fPx, fPy, fPz, fVx, fVy, fVz, INFO, LOG, and WARNING.
 {
 // if ( ! fIon ) {
 //   LOG(WARNING) << "FairIonGenerator: No ion defined! "
 //                << FairLogger::endl;
 //   return kFALSE;
 // }
   TParticlePDG* thisPart =
     TDatabasePDG::Instance()->GetParticle(fIon->GetName());
   if ( ! thisPart ) {
     LOG(WARNING) << "FairIonGenerator: Ion " << fIon->GetName()
                  << " not found in database!" << FairLogger::endl;
     return kFALSE;
   }
   int pdgType = thisPart->PdgCode();
   LOG(INFO) << "FairIonGenerator: Generating " << fMult << " ions of type "
             << fIon->GetName() << " (PDG code " << pdgType << ")"
             << FairLogger::endl;
   LOG(INFO) << "    Momentum (" << fPx << ", " << fPy << ", " << fPz
             << ") Gev from vertex (" << fVx << ", " << fVy
             << ", " << fVz << ") cm" << FairLogger::endl;
   for(Int_t i=0; i<fMult; i++) {
     primGen->AddTrack(pdgType, fPx, fPy, fPz, fVx, fVy, fVz);
   }
   return kTRUE;
 }
void FairIonGenerator::SetCharge (Int_t charge) inline
Modifiers
Definition at line 72 of file FairIonGenerator.h.
References fQ.
 {fQ=charge;}
void FairIonGenerator::SetExcitationEnergy (Double_t eExc)
Definition at line 144 of file FairIonGenerator.cxx.
References fIon, and FairIon::SetExcEnergy().
 {
   fIon->SetExcEnergy(eExc);
 }
void FairIonGenerator::SetMass (Double_t mass)
Definition at line 153 of file FairIonGenerator.cxx.
References fIon, and FairIon::SetMass().
 {
   fIon->SetMass(mass);
 }
Member Data Documentation
Int_t FairIonGenerator::fgNIon = 0 static private
Definition at line 86 of file FairIonGenerator.h.
Referenced by FairIonGenerator().
FairIon* FairIonGenerator::fIon private
Definition at line 90 of file FairIonGenerator.h.
Referenced by FairIonGenerator(), ReadEvent(), SetExcitationEnergy(), and SetMass().
Int_t FairIonGenerator::fMult private
Number of the instance of this class.
Definition at line 87 of file FairIonGenerator.h.
Referenced by FairIonGenerator(), and ReadEvent().
Double_t FairIonGenerator::fPx private
Definition at line 88 of file FairIonGenerator.h.
Referenced by FairIonGenerator(), and ReadEvent().
Double_t FairIonGenerator::fPy private
Definition at line 88 of file FairIonGenerator.h.
Referenced by FairIonGenerator(), and ReadEvent().
Double_t FairIonGenerator::fPz private
Definition at line 88 of file FairIonGenerator.h.
Referenced by FairIonGenerator(), and ReadEvent().
Int_t FairIonGenerator::fQ private
Definition at line 91 of file FairIonGenerator.h.
Referenced by SetCharge().
Double_t FairIonGenerator::fVx private
Definition at line 89 of file FairIonGenerator.h.
Referenced by FairIonGenerator(), and ReadEvent().
Double_t FairIonGenerator::fVy private
Definition at line 89 of file FairIonGenerator.h.
Referenced by FairIonGenerator(), and ReadEvent().
Double_t FairIonGenerator::fVz private
Definition at line 89 of file FairIonGenerator.h.
Referenced by FairIonGenerator(), and ReadEvent().
The documentation for this class was generated from the following files:
FairIonGenerator.h
FairIonGenerator.cxx