FairRroot: RootDeSerializer Class Reference
RootDeSerializer Class Reference
#include <RootSerializer.h>
Public Member Functions
RootDeSerializer ()
~RootDeSerializer ()
void InitContainer (const std::string &ClassName)
void InitContainer (TClonesArray *array)
virtual void DoDeSerialization (FairMQMessage *msg)
virtual TClonesArray * DeSerializeMsg (FairMQMessage *msg)
void SetMessage (FairMQMessage *msg)
FairMQMessage * GetMessage ()
Protected Attributes
TClonesArray * fContainer
FairMQMessage * fMessage
int fNumInput
Detailed Description
Definition at line 100 of file RootSerializer.h.
Constructor & Destructor Documentation
RootDeSerializer::RootDeSerializer () inline
Definition at line 105 of file RootSerializer.h.
 : fContainer(nullptr), fMessage(nullptr), fNumInput(0) {}
RootDeSerializer::~RootDeSerializer () inline
Definition at line 106 of file RootSerializer.h.
 {}
Member Function Documentation
virtual TClonesArray* RootDeSerializer::DeSerializeMsg (FairMQMessage * msg) inline virtual
Definition at line 127 of file RootSerializer.h.
References DoDeSerialization(), and fContainer.
     {
         DoDeSerialization(msg);
         return fContainer;
     }
virtual void RootDeSerializer::DoDeSerialization (FairMQMessage * msg) inline virtual
Definition at line 121 of file RootSerializer.h.
References fContainer, FairMQMessage::GetData(), and FairMQMessage::GetSize().
Referenced by DeSerializeMsg().
     {
         FairTMessage tm(msg->GetData(), msg->GetSize());
         fContainer  = (TClonesArray*)(tm.ReadObject(tm.GetClass()));
     }
FairMQMessage* RootDeSerializer::GetMessage () inline
Definition at line 138 of file RootSerializer.h.
References fMessage.
     {
         return fMessage;
     }
void RootDeSerializer::InitContainer (const std::string & ClassName) inline
Definition at line 108 of file RootSerializer.h.
References fContainer.
     {
         fContainer = new TClonesArray(ClassName.c_str());
     }
void RootDeSerializer::InitContainer (TClonesArray * array) inline
Definition at line 113 of file RootSerializer.h.
References fContainer.
     {
         fContainer = array;
     }
void RootDeSerializer::SetMessage (FairMQMessage * msg) inline
Definition at line 133 of file RootSerializer.h.
References fMessage.
     {
         fMessage=msg;
     }
Member Data Documentation
TClonesArray* RootDeSerializer::fContainer protected
Definition at line 147 of file RootSerializer.h.
Referenced by DeSerializeMsg(), DoDeSerialization(), and InitContainer().
FairMQMessage* RootDeSerializer::fMessage protected
Definition at line 148 of file RootSerializer.h.
Referenced by GetMessage(), and SetMessage().
int RootDeSerializer::fNumInput protected
Definition at line 149 of file RootSerializer.h.
The documentation for this class was generated from the following file:
RootSerializer.h