FairRroot: Pythia6Generator Class Reference
Pythia6Generator Class Reference
#include <Pythia6Generator.h>
Public Member Functions
Pythia6Generator ()
Pythia6Generator (const char *fileName)
virtual ~Pythia6Generator ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)
void SetVerbose (Int_t verb)
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
ClassDef (FairGenerator, 1)
Private Member Functions
void CloseInput ()
Verbose Level.
ClassDef (Pythia6Generator, 1)
Private Attributes
const Char_t * fFileName
FILE * fInputFile
Input file Name.
Int_t fVerbose
File.
Detailed Description
Definition at line 72 of file Pythia6Generator.h.
Constructor & Destructor Documentation
Pythia6Generator::Pythia6Generator ()
Default constructor without arguments should not be used.
Definition at line 27 of file Pythia6Generator.cxx.
 {}
Pythia6Generator::Pythia6Generator (const char * fileName)
Standard constructor.
Parameters
fileName The input file name
Definition at line 33 of file Pythia6Generator.cxx.
References fFileName, fInputFile, and fVerbose.
{
   fFileName  = fileName;
   fVerbose = 0;
   cout << "-I Pythia6Generator: Opening input file " << fileName << endl;
   if ((fInputFile = fopen(fFileName,"r"))==NULL)
     //  fInputFile = new ifstream(fFileName);
     //  if ( ! fInputFile->is_open() )
     Fatal("Pythia6Generator","Cannot open input file.");
   // fPDG=TDatabasePDG::Instance();
 }
Pythia6Generator::~Pythia6Generator () virtual
Destructor.
Definition at line 49 of file Pythia6Generator.cxx.
References CloseInput().
{
   CloseInput();
 }
Member Function Documentation
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
Pythia6Generator::ClassDef (Pythia6Generator , 1) private
PDG data base
FairGenerator * FairGenerator::CloneGenerator () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
 {
   Fatal("CloneGenerator","Has to be overriden in multi-threading applications.");
   return 0;
 }
void Pythia6Generator::CloseInput () private
Verbose Level.
Private method CloseInput. Just for convenience. Closes the input file properly. Called from destructor and from ReadEvent.
Definition at line 121 of file Pythia6Generator.cxx.
References fFileName, and fInputFile.
Referenced by ReadEvent(), and ~Pythia6Generator().
{
   if ( fInputFile ) {
     //if ( fInputFile->is_open() ) {
     {
       cout << "-I Pythia6Generator: Closing input file "
            << fFileName << endl;
       //  fInputFile->close();
       fclose(fInputFile);
     }
     delete fInputFile;
     fInputFile = NULL;
   }
 }
virtual Bool_t FairGenerator::Init () inline virtual inherited
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
 { return kTRUE;}
Bool_t Pythia6Generator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Reads on event from the input file and pushes the tracks onto the stack. Abstract method in base class.
Parameters
primGen pointer to the CbmrimaryGenerator
Implements FairGenerator.
Definition at line 57 of file Pythia6Generator.cxx.
References FairPrimaryGenerator::AddTrack(), buffer, CloseInput(), fInputFile, and fVerbose.
{
   // Check for input file
   if (!fInputFile) {
     // if ( ! fInputFile->is_open() ) {
     cout << "-E Pythia6Generator: Input file not open!" << endl;
     return kFALSE;
   }
   // Define event variable to be read from file
    Int_t ntracks = 0, eventID = 0, ncols = 0;
   // Define track variables to be read from file
   Int_t nLev = 0, pdgID = 0, nM1 = -1, nM2 = -1, nDF = -1, nDL = -1;
   Float_t fPx = 0., fPy = 0., fPz = 0., fM = 0., fE = 0.;
   Float_t fVx = 0., fVy = 0., fVz = 0., fT = 0.;
   // Read event header line from input file
   Int_t max_nr = 0;
   Text_t buffer[200];
   ncols = fscanf(fInputFile,"%d\t%d", &eventID, &ntracks);
   if (ncols && ntracks>0) {
     if (fVerbose>0) cout << "Event number: " << eventID << "\tNtracks: " << ntracks << endl;
     for (Int_t ll=0; ll<ntracks; ll++)
       {
         ncols = fscanf(fInputFile,"%d %d %d %d %d %d %f %f %f %f %f %f %f %f %f", &nLev, &pdgID, &nM1, &nM2, &nDF, &nDL, &fPx, &fPy, &fPz, &fE, &fM, &fVx, &fVy, &fVz, &fT);
         if (fVerbose>0) cout << nLev << "\t" << pdgID << "\t" << nM1 << "\t" << nM2 << "\t" << nDF << "\t" << nDL <<
           "\t" << fPx << "\t" << fPy << "\t" << fPz << "\t" << fE << "\t" << fM << "\t" << fVx << "\t" << fVy << "\t" << fVz << "\t" << fT <<  endl;
         if (nLev==1)
           primGen->AddTrack(pdgID, fPx, fPy, fPz, fVx, fVy, fVz);
       }
   }
   else {
     cout << "-I Pythia6Generator: End of input file reached " << endl;
     CloseInput();
     return kFALSE;
   }
   // If end of input file is reached : close it and abort run
   if ( feof(fInputFile) ) {
     cout << "-I Pythia6Generator: End of input file reached " << endl;
     CloseInput();
     return kFALSE;
   }
   /*
     cout << "-I Pythia6Generator: Event " << eventID << ",  vertex = ("
     << vx << "," << vy << "," << vz << ") cm,  multiplicity "
     << ntracks << endl;
   */
   return kTRUE;
 }
void Pythia6Generator::SetVerbose (Int_t verb) inline
Definition at line 97 of file Pythia6Generator.h.
References fVerbose.
 { fVerbose = verb; };
Member Data Documentation
const Char_t* Pythia6Generator::fFileName private
Definition at line 97 of file Pythia6Generator.h.
Referenced by CloseInput(), and Pythia6Generator().
FILE* Pythia6Generator::fInputFile private
Input file Name.
Definition at line 103 of file Pythia6Generator.h.
Referenced by CloseInput(), Pythia6Generator(), and ReadEvent().
Int_t Pythia6Generator::fVerbose private
File.
Definition at line 104 of file Pythia6Generator.h.
Referenced by Pythia6Generator(), ReadEvent(), and SetVerbose().
The documentation for this class was generated from the following files:
Pythia6Generator.h
Pythia6Generator.cxx