FairRoot: FairGeoCompositeVolume Class Reference
FairGeoCompositeVolume Class Reference
#include <FairGeoCompositeVolume.h>
Public Member Functions
FairGeoCompositeVolume (Int_t nComp=0)
~FairGeoCompositeVolume ()
Int_t getNumComponents ()
FairGeoVolume * getComponent (const Int_t)
void createComponents (const Int_t)
void setComponent (FairGeoVolume *, const Int_t)
void clear ()
void print ()
ClassDef(FairGeoCompositeVolume, 1) private FairGeoCompositeVolume & operator= (const FairGeoCompositeVolume &)
const TString & getName () const
const TString & getShape () const
const TString & getMother () const
FairGeoTransform & getTransform ()
FairGeoTransform & getLabTransform ()
FairGeoMedium & getMedium ()
Int_t getNumPoints ()
FairGeoVector * getPoint (const Int_t n)
void setName (const Text_t *s)
void setVolumePar (FairGeoVolume &)
void setShape (const Text_t *s)
void setMother (const Text_t *s)
void createPoints (const Int_t)
void setPoint (const Int_t, const Double_t, const Double_t, const Double_t)
void setPoint (const Int_t, const FairGeoVector &)
virtual void setHadFormat (Int_t i)
Double_t getVolParameter (Int_t nPoint, Int_t pos)
Int_t getMCid ()
void setMCid (Int_t MCid)
Protected Attributes
TObjArray * components
TString shape
TString mother
TObjArray * points
FairGeoTransform transform
FairGeoTransform fLabTransform
FairGeoMedium fMedium
Int_t nPoints
Int_t fHadFormat
Int_t fgMCid
Detailed Description
basic geometry of a volume with components
Author
Ilse koenig
Definition at line 20 of file FairGeoCompositeVolume.h.
Constructor & Destructor Documentation
FairGeoCompositeVolume::FairGeoCompositeVolume (Int_t nComp = 0)
FairGeoCompositeVolume::~FairGeoCompositeVolume ()
Definition at line 35 of file FairGeoCompositeVolume.cxx.
References components.
 {
   if (components) { components->Delete(); }
   delete components;
 }
Member Function Documentation
void FairGeoCompositeVolume::clear (void) virtual
Reimplemented from FairGeoVolume.
Definition at line 68 of file FairGeoCompositeVolume.cxx.
References FairGeoVolume::clear(), components, and getNumComponents().
 {
   FairGeoVolume::clear();
   Int_t n=getNumComponents();
   for(Int_t i=0; i<n; i++) { ((FairGeoVolume*)components->At(i))->clear(); }
 }
void FairGeoCompositeVolume::createComponents (const Int_t n)
Definition at line 52 of file FairGeoCompositeVolume.cxx.
References components.
 {
   if (components) {
     components->Delete();
   } else {
     components=new TObjArray();
   }
   components->Expand(n);
 }
void FairGeoVolume::createPoints (const Int_t n) inherited
Definition at line 68 of file FairGeoVolume.cxx.
References FairGeoVolume::nPoints, and FairGeoVolume::points.
Referenced by FairGeoOldAsciiIo::calculateShapePoints(), FairGeoTorus::readPoints(), FairGeoTube::readPoints(), FairGeoTubs::readPoints(), FairGeoCons::readPoints(), FairGeoPgon::readPoints(), FairGeoEltu::readPoints(), FairGeoSphe::readPoints(), FairGeoPcon::readPoints(), FairGeoCone::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), and FairGeoNode::setVolumePar().
 {
   // Creates n Points (objects of class FairGeoVector).
   // If the array exists already and the size is different from n it is
   // deleted and recreated with the new size n.
   // If n==0 the points are deleted.
   if (n!=nPoints) {
     nPoints=n;
     if (n>0) {
       if (points!=0) {
         points->Delete();
         delete points;
       }
       points=new TObjArray(n);
       for(Int_t i=0; i<n; i++) { points->AddAt(new FairGeoVector(),i); }
     } else {
       if (points) { points->Delete(); }
       delete points;
       points=0;
     }
   }
 }
FairGeoVolume * FairGeoCompositeVolume::getComponent (const Int_t n)
Definition at line 47 of file FairGeoCompositeVolume.cxx.
References components.
 {
   return (FairGeoVolume*)components->At(n);
 }
FairGeoTransform& FairGeoVolume::getLabTransform () inline inherited
Definition at line 50 of file FairGeoVolume.h.
References FairGeoVolume::fLabTransform.
 { return fLabTransform;}
Int_t FairGeoVolume::getMCid () inline inherited
Definition at line 65 of file FairGeoVolume.h.
References FairGeoVolume::fgMCid.
Referenced by FairModule::ProcessNodes().
 {return fgMCid;}
FairGeoMedium& FairGeoVolume::getMedium () inline inherited
Definition at line 51 of file FairGeoVolume.h.
References FairGeoVolume::fMedium.
 { return fMedium;}
const TString& FairGeoVolume::getMother () const inline inherited
Definition at line 48 of file FairGeoVolume.h.
References FairGeoVolume::mother.
Referenced by FairGeoNode::compare(), and FairGeoVolume::setVolumePar().
 { return mother; }
const TString& FairGeoVolume::getName () const inline inherited
Definition at line 46 of file FairGeoVolume.h.
 { return fName; }
Int_t FairGeoCompositeVolume::getNumComponents ()
Definition at line 41 of file FairGeoCompositeVolume.cxx.
References components.
Referenced by clear().
 {
   if (components) { return components->GetSize(); }
   else { return 0; }
 }
Int_t FairGeoVolume::getNumPoints () inline inherited
Definition at line 52 of file FairGeoVolume.h.
References FairGeoVolume::nPoints.
Referenced by FairGeoPcon::calcVoluParam(), FairGeoPgon::calcVoluParam(), FairGeoNode::compare(), FairGeoPcon::printPoints(), FairGeoPgon::printPoints(), FairGeoBasicShape::printPoints(), FairGeoTorus::readPoints(), FairGeoTube::readPoints(), FairGeoTubs::readPoints(), FairGeoCons::readPoints(), FairGeoSphe::readPoints(), FairGeoCone::readPoints(), FairGeoEltu::readPoints(), FairGeoPgon::readPoints(), FairGeoPcon::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), FairGeoNode::setVolumePar(), FairGeoPgon::writePoints(), FairGeoPcon::writePoints(), and FairGeoBasicShape::writePoints().
 { return nPoints;}
FairGeoVector * FairGeoVolume::getPoint (const Int_t n) inline inherited
Definition at line 88 of file FairGeoVolume.h.
References FairGeoVolume::nPoints, and FairGeoVolume::points.
Referenced by FairGeoBrik::calcVoluParam(), FairGeoTube::calcVoluParam(), FairGeoTubs::calcVoluParam(), FairGeoTorus::calcVoluParam(), FairGeoTrd1::calcVoluParam(), FairGeoTrap::calcVoluParam(), FairGeoCons::calcVoluParam(), FairGeoEltu::calcVoluParam(), FairGeoCone::calcVoluParam(), FairGeoPcon::calcVoluParam(), FairGeoPgon::calcVoluParam(), FairGeoSphe::calcVoluParam(), FairGeoBrik::calcVoluPosition(), FairGeoTube::calcVoluPosition(), FairGeoTubs::calcVoluPosition(), FairGeoTrap::calcVoluPosition(), FairGeoTrd1::calcVoluPosition(), FairGeoCons::calcVoluPosition(), FairGeoEltu::calcVoluPosition(), FairGeoCone::calcVoluPosition(), FairGeoNode::compare(), FairGeoTorus::printPoints(), FairGeoAssembly::printPoints(), FairGeoTube::printPoints(), FairGeoTubs::printPoints(), FairGeoCons::printPoints(), FairGeoEltu::printPoints(), FairGeoPcon::printPoints(), FairGeoPgon::printPoints(), FairGeoCone::printPoints(), FairGeoSphe::printPoints(), FairGeoBasicShape::printPoints(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), FairGeoNode::setVolumePar(), FairGeoTubs::writePoints(), FairGeoTube::writePoints(), FairGeoTorus::writePoints(), FairGeoAssembly::writePoints(), FairGeoCons::writePoints(), FairGeoCone::writePoints(), FairGeoPcon::writePoints(), FairGeoEltu::writePoints(), FairGeoSphe::writePoints(), FairGeoPgon::writePoints(), and FairGeoBasicShape::writePoints().
 {
   if (points && n<nPoints) { return (FairGeoVector*)points->At(n); }
   else { return 0; }
 }
const TString& FairGeoVolume::getShape () const inline inherited
Definition at line 47 of file FairGeoVolume.h.
References FairGeoVolume::shape.
Referenced by FairGeoNode::compare(), FairGeoRootBuilder::createNode(), FairGeoShapes::selectShape(), and FairGeoVolume::setVolumePar().
 { return shape; }
FairGeoTransform& FairGeoVolume::getTransform () inline inherited
Definition at line 49 of file FairGeoVolume.h.
References FairGeoVolume::transform.
Referenced by FairGeoNode::calcModuleTransform(), FairGeoNode::calcRefPos(), FairGeoBasicShape::calcVoluPosition(), FairGeoNode::compare(), FairGeoOldAsciiIo::read(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), and FairGeoNode::setVolumePar().
 { return transform; }
Double_t FairGeoVolume::getVolParameter (Int_t nPoint, Int_t pos) inherited
Definition at line 141 of file FairGeoVolume.cxx.
References FairGeoVector::getValues(), and FairGeoVolume::points.
 {
   FairGeoVector* vec = (FairGeoVector*) points->At( nPoint );
   if ( vec ) { return vec->getValues( pos ); }
   else { return -1; }
 }
ClassDef (FairGeoCompositeVolume,1) private FairGeoCompositeVolume& FairGeoCompositeVolume::operator= (const FairGeoCompositeVolume &)
void FairGeoCompositeVolume::print () virtual
Reimplemented from FairGeoVolume.
Definition at line 75 of file FairGeoCompositeVolume.cxx.
References components, and FairGeoVolume::print().
 {
   FairGeoVolume::print();
   FairGeoVolume* v;
   for(Int_t i=0; i<components->GetSize(); i++) {
     v=(FairGeoVolume*)components->At(i);
     if (v) { v->print(); }
   }
 }
void FairGeoCompositeVolume::setComponent (FairGeoVolume * v, const Int_t n)
Definition at line 62 of file FairGeoCompositeVolume.cxx.
References components.
 {
   if (components) { components->AddAt(v,n); }
   else { Error("FairGeoCompositeVolume::setComponent","no array of components"); }
 }
virtual void FairGeoVolume::setHadFormat (Int_t i) inline virtual inherited
Definition at line 63 of file FairGeoVolume.h.
Referenced by FairGeoRootBuilder::createNode().
 { fHadFormat=i;}
void FairGeoVolume::setMCid (Int_t MCid) inline inherited
Definition at line 66 of file FairGeoVolume.h.
Referenced by FairDetector::Initialize().
 {fgMCid=MCid;}
void FairGeoVolume::setMother (const Text_t * s) inline inherited
Definition at line 106 of file FairGeoVolume.h.
References FairGeoVolume::mother.
 {
   mother=s;
   mother.ToUpper();
 }
void FairGeoVolume::setName (const Text_t * s) inline inherited
Definition at line 94 of file FairGeoVolume.h.
 {
   fName=s;
   fName.ToUpper();
 }
void FairGeoVolume::setPoint (const Int_t n, const Double_t x, const Double_t y, const Double_t z) inherited
Definition at line 91 of file FairGeoVolume.cxx.
References FairGeoVolume::nPoints, FairGeoVolume::points, FairGeoVector::setX(), FairGeoVector::setY(), and FairGeoVector::setZ().
Referenced by FairGeoOldAsciiIo::calculateShapePoints(), FairGeoTorus::readPoints(), FairGeoTube::readPoints(), FairGeoTubs::readPoints(), FairGeoCons::readPoints(), FairGeoPgon::readPoints(), FairGeoEltu::readPoints(), FairGeoSphe::readPoints(), FairGeoPcon::readPoints(), FairGeoCone::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), FairGeoVolume::setVolumePar(), and FairGeoNode::setVolumePar().
 {
   // set the 3 values of the point with index n
   if (points && n<nPoints) {
     FairGeoVector* v=(FairGeoVector*)points->At(n);
     v->setX(x);
     v->setY(y);
     v->setZ(z);
   }
 }
void FairGeoVolume::setPoint (const Int_t n, const FairGeoVector & p) inherited
Definition at line 103 of file FairGeoVolume.cxx.
References FairGeoVolume::nPoints, and FairGeoVolume::points.
 {
   // sets point with index n by copying the 3 components of point p
   if (points && n<nPoints) {
     FairGeoVector& v=*((FairGeoVector*)points->At(n));
     v=p;
   }
 }
void FairGeoVolume::setShape (const Text_t * s) inline inherited
Definition at line 100 of file FairGeoVolume.h.
References FairGeoVolume::shape.
 {
   shape=s;
   shape.ToUpper();
 }
void FairGeoVolume::setVolumePar (FairGeoVolume & r) inherited
Definition at line 57 of file FairGeoVolume.cxx.
References FairGeoVolume::createPoints(), FairGeoVolume::getMother(), FairGeoVolume::getNumPoints(), FairGeoVolume::getPoint(), FairGeoVolume::getShape(), FairGeoVolume::getTransform(), FairGeoVolume::mother, FairGeoVolume::nPoints, FairGeoVolume::setPoint(), FairGeoVolume::shape, and FairGeoVolume::transform.
 {
   // copies all volume parameters except the name
   shape=r.getShape();
   mother=r.getMother();
   Int_t n=r.getNumPoints();
   createPoints(n);
   for (Int_t i=0; i<nPoints; i++) { setPoint(i,*(r.getPoint(i))); }
   transform=r.getTransform();
 }
Member Data Documentation
TObjArray* FairGeoCompositeVolume::components protected
Definition at line 23 of file FairGeoCompositeVolume.h.
Referenced by clear(), createComponents(), getComponent(), getNumComponents(), print(), setComponent(), and ~FairGeoCompositeVolume().
Int_t FairGeoVolume::fgMCid protected inherited
Definition at line 40 of file FairGeoVolume.h.
Referenced by FairGeoVolume::getMCid().
Int_t FairGeoVolume::fHadFormat protected inherited
number of points
Definition at line 39 of file FairGeoVolume.h.
Referenced by FairGeoNode::getCopyNo().
FairGeoTransform FairGeoVolume::fLabTransform protected inherited
transformation relative to the mother system
Definition at line 36 of file FairGeoVolume.h.
Referenced by FairGeoNode::calcLabTransform(), FairGeoVolume::getLabTransform(), and FairGeoVolume::print().
FairGeoMedium FairGeoVolume::fMedium protected inherited
transformation to the LAB system;
Definition at line 37 of file FairGeoVolume.h.
Referenced by FairGeoNode::calcLabTransform(), and FairGeoVolume::getMedium().
TString FairGeoVolume::mother protected inherited
eant shape of the volume
Definition at line 33 of file FairGeoVolume.h.
Referenced by FairGeoVolume::clear(), FairGeoNode::compare(), FairGeoVolume::getMother(), FairGeoVolume::print(), FairGeoVolume::setMother(), FairGeoNode::setMother(), FairGeoVolume::setVolumePar(), and FairGeoNode::write().
Int_t FairGeoVolume::nPoints protected inherited
medium properties
Definition at line 38 of file FairGeoVolume.h.
Referenced by FairGeoVolume::clear(), FairGeoNode::compare(), FairGeoVolume::createPoints(), FairGeoNode::FairGeoNode(), FairGeoVolume::getNumPoints(), FairGeoVolume::getPoint(), FairGeoVolume::print(), FairGeoVolume::setPoint(), FairGeoVolume::setVolumePar(), FairGeoNode::setVolumePar(), and FairGeoNode::~FairGeoNode().
TObjArray* FairGeoVolume::points protected inherited
Name of the mother volume
Definition at line 34 of file FairGeoVolume.h.
Referenced by FairGeoVolume::clear(), FairGeoNode::compare(), FairGeoVolume::createPoints(), FairGeoNode::FairGeoNode(), FairGeoVolume::getPoint(), FairGeoVolume::getVolParameter(), FairGeoVolume::print(), FairGeoVolume::setPoint(), FairGeoNode::write(), FairGeoNode::~FairGeoNode(), and FairGeoVolume::~FairGeoVolume().
TString FairGeoVolume::shape protected inherited
Definition at line 32 of file FairGeoVolume.h.
Referenced by FairGeoVolume::clear(), FairGeoNode::compare(), FairGeoVolume::getShape(), FairGeoVolume::print(), FairGeoVolume::setShape(), FairGeoNode::setShape(), FairGeoVolume::setVolumePar(), and FairGeoNode::write().
FairGeoTransform FairGeoVolume::transform protected inherited
array of points (type FairGeoVector)
Definition at line 35 of file FairGeoVolume.h.
Referenced by FairGeoNode::calcLabTransform(), FairGeoNode::calcModuleTransform(), FairGeoVolume::clear(), FairGeoNode::compare(), FairGeoVolume::getTransform(), FairGeoNode::setLabTransform(), FairGeoVolume::setVolumePar(), FairGeoNode::setVolumePar(), and FairGeoNode::write().
The documentation for this class was generated from the following files:
FairGeoCompositeVolume.h
FairGeoCompositeVolume.cxx