FairRroot: FairGenericParTSQLIo Class Reference
FairGenericParTSQLIo Class Reference
#include <FairGenericParTSQLIo.h>
Public Member Functions
FairGenericParTSQLIo ()
Constructor.
FairGenericParTSQLIo (FairDbConnectionPool const &cons, int const dbNum=-1)
virtual ~FairGenericParTSQLIo ()
Destructor.
Bool_t init (FairParSet *pPar)
Bool_t read (FairParGenericSet *pPar)
Read and write functions.
Int_t write (FairParSet *pars)
Int_t writeSet (FairParGenericSet *pars)
Bool_t read (FairParSet *pars)
Int_t getRunStart (FairParSet *pPar=0)
virtual void commit ()
virtual void rollback ()
void print ()
_______________ Inline Implementations ________________
void setInputNumber (Int_t n)
Int_t getInputNumber ()
Protected Member Functions
void setChanged (FairParSet *pars)
Protected Attributes
int fDefaultDb
FairDbConnectionPool * fConnections
TList * fcontainerList
FairDbConnection.
FairRtdbRun * factContVers
List of parameter containers.
int actRunId
The actual list of container versions.
Int_t inputNumber
Private Member Functions
FairGenericParTSQLIo (FairGenericParTSQLIo const &ot)
FairGenericParTSQLIo & operator= (FairGenericParTSQLIo const &ot)
Private Attributes
FairRuntimeDb * fRtdb
Detailed Description
Definition at line 28 of file FairGenericParTSQLIo.h.
Constructor & Destructor Documentation
FairGenericParTSQLIo::FairGenericParTSQLIo ()
Constructor.
FairGenericParTSQLIo::FairGenericParTSQLIo (FairDbConnectionPool const & cons, int const dbNum = -1)
Parameters
cons FairDbConnectionPool which holds a number of initialized db connections.
dbNum The db which is selected to act as the master for the current operations. Note: A new FairDbConnectionPool object is created (to keep the ownership).
Definition at line 46 of file FairGenericParTSQLIo.cxx.
   : FairDetParTSQLIo(cons, dbNum),
     fRtdb(FairRuntimeDb::instance())
 {
   fName = "FairGenericParIo";
 //  fRtdb = FairRuntimeDb::instance();
 }
FairGenericParTSQLIo::~FairGenericParTSQLIo () virtual
Destructor.
Definition at line 56 of file FairGenericParTSQLIo.cxx.
 {
   std::cout << "\n\n\t<DEBUG>~FairGenericParTSQLIo() Destroy\n\n";
 }
FairGenericParTSQLIo::FairGenericParTSQLIo (FairGenericParTSQLIo const & ot) private
Member Function Documentation
void FairDetParTSQLIo::commit () virtual inherited
Definition at line 119 of file FairDetParTSQLIo.cxx.
 {
   std::cerr << "<ERROR> Commit() is Not implemented yet. Maybe later"
             << std::endl;
 }
Int_t FairDetParIo::getInputNumber () inline inherited
Definition at line 29 of file FairDetParIo.h.
References FairDetParIo::inputNumber.
 {return inputNumber;}
int FairDetParTSQLIo::getRunStart (FairParSet * pPar = 0) inherited
Definition at line 76 of file FairDetParTSQLIo.cxx.
References FairDetParTSQLIo::actRunId, FairDetParTSQLIo::factContVers, FairRuntimeDb::getCurrentRun(), FairRtdbRun::getRefRun(), FairRtdbRun::getRunId(), and FairRuntimeDb::instance().
 {
   std::cout << "\n\n\n\n\t<DEBUG> FairDetParTSQLIo::getRunStart(FairParSet* pPar)\n\n\n\n";
   actRunId=-1;
   int runStart=-1;
   factContVers=FairRuntimeDb::instance()->getCurrentRun();
   if (!factContVers) {
     Error("getRunStart()","current run not set in runtime database");
     return -1;
   }
   const Text_t* refRun=factContVers->getRefRun();
   if (strlen(refRun) > 0) {
     sscanf(refRun,"%i",&actRunId);
   } else {
     actRunId=factContVers->getRunId();
   }
   if(pPar) {
     Int_t contVers = 10;//getPredefVersion(pPar);
     if (contVers>=0) {
       actRunId = contVers;
     }
   }
   //runStart=pConn->getRunStart(actRunId);
   return runStart;
 }
Bool_t FairGenericParTSQLIo::init (FairParSet * pPar) virtual
Reimplemented from FairDetParIo.
Definition at line 71 of file FairGenericParTSQLIo.cxx.
References FairParSet::GetName(), and read().
 {
   std::cout << "-I- FairGenericParTSQLIo::init(FairParSet* par) called  " << std::endl;
   if (pPar->InheritsFrom("FairParGenericSet")) {
     return read((FairParGenericSet*)pPar);
   }
   Error("FairGenericParTSQLIo::init(FairParSet*, Int_t*)",
         "%s does not inherit from FairParGenericSet", pPar->GetName());
   return false;
 }
FairGenericParTSQLIo& FairGenericParTSQLIo::operator= (FairGenericParTSQLIo const & ot) private
void FairDetParTSQLIo::print () inline inherited
_______________ Inline Implementations ________________
Definition at line 91 of file FairDetParTSQLIo.h.
 {
   std::cout << "FairDetParTSQLIo::print()\n\n";
 };
Bool_t FairDetParTSQLIo::read (FairParSet * pars) inherited
Read the parameter set from the DB.
Definition at line 134 of file FairDetParTSQLIo.cxx.
 {
   std::cout << "========================================================\n";
   pars->Print();
   std::cout << "\n\t<DEBUG>FairDetParTSQLIo::READ(FairParSet* pars)\n"
             << "========================================================\n";
   return false;
 }
Bool_t FairGenericParTSQLIo::read (FairParGenericSet * pPar)
Read and write functions.
Definition at line 61 of file FairGenericParTSQLIo.cxx.
References FairParSet::fill(), fRtdb, FairRuntimeDb::getCurrentRun(), and FairRtdbRun::getRunId().
Referenced by init().
 {
   UInt_t rid = fRtdb->getCurrentRun()->getRunId();
   par->fill(rid);
   std::cout << "-I- FairGenericParTSQLIo::read(FairParGenericSet* par) done for runId#  " <<  rid << std::endl;
   return kTRUE;
 }
void FairDetParTSQLIo::rollback () virtual inherited
Definition at line 126 of file FairDetParTSQLIo.cxx.
 {
   std::cerr << "<ERROR> Rollback() Not implemented yet. Maybe later\n"
             << "        It remains engine dependent."
             << std::endl;
 }
void FairDetParTSQLIo::setChanged (FairParSet * pars) protected inherited
Definition at line 106 of file FairDetParTSQLIo.cxx.
References FairParSet::setChanged(), and FairParSet::setDescription().
 {
   // sets the changed flag, the version (id of actual run) and the comment
   pPar->setChanged();
   //pPar->setInputVersion(getActRunId(), inputNumber);
   TString s="Read from TSQL\n             Valid for Run Id ";
   //s.Append(Form("%d",getActRunId()));
   s.Append("\n             Status at ");
   //s.Append(pConn->getHistoryDate());
   pPar->setDescription(s.Data());
 }
void FairDetParIo::setInputNumber (Int_t n) inline inherited
Definition at line 26 of file FairDetParIo.h.
Referenced by FairParIo::setInputNumber().
 {inputNumber=n;}
Int_t FairGenericParTSQLIo::write (FairParSet * pars) virtual
Reimplemented from FairDetParTSQLIo.
Definition at line 85 of file FairGenericParTSQLIo.cxx.
References FairParSet::GetName(), and writeSet().
 {
   if (par->InheritsFrom("FairParGenericSet")) {
     return writeSet((FairParGenericSet*)par);
   }
   Error("FairGenericParOraIo::write(FairParSet*)",
         "%s does not inherit from FairParGenericSet",par->GetName());
   return -1;
 }
Int_t FairGenericParTSQLIo::writeSet (FairParGenericSet * pars)
Definition at line 95 of file FairGenericParTSQLIo.cxx.
References fRtdb, FairRuntimeDb::getCurrentRun(), FairParSet::GetName(), FairParSet::getParamContext(), FairRtdbRun::getRunId(), and FairParSet::store().
Referenced by write().
 {
   if(!par) {
     std::cerr << "-E FairGenericParTSQLIo::writeSet() : no Parameter container#\n" << std::endl;;
     return -1;
   }
   std::cout << "-I- FairGenericParTSQLIo::writeSet(FairParGenericSet* par)\n"
             << " Name is " << par->GetName()
             << " Context = " << par->getParamContext()
             <<"\n---------------  Storage of "<< par->GetName()<<"  ---------------\n"
             << "Class name = " << par->ClassName() << std::endl;
   UInt_t rid = fRtdb->getCurrentRun()->getRunId();
   par->store(rid);
   std::cout << "-I- FairGenericParTSQLIo::WriteSet() done  for runID# " <<  rid << std::endl;
   return 1;
 }
Member Data Documentation
int FairDetParTSQLIo::actRunId protected inherited
The actual list of container versions.
Definition at line 76 of file FairDetParTSQLIo.h.
Referenced by FairDetParTSQLIo::getRunStart().
FairRtdbRun* FairDetParTSQLIo::factContVers protected inherited
List of parameter containers.
Definition at line 75 of file FairDetParTSQLIo.h.
Referenced by FairDetParTSQLIo::getRunStart(), and FairDetParTSQLIo::~FairDetParTSQLIo().
FairDbConnectionPool* FairDetParTSQLIo::fConnections protected inherited
Definition at line 73 of file FairDetParTSQLIo.h.
Referenced by FairDetParTSQLIo::~FairDetParTSQLIo().
TList* FairDetParTSQLIo::fcontainerList protected inherited
FairDbConnection.
Definition at line 74 of file FairDetParTSQLIo.h.
Referenced by FairDetParTSQLIo::~FairDetParTSQLIo().
int FairDetParTSQLIo::fDefaultDb protected inherited
The default Database connection.
Definition at line 72 of file FairDetParTSQLIo.h.
FairRuntimeDb* FairGenericParTSQLIo::fRtdb private
Definition at line 65 of file FairGenericParTSQLIo.h.
Referenced by read(), and writeSet().
Int_t FairDetParIo::inputNumber protected inherited
Definition at line 20 of file FairDetParIo.h.
Referenced by FairDetParRootFileIo::findInputVersion(), FairDetParIo::getInputNumber(), and FairDetParRootFileIo::read().
The documentation for this class was generated from the following files:
FairGenericParTSQLIo.h
FairGenericParTSQLIo.cxx