FairRoot: cxx11-test-variadic_templates.cpp File Reference
cxx11-test-variadic_templates.cpp File Reference
Functions
int Accumulate ()
template<typename T , typename... Ts>
int Accumulate (T v, Ts...vs)
template<int... Is>
int CountElements ()
int main ()
Function Documentation
int Accumulate ()
Definition at line 1 of file cxx11-test-variadic_templates.cpp.
Referenced by Accumulate(), and main().
 {
         return 0;
 }
template<typename T , typename... Ts> int Accumulate (T v, Ts... vs)
Definition at line 7 of file cxx11-test-variadic_templates.cpp.
References Accumulate().
 {
         return v + Accumulate(vs...);
 }
template<int... Is> int CountElements ()
Definition at line 13 of file cxx11-test-variadic_templates.cpp.
 {
         return sizeof...(Is);
 }
int main (void)
Definition at line 18 of file cxx11-test-variadic_templates.cpp.
References Accumulate().
 {
         int acc = Accumulate(1, 2, 3, 4, -5);
         int count = CountElements<1,2,3,4,5>();
         return ((acc == 5) && (count == 5)) ? 0 : 1;
 }