FairRoot: FairDetParAsciiFileIo Class Reference
FairDetParAsciiFileIo Class Reference
#include <FairDetParAsciiFileIo.h>
Public Member Functions
FairDetParAsciiFileIo (std::fstream *f)
virtual ~FairDetParAsciiFileIo ()
void setInputNumber (Int_t n)
Int_t getInputNumber ()
virtual Bool_t init (FairParSet *)
virtual Int_t write (FairParSet *)
Protected Member Functions
Bool_t findContainer (const Text_t *name)
pointer to ascii file
Bool_t checkAllFound (Int_t *, Int_t)
void writeHeader (const Text_t *, const Text_t *context="", const Text_t *author="", const Text_t *description="")
void writeComment (FairParSet *)
void readComment (const Char_t *, FairParSet *)
Protected Attributes
TString fHeader
TString sepLine
header of container output in file
std::fstream * pFile
comment line
Int_t inputNumber
Private Member Functions
FairDetParAsciiFileIo & operator= (const FairDetParAsciiFileIo &)
FairDetParAsciiFileIo (const FairDetParAsciiFileIo &)
Detailed Description
Definition at line 21 of file FairDetParAsciiFileIo.h.
Constructor & Destructor Documentation
FairDetParAsciiFileIo::FairDetParAsciiFileIo (std::fstream * f)
Definition at line 28 of file FairDetParAsciiFileIo.cxx.
   :FairDetParIo(),
    fHeader(""),
    sepLine("##############################################################################\n"),
    pFile(f)
 {
   // constructor
   /*  pFile=f;
   sepLine=
   "##############################################################################\n";
   */
 }
virtual FairDetParAsciiFileIo::~FairDetParAsciiFileIo () inline virtual
Definition at line 43 of file FairDetParAsciiFileIo.h.
 {}
FairDetParAsciiFileIo::FairDetParAsciiFileIo (const FairDetParAsciiFileIo &) private
Member Function Documentation
Bool_t FairDetParAsciiFileIo::checkAllFound (Int_t * set, Int_t setSize) protected
Definition at line 63 of file FairDetParAsciiFileIo.cxx.
 {
   // checks if all modules have been initialized
   Bool_t allFound=kTRUE;
   for(Int_t i=0; i<setSize; i++) {
     if (set[i]==999) {
       set[i]=0;
       printf(" %i",i);
     }
     if (set[i]) { allFound=kFALSE; }
   }
   printf("\n");
   return allFound;
 }
Bool_t FairDetParAsciiFileIo::findContainer (const Text_t * name) protected
pointer to ascii file
Definition at line 42 of file FairDetParAsciiFileIo.cxx.
References pFile.
 {
   // searches the container in the file
   const Int_t maxbuf=4000;
   Text_t buf[maxbuf];
   Text_t buf2[maxbuf];
   sprintf(buf2,"%s%s%s","[",name,"]");
   //cout << " buf2 " <<  buf2 << endl;
   pFile->clear();
   pFile->seekg(0,ios::beg);
   while (!pFile->eof()) {
     pFile->getline(buf,maxbuf);
     if (buf[0]!='[') { continue; }
     //cout << " buf: " <<  buf << endl;
     if (!strncmp(buf,buf2,strlen(buf2))) { break; }
   }
   if (pFile->eof()) { return kFALSE; }
   return kTRUE;
 }
Int_t FairDetParIo::getInputNumber () inline inherited
Definition at line 29 of file FairDetParIo.h.
References FairDetParIo::inputNumber.
 {return inputNumber;}
virtual Bool_t FairDetParIo::init (FairParSet *) inline virtual inherited
Reimplemented in FairGenericParAsciiFileIo, and FairGenericParRootFileIo.
Definition at line 32 of file FairDetParIo.h.
Referenced by ClassImp().
 {return kFALSE;}
FairDetParAsciiFileIo& FairDetParAsciiFileIo::operator= (const FairDetParAsciiFileIo &) private
void FairDetParAsciiFileIo::readComment (const Char_t * lastBuf, FairParSet * pPar) protected
Definition at line 100 of file FairDetParAsciiFileIo.cxx.
References pFile, FairParSet::setAuthor(), and FairParSet::setDescription().
 {
   // reads the author or the description
   const Int_t maxbuf=4000;
   Text_t buf[maxbuf];
   TString s=lastBuf;
   TString pName, pVal;
   Ssiz_t n=s.First(':');
   Ssiz_t m=s.Last('\\');
   pName=s(0,n);
   if (m>0) { pVal=s(n+1,m-n-1); }
   else { pVal=s(n+1,s.Length()-n-1); }
   pVal=pVal.Strip(pVal.kLeading);
   while (m>0) {
     pVal+="\n";
     pFile->getline(buf,maxbuf);
     if (buf[0]!='/') {
       s=buf;
       m=s.Last('\\');
       if (m>0) { pVal+=s(0,m); }
       else { pVal+=s; }
     }
   }
   if (pName.CompareTo("author")==0) { pPar->setAuthor(pVal.Data()); }
   else if ( pName.CompareTo("description")==0) { pPar->setDescription(pVal.Data()); }
 }
void FairDetParIo::setInputNumber (Int_t n) inline inherited
Definition at line 26 of file FairDetParIo.h.
Referenced by FairParIo::setInputNumber().
 {inputNumber=n;}
virtual Int_t FairDetParIo::write (FairParSet *) inline virtual inherited
Reimplemented in FairDetParRootFileIo, and FairGenericParAsciiFileIo.
Definition at line 35 of file FairDetParIo.h.
Referenced by FairParGenericSet::write().
 {return kFALSE;}
void FairDetParAsciiFileIo::writeComment (FairParSet * pPar) protected
Definition at line 127 of file FairDetParAsciiFileIo.cxx.
References FairParSet::getAuthor(), FairParSet::getDescription(), and pFile.
Referenced by FairGenericParAsciiFileIo::writeGenericSet().
 {
   TString t=pPar->getAuthor();
   if (!t.IsNull()) { *pFile<<"author:      "<<t<<"\n"; }
   t=pPar->getDescription();
   if (!t.IsNull()) {
     t=t.ReplaceAll("\n"," \\\n");
     *pFile<<"description: "<<t<<"\n";
   }
 }
void FairDetParAsciiFileIo::writeHeader (const Text_t * name, const Text_t * context = "", const Text_t * author = "", const Text_t * description = "") protected
Definition at line 79 of file FairDetParAsciiFileIo.cxx.
References fHeader, pFile, and sepLine.
 {
   // calls the function putAsciiHeader(...) of the parameter container
   // class and writes the header to the file
   pFile->write(sepLine,strlen(sepLine));
   pFile->write(fHeader.Data(),fHeader.Length());
   pFile->write(sepLine,strlen(sepLine));
   *pFile<<"["<<name<<"]\n";
   if (strlen(context)>0) { *pFile<<"// Parameter Context: "<<context<<"\n"; }
   if (strlen(author)>0) { *pFile<<"author:      "<<author<<"\n"; }
   TString t=description;
   if (!t.IsNull()) {
     t=t.ReplaceAll("\n"," \\\n");
     *pFile<<"description: "<<t<<"\n";
   }
   *pFile<<"//-----------------------------------------------------------"
         "-----------------\n";
 }
Member Data Documentation
TString FairDetParAsciiFileIo::fHeader protected
Definition at line 24 of file FairDetParAsciiFileIo.h.
Referenced by writeHeader().
Int_t FairDetParIo::inputNumber protected inherited
Definition at line 20 of file FairDetParIo.h.
Referenced by FairDetParRootFileIo::findInputVersion(), FairDetParIo::getInputNumber(), and FairDetParRootFileIo::read().
std::fstream* FairDetParAsciiFileIo::pFile protected
comment line
Definition at line 26 of file FairDetParAsciiFileIo.h.
Referenced by findContainer(), FairGenericParAsciiFileIo::init(), readComment(), FairGenericParAsciiFileIo::readData(), FairGenericParAsciiFileIo::write(), writeComment(), FairGenericParAsciiFileIo::writeData(), FairGenericParAsciiFileIo::writeGenericSet(), and writeHeader().
TString FairDetParAsciiFileIo::sepLine protected
header of container output in file
Definition at line 25 of file FairDetParAsciiFileIo.h.
Referenced by FairGenericParAsciiFileIo::writeGenericSet(), and writeHeader().
The documentation for this class was generated from the following files:
FairDetParAsciiFileIo.h
FairDetParAsciiFileIo.cxx