FairRroot: FairPlutoGenerator Class Reference
FairPlutoGenerator Class Reference
#include <FairPlutoGenerator.h>
Public Member Functions
FairPlutoGenerator ()
FairPlutoGenerator (const Char_t *fileName)
virtual ~FairPlutoGenerator ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
ClassDef (FairGenerator, 1)
Private Member Functions
void CloseInput ()
Particle array from PLUTO.
FairPlutoGenerator (const FairPlutoGenerator &)
FairPlutoGenerator & operator= (const FairPlutoGenerator &)
ClassDef (FairPlutoGenerator, 1)
Private Attributes
Int_t iEvent
const Char_t * fFileName
Event number.
TFile * fInputFile
Input file name.
TTree * fInputTree
Pointer to input file.
TClonesArray * fParticles
Pointer to input tree.
Detailed Description
Definition at line 35 of file FairPlutoGenerator.h.
Constructor & Destructor Documentation
FairPlutoGenerator::FairPlutoGenerator ()
Default constructor (should not be used)
Definition at line 30 of file FairPlutoGenerator.cxx.
   :FairGenerator(),
    iEvent(0),
    fFileName(NULL),
    fInputFile(NULL),
    fInputTree(NULL),
    fParticles(NULL)
 {
   /*
   iEvent     = 0;
   fInputFile = NULL;
   fInputTree = NULL;
   */
 }
FairPlutoGenerator::FairPlutoGenerator (const Char_t * fileName)
Standard constructor
Parameters
fileName The input (PLUTO) file name
Definition at line 49 of file FairPlutoGenerator.cxx.
References fInputFile, fInputTree, and fParticles.
   :FairGenerator(),
    iEvent(0),
    fFileName(fileName),
    fInputFile(new TFile(fileName)),
    fInputTree(NULL),
    fParticles(new TClonesArray("PParticle",100))
 {
   /*
   iEvent     = 0;
   fFileName  = fileName;
   fInputFile = new TFile(fFileName);
   */
   fInputTree = (TTree*) fInputFile->Get("data");
   //  fParticles = new TClonesArray("PParticle",100);
   fInputTree->SetBranchAddress("Particles", &fParticles);
 }
FairPlutoGenerator::~FairPlutoGenerator () virtual
Destructor
Definition at line 71 of file FairPlutoGenerator.cxx.
References CloseInput().
 {
   CloseInput();
 }
FairPlutoGenerator::FairPlutoGenerator (const FairPlutoGenerator &) private
Member Function Documentation
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
FairPlutoGenerator::ClassDef (FairPlutoGenerator , 1) private
FairGenerator * FairGenerator::CloneGenerator () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
 {
   Fatal("CloneGenerator","Has to be overriden in multi-threading applications.");
   return 0;
 }
void FairPlutoGenerator::CloseInput () private
Particle array from PLUTO.
Private method CloseInput. Just for convenience. Closes the input file properly. Called from destructor and from ReadEvent.
Definition at line 142 of file FairPlutoGenerator.cxx.
References fFileName, and fInputFile.
Referenced by ReadEvent(), and ~FairPlutoGenerator().
 {
   if ( fInputFile ) {
     cout << "-I FairPlutoGenerator: Closing input file " << fFileName
          << endl;
     fInputFile->Close();
     delete fInputFile;
   }
   fInputFile = NULL;
 }
virtual Bool_t FairGenerator::Init () inline virtual inherited
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
 { return kTRUE;}
FairPlutoGenerator& FairPlutoGenerator::operator= (const FairPlutoGenerator &) private
Bool_t FairPlutoGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Reads on event from the input file and pushes the tracks onto the stack. Abstract method in base class.
Parameters
primGen pointer to the FairPrimaryGenerator
Implements FairGenerator.
Definition at line 80 of file FairPlutoGenerator.cxx.
References FairPrimaryGenerator::AddTrack(), CloseInput(), fInputFile, fInputTree, fParticles, and iEvent.
 {
   // Check for input file
   if ( ! fInputFile ) {
     cout << "-E FairPlutoGenerator: Input file nor open!" << endl;
     return kFALSE;
   }
   // Check for number of events in input file
   if ( iEvent > fInputTree->GetEntries() ) {
     cout << "-E FairPlutoGenerator: No more events in input file!" << endl;
     CloseInput();
     return kFALSE;
   }
   TFile*  g=gFile;
   fInputFile->cd();
   fInputTree->GetEntry(iEvent++);
   g->cd();
   // Get PDG database
   TDatabasePDG* dataBase = TDatabasePDG::Instance();
   // Get number of particle in TClonesrray
   Int_t nParts = fParticles->GetEntriesFast();
   // Loop over particles in TClonesArray
   for (Int_t iPart=0; iPart < nParts; iPart++) {
     PParticle* part = (PParticle*) fParticles->At(iPart);
     Int_t pdgType = dataBase->ConvertGeant3ToPdg( part->ID() );
     // Check if particle type is known to database
     if ( ! pdgType ) {
       cout << "-W FairPlutoGenerator: Unknown type " << part->ID()
            << ", skipping particle." << endl;
       continue;
     }
     TLorentzVector mom = part->Vect4();
     Double_t px = mom.Px();
     Double_t py = mom.Py();
     Double_t pz = mom.Pz();
     TVector3 vertex = part->getVertex();
     Double_t vx = vertex.x();
     Double_t vy = vertex.y();
     Double_t vz = vertex.z();
     // Give track to PrimaryGenerator
     primGen->AddTrack(pdgType, px, py, pz, vx, vy, vz);
   }        //  Loop over particle in event
   return kTRUE;
 }
Member Data Documentation
const Char_t* FairPlutoGenerator::fFileName private
Event number.
Definition at line 65 of file FairPlutoGenerator.h.
Referenced by CloseInput().
TFile* FairPlutoGenerator::fInputFile private
Input file name.
Definition at line 66 of file FairPlutoGenerator.h.
Referenced by CloseInput(), FairPlutoGenerator(), and ReadEvent().
TTree* FairPlutoGenerator::fInputTree private
Pointer to input file.
Definition at line 67 of file FairPlutoGenerator.h.
Referenced by FairPlutoGenerator(), and ReadEvent().
TClonesArray* FairPlutoGenerator::fParticles private
Pointer to input tree.
Definition at line 68 of file FairPlutoGenerator.h.
Referenced by FairPlutoGenerator(), and ReadEvent().
Int_t FairPlutoGenerator::iEvent private
Definition at line 64 of file FairPlutoGenerator.h.
Referenced by ReadEvent().
The documentation for this class was generated from the following files:
FairPlutoGenerator.h
FairPlutoGenerator.cxx