/********************************************************************************
 * Copyright (C) 2014-2023 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH  *
 *                                                                              *
 *              This software is distributed under the terms of the             *
 *              GNU Lesser General Public Licence (LGPL) version 3,             *
 *                  copied verbatim in the file "LICENSE"                       *
 ********************************************************************************/
/* Generated by Together */
#include "FairTarget.h"

#include "FairGeoPassivePar.h"   // for FairGeoPassivePar
#include "FairGeoTarget.h"       // for FairGeoTarget

FairTarget::~FairTarget() {}

FairTarget::FairTarget()
    : FairModule("FairTarget", "")
{}

FairTarget::FairTarget(const char* name, const char* title)
    : FairModule(name, title)
{}

FairTarget::FairTarget(const FairTarget& rhs)
    : FairModule(rhs)
{}

void FairTarget::ConstructGeometry()
{
    ConstructASCIIGeometry<FairGeoTarget, FairGeoPassivePar>("FairGeoPassivePar");
}

FairModule* FairTarget::CloneModule() const
{
    return new FairTarget(*this);
}
