FairRoot: FairMCEventHeader Class Reference
FairMCEventHeader Class Reference
#include <FairMCEventHeader.h>
Public Member Functions
FairMCEventHeader ()
FairMCEventHeader (Int_t iEvent, Double_t x, Double_t y, Double_t z, Double_t t, Double_t b, Int_t nPrim)
FairMCEventHeader (UInt_t runId)
virtual ~FairMCEventHeader ()
UInt_t GetRunID () const
UInt_t GetEventID () const
run identifier
Double_t GetX () const
event identifier
Double_t GetY () const
vertex x [cm]
Double_t GetZ () const
vertex y [cm]
Double_t GetT () const
vertex z [cm]
Double_t GetB () const
event time [ns]
Int_t GetNPrim () const
impact parameter [fm]
Bool_t IsSet () const
number of input tracks
Double_t GetRotX () const
Flag.
Double_t GetRotY () const
rot. around x-axis [rad]
Double_t GetRotZ () const
rot. around y-axis [rad]
void GetVertex (TVector3 &vertex)
rot. around z-axis [rad]
void SetEventID (UInt_t eventId)
void SetRunID (UInt_t runId)
void SetTime (Double_t t)
void SetB (Double_t b)
void SetNPrim (Int_t nPrim)
void MarkSet (Bool_t isSet)
void SetVertex (Double_t x, Double_t y, Double_t z)
void SetVertex (const TVector3 &vertex)
void SetRotX (Double_t rotx)
void SetRotY (Double_t roty)
void SetRotZ (Double_t rotz)
void Reset ()
virtual void Register ()
Protected Member Functions
ClassDef (FairMCEventHeader, 2)
Rotation around z-axis (event plane) [rad].
Protected Attributes
UInt_t fRunId
UInt_t fEventId
Run identifier.
Double32_t fX
Event identifier.
Double32_t fY
Primary vertex x [cm].
Double32_t fZ
Primary vertex y [cm].
Double32_t fT
Primary vertex z [cm].
Double32_t fB
Event time [s].
Int_t fNPrim
Impact parameter [fm] (if relevant)
Bool_t fIsSet
Number of input tracks.
Double32_t fRotX
Flag whether variables are filled.
Double32_t fRotY
Rotation around x-axis (beam tilt) [rad].
Double32_t fRotZ
Rotation around y-axis (beam tilt) [rad].
Detailed Description
FairMCEventHeader.h
Author
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e Data class (level MC) containing information about the input event. 15.05.2008 change the event time to ns (M. Al-Turany)
Definition at line 23 of file FairMCEventHeader.h.
Constructor & Destructor Documentation
FairMCEventHeader::FairMCEventHeader ()
Default constructor
Definition at line 20 of file FairMCEventHeader.cxx.
   : TNamed("MCEvent", "MC"),
     fRunId(0),
     fEventId(-1),
     fX (0.),
     fY (0.),
     fZ (0.),
     fT (0.),
     fB (0.),
     fNPrim(0),
     fIsSet(kFALSE),
     fRotX (0.),
     fRotY (0.),
     fRotZ (0.)
 {
 }
FairMCEventHeader::FairMCEventHeader (Int_t iEvent, Double_t x, Double_t y, Double_t z, Double_t t, Double_t b, Int_t nPrim)
Constructor with all members
Parameters
iEvent event identifier
x,y,z vertex oordinates [cm]
t event time [ns]
b impact parameter [fm] (if relevant)
nPrim number of input tracks
Definition at line 64 of file FairMCEventHeader.cxx.
   : TNamed("MCEvent", "MC"),
     fRunId(0),
     fEventId(iEvent),
     fX (x),
     fY (y),
     fZ (z),
     fT (t),
     fB (b),
     fNPrim(nPrim),
     fIsSet(kFALSE),
     fRotX (0.),
     fRotY (0.),
     fRotZ (0.)
 {
 }
FairMCEventHeader::FairMCEventHeader (UInt_t runId)
Standard constructor with run identifier
Definition at line 42 of file FairMCEventHeader.cxx.
   : TNamed("MCEvent", "MC"),
     fRunId(runId),
     fEventId(-1),
     fX (0.),
     fY (0.),
     fZ (0.),
     fT (0.),
     fB (0.),
     fNPrim(0),
     fIsSet(kFALSE),
     fRotX (0.),
     fRotY (0.),
     fRotZ (0.)
 {
 }
FairMCEventHeader::~FairMCEventHeader () virtual
Destructor
Definition at line 88 of file FairMCEventHeader.cxx.
 {
 }
Member Function Documentation
FairMCEventHeader::ClassDef (FairMCEventHeader , 2) protected
Rotation around z-axis (event plane) [rad].
Double_t FairMCEventHeader::GetB () const inline
event time [ns]
Definition at line 59 of file FairMCEventHeader.h.
References fB.
 { return fB; }
UInt_t FairMCEventHeader::GetEventID () const inline
run identifier
Definition at line 54 of file FairMCEventHeader.h.
References fEventId.
Referenced by FairPrimaryGenerator::GenerateEvent().
 { return fEventId; }
Int_t FairMCEventHeader::GetNPrim () const inline
impact parameter [fm]
Definition at line 60 of file FairMCEventHeader.h.
References fNPrim.
 { return fNPrim; }
Double_t FairMCEventHeader::GetRotX () const inline
Flag.
Definition at line 62 of file FairMCEventHeader.h.
References fRotX.
 { return fRotX; }
Double_t FairMCEventHeader::GetRotY () const inline
rot. around x-axis [rad]
Definition at line 63 of file FairMCEventHeader.h.
References fRotY.
 { return fRotY; }
Double_t FairMCEventHeader::GetRotZ () const inline
rot. around y-axis [rad]
Definition at line 64 of file FairMCEventHeader.h.
References fRotZ.
 { return fRotZ; }
UInt_t FairMCEventHeader::GetRunID () const inline
Accessors
Definition at line 53 of file FairMCEventHeader.h.
References fRunId.
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunAna::InitContainers(), FairRunAna::Run(), and FairRunAna::RunEventReco().
 { return fRunId; }
Double_t FairMCEventHeader::GetT () const inline
vertex z [cm]
Definition at line 58 of file FairMCEventHeader.h.
References fT.
Referenced by FairRootManager::GetEventTime().
 { return fT; }
void FairMCEventHeader::GetVertex (TVector3 & vertex) inline
rot. around z-axis [rad]
Definition at line 66 of file FairMCEventHeader.h.
References fX, fY, and fZ.
 { vertex.SetXYZ(fX, fY, fZ); }
Double_t FairMCEventHeader::GetX () const inline
event identifier
Definition at line 55 of file FairMCEventHeader.h.
References fX.
 { return fX; }
Double_t FairMCEventHeader::GetY () const inline
vertex x [cm]
Definition at line 56 of file FairMCEventHeader.h.
References fY.
 { return fY; }
Double_t FairMCEventHeader::GetZ () const inline
vertex y [cm]
Definition at line 57 of file FairMCEventHeader.h.
References fZ.
 { return fZ; }
Bool_t FairMCEventHeader::IsSet () const inline
number of input tracks
Definition at line 61 of file FairMCEventHeader.h.
References fIsSet.
 { return fIsSet; }
void FairMCEventHeader::MarkSet (Bool_t isSet) inline
Definition at line 75 of file FairMCEventHeader.h.
References fIsSet.
 { fIsSet = isSet; }
void FairMCEventHeader::Register () virtual
Register the class as data branch to the output
Definition at line 106 of file FairMCEventHeader.cxx.
References FairRootManager::Instance(), and FairRootManager::Register().
Referenced by FairMCApplication::InitGeometry().
 {
   // Dot at the end of the name is needed for splitting!!
   FairRootManager::Instance()->Register("MCEventHeader.", "Event", this, kTRUE);
 }
void FairMCEventHeader::Reset ()
Reset all members
Definition at line 96 of file FairMCEventHeader.cxx.
References fB, fEventId, fIsSet, fNPrim, fRotX, fRotY, fRotZ, fT, fX, fY, and fZ.
Referenced by FairPrimaryGenerator::GenerateEvent().
 {
   fEventId = -1;
   fNPrim = 0;
   fX = fY = fZ = fT = fB = 0.;
   fIsSet = kFALSE;
   fRotX = fRotY = fRotZ = 0.;
 }
void FairMCEventHeader::SetB (Double_t b) inline
Definition at line 73 of file FairMCEventHeader.h.
References fB.
 { fB = b; }
void FairMCEventHeader::SetEventID (UInt_t eventId) inline
Modifiers
Definition at line 70 of file FairMCEventHeader.h.
References fEventId.
Referenced by FairPrimaryGenerator::GenerateEvent(), and FairUrqmdGenerator::ReadEvent().
 { fEventId = eventId; }
void FairMCEventHeader::SetNPrim (Int_t nPrim) inline
Definition at line 74 of file FairMCEventHeader.h.
References fNPrim.
Referenced by FairPrimaryGenerator::GenerateEvent().
 { fNPrim = nPrim; }
void FairMCEventHeader::SetRotX (Double_t rotx) inline
Definition at line 78 of file FairMCEventHeader.h.
References fRotX.
Referenced by FairPrimaryGenerator::MakeBeamAngle().
 { fRotX = rotx; }
void FairMCEventHeader::SetRotY (Double_t roty) inline
Definition at line 79 of file FairMCEventHeader.h.
References fRotY.
Referenced by FairPrimaryGenerator::MakeBeamAngle().
 { fRotY = roty; }
void FairMCEventHeader::SetRotZ (Double_t rotz) inline
Definition at line 80 of file FairMCEventHeader.h.
References fRotZ.
Referenced by FairPrimaryGenerator::MakeEventPlane().
 { fRotZ = rotz; }
void FairMCEventHeader::SetRunID (UInt_t runId) inline
Definition at line 71 of file FairMCEventHeader.h.
References fRunId.
Referenced by FairMCApplication::InitGeometry().
 { fRunId = runId; }
void FairMCEventHeader::SetTime (Double_t t) inline
Definition at line 72 of file FairMCEventHeader.h.
References fT.
 { fT = t; }
void FairMCEventHeader::SetVertex (Double_t x, Double_t y, Double_t z) inline
Definition at line 110 of file FairMCEventHeader.h.
References fX, fY, and fZ.
Referenced by FairPrimaryGenerator::GenerateEvent().
 {
   fX = x;
   fY = y;
   fZ = z;
 }
void FairMCEventHeader::SetVertex (const TVector3 & vertex) inline
Definition at line 119 of file FairMCEventHeader.h.
References fX, fY, and fZ.
 {
   fX = vertex.X();
   fY = vertex.Y();
   fZ = vertex.Z();
 }
Member Data Documentation
Double32_t FairMCEventHeader::fB protected
Event time [s].
Definition at line 97 of file FairMCEventHeader.h.
Referenced by GetB(), Reset(), and SetB().
UInt_t FairMCEventHeader::fEventId protected
Run identifier.
Definition at line 92 of file FairMCEventHeader.h.
Referenced by GetEventID(), Reset(), and SetEventID().
Bool_t FairMCEventHeader::fIsSet protected
Number of input tracks.
Definition at line 99 of file FairMCEventHeader.h.
Referenced by IsSet(), MarkSet(), and Reset().
Int_t FairMCEventHeader::fNPrim protected
Impact parameter [fm] (if relevant)
Definition at line 98 of file FairMCEventHeader.h.
Referenced by GetNPrim(), Reset(), and SetNPrim().
Double32_t FairMCEventHeader::fRotX protected
Flag whether variables are filled.
Definition at line 100 of file FairMCEventHeader.h.
Referenced by GetRotX(), Reset(), and SetRotX().
Double32_t FairMCEventHeader::fRotY protected
Rotation around x-axis (beam tilt) [rad].
Definition at line 101 of file FairMCEventHeader.h.
Referenced by GetRotY(), Reset(), and SetRotY().
Double32_t FairMCEventHeader::fRotZ protected
Rotation around y-axis (beam tilt) [rad].
Definition at line 102 of file FairMCEventHeader.h.
Referenced by GetRotZ(), Reset(), and SetRotZ().
UInt_t FairMCEventHeader::fRunId protected
Definition at line 91 of file FairMCEventHeader.h.
Referenced by GetRunID(), and SetRunID().
Double32_t FairMCEventHeader::fT protected
Primary vertex z [cm].
Definition at line 96 of file FairMCEventHeader.h.
Referenced by GetT(), Reset(), and SetTime().
Double32_t FairMCEventHeader::fX protected
Event identifier.
Definition at line 93 of file FairMCEventHeader.h.
Referenced by GetVertex(), GetX(), Reset(), and SetVertex().
Double32_t FairMCEventHeader::fY protected
Primary vertex x [cm].
Definition at line 94 of file FairMCEventHeader.h.
Referenced by GetVertex(), GetY(), Reset(), and SetVertex().
Double32_t FairMCEventHeader::fZ protected
Primary vertex y [cm].
Definition at line 95 of file FairMCEventHeader.h.
Referenced by GetVertex(), GetZ(), Reset(), and SetVertex().
The documentation for this class was generated from the following files:
FairMCEventHeader.h
FairMCEventHeader.cxx