FairRoot: TestDetectorProto::HitPayload Class Reference
TestDetectorProto::HitPayload Class Reference
#include <FairTestDetectorPayload.pb.h>
Public Member Functions
HitPayload ()
virtual ~HitPayload ()
HitPayload (const HitPayload &from)
HitPayload & operator= (const HitPayload &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (HitPayload *other)
HitPayload * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const HitPayload &from)
void MergeFrom (const HitPayload &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int hit_size () const
void clear_hit ()
const ::TestDetectorProto::Hit & hit (int index) const
inline::TestDetectorProto::Hit * mutable_hit (int index)
inline::TestDetectorProto::Hit * add_hit ()
const ::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Hit > & hit () const
inline::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Hit > * mutable_hit ()
HitPayload ()
virtual ~HitPayload ()
HitPayload (const HitPayload &from)
HitPayload & operator= (const HitPayload &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (HitPayload *other)
HitPayload * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const HitPayload &from)
void MergeFrom (const HitPayload &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int hit_size () const
void clear_hit ()
const ::TestDetectorProto::Hit & hit (int index) const
inline::TestDetectorProto::Hit * mutable_hit (int index)
inline::TestDetectorProto::Hit * add_hit ()
const ::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Hit > & hit () const
inline::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Hit > * mutable_hit ()
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const HitPayload & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const HitPayload & default_instance ()
Static Public Attributes
static const int kHitFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Hit > hit_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(1+31)/32]
Static Private Attributes
static HitPayload * default_instance_ = NULL
Friends
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
Detailed Description
Definition at line 422 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Constructor & Destructor Documentation
TestDetectorProto::HitPayload::HitPayload ()
Definition at line 1322 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References SharedCtor().
Referenced by New().
   : ::google::protobuf::Message() {
   SharedCtor();
 }
TestDetectorProto::HitPayload::~HitPayload () virtual
Definition at line 1341 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References SharedDtor().
{
   SharedDtor();
 }
TestDetectorProto::HitPayload::HitPayload (const HitPayload & from)
Definition at line 1330 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References MergeFrom(), and SharedCtor().
   : ::google::protobuf::Message() {
   SharedCtor();
   MergeFrom(from);
 }
TestDetectorProto::HitPayload::HitPayload ()
virtual TestDetectorProto::HitPayload::~HitPayload () virtual
TestDetectorProto::HitPayload::HitPayload (const HitPayload & from)
Member Function Documentation
TestDetectorProto::Hit * TestDetectorProto::HitPayload::add_hit () inline
Definition at line 892 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References hit_.
Referenced by MergePartialFromCodedStream().
{
   return hit_.Add();
 }
inline ::TestDetectorProto::Hit* TestDetectorProto::HitPayload::add_hit ()
int TestDetectorProto::HitPayload::ByteSize () const
int TestDetectorProto::HitPayload::ByteSize () const
Definition at line 1444 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, hit(), hit_size(), and unknown_fields().
{
   int total_size = 0;
   // repeated .TestDetectorProto.Hit hit = 1;
   total_size += 1 * this->hit_size();
   for (int i = 0; i < this->hit_size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->hit(i));
   }
   if (!unknown_fields().empty()) {
     total_size +=
       ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
         unknown_fields());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void TestDetectorProto::HitPayload::Clear ()
void TestDetectorProto::HitPayload::Clear ()
Definition at line 1371 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _has_bits_, hit_, and mutable_unknown_fields().
Referenced by CopyFrom().
{
   hit_.Clear();
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
   mutable_unknown_fields()->Clear();
 }
void TestDetectorProto::HitPayload::clear_hit () inline
Definition at line 883 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References hit_.
{
   hit_.Clear();
 }
void TestDetectorProto::HitPayload::clear_hit () inline
void TestDetectorProto::HitPayload::CopyFrom (const ::google::protobuf::Message & from)
void TestDetectorProto::HitPayload::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1484 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void TestDetectorProto::HitPayload::CopyFrom (const HitPayload & from)
Definition at line 1490 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Clear(), and MergeFrom().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void TestDetectorProto::HitPayload::CopyFrom (const HitPayload & from)
static const HitPayload& TestDetectorProto::HitPayload::default_instance () static
const HitPayload & TestDetectorProto::HitPayload::default_instance () static
Definition at line 1360 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References default_instance_, and protobuf_AddDesc_FairTestDetectorPayload_2eproto.
{
   if (default_instance_ == NULL) protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   return *default_instance_;
 }
const ::google::protobuf::Descriptor * TestDetectorProto::HitPayload::descriptor () static
Definition at line 1355 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   return HitPayload_descriptor_;
 }
static const ::google::protobuf::Descriptor* TestDetectorProto::HitPayload::descriptor () static
int TestDetectorProto::HitPayload::GetCachedSize () const inline
Definition at line 463 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _cached_size_.
 { return _cached_size_; }
int TestDetectorProto::HitPayload::GetCachedSize () const inline
Definition at line 463 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _cached_size_.
 { return _cached_size_; }
google::protobuf::Metadata TestDetectorProto::HitPayload::GetMetadata () const
Definition at line 1510 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::Metadata metadata;
   metadata.descriptor = HitPayload_descriptor_;
   metadata.reflection = HitPayload_reflection_;
   return metadata;
 }
::google::protobuf::Metadata TestDetectorProto::HitPayload::GetMetadata () const
const ::TestDetectorProto::Hit & TestDetectorProto::HitPayload::hit (int index) const inline
Definition at line 886 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References hit_.
{
   return hit_.Get(index);
 }
const ::TestDetectorProto::Hit& TestDetectorProto::HitPayload::hit (int index) const inline
const ::google::protobuf::RepeatedPtrField<::TestDetectorProto::Hit > & TestDetectorProto::HitPayload::hit () const inline
Definition at line 896 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References hit_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
                       {
   return hit_;
 }
const ::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Hit >& TestDetectorProto::HitPayload::hit () const inline
int TestDetectorProto::HitPayload::hit_size () const inline
Definition at line 880 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References hit_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return hit_.size();
 }
int TestDetectorProto::HitPayload::hit_size () const inline
void TestDetectorProto::HitPayload::InitAsDefaultInstance () private
Definition at line 1327 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto().
{
 }
void TestDetectorProto::HitPayload::InitAsDefaultInstance () private
bool TestDetectorProto::HitPayload::IsInitialized () const
bool TestDetectorProto::HitPayload::IsInitialized () const
Definition at line 1496 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   return true;
 }
void TestDetectorProto::HitPayload::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1466 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by CopyFrom(), and HitPayload().
{
   GOOGLE_CHECK_NE(&from, this);
   const HitPayload* source =
     ::google::protobuf::internal::dynamic_cast_if_available<const HitPayload*>(
       &from);
   if (source == NULL) {
     ::google::protobuf::internal::ReflectionOps::Merge(from, this);
   } else {
     MergeFrom(*source);
   }
 }
void TestDetectorProto::HitPayload::MergeFrom (const ::google::protobuf::Message & from)
void TestDetectorProto::HitPayload::MergeFrom (const HitPayload & from)
void TestDetectorProto::HitPayload::MergeFrom (const HitPayload & from)
Definition at line 1478 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References hit_, mutable_unknown_fields(), and unknown_fields().
{
   GOOGLE_CHECK_NE(&from, this);
   hit_.MergeFrom(from.hit_);
   mutable_unknown_fields()->MergeFrom(from.unknown_fields());
 }
bool TestDetectorProto::HitPayload::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool TestDetectorProto::HitPayload::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1377 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References add_hit(), DO_, and mutable_unknown_fields().
{
 #define DO_(EXPRESSION) if (!(EXPRESSION)) return false
   ::google::protobuf::uint32 tag;
   while ((tag = input->ReadTag()) != 0) {
     switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
       // repeated .TestDetectorProto.Hit hit = 1;
       case 1: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          parse_hit:
           DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                 input, add_hit()));
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(10)) goto parse_hit;
         if (input->ExpectAtEnd()) return true;
         break;
       }
       default: {
       handle_uninterpreted:
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
           return true;
         }
         DO_(::google::protobuf::internal::WireFormat::SkipField(
               input, tag, mutable_unknown_fields()));
         break;
       }
     }
   }
   return true;
 #undef DO_
 }
inline ::TestDetectorProto::Hit* TestDetectorProto::HitPayload::mutable_hit (int index)
TestDetectorProto::Hit * TestDetectorProto::HitPayload::mutable_hit (int index) inline
Definition at line 889 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References hit_.
{
   return hit_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::TestDetectorProto::Hit > * TestDetectorProto::HitPayload::mutable_hit () inline
Definition at line 900 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References hit_.
{
   return &hit_;
 }
inline ::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Hit >* TestDetectorProto::HitPayload::mutable_hit ()
inline ::google::protobuf::UnknownFieldSet* TestDetectorProto::HitPayload::mutable_unknown_fields () inline
Definition at line 438 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
{
     return &_unknown_fields_;
   }
inline ::google::protobuf::UnknownFieldSet* TestDetectorProto::HitPayload::mutable_unknown_fields () inline
Definition at line 438 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
{
     return &_unknown_fields_;
   }
HitPayload* TestDetectorProto::HitPayload::New () const
HitPayload * TestDetectorProto::HitPayload::New () const
Definition at line 1367 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References HitPayload().
{
   return new HitPayload;
 }
HitPayload& TestDetectorProto::HitPayload::operator= (const HitPayload & from) inline
Definition at line 429 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
HitPayload& TestDetectorProto::HitPayload::operator= (const HitPayload & from) inline
Definition at line 429 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
void TestDetectorProto::HitPayload::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1414 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References hit(), hit_size(), and unknown_fields().
{
   // repeated .TestDetectorProto.Hit hit = 1;
   for (int i = 0; i < this->hit_size(); i++) {
     ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
       1, this->hit(i), output);
   }
   if (!unknown_fields().empty()) {
     ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
         unknown_fields(), output);
   }
 }
void TestDetectorProto::HitPayload::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
google::protobuf::uint8 * TestDetectorProto::HitPayload::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1428 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References hit(), hit_size(), and unknown_fields().
{
   // repeated .TestDetectorProto.Hit hit = 1;
   for (int i = 0; i < this->hit_size(); i++) {
     target = ::google::protobuf::internal::WireFormatLite::
       WriteMessageNoVirtualToArray(
         1, this->hit(i), target);
   }
   if (!unknown_fields().empty()) {
     target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
         unknown_fields(), target);
   }
   return target;
 }
::google::protobuf::uint8* TestDetectorProto::HitPayload::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
void TestDetectorProto::HitPayload::SetCachedSize (int size) const private
void TestDetectorProto::HitPayload::SetCachedSize (int size) const private
Definition at line 1350 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_.
{
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
 }
void TestDetectorProto::HitPayload::SharedCtor () private
Definition at line 1336 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, and _has_bits_.
Referenced by HitPayload().
{
   _cached_size_ = 0;
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
 }
void TestDetectorProto::HitPayload::SharedCtor () private
void TestDetectorProto::HitPayload::SharedDtor () private
void TestDetectorProto::HitPayload::SharedDtor () private
Definition at line 1345 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References default_instance_.
Referenced by ~HitPayload().
{
   if (this != default_instance_) {
   }
 }
void TestDetectorProto::HitPayload::Swap (HitPayload * other)
Definition at line 1501 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, and hit_.
{
   if (other != this) {
     hit_.Swap(&other->hit_);
     std::swap(_has_bits_[0], other->_has_bits_[0]);
     _unknown_fields_.Swap(&other->_unknown_fields_);
     std::swap(_cached_size_, other->_cached_size_);
   }
 }
void TestDetectorProto::HitPayload::Swap (HitPayload * other)
const ::google::protobuf::UnknownFieldSet& TestDetectorProto::HitPayload::unknown_fields () const inline
Definition at line 434 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
     return _unknown_fields_;
   }
const ::google::protobuf::UnknownFieldSet& TestDetectorProto::HitPayload::unknown_fields () const inline
Definition at line 434 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
{
     return _unknown_fields_;
   }
Friends And Related Function Documentation
void protobuf_AddDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by default_instance().
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void protobuf_AddDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto () friend
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto () friend
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
Member Data Documentation
int TestDetectorProto::HitPayload::_cached_size_ mutable private
Definition at line 495 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
google::protobuf::uint32 TestDetectorProto::HitPayload::_has_bits_ private
Definition at line 496 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), SharedCtor(), and Swap().
google::protobuf::UnknownFieldSet TestDetectorProto::HitPayload::_unknown_fields_ private
Definition at line 491 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
static HitPayload * TestDetectorProto::HitPayload::default_instance_ = NULL static private
Definition at line 503 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by default_instance(), TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto(), TestDetectorProto::protobuf_AssignDesc_FairTestDetectorPayload_2eproto(), TestDetectorProto::protobuf_ShutdownFile_FairTestDetectorPayload_2eproto(), and SharedDtor().
google::protobuf::RepeatedPtrField<::TestDetectorProto::Hit > TestDetectorProto::HitPayload::hit_ private
Definition at line 493 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by add_hit(), Clear(), clear_hit(), hit(), hit_size(), MergeFrom(), mutable_hit(), and Swap().
static const int TestDetectorProto::HitPayload::kHitFieldNumber = 1 static
Definition at line 479 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
The documentation for this class was generated from the following files:
Tutorial3/data/FairTestDetectorPayload.pb.h
Tutorial3/data/FairTestDetectorPayload.pb.cc