FairRroot: FairLink Class Reference
FairLink Class Reference
#include <FairLink.h>
Public Member Functions
FairLink ()
FairLink (Int_t type, Int_t index, Float_t weight=1.)
FairLink (TString branchName, Int_t index, Float_t weight=1.)
FairLink (Int_t file, Int_t entry, Int_t type, Int_t index, Float_t weight=1.)
FairLink (Int_t file, Int_t entry, TString branchName, Int_t index, Float_t weight=1.)
virtual ~FairLink ()
void SetLink (Int_t file, Int_t entry, Int_t type, Int_t index, Float_t weight=1.)
void SetLink (Int_t type, Int_t index, Float_t weight=1.)
Int_t GetFile () const
Int_t GetEntry () const
Int_t GetType () const
Int_t GetIndex () const
Float_t GetWeight () const
void SetWeight (Float_t weight)
void AddWeight (Float_t weight)
virtual void Print (std::ostream &out=std::cout) const
virtual bool operator== (const FairLink &link) const
virtual bool operator< (const FairLink &link) const
ClassDef (FairLink, 3)
Private Attributes
Int_t fFile
Int_t fEntry
Int_t fType
Int_t fIndex
Float_t fWeight
Friends
std::ostream & operator<< (std::ostream &out, const FairLink &link)
Detailed Description
Definition at line 26 of file FairLink.h.
Constructor & Destructor Documentation
FairLink::FairLink ()
Definition at line 20 of file FairLink.cxx.
   :TObject(),
    fFile(-1),
    fEntry(-1),
    fType(-1),
    fIndex(-1),
    fWeight(1.0)
 {
 }
FairLink::FairLink (Int_t type, Int_t index, Float_t weight = 1.)
Definition at line 30 of file FairLink.cxx.
   :TObject(),
    fFile(-1),
    fEntry(-1),
    fType(type),
    fIndex(index),
    fWeight(weight)
 {
 }
FairLink::FairLink (TString branchName, Int_t index, Float_t weight = 1.)
Definition at line 41 of file FairLink.cxx.
   :TObject(),
    fFile(-1),
    fEntry(-1),
    fType(FairRootManager::Instance()->GetBranchId(branchName)),
    fIndex(index),
    fWeight(weight)
 {
 }
FairLink::FairLink (Int_t file, Int_t entry, Int_t type, Int_t index, Float_t weight = 1.)
Definition at line 52 of file FairLink.cxx.
   :TObject(),
    fFile(file),
    fEntry(entry),
    fType(type),
    fIndex(index),
    fWeight(weight)
 {
 }
FairLink::FairLink (Int_t file, Int_t entry, TString branchName, Int_t index, Float_t weight = 1.)
Definition at line 62 of file FairLink.cxx.
   :TObject(),
    fFile(file),
    fEntry(entry),
    fType(FairRootManager::Instance()->GetBranchId(branchName)),
    fIndex(index),
    fWeight(weight)
 {
 }
FairLink::~FairLink () virtual
Definition at line 78 of file FairLink.cxx.
 {
   // TODO Auto-generated destructor stub
 }
Member Function Documentation
void FairLink::AddWeight (Float_t weight) inline
Definition at line 57 of file FairLink.h.
References fWeight.
Referenced by FairMultiLinkedData::InsertLink().
 {fWeight += weight;}
FairLink::ClassDef (FairLink , 3)
Int_t FairLink::GetEntry () const inline
Definition at line 51 of file FairLink.h.
References fEntry.
Referenced by FairRootManager::GetCloneOfLinkData(), FairRootManager::GetCloneOfTClonesArray(), operator<(), operator==(), and Print().
 {return fEntry;}
Int_t FairLink::GetFile () const inline
Definition at line 50 of file FairLink.h.
References fFile.
Referenced by FairRootManager::GetCloneOfLinkData(), FairRootManager::GetCloneOfTClonesArray(), operator<(), operator==(), and Print().
 {return fFile;}
Int_t FairLink::GetIndex () const inline
Definition at line 53 of file FairLink.h.
References fIndex.
Referenced by FairMultiLinkedData::AddLink(), FairMCMatch::CreateArtificialStage(), FairMultiLinkedData::DeleteLink(), FairRootManager::GetCloneOfLinkData(), FairRootManager::GetCloneOfTClonesArray(), FairMultiLinkedData::GetData(), FairMCMatch::GetEntry(), FairMCMatch::GetMCInfoBackwardSingle(), FairMCMatch::GetMCInfoSingle(), FairMultiLinkedData::InsertHistory(), FairMultiLinkedData::IsLinkInList(), FairMultiLinkedData::LinkPosInList(), operator<(), operator==(), FairMCObject::PosInList(), and Print().
 {return fIndex;}
Int_t FairLink::GetType () const inline
Definition at line 52 of file FairLink.h.
References fType.
Referenced by FairMultiLinkedData::AddLink(), FairMultiLinkedData::DeleteLink(), FairMCMatch::FindStagesPointingToLink(), FairMCMatch::FindStagesPointingToLinks(), FairRootManager::GetCloneOfLinkData(), FairRootManager::GetCloneOfTClonesArray(), FairMultiLinkedData::GetData(), FairMCMatch::GetEntry(), FairMCMatch::GetMCInfoBackwardSingle(), FairMCMatch::GetMCInfoSingle(), FairMCDataCrawler::GetNextStage(), FairMCMatch::GetNextStage(), FairMultiLinkedData::InsertHistory(), FairMultiLinkedData::InsertLink(), FairMultiLinkedData::IsLinkInList(), FairMultiLinkedData::LinkPosInList(), operator<(), operator==(), FairMCObject::PosInList(), and Print().
 {return fType;}
Float_t FairLink::GetWeight () const inline
Definition at line 54 of file FairLink.h.
References fWeight.
Referenced by FairMultiLinkedData::AddAllWeights(), FairMultiLinkedData::AddLink(), FairMultiLinkedData::AddLinks(), FairMCDataCrawler::GetNextStage(), FairMCMatch::GetNextStage(), FairMultiLinkedData::InsertLink(), FairMultiLinkedData::MultiplyAllWeights(), Print(), and FairMultiLinkedData::SetLink().
 {return fWeight;}
virtual bool FairLink::operator< (const FairLink & link) const inline virtual
Definition at line 69 of file FairLink.h.
References fEntry, fFile, fIndex, fType, GetEntry(), GetFile(), GetIndex(), and GetType().
{
       if (fFile < link.GetFile()) {
         return true;
       } else if ((fFile == link.GetFile() || link.GetFile() == -1) && fEntry < link.GetEntry()) {
         return true;
       } else if ((fFile == link.GetFile() || link.GetFile() == -1)  && (fEntry == link.GetEntry() || link.GetEntry() == -1) && fType < link.GetType()) {
         return true;
       } else if ((fFile == link.GetFile() || link.GetFile() == -1)  && (fEntry == link.GetEntry() || link.GetEntry() == -1) && fType == link.GetType() && fIndex < link.GetIndex()) {
         return true;
       } else {
         return false;
       }
     }
virtual bool FairLink::operator== (const FairLink & link) const inline virtual
Definition at line 61 of file FairLink.h.
References fEntry, fFile, fIndex, fType, GetEntry(), GetFile(), GetIndex(), and GetType().
{
       if ((fFile == link.GetFile() || link.GetFile() == -1) && (fEntry == link.GetEntry() || link.GetEntry() == -1) && fType == link.GetType() && fIndex == link.GetIndex()) {
         return true;
       } else {
         return false;
       }
     }
void FairLink::Print (std::ostream & out = std::cout) const virtual
Definition at line 72 of file FairLink.cxx.
References GetEntry(), GetFile(), GetIndex(), GetType(), and GetWeight().
Referenced by FairMCDataCrawler::GetNextStage(), FairMCMatch::GetNextStage(), and FairMultiLinkedData::Print().
 {
   out << "(" << GetFile() << "/" << GetEntry() << "/";
   out << GetType() << "/" << GetIndex() << "/" << GetWeight() << ")";
 }
void FairLink::SetLink (Int_t file, Int_t entry, Int_t type, Int_t index, Float_t weight = 1.) inline
Definition at line 36 of file FairLink.h.
References fEntry, fFile, fIndex, fType, and fWeight.
{
       fFile = file;
       fEntry = entry;
       fType = type;
       fIndex = index;
       fWeight = weight;
     };
void FairLink::SetLink (Int_t type, Int_t index, Float_t weight = 1.) inline
Definition at line 43 of file FairLink.h.
References fEntry, fFile, fIndex, fType, and fWeight.
{
       fFile = -1;
       fEntry = -1;
       fType = type;
       fIndex = index;
       fWeight = weight;
     };
void FairLink::SetWeight (Float_t weight) inline
Definition at line 56 of file FairLink.h.
References fWeight.
Referenced by FairMultiLinkedData::AddAllWeights(), FairMultiLinkedData::AddLink(), FairMultiLinkedData::AddLinks(), FairMultiLinkedData::MultiplyAllWeights(), FairMultiLinkedData::SetAllWeights(), and FairMultiLinkedData::SetLink().
 {fWeight = weight;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const FairLink & link) friend
Definition at line 83 of file FairLink.h.
{
       link.Print(out);
       return out;
     }
Member Data Documentation
Int_t FairLink::fEntry private
Definition at line 93 of file FairLink.h.
Referenced by GetEntry(), operator<(), operator==(), and SetLink().
Int_t FairLink::fFile private
Definition at line 92 of file FairLink.h.
Referenced by GetFile(), operator<(), operator==(), and SetLink().
Int_t FairLink::fIndex private
Definition at line 95 of file FairLink.h.
Referenced by GetIndex(), operator<(), operator==(), and SetLink().
Int_t FairLink::fType private
Definition at line 94 of file FairLink.h.
Referenced by GetType(), operator<(), operator==(), and SetLink().
Float_t FairLink::fWeight private
Definition at line 96 of file FairLink.h.
Referenced by AddWeight(), GetWeight(), SetLink(), and SetWeight().
The documentation for this class was generated from the following files:
FairLink.h
FairLink.cxx