FairRroot: MyFieldPar Class Reference
MyFieldPar Class Reference
#include <MyFieldPar.h>
Public Member Functions
MyFieldPar (const char *name, const char *title, const char *context)
MyFieldPar ()
~MyFieldPar ()
virtual void putParams (FairParamList *list)
virtual Bool_t getParams (FairParamList *list)
void SetParameters (FairField *field)
Int_t GetType () const
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
Double_t GetBx () const
Double_t GetBy () const
Double_t GetBz () const
void MapName (TString &name)
Double_t GetPositionX () const
Double_t GetPositionY () const
Double_t GetPositionZ () const
Double_t GetScale () const
Double_t GetPeak () const
Double_t GetMiddle () const
virtual void printParams ()
Bool_t init (FairParIo *inp)
virtual Bool_t init ()
Int_t write (FairParIo *output)
virtual Int_t write ()
void fill (UInt_t rid=0)
void store (UInt_t rid=0)
virtual const char * GetName () const
virtual const char * GetTitle () const
virtual void clear ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setOwnership (Bool_t flag=kTRUE)
Bool_t isOwned ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Attributes
TString fName
TString fTitle
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
Bool_t owned
flag is kTRUE if parameters have changed
TString paramContext
if flag is KTRUE FairDB has the par. class ownership
TString author
TString description
FairLogger * fLogger
Private Member Functions
MyFieldPar (const MyFieldPar &)
MyFieldPar & operator= (const MyFieldPar &)
ClassDef (MyFieldPar, 1)
Private Attributes
Int_t fType
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
Double_t fBx
Double_t fBy
Double_t fBz
TString fMapName
Double_t fPosX
Double_t fPosY
Double_t fPosZ
Double_t fScale
Double_t fPeak
Double_t fMiddle
Detailed Description
Definition at line 26 of file MyFieldPar.h.
Constructor & Destructor Documentation
MyFieldPar::MyFieldPar (const char * name, const char * title, const char * context)
Standard constructor
Definition at line 28 of file MyFieldPar.cxx.
   : FairParGenericSet(name, title, context),
     fType(-1),
     fXmin(0.),
     fXmax(0.),
     fYmin(0.),
     fYmax(0.),
     fZmin(0.),
     fZmax(0.),
     fBx(0.),
     fBy(0.),
     fBz(0.),
     fMapName(""),
     fPosX(0.),
     fPosY(0.),
     fPosZ(0.),
     fScale(0.),
     fPeak(0.),
     fMiddle(0.)
 {
 }
MyFieldPar::MyFieldPar ()
default constructor
Definition at line 53 of file MyFieldPar.cxx.
   : FairParGenericSet(),
     fType(-1),
     fXmin(0.),
     fXmax(0.),
     fYmin(0.),
     fYmax(0.),
     fZmin(0.),
     fZmax(0.),
     fBx(0.),
     fBy(0.),
     fBz(0.),
     fMapName(""),
     fPosX(0.),
     fPosY(0.),
     fPosZ(0.),
     fScale(0.),
     fPeak(0.),
     fMiddle(0.)
 {
 }
MyFieldPar::~MyFieldPar ()
Destructor
Definition at line 78 of file MyFieldPar.cxx.
 { }
MyFieldPar::MyFieldPar (const MyFieldPar &) private
Member Function Documentation
MyFieldPar::ClassDef (MyFieldPar , 1) private
virtual void FairParSet::clear (void) inline virtual inherited
Reimplemented in FairTutorialDet2DigiPar, FairBaseParSet, FairGeoParSet, FairRutherfordGeoPar, FairTutorialDet1GeoPar, FairTutorialDet4GeoPar, FairTestDetectorGeoPar, FairTestDetectorGeoPar, FairTutorialDet2GeoPar, NewDetectorGeoPar, NewDetectorGeoPar, FairGeoPassivePar, FairTutorialDet4MisalignPar, and NewParameterContainer.
Definition at line 46 of file FairParSet.h.
Referenced by FairDetParRootFileIo::read().
 {}
void FairParSet::copyComment (FairParSet & r) inline inherited
Definition at line 77 of file FairParSet.h.
References FairParSet::getAuthor(), and FairParSet::getDescription().
{
       author=r.getAuthor();
       description=r.getDescription();
     }
void FairParGenericSet::fill (UInt_t rid = 0) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 32 of file FairParGenericSet.h.
 {};
const char* FairParSet::getAuthor () const inline inherited
Definition at line 72 of file FairParSet.h.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
 { return author.Data(); }
Double_t MyFieldPar::GetBx () const inline
Definition at line 62 of file MyFieldPar.h.
References fBx.
Referenced by MyConstField::MyConstField().
 { return fBx; }
Double_t MyFieldPar::GetBy () const inline
Definition at line 63 of file MyFieldPar.h.
References fBy.
Referenced by MyConstField::MyConstField().
 { return fBy; }
Double_t MyFieldPar::GetBz () const inline
Definition at line 64 of file MyFieldPar.h.
References fBz.
Referenced by MyConstField::MyConstField().
 { return fBz; }
const char* FairParSet::getDescription () const inline inherited
Definition at line 75 of file FairParSet.h.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
 { return description.Data(); }
const char* FairParSet::getDetectorName () inline inherited
Definition at line 49 of file FairParSet.h.
 {return detName.Data();}
Int_t FairParSet::getInputVersion (Int_t i) inline inherited
Definition at line 55 of file FairParSet.h.
Referenced by FairRuntimeDb::findOutputVersion(), FairDetParRootFileIo::read(), and FairRuntimeDb::writeContainer().
{
       if (i>=0 && i<3) { return versions[i]; }
       else { return 0; }
     }
Double_t MyFieldPar::GetMiddle () const inline
Definition at line 71 of file MyFieldPar.h.
References fMiddle.
 { return fMiddle; }
virtual const char* FairParSet::GetName () const inline virtual inherited
Definition at line 39 of file FairParSet.h.
Referenced by FairRuntimeDb::addContainer(), FairRuntimeDb::addRun(), FairRuntimeDb::findOutputVersion(), FairGenericParAsciiFileIo::init(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), FairRuntimeDb::initContainers(), FairParSet::print(), FairRuntimeDb::print(), FairParGenericSet::printParams(), FairDetParRootFileIo::read(), FairGenericParAsciiFileIo::write(), FairDetParRootFileIo::write(), FairParSet::write(), FairRuntimeDb::writeContainer(), FairGenericParAsciiFileIo::writeGenericSet(), and FairRuntimeDb::~FairRuntimeDb().
 {return (char*)fName.Data();}
const char* FairParSet::getParamContext () const inline inherited
Definition at line 69 of file FairParSet.h.
Referenced by FairGenericParAsciiFileIo::writeGenericSet().
 { return paramContext.Data(); }
Bool_t MyFieldPar::getParams (FairParamList * list) virtual
Get parameters
Implements FairParGenericSet.
Definition at line 118 of file MyFieldPar.cxx.
References fBx, fBy, fBz, FairParamList::fill(), fMapName, fMiddle, fPeak, fPosX, fPosY, fPosZ, fScale, fType, fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, and kMaxFieldMapType.
{
   if ( ! list ) return kFALSE;
   if ( ! list->fill("Field Type", &fType) ) return kFALSE;
   if ( fType == 0 ) {                    // constant field
     if ( ! list->fill("Field min x", &fXmin) ) return kFALSE;
     if ( ! list->fill("Field max x", &fXmax) ) return kFALSE;
     if ( ! list->fill("Field min y", &fYmin) ) return kFALSE;
     if ( ! list->fill("Field max y", &fYmax) ) return kFALSE;
     if ( ! list->fill("Field min z", &fZmin) ) return kFALSE;
     if ( ! list->fill("Field max z", &fZmax) ) return kFALSE;
     if ( ! list->fill("Field Bx", &fBx) ) return kFALSE;
     if ( ! list->fill("Field By", &fBy) ) return kFALSE;
     if ( ! list->fill("Field Bz", &fBz) ) return kFALSE;
   }  else if (fType >=1 && fType <= kMaxFieldMapType) {
       if ( ! list->fill("Field Peak", &fPeak) ) return kFALSE;
       if ( ! list->fill("Field Middle", &fMiddle) ) return kFALSE;
   }  else if (fType >=2 && fType <= kMaxFieldMapType) {    // field map
     Text_t mapName[80];
     if ( ! list->fill("Field map name", mapName, 80) ) return kFALSE;
     fMapName = mapName;
     if ( ! list->fill("Field x position", &fPosX) )  return kFALSE;
     if ( ! list->fill("Field y position", &fPosY) )  return kFALSE;
     if ( ! list->fill("Field z position", &fPosZ) )  return kFALSE;
     if ( ! list->fill("Field scaling factor", &fScale) ) return kFALSE;
   }
   return kTRUE;
 }
Double_t MyFieldPar::GetPeak () const inline
Definition at line 70 of file MyFieldPar.h.
References fPeak.
 { return fPeak; }
Double_t MyFieldPar::GetPositionX () const inline
Definition at line 66 of file MyFieldPar.h.
References fPosX.
 { return fPosX; }
Double_t MyFieldPar::GetPositionY () const inline
Definition at line 67 of file MyFieldPar.h.
References fPosY.
 { return fPosY; }
Double_t MyFieldPar::GetPositionZ () const inline
Definition at line 68 of file MyFieldPar.h.
References fPosZ.
 { return fPosZ; }
Double_t MyFieldPar::GetScale () const inline
Definition at line 69 of file MyFieldPar.h.
References fScale.
 { return fScale; }
virtual const char* FairParSet::GetTitle () const inline virtual inherited
Definition at line 40 of file FairParSet.h.
Referenced by FairRuntimeDb::print().
 {return (char*)fTitle.Data();}
Int_t MyFieldPar::GetType () const inline
Accessors
Definition at line 55 of file MyFieldPar.h.
References fType.
Referenced by MyFieldCreator::createFairField(), and MyConstField::MyConstField().
 { return fType; }
Double_t MyFieldPar::GetXmax () const inline
Definition at line 57 of file MyFieldPar.h.
References fXmax.
Referenced by MyConstField::MyConstField().
 { return fXmax; }
Double_t MyFieldPar::GetXmin () const inline
Definition at line 56 of file MyFieldPar.h.
References fXmin.
Referenced by MyConstField::MyConstField().
 { return fXmin; }
Double_t MyFieldPar::GetYmax () const inline
Definition at line 59 of file MyFieldPar.h.
References fYmax.
Referenced by MyConstField::MyConstField().
 { return fYmax; }
Double_t MyFieldPar::GetYmin () const inline
Definition at line 58 of file MyFieldPar.h.
References fYmin.
Referenced by MyConstField::MyConstField().
 { return fYmin; }
Double_t MyFieldPar::GetZmax () const inline
Definition at line 61 of file MyFieldPar.h.
References fZmax.
Referenced by MyConstField::MyConstField().
 { return fZmax; }
Double_t MyFieldPar::GetZmin () const inline
Definition at line 60 of file MyFieldPar.h.
References fZmin.
Referenced by MyConstField::MyConstField().
 { return fZmin; }
Bool_t FairParSet::hasChanged () inline inherited
Definition at line 67 of file FairParSet.h.
References FairParSet::changed.
Referenced by FairRuntimeDb::findOutputVersion(), and FairRuntimeDb::writeContainer().
 {return changed;}
Bool_t FairParGenericSet::init (FairParIo * inp) virtual inherited
Reimplemented from FairParSet.
Bool_t FairParSet::init () virtual inherited
Definition at line 48 of file FairParSet.cxx.
References FairLogger::Error(), FairParSet::fLogger, FairRuntimeDb::getFirstInput(), FairParSet::GetName(), FairRuntimeDb::getSecondInput(), FairRuntimeDb::instance(), MESSAGE_ORIGIN, and FairParSet::setInputVersion().
Referenced by FairRuntimeDb::initContainers().
 {
   // intitializes the container from an input in run time
   // database. If this is not successful it is initialized from
   // the second input. If this failes too, it returns an error.
   // (calls internally the init function in the derived class)
   FairRuntimeDb* rtdb=FairRuntimeDb::instance();
   //FairRunAna* fRun =FairRunAna::Instance();
 // cout << "-I-  FairParSet::init() " << GetName() << endl;
   Bool_t allFound=kFALSE;
   FairParIo* io=0;
   if (rtdb) {
     io=rtdb->getFirstInput();
     if (io) { allFound=init(io); }
     if (!allFound) {
       io=rtdb->getSecondInput();
       //cout << "-I FairParSet::init() 2 " << io <<  std::endl;
       if (io) { allFound=init(io); }
     } else { setInputVersion(-1,2); }
   }
   if (allFound) { return kTRUE; }
   if (fLogger ) { fLogger->Error(MESSAGE_ORIGIN, "init() %s  not initialized",GetName()); }
   return kFALSE;
 }
Bool_t FairParSet::isOwned () inline inherited
Definition at line 64 of file FairParSet.h.
References FairParSet::owned.
Referenced by FairRuntimeDb::~FairRuntimeDb().
 {return owned;}
Bool_t FairParSet::isStatic () inline inherited
Definition at line 61 of file FairParSet.h.
References FairParSet::status.
Referenced by FairRuntimeDb::initContainers(), and FairRuntimeDb::resetInputVersions().
 {return status;}
void MyFieldPar::MapName (TString & name) inline
Definition at line 65 of file MyFieldPar.h.
References fMapName.
 { name = fMapName; }
MyFieldPar& MyFieldPar::operator= (const MyFieldPar &) private
void FairParSet::print () virtual inherited
Definition at line 86 of file FairParSet.cxx.
References FairParSet::author, FairParSet::changed, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParSet::status, and FairParSet::versions.
Referenced by FairRuntimeDb::writeContainer().
 {
   // prints information about container (versions,status,hasChanged...)
   cout<<"-----  "<<GetName()<<"  -----"<<'\n';
   if (!paramContext.IsNull()) { cout<<"Context/Purpose:       "<<paramContext<<'\n'; }
   if (!author.IsNull()) { cout<<"Author:                "<<author<<'\n'; }
   if (!description.IsNull()) { cout<<"Description:           "<<description<<'\n'; }
   cout<<"first input version:   "<<versions[1]<<'\n';
   cout<<"second input version:  "<<versions[2]<<'\n';
   if (changed) { cout<<"has changed"<<'\n'; }
   else { cout<<"has not changed"<<'\n'; }
   if (status) { cout<<"is static"<<'\n'; }
   else { cout<<"is not static"<<'\n'; }
 }
void FairParGenericSet::printParams () virtual inherited
Definition at line 59 of file FairParGenericSet.cxx.
References FairParSet::author, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParamList::print(), and FairParGenericSet::putParams().
 {
   // prints information about the container
   std::cout<<"\n---------------------------------------------\n";
   std::cout<<"-----  "<<GetName()<<"  -----\n";
   if (!paramContext.IsNull()) { std::cout<<"--  Context/Purpose:  "<<paramContext<<'\n'; }
   if (!author.IsNull()) { std::cout<<"--  Author:           "<<author<<'\n'; }
   if (!description.IsNull()) { std::cout<<"--  Description:      "<<description<<'\n'; }
   std::cout<<"---------------------------------------------\n";
   FairParamList* condList = new FairParamList;
   putParams(condList);
   condList->print();
   std::cout<<"---------------------------------------------\n\n";
   delete condList;
 }
void MyFieldPar::putParams (FairParamList * list) virtual
Put parameters
Implements FairParGenericSet.
Definition at line 84 of file MyFieldPar.cxx.
References FairParamList::add(), fBx, fBy, fBz, fMapName, fMiddle, fPeak, fPosX, fPosY, fPosZ, fScale, fType, fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, and kMaxFieldMapType.
{
   if ( ! list ) return;
   list->add("Field Type", fType);
   if ( fType == 0 ) {                    // constant field
     list->add("Field min x", fXmin);
     list->add("Field max x", fXmax);
     list->add("Field min y", fYmin);
     list->add("Field max y", fYmax);
     list->add("Field min z", fZmin);
     list->add("Field max z", fZmax);
     list->add("Field Bx", fBx);
     list->add("Field By", fBy);
     list->add("Field Bz", fBz);
   } else if (fType >=1 && fType <= kMaxFieldMapType) {    //
     list->add("Field Peak", fPeak);
     list->add("Field Middle", fMiddle);
   } else if (fType >=2 && fType <= kMaxFieldMapType) {    // field map
     list->add("Field map name", fMapName);
     list->add("Field x position", fPosX);
     list->add("Field y position", fPosY);
     list->add("Field z position", fPosZ);
     list->add("Field scaling factor", fScale);
   }
 }
void FairParSet::resetInputVersions () inherited
Definition at line 101 of file FairParSet.cxx.
References FairParSet::changed, FairParSet::status, and FairParSet::versions.
Referenced by FairTutorialDet2DigiPar::clear(), and FairRuntimeDb::resetInputVersions().
 {
   // resets the input versions if the container is not static
   if (!status) {
     for(Int_t i=0; i<3; i++) {versions[i]=-1;}
     changed=kFALSE;
   }
 }
void FairParSet::setAuthor (const char * s) inline inherited
Definition at line 71 of file FairParSet.h.
Referenced by FairDetParAsciiFileIo::readComment().
 {author=s;}
void FairParSet::setChanged (Bool_t flag = kTRUE) inline inherited
Definition at line 66 of file FairParSet.h.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairConstField::FillParContainer(), FairRunOnline::Init(), FairRunSim::Init(), FairDetParRootFileIo::read(), FairDetParRootFileIo::write(), FairRuntimeDb::writeContainer(), and FairGenericParAsciiFileIo::writeGenericSet().
 {changed=flag;}
void FairParSet::setDescription (const char * s) inline inherited
Definition at line 74 of file FairParSet.h.
Referenced by FairDetParAsciiFileIo::readComment().
 {description=s;}
void FairParSet::setInputVersion (Int_t v = -1, Int_t i = 0) inline inherited
Definition at line 52 of file FairParSet.h.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairConstField::FillParContainer(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), and FairDetParRootFileIo::read().
{
       if (i>=0 && i<3) { versions[i]=v; }
     }
void FairParSet::setOwnership (Bool_t flag = kTRUE) inline inherited
Definition at line 63 of file FairParSet.h.
 {owned=flag;}
void MyFieldPar::SetParameters (FairField * field)
Set parameters from CbmField
Definition at line 158 of file MyFieldPar.cxx.
References fBx, fBy, fBz, fMapName, fPosX, fPosY, fPosZ, fScale, fType, fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, MyConstField::GetBx(), MyConstField::GetBy(), MyConstField::GetBz(), MyConstField::GetXmax(), MyConstField::GetXmin(), MyConstField::GetYmax(), MyConstField::GetYmin(), MyConstField::GetZmax(), and MyConstField::GetZmin().
{
   if ( ! field ) {
     cerr << "-W- MyFieldPar::SetParameters: Empty field pointer!" << endl;
     return;
   }
   fType = field->GetType();
   if ( fType == 0 ) {                                 // constant field
     MyConstField* fieldConst = (MyConstField*) field;
     fBx = fieldConst->GetBx();
     fBy = fieldConst->GetBy();
     fBz = fieldConst->GetBz();
     fXmin = fieldConst->GetXmin();
     fXmax = fieldConst->GetXmax();
     fYmin = fieldConst->GetYmin();
     fYmax = fieldConst->GetYmax();
     fZmin = fieldConst->GetZmin();
     fZmax = fieldConst->GetZmax();
     fMapName = "";
     fPosX = fPosY = fPosZ = fScale = 0.;
   }  else {
     cerr << "-W- MyFieldPar::SetParameters: Unknown field type "
          << fType << "!" << endl;
     fBx = fBy = fBz = 0.;
     fXmin = fXmax = fYmin = fYmax = fZmin = fZmax = 0.;
     fMapName = "";
     fPosX = fPosY = fPosZ = fScale = 0.;
   }
   return;
 }
void FairParSet::setStatic (Bool_t flag = kTRUE) inline inherited
Definition at line 60 of file FairParSet.h.
Referenced by FairRuntimeDb::setContainersStatic().
 {status=flag;}
void FairParGenericSet::store (UInt_t rid = 0) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 33 of file FairParGenericSet.h.
 {};
Int_t FairParGenericSet::write (FairParIo * output) virtual inherited
Reimplemented from FairParSet.
Definition at line 50 of file FairParGenericSet.cxx.
References FairParIo::getDetParIo(), and FairDetParIo::write().
 {
   // writes the container to an output
   FairDetParIo* out=output->getDetParIo("FairGenericParIo");
   if (out) { return out->write(this); }
   return -1;
 }
Int_t FairParSet::write () virtual inherited
Definition at line 74 of file FairParSet.cxx.
References FairLogger::Error(), FairParSet::fLogger, FairParSet::GetName(), FairRuntimeDb::getOutput(), FairRuntimeDb::instance(), and MESSAGE_ORIGIN.
Referenced by FairRuntimeDb::writeContainer().
 {
   // writes the container to the output defined in the runtime database
   // returns the output version in the ROOT file
   // returns -1 if error occured
   // (calls internally the init function in the derived class)
   FairParIo* output=FairRuntimeDb::instance()->getOutput();
   if (output) { return write(output); }
   if (fLogger) { fLogger->Error(MESSAGE_ORIGIN,"write() %s could not be written to output",GetName()); }
   return -1;
 }
Member Data Documentation
TString FairParSet::author protected inherited
Definition at line 30 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
Bool_t FairParSet::changed protected inherited
static flag
Definition at line 27 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::hasChanged(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
TString FairParSet::description protected inherited
Definition at line 31 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
TString FairParSet::detName protected inherited
Definition at line 24 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairTutorialDet2DigiPar::FairTutorialDet2DigiPar(), and FairParSet::operator=().
Double_t MyFieldPar::fBx private
Field values in case of constant field [kG]
Definition at line 94 of file MyFieldPar.h.
Referenced by GetBx(), getParams(), putParams(), and SetParameters().
Double_t MyFieldPar::fBy private
Definition at line 94 of file MyFieldPar.h.
Referenced by GetBy(), getParams(), putParams(), and SetParameters().
Double_t MyFieldPar::fBz private
Definition at line 94 of file MyFieldPar.h.
Referenced by GetBz(), getParams(), putParams(), and SetParameters().
FairLogger* FairParSet::fLogger protected inherited
Fair Logger
Definition at line 33 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::init(), FairParSet::operator=(), and FairParSet::write().
TString MyFieldPar::fMapName private
Field map name in case of field map
Definition at line 98 of file MyFieldPar.h.
Referenced by getParams(), MapName(), putParams(), and SetParameters().
Double_t MyFieldPar::fMiddle private
Definition at line 110 of file MyFieldPar.h.
Referenced by GetMiddle(), getParams(), and putParams().
TString FairParSet::fName protected inherited
Definition at line 22 of file FairParSet.h.
Referenced by ClassImp(), FairBaseContFact::FairBaseContFact(), FairParSet::FairParSet(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), MyPassiveContFact::MyPassiveContFact(), and FairParSet::operator=().
Double_t MyFieldPar::fPeak private
field parameters
Definition at line 109 of file MyFieldPar.h.
Referenced by getParams(), GetPeak(), and putParams().
Double_t MyFieldPar::fPosX private
Field centre position for field map
Definition at line 102 of file MyFieldPar.h.
Referenced by getParams(), GetPositionX(), putParams(), and SetParameters().
Double_t MyFieldPar::fPosY private
Definition at line 102 of file MyFieldPar.h.
Referenced by getParams(), GetPositionY(), putParams(), and SetParameters().
Double_t MyFieldPar::fPosZ private
Definition at line 102 of file MyFieldPar.h.
Referenced by getParams(), GetPositionZ(), putParams(), and SetParameters().
Double_t MyFieldPar::fScale private
Scaling factor for field map
Definition at line 106 of file MyFieldPar.h.
Referenced by getParams(), GetScale(), putParams(), and SetParameters().
TString FairParSet::fTitle protected inherited
Definition at line 23 of file FairParSet.h.
Referenced by FairBaseContFact::FairBaseContFact(), FairParSet::FairParSet(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), MyPassiveContFact::MyPassiveContFact(), and FairParSet::operator=().
Int_t MyFieldPar::fType private
Field type 0 = constant field 1 = field map 2 = field map sym2 (symmetries in x and y) 3 = field map sym3 (symmetries in x, y and z) kTypeDistorted = distorted field map (its parent field can be field map or constant field)
Definition at line 84 of file MyFieldPar.h.
Referenced by getParams(), GetType(), putParams(), and SetParameters().
Double_t MyFieldPar::fXmax private
Definition at line 88 of file MyFieldPar.h.
Referenced by getParams(), GetXmax(), putParams(), and SetParameters().
Double_t MyFieldPar::fXmin private
Field limits in case of constant field
Definition at line 88 of file MyFieldPar.h.
Referenced by getParams(), GetXmin(), putParams(), and SetParameters().
Double_t MyFieldPar::fYmax private
Definition at line 89 of file MyFieldPar.h.
Referenced by getParams(), GetYmax(), putParams(), and SetParameters().
Double_t MyFieldPar::fYmin private
Definition at line 89 of file MyFieldPar.h.
Referenced by getParams(), GetYmin(), putParams(), and SetParameters().
Double_t MyFieldPar::fZmax private
Definition at line 90 of file MyFieldPar.h.
Referenced by getParams(), GetZmax(), putParams(), and SetParameters().
Double_t MyFieldPar::fZmin private
Definition at line 90 of file MyFieldPar.h.
Referenced by getParams(), GetZmin(), putParams(), and SetParameters().
Bool_t FairParSet::owned protected inherited
flag is kTRUE if parameters have changed
Definition at line 28 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::isOwned(), and FairParSet::operator=().
TString FairParSet::paramContext protected inherited
if flag is KTRUE FairDB has the par. class ownership
Definition at line 29 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
Bool_t FairParSet::status protected inherited
versions of container in the 2 possible inputs
Definition at line 26 of file FairParSet.h.
Referenced by FairTutorialDet2DigiPar::clear(), FairParSet::FairParSet(), FairParSet::isStatic(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
Int_t FairParSet::versions[3] protected inherited
name of the detector the container belongs to
Definition at line 25 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
The documentation for this class was generated from the following files:
MyFieldPar.h
MyFieldPar.cxx