FairRroot: FairTestOutputHandler Class Reference
FairTestOutputHandler Class Reference
#include <FairTestOutputHandler.h>
Public Member Functions
FairTestOutputHandler (std::string filename)
FairTestOutputHandler ()
~FairTestOutputHandler ()
std::string GetCaptureLine (int line)
int GetNumberOfLines ()
void SetFileName (std::string filename)
Private Member Functions
void ReadContentFromFile ()
Private Attributes
std::string fFileName
std::vector< std::string > fFileContent
std::vector< std::string >
::iterator fFileContentIterator
int fNumberOfLines
bool fFileAlreadyRead
Detailed Description
Definition at line 15 of file FairTestOutputHandler.h.
Constructor & Destructor Documentation
FairTestOutputHandler::FairTestOutputHandler (std::string filename)
Definition at line 12 of file FairTestOutputHandler.cxx.
   : fFileName(filename),
     fFileContent(),
     fFileContentIterator(),
     fNumberOfLines(0),
     fFileAlreadyRead(false)
 {
 }
FairTestOutputHandler::FairTestOutputHandler ()
Definition at line 21 of file FairTestOutputHandler.cxx.
   : fFileName(),
     fFileContent(),
     fFileContentIterator(),
     fNumberOfLines(0),
     fFileAlreadyRead(false)
 {
 }
FairTestOutputHandler::~FairTestOutputHandler ()
Definition at line 30 of file FairTestOutputHandler.cxx.
References fFileName.
 {
   remove(fFileName.c_str());
 }
Member Function Documentation
std::string FairTestOutputHandler::GetCaptureLine (int line)
Definition at line 66 of file FairTestOutputHandler.cxx.
References fFileContent, and ReadContentFromFile().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckFileOutput(), FairCaptureOutput::GetCaptureLine(), and TEST_P().
 {
   ReadContentFromFile();
   return fFileContent[line];
 }
int FairTestOutputHandler::GetNumberOfLines ()
Definition at line 43 of file FairTestOutputHandler.cxx.
References fNumberOfLines, and ReadContentFromFile().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckFileOutput(), and FairCaptureOutput::GetNumberOfLines().
 {
   ReadContentFromFile();
   return fNumberOfLines;
 }
void FairTestOutputHandler::ReadContentFromFile () private
Definition at line 49 of file FairTestOutputHandler.cxx.
References fFileAlreadyRead, fFileContent, fFileName, and fNumberOfLines.
Referenced by GetCaptureLine(), and GetNumberOfLines().
 {
   if ( !fFileAlreadyRead ) {
     fFileContent.clear();
     fNumberOfLines = 0;
     std::ifstream ifs(fFileName.c_str());
     std::string line;
     while( getline( ifs, line ) ) {
       fFileContent.push_back( line );
       ++fNumberOfLines;
     }
     fFileAlreadyRead = true;
   }
 }
void FairTestOutputHandler::SetFileName (std::string filename)
Definition at line 35 of file FairTestOutputHandler.cxx.
References fFileAlreadyRead, fFileContent, fFileName, and fNumberOfLines.
Referenced by FairCaptureOutput::BeginCapture().
 {
   fFileName = filename;
   fFileContent.clear();
   fNumberOfLines = 0;
   fFileAlreadyRead =false;
 }
Member Data Documentation
bool FairTestOutputHandler::fFileAlreadyRead private
Definition at line 35 of file FairTestOutputHandler.h.
Referenced by ReadContentFromFile(), and SetFileName().
std::vector<std::string> FairTestOutputHandler::fFileContent private
Definition at line 32 of file FairTestOutputHandler.h.
Referenced by GetCaptureLine(), ReadContentFromFile(), and SetFileName().
std::vector<std::string>::iterator FairTestOutputHandler::fFileContentIterator private
Definition at line 33 of file FairTestOutputHandler.h.
std::string FairTestOutputHandler::fFileName private
Definition at line 31 of file FairTestOutputHandler.h.
Referenced by ReadContentFromFile(), SetFileName(), and ~FairTestOutputHandler().
int FairTestOutputHandler::fNumberOfLines private
Definition at line 34 of file FairTestOutputHandler.h.
Referenced by GetNumberOfLines(), ReadContentFromFile(), and SetFileName().
The documentation for this class was generated from the following files:
FairTestOutputHandler.h
FairTestOutputHandler.cxx