/********************************************************************************
 * Copyright (C) 2014-2023 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH  *
 *                                                                              *
 *              This software is distributed under the terms of the             *
 *              GNU Lesser General Public Licence (LGPL) version 3,             *
 *                  copied verbatim in the file "LICENSE"                       *
 ********************************************************************************/
/* Generated by Together */

#include "FairDoubleHit.h"

FairDoubleHit::FairDoubleHit()
    : fRefIndex(-1)
    , fDetectorID(-1)
    , fPosition_in()
    , fPositionError_in()
    , fPosition_out()
    , fPositionError_out()
{}

FairDoubleHit::~FairDoubleHit() {}
