FairRoot: MyHitDeSerializer< PodType, HitType > Class Template Reference
MyHitDeSerializer< PodType, HitType > Class Template Reference
#include <MyHitSerializer.h>
Public Member Functions
MyHitDeSerializer ()
virtual ~MyHitDeSerializer ()
virtual void DoDeSerialization (FairMQMessage *msg)
virtual TClonesArray * DeSerializeMsg (FairMQMessage *msg)
void InitContainer (const std::string &ClassName)
void InitContainer (TClonesArray *array)
void GetPayload (FairMQMessage *msg)
void SetMessage (FairMQMessage *msg)
FairMQMessage * GetMessage ()
Protected Attributes
TClonesArray * fContainer
PodType * fPayload
FairMQMessage * fMessage
int fNumInput
Detailed Description
template<typename PodType, typename HitType>
class MyHitDeSerializer< PodType, HitType >
Definition at line 93 of file MyHitSerializer.h.
Constructor & Destructor Documentation
template<typename PodType , typename HitType > MyHitDeSerializer< PodType, HitType >::MyHitDeSerializer () inline
Definition at line 102 of file MyHitSerializer.h.
 : BinaryBaseClassSerializer<PodType>(), fContainer(nullptr) {}
template<typename PodType , typename HitType > virtual MyHitDeSerializer< PodType, HitType >::~MyHitDeSerializer () inline virtual
Definition at line 103 of file MyHitSerializer.h.
References MyHitDeSerializer< PodType, HitType >::fContainer.
     {
         if(fContainer)
             delete fContainer;
         fContainer=nullptr;
     }
Member Function Documentation
template<typename PodType , typename HitType > virtual TClonesArray* MyHitDeSerializer< PodType, HitType >::DeSerializeMsg (FairMQMessage * msg) inline virtual
Definition at line 131 of file MyHitSerializer.h.
References MyHitDeSerializer< PodType, HitType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::fContainer.
     {
         DoDeSerialization(msg);
         return fContainer;
     }
template<typename PodType , typename HitType > virtual void MyHitDeSerializer< PodType, HitType >::DoDeSerialization (FairMQMessage * msg) inline virtual
Definition at line 110 of file MyHitSerializer.h.
References ERROR, MyHitDeSerializer< PodType, HitType >::fContainer, BinaryBaseClassSerializer< PodType >::fNumInput, BinaryBaseClassSerializer< PodType >::fPayload, BinaryBaseClassSerializer< PodType >::GetPayload(), and MQLOG.
Referenced by MyHitDeSerializer< PodType, HitType >::DeSerializeMsg().
     {
         GetPayload(msg);
         if(fContainer)
         {
             fContainer->Delete();
             for (Int_t i = 0; i < fNumInput; ++i)
             {
                 TVector3 pos(fPayload[i].posX, fPayload[i].posY, fPayload[i].posZ);
                 TVector3 dpos(fPayload[i].dposX, fPayload[i].dposY, fPayload[i].dposZ);
                 new ((*fContainer)[i]) HitType(fPayload[i].detID, fPayload[i].mcindex, pos, dpos);
             }
             if (fContainer->IsEmpty())
             {
                 MQLOG(ERROR) << "MyHitDeSerializer::DeSerializeMsg(): No Output array!";
             }
         }
     }
FairMQMessage* BinaryBaseClassSerializer< PodType >::GetMessage () inline inherited
Definition at line 37 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fMessage.
     {
         return fMessage;
     }
void BinaryBaseClassSerializer< PodType >::GetPayload (FairMQMessage * msg) inline inherited
Definition at line 24 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fNumInput, BinaryBaseClassSerializer< TPayload >::fPayload, FairMQMessage::GetData(), and FairMQMessage::GetSize().
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
     {
         int inputSize = msg->GetSize();
         if(inputSize>0)
             fNumInput = inputSize / sizeof(TPayload);
         fPayload = static_cast<TPayload*>(msg->GetData());
     }
template<typename PodType , typename HitType > void MyHitDeSerializer< PodType, HitType >::InitContainer (const std::string & ClassName) inline
Definition at line 137 of file MyHitSerializer.h.
References MyHitDeSerializer< PodType, HitType >::fContainer.
     {
         fContainer = new TClonesArray(ClassName.c_str());
     }
template<typename PodType , typename HitType > void MyHitDeSerializer< PodType, HitType >::InitContainer (TClonesArray * array) inline
Definition at line 142 of file MyHitSerializer.h.
References MyHitDeSerializer< PodType, HitType >::fContainer.
     {
         fContainer = array;
     }
void BinaryBaseClassSerializer< PodType >::SetMessage (FairMQMessage * msg) inline inherited
Definition at line 32 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fMessage.
     {
         fMessage=msg;
     }
Member Data Documentation
template<typename PodType , typename HitType > TClonesArray* MyHitDeSerializer< PodType, HitType >::fContainer protected
Definition at line 149 of file MyHitSerializer.h.
Referenced by MyHitDeSerializer< PodType, HitType >::DeSerializeMsg(), MyHitDeSerializer< PodType, HitType >::DoDeSerialization(), MyHitDeSerializer< PodType, HitType >::InitContainer(), and MyHitDeSerializer< PodType, HitType >::~MyHitDeSerializer().
FairMQMessage* BinaryBaseClassSerializer< PodType >::fMessage protected inherited
Definition at line 46 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiSerializer< PodType, DigiType >::DoSerialization(), MyHitSerializer< PodType, HitType >::DoSerialization(), MyDigiSerializer< PodType, DigiType >::SerializeMsg(), and MyHitSerializer< PodType, HitType >::SerializeMsg().
int BinaryBaseClassSerializer< PodType >::fNumInput protected inherited
Definition at line 47 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
PodType * BinaryBaseClassSerializer< PodType >::fPayload protected inherited
Definition at line 45 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
The documentation for this class was generated from the following file:
MyHitSerializer.h