FairRoot: FairMCMatch Class Reference
FairMCMatch Class Reference
#include <FairMCMatch.h>
Public Member Functions
FairMCMatch ()
FairMCMatch (const char *name, const char *title)
virtual ~FairMCMatch ()
void AddElement (Int_t type, int index, FairLink link)
void AddElement (Int_t sourceType, int index, Int_t targetType, int link)
void SetElements (Int_t sourceType, int index, FairMultiLinkedData *links)
void InitStage (Int_t type, std::string fileName, std::string branchName)
void InitStage (std::string fileName, std::string branchName="")
void RemoveStage (Int_t type)
void LoadInMCLists (TClonesArray *myLinkArray)
void ClearMCList ()
void SetCommonWeightStages (Float_t weight)
FairMCEntry GetEntry (Int_t type, int index)
FairMCEntry GetEntry (FairLink link)
FairMCResult GetMCInfo (Int_t start, Int_t stop)
FairMCResult GetMCInfo (TString start, TString stop)
FairMCEntry GetMCInfoSingle (FairLink aLink, Int_t stop)
FairMCEntry GetMCInfoSingle (FairLink aLink, TString stop)
int GetNMCStages () const
FairMCStage * GetMCStage (int index) const
FairMCStage * GetMCStageType (TString branch)
FairMCStage * GetMCStageType (Int_t type)
void CreateArtificialStage (TString branchName, std::string fileName="")
void CreateArtificialStage (Int_t stage, std::string fileName="", std::string branchName="")
FairMultiLinkedData FindLinksToStage (Int_t stage)
bool IsTypeInList (Int_t type)
void Print (std::ostream &out=std::cout)
Private Member Functions
void FindStagesPointingToLinks (FairMultiLinkedData links, Int_t stop)
FairMultiLinkedData FindStagesPointingToLink (FairLink link)
FairMCResult GetMCInfoForward (Int_t start, Int_t stop)
FairMCResult GetMCInfoBackward (Int_t start, Int_t stop)
FairMCEntry GetMCInfoForwardSingle (FairLink link, Int_t stop)
FairMCEntry GetMCInfoBackwardSingle (FairLink link, Int_t stop, Double_t weight=1.)
void GetNextStage (FairMultiLinkedData &startEntry, Int_t stopStage)
void AddToFinalStage (FairLink link, Float_t mult)
void ClearFinalStage ()
ClassDef (FairMCMatch, 1)
Private Attributes
Int_t fUltimateStage
last stage in link chain. Here all recursive operations must stop.
std::map< Int_t, FairMCStage * > fList
FairMultiLinkedData fFinalStageML
Int_t fVerbose
Friends
std::ostream & operator<< (std::ostream &out, const FairMCMatch &match)
Detailed Description
Definition at line 41 of file FairMCMatch.h.
Constructor & Destructor Documentation
FairMCMatch::FairMCMatch ()
Definition at line 26 of file FairMCMatch.cxx.
References fFinalStageML, and FairMultiLinkedData::SetPersistanceCheck().
   : TNamed(),
     fUltimateStage(0),
     fList(),
     fFinalStageML(),
     fVerbose(0)
 {
   fFinalStageML.SetPersistanceCheck(kFALSE);
 }
FairMCMatch::FairMCMatch (const char * name, const char * title) inline
Definition at line 45 of file FairMCMatch.h.
References fFinalStageML, and FairMultiLinkedData::SetPersistanceCheck().
       : TNamed(name, title),
         fUltimateStage(0),
         fList(),
         fFinalStageML(),
         fVerbose(0) {
       fFinalStageML.SetPersistanceCheck(kFALSE);
     }
FairMCMatch::~FairMCMatch () virtual
Definition at line 36 of file FairMCMatch.cxx.
References fList.
 {
   for (TListIterator iter = fList.begin(); iter != fList.end(); iter++) {
     delete(iter->second);
   }
   fList.clear();
 }
Member Function Documentation
void FairMCMatch::AddElement (Int_t type, int index, FairLink link)
Definition at line 50 of file FairMCMatch.cxx.
References fList.
Referenced by AddElement().
 {
   fList[type]->AddLink(link, index);
 }
void FairMCMatch::AddElement (Int_t sourceType, int index, Int_t targetType, int link)
Definition at line 44 of file FairMCMatch.cxx.
References AddElement().
 {
   FairLink myPair(targetType, link);
   AddElement(sourceType, index, myPair);
 }
void FairMCMatch::AddToFinalStage (FairLink link, Float_t mult) private
Definition at line 366 of file FairMCMatch.cxx.
References FairMultiLinkedData::AddLink(), and fFinalStageML.
Referenced by GetNextStage().
 {
   fFinalStageML.AddLink(hitPair, true, mult);
 }
FairMCMatch::ClassDef (FairMCMatch , 1) private
void FairMCMatch::ClearFinalStage () private
Definition at line 371 of file FairMCMatch.cxx.
References fFinalStageML, and FairMultiLinkedData::Reset().
Referenced by GetMCInfoBackwardSingle(), and GetMCInfoForwardSingle().
 {
   fFinalStageML.Reset();
 }
void FairMCMatch::ClearMCList ()
Definition at line 376 of file FairMCMatch.cxx.
References fList.
Referenced by FairMCMatchLoaderTask::Exec(), and FairMCMatchCreatorTask::Exec().
 {
   for (TListIterator iter = fList.begin(); iter != fList.end(); iter++) {
     if (iter->second != 0) {
       iter->second->ClearEntries();
     }
   }
   fList.clear();
 }
void FairMCMatch::CreateArtificialStage (TString branchName, std::string fileName = "")
Definition at line 257 of file FairMCMatch.cxx.
References FairRootManager::GetBranchId(), and FairRootManager::Instance().
Referenced by FairMCMatchLoaderTask::Exec(), and FairMCMatchSelectorTask::Exec().
 {
   FairRootManager* ioman = FairRootManager::Instance();
   std::cout << "Create Artificial Stage for " << branchName;
   std::cout << " with ID " << ioman->GetBranchId(branchName) << std::endl;
   if (ioman->GetBranchId(branchName) > -1) {
     CreateArtificialStage(ioman->GetBranchId(branchName), fileName, branchName.Data());
   } else {
     std::cout << "-E- FairMCMatch::CreateArtificialStage: Branch does not exist: " << branchName << std::endl;
   }
 }
void FairMCMatch::CreateArtificialStage (Int_t stage, std::string fileName = "", std::string branchName = "")
Definition at line 269 of file FairMCMatch.cxx.
References FindLinksToStage(), fList, FairLink::GetIndex(), FairMultiLinkedData::GetLink(), FairMultiLinkedData::GetNLinks(), InitStage(), FairMultiLinkedData::SetLink(), and FairMultiLinkedData::SetPersistanceCheck().
 {
   FairMultiLinkedData stageLinks = FindLinksToStage(stage);
   stageLinks.SetPersistanceCheck(kFALSE);
   if (stageLinks.GetNLinks() > 0) {
     InitStage(stage, fileName, branchName);
     FairMultiLinkedData artData;
     artData.SetLink(FairLink((Int_t)-1, -1));
     for (int i = 0; i < stageLinks.GetNLinks(); i++) {
       if (stageLinks.GetLink(i).GetIndex() > -1) {
         fList[stage]->SetEntry(&artData, stageLinks.GetLink(i).GetIndex());
       }
     }
     fList[stage]->SetLoaded(kTRUE);
   }
 }
FairMultiLinkedData FairMCMatch::FindLinksToStage (Int_t stage)
Definition at line 247 of file FairMCMatch.cxx.
References FairMultiLinkedData::AddLinks(), GetMCStage(), GetNMCStages(), and FairMultiLinkedData::SetPersistanceCheck().
Referenced by CreateArtificialStage().
 {
   FairMultiLinkedData result;
   result.SetPersistanceCheck(kFALSE);
   for (int i = 0; i < GetNMCStages(); i++) {
     result.AddLinks(GetMCStage(i)->GetLinksWithType(stage), true);
   }
   return result;
 }
FairMultiLinkedData FairMCMatch::FindStagesPointingToLink (FairLink link) private
Definition at line 233 of file FairMCMatch.cxx.
References FairMultiLinkedData::AddLinks(), fList, FairLink::GetType(), and FairMultiLinkedData::SetPersistanceCheck().
Referenced by FindStagesPointingToLinks().
 {
   FairMultiLinkedData result;
   result.SetPersistanceCheck(kFALSE);
   TListIteratorConst iter = fList.find((Int_t)link.GetType());
   for(; iter!= fList.end(); iter++) {
     if (iter->second->PosInList(link).GetNLinks() > 0) {
       result.AddLinks(iter->second->PosInList(link), true);
     }
   }
   return result;
 }
void FairMCMatch::FindStagesPointingToLinks (FairMultiLinkedData links, Int_t stop) private
Definition at line 205 of file FairMCMatch.cxx.
References FairMultiLinkedData::AddLink(), fFinalStageML, FindStagesPointingToLink(), FairMultiLinkedData::GetLink(), FairMultiLinkedData::GetNLinks(), FairLink::GetType(), and FairMultiLinkedData::SetPersistanceCheck().
Referenced by GetMCInfoForwardSingle().
 {
   FairMultiLinkedData tempLinks;
   tempLinks.SetPersistanceCheck(kFALSE);
   for (int i = 0; i < links.GetNLinks(); i++) {
     FairLink myLink = links.GetLink(i);
     FairMultiLinkedData myNewLinks = FindStagesPointingToLink(myLink);
     myNewLinks.SetPersistanceCheck(kFALSE);
     if (myNewLinks.GetNLinks() == 0) {
       fFinalStageML.AddLink(myLink, true);
     } else {
       for (int j = 0; j < myNewLinks.GetNLinks(); j++) {
         if (myNewLinks.GetLink(j).GetType() == (Int_t)stop) {
           fFinalStageML.AddLink(myNewLinks.GetLink(j), true);
         } else if (myNewLinks.GetLink(j).GetType() > (Int_t)stop) {
           fFinalStageML.AddLink(myLink, true);
         } else {
           tempLinks.AddLink(myNewLinks.GetLink(j), true);
         }
       }
     }
   }
   if (tempLinks.GetNLinks() != 0) {
     FindStagesPointingToLinks(tempLinks, stop);
   }
 }
FairMCEntry FairMCMatch::GetEntry (Int_t type, int index)
Definition at line 347 of file FairMCMatch.cxx.
References fList.
Referenced by GetEntry(), and GetNextStage().
 {
   FairMCEntry empty;
   if (index < 0) { return empty; }
   if (fList[type] == 0) {
     return empty;
   }
   if (fList[type]->GetNEntries() > index) {
     return fList[type]->GetEntry(index);
   }
   return empty;
 }
FairMCEntry FairMCMatch::GetEntry (FairLink link)
Definition at line 361 of file FairMCMatch.cxx.
References GetEntry(), FairLink::GetIndex(), and FairLink::GetType().
 {
   return GetEntry(static_cast<Int_t>(link.GetType()), link.GetIndex());
 }
FairMCResult FairMCMatch::GetMCInfo (Int_t start, Int_t stop)
Definition at line 111 of file FairMCMatch.cxx.
References GetMCInfoBackward(), GetMCInfoForward(), and IsTypeInList().
Referenced by FairMCMatchSelectorTask::Exec(), and GetMCInfo().
 {
   FairMCResult result(start, stop);
   if(!IsTypeInList(start)) {
     return result;
   }
   if (start < stop) {
     return GetMCInfoForward(start, stop);
   } else {
     return GetMCInfoBackward(start, stop);
   }
 }
FairMCResult FairMCMatch::GetMCInfo (TString start, TString stop)
Definition at line 105 of file FairMCMatch.cxx.
References FairRootManager::GetBranchId(), GetMCInfo(), and FairRootManager::Instance().
 {
   FairRootManager* ioman = FairRootManager::Instance();
   return GetMCInfo(ioman->GetBranchId(start), ioman->GetBranchId(stop));
 }
FairMCResult FairMCMatch::GetMCInfoBackward (Int_t start, Int_t stop) private
Definition at line 179 of file FairMCMatch.cxx.
References fFinalStageML, fList, GetMCInfoBackwardSingle(), FairMCObject::GetNEntries(), FairMCStage::GetWeight(), and FairMCObject::SetEntry().
Referenced by GetMCInfo().
 {
   FairMCResult result(start, stop);
   FairMCStage startVec = *(fList[start]);
   for (int i = 0; i < startVec.GetNEntries(); i++) {
     FairLink tempLink(start, i);
     GetMCInfoBackwardSingle(tempLink, stop, startVec.GetWeight());
     result.SetEntry(&fFinalStageML, result.GetNEntries());
   }
   return result;
 }
FairMCEntry FairMCMatch::GetMCInfoBackwardSingle (FairLink link, Int_t stop, Double_t weight = 1.) private
Definition at line 191 of file FairMCMatch.cxx.
References ClearFinalStage(), fFinalStageML, fList, FairLink::GetIndex(), GetNextStage(), FairLink::GetType(), FairMultiLinkedData::MultiplyAllWeights(), and FairMultiLinkedData::SetLinks().
Referenced by GetMCInfoBackward(), and GetMCInfoSingle().
 {
   FairMCEntry result;
   FairMultiLinkedData multiLink = fList[(Int_t)aLink.GetType()]->GetEntry(aLink.GetIndex());
   ClearFinalStage();
   multiLink.MultiplyAllWeights(weight);
   GetNextStage(multiLink, stop);
   result.SetLinks(fFinalStageML);
   return result;
 }
FairMCResult FairMCMatch::GetMCInfoForward (Int_t start, Int_t stop) private
Definition at line 147 of file FairMCMatch.cxx.
References fList, GetMCInfoForwardSingle(), FairMCObject::GetNEntries(), FairMCObject::GetStageId(), and FairMCObject::SetEntry().
Referenced by GetMCInfo().
 {
   FairMCResult result(start, stop);
   FairMCStage startVec = *(fList[start]);
   for (int i = 0; i < startVec.GetNEntries(); i++) {
     FairLink tempLink(startVec.GetStageId(), i);
     FairMCEntry tempEntry(GetMCInfoForwardSingle(tempLink, stop));
     if (tempEntry.GetNLinks() > 0)
       if (tempEntry.GetLink(0).GetType() == start) {
         tempEntry.DeleteLink(tempEntry.GetLink(0));
       }
     tempEntry.SetSource(start);
     tempEntry.SetPos(i);
     result.SetEntry(tempEntry);
   }
   return result;
 }
FairMCEntry FairMCMatch::GetMCInfoForwardSingle (FairLink link, Int_t stop) private
Definition at line 166 of file FairMCMatch.cxx.
References FairMultiLinkedData::AddLink(), ClearFinalStage(), fFinalStageML, FindStagesPointingToLinks(), FairMultiLinkedData::SetLinks(), and FairMultiLinkedData::SetPersistanceCheck().
Referenced by GetMCInfoForward(), and GetMCInfoSingle().
 {
   FairMCEntry result;
   ClearFinalStage();
   FairMultiLinkedData tempStage;
   tempStage.SetPersistanceCheck(kFALSE);
   tempStage.AddLink(link, true);
   FindStagesPointingToLinks(tempStage, stop);
   result.SetLinks(fFinalStageML);
   return result;
 }
FairMCEntry FairMCMatch::GetMCInfoSingle (FairLink aLink, Int_t stop)
Definition at line 130 of file FairMCMatch.cxx.
References fList, FairLink::GetIndex(), GetMCInfoBackwardSingle(), GetMCInfoForwardSingle(), FairLink::GetType(), and IsTypeInList().
Referenced by GetMCInfoSingle().
 {
   FairMCEntry result;
   if(!IsTypeInList((Int_t)aLink.GetType())) {
     return result;
   }
   if(!(fList[(Int_t)aLink.GetType()]->GetNEntries() > aLink.GetIndex())) {
     return result;
   }
   if (aLink.GetType() < stop) {
     return GetMCInfoForwardSingle(aLink, stop);
   } else {
     return GetMCInfoBackwardSingle(aLink, stop);
   }
 }
FairMCEntry FairMCMatch::GetMCInfoSingle (FairLink aLink, TString stop)
Definition at line 124 of file FairMCMatch.cxx.
References FairRootManager::GetBranchId(), GetMCInfoSingle(), and FairRootManager::Instance().
 {
   FairRootManager* ioman = FairRootManager::Instance();
   return GetMCInfoSingle(aLink, ioman->GetBranchId(stop));
 }
FairMCStage* FairMCMatch::GetMCStage (int index) const inline
Definition at line 77 of file FairMCMatch.h.
References fList.
Referenced by FairMCMatchCreatorTask::Exec(), FindLinksToStage(), FairMCMatchCreatorTask::InitBranches(), and SetCommonWeightStages().
{
       TListIteratorConst iter = fList.begin();
       for (int i = 0; i < index; i++) {
         iter++;
       }
       return (iter->second);
     }
FairMCStage* FairMCMatch::GetMCStageType (TString branch) inline
Definition at line 85 of file FairMCMatch.h.
References fList, FairRootManager::GetBranchId(), and FairRootManager::Instance().
Referenced by GetNextStage(), and FairMCMatchSelectorTask::SetWeights().
{
       FairRootManager* ioman = FairRootManager::Instance();
       if (ioman->GetBranchId(branch) > 0) {
         return fList[ioman->GetBranchId(branch)];
       } else {
         return 0;
       }
     }
FairMCStage* FairMCMatch::GetMCStageType (Int_t type) inline
Definition at line 94 of file FairMCMatch.h.
References fList.
{
       return fList[type];
     }
void FairMCMatch::GetNextStage (FairMultiLinkedData & startEntry, Int_t stopStage) private
Definition at line 287 of file FairMCMatch.cxx.
References FairMultiLinkedData::AddAllWeights(), AddToFinalStage(), fFinalStageML, fUltimateStage, fVerbose, GetEntry(), FairMultiLinkedData::GetLink(), GetMCStageType(), FairMultiLinkedData::GetNLinks(), FairMCEntry::GetSource(), FairLink::GetType(), FairLink::GetWeight(), FairMCStage::GetWeight(), FairMultiLinkedData::MultiplyAllWeights(), and FairLink::Print().
Referenced by GetMCInfoBackwardSingle().
 {
   FairMCEntry tempStage;
   for (int i = 0; i < startStage.GetNLinks(); i++) {
     if (startStage.GetLink(i).GetType() == stopStage) {
       AddToFinalStage(startStage.GetLink(i),1);
       if (fVerbose > 0) {
         std::cout << "FinalStage: " << fFinalStageML << std::endl;
         std::cout << "---------------------" << std::endl;
       }
     } else if (startStage.GetLink(i).GetType() == fUltimateStage) {
     } else {
       tempStage = GetEntry(startStage.GetLink(i));
       if (fVerbose > 0) {
         std::cout << "TempStage Start";
         startStage.GetLink(i).Print();
         std::cout << " --> " << tempStage << std::endl;
       }
       if (tempStage.GetNLinks() == 0) {
         AddToFinalStage(startStage.GetLink(i),1);
         if (fVerbose > 0) {
           std::cout << "FinalStage: " << fFinalStageML << std::endl;
           std::cout << "---------------------" << std::endl;
         }
       } else {
         double tempStageWeight = GetMCStageType(static_cast<Int_t>(tempStage.GetSource()))->GetWeight();
         double startLinkWeight = startStage.GetLink(i).GetWeight();
         if (fVerbose > 0) {
           std::cout << "Tempstage " << tempStage.GetSource() << ": weight " << tempStageWeight << std::endl;
           std::cout << "StartLinkWeight " << startLinkWeight << std::endl;
         }
         tempStage.MultiplyAllWeights(tempStageWeight);
         if ((tempStageWeight * startLinkWeight) == 0) {
           tempStage.MultiplyAllWeights(tempStageWeight);
           tempStage.AddAllWeights(startLinkWeight/startStage.GetNLinks());
           if (fVerbose > 0) {
             std::cout << " NLinks: " << tempStage.GetNLinks() << " ";
             std::cout << "AddAllWeights: " << startLinkWeight/startStage.GetNLinks() << std::endl;
           }
         } else {
           tempStage.MultiplyAllWeights(startLinkWeight);
           if (fVerbose > 0) {
             std::cout << "MultiplyAllWeights: " << startLinkWeight << std::endl;
           }
         }
       }
       if (fVerbose > 0) {
         std::cout<< "TempStage Stop: " << tempStage << std::endl;
       }
       GetNextStage(tempStage, stopStage);
     }
   }
 }
int FairMCMatch::GetNMCStages () const inline
Definition at line 75 of file FairMCMatch.h.
References fList.
Referenced by FairMCMatchCreatorTask::Exec(), FindLinksToStage(), FairMCMatchCreatorTask::InitBranches(), and SetCommonWeightStages().
 {return fList.size();}
void FairMCMatch::InitStage (Int_t type, std::string fileName, std::string branchName)
Definition at line 62 of file FairMCMatch.cxx.
References fList, and fVerbose.
Referenced by CreateArtificialStage(), and InitStage().
 {
   if (fList[type] == 0) {
     FairMCStage* newStage = new FairMCStage(type, fileName, branchName);
     fList[type] = newStage;
     if (fVerbose > 1) {
       std::cout << "InitStages: " << *newStage;
     }
   } else {
     std::cout << "-W- FairMCMatch::InitStage: Stage " << type << " exists already!" << std::endl;
   }
 }
void FairMCMatch::InitStage (std::string fileName, std::string branchName = "")
Definition at line 75 of file FairMCMatch.cxx.
References FairRootManager::CheckBranch(), FairRootManager::GetBranchId(), InitStage(), and FairRootManager::Instance().
 {
   FairRootManager* ioman = FairRootManager::Instance();
   if (ioman->CheckBranch(branchName.c_str()) == 1) {
     Int_t type = ioman->GetBranchId(branchName.c_str());
     if (type > -1) {
       InitStage(type, fileName, branchName);
     } else {
       std::cout << "-W- FairMCMatch::InitStage: Branch name " << branchName << " not registered!" << std::endl;
     }
   } else {
     std::cout << "-W- FairMCMatch::InitStage: Branch name " << branchName << " not persistant!" << std::endl;
   }
 }
bool FairMCMatch::IsTypeInList (Int_t type)
Definition at line 386 of file FairMCMatch.cxx.
References fList.
Referenced by GetMCInfo(), GetMCInfoSingle(), and LoadInMCLists().
 {
   for(TListIterator iter = fList.begin(); iter != fList.end(); iter++) {
     if (iter->first == type) {
       return true;
     }
   }
   return false;
 }
void FairMCMatch::LoadInMCLists (TClonesArray * myLinkArray)
Definition at line 396 of file FairMCMatch.cxx.
References fList, FairMCEntry::GetSource(), and IsTypeInList().
Referenced by FairMCMatchLoaderTask::Exec(), and FairMCMatchCreatorTask::Exec().
 {
   for (int i = 0; i < myLinkArray->GetEntriesFast(); i++) {
     FairMCEntry* myLink = (FairMCEntry*)myLinkArray->At(i);
     if (IsTypeInList((Int_t)myLink->GetSource())) {
       fList[(Int_t)myLink->GetSource()]->SetEntry(*myLink);
       fList[(Int_t)myLink->GetSource()]->SetLoaded(kTRUE);
     }
   }
 }
void FairMCMatch::Print (std::ostream & out = std::cout) inline
Definition at line 105 of file FairMCMatch.h.
Referenced by FairMCMatchLoaderTask::Exec(), and FairMCMatchCreatorTask::Exec().
 {out << *this;}
void FairMCMatch::RemoveStage (Int_t type)
Definition at line 90 of file FairMCMatch.cxx.
References fList.
 {
   fList.erase(type);
 }
void FairMCMatch::SetCommonWeightStages (Float_t weight)
Definition at line 96 of file FairMCMatch.cxx.
References GetMCStage(), GetNMCStages(), and FairMCStage::SetWeight().
Referenced by FairMCMatchSelectorTask::SetWeights().
 {
   for (int i = 0; i < GetNMCStages(); i++) {
     if (GetMCStage(i)) {
       GetMCStage(i)->SetWeight(weight);
     }
   }
 }
void FairMCMatch::SetElements (Int_t sourceType, int index, FairMultiLinkedData * links)
Definition at line 57 of file FairMCMatch.cxx.
References fList.
Referenced by FairMCMatchCreatorTask::Exec().
 {
   fList[sourceType]->SetEntry(links, index);
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const FairMCMatch & match) friend
Definition at line 107 of file FairMCMatch.h.
{
       for (int i = 0; i < match.GetNMCStages(); i++) {
         if (match.GetMCStage(i)->GetLoaded() == kTRUE) {
           match.GetMCStage(i)->Print(out);
           out << std::endl;
         }
       }
       return out;
     }
Member Data Documentation
FairMultiLinkedData FairMCMatch::fFinalStageML private
Definition at line 121 of file FairMCMatch.h.
Referenced by AddToFinalStage(), ClearFinalStage(), FairMCMatch(), FindStagesPointingToLinks(), GetMCInfoBackward(), GetMCInfoBackwardSingle(), GetMCInfoForwardSingle(), and GetNextStage().
std::map<Int_t, FairMCStage*> FairMCMatch::fList private
Definition at line 120 of file FairMCMatch.h.
Referenced by AddElement(), ClearMCList(), CreateArtificialStage(), FindStagesPointingToLink(), GetEntry(), GetMCInfoBackward(), GetMCInfoBackwardSingle(), GetMCInfoForward(), GetMCInfoSingle(), GetMCStage(), GetMCStageType(), GetNMCStages(), InitStage(), IsTypeInList(), LoadInMCLists(), RemoveStage(), SetElements(), and ~FairMCMatch().
Int_t FairMCMatch::fUltimateStage private
last stage in link chain. Here all recursive operations must stop.
Definition at line 119 of file FairMCMatch.h.
Referenced by GetNextStage().
Int_t FairMCMatch::fVerbose private
Definition at line 122 of file FairMCMatch.h.
Referenced by GetNextStage(), and InitStage().
The documentation for this class was generated from the following files:
FairMCMatch.h
FairMCMatch.cxx