FairRoot: tuto7BinarySerializer< PodData > Class Template Reference
tuto7BinarySerializer< PodData > Class Template Reference abstract
#include <tuto7BinarySerializer.h>
Public Member Functions
tuto7BinarySerializer ()
~tuto7BinarySerializer ()
void Init ()
void InitContainer (const std::string &ClassName)
void InitContainer (TClonesArray *array)
virtual FairMQMessage * message (TClonesArray *array)
virtual void DoSerialization (TClonesArray *array)=0
virtual TClonesArray * message (FairMQMessage *msg)
virtual void DoDeSerialization (FairMQMessage *msg)=0
void GetPayload (FairMQMessage *msg)
void SetMessage (FairMQMessage *msg)
FairMQMessage * GetMessage ()
Protected Attributes
TClonesArray * fContainer
PodData * fPayload
FairMQMessage * fMessage
int fNumInput
Detailed Description
template<typename PodData>
class tuto7BinarySerializer< PodData >
Definition at line 28 of file tuto7BinarySerializer.h.
Constructor & Destructor Documentation
template<typename PodData > tuto7BinarySerializer< PodData >::tuto7BinarySerializer () inline
Definition at line 32 of file tuto7BinarySerializer.h.
 : BinaryBaseClassSerializer<PodData>(), fContainer(nullptr) {;}
template<typename PodData > tuto7BinarySerializer< PodData >::~tuto7BinarySerializer () inline
Definition at line 33 of file tuto7BinarySerializer.h.
 {;}
Member Function Documentation
template<typename PodData > virtual void tuto7BinarySerializer< PodData >::DoDeSerialization (FairMQMessage * msg) pure virtual
Referenced by tuto7BinarySerializer< PodData >::message().
template<typename PodData > virtual void tuto7BinarySerializer< PodData >::DoSerialization (TClonesArray * array) pure virtual
Referenced by tuto7BinarySerializer< PodData >::message().
FairMQMessage* BinaryBaseClassSerializer< PodData >::GetMessage () inline inherited
Definition at line 37 of file BinaryBaseClassSerializer.h.
     {
         return fMessage;
     }
void BinaryBaseClassSerializer< PodData >::GetPayload (FairMQMessage * msg) inline inherited
Definition at line 24 of file BinaryBaseClassSerializer.h.
     {
         int inputSize = msg->GetSize();
         if(inputSize>0)
             fNumInput = inputSize / sizeof(TPayload);
         fPayload = static_cast<TPayload*>(msg->GetData());
     }
template<typename PodData > void tuto7BinarySerializer< PodData >::Init () inline
Definition at line 35 of file tuto7BinarySerializer.h.
     {
         //InitContainer();
     }
template<typename PodData > void tuto7BinarySerializer< PodData >::InitContainer (const std::string & ClassName) inline
Definition at line 40 of file tuto7BinarySerializer.h.
References tuto7BinarySerializer< PodData >::fContainer.
     {
         fContainer = new TClonesArray(ClassName.c_str());
     }
template<typename PodData > void tuto7BinarySerializer< PodData >::InitContainer (TClonesArray * array) inline
Definition at line 45 of file tuto7BinarySerializer.h.
References tuto7BinarySerializer< PodData >::fContainer.
     {
         fContainer = array;
     }
template<typename PodData > virtual FairMQMessage* tuto7BinarySerializer< PodData >::message (TClonesArray * array) inline virtual
Definition at line 54 of file tuto7BinarySerializer.h.
References tuto7BinarySerializer< PodData >::DoSerialization(), and BinaryBaseClassSerializer< PodData >::fMessage.
     {
         DoSerialization(array);
         return fMessage;
     }
template<typename PodData > virtual TClonesArray* tuto7BinarySerializer< PodData >::message (FairMQMessage * msg) inline virtual
Definition at line 65 of file tuto7BinarySerializer.h.
References tuto7BinarySerializer< PodData >::DoDeSerialization(), and tuto7BinarySerializer< PodData >::fContainer.
     {
         DoDeSerialization(msg);
         return fContainer;
     }
void BinaryBaseClassSerializer< PodData >::SetMessage (FairMQMessage * msg) inline inherited
Definition at line 32 of file BinaryBaseClassSerializer.h.
     {
         fMessage=msg;
     }
Member Data Documentation
template<typename PodData > TClonesArray* tuto7BinarySerializer< PodData >::fContainer protected
Definition at line 75 of file tuto7BinarySerializer.h.
Referenced by tuto7BinarySerializer< PodData >::InitContainer(), and tuto7BinarySerializer< PodData >::message().
FairMQMessage* BinaryBaseClassSerializer< PodData >::fMessage protected inherited
Definition at line 46 of file BinaryBaseClassSerializer.h.
Referenced by tuto7BinarySerializer< PodData >::message().
int BinaryBaseClassSerializer< PodData >::fNumInput protected inherited
Definition at line 47 of file BinaryBaseClassSerializer.h.
PodData * BinaryBaseClassSerializer< PodData >::fPayload protected inherited
Definition at line 45 of file BinaryBaseClassSerializer.h.
The documentation for this class was generated from the following file:
tuto7BinarySerializer.h