FairRroot: FairMQSamplerTask Class Reference
FairMQSamplerTask Class Reference
#include <FairMQSamplerTask.h>
Public Member Functions
FairMQSamplerTask ()
FairMQSamplerTask (const Text_t *name, int iVerbose=1)
virtual ~FairMQSamplerTask ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
void SetSendPart (boost::function< void()>)
void SetEventIndex (Long64_t EventIndex)
void SetBranch (std::string branch)
FairMQMessage * GetOutput ()
void SetTransport (FairMQTransportFactory *factory)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
TClonesArray * fInput
std::string fBranch
FairMQMessage * fOutput
FairMQTransportFactory * fTransportFactory
Long64_t fEventIndex
boost::function< void()> SendPart
FairEventHeader * fEvtHeader
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairMQSamplerTask (const FairMQSamplerTask &)
Copy Constructor.
FairMQSamplerTask operator= (const FairMQSamplerTask &)
Detailed Description
FairMQSamplerTask.h
Since
2012-11-22
Author
D. Klein, A. Rybalchenko
Definition at line 30 of file FairMQSamplerTask.h.
Constructor & Destructor Documentation
FairMQSamplerTask::FairMQSamplerTask ()
Definition at line 19 of file FairMQSamplerTask.cxx.
                                      :
   FairTask("Abstract base task used for loading a branch from a root file into memory"),
   fInput(NULL),
   fBranch(),
   fOutput(NULL),
   fTransportFactory(NULL),
   fEventIndex(0),
   SendPart(),
   fEvtHeader(NULL)
 {
 }
FairMQSamplerTask::FairMQSamplerTask (const Text_t * name, int iVerbose = 1)
Definition at line 31 of file FairMQSamplerTask.cxx.
                                                                      :
   FairTask(name, iVerbose),
   fInput(NULL),
   fBranch(),
   fOutput(NULL),
   fTransportFactory(NULL),
   fEventIndex(0),
   SendPart(),
   fEvtHeader(NULL)
 {
 }
FairMQSamplerTask::~FairMQSamplerTask () virtual
Definition at line 43 of file FairMQSamplerTask.cxx.
References fInput.
 {
   delete fInput;
   // fOutput->CloseMessage();
 }
FairMQSamplerTask::FairMQSamplerTask (const FairMQSamplerTask &) private
Copy Constructor.
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
void FairMQSamplerTask::Exec (Option_t * opt) virtual
Reimplemented in TestDetectorDigiLoader< T1, T2 >, and TestDetectorDigiLoader< T1, T2 >.
Definition at line 58 of file FairMQSamplerTask.cxx.
 {
 }
virtual void FairTask::Finish () inline protected virtual inherited
Action after each event. To be implemented in the derived class
Reimplemented in FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, FairDbTutAccessRtdbTask, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 111 of file FairTask.h.
Referenced by FairTask::FinishTask(), and FairTask::FinishTasks().
 { };
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
FairMQMessage * FairMQSamplerTask::GetOutput ()
Definition at line 78 of file FairMQSamplerTask.cxx.
References fOutput.
 {
   return fOutput;
 }
InitStatus FairMQSamplerTask::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 49 of file FairMQSamplerTask.cxx.
References fBranch, fEvtHeader, fInput, FairRootManager::GetObject(), FairRootManager::Instance(), and kSUCCESS.
 {
   FairRootManager* ioman = FairRootManager::Instance();
   fEvtHeader = (FairEventHeader *)ioman->GetObject("EventHeader.");
   fInput = (TClonesArray*) ioman->GetObject(fBranch.c_str());
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairMQSamplerTask FairMQSamplerTask::operator= (const FairMQSamplerTask &) private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairMQSamplerTask::SetBranch (std::string branch)
Definition at line 68 of file FairMQSamplerTask.cxx.
References fBranch.
 {
   fBranch = branch;
 }
void FairMQSamplerTask::SetEventIndex (Long64_t EventIndex)
Definition at line 73 of file FairMQSamplerTask.cxx.
References fEventIndex.
 {
   fEventIndex = EventIndex;
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
virtual void FairTask::SetParContainers () inline protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented in FairRingSorterTask, FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairTutorialDet4HitProducerIdealMisalign, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairMCMatchLoaderTask, FairTutorialDet4StraightLineFitter, NewTask, FairDbTutAccessRtdbTask, and FairTestDetectorHitProducerSmearing.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::SetParTask().
 { };
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairMQSamplerTask::SetSendPart (boost::function< void()> callback)
Definition at line 63 of file FairMQSamplerTask.cxx.
References SendPart.
 {
   SendPart = callback;
 }
void FairMQSamplerTask::SetTransport (FairMQTransportFactory * factory)
Definition at line 83 of file FairMQSamplerTask.cxx.
References fTransportFactory.
 {
   fTransportFactory = factory;
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
std::string FairMQSamplerTask::fBranch protected
Definition at line 48 of file FairMQSamplerTask.h.
Referenced by Init(), and SetBranch().
Long64_t FairMQSamplerTask::fEventIndex protected
Definition at line 51 of file FairMQSamplerTask.h.
Referenced by SetEventIndex().
FairEventHeader* FairMQSamplerTask::fEvtHeader protected
Definition at line 53 of file FairMQSamplerTask.h.
Referenced by Init().
TClonesArray* FairMQSamplerTask::fInput protected
Definition at line 47 of file FairMQSamplerTask.h.
Referenced by Init(), and ~FairMQSamplerTask().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
FairMQMessage* FairMQSamplerTask::fOutput protected
Definition at line 49 of file FairMQSamplerTask.h.
Referenced by GetOutput().
FairMQTransportFactory* FairMQSamplerTask::fTransportFactory protected
Definition at line 50 of file FairMQSamplerTask.h.
Referenced by SetTransport().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
boost::function<void()> FairMQSamplerTask::SendPart protected
Definition at line 52 of file FairMQSamplerTask.h.
Referenced by SetSendPart().
The documentation for this class was generated from the following files:
FairMQSamplerTask.h
FairMQSamplerTask.cxx