FairRoot: FairPointSetDraw Class Reference
FairPointSetDraw Class Reference abstract
#include <FairPointSetDraw.h>
Public Member Functions
FairPointSetDraw ()
FairPointSetDraw (const char *name, Color_t color, Style_t mstyle, Int_t iVerbose=1)
virtual ~FairPointSetDraw ()
void SetVerbose (Int_t iVerbose)
virtual void Exec (Option_t *option)
void Reset ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual TVector3 GetVector (TObject *obj)=0
virtual TObject * GetValue (TObject *obj, Int_t i)
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Finish ()
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
TClonesArray * fPointList
FairEventManager * fEventManager
TEvePointSet * fq
Color_t fColor
Style_t fStyle
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairPointSetDraw (const FairPointSetDraw &)
FairPointSetDraw & operator= (const FairPointSetDraw &)
ClassDef (FairPointSetDraw, 1)
Detailed Description
Definition at line 34 of file FairPointSetDraw.h.
Constructor & Destructor Documentation
FairPointSetDraw::FairPointSetDraw ()
Default constructor
Definition at line 35 of file FairPointSetDraw.cxx.
   : FairTask("FairPointSetDraw", 0),
     fVerbose(0),
     fPointList(NULL),
     fEventManager(NULL),
     fq(NULL),
     fColor(0),
     fStyle(0)
 {
 }
FairPointSetDraw::FairPointSetDraw (const char * name, Color_t color, Style_t mstyle, Int_t iVerbose = 1)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 50 of file FairPointSetDraw.cxx.
   : FairTask(name, iVerbose),
     fVerbose(iVerbose),
     fPointList(NULL),
     fEventManager(NULL),
     fq(NULL),
     fColor(color),
     fStyle(mstyle)
 {
 }
FairPointSetDraw::~FairPointSetDraw () virtual
Destructor
Definition at line 112 of file FairPointSetDraw.cxx.
 {
 }
FairPointSetDraw::FairPointSetDraw (const FairPointSetDraw &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairPointSetDraw::ClassDef (FairPointSetDraw , 1) private
void FairPointSetDraw::Exec (Option_t * option) virtual
Executed task
Definition at line 80 of file FairPointSetDraw.cxx.
References fColor, fPointList, fq, fStyle, GetValue(), GetVector(), and Reset().
 {
   if (IsActive()) {
     Int_t npoints=fPointList->GetEntriesFast();
     Reset();
     TEvePointSet* q = new TEvePointSet(GetName(),npoints,  TEvePointSelectorConsumer::kTVT_XYZ);
     q->SetOwnIds(kTRUE);
     q->SetMarkerColor(fColor);
     q->SetMarkerSize(1.5);
     q->SetMarkerStyle(fStyle);
     //std::cout << "fPointList: " << fPointList << " " << fPointList->GetEntries() << std::endl;
     for (Int_t i=0; i<npoints; ++i) {
       TObject*  p=(TObject*)fPointList->At(i);
       if(p!=0) {
         TVector3 vec(GetVector(p));
         q->SetNextPoint(vec.X(),vec.Y(), vec.Z());
         q->SetPointId(GetValue(p, i));
       }
     }
     gEve->AddElement(q);
     gEve->Redraw3D(kFALSE);
     fq=q;
   }
 }
void FairPointSetDraw::Finish () protected virtual
Action after each event
Reimplemented from FairTask.
Definition at line 122 of file FairPointSetDraw.cxx.
 {
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
TObject * FairPointSetDraw::GetValue (TObject * obj, Int_t i) protected virtual
Definition at line 106 of file FairPointSetDraw.cxx.
Referenced by Exec().
 {
   return new TNamed(Form("Point %d", i),"");
 }
virtual TVector3 FairPointSetDraw::GetVector (TObject * obj) protected pure virtual
Implemented in FairHitPointSetDraw, and FairMCPointDraw.
Referenced by Exec().
InitStatus FairPointSetDraw::Init () protected virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 62 of file FairPointSetDraw.cxx.
References fEventManager, fPointList, fq, fVerbose, FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), and kSUCCESS.
 {
   if(fVerbose>1) { cout<<  "FairPointSetDraw::Init()" << endl; }
   FairRootManager* fManager = FairRootManager::Instance();
   fPointList = (TClonesArray*)fManager->GetObject(GetName());
   if(fPointList==0) {
     cout << "FairPointSetDraw::Init()  branch " << GetName() << " Not found! Task will be deactivated "<< endl;
     SetActive(kFALSE);
   }
   if(fVerbose>2) { cout<<  "FairPointSetDraw::Init() get track list" <<  fPointList<< endl; }
   fEventManager =FairEventManager::Instance();
   if(fVerbose>2) { cout<<  "FairPointSetDraw::Init() get instance of FairEventManager " << endl; }
   fq =0;
   // gEve->AddElement(fq, fEventManager );
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairPointSetDraw& FairPointSetDraw::operator= (const FairPointSetDraw &) private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairPointSetDraw::Reset ()
Definition at line 126 of file FairPointSetDraw.cxx.
References fEventManager, and fq.
Referenced by Exec().
 {
   if(fq!=0) {
     fq->Reset();
     gEve->RemoveElement(fq, fEventManager );
   }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairPointSetDraw::SetParContainers () protected virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 116 of file FairPointSetDraw.cxx.
 {
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairPointSetDraw::SetVerbose (Int_t iVerbose) inline
Set verbosity level. For this task and all of the subtasks.
Definition at line 53 of file FairPointSetDraw.h.
References fVerbose.
 {fVerbose = iVerbose;};
Member Data Documentation
Color_t FairPointSetDraw::fColor protected
Definition at line 70 of file FairPointSetDraw.h.
Referenced by Exec().
FairEventManager* FairPointSetDraw::fEventManager protected
Definition at line 68 of file FairPointSetDraw.h.
Referenced by Init(), and Reset().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
TClonesArray* FairPointSetDraw::fPointList protected
Definition at line 67 of file FairPointSetDraw.h.
Referenced by Exec(), and Init().
TEvePointSet* FairPointSetDraw::fq protected
Definition at line 69 of file FairPointSetDraw.h.
Referenced by Exec(), Init(), and Reset().
Style_t FairPointSetDraw::fStyle protected
Definition at line 71 of file FairPointSetDraw.h.
Referenced by Exec().
Int_t FairPointSetDraw::fVerbose protected
Definition at line 62 of file FairPointSetDraw.h.
Referenced by FairHitPointSetDraw::GetVector(), Init(), and SetVerbose().
The documentation for this class was generated from the following files:
FairPointSetDraw.h
FairPointSetDraw.cxx