FairRoot: FairMapPar Class Reference
FairMapPar Class Reference abstract
#include <FairMapPar.h>
Public Member Functions
FairMapPar (const char *name, const char *title, const char *context)
FairMapPar ()
~FairMapPar ()
Int_t GetType () const
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
void MapName (TString &name)
Double_t GetPositionX () const
Double_t GetPositionY () const
Double_t GetPositionZ () const
Double_t GetScale () const
FairMapPar (const char *name, const char *title, const char *context)
FairMapPar ()
~FairMapPar ()
Int_t GetType () const
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
void MapName (TString &name)
Double_t GetPositionX () const
Double_t GetPositionY () const
Double_t GetPositionZ () const
Double_t GetScale () const
virtual void putParams (FairParamList *)=0
virtual Bool_t getParams (FairParamList *)=0
virtual void printParams ()
Bool_t init (FairParIo *inp)
virtual Bool_t init ()
Int_t write (FairParIo *output)
virtual Int_t write ()
void fill (UInt_t rid=0)
void store (UInt_t rid=0)
virtual const char * GetName () const
virtual const char * GetTitle () const
virtual void clear ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setOwnership (Bool_t flag=kTRUE)
Bool_t isOwned ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Member Functions
ClassDef (FairMapPar, 1)
ClassDef (FairMapPar, 1)
Protected Attributes
Int_t fType
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
TString fMapName
Double_t fPosX
Double_t fPosY
Double_t fPosZ
Double_t fScale
TString fName
TString fTitle
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
Bool_t owned
flag is kTRUE if parameters have changed
TString paramContext
if flag is KTRUE FairDB has the par. class ownership
TString author
TString description
FairLogger * fLogger
Detailed Description
FairMapPar.h
Author
M.Al-Turany
Since
30.01.2007
Version
1.0
Parameter set field maps.
Definition at line 25 of file Tutorial3/simulation/FairMapPar.h.
Constructor & Destructor Documentation
FairMapPar::FairMapPar (const char * name, const char * title, const char * context)
Standard constructor
Definition at line 11 of file Tutorial3/simulation/FairMapPar.cxx.
     : FairParGenericSet(name, title, context)
     , fType(-1)
     , fXmin(0)
     , fXmax(0)
     , fYmin(0)
     , fYmax(0)
     , fZmin(0)
     , fZmax(0)
     , fMapName(TString(""))
     , fPosX(0)
     , fPosY(0)
     , fPosZ(0)
     , fScale(0)
 {
 }
FairMapPar::FairMapPar ()
default constructor
Definition at line 29 of file Tutorial3/simulation/FairMapPar.cxx.
     : fType(-1)
     , fXmin(0)
     , fXmax(0)
     , fYmin(0)
     , fYmax(0)
     , fZmin(0)
     , fZmax(0)
     , fMapName(TString(""))
     , fPosX(0)
     , fPosY(0)
     , fPosZ(0)
     , fScale(0)
 {
 }
FairMapPar::~FairMapPar ()
Destructor
Definition at line 47 of file Tutorial3/simulation/FairMapPar.cxx.
 {
 }
FairMapPar::FairMapPar (const char * name, const char * title, const char * context)
Standard constructor
FairMapPar::FairMapPar ()
default constructor
FairMapPar::~FairMapPar ()
Destructor
Member Function Documentation
FairMapPar::ClassDef (FairMapPar , 1) protected
FairMapPar::ClassDef (FairMapPar , 1) protected
virtual void FairParSet::clear (void) inline virtual inherited
Reimplemented in FairTutorialDet2DigiPar, FairBaseParSet, FairGeoParSet, FairRutherfordGeoPar, FairTutorialDet1GeoPar, FairTutorialDet4GeoPar, FairTestDetectorGeoPar, FairTestDetectorGeoPar, FairTutorialDet2GeoPar, NewDetectorGeoPar, NewDetectorGeoPar, FairGeoPassivePar, FairTutorialDet4MisalignPar, and NewParameterContainer.
Definition at line 45 of file FairParSet.h.
Referenced by FairDetParRootFileIo::read().
 {}
void FairParSet::copyComment (FairParSet & r) inline inherited
Definition at line 76 of file FairParSet.h.
References FairParSet::getAuthor(), and FairParSet::getDescription().
{
       author=r.getAuthor();
       description=r.getDescription();
     }
void FairParGenericSet::fill (UInt_t rid = 0) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 32 of file FairParGenericSet.h.
 {};
const char* FairParSet::getAuthor () const inline inherited
Definition at line 71 of file FairParSet.h.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
 { return author.Data(); }
const char* FairParSet::getDescription () const inline inherited
Definition at line 74 of file FairParSet.h.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
 { return description.Data(); }
const char* FairParSet::getDetectorName () inline inherited
Definition at line 48 of file FairParSet.h.
 {return detName.Data();}
Int_t FairParSet::getInputVersion (Int_t i) inline inherited
Definition at line 54 of file FairParSet.h.
Referenced by FairRuntimeDb::findOutputVersion(), FairDetParRootFileIo::read(), and FairRuntimeDb::writeContainer().
{
       if (i>=0 && i<3) { return versions[i]; }
       else { return 0; }
     }
virtual const char* FairParSet::GetName () const inline virtual inherited
Definition at line 38 of file FairParSet.h.
Referenced by FairRuntimeDb::addContainer(), FairRuntimeDb::addRun(), FairRuntimeDb::findOutputVersion(), FairGenericParAsciiFileIo::init(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), FairRuntimeDb::initContainers(), FairParSet::print(), FairRuntimeDb::print(), FairParGenericSet::printParams(), FairDetParRootFileIo::read(), FairGenericParAsciiFileIo::write(), FairDetParRootFileIo::write(), FairParSet::write(), FairRuntimeDb::writeContainer(), FairGenericParAsciiFileIo::writeGenericSet(), and FairRuntimeDb::~FairRuntimeDb().
 {return (char*)fName.Data();}
const char* FairParSet::getParamContext () const inline inherited
Definition at line 68 of file FairParSet.h.
Referenced by FairGenericParAsciiFileIo::writeGenericSet().
 { return paramContext.Data(); }
virtual Bool_t FairParGenericSet::getParams (FairParamList *) pure virtual inherited
Implemented in FairTutorialDet2DigiPar, FairBaseParSet, FairGeoParSet, MyFieldPar, FairConstPar, FairConstPar, FairRutherfordGeoPar, FairTutorialDet1GeoPar, FairTutorialDet4GeoPar, FairTestDetectorGeoPar, FairTestDetectorGeoPar, FairTutorialDet2GeoPar, NewDetectorGeoPar, NewDetectorGeoPar, FairGeoPassivePar, FairTutorialDet4MisalignPar, and NewParameterContainer.
Double_t FairMapPar::GetPositionX () const inline
Definition at line 71 of file Tutorial6/sim/FairMapPar.h.
References fPosX.
     {
         return fPosX;
     }
Double_t FairMapPar::GetPositionX () const inline
Definition at line 71 of file Tutorial3/simulation/FairMapPar.h.
References fPosX.
     {
         return fPosX;
     }
Double_t FairMapPar::GetPositionY () const inline
Definition at line 75 of file Tutorial3/simulation/FairMapPar.h.
References fPosY.
     {
         return fPosY;
     }
Double_t FairMapPar::GetPositionY () const inline
Definition at line 75 of file Tutorial6/sim/FairMapPar.h.
References fPosY.
     {
         return fPosY;
     }
Double_t FairMapPar::GetPositionZ () const inline
Definition at line 79 of file Tutorial3/simulation/FairMapPar.h.
References fPosZ.
     {
         return fPosZ;
     }
Double_t FairMapPar::GetPositionZ () const inline
Definition at line 79 of file Tutorial6/sim/FairMapPar.h.
References fPosZ.
     {
         return fPosZ;
     }
Double_t FairMapPar::GetScale () const inline
Definition at line 83 of file Tutorial6/sim/FairMapPar.h.
References fScale.
     {
         return fScale;
     }
Double_t FairMapPar::GetScale () const inline
Definition at line 83 of file Tutorial3/simulation/FairMapPar.h.
References fScale.
     {
         return fScale;
     }
virtual const char* FairParSet::GetTitle () const inline virtual inherited
Definition at line 39 of file FairParSet.h.
Referenced by FairRuntimeDb::print().
 {return (char*)fTitle.Data();}
Int_t FairMapPar::GetType () const inline
Accessors
Definition at line 39 of file Tutorial3/simulation/FairMapPar.h.
References fType.
Referenced by FairConstField::FairConstField().
     {
         return fType;
     }
Int_t FairMapPar::GetType () const inline
Accessors
Definition at line 39 of file Tutorial6/sim/FairMapPar.h.
References fType.
     {
         return fType;
     }
Double_t FairMapPar::GetXmax () const inline
Definition at line 47 of file Tutorial6/sim/FairMapPar.h.
References fXmax.
     {
         return fXmax;
     }
Double_t FairMapPar::GetXmax () const inline
Definition at line 47 of file Tutorial3/simulation/FairMapPar.h.
References fXmax.
Referenced by FairConstField::FairConstField().
     {
         return fXmax;
     }
Double_t FairMapPar::GetXmin () const inline
Definition at line 43 of file Tutorial3/simulation/FairMapPar.h.
References fXmin.
Referenced by FairConstField::FairConstField().
     {
         return fXmin;
     }
Double_t FairMapPar::GetXmin () const inline
Definition at line 43 of file Tutorial6/sim/FairMapPar.h.
References fXmin.
     {
         return fXmin;
     }
Double_t FairMapPar::GetYmax () const inline
Definition at line 55 of file Tutorial6/sim/FairMapPar.h.
References fYmax.
     {
         return fYmax;
     }
Double_t FairMapPar::GetYmax () const inline
Definition at line 55 of file Tutorial3/simulation/FairMapPar.h.
References fYmax.
Referenced by FairConstField::FairConstField().
     {
         return fYmax;
     }
Double_t FairMapPar::GetYmin () const inline
Definition at line 51 of file Tutorial6/sim/FairMapPar.h.
References fYmin.
     {
         return fYmin;
     }
Double_t FairMapPar::GetYmin () const inline
Definition at line 51 of file Tutorial3/simulation/FairMapPar.h.
References fYmin.
Referenced by FairConstField::FairConstField().
     {
         return fYmin;
     }
Double_t FairMapPar::GetZmax () const inline
Definition at line 63 of file Tutorial6/sim/FairMapPar.h.
References fZmax.
     {
         return fZmax;
     }
Double_t FairMapPar::GetZmax () const inline
Definition at line 63 of file Tutorial3/simulation/FairMapPar.h.
References fZmax.
Referenced by FairConstField::FairConstField().
     {
         return fZmax;
     }
Double_t FairMapPar::GetZmin () const inline
Definition at line 59 of file Tutorial6/sim/FairMapPar.h.
References fZmin.
     {
         return fZmin;
     }
Double_t FairMapPar::GetZmin () const inline
Definition at line 59 of file Tutorial3/simulation/FairMapPar.h.
References fZmin.
Referenced by FairConstField::FairConstField().
     {
         return fZmin;
     }
Bool_t FairParSet::hasChanged () inline inherited
Definition at line 66 of file FairParSet.h.
References FairParSet::changed.
Referenced by FairRuntimeDb::findOutputVersion(), and FairRuntimeDb::writeContainer().
 {return changed;}
Bool_t FairParGenericSet::init (FairParIo * inp) virtual inherited
Reimplemented from FairParSet.
Bool_t FairParSet::init () virtual inherited
Definition at line 46 of file FairParSet.cxx.
References FairLogger::Error(), FairParSet::fLogger, FairRuntimeDb::getFirstInput(), FairParSet::GetName(), FairRuntimeDb::getSecondInput(), FairRuntimeDb::instance(), MESSAGE_ORIGIN, and FairParSet::setInputVersion().
Referenced by FairRuntimeDb::initContainers().
 {
   // intitializes the container from an input in run time
   // database. If this is not successful it is initialized from
   // the second input. If this failes too, it returns an error.
   // (calls internally the init function in the derived class)
   FairRuntimeDb* rtdb=FairRuntimeDb::instance();
   //FairRunAna* fRun =FairRunAna::Instance();
 // cout << "-I-  FairParSet::init() " << GetName() << endl;
   Bool_t allFound=kFALSE;
   FairParIo* io=0;
   if (rtdb) {
     io=rtdb->getFirstInput();
     if (io) { allFound=init(io); }
     if (!allFound) {
       io=rtdb->getSecondInput();
       //cout << "-I FairParSet::init() 2 " << io <<  std::endl;
       if (io) { allFound=init(io); }
     } else { setInputVersion(-1,2); }
   }
   if (allFound) { return kTRUE; }
   if (fLogger ) { fLogger->Error(MESSAGE_ORIGIN, "init() %s  not initialized",GetName()); }
   return kFALSE;
 }
Bool_t FairParSet::isOwned () inline inherited
Definition at line 63 of file FairParSet.h.
References FairParSet::owned.
Referenced by FairRuntimeDb::~FairRuntimeDb().
 {return owned;}
Bool_t FairParSet::isStatic () inline inherited
Definition at line 60 of file FairParSet.h.
References FairParSet::status.
Referenced by FairRuntimeDb::initContainers(), and FairRuntimeDb::resetInputVersions().
 {return status;}
void FairMapPar::MapName (TString & name) inline
Definition at line 67 of file Tutorial3/simulation/FairMapPar.h.
References fMapName.
     {
         name = fMapName;
     }
void FairMapPar::MapName (TString & name) inline
Definition at line 67 of file Tutorial6/sim/FairMapPar.h.
References fMapName.
     {
         name = fMapName;
     }
void FairParSet::print () virtual inherited
Definition at line 84 of file FairParSet.cxx.
References FairParSet::author, FairParSet::changed, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParSet::status, and FairParSet::versions.
Referenced by FairRuntimeDb::writeContainer().
 {
   // prints information about container (versions,status,hasChanged...)
   cout<<"-----  "<<GetName()<<"  -----"<<'\n';
   if (!paramContext.IsNull()) { cout<<"Context/Purpose:       "<<paramContext<<'\n'; }
   if (!author.IsNull()) { cout<<"Author:                "<<author<<'\n'; }
   if (!description.IsNull()) { cout<<"Description:           "<<description<<'\n'; }
   cout<<"first input version:   "<<versions[1]<<'\n';
   cout<<"second input version:  "<<versions[2]<<'\n';
   if (changed) { cout<<"has changed"<<'\n'; }
   else { cout<<"has not changed"<<'\n'; }
   if (status) { cout<<"is static"<<'\n'; }
   else { cout<<"is not static"<<'\n'; }
 }
void FairParGenericSet::printParams () virtual inherited
Definition at line 59 of file FairParGenericSet.cxx.
References FairParSet::author, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParamList::print(), and FairParGenericSet::putParams().
 {
   // prints information about the container
   std::cout<<"\n---------------------------------------------\n";
   std::cout<<"-----  "<<GetName()<<"  -----\n";
   if (!paramContext.IsNull()) { std::cout<<"--  Context/Purpose:  "<<paramContext<<'\n'; }
   if (!author.IsNull()) { std::cout<<"--  Author:           "<<author<<'\n'; }
   if (!description.IsNull()) { std::cout<<"--  Description:      "<<description<<'\n'; }
   std::cout<<"---------------------------------------------\n";
   FairParamList* condList = new FairParamList;
   putParams(condList);
   condList->print();
   std::cout<<"---------------------------------------------\n\n";
   delete condList;
 }
virtual void FairParGenericSet::putParams (FairParamList *) pure virtual inherited
Implemented in FairTutorialDet2DigiPar, FairBaseParSet, FairGeoParSet, MyFieldPar, FairConstPar, FairConstPar, FairRutherfordGeoPar, FairTutorialDet1GeoPar, FairTutorialDet4GeoPar, FairTestDetectorGeoPar, FairTestDetectorGeoPar, FairTutorialDet2GeoPar, NewDetectorGeoPar, NewDetectorGeoPar, FairGeoPassivePar, FairTutorialDet4MisalignPar, and NewParameterContainer.
Referenced by FairParGenericSet::printParams(), and FairGenericParAsciiFileIo::writeGenericSet().
void FairParSet::resetInputVersions () inherited
Definition at line 99 of file FairParSet.cxx.
References FairParSet::changed, FairParSet::status, and FairParSet::versions.
Referenced by FairTutorialDet2DigiPar::clear(), and FairRuntimeDb::resetInputVersions().
 {
   // resets the input versions if the container is not static
   if (!status) {
     for(Int_t i=0; i<3; i++) {versions[i]=-1;}
     changed=kFALSE;
   }
 }
void FairParSet::setAuthor (const char * s) inline inherited
Definition at line 70 of file FairParSet.h.
Referenced by FairDetParAsciiFileIo::readComment().
 {author=s;}
void FairParSet::setChanged (Bool_t flag = kTRUE) inline inherited
Definition at line 65 of file FairParSet.h.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairConstField::FillParContainer(), FairRunOnline::Init(), FairRunSim::Init(), FairDetParRootFileIo::read(), FairDetParRootFileIo::write(), FairRuntimeDb::writeContainer(), and FairGenericParAsciiFileIo::writeGenericSet().
 {changed=flag;}
void FairParSet::setDescription (const char * s) inline inherited
Definition at line 73 of file FairParSet.h.
Referenced by FairDetParAsciiFileIo::readComment().
 {description=s;}
void FairParSet::setInputVersion (Int_t v = -1, Int_t i = 0) inline inherited
Definition at line 51 of file FairParSet.h.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairConstField::FillParContainer(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), and FairDetParRootFileIo::read().
{
       if (i>=0 && i<3) { versions[i]=v; }
     }
void FairParSet::setOwnership (Bool_t flag = kTRUE) inline inherited
Definition at line 62 of file FairParSet.h.
 {owned=flag;}
void FairParSet::setStatic (Bool_t flag = kTRUE) inline inherited
Definition at line 59 of file FairParSet.h.
Referenced by FairRuntimeDb::setContainersStatic().
 {status=flag;}
void FairParGenericSet::store (UInt_t rid = 0) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 33 of file FairParGenericSet.h.
 {};
Int_t FairParGenericSet::write (FairParIo * output) virtual inherited
Reimplemented from FairParSet.
Definition at line 50 of file FairParGenericSet.cxx.
References FairParIo::getDetParIo(), and FairDetParIo::write().
 {
   // writes the container to an output
   FairDetParIo* out=output->getDetParIo("FairGenericParIo");
   if (out) { return out->write(this); }
   return -1;
 }
Int_t FairParSet::write () virtual inherited
Definition at line 72 of file FairParSet.cxx.
References FairLogger::Error(), FairParSet::fLogger, FairParSet::GetName(), FairRuntimeDb::getOutput(), FairRuntimeDb::instance(), and MESSAGE_ORIGIN.
Referenced by FairRuntimeDb::writeContainer().
 {
   // writes the container to the output defined in the runtime database
   // returns the output version in the ROOT file
   // returns -1 if error occured
   // (calls internally the init function in the derived class)
   FairParIo* output=FairRuntimeDb::instance()->getOutput();
   if (output) { return write(output); }
   if (fLogger) { fLogger->Error(MESSAGE_ORIGIN,"write() %s could not be written to output",GetName()); }
   return -1;
 }
Member Data Documentation
TString FairParSet::author protected inherited
Definition at line 29 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
Bool_t FairParSet::changed protected inherited
static flag
Definition at line 26 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::hasChanged(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
TString FairParSet::description protected inherited
Definition at line 30 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
TString FairParSet::detName protected inherited
Definition at line 23 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairTutorialDet2DigiPar::FairTutorialDet2DigiPar(), and FairParSet::operator=().
FairLogger* FairParSet::fLogger protected inherited
Fair Logger
Definition at line 32 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::init(), FairParSet::operator=(), and FairParSet::write().
TString FairMapPar::fMapName protected
Field map name in case of field map
Definition at line 103 of file Tutorial3/simulation/FairMapPar.h.
Referenced by MapName(), and FairConstPar::SetParameters().
TString FairParSet::fName protected inherited
Definition at line 21 of file FairParSet.h.
Referenced by ClassImp(), FairBaseContFact::FairBaseContFact(), FairParSet::FairParSet(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), MyPassiveContFact::MyPassiveContFact(), and FairParSet::operator=().
Double_t FairMapPar::fPosX protected
Field centre position for field map
Definition at line 106 of file Tutorial3/simulation/FairMapPar.h.
Referenced by GetPositionX(), and FairConstPar::SetParameters().
Double_t FairMapPar::fPosY protected
Definition at line 106 of file Tutorial3/simulation/FairMapPar.h.
Referenced by GetPositionY(), and FairConstPar::SetParameters().
Double_t FairMapPar::fPosZ protected
Definition at line 106 of file Tutorial3/simulation/FairMapPar.h.
Referenced by GetPositionZ(), and FairConstPar::SetParameters().
Double_t FairMapPar::fScale protected
Scaling factor for field map
Definition at line 109 of file Tutorial3/simulation/FairMapPar.h.
Referenced by GetScale(), and FairConstPar::SetParameters().
TString FairParSet::fTitle protected inherited
Definition at line 22 of file FairParSet.h.
Referenced by FairBaseContFact::FairBaseContFact(), FairParSet::FairParSet(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), MyPassiveContFact::MyPassiveContFact(), and FairParSet::operator=().
Int_t FairMapPar::fType protected
Field type 0 = constant field 1 = field map 2 = field map sym2 (symmetries in x and y) 3 = field map sym3 (symmetries in x, y and z)
Definition at line 95 of file Tutorial3/simulation/FairMapPar.h.
Referenced by FairConstPar::FairConstPar(), FairConstPar::getParams(), GetType(), FairConstPar::putParams(), and FairConstPar::SetParameters().
Double_t FairMapPar::fXmax protected
Definition at line 98 of file Tutorial3/simulation/FairMapPar.h.
Referenced by FairConstPar::getParams(), GetXmax(), FairConstPar::putParams(), and FairConstPar::SetParameters().
Double_t FairMapPar::fXmin protected
Field limits in case of constant field
Definition at line 98 of file Tutorial3/simulation/FairMapPar.h.
Referenced by FairConstPar::getParams(), GetXmin(), FairConstPar::putParams(), and FairConstPar::SetParameters().
Double_t FairMapPar::fYmax protected
Definition at line 99 of file Tutorial3/simulation/FairMapPar.h.
Referenced by FairConstPar::getParams(), GetYmax(), FairConstPar::putParams(), and FairConstPar::SetParameters().
Double_t FairMapPar::fYmin protected
Definition at line 99 of file Tutorial3/simulation/FairMapPar.h.
Referenced by FairConstPar::getParams(), GetYmin(), FairConstPar::putParams(), and FairConstPar::SetParameters().
Double_t FairMapPar::fZmax protected
Definition at line 100 of file Tutorial3/simulation/FairMapPar.h.
Referenced by FairConstPar::getParams(), GetZmax(), FairConstPar::putParams(), and FairConstPar::SetParameters().
Double_t FairMapPar::fZmin protected
Definition at line 100 of file Tutorial3/simulation/FairMapPar.h.
Referenced by FairConstPar::getParams(), GetZmin(), FairConstPar::putParams(), and FairConstPar::SetParameters().
Bool_t FairParSet::owned protected inherited
flag is kTRUE if parameters have changed
Definition at line 27 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::isOwned(), and FairParSet::operator=().
TString FairParSet::paramContext protected inherited
if flag is KTRUE FairDB has the par. class ownership
Definition at line 28 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
Bool_t FairParSet::status protected inherited
versions of container in the 2 possible inputs
Definition at line 25 of file FairParSet.h.
Referenced by FairTutorialDet2DigiPar::clear(), FairParSet::FairParSet(), FairParSet::isStatic(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
Int_t FairParSet::versions[3] protected inherited
name of the detector the container belongs to
Definition at line 24 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
The documentation for this class was generated from the following files:
Tutorial3/simulation/FairMapPar.h
Tutorial3/simulation/FairMapPar.cxx