FairRroot: FairGeoRotation Class Reference
FairGeoRotation Class Reference
#include <FairGeoRotation.h>
Public Member Functions
FairGeoRotation ()
FairGeoRotation (const FairGeoRotation &)
FairGeoRotation (const Double_t *)
FairGeoRotation (const Double_t, const Double_t, const Double_t)
~FairGeoRotation ()
void setMatrix (const Double_t *)
void setMatrix (const Float_t *)
void setEulerAngles (const Double_t, const Double_t, const Double_t)
void setElement (const Double_t, const Int_t)
Double_t operator() (Int_t) const
FairGeoRotation & operator= (const FairGeoRotation &)
Bool_t operator== (const FairGeoRotation &)
Bool_t operator!= (const FairGeoRotation &)
FairGeoVector operator* (const FairGeoVector &) const
FairGeoRotation operator* (const FairGeoRotation &) const
FairGeoRotation & operator*= (const FairGeoRotation &)
FairGeoRotation & transform (const FairGeoRotation &)
Bool_t isUnitMatrix ()
FairGeoRotation inverse () const
FairGeoRotation & invert ()
Double_t determinant () const
Double_t diff2 (const FairGeoRotation &) const
Double_t getElement (Int_t i, Int_t j) const
void setUnitMatrix ()
void setZero ()
void print () const
TRotMatrix * createTRotMatrix (const Text_t *name="", const Text_t *title="")
Protected Attributes
Double_t rot [9]
Detailed Description
rotation matrix
Author
Ilse koenig
Definition at line 26 of file FairGeoRotation.h.
Constructor & Destructor Documentation
FairGeoRotation::FairGeoRotation () inline
Definition at line 64 of file FairGeoRotation.h.
References rot.
Referenced by inverse(), and operator*().
   :TObject()
 {
   rot[0]=rot[4]=rot[8]=1.;
   rot[1]=rot[2]=rot[3]=rot[5]=rot[6]=rot[7]=0.;
 }
FairGeoRotation::FairGeoRotation (const FairGeoRotation & r) inline
Definition at line 78 of file FairGeoRotation.h.
References rot.
   :TObject(r)
 {
   for(Int_t i=0; i<9; i++) { rot[i]=r(i); }
 }
FairGeoRotation::FairGeoRotation (const Double_t * a) inline
Definition at line 84 of file FairGeoRotation.h.
References rot.
   :TObject()
 {
   for(Int_t i=0; i<9; i++) { rot[i]=a[i]; }
 }
FairGeoRotation::FairGeoRotation (const Double_t , const Double_t , const Double_t)
FairGeoRotation::~FairGeoRotation () inline
Definition at line 35 of file FairGeoRotation.h.
 {}
Member Function Documentation
TRotMatrix * FairGeoRotation::createTRotMatrix (const Text_t * name = "", const Text_t * title = "")
Definition at line 127 of file FairGeoRotation.cxx.
References isUnitMatrix(), and rot.
 {
   // creates a TRotMatrix
   // (uses a new() operator and the user has to take care to free the memory)
   TRotMatrix* t=0;
   if (isUnitMatrix()==kTRUE) { return t; }
   Double_t a[9];
   for(Int_t i=0; i<3; i++) {
     for(Int_t j=0; j<3; j++) { a[j+3*i]=rot[i+3*j]; }
   }
   t=new TRotMatrix(name,title,a);
   return t;
 }
Double_t FairGeoRotation::determinant () const inline
Definition at line 187 of file FairGeoRotation.h.
References rot.
 {
   return rot[0]*(rot[4]*rot[8]-rot[7]*rot[5])
          -rot[3]*(rot[1]*rot[8]-rot[7]*rot[2])
          +rot[6]*(rot[1]*rot[5]-rot[4]*rot[2]);
 }
Double_t FairGeoRotation::diff2 (const FairGeoRotation & r) const
Definition at line 115 of file FairGeoRotation.cxx.
References rot.
Referenced by FairGeoTransform::transTo().
 {
   // calculates the square of the difference between 2 matrices
   Double_t s=0;
   for(Int_t i=0; i<9; i++) {
     Double_t d=rot[i]-r(i);
     s+=d*d;
   }
   return s;
 }
Double_t FairGeoRotation::getElement (Int_t i, Int_t j) const inline
Definition at line 105 of file FairGeoRotation.h.
References rot.
 {
   return rot[i*3+j];
 }
FairGeoRotation FairGeoRotation::inverse () const inline
Definition at line 173 of file FairGeoRotation.h.
References FairGeoRotation(), and rot.
Referenced by invert(), and FairGeoTransform::transTo().
 {
   Double_t a[9];
   for(Int_t i=0; i<3; i++) {
     for(Int_t j=0; j<3; j++) { a[j+3*i]=rot[i+3*j]; }
   }
   return FairGeoRotation(a);
 }
FairGeoRotation & FairGeoRotation::invert () inline
Definition at line 182 of file FairGeoRotation.h.
References inverse().
Referenced by FairGeoTransform::invert().
 {
   return *this=inverse();
 }
Bool_t FairGeoRotation::isUnitMatrix () inline
Definition at line 166 of file FairGeoRotation.h.
References rot.
Referenced by createTRotMatrix().
 {
   return (rot[0]==1. && rot[1]==0. && rot[2]==0. &&
           rot[3]==0. && rot[4]==1. && rot[5]==0. &&
           rot[6]==0. && rot[7]==0. && rot[8]==1.)  ? kTRUE : kFALSE;
 }
Bool_t FairGeoRotation::operator!= (const FairGeoRotation & r) inline
Definition at line 126 of file FairGeoRotation.h.
References rot.
 {
   Int_t i=0;
   while (i<9) {
     if (rot[i]!=r(i)) { return kTRUE; }
     i++;
   }
   return kFALSE;
 }
Double_t FairGeoRotation::operator() (Int_t i) const inline
Definition at line 71 of file FairGeoRotation.h.
References rot.
 {
   if (i>=0 && i<9) { return rot[i]; }
   Error("operator()","bad index");
   return 0;
 }
FairGeoVector FairGeoRotation::operator* (const FairGeoVector & v) const inline
Definition at line 136 of file FairGeoRotation.h.
References rot.
Referenced by operator*=().
 {
   return FairGeoVector(rot[0]*v(0)+rot[1]*v(1)+rot[2]*v(2),
                        rot[3]*v(0)+rot[4]*v(1)+rot[5]*v(2),
                        rot[6]*v(0)+rot[7]*v(1)+rot[8]*v(2));
 }
FairGeoRotation FairGeoRotation::operator* (const FairGeoRotation & r) const inline
Definition at line 143 of file FairGeoRotation.h.
References FairGeoRotation(), and rot.
 {
   Double_t a[9];
   for(Int_t kk=0; kk<9; kk++) { a[kk]=0; }
   for(Int_t i=0; i<3; i++) {
     for(Int_t j=0; j<3; j++) {
       Int_t n=3*i+j;
       for(Int_t k=0; k<3; k++) { a[n]+=rot[3*i+k]*r(3*k+j); }
     }
   }
   return FairGeoRotation(&a[0]);
 }
FairGeoRotation & FairGeoRotation::operator*= (const FairGeoRotation & r) inline
Definition at line 156 of file FairGeoRotation.h.
References operator*().
 {
   return *this=operator * (r);
 }
FairGeoRotation & FairGeoRotation::operator= (const FairGeoRotation & r) inline
Definition at line 110 of file FairGeoRotation.h.
References rot.
 {
   for(Int_t i=0; i<9; i++) { rot[i]=r(i); }
   return *this;
 }
Bool_t FairGeoRotation::operator== (const FairGeoRotation & r) inline
Definition at line 116 of file FairGeoRotation.h.
References rot.
 {
   Int_t i=0;
   while (i<9) {
     if (rot[i]!=r(i)) { return kFALSE; }
     i++;
   }
   return kTRUE;
 }
void FairGeoRotation::print () const inline
Definition at line 205 of file FairGeoRotation.h.
References rot.
Referenced by FairGeoTransform::print(), and FairGeoNode::print().
 {
   for(Int_t i=0; i<9; i++) { std::cout<<rot[i]<<"  "; }
   std::cout<<'\n';
 }
void FairGeoRotation::setElement (const Double_t a, const Int_t i) inline
Definition at line 100 of file FairGeoRotation.h.
References rot.
 {
   if (i<9) { rot[i]=a; }
 }
void FairGeoRotation::setEulerAngles (const Double_t a, const Double_t b, const Double_t c)
Definition at line 92 of file FairGeoRotation.cxx.
References rot.
 {
   // sets the matrix calculating the values from the given Euler angles
   const double deg2rad=0.01745329252;
   Double_t s0=TMath::Sin(a*deg2rad);
   Double_t c0=TMath::Cos(a*deg2rad);
   Double_t s1=TMath::Sin(b*deg2rad);
   Double_t c1=TMath::Cos(b*deg2rad);
   Double_t s2=TMath::Sin(c*deg2rad);
   Double_t c2=TMath::Cos(c*deg2rad);
   rot[0]=c0*c1*c2 - s0*s2;
   rot[1]=-c0*c1*s2 - s0*c2;
   rot[2]=c0*s1;
   rot[3]=s0*c1*c2 + c0*s2;
   rot[4]=c0*c2 - s0*c1*s2;
   rot[5]=s0*s1;
   rot[6]=-s1*c2;
   rot[7]=s1*s2;
   rot[8]=c1;
 }
void FairGeoRotation::setMatrix (const Double_t * a) inline
Definition at line 90 of file FairGeoRotation.h.
References rot.
Referenced by FairGeoTransform::setRotMatrix().
 {
   for(Int_t i=0; i<9; i++) { rot[i]=a[i]; }
 }
void FairGeoRotation::setMatrix (const Float_t * a) inline
Definition at line 95 of file FairGeoRotation.h.
References rot.
 {
   for(Int_t i=0; i<9; i++) { rot[i]=a[i]; }
 }
void FairGeoRotation::setUnitMatrix () inline
Definition at line 194 of file FairGeoRotation.h.
References rot.
Referenced by FairGeoTransform::clear(), and FairGeoTransform::transTo().
 {
   rot[0]=rot[4]=rot[8]=1.;
   rot[1]=rot[2]=rot[3]=rot[5]=rot[6]=rot[7]=0.;
 }
void FairGeoRotation::setZero () inline
Definition at line 200 of file FairGeoRotation.h.
References rot.
 {
   for(Int_t i=0; i<9; i++) { rot[i]=0.; }
 }
FairGeoRotation & FairGeoRotation::transform (const FairGeoRotation & r) inline
Definition at line 161 of file FairGeoRotation.h.
Referenced by FairGeoTransform::transFrom(), and FairGeoTransform::transTo().
 {
   return *this=r*(*this);
 }
Member Data Documentation
Double_t FairGeoRotation::rot[9] protected
Definition at line 29 of file FairGeoRotation.h.
Referenced by createTRotMatrix(), determinant(), diff2(), FairGeoRotation(), getElement(), inverse(), isUnitMatrix(), operator!=(), operator()(), operator*(), operator=(), operator==(), print(), setElement(), setEulerAngles(), setMatrix(), setUnitMatrix(), and setZero().
The documentation for this class was generated from the following files:
FairGeoRotation.h
FairGeoRotation.cxx