FairRoot: FairTestDetectorDigiSorterTask Class Reference
FairTestDetectorDigiSorterTask Class Reference
#include <FairTestDetectorDigiSorterTask.h>
Public Member Functions
FairTestDetectorDigiSorterTask ()
FairTestDetectorDigiSorterTask (const char *name)
FairTestDetectorDigiSorterTask (Int_t numberOfCells, Double_t widthOfCells, TString inputBranch, TString outputBranch, TString folderName)
virtual ~FairTestDetectorDigiSorterTask ()
virtual void AddNewDataToTClonesArray (FairTimeStamp *data)
virtual FairRingSorter * InitSorter (Int_t numberOfCells, Double_t widthOfCells) const
ClassDef (FairTestDetectorDigiSorterTask, 1)
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void Exec (Option_t *opt)
virtual void FinishEvent ()
virtual void FinishTask ()
virtual void SetParContainers ()
void SetPersistance (Bool_t p=kTRUE)
Bool_t GetPersistance ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
ClassDef (FairRingSorterTask, 2)
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
FairRingSorter * fSorter
Bool_t fPersistance
Bool_t fDigiPixelMCInfo
Int_t fNumberOfCells
Double_t fWidthOfCells
TString fInputBranch
TClonesArray * fInputArray
TString fOutputBranch
TString fFolder
TClonesArray * fOutputArray
Int_t fEntryNr
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 26 of file FairTestDetectorDigiSorterTask.h.
Constructor & Destructor Documentation
FairTestDetectorDigiSorterTask::FairTestDetectorDigiSorterTask ()
Definition at line 30 of file FairTestDetectorDigiSorterTask.cxx.
 {
     // TODO Auto-generated constructor stub
 }
FairTestDetectorDigiSorterTask::FairTestDetectorDigiSorterTask (const char * name) inline
Definition at line 30 of file FairTestDetectorDigiSorterTask.h.
         : FairRingSorterTask(name) {};
FairTestDetectorDigiSorterTask::FairTestDetectorDigiSorterTask (Int_t numberOfCells, Double_t widthOfCells, TString inputBranch, TString outputBranch, TString folderName) inline
Definition at line 32 of file FairTestDetectorDigiSorterTask.h.
         : FairRingSorterTask(numberOfCells, widthOfCells, inputBranch, outputBranch, folderName) {};
FairTestDetectorDigiSorterTask::~FairTestDetectorDigiSorterTask () virtual
Definition at line 35 of file FairTestDetectorDigiSorterTask.cxx.
 {
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
void FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray (FairTimeStamp * data) virtual
Reimplemented from FairRingSorterTask.
Definition at line 40 of file FairTestDetectorDigiSorterTask.cxx.
References FairLogger::endl(), FairRingSorterTask::fOutputBranch, FairTask::fVerbose, FairRootManager::GetTClonesArray(), INFO, FairRootManager::Instance(), and LOG.
 {
     FairRootManager* ioman = FairRootManager::Instance();
     TClonesArray* myArray = ioman->GetTClonesArray(fOutputBranch);
     if (fVerbose > 1)
     {
         LOG(INFO) << "AddNewDataToTClonesArray Data: "
                   << FairLogger::endl;
         LOG(INFO) << static_cast<FairTestDetectorDigi*>(data)->ToString();
     }
     new ((*myArray)[myArray->GetEntries()]) FairTestDetectorDigi(*(FairTestDetectorDigi*)(data));
 }
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTestDetectorDigiSorterTask::ClassDef (FairTestDetectorDigiSorterTask , 1)
FairRingSorterTask::ClassDef (FairRingSorterTask , 2) protected inherited
void FairRingSorterTask::Exec (Option_t * opt) virtual inherited
Virtual method Exec
Definition at line 60 of file FairRingSorterTask.cxx.
References FairRingSorter::AddElement(), FairRingSorterTask::AddNewDataToTClonesArray(), FairRingSorter::DeleteOutputData(), FairRingSorterTask::fEntryNr, FairRingSorterTask::fInputArray, FairRingSorterTask::fInputBranch, FairRingSorterTask::fOutputArray, FairRingSorterTask::fOutputBranch, FairRingSorterTask::fSorter, FairTask::fVerbose, FairRootManager::GetEmptyTClonesArray(), FairRingSorter::GetOutputData(), FairRootManager::GetTClonesArray(), FairTimeStamp::GetTimeStamp(), FairRootManager::Instance(), FairTimeStamp::Print(), and FairTimeStamp::SetEntryNr().
 {
   fInputArray = FairRootManager::Instance()->GetTClonesArray(fInputBranch);
   if (fVerbose > 1) {
     std::cout << "-I- FairRingSorterTask: Size PixelArray: " << fInputArray->GetEntriesFast() << std::endl;
   }
   for (int i = 0; i < fInputArray->GetEntriesFast(); i++) {
     FairTimeStamp* myData = (FairTimeStamp*)fInputArray->At(i);
     myData->SetEntryNr(FairLink(0, fEntryNr, fInputBranch, i));
     if (fVerbose > 1) {
       std::cout << "Sorter filled with: ";
       myData->Print();
       std::cout<< std::endl;
     }
     fSorter->AddElement(myData, myData->GetTimeStamp());
   }
   if (fVerbose > 2) { fSorter->Print(); }
   std::vector<FairTimeStamp*> sortedData = fSorter->GetOutputData();
   fOutputArray = FairRootManager::Instance()->GetEmptyTClonesArray(fOutputBranch);
   for (int i = 0; i < sortedData.size(); i++) {
     AddNewDataToTClonesArray(sortedData[i]);
   }
   fSorter->DeleteOutputData();
   fEntryNr++;
 }
virtual void FairTask::Finish () inline protected virtual inherited
Action after each event. To be implemented in the derived class
Reimplemented in FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, FairDbTutAccessRtdbTask, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 111 of file FairTask.h.
Referenced by FairTask::FinishTask(), and FairTask::FinishTasks().
 { };
void FairRingSorterTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 102 of file FairRingSorterTask.cxx.
References FairRingSorterTask::fOutputArray.
 {
   fOutputArray->Delete();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairRingSorterTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 107 of file FairRingSorterTask.cxx.
References FairRingSorter::AddElement(), FairRingSorterTask::AddNewDataToTClonesArray(), FairRingSorter::DeleteOutputData(), FairRingSorterTask::fInputArray, FairRingSorterTask::fInputBranch, FairRingSorterTask::fOutputArray, FairRingSorterTask::fOutputBranch, FairRingSorterTask::fSorter, FairTask::fVerbose, FairRootManager::GetEmptyTClonesArray(), FairRingSorter::GetOutputData(), FairRootManager::GetTClonesArray(), FairRootManager::Instance(), FairRootManager::SetLastFill(), and FairRingSorter::WriteOutAll().
 {
   fInputArray = FairRootManager::Instance()->GetTClonesArray(fInputBranch);
   if (fVerbose > 2) { std::cout << "-I- FairRingSorterTaskT::FinishTask Size InputArray: " << fInputArray->GetEntriesFast() << std::endl; }
   for (int i = 0; i < fInputArray->GetEntriesFast(); i++) {
     FairTimeStamp* myDigi = (FairTimeStamp*) fInputArray->At(i);
     fSorter->AddElement(myDigi, ((FairTimeStamp*)myDigi)->GetTimeStamp());
   }
   fSorter->Print();
   fSorter->WriteOutAll();
   std::vector<FairTimeStamp*> sortedData = fSorter->GetOutputData();
   FairRootManager* ioman = FairRootManager::Instance();
   fOutputArray = ioman->GetEmptyTClonesArray(fOutputBranch);
   for (int i = 0; i < sortedData.size(); i++) {
     if (fVerbose > 2) {
       std::cout << i << " FinishTask : ";
       sortedData[i]->Print();
       std::cout << std::endl;
     }
     AddNewDataToTClonesArray(sortedData[i]);
   }
   fSorter->DeleteOutputData();
   if (fVerbose > 1) {
     fSorter->Print();
   }
   ioman->SetLastFill();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
Bool_t FairRingSorterTask::GetPersistance () inline inherited
Definition at line 97 of file FairRingSorterTask.h.
References FairRingSorterTask::fPersistance.
 {return fPersistance;};
InitStatus FairRingSorterTask::Init () virtual inherited
Virtual method Init
Reimplemented from FairTask.
Definition at line 36 of file FairRingSorterTask.cxx.
References FairRingSorterTask::fFolder, FairRingSorterTask::fInputArray, FairRingSorterTask::fInputBranch, FairRingSorterTask::fNumberOfCells, FairRingSorterTask::fOutputArray, FairRingSorterTask::fOutputBranch, FairRingSorterTask::fPersistance, FairRingSorterTask::fSorter, FairTask::fVerbose, FairRingSorterTask::fWidthOfCells, FairRootManager::GetTClonesArray(), FairRingSorterTask::InitSorter(), FairRootManager::Instance(), kFATAL, kSUCCESS, and FairRootManager::Register().
 {
   FairRootManager* ioman = FairRootManager::Instance();
   if ( ! ioman ) {
     std::cout << "-E- FairRingSorterTaskT::Init: "
               << "RootManager not instantiated!" << std::endl;
     return kFATAL;
   }
   fSorter = InitSorter(fNumberOfCells, fWidthOfCells);
   // Create and register output array
   fInputArray = FairRootManager::Instance()->GetTClonesArray(fInputBranch);
   if(fVerbose>1) { Info("Init","Registering this branch: %s/%s",fFolder.Data(),fOutputBranch.Data()); }
   fOutputArray = ioman->Register(fOutputBranch, fInputArray->GetClass()->GetName(), fFolder, fPersistance);
   return kSUCCESS;
 }
FairRingSorter * FairTestDetectorDigiSorterTask::InitSorter (Int_t numberOfCells, Double_t widthOfCells) const virtual
Reimplemented from FairRingSorterTask.
Definition at line 53 of file FairTestDetectorDigiSorterTask.cxx.
 {
     return new FairTestDetectorDigiRingSorter(numberOfCells, widthOfCells);
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
InitStatus FairRingSorterTask::ReInit () virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 25 of file FairRingSorterTask.cxx.
References kSUCCESS.
 {
   return kSUCCESS;
 }
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
virtual void FairRingSorterTask::SetParContainers () inline virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 94 of file FairRingSorterTask.h.
 {};
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairRingSorterTask::SetPersistance (Bool_t p = kTRUE) inline inherited
Definition at line 96 of file FairRingSorterTask.h.
References FairRingSorterTask::fPersistance.
 {fPersistance=p;};
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
Bool_t FairRingSorterTask::fDigiPixelMCInfo protected inherited
switch to turn on/off storing additional MC Info of Digis
Definition at line 108 of file FairRingSorterTask.h.
Int_t FairRingSorterTask::fEntryNr protected inherited
Definition at line 118 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec().
TString FairRingSorterTask::fFolder protected inherited
Definition at line 116 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Init().
TClonesArray* FairRingSorterTask::fInputArray protected inherited
Definition at line 113 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), and FairRingSorterTask::Init().
TString FairRingSorterTask::fInputBranch protected inherited
Input array of PndSdsPixelDigis
Definition at line 112 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), and FairRingSorterTask::Init().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
Int_t FairRingSorterTask::fNumberOfCells protected inherited
Definition at line 109 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Init().
TClonesArray* FairRingSorterTask::fOutputArray protected inherited
Definition at line 117 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec(), FairRingSorterTask::FinishEvent(), FairRingSorterTask::FinishTask(), and FairRingSorterTask::Init().
TString FairRingSorterTask::fOutputBranch protected inherited
Output array of sorted PndSdsDigis
Definition at line 115 of file FairRingSorterTask.h.
Referenced by AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairRingSorterTask::AddNewDataToTClonesArray(), FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), and FairRingSorterTask::Init().
Bool_t FairRingSorterTask::fPersistance protected inherited
switch to turn on/off storing the arrays to a file
Definition at line 106 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::GetPersistance(), FairRingSorterTask::Init(), and FairRingSorterTask::SetPersistance().
FairRingSorter* FairRingSorterTask::fSorter protected inherited
Definition at line 104 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), and FairRingSorterTask::~FairRingSorterTask().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
Double_t FairRingSorterTask::fWidthOfCells protected inherited
Definition at line 110 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Init().
The documentation for this class was generated from the following files:
FairTestDetectorDigiSorterTask.h
FairTestDetectorDigiSorterTask.cxx