FairRoot: BoostDeSerializer< DataType, TContainer, BoostArchiveIn > Class Template Reference
BoostDeSerializer< DataType, TContainer, BoostArchiveIn > Class Template Reference
#include <BoostSerializer.h>
Public Member Functions
BoostDeSerializer ()
~BoostDeSerializer ()
void CloseMessage ()
void SetMessage (FairMQMessage *msg)
void GetMessage ()
void Init ()
void DoDeSerialization (FairMQMessage *msg)
template<typename T = TContainer, enable_if_match< T, std::vector< DataType > > = 0>
T & DeSerializeMsg (FairMQMessage *msg)
template<typename T = TContainer, enable_if_match< T, TClonesArray * > = 0>
void InitTClonesArray (const std::string &ClassName)
template<typename T = TContainer, enable_if_match< T, TClonesArray * > = 0>
T DeSerializeMsg (FairMQMessage *msg)
template<typename T = TContainer, enable_if_match< T, DataType > = 0>
T DeSerializeMsg (FairMQMessage *msg)
template<typename T = TContainer, enable_if_match< T, FairMQMessage * > = 0>
T DeSerializeMsg (FairMQMessage *msg)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Diverse.
template<typename T = TContainer, enable_if_pointer< T > = 0, typename... Args>
void InitContainer (Args...args)
template<typename T = TContainer, enable_if_pointer< T > = 0>
void InitContainer (TContainer container)
template<typename T = TContainer, enable_ifnot_pointer< T > = 0>
void InitContainer ()
Protected Member Functions
virtual void SetTransport (FairMQTransportFactory *transport)
template<typename T = TContainer, enable_if_pointer< T > = 0>
void DefaultContainerInit ()
container init/destroy specialization for pointer/not pointer type ///
template<typename T = TContainer, enable_ifnot_pointer< T > = 0>
void DefaultContainerInit ()
template<typename T = TContainer, enable_if_pointer< T > = 0>
void DestroyContainer ()
template<typename T = TContainer, enable_ifnot_pointer< T > = 0>
void DestroyContainer ()
Protected Attributes
FairMQMessage * fMessage
FairMQTransportFactory * fTransport
std::vector< DataType > fDataVector
TContainer fDataContainer
Detailed Description
template<typename DataType, typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn>
class BoostDeSerializer< DataType, TContainer, BoostArchiveIn >
Definition at line 242 of file BoostSerializer.h.
Constructor & Destructor Documentation
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::BoostDeSerializer () inline
Definition at line 246 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DefaultContainerInit().
                             :   fMessage(nullptr),
                                 fTransport(nullptr)
                             {DefaultContainerInit();}
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::~BoostDeSerializer () inline
Definition at line 249 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DestroyContainer().
             {DestroyContainer();}
Member Function Documentation
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::CloseMessage () inline
Definition at line 252 of file BoostSerializer.h.
References FairMQMessage::CloseMessage(), and BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fMessage.
         {
             if(fMessage)
                 fMessage->CloseMessage();
         }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_pointer< T > = 0> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DefaultContainerInit () inline protected
container init/destroy specialization for pointer/not pointer type ///
Definition at line 405 of file BoostSerializer.h.
Referenced by BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::BoostDeSerializer().
             {
                 fDataContainer=nullptr;
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_ifnot_pointer< T > = 0> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DefaultContainerInit () inline protected
Definition at line 411 of file BoostSerializer.h.
             {
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_match< T, std::vector< DataType > > = 0> T& BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg (FairMQMessage * msg) inline
FairMQMessage* -----—> std::vector<DataType>&
Definition at line 297 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DoDeSerialization(), and BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataVector.
             {
                 DoDeSerialization(msg);
                 return fDataVector;
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_match< T, TClonesArray * > = 0> T BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg (FairMQMessage * msg) inline
Definition at line 314 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DoDeSerialization(), ERROR, BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataContainer, BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataVector, and MQLOG.
             {
                 DoDeSerialization(msg);
                 if(fDataContainer)
                 {
                     fDataContainer->Delete();
                     for (unsigned int i(0); i < fDataVector.size(); ++i)
                     {
                         new ((*fDataContainer)[i]) DataType(fDataVector.at(i));
                     }
                     if (fDataContainer->IsEmpty())
                     {
                         MQLOG(ERROR) << "BoostSerializer::message(): No Output array!";
                     }
                 }
                 return fDataContainer;
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_match< T, DataType > = 0> T BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg (FairMQMessage * msg) inline
FairMQMessage* -----—> DataType
Definition at line 335 of file BoostSerializer.h.
References buffer, ERROR, BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataContainer, FairMQMessage::GetData(), FairMQMessage::GetSize(), and MQLOG.
             {
                 std::string msgStr(static_cast<char*>(msg->GetData()), msg->GetSize());
                 std::istringstream buffer(msgStr);
                 BoostArchiveIn InputArchive(buffer);
                 try
                 {
                     InputArchive >> fDataContainer;
                 }
                 catch (boost::archive::archive_exception& e)
                 {
                     MQLOG(ERROR) << e.what();
                 }
                 return fDataContainer;
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_match< T, FairMQMessage * > = 0> T BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg (FairMQMessage * msg) inline
FairMQMessage* -----—> FairMQMessage*
Definition at line 354 of file BoostSerializer.h.
             {
                 return msg;
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_pointer< T > = 0> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DestroyContainer () inline protected
Definition at line 416 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataContainer.
Referenced by BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::~BoostDeSerializer().
             {
                 if(fDataContainer)
                     delete fDataContainer;
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_ifnot_pointer< T > = 0> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DestroyContainer () inline protected
Definition at line 423 of file BoostSerializer.h.
             {
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DoDeSerialization (FairMQMessage * msg) inline
main method to boost deserialize
Definition at line 277 of file BoostSerializer.h.
References buffer, ERROR, BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataVector, FairMQMessage::GetData(), FairMQMessage::GetSize(), and MQLOG.
Referenced by BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg().
         {
             if (fDataVector.size() > 0)
                     fDataVector.clear();
             std::string msgStr(static_cast<char*>(msg->GetData()), msg->GetSize());
             std::istringstream buffer(msgStr);
             BoostArchiveIn InputArchive(buffer);
             try
             {
                 InputArchive >> fDataVector;
             }
             catch (boost::archive::archive_exception& e)
             {
                 MQLOG(ERROR) << e.what();
             }
         }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::GetMessage () inline
Definition at line 263 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fMessage.
         {
             return fMessage;
         }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::Init () inline
Definition at line 268 of file BoostSerializer.h.
         {
             //InitContainer();
         }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_pointer< T > = 0, typename... Args> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::InitContainer (Args... args) inline
Definition at line 369 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataContainer.
             {
                 typedef typename std::remove_pointer<T>::type NoptrT;
                 fDataContainer = new NoptrT(std::forward<Args>(args)...);
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_pointer< T > = 0> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::InitContainer (TContainer container) inline
Definition at line 377 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataContainer.
             {
                 fDataContainer = container;
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_ifnot_pointer< T > = 0> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::InitContainer () inline
Definition at line 383 of file BoostSerializer.h.
             {
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<typename T = TContainer, enable_if_match< T, TClonesArray * > = 0> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::InitTClonesArray (const std::string & ClassName) inline
FairMQMessage* -----—> TClonesArray*
Definition at line 306 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataContainer.
             {
                 if(fDataContainer)
                     delete fDataContainer;
                 fDataContainer = new TClonesArray(ClassName.c_str());
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> template<class Archive > void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::serialize (Archive & ar, const unsigned int version) inline
Diverse.
Definition at line 363 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataVector.
             {
                 ar& fDataVector;
             }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::SetMessage (FairMQMessage * msg) inline
Definition at line 258 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fMessage.
         {
             fMessage=msg;
         }
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> virtual void BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::SetTransport (FairMQTransportFactory * transport) inline protected virtual
Definition at line 390 of file BoostSerializer.h.
References BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fTransport.
         {
             fTransport=transport;
         }
Member Data Documentation
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> TContainer BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataContainer protected
Definition at line 398 of file BoostSerializer.h.
Referenced by BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg(), BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DestroyContainer(), BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::InitContainer(), and BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::InitTClonesArray().
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> std::vector<DataType> BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fDataVector protected
Definition at line 397 of file BoostSerializer.h.
Referenced by BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg(), BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DoDeSerialization(), and BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::serialize().
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> FairMQMessage* BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fMessage protected
Definition at line 395 of file BoostSerializer.h.
Referenced by BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::CloseMessage(), BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::GetMessage(), and BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::SetMessage().
template<typename DataType , typename TContainer = std::vector<DataType>, typename BoostArchiveIn = BoostBinArchIn> FairMQTransportFactory* BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::fTransport protected
Definition at line 396 of file BoostSerializer.h.
Referenced by BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::SetTransport().
The documentation for this class was generated from the following file:
BoostSerializer.h