FairRroot: FairGeoAsciiIo Class Reference
FairGeoAsciiIo Class Reference
#include <FairGeoAsciiIo.h>
Public Member Functions
FairGeoAsciiIo ()
virtual ~FairGeoAsciiIo ()
void setDirectory (const char *fDir)
const char * getDirectory ()
const char * getFilename ()
Bool_t open (const char *, const Text_t *status="in")
Bool_t isOpen ()
Bool_t isWritable ()
void close ()
void print ()
Bool_t read (FairGeoMedia *)
Bool_t read (FairGeoSet *, FairGeoMedia *)
Bool_t write (FairGeoMedia *)
Bool_t write (FairGeoSet *set)
Bool_t readGeomConfig (FairGeoInterface *)
Bool_t readDetectorSetup (FairGeoInterface *)
Bool_t setSimulRefRun (const char *)
Bool_t setHistoryDate (const char *)
Private Member Functions
FairGeoAsciiIo (const FairGeoAsciiIo &)
FairGeoAsciiIo & operator= (const FairGeoAsciiIo &)
Private Attributes
TString filename
TString filedir
Bool_t writable
fstream * file
Detailed Description
Class for geometry I/O from ASCII file
Author
Ilse Koenig
Definition at line 27 of file FairGeoAsciiIo.h.
Constructor & Destructor Documentation
FairGeoAsciiIo::FairGeoAsciiIo ()
FairGeoAsciiIo::~FairGeoAsciiIo () virtual
Definition at line 44 of file FairGeoAsciiIo.cxx.
References close(), and file.
 {
   // Destructor
   close();
   if (file) {
     delete file;
     file=0;
   }
 }
FairGeoAsciiIo::FairGeoAsciiIo (const FairGeoAsciiIo &) private
Member Function Documentation
void FairGeoAsciiIo::close () virtual
Implements FairGeoIo.
Definition at line 103 of file FairGeoAsciiIo.cxx.
References file, filename, and isOpen().
Referenced by open(), and ~FairGeoAsciiIo().
 {
   // Closes the file
   if (isOpen()) {
     file->close();
     filename="";
   }
 }
const char* FairGeoAsciiIo::getDirectory () inline
Definition at line 37 of file FairGeoAsciiIo.h.
 {return filedir.Data();}
const char* FairGeoAsciiIo::getFilename () inline
Definition at line 38 of file FairGeoAsciiIo.h.
 {return filename.Data();}
Bool_t FairGeoAsciiIo::isOpen () virtual
Implements FairGeoIo.
Definition at line 89 of file FairGeoAsciiIo.cxx.
References file.
Referenced by close(), isWritable(), open(), print(), read(), readDetectorSetup(), readGeomConfig(), and write().
 {
   // Returns kTRUE, if the file is open
   if (file && file->rdbuf()->is_open()==1) { return kTRUE; }
   return kFALSE;
 }
Bool_t FairGeoAsciiIo::isWritable () virtual
Implements FairGeoIo.
Definition at line 96 of file FairGeoAsciiIo.cxx.
References isOpen(), and writable.
 {
   // Returns kTRUE, if the file is open and writable
   if (isOpen() && writable) { return kTRUE; }
   return kFALSE;
 }
Bool_t FairGeoAsciiIo::open (const char * fname, const Text_t * status = "in") virtual
Implements FairGeoIo.
Definition at line 54 of file FairGeoAsciiIo.cxx.
References close(), file, filedir, filename, isOpen(), and writable.
 {
   // Opens the file fname
   close();
   if (!file) { file=new fstream(); }
   else { (file->clear()); }
   if (!filedir.IsNull()) { filename=filedir+"/"+fname; }
   else { filename=fname; }
   filename=filename.Strip();
   if (strcmp(status,"in")==0) {
     file->open(filename,ios::in);
     writable=kFALSE;
   } else {
     if (strcmp(status,"out")==0) {
       file->open(filename,ios::in);
       if (!isOpen()) {
         file->close();
         file->clear();
         file->open(filename,ios::out);
         writable=kTRUE;
       } else {
         file->close();
         Error("open","Output file %s exists already and will not be recreated.",
               filename.Data());
         return kFALSE;
       }
     } else { Error("open","Invalid file option!"); }
   }
   if (file->rdbuf()->is_open()==0) {
     Fatal("open","Failed to open file %s",filename.Data());
     return kFALSE;
   }
   return kTRUE;
 }
FairGeoAsciiIo& FairGeoAsciiIo::operator= (const FairGeoAsciiIo &) private
void FairGeoAsciiIo::print () virtual
Implements FairGeoIo.
Definition at line 112 of file FairGeoAsciiIo.cxx.
References filename, isOpen(), and writable.
 {
   // Prints file information
   if (isOpen()) {
     if (writable) { cout<<"Open output file: "<<filename<<endl; }
     else { cout<<"Open input file: "<<filename<<endl; }
   } else { cout<<"No file open."<<endl; }
 }
Bool_t FairGeoAsciiIo::read (FairGeoMedia * media) virtual
Implements FairGeoIo.
Definition at line 121 of file FairGeoAsciiIo.cxx.
References file, isOpen(), FairGeoMedia::read(), and writable.
 {
   // Reads the media from file
   if (!isOpen() || writable || media==0) { return kFALSE; }
   media->read(*file);
   return kTRUE;
 }
Bool_t FairGeoAsciiIo::read (FairGeoSet * set, FairGeoMedia * media) virtual
Implements FairGeoIo.
Definition at line 129 of file FairGeoAsciiIo.cxx.
References file, isOpen(), FairGeoSet::read(), and writable.
 {
   // Reads the geometry set from file
   if (!isOpen() || writable || set==0) { return kFALSE; }
   set->read(*file,media);
   return kTRUE;
 }
Bool_t FairGeoAsciiIo::readDetectorSetup (FairGeoInterface * interface)
Definition at line 195 of file FairGeoAsciiIo.cxx.
References FairGeoInterface::findSet(), FairGeoSet::getMaxModules(), isOpen(), FairGeoSet::setModules(), and writable.
Referenced by FairGeoInterface::readSetupFile().
 {
   // Reads the detector setups, needed for create only subsets
   if (!isOpen() || writable || interface==0) { return kFALSE; }
   const Int_t maxbuf=256;
   char buf[maxbuf];
   TString s, det;
   FairGeoSet* set=0;
   Int_t maxModules=0, secNo=-1;
   Int_t* mod=0;
   const char d[]=" ";
   while(!(*file).eof()) {
     (*file).getline(buf,maxbuf);
     if (strlen(buf)>=3 && buf[1]!='/') {
       if (buf[0]=='[') {
         set=0;
         if (mod) {
           delete [] mod;
           mod=0;
         }
         s=buf;
         Ssiz_t n=s.First(']');
         det=s(1,n-1);
         det.ToLower();
         set=interface->findSet(det);
         if (!set) {
           Error("readDetectorSetup","Detector %s not found",det.Data());
           if (mod) { delete [] mod; }
           return kFALSE;
         }
         maxModules=set->getMaxModules();
         mod=new Int_t[maxModules];
       } else {
         if (set&&mod) {
           char* ss=strtok(buf,d);
           if (ss&&strlen(ss)>3) {
             secNo=(Int_t)(ss[3]-'0')-1;
             for(Int_t i=0; i<maxModules&&mod; i++) {
               ss=strtok(NULL,d);
               if (ss) { sscanf(ss,"%i",&mod[i]); }
             }
             set->setModules(secNo,mod);
           }
         } else {
           if (mod) { delete [] mod; }
           return kFALSE;
         }
       }
     }
   }
   if (mod) { delete [] mod; }
   return kTRUE;
 }
Bool_t FairGeoAsciiIo::readGeomConfig (FairGeoInterface * interface) virtual
Implements FairGeoIo.
Definition at line 153 of file FairGeoAsciiIo.cxx.
References FairGeoInterface::addInputFile(), FairGeoInterface::addSetupFile(), file, FairGeoInterface::getOraInput(), isOpen(), FairGeoIo::setHistoryDate(), FairGeoIo::setSimulRefRun(), and writable.
 {
   // Reads the GEANT configuration file
   if (!isOpen() || writable || interface==0) { return kFALSE; }
   TString buf(256);
   TString simRefRun,historyDate;
   Int_t k=-1;
   while(!(*file).eof()) {
     buf.ReadLine(*file);
     buf=buf.Strip(buf.kBoth);
     if (!buf.IsNull() && buf(0,2)!="//" && buf(0,1)!="*") {
       if (buf.Contains(".geo")||buf.Contains("_gdb")) {
         interface->addInputFile(buf.Data());
       } else {
         if (buf.Contains(".setup")) {
           interface->addSetupFile(buf.Data());
         } else {
           if (buf.Contains("SimulRefRunDb:")) {
             k=buf.Last(' ')+1;
             if (k) { simRefRun=buf(k,buf.Length()-k); }
           } else {
             if (buf.Contains("HistoryDateDb:")) {
               k=buf.First(' ')+1;
               if (buf.Length()>k) {
                 historyDate=buf(k,buf.Length()-k);
                 historyDate=historyDate.Strip(historyDate.kBoth);
               }
             }
           }
         }
       }
     }
   }
   Bool_t rc=kTRUE;
   FairGeoIo* oraIo=interface->getOraInput();
   if (oraIo) {
     if (historyDate.Length()>0) { rc=oraIo->setHistoryDate(historyDate.Data()); }
     if (rc&&simRefRun.Length()>0) { rc=oraIo->setSimulRefRun(simRefRun.Data()); }
   }
   return rc;
 }
void FairGeoAsciiIo::setDirectory (const char * fDir) inline
Definition at line 36 of file FairGeoAsciiIo.h.
 {filedir=fDir;}
Bool_t FairGeoAsciiIo::setHistoryDate (const char *) inline virtual
Implements FairGeoIo.
Definition at line 51 of file FairGeoAsciiIo.h.
 {return kTRUE;}
Bool_t FairGeoAsciiIo::setSimulRefRun (const char *) inline virtual
Implements FairGeoIo.
Definition at line 50 of file FairGeoAsciiIo.h.
 {return kTRUE;}
Bool_t FairGeoAsciiIo::write (FairGeoMedia * media) virtual
Implements FairGeoIo.
Definition at line 137 of file FairGeoAsciiIo.cxx.
References file, isOpen(), writable, and FairGeoMedia::write().
 {
   // Writes the media to file
   if (!isOpen() || !writable || media==0) { return kFALSE; }
   media->write(*file);
   return kTRUE;
 }
Bool_t FairGeoAsciiIo::write (FairGeoSet * set) virtual
Implements FairGeoIo.
Definition at line 145 of file FairGeoAsciiIo.cxx.
References file, isOpen(), writable, and FairGeoSet::write().
 {
   // Writes the geometry set to file
   if (!isOpen() || !writable || set==0) { return kFALSE; }
   set->write(*file);
   return kTRUE;
 }
Member Data Documentation
fstream* FairGeoAsciiIo::file private
Definition at line 32 of file FairGeoAsciiIo.h.
Referenced by close(), isOpen(), open(), read(), readGeomConfig(), write(), and ~FairGeoAsciiIo().
TString FairGeoAsciiIo::filedir private
Definition at line 30 of file FairGeoAsciiIo.h.
Referenced by open().
TString FairGeoAsciiIo::filename private
Definition at line 29 of file FairGeoAsciiIo.h.
Referenced by close(), open(), and print().
Bool_t FairGeoAsciiIo::writable private
Definition at line 31 of file FairGeoAsciiIo.h.
Referenced by isWritable(), open(), print(), read(), readDetectorSetup(), readGeomConfig(), and write().
The documentation for this class was generated from the following files:
FairGeoAsciiIo.h
FairGeoAsciiIo.cxx