FairRoot: FairField.h File Reference
FairField.h File Reference
#include "RVersion.h"
#include "Riosfwd.h"
#include "Rtypes.h"
#include "TNamed.h"
#include <stdio.h>
#include <iostream>
#include "FairLogger.h"
Classes
class TVirtualMagField
Macros
#define ROOT_TVirtualMagField
Functions
ClassImp(TVirtualMagField) class FairField FairField (const char *name, const char *title="FAIR Magnetic Field")
FairField & operator= (const FairField &)
virtual ~FairField ()
virtual void Init ()
Bool_t IsConst ()
Bool_t IsMap ()
Int_t GetType () const
virtual Double_t GetBx (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBy (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBz (Double_t x, Double_t y, Double_t z)
virtual void GetFieldValue (const Double_t point[3], Double_t *bField)
void Field (const Double_t point[3], Double_t *B)
virtual void Print (Option_t *option="") const
virtual void GetBxyz (const Double_t point[3], Double_t *bField)
virtual void FillParContainer ()
FairField (const FairField &)
ClassDef (FairField, 4)
Variables
Int_t fType
Macro Definition Documentation
#define ROOT_TVirtualMagField
FairField.h
Author
M.Al-Turany <m.al/turany.de>
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e
Since
06.01.2004 .0
Abstract base class for magnetic fields in FAIR Concrete field should implement the pure virtual methods GetBx, GetBy and GetBz and/or GetBxyz
Note: Field values should be returned in kG (thanks to GEANT3)
Definition at line 39 of file FairField.h.
Function Documentation
ClassDef (FairField , 4) private
FairField::FairField (const char * name, const char * title = "FAIR Magnetic Field")
Default constructor Constructor with name and title
Definition at line 27 of file FairField.cxx.
Referenced by FairFieldFactory::createFairField(), MyFieldCreator::createFairField(), and FairGeane::Init().
   : TVirtualMagField(name),
     fType(0)
 {
 }
FairField (const FairField &) private
void Field (const Double_t point[3], Double_t * B)
Definition at line 127 of file FairField.h.
References GetFieldValue().
 {GetFieldValue(point,B);}
virtual void FillParContainer () virtual
Fill Paramater
Definition at line 138 of file FairField.h.
References FairLogger::endl(), LOG, and WARNING.
 {LOG(WARNING)<<"FairField::FillParContainer Should be implemented in User class"<<FairLogger::endl;}
virtual Double_t GetBx (Double_t x, Double_t y, Double_t z) virtual
Get x component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Definition at line 106 of file FairField.h.
References FairLogger::endl(), LOG, and WARNING.
Referenced by GetFieldValue().
 {LOG(WARNING)<<"FairField::GetBx Should be implemented in User class"<<FairLogger::endl; return 0;}
virtual void GetBxyz (const Double_t point[3], Double_t * bField) virtual
Definition at line 132 of file FairField.h.
References FairLogger::endl(), LOG, and WARNING.
 {LOG(WARNING)<<"FairField::GetBxyz Should be implemented in User class"<<FairLogger::endl;}
virtual Double_t GetBy (Double_t x, Double_t y, Double_t z) virtual
Get y component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Definition at line 112 of file FairField.h.
References FairLogger::endl(), LOG, and WARNING.
Referenced by GetFieldValue().
 {LOG(WARNING)<<"FairField::GetBy Should be implemented in User class"<<FairLogger::endl; return 0;}
virtual Double_t GetBz (Double_t x, Double_t y, Double_t z) virtual
Get z component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Definition at line 117 of file FairField.h.
References FairLogger::endl(), LOG, and WARNING.
Referenced by GetFieldValue().
 {LOG(WARNING)<<"FairField::GetBz Should be implemented in User class"<<FairLogger::endl; return 0;}
void FairField::GetFieldValue (const Double_t point[3], Double_t * bField) virtual
Get magnetic field. For use of GEANT3
Parameters
point Coordinates [cm]
bField (return) Field components [kG]
Definition at line 60 of file FairField.cxx.
References GetBx(), GetBy(), and GetBz().
Referenced by Field().
 {
   bField[0] = GetBx(point[0], point[1], point[2]);
   bField[1] = GetBy(point[0], point[1], point[2]);
   bField[2] = GetBz(point[0], point[1], point[2]);
 }
Int_t GetType () const
Field type (0=constant, 1=map, 2=map sym2, 3 = map sym3)
Definition at line 100 of file FairField.h.
References fType.
 { return fType; }
virtual void Init () virtual
Intialisation. E.g. read in the field map. If needed, to be implemented in the concrete class.
Definition at line 89 of file FairField.h.
Referenced by ClassImp(), and MultiVariatePDF::MultiVariatePDF().
 { };
Bool_t FairField::IsConst ()
Test whether field type is Constant
Definition at line 44 of file FairField.cxx.
References fType.
 {
   if ( fType == 1 ) { return kTRUE; }
   return kFALSE;
 }
Bool_t FairField::IsMap ()
Test whether field typ is Map
Definition at line 54 of file FairField.cxx.
References fType.
 {
   if ( fType == 2 ) { return kTRUE; }
   return kFALSE;
 }
FairField& operator= (const FairField &)
Definition at line 80 of file FairField.h.
Referenced by FairMCObject::operator=(), FairGenerator::operator=(), FairParSet::operator=(), FairBoxGenerator::operator=(), FairModule::operator=(), FairPrimaryGenerator::operator=(), FairGenericStack::operator=(), and FairMCApplication::operator=().
 {return *this;}
virtual void Print (Option_t * option = "") const virtual
Screen output. To be implemented in the concrete class.
Definition at line 131 of file FairField.h.
Referenced by FairDbTutParBin::print().
 {;}
FairField::~FairField () virtual
Destructor
Definition at line 38 of file FairField.cxx.
 { }
Variable Documentation
Int_t fType
Field type. 1 = constant field, 2 = field map.
Definition at line 142 of file FairField.h.
Referenced by MyFieldCreator::createFairField(), FairConstField::FairConstField(), GetType(), IsConst(), IsMap(), and MyConstField::MyConstField().