FairRroot: create_digis.C File Reference
create_digis.C File Reference
Functions
void create_digis ()
Function Documentation
void create_digis ()
Definition at line 8 of file create_digis.C.
References FairRun::AddTask(), FairRuntimeDb::getContainer(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairRunAna::Init(), FairParAsciiFileIo::open(), FairParRootFileIo::open(), FairParSet::print(), FairRuntimeDb::print(), FairRunAna::Run(), FairRuntimeDb::saveOutput(), FairParSet::setChanged(), FairRuntimeDb::setFirstInput(), FairRunAna::SetInputFile(), FairParSet::setInputVersion(), FairRuntimeDb::setOutput(), FairRun::SetOutputFile(), and FairRuntimeDb::setSecondInput().
                    {
     TStopwatch timer;
     timer.Start();
     gDebug=0;
     TString dir = getenv("VMCWORKDIR");
     TString tutdir = dir + "/Tutorial2";
     TString inFile = "./tutorial2_pions.mc_p2.000_t0_n10.root";
     TString paramFile = "./tutorial2_pions.params_p2.000_t0_n10.root";
     TString outFile = "./digis.mc.root";
     cout << "******************************" << endl;
     cout << "InFile: " << inFile << endl;
     cout << "ParamFile: " << paramFile << endl;
     cout << "OutFile: " << outFile << endl;
     cout << "******************************" << endl;
     FairRunAna *fRun= new FairRunAna();
     fRun->SetInputFile(inFile);
     fRun->SetOutputFile(outFile);
     // Init Simulation Parameters from Root File
     FairRuntimeDb* rtdb=fRun->GetRuntimeDb();
     FairParRootFileIo* io1=new FairParRootFileIo();
     io1->open(paramFile.Data(),"UPDATE");
     FairParAsciiFileIo* parInput2 = new FairParAsciiFileIo();
     TString tutDetDigiFile = gSystem->Getenv("VMCWORKDIR");
     tutDetDigiFile += "/Tutorial2/parameters/tutdet.digi.par";
     parInput2->open(tutDetDigiFile.Data(),"in");
     rtdb->setFirstInput(io1);
     rtdb->setSecondInput(parInput2);
    rtdb->print();
     //**  TUt Det Digi Producer **//
     FairTutorialDet2Digitizer *digi = new FairTutorialDet2Digitizer("tutdet","tut det task");
     // add the task
     fRun->AddTask( digi );
     fRun->Init();
     rtdb->getContainer("FairTutorialDet2DigiPar")->print();
     FairTutorialDet2DigiPar* DigiPar = (FairTutorialDet2DigiPar*)
                                       rtdb->getContainer("FairTutorialDet2DigiPar");
     DigiPar->setChanged();
     DigiPar->setInputVersion(fRun->GetRunId(),1);
     rtdb->setOutput(io1);
     rtdb->saveOutput();
     rtdb->print();
     fRun->Run();
     timer.Stop();
     Double_t rtime = timer.RealTime();
     Double_t ctime = timer.CpuTime();
     printf("RealTime=%f seconds, CpuTime=%f seconds\n",rtime,ctime);
     cout << "Macro finished succesfully." << endl;
 }