FairRoot: runFileSinkBin.cxx File Reference
Tutorial6/run/runFileSinkBin.cxx File Reference
#include <iostream>
#include <csignal>
#include "FairMQLogger.h"
#include "FairMQFileSink.h"
#include "zeromq/FairMQTransportFactoryZMQ.h"
#include "FairTestDetectorHit.h"
#include "FairTestDetectorPayload.h"
Typedefs
typedef FairTestDetectorHit THit
typedef TestDetectorPayload::Hit TPayloadIn
typedef FairMQFileSink< THit, TPayloadIn > TSink
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
int main (int argc, char **argv)
Variables
TSink filesink
Typedef Documentation
typedef FairTestDetectorHit THit
Definition at line 35 of file Tutorial6/run/runFileSinkBin.cxx.
typedef TestDetectorPayload::Hit TPayloadIn
Definition at line 36 of file Tutorial6/run/runFileSinkBin.cxx.
typedef FairMQFileSink<THit, TPayloadIn> TSink
Definition at line 37 of file Tutorial6/run/runFileSinkBin.cxx.
Function Documentation
int main (int argc, char ** argv)
Definition at line 62 of file Tutorial6/run/runFileSinkBin.cxx.
References FairMQStateMachine::BIND, FairMQStateMachine::ChangeState(), FairMQStateMachine::CONNECT, FairMQStateMachine::END, FairMQDevice::Id, INFO, FairMQStateMachine::INIT, FairMQFileSink< TIn, TPayloadIn >::InitOutputFile(), FairMQDevice::InputAddress, FairMQDevice::InputMethod, FairMQDevice::InputRcvBufSize, FairMQDevice::InputSocketType, LOG, FairMQDevice::NumInputs, FairMQDevice::NumIoThreads, FairMQDevice::NumOutputs, FairMQStateMachine::RUN, s_catch_signals(), FairMQStateMachine::SETINPUT, FairMQStateMachine::SETOUTPUT, FairMQDevice::SetProperty(), FairMQDevice::SetTransport(), and FairMQStateMachine::STOP.
 {
     if (argc != 7)
     {
         cout << "Usage: fileSink \tID numIoTreads\n"
              << "\t\tinputSocketType inputRcvBufHSize inputMethod inputAddress\n" << endl;
         return 1;
     }
     s_catch_signals();
     LOG(INFO) << "PID: " << getpid();
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     filesink.SetTransport(transportFactory);
     int i = 1;
     filesink.SetProperty(TSink::Id, argv[i]);
     ++i;
     int numIoThreads;
     stringstream(argv[i]) >> numIoThreads;
     filesink.SetProperty(TSink::NumIoThreads, numIoThreads);
     ++i;
     filesink.SetProperty(TSink::NumInputs, 1);
     filesink.SetProperty(TSink::NumOutputs, 0);
     filesink.ChangeState(TSink::INIT);
     filesink.InitOutputFile(argv[1]);
     filesink.SetProperty(TSink::InputSocketType, argv[i], 0);
     ++i;
     int inputRcvBufSize;
     stringstream(argv[i]) >> inputRcvBufSize;
     filesink.SetProperty(TSink::InputRcvBufSize, inputRcvBufSize, 0);
     ++i;
     filesink.SetProperty(TSink::InputMethod, argv[i], 0);
     ++i;
     filesink.SetProperty(TSink::InputAddress, argv[i], 0);
     ++i;
     filesink.ChangeState(TSink::SETOUTPUT);
     filesink.ChangeState(TSink::SETINPUT);
     filesink.ChangeState(TSink::BIND);
     filesink.ChangeState(TSink::CONNECT);
     filesink.ChangeState(TSink::RUN);
     char ch;
     cin.get(ch);
     filesink.ChangeState(TSink::STOP);
     filesink.ChangeState(TSink::END);
     return 0;
 }
static void s_catch_signals (void) static
Definition at line 52 of file Tutorial6/run/runFileSinkBin.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 41 of file Tutorial6/run/runFileSinkBin.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, and FairMQStateMachine::STOP.
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     filesink.ChangeState(TSink::STOP);
     filesink.ChangeState(TSink::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
TSink filesink
Definition at line 39 of file Tutorial6/run/runFileSinkBin.cxx.