FairRroot: _GTestFairTools.cxx File Reference
_GTestFairTools.cxx File Reference
#include "FairLogger.h"
#include "FairTestNewOutputHandler.h"
#include "gtest/gtest.h"
#include "gtest/gtest-spi.h"
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <algorithm>
#include <boost/regex.hpp>
Classes
class _TestFairLoggerBase< T >
class FairToolsTest
class LogLevelTest
class VerbosityLevelTest
Functions
TEST (FairToolsTestFatal, TestFatalError)
TEST_F (FairToolsTest, CheckDefaultSettings)
TEST_F (FairToolsTest, CheckOutputOnlyToFile)
TEST_F (FairToolsTest, CheckWrongLogLevelSettings)
TEST_F (FairToolsTest, CheckVerbosityLevelSettings)
TEST_F (FairToolsTest, testScreenAndFileOutputWithoutArgument)
TEST_P (LogLevelTest, testAllLogLevelsToScreenAndFile)
INSTANTIATE_TEST_CASE_P (TestAllLogLevels, LogLevelTest,::testing::ValuesIn(TestLogs))
TEST_P (VerbosityLevelTest, testAllVerbosityLevelsToScreenAndFile)
INSTANTIATE_TEST_CASE_P (TestAllVerbosityLevels, VerbosityLevelTest,::testing::ValuesIn(VerbosityLevelArray))
Variables
static const char *const LogString []
static const char *const TestLogs []
static const char *const VerbosityLevelArray [] = { "LOW", "MEDIUM", "HIGH"}
Function Documentation
INSTANTIATE_TEST_CASE_P (TestAllLogLevels , LogLevelTest , ::testing:: ValuesInTestLogs)
INSTANTIATE_TEST_CASE_P (TestAllVerbosityLevels , VerbosityLevelTest , ::testing:: ValuesInVerbosityLevelArray)
TEST (FairToolsTestFatal , TestFatalError)
Definition at line 35 of file _GTestFairTools.cxx.
References FairLogger::Fatal(), FairLogger::GetLogger(), MESSAGE_ORIGIN, and FairLogger::SetScreenStreamToCerr().
 {
   FairLogger* fLogger;
   fLogger = FairLogger::GetLogger();
   fLogger->SetScreenStreamToCerr(true);
   EXPECT_DEATH(fLogger->Fatal(MESSAGE_ORIGIN, "This is a fatal problem"),
                "FATAL");
   // TODO: check if cored dump is written to file
 }
TEST_F (FairToolsTest , CheckDefaultSettings)
Definition at line 232 of file _GTestFairTools.cxx.
 {
   LogNoArguments();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
 }
TEST_F (FairToolsTest , CheckOutputOnlyToFile)
Definition at line 243 of file _GTestFairTools.cxx.
 {
   char fileName[25];
   tmpnam(fileName);
   fLogger->SetLogFileName(fileName);
   fLogger->SetLogToFile(true);
   fLogger->SetLogToScreen(false);
   LogNoArguments();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckFileOutput(v, fileName);
   }
 }
TEST_F (FairToolsTest , CheckWrongLogLevelSettings)
Definition at line 260 of file _GTestFairTools.cxx.
 {
   fLogger->SetLogToFile(false);
   fLogger->SetLogToScreen(true);
   fLogger->SetLogScreenLevel("BLA");
   LogNoArguments();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   std::string outString="[ERROR  ] Log level \"BLA\" not supported. Use default level \"INFO\".";
   std::vector<std::string>::iterator it;
   it = v.begin();
   it = v.insert ( it , outString );
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
 }
TEST_F (FairToolsTest , CheckVerbosityLevelSettings)
Definition at line 281 of file _GTestFairTools.cxx.
 {
   fLogger->SetLogToFile(false);
   fLogger->SetLogToScreen(true);
   fLogger->SetLogVerbosityLevel("BLA");
   LogNoArguments();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   std::string outString="[ERROR  ] Verbosity level \"BLA\" not supported. Use default level \"LOW\".";
   std::vector<std::string>::iterator it;
   it = v.begin();
   it = v.insert ( it , outString );
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
 }
TEST_F (FairToolsTest , testScreenAndFileOutputWithoutArgument)
Definition at line 304 of file _GTestFairTools.cxx.
 {
   char fileName[25];
   tmpnam(fileName);
   fLogger->SetLogFileName(fileName);
   fLogger->SetLogToScreen(true);
   fLogger->SetLogToFile(true);
   LogNoArguments();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString, fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
   v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckFileOutput(v, fileName);
   }
 }
TEST_P (LogLevelTest , testAllLogLevelsToScreenAndFile)
Definition at line 329 of file _GTestFairTools.cxx.
 {
   fLogger->SetLogFileLevel(logLevelSettingToTest.c_str());
   fLogger->SetLogScreenLevel(logLevelSettingToTest.c_str());
   char fileName[25];
   tmpnam(fileName);
   fLogger->SetLogFileName(fileName);
   fLogger->SetLogToScreen(true);
   fLogger->SetLogToFile(true);
   LogNoArguments();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString, fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
   v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckFileOutput(v, fileName);
   }
 }
TEST_P (VerbosityLevelTest , testAllVerbosityLevelsToScreenAndFile)
Definition at line 360 of file _GTestFairTools.cxx.
 {
   fLogger->SetLogVerbosityLevel(verbosityLevel.c_str());
   char fileName[25];
   tmpnam(fileName);
   fLogger->SetLogFileName(fileName);
   fLogger->SetLogToScreen(true);
   fLogger->SetLogToFile(true);
   LogNoArguments();
   std::vector<std::string> v = CreateExpectedLogLevels(logLevelSettingToTest);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     int Lines = v.size();
     for (int i = 0; i < Lines; ++i) {
       EXPECT_TRUE( CheckVerboseOutput( v[i], OutputString, verbosityLevel, handler.GetCaptureLine(i) ) );
     }
   }
   std::vector<std::string> fileInfo;
   fileInfo=ReadLinesFromFile(fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     int Lines = v.size();
     for (int i = 0; i < Lines; ++i) {
       EXPECT_TRUE( CheckVerboseOutput( v[i], OutputString, verbosityLevel, fileInfo[i] ) );
     }
   }
 }
Variable Documentation
const char* const LogString[] static
Initial value:
= { "FATAL  ", "ERROR  ", "WARNING",
                                       "INFO   ", "DEBUG  ", "DEBUG1 ",
                                       "DEBUG2 ", "DEBUG3 ", "DEBUG4 "
                                       }
Definition at line 21 of file _GTestFairTools.cxx.
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedOutputNoArguments().
const char* const TestLogs[] static
Initial value:
= { "ERROR", "WARNING",
                                        "INFO", "DEBUG", "DEBUG1",
                                        "DEBUG2", "DEBUG3", "DEBUG4"
                                      }
Definition at line 27 of file _GTestFairTools.cxx.
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedLogLevels().
const char* const VerbosityLevelArray[] = { "LOW", "MEDIUM", "HIGH"} static
Definition at line 32 of file _GTestFairTools.cxx.