FairRroot: FairRunSim Class Reference
FairRunSim Class Reference
#include <FairRunSim.h>
Public Member Functions
FairRunSim (Bool_t isMaster=kTRUE)
virtual ~FairRunSim ()
void AddModule (FairModule *Mod)
void AddNewIon (FairIon *ion)
void AddNewParticle (FairParticle *Particle)
TObjArray * GetUserDefIons ()
TObjArray * GetUserDefParticles ()
virtual void Init ()
virtual void Run (Int_t NEvents=0, Int_t NotUsed=0)
void SetField (FairField *field)
void SetGenerator (FairPrimaryGenerator *Gen)
void SetMCEventHeader (FairMCEventHeader *McHeader)
void SetMaterials (const char *MatFileName)
void SetStoreTraj (Bool_t storeTraj=kTRUE)
void SetTrackingDebugMode (Bool_t set)
void SetGeoModel (char *name)
TString * GetGeoModel ()
FairField * GetField ()
FairMCEventHeader * GetMCEventHeader ()
TObjArray * GetListOfModules ()
FairPrimaryGenerator * GetPrimaryGenerator ()
void SetPythiaDecayer (Bool_t decayer)
void SetPythiaDecayer (const TString &Config)
void SetUserDecay (const TString &Config)
void SetUserDecay (Bool_t decay)
Bool_t IsExtDecayer ()
Bool_t IsUserDecay ()
void SetRadLenRegister (Bool_t value)
void SetRadMapRegister (Bool_t value)
void SetRadGridRegister (Bool_t value)
void AddMesh (FairMesh *Mesh)
void SetUserConfig (const TString &Config)
void SetUserCuts (const TString &Cuts)
void SetBeamMom (Double_t BeamMom)
Double_t GetBeamMom ()
Bool_t UseBeamMom ()
void SetFieldContainer ()
virtual void AddTask (FairTask *t)
virtual void SetTask (FairTask *t)
void SetOutputFile (const char *fname)
void SetOutputFile (TFile *f)
void SetEventHeader (FairEventHeader *EvHeader)
FairRuntimeDb * GetRuntimeDb (void)
TFile * GetOutputFile ()
Int_t GetRunId ()
void SetRunId (UInt_t runId)
FairEventHeader * GetEventHeader ()
Bool_t IsAna ()
FairTask * GetTask (const char *taskName)
FairTask * GetMainTask ()
Int_t GetNTasks ()
void CreateGeometryFile (const char *geofile)
void SetWriteRunInfoFile (Bool_t write)
void SetGenerateRunInfo (Bool_t write)
Bool_t GetWriteRunInfoFile ()
Bool_t IsRunInfoGenerated ()
void SetUseFairLinks (Bool_t val)
Bool_t GetIsMaster () const
Static Public Member Functions
static FairRunSim * Instance ()
Protected Attributes
Int_t count
FairMCApplication * fApp
/** Internal counter*/
Double_t fBeamMom
/** Main VMC application */
Bool_t fUseBeamMom
/** Beam Energy in GeV/c */
FairPrimaryGenerator * fGen
/** flag for use Beam Energy */
FairMCEventHeader * fMCEvHead
/** Primary Event Generator */
FairField * fField
/** Singleton Instance */
const char * fMapName
TObjArray * fIons
/** Input file name map*/
TObjArray * fParticles
/** Array of user defined ions */
TObjArray * ListOfModules
/** Array of user defined particles*/
TString MatFname
/** Array of used modules */
Bool_t fStoreTraj
/** Material file name */
TString * fLoaderName
/** Trajectory store flags */
Bool_t fPythiaDecayer
/** Geometry Model (TGeo or G3)*/
TString fPythiaDecayerConfig
/** flag for using Pythia decayer*/
Bool_t fUserDecay
/** Macro for Pythia decay configuration*/
TString fUserDecayConfig
Bool_t fRadLength
/** Macro for decay configuration*/
Bool_t fRadMap
/** flag for registring radiation length*/
Bool_t fRadGrid
/** flag for RadiationMapManager
TObjArray * fMeshList
TString fUserConfig
/** radiation grid scoring
TString fUserCuts
/** Macro for geant configuration*/
FairLogger * fLogger
FairRuntimeDb * fRtdb
FairTask * fTask
const char * fOutname
FairRootManager * fRootManager
TFile * fOutFile
UInt_t fRunId
Bool_t fAna
FairEventHeader * fEvHead
FairFileHeader * fFileHeader
Bool_t fGenerateRunInfo
Bool_t fIsMaster
Static Protected Attributes
static TMCThreadLocal FairRunSim * fginstance = 0
/** MC Event Header */
static TMCThreadLocal FairRun * fRunInstance = 0
Private Member Functions
FairRunSim (const FairRunSim &M)
FairRunSim & operator= (const FairRunSim &)
void SetMCConfig ()
void CheckFlukaExec ()
Detailed Description
Configure the Simulation session
Author
M. Al-Turany D. Bertini
Version
0.1
Since
12.01.04
Definition at line 34 of file FairRunSim.h.
Constructor & Destructor Documentation
FairRunSim::FairRunSim (Bool_t isMaster = kTRUE)
default ctor
FairRunSim::~FairRunSim () virtual
default dtor
List of Modules is filled via AddModule from the macro, but it is the responsibility of FairRunSim to call the destructors of the modules-
Definition at line 88 of file FairRunSim.cxx.
References FairLogger::Debug(), fApp, fField, fGen, fIons, FairRun::fLogger, fMCEvHead, fParticles, ListOfModules, and MESSAGE_ORIGIN.
 {
   fLogger->Debug(MESSAGE_ORIGIN," Enter Destructor of FairRunSim ");
   fLogger->Debug(MESSAGE_ORIGIN," Start deleting all registered modules");
   ListOfModules->Delete();
   delete ListOfModules;
   fLogger->Debug(MESSAGE_ORIGIN," Finish deleting all registered modules");
   fIons->Delete();
   delete fIons;
   fParticles->Delete();
   delete fParticles;
   delete fApp;
   delete fField;
   delete fGen;
   delete fMCEvHead;
 }
FairRunSim::FairRunSim (const FairRunSim & M) private
Member Function Documentation
void FairRunSim::AddMesh (FairMesh * Mesh)
Definition at line 122 of file FairRunSim.cxx.
References FairMesh::calculate(), fMeshList, and FairMesh::print().
 {
   Mesh->print();
   Mesh->calculate();
   fMeshList->Add(Mesh);
 }
void FairRunSim::AddModule (FairModule * Mod)
Add a module to the simulation (e.g. PIPE, Magnet, ..etc)
Definition at line 116 of file FairRunSim.cxx.
References count, ListOfModules, and FairModule::SetModId().
 {
   ListOfModules->Add(Mod);
   Mod->SetModId(count++);
 }
void FairRunSim::AddNewIon (FairIon * ion) inline
Add a user defined ion to the simulation
Definition at line 50 of file FairRunSim.h.
References fIons.
Referenced by FairIonGenerator::FairIonGenerator(), and FairShieldGenerator::RegisterIons().
 {fIons->Add(ion);}
void FairRunSim::AddNewParticle (FairParticle * Particle) inline
Add a user defined ion to the simulation
Definition at line 54 of file FairRunSim.h.
References fParticles.
 {fParticles->Add(Particle);}
void FairRun::AddTask (FairTask * t) virtual inherited
Add a FAIRTask to the simulation or analysis
Definition at line 108 of file FairRun.cxx.
References FairFileHeader::AddTaskClassName(), FairRun::fFileHeader, FairRun::fNTasks, and FairRun::fTask.
Referenced by FairEventManager::AddTask().
 {
   fTask->Add(t);
   fNTasks++;
   fFileHeader->AddTaskClassName(t->ClassName());
 }
void FairRunSim::CheckFlukaExec () private
Private method for setting FLUKA simulation
Definition at line 242 of file FairRunSim.cxx.
References FairRun::fLogger, FairLogger::Info(), and MESSAGE_ORIGIN.
Referenced by Init().
 {
   TString work = getenv("VMCWORKDIR");
   TString work_config=work+"/gconfig/";
   TString config_dir= getenv("CONFIG_DIR");
   if (!config_dir.EndsWith("/")) { config_dir+="/"; }
   TString flout;
   if(strcmp(GetName(),"TFluka") == 0 ) {
     TString flexec="run_fluka.sh";
     if (TString(gSystem->FindFile(config_dir.Data(),flexec)) != TString("")) {
       fLogger->Info(MESSAGE_ORIGIN,"---User path for Configuration is used :  %s ", config_dir.Data());
     } else {
       flexec=work_config+"run_fluka.sh";
     }
     gSystem->Exec(flexec.Data());
     // More generic for different macro
     // dir layout <D.B>
     TString macrodir = getenv("PWD");
     cout << macrodir << endl;
     flout = macrodir + "/fluka_out" ;
     gSystem->cd(flout.Data());
   }
 }
void FairRun::CreateGeometryFile (const char * geofile) inherited
Create a new file and save the TGeoManager to it
Definition at line 122 of file FairRun.cxx.
References FairRootManager::CreateGeometryFile(), and FairRun::fRootManager.
 {
   fRootManager->CreateGeometryFile(geofile);
 }
Double_t FairRunSim::GetBeamMom () inline
Get the Beam energy
Definition at line 149 of file FairRunSim.h.
References fBeamMom.
 {return fBeamMom;}
FairEventHeader * FairRun::GetEventHeader () inherited
Get the detector specific run header
Definition at line 134 of file FairRun.cxx.
References FairRun::fEvHead.
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), and FairRunOnline::InitContainers().
 {
   if ( NULL == fEvHead ) {
     fEvHead = new FairEventHeader();
   }
   return fEvHead;
 }
FairField* FairRunSim::GetField () inline virtual
Get the field used in simulation
Implements FairRun.
Definition at line 103 of file FairRunSim.h.
References fField.
 { return fField;}
TString* FairRunSim::GetGeoModel () inline
return the geometry loader used in this session
Definition at line 100 of file FairRunSim.h.
References fLoaderName.
 { return fLoaderName; }
Bool_t FairRun::GetIsMaster () const inline inherited
Definition at line 151 of file FairRun.h.
References FairRun::fIsMaster.
 { return fIsMaster;}
TObjArray* FairRunSim::GetListOfModules () inline
return the full list of modules used in simulation
Definition at line 109 of file FairRunSim.h.
References ListOfModules.
Referenced by Init().
 { return ListOfModules;}
FairTask* FairRun::GetMainTask () inline inherited
Get Main Task
Definition at line 122 of file FairRun.h.
References FairRun::fTask.
{
       return fTask;
     }
FairMCEventHeader * FairRunSim::GetMCEventHeader ()
Get the detector specific event header
Definition at line 441 of file FairRunSim.cxx.
References fMCEvHead.
Referenced by FairMCApplication::InitGeometry().
 {
   if ( NULL == fMCEvHead ) { fMCEvHead = new FairMCEventHeader(); }
   return fMCEvHead;
 }
Int_t FairRun::GetNTasks () inline inherited
Return the number of Tasks added to this Run
Definition at line 128 of file FairRun.h.
References FairRun::fNTasks.
{
       return fNTasks;
     }
TFile* FairRun::GetOutputFile () inline inherited
return a pointer to the output file
Definition at line 88 of file FairRun.h.
References FairRun::fOutFile.
{
       return fOutFile;
     }
FairPrimaryGenerator* FairRunSim::GetPrimaryGenerator () inline
Get the used primary generator
Definition at line 112 of file FairRunSim.h.
References fGen.
Referenced by FairMCApplication::FinishRun(), and Init().
 { return fGen;}
Int_t FairRun::GetRunId () inline inherited
return the run ID for the actul run
Definition at line 94 of file FairRun.h.
References FairRun::fRunId.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairConstField::FillParContainer(), and FairMCApplication::InitGeometry().
                       {
       return ((Int_t) fRunId);
     }
FairRuntimeDb* FairRun::GetRuntimeDb (void) inline inherited
return a pointer to the RuntimeDB
Definition at line 82 of file FairRun.h.
References FairRun::fRtdb.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairPipe::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairConstField::FillParContainer(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTestDetector::Initialize(), FairTutorialDet2::Initialize(), NewDetector::Initialize(), FairRutherford::Initialize(), FairTutorialDet1::Initialize(), FairTutorialDet4::Initialize(), FairModule::ProcessNodes(), FairTutorialDet2Digitizer::ReInit(), FairTutorialDet4HitProducerIdealMisalign::ReInit(), FairDbTutAccessRtdbTask::SetParContainers(), FairTutorialDet2Digitizer::SetParContainers(), FairTutorialDet4HitProducerIdealMisalign::SetParContainers(), FairTutorialDet4::SetParContainers(), FairEventBuilderManager::SetParContainers(), MyFieldCreator::SetParm(), and FairMCApplication::SetParTask().
{
       return fRtdb;
     }
FairTask * FairRun::GetTask (const char * taskName) inherited
Get task by name
Definition at line 127 of file FairRun.cxx.
References FairRun::fTask.
 {
   TList* taskList = fTask->GetListOfTasks();
   TObject* task = taskList->FindObject(taskName);
   return dynamic_cast<FairTask*>(task);
 }
TObjArray * FairRunSim::GetUserDefIons ()
this method is used by the FAIRMCApplication
return the array of user defined ions
Definition at line 129 of file FairRunSim.cxx.
References fIons.
Referenced by FairMCApplication::AddIons(), FairMCApplication::AddParticles(), and FairIonGenerator::FairIonGenerator().
 {
   return fIons;
 }
TObjArray * FairRunSim::GetUserDefParticles ()
this method is used by the FAIRMCApplication
return the array of user defined particles
Definition at line 135 of file FairRunSim.cxx.
References fParticles.
Referenced by FairMCApplication::AddParticles(), and FairIonGenerator::FairIonGenerator().
 {
   return fParticles;
 }
Bool_t FairRun::GetWriteRunInfoFile () inherited
Definition at line 156 of file FairRun.cxx.
References FairLogger::endl(), FairRun::fGenerateRunInfo, LOG, and WARNING.
 {
   LOG(WARNING) << "Function FairRun::GetWriteRunInfoFile() is depcrecated and will vanish in future versions of FairRoot.\n";
   LOG(WARNING) << "Please use FairRun::IsRunInfoGenerated() instead." << FairLogger::endl;
   return fGenerateRunInfo;
 }
void FairRunSim::Init () virtual
Initialize the Simulation
Initialize the simulation session
Add Tasks to simulation if any
Set the configuration for MC engine
Implements FairRun.
Definition at line 141 of file FairRunSim.cxx.
References FairMCApplication::AddMeshList(), FairRuntimeDb::addRun(), FairMCApplication::AddTask(), CheckFlukaExec(), fApp, fBeamMom, fField, FairRun::fFileHeader, fGen, fLoaderName, FairRun::fLogger, fMeshList, fPythiaDecayer, fPythiaDecayerConfig, fRadGrid, fRadLength, fRadMap, FairRun::fRootManager, FairRun::fRtdb, FairRun::fRunId, fStoreTraj, FairRun::fTask, fUserDecay, fUserDecayConfig, FairRunIdGenerator::generateId(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoInterface(), FairRuntimeDb::getListOfContainers(), GetListOfModules(), FairParSet::GetName(), GetPrimaryGenerator(), FairLogger::Info(), ListOfModules, MatFname, MESSAGE_ORIGIN, FairBaseParSet::SetBeamMom(), FairParSet::setChanged(), FairBaseParSet::SetContListStr(), FairBaseParSet::SetDetList(), FairMCApplication::SetField(), SetFieldContainer(), FairBaseParSet::SetGen(), FairMCApplication::SetGenerator(), FairGeoParSet::SetGeometry(), FairParSet::setInputVersion(), SetMCConfig(), FairGeoInterface::SetNoOfSets(), FairMCApplication::SetPythiaDecayer(), FairMCApplication::SetPythiaDecayerConfig(), FairMCApplication::SetRadiationLengthReg(), FairMCApplication::SetRadiationMapReg(), FairFileHeader::SetRunId(), FairMCApplication::SetUserDecay(), FairMCApplication::SetUserDecayConfig(), and FairRootManager::WriteFileHeader().
 {
   CheckFlukaExec();
 //  fOutFile=fRootManager->OpenOutFile(fOutname);
   fLogger->Info(MESSAGE_ORIGIN,"==============  FairRunSim: Initialising simulation run ==============");
   FairGeoLoader* loader=new FairGeoLoader(fLoaderName->Data(), "Geo Loader");
   FairGeoInterface* GeoInterFace=loader->getGeoInterface();
   GeoInterFace->SetNoOfSets(ListOfModules->GetEntries());
   GeoInterFace->setMediaFile(MatFname.Data());
   GeoInterFace->readMedia();
   //  gSystem->cd(flout.Data());
   fApp= new FairMCApplication("Fair","The Fair VMC App",ListOfModules, MatFname);
   fApp->SetGenerator(fGen);
   // Add a Generated run ID to the FairRunTimeDb
   FairRunIdGenerator genid;
   // FairRuntimeDb *rtdb= GetRuntimeDb();
   fRunId = genid.generateId();
   fRtdb->addRun(fRunId);
   fFileHeader->SetRunId(fRunId);
   fApp->AddTask(fTask);
   FairBaseParSet* par=dynamic_cast<FairBaseParSet*>(fRtdb->getContainer("FairBaseParSet"));
   par->SetDetList(GetListOfModules());
   par->SetGen(GetPrimaryGenerator());
   par->SetBeamMom(fBeamMom);
   FairGeoParSet* geopar=dynamic_cast<FairGeoParSet*>(fRtdb->getContainer("FairGeoParSet"));
   geopar->SetGeometry(gGeoManager);
   // Set global Parameter Info
   if(fPythiaDecayer) {
     fApp->SetPythiaDecayer(fPythiaDecayer);
     if (fPythiaDecayerConfig) {
       fApp->SetPythiaDecayerConfig(fPythiaDecayerConfig);
     }
   }
   if(fUserDecay) {
     fApp->SetUserDecay(fUserDecay);
     if (fUserDecayConfig) {
       fApp->SetUserDecayConfig(fUserDecayConfig);
     }
   }
   // on/off visualisation
   if( fStoreTraj ) {
     fLogger->Info(MESSAGE_ORIGIN, "Create visualisation manager ");
     new FairTrajFilter();
   }
   if(fRadLength) {
     fApp->SetRadiationLengthReg(fRadLength);
   }
   if(fRadMap) {
     fApp->SetRadiationMapReg(fRadMap);
   }
   if(fRadGrid) {
     fApp->AddMeshList(fMeshList);
   }
   if(fField) { fField->Init(); }
   fApp->SetField(fField);
   SetFieldContainer();
   TList* containerList=fRtdb->getListOfContainers();
   TIter next(containerList);
   FairParSet* cont;
   TObjArray* ContList= new TObjArray();
   while ((cont=dynamic_cast<FairParSet*>(next()))) {
     ContList->Add(new TObjString(cont->GetName()));
   }
   par->SetContListStr(ContList);
   par->setChanged();
   par->setInputVersion(fRunId,1);
   geopar->setChanged();
   geopar->setInputVersion(fRunId,1);
   SetMCConfig();
   fRootManager->WriteFileHeader(fFileHeader);
 }
FairRunSim * FairRunSim::Instance () static
Singelton instance
Definition at line 111 of file FairRunSim.cxx.
References fginstance.
Referenced by FairMCApplication::AddIons(), FairMCApplication::AddParticles(), FairMCApplication::CloneForWorker(), FairIonGenerator::FairIonGenerator(), FairMCApplication::FinishRun(), FairMCApplication::InitGeometry(), FairShieldGenerator::RegisterIons(), FairMCApplication::RunMC(), and FairMCApplication::SetParTask().
 {
   return fginstance;
 }
Bool_t FairRun::IsAna () inline inherited
return true for Anaylsis session
Definition at line 111 of file FairRun.h.
References FairRun::fAna.
Referenced by FairRootManager::OpenOutFile().
{
       return fAna;
     }
Bool_t FairRunSim::IsExtDecayer () inline
Flag for external decayer
Definition at line 127 of file FairRunSim.h.
References fPythiaDecayer.
 {return fPythiaDecayer; }
Bool_t FairRun::IsRunInfoGenerated () inline inherited
Definition at line 145 of file FairRun.h.
References FairRun::fGenerateRunInfo.
 { return fGenerateRunInfo;}
Bool_t FairRunSim::IsUserDecay () inline
Flag for User decay
Definition at line 130 of file FairRunSim.h.
References fUserDecay.
 {return fUserDecay; }
FairRunSim& FairRunSim::operator= (const FairRunSim &) inline private
Definition at line 156 of file FairRunSim.h.
 {return *this;}
void FairRunSim::Run (Int_t NEvents = 0, Int_t NotUsed = 0) virtual
run the simulation
Implements FairRun.
Definition at line 383 of file FairRunSim.cxx.
References fApp, and FairMCApplication::RunMC().
 {
   fApp->RunMC(NEvents);
 }
void FairRunSim::SetBeamMom (Double_t BeamMom) inline
Set Beam energy in GeV/c
Definition at line 146 of file FairRunSim.h.
References fBeamMom, and fUseBeamMom.
 {  fBeamMom= BeamMom; fUseBeamMom=kTRUE;}
void FairRun::SetEventHeader (FairEventHeader * EvHeader) inline inherited
Set the experiment dependent run header for each run
Definition at line 76 of file FairRun.h.
References FairRun::fEvHead.
{
       fEvHead=EvHeader;
     }
void FairRunSim::SetField (FairField * field)
Set the magnetic that has to be used for simulation field
Definition at line 388 of file FairRunSim.cxx.
References fField.
 {
   fField=field;
 }
void FairRunSim::SetFieldContainer ()
Definition at line 235 of file FairRunSim.cxx.
References fField.
Referenced by Init().
 {
   if (fField) {
     fField->FillParContainer();
   }
 }
void FairRun::SetGenerateRunInfo (Bool_t write) inline inherited
Definition at line 139 of file FairRun.h.
References FairRun::fGenerateRunInfo.
 { fGenerateRunInfo = write;}
void FairRunSim::SetGenerator (FairPrimaryGenerator * Gen)
Set the event generator that has to be used for simulation field
Definition at line 393 of file FairRunSim.cxx.
References fGen.
 {
   fGen=Gen;
 }
void FairRunSim::SetGeoModel (char * name)
Set geometry builder
Definition at line 413 of file FairRunSim.cxx.
References fLoaderName, FairRun::fLogger, FairLogger::Info(), and MESSAGE_ORIGIN.
 {
   if ( strncmp(fName,"TGeant3",7) == 0 ) {
     if (fLoaderName) { delete fLoaderName; }
     fLoaderName = new TString(name);
     fLogger->Info(MESSAGE_ORIGIN,"FairRun::SetGeoModel(): G3 native geometry model used ");
   } else {
     fLogger->Info(MESSAGE_ORIGIN,"FairRun::SetGeoModel(): Geant3 MC engine only !");
     fLogger->Info(MESSAGE_ORIGIN,"FairRun::SetGeoModel(): Method skipped ... ");
   }
 }
void FairRunSim::SetMaterials (const char * MatFileName)
Set the material file name to be used
Definition at line 398 of file FairRunSim.cxx.
References FairRun::fLogger, FairLogger::Info(), MatFname, and MESSAGE_ORIGIN.
 {
   TString Mat="";
   TString work = getenv("GEOMPATH");
   if (work.IsNull()) {
     work = getenv("VMCWORKDIR");
     Mat=work+"/geometry/";
   } else {
     Mat=work;
     if (!Mat.EndsWith("/")) { Mat+="/"; }
   }
   MatFname=Mat+MatFileName;
   fLogger->Info(MESSAGE_ORIGIN,"Media file used : %s ", MatFname.Data());
 }
void FairRunSim::SetMCConfig () private
Private method for setting simulation and/or Geane configuration and cuts
Definition at line 267 of file FairRunSim.cxx.
References fApp, FairRun::fLogger, fUserConfig, fUserCuts, FairLogger::Info(), FairMCApplication::InitMC(), and MESSAGE_ORIGIN.
Referenced by Init().
 {
   TString work = getenv("VMCWORKDIR");
   TString Lib_config= getenv("GEANT4VMC_MACRO_DIR");
   TString work_config=work+"/gconfig/";
   TString config_dir= getenv("CONFIG_DIR");
   Bool_t AbsPath=kFALSE;
   if (!config_dir.EndsWith("/")) { config_dir+="/"; }
   if (!Lib_config.EndsWith("/")) { Lib_config+="/"; }
   TString LibMacro;
   TString LibFunction;
   TString ConfigMacro;
   TString cuts=fUserCuts;
   //----------------------------------------------Geant4 Config-----------------------------------------
   if(strcmp(GetName(),"TGeant4") == 0 ) {
     TString g4LibMacro="g4libs.C";
     TString g4Macro;
     if(fUserConfig.IsNull()) {
       g4Macro="g4Config.C";
       fUserConfig = g4Macro;
     } else {
       if (fUserConfig.Contains("/")) { AbsPath=kTRUE; }
       g4Macro = fUserConfig;
       fLogger->Info(MESSAGE_ORIGIN,"---------------User config is used : %s ",g4Macro.Data());
     }
     if (TString(gSystem->FindFile(config_dir.Data(),g4LibMacro)) != TString("")) { //be carfull after this call the string g4LibMacro is empty if not found!!!!
       fLogger->Info(MESSAGE_ORIGIN,"---User path for Configuration (g4libs.C) is used : %s" ,config_dir.Data());
     } else {
       g4LibMacro=Lib_config+"g4libs.C";
     }
     LibMacro=g4LibMacro;
     LibFunction="g4libs()";
     if (!AbsPath && TString(gSystem->FindFile(config_dir.Data(),g4Macro)) != TString("")) {
       fLogger->Info(MESSAGE_ORIGIN,"---User path for Configuration (g4Config.C) is used : %s" , config_dir.Data());
       ConfigMacro=g4Macro;
     } else {
       if(AbsPath) { ConfigMacro = fUserConfig; }
       else { ConfigMacro =work_config+fUserConfig; }
     }
     //----------------------------------------------Geant3 Config-----------------------------------------
   } else if(strcmp(GetName(),"TGeant3") == 0 ) {
     TString g3LibMacro="g3libs.C";
     TString g3Macro="g3Config.C";
     if(fUserConfig.IsNull()) {
       g3Macro="g3Config.C";
       fUserConfig = g3Macro;
       fLogger->Info(MESSAGE_ORIGIN,"-------------- Standard Config is called ------------------------------------");
     } else {
       if (fUserConfig.Contains("/")) { AbsPath=kTRUE; }
       g3Macro = fUserConfig;
       fLogger->Info(MESSAGE_ORIGIN,"---------------User config is used :  ", g3Macro.Data());
     }
     if (TString(gSystem->FindFile(config_dir.Data(),g3LibMacro)) != TString("")) {
       fLogger->Info(MESSAGE_ORIGIN,"---User path for Configuration (g3libs.C) is used : %s " , config_dir.Data());
     } else {
       g3LibMacro=work_config+"g3libs.C";
     }
     LibMacro=g3LibMacro;
     LibFunction="g3libs()";
     if (!AbsPath && TString(gSystem->FindFile(config_dir.Data(),g3Macro)) != TString("")) {
       fLogger->Info(MESSAGE_ORIGIN,"---User path for Configuration (g3Config.C) is used : %s", config_dir.Data());
       ConfigMacro=g3Macro;
     } else {
       if(AbsPath) { ConfigMacro = fUserConfig; }
       else { ConfigMacro =work_config+fUserConfig; }
     }
     //----------------------------------------------Fluka Config-----------------------------------------
   } else if(strcmp(GetName(),"TFluka") == 0 ) {
     TString flLibMacro="fllibs.C";
     TString flMacro="flConfig.C";
     if(fUserConfig.IsNull()) {
       flMacro="flConfig.C";
       fUserConfig=flMacro;
     } else {
       if (fUserConfig.Contains("/")) { AbsPath=kTRUE; }
       flMacro = fUserConfig;
       fLogger->Info(MESSAGE_ORIGIN,"---------------User config is used : %s " , flMacro.Data());
     }
     if (TString(gSystem->FindFile(config_dir.Data(), flLibMacro)) != TString("")) {
       fLogger->Info(MESSAGE_ORIGIN,"---User path for Configuration (fllibs.C) is used : %s", config_dir.Data());
     } else {
       flLibMacro=work_config+"fllibs.C";
     }
     LibMacro=flLibMacro;
     LibFunction="fllibs()";
     if (!AbsPath && TString(gSystem->FindFile(config_dir.Data(),flMacro)) != TString("")) {
       fLogger->Info(MESSAGE_ORIGIN, "---User path for Configuration (flConfig.C) is used : %s",  config_dir.Data());
       ConfigMacro=flMacro;
     } else {
       if(AbsPath) { ConfigMacro = fUserConfig; }
       else { ConfigMacro =work_config+fUserConfig; }
     }
   }
   //----------------------------------------------SetCuts------------------------------------------------
   if (TString(gSystem->FindFile(config_dir.Data(),cuts)) != TString("")) {
     fLogger->Info(MESSAGE_ORIGIN,"---User path for Cuts and Processes  (SetCuts.C) is used : %s", config_dir.Data());
   } else {
     cuts =work_config+ fUserCuts;
   }
   //--------------------------------------Now load the Config and Cuts------------------------------------
   gROOT->LoadMacro(LibMacro.Data());
   gROOT->ProcessLine(LibFunction.Data());
   gROOT->LoadMacro(ConfigMacro.Data());
   gROOT->ProcessLine("Config()");
   gROOT->LoadMacro(cuts);
   gROOT->ProcessLine("SetCuts()");
   fApp->InitMC(ConfigMacro.Data(), cuts.Data());
 }
void FairRunSim::SetMCEventHeader (FairMCEventHeader * McHeader) inline
Set the experiment dependent event header for each Monte Carlo Event
Definition at line 85 of file FairRunSim.h.
References fMCEvHead.
 {fMCEvHead=McHeader;}
void FairRun::SetOutputFile (const char * fname) inherited
Set the output file name for analysis or simulation
Definition at line 87 of file FairRun.cxx.
References FairRun::fOutFile, FairRun::fOutname, FairRun::fRootManager, and FairRootManager::OpenOutFile().
Referenced by FairMCApplication::CloneForWorker().
 {
   fOutname=fname;
   if (fRootManager) fOutFile = fRootManager->OpenOutFile(fOutname);
 }
void FairRun::SetOutputFile (TFile * f) inherited
Set the output file for analysis or simulation
Definition at line 96 of file FairRun.cxx.
References FairRun::fOutFile, FairRun::fOutname, FairRun::fRootManager, and FairRootManager::OpenOutFile().
 {
   if (! fRootManager) return;
   fOutname=f->GetName();
   fRootManager->OpenOutFile(f);
   fOutFile = f;
 }
void FairRunSim::SetPythiaDecayer (Bool_t decayer) inline
switch On/Off external decayer (Pythia)
Definition at line 115 of file FairRunSim.h.
References fPythiaDecayer.
 {fPythiaDecayer = decayer;}
void FairRunSim::SetPythiaDecayer (const TString & Config)
switch On external decayer (Pythia). Config macro will be used
switch On external decayer (Pythia). Config macro will be used
Definition at line 425 of file FairRunSim.cxx.
References fPythiaDecayer, and fPythiaDecayerConfig.
 {
   fPythiaDecayerConfig = Config;
   fPythiaDecayer =kTRUE;
 }
void FairRunSim::SetRadGridRegister (Bool_t value) inline
Definition at line 137 of file FairRunSim.h.
References fRadGrid.
 {fRadGrid= value;}
void FairRunSim::SetRadLenRegister (Bool_t value) inline
Switch on/off Radiation length register
Definition at line 133 of file FairRunSim.h.
References fRadLength.
 {fRadLength= value;}
void FairRunSim::SetRadMapRegister (Bool_t value) inline
Definition at line 135 of file FairRunSim.h.
References fRadMap.
 { fRadMap=value; }
void FairRun::SetRunId (UInt_t runId) inline inherited
Set the Run ID
Definition at line 101 of file FairRun.h.
References FairRun::fRunId.
         {
           fRunId = runId;
     }
void FairRunSim::SetStoreTraj (Bool_t storeTraj = kTRUE) inline
switch On/Off the track visualisation
Definition at line 91 of file FairRunSim.h.
References fStoreTraj.
 {fStoreTraj = storeTraj;}
void FairRun::SetTask (FairTask * t) virtual inherited
Definition at line 115 of file FairRun.cxx.
References FairFileHeader::AddTaskClassName(), FairRun::fFileHeader, and FairRun::fTask.
 {
   if ( fTask ) { delete fTask; }
   fTask = t;
   fFileHeader->AddTaskClassName(t->ClassName());
 }
void FairRunSim::SetTrackingDebugMode (Bool_t set) inline
switch On/Off the debug mode
Definition at line 94 of file FairRunSim.h.
References fApp, and FairMCApplication::SetTrackingDebugMode().
 { if (fApp) { fApp->SetTrackingDebugMode( set ); } }
void FairRun::SetUseFairLinks (Bool_t val) inherited
Definition at line 142 of file FairRun.cxx.
References FairRun::fRootManager, and FairRootManager::SetUseFairLinks().
 {
         fRootManager->SetUseFairLinks(val);
 }
void FairRunSim::SetUserConfig (const TString & Config) inline
Definition at line 141 of file FairRunSim.h.
References fUserConfig.
 {fUserConfig = Config;}
void FairRunSim::SetUserCuts (const TString & Cuts) inline
Definition at line 143 of file FairRunSim.h.
References fUserCuts.
 {fUserCuts= Cuts;}
void FairRunSim::SetUserDecay (const TString & Config)
switch On user defined decay, Config macro will be called
switch On user defined decay, Config macro will be called
Definition at line 434 of file FairRunSim.cxx.
References fUserDecay, and fUserDecayConfig.
 {
   fUserDecayConfig = Config;
   fUserDecay = kTRUE;
 }
void FairRunSim::SetUserDecay (Bool_t decay) inline
switch On/Off user defined decay if true gconfig/UserDecay.C macro will be called
Definition at line 124 of file FairRunSim.h.
References fUserDecay.
 {fUserDecay = decay;}
void FairRun::SetWriteRunInfoFile (Bool_t write) inherited
Definition at line 148 of file FairRun.cxx.
References FairLogger::endl(), FairRun::fGenerateRunInfo, LOG, and WARNING.
 {
   LOG(WARNING) << "Function FairRun::SetWriteRunInfoFile(Bool_t) is depcrecated and will vanish in future versions of FairRoot.\n";
   LOG(WARNING) << "Please use FairRun::SetGenerateRunInfo(Bool_t) instead." << FairLogger::endl;
   fGenerateRunInfo = write;
 }
Bool_t FairRunSim::UseBeamMom () inline
Get beam energy flag
Definition at line 152 of file FairRunSim.h.
References fUseBeamMom.
 {return fUseBeamMom;}
Member Data Documentation
Int_t FairRunSim::count protected
Definition at line 161 of file FairRunSim.h.
Referenced by AddModule().
Bool_t FairRun::fAna protected inherited
true for Anaylsis session
Definition at line 184 of file FairRun.h.
Referenced by FairRunAna::FairRunAna(), FairRunAnaProof::FairRunAnaProof(), FairRunOnline::FairRunOnline(), and FairRun::IsAna().
FairMCApplication* FairRunSim::fApp protected
/** Internal counter*/
Definition at line 162 of file FairRunSim.h.
Referenced by Init(), Run(), SetMCConfig(), SetTrackingDebugMode(), and ~FairRunSim().
Double_t FairRunSim::fBeamMom protected
/** Main VMC application */
Definition at line 163 of file FairRunSim.h.
Referenced by GetBeamMom(), Init(), and SetBeamMom().
FairEventHeader* FairRun::fEvHead protected inherited
MC Event Header
Definition at line 186 of file FairRun.h.
Referenced by FairRun::GetEventHeader(), FairRun::SetEventHeader(), and FairRun::~FairRun().
FairField* FairRunSim::fField protected
/** Singleton Instance */
Definition at line 172 of file FairRunSim.h.
Referenced by GetField(), Init(), SetField(), SetFieldContainer(), and ~FairRunSim().
FairFileHeader* FairRun::fFileHeader protected inherited
File Header
Definition at line 188 of file FairRun.h.
Referenced by FairRun::AddTask(), FairRun::FairRun(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), Init(), and FairRun::SetTask().
FairPrimaryGenerator* FairRunSim::fGen protected
/** flag for use Beam Energy */
Definition at line 165 of file FairRunSim.h.
Referenced by GetPrimaryGenerator(), Init(), SetGenerator(), and ~FairRunSim().
Bool_t FairRun::fGenerateRunInfo protected inherited
true if RunInfo file should be written
Definition at line 190 of file FairRun.h.
Referenced by FairRun::GetWriteRunInfoFile(), FairRun::IsRunInfoGenerated(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRun::SetGenerateRunInfo(), and FairRun::SetWriteRunInfoFile().
TMCThreadLocal FairRunSim * FairRunSim::fginstance = 0 static protected
/** MC Event Header */
Definition at line 168 of file FairRunSim.h.
Referenced by Instance().
TObjArray* FairRunSim::fIons protected
/** Input file name map*/
Definition at line 174 of file FairRunSim.h.
Referenced by AddNewIon(), GetUserDefIons(), and ~FairRunSim().
Bool_t FairRun::fIsMaster protected inherited
true if on master
Definition at line 192 of file FairRun.h.
Referenced by FairRun::GetIsMaster().
TString* FairRunSim::fLoaderName protected
/** Trajectory store flags */
Definition at line 179 of file FairRunSim.h.
Referenced by GetGeoModel(), Init(), and SetGeoModel().
FairLogger* FairRun::fLogger protected inherited
Fair Logger
Definition at line 164 of file FairRun.h.
Referenced by FairRunAna::AddBackgroundFile(), FairRunAna::AddFriend(), FairRunAna::AddSignalFile(), CheckFlukaExec(), FairRunAnaProof::Init(), FairRunAna::Init(), Init(), FairRunAna::RunMixed(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunWithTimeStamps(), FairRunAna::SetBackgroundFile(), FairRunOnline::SetContainerStatic(), FairRunAna::SetContainerStatic(), FairRunAna::SetGeomFile(), SetGeoModel(), SetMaterials(), SetMCConfig(), FairRunAna::SetMixAllInputs(), FairRunAna::SetSignalFile(), FairRun::~FairRun(), and ~FairRunSim().
const char* FairRunSim::fMapName protected
Magnetic Field
Definition at line 173 of file FairRunSim.h.
FairMCEventHeader* FairRunSim::fMCEvHead protected
/** Primary Event Generator */
Definition at line 166 of file FairRunSim.h.
Referenced by GetMCEventHeader(), SetMCEventHeader(), and ~FairRunSim().
TObjArray* FairRunSim::fMeshList protected
Definition at line 187 of file FairRunSim.h.
Referenced by AddMesh(), and Init().
TFile* FairRun::fOutFile protected inherited
Output file
Definition at line 180 of file FairRun.h.
Referenced by FairRun::GetOutputFile(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunOnline::Run(), and FairRun::SetOutputFile().
const char* FairRun::fOutname protected inherited
Output file name
Definition at line 176 of file FairRun.h.
Referenced by FairRun::SetOutputFile().
TObjArray* FairRunSim::fParticles protected
/** Array of user defined ions */
Definition at line 175 of file FairRunSim.h.
Referenced by AddNewParticle(), GetUserDefParticles(), and ~FairRunSim().
Bool_t FairRunSim::fPythiaDecayer protected
/** Geometry Model (TGeo or G3)*/
Definition at line 180 of file FairRunSim.h.
Referenced by Init(), IsExtDecayer(), and SetPythiaDecayer().
TString FairRunSim::fPythiaDecayerConfig protected
/** flag for using Pythia decayer*/
Definition at line 181 of file FairRunSim.h.
Referenced by Init(), and SetPythiaDecayer().
Bool_t FairRunSim::fRadGrid protected
/** flag for RadiationMapManager
Definition at line 186 of file FairRunSim.h.
Referenced by Init(), and SetRadGridRegister().
Bool_t FairRunSim::fRadLength protected
/** Macro for decay configuration*/
Definition at line 184 of file FairRunSim.h.
Referenced by Init(), and SetRadLenRegister().
Bool_t FairRunSim::fRadMap protected
/** flag for registring radiation length*/
Definition at line 185 of file FairRunSim.h.
Referenced by Init(), and SetRadMapRegister().
FairRootManager* FairRun::fRootManager protected inherited
IO manager
Definition at line 178 of file FairRun.h.
Referenced by FairRunAna::AddBackgroundFile(), FairRunAna::AddFile(), FairRunAna::AddFriend(), FairRunAna::AddSignalFile(), FairRunAna::BGWindowWidthNo(), FairRunAna::BGWindowWidthTime(), FairRunAna::CompressData(), FairRun::CreateGeometryFile(), FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairRun::FairRun(), FairRunOnline::Finish(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunOnline::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAnaProof::RunOnProof(), FairRunAna::RunTSBuffers(), FairRunAna::RunWithTimeStamps(), FairRunAna::SetBackgroundFile(), FairRunAna::SetBeamTime(), FairRunAna::SetEventMeanTime(), FairRunAna::SetEventTimeInterval(), FairRunAna::SetInputFile(), FairRunAnaProof::SetInTree(), FairRunAna::SetMixAllInputs(), FairRun::SetOutputFile(), FairRunAna::SetSignalFile(), FairRun::SetUseFairLinks(), FairRunAna::TerminateRun(), and FairRun::~FairRun().
FairRuntimeDb* FairRun::fRtdb protected inherited
RuntimeDb
Definition at line 172 of file FairRun.h.
Referenced by FairRun::GetRuntimeDb(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunOnline::Reinit(), FairRunAna::Reinit(), FairRunAnaProof::RunOnProof(), and FairRun::~FairRun().
UInt_t FairRun::fRunId protected inherited
Run Id
Definition at line 182 of file FairRun.h.
Referenced by FairRunOnline::EventLoop(), FairRunOnline::getRunId(), FairRunAna::getRunId(), FairRun::GetRunId(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), and FairRun::SetRunId().
TMCThreadLocal FairRun * FairRun::fRunInstance = 0 static protected inherited
static pointer to this run
Definition at line 167 of file FairRun.h.
Referenced by FairRun::FairRun(), and FairRun::Instance().
Bool_t FairRunSim::fStoreTraj protected
/** Material file name */
Definition at line 178 of file FairRunSim.h.
Referenced by Init(), and SetStoreTraj().
FairTask* FairRun::fTask protected inherited
Tasks used
Definition at line 174 of file FairRun.h.
Referenced by FairRun::AddTask(), FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairRunOnline::Finish(), FairRun::GetMainTask(), FairRun::GetTask(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAnaProof::RunOnProof(), FairRunAna::RunTSBuffers(), FairRun::SetTask(), FairRunAna::TerminateRun(), and FairRun::~FairRun().
Bool_t FairRunSim::fUseBeamMom protected
/** Beam Energy in GeV/c */
Definition at line 164 of file FairRunSim.h.
Referenced by SetBeamMom(), and UseBeamMom().
TString FairRunSim::fUserConfig protected
/** radiation grid scoring
Definition at line 188 of file FairRunSim.h.
Referenced by SetMCConfig(), and SetUserConfig().
TString FairRunSim::fUserCuts protected
/** Macro for geant configuration*/
Definition at line 189 of file FairRunSim.h.
Referenced by SetMCConfig(), and SetUserCuts().
Bool_t FairRunSim::fUserDecay protected
/** Macro for Pythia decay configuration*/
Definition at line 182 of file FairRunSim.h.
Referenced by Init(), IsUserDecay(), and SetUserDecay().
TString FairRunSim::fUserDecayConfig protected
flag for setting user decay
Definition at line 183 of file FairRunSim.h.
Referenced by Init(), and SetUserDecay().
TObjArray* FairRunSim::ListOfModules protected
/** Array of user defined particles*/
Definition at line 176 of file FairRunSim.h.
Referenced by AddModule(), GetListOfModules(), Init(), and ~FairRunSim().
TString FairRunSim::MatFname protected
/** Array of used modules */
Definition at line 177 of file FairRunSim.h.
Referenced by Init(), and SetMaterials().
The documentation for this class was generated from the following files:
FairRunSim.h
FairRunSim.cxx