FairRoot: FairParRootFile Class Reference
FairParRootFile Class Reference
#include <FairParRootFileIo.h>
Public Member Functions
FairParRootFile (const Text_t *fname, Option_t *option="READ", const Text_t *ftitle="", Int_t compress=1)
pointer to current run in ROOT file
FairParRootFile (TFile *f)
~FairParRootFile ()
FairRtdbRun * getRun ()
void readVersions (FairRtdbRun *)
Bool_t IsOpen ()
void cd ()
Bool_t IsWritable ()
TKey * GetKey (Text_t *t)
TList * GetListOfKeys ()
void Close ()
Public Attributes
FairRtdbRun * run
Protected Attributes
TFile * RootFile
Private Member Functions
FairParRootFile (const FairParRootFile &)
FairParRootFile & operator= (const FairParRootFile &)
Detailed Description
Definition at line 24 of file FairParRootFileIo.h.
Constructor & Destructor Documentation
FairParRootFile::FairParRootFile (const Text_t * fname, Option_t * option = "READ", const Text_t * ftitle = "", Int_t compress = 1)
pointer to current run in ROOT file
FairParRootFile::FairParRootFile (TFile * f)
Definition at line 63 of file FairParRootFileIo.cxx.
   :TNamed(f->GetName(), f->GetTitle()),
    run(NULL),
    RootFile(f)
 {
 //  :TFile(f->GetName(),"UPDATE"){
   // constructor opens a ROOT file
   //RootFile=new TFile(f->GetName(),"UPDATE");
   //  RootFile=f;
   //  run=0;
 }
FairParRootFile::~FairParRootFile ()
Definition at line 77 of file FairParRootFileIo.cxx.
References run.
 {
   // destructor
   if (run) {
     delete run;
   }
   run=0;
   //TODO: What about the file? Should it be closed or not
 }
FairParRootFile::FairParRootFile (const FairParRootFile &) private
Member Function Documentation
void FairParRootFile::cd () inline
Definition at line 36 of file FairParRootFileIo.h.
References RootFile.
Referenced by FairParRootFileIo::cd(), FairDetParRootFileIo::findContainer(), and FairDetParRootFileIo::write().
 {RootFile->cd();}
void FairParRootFile::Close () inline
Definition at line 41 of file FairParRootFileIo.h.
References RootFile.
Referenced by FairParRootFileIo::close().
 {RootFile->Close();}
TKey* FairParRootFile::GetKey (Text_t * t) inline
Definition at line 39 of file FairParRootFileIo.h.
References RootFile.
Referenced by FairDetParRootFileIo::getMaxVersion().
 { return RootFile->GetKey(t);}
TList* FairParRootFile::GetListOfKeys () inline
Definition at line 40 of file FairParRootFileIo.h.
References RootFile.
Referenced by FairParRootFileIo::getKeys().
 { return RootFile->GetListOfKeys();}
FairRtdbRun* FairParRootFile::getRun () inline
Definition at line 32 of file FairParRootFileIo.h.
References run.
Referenced by FairDetParRootFileIo::findInputVersion().
 {return run;}
Bool_t FairParRootFile::IsOpen () inline
Definition at line 35 of file FairParRootFileIo.h.
References RootFile.
Referenced by FairParRootFileIo::check(), and FairParRootFileIo::open().
 {return RootFile->IsOpen();}
Bool_t FairParRootFile::IsWritable () inline
Definition at line 37 of file FairParRootFileIo.h.
References RootFile.
Referenced by FairDetParRootFileIo::write().
 {return RootFile->IsWritable();}
FairParRootFile& FairParRootFile::operator= (const FairParRootFile &) private
void FairParRootFile::readVersions (FairRtdbRun * currentRun)
Definition at line 89 of file FairParRootFileIo.cxx.
References RootFile, and run.
Referenced by FairParRootFileIo::readVersions().
 {
   // finds the current run containing the parameter container versions
   // in the ROOT file
   if (run) {
     delete run;
   }
   run=(FairRtdbRun*)RootFile->Get(((char*)currentRun->GetName()));
   //cout << "-I- FairParRootFile :: readversions " << currentRun->GetName() << " : " << run << endl;
 }
Member Data Documentation
TFile* FairParRootFile::RootFile protected
Definition at line 44 of file FairParRootFileIo.h.
Referenced by cd(), Close(), GetKey(), GetListOfKeys(), IsOpen(), IsWritable(), and readVersions().
FairRtdbRun* FairParRootFile::run
Definition at line 27 of file FairParRootFileIo.h.
Referenced by getRun(), readVersions(), and ~FairParRootFile().
The documentation for this class was generated from the following files:
FairParRootFileIo.h
FairParRootFileIo.cxx