FairRoot: FairMultiLinkedData_Interface Class Reference
FairMultiLinkedData_Interface Class Reference
#include <FairMultiLinkedData_Interface.h>
Public Member Functions
FairMultiLinkedData_Interface ()
Default constructor.
FairMultiLinkedData_Interface (FairMultiLinkedData &links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData_Interface (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData_Interface (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData_Interface (const FairMultiLinkedData_Interface &toCopy)
virtual ~FairMultiLinkedData_Interface ()
FairMultiLinkedData_Interface & operator= (const FairMultiLinkedData_Interface &rhs)
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
virtual FairLink GetEntryNr () const
virtual FairMultiLinkedData * GetPointerToLinks () const
virtual void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link)
Sets the Links with a single FairLink.
virtual void SetInsertHistory (Bool_t val)
virtual void SetEntryNr (FairLink val)
virtual void SetPointerToLinks (FairMultiLinkedData *links)
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
virtual void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
virtual void AddInterfaceData (FairMultiLinkedData_Interface *data)
virtual void ResetLinks ()
std::ostream & Print (std::ostream &out=std::cout) const
Output.
Protected Member Functions
FairMultiLinkedData * CreateFairMultiLinkedData ()
ClassDef (FairMultiLinkedData_Interface, 5)
Protected Attributes
Int_t fVerbose
FairMultiLinkedData * fLink
Friends
std::ostream & operator<< (std::ostream &out, FairMultiLinkedData_Interface &data)
Output.
Detailed Description
FairMultiLinkedData_Interface.h
Date
Dec 7, 2009
Author
T.Stockmanns t.sto.nosp@m.ckma.nosp@m.nns@f.nosp@m.z-ju.nosp@m.elich.nosp@m..de
Definition at line 27 of file FairMultiLinkedData_Interface.h.
Constructor & Destructor Documentation
FairMultiLinkedData_Interface::FairMultiLinkedData_Interface ()
Default constructor.
Definition at line 19 of file FairMultiLinkedData_Interface.cxx.
   :TObject(), fLink(0), fVerbose(0)
 {
 }
FairMultiLinkedData_Interface::FairMultiLinkedData_Interface (FairMultiLinkedData & links, Bool_t persistanceCheck = kTRUE)
Constructor.
Definition at line 24 of file FairMultiLinkedData_Interface.cxx.
References SetLinks().
   :TObject(), fLink(0), fVerbose(0)
 {
         SetLinks(links);
 }
FairMultiLinkedData_Interface::FairMultiLinkedData_Interface (TString dataType, std::vector< Int_t > links, Int_t fileId = -1, Int_t evtId = -1, Bool_t persistanceCheck = kTRUE, Bool_t bypass = kFALSE, Float_t mult = 1.0)
Constructor.
Definition at line 30 of file FairMultiLinkedData_Interface.cxx.
References SetLinks().
   :TObject(), fLink(0), fVerbose(0)
 {
         FairMultiLinkedData data(dataType, links, fileId, evtId, persistanceCheck, bypass, mult);
         SetLinks(data);
 }
FairMultiLinkedData_Interface::FairMultiLinkedData_Interface (Int_t dataType, std::vector< Int_t > links, Int_t fileId = -1, Int_t evtId = -1, Bool_t persistanceCheck = kTRUE, Bool_t bypass = kFALSE, Float_t mult = 1.0)
Constructor.
Definition at line 37 of file FairMultiLinkedData_Interface.cxx.
References SetLinks().
   :TObject(), fLink(0), fVerbose(0)
 {
         FairMultiLinkedData data(dataType, links, fileId, evtId, persistanceCheck, bypass, mult);
         SetLinks(data);
 }
FairMultiLinkedData_Interface::FairMultiLinkedData_Interface (const FairMultiLinkedData_Interface & toCopy)
Definition at line 44 of file FairMultiLinkedData_Interface.cxx.
References GetEntryNr(), GetPointerToLinks(), SetEntryNr(), and SetLinks().
   :TObject(), fLink(0), fVerbose(0)
 {
         if (toCopy.GetPointerToLinks() != 0){
                 SetLinks(*(toCopy.GetPointerToLinks()));
         SetEntryNr(toCopy.GetEntryNr());
     }
 }
virtual FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface () inline virtual
Definition at line 36 of file FairMultiLinkedData_Interface.h.
References fLink.
{
         delete(fLink);
     };
Member Function Documentation
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) virtual
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References AddLink(), AddLinks(), GetEntryNr(), GetPointerToLinks(), FairLink::GetType(), and SetInsertHistory().
 {
         SetInsertHistory(kFALSE); //todo add previous history value
         if (data->GetEntryNr().GetType() != -1)
                 AddLink(data->GetEntryNr());
         else
                 std::cout
                                 << "-E- FairMultiLinkedData_Interface::AddInterfaceData EntryNr == "
                                 << data->GetEntryNr() << std::endl;
         if (data->GetPointerToLinks() != 0) {
                 AddLinks(*data->GetPointerToLinks());
         }
         SetInsertHistory(kTRUE);
 }
void FairMultiLinkedData_Interface::AddLink (FairLink link) virtual
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 154 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), CreateFairMultiLinkedData(), and GetPointerToLinks().
Referenced by AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLink(link);
         }
 }
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 146 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), CreateFairMultiLinkedData(), and GetPointerToLinks().
Referenced by AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLinks(links, mult);
         }
 }
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected
Definition at line 62 of file FairMultiLinkedData_Interface.cxx.
References fLink, and FairRootManager::Instance().
Referenced by AddLink(), AddLinks(), SetEntryNr(), SetLink(), and SetLinks().
 {
         if (FairRootManager::Instance()->GetUseFairLinks()){
                 if (fLink == 0){
                         fLink = new FairMultiLinkedData();
                 }
                 return fLink;
         }
         return 0;
 }
FairLink FairMultiLinkedData_Interface::GetEntryNr () const virtual
Reimplemented in FairTimeStamp.
Definition at line 102 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetEntryNr(), and GetPointerToLinks().
Referenced by AddInterfaceData(), FairMultiLinkedData_Interface(), and operator=().
 {
         if (GetPointerToLinks() != 0) {
                 return GetPointerToLinks()->GetEntryNr();
         } else {
                 FairLink emptyLink;
                 return emptyLink;
         }
 }
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const virtual
returns the FairLink at the given position
Definition at line 92 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLink(pos);
         } else {
                 FairLink emptyLink;
                 return emptyLink;
         }
 }
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const virtual
returns stored links as FairLinks
Definition at line 73 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinks();
         } else {
                 std::set<FairLink> emptySet;
                 return emptySet;
         }
 }
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const virtual
returns all FairLinks with the corresponding type
Definition at line 112 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinksWithType(type);
         } else {
                 FairMultiLinkedData emptyLinks;
                 return emptyLinks;
         }
 }
Int_t FairMultiLinkedData_Interface::GetNLinks () const virtual
returns the number of stored links
Definition at line 83 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetNLinks();
         } else {
                 return 0;
         }
 }
virtual FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline virtual
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References fLink.
Referenced by AddInterfaceData(), AddLink(), AddLinks(), FairMultiLinkedData_Interface(), GetEntryNr(), GetLink(), GetLinks(), GetLinksWithType(), GetNLinks(), operator=(), Print(), ResetLinks(), SetEntryNr(), SetInsertHistory(), SetLink(), and SetLinks().
 {       return fLink;}
FairMultiLinkedData_Interface & FairMultiLinkedData_Interface::operator= (const FairMultiLinkedData_Interface & rhs)
Definition at line 53 of file FairMultiLinkedData_Interface.cxx.
References GetEntryNr(), GetPointerToLinks(), SetEntryNr(), and SetLinks().
 {
         if (rhs.GetPointerToLinks() != 0){
                 SetLinks(*(rhs.GetPointerToLinks()));
         SetEntryNr(rhs.GetEntryNr());
     }
     return *this;
 }
std::ostream& FairMultiLinkedData_Interface::Print (std::ostream & out = std::cout) const inline
Output.
Definition at line 64 of file FairMultiLinkedData_Interface.h.
References GetPointerToLinks(), and FairMultiLinkedData::Print().
Referenced by FairTimeStamp::Print().
void FairMultiLinkedData_Interface::ResetLinks () virtual
Definition at line 185 of file FairMultiLinkedData_Interface.cxx.
References GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
 {
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->ResetLinks();
         }
 }
void FairMultiLinkedData_Interface::SetEntryNr (FairLink val) virtual
Reimplemented in FairTimeStamp.
Definition at line 138 of file FairMultiLinkedData_Interface.cxx.
References CreateFairMultiLinkedData(), GetPointerToLinks(), and FairMultiLinkedData::SetEntryNr().
Referenced by FairMultiLinkedData_Interface(), and operator=().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0) {
                 GetPointerToLinks()->SetEntryNr(val);
         }
 }
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) virtual
Definition at line 178 of file FairMultiLinkedData_Interface.cxx.
References GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by AddInterfaceData().
 {
         if (GetPointerToLinks() != 0) {
                 GetPointerToLinks()->SetInsertHistory(val);
         }
 }
void FairMultiLinkedData_Interface::SetLink (FairLink link) virtual
Sets the Links with a single FairLink.
Definition at line 130 of file FairMultiLinkedData_Interface.cxx.
References CreateFairMultiLinkedData(), GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetectorTimeRecoTask::Exec(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLink(link);
         }
 }
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) virtual
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 122 of file FairMultiLinkedData_Interface.cxx.
References CreateFairMultiLinkedData(), GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface(), and operator=().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLinks(links);
         }
 }
virtual void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline virtual
Definition at line 53 of file FairMultiLinkedData_Interface.h.
References fLink.
 {fLink = links;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, FairMultiLinkedData_Interface & data) friend
Output.
Definition at line 71 of file FairMultiLinkedData_Interface.h.
Member Data Documentation
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by CreateFairMultiLinkedData(), GetPointerToLinks(), SetPointerToLinks(), and ~FairMultiLinkedData_Interface().
Int_t FairMultiLinkedData_Interface::fVerbose protected
Definition at line 78 of file FairMultiLinkedData_Interface.h.
The documentation for this class was generated from the following files:
FairMultiLinkedData_Interface.h
FairMultiLinkedData_Interface.cxx