FairRroot: FairMQSocketZMQ Class Reference
FairMQSocketZMQ Class Reference
#include <FairMQSocketZMQ.h>
Public Member Functions
FairMQSocketZMQ (const string &type, int num, int numIoThreads)
virtual string GetId ()
virtual void Bind (const string &address)
virtual void Connect (const string &address)
virtual int Send (FairMQMessage *msg, const string &flag="")
virtual int Receive (FairMQMessage *msg, const string &flag="")
virtual void * GetSocket ()
virtual int GetSocket (int nothing)
virtual void Close ()
virtual void Terminate ()
virtual void SetOption (const string &option, const void *value, size_t valueSize)
virtual void GetOption (const string &option, void *value, size_t *valueSize)
virtual unsigned long GetBytesTx ()
virtual unsigned long GetBytesRx ()
virtual unsigned long GetMessagesTx ()
virtual unsigned long GetMessagesRx ()
virtual ~FairMQSocketZMQ ()
Static Public Member Functions
static int GetConstant (const string &constant)
Private Attributes
void * fSocket
string fId
unsigned long fBytesTx
unsigned long fBytesRx
unsigned long fMessagesTx
unsigned long fMessagesRx
Static Private Attributes
static boost::shared_ptr
< FairMQContextZMQ > fContext = boost::shared_ptr<FairMQContextZMQ>(new FairMQContextZMQ(1))
Detailed Description
FairMQSocketZMQ.h
Since
2012-12-05
Author
D. Klein, A. Rybalchenko
Definition at line 25 of file FairMQSocketZMQ.h.
Constructor & Destructor Documentation
FairMQSocketZMQ::FairMQSocketZMQ (const string & type, int num, int numIoThreads)
Definition at line 22 of file FairMQSocketZMQ.cxx.
References ERROR, fContext, fId, fSocket, GetConstant(), INFO, and LOG.
     : fBytesTx(0)
     , fBytesRx(0)
     , fMessagesTx(0)
     , fMessagesRx(0)
 {
     stringstream id;
     id << type << "." << num;
     fId = id.str();
     int rc = zmq_ctx_set(fContext->GetContext(), ZMQ_IO_THREADS, numIoThreads);
     if (rc != 0)
     {
         LOG(ERROR) << "failed configuring context, reason: " << zmq_strerror(errno);
     }
     fSocket = zmq_socket(fContext->GetContext(), GetConstant(type));
     rc = zmq_setsockopt(fSocket, ZMQ_IDENTITY, &fId, fId.length());
     if (rc != 0)
     {
         LOG(ERROR) << "failed setting ZMQ_IDENTITY socket option, reason: " << zmq_strerror(errno);
     }
     // Tell socket to try and send/receive outstanding messages for <linger> milliseconds before terminating.
     // Default value for ZeroMQ is -1, which is to wait forever.
     int linger = 500;
     rc = zmq_setsockopt(fSocket, ZMQ_LINGER, &linger, sizeof(linger));
     if (rc != 0)
     {
         LOG(ERROR) << "failed setting ZMQ_LINGER socket option, reason: " << zmq_strerror(errno);
     }
     if (type == "sub")
     {
         rc = zmq_setsockopt(fSocket, ZMQ_SUBSCRIBE, NULL, 0);
         if (rc != 0)
         {
             LOG(ERROR) << "failed setting ZMQ_SUBSCRIBE socket option, reason: " << zmq_strerror(errno);
         }
     }
     LOG(INFO) << "created socket #" << fId;
 }
FairMQSocketZMQ::~FairMQSocketZMQ () virtual
Definition at line 255 of file FairMQSocketZMQ.cxx.
 {
 }
Member Function Documentation
void FairMQSocketZMQ::Bind (const string & address) virtual
Implements FairMQSocket.
Definition at line 72 of file FairMQSocketZMQ.cxx.
References ERROR, fId, fSocket, INFO, and LOG.
 {
     LOG(INFO) << "bind socket #" << fId << " on " << address;
     int rc = zmq_bind(fSocket, address.c_str());
     if (rc != 0)
     {
         LOG(ERROR) << "failed binding socket #" << fId << ", reason: " << zmq_strerror(errno);
     }
 }
void FairMQSocketZMQ::Close () virtual
Implements FairMQSocket.
Definition at line 138 of file FairMQSocketZMQ.cxx.
References ERROR, fSocket, and LOG.
 {
     if (fSocket == NULL)
     {
         return;
     }
     int rc = zmq_close(fSocket);
     if (rc != 0)
     {
         LOG(ERROR) << "failed closing socket, reason: " << zmq_strerror(errno);
     }
     fSocket = NULL;
 }
void FairMQSocketZMQ::Connect (const string & address) virtual
Implements FairMQSocket.
Definition at line 83 of file FairMQSocketZMQ.cxx.
References ERROR, fId, fSocket, INFO, and LOG.
 {
     LOG(INFO) << "connect socket #" << fId << " on " << address;
     int rc = zmq_connect(fSocket, address.c_str());
     if (rc != 0)
     {
         LOG(ERROR) << "failed connecting socket #" << fId << ", reason: " << zmq_strerror(errno);
     }
 }
unsigned long FairMQSocketZMQ::GetBytesRx () virtual
Implements FairMQSocket.
Definition at line 196 of file FairMQSocketZMQ.cxx.
References fBytesRx.
 {
     return fBytesRx;
 }
unsigned long FairMQSocketZMQ::GetBytesTx () virtual
Implements FairMQSocket.
Definition at line 191 of file FairMQSocketZMQ.cxx.
References fBytesTx.
 {
     return fBytesTx;
 }
int FairMQSocketZMQ::GetConstant (const string & constant) static
Definition at line 211 of file FairMQSocketZMQ.cxx.
Referenced by FairMQSocketZMQ(), GetOption(), Receive(), Send(), and SetOption().
 {
     if (constant == "")
         return 0;
     if (constant == "sub")
         return ZMQ_SUB;
     if (constant == "pub")
         return ZMQ_PUB;
     if (constant == "xsub")
         return ZMQ_XSUB;
     if (constant == "xpub")
         return ZMQ_XPUB;
     if (constant == "push")
         return ZMQ_PUSH;
     if (constant == "pull")
         return ZMQ_PULL;
     if (constant == "req")
         return ZMQ_REQ;
     if (constant == "rep")
         return ZMQ_REP;
     if (constant == "dealer")
         return ZMQ_DEALER;
     if (constant == "router")
         return ZMQ_ROUTER;
     if (constant == "pair")
         return ZMQ_PAIR;
     if (constant == "snd-hwm")
         return ZMQ_SNDHWM;
     if (constant == "rcv-hwm")
         return ZMQ_RCVHWM;
     if (constant == "snd-more")
         return ZMQ_SNDMORE;
     if (constant == "rcv-more")
         return ZMQ_RCVMORE;
     if (constant == "linger")
         return ZMQ_LINGER;
     if (constant == "no-block")
         return ZMQ_DONTWAIT;
     return -1;
 }
string FairMQSocketZMQ::GetId () virtual
Implements FairMQSocket.
Definition at line 67 of file FairMQSocketZMQ.cxx.
References fId.
 {
     return fId;
 }
unsigned long FairMQSocketZMQ::GetMessagesRx () virtual
Implements FairMQSocket.
Definition at line 206 of file FairMQSocketZMQ.cxx.
References fMessagesRx.
 {
     return fMessagesRx;
 }
unsigned long FairMQSocketZMQ::GetMessagesTx () virtual
Implements FairMQSocket.
Definition at line 201 of file FairMQSocketZMQ.cxx.
References fMessagesTx.
 {
     return fMessagesTx;
 }
void FairMQSocketZMQ::GetOption (const string & option, void * value, size_t * valueSize) virtual
Implements FairMQSocket.
Definition at line 183 of file FairMQSocketZMQ.cxx.
References ERROR, fSocket, GetConstant(), and LOG.
 {
     int rc = zmq_getsockopt(fSocket, GetConstant(option), value, valueSize);
     if (rc < 0) {
         LOG(ERROR) << "failed getting socket option, reason: " << zmq_strerror(errno);
     }
 }
void * FairMQSocketZMQ::GetSocket () virtual
Implements FairMQSocket.
Definition at line 163 of file FairMQSocketZMQ.cxx.
References fSocket.
 {
     return fSocket;
 }
int FairMQSocketZMQ::GetSocket (int nothing) virtual
Implements FairMQSocket.
Definition at line 168 of file FairMQSocketZMQ.cxx.
 {
     // dummy method to comply with the interface. functionality not possible in zeromq.
     return -1;
 }
int FairMQSocketZMQ::Receive (FairMQMessage * msg, const string & flag = "") virtual
Implements FairMQSocket.
Definition at line 116 of file FairMQSocketZMQ.cxx.
References ERROR, fBytesRx, fId, fMessagesRx, fSocket, GetConstant(), FairMQMessage::GetMessage(), INFO, and LOG.
 {
     int nbytes = zmq_msg_recv(static_cast<zmq_msg_t*>(msg->GetMessage()), fSocket, GetConstant(flag));
     if (nbytes >= 0)
     {
         fBytesRx += nbytes;
         ++fMessagesRx;
         return nbytes;
     }
     if (zmq_errno() == EAGAIN)
     {
         return 0;
     }
     if (zmq_errno() == ETERM)
     {
         LOG(INFO) << "terminating socket #" << fId;
         return -1;
     }
     LOG(ERROR) << "failed receiving on socket #" << fId << ", reason: " << zmq_strerror(errno);
     return nbytes;
 }
int FairMQSocketZMQ::Send (FairMQMessage * msg, const string & flag = "") virtual
Implements FairMQSocket.
Definition at line 94 of file FairMQSocketZMQ.cxx.
References ERROR, fBytesTx, fId, fMessagesTx, fSocket, GetConstant(), FairMQMessage::GetMessage(), INFO, and LOG.
 {
     int nbytes = zmq_msg_send(static_cast<zmq_msg_t*>(msg->GetMessage()), fSocket, GetConstant(flag));
     if (nbytes >= 0)
     {
         fBytesTx += nbytes;
         ++fMessagesTx;
         return nbytes;
     }
     if (zmq_errno() == EAGAIN)
     {
         return 0;
     }
     if (zmq_errno() == ETERM)
     {
         LOG(INFO) << "terminating socket #" << fId;
         return -1;
     }
     LOG(ERROR) << "failed sending on socket #" << fId << ", reason: " << zmq_strerror(errno);
     return nbytes;
 }
void FairMQSocketZMQ::SetOption (const string & option, const void * value, size_t valueSize) virtual
Implements FairMQSocket.
Definition at line 174 of file FairMQSocketZMQ.cxx.
References ERROR, fSocket, GetConstant(), and LOG.
 {
     int rc = zmq_setsockopt(fSocket, GetConstant(option), value, valueSize);
     if (rc < 0)
     {
         LOG(ERROR) << "failed setting socket option, reason: " << zmq_strerror(errno);
     }
 }
void FairMQSocketZMQ::Terminate () virtual
Implements FairMQSocket.
Definition at line 154 of file FairMQSocketZMQ.cxx.
References ERROR, fContext, and LOG.
 {
     int rc = zmq_ctx_destroy(fContext->GetContext());
     if (rc != 0)
     {
         LOG(ERROR) << "failed terminating context, reason: " << zmq_strerror(errno);
     }
 }
Member Data Documentation
unsigned long FairMQSocketZMQ::fBytesRx private
Definition at line 59 of file FairMQSocketZMQ.h.
Referenced by GetBytesRx(), and Receive().
unsigned long FairMQSocketZMQ::fBytesTx private
Definition at line 58 of file FairMQSocketZMQ.h.
Referenced by GetBytesTx(), and Send().
boost::shared_ptr< FairMQContextZMQ > FairMQSocketZMQ::fContext = boost::shared_ptr<FairMQContextZMQ>(new FairMQContextZMQ(1)) static private
FairMQSocketZMQ.cxx
Since
2012-12-05
Author
D. Klein, A. Rybalchenko
Definition at line 63 of file FairMQSocketZMQ.h.
Referenced by FairMQSocketZMQ(), and Terminate().
string FairMQSocketZMQ::fId private
Definition at line 57 of file FairMQSocketZMQ.h.
Referenced by Bind(), Connect(), FairMQSocketZMQ(), GetId(), Receive(), and Send().
unsigned long FairMQSocketZMQ::fMessagesRx private
Definition at line 61 of file FairMQSocketZMQ.h.
Referenced by GetMessagesRx(), and Receive().
unsigned long FairMQSocketZMQ::fMessagesTx private
Definition at line 60 of file FairMQSocketZMQ.h.
Referenced by GetMessagesTx(), and Send().
void* FairMQSocketZMQ::fSocket private
Definition at line 56 of file FairMQSocketZMQ.h.
Referenced by Bind(), Close(), Connect(), FairMQSocketZMQ(), GetOption(), GetSocket(), Receive(), Send(), and SetOption().
The documentation for this class was generated from the following files:
FairMQSocketZMQ.h
FairMQSocketZMQ.cxx