FairRoot: FairTrackParam Class Reference
FairTrackParam Class Reference
#include <FairTrackParam.h>
Public Member Functions
FairTrackParam ()
FairTrackParam (Double_t x, Double_t y, Double_t z, Double_t tx, Double_t ty, Double_t qp, const TMatrixFSym &covMat)
FairTrackParam (const FairTrackParam &param)
virtual ~FairTrackParam ()
void Print (Option_t *option="") const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
Double_t GetTx () const
Double_t GetTy () const
Double_t GetQp () const
void Position (TVector3 &pos) const
void Momentum (TVector3 &mom) const
void CovMatrix (Double_t cov[]) const
void CovMatrix (TMatrixFSym &covMat) const
Double_t GetCovariance (Int_t i, Int_t j) const
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetTx (Double_t tx)
void SetTy (Double_t ty)
void SetQp (Double_t qp)
void SetPosition (const TVector3 &pos)
void SetCovMatrix (Double_t cov[])
void SetCovMatrix (const TMatrixFSym &covMat)
void SetCovariance (Int_t i, Int_t j, Double_t val)
FairTrackParam & operator= (const FairTrackParam &par)
Private Member Functions
ClassDef (FairTrackParam, 1)
Private Attributes
Double32_t fX
Double32_t fY
Double32_t fZ
Double32_t fTx
Double32_t fTy
Double32_t fQp
Double32_t fCovMatrix [15]
Detailed Description
FairTrackParam.h
Author
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e
Parameters (x, y, tx, ty, q/p) of a track resulting from the track fit. The z coordinate is not a parameter. The 5x5 covariance matrix can be set and accessed by either an array of size 15, the TMatrixFSym class or elementwise. Note that TMatrixFSym should not be used when performance is an issue. The internal representation of the covariance matrix elements is an array of double.
Definition at line 36 of file FairTrackParam.h.
Constructor & Destructor Documentation
FairTrackParam::FairTrackParam ()
Constructor
Definition at line 26 of file FairTrackParam.cxx.
References fCovMatrix.
   : TObject(),
     fX(0),
     fY(0),
     fZ(0),
     fTx(0),
     fTy(0),
     fQp(0)
 {
   //  fX = fY = fZ = fTx = fTy = fQp = 0.;
   for (int i=0; i<15; i++) { fCovMatrix[i] = 0; }
 }
FairTrackParam::FairTrackParam (Double_t x, Double_t y, Double_t z, Double_t tx, Double_t ty, Double_t qp, const TMatrixFSym & covMat)
Constructor with all variables
Definition at line 43 of file FairTrackParam.cxx.
References fCovMatrix.
   : TObject(),
     fX(x),
     fY(y),
     fZ(z),
     fTx(tx),
     fTy(ty),
     fQp(qp)
 {
   int index = 0;
   for (int i=0; i<5; i++) {
     for (int j=i; j<5; j++) { fCovMatrix[index++] = covMat[i][j]; }
   }
 }
FairTrackParam::FairTrackParam (const FairTrackParam & param)
Copy constructor
Definition at line 61 of file FairTrackParam.cxx.
   : TObject(param),
     fX(param.GetX()),
     fY(param.GetY()),
     fZ(param.GetZ()),
     fTx(param.GetTx()),
     fTy(param.GetTy()),
     fQp(param.GetQp())
 {
   *this = param;
 }
FairTrackParam::~FairTrackParam () virtual
Destructor
Definition at line 74 of file FairTrackParam.cxx.
 {}
Member Function Documentation
FairTrackParam::ClassDef (FairTrackParam , 1) private
void FairTrackParam::CovMatrix (Double_t cov[]) const
Definition at line 108 of file FairTrackParam.cxx.
References fCovMatrix.
Referenced by operator=().
 {
   for (Int_t i=0; i<15; i++) { cov[i] = fCovMatrix[i]; }
 }
void FairTrackParam::CovMatrix (TMatrixFSym & covMat) const
Definition at line 117 of file FairTrackParam.cxx.
References fCovMatrix.
 {
   Int_t index = 0;
   for (int i=0; i<5; i++) {
     for (int j=i; j<5; j++) {
       covMat[i][j] = fCovMatrix[index];
       covMat[j][i] = fCovMatrix[index];
       index++;
     }
   }
 }
Double_t FairTrackParam::GetCovariance (Int_t i, Int_t j) const
Definition at line 133 of file FairTrackParam.cxx.
References FairLogger::endl(), ERROR, fCovMatrix, and LOG.
 {
   if ( i<0 || j<0 || i>4 || j>4 ) {
     LOG(ERROR) << "FairTrackParam::GetCovariance: Invalid index pair ("
                << i << "," << j << ") !" << FairLogger::endl;
     return 0;
   }
   if (i>j) {
     Int_t k = i;
     i = j;
     j = k;
   }
   Int_t index = 0;
   if (i==0) { index = j; }
   else if (i==1) { index =  4 + j; }
   else if (i==2) { index =  7 + j; }
   else if (i==3) { index =  9 + j; }
   else if (i==4) { index = 10 + j; }
   return fCovMatrix[index];
 }
Double_t FairTrackParam::GetQp () const inline
Definition at line 68 of file FairTrackParam.h.
References fQp.
Referenced by operator=().
 { return fQp; };
Double_t FairTrackParam::GetTx () const inline
Definition at line 66 of file FairTrackParam.h.
References fTx.
Referenced by operator=(), FairTutorialDet4MilleWriter::StraightLineShiftX(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
 { return fTx; };
Double_t FairTrackParam::GetTy () const inline
Definition at line 67 of file FairTrackParam.h.
References fTy.
Referenced by operator=(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
 { return fTy; };
Double_t FairTrackParam::GetX () const inline
Accessors
Definition at line 63 of file FairTrackParam.h.
References fX.
Referenced by operator=(), FairTutorialDet4MilleWriter::StraightLineShiftX(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
 { return fX; };
Double_t FairTrackParam::GetY () const inline
Definition at line 64 of file FairTrackParam.h.
References fY.
Referenced by operator=(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
 { return fY; };
Double_t FairTrackParam::GetZ () const inline
Definition at line 65 of file FairTrackParam.h.
References fZ.
Referenced by operator=().
 { return fZ; };
void FairTrackParam::Momentum (TVector3 & mom) const
Definition at line 94 of file FairTrackParam.cxx.
References fQp, fTx, and fTy.
 {
   Double_t p  = ( TMath::Abs(fQp)>1.e-4 ) ?1./TMath::Abs(fQp) :1.e4;
   Double_t pz = TMath::Sqrt( p*p / ( fTx*fTx + fTy*fTy + 1 ) );
   Double_t px = fTx * pz;
   Double_t py = fTy * pz;
   mom.SetXYZ(px, py, pz);
 }
FairTrackParam & FairTrackParam::operator= (const FairTrackParam & par)
Assignment operator
Definition at line 221 of file FairTrackParam.cxx.
References CovMatrix(), fQp, fTx, fTy, fX, fY, fZ, GetQp(), GetTx(), GetTy(), GetX(), GetY(), GetZ(), and SetCovMatrix().
 {
   fX  = par.GetX();
   fY  = par.GetY();
   fZ  = par.GetZ();
   fTx = par.GetTx();
   fTy = par.GetTy();
   fQp = par.GetQp();
   Double_t cov[15];
   par.CovMatrix(cov);
   SetCovMatrix(cov);
   return *this;
 }
void FairTrackParam::Position (TVector3 & pos) const inline
Definition at line 69 of file FairTrackParam.h.
References fX, fY, and fZ.
 { pos.SetXYZ(fX, fY, fZ); };
void FairTrackParam::Print (Option_t * option = "") const
Output to screen
Definition at line 80 of file FairTrackParam.cxx.
References FairLogger::endl(), fQp, fTx, fTy, fX, fY, fZ, INFO, and LOG.
 {
   LOG(INFO) << "Position : (" << std::setprecision(2)
             << fX << ", " << fY << ", " << fZ << ")" << FairLogger::endl;
   LOG(INFO) << "Slopes : dx/dz = " << fTx << ", dy/dz = " << fTy
             << FairLogger::endl;
   LOG(INFO) << "q/p = " << fQp << FairLogger::endl;
 }
void FairTrackParam::SetCovariance (Int_t i, Int_t j, Double_t val)
Definition at line 190 of file FairTrackParam.cxx.
References FairLogger::endl(), fCovMatrix, LOG, and WARNING.
 {
   if (i < 0 || i > 4) {
     LOG(WARNING) << "FairTrackParam::SetCovariance: "
                  << "First index out of range!  " << i << FairLogger::endl;
     return;
   }
   if (j < 0 || j > 4) {
     LOG(WARNING) << "FairTrackParam::SetCovariance: "
          << "Second index out of range!  " << j << FairLogger::endl;
     return;
   }
   if (i>j) {
     Int_t k = i;
     i = j;
     j = k;
   }
   Int_t index = 0;
   if (i==0) { index = j; }
   else if (i==1) { index =  4 + j; }
   else if (i==2) { index =  7 + j; }
   else if (i==3) { index =  9 + j; }
   else if (i==4) { index = 10 + j; }
   fCovMatrix[index] = val;
   return;
 }
void FairTrackParam::SetCovMatrix (Double_t cov[])
Definition at line 169 of file FairTrackParam.cxx.
References fCovMatrix.
Referenced by operator=().
 {
   for (Int_t i=0; i<15; i++) { fCovMatrix[i] = cov[i]; }
 }
void FairTrackParam::SetCovMatrix (const TMatrixFSym & covMat)
Definition at line 178 of file FairTrackParam.cxx.
References fCovMatrix.
 {
   Int_t index = 0;
   for (int i=0; i<5; i++) {
     for (int j=i; j<5; j++) { fCovMatrix[index++] = covMat[i][j]; }
   }
 }
void FairTrackParam::SetPosition (const TVector3 & pos)
Definition at line 158 of file FairTrackParam.cxx.
References fX, fY, and fZ.
 {
   fX = pos.X();
   fY = pos.Y();
   fZ = pos.Z();
 }
void FairTrackParam::SetQp (Double_t qp) inline
Definition at line 82 of file FairTrackParam.h.
References fQp.
 { fQp = qp; };
void FairTrackParam::SetTx (Double_t tx) inline
Definition at line 80 of file FairTrackParam.h.
References fTx.
Referenced by FairTutorialDet4StraightLineFitter::Exec().
 { fTx = tx; };
void FairTrackParam::SetTy (Double_t ty) inline
Definition at line 81 of file FairTrackParam.h.
References fTy.
Referenced by FairTutorialDet4StraightLineFitter::Exec().
 { fTy = ty; };
void FairTrackParam::SetX (Double_t x) inline
Modifiers
Definition at line 77 of file FairTrackParam.h.
References fX.
Referenced by FairTutorialDet4StraightLineFitter::Exec().
 { fX  = x;  };
void FairTrackParam::SetY (Double_t y) inline
Definition at line 78 of file FairTrackParam.h.
References fY.
Referenced by FairTutorialDet4StraightLineFitter::Exec().
 { fY  = y;  };
void FairTrackParam::SetZ (Double_t z) inline
Definition at line 79 of file FairTrackParam.h.
References fZ.
Referenced by FairTutorialDet4StraightLineFitter::Exec().
 { fZ  = z;  };
Member Data Documentation
Double32_t FairTrackParam::fCovMatrix[15] private
Covariance matrix for the variables x, y, tx, ty, q/p The 15 elements of the upper triangle of the symmetric matrix are stored in an array of floats. The sequence of the array is a[0,0..4], a[1,1..4], a[2,2..4], a[3,3..4], a[4,4].
Definition at line 111 of file FairTrackParam.h.
Referenced by CovMatrix(), FairTrackParam(), GetCovariance(), SetCovariance(), and SetCovMatrix().
Double32_t FairTrackParam::fQp private
Charge over momentum [1/GeV]
Definition at line 103 of file FairTrackParam.h.
Referenced by GetQp(), Momentum(), operator=(), Print(), and SetQp().
Double32_t FairTrackParam::fTx private
Direction of track tx = dx/dz; ty = dy/dz
Definition at line 100 of file FairTrackParam.h.
Referenced by GetTx(), Momentum(), operator=(), Print(), and SetTx().
Double32_t FairTrackParam::fTy private
Definition at line 100 of file FairTrackParam.h.
Referenced by GetTy(), Momentum(), operator=(), Print(), and SetTy().
Double32_t FairTrackParam::fX private
Position of track at given z [cm]
Definition at line 97 of file FairTrackParam.h.
Referenced by GetX(), operator=(), Position(), Print(), SetPosition(), and SetX().
Double32_t FairTrackParam::fY private
Definition at line 97 of file FairTrackParam.h.
Referenced by GetY(), operator=(), Position(), Print(), SetPosition(), and SetY().
Double32_t FairTrackParam::fZ private
Definition at line 97 of file FairTrackParam.h.
Referenced by GetZ(), operator=(), Position(), Print(), SetPosition(), and SetZ().
The documentation for this class was generated from the following files:
FairTrackParam.h
FairTrackParam.cxx