
CREATE TABLE FAIRDBLOGENTRYVAL(
    SEQNO         INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TIMESTART     DATETIME NOT NULL,
    TIMEEND       DATETIME NOT NULL,
    DETID         TINYINT,
    DATAID        TINYINT,
    VERSION       INT,
    COMPOSITEID   INT,
    TIMEINCR      DATETIME NOT NULL,
    TIMETRANS     DATETIME NOT NULL
);

CREATE TABLE FAIRDBLOGENTRY(
    SEQNO        INT,
    ROW_COUNTER  INT,
    TABLENAME    TEXT,
    SEQNOMIN     INT NOT NULL,
    SEQNOMAX     INT NOT NULL,
    NUMSEQNO     INT NOT NULL,
    USERNAME     TEXT,
    PROCESSNAME  TEXT,
    HOSTNAME     TEXT,
    SERVERNAME   TEXT,
    LOG_REASON   TEXT
 );


CREATE TABLE FAIRDBGLOBALSEQNO(
    TABLENAME      CHAR(64) NOT NULL PRIMARY KEY,
    LASTUSEDSEQNO  INT );
INSERT INTO FAIRDBGLOBALSEQNO VALUES ('*',900000000);


