FairRoot: FairBoxSetEditor Class Reference
FairBoxSetEditor Class Reference
#include <FairBoxSetEditor.h>
Public Member Functions
FairBoxSetEditor (const TGWindow *p=0, Int_t width=170, Int_t height=30, UInt_t options=kChildFrame, Pixel_t back=GetDefaultFrameBackground())
virtual ~FairBoxSetEditor ()
virtual void Init ()
virtual void SetModel (TObject *obj)
virtual void TimeWindow ()
Public Attributes
TGVerticalFrame * fInfoFrame
TGNumberEntry * fTimeWindowPlus
TGNumberEntry * fTimeWindowMinus
Protected Attributes
TObject * fObject
FairBoxSet * fM
Private Member Functions
FairBoxSetEditor (const FairBoxSetEditor &)
FairBoxSetEditor & operator= (const FairBoxSetEditor &)
ClassDef (FairBoxSetEditor, 2)
Detailed Description
Definition at line 40 of file FairBoxSetEditor.h.
Constructor & Destructor Documentation
FairBoxSetEditor::FairBoxSetEditor (const TGWindow * p = 0, Int_t width = 170, Int_t height = 30, UInt_t options = kChildFrame, Pixel_t back = GetDefaultFrameBackground())
virtual FairBoxSetEditor::~FairBoxSetEditor () inline virtual
Definition at line 47 of file FairBoxSetEditor.h.
 {};
FairBoxSetEditor::FairBoxSetEditor (const FairBoxSetEditor &) private
Member Function Documentation
FairBoxSetEditor::ClassDef (FairBoxSetEditor , 2) private
void FairBoxSetEditor::Init () virtual
Definition at line 43 of file FairBoxSetEditor.cxx.
References fInfoFrame, fTimeWindowMinus, and fTimeWindowPlus.
 {
 //  FairRootManager* fRootManager=FairRootManager::Instance();
 //  TChain* chain =fRootManager->GetInChain();
 //  Int_t Entries= chain->GetEntriesFast();
   MakeTitle("FairBoxSet  Editor");
   fInfoFrame= CreateEditorTabSubFrame("Time");
   TGCompositeFrame* title1 = new TGCompositeFrame(fInfoFrame, 250, 10,
       kVerticalFrame | kLHintsExpandX |
       kFixedWidth    | kOwnBackground);
   TGLabel* label1 = new TGLabel(title1,"Time window after event time [ns]: ");
   title1->AddFrame(label1, new TGLayoutHints(kLHintsLeft | kLHintsCenterY, 1, 2, 1, 1));
   fTimeWindowPlus = new TGNumberEntry(title1);//, 0, 5, -1, TGNumberFormat::kNESRealTwo); //, TGNumberFormat::kNEANonNegative);
 // fTimeWindow->SetLimits(0, MAXE, 2501, TGNumberFormat::kNESRealOne);
   fTimeWindowPlus->GetNumberEntry()->SetToolTipText("Time window in ns for which points are shown");
   fTimeWindowPlus->Connect("ValueSet(Long_t)", "FairBoxSetEditor",this, "TimeWindow()");
   title1->AddFrame(fTimeWindowPlus, new TGLayoutHints(kLHintsTop, 1, 1, 1, 0));
   fInfoFrame->AddFrame(title1);
   TGCompositeFrame* title2 = new TGCompositeFrame(fInfoFrame, 250, 10,
       kVerticalFrame | kLHintsExpandX |
       kFixedWidth    | kOwnBackground);
   TGLabel* label2 = new TGLabel(title2, "Time window before event time [ns]: ");
   title2->AddFrame(label2, new TGLayoutHints(kLHintsLeft | kLHintsCenterY, 1, 2, 1, 1));
   fTimeWindowMinus = new TGNumberEntry(title2, 0., 6, -1, TGNumberFormat::kNESInteger, TGNumberFormat::kNEANonNegative);//, 1, 5, -1, TGNumberFormat::kNESRealTwo, TGNumberFormat::kNEANonNegative);
 // fTimeWindow->SetLimits(0, MAXE, 2501, TGNumberFormat::kNESRealOne);
   fTimeWindowMinus->GetNumberEntry()->SetToolTipText("Time window in ns for which points are shown");
   fTimeWindowMinus->Connect("ValueSet(Long_t)", "FairBoxSetEditor",this, "TimeWindow()");
   title2->AddFrame(fTimeWindowMinus, new TGLayoutHints(kLHintsTop, 1, 1, 1, 0));
   fInfoFrame->AddFrame(title2);
 }
FairBoxSetEditor& FairBoxSetEditor::operator= (const FairBoxSetEditor &) private
virtual void FairBoxSetEditor::SetModel (TObject * obj) inline virtual
Definition at line 51 of file FairBoxSetEditor.h.
References fM, fTimeWindowMinus, fTimeWindowPlus, FairBoxSet::GetTimeWindowMinus(), and FairBoxSet::GetTimeWindowPlus().
{
       fM = dynamic_cast<FairBoxSet*>(obj);
       if (fM) {
         fTimeWindowPlus->SetNumber(fM->GetTimeWindowPlus());
         fTimeWindowMinus->SetNumber(fM->GetTimeWindowMinus());
       }
     }
void FairBoxSetEditor::TimeWindow () virtual
Definition at line 84 of file FairBoxSetEditor.cxx.
References fM, fTimeWindowMinus, fTimeWindowPlus, FairEventManager::GetCurrentEvent(), FairEventManager::GotoEvent(), FairEventManager::Instance(), FairBoxSet::SetTimeWindowMinus(), and FairBoxSet::SetTimeWindowPlus().
 {
   std::cout << "FairBoxSetEditor::TimeWindowPlus " << fTimeWindowPlus->GetNumber() << std::endl;
   std::cout << "FairBoxSetEditor::TimeWindowMinus " << fTimeWindowMinus->GetNumber() << std::endl;
   fM->SetTimeWindowPlus(fTimeWindowPlus->GetNumber());
   fM->SetTimeWindowMinus(fTimeWindowMinus->GetNumber());
   FairEventManager* man = FairEventManager::Instance();
   man->GotoEvent(man->GetCurrentEvent());
   Update();
 }
Member Data Documentation
TGVerticalFrame* FairBoxSetEditor::fInfoFrame
Definition at line 61 of file FairBoxSetEditor.h.
Referenced by Init().
FairBoxSet* FairBoxSetEditor::fM protected
Definition at line 68 of file FairBoxSetEditor.h.
Referenced by SetModel(), and TimeWindow().
TObject* FairBoxSetEditor::fObject protected
Definition at line 67 of file FairBoxSetEditor.h.
TGNumberEntry* FairBoxSetEditor::fTimeWindowMinus
Definition at line 63 of file FairBoxSetEditor.h.
Referenced by Init(), SetModel(), and TimeWindow().
TGNumberEntry* FairBoxSetEditor::fTimeWindowPlus
Definition at line 62 of file FairBoxSetEditor.h.
Referenced by Init(), SetModel(), and TimeWindow().
The documentation for this class was generated from the following files:
FairBoxSetEditor.h
FairBoxSetEditor.cxx