FairRroot: FairVolumeList Class Reference
FairVolumeList Class Reference
#include <FairVolumeList.h>
Public Member Functions
FairVolumeList ()
virtual ~FairVolumeList ()
FairVolume * getVolume (TString *name)
Int_t getVolumeId (TString *name)
FairVolume * findObject (TString name)
void addVolume (FairVolume *elem)
Int_t getEntries ()
FairVolume * At (Int_t pos)
Private Member Functions
FairVolumeList (const FairVolumeList &)
FairVolumeList & operator= (const FairVolumeList &)
Private Attributes
TObjArray * fData
Detailed Description
This Object is only used for internal book keeping!
Author
M. Al-Turany, D. Bertini
Version
0.1
Since
12.01.04
Definition at line 26 of file FairVolumeList.h.
Constructor & Destructor Documentation
FairVolumeList::FairVolumeList (const FairVolumeList &) private
FairVolumeList::FairVolumeList ()
Definition at line 28 of file FairVolumeList.cxx.
   :TObject(),
    fData(new TObjArray())
 {
   //
 }
FairVolumeList::~FairVolumeList () virtual
Definition at line 37 of file FairVolumeList.cxx.
References fData.
 {
   if (fData) {
     fData->Delete();
     delete fData;
   }
 }
Member Function Documentation
void FairVolumeList::addVolume (FairVolume * elem)
Definition at line 82 of file FairVolumeList.cxx.
References fData, findObject(), and FairVolume::getVolumeId().
Referenced by FairModule::AddSensitiveVolume(), and FairModule::ProcessNodes().
 {
   FairVolume* v= (FairVolume*)findObject(elem->GetName());
   if (v) {
     if(gDebug>0) { cerr << "-I FairVolumeList element: " << elem->GetName() <<  " VolId : " << elem->getVolumeId() << " already defined " << v->getVolumeId()<< endl; }
   } else {
     fData->Add(elem);
   }
 }
FairVolume* FairVolumeList::At (Int_t pos) inline
Definition at line 44 of file FairVolumeList.h.
Referenced by FairModule::getFairVolume().
 { return ( (FairVolume*) fData->At(pos)); }
FairVolume * FairVolumeList::findObject (TString name)
Definition at line 67 of file FairVolumeList.cxx.
References fData.
Referenced by FairModule::AddSensitiveVolume(), addVolume(), getVolume(), and getVolumeId().
 {
   FairVolume* obj = NULL;
   for (int i = 0; i < fData->GetEntriesFast(); i++) {
     obj = (FairVolume*) fData->At(i);
     if (obj ) {
       if (obj->GetName() == name) { return (FairVolume*) obj; }
     }
   }
   return NULL;
 }
Int_t FairVolumeList::getEntries () inline
Definition at line 43 of file FairVolumeList.h.
Referenced by FairModule::getFairVolume().
 { return fData->GetEntries();}
FairVolume * FairVolumeList::getVolume (TString * name)
Definition at line 46 of file FairVolumeList.cxx.
References findObject().
 {
   TObject* obj = findObject(* name);
   if (obj) { cout << "-I FairVolume getVolume " << name->Data() << "found" << endl; }
   return (FairVolume*) obj;
 }
Int_t FairVolumeList::getVolumeId (TString * name)
Definition at line 55 of file FairVolumeList.cxx.
References findObject(), and FairVolume::getVolumeId().
 {
   TObject* obj = findObject(* name);
   if (obj) { cout << "-I FairVolume getVolume " << name->Data() << "found" << endl; }
   FairVolume* vol = (FairVolume*) obj;
   return vol->getVolumeId();
 }
FairVolumeList& FairVolumeList::operator= (const FairVolumeList &) private
Member Data Documentation
TObjArray* FairVolumeList::fData private
Definition at line 29 of file FairVolumeList.h.
Referenced by addVolume(), findObject(), and ~FairVolumeList().
The documentation for this class was generated from the following files:
FairVolumeList.h
FairVolumeList.cxx