FairRroot: FairTestDetectorDigiTask Class Reference
FairTestDetectorDigiTask Class Reference
#include <FairTestDetectorDigiTask.h>
Public Member Functions
FairTestDetectorDigiTask ()
~FairTestDetectorDigiTask ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
void SetTimeResolution (Double_t timeInNs)
Double_t GetTimeResolution ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
Int_t CalcPad (Double_t posIn, Double_t posOut)
Double_t CalcTimeStamp (Double_t timeOfFlight)
FairTestDetectorDigiTask (const FairTestDetectorDigiTask &)
FairTestDetectorDigiTask & operator= (const FairTestDetectorDigiTask &)
ClassDef (FairTestDetectorDigiTask, 1)
Private Attributes
Double_t fTimeResolution
TClonesArray * fPointArray
TClonesArray * fDigiArray
Detailed Description
Definition at line 17 of file FairTestDetectorDigiTask.h.
Constructor & Destructor Documentation
FairTestDetectorDigiTask::FairTestDetectorDigiTask ()
Default constructor
Definition at line 24 of file FairTestDetectorDigiTask.cxx.
     : FairTask("TestDetectorDigTask")
     , fTimeResolution(0.)
     , fPointArray(NULL)
     , fDigiArray(NULL)
 {
 }
FairTestDetectorDigiTask::~FairTestDetectorDigiTask ()
Destructor
Definition at line 34 of file FairTestDetectorDigiTask.cxx.
 {
 }
FairTestDetectorDigiTask::FairTestDetectorDigiTask (const FairTestDetectorDigiTask &) private
Member Function Documentation
Int_t FairTestDetectorDigiTask::CalcPad (Double_t posIn, Double_t posOut) private
Definition at line 102 of file FairTestDetectorDigiTask.cxx.
Referenced by Exec().
 {
     Int_t result = (Int_t)(posIn + posOut) / 2;
     return result;
 }
Double_t FairTestDetectorDigiTask::CalcTimeStamp (Double_t timeOfFlight) private
Definition at line 109 of file FairTestDetectorDigiTask.cxx.
References fTimeResolution, FairRootManager::GetEventTime(), and FairRootManager::Instance().
Referenced by Exec().
 {
     Double_t eventTime = FairRootManager::Instance()->GetEventTime();
     Double_t detectionTime = gRandom->Gaus(0, fTimeResolution);
     Double_t result = eventTime + timeOfFlight + detectionTime;
     if (result < 0)
     {
         return 0;
     }
     else
     {
         return result;
     }
 }
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTestDetectorDigiTask::ClassDef (FairTestDetectorDigiTask , 1) private
void FairTestDetectorDigiTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 66 of file FairTestDetectorDigiTask.cxx.
References CalcPad(), CalcTimeStamp(), fDigiArray, fPointArray, fTimeResolution, FairMCPoint::GetTime(), FairMCPoint::GetX(), FairTestDetectorPoint::GetXOut(), FairMCPoint::GetY(), FairTestDetectorPoint::GetYOut(), FairMCPoint::GetZ(), FairTestDetectorPoint::GetZOut(), and FairTimeStamp::SetTimeStampError().
 {
     fDigiArray->Delete();
     // fill the map
     for (int ipnt = 0; ipnt < fPointArray->GetEntries(); ipnt++)
     {
         FairTestDetectorPoint* point = (FairTestDetectorPoint*)fPointArray->At(ipnt);
         if (!point)
         {
             continue;
         }
         Int_t xPad = CalcPad(point->GetX(), point->GetXOut());
         Int_t yPad = CalcPad(point->GetY(), point->GetYOut());
         Int_t zPad = CalcPad(point->GetZ(), point->GetZOut());
         Double_t timestamp = CalcTimeStamp(point->GetTime());
         FairTestDetectorDigi* digi = new ((*fDigiArray)[ipnt]) FairTestDetectorDigi(xPad, yPad, zPad, timestamp);
         if (fTimeResolution > 0)
         {
             digi->SetTimeStampError(fTimeResolution / TMath::Sqrt(fTimeResolution));
         }
         else
         {
             digi->SetTimeStampError(0);
         }
         digi->SetLink(FairLink("FairTestDetectorPoint", ipnt));
     }
 }
virtual void FairTask::Finish () inline protected virtual inherited
Action after each event. To be implemented in the derived class
Reimplemented in FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 111 of file FairTask.h.
Referenced by FairTask::FinishTask(), and FairTask::FinishTasks().
 { };
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
Double_t FairTestDetectorDigiTask::GetTimeResolution () inline
Definition at line 36 of file FairTestDetectorDigiTask.h.
References fTimeResolution.
     {
         return fTimeResolution;
     }
InitStatus FairTestDetectorDigiTask::Init () virtual
Virtual method Init
todo replace with logger!
Reimplemented from FairTask.
Definition at line 40 of file FairTestDetectorDigiTask.cxx.
References fDigiArray, fPointArray, FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kFATAL, kSUCCESS, and FairRootManager::Register().
 {
     FairRootManager* ioman = FairRootManager::Instance();
     if (!ioman)
     {
         std::cout << "-E- FairTestDetectorDigiTask::Init: "
                   << "RootManager not instantiated!" << std::endl;
         return kFATAL;
     }
     fPointArray = (TClonesArray*)ioman->GetObject("FairTestDetectorPoint");
     if (!fPointArray)
     {
         std::cout << "-W- FairTestDetectorDigiTask::Init: "
                   << "No Point array!" << std::endl;
         return kERROR;
     }
     // Create and register output array
     fDigiArray = new TClonesArray("FairTestDetectorDigi");
     ioman->Register("FairTestDetectorDigi", "FairTestDetector", fDigiArray, kTRUE);
     return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairTestDetectorDigiTask& FairTestDetectorDigiTask::operator= (const FairTestDetectorDigiTask &) private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
virtual void FairTask::SetParContainers () inline protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented in FairRingSorterTask, FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairTutorialDet4HitProducerIdealMisalign, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairMCMatchLoaderTask, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::SetParTask().
 { };
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTestDetectorDigiTask::SetTimeResolution (Double_t timeInNs) inline
Definition at line 32 of file FairTestDetectorDigiTask.h.
References fTimeResolution.
     {
         fTimeResolution = timeInNs;
     }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
TClonesArray* FairTestDetectorDigiTask::fDigiArray private
Definition at line 48 of file FairTestDetectorDigiTask.h.
Referenced by Exec(), and Init().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
TClonesArray* FairTestDetectorDigiTask::fPointArray private
Definition at line 47 of file FairTestDetectorDigiTask.h.
Referenced by Exec(), and Init().
Double_t FairTestDetectorDigiTask::fTimeResolution private
Definition at line 45 of file FairTestDetectorDigiTask.h.
Referenced by CalcTimeStamp(), Exec(), GetTimeResolution(), and SetTimeResolution().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairMCTracks::Exec(), FairMCStack::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairMCTracks::Init(), FairMCStack::Init(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairTestDetectorDigiTask.h
FairTestDetectorDigiTask.cxx