FairRroot: FairLmdSource Class Reference
FairLmdSource Class Reference
#include <FairLmdSource.h>
Public Member Functions
FairLmdSource ()
FairLmdSource (const FairLmdSource &source)
virtual ~FairLmdSource ()
void AddFile (TString fileName)
void AddPath (TString dir, TString wildCard)
const Int_t GetCurrentFile () const
const TList * GetFileNames () const
virtual Bool_t Init ()
virtual Int_t ReadEvent (UInt_t=0)
virtual void Close ()
void AddUnpacker (FairUnpack *unpacker)
const TObjArray * GetUnpackers () const
void Reset ()
Protected Member Functions
Bool_t OpenNextFile (TString fileName)
Bool_t Unpack (Int_t *data, Int_t size, Short_t type, Short_t subType, Short_t procId, Short_t subCrate, Short_t control)
Protected Attributes
Int_t fCurrentFile
Int_t fNEvent
Int_t fCurrentEvent
TList * fFileNames
s_evt_channel * fxInputChannel
s_ve10_1 * fxEvent
s_bufhe * fxBuffer
Int_t * fxEventData
s_ves10_1 * fxSubEvent
s_filhe * fxInfoHeader
Detailed Description
Definition at line 32 of file FairLmdSource.h.
Constructor & Destructor Documentation
FairLmdSource::FairLmdSource ()
Definition at line 25 of file FairLmdSource.cxx.
   : FairMbsSource(),
     fCurrentFile(0),
         fNEvent(0),
     fCurrentEvent(0),
     fFileNames(new TList()),
     fxInputChannel(NULL),
     fxEvent(NULL),
     fxBuffer(NULL),
     fxEventData(NULL),
     fxSubEvent(NULL),
     fxInfoHeader(NULL)
 {
 }
FairLmdSource::FairLmdSource (const FairLmdSource & source)
Definition at line 41 of file FairLmdSource.cxx.
   : FairMbsSource(source),
     fCurrentFile(source.GetCurrentFile()),
         fNEvent(0),
     fCurrentEvent(0),
     fFileNames(new TList()),
     fxInputChannel(NULL),
     fxEvent(NULL),
     fxBuffer(NULL),
     fxEventData(NULL),
     fxSubEvent(NULL),
     fxInfoHeader(NULL)
 {
 }
FairLmdSource::~FairLmdSource () virtual
Definition at line 57 of file FairLmdSource.cxx.
References fFileNames.
 {
   fFileNames->Delete();
   delete fFileNames;
 }
Member Function Documentation
void FairLmdSource::AddFile (TString fileName)
Definition at line 64 of file FairLmdSource.cxx.
References FairLogger::endl(), fFileNames, LOG, and WARNING.
Referenced by AddPath().
 {
   FileStat_t buf;
   if(1 == gSystem->GetPathInfo(fileName.Data(), buf))
   {
     LOG(WARNING) << "FairLmdSource: not found: " << fileName << FairLogger::endl;
     return;
   }
   TObjString* str = new TObjString(fileName);
   fFileNames->Add(str);
 }
void FairLmdSource::AddPath (TString dir, TString wildCard)
Definition at line 78 of file FairLmdSource.cxx.
References AddFile(), FairLogger::endl(), LOG, and WARNING.
 {
   FileStat_t buf;
   if(1 == gSystem->GetPathInfo(dir.Data(), buf))
   {
     LOG(WARNING) << "FairLmdSource: not found: " << dir << FairLogger::endl;
     return;
   }
   TRegexp *re = new TRegexp(wildCard.Data(), kTRUE);
   TSystemDirectory *sdir = new TSystemDirectory("dir", dir.Data());
   TString dname(dir);
   if(! dname.EndsWith("/"))
   {
       dname += "/";
   }
   TList *list = sdir->GetListOfFiles();
   TIterator *iter = list->MakeIterator();
   TSystemFile *file;
   TString name;
   while(NULL != (file = (TSystemFile*)iter->Next()))
   {
     name = file->GetName();
     if(name.Contains(*re))
     {
       name = dname + name;
       AddFile(name);
     }
   }
   list->Delete();
 }
void FairMbsSource::AddUnpacker (FairUnpack * unpacker) inline inherited
Definition at line 32 of file FairMbsSource.h.
References FairMbsSource::fUnpackers.
 { fUnpackers->Add(unpacker); }
void FairLmdSource::Close () virtual
Implements FairMbsSource.
Definition at line 262 of file FairLmdSource.cxx.
References f_evt_get_close(), fCurrentEvent, fxBuffer, fxInputChannel, and FairMbsSource::Unpack().
Referenced by ReadEvent().
 {
   f_evt_get_close(fxInputChannel);
   Unpack((Int_t*)fxBuffer, sizeof(s_bufhe), -4, -4, -4, -4, -4);
   fCurrentEvent=0;
 }
const Int_t FairLmdSource::GetCurrentFile () const inline
Definition at line 41 of file FairLmdSource.h.
References fCurrentFile.
 { return fCurrentFile; }
const TList* FairLmdSource::GetFileNames () const inline
Definition at line 42 of file FairLmdSource.h.
References fFileNames.
 { return fFileNames; }
const TObjArray* FairMbsSource::GetUnpackers () const inline inherited
Definition at line 33 of file FairMbsSource.h.
References FairMbsSource::fUnpackers.
 { return fUnpackers; }
Bool_t FairLmdSource::Init () virtual
Reimplemented from FairMbsSource.
Definition at line 113 of file FairLmdSource.cxx.
References fCurrentEvent, fCurrentFile, fFileNames, fNEvent, FairMbsSource::Init(), and OpenNextFile().
 {
   if(! FairMbsSource::Init()) {
     return kFALSE;
   }
   if(fFileNames->GetSize() == 0) {
     return kFALSE;
   }
   TString name = ((TObjString*)fFileNames->At(fCurrentFile))->GetString();
   if(! OpenNextFile(name)) {
     return kFALSE;
   }
   fCurrentFile += 1;
  // Init Counters
   fNEvent=fCurrentEvent=0;
   return kTRUE;
 }
Bool_t FairLmdSource::OpenNextFile (TString fileName) protected
Definition at line 137 of file FairLmdSource.cxx.
References FairLogger::endl(), ERROR, f_evt_get_open(), fxInfoHeader, fxInputChannel, GETEVT__FILE, INFO, LOG, and FairMbsSource::Unpack().
Referenced by Init(), and ReadEvent().
 {
   Int_t inputMode = GETEVT__FILE;
   fxInputChannel = new s_evt_channel;
   void* headptr = &fxInfoHeader;
   INTS4 status;
   LOG(INFO) << "File " << fileName << " will be opened." << FairLogger::endl;
   status = f_evt_get_open(inputMode,
                           const_cast<char*>(fileName.Data()),
                           fxInputChannel,
                           (Char_t**)headptr,
                           1,
                           1);
   if(status) {
      LOG(ERROR) << "File " << fileName << " opening failed." << FairLogger::endl;
     return kFALSE;
   }
   LOG(INFO) << "File " << fileName << " opened." << FairLogger::endl;
   // Decode File Header
   Bool_t result = Unpack((Int_t*)fxInfoHeader, sizeof(s_filhe), -4, -4, -4, -4, -4);
   return kTRUE;
 }
Int_t FairLmdSource::ReadEvent (UInt_t iev = 0) virtual
Implements FairMbsSource.
Definition at line 167 of file FairLmdSource.cxx.
References Close(), DEBUG2, FairLogger::endl(), f_evt_error(), f_evt_get_event(), f_evt_get_subevent(), fCurrentEvent, fCurrentFile, fFileNames, fNEvent, fxBuffer, fxEvent, fxEventData, fxInputChannel, fxSubEvent, GETEVT__NOMORE, GETEVT__SUCCESS, s_ves10_1::h_control, s_ves10_1::h_subcrate, s_ves10_1::i_procid, s_ves10_1::i_subtype, s_ves10_1::i_type, INFO, LOG, OpenNextFile(), and FairMbsSource::Unpack().
 {
   void* evtptr = &fxEvent;
   void* buffptr = &fxBuffer;
   Int_t status = f_evt_get_event(fxInputChannel, (INTS4**)evtptr,(INTS4**) buffptr);
   //Int_t fuEventCounter = fxEvent->l_count;
   //Int_t fCurrentMbsEventNo = fuEventCounter;
   if(GETEVT__SUCCESS != status) {
     LOG(INFO) << "FairMbsStreamSource::ReadEvent()"
               << FairLogger::endl;
     CHARS* sErrorString = NULL;
     f_evt_error(status, sErrorString , 0);
     if(fCurrentFile >= fFileNames->GetSize()) {
       return 1;
     }
     if(GETEVT__NOMORE == status) {
       Close();
     }
     TString name = ((TObjString*)fFileNames->At(fCurrentFile))->GetString();
     if(! OpenNextFile(name)) {
       return 1;
     } else {
       fCurrentFile += 1;
       return ReadEvent();
     }
   }
  //Store Start Times
   if (fCurrentEvent==0 )
       Unpack((Int_t*)fxBuffer, sizeof(s_bufhe), -4, -4, -4, -4, -4);
   // Decode event header
   Bool_t result = kFALSE;
   /*Bool_t result = */Unpack((Int_t*)fxEvent, sizeof(s_ve10_1), -2, -2, -2, -2, -2);
   Int_t nrSubEvts = f_evt_get_subevent(fxEvent, 0, NULL, NULL, NULL);
   Int_t sebuflength;
   Short_t setype;
   Short_t sesubtype;
   Short_t seprocid;
   Short_t sesubcrate;
   Short_t secontrol;
   LOG(DEBUG2)<< "FairLmdSource::ReadEvent => Found " << nrSubEvts << " Sub-event "
              << FairLogger::endl;
   //if (fCurrentEvent%10000==0)
   //cout << " -I- LMD_ANA:  evt# " <<  fCurrentEvent << "  n_subevt# " << nrSubEvts << " evt processed# " << fNEvent <<  " : " << fxEvent->l_count << endl;
 //  Int_t* SubEventDataPtr = new Int_t;
   for(Int_t i = 1; i <= nrSubEvts; i++) {
     void* SubEvtptr = &fxSubEvent;
     void* EvtDataptr = &fxEventData;
     Int_t nrlongwords;
     status = f_evt_get_subevent(fxEvent, i, (Int_t**)SubEvtptr, (Int_t**)EvtDataptr, &nrlongwords);
     if(status) {
       return 1;
     }
     sebuflength = nrlongwords;
     setype = fxSubEvent->i_type;
     sesubtype = fxSubEvent->i_subtype;
     seprocid = fxSubEvent->i_procid;
     sesubcrate = fxSubEvent->h_subcrate;
     secontrol = fxSubEvent->h_control;
     //cout << setype << "  " << sesubtype << "  " << seprocid << "  " << sesubcrate << "  " << secontrol << endl;
     if(Unpack(fxEventData, sebuflength,
               setype, sesubtype,
               seprocid, sesubcrate, secontrol)) {
       result = kTRUE;
     }
   }
   // Increment evt counters.
   fNEvent++;
   fCurrentEvent++;
   if(! result)
   {
     return 2;
   }
  return 0;
 }
void FairMbsSource::Reset () virtual inherited
Implements FairSource.
Definition at line 40 of file FairMbsSource.cxx.
References FairMbsSource::fUnpackers.
{
   for (Int_t i = 0; i < fUnpackers->GetEntriesFast(); i++) {
     ((FairUnpack *)fUnpackers->At(i))->Reset();
   }
 }
Bool_t FairMbsSource::Unpack (Int_t * data, Int_t size, Short_t type, Short_t subType, Short_t procId, Short_t subCrate, Short_t control) protected inherited
Definition at line 46 of file FairMbsSource.cxx.
References DEBUG2, FairUnpack::DoUnpack(), FairLogger::endl(), FairMbsSource::fUnpackers, FairUnpack::GetControl(), FairUnpack::GetProcId(), FairUnpack::GetSubCrate(), FairUnpack::GetSubType(), FairUnpack::GetType(), and LOG.
Referenced by Close(), OpenNextFile(), FairMbsStreamSource::ReadEvent(), FairRemoteSource::ReadEvent(), and ReadEvent().
{
   LOG(DEBUG2)<< "FairMbsSource::Unpack => Found Sub-event with flags: "
              << " Type " << type << " SubType " << subType
              << " ProcId " << procId << " SubCrate " << subCrate
              << " Control " << control
              << FairLogger::endl;
   FairUnpack *unpack;
   Bool_t seen = kFALSE;
   for (Int_t i = 0; i < fUnpackers->GetEntriesFast(); i++) {
     unpack = (FairUnpack *)fUnpackers->At(i);
     if (unpack->GetSubCrate() < 0) { // All sub-crates
       if (type != unpack->GetType() || subType != unpack->GetSubType() ||
           procId != unpack->GetProcId() || control != unpack->GetControl()) {
         continue;
       }
     } else { // specified sub-crate
       if (type != unpack->GetType() || subType != unpack->GetSubType() ||
           procId != unpack->GetProcId() || subCrate != unpack->GetSubCrate() ||
           control != unpack->GetControl()) {
         continue;
       }
     }
     if (!unpack->DoUnpack(data, size)) {
       return kFALSE;
     }
     seen = kTRUE;
   }
   return seen;
 }
Member Data Documentation
Int_t FairLmdSource::fCurrentEvent protected
Definition at line 53 of file FairLmdSource.h.
Referenced by Close(), Init(), and ReadEvent().
Int_t FairLmdSource::fCurrentFile protected
Definition at line 51 of file FairLmdSource.h.
Referenced by GetCurrentFile(), Init(), and ReadEvent().
TList* FairLmdSource::fFileNames protected
Definition at line 54 of file FairLmdSource.h.
Referenced by AddFile(), GetFileNames(), Init(), ReadEvent(), and ~FairLmdSource().
Int_t FairLmdSource::fNEvent protected
Definition at line 52 of file FairLmdSource.h.
Referenced by Init(), and ReadEvent().
s_bufhe* FairLmdSource::fxBuffer protected
Definition at line 57 of file FairLmdSource.h.
Referenced by Close(), and ReadEvent().
s_ve10_1* FairLmdSource::fxEvent protected
Definition at line 56 of file FairLmdSource.h.
Referenced by ReadEvent().
Int_t* FairLmdSource::fxEventData protected
Definition at line 58 of file FairLmdSource.h.
Referenced by ReadEvent().
s_filhe* FairLmdSource::fxInfoHeader protected
Definition at line 60 of file FairLmdSource.h.
Referenced by OpenNextFile().
s_evt_channel* FairLmdSource::fxInputChannel protected
Definition at line 55 of file FairLmdSource.h.
Referenced by Close(), OpenNextFile(), and ReadEvent().
s_ves10_1* FairLmdSource::fxSubEvent protected
Definition at line 59 of file FairLmdSource.h.
Referenced by ReadEvent().
The documentation for this class was generated from the following files:
FairLmdSource.h
FairLmdSource.cxx