FairRroot: FairDetParTSQLIo Class Reference
FairDetParTSQLIo Class Reference
#include <FairDetParTSQLIo.h>
Public Member Functions
FairDetParTSQLIo ()
Constructors.
FairDetParTSQLIo (FairDbConnectionPool const &cons, int const dbNum=-1)
virtual ~FairDetParTSQLIo ()
Bool_t read (FairParSet *pars)
Int_t write (FairParSet *pars)
Int_t getRunStart (FairParSet *pPar=0)
virtual void commit ()
virtual void rollback ()
void print ()
_______________ Inline Implementations ________________
void setInputNumber (Int_t n)
Int_t getInputNumber ()
virtual Bool_t init (FairParSet *)
Protected Member Functions
void setChanged (FairParSet *pars)
Protected Attributes
int fDefaultDb
FairDbConnectionPool * fConnections
TList * fcontainerList
FairDbConnection.
FairRtdbRun * factContVers
List of parameter containers.
int actRunId
The actual list of container versions.
Int_t inputNumber
Private Member Functions
FairDetParTSQLIo (FairDetParTSQLIo const &ot)
FairDetParTSQLIo & operator= (FairDetParTSQLIo const &ot)
Detailed Description
Definition at line 29 of file FairDetParTSQLIo.h.
Constructor & Destructor Documentation
FairDetParTSQLIo::FairDetParTSQLIo ()
Constructors.
FairDetParTSQLIo::FairDetParTSQLIo (FairDbConnectionPool const & cons, int const dbNum = -1)
Parameters
cons FairDbConnectionPool which holds a number of initialized db connections.
dbNum The db which is selected to act as the master for the current operations. Note: A new FairDbConnectionPool object is created (to keep the ownership).
cons FairDbConnectionPool which holds a number of initialized db connections.
dbNum The number of the db which is selected to act as the master for the current operations. Note: A new FairDbConnectionPool object is created (to keep the ownership).
Definition at line 49 of file FairDetParTSQLIo.cxx.
   : FairDetParIo(),
     fDefaultDb(dbNum),
     fConnections(new FairDbConnectionPool(cons)),
     fcontainerList(0),
     factContVers(0),
     actRunId(-1)
 {}
FairDetParTSQLIo::~FairDetParTSQLIo () virtual
Definition at line 59 of file FairDetParTSQLIo.cxx.
References factContVers, fConnections, and fcontainerList.
 {
   std::cout << "\n\t<DEBUG> FairDetParTSQLIo::~FairDetParTSQLIo()\n\n";
   if( fConnections ) {
     delete fConnections;
   }
   if( factContVers ) {
     delete factContVers;
   }
   if( fcontainerList ) {
     fcontainerList->Delete();
     delete fcontainerList;
   }
 }
FairDetParTSQLIo::FairDetParTSQLIo (FairDetParTSQLIo const & ot) private
Member Function Documentation
void FairDetParTSQLIo::commit () virtual
Definition at line 119 of file FairDetParTSQLIo.cxx.
 {
   std::cerr << "<ERROR> Commit() is Not implemented yet. Maybe later"
             << std::endl;
 }
Int_t FairDetParIo::getInputNumber () inline inherited
Definition at line 29 of file FairDetParIo.h.
References FairDetParIo::inputNumber.
 {return inputNumber;}
int FairDetParTSQLIo::getRunStart (FairParSet * pPar = 0)
Definition at line 76 of file FairDetParTSQLIo.cxx.
References actRunId, factContVers, FairRuntimeDb::getCurrentRun(), FairRtdbRun::getRefRun(), FairRtdbRun::getRunId(), and FairRuntimeDb::instance().
 {
   std::cout << "\n\n\n\n\t<DEBUG> FairDetParTSQLIo::getRunStart(FairParSet* pPar)\n\n\n\n";
   actRunId=-1;
   int runStart=-1;
   factContVers=FairRuntimeDb::instance()->getCurrentRun();
   if (!factContVers) {
     Error("getRunStart()","current run not set in runtime database");
     return -1;
   }
   const Text_t* refRun=factContVers->getRefRun();
   if (strlen(refRun) > 0) {
     sscanf(refRun,"%i",&actRunId);
   } else {
     actRunId=factContVers->getRunId();
   }
   if(pPar) {
     Int_t contVers = 10;//getPredefVersion(pPar);
     if (contVers>=0) {
       actRunId = contVers;
     }
   }
   //runStart=pConn->getRunStart(actRunId);
   return runStart;
 }
virtual Bool_t FairDetParIo::init (FairParSet *) inline virtual inherited
Reimplemented in FairGenericParTSQLIo, FairGenericParAsciiFileIo, and FairGenericParRootFileIo.
Definition at line 32 of file FairDetParIo.h.
Referenced by ClassImp().
 {return kFALSE;}
FairDetParTSQLIo& FairDetParTSQLIo::operator= (FairDetParTSQLIo const & ot) private
void FairDetParTSQLIo::print () inline
_______________ Inline Implementations ________________
Definition at line 91 of file FairDetParTSQLIo.h.
 {
   std::cout << "FairDetParTSQLIo::print()\n\n";
 };
Bool_t FairDetParTSQLIo::read (FairParSet * pars)
Read the parameter set from the DB.
Definition at line 134 of file FairDetParTSQLIo.cxx.
 {
   std::cout << "========================================================\n";
   pars->Print();
   std::cout << "\n\t<DEBUG>FairDetParTSQLIo::READ(FairParSet* pars)\n"
             << "========================================================\n";
   return false;
 }
void FairDetParTSQLIo::rollback () virtual
Definition at line 126 of file FairDetParTSQLIo.cxx.
 {
   std::cerr << "<ERROR> Rollback() Not implemented yet. Maybe later\n"
             << "        It remains engine dependent."
             << std::endl;
 }
void FairDetParTSQLIo::setChanged (FairParSet * pars) protected
Definition at line 106 of file FairDetParTSQLIo.cxx.
References FairParSet::setChanged(), and FairParSet::setDescription().
 {
   // sets the changed flag, the version (id of actual run) and the comment
   pPar->setChanged();
   //pPar->setInputVersion(getActRunId(), inputNumber);
   TString s="Read from TSQL\n             Valid for Run Id ";
   //s.Append(Form("%d",getActRunId()));
   s.Append("\n             Status at ");
   //s.Append(pConn->getHistoryDate());
   pPar->setDescription(s.Data());
 }
void FairDetParIo::setInputNumber (Int_t n) inline inherited
Definition at line 26 of file FairDetParIo.h.
Referenced by FairParIo::setInputNumber().
 {inputNumber=n;}
Int_t FairDetParTSQLIo::write (FairParSet * pars) virtual
Reimplemented from FairDetParIo.
Reimplemented in FairGenericParTSQLIo.
Definition at line 143 of file FairDetParTSQLIo.cxx.
References FairParSet::getAuthor(), FairParSet::getDescription(), FairParSet::getDetectorName(), FairParSet::GetName(), and FairParSet::getParamContext().
 {
   std::cout << "========================================================\n"
             <<"\t<DEBUG> FairDetParTSQLIo::WRITE(FairParSet* pars)\n"
             << "Name is = " << pars->GetName() << " "
             << " Desc = " << pars->getDescription() << " "
             << " Autho = " << pars->getAuthor() << " "
             << " Context = " << pars->getParamContext() << " "
             << " DetNAme = " << pars->getDetectorName()
             << "\n========================================================\n";
   return 0;
 }
Member Data Documentation
int FairDetParTSQLIo::actRunId protected
The actual list of container versions.
Definition at line 76 of file FairDetParTSQLIo.h.
Referenced by getRunStart().
FairRtdbRun* FairDetParTSQLIo::factContVers protected
List of parameter containers.
Definition at line 75 of file FairDetParTSQLIo.h.
Referenced by getRunStart(), and ~FairDetParTSQLIo().
FairDbConnectionPool* FairDetParTSQLIo::fConnections protected
Definition at line 73 of file FairDetParTSQLIo.h.
Referenced by ~FairDetParTSQLIo().
TList* FairDetParTSQLIo::fcontainerList protected
FairDbConnection.
Definition at line 74 of file FairDetParTSQLIo.h.
Referenced by ~FairDetParTSQLIo().
int FairDetParTSQLIo::fDefaultDb protected
The default Database connection.
Definition at line 72 of file FairDetParTSQLIo.h.
Int_t FairDetParIo::inputNumber protected inherited
Definition at line 20 of file FairDetParIo.h.
Referenced by FairDetParRootFileIo::findInputVersion(), FairDetParIo::getInputNumber(), and FairDetParRootFileIo::read().
The documentation for this class was generated from the following files:
FairDetParTSQLIo.h
FairDetParTSQLIo.cxx