FairRoot: FairMCMatchLoaderTask Class Reference
FairMCMatchLoaderTask Class Reference abstract
#include <FairMCMatchLoaderTask.h>
Public Member Functions
FairMCMatchLoaderTask ()
virtual ~FairMCMatchLoaderTask ()
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
virtual void Finish ()
virtual void InitDataStages ()=0
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
FairMCMatch * fMCMatch
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
void Register ()
void Reset ()
void ProduceHits ()
FairMCMatchLoaderTask (const FairMCMatchLoaderTask &)
FairMCMatchLoaderTask & operator= (const FairMCMatchLoaderTask &)
ClassDef (FairMCMatchLoaderTask, 1)
Private Attributes
TClonesArray * fMCLink
int fEventNr
Detailed Description
Definition at line 31 of file FairMCMatchLoaderTask.h.
Constructor & Destructor Documentation
FairMCMatchLoaderTask::FairMCMatchLoaderTask ()
Default constructor
Definition at line 24 of file FairMCMatchLoaderTask.cxx.
   : FairTask("Creates FairMCMatch"),
     fMCLink(NULL),
     fEventNr(0),
     fMCMatch(NULL)
 {
 }
FairMCMatchLoaderTask::~FairMCMatchLoaderTask () virtual
Destructor
Definition at line 35 of file FairMCMatchLoaderTask.cxx.
 {
 }
FairMCMatchLoaderTask::FairMCMatchLoaderTask (const FairMCMatchLoaderTask &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairMCMatchLoaderTask::ClassDef (FairMCMatchLoaderTask , 1) private
void FairMCMatchLoaderTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 123 of file FairMCMatchLoaderTask.cxx.
References FairMCMatch::ClearMCList(), FairMCMatch::CreateArtificialStage(), fMCLink, fMCMatch, FairMCMatch::LoadInMCLists(), and FairMCMatch::Print().
 {
   if (!fMCLink) { Fatal("Exec", "No fMCLink"); }
   fMCMatch->ClearMCList();
   fMCMatch->LoadInMCLists(fMCLink);
   fMCMatch->CreateArtificialStage("MCTrack");
   fMCMatch->Print();
   std::cout << std::endl;
 }
void FairMCMatchLoaderTask::Finish () virtual
Action after each event. To be implemented in the derived class
Reimplemented from FairTask.
Definition at line 136 of file FairMCMatchLoaderTask.cxx.
 {
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
InitStatus FairMCMatchLoaderTask::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 40 of file FairMCMatchLoaderTask.cxx.
References fMCLink, fMCMatch, FairRootManager::GetObject(), InitDataStages(), FairRootManager::Instance(), kFATAL, kSUCCESS, and FairRootManager::Register().
 {
   fMCMatch = new FairMCMatch("FairMCMatch", "FairMCMatch");
   InitDataStages();
   /*
   fMCMatch->InitStage("MVDPoint");
   fMCMatch->InitStage("MVDStripDigis");
   fMCMatch->InitStage("MVDPixelDigis");
   fMCMatch->InitStage("MVDHitsPixel");
   fMCMatch->InitStage("MVDHitsStrip");
   fMCMatch->InitStage("MVDPixelClusterCand");
   fMCMatch->InitStage("MVDStripClusterCand");
   fMCMatch->InitStage("EmcCluster");
   fMCMatch->InitStage("EmcBump");
   fMCMatch->InitStage("EmcDigi");
   fMCMatch->InitStage("EmcHit");
   fMCMatch->InitStage("EmcPoint");
   fMCMatch->InitStage("EmcRecoHit");
   fMCMatch->InitStage("EmcSharedDigi");
   fMCMatch->InitStage("EmcWaveform");
   fMCMatch->InitStage("STTPoint");
   fMCMatch->InitStage("STTHit");
   fMCMatch->InitStage("SttHelixHit");
   fMCMatch->InitStage("STTTrack");
   fMCMatch->InitStage("STTTrackCand");
   fMCMatch->InitStage("PndTpcPoint");
   fMCMatch->InitStage("PndTpcPrimaryCluster");
   fMCMatch->InitStage("PndTpcDriftedElectron");
   fMCMatch->InitStage("PndTpcAvalanche");
   fMCMatch->InitStage("PndTpcSignal");
   fMCMatch->InitStage("PndTpcDigi");
   fMCMatch->InitStage("PndTpcCluster");
   fMCMatch->InitStage("GEMPoint");
   fMCMatch->InitStage("GEMDigi");
   fMCMatch->InitStage("GEMHit");
   fMCMatch->InitStage("PndDchPoint");
   fMCMatch->InitStage("PndDchDigi");
   fMCMatch->InitStage("PndDchCylinderHit");
   fMCMatch->InitStage("MdtPoint");
   fMCMatch->InitStage("MdtHit");
   fMCMatch->InitStage("MdtTrk");
   fMCMatch->InitStage("LheHit");
   fMCMatch->InitStage("LheCandidate");
   fMCMatch->InitStage("LheTrack");
   fMCMatch->InitStage("MVDIdealTrackCand");
   fMCMatch->InitStage("MVDRiemannTrackCand");
   //fMCMatch->InitStage("PndTrack");
   fMCMatch->InitStage("LheGenTrack");
   fMCMatch->InitStage("PidChargedCand");
   fMCMatch->InitStage("PidNeutralCand");
   */
   FairRootManager* ioman = FairRootManager::Instance();
   if (!ioman) {
     std::cout << "-E- FairMCMatchLoaderTask::Init: "
               << "RootManager not instantiated!" << std::endl;
     return kFATAL;
   }
   fMCLink = (TClonesArray*)ioman->GetObject("MCLink");
   ioman->Register("MCMatch", "MCInfo", fMCMatch, kFALSE);
   return kSUCCESS;
 }
virtual void FairMCMatchLoaderTask::InitDataStages () pure virtual
Referenced by Init().
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairMCMatchLoaderTask& FairMCMatchLoaderTask::operator= (const FairMCMatchLoaderTask &) private
void FairMCMatchLoaderTask::ProduceHits () private
void FairMCMatchLoaderTask::Register () private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairMCMatchLoaderTask::Reset () private
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairMCMatchLoaderTask::SetParContainers () virtual
Virtual method Init
Reimplemented from FairTask.
Definition at line 117 of file FairMCMatchLoaderTask.cxx.
 {
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
int FairMCMatchLoaderTask::fEventNr private
Definition at line 61 of file FairMCMatchLoaderTask.h.
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
TClonesArray* FairMCMatchLoaderTask::fMCLink private
Definition at line 60 of file FairMCMatchLoaderTask.h.
Referenced by Exec(), and Init().
FairMCMatch* FairMCMatchLoaderTask::fMCMatch protected
Definition at line 56 of file FairMCMatchLoaderTask.h.
Referenced by Exec(), and Init().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairMCMatchLoaderTask.h
FairMCMatchLoaderTask.cxx