FairRoot: FairTrackParH Class Reference
FairTrackParH Class Reference
#include <FairTrackParH.h>
Public Member Functions
FairTrackParH ()
FairTrackParH (Double_t x, Double_t y, Double_t z, Double_t lambda, Double_t phi, Double_t qp, Double_t CovMatrix[15])
FairTrackParH (TVector3 pos, TVector3 Mom, TVector3 posErr, TVector3 MomErr, Int_t q)
FairTrackParH (FairTrackPar &Trkbase)
FairTrackParH (FairTrackParP *parab, Int_t &ierr)
virtual ~FairTrackParH ()
virtual void Print (Option_t *option="") const
Double_t GetLambda ()
Double_t GetPhi ()
Double_t GetDLambda ()
Double_t GetDPhi ()
void GetCov (Double_t *Cov)
void GetCovQ (Double_t *CovQ)
void GetMARSCov (Double_t Cov66[6][6])
Double_t GetDX_sc ()
Double_t GetDY_sc ()
Double_t GetDZ_sc ()
Double_t GetX_sc ()
Double_t GetY_sc ()
Double_t GetZ_sc ()
Double_t GetX ()
Double_t GetY ()
Double_t GetZ ()
void SetLambda (Double_t Lm)
void SetPhi (Double_t Phi)
void SetDLambda (Double_t DLm)
void SetDPhi (Double_t DPhi)
void SetX_sc (Double_t x)
void SetY_sc (Double_t y)
void SetZ_sc (Double_t z)
void SetCov (Double_t *Cov)
void SetTrackPar (Double_t x, Double_t y, Double_t z, Double_t Px, Double_t Py, Double_t Pz, Int_t Q, Double_t CovMatrix[15])
void SetTrackPar (Double_t x, Double_t y, Double_t z, Double_t pq, Double_t lm, Double_t phi, Double_t CovMatrix[15])
void Reset ()
ClassDef (FairTrackParH, 1)
virtual TVector3 GetPosition () const
Int_t GetQ () const
virtual Double_t GetDX () const
virtual Double_t GetDY () const
virtual Double_t GetDZ () const
virtual TVector3 GetMomentum () const
virtual Double_t GetPx () const
virtual Double_t GetPy () const
virtual Double_t GetPz () const
virtual Double_t GetQp () const
virtual Double_t GetDPx () const
virtual Double_t GetDPy () const
virtual Double_t GetDPz () const
virtual Double_t GetDQp () const
virtual void SetX (Double_t x)
virtual void SetY (Double_t y)
virtual void SetZ (Double_t z)
virtual void SetDX (Double_t dx)
virtual void SetDY (Double_t dy)
virtual void SetDZ (Double_t dz)
virtual void SetPx (Double_t px)
virtual void SetPy (Double_t py)
virtual void SetPz (Double_t pz)
virtual void SetDPx (Double_t dpx)
virtual void SetDPy (Double_t dpy)
virtual void SetDPz (Double_t dpz)
void SetQp (Double_t qp)
Protected Member Functions
ClassDef (FairTrackPar, 2)
Protected Attributes
Double_t fX
Double_t fY
Double_t fZ
Double_t fDX
Double_t fDY
Double_t fDZ
Double_t fPx
Double_t fPy
Double_t fPz
Double_t fDPx
Double_t fDPy
Double_t fDPz
Double_t fQp
Double_t fDQp
Int_t fq
Private Member Functions
void CalCov ()
Private Attributes
Double_t fLm
Double_t fPhi
Double_t fDLm
Double_t fDPhi
Double_t fX_sc
Double_t fY_sc
Double_t fZ_sc
Double_t fDX_sc
Double_t fDY_sc
Double_t fDZ_sc
Double_t fCovMatrix [15]
Double_t fCovMatrix66 [6][6]
Double_t cLm
Double_t sLm
Double_t cphi
Double_t sphi
Detailed Description
Definition at line 27 of file FairTrackParH.h.
Constructor & Destructor Documentation
FairTrackParH::FairTrackParH ()
Constructor
FairTrackParH::FairTrackParH (Double_t x, Double_t y, Double_t z, Double_t lambda, Double_t phi, Double_t qp, Double_t CovMatrix[15])
Constructor with track variables (in SC)
Definition at line 60 of file FairTrackParH.cxx.
References cLm, cphi, fCovMatrix, fCovMatrix66, fDLm, fDPhi, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, FairTrackPar::fDX, fDX_sc, FairTrackPar::fDY, fDY_sc, FairTrackPar::fDZ, fDZ_sc, fLm, fPhi, FairTrackPar::fPx, FairTrackPar::fPy, FairTrackPar::fPz, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromSCToMars(), FairTrackPar::fX, fX_sc, FairTrackPar::fY, fY_sc, FairTrackPar::fZ, fZ_sc, FairRunAna::GetField(), FairRunAna::Instance(), sLm, and sphi.
   : FairTrackPar(),
     fLm (lm),
     fPhi (phi),
     fDLm(0.),
     fDPhi(0.),
     fX_sc (x),
     fY_sc (y),
     fZ_sc (z),
     fDX_sc(0.),
     fDY_sc(0.),
     fDZ_sc(0.),
     cLm(TMath::Cos(lm)),
     sLm(TMath::Sin(lm)),
     cphi(TMath::Cos(phi)),
     sphi(TMath::Sin(phi))
 {
   /*
   fLm = lm;
   fPhi = phi;
   */
   fQp = qp;
   Double_t P  = TMath::Abs(1/fQp);
   //fq= int (P * fQp);
   fq = (int)TMath::Sign(1.0, fQp);
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=CovMatrix[i];
   }
   /*
   cLm= TMath::Cos(fLm);
   sLm= TMath::Sin(fLm);
   cphi= TMath::Cos(fPhi);
   sphi= TMath::Sin(fPhi);
   */
   fPx = P * cLm* cphi;
   fPy = P * cLm* sphi;
   fPz = P * sLm;
   /*
   fX_sc   = x;
   fY_sc   = y;
   fZ_sc   = z;
   */
   fX =fX_sc*cLm*cphi -fY_sc*sphi -fZ_sc*cphi*sLm;
   fY =fX_sc*cLm*sphi +fY_sc*cphi -fZ_sc*sphi*sLm;
   fZ =fX_sc*sLm +fZ_sc*cLm;
   fDQp  = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDLm  = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDPhi = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDX_sc   = 0.;
   fDY_sc   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDZ_sc   = TMath::Sqrt(fabs(fCovMatrix[14]));
   Double_t PD[3],RD[6][6],H[3],PC[3],RC[15];
   Int_t CH;
   PC[0]   = fQp;
   PC[1]   = fLm;
   PC[2]   = fPhi;
   for(Int_t i=0; i<15; i++)  {
     RC[i]=fCovMatrix[i];
   }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   FairGeaneUtil util;
   util.FromSCToMars(PC,RC,H,CH,PD,RD);
   // test
   fDPx = sqrt(fabs(RD[0][0]));
   fDPy = sqrt(fabs(RD[1][1]));
   fDPz = sqrt(fabs(RD[2][2]));
   fDX = sqrt(fabs(RD[3][3]));
   fDY = sqrt(fabs(RD[4][4]));
   fDZ = sqrt(fabs(RD[5][5]));
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
 }
FairTrackParH::FairTrackParH (TVector3 pos, TVector3 Mom, TVector3 posErr, TVector3 MomErr, Int_t q)
Constructor track parameters with position and momentum (in LAB)
Definition at line 154 of file FairTrackParH.cxx.
References cLm, cphi, fCovMatrix, fCovMatrix66, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDX, fDX_sc, FairTrackPar::fDY, fDY_sc, FairTrackPar::fDZ, fDZ_sc, fLm, fPhi, FairTrackPar::fPx, FairTrackPar::fPy, FairTrackPar::fPz, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromMarsToSC(), FairTrackPar::fX, fX_sc, FairTrackPar::fY, fY_sc, FairTrackPar::fZ, fZ_sc, FairRunAna::GetField(), FairRunAna::Instance(), Reset(), FairTrackPar::SetPx(), FairTrackPar::SetPy(), FairTrackPar::SetPz(), FairTrackPar::SetX(), FairTrackPar::SetY(), FairTrackPar::SetZ(), sLm, and sphi.
   : FairTrackPar(pos.x(),pos.y(),pos.z(),Mom.x(),Mom.y(),Mom.z(),q),
     fLm (0.),
     fPhi (0.),
     fDLm(0.),
     fDPhi(0.),
     fX_sc (0.),
     fY_sc (0.),
     fZ_sc (0.),
     fDX_sc(0.),
     fDY_sc(0.),
     fDZ_sc(0.),
     cLm(0.),
     sLm(0.),
     cphi(0.),
     sphi(0.)
 {
   Reset();
   SetPx(Mom.x());
   SetPy(Mom.y());
   SetPz(Mom.z());
   SetX(pos.x()); //x (lab)
   SetY(pos.y()); //y (lab)
   SetZ(pos.z()); //z (lab)
   fq= int (q/TMath::Abs(q));
   Double_t P =TMath::Sqrt(fPx*fPx+fPy*fPy+fPz*fPz);
   fLm    = TMath::ASin(fPz/P);
   fPhi   = TMath::ATan2(fPy,fPx);
   fQp    = fq/P;
   cLm= TMath::Cos(fLm);
   sLm= TMath::Sin(fLm);
   cphi= TMath::Cos(fPhi);
   sphi= TMath::Sin(fPhi);
   fDPx= MomErr.x(); //dpx
   fDPy= MomErr.y(); //dpy
   fDPz= MomErr.z(); //dpz
   fX_sc   = fX*cphi*cLm+ fY*cLm*sphi+fZ*sLm;
   fY_sc   = fY*cphi-fX*sphi;
   fZ_sc   = fZ*cLm-fY*sLm*sphi-fX*sLm*cphi;
   fDX   = posErr.x(); //dx (lab)
   fDY   = posErr.y(); //dy (lab)
   fDZ   = posErr.z(); //dz (lab)
   Double_t PD[3],RD[6][6],H[3],PC[3],RC[15];
   Int_t CH;
   PD[0]=Mom.x();
   PD[1]=Mom.y();
   PD[2]=Mom.z();
   for(Int_t i=0; i<6; i++)  for(Int_t j=0; j<6; j++)  {
       RD[i][j]=0;
     }
   RD[0][0] = fDPx * fDPx;
   RD[1][1] = fDPy * fDPy;
   RD[2][2] = fDPz * fDPz;
   RD[3][3] = fDX * fDX;
   RD[4][4] = fDY * fDY;
   RD[5][5] = fDZ * fDZ;
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   FairGeaneUtil util;
   util.FromMarsToSC(PD,RD,H,CH,PC,RC);
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=RC[i];
   }
   fDX_sc   = 0;
   fDY_sc   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDZ_sc   = TMath::Sqrt(fabs(fCovMatrix[14]));
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
 }
FairTrackParH::FairTrackParH (FairTrackPar & Trkbase)
copy Constructor
Definition at line 523 of file FairTrackParH.cxx.
References cLm, cphi, fCovMatrix, fCovMatrix66, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDX, fDX_sc, FairTrackPar::fDY, fDY_sc, FairTrackPar::fDZ, fDZ_sc, fLm, fPhi, FairTrackPar::fPx, FairTrackPar::fPy, FairTrackPar::fPz, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromMarsToSC(), FairTrackPar::fX, fX_sc, FairTrackPar::fY, fY_sc, FairTrackPar::fZ, fZ_sc, FairTrackPar::GetDPx(), FairTrackPar::GetDPy(), FairTrackPar::GetDPz(), FairTrackPar::GetDX(), FairTrackPar::GetDY(), FairTrackPar::GetDZ(), FairRunAna::GetField(), FairTrackPar::GetPx(), FairTrackPar::GetPy(), FairTrackPar::GetPz(), FairTrackPar::GetQ(), FairTrackPar::GetX(), FairTrackPar::GetY(), FairTrackPar::GetZ(), FairRunAna::Instance(), Reset(), sLm, and sphi.
   : FairTrackPar(Trkbase),
     fLm (0.),
     fPhi (0.),
     fDLm(0.),
     fDPhi(0.),
     fX_sc (0.),
     fY_sc (0.),
     fZ_sc (0.),
     fDX_sc(0.),
     fDY_sc(0.),
     fDZ_sc(0.),
     cLm(0.),
     sLm(0.),
     cphi(0.),
     sphi(0.)
 {
   cout << "FairTrackParH::FairTrackParH(FairTrackPar &Trkbase)"     << endl;
   Reset();
   fX = Trkbase.GetX();
   fY = Trkbase.GetY();
   fZ = Trkbase.GetZ();
   fPx = Trkbase.GetPx();
   fPy = Trkbase.GetPy();
   fPz = Trkbase.GetPz();
   fq = Trkbase.GetQ();
   Double_t fP=TMath::Sqrt(fPx*fPx +fPy*fPy +fPz*fPz );
   if (fP!=0) { fQp = fq/fP; }
   else { fQp=0; }
   fLm    = TMath::ASin(fPz/fP);
   fPhi   = TMath::ATan2(fPy,fPx);
   cLm= TMath::Cos(fLm);
   sLm= TMath::Sin(fLm);
   cphi= TMath::Cos(fPhi);
   sphi= TMath::Sin(fPhi);
   fDPx  = Trkbase.GetDPx();
   fDPy  = Trkbase.GetDPy();
   fDPz  = Trkbase.GetDPz();
   fDX   = Trkbase.GetDX();
   fDY   = Trkbase.GetDY();
   fDZ   = Trkbase.GetDZ();
   fX_sc   = fX*cphi*cLm+ fY*cLm*sphi+fZ*sLm;
   fY_sc   = fY*cphi-fX*sphi;
   fZ_sc   = fZ*cLm-fY*sLm*sphi-fX*sLm*cphi;
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=0;
   }
   Double_t PD[3],RD[6][6],H[3],PC[3],RC[15];
   Int_t CH;
   PD[0]=fPx;
   PD[1]=fPy;
   PD[2]=fPz;
   for(Int_t i=0; i<6; i++)  for(Int_t j=0; j<6; j++)  {
       RD[i][j]=0;
     }
   RD[0][0] = fDPx * fDPx;
   RD[1][1] = fDPy * fDPy;
   RD[2][2] = fDPz * fDPz;
   RD[3][3] = fDX * fDX;
   RD[4][4] = fDY * fDY;
   RD[5][5] = fDZ * fDZ;
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   FairGeaneUtil fUtil;
   fUtil.FromMarsToSC(PD,RD,H,CH,PC,RC);
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=RC[i];
   }
   fDX_sc   = 0;
   fDY_sc   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDZ_sc   = TMath::Sqrt(fabs(fCovMatrix[14]));
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
 }
FairTrackParH::FairTrackParH (FairTrackParP * parab, Int_t & ierr)
Definition at line 248 of file FairTrackParH.cxx.
References FairGeaneUtil::FromSDToSC(), FairTrackParP::GetCov(), FairRunAna::GetField(), FairTrackParP::GetJVer(), FairTrackParP::GetKVer(), FairTrackPar::GetPx(), FairTrackPar::GetPy(), FairTrackPar::GetPz(), FairTrackPar::GetQ(), FairTrackPar::GetQp(), FairTrackParP::GetSPU(), FairTrackParP::GetTV(), FairTrackParP::GetTW(), FairTrackPar::GetX(), FairTrackPar::GetY(), FairTrackPar::GetZ(), FairRunAna::Instance(), and SetTrackPar().
   : FairTrackPar(),
     fLm (0.),
     fPhi (0.),
     fDLm(0.),
     fDPhi(0.),
     fX_sc (0.),
     fY_sc (0.),
     fZ_sc (0.),
     fDX_sc(0.),
     fDY_sc(0.),
     fDZ_sc(0.),
     cLm(0.),
     sLm(0.),
     cphi(0.),
     sphi(0.)
 {
   // q/p, v', w' --> q/p, lambda, phi
   Double_t PD[3] = {parab->GetQp(), parab->GetTV(), parab->GetTW()};
   Double_t RD[15];
   parab->GetCov(RD);
   // retrieve field
   TVector3 xyz(parab->GetX(), parab->GetY(), parab->GetZ());
   Double_t H[3], pnt[3];
   pnt[0] = xyz.X();
   pnt[1] = xyz.Y();
   pnt[2] = xyz.Z();
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   Int_t CH  = parab->GetQ();
   Double_t DJ[3] = {parab->GetJVer().X(), parab->GetJVer().Y(), parab->GetJVer().Z()};
   Double_t DK[3] = {parab->GetKVer().X(), parab->GetKVer().Y(), parab->GetKVer().Z()};
   Double_t SPU = parab->GetSPU();
   Int_t IERR = 0;
   Double_t PC[3], RC[15];
   FairGeaneUtil util;
   util.FromSDToSC(PD, RD, H, CH, SPU, DJ, DK,
                   IERR, PC, RC);
   ierr = IERR;
   if(ierr == 0)  SetTrackPar(parab->GetX(), parab->GetY(), parab->GetZ(),
                                parab->GetPx(), parab->GetPy(), parab->GetPz(),
                                CH, RC);
   else { cout << "FairTrackParH(FairTrackParP *) contructor ERROR: CANNOT convert parabola to helix" << endl; }
 }
FairTrackParH::~FairTrackParH () virtual
Destructor
Definition at line 614 of file FairTrackParH.cxx.
 {
 }
Member Function Documentation
void FairTrackParH::CalCov () private
Calculate the cov. mat. for this helix
Definition at line 458 of file FairTrackParH.cxx.
References cLm, cphi, fCovMatrix, fDLm, fDPhi, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, fDX_sc, fDY_sc, fLm, fPhi, FairTrackPar::fPx, FairTrackPar::fPy, FairTrackPar::fPz, fX_sc, fY_sc, FairTrackPar::fZ, fZ_sc, FairTrackPar::GetDPx(), FairTrackPar::GetDPy(), FairTrackPar::GetDPz(), and sLm.
 {
   fDPx= GetDPx();
   fDPy= GetDPy();
   fDPz= GetDPz();
   Double_t fP =sqrt(fPx*fPx+fPy*fPy+fPz*fPz);
   Double_t fDP= (2*fPx*fDPx+2*fPy*fDPy+2*fPz*fDPz)/(2*fP); //dp
   fDQp = - fDP/(fP*fP);  // d(1/p)
   Double_t fDPQDLm = - sLm * cphi / fPx; // d(1/p)/dLambda
   Double_t fDPQDPhi= - cLm * TMath::Sin(fPhi) / fPx; // d(1/p)/dphi
   Double_t fDPQDX_sc  = (fX_sc*pow(fZ,3))/(fPz*pow(pow(fX_sc,2) + pow(fY_sc,2),2.5)*
                         pow(1 + pow(fZ_sc,2)/(pow(fX_sc,2) + pow(fY_sc,2)),1.5)) -
                         (fX_sc*fZ_sc)/(fPz*pow(pow(fX_sc,2) +
                                        pow(fY_sc,2),1.5)*TMath::Sqrt(1 + pow(fZ_sc,2)/(pow(fX_sc,2) + pow(fY_sc,2))));  //d(1/p)/dx
   Double_t fDPQDY_sc  = (fY_sc*pow(fZ_sc,3))/(fPz*pow(pow(fX_sc,2) + pow(fY_sc,2),2.5)*
                         pow(1 + pow(fZ_sc,2)/(pow(fX_sc,2) + pow(fY_sc,2)),1.5)) -
                         (fY_sc*fZ_sc)/(fPz*pow(pow(fX_sc,2) + pow(fY_sc,2),1.5)*
                                        TMath::Sqrt(1 + pow(fZ_sc,2)/(pow(fX_sc,2) + pow(fY_sc,2))));                  //d(1/p)/dy
   fDLm= (-((fPz*fDP)/pow(fP,2)) + fDPz/fP)/ TMath::Sqrt(1 - pow(fPz,2)/pow(fP,2)); // d(Lambda)
   Double_t fDLmDPhi =-((fPx*TMath::Tan(fPhi)/cphi)/
                        (fP*TMath::Sqrt(1 - (pow(fPx,2)*pow(1/cphi,2))/pow(fP,2)))); // dLambda/dPhi
   Double_t fDLmDX_sc = -((fX_sc*fZ_sc)/(pow(pow(fX_sc,2) + pow(fY_sc,2),1.5)*
                                         (1 + pow(fZ_sc,2)/(pow(fX_sc,2) + pow(fY_sc,2)))));                // dLambda/dX
   Double_t fDLmDY_sc = -((fY_sc*fZ_sc)/(pow(pow(fX_sc,2) + pow(fY_sc,2),1.5)*
                                         (1 + pow(fZ_sc,2)/(pow(fX_sc,2) + pow(fY_sc,2)))));               // dLambda/dY
   fDPhi=   (-((fPy*fDP/cLm)/pow(fP,2)) +
             (fDPy/cLm)/fP +(fPy*fDLm*TMath::Tan(fLm)/cLm)/fP) /TMath::Sqrt(1 - (pow(fPy,2)*pow(1/cLm,2))/pow(fP,2));  // d(Phi)
   Double_t fDPhiDx_sc = -(fY_sc/(pow(fX_sc,2)*(1 + pow(fY_sc,2)/pow(fX_sc,2))));  //   dPhi/dx
   Double_t fDPhiDy_sc = 1/(fX_sc*(1 + pow(fY_sc,2)/pow(fX_sc,2))); //    dPhi/dy
   Double_t fDXDY_sc = 1/TMath::Tan(fPhi);                              // dX/dY
   if(fDQp==0 && fDLm==0 && fDPhi ==0 ) {
     cout << "FairTrackParH::CalCov()  No Errors" << endl;
   } else {
     fCovMatrix[0]  =fDQp*fDQp;
     fCovMatrix[1]  =fDPQDLm;
     fCovMatrix[2]  =fDPQDPhi;
     fCovMatrix[3]  =fDPQDX_sc;
     fCovMatrix[4]  =fDPQDY_sc;
     fCovMatrix[5]  =fDLm*fDLm;
     fCovMatrix[6]  =fDLmDPhi;
     fCovMatrix[7]  =fDLmDX_sc;
     fCovMatrix[8]  =fDLmDY_sc;
     fCovMatrix[9]  =fDPhi*fDPhi;
     fCovMatrix[10] =fDPhiDx_sc;
     fCovMatrix[11] =fDPhiDy_sc;
     fCovMatrix[12] =fDX_sc*fDX_sc;
     fCovMatrix[13] =fDXDY_sc;
     fCovMatrix[14] =fDY_sc*fDY_sc;
   }
 }
FairTrackParH::ClassDef (FairTrackParH , 1)
FairTrackPar::ClassDef (FairTrackPar , 2) protected inherited
void FairTrackParH::GetCov (Double_t * Cov) inline
Get Error in Phi Get the coveriant matrix
Definition at line 64 of file FairTrackParH.h.
References fCovMatrix.
Referenced by FairTrackParP::FairTrackParP().
 {for(Int_t i=0; i<15; i++) { Cov[i]=fCovMatrix[i]; }}
void FairTrackParH::GetCovQ (Double_t * CovQ)
Definition at line 719 of file FairTrackParH.cxx.
References fCovMatrix, and FairTrackPar::fq.
Referenced by FairGeanePro::Propagate().
 {
   // return error matrix in 1/p instead of q/p
   for(int i = 0; i < 15; i++) {
     CovQ[i] = fCovMatrix[i];
     if(fq!=0) {
       if(i == 0) { CovQ[i] = CovQ[i] / (fq * fq); }
       if(i > 0 && i < 5) { CovQ[i] = CovQ[i] / fq; }
     }
   }
 }
Double_t FairTrackParH::GetDLambda ()
Definition at line 688 of file FairTrackParH.cxx.
References fDLm.
 {
   return fDLm;
 };
Double_t FairTrackParH::GetDPhi ()
Get Error in Lambda
Definition at line 692 of file FairTrackParH.cxx.
References fDPhi.
 {
   return fDPhi;
 };
virtual Double_t FairTrackPar::GetDPx () const inline virtual inherited
Definition at line 78 of file FairTrackPar.h.
References FairTrackPar::fDPx.
Referenced by CalCov(), FairTrackParH(), and SetTrackPar().
{
       return fDPx;
     };
virtual Double_t FairTrackPar::GetDPy () const inline virtual inherited
Definition at line 81 of file FairTrackPar.h.
References FairTrackPar::fDPy.
Referenced by CalCov(), FairTrackParH(), and SetTrackPar().
{
       return fDPy;
     };
virtual Double_t FairTrackPar::GetDPz () const inline virtual inherited
Definition at line 84 of file FairTrackPar.h.
References FairTrackPar::fDPz.
Referenced by CalCov(), FairTrackParH(), and SetTrackPar().
{
       return fDPz;
     };
virtual Double_t FairTrackPar::GetDQp () const inline virtual inherited
Definition at line 87 of file FairTrackPar.h.
References FairTrackPar::fDQp.
{
       return fDQp;
     };
virtual Double_t FairTrackPar::GetDX () const inline virtual inherited
Definition at line 51 of file FairTrackPar.h.
References FairTrackPar::fDX.
Referenced by FairTrackParH().
{
       return fDX;
     };
Double_t FairTrackParH::GetDX_sc ()
Definition at line 631 of file FairTrackParH.cxx.
References fDX_sc.
 {
   return fDX_sc;
 }
virtual Double_t FairTrackPar::GetDY () const inline virtual inherited
Definition at line 54 of file FairTrackPar.h.
References FairTrackPar::fDY.
Referenced by FairTrackParH().
{
       return fDY;
     };
Double_t FairTrackParH::GetDY_sc ()
Get dx in SC
Definition at line 636 of file FairTrackParH.cxx.
References fDY_sc.
 {
   return fDY_sc;
 }
virtual Double_t FairTrackPar::GetDZ () const inline virtual inherited
Definition at line 57 of file FairTrackPar.h.
References FairTrackPar::fDZ.
Referenced by FairTrackParH().
{
       return fDZ;
     };
Double_t FairTrackParH::GetDZ_sc ()
Get dy in SC
Definition at line 640 of file FairTrackParH.cxx.
References fDZ_sc.
 {
   return fDZ_sc;
 }
Double_t FairTrackParH::GetLambda () inline
Accessors
Definition at line 59 of file FairTrackParH.h.
References fLm.
Referenced by FairTrackParP::FairTrackParP().
 { return fLm; };
void FairTrackParH::GetMARSCov (Double_t Cov66[6][6]) inline
Definition at line 67 of file FairTrackParH.h.
References fCovMatrix66.
 {for(Int_t i=0; i<6; i++) for(Int_t j=0; j<6; j++) { Cov66[i][j] = fCovMatrix66[i][j]; }  }
virtual TVector3 FairTrackPar::GetMomentum () const inline virtual inherited
Definition at line 61 of file FairTrackPar.h.
References FairTrackPar::fPx, FairTrackPar::fPy, and FairTrackPar::fPz.
{
       return TVector3(fPx, fPy, fPz);
     };
Double_t FairTrackParH::GetPhi () inline
Definition at line 60 of file FairTrackParH.h.
References fPhi.
Referenced by FairTrackParP::FairTrackParP().
 { return fPhi; };
virtual TVector3 FairTrackPar::GetPosition () const inline virtual inherited
Accessors
Definition at line 34 of file FairTrackPar.h.
References FairTrackPar::fX, FairTrackPar::fY, and FairTrackPar::fZ.
{
       return TVector3(fX, fY, fZ);
     };
virtual Double_t FairTrackPar::GetPx () const inline virtual inherited
Definition at line 65 of file FairTrackPar.h.
References FairTrackPar::fPx.
Referenced by FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fPx;
     };
virtual Double_t FairTrackPar::GetPy () const inline virtual inherited
Definition at line 68 of file FairTrackPar.h.
References FairTrackPar::fPy.
Referenced by FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fPy;
     };
virtual Double_t FairTrackPar::GetPz () const inline virtual inherited
Definition at line 71 of file FairTrackPar.h.
References FairTrackPar::fPz.
Referenced by FairTrackParH(), FairGeanePro::Init(), and FairGeanePro::Propagate().
{
       return fPz;
     };
Int_t FairTrackPar::GetQ () const inline inherited
Definition at line 47 of file FairTrackPar.h.
References FairTrackPar::fq.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), and FairGeanePro::Propagate().
{
       return fq;
     };
virtual Double_t FairTrackPar::GetQp () const inline virtual inherited
Definition at line 74 of file FairTrackPar.h.
References FairTrackPar::fQp.
Referenced by FairTrackParH(), and FairTrackParP::FairTrackParP().
{
       return fQp;
     };
Double_t FairTrackParH::GetX () virtual
Get z in SC
Reimplemented from FairTrackPar.
Definition at line 645 of file FairTrackParH.cxx.
References cLm, cphi, FairTrackPar::fX, fX_sc, fY_sc, fZ_sc, sLm, and sphi.
Referenced by FairTrackParP::FairTrackParP(), and FairGeanePro::Propagate().
 {
   if(fX==0) {
     fX =fX_sc*cLm*cphi -fY_sc*sphi -fZ_sc*cphi*sLm;
   }
   return fX;
 }
Double_t FairTrackParH::GetX_sc () inline
Get dz in SC
Definition at line 71 of file FairTrackParH.h.
References fX_sc.
 {return fX_sc;}
Double_t FairTrackParH::GetY () virtual
Get X in Lab
Reimplemented from FairTrackPar.
Definition at line 653 of file FairTrackParH.cxx.
References cLm, cphi, fX_sc, FairTrackPar::fY, fY_sc, fZ_sc, sLm, and sphi.
Referenced by FairTrackParP::FairTrackParP(), and FairGeanePro::Propagate().
 {
   if(fY==0) {
     fY =fX_sc*cLm*sphi +fY_sc*cphi -fZ_sc*sphi*sLm;
   }
   return fY;
 }
Double_t FairTrackParH::GetY_sc () inline
Get x in SC
Definition at line 72 of file FairTrackParH.h.
References fY_sc.
 {return fY_sc;}
Double_t FairTrackParH::GetZ () virtual
Get Y in Lab
Reimplemented from FairTrackPar.
Definition at line 661 of file FairTrackParH.cxx.
References cLm, fX_sc, FairTrackPar::fZ, fZ_sc, and sLm.
Referenced by FairTrackParP::FairTrackParP(), and FairGeanePro::Propagate().
 {
   if(fZ==0) {
     fZ =fX_sc*sLm +fZ_sc*cLm;
   }
   return fZ;
 }
Double_t FairTrackParH::GetZ_sc () inline
Get y in SC
Definition at line 73 of file FairTrackParH.h.
References fZ_sc.
 {return fZ_sc;}
void FairTrackParH::Print (Option_t * option = "") const virtual
Output to screen
Reimplemented from FairTrackPar.
Definition at line 618 of file FairTrackParH.cxx.
References fCovMatrix, fLm, fPhi, FairTrackPar::fQp, FairTrackPar::fX, FairTrackPar::fY, and FairTrackPar::fZ.
 {
   cout << this<< endl;
   cout << "Position : (";
   cout.precision(2);
   cout << fX << ", " << fY << ", " << fZ << ")" << endl;
   cout << "Angles : Lambda = " << fLm << ", Phi = " << fPhi << endl;
   cout << "q/p = " << fQp << endl;
   for(Int_t i=0; i<15; i++) {
     cout << "fCovMatrix[" << i << "] = " <<  this << " " << fCovMatrix[i] << endl;
   }
 }
void FairTrackParH::Reset ()
Definition at line 697 of file FairTrackParH.cxx.
References cLm, cphi, fCovMatrix, fDLm, fDPhi, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, FairTrackPar::fDX, fDX_sc, FairTrackPar::fDY, fDY_sc, FairTrackPar::fDZ, fDZ_sc, fLm, fPhi, FairTrackPar::fPx, FairTrackPar::fPy, FairTrackPar::fPz, FairTrackPar::fq, FairTrackPar::fQp, FairTrackPar::fX, fX_sc, FairTrackPar::fY, fY_sc, FairTrackPar::fZ, fZ_sc, sLm, and sphi.
Referenced by FairTrackParH(), and SetTrackPar().
 {
   fLm=0;
   fPhi=0;
   fDLm=0;
   fDPhi=0;
   fX_sc= fY_sc= fZ_sc=0;
   fDX_sc= fDY_sc= fDZ_sc =0;
   cLm =sLm= cphi =sphi=0;
   for(Int_t i= 0; i<15; i++)  { fCovMatrix[i] =0; }
   //base class members
   fX= fY= fZ=0;
   fDX= fDY= fDZ=0;
   fPx= fPy= fPz=0;
   fDPx= fDPy= fDPz=0;
   fQp=fDQp=fq=0;
 }
void FairTrackParH::SetCov (Double_t * Cov) inline
Set z in SC
Definition at line 94 of file FairTrackParH.h.
References fCovMatrix.
 {for(Int_t i=0; i<15; i++) { fCovMatrix[i]=Cov[i]; }}
void FairTrackParH::SetDLambda (Double_t DLm) inline
Definition at line 88 of file FairTrackParH.h.
References fDLm.
 { fDLm = DLm; };
void FairTrackParH::SetDPhi (Double_t DPhi) inline
Definition at line 89 of file FairTrackParH.h.
References fDPhi.
 { fDPhi = DPhi; };
virtual void FairTrackPar::SetDPx (Double_t dpx) inline virtual inherited
Definition at line 123 of file FairTrackPar.h.
References FairTrackPar::fDPx.
{
       fDPx = dpx;
     };
virtual void FairTrackPar::SetDPy (Double_t dpy) inline virtual inherited
Definition at line 126 of file FairTrackPar.h.
References FairTrackPar::fDPy.
{
       fDPy = dpy;
     };
virtual void FairTrackPar::SetDPz (Double_t dpz) inline virtual inherited
Definition at line 129 of file FairTrackPar.h.
References FairTrackPar::fDPz.
{
       fDPz = dpz;
     };
virtual void FairTrackPar::SetDX (Double_t dx) inline virtual inherited
Definition at line 103 of file FairTrackPar.h.
References FairTrackPar::fDX.
{
       fDX  = dx;
     };
virtual void FairTrackPar::SetDY (Double_t dy) inline virtual inherited
Definition at line 106 of file FairTrackPar.h.
References FairTrackPar::fDY.
{
       fDY  = dy;
     };
virtual void FairTrackPar::SetDZ (Double_t dz) inline virtual inherited
Definition at line 109 of file FairTrackPar.h.
References FairTrackPar::fDZ.
{
       fDZ  = dz;
     };
void FairTrackParH::SetLambda (Double_t Lm) inline
Get Z in Lab Modifiers
Definition at line 85 of file FairTrackParH.h.
References fLm.
 { fLm = Lm; };
void FairTrackParH::SetPhi (Double_t Phi) inline
Definition at line 86 of file FairTrackParH.h.
References fPhi.
 { fPhi = Phi; };
virtual void FairTrackPar::SetPx (Double_t px) inline virtual inherited
Definition at line 113 of file FairTrackPar.h.
References FairTrackPar::fPx.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and SetTrackPar().
{
       fPx = px;
     };
virtual void FairTrackPar::SetPy (Double_t py) inline virtual inherited
Definition at line 116 of file FairTrackPar.h.
References FairTrackPar::fPy.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and SetTrackPar().
{
       fPy = py;
     };
virtual void FairTrackPar::SetPz (Double_t pz) inline virtual inherited
Definition at line 119 of file FairTrackPar.h.
References FairTrackPar::fPz.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and SetTrackPar().
{
       fPz = pz;
     };
void FairTrackPar::SetQp (Double_t qp) inline inherited
Definition at line 133 of file FairTrackPar.h.
References FairTrackPar::fQp.
{
       fQp = qp;
     };
void FairTrackParH::SetTrackPar (Double_t x, Double_t y, Double_t z, Double_t Px, Double_t Py, Double_t Pz, Int_t Q, Double_t CovMatrix[15])
Definition at line 302 of file FairTrackParH.cxx.
References cLm, cphi, fCovMatrix, fCovMatrix66, fDLm, fDPhi, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, FairTrackPar::fDX, fDX_sc, FairTrackPar::fDY, fDY_sc, FairTrackPar::fDZ, fDZ_sc, fLm, fPhi, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromSCToMars(), FairTrackPar::fX, fX_sc, FairTrackPar::fY, fY_sc, FairTrackPar::fZ, fZ_sc, FairTrackPar::GetDPx(), FairTrackPar::GetDPy(), FairTrackPar::GetDPz(), FairRunAna::GetField(), FairRunAna::Instance(), Reset(), FairTrackPar::SetPx(), FairTrackPar::SetPy(), FairTrackPar::SetPz(), FairTrackPar::SetX(), FairTrackPar::SetY(), FairTrackPar::SetZ(), sLm, and sphi.
Referenced by FairTrackParH(), and FairGeanePro::Propagate().
 {
   Reset();
   Double_t P =TMath::Sqrt(Px*Px+Py*Py+Pz*Pz);
   fLm    = TMath::ASin(Pz/P);
   fPhi   = TMath::ATan2(Py,Px);
   if (Q!=0) { fq = int (TMath::Abs(Q)/Q); }
   fQp    = fq/P;
   cLm= TMath::Cos(fLm);
   sLm= TMath::Sin(fLm);
   cphi= TMath::Cos(fPhi);
   sphi= TMath::Sin(fPhi);
   SetX(X);
   SetY(Y);
   SetZ(Z);
   SetPx(Px);
   SetPy(Py);
   SetPz(Pz);
   fX_sc   = fX*cphi*cLm+ fY*cLm*sphi+fZ*sLm;
   fY_sc   = fY*cphi-fX*sphi;
   fZ_sc   = fZ*cLm-fY*sLm*sphi-fX*sLm*cphi;
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=CovMatrix[i];
   }
   fDQp  = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDLm  = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDPhi = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDX_sc   = 0;
   fDY_sc   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDZ_sc   = TMath::Sqrt(fabs(fCovMatrix[14]));
   fDPx= GetDPx();
   fDPy= GetDPy();
   fDPz= GetDPz();
   Double_t PD[3],RD[6][6],H[3],PC[3],RC[15];
   Int_t CH;
   PC[0]   = fQp;
   PC[1]   = fLm;
   PC[2]   = fPhi;
   for(Int_t i=0; i<15; i++)  {
     RC[i]=fCovMatrix[i];
   }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   FairGeaneUtil util;
   util.FromSCToMars(PC,RC,H,CH,PD,RD);
   fDPx = sqrt(fabs(RD[0][0]));
   fDPy = sqrt(fabs(RD[1][1]));
   fDPz = sqrt(fabs(RD[2][2]));
   fDX = sqrt(fabs(RD[3][3]));
   fDY = sqrt(fabs(RD[4][4]));
   fDZ = sqrt(fabs(RD[5][5]));
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
 }
void FairTrackParH::SetTrackPar (Double_t x, Double_t y, Double_t z, Double_t pq, Double_t lm, Double_t phi, Double_t CovMatrix[15])
Definition at line 381 of file FairTrackParH.cxx.
References cLm, cphi, fCovMatrix, fCovMatrix66, fDLm, fDPhi, FairTrackPar::fDPx, FairTrackPar::fDPy, FairTrackPar::fDPz, FairTrackPar::fDQp, FairTrackPar::fDX, fDX_sc, FairTrackPar::fDY, fDY_sc, FairTrackPar::fDZ, fDZ_sc, fLm, fPhi, FairTrackPar::fPx, FairTrackPar::fPy, FairTrackPar::fPz, FairTrackPar::fq, FairTrackPar::fQp, FairGeaneUtil::FromSCToMars(), FairTrackPar::fX, fX_sc, FairTrackPar::fY, fY_sc, FairTrackPar::fZ, fZ_sc, FairTrackPar::GetDPx(), FairTrackPar::GetDPy(), FairTrackPar::GetDPz(), FairRunAna::GetField(), FairRunAna::Instance(), sLm, and sphi.
 {
   fLm = lm;
   fPhi = phi;
   fQp = qp;
   Double_t P  = TMath::Abs(1/fQp);
 // fq= int (P * fQp);
   fq = (int)TMath::Sign(1.0, fQp);
   for(Int_t i=0; i<15; i++)  {
     fCovMatrix[i]=CovMatrix[i];
   }
   cLm= TMath::Cos(fLm);
   sLm= TMath::Sin(fLm);
   cphi= TMath::Cos(fPhi);
   sphi= TMath::Sin(fPhi);
   fPx = P * cLm* cphi;
   fPy = P * cLm* sphi;
   fPz = P * sLm;
   fX_sc   = x;
   fY_sc   = y;
   fZ_sc   = z;
   fX =fX_sc*cLm*cphi -fY_sc*sphi -fZ_sc*cphi*sLm;
   fY =fX_sc*cLm*sphi +fY_sc*cphi -fZ_sc*sphi*sLm;
   fZ =fX_sc*sLm +fZ_sc*cLm;
   fDQp  = TMath::Sqrt(fabs(fCovMatrix[0]));
   fDLm  = TMath::Sqrt(fabs(fCovMatrix[5]));
   fDPhi = TMath::Sqrt(fabs(fCovMatrix[9]));
   fDX_sc   = 0;
   fDY_sc   = TMath::Sqrt(fabs(fCovMatrix[12]));
   fDZ_sc   = TMath::Sqrt(fabs(fCovMatrix[14]));
   fDPx= GetDPx() ;
   fDPy= GetDPy() ;
   fDPz= GetDPz() ;
   Double_t PD[3],RD[6][6],H[3],PC[3],RC[15];
   Int_t CH;
   PC[0]   = fQp;
   PC[1]   = fLm;
   PC[2]   = fPhi;
   for(Int_t i=0; i<15; i++)  {
     RC[i]=fCovMatrix[i];
   }
   // retrieve field
   Double_t pnt[3];
   pnt[0] = fX;
   pnt[1] = fY;
   pnt[2] = fZ;
   FairRunAna* fRun = FairRunAna::Instance();
   fRun->GetField()->GetFieldValue(pnt, H);
   CH=fq;
   FairGeaneUtil util;
   util.FromSCToMars(PC,RC,H,CH,PD,RD);
   // test
   fDPx = sqrt(fabs(RD[0][0]));
   fDPy = sqrt(fabs(RD[1][1]));
   fDPz = sqrt(fabs(RD[2][2]));
   fDX = sqrt(fabs(RD[3][3]));
   fDY = sqrt(fabs(RD[4][4]));
   fDZ = sqrt(fabs(RD[5][5]));
   for(int i = 0; i < 6; i++) for(int j = 0; j < 6; j++) { fCovMatrix66[i][j] = RD[i][j]; }
 }
virtual void FairTrackPar::SetX (Double_t x) inline virtual inherited
Definition at line 93 of file FairTrackPar.h.
References FairTrackPar::fX.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and SetTrackPar().
{
       fX  = x;
     };
void FairTrackParH::SetX_sc (Double_t x) inline
Definition at line 91 of file FairTrackParH.h.
References fX_sc.
 {fX_sc =x;}
virtual void FairTrackPar::SetY (Double_t y) inline virtual inherited
Definition at line 96 of file FairTrackPar.h.
References FairTrackPar::fY.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and SetTrackPar().
{
       fY  = y;
     };
void FairTrackParH::SetY_sc (Double_t y) inline
Set x in SC
Definition at line 92 of file FairTrackParH.h.
References fY_sc.
 {fY_sc =y;}
virtual void FairTrackPar::SetZ (Double_t z) inline virtual inherited
Definition at line 99 of file FairTrackPar.h.
References FairTrackPar::fZ.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and SetTrackPar().
{
       fZ  = z;
     };
void FairTrackParH::SetZ_sc (Double_t z) inline
Set y in SC
Definition at line 93 of file FairTrackParH.h.
References fZ_sc.
 {fZ_sc =z;}
Member Data Documentation
Double_t FairTrackParH::cLm private
just to simplify a little bit typing the equations cLm = Cos(Lambda), sLm = Sin(Lambda), cphi = cos(Phi), sphi = Sin(Phi) ! do not streame this to the file
Definition at line 134 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetX(), GetY(), GetZ(), Reset(), and SetTrackPar().
Double_t FairTrackParH::cphi private
Definition at line 134 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetX(), GetY(), Reset(), and SetTrackPar().
Double_t FairTrackParH::fCovMatrix[15] private
Covariant matrix in SC
Definition at line 120 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetCov(), GetCovQ(), Print(), Reset(), SetCov(), and SetTrackPar().
Double_t FairTrackParH::fCovMatrix66[6][6] private
Definition at line 122 of file FairTrackParH.h.
Referenced by FairTrackParH(), GetMARSCov(), and SetTrackPar().
Double_t FairTrackParH::fDLm private
Error in Lambda
Definition at line 112 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetDLambda(), Reset(), SetDLambda(), and SetTrackPar().
Double_t FairTrackParH::fDPhi private
Error in Phi
Definition at line 114 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetDPhi(), Reset(), SetDPhi(), and SetTrackPar().
Double_t FairTrackPar::fDPx protected inherited
Error in momentum [GeV]
Definition at line 150 of file FairTrackPar.h.
Referenced by CalCov(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetDPx(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetDPx(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackPar::fDPy protected inherited
Definition at line 150 of file FairTrackPar.h.
Referenced by CalCov(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetDPy(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetDPy(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackPar::fDPz protected inherited
Definition at line 150 of file FairTrackPar.h.
Referenced by CalCov(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetDPz(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetDPz(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackPar::fDQp protected inherited
Error in charge over momentum [1/GeV]
Definition at line 156 of file FairTrackPar.h.
Referenced by CalCov(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetDQp(), FairTrackParP::Reset(), Reset(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackPar::fDX protected inherited
Error in position of track [cm]
Definition at line 144 of file FairTrackPar.h.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetDX(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetDX(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackParH::fDX_sc private
Errors for X,Y,Z (in SC system)
Definition at line 118 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetDX_sc(), Reset(), and SetTrackPar().
Double_t FairTrackPar::fDY protected inherited
Definition at line 144 of file FairTrackPar.h.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetDY(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetDY(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackParH::fDY_sc private
Definition at line 118 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetDY_sc(), Reset(), and SetTrackPar().
Double_t FairTrackPar::fDZ protected inherited
Definition at line 144 of file FairTrackPar.h.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetDZ(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetDZ(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackParH::fDZ_sc private
Definition at line 118 of file FairTrackParH.h.
Referenced by FairTrackParH(), GetDZ_sc(), Reset(), and SetTrackPar().
Double_t FairTrackParH::fLm private
fLm = Dip angle
Definition at line 108 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetLambda(), Print(), Reset(), SetLambda(), and SetTrackPar().
Double_t FairTrackParH::fPhi private
fPhi = azimuthal angle
Definition at line 110 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetPhi(), Print(), Reset(), SetPhi(), and SetTrackPar().
Double_t FairTrackPar::fPx protected inherited
momentum [GeV]
Definition at line 147 of file FairTrackPar.h.
Referenced by CalCov(), FairTrackPar::FairTrackPar(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetMomentum(), FairTrackPar::GetPx(), FairTrackPar::Print(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetPx(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackPar::fPy protected inherited
Definition at line 147 of file FairTrackPar.h.
Referenced by CalCov(), FairTrackPar::FairTrackPar(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetMomentum(), FairTrackPar::GetPy(), FairTrackPar::Print(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetPy(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackPar::fPz protected inherited
Definition at line 147 of file FairTrackPar.h.
Referenced by CalCov(), FairTrackPar::FairTrackPar(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetMomentum(), FairTrackPar::GetPz(), FairTrackPar::Print(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetPz(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Int_t FairTrackPar::fq protected inherited
charge
Definition at line 159 of file FairTrackPar.h.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), GetCovQ(), FairTrackParP::GetCovQ(), FairTrackPar::GetQ(), FairTrackParP::Reset(), Reset(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackPar::fQp protected inherited
Charge over momentum [1/GeV]
Definition at line 153 of file FairTrackPar.h.
Referenced by FairTrackPar::FairTrackPar(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetQp(), Print(), FairTrackParP::Print(), FairTrackParP::Reset(), Reset(), FairTrackPar::SetQp(), FairTrackParP::SetTrackPar(), and SetTrackPar().
Double_t FairTrackPar::fX protected inherited
Position of track [cm]
Definition at line 135 of file FairTrackPar.h.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetPosition(), FairTrackPar::GetX(), GetX(), FairTrackPar::Print(), Print(), FairTrackParP::Print(), FairTrackParP::Reset(), Reset(), FairTrackParP::SetTrackPar(), SetTrackPar(), and FairTrackPar::SetX().
Double_t FairTrackParH::fX_sc private
Points coordinates in SC system
Definition at line 116 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetX(), GetX_sc(), GetY(), GetZ(), Reset(), SetTrackPar(), and SetX_sc().
Double_t FairTrackPar::fY protected inherited
Definition at line 135 of file FairTrackPar.h.
Referenced by FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetPosition(), FairTrackPar::GetY(), GetY(), FairTrackPar::Print(), Print(), FairTrackParP::Print(), FairTrackParP::Reset(), Reset(), FairTrackParP::SetTrackPar(), SetTrackPar(), and FairTrackPar::SetY().
Double_t FairTrackParH::fY_sc private
Definition at line 116 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetX(), GetY(), GetY_sc(), Reset(), SetTrackPar(), and SetY_sc().
Double_t FairTrackPar::fZ protected inherited
Definition at line 135 of file FairTrackPar.h.
Referenced by CalCov(), FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackPar::GetPosition(), FairTrackPar::GetZ(), GetZ(), FairTrackPar::Print(), Print(), FairTrackParP::Print(), FairTrackParP::Reset(), Reset(), FairTrackParP::SetTrackPar(), SetTrackPar(), and FairTrackPar::SetZ().
Double_t FairTrackParH::fZ_sc private
Definition at line 116 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetX(), GetY(), GetZ(), GetZ_sc(), Reset(), SetTrackPar(), and SetZ_sc().
Double_t FairTrackParH::sLm private
Definition at line 134 of file FairTrackParH.h.
Referenced by CalCov(), FairTrackParH(), GetX(), GetY(), GetZ(), Reset(), and SetTrackPar().
Double_t FairTrackParH::sphi private
Definition at line 134 of file FairTrackParH.h.
Referenced by FairTrackParH(), GetX(), GetY(), Reset(), and SetTrackPar().
The documentation for this class was generated from the following files:
FairTrackParH.h
FairTrackParH.cxx