FairRoot: FairGeoVolume Class Reference
FairGeoVolume Class Reference
#include <FairGeoVolume.h>
Public Member Functions
FairGeoVolume ()
FairGeoVolume (FairGeoVolume &)
virtual ~FairGeoVolume ()
const TString & getName () const
const TString & getShape () const
const TString & getMother () const
FairGeoTransform & getTransform ()
FairGeoTransform & getLabTransform ()
FairGeoMedium & getMedium ()
Int_t getNumPoints ()
FairGeoVector * getPoint (const Int_t n)
void setName (const Text_t *s)
void setVolumePar (FairGeoVolume &)
void setShape (const Text_t *s)
void setMother (const Text_t *s)
void createPoints (const Int_t)
void setPoint (const Int_t, const Double_t, const Double_t, const Double_t)
void setPoint (const Int_t, const FairGeoVector &)
virtual void clear ()
virtual void print ()
virtual void setHadFormat (Int_t i)
Double_t getVolParameter (Int_t nPoint, Int_t pos)
Int_t getMCid ()
void setMCid (Int_t MCid)
Protected Attributes
TString shape
TString mother
TObjArray * points
FairGeoTransform transform
FairGeoTransform fLabTransform
FairGeoMedium fMedium
Int_t nPoints
Int_t fHadFormat
Int_t fgMCid
Private Member Functions
FairGeoVolume & operator= (const FairGeoVolume &)
Detailed Description
basic geometry parameters of a volume
Author
Ilse koenig
Definition at line 27 of file FairGeoVolume.h.
Constructor & Destructor Documentation
FairGeoVolume::FairGeoVolume () inline
Volume Id given by MC
Definition at line 73 of file FairGeoVolume.h.
   :TNamed(),
    shape(""),
    mother(""),
    points(NULL),
    transform(FairGeoTransform()),
    fLabTransform(FairGeoTransform()),
    fMedium(0),
    nPoints(0),
    fHadFormat(0),
    fgMCid(0)
 {
 }
FairGeoVolume::FairGeoVolume (FairGeoVolume &)
FairGeoVolume::~FairGeoVolume () virtual
Definition at line 149 of file FairGeoVolume.cxx.
References points.
 {
   if (points) {
     points->Delete();
     delete points;
     points=0;
   }
 }
Member Function Documentation
void FairGeoVolume::clear (void) virtual
Reimplemented in FairGeoNode, and FairGeoCompositeVolume.
Definition at line 112 of file FairGeoVolume.cxx.
References FairGeoTransform::clear(), mother, nPoints, points, shape, and transform.
Referenced by FairGeoCompositeVolume::clear(), and FairGeoNode::clear().
 {
   // clears the volume
   // deletes the points
   shape="";
   mother="";
   if (points) { points->Delete(); }
   delete points;
   points=0;
   nPoints=0;
   transform.clear();
 }
void FairGeoVolume::createPoints (const Int_t n)
Definition at line 68 of file FairGeoVolume.cxx.
References nPoints, and points.
Referenced by FairGeoOldAsciiIo::calculateShapePoints(), FairGeoTorus::readPoints(), FairGeoTube::readPoints(), FairGeoTubs::readPoints(), FairGeoCons::readPoints(), FairGeoCone::readPoints(), FairGeoEltu::readPoints(), FairGeoPgon::readPoints(), FairGeoPcon::readPoints(), FairGeoSphe::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), setVolumePar(), and FairGeoNode::setVolumePar().
 {
   // Creates n Points (objects of class FairGeoVector).
   // If the array exists already and the size is different from n it is
   // deleted and recreated with the new size n.
   // If n==0 the points are deleted.
   if (n!=nPoints) {
     nPoints=n;
     if (n>0) {
       if (points!=0) {
         points->Delete();
         delete points;
       }
       points=new TObjArray(n);
       for(Int_t i=0; i<n; i++) { points->AddAt(new FairGeoVector(),i); }
     } else {
       if (points) { points->Delete(); }
       delete points;
       points=0;
     }
   }
 }
FairGeoTransform& FairGeoVolume::getLabTransform () inline
Definition at line 50 of file FairGeoVolume.h.
References fLabTransform.
 { return fLabTransform;}
Int_t FairGeoVolume::getMCid () inline
Definition at line 65 of file FairGeoVolume.h.
References fgMCid.
Referenced by FairModule::ProcessNodes().
 {return fgMCid;}
FairGeoMedium& FairGeoVolume::getMedium () inline
Definition at line 51 of file FairGeoVolume.h.
References fMedium.
 { return fMedium;}
const TString& FairGeoVolume::getMother () const inline
Definition at line 48 of file FairGeoVolume.h.
References mother.
Referenced by FairGeoNode::compare(), and setVolumePar().
 { return mother; }
const TString& FairGeoVolume::getName () const inline
Definition at line 46 of file FairGeoVolume.h.
 { return fName; }
Int_t FairGeoVolume::getNumPoints () inline
Definition at line 52 of file FairGeoVolume.h.
References nPoints.
Referenced by FairGeoPcon::calcVoluParam(), FairGeoPgon::calcVoluParam(), FairGeoNode::compare(), FairGeoPcon::printPoints(), FairGeoPgon::printPoints(), FairGeoBasicShape::printPoints(), FairGeoTubs::readPoints(), FairGeoTorus::readPoints(), FairGeoTube::readPoints(), FairGeoCons::readPoints(), FairGeoPcon::readPoints(), FairGeoEltu::readPoints(), FairGeoPgon::readPoints(), FairGeoSphe::readPoints(), FairGeoCone::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), setVolumePar(), FairGeoNode::setVolumePar(), FairGeoPgon::writePoints(), FairGeoPcon::writePoints(), and FairGeoBasicShape::writePoints().
 { return nPoints;}
FairGeoVector * FairGeoVolume::getPoint (const Int_t n) inline
Definition at line 88 of file FairGeoVolume.h.
References nPoints, and points.
Referenced by FairGeoBrik::calcVoluParam(), FairGeoTube::calcVoluParam(), FairGeoTubs::calcVoluParam(), FairGeoTorus::calcVoluParam(), FairGeoTrd1::calcVoluParam(), FairGeoTrap::calcVoluParam(), FairGeoCons::calcVoluParam(), FairGeoEltu::calcVoluParam(), FairGeoCone::calcVoluParam(), FairGeoPcon::calcVoluParam(), FairGeoPgon::calcVoluParam(), FairGeoSphe::calcVoluParam(), FairGeoBrik::calcVoluPosition(), FairGeoTube::calcVoluPosition(), FairGeoTubs::calcVoluPosition(), FairGeoTrap::calcVoluPosition(), FairGeoTrd1::calcVoluPosition(), FairGeoCons::calcVoluPosition(), FairGeoEltu::calcVoluPosition(), FairGeoCone::calcVoluPosition(), FairGeoNode::compare(), FairGeoTorus::printPoints(), FairGeoAssembly::printPoints(), FairGeoTube::printPoints(), FairGeoTubs::printPoints(), FairGeoCons::printPoints(), FairGeoCone::printPoints(), FairGeoSphe::printPoints(), FairGeoEltu::printPoints(), FairGeoPcon::printPoints(), FairGeoPgon::printPoints(), FairGeoBasicShape::printPoints(), FairGeoSet::readVolumeParams(), setVolumePar(), FairGeoNode::setVolumePar(), FairGeoTube::writePoints(), FairGeoTubs::writePoints(), FairGeoAssembly::writePoints(), FairGeoTorus::writePoints(), FairGeoCons::writePoints(), FairGeoEltu::writePoints(), FairGeoSphe::writePoints(), FairGeoCone::writePoints(), FairGeoPcon::writePoints(), FairGeoPgon::writePoints(), and FairGeoBasicShape::writePoints().
 {
   if (points && n<nPoints) { return (FairGeoVector*)points->At(n); }
   else { return 0; }
 }
const TString& FairGeoVolume::getShape () const inline
Definition at line 47 of file FairGeoVolume.h.
References shape.
Referenced by FairGeoNode::compare(), FairGeoRootBuilder::createNode(), FairGeoShapes::selectShape(), and setVolumePar().
 { return shape; }
FairGeoTransform& FairGeoVolume::getTransform () inline
Definition at line 49 of file FairGeoVolume.h.
References transform.
Referenced by FairGeoNode::calcModuleTransform(), FairGeoNode::calcRefPos(), FairGeoBasicShape::calcVoluPosition(), FairGeoNode::compare(), FairGeoOldAsciiIo::read(), FairGeoSet::readVolumeParams(), setVolumePar(), and FairGeoNode::setVolumePar().
 { return transform; }
Double_t FairGeoVolume::getVolParameter (Int_t nPoint, Int_t pos)
Definition at line 141 of file FairGeoVolume.cxx.
References FairGeoVector::getValues(), and points.
 {
   FairGeoVector* vec = (FairGeoVector*) points->At( nPoint );
   if ( vec ) { return vec->getValues( pos ); }
   else { return -1; }
 }
FairGeoVolume& FairGeoVolume::operator= (const FairGeoVolume &) private
void FairGeoVolume::print () virtual
Reimplemented in FairGeoNode, and FairGeoCompositeVolume.
Definition at line 125 of file FairGeoVolume.cxx.
References fLabTransform, mother, nPoints, points, FairGeoTransform::print(), and shape.
Referenced by FairGeoCompositeVolume::print(), and FairGeoNode::print().
 {
   // prints all parameters of a volume
   cout<<"Volume: " <<((const char*)fName)<<"  Shape: "<<((const char*)shape)<<"  Mother: "
       <<((const char*)mother)<<'\n';
   cout << "Points definition " << endl;
   if (points) {
     for (Int_t i=0; i<nPoints; i++) {
       cout<<(*((FairGeoVector*)points->At(i)));
     }
   }
   cout << "Lab Transform " << endl;
   fLabTransform.print();
   cout<<'\n';
 }
virtual void FairGeoVolume::setHadFormat (Int_t i) inline virtual
Definition at line 63 of file FairGeoVolume.h.
Referenced by FairGeoRootBuilder::createNode().
 { fHadFormat=i;}
void FairGeoVolume::setMCid (Int_t MCid) inline
Definition at line 66 of file FairGeoVolume.h.
Referenced by FairDetector::Initialize().
 {fgMCid=MCid;}
void FairGeoVolume::setMother (const Text_t * s) inline
Definition at line 106 of file FairGeoVolume.h.
References mother.
 {
   mother=s;
   mother.ToUpper();
 }
void FairGeoVolume::setName (const Text_t * s) inline
Definition at line 94 of file FairGeoVolume.h.
 {
   fName=s;
   fName.ToUpper();
 }
void FairGeoVolume::setPoint (const Int_t n, const Double_t x, const Double_t y, const Double_t z)
Definition at line 91 of file FairGeoVolume.cxx.
References nPoints, points, FairGeoVector::setX(), FairGeoVector::setY(), and FairGeoVector::setZ().
Referenced by FairGeoOldAsciiIo::calculateShapePoints(), FairGeoTorus::readPoints(), FairGeoTube::readPoints(), FairGeoTubs::readPoints(), FairGeoCons::readPoints(), FairGeoCone::readPoints(), FairGeoEltu::readPoints(), FairGeoPgon::readPoints(), FairGeoPcon::readPoints(), FairGeoSphe::readPoints(), FairGeoBasicShape::readPoints(), FairGeoSet::readVolumeParams(), setVolumePar(), and FairGeoNode::setVolumePar().
 {
   // set the 3 values of the point with index n
   if (points && n<nPoints) {
     FairGeoVector* v=(FairGeoVector*)points->At(n);
     v->setX(x);
     v->setY(y);
     v->setZ(z);
   }
 }
void FairGeoVolume::setPoint (const Int_t n, const FairGeoVector & p)
Definition at line 103 of file FairGeoVolume.cxx.
References nPoints, and points.
 {
   // sets point with index n by copying the 3 components of point p
   if (points && n<nPoints) {
     FairGeoVector& v=*((FairGeoVector*)points->At(n));
     v=p;
   }
 }
void FairGeoVolume::setShape (const Text_t * s) inline
Definition at line 100 of file FairGeoVolume.h.
References shape.
 {
   shape=s;
   shape.ToUpper();
 }
void FairGeoVolume::setVolumePar (FairGeoVolume & r)
Definition at line 57 of file FairGeoVolume.cxx.
References createPoints(), getMother(), getNumPoints(), getPoint(), getShape(), getTransform(), mother, nPoints, setPoint(), shape, and transform.
 {
   // copies all volume parameters except the name
   shape=r.getShape();
   mother=r.getMother();
   Int_t n=r.getNumPoints();
   createPoints(n);
   for (Int_t i=0; i<nPoints; i++) { setPoint(i,*(r.getPoint(i))); }
   transform=r.getTransform();
 }
Member Data Documentation
Int_t FairGeoVolume::fgMCid protected
Definition at line 40 of file FairGeoVolume.h.
Referenced by getMCid().
Int_t FairGeoVolume::fHadFormat protected
number of points
Definition at line 39 of file FairGeoVolume.h.
Referenced by FairGeoNode::getCopyNo().
FairGeoTransform FairGeoVolume::fLabTransform protected
transformation relative to the mother system
Definition at line 36 of file FairGeoVolume.h.
Referenced by FairGeoNode::calcLabTransform(), getLabTransform(), and print().
FairGeoMedium FairGeoVolume::fMedium protected
transformation to the LAB system;
Definition at line 37 of file FairGeoVolume.h.
Referenced by FairGeoNode::calcLabTransform(), and getMedium().
TString FairGeoVolume::mother protected
eant shape of the volume
Definition at line 33 of file FairGeoVolume.h.
Referenced by clear(), FairGeoNode::compare(), getMother(), print(), setMother(), FairGeoNode::setMother(), setVolumePar(), and FairGeoNode::write().
Int_t FairGeoVolume::nPoints protected
medium properties
Definition at line 38 of file FairGeoVolume.h.
Referenced by clear(), FairGeoNode::compare(), createPoints(), FairGeoNode::FairGeoNode(), getNumPoints(), getPoint(), print(), setPoint(), setVolumePar(), FairGeoNode::setVolumePar(), and FairGeoNode::~FairGeoNode().
TObjArray* FairGeoVolume::points protected
Name of the mother volume
Definition at line 34 of file FairGeoVolume.h.
Referenced by clear(), FairGeoNode::compare(), createPoints(), FairGeoNode::FairGeoNode(), getPoint(), getVolParameter(), print(), setPoint(), FairGeoNode::write(), FairGeoNode::~FairGeoNode(), and ~FairGeoVolume().
TString FairGeoVolume::shape protected
Definition at line 32 of file FairGeoVolume.h.
Referenced by clear(), FairGeoNode::compare(), getShape(), print(), setShape(), FairGeoNode::setShape(), setVolumePar(), and FairGeoNode::write().
FairGeoTransform FairGeoVolume::transform protected
array of points (type FairGeoVector)
Definition at line 35 of file FairGeoVolume.h.
Referenced by FairGeoNode::calcLabTransform(), FairGeoNode::calcModuleTransform(), clear(), FairGeoNode::compare(), getTransform(), FairGeoNode::setLabTransform(), setVolumePar(), FairGeoNode::setVolumePar(), and FairGeoNode::write().
The documentation for this class was generated from the following files:
FairGeoVolume.h
FairGeoVolume.cxx