FairRoot: FairTutorialDet4 Class Reference
FairTutorialDet4 Class Reference
#include <FairTutorialDet4.h>
Public Member Functions
FairTutorialDet4 (const char *Name, Bool_t Active)
FairTutorialDet4 ()
virtual ~FairTutorialDet4 ()
virtual void Initialize ()
virtual void InitParContainers ()
virtual Bool_t ProcessHits (FairVolume *v=0)
virtual void Register ()
virtual TClonesArray * GetCollection (Int_t iColl) const
virtual void Reset ()
void ConstructGeometry ()
void ModifyGeometry ()
void SetParContainers ()
FairTutorialDet4Point * AddHit (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t time, Double_t length, Double_t eLoss)
virtual void CopyClones (TClonesArray *cl1, TClonesArray *cl2, Int_t offset)
virtual void SetSpecialPhysicsCuts ()
virtual void EndOfEvent ()
virtual void FinishPrimary ()
virtual void FinishRun ()
virtual void BeginPrimary ()
virtual void PostTrack ()
virtual void PreTrack ()
virtual void BeginEvent ()
void SetModifyGeometry (Bool_t val)
virtual void FinishEvent ()
void SaveGeoParams ()
Int_t GetDetId ()
virtual void Print (Option_t *option="") const
virtual void SetGeometryFileName (TString fname, TString geoVer="0")
virtual TString GetGeometryFileName ()
virtual TString GetGeometryFileVer ()
virtual void ConstructOpGeometry ()
virtual void ConstructRootGeometry ()
template<class T , class U >
void ConstructASCIIGeometry (T dataType1, TString containerName="", U datatype2=NULL)
virtual void ConstructGDMLGeometry (TGeoMatrix *)
virtual FairModule * CloneModule () const
virtual void BeginWorkerRun () const
virtual void FinishWorkerRun () const
virtual void ExpandNode (TGeoNode *Node)
virtual void ExpandNodeForGDML (TGeoNode *)
virtual Int_t getVolId (const TString &vname) const
Int_t GetModId ()
void SetVerboseLevel (Int_t level)
Bool_t IsActive ()
void SetModId (Int_t id)
void SetMotherVolume (TString volName)
void ProcessNodes (TList *aList)
TList * GetListOfGeoPar ()
FairVolume * getFairVolume (FairGeoNode *fNode)
void AddSensitiveVolume (TGeoVolume *v)
Public Attributes
TString fMotherVolumeName
Static Public Attributes
static FairVolumeList * vList =0
static Int_t fNbOfVolumes =0
static TRefArray * svList =0
static TArrayI * volNumber =0
Protected Attributes
Int_t fDetId
FairLogger * fLogger
TString fgeoVer
TString fgeoName
Int_t fModId
Bool_t fActive
Int_t fNbOfSensitiveVol
Int_t fVerboseLevel
TList * flGeoPar
Bool_t kGeoSaved
list of Detector Geometry parameters
Private Member Functions
void ConstructASCIIGeometry ()
Bool_t CheckIfSensitive (std::string name)
void ModifyGeometryBySymlink ()
void ModifyGeometryByFullPath ()
FairTutorialDet4 (const FairTutorialDet4 &)
FairTutorialDet4 & operator= (const FairTutorialDet4 &)
Private Attributes
Int_t fTrackID
Int_t fVolumeID
track index
TLorentzVector fPos
volume id
TLorentzVector fMom
position at entrance
Double32_t fTime
momentum at entrance
Double32_t fLength
time
Double32_t fELoss
length
TClonesArray * fFairTutorialDet4PointCollection
energy loss
FairTutorialDet4GeoHandler * fGeoHandler
FairTutorialDet4MisalignPar * fMisalignPar
Int_t fNrOfDetectors
TArrayD fShiftX
TArrayD fShiftY
TArrayD fShiftZ
TArrayD fRotX
TArrayD fRotY
TArrayD fRotZ
Bool_t fModifyGeometry
Detailed Description
Definition at line 26 of file FairTutorialDet4.h.
Constructor & Destructor Documentation
FairTutorialDet4::FairTutorialDet4 (const char * Name, Bool_t Active)
Name : Detector Name Active: kTRUE for active detectors (ProcessHits() will be called) kFALSE for inactive detectors
Definition at line 63 of file FairTutorialDet4.cxx.
   : FairDetector(name, active, kTutDet),
     fTrackID(-1),
     fVolumeID(-1),
     fPos(),
     fMom(),
     fTime(-1.),
     fLength(-1.),
     fELoss(-1),
     fFairTutorialDet4PointCollection(new TClonesArray("FairTutorialDet4Point")),
     fGeoHandler(new FairTutorialDet4GeoHandler()),
     fMisalignPar(NULL),
     fNrOfDetectors(-1),
     fShiftX(),
     fShiftY(),
     fShiftZ(),
     fRotX(),
     fRotY(),
     fRotZ(),
     fModifyGeometry(kFALSE)
 {
 }
FairTutorialDet4::FairTutorialDet4 ()
default constructor
Definition at line 40 of file FairTutorialDet4.cxx.
   : FairDetector("TutorialDet", kTRUE, kTutDet),
     fTrackID(-1),
     fVolumeID(-1),
     fPos(),
     fMom(),
     fTime(-1.),
     fLength(-1.),
     fELoss(-1),
     fFairTutorialDet4PointCollection(new TClonesArray("FairTutorialDet4Point")),
     fGeoHandler(new FairTutorialDet4GeoHandler()),
     fMisalignPar(NULL),
     fNrOfDetectors(-1),
     fShiftX(),
     fShiftY(),
     fShiftZ(),
     fRotX(),
     fRotY(),
     fRotZ(),
     fModifyGeometry(kFALSE)
 {
 }
FairTutorialDet4::~FairTutorialDet4 () virtual
destructor
Definition at line 86 of file FairTutorialDet4.cxx.
References DEBUG4, FairLogger::endl(), fFairTutorialDet4PointCollection, and LOG.
 {
   LOG(DEBUG4)<<"Entering Destructor of FairTutorialDet4"<<FairLogger::endl;
   if (fFairTutorialDet4PointCollection) {
     fFairTutorialDet4PointCollection->Delete();
     delete fFairTutorialDet4PointCollection;
   }
   LOG(DEBUG4)<<"Leaving Destructor of FairTutorialDet4"<<FairLogger::endl;
 }
FairTutorialDet4::FairTutorialDet4 (const FairTutorialDet4 &) private
Member Function Documentation
FairTutorialDet4Point * FairTutorialDet4::AddHit (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t time, Double_t length, Double_t eLoss)
This method is an example of how to add your own point of type FairTutorialDet4Point to the clones array
Definition at line 405 of file FairTutorialDet4.cxx.
References fFairTutorialDet4PointCollection.
Referenced by ProcessHits().
 {
   TClonesArray& clref = *fFairTutorialDet4PointCollection;
   Int_t size = clref.GetEntriesFast();
   return new(clref[size]) FairTutorialDet4Point(trackID, detID, pos, mom,
          time, length, eLoss);
 }
void FairModule::AddSensitiveVolume (TGeoVolume * v) inherited
Definition at line 282 of file FairModule.cxx.
References FairVolumeList::addVolume(), DEBUG2, FairLogger::endl(), FairVolumeList::findObject(), FairModule::fModId, FairModule::fNbOfSensitiveVol, FairModule::fNbOfVolumes, LOG, FairVolume::setModId(), FairVolume::SetModule(), FairModule::svList, and FairModule::vList.
Referenced by FairModule::ExpandNode().
 {
   LOG(DEBUG2)<<"AddSensitiveVolume " << v->GetName() << FairLogger::endl;
   // Only register volumes which are not already registered
   // Otherwise the stepping will be slowed down
   if( ! vList->findObject(v->GetName() ) ) {
     FairVolume*  volume = NULL;
     volume = new FairVolume(v->GetName(), fNbOfVolumes++);
     vList->addVolume(volume);
     volume->setModId(fModId);
     volume->SetModule(this);
     svList->Add(volume);
     fNbOfSensitiveVol++;
   }
 }
virtual void FairTutorialDet4::BeginEvent () inline virtual
Reimplemented from FairDetector.
Definition at line 92 of file FairTutorialDet4.h.
 {;}
virtual void FairTutorialDet4::BeginPrimary () inline virtual
Reimplemented from FairDetector.
Definition at line 89 of file FairTutorialDet4.h.
 {;}
virtual void FairModule::BeginWorkerRun () const inline virtual inherited
Init worker run (used in MT mode only)
Definition at line 81 of file FairModule.h.
 {;}
Bool_t FairTutorialDet4::CheckIfSensitive (std::string name) private virtual
Set the sensitivity flag for volumes, called from ConstructASCIIRootGeometry(), and has to be implimented for detectors which use ConstructASCIIRootGeometry() to build the geometry
Reimplemented from FairModule.
Definition at line 227 of file FairTutorialDet4.cxx.
 {
   TString tsname = name;
   if (tsname.Contains("tut4")) {
     return kTRUE;
   }
   return kFALSE;
 }
FairModule * FairModule::CloneModule () const virtual inherited
Clone this object (used in MT mode only)
Definition at line 652 of file FairModule.cxx.
 {
   Fatal("CloneModule","Has to be overriden in multi-threading applications.");
   return 0;
 }
template<class T , class U > void FairModule::ConstructASCIIGeometry (T dataType1, TString containerName = "", U datatype2 = NULL) inherited
template function to construct geometry. to be used in derived classes.
Definition at line 156 of file FairModule.h.
References FairGeoInterface::addGeoModule(), FairLogger::endl(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairModule::GetGeometryFileName(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), INFO, FairGeoLoader::Instance(), FairRun::Instance(), FairGeoNode::isSensitive(), LOG, FairModule::ProcessNodes(), and FairGeoInterface::readSet().
 {
   FairGeoLoader* loader=FairGeoLoader::Instance();
   FairGeoInterface* GeoInterface =loader->getGeoInterface();
   T* MGeo=new T();
   MGeo->print();
   MGeo->setGeomFile(GetGeometryFileName());
   GeoInterface->addGeoModule(MGeo);
   Bool_t rc = GeoInterface->readSet(MGeo);
   if ( rc ) { MGeo->create(loader->getGeoBuilder()); }
   TList* volList = MGeo->getListOfVolumes();
   // store geo parameter
   FairRun* fRun = FairRun::Instance();
   FairRuntimeDb* rtdb= FairRun::Instance()->GetRuntimeDb();
   dataType1 = *MGeo;
   if ( "" != containerName) {
     LOG(INFO) << "Add GeoNodes for "<< MGeo->getDescription()
               << " to container " << containerName << FairLogger::endl;
     //    U par=(U)(rtdb->getContainer(containerName));
     U*      par=(U*)(rtdb->getContainer(containerName));
     TObjArray* fSensNodes = par->GetGeoSensitiveNodes();
     TObjArray* fPassNodes = par->GetGeoPassiveNodes();
     TListIter iter(volList);
     FairGeoNode* node   = NULL;
     FairGeoVolume* aVol=NULL;
     while( (node = (FairGeoNode*)iter.Next()) ) {
       aVol = dynamic_cast<FairGeoVolume*> ( node );
       if ( node->isSensitive()  ) {
         fSensNodes->AddLast( aVol );
       } else {
         fPassNodes->AddLast( aVol );
       }
     }
     ProcessNodes( volList );
     par->setChanged();
     par->setInputVersion(fRun->GetRunId(),1);
   }
 }
void FairTutorialDet4::ConstructASCIIGeometry () private virtual
Method to construct the ascii geometry
If you are using the standard ASCII input for the geometry just copy this and use it for your detector, otherwise you can implement here you own way of constructing the geometry.
Reimplemented from FairModule.
Definition at line 236 of file FairTutorialDet4.cxx.
References FairGeoInterface::addGeoModule(), FairGeoSet::create(), DEBUG, FairLogger::endl(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairModule::GetGeometryFileName(), FairTutorialDet4GeoPar::GetGeoPassiveNodes(), FairTutorialDet4GeoPar::GetGeoSensitiveNodes(), FairGeoSet::getListOfVolumes(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairGeoLoader::Instance(), FairRun::Instance(), FairGeoNode::isSensitive(), LOG, FairModule::ProcessNodes(), FairGeoInterface::readSet(), FairParSet::setChanged(), FairGeoSet::setGeomFile(), and FairParSet::setInputVersion().
Referenced by ConstructGeometry().
 {
   FairGeoLoader*    geoLoad = FairGeoLoader::Instance();
   FairGeoInterface* geoFace = geoLoad->getGeoInterface();
   FairTutorialDet4Geo*  Geo  = new FairTutorialDet4Geo();
   LOG(DEBUG)<<"Read Geo file "<<GetGeometryFileName()<<FairLogger::endl;
   Geo->setGeomFile(GetGeometryFileName());
   geoFace->addGeoModule(Geo);
   Bool_t rc = geoFace->readSet(Geo);
   if (rc) { Geo->create(geoLoad->getGeoBuilder()); }
   TList* volList = Geo->getListOfVolumes();
   // store geo parameter
   FairRun* fRun = FairRun::Instance();
   FairRuntimeDb* rtdb= FairRun::Instance()->GetRuntimeDb();
   FairTutorialDet4GeoPar* par=(FairTutorialDet4GeoPar*)(rtdb->getContainer("FairTutorialDet4GeoPar"));
   TObjArray* fSensNodes = par->GetGeoSensitiveNodes();
   TObjArray* fPassNodes = par->GetGeoPassiveNodes();
   TListIter iter(volList);
   FairGeoNode* node   = NULL;
   FairGeoVolume* aVol=NULL;
   while( (node = (FairGeoNode*)iter.Next()) ) {
     aVol = dynamic_cast<FairGeoVolume*> ( node );
     if ( node->isSensitive()  ) {
       fSensNodes->AddLast( aVol );
     } else {
       fPassNodes->AddLast( aVol );
     }
   }
   par->setChanged();
   par->setInputVersion(fRun->GetRunId(),1);
   ProcessNodes ( volList );
 }
void FairModule::ConstructGDMLGeometry (TGeoMatrix * posrot) virtual inherited
construct geometry from GDML files
Definition at line 463 of file FairModule.cxx.
References FairLogger::Error(), FairLogger::Fatal(), gLogger, and MESSAGE_ORIGIN.
 {
     gLogger->Error(MESSAGE_ORIGIN," Could not construct magnet geometry from gdml file. ");
     gLogger->Error(MESSAGE_ORIGIN," The used ROOT version does not support gdml. ");
     gLogger->Error(MESSAGE_ORIGIN," Please recompile ROOT with gdml support. ");
     gLogger->Fatal(MESSAGE_ORIGIN," Stop execution at this point. ");
 }
void FairTutorialDet4::ConstructGeometry () virtual
Create the detector geometry
Reimplemented from FairModule.
Definition at line 213 of file FairTutorialDet4.cxx.
References ConstructASCIIGeometry(), FairModule::ConstructRootGeometry(), FairLogger::endl(), FATAL, FairModule::GetGeometryFileName(), INFO, and LOG.
 {
   TString fileName=GetGeometryFileName();
   if (fileName.EndsWith(".geo")) {
     LOG(INFO)<<"Constructing Tutorial4 geometry from ASCII file "<<fileName<<FairLogger::endl;
     ConstructASCIIGeometry();
   } else if (fileName.EndsWith(".root")) {
     LOG(INFO)<<"Constructing Tutorial4 geometry from ROOT file "<<fileName<<FairLogger::endl;
     ConstructRootGeometry();
   } else {
     LOG(FATAL) << "Geometry format not supported." << FairLogger::endl;
   }
 }
void FairModule::ConstructOpGeometry () virtual inherited
method called from the MC application to set optical geometry properties
Definition at line 67 of file FairModule.cxx.
References DEBUG2, FairLogger::endl(), and LOG.
Referenced by FairMCApplication::ConstructOpGeometry().
 {
   LOG(DEBUG2)<<"The method ConstructOpGeometry has to be implemented in the detector class which inherits from FairModule"<<FairLogger::endl;;
 }
void FairModule::ConstructRootGeometry () virtual inherited
construct geometry from root files (TGeo)
Construct the detector geometry from ROOT files, possible inputs are:
A TGeoVolume as a mother (master) volume containing the detector geometry
A TGeoManager with the detector geometry
A TGeoVolume as a mother or Master volume which is the output of the CAD2ROOT geometry, in this case the materials are not proprely defined and had to be reset In all cases we have to check that the material properties are the same or is the materials defined in the current simulation session
loop inside the delivered root file and try to fine a TGeoManager object the first TGeoManager found will be read
in case a TGeoManager was found get the top most volume and the node
The file does not contain any TGeoManager, so we assume to have a file with a TGeoVolume try to look for a TGeoVolume inside the file
Every thing is OK, we have a TGeoVolume and now we add it to the simulation TGeoManager
force rebuilding of voxels
To avoid having different names of the default matrices because we could have get the volume from another TGeoManager, we reset the default matrix name
NOw we can remove the matrix so that the new geomanager will rebuild it properly
Now we can add the node to the existing cave
correction from O. Merle: in case of a TGeoVolume (v1) set the material properly
now go through the herachy and set the materials properly, this is important becase the CAD converter produce TGeoVolumes with materials that have only names and no properties
Definition at line 316 of file FairModule.cxx.
References FairModule::AssignMediumAtImport(), FairLogger::endl(), FairModule::ExpandNode(), FATAL, FairModule::fMotherVolumeName, FairModule::GetGeometryFileName(), LOG, and FairModule::SetDefaultMatrixName().
Referenced by FairMagnet::ConstructGeometry(), and ConstructGeometry().
 {
   TGeoManager* OldGeo=gGeoManager;
   TGeoManager* NewGeo=0;
   TGeoVolume* volume=0;;
   TFile* f=new TFile(GetGeometryFileName().Data());
   TList* l= f->GetListOfKeys();
   TKey* key;
   TIter next( l);
   TGeoNode* n=0;
   TGeoVolume* v1=0;
   while ((key = (TKey*)next())) {
     if (strcmp(key->GetClassName(),"TGeoManager") != 0) { continue; }
     gGeoManager=0;
     NewGeo = (TGeoManager*)key->ReadObj();
     break;
   }
   if (NewGeo!=0) {
     NewGeo->cd();
     volume=(TGeoVolume*)NewGeo->GetNode(0)->GetDaughter(0)->GetVolume();
     v1=volume->MakeCopyVolume(volume->GetShape());
     // n=NewGeo->GetTopNode();
     n=v1->GetNode(0);
     //  NewGeo=0;
     // delete NewGeo; //move it to the end of the method
   } else {
     key=(TKey*) l->At(0);  //Get the first key in the list
     volume=dynamic_cast<TGeoVolume*> (key->ReadObj());
     if(volume!=0) { n=volume->GetNode(0); }
     if(n!=0) { v1=n->GetVolume(); }
   }
   if(v1==0) {
     LOG(FATAL)<<"Could not find any geometry in file " << GetGeometryFileName().Data() << FairLogger::endl;
   } else {
     gGeoManager=OldGeo;
     gGeoManager->cd();
     // If AddToVolume is empty add the volume to the top volume Cave
     // If it is defined check if the volume exists and if it exists add the volume from the root file
     // to the already existing volume
     TGeoVolume* Cave=NULL;
     if ( 0 == fMotherVolumeName.Length() ) {
       Cave= gGeoManager->GetTopVolume();
     } else {
       Cave = gGeoManager->GetVolume(fMotherVolumeName);
     }
     if(Cave!=NULL) {
       gGeoManager->AddVolume(v1);
       TGeoVoxelFinder* voxels = v1->GetVoxels();
       if (voxels) { voxels->SetNeedRebuild(); }
       // else { fLogger->Fatal(MESSAGE_ORIGIN, "\033[5m\033[31mFairModule::ConstructRootGeometry(): could not find voxels  \033[0m"); }
       TGeoMatrix* M = n->GetMatrix();
       SetDefaultMatrixName(M);
       gGeoManager->GetListOfMatrices()->Remove(M);
       TGeoHMatrix* global = gGeoManager->GetHMatrix();
       gGeoManager->GetListOfMatrices()->Remove(global); //Remove the Identity matrix
       Cave->AddNode(v1,0, M);
       AssignMediumAtImport(v1);
       ExpandNode(n);
       if(NewGeo!=0) { delete NewGeo; }
       delete f;
     } else {
       LOG(FATAL)<<"Could not find the given mother volume "<< fMotherVolumeName.Data() << " where the geomanger should be added."<<FairLogger::endl;
     }
   }
 }
virtual void FairTutorialDet4::CopyClones (TClonesArray * cl1, TClonesArray * cl2, Int_t offset) inline virtual
The following methods can be implemented if you need to make any optional action in your detector during the transport.
Reimplemented from FairDetector.
Definition at line 83 of file FairTutorialDet4.h.
                                              {;}
void FairTutorialDet4::EndOfEvent () virtual
this is called at the end of an event
Reimplemented from FairDetector.
Definition at line 178 of file FairTutorialDet4.cxx.
References fFairTutorialDet4PointCollection.
 {
   fFairTutorialDet4PointCollection->Clear();
 }
void FairModule::ExpandNode (TGeoNode * Node) virtual inherited
called from ConstructRootGeometry()
Definition at line 528 of file FairModule.cxx.
References FairModule::AddSensitiveVolume(), FairModule::AssignMediumAtImport(), FairModule::CheckIfSensitive(), DEBUG2, FairLogger::endl(), LOG, and FairModule::SetDefaultMatrixName().
Referenced by FairModule::ConstructRootGeometry().
 {
   //FairGeoLoader* geoLoad = FairGeoLoader::Instance();
   //FairGeoInterface* geoFace = geoLoad->getGeoInterface();
   //FairGeoMedia* Media =  geoFace->getMedia();
   //FairGeoBuilder* geobuild=geoLoad->getGeoBuilder();
   TGeoMatrix* Matrix =fN->GetMatrix();
   if(gGeoManager->GetListOfMatrices()->FindObject(Matrix)) { gGeoManager->GetListOfMatrices()->Remove(Matrix); }
   TGeoVolume* v1=fN->GetVolume();
   TObjArray* NodeList=v1->GetNodes();
   for (Int_t Nod=0; Nod<NodeList->GetEntriesFast(); Nod++) {
     TGeoNode* fNode =(TGeoNode*)NodeList->At(Nod);
     TGeoMatrix* M =fNode->GetMatrix();
     //M->SetDefaultName();
     SetDefaultMatrixName(M);
     if(fNode->GetNdaughters()>0) { ExpandNode(fNode); }
     TGeoVolume* v= fNode->GetVolume();
     AssignMediumAtImport(v);
     if (!gGeoManager->FindVolumeFast(v->GetName())) {
       LOG(DEBUG2)<<"Register Volume " << v->GetName()<<FairLogger::endl;
       v->RegisterYourself();
     }
     if ( (this->InheritsFrom("FairDetector")) && CheckIfSensitive(v->GetName())) {
       LOG(DEBUG2)<<"Sensitive Volume "<< v->GetName() << FairLogger::endl;
       AddSensitiveVolume(v);
     }
   }
 }
void FairModule::ExpandNodeForGDML (TGeoNode * curNode) virtual inherited
called from ConstructGDMLGeometry()
Definition at line 471 of file FairModule.cxx.
 {
 }
virtual void FairDetector::FinishEvent () inline virtual inherited
Definition at line 94 of file FairDetector.h.
{
       ;
     }
virtual void FairTutorialDet4::FinishPrimary () inline virtual
Reimplemented from FairDetector.
Definition at line 87 of file FairTutorialDet4.h.
 {;}
virtual void FairTutorialDet4::FinishRun () inline virtual
Reimplemented from FairDetector.
Definition at line 88 of file FairTutorialDet4.h.
 {;}
virtual void FairModule::FinishWorkerRun () const inline virtual inherited
Finish worker run (used in MT mode only)
Definition at line 83 of file FairModule.h.
 {;}
TClonesArray * FairTutorialDet4::GetCollection (Int_t iColl) const virtual
Gets the produced collections
Implements FairDetector.
Definition at line 202 of file FairTutorialDet4.cxx.
References fFairTutorialDet4PointCollection.
 {
   if (iColl == 0) { return fFairTutorialDet4PointCollection; }
   else { return NULL; }
 }
Int_t FairDetector::GetDetId () inline inherited
Definition at line 101 of file FairDetector.h.
References FairDetector::fDetId.
                       {
       return fDetId;
     }
FairVolume * FairModule::getFairVolume (FairGeoNode * fNode) inherited
Definition at line 301 of file FairModule.cxx.
References FairVolumeList::At(), FairVolumeList::getEntries(), FairVolume::getGeoNode(), and FairModule::vList.
 {
   FairVolume* fv;
   FairVolume*  fvol=0;
   for(Int_t i=0; i<vList->getEntries(); i++) {
     fv=vList->At(i);
     if((fv->getGeoNode())==fN) {
       fvol=fv;
       return fvol;
       break;
     }
   }
   return fvol;
 }
virtual TString FairModule::GetGeometryFileName () inline virtual inherited
Get the Geometry file name
Definition at line 63 of file FairModule.h.
References FairModule::fgeoName.
Referenced by FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairMagnet::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTestDetector::ConstructGeometry(), NewDetector::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), ConstructGeometry(), and FairModule::ConstructRootGeometry().
 {return  fgeoName ;}
virtual TString FairModule::GetGeometryFileVer () inline virtual inherited
Get the geometry file version if used
Definition at line 65 of file FairModule.h.
References FairModule::fgeoVer.
 {return   fgeoVer ;}
TList* FairModule::GetListOfGeoPar () inline inherited
return the geo parameter of this detector/module
Definition at line 118 of file FairModule.h.
References FairModule::flGeoPar.
 { return flGeoPar;}
Int_t FairModule::GetModId () inline inherited
return the detector/Module id (which was set in the sim macro for the detector)
Definition at line 99 of file FairModule.h.
References FairModule::fModId.
Referenced by FairMCApplication::ConstructGeometry(), and FairDetector::Initialize().
 {return fModId;}
virtual Int_t FairModule::getVolId (const TString & vname) const inline virtual inherited
return the MC id of a volume named vname
Definition at line 97 of file FairModule.h.
 {return 0;}
void FairTutorialDet4::Initialize () virtual
Initialization of the detector is done here
Reimplemented from FairDetector.
Definition at line 110 of file FairTutorialDet4.cxx.
References fGeoHandler, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), FairTutorialDet4GeoHandler::Init(), FairDetector::Initialize(), and FairRun::Instance().
 {
   FairDetector::Initialize();
   FairRuntimeDb* rtdb= FairRun::Instance()->GetRuntimeDb();
   FairTutorialDet4GeoPar* par=(FairTutorialDet4GeoPar*)(rtdb->getContainer("FairTutorialDet4GeoPar"));
   Bool_t isSimulation = kTRUE;
   fGeoHandler->Init(isSimulation);
 }
void FairTutorialDet4::InitParContainers () virtual
Init parameter containers
Reimplemented from FairModule.
Definition at line 120 of file FairTutorialDet4.cxx.
References FairLogger::endl(), fMisalignPar, fNrOfDetectors, fRotX, fRotY, fRotZ, fShiftX, fShiftY, fShiftZ, FairTutorialDet4MisalignPar::GetNrOfDetectors(), FairTutorialDet4MisalignPar::GetRotX(), FairTutorialDet4MisalignPar::GetRotY(), FairTutorialDet4MisalignPar::GetRotZ(), FairTutorialDet4MisalignPar::GetShiftX(), FairTutorialDet4MisalignPar::GetShiftY(), FairTutorialDet4MisalignPar::GetShiftZ(), INFO, and LOG.
 {
   LOG(INFO)<< "Initialize tutdet missallign parameters"<<FairLogger::endl;
   fNrOfDetectors=fMisalignPar->GetNrOfDetectors();
   fShiftX=fMisalignPar->GetShiftX();
   fShiftY=fMisalignPar->GetShiftY();
   fShiftZ=fMisalignPar->GetShiftZ();
   fRotX=fMisalignPar->GetRotX();
   fRotY=fMisalignPar->GetRotY();
   fRotZ=fMisalignPar->GetRotZ();
 }
Bool_t FairModule::IsActive () inline inherited
return the detector status
Definition at line 103 of file FairModule.h.
References FairModule::fActive.
Referenced by FairMCApplication::FairMCApplication(), and FairMCApplication::operator=().
 {return fActive;}
void FairTutorialDet4::ModifyGeometry () virtual
Misalign the detector geometry
Reimplemented from FairModule.
Definition at line 278 of file FairTutorialDet4.cxx.
References FairLogger::endl(), fModifyGeometry, INFO, LOG, ModifyGeometryByFullPath(), and ModifyGeometryBySymlink().
 {
   // When saving the top volume of the geometry to a file the information
   // about the TGeoPNEntries is not saved. So the misalign procedure
   // which uses the TGeoPNEntry information can not be used.
   // The code is here to demonstrate how to use this feature.
   if (fModifyGeometry) {
     LOG(INFO)<<"Misalign the geometry for the tutorial detector."<<FairLogger::endl;
     TString detStr   = "Tutorial4/det00";
     TGeoPNEntry* entry = gGeoManager->GetAlignableEntry(detStr.Data());
     if (entry) {
       LOG(INFO)<<"Misalign using symlinks."<<FairLogger::endl;
       TGeoPhysicalNode* node = entry->GetPhysicalNode();
 //    LOG(INFO)<<"Nr of alignable objects: "<<gGeoManager->GetNAlignable()<<FairLogger::endl;
       ModifyGeometryBySymlink();
     } else {
       LOG(INFO)<<"Misalign using full path."<<FairLogger::endl;
       ModifyGeometryByFullPath();
     }
   }
 }
void FairTutorialDet4::ModifyGeometryByFullPath () private
Definition at line 303 of file FairTutorialDet4.cxx.
References DEBUG, FairLogger::endl(), fNrOfDetectors, fRotX, fRotY, fRotZ, fShiftX, fShiftY, fShiftZ, INFO, and LOG.
Referenced by ModifyGeometry().
 {
   TString volPath;
   TString volStr   = "/cave_1/tutorial4_0/tut4_det_";
   for (Int_t iDet = 0; iDet < fNrOfDetectors; ++iDet) {
     LOG(DEBUG)<<"Misalign detector nr "<<iDet<<FairLogger::endl;
     volPath  = volStr;
     volPath += iDet;
     LOG(INFO) << "Path: "<< volPath << FairLogger::endl;
     gGeoManager->cd(volPath);
     TGeoHMatrix* g3 = gGeoManager->GetCurrentMatrix();
 //      g3->Print();
     TGeoNode* n3 = gGeoManager->GetCurrentNode();
     TGeoMatrix* l3 = n3->GetMatrix();
 //      l3->Print();
     //we have to express the displacements as regards the old local RS (non misaligned BTOF)
     Double_t dx     = fShiftX[iDet];
     Double_t dy     = fShiftY[iDet];
     Double_t dz     = fShiftZ[iDet];
     Double_t dphi   = fRotX[iDet];
     Double_t dtheta = fRotY[iDet];
     Double_t dpsi   = fRotZ[iDet];
     TGeoRotation* rrot = new TGeoRotation("rot",dphi,dtheta,dpsi);
     TGeoCombiTrans localdelta = *(new TGeoCombiTrans(dx,dy,dz, rrot));
 //      localdelta.Print();
     TGeoHMatrix nlocal = *l3 * localdelta;
     TGeoHMatrix* nl3 = new TGeoHMatrix(nlocal); // new matrix, representing real position (from new local mis RS to the global one)
     TGeoPhysicalNode* pn3 = gGeoManager->MakePhysicalNode(volPath);
     pn3->Align(nl3);
     TGeoHMatrix* ng3 = pn3->GetMatrix(); //"real" global matrix, what survey sees
     LOG(DEBUG)<<"*************  The Misaligned Matrix in GRS **************"<<FairLogger::endl;
 //      ng3->Print();
   }
   LOG(DEBUG)<<"Align in total "<<fNrOfDetectors<<" detectors."<<FairLogger::endl;
 }
void FairTutorialDet4::ModifyGeometryBySymlink () private
Definition at line 350 of file FairTutorialDet4.cxx.
References FairLogger::endl(), fNrOfDetectors, fRotX, fRotY, fRotZ, fShiftX, fShiftY, fShiftZ, INFO, and LOG.
Referenced by ModifyGeometry().
 {
   TString symName;
   TString detStr   = "Tutorial4/det";
   for (Int_t iDet = 0; iDet < fNrOfDetectors; ++iDet) {
     LOG(INFO)<<"Misalign detector nr "<<iDet<<FairLogger::endl;
     symName  = detStr;
     symName += Form("%02d",iDet);
     TGeoPhysicalNode* node = NULL;
     TGeoPNEntry* entry = gGeoManager->GetAlignableEntry(detStr);
     if (entry) {
       node = gGeoManager->MakeAlignablePN(entry);
     }
     TGeoMatrix* l3 = NULL;
     if (node) {
       l3 = node->GetMatrix();
     } else {
       continue;
     }
     //we have to express the displacements as regards the old local RS (non misaligned BTOF)
     Double_t dx     = fShiftX[iDet];
     Double_t dy     = fShiftY[iDet];
     Double_t dz     = fShiftZ[iDet];
     Double_t dphi   = fRotX[iDet];
     Double_t dtheta = fRotY[iDet];
     Double_t dpsi   = fRotZ[iDet];
     LOG(INFO)<<"Psi: "<<dpsi<<FairLogger::endl;
     TGeoRotation* rrot = new TGeoRotation("rot",dphi,dtheta,dpsi);
     TGeoCombiTrans localdelta = *(new TGeoCombiTrans(dx,dy,dz, rrot));
     localdelta.Print();
     TGeoHMatrix nlocal = *l3 * localdelta;
     TGeoHMatrix* nl3 = new TGeoHMatrix(nlocal); // new matrix, representing real position (from new local mis RS to the global one)
     node->Align(nl3);
     TGeoHMatrix* ng3 = node->GetMatrix(); //"real" global matrix, what survey sees
     printf("\n\n*************  The Misaligned Matrix in GRS **************\n");
     ng3->Print();
   }
   //do something
   LOG(INFO)<<"Total Nr of detectors: "<<fNrOfDetectors<<FairLogger::endl;
 }
FairTutorialDet4& FairTutorialDet4::operator= (const FairTutorialDet4 &) private
virtual void FairTutorialDet4::PostTrack () inline virtual
Reimplemented from FairDetector.
Definition at line 90 of file FairTutorialDet4.h.
 {;}
virtual void FairTutorialDet4::PreTrack () inline virtual
Reimplemented from FairDetector.
Definition at line 91 of file FairTutorialDet4.h.
 {;}
virtual void FairModule::Print (Option_t * option = "") const inline virtual inherited
Print method should be implemented in detector or module
Definition at line 59 of file FairModule.h.
 {;}
Bool_t FairTutorialDet4::ProcessHits (FairVolume * v = 0) virtual
this method is called for each step during simulation (see FairMCApplication::Stepping())
This method is called from the MC stepping
Implements FairDetector.
Definition at line 133 of file FairTutorialDet4.cxx.
References AddHit(), FairStack::AddPoint(), fELoss, fGeoHandler, fLength, fMom, fPos, fTime, fTrackID, fVolumeID, FairTutorialDet4GeoHandler::GetUniqueDetectorId(), and kTutDet.
 {
   //Set parameters at entrance of volume. Reset ELoss.
   if ( gMC->IsTrackEntering() ) {
     fELoss  = 0.;
     fTime   = gMC->TrackTime() * 1.0e09;
     fLength = gMC->TrackLength();
     gMC->TrackPosition(fPos);
     gMC->TrackMomentum(fMom);
   }
   // Sum energy loss for all steps in the active volume
   fELoss += gMC->Edep();
   // Create FairTutorialDet4Point at exit of active volume
   if ( gMC->IsTrackExiting()    ||
        gMC->IsTrackStop()       ||
        gMC->IsTrackDisappeared()   ) {
     fTrackID  = gMC->GetStack()->GetCurrentTrackNumber();
 //    fVolumeID = vol->getMCid();
     fVolumeID = fGeoHandler->GetUniqueDetectorId();
     if (fELoss == 0. ) { return kFALSE; }
     // Save positions in local coordinate system, so transform the
     // global coordinates into local ones.
     Double_t master[3] = {fPos.X(), fPos.Y(), fPos.Z()};
     Double_t local[3];
     gMC->Gmtod(master, local, 1);
 //    AddHit(fTrackID, fVolumeID, TVector3(fPos.X(),  fPos.Y(),  fPos.Z()),
     AddHit(fTrackID, fVolumeID, TVector3(local[0], local[1], local[2]),
            TVector3(fMom.Px(), fMom.Py(), fMom.Pz()), fTime, fLength,
            fELoss);
     // Increment number of tutorial det points in TParticle
     FairStack* stack = (FairStack*) gMC->GetStack();
     stack->AddPoint(kTutDet);
   }
   return kTRUE;
 }
void FairModule::ProcessNodes (TList * aList) inherited
called from ConstuctASCIIGeometry
Definition at line 244 of file FairModule.cxx.
References FairVolumeList::addVolume(), FairGeoNode::calcLabTransform(), FairModule::fActive, FairModule::fModId, FairModule::fNbOfSensitiveVol, FairModule::fNbOfVolumes, FairRuntimeDb::getContainer(), FairGeoNode::getCopyNo(), FairGeoParSet::GetGeoNodes(), FairGeoVolume::getMCid(), FairGeoNode::getMotherNode(), FairRun::GetRuntimeDb(), FairGeoNode::getTruncName(), FairRun::Instance(), FairGeoNode::isSensitive(), FairVolume::setCopyNo(), FairVolume::setGeoNode(), FairVolume::setModId(), FairVolume::SetModule(), FairVolume::setMotherCopyNo(), FairVolume::setMotherId(), FairVolume::setRealName(), FairModule::svList, and FairModule::vList.
Referenced by FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairRutherford::ConstructGeometry(), and FairTutorialDet1::ConstructGeometry().
 {
   TListIter iter(aList);
   FairGeoNode* node   = NULL;
   FairGeoNode* MotherNode =NULL;
   FairVolume*  volume = NULL;
   FairRuntimeDb* rtdb= FairRun::Instance()->GetRuntimeDb();
   FairGeoParSet* par=(FairGeoParSet*)(rtdb->getContainer("FairGeoParSet"));
   TObjArray* fNodes = par->GetGeoNodes();
   while( (node = (FairGeoNode*)iter.Next()) ) {
     node->calcLabTransform();
     MotherNode=node->getMotherNode();
     volume = new FairVolume( node->getTruncName(), fNbOfVolumes++);
     volume->setRealName(node->GetName());
     vList->addVolume(volume);
     volume->setGeoNode(node);
     volume->setCopyNo(  node->getCopyNo());
     if(MotherNode!=0) {
       volume->setMotherId(node->getMCid());
       volume->setMotherCopyNo(MotherNode->getCopyNo());
     }
     FairGeoVolume* aVol=NULL;
     if ( node->isSensitive() && fActive ) {
       volume->setModId(fModId);
       volume->SetModule(this);
       svList->Add(volume);
       aVol = dynamic_cast<FairGeoVolume*> ( node );
       fNodes->AddLast( aVol );
       fNbOfSensitiveVol++;
     }
   }
 }
void FairTutorialDet4::Register () virtual
Registers the produced collections in FAIRRootManager.
This will create a branch in the output tree called FairTutorialDet4Point, setting the last parameter to kFALSE means: this collection will not be written to the file, it will exist only during the simulation.
Implements FairDetector.
Definition at line 187 of file FairTutorialDet4.cxx.
References fFairTutorialDet4PointCollection, FairRootManager::Instance(), and FairRootManager::Register().
 {
   FairRootManager::Instance()->Register("TutorialDetPoint", "TutorialDet",
                                         fFairTutorialDet4PointCollection, kTRUE);
 }
void FairTutorialDet4::Reset () virtual
has to be called after each event to reset the containers
Implements FairDetector.
Definition at line 208 of file FairTutorialDet4.cxx.
References fFairTutorialDet4PointCollection.
 {
   fFairTutorialDet4PointCollection->Clear();
 }
void FairDetector::SaveGeoParams () inherited
Definition at line 113 of file FairDetector.cxx.
References FairModule::flGeoPar, FairDetector::fLogger, FairLogger::Info(), FairModule::kGeoSaved, and MESSAGE_ORIGIN.
 {
   if ( ! kGeoSaved  ) {
     fLogger->Info(MESSAGE_ORIGIN,"Detector: %s Geometry parameters saved ... ", GetName());
     TFolder* mf = dynamic_cast<TFolder*>(gROOT->FindObjectAny("cbmroot")) ;
     TFolder* stsf = NULL;
     if (mf ) { stsf = dynamic_cast<TFolder*> (mf->FindObjectAny(GetName())); }
     if (stsf) {
       TFolder* newf = stsf->AddFolder("Parameters","Detector parameters",NULL);
       newf->Add( flGeoPar ) ;
     }
     kGeoSaved = kTRUE;
   }
 }
void FairModule::SetGeometryFileName (TString fname, TString geoVer = "0") virtual inherited
Set the geometry file name o be used
Definition at line 189 of file FairModule.cxx.
References DEBUG, FairLogger::endl(), FATAL, FairModule::fgeoName, and LOG.
Referenced by TEST().
 {
   // If absolute path is given as argument, try to find it there.
   // If the file don't exist break. Don't look anywhere else.
   if ( fname.BeginsWith("/") ) {
     if ( gSystem->AccessPathName(fname.Data()) ) {
       LOG(FATAL) << fName << ": geometry file " << fname
                  << " not found in absolut path!"
                  << FairLogger::endl;
       fgeoName = "";
     } // file not found
     fgeoName = fname;
     LOG(DEBUG) << fName << ": using geometry file "
                << fgeoName << FairLogger::endl;
     return;
   }
   // If GEOMPATH is set, try to find the file there.
   // If there is no such file go on to look in the default location.
   TString userPath = getenv("GEOMPATH");
   userPath.ReplaceAll("//","/");
   if ( ! userPath.IsNull() ) {
     if ( ! userPath.EndsWith("/") ) {
       userPath += "/";
     }
     fgeoName = userPath + fname;
     if ( ! gSystem->AccessPathName(fgeoName.Data()) ) {
       LOG(DEBUG) << fName << ": using geometry file " << fgeoName
                  << FairLogger::endl;
       return;
     }
     LOG(DEBUG) << fName << ": geometry file " << fname
                << " not found in GEOMPATH "
                << userPath << FairLogger::endl;
   }
   // Look in the standard path
   fgeoName = getenv("VMCWORKDIR");
   fgeoName += "/geometry/" + fname;
   if ( ! gSystem->AccessPathName(fgeoName.Data()) ) {
     LOG(DEBUG) << fName << ": using geometry file "
                << fgeoName << FairLogger::endl;
     return;
   }
   // File not found
   LOG(FATAL) << fName << ": geometry file " << fname
              << " not found in standard path "
              << FairLogger::endl;
   fgeoName = "";
   return;
 }
void FairModule::SetModId (Int_t id) inline inherited
set the detector/module id
Definition at line 105 of file FairModule.h.
References FairModule::fModId.
Referenced by FairRunSim::AddModule().
 {fModId=id;}
void FairTutorialDet4::SetModifyGeometry (Bool_t val) inline
Definition at line 94 of file FairTutorialDet4.h.
References fModifyGeometry.
 { fModifyGeometry=val;}
void FairModule::SetMotherVolume (TString volName) inline inherited
Set the name of the mother volume to which a new geometry is added. This function is needed for geometries which are defined as ROOT geometry manager.
Definition at line 109 of file FairModule.h.
References FairModule::fMotherVolumeName.
 {fMotherVolumeName=volName;}
void FairTutorialDet4::SetParContainers () virtual
Set the parameter containers
Reimplemented from FairModule.
Definition at line 95 of file FairTutorialDet4.cxx.
References FairLogger::endl(), FATAL, fMisalignPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), INFO, FairRun::Instance(), LOG, and LOG_IF.
 {
   LOG(INFO)<< "Set tutdet missallign parameters"<<FairLogger::endl;
   // Get Base Container
   FairRun* sim = FairRun::Instance();
   LOG_IF(FATAL, !sim) << "No run object"<<FairLogger::endl;
   FairRuntimeDb* rtdb=sim->GetRuntimeDb();
   LOG_IF(FATAL, !rtdb) << "No runtime database"<<FairLogger::endl;
   fMisalignPar = (FairTutorialDet4MisalignPar*)
                  (rtdb->getContainer("FairTutorialDet4MissallignPar"));
 }
virtual void FairTutorialDet4::SetSpecialPhysicsCuts () inline virtual
Reimplemented from FairDetector.
Definition at line 85 of file FairTutorialDet4.h.
 {;}
void FairModule::SetVerboseLevel (Int_t level) inline inherited
Set the verbose level in this detector
Definition at line 101 of file FairModule.h.
References FairModule::fVerboseLevel.
 {fVerboseLevel=level;}
Member Data Documentation
Bool_t FairModule::fActive protected inherited
Definition at line 146 of file FairModule.h.
Referenced by FairModule::IsActive(), FairModule::operator=(), and FairModule::ProcessNodes().
Int_t FairDetector::fDetId protected inherited
Definition at line 111 of file FairDetector.h.
Referenced by FairDetector::GetDetId(), and FairDetector::operator=().
Double32_t FairTutorialDet4::fELoss private
length
Definition at line 108 of file FairTutorialDet4.h.
Referenced by ProcessHits().
TClonesArray* FairTutorialDet4::fFairTutorialDet4PointCollection private
energy loss
container for data points
Definition at line 112 of file FairTutorialDet4.h.
Referenced by AddHit(), EndOfEvent(), GetCollection(), Register(), Reset(), and ~FairTutorialDet4().
FairTutorialDet4GeoHandler* FairTutorialDet4::fGeoHandler private
Definition at line 114 of file FairTutorialDet4.h.
Referenced by Initialize(), and ProcessHits().
TString FairModule::fgeoName protected inherited
Definition at line 144 of file FairModule.h.
Referenced by FairModule::GetGeometryFileName(), FairModule::operator=(), and FairModule::SetGeometryFileName().
TString FairModule::fgeoVer protected inherited
Definition at line 143 of file FairModule.h.
Referenced by FairModule::GetGeometryFileVer(), and FairModule::operator=().
Double32_t FairTutorialDet4::fLength private
time
Definition at line 107 of file FairTutorialDet4.h.
Referenced by ProcessHits().
TList* FairModule::flGeoPar protected inherited
Definition at line 149 of file FairModule.h.
Referenced by FairDetector::FairDetector(), FairModule::GetListOfGeoPar(), FairModule::operator=(), FairDetector::SaveGeoParams(), and FairDetector::~FairDetector().
FairLogger* FairDetector::fLogger protected inherited
Definition at line 112 of file FairDetector.h.
Referenced by FairDetector::operator=(), and FairDetector::SaveGeoParams().
FairTutorialDet4MisalignPar* FairTutorialDet4::fMisalignPar private
Definition at line 116 of file FairTutorialDet4.h.
Referenced by InitParContainers(), and SetParContainers().
Int_t FairModule::fModId protected inherited
Definition at line 145 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::GetModId(), FairModule::operator=(), FairModule::ProcessNodes(), and FairModule::SetModId().
Bool_t FairTutorialDet4::fModifyGeometry private
Definition at line 126 of file FairTutorialDet4.h.
Referenced by ModifyGeometry(), and SetModifyGeometry().
TLorentzVector FairTutorialDet4::fMom private
position at entrance
Definition at line 105 of file FairTutorialDet4.h.
Referenced by ProcessHits().
TString FairModule::fMotherVolumeName inherited
Definition at line 128 of file FairModule.h.
Referenced by FairModule::ConstructRootGeometry(), FairModule::operator=(), and FairModule::SetMotherVolume().
Int_t FairModule::fNbOfSensitiveVol protected inherited
Definition at line 147 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::operator=(), and FairModule::ProcessNodes().
Int_t FairModule::fNbOfVolumes =0 static inherited
total number of volumes in a simulaion session
Definition at line 123 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), and FairModule::ProcessNodes().
Int_t FairTutorialDet4::fNrOfDetectors private
Definition at line 118 of file FairTutorialDet4.h.
Referenced by InitParContainers(), ModifyGeometryByFullPath(), and ModifyGeometryBySymlink().
TLorentzVector FairTutorialDet4::fPos private
volume id
Definition at line 104 of file FairTutorialDet4.h.
Referenced by ProcessHits().
TArrayD FairTutorialDet4::fRotX private
Definition at line 122 of file FairTutorialDet4.h.
Referenced by InitParContainers(), ModifyGeometryByFullPath(), and ModifyGeometryBySymlink().
TArrayD FairTutorialDet4::fRotY private
Definition at line 123 of file FairTutorialDet4.h.
Referenced by InitParContainers(), ModifyGeometryByFullPath(), and ModifyGeometryBySymlink().
TArrayD FairTutorialDet4::fRotZ private
Definition at line 124 of file FairTutorialDet4.h.
Referenced by InitParContainers(), ModifyGeometryByFullPath(), and ModifyGeometryBySymlink().
TArrayD FairTutorialDet4::fShiftX private
Definition at line 119 of file FairTutorialDet4.h.
Referenced by InitParContainers(), ModifyGeometryByFullPath(), and ModifyGeometryBySymlink().
TArrayD FairTutorialDet4::fShiftY private
Definition at line 120 of file FairTutorialDet4.h.
Referenced by InitParContainers(), ModifyGeometryByFullPath(), and ModifyGeometryBySymlink().
TArrayD FairTutorialDet4::fShiftZ private
Definition at line 121 of file FairTutorialDet4.h.
Referenced by InitParContainers(), ModifyGeometryByFullPath(), and ModifyGeometryBySymlink().
Double32_t FairTutorialDet4::fTime private
momentum at entrance
Definition at line 106 of file FairTutorialDet4.h.
Referenced by ProcessHits().
Int_t FairTutorialDet4::fTrackID private
Track information to be stored until the track leaves the active volume.
Definition at line 102 of file FairTutorialDet4.h.
Referenced by ProcessHits().
Int_t FairModule::fVerboseLevel protected inherited
Definition at line 148 of file FairModule.h.
Referenced by FairModule::operator=(), and FairModule::SetVerboseLevel().
Int_t FairTutorialDet4::fVolumeID private
track index
Definition at line 103 of file FairTutorialDet4.h.
Referenced by ProcessHits().
Bool_t FairModule::kGeoSaved protected inherited
list of Detector Geometry parameters
Definition at line 150 of file FairModule.h.
Referenced by FairDetector::FairDetector(), FairModule::operator=(), and FairDetector::SaveGeoParams().
TRefArray * FairModule::svList =0 static inherited
list of all sensitive volumes in a simulaion session
Definition at line 125 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairMCApplication::ConstructGeometry(), FairModule::FairModule(), FairDetector::Initialize(), and FairModule::ProcessNodes().
FairVolumeList * FairModule::vList =0 static inherited
list of volumes in a simulation session
Definition at line 121 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::FairModule(), FairModule::getFairVolume(), and FairModule::ProcessNodes().
TArrayI * FairModule::volNumber =0 static inherited
Definition at line 127 of file FairModule.h.
The documentation for this class was generated from the following files:
FairTutorialDet4.h
FairTutorialDet4.cxx