FairRoot: MultiVariatePDF Class Reference
MultiVariatePDF Class Reference
#include <RooDataGenerator.h>
Public Member Functions
MultiVariatePDF (const unsigned int &t_start=0)
MultiVariatePDF (const PDFConfig &opt, const unsigned int &t_start=0)
~MultiVariatePDF ()
RooDataSet * GetGeneratedData (const unsigned int &N, const unsigned int &t_i)
Private Member Functions
void Init (const double &t_start)
Private Attributes
PDFConfig fOpt
RooProdPdf * fModel
RooDataSet * fDataSet
RooRealVar * x
RooRealVar * y
RooRealVar * z
RooRealVar * t
RooRealVar * tErr
RooRealVar * mean_t
RooRealVar * sigma_t
RooGaussian * Gauss_x
RooGaussian * Gauss_y
RooGaussian * Gauss_z
RooGaussian * Gauss_t
RooGaussian * Gauss_tErr
Detailed Description
Definition at line 72 of file RooDataGenerator.h.
Constructor & Destructor Documentation
MultiVariatePDF::MultiVariatePDF (const unsigned int & t_start = 0) inline
Definition at line 75 of file RooDataGenerator.h.
References Init().
                                                         :
             fOpt(),
             fModel(nullptr),
             fDataSet(nullptr),
             x(nullptr),
             y(nullptr),
             z(nullptr),
             t(nullptr),
             tErr(nullptr),
             mean_t(nullptr),
             sigma_t(nullptr),
             Gauss_x(nullptr),
             Gauss_y(nullptr),
             Gauss_z(nullptr),
             Gauss_t(nullptr),
             Gauss_tErr(nullptr)
         {
                 Init(t_start);
         }
MultiVariatePDF::MultiVariatePDF (const PDFConfig & opt, const unsigned int & t_start = 0) inline
Definition at line 94 of file RooDataGenerator.h.
References Init().
                                                                                :
             fOpt(opt),
             fModel(nullptr),
             fDataSet(nullptr),
             x(nullptr),
             y(nullptr),
             z(nullptr),
             t(nullptr),
             tErr(nullptr),
             mean_t(nullptr),
             sigma_t(nullptr),
             Gauss_x(nullptr),
             Gauss_y(nullptr),
             Gauss_z(nullptr),
             Gauss_t(nullptr),
             Gauss_tErr(nullptr)
         {
             Init(t_start);
         }
MultiVariatePDF::~MultiVariatePDF () inline
Definition at line 114 of file RooDataGenerator.h.
         {
             delete x;
             delete y;
             delete z;
             delete t;
             delete tErr;
             delete mean_t;
             delete sigma_t;
             delete Gauss_x;
             delete Gauss_y;
             delete Gauss_z;
             delete Gauss_t;
             delete Gauss_tErr;
             delete fModel;
         }
Member Function Documentation
RooDataSet* MultiVariatePDF::GetGeneratedData (const unsigned int & N, const unsigned int & t_i) inline
Definition at line 132 of file RooDataGenerator.h.
Referenced by main().
         {
             t->setRange((double)t_i,(double)(t_i+1));
             mean_t->setVal((double)t_i+0.5);
             fDataSet = fModel->generate(RooArgSet(*x,*y,*z,*t,*tErr),N);
             return fDataSet;
         }
void MultiVariatePDF::Init (const double & t_start) inline private
Definition at line 163 of file RooDataGenerator.h.
References ERROR, RdmVarParameters::max, RdmVarParameters::mean, RdmVarParameters::min, RdmVarParameters::sigma, PDFConfig::tErr, PDFConfig::x, PDFConfig::y, and PDFConfig::z.
         {
             RooMsgService::instance().setGlobalKillBelow(ERROR);
             TDatime* time = new TDatime();
             int seed=time->GetTime();
             delete time;
             RooRandom::randomGenerator()->SetSeed(seed);
             double tmin=(double)t_start;
             double tmax=(double)(t_start+1);
             x = new RooRealVar("x","x",fOpt.x.min,fOpt.x.max);
             y = new RooRealVar("y","y",fOpt.y.min,fOpt.y.max) ;
             z = new RooRealVar("z","z",fOpt.z.min,fOpt.z.max) ;
             t = new RooRealVar("t","t",tmin,tmax);
             tErr = new RooRealVar("tErr","tErr",fOpt.tErr.min,fOpt.tErr.max);
             mean_t = new RooRealVar("mu_t","mean of t-distribution",(tmin+tmax)/2) ;
             sigma_t = new RooRealVar("sigma_t","width of t-distribution",0.1) ;
             Gauss_x = new RooGaussian(   "Gauss_x"   , "gaussian PDF", *x   , RooConst(fOpt.x.mean),   RooConst(fOpt.x.sigma));
             Gauss_y = new RooGaussian(   "Gauss_y"   , "gaussian PDF", *y   , RooConst(fOpt.y.mean) ,  RooConst(fOpt.y.sigma));
             Gauss_z = new RooGaussian(   "Gauss_z"   , "gaussian PDF", *z   , RooConst(fOpt.z.mean)  , RooConst(fOpt.z.sigma));
             Gauss_t = new RooGaussian(   "Gauss_t"   , "gaussian PDF", *t   , *mean_t       , *sigma_t) ;
             Gauss_tErr=new RooGaussian("Gauss_tErr", "gaussian PDF", *tErr, RooConst((tErr->getMin()+tErr->getMax())/2), RooConst(fOpt.tErr.sigma)) ;
             fModel = new RooProdPdf("Gauss_xyzt_ter","Gauss_x*Gauss_y*Gauss_z*Gauss_t*Gauss_tErr",RooArgList(*Gauss_x,*Gauss_y,*Gauss_z,*Gauss_t,*Gauss_tErr));
         }
Member Data Documentation
RooDataSet* MultiVariatePDF::fDataSet private
Definition at line 145 of file RooDataGenerator.h.
RooProdPdf* MultiVariatePDF::fModel private
Definition at line 144 of file RooDataGenerator.h.
PDFConfig MultiVariatePDF::fOpt private
Definition at line 143 of file RooDataGenerator.h.
RooGaussian* MultiVariatePDF::Gauss_t private
Definition at line 159 of file RooDataGenerator.h.
RooGaussian* MultiVariatePDF::Gauss_tErr private
Definition at line 160 of file RooDataGenerator.h.
RooGaussian* MultiVariatePDF::Gauss_x private
Definition at line 156 of file RooDataGenerator.h.
RooGaussian* MultiVariatePDF::Gauss_y private
Definition at line 157 of file RooDataGenerator.h.
RooGaussian* MultiVariatePDF::Gauss_z private
Definition at line 158 of file RooDataGenerator.h.
RooRealVar* MultiVariatePDF::mean_t private
Definition at line 153 of file RooDataGenerator.h.
RooRealVar* MultiVariatePDF::sigma_t private
Definition at line 154 of file RooDataGenerator.h.
RooRealVar* MultiVariatePDF::t private
Definition at line 150 of file RooDataGenerator.h.
RooRealVar* MultiVariatePDF::tErr private
Definition at line 151 of file RooDataGenerator.h.
RooRealVar* MultiVariatePDF::x private
Definition at line 147 of file RooDataGenerator.h.
RooRealVar* MultiVariatePDF::y private
Definition at line 148 of file RooDataGenerator.h.
RooRealVar* MultiVariatePDF::z private
Definition at line 149 of file RooDataGenerator.h.
The documentation for this class was generated from the following file:
RooDataGenerator.h