FairRroot: FairParamObj Class Reference
FairParamObj Class Reference
#include <FairParamList.h>
Public Member Functions
FairParamObj (const Text_t *name="")
FairParamObj (FairParamObj &)
FairParamObj (const Text_t *, Int_t)
FairParamObj (const Text_t *, Float_t)
FairParamObj (const Text_t *, Double_t)
FairParamObj (const Text_t *, const Int_t *, const Int_t)
FairParamObj (const Text_t *, const Float_t *, const Int_t)
FairParamObj (const Text_t *, const Double_t *, const Int_t)
FairParamObj (const Text_t *, const Text_t *)
FairParamObj (const Text_t *, const Char_t *, const Int_t)
FairParamObj (const Text_t *, const UChar_t *, const Int_t)
~FairParamObj ()
void setParamType (const Text_t *t)
UChar_t * setLength (Int_t l)
void setParamValue (UChar_t *, const Int_t)
void setClassVersion (const Int_t v)
UChar_t * setStreamerInfoSize (Int_t)
void setStreamerInfo (UChar_t *, const Int_t)
UChar_t * getParamValue ()
Bool_t isBasicType ()
const char * getParamType ()
Int_t getBytesPerValue ()
Int_t getClassVersion ()
Int_t getLength ()
Int_t getNumParams ()
UChar_t * getStreamerInfo ()
Int_t getStreamerInfoSize ()
void print ()
Protected Member Functions
template<class type >
void printData (type *, Int_t)
Protected Attributes
UChar_t * paramValue
Int_t arraySize
TString paramType
Bool_t basicType
Int_t bytesPerValue
Int_t classVersion
UChar_t * streamerInfo
Int_t streamerInfoSize
Private Member Functions
FairParamObj & operator= (const FairParamObj &)
Detailed Description
Definition at line 27 of file FairParamList.h.
Constructor & Destructor Documentation
FairParamObj::FairParamObj (const Text_t * name = "")
FairParamObj::FairParamObj (FairParamObj & o)
Definition at line 112 of file FairParamList.cxx.
References arraySize, getParamValue(), getStreamerInfo(), paramValue, streamerInfo, and streamerInfoSize.
   :TNamed(o),
    paramValue(NULL),
    arraySize(o.arraySize),
    paramType(o.paramType),
    basicType(o.basicType),
    bytesPerValue(o.bytesPerValue),
    classVersion(o.classVersion),
    streamerInfo(NULL),
    streamerInfoSize(o.streamerInfoSize)
 {
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,o.getParamValue(),arraySize);
   if (streamerInfoSize>0) {
     memcpy(streamerInfo,o.getStreamerInfo(),streamerInfoSize);
   }
 }
FairParamObj::FairParamObj (const Text_t * name, Int_t value)
Definition at line 130 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(sizeof(Int_t)),
    paramType("Int_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(Int_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   // Constructor for a Int_t value
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,&value,arraySize);
 }
FairParamObj::FairParamObj (const Text_t * name, Float_t value)
Definition at line 146 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(sizeof(Float_t)),
    paramType("Float_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(Float_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   // Constructor for a Float_t value
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,&value,arraySize);
 }
FairParamObj::FairParamObj (const Text_t * name, Double_t value)
Definition at line 162 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(sizeof(Double_t)),
    paramType("Double_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(Double_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   // Constructor for a Double_t value
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,&value,arraySize);
 }
FairParamObj::FairParamObj (const Text_t * name, const Int_t * value, const Int_t nValues)
Definition at line 178 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(sizeof(Int_t)*nValues),
    paramType("Int_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(Int_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   // Constructor for an array with nValues elements of type Int_t
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,value,arraySize);
 }
FairParamObj::FairParamObj (const Text_t * name, const Float_t * value, const Int_t nValues)
Definition at line 195 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(sizeof(Float_t)*nValues),
    paramType("Float_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(Float_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   // Constructor for an array with nValues elements of type Float_t
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,value,arraySize);
 }
FairParamObj::FairParamObj (const Text_t * name, const Double_t * value, const Int_t nValues)
Definition at line 211 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(sizeof(Double_t)*nValues),
    paramType("Double_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(Double_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   // Constructor for an array with nValues elements of type Double_t
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,value,arraySize);
 }
FairParamObj::FairParamObj (const Text_t * name, const Text_t * value)
Definition at line 227 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(strlen(value)),
    paramType("Text_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(Char_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   // Constructor for a string value
   paramValue=new UChar_t[arraySize+1];
   memcpy(paramValue,value,arraySize);
 }
FairParamObj::FairParamObj (const Text_t * name, const Char_t * value, const Int_t nValues)
Definition at line 244 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(sizeof(Char_t)*nValues),
    paramType("Char_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(Char_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   // Constructor for an array with nValues elements of type Char_t
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,value,arraySize);
 }
FairParamObj::FairParamObj (const Text_t * name, const UChar_t * value, const Int_t nValues)
Definition at line 260 of file FairParamList.cxx.
References arraySize, and paramValue.
   :TNamed(name,""),
    paramValue(NULL),
    arraySize(sizeof(UChar_t)*nValues),
    paramType("UChar_t"),
    basicType(kTRUE),
    bytesPerValue(sizeof(UChar_t)),
    classVersion(-1),
    streamerInfo(NULL),
    streamerInfoSize(0)
 {
   paramValue=new UChar_t[arraySize];
   memcpy(paramValue,value,arraySize);
 }
FairParamObj::~FairParamObj ()
Definition at line 275 of file FairParamList.cxx.
References paramValue, and streamerInfo.
 {
   // Destructor
   if (paramValue) {
     delete [] paramValue;
     paramValue=0;
   }
   if (streamerInfo) {
     delete [] streamerInfo;
     streamerInfo=0;
   }
 }
Member Function Documentation
Int_t FairParamObj::getBytesPerValue () inline
Definition at line 60 of file FairParamList.h.
References bytesPerValue.
 { return bytesPerValue; }
Int_t FairParamObj::getClassVersion () inline
Definition at line 61 of file FairParamList.h.
References classVersion.
Referenced by FairParamList::fillObject().
 { return classVersion; }
Int_t FairParamObj::getLength () inline
Definition at line 62 of file FairParamList.h.
References arraySize.
Referenced by FairParamList::fill(), FairParamList::fillObject(), and FairGenericParAsciiFileIo::writeGenericSet().
 { return arraySize; }
Int_t FairParamObj::getNumParams ()
Definition at line 367 of file FairParamList.cxx.
References arraySize, basicType, and bytesPerValue.
Referenced by FairParamList::fill(), print(), and FairGenericParAsciiFileIo::writeGenericSet().
 {
   // Returns the number of values in the array, respectively 1 for classes and strings
   Int_t n=1;
   if (basicType) {
     n=arraySize/bytesPerValue;
   }
   return n;
 }
const char* FairParamObj::getParamType () inline
Definition at line 59 of file FairParamList.h.
Referenced by FairParamList::fill(), FairParamList::fillObject(), and FairGenericParAsciiFileIo::writeGenericSet().
 { return paramType.Data(); }
UChar_t* FairParamObj::getParamValue () inline
Definition at line 57 of file FairParamList.h.
References paramValue.
Referenced by FairParamObj(), FairParamList::fill(), FairParamList::fillObject(), and FairGenericParAsciiFileIo::writeGenericSet().
 { return paramValue; }
UChar_t* FairParamObj::getStreamerInfo () inline
Definition at line 64 of file FairParamList.h.
References streamerInfo.
Referenced by FairParamObj(), and FairParamList::fillObject().
 { return streamerInfo; }
Int_t FairParamObj::getStreamerInfoSize () inline
Definition at line 65 of file FairParamList.h.
References streamerInfoSize.
Referenced by FairParamList::fillObject().
 { return streamerInfoSize; }
Bool_t FairParamObj::isBasicType () inline
Definition at line 58 of file FairParamList.h.
References basicType.
Referenced by FairGenericParAsciiFileIo::writeGenericSet().
 { return basicType; }
FairParamObj& FairParamObj::operator= (const FairParamObj &) private
void FairParamObj::print ()
Definition at line 377 of file FairParamList.cxx.
References arraySize, classVersion, getNumParams(), paramType, paramValue, and printData().
Referenced by FairParamList::print().
 {
   // Prints the name and type of the parameters, respectively class name and version.
   // Prints also the numbers for an array of type Int_t, Float_t, Double_t.
   std::cout<<GetName()<<": ";
   if (classVersion>=0) {
     std::cout<<"\n  Class Type:    "<<paramType.Data()<<"\n  Class Version: "
              <<classVersion<<std::endl;
   } else if (strcmp(paramType,"Text_t")==0) {
     TString val((Char_t*)paramValue,arraySize);
     val.ReplaceAll("\n","\n  ");
     std::cout<<paramType<<"\n  "<<val.Data()<<std::endl;
   } else {
     Int_t nParams=getNumParams();
     if (nParams==1) {
       std::cout<<paramType<<"   ";
     } else {
       std::cout<<paramType<<" array, nValues: "<<nParams<<"\n  ";
     }
     if (strcmp(paramType,"Char_t")==0) {
       Char_t* val=(Char_t*)paramValue;
       printData(val,nParams);
     } else if (strcmp(paramType,"Int_t")==0) {
       Int_t* val=(Int_t*)paramValue;
       printData(val,nParams);
     } else if (strcmp(paramType,"Float_t")==0) {
       Float_t* val=(Float_t*)paramValue;
       printData(val,nParams);
     } else if (strcmp(paramType,"Double_t")==0) {
       Double_t* val=(Double_t*)paramValue;
       printData(val,nParams);
     } else {
       std::cout<<"Type: "<<paramType<<"  Array  length: "<<arraySize<<std::endl;
     }
   }
 }
template<class type > void FairParamObj::printData (type * val, Int_t nParams) protected
Definition at line 414 of file FairParamList.cxx.
Referenced by print().
 {
   Int_t i=0, k=0;
   while (k<nParams) {
     if (i==10) {
       std::cout<<"\n  ";
       i=0;
     }
     std::cout<<val[k]<<" ";
     i++;
     k++;
     if (k>50) {
       std::cout<<"...";
       break;
     }
   }
   std::cout<<std::endl;
 }
void FairParamObj::setClassVersion (const Int_t v) inline
Definition at line 54 of file FairParamList.h.
Referenced by FairParamList::addObject().
 { classVersion=v; }
UChar_t * FairParamObj::setLength (Int_t l)
Definition at line 325 of file FairParamList.cxx.
References arraySize, and paramValue.
 {
   // Sets the length of the binary array
   if (paramValue) { delete [] paramValue; }
   arraySize=l;
   if (l>0) {
     paramValue=new UChar_t[arraySize];
   } else {
     paramValue=0;
   }
   return paramValue;
 }
void FairParamObj::setParamType (const Text_t * t)
Definition at line 288 of file FairParamList.cxx.
References basicType, bytesPerValue, classVersion, paramType, streamerInfo, and streamerInfoSize.
Referenced by FairParamList::addObject().
 {
   // Sets the parameter type. Accepted type names are:
   //     UChar_t (default)
   //     Char_t
   //     Int_t
   //     Float_t
   //     Double_t
   //     Text_t
   //     class name
   paramType=t;
   if (strcmp(t,"Char_t")==0) {
     basicType=kTRUE;
     bytesPerValue=sizeof(Char_t);
   } else if (strcmp(t,"Int_t")==0) {
     basicType=kTRUE;
     bytesPerValue=sizeof(Int_t);
   } else if (strcmp(t,"Float_t")==0) {
     basicType=kTRUE;
     bytesPerValue=sizeof(Float_t);
   } else if (strcmp(t,"Double_t")==0) {
     basicType=kTRUE;
     bytesPerValue=sizeof(Double_t);
   } else if (strcmp(t,"Text_t")==0) {
     basicType=kTRUE;
     bytesPerValue=sizeof(Char_t);
   } else {
     basicType=kFALSE;
     bytesPerValue=1;
   }
   if (basicType==kTRUE) {
     classVersion=-1;
     streamerInfoSize=0;
     streamerInfo=0;
   }
 }
void FairParamObj::setParamValue (UChar_t * value, const Int_t length)
Definition at line 338 of file FairParamList.cxx.
References arraySize, and paramValue.
Referenced by FairParamList::addObject().
 {
   // Sets the parameter value (the array is not copied!)
   if (paramValue) { delete [] paramValue; }
   arraySize=length;
   paramValue=value;
 }
void FairParamObj::setStreamerInfo (UChar_t * array, const Int_t length)
Definition at line 359 of file FairParamList.cxx.
References streamerInfo, and streamerInfoSize.
Referenced by FairParamList::addObject().
 {
   // Sets the streamer info of ROOT classes (the array is not copied!)
   if (streamerInfo) { delete [] streamerInfo; }
   streamerInfoSize=length;
   streamerInfo=array;
 }
UChar_t * FairParamObj::setStreamerInfoSize (Int_t l)
Definition at line 346 of file FairParamList.cxx.
References streamerInfo, and streamerInfoSize.
 {
   // Sets the length of the streamer info
   if (streamerInfo) { delete [] streamerInfo; }
   streamerInfoSize=l;
   if (l>0) {
     streamerInfo=new UChar_t[streamerInfoSize];
   } else {
     streamerInfo=0;
   }
   return streamerInfo;
 }
Member Data Documentation
Int_t FairParamObj::arraySize protected
Definition at line 31 of file FairParamList.h.
Referenced by FairParamObj(), getLength(), getNumParams(), print(), setLength(), and setParamValue().
Bool_t FairParamObj::basicType protected
Definition at line 33 of file FairParamList.h.
Referenced by getNumParams(), isBasicType(), and setParamType().
Int_t FairParamObj::bytesPerValue protected
Definition at line 34 of file FairParamList.h.
Referenced by getBytesPerValue(), getNumParams(), and setParamType().
Int_t FairParamObj::classVersion protected
Definition at line 35 of file FairParamList.h.
Referenced by getClassVersion(), print(), and setParamType().
TString FairParamObj::paramType protected
Definition at line 32 of file FairParamList.h.
Referenced by print(), and setParamType().
UChar_t* FairParamObj::paramValue protected
Definition at line 30 of file FairParamList.h.
Referenced by FairParamObj(), getParamValue(), print(), setLength(), setParamValue(), and ~FairParamObj().
UChar_t* FairParamObj::streamerInfo protected
Definition at line 36 of file FairParamList.h.
Referenced by FairParamObj(), getStreamerInfo(), setParamType(), setStreamerInfo(), setStreamerInfoSize(), and ~FairParamObj().
Int_t FairParamObj::streamerInfoSize protected
Definition at line 37 of file FairParamList.h.
Referenced by FairParamObj(), getStreamerInfoSize(), setParamType(), setStreamerInfo(), and setStreamerInfoSize().
The documentation for this class was generated from the following files:
FairParamList.h
FairParamList.cxx