FairRroot: FairTestDetectorHit Class Reference
FairTestDetectorHit Class Reference
#include <FairTestDetectorHit.h>
Public Member Functions
FairTestDetectorHit ()
FairTestDetectorHit (Int_t detID, Int_t mcindex, TVector3 &pos, TVector3 &dpos)
virtual ~FairTestDetectorHit ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
FairTestDetectorHit ()
FairTestDetectorHit (Int_t detID, Int_t mcindex, TVector3 &pos, TVector3 &dpos)
virtual ~FairTestDetectorHit ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Double_t GetDx () const
Double_t GetDy () const
Double_t GetDz () const
Int_t GetRefIndex () const
void PositionError (TVector3 &dpos) const
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetDx (Double_t dx)
void SetDy (Double_t dy)
void SetDz (Double_t dz)
void SetDxyz (Double_t dx, Double_t dy, Double_t dz)
void SetPositionError (const TVector3 &dpos)
void SetRefIndex (Int_t index)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
virtual void Print (const Option_t *opt="") const
virtual std::ostream & Print (std::ostream &out=std::cout) const
virtual Double_t GetTimeStamp () const
virtual Double_t GetTimeStampError () const
virtual FairLink GetEntryNr () const
virtual void SetTimeStamp (Double_t t)
virtual void SetTimeStampError (Double_t t)
virtual void SetEntryNr (FairLink entry)
virtual Int_t Compare (const TObject *obj) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
virtual bool operator< (const FairTimeStamp *rValue) const
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
virtual FairMultiLinkedData * GetPointerToLinks () const
virtual void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link)
Sets the Links with a single FairLink.
virtual void SetInsertHistory (Bool_t val)
virtual void SetPointerToLinks (FairMultiLinkedData *links)
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
virtual void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
virtual void AddInterfaceData (FairMultiLinkedData_Interface *data)
virtual void ResetLinks ()
Protected Member Functions
ClassDef (FairHit, 3)
ClassDef (FairTimeStamp, 3)
indicates where the data is stored in the branch
ClassDef (FairMultiLinkedData_Interface, 5)
FairMultiLinkedData * CreateFairMultiLinkedData ()
Protected Attributes
Double32_t fDx
Double32_t fDy
Double32_t fDz
Errors of position [cm].
Int_t fRefIndex
Index of FairMCPoint for this hit.
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
Double_t fTimeStamp
Double_t fTimeStampError
FairLink fEntryNr
Int_t fVerbose
FairMultiLinkedData * fLink
Private Member Functions
ClassDef (FairTestDetectorHit, 1)
ClassDef (FairTestDetectorHit, 1)
Friends
class boost::serialization::access
Detailed Description
Definition at line 22 of file Tutorial3/data/FairTestDetectorHit.h.
Constructor & Destructor Documentation
FairTestDetectorHit::FairTestDetectorHit ()
Default constructor
Definition at line 10 of file Tutorial3/data/FairTestDetectorHit.cxx.
     : FairHit()
 {
 }
FairTestDetectorHit::FairTestDetectorHit (Int_t detID, Int_t mcindex, TVector3 & pos, TVector3 & dpos)
Constructor
Definition at line 15 of file Tutorial3/data/FairTestDetectorHit.cxx.
     : FairHit(detID, pos, dpos, mcindex)
 {
 }
FairTestDetectorHit::~FairTestDetectorHit () virtual
Destructor
Definition at line 20 of file Tutorial3/data/FairTestDetectorHit.cxx.
 {
 }
FairTestDetectorHit::FairTestDetectorHit ()
Default constructor
FairTestDetectorHit::FairTestDetectorHit (Int_t detID, Int_t mcindex, TVector3 & pos, TVector3 & dpos)
Constructor
virtual FairTestDetectorHit::~FairTestDetectorHit () virtual
Destructor
Member Function Documentation
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) virtual inherited
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
 {
         SetInsertHistory(kFALSE); //todo add previous history value
         if (data->GetEntryNr().GetType() != -1)
                 AddLink(data->GetEntryNr());
         else
                 std::cout
                                 << "-E- FairMultiLinkedData_Interface::AddInterfaceData EntryNr == "
                                 << data->GetEntryNr() << std::endl;
         if (data->GetPointerToLinks() != 0) {
                 AddLinks(*data->GetPointerToLinks());
         }
         SetInsertHistory(kTRUE);
 }
void FairMultiLinkedData_Interface::AddLink (FairLink link) virtual inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 154 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLink(link);
         }
 }
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 146 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLinks(links, mult);
         }
 }
FairTestDetectorHit::ClassDef (FairTestDetectorHit , 1) private
FairTestDetectorHit::ClassDef (FairTestDetectorHit , 1) private
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
FairTimeStamp::ClassDef (FairTimeStamp , 3) protected inherited
indicates where the data is stored in the branch
FairHit::ClassDef (FairHit , 3) protected inherited
virtual Int_t FairTimeStamp::Compare (const TObject * obj) const inline virtual inherited
Definition at line 54 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
{
       if (this == obj) { return 0; }
       FairTimeStamp* tsobj = (FairTimeStamp*)obj;
       Double_t ts = tsobj->GetTimeStamp();
       Double_t tserror = tsobj->GetTimeStampError();
       if (fTimeStamp < ts) { return -1; }
       else if (fTimeStamp == ts && fTimeStampError < tserror) { return -1; }
       else if (fTimeStamp == ts && fTimeStampError == tserror) { return 0; }
       else { return 1; }
     }
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 62 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
 {
         if (FairRootManager::Instance()->GetUseFairLinks()){
                 if (fLink == 0){
                         fLink = new FairMultiLinkedData();
                 }
                 return fLink;
         }
         return 0;
 }
virtual bool FairTimeStamp::equal (FairTimeStamp * data) inline virtual inherited
Reimplemented in FairTestDetectorDigi, FairTestDetectorDigi, and MyDigi.
Definition at line 70 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
{
       return (fTimeStamp == data->GetTimeStamp() && fTimeStampError == data->GetTimeStampError());
     }
Int_t FairHit::GetDetectorID () const inline inherited
Definition at line 51 of file FairHit.h.
References FairHit::fDetectorID.
Referenced by FairTutorialDet4StraightLineFitter::IsGoodEvent(), and FairTutorialDet4MilleWriter::IsGoodEvent().
 { return fDetectorID;             };
Double_t FairHit::GetDx () const inline inherited
Accessors
Definition at line 46 of file FairHit.h.
References FairHit::fDx.
Referenced by FairTutorialDet4StraightLineFitter::Exec().
 { return fDx;                     };
Double_t FairHit::GetDy () const inline inherited
Definition at line 47 of file FairHit.h.
References FairHit::fDy.
Referenced by FairTutorialDet4StraightLineFitter::Exec().
 { return fDy;                     };
Double_t FairHit::GetDz () const inline inherited
Definition at line 48 of file FairHit.h.
References FairHit::fDz.
 { return fDz;                     };
virtual FairLink FairTimeStamp::GetEntryNr () const inline virtual inherited
Reimplemented from FairMultiLinkedData_Interface.
Definition at line 49 of file FairTimeStamp.h.
References FairTimeStamp::fEntryNr.
 {return fEntryNr;}
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const virtual inherited
returns the FairLink at the given position
Definition at line 92 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLink(pos);
         } else {
                 FairLink emptyLink;
                 return emptyLink;
         }
 }
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const virtual inherited
returns stored links as FairLinks
Definition at line 73 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinks();
         } else {
                 std::set<FairLink> emptySet;
                 return emptySet;
         }
 }
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const virtual inherited
returns all FairLinks with the corresponding type
Definition at line 112 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinksWithType(type);
         } else {
                 FairMultiLinkedData emptyLinks;
                 return emptyLinks;
         }
 }
Int_t FairMultiLinkedData_Interface::GetNLinks () const virtual inherited
returns the number of stored links
Definition at line 83 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetNLinks();
         } else {
                 return 0;
         }
 }
virtual FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline virtual inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::Print(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
 {       return fLink;}
Int_t FairHit::GetRefIndex () const inline inherited
Definition at line 49 of file FairHit.h.
References FairHit::fRefIndex.
 { return fRefIndex;               };
virtual Double_t FairTimeStamp::GetTimeStamp () const inline virtual inherited
Accessors
Definition at line 47 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by StopTime::Call(), TimeGap::Call(), FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), FairRingSorterTask::Exec(), FairTSBufferFunctional::GetData(), FairTimeStampPointDraw::GetValue(), FairTimeStamp::operator<(), FairTimeStamp::Print(), FairWriteoutBuffer::PrintData(), and FairWriteoutBuffer::PrintStartTimeMap().
 { return fTimeStamp; };
virtual Double_t FairTimeStamp::GetTimeStampError () const inline virtual inherited
Definition at line 48 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), and FairTimeStamp::Print().
 { return fTimeStampError;};
Double_t FairHit::GetX () const inline inherited
Definition at line 52 of file FairHit.h.
References FairHit::fX.
Referenced by FairTutorialDet4StraightLineFitter::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), FairTutorialDet4MilleWriter::StraightLineShiftX(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
 { return fX;                      };
Double_t FairHit::GetY () const inline inherited
Definition at line 53 of file FairHit.h.
References FairHit::fY.
Referenced by FairTutorialDet4StraightLineFitter::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
 { return fY;                      };
Double_t FairHit::GetZ () const inline inherited
Definition at line 54 of file FairHit.h.
References FairHit::fZ.
Referenced by FairTutorialDet4StraightLineFitter::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), FairTutorialDet4MilleWriter::StraightLineShiftX(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
 { return fZ;                      };
virtual Bool_t FairTimeStamp::IsSortable () const inline virtual inherited
Definition at line 67 of file FairTimeStamp.h.
 { return kTRUE;};
virtual bool FairTimeStamp::operator< (const FairTimeStamp * rValue) const inline virtual inherited
Definition at line 79 of file FairTimeStamp.h.
References FairTimeStamp::GetTimeStamp().
{
         if (GetTimeStamp() < rValue->GetTimeStamp())
                 return true;
         else
                 return false;
     }
void FairHit::Position (TVector3 & pos) const inline inherited
Definition at line 134 of file FairHit.h.
References FairHit::fX, FairHit::fY, and FairHit::fZ.
 {
   pos.SetXYZ(fX, fY, fZ);
 }
void FairHit::PositionError (TVector3 & dpos) const inline inherited
Definition at line 113 of file FairHit.h.
References FairHit::fDx, FairHit::fDy, and FairHit::fDz.
 {
   dpos.SetXYZ(fDx, fDy, fDz);
 }
std::ostream & FairTimeStamp::Print (std::ostream & out = std::cout) const virtual inherited
Definition at line 42 of file FairTimeStamp.cxx.
References FairTimeStamp::fEntryNr, FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), and FairMultiLinkedData_Interface::Print().
Referenced by FairRingSorter::AddElement(), FairRingSorterTask::Exec(), and FairWriteoutBuffer::FillDataToDeadTimeMap().
 {
   out << "EntryNr of Data: " << fEntryNr << " TimeStamp: " << GetTimeStamp() << " +/- " << GetTimeStampError() << std::endl;
   FairMultiLinkedData_Interface::Print(out);
   return out;
 }
virtual void FairHit::Print (const Option_t * opt = "") const inline virtual inherited
Definition at line 75 of file FairHit.h.
 {;}
void FairMultiLinkedData_Interface::ResetLinks () virtual inherited
Definition at line 185 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
 {
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->ResetLinks();
         }
 }
template<class Archive > void FairTestDetectorHit::serialize (Archive & ar, const unsigned int version) inline
Definition at line 35 of file Tutorial3/data/FairTestDetectorHit.h.
     {
         ar& boost::serialization::base_object<FairHit>(*this);
     }
template<class Archive > void FairTestDetectorHit::serialize (Archive & ar, const unsigned int version) inline
Definition at line 35 of file Tutorial6/sim/FairTestDetectorHit.h.
     {
         ar& boost::serialization::base_object<FairHit>(*this);
     }
void FairHit::SetDetectorID (Int_t detID) inline inherited
Definition at line 66 of file FairHit.h.
References FairHit::fDetectorID.
 { fDetectorID = detID; }
void FairHit::SetDx (Double_t dx) inline inherited
Modifiers
Definition at line 60 of file FairHit.h.
References FairHit::fDx.
 { fDx = dx; }
void FairHit::SetDxyz (Double_t dx, Double_t dy, Double_t dz) inline inherited
Definition at line 119 of file FairHit.h.
References FairHit::fDx, FairHit::fDy, and FairHit::fDz.
 {
   fDx = dx;
   fDy = dy;
   fDz = dz;
 }
void FairHit::SetDy (Double_t dy) inline inherited
Definition at line 61 of file FairHit.h.
References FairHit::fDy.
 { fDy = dy; }
void FairHit::SetDz (Double_t dz) inline inherited
Definition at line 62 of file FairHit.h.
References FairHit::fDz.
 { fDz = dz; }
virtual void FairTimeStamp::SetEntryNr (FairLink entry) inline virtual inherited
Reimplemented from FairMultiLinkedData_Interface.
Definition at line 53 of file FairTimeStamp.h.
References FairTimeStamp::fEntryNr.
Referenced by FairRingSorterTask::Exec().
 {fEntryNr = entry;}
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) virtual inherited
Definition at line 178 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         if (GetPointerToLinks() != 0) {
                 GetPointerToLinks()->SetInsertHistory(val);
         }
 }
void FairMultiLinkedData_Interface::SetLink (FairLink link) virtual inherited
Sets the Links with a single FairLink.
Definition at line 130 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetectorTimeRecoTask::Exec(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLink(link);
         }
 }
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) virtual inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 122 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLinks(links);
         }
 }
virtual void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline virtual inherited
Definition at line 53 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
 {fLink = links;}
void FairHit::SetPosition (const TVector3 & pos) inline inherited
Definition at line 148 of file FairHit.h.
References FairHit::fX, FairHit::fY, and FairHit::fZ.
 {
   fX = pos.X();
   fY = pos.Y();
   fZ = pos.Z();
 }
void FairHit::SetPositionError (const TVector3 & dpos) inline inherited
Definition at line 127 of file FairHit.h.
References FairHit::fDx, FairHit::fDy, and FairHit::fDz.
 {
   fDx = dpos.X();
   fDy = dpos.Y();
   fDz = dpos.Z();
 }
void FairHit::SetRefIndex (Int_t index) inline inherited
Definition at line 65 of file FairHit.h.
References FairHit::fRefIndex.
 { fRefIndex = index; }
virtual void FairTimeStamp::SetTimeStamp (Double_t t) inline virtual inherited
Modifiers
Definition at line 51 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
 { fTimeStamp = t; }
virtual void FairTimeStamp::SetTimeStampError (Double_t t) inline virtual inherited
Definition at line 52 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
 {fTimeStampError = t;}
void FairHit::SetX (Double_t x) inline inherited
Definition at line 67 of file FairHit.h.
References FairHit::fX.
 { fX = x; }
void FairHit::SetXYZ (Double_t x, Double_t y, Double_t z) inline inherited
Definition at line 140 of file FairHit.h.
References FairHit::fX, FairHit::fY, and FairHit::fZ.
 {
   fX = x;
   fY = y;
   fZ = z;
 }
void FairHit::SetY (Double_t y) inline inherited
Definition at line 68 of file FairHit.h.
References FairHit::fY.
 { fY = y; }
void FairHit::SetZ (Double_t z) inline inherited
Definition at line 69 of file FairHit.h.
References FairHit::fZ.
 { fZ = z; }
Friends And Related Function Documentation
boost::serialization::access friend
Definition at line 42 of file Tutorial3/data/FairTestDetectorHit.h.
Member Data Documentation
Int_t FairHit::fDetectorID protected inherited
Detector unique identifier.
Definition at line 103 of file FairHit.h.
Referenced by FairHit::GetDetectorID(), FairHit::serialize(), and FairHit::SetDetectorID().
Double32_t FairHit::fDx protected inherited
Definition at line 101 of file FairHit.h.
Referenced by FairHit::GetDx(), FairHit::PositionError(), FairHit::serialize(), FairHit::SetDx(), FairHit::SetDxyz(), and FairHit::SetPositionError().
Double32_t FairHit::fDy protected inherited
Definition at line 101 of file FairHit.h.
Referenced by FairHit::GetDy(), FairHit::PositionError(), FairHit::serialize(), FairHit::SetDxyz(), FairHit::SetDy(), and FairHit::SetPositionError().
Double32_t FairHit::fDz protected inherited
Errors of position [cm].
Definition at line 101 of file FairHit.h.
Referenced by FairHit::GetDz(), FairHit::PositionError(), FairHit::serialize(), FairHit::SetDxyz(), FairHit::SetDz(), and FairHit::SetPositionError().
FairLink FairTimeStamp::fEntryNr protected inherited
Error on time stamp
Definition at line 104 of file FairTimeStamp.h.
Referenced by FairTimeStamp::GetEntryNr(), FairTimeStamp::Print(), and FairTimeStamp::SetEntryNr().
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
Int_t FairHit::fRefIndex protected inherited
Index of FairMCPoint for this hit.
Definition at line 102 of file FairHit.h.
Referenced by FairHit::GetRefIndex(), FairHit::serialize(), and FairHit::SetRefIndex().
Double_t FairTimeStamp::fTimeStamp protected inherited
Definition at line 102 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStamp(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStamp().
Double_t FairTimeStamp::fTimeStampError protected inherited
Time of digit or Hit [ns]
Definition at line 103 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStampError(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStampError().
Int_t FairMultiLinkedData_Interface::fVerbose protected inherited
Definition at line 78 of file FairMultiLinkedData_Interface.h.
Double32_t FairHit::fX protected inherited
Definition at line 104 of file FairHit.h.
Referenced by FairHit::GetX(), FairHit::Position(), FairHit::serialize(), FairHit::SetPosition(), FairHit::SetX(), and FairHit::SetXYZ().
Double32_t FairHit::fY protected inherited
Definition at line 104 of file FairHit.h.
Referenced by FairHit::GetY(), FairHit::Position(), FairHit::serialize(), FairHit::SetPosition(), FairHit::SetXYZ(), and FairHit::SetY().
Double32_t FairHit::fZ protected inherited
Position of hit [cm].
Definition at line 104 of file FairHit.h.
Referenced by FairHit::GetZ(), FairHit::Position(), FairHit::serialize(), FairHit::SetPosition(), FairHit::SetXYZ(), and FairHit::SetZ().
The documentation for this class was generated from the following files:
Tutorial3/data/FairTestDetectorHit.h
Tutorial3/data/FairTestDetectorHit.cxx