FairRroot: sampler Namespace Reference
sampler Namespace Reference
Classes
class Content
class Payload
struct StaticDescriptorInitializer_payload_2eproto
Functions
void protobuf_AssignDesc_payload_2eproto ()
void protobuf_ShutdownFile_payload_2eproto ()
void protobuf_AddDesc_payload_2eproto ()
Variables
struct
sampler::StaticDescriptorInitializer_payload_2eproto static_descriptor_initializer_payload_2eproto_
Function Documentation
void sampler::protobuf_AddDesc_payload_2eproto ()
Definition at line 100 of file payload.pb.cc.
References sampler::Content::default_instance_, sampler::Payload::default_instance_, sampler::Content::InitAsDefaultInstance(), sampler::Payload::InitAsDefaultInstance(), and protobuf_ShutdownFile_payload_2eproto().
Referenced by protobuf_AssignDesc_payload_2eproto(), and sampler::StaticDescriptorInitializer_payload_2eproto::StaticDescriptorInitializer_payload_2eproto().
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\rpayload.proto\022\007sampler\"@\n\007Content\022\t\n\001a"
     "\030\001 \001(\001\022\t\n\001b\030\002 \001(\001\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022"
     "\t\n\001z\030\005 \001(\005\")\n\007Payload\022\036\n\004data\030\001 \003(\0132\020.sa"
     "mpler.Content", 133);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "payload.proto", &protobuf_RegisterTypes);
   Content::default_instance_ = new Content();
   Payload::default_instance_ = new Payload();
   Content::default_instance_->InitAsDefaultInstance();
   Payload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_payload_2eproto);
 }
void sampler::protobuf_AssignDesc_payload_2eproto ()
Definition at line 33 of file payload.pb.cc.
References sampler::Content::default_instance_, sampler::Payload::default_instance_, and protobuf_AddDesc_payload_2eproto().
{
   protobuf_AddDesc_payload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "payload.proto");
   GOOGLE_CHECK(file != NULL);
   Content_descriptor_ = file->message_type(0);
   static const int Content_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, a_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, b_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, z_),
   };
   Content_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Content_descriptor_,
       Content::default_instance_,
       Content_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Content));
   Payload_descriptor_ = file->message_type(1);
   static const int Payload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, data_),
   };
   Payload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Payload_descriptor_,
       Payload::default_instance_,
       Payload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Payload));
 }
void sampler::protobuf_ShutdownFile_payload_2eproto ()
Definition at line 93 of file payload.pb.cc.
References sampler::Content::default_instance_, and sampler::Payload::default_instance_.
Referenced by protobuf_AddDesc_payload_2eproto().
{
   delete Content::default_instance_;
   delete Content_reflection_;
   delete Payload::default_instance_;
   delete Payload_reflection_;
 }
Variable Documentation
struct sampler::StaticDescriptorInitializer_payload_2eproto sampler::static_descriptor_initializer_payload_2eproto_