FairRoot: FairConstField Class Reference
FairConstField Class Reference
#include <FairConstField.h>
Public Member Functions
FairConstField ()
FairConstField (const char *name, Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax, Double_t bX, Double_t bY, Double_t bZ)
FairConstField (FairConstPar *fieldPar)
virtual ~FairConstField ()
void FillParContainer ()
void SetFieldRegion (Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax)
void SetField (Double_t bX, Double_t bY, Double_t bZ)
virtual Double_t GetBx (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBy (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBz (Double_t x, Double_t y, Double_t z)
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
Double_t GetBx () const
Double_t GetBy () const
Double_t GetBz () const
virtual void Print ()
ClassDef (FairConstField, 1)
FairConstField ()
FairConstField (const char *name, Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax, Double_t bX, Double_t bY, Double_t bZ)
FairConstField (FairConstPar *fieldPar)
virtual ~FairConstField ()
void FillParContainer ()
void SetFieldRegion (Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax)
void SetField (Double_t bX, Double_t bY, Double_t bZ)
virtual Double_t GetBx (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBy (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBz (Double_t x, Double_t y, Double_t z)
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
Double_t GetBx () const
Double_t GetBy () const
Double_t GetBz () const
virtual void Print ()
ClassDef (FairConstField, 1)
Private Attributes
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
Double_t fBx
Double_t fBy
Double_t fBz
Detailed Description
Definition at line 24 of file Tutorial3/simulation/FairConstField.h.
Constructor & Destructor Documentation
FairConstField::FairConstField ()
Default constructor
Definition at line 28 of file Tutorial3/simulation/FairConstField.cxx.
References fType.
     : fXmin(0)
     , fXmax(0)
     , fYmin(0)
     , fYmax(0)
     , fZmin(0)
     , fZmax(0)
     , fBx(0)
     , fBy(0)
     , fBz(0)
 {
     fType = 0;
 }
FairConstField::FairConstField (const char * name, Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax, Double_t bX, Double_t bY, Double_t bZ)
Standard constructor
Parameters
name Object name
xMin,xMax x region of field (global coordinates)
yMin,yMax y region of field (global coordinates)
zMin,zMax z region of field (global coordinates)
bX,bY,bZ Field values [kG]
Definition at line 44 of file Tutorial3/simulation/FairConstField.cxx.
References fType.
     : FairField(name)
     , fXmin(xMin)
     , fXmax(xMax)
     , fYmin(yMin)
     , fYmax(yMax)
     , fZmin(zMin)
     , fZmax(zMax)
     , fBx(bX)
     , fBy(bY)
     , fBz(bZ)
 {
     fType = 0;
 }
FairConstField::FairConstField (FairConstPar * fieldPar)
Constructor from PndFieldPar
Definition at line 71 of file Tutorial3/simulation/FairConstField.cxx.
References FairLogger::endl(), fBx, fBy, fBz, fType, fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, FairConstPar::GetBx(), FairConstPar::GetBy(), FairConstPar::GetBz(), FairMapPar::GetType(), FairMapPar::GetXmax(), FairMapPar::GetXmin(), FairMapPar::GetYmax(), FairMapPar::GetYmin(), FairMapPar::GetZmax(), FairMapPar::GetZmin(), LOG, and WARNING.
     : FairField()
     , fXmin(0)
     , fXmax(0)
     , fYmin(0)
     , fYmax(0)
     , fZmin(0)
     , fZmax(0)
     , fBx(0)
     , fBy(0)
     , fBz(0)
 {
     if (!fieldPar)
     {
       LOG(WARNING) << "empty parameter container!" << FairLogger::endl;
         fType = -1;
     }
     else
     {
         fXmin = fieldPar->GetXmin();
         fXmax = fieldPar->GetXmax();
         fYmin = fieldPar->GetYmin();
         fYmax = fieldPar->GetYmax();
         fZmin = fieldPar->GetZmin();
         fZmax = fieldPar->GetZmax();
         fBx = fieldPar->GetBx();
         fBy = fieldPar->GetBy();
         fBz = fieldPar->GetBz();
         fType = fieldPar->GetType();
     }
 }
FairConstField::~FairConstField () virtual
Destructor
Definition at line 105 of file Tutorial3/simulation/FairConstField.cxx.
 {
 }
FairConstField::FairConstField ()
Default constructor
FairConstField::FairConstField (const char * name, Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax, Double_t bX, Double_t bY, Double_t bZ)
Standard constructor
Parameters
name Object name
xMin,xMax x region of field (global coordinates)
yMin,yMax y region of field (global coordinates)
zMin,zMax z region of field (global coordinates)
bX,bY,bZ Field values [kG]
FairConstField::FairConstField (FairConstPar * fieldPar)
Constructor from PndFieldPar
virtual FairConstField::~FairConstField () virtual
Destructor
Member Function Documentation
FairConstField::ClassDef (FairConstField , 1)
FairConstField::ClassDef (FairConstField , 1)
void FairConstField::FillParContainer ()
Definition at line 187 of file Tutorial3/simulation/FairConstField.cxx.
References FairRuntimeDb::getContainer(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairRun::Instance(), FairParSet::setChanged(), FairParSet::setInputVersion(), and FairConstPar::SetParameters().
 {
     TString MapName = GetName();
     //  LOG(INFO) << "FairConstField::FillParContainer() "
     //            << FairLogger::endl;
     FairRun* fRun = FairRun::Instance();
     FairRuntimeDb* rtdb = fRun->GetRuntimeDb();
     Bool_t kParameterMerged = kTRUE;
     FairConstPar* Par = (FairConstPar*)rtdb->getContainer("FairConstPar");
     Par->SetParameters(this);
     Par->setInputVersion(fRun->GetRunId(), 1);
     Par->setChanged();
 }
void FairConstField::FillParContainer ()
Double_t FairConstField::GetBx (Double_t x, Double_t y, Double_t z) virtual
Get components of field at a given point
Parameters
x,y,z Point coordinates [cm]
Definition at line 132 of file Tutorial3/simulation/FairConstField.cxx.
References fBx, fXmax, fYmax, and fZmax.
Referenced by FairConstPar::SetParameters().
 {
     if (x < fXmin || x > fXmax || y < fYmin || y > fYmax || z < fZmin || z > fZmax)
     {
         return 0.;
     }
     return fBx;
 }
virtual Double_t FairConstField::GetBx (Double_t x, Double_t y, Double_t z) virtual
Get components of field at a given point
Parameters
x,y,z Point coordinates [cm]
Double_t FairConstField::GetBx () const inline
Accessors to field values
Definition at line 103 of file Tutorial3/simulation/FairConstField.h.
References fBx.
     {
         return fBx;
     }
Double_t FairConstField::GetBx () const inline
Accessors to field values
Definition at line 103 of file Tutorial6/sim/FairConstField.h.
References fBx.
     {
         return fBx;
     }
Double_t FairConstField::GetBy (Double_t x, Double_t y, Double_t z) virtual
Definition at line 143 of file Tutorial3/simulation/FairConstField.cxx.
References fBy, fXmax, fYmax, and fZmax.
Referenced by FairConstPar::SetParameters().
 {
     if (x < fXmin || x > fXmax || y < fYmin || y > fYmax || z < fZmin || z > fZmax)
     {
         return 0.;
     }
     return fBy;
 }
virtual Double_t FairConstField::GetBy (Double_t x, Double_t y, Double_t z) virtual
Double_t FairConstField::GetBy () const inline
Definition at line 107 of file Tutorial6/sim/FairConstField.h.
References fBy.
     {
         return fBy;
     }
Double_t FairConstField::GetBy () const inline
Definition at line 107 of file Tutorial3/simulation/FairConstField.h.
References fBy.
     {
         return fBy;
     }
virtual Double_t FairConstField::GetBz (Double_t x, Double_t y, Double_t z) virtual
Double_t FairConstField::GetBz (Double_t x, Double_t y, Double_t z) virtual
Definition at line 154 of file Tutorial3/simulation/FairConstField.cxx.
References fBz, fXmax, fYmax, and fZmax.
Referenced by FairConstPar::SetParameters().
 {
     if (x < fXmin || x > fXmax || y < fYmin || y > fYmax || z < fZmin || z > fZmax)
     {
         return 0.;
     }
     return fBz;
 }
Double_t FairConstField::GetBz () const inline
Definition at line 111 of file Tutorial6/sim/FairConstField.h.
References fBz.
     {
         return fBz;
     }
Double_t FairConstField::GetBz () const inline
Definition at line 111 of file Tutorial3/simulation/FairConstField.h.
References fBz.
     {
         return fBz;
     }
Double_t FairConstField::GetXmax () const inline
Definition at line 81 of file Tutorial3/simulation/FairConstField.h.
References fXmax.
Referenced by FairConstPar::SetParameters().
     {
         return fXmax;
     }
Double_t FairConstField::GetXmax () const inline
Definition at line 81 of file Tutorial6/sim/FairConstField.h.
References fXmax.
     {
         return fXmax;
     }
Double_t FairConstField::GetXmin () const inline
Accessors to field region
Definition at line 77 of file Tutorial6/sim/FairConstField.h.
References fXmin.
     {
         return fXmin;
     }
Double_t FairConstField::GetXmin () const inline
Accessors to field region
Definition at line 77 of file Tutorial3/simulation/FairConstField.h.
References fXmin.
Referenced by FairConstPar::SetParameters().
     {
         return fXmin;
     }
Double_t FairConstField::GetYmax () const inline
Definition at line 89 of file Tutorial3/simulation/FairConstField.h.
References fYmax.
Referenced by FairConstPar::SetParameters().
     {
         return fYmax;
     }
Double_t FairConstField::GetYmax () const inline
Definition at line 89 of file Tutorial6/sim/FairConstField.h.
References fYmax.
     {
         return fYmax;
     }
Double_t FairConstField::GetYmin () const inline
Definition at line 85 of file Tutorial3/simulation/FairConstField.h.
References fYmin.
Referenced by FairConstPar::SetParameters().
     {
         return fYmin;
     }
Double_t FairConstField::GetYmin () const inline
Definition at line 85 of file Tutorial6/sim/FairConstField.h.
References fYmin.
     {
         return fYmin;
     }
Double_t FairConstField::GetZmax () const inline
Definition at line 97 of file Tutorial3/simulation/FairConstField.h.
References fZmax.
Referenced by FairConstPar::SetParameters().
     {
         return fZmax;
     }
Double_t FairConstField::GetZmax () const inline
Definition at line 97 of file Tutorial6/sim/FairConstField.h.
References fZmax.
     {
         return fZmax;
     }
Double_t FairConstField::GetZmin () const inline
Definition at line 93 of file Tutorial3/simulation/FairConstField.h.
References fZmin.
Referenced by FairConstPar::SetParameters().
     {
         return fZmin;
     }
Double_t FairConstField::GetZmin () const inline
Definition at line 93 of file Tutorial6/sim/FairConstField.h.
References fZmin.
     {
         return fZmin;
     }
virtual void FairConstField::Print () virtual
Screen output
void FairConstField::Print () virtual
Screen output
Definition at line 165 of file Tutorial3/simulation/FairConstField.cxx.
References FairLogger::endl(), fBx, fBy, fBz, fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, INFO, and LOG.
 {
     LOG(INFO) << "======================================================"
               << FairLogger::endl;
     LOG(INFO) << "----  " << fTitle << " : " << fName << FairLogger::endl;
     LOG(INFO) << "----" << FairLogger::endl;
     LOG(INFO) << "----  Field type    : constant" << FairLogger::endl;
     LOG(INFO) << "----" << FairLogger::endl;
     LOG(INFO) << "----  Field regions : " << FairLogger::endl;
     LOG(INFO) << "----        x = " << setw(4) << fXmin << " to " << setw(4)
               << fXmax << " cm" << FairLogger::endl;
     LOG(INFO) << "----        y = " << setw(4) << fYmin << " to " << setw(4)
               << fYmax << " cm" << FairLogger::endl;
     LOG(INFO) << "----        z = " << setw(4) << fZmin << " to " << setw(4)
               << fZmax << " cm" << FairLogger::endl;
     LOG(INFO) << "----  B = ( " << setprecision(4) << fBx << ", " << fBy
               << ", " << fBz << " ) kG" << FairLogger::endl;
     LOG(INFO) << "======================================================"
               << FairLogger::endl;
 }
void FairConstField::SetField (Double_t bX, Double_t bY, Double_t bZ)
Set the field values
Parameters
bX,bY,bZ Field values [kG]
void FairConstField::SetField (Double_t bX, Double_t bY, Double_t bZ)
Set the field values
Parameters
bX,bY,bZ Field values [kG]
Definition at line 123 of file Tutorial3/simulation/FairConstField.cxx.
References fBx, fBy, and fBz.
 {
     fBx = bX;
     fBy = bY;
     fBz = bZ;
 }
void FairConstField::SetFieldRegion (Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax)
Set the field region
Parameters
xMin,xMax x region of field (global coordinates)
yMin,yMax y region of field (global coordinates)
zMin,zMax z region of field (global coordinates)
void FairConstField::SetFieldRegion (Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax)
Set the field region
Parameters
xMin,xMax x region of field (global coordinates)
yMin,yMax y region of field (global coordinates)
zMin,zMax z region of field (global coordinates)
Definition at line 111 of file Tutorial3/simulation/FairConstField.cxx.
References fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
 {
     fXmin = xMin;
     fXmax = xMax;
     fYmin = yMin;
     fYmax = yMax;
     fZmin = zMin;
     fZmax = zMax;
 }
Member Data Documentation
Double_t FairConstField::fBx private
Field components inside the field region
Definition at line 131 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetBx(), Print(), and SetField().
Double_t FairConstField::fBy private
Definition at line 132 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetBy(), Print(), and SetField().
Double_t FairConstField::fBz private
Definition at line 133 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetBz(), Print(), and SetField().
Double_t FairConstField::fXmax private
Definition at line 124 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetBx(), GetBy(), GetBz(), GetXmax(), Print(), and SetFieldRegion().
Double_t FairConstField::fXmin private
Limits of the field region
Definition at line 123 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetXmin(), Print(), and SetFieldRegion().
Double_t FairConstField::fYmax private
Definition at line 126 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetBx(), GetBy(), GetBz(), GetYmax(), Print(), and SetFieldRegion().
Double_t FairConstField::fYmin private
Definition at line 125 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetYmin(), Print(), and SetFieldRegion().
Double_t FairConstField::fZmax private
Definition at line 128 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetBx(), GetBy(), GetBz(), GetZmax(), Print(), and SetFieldRegion().
Double_t FairConstField::fZmin private
Definition at line 127 of file Tutorial3/simulation/FairConstField.h.
Referenced by FairConstField(), GetZmin(), Print(), and SetFieldRegion().
The documentation for this class was generated from the following files:
Tutorial3/simulation/FairConstField.h
Tutorial3/simulation/FairConstField.cxx