FairRroot: eventDisplay.C File Reference
example/Tutorial3/macro/eventDisplay.C File Reference
Functions
eventDisplay (TString mcEngine="TGeant3")
Function Documentation
eventDisplay (TString mcEngine = "TGeant3")
Definition at line 8 of file example/Tutorial3/macro/eventDisplay.C.
References FairEventManager::AddTask(), FairRun::GetRuntimeDb(), FairEventManager::Init(), FairParRootFileIo::open(), FairRuntimeDb::setFirstInput(), FairRunAna::SetInputFile(), and FairRun::SetOutputFile().
 {
   //-----User Settings:-----------------------------------------------
   TString  InputFile     ="data/testrun_" + mcEngine + ".root";
   TString  ParFile       ="data/testparams_" + mcEngine + ".root";
   TString  OutFile       ="data/tst.root";
   //------------------------------------------------------------------
   // -----   Reconstruction run   -------------------------------------------
   FairRunAna *fRun= new FairRunAna();
   fRun->SetInputFile(InputFile.Data());
   fRun->SetOutputFile(OutFile.Data());
   FairRuntimeDb* rtdb = fRun->GetRuntimeDb();
   FairParRootFileIo* parInput1 = new FairParRootFileIo();
   parInput1->open(ParFile.Data());
   rtdb->setFirstInput(parInput1);
   FairEventManager *fMan= new FairEventManager();
   //----------------------Traks and points -------------------------------------
   FairMCTracks    *Track     = new FairMCTracks("Monte-Carlo Tracks");
   FairMCPointDraw *TorinoDetectorPoints = new FairMCPointDraw("FairTestDetectorPoint", kRed, kFullSquare);
 //  FairHitDraw     *ToyHits   = new FairHitDraw("ToyHit");
   fMan->AddTask(Track);
   fMan->AddTask(TorinoDetectorPoints);
 //  fMan->AddTask(ToyHits);
   fMan->Init();
 }