FairRroot: MyHitSerializer< PodType, HitType > Class Template Reference
MyHitSerializer< PodType, HitType > Class Template Reference
#include <MyHitSerializer.h>
Public Member Functions
MyHitSerializer ()
virtual ~MyHitSerializer ()
virtual void DoSerialization (TClonesArray *array)
virtual FairMQMessage * SerializeMsg (TClonesArray *array)
void GetPayload (FairMQMessage *msg)
void SetMessage (FairMQMessage *msg)
FairMQMessage * GetMessage ()
Protected Attributes
PodType * fPayload
FairMQMessage * fMessage
int fNumInput
Detailed Description
template<typename PodType, typename HitType>
class MyHitSerializer< PodType, HitType >
Definition at line 42 of file MyHitSerializer.h.
Constructor & Destructor Documentation
template<typename PodType , typename HitType > MyHitSerializer< PodType, HitType >::MyHitSerializer () inline
Definition at line 46 of file MyHitSerializer.h.
 : BinaryBaseClassSerializer<PodType>() {}
template<typename PodType , typename HitType > virtual MyHitSerializer< PodType, HitType >::~MyHitSerializer () inline virtual
Definition at line 47 of file MyHitSerializer.h.
 {}
Member Function Documentation
template<typename PodType , typename HitType > virtual void MyHitSerializer< PodType, HitType >::DoSerialization (TClonesArray * array) inline virtual
Definition at line 51 of file MyHitSerializer.h.
References BinaryBaseClassSerializer< PodType >::fMessage, FairMQMessage::GetData(), and FairMQMessage::Rebuild().
Referenced by MyHitSerializer< PodType, HitType >::SerializeMsg().
     {
         int numOutput = array->GetEntriesFast();
         int outputSize = numOutput * sizeof(PodType);
         fMessage->Rebuild(outputSize);
         PodType* output = reinterpret_cast<PodType*>(fMessage->GetData());
         if (outputSize > 0)
         {
             for (int i = 0; i < numOutput; ++i)
             {
                 HitType* hit = (HitType*)array->At(i);
                 output[i].detID = hit->GetDetectorID();
                 output[i].posX = hit->GetX();
                 output[i].posY = hit->GetY();
                 output[i].posZ = hit->GetZ();
                 output[i].dposX = hit->GetDx();
                 output[i].dposY = hit->GetDy();
                 output[i].dposZ = hit->GetDz();
             }
         }
     }
FairMQMessage* BinaryBaseClassSerializer< PodType >::GetMessage () inline inherited
Definition at line 37 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fMessage.
     {
         return fMessage;
     }
void BinaryBaseClassSerializer< PodType >::GetPayload (FairMQMessage * msg) inline inherited
Definition at line 24 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fNumInput, BinaryBaseClassSerializer< TPayload >::fPayload, FairMQMessage::GetData(), and FairMQMessage::GetSize().
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
     {
         int inputSize = msg->GetSize();
         if(inputSize>0)
             fNumInput = inputSize / sizeof(TPayload);
         fPayload = static_cast<TPayload*>(msg->GetData());
     }
template<typename PodType , typename HitType > virtual FairMQMessage* MyHitSerializer< PodType, HitType >::SerializeMsg (TClonesArray * array) inline virtual
Definition at line 76 of file MyHitSerializer.h.
References MyHitSerializer< PodType, HitType >::DoSerialization(), and BinaryBaseClassSerializer< PodType >::fMessage.
     {
         DoSerialization(array);
         return fMessage;
     }
void BinaryBaseClassSerializer< PodType >::SetMessage (FairMQMessage * msg) inline inherited
Definition at line 32 of file BinaryBaseClassSerializer.h.
References BinaryBaseClassSerializer< TPayload >::fMessage.
     {
         fMessage=msg;
     }
Member Data Documentation
FairMQMessage* BinaryBaseClassSerializer< PodType >::fMessage protected inherited
Definition at line 46 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiSerializer< PodType, DigiType >::DoSerialization(), MyHitSerializer< PodType, HitType >::DoSerialization(), MyDigiSerializer< PodType, DigiType >::SerializeMsg(), and MyHitSerializer< PodType, HitType >::SerializeMsg().
int BinaryBaseClassSerializer< PodType >::fNumInput protected inherited
Definition at line 47 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
PodType * BinaryBaseClassSerializer< PodType >::fPayload protected inherited
Definition at line 45 of file BinaryBaseClassSerializer.h.
Referenced by MyDigiDeSerializer< PodType, DigiType >::DoDeSerialization(), and MyHitDeSerializer< PodType, HitType >::DoDeSerialization().
The documentation for this class was generated from the following file:
MyHitSerializer.h