FairRoot: FairContainer Class Reference
FairContainer Class Reference
#include <FairContFact.h>
Public Member Functions
FairContainer (const char *, const char *, const char *)
~FairContainer ()
void addContext (const char *)
Bool_t setActualContext (const char *c)
const char * getDefaultContext ()
const char * getActualContext ()
void print ()
TString getConcatName ()
const char * getContext ()
Protected Attributes
TList * contexts
TString actualContext
FairLogger * fLogger
Private Member Functions
FairContainer ()
FairContainer (const FairContainer &)
FairContainer & operator= (const FairContainer &)
Detailed Description
Definition at line 21 of file FairContFact.h.
Constructor & Destructor Documentation
FairContainer::FairContainer () private
FairContainer::FairContainer (const FairContainer &) private
FairContainer::FairContainer (const char * name, const char * title, const char * defContext)
Definition at line 45 of file FairContFact.cxx.
References addContext().
   : TNamed(name, title),
     contexts(new TList()),
     actualContext(""),
     fLogger(FairLogger::GetLogger())
 {
   // Constructor
   // Arguments:  name       = name of the corresponding parameter container
   //             title      = title of this parameter container
   //             defContext = default context of this parameter container
   addContext(defContext);
 }
FairContainer::~FairContainer ()
Definition at line 59 of file FairContFact.cxx.
References contexts.
 {
   // Destructor deletes the list of accepted contexts
   if (contexts) {
     contexts->Delete();
     delete contexts;
   }
 }
Member Function Documentation
void FairContainer::addContext (const char * name)
Definition at line 68 of file FairContFact.cxx.
References contexts.
Referenced by FairContainer(), FairTutorialDet2ContFact::setAllContainers(), NewDetectorContFact::setAllContainers(), FairPassiveContFact::setAllContainers(), FairTutorialDet1ContFact::setAllContainers(), FairTutorialDet4ContFact::setAllContainers(), FairTestDetectorContFact::setAllContainers(), FairRutherfordContFact::setAllContainers(), FairBaseContFact::setAllContainers(), MyPassiveContFact::setAllContainers(), FairDbTutContFact2::setAllContainers(), and FairDbTutContFact::setAllContainers().
 {
   // Adds a context to the list of accepted contexts
   TObjString* c=new TObjString(name);
   contexts->Add(c);
 }
const char* FairContainer::getActualContext () inline
Definition at line 41 of file FairContFact.h.
Referenced by FairContFact::getContainer().
 { return actualContext.Data(); }
TString FairContainer::getConcatName ()
Definition at line 118 of file FairContFact.cxx.
References actualContext, and contexts.
Referenced by FairTutorialDet2ContFact::createContainer(), NewDetectorContFact::createContainer(), FairTutorialDet4ContFact::createContainer(), FairTutorialDet1ContFact::createContainer(), FairPassiveContFact::createContainer(), FairRutherfordContFact::createContainer(), FairTestDetectorContFact::createContainer(), FairBaseContFact::createContainer(), FairDbTutContFact2::createContainer(), FairDbTutContFact::createContainer(), and FairContFact::getContainer().
 {
   // Returns the name of the parameter container used in the constructor and the
   // runtime database.
   // When the parameter container supportes different contexts (not only an empty string)
   // and the actual context set is not the default context, the new name of the parameter
   // container is concatinated as
   //      original container name  +  _  +  actualcontext
   TString cn=fName;
   if (!actualContext.IsNull() && actualContext!=((TObjString*)contexts->At(0))->String()) {
     cn+="_";
     cn+=actualContext;
   }
   return cn;
 }
const char * FairContainer::getContext ()
Definition at line 134 of file FairContFact.cxx.
References actualContext, and getDefaultContext().
Referenced by FairTutorialDet2ContFact::createContainer(), NewDetectorContFact::createContainer(), FairRutherfordContFact::createContainer(), FairTutorialDet4ContFact::createContainer(), FairPassiveContFact::createContainer(), FairTutorialDet1ContFact::createContainer(), FairTestDetectorContFact::createContainer(), FairBaseContFact::createContainer(), FairDbTutContFact2::createContainer(), and FairDbTutContFact::createContainer().
 {
   // return the actual context, if set, or the default context
   if (!actualContext.IsNull()) { return actualContext.Data(); }
   else { return getDefaultContext(); }
 }
const char * FairContainer::getDefaultContext ()
Definition at line 91 of file FairContFact.cxx.
References contexts.
Referenced by FairContFact::getContainer(), and getContext().
 {
   // Returns the default context
   return ((TObjString*)contexts->At(0))->String().Data();
 }
FairContainer& FairContainer::operator= (const FairContainer &) private
void FairContainer::print ()
Definition at line 97 of file FairContFact.cxx.
References actualContext, and contexts.
Referenced by FairContFact::print().
 {
   // prints the name, title of the container together with the actual context set
   // or all possible contexts, when the actual context was not set
   cout<<fName<<"\t"<<fTitle<<"\n";
   if (!actualContext.IsNull()) { cout<<"     actual context:  "<<actualContext<<"\n"; }
   else {
     TIter next(contexts);
     Int_t i=0;
     TObjString* c;
     cout<<"  all contexts:"<<"\n";
     while ((c=(TObjString*)next())) {
       if (c->String().IsNull()) { cout<<"     \"\""; }
       else { cout<<"     "<<c->String(); }
       if (i==0) { cout<<"\t default"; }
       cout<<"\n";
       i++;
     }
   }
 }
Bool_t FairContainer::setActualContext (const char * c)
Definition at line 75 of file FairContFact.cxx.
References actualContext, and contexts.
Referenced by FairContFact::addContext(), and FairContFact::getContainer().
 {
   // The function sets the actual context for the container, if it is in the list of
   // accepted contexts. When the actual context was already set before, it prints a warning
   // and ignores the second setting.
   // The function returns kFALSE, when the context is not in the list.
   if (contexts->FindObject(c)) {
     if (actualContext.IsNull()) { actualContext=c; }
     else Warning("addContext",
                    "Actual context of parameter container %s already defined as %s",
                    GetName(),actualContext.Data());
     return kTRUE;
   }
   return kFALSE;
 }
Member Data Documentation
TString FairContainer::actualContext protected
actual context set by the user
Definition at line 32 of file FairContFact.h.
Referenced by getConcatName(), getContext(), print(), and setActualContext().
TList* FairContainer::contexts protected
available contexts for this parameter container
Definition at line 30 of file FairContFact.h.
Referenced by addContext(), getConcatName(), getDefaultContext(), print(), setActualContext(), and ~FairContainer().
FairLogger* FairContainer::fLogger protected
Fair Logger
Definition at line 34 of file FairContFact.h.
The documentation for this class was generated from the following files:
FairContFact.h
FairContFact.cxx