FairRoot: FairTutorialDet4StraightLineFitter Class Reference
FairTutorialDet4StraightLineFitter Class Reference
#include <FairTutorialDet4StraightLineFitter.h>
Public Member Functions
FairTutorialDet4StraightLineFitter ()
~FairTutorialDet4StraightLineFitter ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void Exec (Option_t *opt)
virtual void SetParContainers ()
virtual void Finish ()
void SetVersion (Int_t val)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
Bool_t IsGoodEvent ()
FairTutorialDet4StraightLineFitter (const FairTutorialDet4StraightLineFitter &)
FairTutorialDet4StraightLineFitter operator= (const FairTutorialDet4StraightLineFitter &)
ClassDef (FairTutorialDet4StraightLineFitter, 1)
Private Attributes
TClonesArray * fHits
TClonesArray * fTracks
Int_t fVersion
Detailed Description
Definition at line 17 of file FairTutorialDet4StraightLineFitter.h.
Constructor & Destructor Documentation
FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter ()
Default constructor
Definition at line 24 of file FairTutorialDet4StraightLineFitter.cxx.
References DEBUG, FairLogger::endl(), and LOG.
   :FairTask("FairTutorialDet4StraightLineFitter"),
    fHits(NULL),
    fTracks(NULL),
    fVersion(2)
 {
   LOG(DEBUG) << "Default Constructor of FairTutorialDet4StraightLineFitter"
              << FairLogger::endl;
 }
FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter ()
Constructor with parameters (Optional) Destructor
Definition at line 35 of file FairTutorialDet4StraightLineFitter.cxx.
References DEBUG, FairLogger::endl(), fTracks, and LOG.
 {
   LOG(DEBUG) << "Destructor of FairTutorialDet4StraightLineFitter"
              << FairLogger::endl;
   if (fTracks) {
     fTracks->Delete();
     delete fTracks;
   }
 }
FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter (const FairTutorialDet4StraightLineFitter &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTutorialDet4StraightLineFitter::ClassDef (FairTutorialDet4StraightLineFitter , 1) private
void FairTutorialDet4StraightLineFitter::Exec (Option_t * opt) virtual
Executed for each event.
Definition at line 101 of file FairTutorialDet4StraightLineFitter.cxx.
References DEBUG, FairLogger::endl(), fHits, fVersion, FairHit::GetDx(), FairHit::GetDy(), FairHit::GetX(), FairHit::GetY(), FairHit::GetZ(), IsGoodEvent(), LOG, FairTrackParam::SetTx(), FairTrackParam::SetTy(), FairTrackParam::SetX(), FairTrackParam::SetY(), and FairTrackParam::SetZ().
 {
   LOG(DEBUG) << "Exec of FairTutorialDet4StraightLineFitter"
              << FairLogger::endl;
   if (!IsGoodEvent()) { return; }
   // Declare some variables
   FairTutorialDet4Hit* hit = NULL;
   Int_t detID   = 0;        // Detector ID
   Int_t trackID = 0;        // Track index
   Double_t x, y, z;         // Position
   Double_t dx = 0.1;        // Position error
   Double_t tof = 0.;        // Time of flight
   TVector3 pos, dpos;       // Position and error vectors
   // Loop over TofPoints
   Int_t nHits = fHits->GetEntriesFast();
   Float_t* ZPos = new Float_t[nHits];
   Float_t* XPos = new Float_t[nHits];
   Float_t* XPosErr = new Float_t[nHits];
   Float_t* YPos = new Float_t[nHits];
   Float_t* YPosErr = new Float_t[nHits];
   for (Int_t iHit=0; iHit<nHits; iHit++) {
     hit = (FairTutorialDet4Hit*) fHits->At(iHit);
     if ( ! hit) { continue; }
     XPos[iHit] = hit->GetX();
     YPos[iHit] = hit->GetY();
     ZPos[iHit] = hit->GetZ();
     XPosErr[iHit] = hit->GetDx();
     YPosErr[iHit] = hit->GetDy();
   }
   TF1* f1 = new TF1("f1", "[0]*x + [1]");
   TGraphErrors* LineGraph;
   LineGraph = new TGraphErrors(nHits, ZPos, XPos, 0, XPosErr);
   LineGraph->Fit("f1", "Q");
   Double_t SlopeX = f1->GetParameter(0);
   Double_t OffX = f1->GetParameter(1);
   Double_t Chi2X = f1->GetChisquare();
   Double_t SlopeY;
   Double_t OffY;
   Double_t Chi2Y;
   if ( 2 == fVersion ) {
     LineGraph = new TGraphErrors(nHits, ZPos, YPos, 0, YPosErr);
     LineGraph->Fit("f1", "Q");
     SlopeY = f1->GetParameter(0);
     OffY = f1->GetParameter(1);
     Chi2Y = f1->GetChisquare();
     LOG(DEBUG)<<XPos[0]<<","<<XPos[nHits-1]<<","<<YPos[0]<<","<<YPos[nHits-1]<<","<<ZPos[0]<<","<<ZPos[nHits-1]<<FairLogger::endl;
     Double_t XSlope = (XPos[nHits-1]-XPos[0])/(ZPos[nHits-1]-ZPos[0]);
     Double_t YSlope = (YPos[nHits-1]-YPos[0])/(ZPos[nHits-1]-ZPos[0]);
     LOG(DEBUG)<<"Slope(x,y): "<<SlopeX<<" ,"<<SlopeY<<FairLogger::endl;
     LOG(DEBUG)<<"Slope1(x,y): "<<XSlope<<" ,"<<YSlope<<FairLogger::endl;
     LOG(DEBUG)<<"Offset(x,y): "<<OffX<<" ,"<<OffY<<FairLogger::endl;
     LOG(DEBUG)<<"Chi2(x,y): "<<Chi2X<<" ,"<<Chi2Y<<FairLogger::endl;
   }
   FairTrackParam* track = new FairTrackParam();
   track->SetX(OffX);
   track->SetTx(SlopeX);
   track->SetZ(0.);
   if ( 2 == fVersion ) {
     track->SetY(OffY);
     track->SetTy(SlopeY);
   }
   new ((*fTracks)[0]) FairTrackParam(*track);
   //  const TMatrixFSym matrix;
   //  Double_t Z = 0.;
   //  new ((*fTracks)[0]) FairTrackParam(OffX, OffY, Z, SlopeX, SlopeY, matrix);
   delete[] ZPos;
   delete[] XPos;
   delete[] XPosErr;
   delete[] YPos;
   delete[] YPosErr;
 }
void FairTutorialDet4StraightLineFitter::Finish () virtual
Finish task called at the end of the run
Reimplemented from FairTask.
Definition at line 215 of file FairTutorialDet4StraightLineFitter.cxx.
References DEBUG, FairLogger::endl(), and LOG.
 {
   LOG(DEBUG) << "Finish of FairTutorialDet4StraightLineFitter"
              << FairLogger::endl;
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
InitStatus FairTutorialDet4StraightLineFitter::Init () virtual
Initiliazation of task at the beginning of a run
Reimplemented from FairTask.
Definition at line 61 of file FairTutorialDet4StraightLineFitter.cxx.
References DEBUG, FairLogger::endl(), ERROR, fHits, fTracks, FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kSUCCESS, LOG, and FairRootManager::Register().
 {
   LOG(DEBUG) << "Initilization of FairTutorialDet4StraightLineFitter"
              << FairLogger::endl;
   // Get a handle from the IO manager
   FairRootManager* ioman = FairRootManager::Instance();
   // Get a pointer to the previous already existing data level
   fHits = (TClonesArray*) ioman->GetObject("TutorialDetHit");
   if ( ! fHits ) {
     LOG(ERROR)<<"No InputDataLevelName array!\n"
               << "FairTutorialDet4StraightLineFitter will be inactive"<<FairLogger::endl;
     return kERROR;
   }
   // Create the TClonesArray for the output data and register
   // it in the IO manager
   fTracks = new TClonesArray("FairTrackParam", 100);
   ioman->Register("TutorialDetTrack","TutorialDet",fTracks,kTRUE);
   // Do whatever else is needed at the initilization stage
   // Create histograms to be filled
   // initialize variables
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
Bool_t FairTutorialDet4StraightLineFitter::IsGoodEvent () private
Definition at line 187 of file FairTutorialDet4StraightLineFitter.cxx.
References fHits, and FairHit::GetDetectorID().
Referenced by Exec().
 {
   // Check if each for the event there is maximum 1 hit per detector
   // station. In the moment we create tracks with all hits in the
   // event, so we have to check for this.
   // In the end the algorithm should be able to work also with
   // missing hits in some stations
   FairTutorialDet4Hit* hit;
   std::set<Int_t> detIdSet;
   std::set<Int_t>::iterator it;
   Int_t nHits = fHits->GetEntriesFast();
   for (Int_t iHit=0; iHit<nHits; ++iHit) {
     hit = (FairTutorialDet4Hit*) fHits->At(iHit);
     Int_t detId = hit->GetDetectorID();
     it = detIdSet.find(detId);
     if ( it == detIdSet.end() ) {
       detIdSet.insert(detId);
     } else {
       // find hit in already used detector station
       // this is not a good event
       return kFALSE;
     }
   }
   return kTRUE;
 }
FairTutorialDet4StraightLineFitter FairTutorialDet4StraightLineFitter::operator= (const FairTutorialDet4StraightLineFitter &) private
InitStatus FairTutorialDet4StraightLineFitter::ReInit () virtual
ReInitiliazation of task when the runID changes
Reimplemented from FairTask.
Definition at line 93 of file FairTutorialDet4StraightLineFitter.cxx.
References DEBUG, FairLogger::endl(), kSUCCESS, and LOG.
 {
   LOG(DEBUG) << "Initilization of FairTutorialDet4StraightLineFitter"
              << FairLogger::endl;
   return kSUCCESS;
 }
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairTutorialDet4StraightLineFitter::SetParContainers () virtual
Load the parameter container from the runtime database
Reimplemented from FairTask.
Definition at line 46 of file FairTutorialDet4StraightLineFitter.cxx.
References DEBUG, FairLogger::endl(), and LOG.
 {
   LOG(DEBUG) << "SetParContainers of FairTutorialDet4StraightLineFitter"
              << FairLogger::endl;
   // Load all necessary parameter containers from the runtime data base
   /*
   FairRunAna* ana = FairRunAna::Instance();
   FairRuntimeDb* rtdb=ana->GetRuntimeDb();
   <FairTutorialDet4StraightLineFitterDataMember> = (<ClassPointer>*)
     (rtdb->getContainer("<ContainerName>"));
   */
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
void FairTutorialDet4StraightLineFitter::SetVersion (Int_t val) inline
Definition at line 48 of file FairTutorialDet4StraightLineFitter.h.
References fVersion.
 {fVersion = val;}
Member Data Documentation
TClonesArray* FairTutorialDet4StraightLineFitter::fHits private
Input array from previous already existing data level
Definition at line 53 of file FairTutorialDet4StraightLineFitter.h.
Referenced by Exec(), Init(), and IsGoodEvent().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
TClonesArray* FairTutorialDet4StraightLineFitter::fTracks private
Output array to new data level
Definition at line 56 of file FairTutorialDet4StraightLineFitter.h.
Referenced by Init(), and ~FairTutorialDet4StraightLineFitter().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
Int_t FairTutorialDet4StraightLineFitter::fVersion private
Definition at line 58 of file FairTutorialDet4StraightLineFitter.h.
Referenced by Exec(), and SetVersion().
The documentation for this class was generated from the following files:
FairTutorialDet4StraightLineFitter.h
FairTutorialDet4StraightLineFitter.cxx