FairRoot: FairTestDetectorTimeDigiTask Class Reference
FairTestDetectorTimeDigiTask Class Reference
#include <FairTestDetectorTimeDigiTask.h>
Public Member Functions
FairTestDetectorTimeDigiTask ()
~FairTestDetectorTimeDigiTask ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
void SetTimeResolution (Double_t timeInNs)
Double_t GetTimeResolution ()
void RunTimeBased ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
Int_t CalcPad (Double_t posIn, Double_t posOut)
Double_t CalcTimeStamp (Double_t timeOfFlight)
FairTestDetectorTimeDigiTask (const FairTestDetectorTimeDigiTask &)
FairTestDetectorTimeDigiTask & operator= (const FairTestDetectorTimeDigiTask &)
ClassDef (FairTestDetectorTimeDigiTask, 1)
Private Attributes
Double_t fTimeResolution
TClonesArray * fPointArray
TClonesArray * fDigiArray
FairTestDetectorDigiWriteoutBuffer * fDataBuffer
Bool_t fTimeOrderedDigi
Detailed Description
Definition at line 18 of file FairTestDetectorTimeDigiTask.h.
Constructor & Destructor Documentation
FairTestDetectorTimeDigiTask::FairTestDetectorTimeDigiTask ()
Default constructor
Definition at line 25 of file FairTestDetectorTimeDigiTask.cxx.
     : FairTask()
     , fTimeResolution(100.)
     , fPointArray(NULL)
     , fDigiArray(NULL)
     , fDataBuffer(NULL)
     , fTimeOrderedDigi(kFALSE)
 {
 }
FairTestDetectorTimeDigiTask::~FairTestDetectorTimeDigiTask ()
Destructor
Definition at line 37 of file FairTestDetectorTimeDigiTask.cxx.
 {
 }
FairTestDetectorTimeDigiTask::FairTestDetectorTimeDigiTask (const FairTestDetectorTimeDigiTask &) private
Member Function Documentation
Int_t FairTestDetectorTimeDigiTask::CalcPad (Double_t posIn, Double_t posOut) private
Definition at line 115 of file FairTestDetectorTimeDigiTask.cxx.
Referenced by Exec().
 {
     Int_t result = (Int_t)(posIn + posOut) / 2;
     return result;
 }
Double_t FairTestDetectorTimeDigiTask::CalcTimeStamp (Double_t timeOfFlight) private
Definition at line 122 of file FairTestDetectorTimeDigiTask.cxx.
References fTimeResolution, FairRootManager::GetEventTime(), and FairRootManager::Instance().
Referenced by Exec().
 {
     Double_t eventTime = FairRootManager::Instance()->GetEventTime();
     Double_t detectionTime = gRandom->Gaus(0, fTimeResolution);
     Double_t result = eventTime + timeOfFlight + detectionTime;
     if (result < 0)
     {
         return 0;
     }
     else
     {
         return result;
     }
 }
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTestDetectorTimeDigiTask::ClassDef (FairTestDetectorTimeDigiTask , 1) private
void FairTestDetectorTimeDigiTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 70 of file FairTestDetectorTimeDigiTask.cxx.
References CalcPad(), CalcTimeStamp(), FairLogger::endl(), fDataBuffer, FairWriteoutBuffer::FillNewData(), fPointArray, fTimeResolution, FairRootManager::GetEventTime(), FairMCPoint::GetTime(), FairMCPoint::GetX(), FairTestDetectorPoint::GetXOut(), FairMCPoint::GetY(), FairTestDetectorPoint::GetYOut(), FairMCPoint::GetZ(), FairTestDetectorPoint::GetZOut(), INFO, FairRootManager::Instance(), and LOG.
 {
     // fDigiArray->Delete();
     // fill the map
     LOG(INFO) << "EventTime: "
               << FairRootManager::Instance()->GetEventTime()
               << FairLogger::endl;
     for (int ipnt = 0; ipnt < fPointArray->GetEntries(); ipnt++)
     {
         FairTestDetectorPoint* point = (FairTestDetectorPoint*)fPointArray->At(ipnt);
         if (!point)
         {
             continue;
         }
         Int_t xPad = CalcPad(point->GetX(), point->GetXOut());
         Int_t yPad = CalcPad(point->GetY(), point->GetYOut());
         Int_t zPad = CalcPad(point->GetZ(), point->GetZOut());
         Double_t timestamp = CalcTimeStamp(point->GetTime());
         FairTestDetectorDigi* digi = new FairTestDetectorDigi(xPad, yPad, zPad, timestamp);
         if (fTimeResolution > 0)
         {
             digi->SetTimeStampError(fTimeResolution / TMath::Sqrt(fTimeResolution));
         }
         else
         {
             digi->SetTimeStampError(0);
         }
         digi->SetLink(FairLink("FairTestDetectorPoint", ipnt));
         Double_t timeOfFlight = point->GetTime();
         Double_t eventTime = FairRootManager::Instance()->GetEventTime();
         fDataBuffer->FillNewData(digi, timeOfFlight + eventTime, digi->GetTimeStamp() + 10);
     }
 }
virtual void FairTask::Finish () inline protected virtual inherited
Action after each event. To be implemented in the derived class
Reimplemented in FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, FairDbTutAccessRtdbTask, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 111 of file FairTask.h.
Referenced by FairTask::FinishTask(), and FairTask::FinishTasks().
 { };
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
Double_t FairTestDetectorTimeDigiTask::GetTimeResolution () inline
Definition at line 37 of file FairTestDetectorTimeDigiTask.h.
References fTimeResolution.
     {
         return fTimeResolution;
     }
InitStatus FairTestDetectorTimeDigiTask::Init () virtual
Virtual method Init
Reimplemented from FairTask.
Definition at line 43 of file FairTestDetectorTimeDigiTask.cxx.
References FairWriteoutBuffer::ActivateBuffering(), FairLogger::endl(), ERROR, fDataBuffer, fPointArray, fTimeOrderedDigi, FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kFATAL, kSUCCESS, LOG, FairRootManager::RegisterWriteoutBuffer(), and WARNING.
 {
     FairRootManager* ioman = FairRootManager::Instance();
     if (!ioman)
     {
         LOG(ERROR) << "FairTestDetectorTimeDigiTask::Init: "
                    << "RootManager not instantiated!" << FairLogger::endl;
         return kFATAL;
     }
     fPointArray = (TClonesArray*)ioman->GetObject("FairTestDetectorPoint");
     if (!fPointArray)
     {
         LOG(WARNING) << "FairTestDetectorTimeDigiTask::Init: "
                      << "No Point array!" << FairLogger::endl;
         return kERROR;
     }
     // Create and register output array
     fDataBuffer = new FairTestDetectorDigiWriteoutBuffer("FairTestDetectorDigi", "TOY", kTRUE);
     fDataBuffer = (FairTestDetectorDigiWriteoutBuffer*)ioman->RegisterWriteoutBuffer("FairTestDetectorDigi", fDataBuffer);
     fDataBuffer->ActivateBuffering(fTimeOrderedDigi);
     return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairTestDetectorTimeDigiTask& FairTestDetectorTimeDigiTask::operator= (const FairTestDetectorTimeDigiTask &) private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTestDetectorTimeDigiTask::RunTimeBased () inline
Definition at line 42 of file FairTestDetectorTimeDigiTask.h.
References fTimeOrderedDigi.
     {
         fTimeOrderedDigi = kTRUE;
     }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
virtual void FairTask::SetParContainers () inline protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented in FairRingSorterTask, FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairTutorialDet4HitProducerIdealMisalign, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairMCMatchLoaderTask, FairTutorialDet4StraightLineFitter, NewTask, FairDbTutAccessRtdbTask, and FairTestDetectorHitProducerSmearing.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::SetParTask().
 { };
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTestDetectorTimeDigiTask::SetTimeResolution (Double_t timeInNs) inline
Definition at line 33 of file FairTestDetectorTimeDigiTask.h.
References fTimeResolution.
     {
         fTimeResolution = timeInNs;
     }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
FairTestDetectorDigiWriteoutBuffer* FairTestDetectorTimeDigiTask::fDataBuffer private
Definition at line 56 of file FairTestDetectorTimeDigiTask.h.
Referenced by Exec(), and Init().
TClonesArray* FairTestDetectorTimeDigiTask::fDigiArray private
Definition at line 54 of file FairTestDetectorTimeDigiTask.h.
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
TClonesArray* FairTestDetectorTimeDigiTask::fPointArray private
Definition at line 53 of file FairTestDetectorTimeDigiTask.h.
Referenced by Exec(), and Init().
Bool_t FairTestDetectorTimeDigiTask::fTimeOrderedDigi private
Definition at line 58 of file FairTestDetectorTimeDigiTask.h.
Referenced by Init(), and RunTimeBased().
Double_t FairTestDetectorTimeDigiTask::fTimeResolution private
Definition at line 51 of file FairTestDetectorTimeDigiTask.h.
Referenced by CalcTimeStamp(), Exec(), GetTimeResolution(), and SetTimeResolution().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairTestDetectorTimeDigiTask.h
FairTestDetectorTimeDigiTask.cxx