/* Generated by Together */

#include "CbmMCApplication.h"
#include "PndCave.h"
#include "CbmVolume.h"
#include "CbmVolumeList.h"
#include "TGeoMCGeometry.h"
#include "TGeoManager.h"
#include "TGeoVolume.h"
#include "TGeoMedium.h"

#include "CbmGeoLoader.h"
#include "CbmGeoInterface.h"
#include "PndGeoCave.h"
#include "CbmGeoRootBuilder.h"
#include "CbmRuntimeDb.h"
#include "PndGeoPassivePar.h"
#include "TObjArray.h"
#include "CbmGeoVolume.h"
#include "CbmGeoNode.h"
#include "CbmRun.h"


ClassImp(PndCave)
void PndCave::ConstructGeometry()
{
	CbmGeoLoader *loader=CbmGeoLoader::Instance();
	CbmGeoInterface *GeoInterface =loader->getGeoInterface();
	PndGeoCave *MGeo=new PndGeoCave();
	MGeo->setGeomFile(GetGeometryFileName());
	GeoInterface->addGeoModule(MGeo);
	Bool_t rc = GeoInterface->readSet(MGeo);
	if ( rc ) MGeo->create(loader->getGeoBuilder());

        TList* volList = MGeo->getListOfVolumes();
        // store geo parameter
        CbmRun *fRun = CbmRun::Instance();
        CbmRuntimeDb *rtdb= CbmRun::Instance()->GetRuntimeDb();
        PndGeoPassivePar* par=(PndGeoPassivePar*)(rtdb->getContainer("PndGeoPassivePar"));
        TObjArray *fSensNodes = par->GetGeoSensitiveNodes();
        TObjArray *fPassNodes = par->GetGeoPassiveNodes();

        TListIter iter(volList);
        CbmGeoNode* node   = NULL;
        CbmGeoVolume *aVol=NULL;

        while( (node = (CbmGeoNode*)iter.Next()) ) {
            aVol = dynamic_cast<CbmGeoVolume*> ( node );
            if ( node->isSensitive()  ) {
                fSensNodes->AddLast( aVol );
            }else{
                fPassNodes->AddLast( aVol );
            }
        }
        par->setChanged();
        par->setInputVersion(fRun->GetRunId(),1);

}
PndCave::PndCave(){
}

PndCave::~PndCave()
{

}
PndCave::PndCave(const char * name,  const char *Title)
  : CbmModule(name ,Title)
{
    world[0] = 0;
    world[1] = 0;
    world[2] = 0;
}
