/* Generated by Together */

#include "PndMagnet.h"
#include "CbmGeoLoader.h"
#include "CbmGeoInterface.h"
#include "PndGeoMagnet.h"
#include "CbmGeoRootBuilder.h"
#include "CbmRuntimeDb.h"
#include "PndGeoPassivePar.h"
#include "TObjArray.h"
#include "CbmRun.h"
#include "CbmGeoVolume.h"
#include "CbmGeoNode.h"

PndMagnet::~PndMagnet()
{
}
PndMagnet::PndMagnet()
{
}

PndMagnet::PndMagnet(const char * name, const char *Title)
  : CbmModule(name ,Title)
{
}

void PndMagnet::ConstructGeometry(){
 
  TString fileName=GetGeometryFileName();
  if (fileName.EndsWith(".geo")) {
      ConstructASCIIGeometry();
  } else if(fileName.EndsWith(".root")) {
      ConstructRootGeometry();
  } else {
      std::cout<< "Geometry format not supported " <<std::endl;
  }
}

Bool_t PndMagnet::CheckIfSensitive(std::string name){
	// just to get rid of the warrning during run, not need this is a passive element! 
}

void PndMagnet::ConstructASCIIGeometry(){
	CbmGeoLoader *loader=CbmGeoLoader::Instance();
	CbmGeoInterface *GeoInterface =loader->getGeoInterface();
	PndGeoMagnet *MGeo=new PndGeoMagnet();
	MGeo->setGeomFile(GetGeometryFileName());
	GeoInterface->addGeoModule(MGeo);
	Bool_t rc = GeoInterface->readSet(MGeo);
	if ( rc ) MGeo->create(loader->getGeoBuilder());

        TList* volList = MGeo->getListOfVolumes();
        // store geo parameter
        CbmRun *fRun = CbmRun::Instance();
        CbmRuntimeDb *rtdb= CbmRun::Instance()->GetRuntimeDb();
        PndGeoPassivePar* par=(PndGeoPassivePar*)(rtdb->getContainer("PndGeoPassivePar"));
        TObjArray *fSensNodes = par->GetGeoSensitiveNodes();
        TObjArray *fPassNodes = par->GetGeoPassiveNodes();

        TListIter iter(volList);
        CbmGeoNode* node   = NULL;
        CbmGeoVolume *aVol=NULL;

        while( (node = (CbmGeoNode*)iter.Next()) ) {
            aVol = dynamic_cast<CbmGeoVolume*> ( node );
            if ( node->isSensitive()  ) {
                fSensNodes->AddLast( aVol );
            }else{
                fPassNodes->AddLast( aVol );
            }
        }
	ProcessNodes( volList );
        par->setChanged();
        par->setInputVersion(fRun->GetRunId(),1);	
}

ClassImp(PndMagnet)














