/* Generated by Together */

#include "PndTarget.h"
#include "CbmGeoLoader.h"
#include "CbmGeoInterface.h"
#include "PndGeoTarget.h"
#include "CbmGeoRootBuilder.h"
#include "CbmRuntimeDb.h"
#include "PndGeoPassivePar.h"
#include "TObjArray.h"
#include "CbmRun.h"
#include "CbmGeoVolume.h"
#include "CbmGeoNode.h"

PndTarget::~PndTarget()
{
}
PndTarget::PndTarget()
{
}

PndTarget::PndTarget(const char * name,  const char * title)
  : CbmModule(name ,title)
{
}
void PndTarget::ConstructGeometry()
{
	CbmGeoLoader *loader=CbmGeoLoader::Instance();
	CbmGeoInterface *GeoInterface =loader->getGeoInterface();
	PndGeoTarget *MGeo=new PndGeoTarget();
	MGeo->setGeomFile(GetGeometryFileName());
	GeoInterface->addGeoModule(MGeo);
	Bool_t rc = GeoInterface->readSet(MGeo);
	if ( rc ) MGeo->create(loader->getGeoBuilder());

        TList* volList = MGeo->getListOfVolumes();
        // store geo parameter
        CbmRun *fRun = CbmRun::Instance();
        CbmRuntimeDb *rtdb= CbmRun::Instance()->GetRuntimeDb();
        PndGeoPassivePar* par=(PndGeoPassivePar*)(rtdb->getContainer("PndGeoPassivePar"));
        TObjArray *fSensNodes = par->GetGeoSensitiveNodes();
        TObjArray *fPassNodes = par->GetGeoPassiveNodes();

        TListIter iter(volList);
        CbmGeoNode* node   = NULL;
        CbmGeoVolume *aVol=NULL;

        while( (node = (CbmGeoNode*)iter.Next()) ) {
            aVol = dynamic_cast<CbmGeoVolume*> ( node );
            if ( node->isSensitive()  ) {
                fSensNodes->AddLast( aVol );
            }else{
                fPassNodes->AddLast( aVol );
            }
        }
	ProcessNodes( volList );
        par->setChanged();
        par->setInputVersion(fRun->GetRunId(),1);

}
ClassImp(PndTarget)



