FairRoot: FairGeane Class Reference
FairGeane Class Reference
#include <FairGeane.h>
Public Member Functions
FairGeane (const char *name, TString UserConfig="", TString UserCuts="")
FairGeane (TString fUserConfig="", TString fUserCuts="")
InitStatus Init ()
void SetParTask ()
virtual ~FairGeane ()
void SetField (FairField *field)
void InitTask ()
void ReInitTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Public Attributes
ClassDef(FairGeane, 1) protected const char * fName
TString fUserConfig
TString fUserCuts
Protected Member Functions
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairGeane (const FairGeane &)
FairGeane & operator= (const FairGeane &)
Detailed Description
Definition at line 23 of file FairGeane.h.
Constructor & Destructor Documentation
FairGeane::FairGeane (const char * name, TString UserConfig = "", TString UserCuts = "")
Default constructor
Definition at line 35 of file FairGeane.cxx.
   :  FairTask("Geane Application"),
      fApp(new FairGeaneApplication(kTRUE)),
      fName(name),
      fUserConfig(UserConfig),
      fUserCuts (UserCuts)
 {
   //Create a new Geometry
   new TGeoManager("Geometry", "Geane geometry");
   // now import the geometry from file to the empty TGeo
   TGeoManager::Import(name);
 }
FairGeane::FairGeane (TString fUserConfig = "", TString fUserCuts = "")
Definition at line 50 of file FairGeane.cxx.
   : FairTask("Geane Application"),
     fApp(new FairGeaneApplication(kFALSE)),
     fName(""),
     fUserConfig(UserConfig),
     fUserCuts (UserCuts)
 {
 }
FairGeane::~FairGeane () virtual
Definition at line 148 of file FairGeane.cxx.
 {
 }
FairGeane::FairGeane (const FairGeane &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
virtual void FairTask::Finish () inline protected virtual inherited
Action after each event. To be implemented in the derived class
Reimplemented in FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, FairDbTutAccessRtdbTask, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 111 of file FairTask.h.
Referenced by FairTask::FinishTask(), and FairTask::FinishTasks().
 { };
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
InitStatus FairGeane::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 67 of file FairGeane.cxx.
References FairField(), fUserConfig, fUserCuts, FairRunAna::GetField(), FairRunAna::Instance(), and kSUCCESS.
 {
   cout <<  "------------------------FairGeane::Init ()------------------------------" << endl;
   TString LibMacro;
   TString LibFunction;
   TString ConfigMacro;
   TString cuts=fUserCuts;
   if(cuts== TString("")) { cuts="SetCuts.C"; }
   TString work = getenv("VMCWORKDIR");
   TString work_config=work+"/gconfig/";
   work_config.ReplaceAll("//","/");
   TString config_dir= getenv("CONFIG_DIR");
   config_dir.ReplaceAll("//","/");
   Bool_t AbsPath=kFALSE;
   if (!config_dir.EndsWith("/")) { config_dir+="/"; }
   TString geaneLibMacro="g3libs.C";
   TString geaneMacro;
   if(fUserConfig.IsNull()) {
     geaneMacro="Geane.C";
     fUserConfig = geaneMacro;
   } else {
     if (fUserConfig.Contains("/")) { AbsPath=kTRUE; }
     geaneMacro = fUserConfig;
     cout << "---------------User config is used :  " << geaneMacro.Data() <<"-----------------"<< endl;
   }
   if (TString(gSystem->FindFile(config_dir.Data(),geaneLibMacro)) != TString("")) {
     cout << "---User path for Configuration (g3libs.C) is used : " <<  config_dir.Data() << endl;
   } else {
     geaneLibMacro=work_config+"g3libs.C";
   }
   LibMacro=geaneLibMacro;
   LibFunction="g3libs()";
   if (!AbsPath && TString(gSystem->FindFile(config_dir.Data(),geaneMacro)) != TString("")) {
     cout << "---User path for Configuration (Geane.C) is used : " <<  config_dir.Data() << endl;
     ConfigMacro =geaneMacro;
   } else {
     if(AbsPath) { ConfigMacro = fUserConfig; }
     else { ConfigMacro =work_config+fUserConfig; }
   }
   if (!AbsPath &&TString(gSystem->FindFile(config_dir.Data(),cuts)) != TString("")) {
     cout << "---User path for Cuts and Processes  (SetCuts.C) is used : " <<  config_dir.Data() << endl;
   } else {
     cuts =work_config+ "SetCuts.C";
   }
   gROOT->LoadMacro(LibMacro.Data());
   gROOT->ProcessLine(LibFunction.Data());
   gROOT->LoadMacro(ConfigMacro.Data());
   gROOT->ProcessLine("Config()");
   //gROOT->LoadMacro(cuts);
   //gROOT->ProcessLine("SetCuts()");
   FairField* field=FairRunAna::Instance()->GetField();
   field->Print();
   fApp->SetField(field);
   fApp->InitMC(ConfigMacro.Data(), "");
   cout <<"I- FairGeane::FairGeane:  Geane is Initialized " << endl;
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairGeane& FairGeane::operator= (const FairGeane &) private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairGeane::SetField (FairField * field)
Definition at line 152 of file FairGeane.cxx.
 {
   cout<< "\033[5m\033[31m -W- FairGeane::SetField  This method is not used anymore, use FairRunAna::SetField instead \033[0m " << endl;
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
virtual void FairTask::SetParContainers () inline protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented in FairRingSorterTask, FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairTutorialDet4HitProducerIdealMisalign, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairMCMatchLoaderTask, FairTutorialDet4StraightLineFitter, NewTask, FairDbTutAccessRtdbTask, and FairTestDetectorHitProducerSmearing.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::SetParTask().
 { };
void FairGeane::SetParTask ()
Definition at line 61 of file FairGeane.cxx.
 {
   cout <<  "------------------------FairGeane::SetParTask()------------------------------" << endl;
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
ClassDef (FairGeane,1) protected const char* FairGeane::fName
Definition at line 42 of file FairGeane.h.
TString FairGeane::fUserConfig
Definition at line 47 of file FairGeane.h.
Referenced by Init().
TString FairGeane::fUserCuts
Definition at line 48 of file FairGeane.h.
Referenced by Init().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairGeane.h
FairGeane.cxx