FairRroot: FairTimeStampPointDraw Class Reference
FairTimeStampPointDraw Class Reference
#include <FairTimeStampPointDraw.h>
Public Member Functions
FairTimeStampPointDraw ()
FairTimeStampPointDraw (const char *name, Int_t iVerbose=1)
virtual ~FairTimeStampPointDraw ()
virtual Double_t GetTimeWindowPlus ()
virtual Double_t GetTimeWindowMinus ()
virtual void SetVerbose (Int_t iVerbose)
virtual void SetBoxDimensions (Double_t x, Double_t y, Double_t z)
virtual void SetTimeWindowMinus (Double_t val)
virtual void SetTimeWindowPlus (Double_t val)
virtual void SetStartTime (Double_t val)
virtual void UseEventTimeAsStartTime (Bool_t val=kTRUE)
virtual void Exec (Option_t *option)
FairBoxSet * CreateBoxSet ()
void Reset ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Finish ()
virtual void AddBoxes (FairBoxSet *set, TObject *obj, Int_t i=0)
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
TClonesArray * fList
FairEventManager * fEventManager
FairRootManager * fManager
FairBoxSet * fq
Double_t fX
Double_t fY
Double_t fZ
Double_t fTimeWindowPlus
Double_t fTimeWindowMinus
Double_t fStartTime
Bool_t fUseEventTime
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
virtual TVector3 GetVector (TObject *obj)
virtual Int_t GetValue (TObject *obj, Int_t i)
ClassDef (FairTimeStampPointDraw, 1)
Detailed Description
Definition at line 25 of file FairTimeStampPointDraw.h.
Constructor & Destructor Documentation
FairTimeStampPointDraw::FairTimeStampPointDraw ()
Definition at line 24 of file FairTimeStampPointDraw.cxx.
 {
   // TODO Auto-generated constructor stub
 }
FairTimeStampPointDraw::FairTimeStampPointDraw (const char * name, Int_t iVerbose = 1)
Definition at line 31 of file FairTimeStampPointDraw.cxx.
                                                                               :FairBoxSetDraw(name, iVerbose)
 {
 }
FairTimeStampPointDraw::~FairTimeStampPointDraw () virtual
Definition at line 35 of file FairTimeStampPointDraw.cxx.
 {
   // TODO Auto-generated destructor stub
 }
Member Function Documentation
void FairBoxSetDraw::AddBoxes (FairBoxSet * set, TObject * obj, Int_t i = 0) protected virtual inherited
Definition at line 142 of file FairBoxSetDraw.cxx.
References FairBoxSetDraw::fVerbose, FairBoxSetDraw::GetValue(), and FairBoxSetDraw::GetVector().
Referenced by FairBoxSetDraw::Exec().
 {
   TVector3 point = GetVector(obj);
   set->AddBox(point.X(),point.Y(),point.Z());
   set->DigitValue(GetValue(obj, i));
   if(fVerbose>2) {
     cout<<  "FairBoxSetDraw::Init() Add point " << i << ": " <<point.X()<< " "<<point.Y()<< " "<< point.Z()<< " " << endl;
   }
 }
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTimeStampPointDraw::ClassDef (FairTimeStampPointDraw , 1) private
FairBoxSet * FairBoxSetDraw::CreateBoxSet () inherited
Definition at line 158 of file FairBoxSetDraw.cxx.
Referenced by FairBoxSetDraw::Exec().
 {
   FairBoxSet* aBoxSet = new FairBoxSet(this, GetName());
   aBoxSet->Reset(FairBoxSet::kBT_AABoxFixedDim, kFALSE, 32);
   aBoxSet->SetDefWidth(0.3);
   aBoxSet->SetDefHeight(0.3);
   aBoxSet->SetDefDepth(0.3);
   fq = aBoxSet;
   return aBoxSet;
 }
void FairBoxSetDraw::Exec (Option_t * option) virtual inherited
Executed task
Definition at line 108 of file FairBoxSetDraw.cxx.
References FairBoxSetDraw::AddBoxes(), FairBoxSetDraw::CreateBoxSet(), FairBoxSetDraw::fEventManager, FairBoxSetDraw::fList, FairBoxSetDraw::fStartFunctor, FairBoxSetDraw::fStartTime, FairBoxSetDraw::fStopFunctor, FairBoxSetDraw::fTimeWindowMinus, FairBoxSetDraw::fTimeWindowPlus, FairBoxSetDraw::fUseEventTime, FairBoxSetDraw::fVerbose, FairRootManager::GetData(), FairRootManager::GetEventTime(), FairRunAna::Instance(), FairRootManager::Instance(), and FairBoxSetDraw::Reset().
 {
   if(IsActive()) {
     TObject* p;
     Reset();
     //  cout<<  "FairBoxSetDraw::Init() Exec! " << fList->GetEntriesFast() << endl;
     CreateBoxSet();
     if (FairRunAna::Instance()->IsTimeStamp()) {
       fList->Clear();
       Double_t eventTime = FairRootManager::Instance()->GetEventTime();
       if (fUseEventTime) { fStartTime = eventTime - fTimeWindowMinus; }
       cout << "EventTime: " << eventTime << " TimeWindow: " << fStartTime << " - " << eventTime + fTimeWindowPlus << std::endl;
       fList = FairRootManager::Instance()->GetData(GetName(), fStartFunctor, fStartTime, fStopFunctor, eventTime + fTimeWindowPlus); //FairRootManager::Instance()->GetEventTime() +
     }
     //fList = (TClonesArray *)fManager->GetObject(GetName());
     if (fVerbose > 1) {
       std::cout << GetName() << " fList: " << fList->GetEntries() << std::endl;
     }
     for (Int_t i=0; i<fList->GetEntriesFast(); ++i) {
       p=fList->At(i);
       if (fVerbose > 2) {
 //        FairTimeStamp* data = (FairTimeStamp*)p;
 //        cout << "TimeStamp: " <<  data->GetTimeStamp() << std::endl;
       }
       AddBoxes(fq, p, i);
     }
     gEve->AddElement(fq, fEventManager );
     gEve->Redraw3D(kFALSE);
   }
 }
void FairBoxSetDraw::Finish () protected virtual inherited
Action after each event
Reimplemented from FairTask.
Definition at line 191 of file FairBoxSetDraw.cxx.
 {
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
virtual Double_t FairBoxSetDraw::GetTimeWindowMinus () inline virtual inherited
Definition at line 60 of file FairBoxSetDraw.h.
References FairBoxSetDraw::fTimeWindowMinus.
Referenced by FairBoxSet::GetTimeWindowMinus().
 {return fTimeWindowMinus;}
virtual Double_t FairBoxSetDraw::GetTimeWindowPlus () inline virtual inherited
Definition at line 59 of file FairBoxSetDraw.h.
References FairBoxSetDraw::fTimeWindowPlus.
Referenced by FairBoxSet::GetTimeWindowPlus().
 {return fTimeWindowPlus;}
Int_t FairTimeStampPointDraw::GetValue (TObject * obj, Int_t i) private virtual
Reimplemented from FairBoxSetDraw.
Definition at line 46 of file FairTimeStampPointDraw.cxx.
References FairTimeStamp::GetTimeStamp().
 {
   FairTimeStamp* tsdata = (FairTimeStamp*)obj;
   if (tsdata > 0) {
     return (Int_t)tsdata->GetTimeStamp();
   } else {
     return 0;
   }
 }
TVector3 FairTimeStampPointDraw::GetVector (TObject * obj) private virtual
Implements FairBoxSetDraw.
Definition at line 40 of file FairTimeStampPointDraw.cxx.
References FairMCPoint::GetX(), FairMCPoint::GetY(), and FairMCPoint::GetZ().
 {
   FairMCPoint* hit =(FairMCPoint*)obj;
   return TVector3(hit->GetX(), hit->GetY(), hit->GetZ());
 }
InitStatus FairBoxSetDraw::Init () protected virtual inherited
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 79 of file FairBoxSetDraw.cxx.
References FairBoxSetDraw::fEventManager, FairBoxSetDraw::fList, FairBoxSetDraw::fManager, FairBoxSetDraw::fStartFunctor, FairBoxSetDraw::fStopFunctor, FairBoxSetDraw::fVerbose, FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), kERROR, and kSUCCESS.
 {
   if(fVerbose>1) {
     cout<<  "FairBoxSetDraw::Init()" << endl;
   }
   fManager = FairRootManager::Instance();
   fList = (TClonesArray*)FairRootManager::Instance()->GetObject(GetName());
   //std::cout << fList << std::endl;
   if (fList==0) {
     cout << "FairBoxSetDraw::Init()  branch " << GetName() << " Not found! Task will be deactivated "<< endl;
     SetActive(kFALSE);
     return kERROR;
   }
   if(fVerbose>2) {
     cout<<  "FairBoxSetDraw::Init() get track list" <<  fList<< endl;
   }
   fEventManager =FairEventManager::Instance();
   if(fVerbose>2) {
     cout<<  "FairBoxSetDraw::Init() get instance of FairEventManager " << endl;
   }
   fq=0;
   fStartFunctor = new StopTime();
   fStopFunctor = new StopTime();
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairBoxSetDraw::Reset () inherited
Definition at line 195 of file FairBoxSetDraw.cxx.
References FairBoxSetDraw::fEventManager.
Referenced by FairBoxSetDraw::Exec().
 {
   if(fq!=0) {
     fq->Reset();
     gEve->RemoveElement(fq, fEventManager );
   }
 }
virtual void FairBoxSetDraw::SetBoxDimensions (Double_t x, Double_t y, Double_t z) inline virtual inherited
Definition at line 64 of file FairBoxSetDraw.h.
References FairBoxSetDraw::fX, FairBoxSetDraw::fY, and FairBoxSetDraw::fZ.
{
       fX = x;
       fY = y;
       fZ = z;
     }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairBoxSetDraw::SetParContainers () protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 185 of file FairBoxSetDraw.cxx.
 {
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
virtual void FairBoxSetDraw::SetStartTime (Double_t val) inline virtual inherited
Definition at line 72 of file FairBoxSetDraw.h.
References FairBoxSetDraw::fStartTime.
 {fStartTime = val;}
void FairBoxSetDraw::SetTimeWindowMinus (Double_t val) virtual inherited
Definition at line 170 of file FairBoxSetDraw.cxx.
References FairBoxSetDraw::fTimeWindowMinus.
Referenced by FairBoxSet::SetTimeWindowMinus().
 {
   fTimeWindowMinus = val;
 }
void FairBoxSetDraw::SetTimeWindowPlus (Double_t val) virtual inherited
Definition at line 175 of file FairBoxSetDraw.cxx.
References FairBoxSetDraw::fTimeWindowPlus.
Referenced by FairBoxSet::SetTimeWindowPlus().
 {
   fTimeWindowPlus = val;
 }
virtual void FairBoxSetDraw::SetVerbose (Int_t iVerbose) inline virtual inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 63 of file FairBoxSetDraw.h.
References FairBoxSetDraw::fVerbose.
 {fVerbose = iVerbose;};
virtual void FairBoxSetDraw::UseEventTimeAsStartTime (Bool_t val = kTRUE) inline virtual inherited
Definition at line 73 of file FairBoxSetDraw.h.
References FairBoxSetDraw::fUseEventTime.
 {fUseEventTime = val;}
Member Data Documentation
FairEventManager* FairBoxSetDraw::fEventManager protected inherited
Definition at line 95 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::Exec(), FairBoxSetDraw::Init(), and FairBoxSetDraw::Reset().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
TClonesArray* FairBoxSetDraw::fList protected inherited
Definition at line 94 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::Exec(), and FairBoxSetDraw::Init().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
FairRootManager* FairBoxSetDraw::fManager protected inherited
Definition at line 96 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::Init().
FairBoxSet* FairBoxSetDraw::fq protected inherited
Definition at line 97 of file FairBoxSetDraw.h.
Double_t FairBoxSetDraw::fStartTime protected inherited
Definition at line 102 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::Exec(), and FairBoxSetDraw::SetStartTime().
Double_t FairBoxSetDraw::fTimeWindowMinus protected inherited
Definition at line 101 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::Exec(), FairBoxSetDraw::GetTimeWindowMinus(), and FairBoxSetDraw::SetTimeWindowMinus().
Double_t FairBoxSetDraw::fTimeWindowPlus protected inherited
Definition at line 100 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::Exec(), FairBoxSetDraw::GetTimeWindowPlus(), and FairBoxSetDraw::SetTimeWindowPlus().
Bool_t FairBoxSetDraw::fUseEventTime protected inherited
Definition at line 103 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::Exec(), and FairBoxSetDraw::UseEventTimeAsStartTime().
Int_t FairBoxSetDraw::fVerbose protected inherited
Definition at line 84 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::AddBoxes(), FairBoxSetDraw::Exec(), FairBoxSetDraw::Init(), and FairBoxSetDraw::SetVerbose().
Double_t FairBoxSetDraw::fX protected inherited
Definition at line 98 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::SetBoxDimensions().
Double_t FairBoxSetDraw::fY protected inherited
Definition at line 98 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::SetBoxDimensions().
Double_t FairBoxSetDraw::fZ protected inherited
Definition at line 98 of file FairBoxSetDraw.h.
Referenced by FairBoxSetDraw::SetBoxDimensions().
The documentation for this class was generated from the following files:
FairTimeStampPointDraw.h
FairTimeStampPointDraw.cxx