FairRroot: FairEvtGenGenerator Class Reference
FairEvtGenGenerator Class Reference
#include <FairEvtGenGenerator.h>
Public Member Functions
FairEvtGenGenerator ()
FairEvtGenGenerator (const char *fileName)
FairEvtGenGenerator (const char *fileName, Double_t Rsigma, TF1 *DensityFunction)
virtual ~FairEvtGenGenerator ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
ClassDef (FairGenerator, 1)
Private Member Functions
void CloseInput ()
Input file pointer.
FairEvtGenGenerator (const FairEvtGenGenerator &)
FairEvtGenGenerator & operator= (const FairEvtGenGenerator &)
ClassDef (FairEvtGenGenerator, 1)
Private Attributes
const Char_t * fFileName
FILE * fInputFile
Input file Name.
int fGasmode
double fRsigma
TF1 * fDensityFunction
Detailed Description
Definition at line 95 of file FairEvtGenGenerator.h.
Constructor & Destructor Documentation
FairEvtGenGenerator::FairEvtGenGenerator ()
Default constructor without arguments should not be used.
Definition at line 28 of file FairEvtGenGenerator.cxx.
   : FairGenerator(),
     fFileName(""),
     fInputFile(NULL),
     fGasmode(0),
     fRsigma (0.),
     fDensityFunction(NULL)
 {
 }
FairEvtGenGenerator::FairEvtGenGenerator (const char * fileName)
Standard constructor.
Parameters
fileName The input file name
Definition at line 40 of file FairEvtGenGenerator.cxx.
References fFileName, and fInputFile.
   :FairGenerator ("EvtGen", fileName),
    fFileName(fileName),
    fInputFile(NULL),
    fGasmode(0),
    fRsigma (0.),
    fDensityFunction(0)
 {
   cout << "-I FairEvtGenGenerator: Opening input file " << fileName << endl;
   if ((fInputFile = fopen(fFileName,"r"))==NULL)
     //  fInputFile = new ifstream(fFileName);
     //  if ( ! fInputFile->is_open() )
   {
     Fatal("FairEvtGenGenerator","Cannot open input file.");
   }
   // fPDG=TDatabasePDG::Instance();
 }
FairEvtGenGenerator::FairEvtGenGenerator (const char * fileName, Double_t Rsigma, TF1 * DensityFunction)
Parameters
fileName The input file name, DensityFunction: axial gas density
Definition at line 62 of file FairEvtGenGenerator.cxx.
References fFileName, and fInputFile.
   :FairGenerator ("EvtGen", fileName),
    fFileName(fileName),
    fInputFile(NULL),
    fGasmode(1),
    fRsigma (Rsigma),
    fDensityFunction(DensityFunction)
 {
   cout << "-I FairEvtGenGenerator: Opening input file " << fileName << endl;
   if ((fInputFile = fopen(fFileName,"r"))==NULL) {
     Fatal("FairEvtGenGenerator","Cannot open input file.");
   }
 }
FairEvtGenGenerator::~FairEvtGenGenerator () virtual
Destructor.
Definition at line 81 of file FairEvtGenGenerator.cxx.
References fDensityFunction, and fInputFile.
 {
   if(fDensityFunction) { delete fDensityFunction; }
   if(fInputFile) { fclose(fInputFile); }
 }
FairEvtGenGenerator::FairEvtGenGenerator (const FairEvtGenGenerator &) private
Member Function Documentation
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
FairEvtGenGenerator::ClassDef (FairEvtGenGenerator , 1) private
FairGenerator * FairGenerator::CloneGenerator () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
 {
   Fatal("CloneGenerator","Has to be overriden in multi-threading applications.");
   return 0;
 }
void FairEvtGenGenerator::CloseInput () private
Input file pointer.
Private method CloseInput. Just for convenience. Closes the input file properly. Called from destructor and from ReadEvent.
Definition at line 181 of file FairEvtGenGenerator.cxx.
References fFileName, and fInputFile.
Referenced by ReadEvent().
 {
   if ( fInputFile ) {
     //if ( fInputFile->is_open() ) {
     {
       cout << "-I FairEvtGenGenerator: Closing input file "
            << fFileName << endl;
       //  fInputFile->close();
       fclose(fInputFile);
     }
     // delete fInputFile;
     fInputFile = NULL;
   }
 }
virtual Bool_t FairGenerator::Init () inline virtual inherited
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
 { return kTRUE;}
FairEvtGenGenerator& FairEvtGenGenerator::operator= (const FairEvtGenGenerator &) private
Bool_t FairEvtGenGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Reads on event from the input file and pushes the tracks onto the stack. Abstract method in base class.
Parameters
primGen pointer to the FairrimaryGenerator
Implements FairGenerator.
Definition at line 91 of file FairEvtGenGenerator.cxx.
References FairPrimaryGenerator::AddTrack(), buffer, CloseInput(), fDensityFunction, fGasmode, fInputFile, fRsigma, fX, fY, and fZ.
 {
   // Check for input file
   if (!fInputFile) {
     // if ( ! fInputFile->is_open() ) {
     cout << "-E FairEvtGenGenerator: Input file not open!" << endl;
     return kFALSE;
   }
   // Define event variable to be read from file
   Int_t ntracks = 0, eventID = 0, ncols = 0;
   // Define track variables to be read from file
   Int_t nLine = 0, pdgID = 0, nDecay = 0, nM1 = -1, nM2 = -1, nDF = -1, nDL = -1;
   Float_t fPx = 0., fPy = 0., fPz = 0., fE = 0.;
   Float_t fVx = 0., fVy = 0., fVz = 0., fT = 0.;
   // Read event header line from input file
   Int_t max_nr = 0;
   Text_t buffer[200];
   ncols = fscanf(fInputFile,"%d\t%d", &eventID, &ntracks);
   if (ncols && ntracks>0) {
     // cout << "Event number: " << eventID << "\tNtracks: " << ntracks << endl;
     for (Int_t ii=0; ii<15; ii++) {
       ncols = fscanf(fInputFile,"%s",buffer);
       //   cout << buffer << "\t" ;
     }
     //cout << endl;
     for (Int_t ll=0; ll<ntracks; ll++) {
       ncols = fscanf(fInputFile,"%d %d %d %d %d %d %d %g %f %f %f %f %f %f %f", &nLine, &pdgID, &nDecay, &nM1, &nM2, &nDF, &nDL, &fPx, &fPy, &fPz, &fE, &fT, &fVx, &fVy, &fVz);
 //  cout << nLine << "\t" << pdgID << "\t" << nDecay << "\t" << nM1 << "\t" << nM2 << "\t" << nDF << "\t" << nDL <<
       //  "\t" << fPx << "\t" << fPy << "\t" << fPz << "\t" << fE << "\t" << fT << "\t" << fVx << "\t" << fVy << "\t" << fVz << endl;
       max_nr = max(max_nr, nDF);
       max_nr = max(max_nr, nDL);
       if ((nDF==-1) && (nDL==-1)) {
         /* Check if fGasmode is set */
         if (fGasmode == 1) {
           // Random 2D point in a circle of radius r (simple beamprofile)
           Double_t fX, fY, fZ, radius;
           radius = gRandom->Gaus(0,fRsigma);
           gRandom->Circle(fX, fY, radius);
           fVx = fVx + fX;
           fVy = fVy + fY;
           // calculate fZ according to some (probability) density function of the
           // gas
           fZ=fDensityFunction->GetRandom();
           fVz = fVz + fZ;
         }
 //    printf("Insert coordinates: %f, %f, %f ...\n", fVx, fVy, fVz);
         primGen->AddTrack(pdgID, fPx, fPy, fPz, fVx, fVy, fVz);
       }
     }
   } else {
     cout << "-I FairEvtGenGenerator: End of input file reached " << endl;
     CloseInput();
     return kFALSE;
   }
   // If end of input file is reached : close it and abort run
   if ( feof(fInputFile) ) {
     cout << "-I FairEvtGenGenerator: End of input file reached " << endl;
     CloseInput();
     return kFALSE;
   }
   /*
     cout << "-I FairEvtGenGenerator: Event " << eventID << ",  vertex = ("
     << vx << "," << vy << "," << vz << ") cm,  multiplicity "
     << ntracks << endl;
   */
   return kTRUE;
 }
Member Data Documentation
TF1* FairEvtGenGenerator::fDensityFunction private
PDG data base
Definition at line 143 of file FairEvtGenGenerator.h.
Referenced by ReadEvent(), and ~FairEvtGenGenerator().
const Char_t* FairEvtGenGenerator::fFileName private
Definition at line 129 of file FairEvtGenGenerator.h.
Referenced by CloseInput(), and FairEvtGenGenerator().
int FairEvtGenGenerator::fGasmode private
Definition at line 136 of file FairEvtGenGenerator.h.
Referenced by ReadEvent().
FILE* FairEvtGenGenerator::fInputFile private
Input file Name.
Definition at line 130 of file FairEvtGenGenerator.h.
Referenced by CloseInput(), FairEvtGenGenerator(), ReadEvent(), and ~FairEvtGenGenerator().
double FairEvtGenGenerator::fRsigma private
Definition at line 137 of file FairEvtGenGenerator.h.
Referenced by ReadEvent().
The documentation for this class was generated from the following files:
FairEvtGenGenerator.h
FairEvtGenGenerator.cxx