FairRroot: FairTutorialDet4GeoHandler Class Reference
FairTutorialDet4GeoHandler Class Reference
#include <FairTutorialDet4GeoHandler.h>
Public Member Functions
FairTutorialDet4GeoHandler ()
~FairTutorialDet4GeoHandler ()
Int_t GetUniqueDetectorId ()
Int_t GetUniqueDetectorId (TString volName)
Int_t Init (Bool_t isSimulation=kFALSE)
void FillDetectorInfoArray (Int_t uniqueId)
void NavigateTo (TString volName)
Int_t CurrentVolOffID (Int_t off, Int_t &copy) const
Int_t CurrentVolID (Int_t &copy) const
Int_t VolId (const Text_t *name) const
Int_t VolIdGeo (const char *name) const
const char * CurrentVolName () const
const char * CurrentVolOffName (Int_t off) const
void LocalToGlobal (Double_t *local, Double_t *global, Int_t detID)
Private Member Functions
TString ConstructFullPathFromDetID (Int_t detID)
FairTutorialDet4GeoHandler (const FairTutorialDet4GeoHandler &)
FairTutorialDet4GeoHandler operator= (const FairTutorialDet4GeoHandler &)
Private Attributes
Bool_t fIsSimulation
Int_t fLastUsedDetectorID
UInt_t fGeoPathHash
TGeoVolume * fCurrentVolume
TGeoBBox * fVolumeShape
Double_t fGlobal [3]
TGeoHMatrix * fGlobalMatrix
Global centre of volume.
Detailed Description
Definition at line 33 of file FairTutorialDet4GeoHandler.h.
Constructor & Destructor Documentation
FairTutorialDet4GeoHandler::FairTutorialDet4GeoHandler ()
Constructor
Definition at line 34 of file FairTutorialDet4GeoHandler.cxx.
   : TObject(),
     fIsSimulation(kFALSE),
     fLastUsedDetectorID(0),
     fGeoPathHash(0),
     fCurrentVolume(NULL),
     fVolumeShape(NULL),
     fGlobal(),
     fGlobalMatrix(NULL)
 {
 }
FairTutorialDet4GeoHandler::~FairTutorialDet4GeoHandler () inline
Destructor
Definition at line 42 of file FairTutorialDet4GeoHandler.h.
 {};
FairTutorialDet4GeoHandler::FairTutorialDet4GeoHandler (const FairTutorialDet4GeoHandler &) private
Member Function Documentation
TString FairTutorialDet4GeoHandler::ConstructFullPathFromDetID (Int_t detID) private
Definition at line 62 of file FairTutorialDet4GeoHandler.cxx.
Referenced by LocalToGlobal().
 {
   TString volStr   = "/cave_1/tutorial4_0/tut4_det_";
   TString volPath = volStr;
   volPath += detID;
   return volPath;
 }
Int_t FairTutorialDet4GeoHandler::CurrentVolID (Int_t & copy) const
Definition at line 123 of file FairTutorialDet4GeoHandler.cxx.
References fIsSimulation.
Referenced by CurrentVolOffID().
 {
   if (fIsSimulation) {
     return gMC->CurrentVolID(copy);
   } else {
     //
     // Returns the current volume ID and copy number
     //
     if (gGeoManager->IsOutside()) { return 0; }
     TGeoNode* node = gGeoManager->GetCurrentNode();
     copy = node->GetNumber();
     Int_t id = node->GetVolume()->GetNumber();
     return id;
   }
 }
const char * FairTutorialDet4GeoHandler::CurrentVolName () const
Definition at line 159 of file FairTutorialDet4GeoHandler.cxx.
References fIsSimulation.
Referenced by CurrentVolOffName().
 {
   if (fIsSimulation) {
     return gMC->CurrentVolName();
   } else {
     //
     // Returns the current volume name
     //
     if (gGeoManager->IsOutside()) { return gGeoManager->GetTopVolume()->GetName(); }
     return gGeoManager->GetCurrentVolume()->GetName();
   }
 }
Int_t FairTutorialDet4GeoHandler::CurrentVolOffID (Int_t off, Int_t & copy) const
Definition at line 140 of file FairTutorialDet4GeoHandler.cxx.
References CurrentVolID(), and fIsSimulation.
Referenced by GetUniqueDetectorId().
 {
   if (fIsSimulation) {
     return gMC->CurrentVolOffID(off, copy);
   } else {
     //
     // Return the current volume "off" upward in the geometrical tree
     // ID and copy number
     //
     if (off<0 || off>gGeoManager->GetLevel()) { return 0; }
     if (off==0) { return CurrentVolID(copy); }
     TGeoNode* node = gGeoManager->GetMother(off);
     if (!node) { return 0; }
     copy = node->GetNumber();
     return node->GetVolume()->GetNumber();
   }
 }
const char * FairTutorialDet4GeoHandler::CurrentVolOffName (Int_t off) const
Definition at line 173 of file FairTutorialDet4GeoHandler.cxx.
References CurrentVolName(), and fIsSimulation.
 {
   if (fIsSimulation) {
     return gMC->CurrentVolOffName(off);
   } else {
     //
     // Return the current volume "off" upward in the geometrical tree
     // ID, name and copy number
     // if name=0 no name is returned
     //
     if (off<0 || off>gGeoManager->GetLevel()) { return 0; }
     if (off==0) { return CurrentVolName(); }
     TGeoNode* node = gGeoManager->GetMother(off);
     if (!node) { return 0; }
     return node->GetVolume()->GetName();
   }
 }
void FairTutorialDet4GeoHandler::FillDetectorInfoArray (Int_t uniqueId)
Int_t FairTutorialDet4GeoHandler::GetUniqueDetectorId ()
Definition at line 79 of file FairTutorialDet4GeoHandler.cxx.
References CurrentVolOffID().
Referenced by GetUniqueDetectorId(), and FairTutorialDet4::ProcessHits().
 {
   Int_t detectorNr=0;
   CurrentVolOffID(0, detectorNr);
   return detectorNr;
 }
Int_t FairTutorialDet4GeoHandler::GetUniqueDetectorId (TString volName)
Definition at line 70 of file FairTutorialDet4GeoHandler.cxx.
References fGeoPathHash, GetUniqueDetectorId(), and NavigateTo().
 {
   if (fGeoPathHash != volName.Hash()) {
     NavigateTo(volName);
   }
   return GetUniqueDetectorId();
 }
Int_t FairTutorialDet4GeoHandler::Init (Bool_t isSimulation = kFALSE)
Definition at line 46 of file FairTutorialDet4GeoHandler.cxx.
References fIsSimulation.
Referenced by FairTutorialDet4::Initialize().
 {
 //  Int_t geoVersion = CheckGeometryVersion();
   fIsSimulation=isSimulation;
   return 1;
 }
void FairTutorialDet4GeoHandler::LocalToGlobal (Double_t * local, Double_t * global, Int_t detID)
Definition at line 55 of file FairTutorialDet4GeoHandler.cxx.
References ConstructFullPathFromDetID(), and NavigateTo().
Referenced by FairTutorialDet4HitProducerIdealMisalign::Exec().
 {
   TString path=ConstructFullPathFromDetID(detID);
   NavigateTo(path);
   gGeoManager->LocalToMaster(local, global);
 }
void FairTutorialDet4GeoHandler::NavigateTo (TString volName)
Definition at line 192 of file FairTutorialDet4GeoHandler.cxx.
References DEBUG2, FairLogger::endl(), FATAL, fCurrentVolume, fGeoPathHash, fGlobal, fIsSimulation, fVolumeShape, and LOG.
Referenced by GetUniqueDetectorId(), and LocalToGlobal().
 {
   if (fIsSimulation) {
     LOG(FATAL)<<"This methode is not supported in simulation mode"<<FairLogger::endl;
   } else {
     gGeoManager->cd(volName.Data());
     fGeoPathHash = volName.Hash();
     fCurrentVolume = gGeoManager->GetCurrentVolume();
     fVolumeShape = (TGeoBBox*)fCurrentVolume->GetShape();
     Double_t local[3] = {0., 0., 0.};  // Local centre of volume
     gGeoManager->LocalToMaster(local, fGlobal);
     LOG(DEBUG2)<<"Pos: "<<fGlobal[0]<<" , "<<fGlobal[1]<<" , "<<fGlobal[2]<<FairLogger::endl;
 //    fGlobalMatrix = gGeoManager->GetCurrentMatrix();
   }
 }
FairTutorialDet4GeoHandler FairTutorialDet4GeoHandler::operator= (const FairTutorialDet4GeoHandler &) private
Int_t FairTutorialDet4GeoHandler::VolId (const Text_t * name) const
Definition at line 106 of file FairTutorialDet4GeoHandler.cxx.
References fIsSimulation, and VolIdGeo().
 {
   if (fIsSimulation) {
     return gMC->VolId(name);
   } else {
     //
     // Return the unique numeric identifier for volume name
     //
     char sname[20];
     Int_t len = strlen(name)-1;
     if (name[len] != ' ') { return VolIdGeo(name); }
     strncpy(sname, name, len);
     sname[len] = 0;
     return VolIdGeo(sname);
   }
 }
Int_t FairTutorialDet4GeoHandler::VolIdGeo (const char * name) const
Definition at line 92 of file FairTutorialDet4GeoHandler.cxx.
Referenced by VolId().
 {
   //
   // Return the unique numeric identifier for volume name
   //
   Int_t uid = gGeoManager->GetUID(name);
   if (uid<0) {
     printf("VolId: Volume %s not found\n",name);
     return 0;
   }
   return uid;
 }
Member Data Documentation
TGeoVolume* FairTutorialDet4GeoHandler::fCurrentVolume private
Definition at line 74 of file FairTutorialDet4GeoHandler.h.
Referenced by NavigateTo().
UInt_t FairTutorialDet4GeoHandler::fGeoPathHash private
Definition at line 73 of file FairTutorialDet4GeoHandler.h.
Referenced by GetUniqueDetectorId(), and NavigateTo().
Double_t FairTutorialDet4GeoHandler::fGlobal[3] private
Definition at line 76 of file FairTutorialDet4GeoHandler.h.
Referenced by NavigateTo().
TGeoHMatrix* FairTutorialDet4GeoHandler::fGlobalMatrix private
Global centre of volume.
Definition at line 77 of file FairTutorialDet4GeoHandler.h.
Bool_t FairTutorialDet4GeoHandler::fIsSimulation private
Definition at line 69 of file FairTutorialDet4GeoHandler.h.
Referenced by CurrentVolID(), CurrentVolName(), CurrentVolOffID(), CurrentVolOffName(), Init(), NavigateTo(), and VolId().
Int_t FairTutorialDet4GeoHandler::fLastUsedDetectorID private
Definition at line 71 of file FairTutorialDet4GeoHandler.h.
TGeoBBox* FairTutorialDet4GeoHandler::fVolumeShape private
Definition at line 75 of file FairTutorialDet4GeoHandler.h.
Referenced by NavigateTo().
The documentation for this class was generated from the following files:
FairTutorialDet4GeoHandler.h
FairTutorialDet4GeoHandler.cxx