FairRroot: RootOutFileManager< DataType > Class Template Reference
RootOutFileManager< DataType > Class Template Reference
#include <RootOutFileManager.h>
Public Member Functions
RootOutFileManager ()
RootOutFileManager (const std::string &filename, const std::string &treename, const std::string &branchname, const std::string &Classname, const std::string &FileOption)
virtual ~RootOutFileManager ()
void SetRootFileProperties (const std::string &filename, const std::string &treename, const std::string &branchname, const std::string &Classname="", const std::string &FileOption="RECREATE", bool UseClonesArray=false, bool flowmode=true)
void SetFileProperties (const std::string &filename, const std::string &treename, const std::string &branchname, const std::string &Classname="", const std::string &FileOption="RECREATE", bool UseClonesArray=false, bool flowmode=true)
void AddToFile (std::vector< DataType > &InputData)
void AddToFile (DataType *ObjArr, long size)
void AddToFile (TClonesArray *InputData)
void AddToFile (FairMQMessage *msg)
void InitOutputFile ()
void InitTCA (const std::string &classname)
std::vector< std::vector
< DataType > > GetAllObj (const std::string &filename, const std::string &treename, const std::string &branchname)
void ReadDir (TDirectory *dir)
void SeekObject (TKey *key)
Protected Member Functions
virtual void Init ()
Protected Attributes
std::string fFileName
std::string fTreeName
std::string fBranchName
std::string fClassName
std::string fFileOption
bool fUseClonesArray
bool fFlowMode
bool fWrite
TFile * fOutFile
TTree * fTree
TClonesArray * fOutput
DataType * fOutputData
Detailed Description
template<typename DataType>
class RootOutFileManager< DataType >
Definition at line 30 of file RootOutFileManager.h.
Constructor & Destructor Documentation
template<typename DataType > RootOutFileManager< DataType >::RootOutFileManager ()
template<typename DataType > RootOutFileManager< DataType >::RootOutFileManager (const std::string & filename, const std::string & treename, const std::string & branchname, const std::string & Classname, const std::string & FileOption)
template<typename DataType > virtual RootOutFileManager< DataType >::~RootOutFileManager () virtual
Member Function Documentation
template<typename DataType > void RootOutFileManager< DataType >::AddToFile (std::vector< DataType > & InputData)
template<typename DataType > void RootOutFileManager< DataType >::AddToFile (DataType * ObjArr, long size)
template<typename DataType > void RootOutFileManager< DataType >::AddToFile (TClonesArray * InputData)
template<typename DataType > void RootOutFileManager< DataType >::AddToFile (FairMQMessage * msg)
template<typename DataType > std::vector<std::vector<DataType> > RootOutFileManager< DataType >::GetAllObj (const std::string & filename, const std::string & treename, const std::string & branchname)
Referenced by main().
template<typename DataType > virtual void RootOutFileManager< DataType >::Init () protected virtual
template<typename DataType > void RootOutFileManager< DataType >::InitOutputFile ()
Referenced by main().
template<typename DataType > void RootOutFileManager< DataType >::InitTCA (const std::string & classname)
template<typename DataType > void RootOutFileManager< DataType >::ReadDir (TDirectory * dir)
template<typename DataType > void RootOutFileManager< DataType >::SeekObject (TKey * key)
template<typename DataType > void RootOutFileManager< DataType >::SetFileProperties (const std::string & filename, const std::string & treename, const std::string & branchname, const std::string & Classname = "", const std::string & FileOption = "RECREATE", bool UseClonesArray = false, bool flowmode = true)
Referenced by main().
template<typename DataType > void RootOutFileManager< DataType >::SetRootFileProperties (const std::string & filename, const std::string & treename, const std::string & branchname, const std::string & Classname = "", const std::string & FileOption = "RECREATE", bool UseClonesArray = false, bool flowmode = true)
Member Data Documentation
template<typename DataType > std::string RootOutFileManager< DataType >::fBranchName protected
Definition at line 66 of file RootOutFileManager.h.
template<typename DataType > std::string RootOutFileManager< DataType >::fClassName protected
Definition at line 67 of file RootOutFileManager.h.
template<typename DataType > std::string RootOutFileManager< DataType >::fFileName protected
Definition at line 64 of file RootOutFileManager.h.
template<typename DataType > std::string RootOutFileManager< DataType >::fFileOption protected
Definition at line 68 of file RootOutFileManager.h.
template<typename DataType > bool RootOutFileManager< DataType >::fFlowMode protected
Definition at line 70 of file RootOutFileManager.h.
template<typename DataType > TFile* RootOutFileManager< DataType >::fOutFile protected
Definition at line 73 of file RootOutFileManager.h.
template<typename DataType > TClonesArray* RootOutFileManager< DataType >::fOutput protected
Definition at line 75 of file RootOutFileManager.h.
template<typename DataType > DataType* RootOutFileManager< DataType >::fOutputData protected
Definition at line 76 of file RootOutFileManager.h.
template<typename DataType > TTree* RootOutFileManager< DataType >::fTree protected
Definition at line 74 of file RootOutFileManager.h.
template<typename DataType > std::string RootOutFileManager< DataType >::fTreeName protected
Definition at line 65 of file RootOutFileManager.h.
template<typename DataType > bool RootOutFileManager< DataType >::fUseClonesArray protected
Definition at line 69 of file RootOutFileManager.h.
template<typename DataType > bool RootOutFileManager< DataType >::fWrite protected
Definition at line 71 of file RootOutFileManager.h.
The documentation for this class was generated from the following file:
RootOutFileManager.h