FairRoot: FairEventBuilder Class Reference
FairEventBuilder Class Reference abstract
#include <FairEventBuilder.h>
Public Member Functions
FairEventBuilder ()
FairEventBuilder (TString branchName, TString className, TString folderName, Bool_t persistance)
virtual ~FairEventBuilder ()
virtual void WriteOutAllDeadTimeData ()
virtual std::vector< std::pair< double, FairRecoEventHeader * > > FindEvents ()=0
virtual void StoreEventData (FairRecoEventHeader *)=0
void SetIdentifier (Int_t ident)
Int_t GetIdentifier ()
virtual Bool_t Init ()=0
virtual void Print ()=0
virtual void Finish ()
Double_t AllowedTime ()
void SetMaxAllowedTime (Double_t td)
void SetBuilderName (const char *name)
TString GetBuilderName ()
virtual void SaveDataToTree (Bool_t val=kTRUE)
virtual void ActivateBuffering (Bool_t val=kTRUE)
virtual void FillNewData (FairTimeStamp *data, double startTime, double activeTime)
virtual Int_t GetNData ()
virtual std::vector< FairTimeStamp * > GetRemoveOldData (double time)
virtual std::vector< FairTimeStamp * > GetAllData ()
virtual void SetVerbose (Int_t val)
virtual void DeleteOldData ()
virtual void WriteOutData (double time)
virtual void WriteOutAllData ()
Protected Member Functions
virtual void AddNewDataToTClonesArray (FairTimeStamp *data)=0
store the data from the FairTimeStamp pointer in a TClonesArray (you have to cast it to your type of data)
virtual double FindTimeForData (FairTimeStamp *data)=0
if the same data object (like a pad or a pixel) is already present in the buffer, the time of this object has to be returned otherwise -1
virtual void FillDataMap (FairTimeStamp *data, double activeTime)=0
add a new element in the search buffer
virtual void EraseDataFromDataMap (FairTimeStamp *data)=0
delete the element from the search buffer (see PndSdsDigiPixelWriteoutBuffer)
virtual std::vector< std::pair< double, FairTimeStamp * > > Modify (std::pair< double, FairTimeStamp * > oldData, std::pair< double, FairTimeStamp * > newData)
virtual void WriteOutDataDeadTimeMap (double time)
virtual void MoveDataFromStartTimeMapToDeadTimeMap (double time)
virtual void FillDataToDeadTimeMap (FairTimeStamp *data, double activeTime)
virtual void PrintData (FairTimeStamp *data)
virtual void PrintDeadTimeMap ()
Method should be overwritten in derived classes to print the data of an object stored in the buffer.
virtual void PrintStartTimeMap ()
Protected Attributes
std::multimap< double, std::pair< double, FairTimeStamp * > > fStartTime_map
std::multimap< double, FairTimeStamp * > fDeadTime_map
TString fBranchName
TString fClassName
Bool_t fTreeSave
Bool_t fActivateBuffering
Int_t fVerbose
FairLogger * fLogger
Private Member Functions
ClassDef (FairEventBuilder, 1)
Private Attributes
TString fBuilderName
TStopwatch fTimer
Double_t fExecTime
Int_t fIdentifier
Double_t fMaxAllowedEventCreationTime
Detailed Description
Definition at line 49 of file FairEventBuilder.h.
Constructor & Destructor Documentation
FairEventBuilder::FairEventBuilder ()
Default constructor
Definition at line 54 of file FairEventBuilder.cxx.
   : FairWriteoutBuffer(),
     fBuilderName                (""),
     fTimer                      (),
     fExecTime                   (0.),
     fIdentifier                 (0),
     fMaxAllowedEventCreationTime(0.)
 {
 }
FairEventBuilder::FairEventBuilder (TString branchName, TString className, TString folderName, Bool_t persistance)
Constructor with task name
Definition at line 67 of file FairEventBuilder.cxx.
   : FairWriteoutBuffer(branchName,className,folderName,persistance),
     fBuilderName                (""),
     fTimer                      (),
     fExecTime                   (0.),
     fIdentifier                 (0),
     fMaxAllowedEventCreationTime(0.)
 {
 }
FairEventBuilder::~FairEventBuilder () virtual
Destructor
Definition at line 81 of file FairEventBuilder.cxx.
 {
 }
Member Function Documentation
virtual void FairWriteoutBuffer::ActivateBuffering (Bool_t val = kTRUE) inline virtual inherited
< fActivateBuffering has to be set to kTRUE to use the buffering. Otherwise the data is directly stored in the given TClonesArray.
Definition at line 61 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fActivateBuffering.
Referenced by FairTestDetectorTimeDigiTask::Init().
{
       fActivateBuffering=val;
     }
virtual void FairWriteoutBuffer::AddNewDataToTClonesArray (FairTimeStamp * data) protected pure virtual inherited
store the data from the FairTimeStamp pointer in a TClonesArray (you have to cast it to your type of data)
Implemented in FairTestDetectorDigiWriteoutBuffer, and MyWriteoutBuffer.
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap(), FairWriteoutBuffer::FillNewData(), WriteOutAllDeadTimeData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
Double_t FairEventBuilder::AllowedTime () inline
Definition at line 85 of file FairEventBuilder.h.
References fMaxAllowedEventCreationTime.
{
       return fMaxAllowedEventCreationTime;
     };
FairEventBuilder::ClassDef (FairEventBuilder , 1) private
virtual void FairWriteoutBuffer::DeleteOldData () inline virtual inherited
Definition at line 80 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fBranchName, FairRootManager::GetTClonesArray(), and FairRootManager::Instance().
{
       if ( fBranchName.Length() > 0 ) {
         TClonesArray* myArray = FairRootManager::Instance()->GetTClonesArray(fBranchName);
         myArray->Delete();
       }
     }
virtual void FairWriteoutBuffer::EraseDataFromDataMap (FairTimeStamp * data) protected pure virtual inherited
delete the element from the search buffer (see PndSdsDigiPixelWriteoutBuffer)
Implemented in FairTestDetectorDigiWriteoutBuffer, and MyWriteoutBuffer.
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap(), and FairWriteoutBuffer::GetRemoveOldData().
virtual void FairWriteoutBuffer::FillDataMap (FairTimeStamp * data, double activeTime) protected pure virtual inherited
add a new element in the search buffer
Implemented in FairTestDetectorDigiWriteoutBuffer, and MyWriteoutBuffer.
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
void FairWriteoutBuffer::FillDataToDeadTimeMap (FairTimeStamp * data, double activeTime) protected virtual inherited
Definition at line 168 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::AddNewDataToTClonesArray(), FairTimeStamp::equal(), FairWriteoutBuffer::EraseDataFromDataMap(), FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fDeadTime_map, FairWriteoutBuffer::FillDataMap(), FairWriteoutBuffer::FindTimeForData(), FairWriteoutBuffer::fVerbose, FairWriteoutBuffer::Modify(), and FairTimeStamp::Print().
Referenced by FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap().
 {
   if (fActivateBuffering) {
     typedef  std::multimap<double, FairTimeStamp*>::iterator DTMapIter;
     typedef  std::map<FairTimeStamp, double>::iterator DataMapIter;
     double timeOfOldData = FindTimeForData(data);
     // PrintDeadTimeMap();
     if(timeOfOldData > -1) {        //if an older active data object is already present
       if (fVerbose > 1) {
         std::cout << " OldData found! " << timeOfOldData << std::endl;
       }
       if (fVerbose > 1) {
         std::cout << "New Data: " << activeTime << " : " << data << std::endl;
       }
       double currentdeadtime = timeOfOldData;
       FairTimeStamp* oldData;
       bool dataFound = false;
       // PrintDeadTimeMap();
       for (DTMapIter it = fDeadTime_map.lower_bound(currentdeadtime); it != fDeadTime_map.upper_bound(currentdeadtime); it++) {
         oldData = it->second;
         if (fVerbose > 1) {
           std::cout << "Check Data: " << it->first << " : " << oldData << std::endl;
         }
         if (oldData->equal(data)) {
           if (fVerbose > 1) {
             std::cout << " oldData == data " << std::endl;
           }
           if (fVerbose > 1) {
             std::cout << it->first << " : " << it->second << std::endl;
           }
           fDeadTime_map.erase(it);
           EraseDataFromDataMap(oldData);
           dataFound = true;
           break;
         }
       }
       if (dataFound == true) {
         std::vector<std::pair<double, FairTimeStamp*> > modifiedData = Modify(std::pair<double, FairTimeStamp*>(currentdeadtime, oldData), std::pair<double, FairTimeStamp*>(-1, data));
         for (int i = 0; i < modifiedData.size(); i++) {
           FillDataToDeadTimeMap(modifiedData[i].second, modifiedData[i].first);
           if (fVerbose > 1) {
             std::cout << i << " :Modified Data: " << modifiedData[i].first << " : " << modifiedData[i].second << std::endl;
           }
         }
       } else {
         std::cout << "-E- FairWriteoutBuffer::FillDataToDeadTimeMap: old data present in dataMap but not in deadTimeMap!" << std::endl;
       }
     } else {
       if (fVerbose > 1) {
         std::cout << "-I- FairWriteoutBuffer::FillDataToDeadTimeMap Data Inserted: " << activeTime << " : ";
         data->Print();
         std::cout << std::endl;
       }
       fDeadTime_map.insert(std::pair<double, FairTimeStamp*>(activeTime, data));
       FillDataMap(data, activeTime);
     }
   } else {
     AddNewDataToTClonesArray(data);
     delete data;
   }
 }
void FairWriteoutBuffer::FillNewData (FairTimeStamp * data, double startTime, double activeTime) virtual inherited
Fills a pointer to a data object into the buffer. StartTime gives the time when the data can influence later data, activeTime gives the time how long the data can influence later data. Both time data has to be given as an absolute time!
Definition at line 150 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::AddNewDataToTClonesArray(), FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fStartTime_map, and FairWriteoutBuffer::fVerbose.
Referenced by FairTestDetectorTimeDigiTask::Exec().
 {
   FairTimeStamp* dataClone = static_cast<FairTimeStamp*>(data->Clone());
   if (fActivateBuffering) {
     if (fVerbose > 0) {
       std::cout << "StartTime: " << startTime << std::endl;
     }
     std::pair<double, FairTimeStamp*> timeData(activeTime, dataClone);
     fStartTime_map.insert(std::pair<double, std::pair<double, FairTimeStamp*> >(startTime, timeData));
   } else {
     AddNewDataToTClonesArray(dataClone);
     delete dataClone;
   }
 }
virtual std::vector<std::pair<double, FairRecoEventHeader*> > FairEventBuilder::FindEvents () pure virtual
virtual double FairWriteoutBuffer::FindTimeForData (FairTimeStamp * data) protected pure virtual inherited
if the same data object (like a pad or a pixel) is already present in the buffer, the time of this object has to be returned otherwise -1
Implemented in FairTestDetectorDigiWriteoutBuffer, and MyWriteoutBuffer.
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
void FairEventBuilder::Finish () virtual
Finish at the end of each event
Definition at line 124 of file FairEventBuilder.cxx.
References GetBuilderName().
 {
   cout << "-------------------- " << GetBuilderName() << " : Summary -----------------------" << endl;
   cout << " Should be implemented by the user" << endl;
   cout << "---------------------------------------------------------------------" << endl;
 }
std::vector< FairTimeStamp * > FairWriteoutBuffer::GetAllData () virtual inherited
Definition at line 145 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fDeadTime_map, and FairWriteoutBuffer::GetRemoveOldData().
Referenced by WriteOutAllDeadTimeData().
 {
   return GetRemoveOldData(fDeadTime_map.rbegin()->first + 1);
 }
TString FairEventBuilder::GetBuilderName () inline
Definition at line 95 of file FairEventBuilder.h.
References fBuilderName.
Referenced by Finish().
{
       return fBuilderName;
     }
Int_t FairEventBuilder::GetIdentifier () inline
Definition at line 74 of file FairEventBuilder.h.
References fIdentifier.
{
       return fIdentifier;
     }
virtual Int_t FairWriteoutBuffer::GetNData () inline virtual inherited
Definition at line 69 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fDeadTime_map.
{
       return fDeadTime_map.size();
     }
std::vector< FairTimeStamp * > FairWriteoutBuffer::GetRemoveOldData (double time) virtual inherited
Definition at line 129 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::EraseDataFromDataMap(), FairWriteoutBuffer::fDeadTime_map, and FairWriteoutBuffer::fVerbose.
Referenced by FairWriteoutBuffer::GetAllData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
 {
   typedef std::multimap<double, FairTimeStamp*>::iterator DTMapIter;
   std::vector<FairTimeStamp*> result;
   for(DTMapIter it = fDeadTime_map.begin(); it != fDeadTime_map.lower_bound(time); it++) {
     if (fVerbose > 1) {
       std::cout << "-I- GetRemoveOldData: DeadTime: " << it->first << " Data: " << it->second << std::endl;
     }
     result.push_back(it->second);
     EraseDataFromDataMap(it->second);
   }
   fDeadTime_map.erase(fDeadTime_map.begin(), fDeadTime_map.lower_bound(time));
   return result;
 }
virtual Bool_t FairEventBuilder::Init () pure virtual
virtual std::vector<std::pair<double, FairTimeStamp*> > FairWriteoutBuffer::Modify (std::pair< double, FairTimeStamp * > oldData, std::pair< double, FairTimeStamp * > newData) inline protected virtual inherited
Modify defines the behavior of the buffer if data should be stored which is already in the buffer. Parameters are the old data with the active time, the new data with an active time. Modify returns than a vector with the new data which should be stored.
Definition at line 99 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
{
       std::vector<std::pair<double, FairTimeStamp*> > result;
       result.push_back(oldData);
       return result;
     }
void FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap (double time) protected virtual inherited
Definition at line 235 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::FillDataToDeadTimeMap(), and FairWriteoutBuffer::fStartTime_map.
Referenced by FairWriteoutBuffer::WriteOutAllData(), and FairWriteoutBuffer::WriteOutData().
 {
   typedef std::multimap<double, std::pair<double, FairTimeStamp*> >::iterator startTimeMapIter;
   startTimeMapIter stopTime = fStartTime_map.lower_bound(time);
   for (startTimeMapIter iter = fStartTime_map.begin(); iter != stopTime; iter++) {
     std::pair<double, FairTimeStamp*> data = iter->second;
     FillDataToDeadTimeMap(data.second, data.first);
   }
   fStartTime_map.erase(fStartTime_map.begin(), stopTime);
 }
virtual void FairEventBuilder::Print () pure virtual
virtual void FairWriteoutBuffer::PrintData (FairTimeStamp * data) inline protected virtual inherited
Definition at line 110 of file FairWriteoutBuffer.h.
References FairTimeStamp::GetTimeStamp().
Referenced by FairWriteoutBuffer::PrintDeadTimeMap().
{
       std::cout << data->GetTimeStamp();
     };
void FairWriteoutBuffer::PrintDeadTimeMap () protected virtual inherited
Method should be overwritten in derived classes to print the data of an object stored in the buffer.
Definition at line 259 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fDeadTime_map, and FairWriteoutBuffer::PrintData().
Referenced by FairWriteoutBuffer::WriteOutData().
 {
   typedef  std::multimap<double, FairTimeStamp*>::iterator DTMapIter;
   std::cout << "DeadTimeMap: " << std::endl;
   for (DTMapIter it = fDeadTime_map.begin(); it != fDeadTime_map.end(); it++) {
     std::cout << it->first << " / ";
     PrintData(it->second);
     std::cout << std::endl;
   }
   std::cout << std::endl;
 }
void FairWriteoutBuffer::PrintStartTimeMap () protected virtual inherited
Definition at line 248 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fStartTime_map, and FairTimeStamp::GetTimeStamp().
Referenced by FairWriteoutBuffer::WriteOutData().
 {
   typedef std::multimap<double, std::pair<double, FairTimeStamp*> >::iterator startTimeMapIter;
   std::cout << "StartTimeMap: " << std::endl;
   for (startTimeMapIter iter = fStartTime_map.begin(); iter != fStartTime_map.end(); iter++) {
     FairTimeStamp* data = iter->second.second;
     std::cout << " | " << iter->first << "/" << data->GetTimeStamp();
   }
   std::cout << " |" << std::endl;
 }
virtual void FairWriteoutBuffer::SaveDataToTree (Bool_t val = kTRUE) inline virtual inherited
< If SaveDataToTree is set the data is stored at the end of the buffering into the given TClonesArray.
Definition at line 58 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fTreeSave.
{
       fTreeSave = val;
     }
void FairEventBuilder::SetBuilderName (const char * name) inline
Definition at line 92 of file FairEventBuilder.h.
References fBuilderName.
{
       fBuilderName=name;
     }
void FairEventBuilder::SetIdentifier (Int_t ident) inline
Definition at line 71 of file FairEventBuilder.h.
References fIdentifier.
{
       fIdentifier=ident;
     }
void FairEventBuilder::SetMaxAllowedTime (Double_t td) inline
Definition at line 88 of file FairEventBuilder.h.
References fMaxAllowedEventCreationTime.
{
       fMaxAllowedEventCreationTime = td;
     };
virtual void FairWriteoutBuffer::SetVerbose (Int_t val) inline virtual inherited
Definition at line 76 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fVerbose.
{
       fVerbose = val;
     }
virtual void FairEventBuilder::StoreEventData (FairRecoEventHeader *) pure virtual
void FairWriteoutBuffer::WriteOutAllData () virtual inherited
Definition at line 108 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fDeadTime_map, FairWriteoutBuffer::fStartTime_map, FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap(), and FairWriteoutBuffer::WriteOutData().
 {
   double ultimateTime = 0;
   if (fStartTime_map.size() > 0) {
     ultimateTime = fStartTime_map.rbegin()->first + 1;
     MoveDataFromStartTimeMapToDeadTimeMap(ultimateTime);
   }
   if (fDeadTime_map.size() > 0) {
     if (fDeadTime_map.rbegin()->first > ultimateTime) {
       ultimateTime = fDeadTime_map.rbegin()->first + 1;
     }
   }
   if (ultimateTime > 0) {
     WriteOutData(ultimateTime);
   }
 }
void FairEventBuilder::WriteOutAllDeadTimeData () virtual
Definition at line 86 of file FairEventBuilder.cxx.
References FairWriteoutBuffer::AddNewDataToTClonesArray(), FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fBranchName, FairWriteoutBuffer::fTreeSave, FairWriteoutBuffer::fVerbose, FairWriteoutBuffer::GetAllData(), FairRootManager::GetTClonesArray(), and FairRootManager::Instance().
 {
   if ( fBranchName.Length() < 1 ) {
     return;
   }
   FairRootManager* ioman = FairRootManager::Instance();
   std::vector<FairTimeStamp*> data;
   if (fActivateBuffering) {
     if (fVerbose > 0) {
       std::cout << "-I- FairEventBuilder::WriteOutAllDeadTimeData" << std::endl;
     }
     data = GetAllData();
     if (fTreeSave && data.size() > 0) {
       TClonesArray* myArray = ioman->GetTClonesArray(fBranchName);
       if (!myArray) {
         std::cout << "-E- FairEventBuilder::WriteOutData " << fBranchName << " array is not available!" << std::endl;
       }
       if (fVerbose > 0) {
         std::cout << "-I- FairEventBuilder::WriteOutData size: " << data.size() << std::endl;
       }
       for (int i = 0; i < data.size(); i++) {
         AddNewDataToTClonesArray(data[i]);
         if (fVerbose > 1) {
           std::cout << i << " : ";
           data[i]->Print();
           std::cout << std::endl;
         }
         delete data[i];
       }
     }
   } else {
     ioman->GetTClonesArray(fBranchName);
   }
 }
void FairWriteoutBuffer::WriteOutData (double time) virtual inherited
Definition at line 44 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fBranchName, FairWriteoutBuffer::fVerbose, FairRootManager::GetTClonesArray(), FairRootManager::Instance(), FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap(), FairWriteoutBuffer::PrintDeadTimeMap(), FairWriteoutBuffer::PrintStartTimeMap(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
Referenced by FairWriteoutBuffer::WriteOutAllData().
 {
   if (fActivateBuffering) {
     if (fVerbose > 0) {
       std::cout << "Before removing: ";
       PrintStartTimeMap();
       PrintDeadTimeMap();
     }
     MoveDataFromStartTimeMapToDeadTimeMap(time);
     if (fVerbose > 0) {
       std::cout << "After removing: ";
       PrintStartTimeMap();
       PrintDeadTimeMap();
     }
     WriteOutDataDeadTimeMap(time);
     if (fVerbose > 0) {
       std::cout << "DeadTime map after readout time: " << time << std::endl;
       PrintDeadTimeMap();
     }
   } else {
     FairRootManager::Instance()->GetTClonesArray(fBranchName);
   }
 }
void FairWriteoutBuffer::WriteOutDataDeadTimeMap (double time) protected virtual inherited
Definition at line 75 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::AddNewDataToTClonesArray(), FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fBranchName, FairWriteoutBuffer::fTreeSave, FairWriteoutBuffer::fVerbose, FairWriteoutBuffer::GetRemoveOldData(), FairRootManager::GetTClonesArray(), and FairRootManager::Instance().
Referenced by FairWriteoutBuffer::WriteOutData().
 {
   FairRootManager* ioman = FairRootManager::Instance();
   std::vector<FairTimeStamp*> data;
   if (fActivateBuffering) {
     if (fVerbose > 0) {
       std::cout << "-I- FairWriteoutBuffer::WriteOutData for time: " << time << std::endl;
     }
     data = GetRemoveOldData(time);
     if (fTreeSave && data.size() > 0) {
       TClonesArray* myArray = ioman->GetTClonesArray(fBranchName);
       if (!myArray) {
         std::cout << "-E- FairWriteoutBuffer::WriteOutData " << fBranchName << " array is not available!" << std::endl;
       }
       if (fVerbose > 0) {
         std::cout << "-I- FairWriteoutBuffer::WriteOutData size: " << data.size() << std::endl;
       }
       for (int i = 0; i < data.size(); i++) {
         AddNewDataToTClonesArray(data[i]);
         if (fVerbose > 1) {
           std::cout << i << " : ";
           data[i]->Print();
           std::cout << std::endl;
         }
         delete data[i];
       }
     }
   } else {
     ioman->GetTClonesArray(fBranchName);
   }
 }
Member Data Documentation
Bool_t FairWriteoutBuffer::fActivateBuffering protected inherited
Definition at line 122 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::ActivateBuffering(), FairWriteoutBuffer::FillDataToDeadTimeMap(), FairWriteoutBuffer::FillNewData(), WriteOutAllDeadTimeData(), FairWriteoutBuffer::WriteOutData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
TString FairWriteoutBuffer::fBranchName protected inherited
Definition at line 119 of file FairWriteoutBuffer.h.
Referenced by MyWriteoutBuffer::AddNewDataToTClonesArray(), FairTestDetectorDigiWriteoutBuffer::AddNewDataToTClonesArray(), FairWriteoutBuffer::DeleteOldData(), FairWriteoutBuffer::FairWriteoutBuffer(), WriteOutAllDeadTimeData(), FairWriteoutBuffer::WriteOutData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
TString FairEventBuilder::fBuilderName private
Definition at line 101 of file FairEventBuilder.h.
Referenced by GetBuilderName(), and SetBuilderName().
TString FairWriteoutBuffer::fClassName protected inherited
Definition at line 120 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FairWriteoutBuffer().
std::multimap<double, FairTimeStamp*> FairWriteoutBuffer::fDeadTime_map protected inherited
Definition at line 117 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap(), FairWriteoutBuffer::GetAllData(), FairWriteoutBuffer::GetNData(), FairWriteoutBuffer::GetRemoveOldData(), FairWriteoutBuffer::PrintDeadTimeMap(), and FairWriteoutBuffer::WriteOutAllData().
Double_t FairEventBuilder::fExecTime private
Definition at line 104 of file FairEventBuilder.h.
Int_t FairEventBuilder::fIdentifier private
Definition at line 106 of file FairEventBuilder.h.
Referenced by GetIdentifier(), and SetIdentifier().
FairLogger* FairWriteoutBuffer::fLogger protected inherited
Definition at line 124 of file FairWriteoutBuffer.h.
Double_t FairEventBuilder::fMaxAllowedEventCreationTime private
Definition at line 107 of file FairEventBuilder.h.
Referenced by AllowedTime(), and SetMaxAllowedTime().
std::multimap<double, std::pair<double, FairTimeStamp*> > FairWriteoutBuffer::fStartTime_map protected inherited
Definition at line 116 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FillNewData(), FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap(), FairWriteoutBuffer::PrintStartTimeMap(), and FairWriteoutBuffer::WriteOutAllData().
TStopwatch FairEventBuilder::fTimer private
Definition at line 103 of file FairEventBuilder.h.
Bool_t FairWriteoutBuffer::fTreeSave protected inherited
Definition at line 121 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FairWriteoutBuffer(), FairWriteoutBuffer::SaveDataToTree(), WriteOutAllDeadTimeData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
Int_t FairWriteoutBuffer::fVerbose protected inherited
Definition at line 123 of file FairWriteoutBuffer.h.
Referenced by MyWriteoutBuffer::AddNewDataToTClonesArray(), FairTestDetectorDigiWriteoutBuffer::AddNewDataToTClonesArray(), FairWriteoutBuffer::FillDataToDeadTimeMap(), FairWriteoutBuffer::FillNewData(), FairWriteoutBuffer::GetRemoveOldData(), MyWriteoutBuffer::Modify(), FairWriteoutBuffer::SetVerbose(), WriteOutAllDeadTimeData(), FairWriteoutBuffer::WriteOutData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
The documentation for this class was generated from the following files:
FairEventBuilder.h
FairEventBuilder.cxx