FairRoot: runFileSinkBin.cxx File Reference
Tutorial3/run/runFileSinkBin.cxx File Reference
#include <iostream>
#include <csignal>
#include "boost/program_options.hpp"
#include "FairMQLogger.h"
#include "FairMQFileSink.h"
#include "zeromq/FairMQTransportFactoryZMQ.h"
#include "FairTestDetectorHit.h"
#include "FairTestDetectorPayload.h"
Classes
struct DeviceOptions
Typedefs
typedef FairTestDetectorHit THit
typedef TestDetectorPayload::Hit TPayloadIn
typedef FairMQFileSink< THit, TPayloadIn > TSink
typedef struct DeviceOptions DeviceOptions_t
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
bool parse_cmd_line (int _argc, char *_argv[], DeviceOptions *_options)
int main (int argc, char **argv)
Variables
TSink filesink
Typedef Documentation
typedef struct DeviceOptions DeviceOptions_t
typedef FairTestDetectorHit THit
Definition at line 34 of file Tutorial3/run/runFileSinkBin.cxx.
typedef TestDetectorPayload::Hit TPayloadIn
Definition at line 35 of file Tutorial3/run/runFileSinkBin.cxx.
typedef FairMQFileSink<THit, TPayloadIn> TSink
Definition at line 36 of file Tutorial3/run/runFileSinkBin.cxx.
Function Documentation
int main (int argc, char ** argv)
Definition at line 123 of file Tutorial3/run/runFileSinkBin.cxx.
References FairMQStateMachine::BIND, FairMQStateMachine::ChangeState(), FairMQStateMachine::CONNECT, FairMQStateMachine::END, ERROR, FairMQStateMachine::fRunningCondition, FairMQStateMachine::fRunningFinished, FairMQStateMachine::fRunningMutex, FairMQDevice::Id, DeviceOptions::id, INFO, FairMQStateMachine::INIT, FairMQFileSink< TIn, TPayloadIn >::InitOutputFile(), FairMQDevice::InputAddress, DeviceOptions::inputAddress, DeviceOptions::inputBufSize, FairMQDevice::InputMethod, DeviceOptions::inputMethod, FairMQDevice::InputRcvBufSize, FairMQDevice::InputSocketType, DeviceOptions::inputSocketType, DeviceOptions::ioThreads, LOG, FairMQDevice::NumInputs, FairMQDevice::NumIoThreads, FairMQDevice::NumOutputs, parse_cmd_line(), FairMQStateMachine::RUN, s_catch_signals(), FairMQStateMachine::SETINPUT, FairMQStateMachine::SETOUTPUT, FairMQDevice::SetProperty(), FairMQDevice::SetTransport(), and FairMQStateMachine::STOP.
 {
     s_catch_signals();
     DeviceOptions_t options;
     try
     {
         if (!parse_cmd_line(argc, argv, &options))
             return 0;
     }
     catch (exception& e)
     {
         LOG(ERROR) << e.what();
         return 1;
     }
     LOG(INFO) << "PID: " << getpid();
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     filesink.SetTransport(transportFactory);
     filesink.SetProperty(TSink::Id, options.id);
     filesink.SetProperty(TSink::NumIoThreads, options.ioThreads);
     filesink.SetProperty(TSink::NumInputs, 1);
     filesink.SetProperty(TSink::NumOutputs, 0);
     filesink.ChangeState(TSink::INIT);
     filesink.InitOutputFile(options.id);
     filesink.SetProperty(TSink::InputSocketType, options.inputSocketType);
     filesink.SetProperty(TSink::InputRcvBufSize, options.inputBufSize);
     filesink.SetProperty(TSink::InputMethod, options.inputMethod);
     filesink.SetProperty(TSink::InputAddress, options.inputAddress);
     filesink.ChangeState(TSink::SETOUTPUT);
     filesink.ChangeState(TSink::SETINPUT);
     filesink.ChangeState(TSink::BIND);
     filesink.ChangeState(TSink::CONNECT);
     filesink.ChangeState(TSink::RUN);
     // wait until the running thread has finished processing.
     boost::unique_lock<boost::mutex> lock(filesink.fRunningMutex);
     while (!filesink.fRunningFinished)
     {
         filesink.fRunningCondition.wait(lock);
     }
     filesink.ChangeState(TSink::STOP);
     filesink.ChangeState(TSink::END);
     return 0;
 }
bool parse_cmd_line (int _argc, char * _argv[], DeviceOptions * _options) inline
Definition at line 75 of file Tutorial3/run/runFileSinkBin.cxx.
References DeviceOptions::id, INFO, DeviceOptions::inputAddress, DeviceOptions::inputBufSize, DeviceOptions::inputMethod, DeviceOptions::inputSocketType, DeviceOptions::ioThreads, and LOG.
Referenced by main().
 {
     if (_options == NULL)
         throw std::runtime_error("Internal error: options' container is empty.");
     namespace bpo = boost::program_options;
     bpo::options_description desc("Options");
     desc.add_options()
         ("id", bpo::value<string>()->required(), "Device ID")
         ("io-threads", bpo::value<int>()->default_value(1), "Number of I/O threads")
         ("input-socket-type", bpo::value<string>()->required(), "Input socket type: sub/pull")
         ("input-buff-size", bpo::value<int>()->required(), "Input buffer size in number of messages (ZeroMQ)/bytes(nanomsg)")
         ("input-method", bpo::value<string>()->required(), "Input method: bind/connect")
         ("input-address", bpo::value<string>()->required(), "Input address, e.g.: \"tcp://*:5555\"")
         ("help", "Print help messages");
     bpo::variables_map vm;
     bpo::store(bpo::parse_command_line(_argc, _argv, desc), vm);
     if ( vm.count("help") )
     {
         LOG(INFO) << "FairMQ File Sink" << endl << desc;
         return false;
     }
     bpo::notify(vm);
     if ( vm.count("id") )
         _options->id = vm["id"].as<string>();
     if ( vm.count("io-threads") )
         _options->ioThreads = vm["io-threads"].as<int>();
     if ( vm.count("input-socket-type") )
         _options->inputSocketType = vm["input-socket-type"].as<string>();
     if ( vm.count("input-buff-size") )
         _options->inputBufSize = vm["input-buff-size"].as<int>();
     if ( vm.count("input-method") )
         _options->inputMethod = vm["input-method"].as<string>();
     if ( vm.count("input-address") )
         _options->inputAddress = vm["input-address"].as<string>();
     return true;
 }
static void s_catch_signals (void) static
Definition at line 51 of file Tutorial3/run/runFileSinkBin.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 40 of file Tutorial3/run/runFileSinkBin.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, and FairMQStateMachine::STOP.
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     filesink.ChangeState(TSink::STOP);
     filesink.ChangeState(TSink::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
TSink filesink
Definition at line 38 of file Tutorial3/run/runFileSinkBin.cxx.