FairRroot: BoostSerializer< DataType, BoostArchiveOut > Class Template Reference
BoostSerializer< DataType, BoostArchiveOut > Class Template Reference
#include <BoostSerializer.h>
Public Member Functions
BoostSerializer ()
~BoostSerializer ()
void CloseMessage ()
void SetMessage (FairMQMessage *msg)
void GetMessage ()
void Init ()
void DoSerialization ()
void DoSerialization (const std::vector< DataType > &DataVector)
FairMQMessage * SerializeMsg (DataType &Data)
FairMQMessage * SerializeMsg (const std::vector< DataType > &DataVector)
FairMQMessage * SerializeMsg (TClonesArray *clonesArray)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Diverse.
Protected Member Functions
virtual void SetTransport (FairMQTransportFactory *transport)
Protected Attributes
FairMQMessage * fMessage
FairMQTransportFactory * fTransport
std::vector< DataType > fDataVector
Detailed Description
template<typename DataType, typename BoostArchiveOut = BoostBinArchOut>
class BoostSerializer< DataType, BoostArchiveOut >
//////////////////////////////////////////////////////////////////////// //////////////////////// serialize ///////////////////////////////// ////////////////////////////////////////////////////////////////////////
Definition at line 75 of file BoostSerializer.h.
Constructor & Destructor Documentation
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> BoostSerializer< DataType, BoostArchiveOut >::BoostSerializer () inline
Definition at line 79 of file BoostSerializer.h.
                           : fMessage(nullptr),
                             fTransport(nullptr)
                             {}
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> BoostSerializer< DataType, BoostArchiveOut >::~BoostSerializer () inline
Definition at line 82 of file BoostSerializer.h.
 {}
Member Function Documentation
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> void BoostSerializer< DataType, BoostArchiveOut >::CloseMessage () inline
Definition at line 84 of file BoostSerializer.h.
References FairMQMessage::CloseMessage(), and BoostSerializer< DataType, BoostArchiveOut >::fMessage.
         {
             if(fMessage)
                 fMessage->CloseMessage();
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> void BoostSerializer< DataType, BoostArchiveOut >::DoSerialization () inline
main method to boost serialize
Definition at line 108 of file BoostSerializer.h.
References buffer, ERROR, BoostSerializer< DataType, BoostArchiveOut >::fDataVector, BoostSerializer< DataType, BoostArchiveOut >::fMessage, FairMQMessage::GetData(), MQLOG, and FairMQMessage::Rebuild().
Referenced by BoostSerializer< DataType, BoostArchiveOut >::SerializeMsg().
         {
             std::ostringstream buffer;
             BoostArchiveOut OutputArchive(buffer);
             try
             {
                 OutputArchive << fDataVector;
             }
             catch (boost::archive::archive_exception& e)
             {
                 MQLOG(ERROR) << e.what();
             }
             int size = buffer.str().length();
             //fMessage = fTransport->CreateMessage(size);
             fMessage->Rebuild(size);
             std::memcpy(fMessage->GetData(), buffer.str().c_str(), size);
             // delete the vector content
             if (fDataVector.size() > 0)
                 fDataVector.clear();
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> void BoostSerializer< DataType, BoostArchiveOut >::DoSerialization (const std::vector< DataType > & DataVector) inline
Definition at line 131 of file BoostSerializer.h.
References buffer, ERROR, BoostSerializer< DataType, BoostArchiveOut >::fMessage, FairMQMessage::GetData(), MQLOG, and FairMQMessage::Rebuild().
         {
             std::ostringstream buffer;
             BoostArchiveOut OutputArchive(buffer);
             try
             {
                 OutputArchive << DataVector;
             }
             catch (boost::archive::archive_exception& e)
             {
                 MQLOG(ERROR) << e.what();
             }
             int size = buffer.str().length();
             //fMessage = fTransport->CreateMessage(size);
             fMessage->Rebuild(size);
             std::memcpy(fMessage->GetData(), buffer.str().c_str(), size);
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> void BoostSerializer< DataType, BoostArchiveOut >::GetMessage () inline
Definition at line 95 of file BoostSerializer.h.
References BoostSerializer< DataType, BoostArchiveOut >::fMessage.
         {
             return fMessage;
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> void BoostSerializer< DataType, BoostArchiveOut >::Init () inline
Definition at line 100 of file BoostSerializer.h.
         {
             //InitContainer();
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> template<class Archive > void BoostSerializer< DataType, BoostArchiveOut >::serialize (Archive & ar, const unsigned int version) inline
Diverse.
Definition at line 186 of file BoostSerializer.h.
References BoostSerializer< DataType, BoostArchiveOut >::fDataVector.
             {
                 ar& fDataVector;
             }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> FairMQMessage* BoostSerializer< DataType, BoostArchiveOut >::SerializeMsg (DataType & Data) inline
DataType& -----—> FairMQMessage*
Definition at line 153 of file BoostSerializer.h.
References BoostSerializer< DataType, BoostArchiveOut >::DoSerialization(), BoostSerializer< DataType, BoostArchiveOut >::fDataVector, and BoostSerializer< DataType, BoostArchiveOut >::fMessage.
         {
             fDataVector.push_back(Data);
             DoSerialization();
             return fMessage;
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> FairMQMessage* BoostSerializer< DataType, BoostArchiveOut >::SerializeMsg (const std::vector< DataType > & DataVector) inline
vector<DataType>& -----—> FairMQMessage*
Definition at line 161 of file BoostSerializer.h.
References BoostSerializer< DataType, BoostArchiveOut >::DoSerialization(), and BoostSerializer< DataType, BoostArchiveOut >::fMessage.
         {
             DoSerialization(DataVector);
             return fMessage;
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> FairMQMessage* BoostSerializer< DataType, BoostArchiveOut >::SerializeMsg (TClonesArray * clonesArray) inline
TClonesArray* -----—> FairMQMessage*
Definition at line 168 of file BoostSerializer.h.
References BoostSerializer< DataType, BoostArchiveOut >::DoSerialization(), BoostSerializer< DataType, BoostArchiveOut >::fDataVector, and BoostSerializer< DataType, BoostArchiveOut >::fMessage.
         {
             // convert TClonesArray to vector<DataType>
             for (Int_t i = 0; i < clonesArray->GetEntriesFast(); ++i)
             {
                 DataType* data = reinterpret_cast<DataType*>(clonesArray->At(i));
                 if (!data)
                     continue;
                 fDataVector.push_back(*data);
             }
             DoSerialization();
             return fMessage;
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> void BoostSerializer< DataType, BoostArchiveOut >::SetMessage (FairMQMessage * msg) inline
Definition at line 90 of file BoostSerializer.h.
References BoostSerializer< DataType, BoostArchiveOut >::fMessage.
         {
             fMessage=msg;
         }
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> virtual void BoostSerializer< DataType, BoostArchiveOut >::SetTransport (FairMQTransportFactory * transport) inline protected virtual
Definition at line 195 of file BoostSerializer.h.
References BoostSerializer< DataType, BoostArchiveOut >::fTransport.
         {
             fTransport=transport;
         }
Member Data Documentation
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> std::vector<DataType> BoostSerializer< DataType, BoostArchiveOut >::fDataVector protected
Definition at line 202 of file BoostSerializer.h.
Referenced by BoostSerializer< DataType, BoostArchiveOut >::DoSerialization(), BoostSerializer< DataType, BoostArchiveOut >::serialize(), and BoostSerializer< DataType, BoostArchiveOut >::SerializeMsg().
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> FairMQMessage* BoostSerializer< DataType, BoostArchiveOut >::fMessage protected
Definition at line 200 of file BoostSerializer.h.
Referenced by BoostSerializer< DataType, BoostArchiveOut >::CloseMessage(), BoostSerializer< DataType, BoostArchiveOut >::DoSerialization(), BoostSerializer< DataType, BoostArchiveOut >::GetMessage(), BoostSerializer< DataType, BoostArchiveOut >::SerializeMsg(), and BoostSerializer< DataType, BoostArchiveOut >::SetMessage().
template<typename DataType , typename BoostArchiveOut = BoostBinArchOut> FairMQTransportFactory* BoostSerializer< DataType, BoostArchiveOut >::fTransport protected
Definition at line 201 of file BoostSerializer.h.
Referenced by BoostSerializer< DataType, BoostArchiveOut >::SetTransport().
The documentation for this class was generated from the following file:
BoostSerializer.h