FairRroot: runTestDetectorSamplerRoot.cxx File Reference
runTestDetectorSamplerRoot.cxx File Reference
#include <iostream>
#include <csignal>
#include "boost/program_options.hpp"
#include "FairMQLogger.h"
#include "FairMQSampler.h"
#include "zeromq/FairMQTransportFactoryZMQ.h"
#include "TestDetectorDigiLoader.h"
#include "TMessage.h"
#include "FairTestDetectorDigi.h"
Classes
struct DeviceOptions
Typedefs
typedef TestDetectorDigiLoader
< FairTestDetectorDigi,
TMessage > TLoader
typedef FairMQSampler< TLoader > TSampler
typedef struct DeviceOptions DeviceOptions_t
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
bool parse_cmd_line (int _argc, char *_argv[], DeviceOptions *_options)
int main (int argc, char **argv)
Variables
TSampler sampler
Typedef Documentation
typedef struct DeviceOptions DeviceOptions_t
typedef TestDetectorDigiLoader<FairTestDetectorDigi, TMessage> TLoader
Definition at line 36 of file runTestDetectorSamplerRoot.cxx.
typedef FairMQSampler<TLoader> TSampler
Definition at line 37 of file runTestDetectorSamplerRoot.cxx.
Function Documentation
int main (int argc, char ** argv)
Definition at line 144 of file runTestDetectorSamplerRoot.cxx.
References FairMQStateMachine::BIND, FairMQSampler< Loader >::Branch, DeviceOptions::branch, FairMQStateMachine::ChangeState(), FairMQStateMachine::CONNECT, FairMQStateMachine::END, ERROR, FairMQSampler< Loader >::EventRate, DeviceOptions::eventRate, FairMQStateMachine::fRunningCondition, FairMQStateMachine::fRunningFinished, FairMQStateMachine::fRunningMutex, FairMQDevice::Id, DeviceOptions::id, INFO, FairMQStateMachine::INIT, FairMQSampler< Loader >::InputFile, DeviceOptions::inputFile, DeviceOptions::ioThreads, LOG, FairMQDevice::NumInputs, FairMQDevice::NumIoThreads, FairMQDevice::NumOutputs, FairMQDevice::OutputAddress, DeviceOptions::outputAddress, DeviceOptions::outputBufSize, FairMQDevice::OutputMethod, DeviceOptions::outputMethod, FairMQDevice::OutputSndBufSize, FairMQDevice::OutputSocketType, DeviceOptions::outputSocketType, DeviceOptions::parameterFile, FairMQSampler< Loader >::ParFile, parse_cmd_line(), FairMQStateMachine::RUN, s_catch_signals(), FairMQStateMachine::SETINPUT, FairMQStateMachine::SETOUTPUT, FairMQSampler< Loader >::SetProperty(), FairMQDevice::SetTransport(), and FairMQStateMachine::STOP.
 {
     s_catch_signals();
     DeviceOptions_t options;
     try
     {
         if (!parse_cmd_line(argc, argv, &options))
             return 0;
     }
     catch (exception& e)
     {
         LOG(ERROR) << e.what();
         return 1;
     }
     LOG(INFO) << "PID: " << getpid();
     LOG(INFO) << "CONFIG: " << "id: " << options.id << ", event rate: " << options.eventRate << ", I/O threads: " << options.ioThreads;
     LOG(INFO) << "FILES: " << "input file: " << options.inputFile << ", parameter file: " << options.parameterFile << ", branch: " << options.branch;
     LOG(INFO) << "OUTPUT: " << options.outputSocketType << " " << options.outputBufSize << " " << options.outputMethod << " " << options.outputAddress;
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     sampler.SetTransport(transportFactory);
     sampler.SetProperty(TSampler::Id, options.id);
     sampler.SetProperty(TSampler::InputFile, options.inputFile);
     sampler.SetProperty(TSampler::ParFile, options.parameterFile);
     sampler.SetProperty(TSampler::Branch, options.branch);
     sampler.SetProperty(TSampler::EventRate, options.eventRate);
     sampler.SetProperty(TSampler::NumIoThreads, options.ioThreads);
     sampler.SetProperty(TSampler::NumInputs, 0);
     sampler.SetProperty(TSampler::NumOutputs, 1);
     sampler.ChangeState(TSampler::INIT);
     sampler.SetProperty(TSampler::OutputSocketType, options.outputSocketType);
     sampler.SetProperty(TSampler::OutputSndBufSize, options.outputBufSize);
     sampler.SetProperty(TSampler::OutputMethod, options.outputMethod);
     sampler.SetProperty(TSampler::OutputAddress, options.outputAddress);
     sampler.ChangeState(TSampler::SETOUTPUT);
     sampler.ChangeState(TSampler::SETINPUT);
     sampler.ChangeState(TSampler::BIND);
     sampler.ChangeState(TSampler::CONNECT);
     try
     {
         sampler.ChangeState(TSampler::RUN);
     }
     catch (boost::archive::archive_exception& e)
     {
         LOG(ERROR) << e.what();
     }
     // wait until the running thread has finished processing.
     boost::unique_lock<boost::mutex> lock(sampler.fRunningMutex);
     while (!sampler.fRunningFinished)
     {
         sampler.fRunningCondition.wait(lock);
     }
     sampler.ChangeState(TSampler::STOP);
     sampler.ChangeState(TSampler::END);
     return 0;
 }
bool parse_cmd_line (int _argc, char * _argv[], DeviceOptions * _options) inline
Definition at line 80 of file runTestDetectorSamplerRoot.cxx.
References DeviceOptions::branch, DeviceOptions::eventRate, DeviceOptions::id, INFO, DeviceOptions::inputFile, DeviceOptions::ioThreads, LOG, DeviceOptions::outputAddress, DeviceOptions::outputBufSize, DeviceOptions::outputMethod, DeviceOptions::outputSocketType, and DeviceOptions::parameterFile.
Referenced by main().
 {
     if (_options == NULL)
         throw std::runtime_error("Internal error: options' container is empty.");
     namespace bpo = boost::program_options;
     bpo::options_description desc("Options");
     desc.add_options()
         ("id", bpo::value<string>()->required(), "Device ID")
         ("input-file", bpo::value<string>()->required(), "Path to the input file")
         ("parameter-file", bpo::value<string>()->required(), "path to the parameter file")
         ("branch", bpo::value<string>()->default_value("FairTestDetectorDigi"), "Name of the Branch")
         ("event-rate", bpo::value<int>()->default_value(0), "Event rate limit in maximum number of events per second")
         ("io-threads", bpo::value<int>()->default_value(1), "Number of I/O threads")
         ("output-socket-type", bpo::value<string>()->required(), "Output socket type: pub/push")
         ("output-buff-size", bpo::value<int>()->required(), "Output buffer size in number of messages (ZeroMQ)/bytes(nanomsg)")
         ("output-method", bpo::value<string>()->required(), "Output method: bind/connect")
         ("output-address", bpo::value<string>()->required(), "Output address, e.g.: \"tcp://*:5555\"")
         ("help", "Print help messages");
     bpo::variables_map vm;
     bpo::store(bpo::parse_command_line(_argc, _argv, desc), vm);
     if ( vm.count("help") )
     {
         LOG(INFO) << "FairMQ Test Detector Sampler" << endl << desc;
         return false;
     }
     bpo::notify(vm);
     if ( vm.count("id") )
         _options->id = vm["id"].as<string>();
     if ( vm.count("input-file") )
         _options->inputFile = vm["input-file"].as<string>();
     if ( vm.count("parameter-file") )
         _options->parameterFile = vm["parameter-file"].as<string>();
     if ( vm.count("branch") )
         _options->branch = vm["branch"].as<string>();
     if ( vm.count("event-rate") )
         _options->eventRate = vm["event-rate"].as<int>();
     if ( vm.count("io-threads") )
         _options->ioThreads = vm["io-threads"].as<int>();
     if ( vm.count("output-socket-type") )
         _options->outputSocketType = vm["output-socket-type"].as<string>();
     if ( vm.count("output-buff-size") )
         _options->outputBufSize = vm["output-buff-size"].as<int>();
     if ( vm.count("output-method") )
         _options->outputMethod = vm["output-method"].as<string>();
     if ( vm.count("output-address") )
         _options->outputAddress = vm["output-address"].as<string>();
     return true;
 }
static void s_catch_signals (void) static
Definition at line 52 of file runTestDetectorSamplerRoot.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 41 of file runTestDetectorSamplerRoot.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, and FairMQStateMachine::STOP.
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     sampler.ChangeState(TSampler::STOP);
     sampler.ChangeState(TSampler::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
TSampler sampler
Definition at line 39 of file runTestDetectorSamplerRoot.cxx.