FairRroot: FairTutorialDet4HitProducerIdealMisalign Class Reference
FairTutorialDet4HitProducerIdealMisalign Class Reference
#include <FairTutorialDet4HitProducerIdealMisalign.h>
Public Member Functions
FairTutorialDet4HitProducerIdealMisalign ()
~FairTutorialDet4HitProducerIdealMisalign ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Exec (Option_t *opt)
void DoMisalignment (Bool_t val)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
Double_t GetHitErr (Double_t sigma)
FairTutorialDet4HitProducerIdealMisalign (const FairTutorialDet4HitProducerIdealMisalign &)
FairTutorialDet4HitProducerIdealMisalign & operator= (const FairTutorialDet4HitProducerIdealMisalign &)
ClassDef (FairTutorialDet4HitProducerIdealMisalign, 1)
Private Attributes
TClonesArray * fPointArray
TClonesArray * fHitArray
TArrayD fShiftX
TArrayD fShiftY
TArrayD fShiftZ
TArrayD fRotX
TArrayD fRotY
TArrayD fRotZ
FairTutorialDet4MisalignPar * fDigiPar
FairTutorialDet4GeoHandler * fGeoHandler
Bool_t fDoMisalignment
Detailed Description
Definition at line 38 of file FairTutorialDet4HitProducerIdealMisalign.h.
Constructor & Destructor Documentation
FairTutorialDet4HitProducerIdealMisalign::FairTutorialDet4HitProducerIdealMisalign ()
Default constructor
Definition at line 32 of file FairTutorialDet4HitProducerIdealMisalign.cxx.
   : FairTask("Missallign Hit Producer for the TutorialDet"),
     fPointArray(NULL),
     fHitArray(NULL),
     fShiftX(),
     fShiftY(),
     fShiftZ(),
     fRotX(),
     fRotY(),
     fRotZ(),
     fDigiPar(NULL),
     fGeoHandler(new FairTutorialDet4GeoHandler),
     fDoMisalignment(kFALSE)
 {
 }
FairTutorialDet4HitProducerIdealMisalign::~FairTutorialDet4HitProducerIdealMisalign ()
Destructor
Definition at line 49 of file FairTutorialDet4HitProducerIdealMisalign.cxx.
 { }
FairTutorialDet4HitProducerIdealMisalign::FairTutorialDet4HitProducerIdealMisalign (const FairTutorialDet4HitProducerIdealMisalign &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTutorialDet4HitProducerIdealMisalign::ClassDef (FairTutorialDet4HitProducerIdealMisalign , 1) private
void FairTutorialDet4HitProducerIdealMisalign::DoMisalignment (Bool_t val) inline
Definition at line 63 of file FairTutorialDet4HitProducerIdealMisalign.h.
References fDoMisalignment.
 {fDoMisalignment=val;}
void FairTutorialDet4HitProducerIdealMisalign::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 129 of file FairTutorialDet4HitProducerIdealMisalign.cxx.
References DEBUG, DEBUG2, FairLogger::endl(), FATAL, fDoMisalignment, fGeoHandler, fHitArray, fPointArray, fRotZ, fShiftX, fShiftY, FairMCPoint::GetDetectorID(), GetHitErr(), FairMCPoint::GetTime(), FairMCPoint::GetTrackID(), FairMCPoint::GetX(), FairMCPoint::GetY(), FairMCPoint::GetZ(), INFO, FairTutorialDet4GeoHandler::LocalToGlobal(), and LOG.
 {
   // Reset output array
   if ( ! fHitArray ) { LOG(FATAL)<<"No TutorialDetHitArray"<<FairLogger::endl; }
   fHitArray->Clear();
   // Declare some variables
   FairTutorialDet4Point* point = NULL;
   Int_t detID   = 0;        // Detector ID
   Int_t trackID = 0;        // Track index
   Double_t x, y, z;         // Position
   Double_t dx = 0.1;        // Position error
   Double_t tof = 0.;        // Time of flight
   TVector3 pos, dpos;       // Position and error vectors
   // Loop over TofPoints
   Int_t nHits = 0;
   Int_t nPoints = fPointArray->GetEntriesFast();
   for (Int_t iPoint=0; iPoint<nPoints; iPoint++) {
     point = (FairTutorialDet4Point*) fPointArray->At(iPoint);
     if ( ! point) { continue; }
     // Detector ID
     detID = point->GetDetectorID();
     // MCTrack ID
     trackID = point->GetTrackID();
     if(fDoMisalignment) {
       Float_t cosAlpha = TMath::Cos(fRotZ.At(detID));
       Float_t sinAlpha = TMath::Sin(fRotZ.At(detID));
       // Determine hit position
       x  = (point->GetX()*cosAlpha + point->GetY()*sinAlpha)-fShiftX.At(detID);
       y  = (-point->GetX()*sinAlpha + point->GetY()*cosAlpha)-fShiftY.At(detID);
       z  = point->GetZ();
       LOG(DEBUG)<<"Pos before misalignment: "<< point->GetX() <<", "
                 << point->GetY() <<", "<< point->GetZ() <<FairLogger::endl;
       LOG(DEBUG)<<"Pos after misalignment: "<< x <<", "
                 << y <<", "<< z <<FairLogger::endl;
       x = x + GetHitErr(0.1);
       y = y + GetHitErr(0.1);
       LOG(DEBUG2)<<"Missallign hit by "<<fShiftX.At(detID)<<" cm in x- and "
                  << fShiftY.At(detID)<<" cm in y-direction."<<FairLogger::endl;
       // Time of flight
       tof = point->GetTime();
       // Create new hit
       pos.SetXYZ(x,y,z);
       dpos.SetXYZ(dx, dx, 0.);
       new ((*fHitArray)[nHits]) FairTutorialDet4Hit(detID, iPoint, pos, dpos);
       nHits++;
     }  else {
       // Determine hit position
       x  = point->GetX();
       y  = point->GetY();
       z  = point->GetZ();
       LOG(INFO)<<"Position: "<<x<<", "<<y<<", "<<z<<FairLogger::endl;
       Double_t local[3] = {x, y, z};
       Double_t global[3];
       fGeoHandler->LocalToGlobal(local, global, detID);
       x = global[0] + GetHitErr(0.1);
       y = global[1] + GetHitErr(0.1);
       z = global[2];
       LOG(INFO)<<"Position: "<<x<<", "<<y<<", "<<z<<FairLogger::endl;
       LOG(INFO)<<"****"<<FairLogger::endl;
       // Time of flight
       tof = point->GetTime();
       // Create new hit
       pos.SetXYZ(x,y,z);
       dpos.SetXYZ(dx, dx, 0.);
       new ((*fHitArray)[nHits]) FairTutorialDet4Hit(detID, iPoint, pos, dpos);
       nHits++;
     }
   }
   // Event summary
   LOG(DEBUG)<< "Create " << nHits << " TutorialDetHits out of "
             << nPoints << " TutorilaDetPoints created." << FairLogger::endl;
 }
virtual void FairTask::Finish () inline protected virtual inherited
Action after each event. To be implemented in the derived class
Reimplemented in FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, FairDbTutAccessRtdbTask, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 111 of file FairTask.h.
Referenced by FairTask::FinishTask(), and FairTask::FinishTasks().
 { };
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
Double_t FairTutorialDet4HitProducerIdealMisalign::GetHitErr (Double_t sigma) private
Definition at line 226 of file FairTutorialDet4HitProducerIdealMisalign.cxx.
Referenced by Exec().
 {
   Double_t err = gRandom->Gaus(0, sigma);
   return (TMath::Abs(err) < 3 * sigma) ? err : (err > 0) ? 3 * sigma : -3 * sigma;
 }
InitStatus FairTutorialDet4HitProducerIdealMisalign::Init () virtual
Virtual method Init
Reimplemented from FairTask.
Definition at line 86 of file FairTutorialDet4HitProducerIdealMisalign.cxx.
References FairLogger::endl(), FATAL, fDigiPar, fHitArray, fPointArray, fRotX, fRotY, fRotZ, fShiftX, fShiftY, fShiftZ, FairRootManager::GetObject(), FairTutorialDet4MisalignPar::GetRotX(), FairTutorialDet4MisalignPar::GetRotY(), FairTutorialDet4MisalignPar::GetRotZ(), FairTutorialDet4MisalignPar::GetShiftX(), FairTutorialDet4MisalignPar::GetShiftY(), FairTutorialDet4MisalignPar::GetShiftZ(), INFO, FairRootManager::Instance(), kFATAL, kSUCCESS, LOG, and FairRootManager::Register().
 {
   // Get RootManager
   FairRootManager* ioman = FairRootManager::Instance();
   if ( ! ioman ) {
     LOG(FATAL) << "RootManager not instantised!" << FairLogger::endl;
     return kFATAL;
   }
   // Get input array
   fPointArray = (TClonesArray*) ioman->GetObject("TutorialDetPoint");
   if ( ! fPointArray ) {
     LOG(FATAL)<<"No TutorialDetPoint array!" << FairLogger::endl;
     return kFATAL;
   }
   // Create and register output array
   fHitArray = new TClonesArray("FairTutorialDet4Hit");
   ioman->Register("TutorialDetHit", "TutorialDet", fHitArray, kTRUE);
   LOG(INFO)<< "HitProducerIdealMissallign: Initialisation successfull"
            << FairLogger::endl;
   fShiftX=fDigiPar->GetShiftX();
   fShiftY=fDigiPar->GetShiftY();
   fShiftZ=fDigiPar->GetShiftZ();
   fRotX=fDigiPar->GetRotX();
   fRotY=fDigiPar->GetRotY();
   fRotZ=fDigiPar->GetRotZ();
   /*
     Int_t num = fDigiPar->GetNrOfDetectors();
     Int_t size = fShiftX.GetSize();
     LOG(INFO)<<"Array has a size of "<< size << "elements"<<FairLogger::endl;
     for (Int_t i=0; i< num; ++i) {
       LOG(INFO)<< i <<": "<<fShiftX.At(i)<<FairLogger::endl;
     }
   */
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairTutorialDet4HitProducerIdealMisalign& FairTutorialDet4HitProducerIdealMisalign::operator= (const FairTutorialDet4HitProducerIdealMisalign &) private
InitStatus FairTutorialDet4HitProducerIdealMisalign::ReInit () virtual
Virtual method ReInit
Reimplemented from FairTask.
Definition at line 65 of file FairTutorialDet4HitProducerIdealMisalign.cxx.
References fDigiPar, fRotX, fRotY, fRotZ, fShiftX, fShiftY, fShiftZ, FairRuntimeDb::getContainer(), FairTutorialDet4MisalignPar::GetRotX(), FairTutorialDet4MisalignPar::GetRotY(), FairTutorialDet4MisalignPar::GetRotZ(), FairRun::GetRuntimeDb(), FairTutorialDet4MisalignPar::GetShiftX(), FairTutorialDet4MisalignPar::GetShiftY(), FairTutorialDet4MisalignPar::GetShiftZ(), FairRunAna::Instance(), and kSUCCESS.
 {
   // Get Base Container
   FairRunAna* ana = FairRunAna::Instance();
   FairRuntimeDb* rtdb=ana->GetRuntimeDb();
   fDigiPar = (FairTutorialDet4MisalignPar*)
              (rtdb->getContainer("FairTutorialDet4MissallignPar"));
   fShiftX=fDigiPar->GetShiftX();
   fShiftY=fDigiPar->GetShiftY();
   fShiftZ=fDigiPar->GetShiftZ();
   fRotX=fDigiPar->GetRotX();
   fRotY=fDigiPar->GetRotY();
   fRotZ=fDigiPar->GetRotZ();
   return kSUCCESS;
 }
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairTutorialDet4HitProducerIdealMisalign::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 52 of file FairTutorialDet4HitProducerIdealMisalign.cxx.
References FairLogger::endl(), fDigiPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), INFO, FairRunAna::Instance(), and LOG.
 {
   LOG(INFO)<< "Set tutdet missallign parameters"<<FairLogger::endl;
   // Get Base Container
   FairRunAna* ana = FairRunAna::Instance();
   FairRuntimeDb* rtdb=ana->GetRuntimeDb();
   fDigiPar = (FairTutorialDet4MisalignPar*)
              (rtdb->getContainer("FairTutorialDet4MissallignPar"));
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
FairTutorialDet4MisalignPar* FairTutorialDet4HitProducerIdealMisalign::fDigiPar private
Definition at line 80 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Init(), ReInit(), and SetParContainers().
Bool_t FairTutorialDet4HitProducerIdealMisalign::fDoMisalignment private
Definition at line 83 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by DoMisalignment(), and Exec().
FairTutorialDet4GeoHandler* FairTutorialDet4HitProducerIdealMisalign::fGeoHandler private
Definition at line 81 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Exec().
TClonesArray* FairTutorialDet4HitProducerIdealMisalign::fHitArray private
Output array of CbmTofHits
Definition at line 71 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Exec(), and Init().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
TClonesArray* FairTutorialDet4HitProducerIdealMisalign::fPointArray private
Input array of CbmTofPoints
Definition at line 68 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Exec(), and Init().
TArrayD FairTutorialDet4HitProducerIdealMisalign::fRotX private
Definition at line 76 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Init(), and ReInit().
TArrayD FairTutorialDet4HitProducerIdealMisalign::fRotY private
Definition at line 77 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Init(), and ReInit().
TArrayD FairTutorialDet4HitProducerIdealMisalign::fRotZ private
Definition at line 78 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Exec(), Init(), and ReInit().
TArrayD FairTutorialDet4HitProducerIdealMisalign::fShiftX private
Definition at line 73 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Exec(), Init(), and ReInit().
TArrayD FairTutorialDet4HitProducerIdealMisalign::fShiftY private
Definition at line 74 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Exec(), Init(), and ReInit().
TArrayD FairTutorialDet4HitProducerIdealMisalign::fShiftZ private
Definition at line 75 of file FairTutorialDet4HitProducerIdealMisalign.h.
Referenced by Init(), and ReInit().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairTutorialDet4HitProducerIdealMisalign.h
FairTutorialDet4HitProducerIdealMisalign.cxx