FairRoot: FairIon Class Reference
FairIon Class Reference
#include <FairIon.h>
Public Member Functions
FairIon ()
FairIon (const char *name, Int_t z, Int_t a, Int_t q, Double_t e=0., Double_t m=0.)
void SetParams (const char *name, Int_t z, Int_t a, Int_t q, Double_t e=0., Double_t m=0.)
virtual ~FairIon ()
Int_t GetZ () const
Int_t GetA () const
Int_t GetQ () const
Double_t GetExcEnergy () const
Double_t GetMass () const
void SetExcEnergy (Double_t eExc)
void SetMass (Double_t mass)
Private Member Functions
FairIon (const FairIon &)
.931494028 Gev/c**2
FairIon & operator= (const FairIon &)
ClassDef (FairIon, 2)
Private Attributes
Int_t fZ
/// Number of ions instantiated. One per generator.
Int_t fA
Atomic number.
Int_t fQ
Atomic mass.
Double_t fExcEnergy
Electric charge.
Double_t fMass
Excitation energy [GeV].
FairLogger * fLogger
Mass [GeV].
Static Private Attributes
static Int_t fgNIon
static const Double_t amu =0.931494028
/// FairLogger
Detailed Description
Definition at line 31 of file FairIon.h.
Constructor & Destructor Documentation
FairIon::FairIon ()
Default constructor
Definition at line 21 of file FairIon.cxx.
   :TNamed(),
    fZ(0),
    fA(0),
    fQ(0),
    fExcEnergy(0),
    fMass(0),
    fLogger(FairLogger::GetLogger())
 {
 }
FairIon::FairIon (const char * name, Int_t z, Int_t a, Int_t q, Double_t e = 0., Double_t m = 0.)
Standard constructor
Parameters
name name
z atomic number
a atomic mass
q electric charge
e excitation energy
m mass [GeV] If mass is not given, it will be set to a times the proton mass.
Definition at line 36 of file FairIon.cxx.
References fLogger, fMass, FairLogger::Info(), and MESSAGE_ORIGIN.
   : TNamed(name, "User defined ion"),
     fZ(z),
     fA(a),
     fQ(q),
     fExcEnergy(e),
     fMass(0),
     fLogger(FairLogger::GetLogger())
 {
   TDatabasePDG* pdgDB = TDatabasePDG::Instance();
   TParticlePDG* kProton = pdgDB->GetParticle(2212);
   Double_t kProtonMass=kProton->Mass();
   if (mass == 0.) { fMass = kProtonMass * Double_t(a); }
   else { fMass = mass; }
   fLogger->Info(MESSAGE_ORIGIN, "New Ion %s Z=%d  A=%d  Charge=%d  Mass=%0.7f GeV ", name, z, a , q, fMass);
 }
FairIon::~FairIon () virtual
Destructor
Definition at line 60 of file FairIon.cxx.
 {
 };
FairIon::FairIon (const FairIon &) private
.931494028 Gev/c**2
Member Function Documentation
FairIon::ClassDef (FairIon , 2) private
Int_t FairIon::GetA () const inline
Return the atomic mass
Definition at line 71 of file FairIon.h.
References fA.
Referenced by FairMCApplication::AddIons(), and FairIonGenerator::FairIonGenerator().
 { return fA; }
Double_t FairIon::GetExcEnergy () const inline
Return the excitation energy
Definition at line 79 of file FairIon.h.
References fExcEnergy.
Referenced by FairMCApplication::AddIons().
 { return fExcEnergy; }
Double_t FairIon::GetMass () const inline
Return the mass in GeV
Definition at line 83 of file FairIon.h.
References fMass.
Referenced by FairMCApplication::AddIons().
 { return fMass; }
Int_t FairIon::GetQ () const inline
Return the charge
Definition at line 75 of file FairIon.h.
References fQ.
Referenced by FairMCApplication::AddIons().
 { return fQ; }
Int_t FairIon::GetZ () const inline
Accessors Return the atomic number
Definition at line 67 of file FairIon.h.
References fZ.
Referenced by FairMCApplication::AddIons().
 { return fZ; }
FairIon& FairIon::operator= (const FairIon &) private
void FairIon::SetExcEnergy (Double_t eExc) inline
Modifiers Set the excitation energy
Definition at line 89 of file FairIon.h.
References fExcEnergy.
Referenced by FairIonGenerator::SetExcitationEnergy().
 { fExcEnergy = eExc; }
void FairIon::SetMass (Double_t mass) inline
Set the mass in GeV
Definition at line 93 of file FairIon.h.
References amu, and fMass.
Referenced by FairIonGenerator::SetMass().
 { fMass = mass*amu; }
void FairIon::SetParams (const char * name, Int_t z, Int_t a, Int_t q, Double_t e = 0., Double_t m = 0.) inline
Definition at line 50 of file FairIon.h.
References fA, fExcEnergy, fMass, fQ, and fZ.
{
       SetName(name);
       fZ=z;
       fA=a;
       fQ=q;
       fExcEnergy=e;
       fMass=m;
     }
Member Data Documentation
const Double_t FairIon::amu =0.931494028 static private
/// FairLogger
Definition at line 107 of file FairIon.h.
Referenced by SetMass().
Int_t FairIon::fA private
Atomic number.
Definition at line 102 of file FairIon.h.
Referenced by GetA(), and SetParams().
Double_t FairIon::fExcEnergy private
Electric charge.
Definition at line 104 of file FairIon.h.
Referenced by GetExcEnergy(), SetExcEnergy(), and SetParams().
Int_t FairIon::fgNIon static private
Data members
Definition at line 100 of file FairIon.h.
FairLogger* FairIon::fLogger private
Mass [GeV].
Definition at line 106 of file FairIon.h.
Referenced by FairIon().
Double_t FairIon::fMass private
Excitation energy [GeV].
Definition at line 105 of file FairIon.h.
Referenced by FairIon(), GetMass(), SetMass(), and SetParams().
Int_t FairIon::fQ private
Atomic mass.
Definition at line 103 of file FairIon.h.
Referenced by GetQ(), and SetParams().
Int_t FairIon::fZ private
/// Number of ions instantiated. One per generator.
Definition at line 101 of file FairIon.h.
Referenced by GetZ(), and SetParams().
The documentation for this class was generated from the following files:
FairIon.h
FairIon.cxx