FairRoot: FairAsciiGenerator Class Reference
FairAsciiGenerator Class Reference
#include <FairAsciiGenerator.h>
Public Member Functions
FairAsciiGenerator ()
FairAsciiGenerator (const char *fileName)
virtual ~FairAsciiGenerator ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
ClassDef (FairGenerator, 1)
Private Member Functions
void CloseInput ()
Input file Name.
FairAsciiGenerator (const FairAsciiGenerator &)
FairAsciiGenerator & operator= (const FairAsciiGenerator &)
ClassDef (FairAsciiGenerator, 1)
Private Attributes
std::ifstream * fInputFile
const Char_t * fFileName
Input file stream.
Detailed Description
Definition at line 41 of file FairAsciiGenerator.h.
Constructor & Destructor Documentation
FairAsciiGenerator::FairAsciiGenerator ()
Default constructor without arguments should not be used.
Definition at line 20 of file FairAsciiGenerator.cxx.
   :FairGenerator(),
    fInputFile(NULL),
    fFileName("")
 {
 }
FairAsciiGenerator::FairAsciiGenerator (const char * fileName)
Standard constructor.
Parameters
fileName The input file name
Definition at line 31 of file FairAsciiGenerator.cxx.
References FairLogger::endl(), FATAL, fFileName, fInputFile, INFO, and LOG.
   :FairGenerator(),
    fInputFile(0),
    fFileName(fileName)
 {
   //  fFileName  = fileName;
   LOG(INFO) << "FairAsciiGenerator: Opening input file "
             << fileName << FairLogger::endl;
   fInputFile = new std::ifstream(fFileName);
   if ( ! fInputFile->is_open() ) {
     LOG(FATAL) << "Cannot open input file." << FairLogger::endl;
   }
   // fPDG=TDatabasePDG::Instance();
 }
FairAsciiGenerator::~FairAsciiGenerator () virtual
Destructor.
Definition at line 51 of file FairAsciiGenerator.cxx.
References CloseInput().
 {
   CloseInput();
 }
FairAsciiGenerator::FairAsciiGenerator (const FairAsciiGenerator &) private
Member Function Documentation
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
FairAsciiGenerator::ClassDef (FairAsciiGenerator , 1) private
PDG data base
FairGenerator * FairGenerator::CloneGenerator () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
 {
   Fatal("CloneGenerator","Has to be overriden in multi-threading applications.");
   return 0;
 }
void FairAsciiGenerator::CloseInput () private
Input file Name.
Private method CloseInput. Just for convenience. Closes the input file properly. Called from destructor and from ReadEvent.
Definition at line 116 of file FairAsciiGenerator.cxx.
References FairLogger::endl(), fFileName, fInputFile, INFO, and LOG.
Referenced by ReadEvent(), and ~FairAsciiGenerator().
 {
   if ( fInputFile ) {
     if ( fInputFile->is_open() ) {
       LOG(INFO) << "FairAsciiGenerator: Closing input file "
                 << fFileName << FairLogger::endl;
       fInputFile->close();
     }
     delete fInputFile;
     fInputFile = NULL;
   }
 }
virtual Bool_t FairGenerator::Init () inline virtual inherited
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
 { return kTRUE;}
FairAsciiGenerator& FairAsciiGenerator::operator= (const FairAsciiGenerator &) private
Bool_t FairAsciiGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Reads on event from the input file and pushes the tracks onto the stack. Abstract method in base class.
Parameters
primGen pointer to the FairPrimaryGenerator
Implements FairGenerator.
Definition at line 60 of file FairAsciiGenerator.cxx.
References FairPrimaryGenerator::AddTrack(), CloseInput(), FairLogger::endl(), ERROR, fInputFile, INFO, and LOG.
 {
   // Check for input file
   if ( ! fInputFile->is_open() ) {
     LOG(ERROR) << "FairAsciiGenerator: Input file not open!"
                << FairLogger::endl;
     return kFALSE;
   }
   // Define event variable to be read from file
   Int_t ntracks = 0, eventID = 0;
   Double_t vx = 0., vy = 0., vz = 0.;
   // Define track variables to be read from file
   Int_t pdgID = 0;
   Double_t px = 0., py = 0., pz = 0.;
   // Read event header line from input file
   *fInputFile >> ntracks >> eventID >>  vx >>  vy >>  vz;
   // If end of input file is reached : close it and abort run
   if ( fInputFile->eof() ) {
     LOG(INFO) << "FairAsciiGenerator: End of input file reached "
               << FairLogger::endl;
     CloseInput();
     return kFALSE;
   }
   LOG(INFO) << "FairAsciiGenerator: Event " << eventID << ",  vertex = ("
             << vx << "," << vy << "," << vz << ") cm,  multiplicity "
             << ntracks << FairLogger::endl;
   // Loop over tracks in the current event
   for (Int_t itrack=0; itrack<ntracks; itrack++) {
     // Read PID and momentum from file
     *fInputFile >> pdgID >> px >> py >> pz;
     // convert Geant3 code to PDG code
     // Int_t pdg= fPDG->ConvertGeant3ToPdg(pdgID);
     // Give track to PrimaryGenerator
     primGen->AddTrack(pdgID, px, py, pz, vx, vy, vz);
   }
   return kTRUE;
 }
Member Data Documentation
const Char_t* FairAsciiGenerator::fFileName private
Input file stream.
Definition at line 71 of file FairAsciiGenerator.h.
Referenced by CloseInput(), and FairAsciiGenerator().
std::ifstream* FairAsciiGenerator::fInputFile private
Definition at line 70 of file FairAsciiGenerator.h.
Referenced by CloseInput(), FairAsciiGenerator(), and ReadEvent().
The documentation for this class was generated from the following files:
FairAsciiGenerator.h
FairAsciiGenerator.cxx