FairRroot: TriviallyCopyableDataSaver< TPayload > Class Template Reference
TriviallyCopyableDataSaver< TPayload > Class Template Reference
#include <TriviallyCopyableDataSaver.h>
Public Member Functions
TriviallyCopyableDataSaver ()
virtual ~TriviallyCopyableDataSaver ()
virtual void InitOutputFile ()
void Write (std::ofstream &outfile, TPayload *ObjArr, long sizeArr=1)
void Write (std::ofstream &outfile, FairMQMessage *msg)
std::vector< std::vector
< TPayload > > Read (std::ifstream &infile)
void ReadArr (std::ifstream &infile, std::vector< std::vector< TPayload > > &DataContainer)
template<typename T >
void ReadArr (std::ifstream &infile, T *ObjArr, long posArr=0)
template<typename T >
void write_pod (std::ofstream &out, T &t)
template<typename T >
void read_pod (std::ifstream &in, T &t)
template<typename T >
void write_pod_vector (std::ofstream &out, std::vector< T > &vect)
template<typename T >
void read_pod_vector (std::ifstream &in, std::vector< T > &vect)
template<typename T >
void write_pod_array (std::ofstream &out, T *objarr, long size)
template<typename T >
int count_podObj_inFile (std::ifstream &in)
template<typename T >
long read_pod_array (std::ifstream &in, T *objarr, long posArr=0)
Detailed Description
template<typename TPayload>
class TriviallyCopyableDataSaver< TPayload >
Definition at line 14 of file TriviallyCopyableDataSaver.h.
Constructor & Destructor Documentation
template<typename TPayload > TriviallyCopyableDataSaver< TPayload >::TriviallyCopyableDataSaver () inline
Definition at line 17 of file TriviallyCopyableDataSaver.h.
 {}
template<typename TPayload > virtual TriviallyCopyableDataSaver< TPayload >::~TriviallyCopyableDataSaver () inline virtual
Definition at line 18 of file TriviallyCopyableDataSaver.h.
 {}
Member Function Documentation
template<typename TPayload > template<typename T > int TriviallyCopyableDataSaver< TPayload >::count_podObj_inFile (std::ifstream & in) inline
Definition at line 157 of file TriviallyCopyableDataSaver.h.
     {
         int count=0;
         //if(std::is_trivially_copyable<T>::value)
         if(std::is_trivial<TPayload>::value)
         {
             int c = in.peek();
             if (c == EOF)
             {
                 if (in.eof())
                 {
                      in.close();
                 }
             }
             else
             {
                 long size;
                 read_pod<long>(in, size);
                 count+=size;
                 in.seekg (size * sizeof(T), std::ios::cur);
                 count+=count_podObj_inFile<T>(in);
             }
         }
         return count;
     }
template<typename TPayload > virtual void TriviallyCopyableDataSaver< TPayload >::InitOutputFile () inline virtual
Definition at line 21 of file TriviallyCopyableDataSaver.h.
 {}
template<typename TPayload > std::vector<std::vector<TPayload> > TriviallyCopyableDataSaver< TPayload >::Read (std::ifstream & infile) inline
Definition at line 48 of file TriviallyCopyableDataSaver.h.
References TriviallyCopyableDataSaver< TPayload >::ReadArr().
     {
         std::vector<std::vector<TPayload> > DataContainer;
         ReadArr(infile,DataContainer);
         return DataContainer;
     }
template<typename TPayload > template<typename T > void TriviallyCopyableDataSaver< TPayload >::read_pod (std::ifstream & in, T & t) inline
Definition at line 126 of file TriviallyCopyableDataSaver.h.
Referenced by TriviallyCopyableDataSaver< TPayload >::read_pod_vector().
     {
         in.read(reinterpret_cast<char*>(&t), sizeof(T));
     }
template<typename TPayload > template<typename T > long TriviallyCopyableDataSaver< TPayload >::read_pod_array (std::ifstream & in, T * objarr, long posArr = 0) inline
Definition at line 184 of file TriviallyCopyableDataSaver.h.
     {
         long size;
         read_pod<long>(in, size);
         in.read(reinterpret_cast<char*>(objarr+posArr), size * sizeof(T));
         return size;
     }
template<typename TPayload > template<typename T > void TriviallyCopyableDataSaver< TPayload >::read_pod_vector (std::ifstream & in, std::vector< T > & vect) inline
Definition at line 140 of file TriviallyCopyableDataSaver.h.
References TriviallyCopyableDataSaver< TPayload >::read_pod().
     {
         long size;
         read_pod(in, size);
         vect.resize(size);
         in.read(reinterpret_cast<char*>(vect.front()), size * sizeof(T));
     }
template<typename TPayload > void TriviallyCopyableDataSaver< TPayload >::ReadArr (std::ifstream & infile, std::vector< std::vector< TPayload > > & DataContainer) inline
Definition at line 57 of file TriviallyCopyableDataSaver.h.
References ERROR, and MQLOG.
Referenced by TriviallyCopyableDataSaver< TPayload >::Read().
     {
         //if(std::is_trivially_copyable<TPayload>::value)
         if(std::is_trivial<TPayload>::value)
         {
             int c = infile.peek();
             if (c == EOF)
             {
                 if (infile.eof())
                 {
                      infile.close();
                 }
             }
             else
             {
                 long sizeArr;
                 read_pod<long>(infile, sizeArr);
                 TPayload* ObjArr = new TPayload[sizeArr];
                 infile.read(reinterpret_cast<char*>(ObjArr), sizeArr * sizeof(TPayload));
                 std::vector<TPayload>  DataVector(ObjArr, ObjArr +sizeArr);
                 delete[] ObjArr;
                 DataContainer.push_back(DataVector);
                 ReadArr(infile, DataContainer);
             }
         }
         else
         {
             MQLOG(ERROR)<<"In ReadArr(std::ifstream& , std::vector<std::vector<TPayload> >& ) :";
             MQLOG(ERROR)<<"(de)serialization of object is not supported (Object must be a 'trivially copyable' data class).";
         }
     }
template<typename TPayload > template<typename T > void TriviallyCopyableDataSaver< TPayload >::ReadArr (std::ifstream & infile, T * ObjArr, long posArr = 0) inline
Definition at line 92 of file TriviallyCopyableDataSaver.h.
References ERROR, and MQLOG.
     {
         //if(std::is_trivially_copyable<T>::value)
         if(std::is_trivial<TPayload>::value)
         {
             int c = infile.peek();
             if (c == EOF)
             {
                 if (infile.eof())
                 {
                      infile.close();
                 }
             }
             else
             {
                 posArr+=read_pod_array<T>(infile, ObjArr,posArr);
                 ReadArr<T>(infile, ObjArr,posArr);
             }
         }
         else
         {
             MQLOG(ERROR)<<"In ReadArr(std::ifstream& infile, T* ObjArr, long posArr=0) :";
             MQLOG(ERROR)<<"(de)serialization of object is not supported (Object must be a 'trivially copyable' data class).";
         }
     }
template<typename TPayload > void TriviallyCopyableDataSaver< TPayload >::Write (std::ofstream & outfile, TPayload * ObjArr, long sizeArr = 1) inline
Definition at line 23 of file TriviallyCopyableDataSaver.h.
     {
         //if(std::is_trivially_copyable<TPayload>::value) not implemented yet in gcc 4.8.2
         if(std::is_trivial<TPayload>::value)
         {
             write_pod_array<TPayload>(outfile, ObjArr, sizeArr);
             outfile.close();
         }
     }
template<typename TPayload > void TriviallyCopyableDataSaver< TPayload >::Write (std::ofstream & outfile, FairMQMessage * msg) inline
Definition at line 33 of file TriviallyCopyableDataSaver.h.
References FairMQMessage::GetData(), and FairMQMessage::GetSize().
     {
         int inputSize = msg->GetSize();
         long sizeArr=0;
         if(inputSize>0)
             sizeArr = inputSize / sizeof(TPayload);
         TPayload* ObjArr = static_cast<TPayload*>(msg->GetData());
         //if(std::is_trivially_copyable<TPayload>::value)
         if(std::is_trivial<TPayload>::value)
         {
             write_pod_array<TPayload>(outfile, ObjArr, sizeArr);
             outfile.close();
         }
     }
template<typename TPayload > template<typename T > void TriviallyCopyableDataSaver< TPayload >::write_pod (std::ofstream & out, T & t) inline
Definition at line 120 of file TriviallyCopyableDataSaver.h.
     {
         out.write(reinterpret_cast<char*>(&t), sizeof(T));
     }
template<typename TPayload > template<typename T > void TriviallyCopyableDataSaver< TPayload >::write_pod_array (std::ofstream & out, T * objarr, long size) inline
Definition at line 149 of file TriviallyCopyableDataSaver.h.
     {
         write_pod<long>(out, size);
         out.write(reinterpret_cast<char*>(objarr), size * sizeof(T));
     }
template<typename TPayload > template<typename T > void TriviallyCopyableDataSaver< TPayload >::write_pod_vector (std::ofstream & out, std::vector< T > & vect) inline
Definition at line 132 of file TriviallyCopyableDataSaver.h.
     {
         long size = vect.size();
         write_pod<long>(out, size);
         out.write(reinterpret_cast<char*>(vect.front()), size * sizeof(T));
     }
The documentation for this class was generated from the following file:
TriviallyCopyableDataSaver.h