FairRroot: FairMCObject Class Reference
FairMCObject Class Reference
#include <FairMCObject.h>
Public Member Functions
FairMCObject ()
FairMCObject (Int_t type)
FairMCObject (const FairMCObject &obj)
FairMCObject (Int_t type, std::vector< FairMCEntry > stage)
FairMCObject & operator= (const FairMCObject &from)
virtual ~FairMCObject ()
void SetStageId (Int_t type)
void SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index)
void SetEntry (FairMultiLinkedData *data, int index)
void SetEntry (FairMCEntry link)
void SetStage (std::vector< FairMCEntry > stage)
void SetLink (FairLink link, int index)
void AddLink (FairLink link, int index)
FairMCEntry GetEntry (int index) const
FairLink GetSingleLink (int entryIndex, int linkIndex) const
Int_t GetStageId (void) const
FairMCEntry GetMCLink (Int_t index)
int GetNEntries () const
int GetNLinks (int entryIndex) const
std::vector< FairMCEntry > GetEntryVector () const
FairMultiLinkedData PosInList (std::pair< int, int > link)
FairMultiLinkedData PosInList (FairLink link)
FairMultiLinkedData GetLinksWithType (Int_t type)
void RemoveType (Int_t type)
virtual void ClearEntries ()
virtual void Print (std::ostream &out=std::cout)
Private Member Functions
void AdoptSize (int index)
ClassDef (FairMCObject, 0)
Private Attributes
std::vector< FairMCEntry > fStage
Int_t fStageId
Friends
std::ostream & operator<< (std::ostream &out, const FairMCObject &obj)
Detailed Description
Definition at line 31 of file FairMCObject.h.
Constructor & Destructor Documentation
FairMCObject::FairMCObject ()
Definition at line 19 of file FairMCObject.cxx.
   : TObject(),
     fStage(0),
     fStageId()
 {
 }
FairMCObject::FairMCObject (Int_t type) inline
Definition at line 35 of file FairMCObject.h.
       : TObject(),
         fStage(),
         fStageId(type) {
     }
FairMCObject::FairMCObject (const FairMCObject & obj) inline
Definition at line 40 of file FairMCObject.h.
       : TObject(obj),
         fStageId(obj.GetStageId()),
         fStage(obj.GetEntryVector()) {
     }
FairMCObject::FairMCObject (Int_t type, std::vector< FairMCEntry > stage) inline
Definition at line 45 of file FairMCObject.h.
       : TObject(),
         fStage(stage),
         fStageId(type) {
     }
FairMCObject::~FairMCObject () virtual
Definition at line 26 of file FairMCObject.cxx.
 {
 }
Member Function Documentation
void FairMCObject::AddLink (FairLink link, int index)
Definition at line 66 of file FairMCObject.cxx.
References AdoptSize(), and fStage.
Referenced by SetLink().
 {
   AdoptSize(index);
   fStage[index].AddLink(link);
 }
void FairMCObject::AdoptSize (int index) private
Definition at line 72 of file FairMCObject.cxx.
References fStage, GetStageId(), FairMultiLinkedData::SetPersistanceCheck(), FairMCEntry::SetPos(), and FairMCEntry::SetSource().
Referenced by AddLink(), and SetEntry().
 {
   int start = fStage.size();
   while (fStage.size() < index+1) {
     FairMCEntry myVec;
     myVec.SetPos(fStage.size());
     myVec.SetSource(GetStageId());
     myVec.SetPersistanceCheck(kFALSE);
     fStage.push_back(myVec);
     start++;
   }
 }
FairMCObject::ClassDef (FairMCObject , 0) private
virtual void FairMCObject::ClearEntries () inline virtual
Reimplemented in FairMCStage.
Definition at line 99 of file FairMCObject.h.
References fStage.
Referenced by FairMCStage::ClearEntries().
 {fStage.clear();}
FairMCEntry FairMCObject::GetEntry (int index) const inline
Definition at line 73 of file FairMCObject.h.
References fStage.
 {return fStage[index];}
std::vector<FairMCEntry> FairMCObject::GetEntryVector () const inline
Definition at line 84 of file FairMCObject.h.
References fStage.
 {return fStage;}
FairMultiLinkedData FairMCObject::GetLinksWithType (Int_t type) inline
Definition at line 89 of file FairMCObject.h.
References FairMultiLinkedData::AddLinks(), GetMCLink(), and GetNEntries().
{
       FairMultiLinkedData result;
       for (int i = 0; i < GetNEntries(); i++) {
         result.AddLinks(GetMCLink(i).GetLinksWithType(type));
       }
       return result;
     }
FairMCEntry FairMCObject::GetMCLink (Int_t index) inline
Definition at line 80 of file FairMCObject.h.
References fStage.
Referenced by FairMCMatchCreatorTask::Exec(), and GetLinksWithType().
 {return fStage.at(index);}
int FairMCObject::GetNEntries () const inline
Definition at line 82 of file FairMCObject.h.
References fStage.
Referenced by FairMCMatchCreatorTask::Exec(), GetLinksWithType(), FairMCMatch::GetMCInfoBackward(), and FairMCMatch::GetMCInfoForward().
 {return fStage.size();}
int FairMCObject::GetNLinks (int entryIndex) const inline
Definition at line 83 of file FairMCObject.h.
References fStage.
 {return fStage.at(entryIndex).GetNLinks();}
FairLink FairMCObject::GetSingleLink (int entryIndex, int linkIndex) const inline
Definition at line 74 of file FairMCObject.h.
References fStage.
{
       return fStage.at(entryIndex).GetLink(linkIndex);
     }
Int_t FairMCObject::GetStageId (void) const inline
Definition at line 78 of file FairMCObject.h.
References fStageId.
Referenced by AdoptSize(), FairMCMatchCreatorTask::Exec(), FairMCMatch::GetMCInfoForward(), and PosInList().
 {return fStageId;}
FairMCObject& FairMCObject::operator= (const FairMCObject & from) inline
Definition at line 51 of file FairMCObject.h.
References fStage, fStageId, and operator=().
Referenced by FairMCResult::operator=(), and FairMCStage::operator=().
{
       if (this == &from) { return *this; }
       TObject::operator=(from);
       fStage=from.fStage;
       fStageId=from.fStageId;
       return *this;
     }
FairMultiLinkedData FairMCObject::PosInList (std::pair< int, int > link)
FairMultiLinkedData FairMCObject::PosInList (FairLink link)
Definition at line 85 of file FairMCObject.cxx.
References FairMultiLinkedData::AddLink(), fStage, FairLink::GetIndex(), GetStageId(), FairLink::GetType(), and FairMultiLinkedData::SetPersistanceCheck().
 {
   FairMultiLinkedData result;
   result.SetPersistanceCheck(kFALSE);
   for (int i = 0; i < fStage.size(); i++) {
     if (fStage[i].IsLinkInList(link.GetType(), link.GetIndex())) {
       result.AddLink(FairLink(GetStageId(), i));
     }
   }
   return result;
 }
virtual void FairMCObject::Print (std::ostream & out = std::cout) inline virtual
Reimplemented in FairMCStage, and FairMCResult.
Definition at line 101 of file FairMCObject.h.
 {out << *this;}
void FairMCObject::RemoveType (Int_t type)
Definition at line 97 of file FairMCObject.cxx.
References fStage.
 {
   for (int i = 0; i < fStage.size(); i++) {
     fStage[i].RemoveType(type);
   }
 }
void FairMCObject::SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index)
Definition at line 40 of file FairMCObject.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData::SetPersistanceCheck(), and FairMCEntry::SetPos().
Referenced by FairMCMatch::GetMCInfoBackward(), and FairMCMatch::GetMCInfoForward().
 {
   FairMCEntry myEntry;
   myEntry.SetPos(index);
   myEntry.SetPersistanceCheck(kFALSE);
   for (int i = 0; i < type.size(); i++) {
     myEntry.AddLink(FairLink(type[i],link[i]));
   }
   SetEntry(myEntry);
 }
void FairMCObject::SetEntry (FairMultiLinkedData * data, int index)
Definition at line 51 of file FairMCObject.cxx.
References AdoptSize(), fStage, and FairMultiLinkedData::GetLinks().
 {
   AdoptSize(index);
   fStage[index].SetLinks(data->GetLinks());
 }
void FairMCObject::SetEntry (FairMCEntry link)
Definition at line 30 of file FairMCObject.cxx.
References AdoptSize(), fStage, and FairMCEntry::GetPos().
 {
   if (entry.GetPos() < 0) {
     std::cout << "-E- FairMCObject::SetEntry(FairMCEntry): pos " << entry.GetPos() << std::endl;
     return;
   }
   AdoptSize(entry.GetPos());
   fStage[entry.GetPos()] = entry;
 }
void FairMCObject::SetLink (FairLink link, int index)
Definition at line 57 of file FairMCObject.cxx.
References AddLink(), and fStage.
 {
   if (index < fStage.size()) {
     fStage[index].ResetLinks();
   }
   AddLink(link, index);
 }
void FairMCObject::SetStage (std::vector< FairMCEntry > stage) inline
Definition at line 69 of file FairMCObject.h.
References fStage.
 {fStage = stage;}
void FairMCObject::SetStageId (Int_t type) inline
Definition at line 63 of file FairMCObject.h.
References fStageId.
 {fStageId = type;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const FairMCObject & obj) friend
Definition at line 110 of file FairMCObject.h.
{
       std::vector<FairMCEntry> stages = obj.GetEntryVector();
       for (int i = 0; i < stages.size(); i++) {
         if (stages[i].GetNLinks() > 0) {
           out << i << ": ";
           stages[i].Print(out);
           out << std::endl;
         }
       }
       return out;
     }
Member Data Documentation
std::vector<FairMCEntry> FairMCObject::fStage private
Definition at line 124 of file FairMCObject.h.
Referenced by AddLink(), AdoptSize(), ClearEntries(), GetEntry(), GetEntryVector(), GetMCLink(), GetNEntries(), GetNLinks(), GetSingleLink(), operator=(), PosInList(), RemoveType(), SetEntry(), SetLink(), and SetStage().
Int_t FairMCObject::fStageId private
Definition at line 125 of file FairMCObject.h.
Referenced by GetStageId(), operator=(), and SetStageId().
The documentation for this class was generated from the following files:
FairMCObject.h
FairMCObject.cxx