FairRroot: FairParTSQLIo Class Reference
FairParTSQLIo Class Reference
#include <FairParTSQLIo.h>
Public Member Functions
FairParTSQLIo ()
FairParTSQLIo (FairDbConnectionPool const &cons, int const dbNum=-1)
virtual ~FairParTSQLIo ()
void disconnect ()
void setDetParIo (Text_t *io)
bool check ()
bool open ()
void close ()
void print ()
void SetDefaultDBNum (int const dbNum)
int GetDefaultDBNum () const
FairDbConnectionPool const & GetConnections () const
void readVersions (FairRtdbRun *aRun)
FairRtdbRun * getCurrentRun ()
void SetShutdown (Bool_t shutdown=kFALSE)
void SetRollback (TString rollbackdate, TString tablename="*")
void SetRollbackMode (Int_t mode=0, TString tablename="*")
void SetHoldConnection (Int_t mode=1)
void SetQueryOrdering ()
void SetCache (TString cache_file="")
void CombineDataType (TString input_type, TString other_type)
void SetGlobalSeqNoIn (Int_t seqno)
Int_t GetGlobalSeqNoIn ()
Int_t GetGlobalSeqNoOut ()
void SetVerbosity (Int_t level=1)
virtual FairDetParIo * getDetParIo (const Text_t *)
virtual void setDetParIo (FairDetParIo *)
virtual void removeDetParIo (Text_t *)
void setInputNumber (Int_t)
const char * getFilename ()
virtual void cd ()
void setAutoWritable (Bool_t f=kTRUE)
Bool_t isAutoWritable ()
Protected Member Functions
bool activateDetIo ()
Protected Attributes
TList * detParIoList
Bool_t autoWritable
TString filename
Private Member Functions
FairParTSQLIo (FairParTSQLIo const &ot)
FairParTSQLIo & operator= (FairParTSQLIo const &ot)
Private Attributes
FairRtdbRun * fCurrentRun
int fDefaultDb
FairDbConnectionPool * fConnections
Int_t fGlobalSeqNoIn
Int_t fGlobalSeqNoOut
Detailed Description
Definition at line 31 of file FairParTSQLIo.h.
Constructor & Destructor Documentation
FairParTSQLIo::FairParTSQLIo ()
Default constructor.
FairParTSQLIo::FairParTSQLIo (FairDbConnectionPool const & cons, int const dbNum = -1)
Parameters
cons FairDbConnectionPool which holds a number of initialized db connections.
dbNum The db which is selected to act as the master for the current operations. Note: A new FairDbConnection object is created (to keep the ownership).
Definition at line 66 of file FairParTSQLIo.cxx.
   : FairParIo(),
     fCurrentRun(NULL),
     fDefaultDb (dbNum),
     fConnections(FairDbTableInterfaceStore::Instance().fConnectionPool),
         fGlobalSeqNoIn(MIN_SEQNO),
     fGlobalSeqNoOut(INT_MAX)
 {
 //  fCurrentRun=NULL;
 }
FairParTSQLIo::~FairParTSQLIo () virtual
Destructor
Definition at line 78 of file FairParTSQLIo.cxx.
References disconnect().
 {
   disconnect();
 }
FairParTSQLIo::FairParTSQLIo (FairParTSQLIo const & ot) private
Member Function Documentation
bool FairParTSQLIo::activateDetIo () protected
Definition at line 139 of file FairParTSQLIo.cxx.
References FairParIo::detParIoList, and fConnections.
 {
   std::cout << "-I- FairParTSQLIo::activateDetIo()\n";
   if(!fConnections) {
     return false;
   }
   FairDetParIo* io=new FairGenericParTSQLIo();
   detParIoList->Add(io);
   return true;
 }
virtual void FairParIo::cd () inline virtual inherited
Reimplemented in FairParRootFileIo.
Definition at line 54 of file FairParIo.h.
Referenced by FairRuntimeDb::closeFirstInput(), FairRuntimeDb::closeSecondInput(), FairRuntimeDb::getOutput(), FairRuntimeDb::getSecondInput(), and FairRuntimeDb::writeVersions().
 {;}
bool FairParTSQLIo::check () virtual
Check if at least one connection is alive.
Returns
True if the connection is alive.
Reimplemented from FairParIo.
Definition at line 84 of file FairParTSQLIo.cxx.
References fConnections, and fDefaultDb.
 {
   //FairDbConnectionPool::Status s;
   int stat = -100;
   // Check if at least one DB is connected.
   if(fDefaultDb != -1) { // Has been specified.
     stat = fConnections->GetStatus(fDefaultDb);
     if(stat == FairDbConnectionPool::kFailed ||
         stat == FairDbConnectionPool::kClosed)
       std::cerr << "<Error> The connection to specified default Database"
                 << " is not alive.\n";
   } else { // No selection
     for(size_t db = 0; db < fConnections->GetNumDb(); ++db) {
       stat = fConnections->GetStatus(db);
     }
   }
   return kTRUE;
 }
void FairParTSQLIo::close () inline virtual
Reimplemented from FairParIo.
Definition at line 79 of file FairParTSQLIo.h.
References disconnect().
 {disconnect();}
void FairParTSQLIo::CombineDataType (TString input_type, TString other_type)
Definition at line 399 of file FairParTSQLIo.cxx.
 {
   // Data type combination
   TString comb_cmd = "DataTypeUnion:" + input_type + " = '" + other_type+"'";
   FairDbTableInterfaceStore::Instance().Set(comb_cmd.Data());
   FairDbTableInterfaceStore::Instance().Update();
   DBLOG("FairDb",FairDbLog::kInfo) << " Data Type: "
                                    << input_type.Data() << " is combined with DataTypes: " << other_type.Data() << endl;
 }
void FairParTSQLIo::disconnect ()
Destroy the connection.
Definition at line 120 of file FairParTSQLIo.cxx.
References fConnections.
Referenced by close(), and ~FairParTSQLIo().
 {
   if(fConnections) {
     Int_t nexceptions = FairDbExceptionLog::GetGELog().Size();
     if (  nexceptions ) {
       DBLOG("FairDb",FairDbLog::kInfo)  << "Database Global Exception Log contains "
                                         << nexceptions << " entries:" << endl;;
       FairDbExceptionLog::GetGELog().Print();
     }
     std::cout << "-I- FairParTSQLIO:: Terminating connection: status = "
               << fConnections->GetStatusAsString(0) << " with n_exceptions# "
               << nexceptions
               <<"\n\n";
     delete fConnections;
     fConnections = 0;
   }
 }
FairDbConnectionPool const & FairParTSQLIo::GetConnections () const inline
Get the connection object.
Returns
The actual FairDBConnection object.
Definition at line 155 of file FairParTSQLIo.h.
References fConnections.
 {
   return (*(this->fConnections));
 };
FairRtdbRun* FairParTSQLIo::getCurrentRun () inline
Definition at line 104 of file FairParTSQLIo.h.
References fCurrentRun.
 {return fCurrentRun;}
int FairParTSQLIo::GetDefaultDBNum () const inline
Returns
The default database identification number.
Definition at line 165 of file FairParTSQLIo.h.
References fDefaultDb.
 {
   return this->fDefaultDb;
 };
FairDetParIo * FairParIo::getDetParIo (const Text_t * detName) virtual inherited
Definition at line 69 of file FairParIo.cxx.
Referenced by FairRuntimeDb::activateParIo(), and FairParGenericSet::write().
 {
   // returns pointer to input/output class for a detector
   //std::cout << " DetParIO # " << detName << detParIoList->GetEntries()  <<  std::endl;
   return ((FairDetParIo*)detParIoList->FindObject(detName));
 }
const char* FairParIo::getFilename () inline inherited
Definition at line 36 of file FairParIo.h.
Referenced by FairRunAnaProof::RunOnProof().
 {return filename.Data();}
Int_t FairParTSQLIo::GetGlobalSeqNoIn () inline
Definition at line 126 of file FairParTSQLIo.h.
References fGlobalSeqNoIn.
Referenced by open().
 {return  fGlobalSeqNoIn;}
Int_t FairParTSQLIo::GetGlobalSeqNoOut () inline
Definition at line 127 of file FairParTSQLIo.h.
References fGlobalSeqNoOut.
Referenced by open().
 {return  fGlobalSeqNoOut;}
Bool_t FairParIo::isAutoWritable () inline inherited
Definition at line 58 of file FairParIo.h.
References FairParIo::autoWritable.
Referenced by FairRuntimeDb::closeOutput(), and FairRuntimeDb::writeContainer().
 {return autoWritable;}
bool FairParTSQLIo::open ()
If connection exist to at least on of the specified databases, then activate IO and return true.
Returns
True if at least one connection is available.
(sql_cmds)
entries
Definition at line 151 of file FairParTSQLIo.cxx.
References FairRuntimeDb::activateParIo(), BAS_SEQNO, fConnections, GetGlobalSeqNoIn(), GetGlobalSeqNoOut(), FairRuntimeDb::instance(), and SetGlobalSeqNoIn().
 {
   // Connection check ....
   for (Int_t iEntry = 0; iEntry < fConnections->GetNumDb(); ++iEntry) {
     Bool_t fail= kFALSE;
     auto_ptr<FairDbStatement>
     stmtDb(fConnections->CreateStatement(iEntry));
     if ( ! stmtDb.get() ) {
         DBLOG("FairDb",FairDbLog::kWarning) << "Cannot get a statement for DB entry# " << iEntry
            << "\n  --->  Please check the FAIRDB_TSQL_* environment.  Transaction Failed  ... " << endl;
       return kFALSE;
     }
     // Now prepare Database Infrastructure for each DB entry
         DBLOG("FairDb",FairDbLog::kInfo) << "-I- FairParTSQLIo:.open() checking DB entry# " << iEntry  << endl;
     if (!fConnections->GetConnection(iEntry)->TableExists("FAIRDBGLOBALSEQNO") ) {
      std::vector<std::string> sql_cmds;
      string sql1("CREATE TABLE ");
      sql1 += "FAIRDBLOGENTRYVAL";
      sql1 += "( SEQNO          INT NOT NULL PRIMARY KEY AUTO_INCREMENT,";
      sql1 += "  TIMESTART      DATETIME NOT NULL,";
      sql1 += "  TIMEEND        DATETIME NOT NULL,";
      sql1 += "  DETID          TINYINT,";
      sql1 += "  DATAID         TINYINT,";
      sql1 += "  VERSION        INT,";
      sql1 += "  COMPOSITEID    INT,";
      sql1 += "  TIMEINCR       DATETIME NOT NULL,";
      sql1 += "  TIMETRANS      DATETIME NOT NULL);";
      string sql2("CREATE TABLE ");
      sql2 += "FAIRDBLOGENTRY";
      sql2 += "( SEQNO           INT,";
      sql2 += "  ROW_ID          INT,";
      sql2 += "  TABLENAME       TEXT,";
      sql2 += "  MIN_SEQNO       INT NOT NULL,";
      sql2 += "  MAX_SEQNO       INT NOT NULL,";
      sql2 += "  N_SEQNO         INT NOT NULL,";
      sql2 += "  USERNAME        TEXT,";
      sql2 += "  PROCESS_ID      TEXT,";
      sql2 += "  HOSTNAME        TEXT,";
      sql2 += "  SERVERNAME      TEXT,";
      sql2 += "  LOG_TITLE       TEXT);";
      string sql3("CREATE TABLE ");
      sql3 += "FAIRDBGLOBALSEQNO";
      sql3 += "( TABLENAME      CHAR(64) NOT NULL PRIMARY KEY,";
      sql3 += "  LASTUSEDSEQNO  INT );";
      stringstream insert_sql;
      insert_sql << "INSERT INTO FAIRDBGLOBALSEQNO VALUES ('*'," << GetGlobalSeqNoIn() << ");";
      sql_cmds.push_back(sql1);
      sql_cmds.push_back(sql2);
      sql_cmds.push_back(sql3);
      sql_cmds.push_back(insert_sql.str());
       // Now execute the assemble list of SQL commands.
       auto_ptr<FairDbStatement> stmtDbn(fConnections->CreateStatement(iEntry));
       std::vector<std::string>::iterator itr(sql_cmds.begin()), itrEnd(sql_cmds.end());
       while( itr != itrEnd ) {
         std::string& sql_cmd(*itr++);
                 DBLOG("FairDb",FairDbLog::kInfo)  << " Creating Global Meta Data  at DB entry#  "
                                                                                   << iEntry << "  SQL:" << sql_cmd << endl;
             stmtDbn->ExecuteUpdate(sql_cmd.c_str());
         if ( stmtDbn->PrintExceptions() ) {
           fail = true;
           DBLOG("FairDb",FairDbLog::kFatal) << " ******* Error Creating Meta Data for DB Entry#"
                                             <<  iEntry << endl;
         }
       }
       fConnections->SetAuthorisingEntry(iEntry);
       fConnections->GetConnection(iEntry)->SetTableExists();
           DBLOG("FairDb",FairDbLog::kInfo) << " Meta-structure has been implemented ... continuing " << endl;
     } else {
       // Some Meta-Structure in DB is already existing ... check that !
       TSQLStatement* stmtTSQL = stmtDb->ExecuteQuery("select * from FAIRDBGLOBALSEQNO;");
       if ( stmtTSQL ) {
         while ( stmtTSQL->NextResultRow() ) {
           TString tableName = stmtTSQL->GetString(0);
           int lastUsedSeqNo = stmtTSQL->GetInt(1);
           int abase =  lastUsedSeqNo /  BAS_SEQNO;
           SetGlobalSeqNoIn(abase);
          if ( tableName == "*" && lastUsedSeqNo != GetGlobalSeqNoIn() )  {
               DBLOG("FairDb",FairDbLog::kInfo) << "FAIRDBGLOBALSEQNO table error. Entry * = " <<   lastUsedSeqNo
                  << " but should be: " <<  GetGlobalSeqNoIn() << endl;
             fail = kTRUE;
           } else if  ( tableName != "*" ) {
             string tn3(tableName.Data(),3);
             if ( lastUsedSeqNo < GetGlobalSeqNoIn() || lastUsedSeqNo > GetGlobalSeqNoOut() ) {
                 DBLOG("FairDb",FairDbLog::kInfo) << " FAIRDBGLOBALSEQNO table error. Entry " <<  tableName
                    << " but should start with FAIRDB \n"
                    << "     and last used SEQNO: " << lastUsedSeqNo
                    << " should be in range [ " <<  GetGlobalSeqNoIn() << " .. " << GetGlobalSeqNoOut() <<  " ]" << endl;
               fail = kTRUE;
             }
           }
         }
       }
       if ( fail ) {
          DBLOG("FairDb",FairDbLog::kFatal)
                      << "-I- FairParTSQLIo::open() The FAIRDBGLOBALSEQNO table at DB entry# " << iEntry << " is already\n"
              << " existing but not aligned in sequence nr. range [ " <<  GetGlobalSeqNoIn() << " .. " << GetGlobalSeqNoOut() << " ]"
              << " quit rather than risk damage to this table ... \n" << endl;
         return kFALSE;
       }
        DBLOG("FairDb",FairDbLog::kInfo)  << " Meta-structure for DB entry# " << iEntry
                                          << " looks OK ... continuing" << endl;
     }
   }
   // Activate SQL Io
   FairRuntimeDb::instance()->activateParIo(this);
    DBLOG("FairDb",FairDbLog::kInfo) << " connected with DB Entries# "
                                     << fConnections->GetNumDb() << endl;
   return kTRUE;
 }
FairParTSQLIo& FairParTSQLIo::operator= (FairParTSQLIo const & ot) private
void FairParTSQLIo::print () virtual
Print some info. This function maybe removed in future.
Reimplemented from FairParIo.
Definition at line 283 of file FairParTSQLIo.cxx.
References FairParIo::detParIoList, and fConnections.
 {
   std::cout << "<DEBUG> FairParTSQLIo::print()\n";
   if (fConnections) {
     std::cout << "<INFO> Number of available DBs = " << fConnections->GetNumDb()
               << std::endl;
     TIter next(detParIoList);
     FairDetParIo* io;
     std::cout << " Number of detector I/Os = " << detParIoList->GetSize()
               << "\nDetector IO list:\n";
     while ((io=(FairDetParIo*)next())) {
       std::cout<<" Name = " << io->GetName();
     }//while
     std::cout << std::endl;
   }//if
 }//print
void FairParTSQLIo::readVersions (FairRtdbRun * aRun) virtual
Reimplemented from FairParIo.
Definition at line 303 of file FairParTSQLIo.cxx.
References fCurrentRun.
 {
   // finds the current run containing the parameter container versions
   // in the ROOT file
   fCurrentRun = aRun;
 }
void FairParIo::removeDetParIo (Text_t * detName) virtual inherited
Definition at line 76 of file FairParIo.cxx.
 {
   // removes input/output class for a detector
   TObject* p=detParIoList->FindObject(detName);
   if (p) {
     delete p;
     p=0;
   }
 }
void FairParIo::setAutoWritable (Bool_t f = kTRUE) inline inherited
Definition at line 57 of file FairParIo.h.
 {autoWritable=f;}
void FairParTSQLIo::SetCache (TString cache_file = "")
Definition at line 382 of file FairParTSQLIo.cxx.
 {
   TString cache_cmd = "Level2Cache ";
   TString add_on = "'./'";
   TString cache_def;
   if ( cache_file.IsNull() ) { cache_def = cache_cmd + " = " + add_on; }
   else { cache_def = cache_cmd + " = " + "'"+ cache_file + "'"; }
   FairDbTableInterfaceStore::Instance().Set(cache_def.Data());
   FairDbTableInterfaceStore::Instance().Update();
   DBLOG("FairDb",FairDbLog::kInfo) << " Caching is set: "
                                    << cache_def.Data() << endl;
 }
void FairParTSQLIo::SetDefaultDBNum (int const dbNum) inline
Set which database connection is going to be the default.
Parameters
dbNum The default database identification number.
Definition at line 160 of file FairParTSQLIo.h.
References fDefaultDb.
 {
   this->fDefaultDb = dbNum;
 };
void FairParIo::setDetParIo (FairDetParIo * detParIo) virtual inherited
Definition at line 51 of file FairParIo.cxx.
Referenced by FairRuntimeDb::activateParIo().
 {
   // stores pointer of the input/output class for a detector
   // used for I/O from ROOT file or Ascii file
   Text_t* detName=(char*)detParIo->GetName();
   if (!detParIoList->FindObject(detName)) { detParIoList->Add(detParIo); }
 }
void FairParTSQLIo::setDetParIo (Text_t * io) virtual
creates the specified I/O.
Parameters
io The name of IO to be created/added in the IO list.
Reimplemented from FairParIo.
Definition at line 104 of file FairParTSQLIo.cxx.
References FairParIo::detParIoList, and fConnections.
 {
   if (fConnections) {
     TObject* io = detParIoList->FindObject(ioName);
     // If does not exist
     if(!io) {
       if (strcmp(ioName, "FairGenericParIo") == 0) {
         io = new FairGenericParTSQLIo();
       }
       if (io) {
         detParIoList->Add(io);
       }
     }
   }
 }
void FairParTSQLIo::SetGlobalSeqNoIn (Int_t seqno)
Define the SeqNo boundaries
Definition at line 420 of file FairParTSQLIo.cxx.
References BAS_SEQNO, fGlobalSeqNoIn, fGlobalSeqNoOut, and INC_SEQNO.
Referenced by open().
{
   // DB check for the SEQNO range calculation
   if ( (seqno <0) || (seqno>9) ) {
         DBLOG("FairDb", FairDbLog::kWarning) << "seqno basis: "<< seqno
                                                                                  << "out of range [0..9], seqno will be reset to 0." << endl;
         seqno=0;
   }
   fGlobalSeqNoIn = seqno*BAS_SEQNO;
   fGlobalSeqNoOut = fGlobalSeqNoIn + INC_SEQNO;
   //cout << " SEQNO_IN -------> " << fGlobalSeqNoIn <<  " : " << fGlobalSeqNoOut << endl;
 }
void FairParTSQLIo::SetHoldConnection (Int_t mode = 1)
Definition at line 357 of file FairParTSQLIo.cxx.
 {
   TString hold_cmd;
   if ( mode == 0 ) { hold_cmd="MakeConnectionsPermanent = 0"; }
   if ( mode == 1 ) { hold_cmd="MakeConnectionsPermanent = 1"; }
   if ( mode == -1 ) { hold_cmd="MakeConnectionsPermanent = -1"; }
   FairDbTableInterfaceStore::Instance().Set(hold_cmd.Data());
   FairDbTableInterfaceStore::Instance().Update();
   DBLOG("FairDb",FairDbLog::kInfo) << " Server Connections set to modus: "  <<  mode << endl;
 }
void FairParIo::setInputNumber (Int_t num) inherited
Definition at line 59 of file FairParIo.cxx.
References FairDetParIo::setInputNumber().
Referenced by FairRuntimeDb::setFirstInput(), and FairRuntimeDb::setSecondInput().
 {
   // sets in all detector I/Os the number of the input
   TIter next(detParIoList);
   FairDetParIo* io;
   while ((io=(FairDetParIo*)next())) {
     io->setInputNumber(num);
   }
 }
void FairParTSQLIo::SetQueryOrdering ()
Definition at line 374 of file FairParTSQLIo.cxx.
 {
   TString q_order = "OrderContextQuery = 1";
   FairDbTableInterfaceStore::Instance().Set(q_order.Data());
   FairDbTableInterfaceStore::Instance().Update();
   DBLOG("FairDb",FairDbLog::kInfo) << " Set Query Ordering: 1" << endl;
 }
void FairParTSQLIo::SetRollback (TString rollbackdate, TString tablename = "*")
Definition at line 322 of file FairParTSQLIo.cxx.
 {
   // Rollback settings
   TString rb_cmd = "Rollback:" + tablename + " = '" + rollbackdate + "'";
   FairDbTableInterfaceStore::Instance().Set(rb_cmd.Data());
   FairDbTableInterfaceStore::Instance().Update();
   DBLOG("FairDb",FairDbLog::kInfo) << " Rollback for table: "
                                    << tablename.Data() << " At Date : " << rollbackdate.Data() << " is set "<< endl;
 }
void FairParTSQLIo::SetRollbackMode (Int_t mode = 0, TString tablename = "*")
Definition at line 335 of file FairParTSQLIo.cxx.
 {
   // Rollback Modus settings
   TString modus;
   if ( mode == 0 ) {
     modus="TIMETRANS";
   } else {
     modus="TIMEINCR";
   }
   TString rb_cmd = "RollbackType:" + tablename + " = '" + modus+"'";
   FairDbTableInterfaceStore::Instance().Set(rb_cmd.Data());
   FairDbTableInterfaceStore::Instance().Update();
   DBLOG("FairDb",FairDbLog::kInfo) << " Rollback for table: "
                                    << tablename.Data() << " Using Field: " << modus.Data() << " is set "<< endl;
 }
void FairParTSQLIo::SetShutdown (Bool_t shutdown = kFALSE)
SQL IO Configuration functions
Definition at line 313 of file FairParTSQLIo.cxx.
 {
   // Shutdowm setting
   FairDbTableInterfaceStore::Instance().Set("Shutdown = 1");
   FairDbTableInterfaceStore::Instance().Update();
   DBLOG("FairDb",FairDbLog::kInfo) << " Complete Shutdown is set."<< endl;
 }
void FairParTSQLIo::SetVerbosity (Int_t level = 1)
Verbosity Control
Definition at line 414 of file FairParTSQLIo.cxx.
 {
   FairDbTableInterfaceStore::Instance().SetVerbosity(level);
 }
Member Data Documentation
Bool_t FairParIo::autoWritable protected inherited
Definition at line 24 of file FairParIo.h.
Referenced by FairParIo::isAutoWritable().
TList* FairParIo::detParIoList protected inherited
Definition at line 23 of file FairParIo.h.
Referenced by activateDetIo(), FairParAsciiFileIo::close(), FairParRootFileIo::close(), FairParAsciiFileIo::print(), FairParRootFileIo::print(), print(), and setDetParIo().
FairDbConnectionPool* FairParTSQLIo::fConnections private
Definition at line 146 of file FairParTSQLIo.h.
Referenced by activateDetIo(), check(), disconnect(), GetConnections(), open(), print(), and setDetParIo().
FairRtdbRun* FairParTSQLIo::fCurrentRun private
Definition at line 144 of file FairParTSQLIo.h.
Referenced by getCurrentRun(), and readVersions().
int FairParTSQLIo::fDefaultDb private
Definition at line 145 of file FairParTSQLIo.h.
Referenced by check(), GetDefaultDBNum(), and SetDefaultDBNum().
Int_t FairParTSQLIo::fGlobalSeqNoIn private
Definition at line 147 of file FairParTSQLIo.h.
Referenced by GetGlobalSeqNoIn(), and SetGlobalSeqNoIn().
Int_t FairParTSQLIo::fGlobalSeqNoOut private
Definition at line 148 of file FairParTSQLIo.h.
Referenced by GetGlobalSeqNoOut(), and SetGlobalSeqNoIn().
TString FairParIo::filename protected inherited
Definition at line 25 of file FairParIo.h.
Referenced by FairParAsciiFileIo::close(), FairParAsciiFileIo::open(), FairParRootFileIo::open(), and FairParAsciiFileIo::print().
The documentation for this class was generated from the following files:
FairParTSQLIo.h
FairParTSQLIo.cxx