FairRoot: FairLinkManager Class Reference
FairLinkManager Class Reference
#include <FairLinkManager.h>
Public Member Functions
FairLinkManager ()
virtual ~FairLinkManager ()
virtual void AddIgnoreType (Int_t type)
Adds a BranchId (Type) to which links are not included in the link list. Either ignore types or include types can be given.
virtual Bool_t IsIgnoreType (Int_t type) const
virtual void AddIncludeType (Int_t type)
Adds a BranchId (Type) to which links are included in the link list. Either ignore types or include types can be given (XOR).
std::set< Int_t > GetIgnoreTypes () const
Static Public Member Functions
static FairLinkManager * Instance ()
Private Member Functions
FairLinkManager (const FairLinkManager &)
FairLinkManager & operator= (const FairLinkManager &)
Private Attributes
std::set< Int_t > fIgnoreTypes
Bool_t fIgnoreSetting
FairLogger * fLogger
Static Private Attributes
static TMCThreadLocal FairLinkManager * fgInstance = 0
Detailed Description
Definition at line 15 of file FairLinkManager.h.
Constructor & Destructor Documentation
FairLinkManager::FairLinkManager ()
ctor
Definition at line 26 of file FairLinkManager.cxx.
References fgInstance, fLogger, FairLogger::GetLogger(), and FairRun::Instance().
   : TObject(),
     fIgnoreTypes(),
     fIgnoreSetting(kTRUE),
     fLogger(0)
 {
   if (fgInstance) {
     Fatal("FairLinkManager", "Singleton instance already exists.");
     return;
   }
 //  std::cout << "-I- FairLinkManager::FairLinkManager created!" << std::endl;
   fgInstance = this;
   // Logger only on master - TO DO
   if ( FairRun::Instance()->GetIsMaster() ) {
     fLogger = FairLogger::GetLogger();
   }
 }
FairLinkManager::~FairLinkManager () virtual
dtor
Definition at line 45 of file FairLinkManager.cxx.
References FairLogger::Debug(), fgInstance, fLogger, and MESSAGE_ORIGIN.
 {
 //
   fLogger->Debug(MESSAGE_ORIGIN,"Enter Destructor of FairLinkManager");
   fgInstance = 0;
   fLogger->Debug(MESSAGE_ORIGIN, "Leave Destructor of FairLinkManager");
 }
FairLinkManager::FairLinkManager (const FairLinkManager &) private
private methods
Member Function Documentation
void FairLinkManager::AddIgnoreType (Int_t type) virtual
Adds a BranchId (Type) to which links are not included in the link list. Either ignore types or include types can be given.
Definition at line 54 of file FairLinkManager.cxx.
References FairLogger::Debug(), fIgnoreSetting, fIgnoreTypes, fLogger, and MESSAGE_ORIGIN.
Referenced by FairRootManager::Register().
 {
         if (fIgnoreSetting == kFALSE){
                 fLogger->Debug(MESSAGE_ORIGIN, "AddIgnoreType ignored because of IncludeType setting");
                 return;
         }
         fLogger->Debug(MESSAGE_ORIGIN, "AddIgnoreType");
         fIgnoreTypes.insert(type);
 }
void FairLinkManager::AddIncludeType (Int_t type) virtual
Adds a BranchId (Type) to which links are included in the link list. Either ignore types or include types can be given (XOR).
Definition at line 64 of file FairLinkManager.cxx.
References FairLogger::Debug(), fIgnoreSetting, fIgnoreTypes, fLogger, and MESSAGE_ORIGIN.
 {
         fLogger->Debug(MESSAGE_ORIGIN, "AddIgnoreType");
 //      std::cout << "-I- FairLinkManager::AddIgnoreType: " << type << std::endl;
         if (fIgnoreSetting == kTRUE){
                 fIgnoreSetting=kFALSE;
                 fIgnoreTypes.clear();
         }
         fIgnoreTypes.insert(type);
 }
std::set<Int_t> FairLinkManager::GetIgnoreTypes () const inline
Definition at line 31 of file FairLinkManager.h.
References fIgnoreTypes.
 {return fIgnoreTypes;}
FairLinkManager * FairLinkManager::Instance () static
static access method
Definition at line 18 of file FairLinkManager.cxx.
References fgInstance.
Referenced by FairMultiLinkedData::InsertLink(), and FairRootManager::Register().
 {
 // Returns singleton instance.
 // ---
   return fgInstance;
 }
Bool_t FairLinkManager::IsIgnoreType (Int_t type) const virtual
Definition at line 76 of file FairLinkManager.cxx.
References fIgnoreSetting, and fIgnoreTypes.
 {
         if (fIgnoreSetting)
                 return fIgnoreTypes.count(type);
         else
                 return !fIgnoreTypes.count(type);
 }
FairLinkManager& FairLinkManager::operator= (const FairLinkManager &) private
Member Data Documentation
TMCThreadLocal FairLinkManager * FairLinkManager::fgInstance = 0 static private
Singleton instance
Definition at line 49 of file FairLinkManager.h.
Referenced by FairLinkManager(), Instance(), and ~FairLinkManager().
Bool_t FairLinkManager::fIgnoreSetting private
Definition at line 45 of file FairLinkManager.h.
Referenced by AddIgnoreType(), AddIncludeType(), and IsIgnoreType().
std::set<Int_t> FairLinkManager::fIgnoreTypes private
Set the branch address for a given branch name and return a TObject pointer, the user have to cast this pointer to the right type. private Members
Definition at line 44 of file FairLinkManager.h.
Referenced by AddIgnoreType(), AddIncludeType(), GetIgnoreTypes(), and IsIgnoreType().
FairLogger* FairLinkManager::fLogger private
Definition at line 54 of file FairLinkManager.h.
Referenced by AddIgnoreType(), AddIncludeType(), FairLinkManager(), and ~FairLinkManager().
The documentation for this class was generated from the following files:
FairLinkManager.h
FairLinkManager.cxx