FairRroot: FairPlutoReactionGenerator Class Reference
FairPlutoReactionGenerator Class Reference
#include <FairPlutoReactionGenerator.h>
Public Member Functions
FairPlutoReactionGenerator ()
FairPlutoReactionGenerator (PReaction *reaction)
virtual ~FairPlutoReactionGenerator ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
ClassDef (FairGenerator, 1)
Private Member Functions
FairPlutoReactionGenerator (const FairPlutoReactionGenerator &)
Pointer to the Pluto inline reaction.
FairPlutoReactionGenerator operator= (const FairPlutoReactionGenerator &)
ClassDef (FairPlutoReactionGenerator, 1)
Private Attributes
Int_t iEvent
PReaction * fReaction
Event number.
Detailed Description
Definition at line 41 of file FairPlutoReactionGenerator.h.
Constructor & Destructor Documentation
FairPlutoReactionGenerator::FairPlutoReactionGenerator ()
Default constructor (should not be used)
Definition at line 25 of file FairPlutoReactionGenerator.cxx.
   : FairGenerator(),
     iEvent(0),
 #ifdef PLUTOVERSION_FOR_FAIR
     fPlutoFairGenerator(NULL),
 #endif
     fReaction(NULL)
 {
   /*
   iEvent     = 0;
   fReaction  = NULL;
   #ifdef PLUTOVERSION_FOR_FAIR
   fPlutoFairGenerator = NULL;
   #endif
   */
 }
FairPlutoReactionGenerator::FairPlutoReactionGenerator (PReaction * reaction)
Standard constructor
Parameters
reaction Pointer to PLUTO inline reaction
Definition at line 46 of file FairPlutoReactionGenerator.cxx.
   : FairGenerator(),
     iEvent(0),
 #ifdef PLUTOVERSION_FOR_FAIR
     fPlutoFairGenerator(new PFairGenerator()),
 #endif
     fReaction(reaction)
 {
   //  iEvent     = 0;
   //  fReaction  = reaction;
 #ifdef PLUTOVERSION_FOR_FAIR
   //  fPlutoFairGenerator = new PFairGenerator();
   if (!reaction) {
     std::cout << "-E FairPlutoReactionGenerator: No PReaction!" << std::endl;
   } else {
     reaction->AddBulk(fPlutoFairGenerator);
     reaction->IsInline();
   }
 #else
   std::cout << "-E FairPlutoReactionGenerator: You are using the wrong Pluto version" << std::endl;
 #endif
 }
FairPlutoReactionGenerator::~FairPlutoReactionGenerator () virtual
Destructor
Definition at line 73 of file FairPlutoReactionGenerator.cxx.
 {
 #ifdef PLUTOVERSION_FOR_FAIR
   if (fPlutoFairGenerator) { delete fPlutoFairGenerator; }
 #endif
 }
FairPlutoReactionGenerator::FairPlutoReactionGenerator (const FairPlutoReactionGenerator &) private
Pointer to the Pluto inline reaction.
Member Function Documentation
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
FairPlutoReactionGenerator::ClassDef (FairPlutoReactionGenerator , 1) private
FairGenerator * FairGenerator::CloneGenerator () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
 {
   Fatal("CloneGenerator","Has to be overriden in multi-threading applications.");
   return 0;
 }
virtual Bool_t FairGenerator::Init () inline virtual inherited
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
 { return kTRUE;}
FairPlutoReactionGenerator FairPlutoReactionGenerator::operator= (const FairPlutoReactionGenerator &) private
Bool_t FairPlutoReactionGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Reads on event from the Pluto reaction and pushes the tracks onto the stack. Abstract method in base class.
Parameters
primGen pointer to the FairPrimaryGenerator
Implements FairGenerator.
Definition at line 84 of file FairPlutoReactionGenerator.cxx.
References FairPrimaryGenerator::AddTrack(), and fReaction.
 {
 #ifdef PLUTOVERSION_FOR_FAIR
   // Check for input file
   if ( ! fReaction ) {
     cout << "-E FairPlutoReactionGenerator: No PReaction!" << endl;
     return kFALSE;
   }
   fReaction->InitChannels();
   fReaction->DisableWeightReset();
   if (!fReaction->loop(1,0,0)) { return kFALSE; }
   Double_t px, py, pz, vx, vy, vz;
   Int_t    pdgType;
   while (fPlutoFairGenerator->GetNextParticle(&pdgType, &px, &py, &pz, &vx, &vy, &vz)) {
     if (pdgType) {
       primGen->AddTrack(pdgType, px, py, pz, vx, vy, vz);
     }
   }
   return kTRUE;
 #else
   return kFALSE;
 #endif
 }
Member Data Documentation
PReaction* FairPlutoReactionGenerator::fReaction private
Event number.
Definition at line 74 of file FairPlutoReactionGenerator.h.
Referenced by ReadEvent().
Int_t FairPlutoReactionGenerator::iEvent private
Definition at line 70 of file FairPlutoReactionGenerator.h.
The documentation for this class was generated from the following files:
FairPlutoReactionGenerator.h
FairPlutoReactionGenerator.cxx