FairRroot: FairGeoInterface Class Reference
FairGeoInterface Class Reference
#include <FairGeoInterface.h>
Public Member Functions
FairGeoInterface ()
~FairGeoInterface ()
void setOracleInput (FairGeoIo *p)
void setOutput (FairGeoIo *p)
void setGeomBuilder (FairGeoBuilder *p)
FairGeoIo * getFileInput ()
FairGeoIo * getOraInput ()
FairGeoIo * getOutput ()
FairGeoShapes * getShapes ()
FairGeoMedia * getMedia ()
TList * getMasterNodes ()
void addInputFile (const char *)
void addGeoModule (FairGeoSet *)
void setMediaFile (const char *file)
FairGeoSet * findSet (const char *)
Bool_t readSet (FairGeoSet *)
Bool_t writeSet (FairGeoSet *)
Bool_t writeSet (FairGeoSet *, const char *)
Bool_t createSet (FairGeoSet *)
void deleteSet (FairGeoSet *pSet)
Bool_t readMedia ()
Bool_t writeMedia ()
Bool_t writeMedia (const char *)
Bool_t readAll ()
Bool_t writeAll ()
Bool_t createAll (Bool_t withCleanup=kFALSE)
Bool_t createGeometry (Bool_t withCleanup=kFALSE)
Bool_t readGeomConfig (const char *)
void addSetupFile (const char *f)
Bool_t readSetupFile ()
void print ()
void SetNoOfSets (Int_t n)
Private Member Functions
FairGeoInterface (const FairGeoInterface &)
FairGeoInterface & operator= (const FairGeoInterface &)
FairGeoIo * connectInput (const char *)
Bool_t connectOutput (const char *)
Private Attributes
FairGeoIo * fileInput
FairGeoIo * oraInput
FairGeoIo * output
Int_t nSets
Int_t nActualSets
TObjArray * sets
FairGeoMedia * media
FairGeoShapes * shapes
TList * masterNodes
TString setupFile
FairGeoBuilder * geoBuilder
Detailed Description
Class to manage geometry for simulations
Author
Ilse koenig
M. Al-Turany
Definition at line 42 of file FairGeoInterface.h.
Constructor & Destructor Documentation
FairGeoInterface::FairGeoInterface ()
actually used geometry builder
FairGeoInterface::~FairGeoInterface ()
Definition at line 66 of file FairGeoInterface.cxx.
References fileInput, masterNodes, media, oraInput, output, sets, and shapes.
 {
   // Destructor
   if (fileInput) {
     delete fileInput;
     fileInput=0;
   }
   if (oraInput) {
     delete oraInput;
     oraInput=0;
   }
   if (output) {
     delete output;
     output=0;
   }
 //  if (geoBuilder) {
 //    delete geoBuilder;
 //    geoBuilder=0;
 //  }
   if (masterNodes) {
     masterNodes->Delete();
     delete masterNodes;
     masterNodes=0;
   }
   if (sets) {
     sets->Delete();
     delete sets;
     sets=0;
   }
   if (media) {
     delete media;
     media=0;
   }
   if (shapes) {
     delete shapes;
     shapes=0;
   }
 }
FairGeoInterface::FairGeoInterface (const FairGeoInterface &) private
Member Function Documentation
void FairGeoInterface::addGeoModule (FairGeoSet * pSet)
Definition at line 105 of file FairGeoInterface.cxx.
References masterNodes, nActualSets, FairGeoSet::setMasterNodes(), sets, FairGeoSet::setShapes(), and shapes.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), and FairRutherford::ConstructGeometry().
 {
   sets->AddLast(pSet);
   pSet->setShapes(shapes);
   pSet->setMasterNodes(masterNodes);
   nActualSets++;
 }
void FairGeoInterface::addInputFile (const char * file)
Definition at line 118 of file FairGeoInterface.cxx.
Referenced by createGeometry(), readAll(), and FairGeoAsciiIo::readGeomConfig().
 {
   Error("This Methode is not used any more ","Use addGeoModule to add detectors: %s",file);
   /*
     // Adds the input file and creates the corresponding detector object
     FairGeoSet* pSet=0;
     TString setName(file);
     setName.ToLower();
     Int_t l=setName.Last('/')+1;
     setName=setName(l,setName.Length()-l);
     if (setName.Contains("media")) {
       media->setInputFile(file);
     } else {
       if (setName.Contains("cave")) {
         pSet=(FairGeoSet*)sets->At(kFairGeoCave);
         if (!pSet) {
           pSet=new FairGeoCave;
           sets->AddAt(pSet,kFairGeoCave);
         }
       } else if (setName.Contains("pipe")) {
         pSet=(FairGeoSet*)sets->At(kFairGeoPipe);
         if (!pSet) {
           pSet=new FairGeoPipe;
           sets->AddAt(pSet,kFairGeoPipe);
         }
       } else if (setName.Contains("target")) {
         pSet=(FairGeoSet*)sets->At(kFairGeoTarget);
         if (!pSet) {
           pSet=new FairGeoTarget;
           sets->AddAt(pSet,kFairGeoTarget);
         }
       } else if (setName.Contains("magnet")) {
         pSet=(FairGeoSet*)sets->At(kFairGeoMagnet);
         if (!pSet) {
           pSet=new FairGeoMagnet;
           sets->AddAt(pSet,kFairGeoMagnet);
         }
       } else if (setName.Contains("rich")) {
         pSet=(FairGeoSet*)sets->At(kFairGeoRich);
         if (!pSet) {
           pSet=new FairGeoRich;
           sets->AddAt(pSet,kFairGeoRich);
         }
       } else if (setName.Contains("sts")) {
         pSet=(FairGeoSet*)sets->At(kFairGeoSts);
         if (!pSet) {
           pSet=new FairGeoSts;
           sets->AddAt(pSet,kFairGeoSts);
         }
       } else if (setName.Contains("trd")) {
         pSet=(FairGeoSet*)sets->At(kFairGeoTrd);
         if (!pSet) {
           pSet=new FairGeoTrd;
           sets->AddAt(pSet,kFairGeoTrd);
         }
       } else if (setName.Contains("tof")) {
         pSet=(FairGeoSet*)sets->At(kFairGeoTof);
         if (!pSet) {
           pSet=new FairGeoTof;
           sets->AddAt(pSet,kFairGeoTof);
         }
       } else Error("addInputFile","Unknown detector set: %s",file);
       if (pSet) {
         pSet->setShapes(shapes);
         pSet->setMasterNodes(masterNodes);
         pSet->setGeomFile(file);
         nActualSets++;
       }
     }
     */
 }
void FairGeoInterface::addSetupFile (const char * f) inline
Definition at line 84 of file FairGeoInterface.h.
Referenced by FairGeoAsciiIo::readGeomConfig().
 {setupFile=f;}
FairGeoIo * FairGeoInterface::connectInput (const char * filename) private
Definition at line 385 of file FairGeoInterface.cxx.
References fileInput, FairGeoIo::isOpen(), FairGeoIo::open(), and oraInput.
Referenced by readGeomConfig(), readMedia(), readSet(), and readSetupFile().
 {
   // Connects the input (ASCII or Oracle)
   FairGeoIo* currentIo=0;
   if (filename) {
     TString s(filename);
     s=s.Strip();
     if (s.EndsWith(".dat")||s.EndsWith(".geo")||s.EndsWith(".setup")) {
       if (!fileInput) { fileInput=new FairGeoAsciiIo(); }
       fileInput->open(filename);
       currentIo=fileInput;
     } else if (s.EndsWith("_gdb")) { currentIo=oraInput; }
   }
   if (currentIo && currentIo->isOpen()) { return currentIo; }
   return 0;
 }
Bool_t FairGeoInterface::connectOutput (const char * name) private
Definition at line 402 of file FairGeoInterface.cxx.
References FairGeoIo::isOpen(), FairGeoIo::isWritable(), FairGeoIo::open(), and output.
Referenced by writeMedia(), and writeSet().
 {
   // Connects the output (ASCII or Oracle)
   if (output) {
     if (strcmp(output->IsA()->GetName(),"FairGeoAsciiIo")==0) {
       TString fName(name);
       char buf[80];
       struct tm* newtime;
       time_t t;
       time(&t);
       newtime=localtime(&t);
       if (newtime->tm_mday<10) { sprintf(buf,"_0%i",newtime->tm_mday); }
       else { sprintf(buf,"_%i",newtime->tm_mday); }
       fName=fName+buf;
       if (newtime->tm_mon<9) { sprintf(buf,"0%i",newtime->tm_mon+1); }
       else { sprintf(buf,"%i",newtime->tm_mon+1); }
       fName=fName+buf;
       Int_t y=newtime->tm_year-100;
       if (y<10) { sprintf(buf,"0%i",y); }
       else { sprintf(buf,"%i",y); }
       fName=fName+buf;
       if (newtime->tm_hour<10) { sprintf(buf,"0%i",newtime->tm_hour); }
       else { sprintf(buf,"%i",newtime->tm_hour); }
       fName=fName+buf;
       if (newtime->tm_min<10) { sprintf(buf,"0%i",newtime->tm_min); }
       else { sprintf(buf,"%i",newtime->tm_min); }
       fName=fName+buf;
       if (newtime->tm_sec<10) { sprintf(buf,"0%i",newtime->tm_sec); }
       else { sprintf(buf,"%i",newtime->tm_sec); }
       fName=fName+buf+".geo";
       output->open(fName,"out");
       cout<<"Output file for "<<name<<":  "
           <<((FairGeoAsciiIo*)output)->getFilename()<<endl;
     }
     if (output->isOpen()&&output->isWritable()) { return kTRUE; }
   } else { Error("connectOutput","No output open"); }
   return kFALSE;
 }
Bool_t FairGeoInterface::createAll (Bool_t withCleanup = kFALSE)
Definition at line 326 of file FairGeoInterface.cxx.
References FairGeoSet::create(), FairGeoBuilder::finalize(), geoBuilder, nSets, and sets.
 {
   // Creates the whole geometry
   // (if withCleanup==kTRUE, the geometry input is deleted afterwards)
   Bool_t rc=kTRUE;
   Int_t n=0;
   if (geoBuilder) {
     FairGeoSet* pSet=0;
     for(Int_t i=0; i<nSets&&rc; i++) {
       pSet=(FairGeoSet*)sets->At(i);
       if (pSet) {
         cout<<"Create "<<pSet->GetName()<<endl;
         rc=pSet->create(geoBuilder);
         n++;
         if (withCleanup) {
           sets->RemoveAt(i);
           delete pSet;
         }
       }
     }
     if (rc&&n>0) { geoBuilder->finalize(); }
   } else { Error("createAll()","No Builder"); }
   return rc;
 }
Bool_t FairGeoInterface::createGeometry (Bool_t withCleanup = kFALSE)
Definition at line 351 of file FairGeoInterface.cxx.
References addInputFile(), FairGeoSet::create(), FairGeoBuilder::finalize(), geoBuilder, nActualSets, nSets, oraInput, FairGeoIo::readGeomConfig(), readMedia(), readSet(), readSetupFile(), and sets.
 {
   // Reads and creates the whole geometry
   // (if withCleanup==kTRUE, the geometry input is deleted after creation)
   Bool_t rc=kTRUE;
   Int_t n=0;
   if (geoBuilder) {
     if (nActualSets==0&&oraInput) {
       rc=oraInput->readGeomConfig(this);
       if (rc) { addInputFile("media_gdb"); }
     }
     if (rc) { rc=readSetupFile(); }
     if (rc) { rc=readMedia(); }
     FairGeoSet* pSet=0;
     for(Int_t i=0; i<nSets&&rc; i++) {
       pSet=(FairGeoSet*)sets->At(i);
       if (pSet) {
         cout<<"Read and create "<<pSet->GetName()<<endl;
         rc=readSet(pSet);
         if (rc) {
           rc=pSet->create(geoBuilder);
           n++;
         }
         if (withCleanup) {
           sets->RemoveAt(i);
           delete pSet;
         }
       }
     }
     if (rc&&n>0) { geoBuilder->finalize(); }
   } else { Error("createAll()","No Builder"); }
   return rc;
 }
Bool_t FairGeoInterface::createSet (FairGeoSet * pSet)
Definition at line 441 of file FairGeoInterface.cxx.
References FairGeoSet::create(), and geoBuilder.
 {
   // Creates the geometry of detector part
   if (!geoBuilder) { return kFALSE; }
   return pSet->create(geoBuilder);
 }
void FairGeoInterface::deleteSet (FairGeoSet * pSet)
Definition at line 253 of file FairGeoInterface.cxx.
References sets.
 {
   // Deletes the set
   if (pSet) {
     sets->Remove(pSet);
     delete pSet;
     pSet=0;
   }
 }
FairGeoSet * FairGeoInterface::findSet (const char * name)
Definition at line 191 of file FairGeoInterface.cxx.
References nSets, and sets.
Referenced by FairGeoAsciiIo::readDetectorSetup().
 {
   // Find the detector set in the actual setup
   FairGeoSet* pSet=0;
   TString setName(name);
   TString PSetName;
   setName.ToLower();
   Int_t l=setName.Last('/')+1;
   setName=setName(l,setName.Length()-l);
   /*  if (setName.Contains("cave"))        pSet=(FairGeoSet*)sets->At(kFairGeoCave);
     else if (setName.Contains("pipe"))   pSet=(FairGeoSet*)sets->At(kFairGeoPipe);
     else if (setName.Contains("target")) pSet=(FairGeoSet*)sets->At(kFairGeoTarget);
     else if (setName.Contains("magnet"))  pSet=(FairGeoSet*)sets->At(kFairGeoMagnet);
     else if (setName.Contains("rich"))   pSet=(FairGeoSet*)sets->At(kFairGeoRich);
     else if (setName.Contains("sts"))    pSet=(FairGeoSet*)sets->At(kFairGeoSts);
     else if (setName.Contains("trd"))    pSet=(FairGeoSet*)sets->At(kFairGeoTrd);
     else if (setName.Contains("tof"))    pSet=(FairGeoSet*)sets->At(kFairGeoTof);
     else if (setName.Contains("ecal")) pSet=(FairGeoSet*)sets->At(kFairGeoEcal);
     return pSet;
     */
   for(Int_t i=0; i<nSets; i++) {
     PSetName=sets->At(i)->GetName();
     if (PSetName.Contains(setName.Data())) {
       pSet=(FairGeoSet*)sets->At(i);
       cout << "FairGeoInterface::findSet" <<pSet->GetName() <<endl;
       break;
     }
   }
   return pSet;
 }
FairGeoIo* FairGeoInterface::getFileInput () inline
Definition at line 61 of file FairGeoInterface.h.
References fileInput.
 { return fileInput; }
TList* FairGeoInterface::getMasterNodes () inline
Definition at line 66 of file FairGeoInterface.h.
References masterNodes.
Referenced by FairGeoPipe::create().
 { return masterNodes; }
FairGeoMedia* FairGeoInterface::getMedia () inline
Definition at line 65 of file FairGeoInterface.h.
References media.
Referenced by FairModule::AssignMediumAtImport(), FairPipe::ConstructGeometry(), and FairMCApplication::ConstructOpGeometry().
 { return media; }
FairGeoIo* FairGeoInterface::getOraInput () inline
Definition at line 62 of file FairGeoInterface.h.
References oraInput.
Referenced by FairGeoAsciiIo::readGeomConfig().
 { return oraInput; }
FairGeoIo* FairGeoInterface::getOutput () inline
Definition at line 63 of file FairGeoInterface.h.
References output.
 { return output; }
FairGeoShapes* FairGeoInterface::getShapes () inline
Definition at line 64 of file FairGeoInterface.h.
References shapes.
 { return shapes; }
FairGeoInterface& FairGeoInterface::operator= (const FairGeoInterface &) private
void FairGeoInterface::print ()
Definition at line 448 of file FairGeoInterface.cxx.
References FairGeoSet::getGeomFile(), FairGeoMedia::list(), media, nSets, and sets.
 {
   // Prints the media and the list of detector parts
   media->list();
   cout<<"********************************************************************\n";
   cout<<"List of detector parts:\n";
   FairGeoSet* pSet=0;
   for(Int_t i=0; i<nSets; i++) {
     pSet=(FairGeoSet*)sets->At(i);
     if (pSet) { cout<<"  "<<pSet->GetName()<<":\t"<<pSet->getGeomFile()<<'\n'; }
   }
   cout<<"********************************************************************\n";
 }
Bool_t FairGeoInterface::readAll ()
Definition at line 291 of file FairGeoInterface.cxx.
References addInputFile(), nActualSets, nSets, oraInput, FairGeoIo::readGeomConfig(), readMedia(), readSet(), readSetupFile(), and sets.
 {
   // Reads the media and the whole geometry
   Bool_t rc=kTRUE;
   if (nActualSets==0&&oraInput) {
     rc=oraInput->readGeomConfig(this);
 //  if (rc) addInputFile("media_gdb");
     if (rc) { addInputFile("media_gdb"); }
   }
   if(rc) { rc=readSetupFile(); }
   if(rc) { rc=readMedia(); }
   FairGeoSet* pSet=0;
   for(Int_t i=0; i<nSets&&rc; i++) {
     pSet=(FairGeoSet*)sets->At(i);
     if (pSet) {
       cout<<"Read "<<pSet->GetName()<<endl;
       rc=readSet(pSet);
     }
   }
   return rc;
 }
Bool_t FairGeoInterface::readGeomConfig (const char * configFile)
Definition at line 462 of file FairGeoInterface.cxx.
References connectInput(), and FairGeoIo::readGeomConfig().
 {
   // Reads the GEANT configuration file
   Bool_t rc=kFALSE;
   FairGeoIo* input=0;
   if (configFile) {
     input=connectInput(configFile);
     if (input) { rc=input->readGeomConfig(this); }
   }
   return rc;
 }
Bool_t FairGeoInterface::readMedia ()
Definition at line 263 of file FairGeoInterface.cxx.
References connectInput(), FairGeoMedia::getInputFile(), media, and FairGeoIo::read().
Referenced by createGeometry(), and readAll().
 {
   // Reads the media
   Bool_t rc=kFALSE;
   FairGeoIo* input=connectInput(media->getInputFile());
   if (input) {
     rc=input->read(media);
   }
   return rc;
 }
Bool_t FairGeoInterface::readSet (FairGeoSet * pSet)
Definition at line 224 of file FairGeoInterface.cxx.
References connectInput(), FairGeoSet::getGeomFile(), media, and FairGeoIo::read().
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), createGeometry(), and readAll().
 {
   // Reads the geometry for the detector part
   Bool_t rc=kFALSE;
   FairGeoIo* input=0;
   if (pSet) {
     input=connectInput(pSet->getGeomFile());
     if (input) { rc=input->read(pSet,media); }
   }
   return rc;
 }
Bool_t FairGeoInterface::readSetupFile ()
Definition at line 474 of file FairGeoInterface.cxx.
References connectInput(), FairGeoAsciiIo::readDetectorSetup(), and setupFile.
Referenced by createGeometry(), and readAll().
 {
   // Reads the detector setups, needed for create only subsets
   Bool_t rc=kTRUE;
   if (setupFile.Length()>0) {
     FairGeoAsciiIo* input=(FairGeoAsciiIo*)(connectInput(setupFile));
     if (input) { rc=input->readDetectorSetup(this); }
   }
   return rc;
 }
void FairGeoInterface::setGeomBuilder (FairGeoBuilder * p) inline
Definition at line 60 of file FairGeoInterface.h.
Referenced by FairGeoLoader::FairGeoLoader().
 {geoBuilder=p;}
void FairGeoInterface::setMediaFile (const char * file)
Definition at line 113 of file FairGeoInterface.cxx.
References media, and FairGeoMedia::setInputFile().
 {
   media->setInputFile(file);
 }
void FairGeoInterface::SetNoOfSets (Int_t n) inline
Definition at line 87 of file FairGeoInterface.h.
Referenced by FairRunSim::Init().
 {nSets=n;} //
void FairGeoInterface::setOracleInput (FairGeoIo * p) inline
Definition at line 58 of file FairGeoInterface.h.
 {oraInput=p;}
void FairGeoInterface::setOutput (FairGeoIo * p) inline
Definition at line 59 of file FairGeoInterface.h.
 {output=p;}
Bool_t FairGeoInterface::writeAll ()
Definition at line 313 of file FairGeoInterface.cxx.
References nSets, sets, writeMedia(), and writeSet().
 {
   // Reads the media and the whole geometry to output
   Bool_t rc=kTRUE;
   FairGeoSet* pSet=0;
   rc=writeMedia();
   for(Int_t i=0; i<nSets&&rc; i++) {
     pSet=(FairGeoSet*)sets->At(i);
     if (pSet) { rc=writeSet(pSet); }
   }
   return rc;
 }
Bool_t FairGeoInterface::writeMedia ()
Definition at line 274 of file FairGeoInterface.cxx.
References connectOutput(), media, output, and FairGeoIo::write().
Referenced by writeAll().
 {
   // Writes the media to output
   if (connectOutput("media")) { return output->write(media); }
   return kFALSE;
 }
Bool_t FairGeoInterface::writeMedia (const char * filename)
Definition at line 281 of file FairGeoInterface.cxx.
References FairGeoIo::isOpen(), media, FairGeoIo::open(), output, and FairGeoIo::write().
 {
   // Writes the media to file
   if (output) {
     output->open(filename,"out");
     if (output->isOpen()) { return output->write(media); }
   }
   return kFALSE;
 }
Bool_t FairGeoInterface::writeSet (FairGeoSet * pSet)
Definition at line 236 of file FairGeoInterface.cxx.
References connectOutput(), output, and FairGeoIo::write().
Referenced by writeAll().
 {
   // Writes the geometry for the detector part to output
   if (pSet&&connectOutput(pSet->GetName())) { return output->write(pSet); }
   return kFALSE;
 }
Bool_t FairGeoInterface::writeSet (FairGeoSet * pSet, const char * filename)
Definition at line 243 of file FairGeoInterface.cxx.
References FairGeoIo::isOpen(), FairGeoIo::open(), output, and FairGeoIo::write().
 {
   // Writes the geometry for the detector part to file
   if (pSet&&output) {
     output->open(filename,"out");
     if (output->isOpen()) { return output->write(pSet); }
   }
   return kFALSE;
 }
Member Data Documentation
FairGeoIo* FairGeoInterface::fileInput private
Definition at line 44 of file FairGeoInterface.h.
Referenced by connectInput(), getFileInput(), and ~FairGeoInterface().
FairGeoBuilder* FairGeoInterface::geoBuilder private
file with detector setups (subsets)
Definition at line 54 of file FairGeoInterface.h.
Referenced by createAll(), createGeometry(), and createSet().
TList* FairGeoInterface::masterNodes private
list of shapes
Definition at line 52 of file FairGeoInterface.h.
Referenced by addGeoModule(), getMasterNodes(), and ~FairGeoInterface().
FairGeoMedia* FairGeoInterface::media private
array of geometry sets
Definition at line 50 of file FairGeoInterface.h.
Referenced by getMedia(), print(), readMedia(), readSet(), setMediaFile(), writeMedia(), and ~FairGeoInterface().
Int_t FairGeoInterface::nActualSets private
number of geometry sets (detector parts)
Definition at line 48 of file FairGeoInterface.h.
Referenced by addGeoModule(), createGeometry(), and readAll().
Int_t FairGeoInterface::nSets private
Oracle output
Definition at line 47 of file FairGeoInterface.h.
Referenced by createAll(), createGeometry(), findSet(), print(), readAll(), and writeAll().
FairGeoIo* FairGeoInterface::oraInput private
ASCII file I/O
Definition at line 45 of file FairGeoInterface.h.
Referenced by connectInput(), createGeometry(), getOraInput(), readAll(), and ~FairGeoInterface().
FairGeoIo* FairGeoInterface::output private
Oracle input
Definition at line 46 of file FairGeoInterface.h.
Referenced by connectOutput(), getOutput(), writeMedia(), writeSet(), and ~FairGeoInterface().
TObjArray* FairGeoInterface::sets private
number of set in actual geometry
Definition at line 49 of file FairGeoInterface.h.
Referenced by addGeoModule(), createAll(), createGeometry(), deleteSet(), findSet(), print(), readAll(), writeAll(), and ~FairGeoInterface().
TString FairGeoInterface::setupFile private
list of mother nodes used by several sets
Definition at line 53 of file FairGeoInterface.h.
Referenced by readSetupFile().
FairGeoShapes* FairGeoInterface::shapes private
list of media
Definition at line 51 of file FairGeoInterface.h.
Referenced by addGeoModule(), getShapes(), and ~FairGeoInterface().
The documentation for this class was generated from the following files:
FairGeoInterface.h
FairGeoInterface.cxx