FairRoot: TestDetectorProto Namespace Reference
TestDetectorProto Namespace Reference
Classes
class Digi
class DigiPayload
class Hit
class HitPayload
struct StaticDescriptorInitializer_FairTestDetectorPayload_2eproto
Functions
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
Variables
struct TestDetectorProto::StaticDescriptorInitializer_FairTestDetectorPayload_2eproto static_descriptor_initializer_FairTestDetectorPayload_2eproto_
Function Documentation
void TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References TestDetectorProto::Digi::default_instance_, TestDetectorProto::Hit::default_instance_, TestDetectorProto::DigiPayload::default_instance_, TestDetectorProto::HitPayload::default_instance_, TestDetectorProto::Digi::InitAsDefaultInstance(), TestDetectorProto::Hit::InitAsDefaultInstance(), TestDetectorProto::DigiPayload::InitAsDefaultInstance(), TestDetectorProto::HitPayload::InitAsDefaultInstance(), and protobuf_ShutdownFile_FairTestDetectorPayload_2eproto().
Referenced by protobuf_AssignDesc_FairTestDetectorPayload_2eproto(), and TestDetectorProto::StaticDescriptorInitializer_FairTestDetectorPayload_2eproto::StaticDescriptorInitializer_FairTestDetectorPayload_2eproto().
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void TestDetectorProto::protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References TestDetectorProto::Digi::default_instance_, TestDetectorProto::Hit::default_instance_, TestDetectorProto::DigiPayload::default_instance_, TestDetectorProto::HitPayload::default_instance_, and protobuf_AddDesc_FairTestDetectorPayload_2eproto().
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void TestDetectorProto::protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References TestDetectorProto::Digi::default_instance_, TestDetectorProto::Hit::default_instance_, TestDetectorProto::DigiPayload::default_instance_, and TestDetectorProto::HitPayload::default_instance_.
Referenced by protobuf_AddDesc_FairTestDetectorPayload_2eproto().
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
Variable Documentation
struct TestDetectorProto::StaticDescriptorInitializer_FairTestDetectorPayload_2eproto TestDetectorProto::static_descriptor_initializer_FairTestDetectorPayload_2eproto_