FairRoot: FairRadGridManager Class Reference
FairRadGridManager Class Reference
#include <FairRadGridManager.h>
Public Member Functions
FairRadGridManager ()
virtual ~FairRadGridManager ()
ClassDef (FairRadGridManager, 1)
TObjArray * GetMeshList ()
void AddMeshList (TObjArray *list)
Bool_t IsTrackInside (TLorentzVector &vec, FairMesh *aMesh)
Bool_t IsTrackEntering (TLorentzVector &vec1, TLorentzVector &vec2)
void FillMeshList ()
void Init ()
void Reset ()
Static Public Member Functions
static FairRadGridManager * Instance ()
Private Member Functions
FairRadGridManager (const FairRadGridManager &)
FairRadGridManager & operator= (const FairRadGridManager &)
Private Attributes
TClonesArray * fPointCollection
Int_t fTrackID
Int_t fVolumeID
TLorentzVector fPosIn
TLorentzVector fPosOut
TLorentzVector fMomIn
TLorentzVector fMomOut
Double_t fTime
Double_t fLength
Double_t fELoss
Float_t fA
Float_t fZmat
Float_t fDensity
Float_t fRadl
Float_t fAbsl
Int_t fEstimator
TObjArray * fMeshList
Static Private Attributes
static FairRadGridManager * fgInstance
static Double_t fLtmp
Detailed Description
Definition at line 33 of file FairRadGridManager.h.
Constructor & Destructor Documentation
FairRadGridManager::FairRadGridManager ()
Default constructor. Creates the singleton object of FairRadGridManager class. The pointer to this object can be reached via FairRadGridManager::Instance().
radiation length default ctor
Definition at line 37 of file FairRadGridManager.cxx.
References fgInstance, and fLtmp.
   : fPointCollection(NULL),
     fTrackID(0),
     fVolumeID(0),
     fPosIn(TLorentzVector(0,0,0,0)),
     fPosOut(TLorentzVector(0,0,0,0)),
     fMomIn(TLorentzVector(0,0,0,0)),
     fMomOut(TLorentzVector(0,0,0,0)),
     fTime(0),
     fLength(0),
     fELoss(0),
     fA(0),
     fZmat(0),
     fDensity(0),
     fRadl(0),
     fAbsl(0),
     fEstimator(0),
     fMeshList(NULL)
 {
   if(NULL == fgInstance) {
     fgInstance = this;
   }
   fLtmp=0;
 }
FairRadGridManager::~FairRadGridManager () virtual
Destructor.
radiation length default dtor
Definition at line 63 of file FairRadGridManager.cxx.
References fgInstance.
 {
   fgInstance = NULL;
 }
FairRadGridManager::FairRadGridManager (const FairRadGridManager &) private
Member Function Documentation
void FairRadGridManager::AddMeshList (TObjArray * list) inline
Definition at line 102 of file FairRadGridManager.h.
Referenced by FairMCApplication::AddMeshList().
{
       std::cout << " grid manag " << list->GetEntriesFast() << std::endl;
       fMeshList = list;
     }
FairRadGridManager::ClassDef (FairRadGridManager , 1)
Class definition.
void FairRadGridManager::FillMeshList ()
fill the 2D mesh
Add a point to the collection
Sum energy loss for all steps in the mesh
Definition at line 80 of file FairRadGridManager.cxx.
References fELoss, FairMesh::fillFluence(), FairMesh::fillSEU(), FairMesh::fillTID(), fLength, fMeshList, fMomIn, fMomOut, fPosIn, fPosOut, fTrackID, FairMesh::GetBinVolume(), FairMesh::GetDiag(), and IsTrackInside().
Referenced by FairMCApplication::Stepping().
 {
   TParticle* part = gMC->GetStack()->GetCurrentTrack();
   fTrackID = gMC->GetStack()->GetCurrentTrackNumber();
   gMC->TrackPosition(fPosIn);
   gMC->TrackMomentum(fMomIn);
   fELoss = 0.;
 //  Int_t MatId=  gMC->CurrentMaterial(fA, fZmat, fDensity, fRadl, fAbsl);
   for (Int_t i=0; i<fMeshList->GetEntriesFast(); i++ ) {
     FairMesh* aMesh = (FairMesh*) fMeshList->At(i);
     Double_t fBinVolume = aMesh->GetBinVolume();
     Double_t fDiag = aMesh->GetDiag();
     // Geometry bound test
     if ( IsTrackInside(fPosIn,aMesh) ) {
       fELoss = gMC->Edep();
       //cout << "-I- track (" << fTrackID << ")  is inside " << endl;
       //cout << " E deposited is " << fELoss << endl;
       gMC->TrackPosition(fPosOut);
       gMC->TrackMomentum(fMomOut);
       // Now cumulate fEloss (Gev/cm3)
       // and normalize it to the mesh volume
       // 1 estimator Edep
       fELoss = fELoss/fBinVolume;
       // 2 estimator TrackLengh
       fLength = gMC->TrackStep();
       // fill TID
       aMesh->fillTID(fPosOut.X(),fPosOut.Y(),fELoss);
       // fill total Fluence
       if ( fLength < 5*fDiag ) {
         fLength = fLength/fBinVolume;
         aMesh->fillFluence(fPosOut.X(),fPosOut.Y(),fLength);
         // fill SEU
         if ( part->P() > 0.02 ) {
           aMesh->fillSEU(fPosOut.X(),fPosOut.Y(),fLength);
         }
       }
     }
   }
 }
TObjArray* FairRadGridManager::GetMeshList () inline
Definition at line 101 of file FairRadGridManager.h.
References fMeshList.
Referenced by FairMCApplication::FinishRun().
 { return fMeshList; }
void FairRadGridManager::Init ()
initialize the manager
Definition at line 69 of file FairRadGridManager.cxx.
Referenced by FairMCApplication::InitGeometry().
 {
 //  fMeshList = new TObjArray();
 }
FairRadGridManager * FairRadGridManager::Instance () static
This function is used to access the methods of the class.
Returns
Pointer to the singleton FairRadGridManager object, created with FairRadGridManager::FairRadGridManager().
singelton instance
Definition at line 31 of file FairRadGridManager.cxx.
 {
   return fgInstance;
 }
Bool_t FairRadGridManager::IsTrackEntering (TLorentzVector & vec1, TLorentzVector & vec2)
Definition at line 132 of file FairRadGridManager.cxx.
 {
   // assume for the moment vertical scoring planes
   //    cout << " is entering diagnosis " << endl;
   //    cout << " Z pos " << pos.Z() << endl;
   //    cout << " Zmin "  << fZmin   << endl;
   //    cout << " diff "  << pos.Z()-fZmin   << endl;
   //    if (  (( TMath::Abs(pos.Z() - fZmin) ) < 1.0e-06 )
   //       &&
   //         ( mom.Z() > 0 )
   //      ) return kTRUE;
   //   else
   //     return kFALSE;
   return kFALSE;
 }
Bool_t FairRadGridManager::IsTrackInside (TLorentzVector & vec, FairMesh * aMesh)
Definition at line 152 of file FairRadGridManager.cxx.
References FairMesh::GetXmax(), FairMesh::GetXmin(), FairMesh::GetYmax(), FairMesh::GetYmin(), FairMesh::GetZmax(), and FairMesh::GetZmin().
Referenced by FillMeshList().
 {
   // check if inside volume
   if ( (pos.X() >= aMesh->GetXmin()) && (pos.X() <= aMesh->GetXmax())
        &&
        (pos.Y() >= aMesh->GetYmin()) && (pos.Y() <= aMesh->GetYmax())
        &&
        (pos.Z() >= aMesh->GetZmin()) && (pos.Z() <= aMesh->GetZmax())
      ) {
     /*       cout << " inside Xpos: " << pos.X() << " Xmin: " << aMesh->GetXmin()
           << " Xmax: " << aMesh->GetXmax()  << endl;
            cout << " inside Ypos: " << pos.Y() << " Ymin: " << aMesh->GetYmin()
           << " Ymax: " << aMesh->GetYmax() << endl;
            cout << " inside Zpos: " << pos.Z() << " Zmin: "
           << aMesh->GetZmin() << " Zmax: " << aMesh->GetZmax() << endl;
     */
     return kTRUE;
   } else {
     return kFALSE;
   }
 }
FairRadGridManager& FairRadGridManager::operator= (const FairRadGridManager &) private
void FairRadGridManager::Reset ()
reset
Definition at line 74 of file FairRadGridManager.cxx.
 {
   //  No free of memory ?
   //  fMesh->Reset();
 }
Member Data Documentation
Float_t FairRadGridManager::fA private
mass umber
Definition at line 84 of file FairRadGridManager.h.
Float_t FairRadGridManager::fAbsl private
absorption length
Definition at line 92 of file FairRadGridManager.h.
Float_t FairRadGridManager::fDensity private
density
Definition at line 88 of file FairRadGridManager.h.
Double_t FairRadGridManager::fELoss private
energy loss
Definition at line 82 of file FairRadGridManager.h.
Referenced by FillMeshList().
Int_t FairRadGridManager::fEstimator private
estimator
Definition at line 94 of file FairRadGridManager.h.
FairRadGridManager* FairRadGridManager::fgInstance static private
Definition at line 59 of file FairRadGridManager.h.
Referenced by FairRadGridManager(), and ~FairRadGridManager().
Double_t FairRadGridManager::fLength private
track length
Definition at line 80 of file FairRadGridManager.h.
Referenced by FillMeshList().
Double_t FairRadGridManager::fLtmp static private
Definition at line 98 of file FairRadGridManager.h.
Referenced by FairRadGridManager().
TObjArray* FairRadGridManager::fMeshList private
the mesh
Definition at line 96 of file FairRadGridManager.h.
Referenced by FillMeshList(), and GetMeshList().
TLorentzVector FairRadGridManager::fMomIn private
momentum in
Definition at line 74 of file FairRadGridManager.h.
Referenced by FillMeshList().
TLorentzVector FairRadGridManager::fMomOut private
momentum out
Definition at line 76 of file FairRadGridManager.h.
Referenced by FillMeshList().
TClonesArray* FairRadGridManager::fPointCollection private
collection of point
Definition at line 64 of file FairRadGridManager.h.
TLorentzVector FairRadGridManager::fPosIn private
entry position in global frame
Definition at line 70 of file FairRadGridManager.h.
Referenced by FillMeshList().
TLorentzVector FairRadGridManager::fPosOut private
exit position in global frame
Definition at line 72 of file FairRadGridManager.h.
Referenced by FillMeshList().
Float_t FairRadGridManager::fRadl private
radition length
Definition at line 90 of file FairRadGridManager.h.
Double_t FairRadGridManager::fTime private
track time
Definition at line 78 of file FairRadGridManager.h.
Int_t FairRadGridManager::fTrackID private
track index
Definition at line 66 of file FairRadGridManager.h.
Referenced by FillMeshList().
Int_t FairRadGridManager::fVolumeID private
volume id
Definition at line 68 of file FairRadGridManager.h.
Float_t FairRadGridManager::fZmat private
atomic number
Definition at line 86 of file FairRadGridManager.h.
The documentation for this class was generated from the following files:
FairRadGridManager.h
FairRadGridManager.cxx