FairRoot: FairRunOnline Class Reference
FairRunOnline Class Reference
#include <FairRunOnline.h>
Public Member Functions
virtual ~FairRunOnline ()
FairRunOnline ()
FairRunOnline (FairSource *source)
void Init ()
void Run (Int_t nev, Int_t dummy)
void Reinit (UInt_t runId)
UInt_t getRunId ()
FairField * GetField ()
void SetField (FairField *ffield)
void SetAutoFinish (Bool_t val)
void SetSource (FairSource *source)
void InitContainers ()
void SetContainerStatic (Bool_t tempBool=kTRUE)
Bool_t GetContainerStatic ()
void AddObject (TObject *object)
void SetGenerateHtml (Bool_t flag, const char *histFileName, Int_t refreshRate)
void Finish ()
FairSource * GetSource ()
virtual void AddTask (FairTask *t)
virtual void SetTask (FairTask *t)
void SetOutputFile (const char *fname)
void SetOutputFile (TFile *f)
void SetEventHeader (FairEventHeader *EvHeader)
FairRuntimeDb * GetRuntimeDb (void)
TFile * GetOutputFile ()
Int_t GetRunId ()
void SetRunId (UInt_t runId)
FairEventHeader * GetEventHeader ()
Bool_t IsAna ()
FairTask * GetTask (const char *taskName)
FairTask * GetMainTask ()
Int_t GetNTasks ()
void CreateGeometryFile (const char *geofile)
void SetWriteRunInfoFile (Bool_t write)
void SetGenerateRunInfo (Bool_t write)
Bool_t GetWriteRunInfoFile ()
Bool_t IsRunInfoGenerated ()
void SetUseFairLinks (Bool_t val)
Bool_t GetIsMaster () const
Static Public Member Functions
static FairRunOnline * Instance ()
Protected Member Functions
void WriteObjects ()
void GenerateHtml ()
Protected Attributes
Bool_t fIsInitialized
FairEventHeader * fEvtHeader
Bool_t fStatic
FairField * fField
FairSource * fSource
TFolder * fFolder
Bool_t fGenerateHtml
TString fHistFileName
Int_t fRefreshRate
Int_t fNevents
FairRuntimeDb * fRtdb
FairTask * fTask
const char * fOutname
FairRootManager * fRootManager
TFile * fOutFile
UInt_t fRunId
Bool_t fAna
FairEventHeader * fEvHead
FairFileHeader * fFileHeader
Bool_t fGenerateRunInfo
Bool_t fIsMaster
Static Protected Attributes
static FairRunOnline * fgRinstance = 0
static TMCThreadLocal FairRun * fRunInstance = 0
Private Member Functions
FairRunOnline (const FairRunOnline &M)
FairRunOnline & operator= (const FairRunOnline &)
Int_t EventLoop ()
Private Attributes
Bool_t fAutomaticFinish
Detailed Description
Definition at line 35 of file FairRunOnline.h.
Constructor & Destructor Documentation
FairRunOnline::~FairRunOnline () virtual
Definition at line 107 of file FairRunOnline.cxx.
References fField, fFolder, and fSource.
 {
   //  delete fFriendFileList;
   if (fField) {
     delete fField;
   }
   if (gGeoManager) {
     delete gGeoManager;
   }
   if(fSource) {
     delete fSource;
   }
   if(fFolder) {
     fFolder->Delete();
     delete fFolder;
   }
 }
FairRunOnline::FairRunOnline ()
Definition at line 67 of file FairRunOnline.cxx.
References FairLogger::endl(), FairRun::fAna, fgRinstance, INFO, and LOG.
   :FairRun(),
    fAutomaticFinish(kTRUE),
    fIsInitialized(kFALSE),
    fEvtHeader(0),
    fStatic(kFALSE),
    fField(0),
    fSource(NULL),
    fFolder(new TFolder("HISTO", "HISTO")),
    fGenerateHtml(kFALSE),
    fHistFileName(""),
    fRefreshRate(1000),
    fNevents(0)
 {
   fgRinstance = this;
   fAna = kTRUE;
   LOG(INFO) << "FairRunOnline constructed at " << this << FairLogger::endl;
 }
FairRunOnline::FairRunOnline (FairSource * source)
Definition at line 86 of file FairRunOnline.cxx.
References FairLogger::endl(), FairRun::fAna, fgRinstance, INFO, and LOG.
   :FairRun(),
    fAutomaticFinish(kTRUE),
    fIsInitialized(kFALSE),
    fEvtHeader(0),
    fStatic(kFALSE),
    fField(0),
    fSource(source),
    fFolder(new TFolder("HISTO", "HISTO")),
    fGenerateHtml(kFALSE),
    fHistFileName(""),
    fRefreshRate(1000),
    fNevents(0)
 {
   fgRinstance = this;
   fAna = kTRUE;
   LOG(INFO) << "FairRunOnline constructed at " << this << FairLogger::endl;
 }
FairRunOnline::FairRunOnline (const FairRunOnline & M) private
Member Function Documentation
void FairRunOnline::AddObject (TObject * object)
Definition at line 492 of file FairRunOnline.cxx.
References fFolder.
 {
   if(! fFolder) {
     return;
   }
   fFolder->Add(object);
 }
void FairRun::AddTask (FairTask * t) virtual inherited
Add a FAIRTask to the simulation or analysis
Definition at line 108 of file FairRun.cxx.
References FairFileHeader::AddTaskClassName(), FairRun::fFileHeader, FairRun::fNTasks, and FairRun::fTask.
Referenced by FairEventManager::AddTask().
 {
   fTask->Add(t);
   fNTasks++;
   fFileHeader->AddTaskClassName(t->ClassName());
 }
void FairRun::CreateGeometryFile (const char * geofile) inherited
Create a new file and save the TGeoManager to it
Definition at line 122 of file FairRun.cxx.
References FairRootManager::CreateGeometryFile(), and FairRun::fRootManager.
 {
   fRootManager->CreateGeometryFile(geofile);
 }
Int_t FairRunOnline::EventLoop () private
Main Event loop
Definition at line 261 of file FairRunOnline.cxx.
References FairRootManager::DeleteOldWriteoutBufferData(), fGenerateHtml, FairRootManager::Fill(), FairTask::FinishEvent(), fNevents, fRefreshRate, FairRun::fRootManager, FairRun::fRunId, fSource, FairRun::fTask, GenerateHtml(), FairRun::GetEventHeader(), FairRootManager::GetEventTime(), FairEventHeader::GetRunId(), gIsInterrupted, handler_ctrlc(), FairSource::ReadEvent(), FairSource::Reset(), FairRootManager::StoreWriteoutBufferData(), and WriteObjects().
Referenced by Run().
 {
   gSystem->IgnoreInterrupt();
   gIsInterrupted = kFALSE;
   signal(SIGINT, handler_ctrlc);
   fSource->Reset();
   Int_t status = fSource->ReadEvent();
   if(1 == status || 2 == status) {
     return status;
   }
   Int_t tmpId = GetEventHeader()->GetRunId();
   if ( tmpId != fRunId ) {
 //    LOG(INFO) << "Call Reinit due to changed RunID" << FairLogger::endl;
 //    fRunId = tmpId;
 //    Reinit( fRunId );
 //    fTask->ReInitTask();
   }
   fRootManager->StoreWriteoutBufferData(fRootManager->GetEventTime());
   fTask->ExecuteTask("");
   fRootManager->Fill();
   fRootManager->DeleteOldWriteoutBufferData();
   fTask->FinishEvent();
   fNevents += 1;
   if(fGenerateHtml && 0 == (fNevents%fRefreshRate))
   {
     WriteObjects();
     GenerateHtml();
   }
   if(gIsInterrupted)
   {
     return 1;
   }
   return 0;
 }
void FairRunOnline::Finish ()
Write last data to file, close input and output
Definition at line 350 of file FairRunOnline.cxx.
References FairSource::Close(), FairRootManager::CloseOutFile(), fGenerateHtml, FairTask::FinishTask(), FairRun::fRootManager, fSource, FairRun::fTask, GenerateHtml(), FairRootManager::LastFill(), FairRootManager::Write(), and WriteObjects().
Referenced by Run().
 {
   fTask->FinishTask();
   fRootManager->LastFill();
   fRootManager->Write();
   fSource->Close();
   if(fGenerateHtml) {
     WriteObjects();
     GenerateHtml();
   }
   fRootManager->CloseOutFile();
 }
void FairRunOnline::GenerateHtml () protected
Definition at line 378 of file FairRunOnline.cxx.
References fHistFileName.
Referenced by EventLoop(), and Finish().
 {
   TString htmlName = TString(fHistFileName);
   TString rootName = TString(fHistFileName);
   Int_t last = htmlName.Last('/');
   if(-1 != last) {
     rootName.Remove(0, last+1);
   }
   htmlName.Remove(htmlName.Length()-4, htmlName.Length()-1);
   htmlName += TString("html");
   std::ofstream* ofile = new std::ofstream(htmlName);
   (*ofile) << "<?xml version=\"1.0\" encoding=\"utf-8\"?>" << endl
            << "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"" << endl
            << "\"http://www.w3.org/TR/xhtml1/DTD/xhtml1transitional.dtd\">" << endl
            << "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">" << endl
            << "<head>" << endl
            << "<title>Read a ROOT file</title>" << endl
            << "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge; text/html\">" << endl
            << "<script type=\"text/javascript\" src=\"http://root.cern.ch/js/3.2/scripts/JSRootCore.js\"></script>" << endl
            << "</head>" << endl
            << "<body onload=\"JSROOT.BuildSimpleGUI()\">" << endl
            << "<div id=\"simpleGUI\"" << endl
            << "files=\"" << rootName << "\"></div>" << endl
            << "</body>" << endl
            << "</html>" << endl;
   ofile->close();
   delete ofile;
 }
Bool_t FairRunOnline::GetContainerStatic () inline
Definition at line 70 of file FairRunOnline.h.
References fStatic.
 { return fStatic; };
FairEventHeader * FairRun::GetEventHeader () inherited
Get the detector specific run header
Definition at line 134 of file FairRun.cxx.
References FairRun::fEvHead.
Referenced by EventLoop(), FairRunAnaProof::Init(), Init(), FairRunAna::Init(), and InitContainers().
 {
   if ( NULL == fEvHead ) {
     fEvHead = new FairEventHeader();
   }
   return fEvHead;
 }
FairField* FairRunOnline::GetField () inline virtual
Get the magnetic field
Implements FairRun.
Definition at line 52 of file FairRunOnline.h.
References fField.
 { return fField; }
Bool_t FairRun::GetIsMaster () const inline inherited
Definition at line 150 of file FairRun.h.
References FairRun::fIsMaster.
 { return fIsMaster;}
FairTask* FairRun::GetMainTask () inline inherited
Get Main Task
Definition at line 121 of file FairRun.h.
References FairRun::fTask.
{
       return fTask;
     }
Int_t FairRun::GetNTasks () inline inherited
Return the number of Tasks added to this Run
Definition at line 127 of file FairRun.h.
References FairRun::fNTasks.
{
       return fNTasks;
     }
TFile* FairRun::GetOutputFile () inline inherited
return a pointer to the output file
Definition at line 87 of file FairRun.h.
References FairRun::fOutFile.
{
       return fOutFile;
     }
UInt_t FairRunOnline::getRunId () inline
Definition at line 50 of file FairRunOnline.h.
References FairRun::fRunId.
 { return fRunId; }
Int_t FairRun::GetRunId () inline inherited
return the run ID for the actul run
Definition at line 93 of file FairRun.h.
References FairRun::fRunId.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairConstField::FillParContainer(), and FairMCApplication::InitGeometry().
                       {
       return ((Int_t) fRunId);
     }
FairRuntimeDb* FairRun::GetRuntimeDb (void) inline inherited
return a pointer to the RuntimeDB
Definition at line 81 of file FairRun.h.
References FairRun::fRtdb.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairPipe::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairConstField::FillParContainer(), FairRunAnaProof::Init(), FairRunAna::Init(), InitContainers(), FairRunAna::InitContainers(), FairTestDetector::Initialize(), FairTutorialDet2::Initialize(), NewDetector::Initialize(), FairRutherford::Initialize(), FairTutorialDet1::Initialize(), FairTutorialDet4::Initialize(), FairModule::ProcessNodes(), FairTutorialDet2Digitizer::ReInit(), FairTutorialDet4HitProducerIdealMisalign::ReInit(), FairDbTutAccessRtdbTask::SetParContainers(), FairTutorialDet2Digitizer::SetParContainers(), FairTutorialDet4HitProducerIdealMisalign::SetParContainers(), FairTutorialDet4::SetParContainers(), FairEventBuilderManager::SetParContainers(), MyFieldCreator::SetParm(), and FairMCApplication::SetParTask().
{
       return fRtdb;
     }
FairSource* FairRunOnline::GetSource () inline
Get a pointer to the attached FairSource
Definition at line 80 of file FairRunOnline.h.
References fSource.
 { return fSource; }
FairTask * FairRun::GetTask (const char * taskName) inherited
Get task by name
Definition at line 127 of file FairRun.cxx.
References FairRun::fTask.
 {
   TList* taskList = fTask->GetListOfTasks();
   TObject* task = taskList->FindObject(taskName);
   return dynamic_cast<FairTask*>(task);
 }
Bool_t FairRun::GetWriteRunInfoFile () inherited
Definition at line 156 of file FairRun.cxx.
References FairLogger::endl(), FairRun::fGenerateRunInfo, LOG, and WARNING.
 {
   LOG(WARNING) << "Function FairRun::GetWriteRunInfoFile() is depcrecated and will vanish in future versions of FairRoot.\n";
   LOG(WARNING) << "Please use FairRun::IsRunInfoGenerated() instead." << FairLogger::endl;
   return fGenerateRunInfo;
 }
void FairRunOnline::Init () virtual
initialize the run manager
Implements FairRun.
Definition at line 138 of file FairRunOnline.cxx.
References FairRuntimeDb::addRun(), FairLogger::endl(), FATAL, fEvtHeader, fField, FairRun::fFileHeader, fIsInitialized, FairRun::fOutFile, FairRun::fRootManager, FairRun::fRtdb, FairRun::fRunId, fSource, FairRun::fTask, FairRunIdGenerator::generateId(), FairRuntimeDb::getContainer(), FairRun::GetEventHeader(), FairRuntimeDb::getListOfContainers(), FairParSet::GetName(), INFO, FairSource::Init(), FairRuntimeDb::initContainers(), FairTask::InitTask(), Instance(), LOG, FairRootManager::Register(), FairParSet::setChanged(), FairBaseParSet::SetContListStr(), FairGeoParSet::SetGeometry(), FairParSet::setInputVersion(), FairRootManager::SetOutTree(), FairTask::SetParTask(), FairFileHeader::SetRunId(), FairEventHeader::SetRunId(), FairRootManager::TruncateBranchNames(), FairRootManager::WriteFileHeader(), and FairRootManager::WriteFolder().
 {
   LOG(INFO)<<"FairRunOnline::Init"<<FairLogger::endl;
   if (fIsInitialized) {
     LOG(FATAL) << "Error Init is already called before!" << FairLogger::endl;
     exit(-1);
   } else {
     fIsInitialized = kTRUE;
   }
   //  FairGeoLoader* loader = new FairGeoLoader("TGeo", "Geo Loader");
   //  FairGeoInterface* GeoInterFace = loader->getGeoInterface();
   //  GeoInterFace->SetNoOfSets(ListOfModules->GetEntries());
   //  GeoInterFace->setMediaFile(MatFname.Data());
   //  GeoInterFace->readMedia();
   // Add a Generated run ID to the FairRunTimeDb
   FairRunIdGenerator genid;
   fRunId = genid.generateId();
   fRtdb->addRun(fRunId);
   fFileHeader->SetRunId(fRunId);
   FairBaseParSet* par = dynamic_cast<FairBaseParSet*>(fRtdb->getContainer("FairBaseParSet"));
   FairGeoParSet* geopar = dynamic_cast<FairGeoParSet*>(fRtdb->getContainer("FairGeoParSet"));
   if (geopar) {
     geopar->SetGeometry(gGeoManager);
   }
   if(fField) {
     fField->Init();
     fField->FillParContainer();
   }
   TList* containerList = fRtdb->getListOfContainers();
   TIter next(containerList);
   FairParSet* cont;
   TObjArray* ContList= new TObjArray();
   while ((cont=dynamic_cast<FairParSet*>(next()))) {
     ContList->Add(new TObjString(cont->GetName()));
   }
   if (par) {
     par->SetContListStr(ContList);
     par->setChanged();
     par->setInputVersion(fRunId,1);
   }
   if (geopar) {
     geopar->setChanged();
     geopar->setInputVersion(fRunId,1);
   }
 fRootManager->WriteFileHeader(fFileHeader);
   fTask->SetParTask();
   fRtdb->initContainers(fRunId);
   //  InitContainers();
   // --- Get event header from Run
   fEvtHeader = dynamic_cast<FairEventHeader*> (FairRunOnline::Instance()->GetEventHeader());
   if ( ! fEvtHeader ) {
     LOG(FATAL) << "FairRunOnline::InitContainers:No event header in run!" << FairLogger::endl;
     return;
   }
   LOG(INFO) << "FairRunOnline::InitContainers: event header at " << fEvtHeader << FairLogger::endl;
   fRootManager->Register("EventHeader.", "Event", fEvtHeader, kTRUE);
   fEvtHeader->SetRunId(fRunId);
   // Initialize the source
   if(! fSource->Init()) {
     LOG(FATAL) << "Initialization of data source failed!"
                << FairLogger::endl;
     exit(-1);
   }
   // Now call the User initialize for Tasks
   fTask->InitTask();
   // create the output tree after tasks initialisation
   fOutFile->cd();
   TTree* outTree =new TTree("cbmsim", "/cbmout", 99);
   fRootManager->TruncateBranchNames(outTree, "cbmout");
   fRootManager->SetOutTree(outTree);
   fRootManager->WriteFolder();
 }
void FairRunOnline::InitContainers ()
Initialization of parameter container is set to static, i.e: the run id is is not checked anymore after initializationInit containers executed on PROOF, which is part of Init when running locally
Definition at line 222 of file FairRunOnline.cxx.
References FairLogger::endl(), FATAL, fEvtHeader, FairRun::fRootManager, FairRun::fRtdb, FairRun::fRunId, FairRun::fTask, FairRuntimeDb::getContainer(), FairRun::GetEventHeader(), FairRootManager::GetObjectFromInTree(), FairEventHeader::GetRunId(), FairRun::GetRuntimeDb(), INFO, FairRuntimeDb::initContainers(), Instance(), LOG, FairEventHeader::Register(), FairRootManager::Register(), FairTask::ReInitTask(), and WARNING.
 {
   fRtdb = GetRuntimeDb();
   FairBaseParSet* par=(FairBaseParSet*)
                       (fRtdb->getContainer("FairBaseParSet"));
   LOG(INFO) << "FairRunOnline::InitContainers: par = " << par << FairLogger::endl;
   if (NULL == par)
     LOG(WARNING)<<"FairRunOnline::InitContainers: no  'FairBaseParSet' container !"<<FairLogger::endl;
   if (par) {
     fEvtHeader = (FairEventHeader*)fRootManager->GetObjectFromInTree("EventHeader.");
     fRunId = fEvtHeader->GetRunId();
     //Copy the Event Header Info to Output
     fEvtHeader->Register();
     // Init the containers in Tasks
     fRtdb->initContainers(fRunId);
     fTask->ReInitTask();
     //    fTask->SetParTask();
     fRtdb->initContainers( fRunId );
     //     if (gGeoManager==0) {
     //       par->GetGeometry();
     //     }
   } else
   {
   // --- Get event header from Run
   fEvtHeader = dynamic_cast<FairEventHeader*> (FairRunOnline::Instance()->GetEventHeader());
   if ( ! fEvtHeader ) {
     LOG(FATAL) << "FairRunOnline::InitContainers:No event header in run!" << FairLogger::endl;
     return;
   }
   LOG(INFO) << "FairRunOnline::InitContainers: event header at " << fEvtHeader << FairLogger::endl;
   fRootManager->Register("EventHeader.", "Event", fEvtHeader, kTRUE);
   }
 }
FairRunOnline * FairRunOnline::Instance () static
Definition at line 61 of file FairRunOnline.cxx.
References fgRinstance.
Referenced by Init(), and InitContainers().
 {
   return fgRinstance;
 }
Bool_t FairRun::IsAna () inline inherited
return true for Anaylsis session
Definition at line 110 of file FairRun.h.
References FairRun::fAna.
Referenced by FairRootManager::OpenOutFile().
{
       return fAna;
     }
Bool_t FairRun::IsRunInfoGenerated () inline inherited
Definition at line 144 of file FairRun.h.
References FairRun::fGenerateRunInfo.
 { return fGenerateRunInfo;}
FairRunOnline& FairRunOnline::operator= (const FairRunOnline &) inline private
Definition at line 87 of file FairRunOnline.h.
 { return *this; }
void FairRunOnline::Reinit (UInt_t runId)
Definition at line 466 of file FairRunOnline.cxx.
References FairRun::fRtdb, and FairRuntimeDb::initContainers().
 {
   // reinit procedure
   fRtdb->initContainers( runId );
 }
void FairRunOnline::Run (Int_t nev, Int_t dummy) virtual
Run for the given number of events
Implements FairRun.
Definition at line 306 of file FairRunOnline.cxx.
References EventLoop(), fAutomaticFinish, Finish(), fNevents, FairRun::fOutFile, FairRun::fRootManager, gIsInterrupted, and FairRootManager::StoreAllWriteoutBufferData().
 {
   fOutFile->cd();
   fNevents = 0;
   Int_t status;
   if(nev < 0) {
     while(kTRUE) {
       status = EventLoop();
       if(1 == status) {
         break;
       } else if(2 == status) {
         continue;
       }
       if(gIsInterrupted)
       {
         break;
       }
     }
   } else {
     for (Int_t i = 0; i < nev; i++) {
       status = EventLoop();
       if(1 == status) {
         break;
       } else if(2 == status) {
         i -= 1;
         continue;
       }
       if(gIsInterrupted)
       {
         break;
       }
     }
   }
   fRootManager->StoreAllWriteoutBufferData();
   if (fAutomaticFinish) {
     Finish();
   }
 }
void FairRunOnline::SetAutoFinish (Bool_t val) inline
Set if the run should be closed automatically after executing the run functuion
Definition at line 59 of file FairRunOnline.h.
References fAutomaticFinish.
 { fAutomaticFinish = val; }
void FairRunOnline::SetContainerStatic (Bool_t tempBool = kTRUE)
Definition at line 476 of file FairRunOnline.cxx.
References FairLogger::endl(), fStatic, INFO, and LOG.
 {
   fStatic=tempBool;
   if ( fStatic ) {
     LOG(INFO) << "Parameter Cont. initialisation is static"
               << FairLogger::endl;
   } else {
     LOG(INFO) << "Parameter Cont. initialisation is NOT static"
               << FairLogger::endl;
   }
 }
void FairRun::SetEventHeader (FairEventHeader * EvHeader) inline inherited
Set the experiment dependent run header for each run
Definition at line 75 of file FairRun.h.
References FairRun::fEvHead.
{
       fEvHead=EvHeader;
     }
void FairRunOnline::SetField (FairField * ffield) inline
Set the magnetic Field
Definition at line 54 of file FairRunOnline.h.
References fField.
 { fField = ffield; }
void FairRunOnline::SetGenerateHtml (Bool_t flag, const char * histFileName, Int_t refreshRate)
Definition at line 367 of file FairRunOnline.cxx.
References fGenerateHtml, fHistFileName, and fRefreshRate.
 {
   fGenerateHtml = flag;
   fHistFileName = TString(histFileName);
   fRefreshRate = refreshRate;
 }
void FairRun::SetGenerateRunInfo (Bool_t write) inline inherited
Definition at line 138 of file FairRun.h.
References FairRun::fGenerateRunInfo.
 { fGenerateRunInfo = write;}
void FairRun::SetOutputFile (const char * fname) inherited
Set the output file name for analysis or simulation
Definition at line 87 of file FairRun.cxx.
References FairRun::fOutFile, FairRun::fOutname, FairRun::fRootManager, and FairRootManager::OpenOutFile().
Referenced by FairMCApplication::CloneForWorker().
 {
   fOutname=fname;
   if (fRootManager) fOutFile = fRootManager->OpenOutFile(fOutname);
 }
void FairRun::SetOutputFile (TFile * f) inherited
Set the output file for analysis or simulation
Definition at line 96 of file FairRun.cxx.
References FairRun::fOutFile, FairRun::fOutname, FairRun::fRootManager, and FairRootManager::OpenOutFile().
 {
   if (! fRootManager) return;
   fOutname=f->GetName();
   fRootManager->OpenOutFile(f);
   fOutFile = f;
 }
void FairRun::SetRunId (UInt_t runId) inline inherited
Set the Run ID
Definition at line 100 of file FairRun.h.
References FairRun::fRunId.
         {
           fRunId = runId;
     }
void FairRunOnline::SetSource (FairSource * source) inline
Set the source which should be used
Definition at line 61 of file FairRunOnline.h.
References fSource.
 { fSource = source; }
void FairRun::SetTask (FairTask * t) virtual inherited
Definition at line 115 of file FairRun.cxx.
References FairFileHeader::AddTaskClassName(), FairRun::fFileHeader, and FairRun::fTask.
 {
   if ( fTask ) { delete fTask; }
   fTask = t;
   fFileHeader->AddTaskClassName(t->ClassName());
 }
void FairRun::SetUseFairLinks (Bool_t val) inherited
Definition at line 142 of file FairRun.cxx.
References FairRun::fRootManager, and FairRootManager::SetUseFairLinks().
 {
         fRootManager->SetUseFairLinks(val);
 }
void FairRun::SetWriteRunInfoFile (Bool_t write) inherited
Definition at line 148 of file FairRun.cxx.
References FairLogger::endl(), FairRun::fGenerateRunInfo, LOG, and WARNING.
 {
   LOG(WARNING) << "Function FairRun::SetWriteRunInfoFile(Bool_t) is depcrecated and will vanish in future versions of FairRoot.\n";
   LOG(WARNING) << "Please use FairRun::SetGenerateRunInfo(Bool_t) instead." << FairLogger::endl;
   fGenerateRunInfo = write;
 }
void FairRunOnline::WriteObjects () protected
Definition at line 412 of file FairRunOnline.cxx.
References fFolder, and fHistFileName.
Referenced by EventLoop(), and Finish().
 {
   TDirectory *oldDir = gDirectory;
   TFile *file = new TFile(fHistFileName, "RECREATE");
   // Create iterator with the folder content
   TIter iter(fFolder->GetListOfFolders());
   // Pointer to an object
   TObject* object;
   // Class name of the object
   TString className;
   // Histogram pointers
   TH1* h1;
   TH2* h2;
   // Loop over objects in the folder
   while((object = iter())) {
     // Get class name
     className = object->ClassName();
     // Recognise objects
     if(0 == className.CompareTo("TH1F")) {
       // If a histogram - plot it and save canvas
       h1 = (TH1F*) object;
       h1->Write();
     } else if(0 == className.CompareTo("TH2F")) {
       // If a histogram - plot it and save canvas
       h2 = (TH2F*) object;
       h2->Write();
     } else if(0 == className.CompareTo("TH1D")) {
       // If a histogram - plot it and save canvas
       h1 = (TH1D*) object;
       h1->Write();
     } else if(0 == className.CompareTo("TH2D")) {
       // If a histogram - plot it and save canvas
       h2 = (TH2D*) object;
       h2->Write();
     }
   }
   file->Close();
   oldDir->cd();
 }
Member Data Documentation
Bool_t FairRun::fAna protected inherited
true for Anaylsis session
Definition at line 181 of file FairRun.h.
Referenced by FairRunAna::FairRunAna(), FairRunAnaProof::FairRunAnaProof(), FairRunOnline(), and FairRun::IsAna().
Bool_t FairRunOnline::fAutomaticFinish private
Definition at line 84 of file FairRunOnline.h.
Referenced by Run(), and SetAutoFinish().
FairEventHeader* FairRun::fEvHead protected inherited
MC Event Header
Definition at line 183 of file FairRun.h.
Referenced by FairRun::GetEventHeader(), FairRun::SetEventHeader(), and FairRun::~FairRun().
FairEventHeader* FairRunOnline::fEvtHeader protected
Definition at line 96 of file FairRunOnline.h.
Referenced by Init(), and InitContainers().
FairField* FairRunOnline::fField protected
Definition at line 99 of file FairRunOnline.h.
Referenced by GetField(), Init(), SetField(), and ~FairRunOnline().
FairFileHeader* FairRun::fFileHeader protected inherited
File Header
Definition at line 185 of file FairRun.h.
Referenced by FairRun::AddTask(), FairRun::FairRun(), FairRunAnaProof::Init(), Init(), FairRunAna::Init(), FairRunSim::Init(), and FairRun::SetTask().
TFolder* FairRunOnline::fFolder protected
Definition at line 102 of file FairRunOnline.h.
Referenced by AddObject(), WriteObjects(), and ~FairRunOnline().
Bool_t FairRunOnline::fGenerateHtml protected
Definition at line 103 of file FairRunOnline.h.
Referenced by EventLoop(), Finish(), and SetGenerateHtml().
Bool_t FairRun::fGenerateRunInfo protected inherited
true if RunInfo file should be written
Definition at line 187 of file FairRun.h.
Referenced by FairRun::GetWriteRunInfoFile(), FairRun::IsRunInfoGenerated(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRun::SetGenerateRunInfo(), and FairRun::SetWriteRunInfoFile().
FairRunOnline * FairRunOnline::fgRinstance = 0 static protected
Definition at line 95 of file FairRunOnline.h.
Referenced by FairRunOnline(), and Instance().
TString FairRunOnline::fHistFileName protected
Definition at line 104 of file FairRunOnline.h.
Referenced by GenerateHtml(), SetGenerateHtml(), and WriteObjects().
Bool_t FairRunOnline::fIsInitialized protected
This variable became true after Init is called
Definition at line 94 of file FairRunOnline.h.
Referenced by Init().
Bool_t FairRun::fIsMaster protected inherited
true if on master
Definition at line 189 of file FairRun.h.
Referenced by FairRun::GetIsMaster().
Int_t FairRunOnline::fNevents protected
Definition at line 106 of file FairRunOnline.h.
Referenced by EventLoop(), and Run().
TFile* FairRun::fOutFile protected inherited
Output file
Definition at line 177 of file FairRun.h.
Referenced by FairRun::GetOutputFile(), FairRunAnaProof::Init(), FairRunAna::Init(), Init(), Run(), and FairRun::SetOutputFile().
const char* FairRun::fOutname protected inherited
Output file name
Definition at line 173 of file FairRun.h.
Referenced by FairRun::SetOutputFile().
Int_t FairRunOnline::fRefreshRate protected
Definition at line 105 of file FairRunOnline.h.
Referenced by EventLoop(), and SetGenerateHtml().
FairRootManager* FairRun::fRootManager protected inherited
IO manager
Definition at line 175 of file FairRun.h.
Referenced by FairRunAna::AddBackgroundFile(), FairRunAna::AddFile(), FairRunAna::AddFriend(), FairRunAna::AddSignalFile(), FairRunAna::BGWindowWidthNo(), FairRunAna::BGWindowWidthTime(), FairRunAna::CompressData(), FairRun::CreateGeometryFile(), FairRunAna::DummyRun(), EventLoop(), FairRun::FairRun(), Finish(), FairRunAnaProof::Init(), Init(), FairRunAna::Init(), FairRunSim::Init(), InitContainers(), FairRunAna::InitContainers(), Run(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAnaProof::RunOnProof(), FairRunAna::RunTSBuffers(), FairRunAna::RunWithTimeStamps(), FairRunAna::SetBackgroundFile(), FairRunAna::SetBeamTime(), FairRunAna::SetEventMeanTime(), FairRunAna::SetEventTimeInterval(), FairRunAna::SetInputFile(), FairRunAnaProof::SetInTree(), FairRunAna::SetMixAllInputs(), FairRun::SetOutputFile(), FairRunAna::SetSignalFile(), FairRun::SetUseFairLinks(), FairRunAna::TerminateRun(), and FairRun::~FairRun().
FairRuntimeDb* FairRun::fRtdb protected inherited
RuntimeDb
Definition at line 169 of file FairRun.h.
Referenced by FairRun::GetRuntimeDb(), FairRunAnaProof::Init(), FairRunAna::Init(), Init(), FairRunSim::Init(), InitContainers(), FairRunAna::InitContainers(), Reinit(), FairRunAna::Reinit(), FairRunAnaProof::RunOnProof(), and FairRun::~FairRun().
UInt_t FairRun::fRunId protected inherited
Run Id
Definition at line 179 of file FairRun.h.
Referenced by EventLoop(), getRunId(), FairRunAna::getRunId(), FairRun::GetRunId(), FairRunAnaProof::Init(), Init(), FairRunAna::Init(), FairRunSim::Init(), InitContainers(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), and FairRun::SetRunId().
TMCThreadLocal FairRun * FairRun::fRunInstance = 0 static protected inherited
static pointer to this run
Definition at line 164 of file FairRun.h.
Referenced by FairRun::FairRun(), and FairRun::Instance().
FairSource* FairRunOnline::fSource protected
Definition at line 101 of file FairRunOnline.h.
Referenced by EventLoop(), Finish(), GetSource(), Init(), SetSource(), and ~FairRunOnline().
Bool_t FairRunOnline::fStatic protected
true for static initialisation of parameters
Definition at line 98 of file FairRunOnline.h.
Referenced by GetContainerStatic(), and SetContainerStatic().
FairTask* FairRun::fTask protected inherited
Tasks used
Definition at line 171 of file FairRun.h.
Referenced by FairRun::AddTask(), FairRunAna::DummyRun(), EventLoop(), Finish(), FairRun::GetMainTask(), FairRun::GetTask(), FairRunAnaProof::Init(), Init(), FairRunAna::Init(), FairRunSim::Init(), InitContainers(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAnaProof::RunOnProof(), FairRunAna::RunTSBuffers(), FairRun::SetTask(), FairRunAna::TerminateRun(), and FairRun::~FairRun().
The documentation for this class was generated from the following files:
FairRunOnline.h
FairRunOnline.cxx