FairRroot: FairRecoEventHeader Class Reference
FairRecoEventHeader Class Reference
#include <FairRecoEventHeader.h>
Public Member Functions
FairRecoEventHeader ()
UInt_t GetRunId () const
Double_t GetEventTime () const
Double_t GetEventTimeError () const
Int_t GetIdentifier () const
void SetRunId (UInt_t runid)
void SetEventTime (Double_t time, Double_t terr)
void SetIdentifier (Int_t ident)
virtual bool operator< (const FairRecoEventHeader &tempObj) const
virtual bool operator> (const FairRecoEventHeader &tempObj) const
virtual bool operator== (const FairRecoEventHeader &tempObj) const
virtual ~FairRecoEventHeader ()
Protected Attributes
UInt_t fRunId
Int_t fIdentifier
Double_t fEventTime
Double_t fEventTimeError
Detailed Description
Event Header Class
Author
D.Bertini d.ber.nosp@m.tini.nosp@m.@gsi..nosp@m.de
M.Al-Turany m.al-.nosp@m.tura.nosp@m.ny@gs.nosp@m.i.de
R.Karabowicz r.kar.nosp@m.abow.nosp@m.icz@g.nosp@m.si.d.nosp@m.e
Definition at line 25 of file FairRecoEventHeader.h.
Constructor & Destructor Documentation
FairRecoEventHeader::FairRecoEventHeader ()
Default constructor
Definition at line 17 of file FairRecoEventHeader.cxx.
   :fRunId(0),
    fIdentifier(0),
    fEventTime(-1.),
    fEventTimeError(-1.)
 {
 }
FairRecoEventHeader::~FairRecoEventHeader () virtual
Destructor
Definition at line 26 of file FairRecoEventHeader.cxx.
 { }
Member Function Documentation
Double_t FairRecoEventHeader::GetEventTime () const inline
Get the MC time for this event
Definition at line 39 of file FairRecoEventHeader.h.
References fEventTime.
Referenced by operator<(), operator==(), and operator>().
{
       return fEventTime;
     }
Double_t FairRecoEventHeader::GetEventTimeError () const inline
Get the error of MC time for this event
Definition at line 44 of file FairRecoEventHeader.h.
References fEventTimeError.
{
       return fEventTimeError;
     }
Int_t FairRecoEventHeader::GetIdentifier () const inline
Get identifier
Definition at line 49 of file FairRecoEventHeader.h.
References fIdentifier.
{
       return fIdentifier;
     }
UInt_t FairRecoEventHeader::GetRunId () const inline
Get the run ID for this run
Definition at line 34 of file FairRecoEventHeader.h.
References fRunId.
{
       return fRunId;
     }
virtual bool FairRecoEventHeader::operator< (const FairRecoEventHeader & tempObj) const inline virtual
Definition at line 76 of file FairRecoEventHeader.h.
References fEventTime, and GetEventTime().
{
       if (fEventTime < tempObj.GetEventTime()) { return true; }
       else if (fEventTime > tempObj.GetEventTime()) { return false; }
       return false;
     }
virtual bool FairRecoEventHeader::operator== (const FairRecoEventHeader & tempObj) const inline virtual
Definition at line 88 of file FairRecoEventHeader.h.
References fEventTime, and GetEventTime().
{
       if   (fEventTime == tempObj.GetEventTime() ) {
         return true;
       }
       return false;
     }
virtual bool FairRecoEventHeader::operator> (const FairRecoEventHeader & tempObj) const inline virtual
Definition at line 82 of file FairRecoEventHeader.h.
References fEventTime, and GetEventTime().
{
       if (fEventTime > tempObj.GetEventTime()) { return true; }
       else if (fEventTime < tempObj.GetEventTime()) { return false; }
       return false;
     }
void FairRecoEventHeader::SetEventTime (Double_t time, Double_t terr) inline
Set the MC time for this event
Parameters
time : time in ns
terr : time error in ns
Definition at line 64 of file FairRecoEventHeader.h.
References fEventTime, and fEventTimeError.
{
       fEventTime=time;
       fEventTimeError=terr;
     }
void FairRecoEventHeader::SetIdentifier (Int_t ident) inline
Set the run ID for this run
Parameters
ident : identifier
Definition at line 72 of file FairRecoEventHeader.h.
References fIdentifier.
{
       fIdentifier=ident;
     }
void FairRecoEventHeader::SetRunId (UInt_t runid) inline
Set the run ID for this run
Parameters
runid : unique run id
Definition at line 56 of file FairRecoEventHeader.h.
References fRunId.
{
       fRunId=runid;
     }
Member Data Documentation
Double_t FairRecoEventHeader::fEventTime protected
Event Time
Definition at line 107 of file FairRecoEventHeader.h.
Referenced by GetEventTime(), operator<(), operator==(), operator>(), and SetEventTime().
Double_t FairRecoEventHeader::fEventTimeError protected
Event Time Error
Definition at line 109 of file FairRecoEventHeader.h.
Referenced by GetEventTimeError(), and SetEventTime().
Int_t FairRecoEventHeader::fIdentifier protected
Identifier
Definition at line 105 of file FairRecoEventHeader.h.
Referenced by GetIdentifier(), and SetIdentifier().
UInt_t FairRecoEventHeader::fRunId protected
Run Id
Definition at line 103 of file FairRecoEventHeader.h.
Referenced by GetRunId(), and SetRunId().
The documentation for this class was generated from the following files:
FairRecoEventHeader.h
FairRecoEventHeader.cxx