FairRoot: FairRunInfo Class Reference
FairRunInfo Class Reference
#include <FairRunInfo.h>
Public Member Functions
FairRunInfo ()
~FairRunInfo ()
void StoreInfo ()
void WriteInfo ()
void Reset ()
Private Member Functions
void CalculateTimeDifference ()
void PrintInfo ()
void GetInfo ()
void CreateAndFillHistograms (TList *histoList)
void WriteHistosToFile (TList *histoList)
FairRunInfo (const FairRunInfo &)
FairRunInfo & operator= (const FairRunInfo &)
Private Attributes
TTimeStamp fTimeStamp
CpuInfo_t fCpuInfo
MemInfo_t fMemInfo
ProcInfo_t fProcInfo
std::vector< Double_t > fTimeDiff
std::vector< Double_t > fTime
std::vector< Long_t > fResidentMemory
std::vector< Long_t > fVirtualMemory
FairLogger * fLogger
Detailed Description
Definition at line 22 of file FairRunInfo.h.
Constructor & Destructor Documentation
FairRunInfo::FairRunInfo ()
FairRunInfo::~FairRunInfo ()
Definition at line 39 of file FairRunInfo.cxx.
 {
 }
FairRunInfo::FairRunInfo (const FairRunInfo &) private
Member Function Documentation
void FairRunInfo::CalculateTimeDifference () private
Definition at line 70 of file FairRunInfo.cxx.
References fTime, and fTimeDiff.
Referenced by StoreInfo().
 {
   // Calculates the time difference between now and the last call
   Int_t lastElement = fTime.size()-1;
   fTimeDiff.push_back( fTime.at(lastElement) -
                        fTime.at(lastElement-1) );
 }
void FairRunInfo::CreateAndFillHistograms (TList * histoList) private
Definition at line 98 of file FairRunInfo.cxx.
References fResidentMemory, fTime, fTimeDiff, and fVirtualMemory.
Referenced by WriteInfo().
 {
   Int_t entries = fTime.size();
   Double_t timePeriod = fTime.back()-fTime.front();
   TH1F* ResidentMemoryVsEvent = new TH1F("ResidentMemoryVsEvent","Resident Memory as function of Eventnumber;Event;Memory [MB]",entries, 0, entries);
   TH1F* VirtualMemoryVsEvent = new TH1F("VirtualMemoryVsEvent","Virtual Memory as function of Eventnumber;Event;Memory [MB]",entries, 0, entries);
   TH1F* ResidentMemoryVsTime = new TH1F("ResidentMemoryVsTime","Resident memory as function of Runtime;Time [s];Memory [MB]",(Int_t)(timePeriod*10), 0, (Int_t)timePeriod);
   TH1F* VirtualMemoryVsTime = new TH1F("VirtualMemoryVsTime","Virtual memory as function of Runtime;Time [s];Memory [MB]",(Int_t)(timePeriod*10), 0, (Int_t)timePeriod);
   TH1F* EventtimeVsEvent = new TH1F("EventtimeVsEvent","Runtime per Event as function of Event number;Event;Time [s]",entries-1, 1, entries);
   std::vector<Double_t> timeDiffSorted(fTimeDiff);
   std::vector<Double_t>::iterator it;
   std::sort(timeDiffSorted.begin(), timeDiffSorted.end());
   Double_t minTime = timeDiffSorted.front();
   Double_t maxTime = timeDiffSorted.back();
   timePeriod = maxTime - minTime;
   TH1F* TimePerEvent = new TH1F("TimePerEvent","Runtime;Time [s];Events",(Int_t)((timePeriod+20)*10), (Int_t)minTime-10, (Int_t)maxTime+10);
   Int_t counter = 0;
   std::vector<Long_t>::iterator lit;
   Double_t timeOffset = fTime.front()+1.;
   for(lit=fResidentMemory.begin(); lit<fResidentMemory.end(); lit++) {
     ResidentMemoryVsEvent->Fill(counter, *lit);
     ResidentMemoryVsTime->Fill(fTime.at(counter)-timeOffset, *lit);
     counter++;
   }
   histoList->AddLast(ResidentMemoryVsEvent);
   histoList->AddLast(ResidentMemoryVsTime);
   counter = 0;
   for(lit=fVirtualMemory.begin(); lit<fVirtualMemory.end(); lit++) {
     VirtualMemoryVsEvent->Fill(counter, *lit);
     VirtualMemoryVsTime->Fill(fTime.at(counter)-timeOffset, *lit);
     counter++;
   }
   histoList->AddLast(VirtualMemoryVsEvent);
   histoList->AddLast(VirtualMemoryVsTime);
   counter = 1;
   for(it=fTimeDiff.begin(); it<fTimeDiff.end(); it++) {
     TimePerEvent->Fill(*it);
     EventtimeVsEvent->Fill(counter, *it);
     counter++;
   }
   histoList->AddLast(TimePerEvent);
   histoList->AddLast(EventtimeVsEvent);
 }
void FairRunInfo::GetInfo () private
Definition at line 58 of file FairRunInfo.cxx.
References fProcInfo, fResidentMemory, fTime, fTimeStamp, and fVirtualMemory.
Referenced by Reset(), and StoreInfo().
 {
   // Set the TimeStamp to the actual time and store it
   fTimeStamp.Set();
   //  fTime.push_back(fTimeStamp.GetSec());
   fTime.push_back(fTimeStamp.AsDouble());
   gSystem->GetProcInfo(&fProcInfo);
   fResidentMemory.push_back(fProcInfo.fMemResident/1024);
   fVirtualMemory.push_back(fProcInfo.fMemVirtual/1024);
 }
FairRunInfo& FairRunInfo::operator= (const FairRunInfo &) private
void FairRunInfo::PrintInfo () private
Definition at line 79 of file FairRunInfo.cxx.
References FairLogger::Debug(), fLogger, fResidentMemory, fTimeDiff, fVirtualMemory, and MESSAGE_ORIGIN.
Referenced by StoreInfo().
 {
   fLogger->Debug(MESSAGE_ORIGIN,"Time to execute 1 event: %f s",
                  fTimeDiff.back());
   fLogger->Debug(MESSAGE_ORIGIN,"Used resident memory: %i MB",
                  fResidentMemory.back());
   fLogger->Debug(MESSAGE_ORIGIN,"Used virtual memory: %i MB",
                  fVirtualMemory.back());
 }
void FairRunInfo::Reset ()
Definition at line 228 of file FairRunInfo.cxx.
References GetInfo().
Referenced by FairRunAna::Run(), FairRunAna::RunEventReco(), and FairMCApplication::RunMC().
 {
   GetInfo();
 }
void FairRunInfo::StoreInfo ()
Definition at line 43 of file FairRunInfo.cxx.
References CalculateTimeDifference(), GetInfo(), and PrintInfo().
Referenced by FairMCApplication::FinishEvent(), FairRunAna::Run(), and FairRunAna::RunEventReco().
 {
   // Extract the Information about the used memory from the system.
   // Stores this info together with the timedifference between now
   // and the last call in container arrays for later usage.
   //  gSystem->GetCpuInfo(&cpuInfo, 10);
   //  gSystem->GetMemInfo(&memInfo);
   GetInfo();
   CalculateTimeDifference();
   PrintInfo();
 }
void FairRunInfo::WriteHistosToFile (TList * histoList) private
Definition at line 150 of file FairRunInfo.cxx.
References FairLogger::Debug(), fLogger, and MESSAGE_ORIGIN.
Referenced by WriteInfo().
 {
   // If the file size is larger then approx. 2GB then the histos
   // can't be read any longer. Because of this problem the histos
   // are written to a separate file instead
   TFile* oldfile = gFile;
   TString directory = gFile->GetName();
   fLogger->Debug(MESSAGE_ORIGIN,"Name %s:",
                  gFile->GetName());
   Ssiz_t posLastSlash = directory.Last('/');
   directory.Remove(posLastSlash+1, directory.Length()-posLastSlash-1);
   TString filename = "";
   if ( directory.EndsWith("/") ) {
     filename += directory;
   }
   directory = gFile->GetName();
   fLogger->Debug(MESSAGE_ORIGIN,"Name: %s",
                  directory.Data());
   posLastSlash = directory.Last('/');
   directory.Remove(0, posLastSlash+1);
   directory.ReplaceAll(".root","");
   fLogger->Debug(MESSAGE_ORIGIN,"Name: %s",
                  directory.Data());
 //  Int_t pid = gSystem->GetPid();
   filename += "FairRunInfo_";
   filename += directory;
   filename += ".root";
   fLogger->Debug(MESSAGE_ORIGIN,"FileName: %s",
                  filename.Data());
   TFile* f1 = new TFile(filename, "recreate");
   f1->cd();
   TIterator* listIter=histoList->MakeIterator();
   listIter->Reset();
   TObject* obj = NULL;
   while((obj=listIter->Next())) {
     obj->Write();
   }
   delete listIter;
   histoList->Delete();
   delete histoList;
   f1->Close();
   f1->Delete();
   gFile=oldfile;
   /*
   // create a new subdirectory in the output file and
   // write all histograms
   TDirectory* currentDir = gDirectory;
   gDirectory->cd();
   gDirectory->mkdir("FairRunInfo");
   gDirectory->cd("FairRunInfo");
   TIterator* listIter=histoList->MakeIterator();
   listIter->Reset();
   TObject* obj = NULL;
   while((obj=listIter->Next())) {
     obj->Write();
   }
   gDirectory=currentDir;
   */
 }
void FairRunInfo::WriteInfo ()
Definition at line 90 of file FairRunInfo.cxx.
References CreateAndFillHistograms(), and WriteHistosToFile().
Referenced by FairRunAna::Run(), FairRunAna::RunEventReco(), and FairMCApplication::RunMC().
 {
   TList* histoList = new TList();
   CreateAndFillHistograms(histoList);
   //  CreateAndFillHistograms(histoList);
   WriteHistosToFile(histoList);
 }
Member Data Documentation
CpuInfo_t FairRunInfo::fCpuInfo private
Definition at line 40 of file FairRunInfo.h.
FairLogger* FairRunInfo::fLogger private
Definition at line 47 of file FairRunInfo.h.
Referenced by PrintInfo(), and WriteHistosToFile().
MemInfo_t FairRunInfo::fMemInfo private
Definition at line 41 of file FairRunInfo.h.
ProcInfo_t FairRunInfo::fProcInfo private
Definition at line 42 of file FairRunInfo.h.
Referenced by GetInfo().
std::vector<Long_t> FairRunInfo::fResidentMemory private
Definition at line 45 of file FairRunInfo.h.
Referenced by CreateAndFillHistograms(), GetInfo(), and PrintInfo().
std::vector<Double_t> FairRunInfo::fTime private
Definition at line 44 of file FairRunInfo.h.
Referenced by CalculateTimeDifference(), CreateAndFillHistograms(), and GetInfo().
std::vector<Double_t> FairRunInfo::fTimeDiff private
Definition at line 43 of file FairRunInfo.h.
Referenced by CalculateTimeDifference(), CreateAndFillHistograms(), and PrintInfo().
TTimeStamp FairRunInfo::fTimeStamp private
Definition at line 39 of file FairRunInfo.h.
Referenced by GetInfo().
std::vector<Long_t> FairRunInfo::fVirtualMemory private
Definition at line 46 of file FairRunInfo.h.
Referenced by CreateAndFillHistograms(), GetInfo(), and PrintInfo().
The documentation for this class was generated from the following files:
FairRunInfo.h
FairRunInfo.cxx