FairRoot: FairTestDetectorRecoTask Class Reference
FairTestDetectorRecoTask Class Reference
#include <FairTestDetectorRecoTask.h>
Public Member Functions
FairTestDetectorRecoTask ()
FairTestDetectorRecoTask (Int_t verbose)
virtual ~FairTestDetectorRecoTask ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
FairTestDetectorRecoTask ()
FairTestDetectorRecoTask (Int_t verbose)
virtual ~FairTestDetectorRecoTask ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
virtual void InitWithId (Int_t rid)
FairRuntimeDb * GetRtdb ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Public Attributes
TClonesArray * fDigiArray
TClonesArray * fHitArray
FairEventHeader * fEvtHeader
Int_t fRunId
Protected Member Functions
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairTestDetectorRecoTask (const FairTestDetectorRecoTask &)
FairTestDetectorRecoTask & operator= (const FairTestDetectorRecoTask &)
ClassDef (FairTestDetectorRecoTask, 1)
FairTestDetectorRecoTask (const FairTestDetectorRecoTask &)
FairTestDetectorRecoTask & operator= (const FairTestDetectorRecoTask &)
ClassDef (FairTestDetectorRecoTask, 1)
Detailed Description
Definition at line 17 of file Tutorial3/reconstruction/FairTestDetectorRecoTask.h.
Constructor & Destructor Documentation
FairTestDetectorRecoTask::FairTestDetectorRecoTask ()
Default constructor
Definition at line 24 of file Tutorial3/reconstruction/FairTestDetectorRecoTask.cxx.
     : FairTask()
     , fDigiArray(NULL)
     , fHitArray(NULL)
 {
 }
FairTestDetectorRecoTask::FairTestDetectorRecoTask (Int_t verbose)
Definition at line 34 of file Tutorial3/reconstruction/FairTestDetectorRecoTask.cxx.
References FairTask::fVerbose.
     : FairTask()
     , fDigiArray(NULL)
     , fHitArray(NULL)
 {
     fVerbose = verbose;
 }
FairTestDetectorRecoTask::~FairTestDetectorRecoTask () virtual
Destructor
Definition at line 44 of file Tutorial3/reconstruction/FairTestDetectorRecoTask.cxx.
 {
 }
FairTestDetectorRecoTask::FairTestDetectorRecoTask (const FairTestDetectorRecoTask &) private
FairTestDetectorRecoTask::FairTestDetectorRecoTask ()
Default constructor
FairTestDetectorRecoTask::FairTestDetectorRecoTask (Int_t verbose)
virtual FairTestDetectorRecoTask::~FairTestDetectorRecoTask () virtual
Destructor
FairTestDetectorRecoTask::FairTestDetectorRecoTask (const FairTestDetectorRecoTask &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTestDetectorRecoTask::ClassDef (FairTestDetectorRecoTask , 1) private
FairTestDetectorRecoTask::ClassDef (FairTestDetectorRecoTask , 1) private
void FairTestDetectorRecoTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 76 of file Tutorial3/reconstruction/FairTestDetectorRecoTask.cxx.
References fDigiArray, fHitArray, FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), FairTestDetectorDigi::GetX(), FairTestDetectorDigi::GetY(), FairTestDetectorDigi::GetZ(), FairTimeStamp::SetTimeStamp(), and FairTimeStamp::SetTimeStampError().
 {
     fHitArray->Delete();
     // fill the map
     for (int ipnt = 0; ipnt < fDigiArray->GetEntries(); ipnt++)
     {
         FairTestDetectorDigi* digi = (FairTestDetectorDigi*)fDigiArray->At(ipnt);
         if (!digi)
             continue;
         /*
         LOG(DEBUG) << " x= "  << digi->GetX()
                    << " y= " << digi->GetY()
                    << " z= " << digi->GetZ()
                    << " t= " << digi->GetTimeStamp();
          // */
         TVector3 pos(digi->GetX() + 0.5, digi->GetY() + 0.5, digi->GetZ() + 0.5);
         TVector3 dpos(1 / TMath::Sqrt(12), 1 / TMath::Sqrt(12), 1 / TMath::Sqrt(12));
         FairTestDetectorHit* hit = new ((*fHitArray)[ipnt]) FairTestDetectorHit(-1, -1, pos, dpos);
         hit->SetTimeStamp(digi->GetTimeStamp());
         hit->SetTimeStampError(digi->GetTimeStampError());
         // hit->SetLink(FairLink("FairTestDetectorDigi", ipnt));
     }
 }
virtual void FairTestDetectorRecoTask::Exec (Option_t * opt) virtual
Virtual method Exec
virtual void FairTask::Finish () inline protected virtual inherited
Action after each event. To be implemented in the derived class
Reimplemented in FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, FairDbTutAccessRtdbTask, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 111 of file FairTask.h.
Referenced by FairTask::FinishTask(), and FairTask::FinishTasks().
 { };
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
FairRuntimeDb* FairTestDetectorRecoTask::GetRtdb () inline
Get RTDB
Definition at line 40 of file Tutorial6/reco/FairTestDetectorRecoTask.h.
References FairRuntimeDb::instance().
 {return (FairRuntimeDb::instance());}
InitStatus FairTestDetectorRecoTask::Init () virtual
Virtual method Init
todo replace with logger!
Reimplemented from FairTask.
Definition at line 50 of file Tutorial3/reconstruction/FairTestDetectorRecoTask.cxx.
References fDigiArray, fHitArray, FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kFATAL, kSUCCESS, and FairRootManager::Register().
Referenced by InitWithId().
 {
     FairRootManager* ioman = FairRootManager::Instance();
     if (!ioman)
     {
         std::cout << "-E- FairTestDetectorRecoTask::Init: "
                   << "RootManager not instantiated!" << std::endl;
         return kFATAL;
     }
     fDigiArray = (TClonesArray*)ioman->GetObject("FairTestDetectorDigi");
     if (!fDigiArray)
     {
         std::cout << "-W- FairTestDetectorRecoTask::Init: "
                   << "No Point array!" << std::endl;
         return kERROR;
     }
     // Create and register output array
     fHitArray = new TClonesArray("FairTestDetectorHit");
     ioman->Register("FairTestDetectorHit", "FairTestDetector", fHitArray, kTRUE);
     return kSUCCESS;
 }
virtual InitStatus FairTestDetectorRecoTask::Init () virtual
Virtual method Init
Reimplemented from FairTask.
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
void FairTestDetectorRecoTask::InitWithId (Int_t rid) virtual
Init with Id
Definition at line 140 of file Tutorial6/reco/FairTestDetectorRecoTask.cxx.
References fRunId, and Init().
 {
   //cout << "-I_ FairTestDetectorRecoTask::init() called !!!!" << rid << ":" << fRunId << endl;
   // if (rid != fRunId ) {
         if (true){
     fRunId = rid;
     //cout << "-I_ FairTestDetectorRecoTask::init() called !!!!" << endl;
         Init();
   }
 }
FairTestDetectorRecoTask& FairTestDetectorRecoTask::operator= (const FairTestDetectorRecoTask &) private
FairTestDetectorRecoTask& FairTestDetectorRecoTask::operator= (const FairTestDetectorRecoTask &) private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
virtual void FairTask::SetParContainers () inline protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented in FairRingSorterTask, FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairTutorialDet4HitProducerIdealMisalign, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairMCMatchLoaderTask, FairTutorialDet4StraightLineFitter, NewTask, FairDbTutAccessRtdbTask, and FairTestDetectorHitProducerSmearing.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::SetParTask().
 { };
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
TClonesArray * FairTestDetectorRecoTask::fDigiArray
Definition at line 33 of file Tutorial3/reconstruction/FairTestDetectorRecoTask.h.
Referenced by Exec(), and Init().
FairEventHeader* FairTestDetectorRecoTask::fEvtHeader
Definition at line 43 of file Tutorial6/reco/FairTestDetectorRecoTask.h.
TClonesArray * FairTestDetectorRecoTask::fHitArray
Definition at line 34 of file Tutorial3/reconstruction/FairTestDetectorRecoTask.h.
Referenced by Exec(), and Init().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
Int_t FairTestDetectorRecoTask::fRunId
Definition at line 46 of file Tutorial6/reco/FairTestDetectorRecoTask.h.
Referenced by InitWithId().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
Tutorial3/reconstruction/FairTestDetectorRecoTask.h
Tutorial3/reconstruction/FairTestDetectorRecoTask.cxx