FairRoot: MyCave.cxx File Reference
MyCave.cxx File Reference
#include "MyCave.h"
#include "MyGeoCave.h"
#include "FairGeoInterface.h"
#include "FairGeoLoader.h"
#include "FairGeoNode.h"
#include "FairGeoPassivePar.h"
#include "FairGeoVolume.h"
#include "FairRun.h"
#include "FairRuntimeDb.h"
#include "TList.h"
#include "TObjArray.h"
#include "TString.h"
#include <stddef.h>
Functions
ClassImp (MyCave) void MyCave
Function Documentation
ClassImp (MyCave)
Definition at line 30 of file MyCave.cxx.
References FairGeoInterface::addGeoModule(), FairGeoSet::create(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairGeoLoader::Instance(), FairGeoInterface::readSet(), and FairGeoSet::setGeomFile().
 {
   FairGeoLoader* loader=FairGeoLoader::Instance();
   FairGeoInterface* GeoInterface =loader->getGeoInterface();
   MyGeoCave* MGeo=new MyGeoCave();
   MGeo->setGeomFile(GetGeometryFileName());
   GeoInterface->addGeoModule(MGeo);
   Bool_t rc = GeoInterface->readSet(MGeo);
   if ( rc ) { MGeo->create(loader->getGeoBuilder()); }
 }