FairRroot: FairDbTutContFact Class Reference
FairDbTutContFact Class Reference
#include <FairDbTutContFact.h>
Public Member Functions
FairDbTutContFact ()
~FairDbTutContFact ()
FairParSet * createContainer (FairContainer *c)
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual void activateParIo (FairParIo *)
Protected Member Functions
const char * getActualContext (const char *name)
Protected Attributes
TList * containers
FairLogger * fLogger
Private Member Functions
void setAllContainers ()
ClassDef (FairDbTutContFact, 0)
Detailed Description
Definition at line 26 of file FairDbTutContFact.h.
Constructor & Destructor Documentation
FairDbTutContFact::FairDbTutContFact ()
Definition at line 38 of file FairDbTutContFact.cxx.
References FairRuntimeDb::addContFactory(), and FairRuntimeDb::instance().
 {
   // Constructor (called when the library is loaded)
   fName="FairDbTutContFact";
   fTitle="Tutorial factory for parameter containers";
   setAllContainers();
   FairRuntimeDb::instance()->addContFactory(this);
 }
FairDbTutContFact::~FairDbTutContFact () inline
Definition at line 30 of file FairDbTutContFact.h.
 {}
Member Function Documentation
virtual void FairContFact::activateParIo (FairParIo *) inline virtual inherited
Definition at line 57 of file FairContFact.h.
Referenced by FairRuntimeDb::activateParIo().
 {}
Bool_t FairContFact::addContext (const char * name) inherited
Definition at line 159 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::setActualContext().
Referenced by FairRuntimeDb::addParamContext().
 {
   // Set the actual context in all containers, which accept this context
   FairContainer* c=0;
   Bool_t found=kFALSE;
   TIter next(containers);
   while ((c=(FairContainer*)next())) {
     if (c->setActualContext(name)) { found=kTRUE; }
   }
   return found;
 }
FairDbTutContFact::ClassDef (FairDbTutContFact , 0) private
FairParSet * FairDbTutContFact::createContainer (FairContainer * c) virtual
Calls the constructor of the corresponding parameter container. For an actual context, which is not an empty string and not the default context of this container, the name is concatinated with the context.
Reimplemented from FairContFact.
Definition at line 67 of file FairDbTutContFact.cxx.
References FairContainer::getConcatName(), and FairContainer::getContext().
 {
   const char* name=c->GetName();
   cout << "-I-FairDbTutContFact::createContainer " << name << endl;
   FairDbParSet* p=NULL;
   if (strcmp(name,"TUTParDefault")==0) {
     p=new FairDbTutPar(c->getConcatName().Data(),c->GetTitle(),c->getContext());
     // Set Arguments needed for SQL versioning managment
     p->SetVersion(0);
     p->SetComboNo(-1);
     p->SetDbEntry(0);
     p->SetLogTitle(name);
   }
   if (strcmp(name,"TUTParAlternative")==0) {
     p=new FairDbTutPar(c->getConcatName().Data(),c->GetTitle(),c->getContext());
     // Set Arguments needed for SQL versioning managment
     p->SetVersion(1);
     p->SetComboNo(-1);
     p->SetDbEntry(0);
     p->SetLogTitle(name);
   }
   if (strcmp(name,"TUTParBin")==0) {
     p=new FairDbTutParBin(c->getConcatName().Data(),c->GetTitle(),c->getContext());
     // Set Arguments needed for SQL versioning managment
     p->SetVersion(0);
     p->SetComboNo(-1);
     p->SetDbEntry(0);
     p->SetLogTitle(name);
   }
   return (FairParSet*) p;
 }
const char* FairContFact::getActualContext (const char * name) inline protected inherited
Definition at line 61 of file FairContFact.h.
{
       return ((FairContainer*)containers->FindObject(name))->getActualContext();
     }
FairParSet * FairContFact::getContainer (const char * name) inherited
Definition at line 171 of file FairContFact.cxx.
References FairRuntimeDb::addContainer(), FairContFact::containers, FairContFact::createContainer(), FairRuntimeDb::findContainer(), FairContainer::getActualContext(), FairContainer::getConcatName(), FairContainer::getDefaultContext(), FairRuntimeDb::instance(), and FairContainer::setActualContext().
Referenced by FairRuntimeDb::getContainer().
 {
   // Returns the pointer to the parameter container in the runtime database
   // If this parameter container does not yet exit, it calls the function
   // createContainer(FairContainer*), which is implemented in the derived classes
   // and calls the corresponding constructor. Then the pointer it added in the
   // runtime database.
   FairContainer* c=(FairContainer*)(containers->FindObject(name));
   FairParSet* cont=0;
   if (c) {
     TString cn=c->getConcatName();
     FairRuntimeDb* rtdb = FairRuntimeDb::instance();
     if (!(cont=rtdb->findContainer(c->getConcatName().Data()))) {
       if (strlen(c->getActualContext())==0) { c->setActualContext(c->getDefaultContext()); }
       cont=createContainer(c);
       if (cont) { rtdb->addContainer(cont); }
     }
   }
   return cont;
 }
void FairContFact::print () inherited
Definition at line 193 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::print().
Referenced by FairRuntimeDb::printParamContexts().
 {
   // Loops over all containers in the list and calls their print() function
   cout<<"---------------------------------------------------------------------------"<<"\n";
   cout<<GetName()<<":  "<<GetTitle()<<"\n";
   cout<<"---------------------------------------------------------------------------"<<"\n";
   FairContainer* c;
   TIter next(containers);
   while ((c=(FairContainer*)next())) { c->print(); }
 }
void FairDbTutContFact::setAllContainers () private
Creates the Container objects with all accepted contexts and adds them to the list of containers.
Definition at line 47 of file FairDbTutContFact.cxx.
References FairContainer::addContext().
 {
   FairContainer* p1 = new FairContainer("TUTParDefault", "Default tutorial parameters",
                                         "TestDefaultContext");
   p1->addContext("TestNonDefaultContext");
   containers->Add(p1);
   FairContainer* p2 = new FairContainer("TUTParAlternative", "Alternative to the default tutorial parameters", "TestDefaultContext");
   p2->addContext("TestNonDefaultContext");
   containers->Add(p2);
   FairContainer* p3 = new FairContainer("TUTParBin", "Binary tutorial parameters", "TestDefaultContext");
   p3->addContext("TestNonDefaultContext");
   containers->Add(p3);
 }
Member Data Documentation
TList* FairContFact::containers protected inherited
Definition at line 60 of file FairContFact.h.
Referenced by FairContFact::addContext(), FairContFact::getContainer(), FairContFact::print(), FairTutorialDet2ContFact::setAllContainers(), NewDetectorContFact::setAllContainers(), FairTutorialDet1ContFact::setAllContainers(), FairRutherfordContFact::setAllContainers(), FairTestDetectorContFact::setAllContainers(), FairTutorialDet4ContFact::setAllContainers(), FairBaseContFact::setAllContainers(), and FairContFact::~FairContFact().
FairLogger* FairContFact::fLogger protected inherited
Fair Logger
Definition at line 65 of file FairContFact.h.
The documentation for this class was generated from the following files:
FairDbTutContFact.h
FairDbTutContFact.cxx