FairRoot: _FairLoggerDeathTest2.cxx File Reference
_FairLoggerDeathTest2.cxx File Reference
#include "_TestFairLogger.h"
Functions
TEST (FairToolsTestFatal, TestFatalError1)
Function Documentation
TEST()
TEST (FairToolsTestFatal , TestFatalError1)
Definition at line 3 of file _FairLoggerDeathTest2.cxx.
References FairLogger::Fatal(), FairLogger::GetLogger(), MESSAGE_ORIGIN, FairLogger::SetLogToFile(), and FairLogger::SetScreenStreamToCerr().