FairRoot: FairTestDetectorDigiRingSorter Class Reference
FairTestDetectorDigiRingSorter Class Reference
#include <FairTestDetectorDigiRingSorter.h>
Public Member Functions
FairTestDetectorDigiRingSorter (int size=100, double width=10)
virtual ~FairTestDetectorDigiRingSorter ()
virtual FairTimeStamp * CreateElement (FairTimeStamp *data)
ClassDef (FairTestDetectorDigiRingSorter, 1)
virtual void AddElement (FairTimeStamp *digi, double timestamp)
virtual void WriteOutElements (int index)
writes out the entries from LowerBoundPointer up to index
virtual void WriteOutElement (int index)
writes out the entry at the index and clears it
virtual void WriteOutAll ()
virtual double GetBufferSize ()
virtual std::vector< FairTimeStamp * > GetOutputData ()
virtual void DeleteOutputData ()
virtual void SetLowerBound (double timestampOfHitToWrite)
virtual void print (std::ostream &out=std::cout)
Detailed Description
Definition at line 24 of file FairTestDetectorDigiRingSorter.h.
Constructor & Destructor Documentation
FairTestDetectorDigiRingSorter()
FairTestDetectorDigiRingSorter::FairTestDetectorDigiRingSorter (int size = 100, double width = 10) inline
Definition at line 27 of file FairTestDetectorDigiRingSorter.h.
~FairTestDetectorDigiRingSorter()
FairTestDetectorDigiRingSorter::~FairTestDetectorDigiRingSorter () virtual
Definition at line 23 of file FairTestDetectorDigiRingSorter.cxx.
Member Function Documentation
AddElement()
void FairRingSorter::AddElement (FairTimeStamp * digi, double timestamp) virtual inherited
Definition at line 23 of file FairRingSorter.cxx.
References FairRingSorter::CalcIndex(), FairRingSorter::CreateElement(), FairRingSorter::fLowerBoundPointer, FairRingSorter::fRingBuffer, FairRingSorter::fVerbose, FairRingSorter::GetBufferSize(), FairRingSorter::SetLowerBound(), FairRingSorter::WriteOutAll(), and FairRingSorter::WriteOutElements().
Referenced by FairRingSorterTask::Exec(), and FairRingSorterTask::FinishTask().
ClassDef()
FairTestDetectorDigiRingSorter::ClassDef (FairTestDetectorDigiRingSorter , 1)
CreateElement()
FairTimeStamp * FairTestDetectorDigiRingSorter::CreateElement (FairTimeStamp * data) virtual
Reimplemented from FairRingSorter.
Definition at line 28 of file FairTestDetectorDigiRingSorter.cxx.
DeleteOutputData()
virtual void FairRingSorter::DeleteOutputData () inline virtual inherited
Definition at line 54 of file FairRingSorter.h.
References FairRingSorter::fOutputData.
Referenced by FairRingSorterTask::Exec(), and FairRingSorterTask::FinishTask().
GetBufferSize()
virtual double FairRingSorter::GetBufferSize () inline virtual inherited
Definition at line 49 of file FairRingSorter.h.
References FairRingSorter::fCellWidth, and FairRingSorter::fRingBuffer.
Referenced by FairRingSorter::AddElement(), and FairRingSorter::SetLowerBound().
GetOutputData()
virtual std::vector<FairTimeStamp*> FairRingSorter::GetOutputData () inline virtual inherited
Definition at line 50 of file FairRingSorter.h.
References FairRingSorter::fOutputData.
Referenced by FairRingSorterTask::Exec(), and FairRingSorterTask::FinishTask().
print()
virtual void FairRingSorter::print (std::ostream & out = std::cout) inline virtual inherited
Definition at line 57 of file FairRingSorter.h.
References FairRingSorter::fCellWidth, FairRingSorter::fLowerBoundPointer, and FairRingSorter::fRingBuffer.
SetLowerBound()
void FairRingSorter::SetLowerBound (double timestampOfHitToWrite) virtual inherited
Definition at line 52 of file FairRingSorter.cxx.
References FairRingSorter::CalcIndex(), FairRingSorter::fCellWidth, FairRingSorter::fLowerBoundPointer, FairRingSorter::fVerbose, and FairRingSorter::GetBufferSize().
Referenced by FairRingSorter::AddElement().
WriteOutAll()
virtual void FairRingSorter::WriteOutAll () inline virtual inherited
Definition at line 46 of file FairRingSorter.h.
References FairRingSorter::fLowerBoundPointer, and FairRingSorter::WriteOutElements().
Referenced by FairRingSorter::AddElement(), and FairRingSorterTask::FinishTask().
WriteOutElement()
void FairRingSorter::WriteOutElement (int index) virtual inherited
writes out the entry at the index and clears it
Definition at line 87 of file FairRingSorter.cxx.
References FairRingSorter::fOutputData, FairRingSorter::fRingBuffer, and FairRingSorter::fVerbose.
Referenced by FairRingSorter::WriteOutElements().
WriteOutElements()
void FairRingSorter::WriteOutElements (int index) virtual inherited
writes out the entries from LowerBoundPointer up to index
Definition at line 63 of file FairRingSorter.cxx.
References FairRingSorter::fLowerBoundPointer, FairRingSorter::fOutputData, FairRingSorter::fRingBuffer, FairRingSorter::fVerbose, and FairRingSorter::WriteOutElement().
Referenced by FairRingSorter::AddElement(), and FairRingSorter::WriteOutAll().
The documentation for this class was generated from the following files:
FairTestDetectorDigiRingSorter.h
FairTestDetectorDigiRingSorter.cxx