FairRroot: FairMQMessageNN Class Reference
FairMQMessageNN Class Reference abstract
#include <FairMQMessageNN.h>
Public Member Functions
FairMQMessageNN ()
FairMQMessageNN (const size_t size)
FairMQMessageNN (void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr)
FairMQMessageNN (FairMQUnmanagedRegionPtr &region, void *data, const size_t size, void *hint=0)
FairMQMessageNN (const FairMQMessageNN &)=delete
FairMQMessageNN operator= (const FairMQMessageNN &)=delete
void Rebuild () override
void Rebuild (const size_t size) override
void Rebuild (void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr) override
void * GetData () const override
size_t GetSize () const override
bool SetUsedSize (const size_t size) override
FairMQ::Transport GetType () const override
void Copy (const FairMQMessage &msg) override
void Copy (const FairMQMessagePtr &msg) override
~FairMQMessageNN () override
virtual void Copy (const std::unique_ptr< FairMQMessage > &msg) __attribute__((deprecated("Use 'Copy(const FairMQMessage& msg)'")))=0
Private Member Functions
void * GetMessage () const
void CloseMessage ()
void SetMessage (void *data, const size_t size)
Private Attributes
void * fMessage
size_t fSize
size_t fHint
bool fReceiving
FairMQUnmanagedRegion * fRegionPtr
Static Private Attributes
static FairMQ::Transport fTransportType = FairMQ::Transport::NN
Friends
class FairMQSocketNN
Detailed Description
Definition at line 27 of file FairMQMessageNN.h.
Constructor & Destructor Documentation
FairMQMessageNN::FairMQMessageNN ()
Definition at line 27 of file FairMQMessageNN.cxx.
References fMessage, and LOG.
FairMQMessageNN::FairMQMessageNN (const size_t size)
Definition at line 41 of file FairMQMessageNN.cxx.
References fMessage, fSize, and LOG.
FairMQMessageNN::FairMQMessageNN (void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr)
Definition at line 62 of file FairMQMessageNN.cxx.
References fMessage, fSize, and LOG.
FairMQMessageNN::FairMQMessageNN (FairMQUnmanagedRegionPtr & region, void * data, const size_t size, void * hint = 0)
Definition at line 89 of file FairMQMessageNN.cxx.
FairMQMessageNN::FairMQMessageNN (const FairMQMessageNN &) delete
FairMQMessageNN::~FairMQMessageNN () override
Definition at line 241 of file FairMQMessageNN.cxx.
References CloseMessage(), and fReceiving.
Member Function Documentation
void FairMQMessageNN::CloseMessage () private
Definition at line 228 of file FairMQMessageNN.cxx.
References fMessage, fSize, and LOG.
Referenced by Rebuild(), and ~FairMQMessageNN().
virtual void FairMQMessage::Copy (const std::unique_ptr< FairMQMessage > & msg) const pure virtual inherited
void FairMQMessageNN::Copy (const FairMQMessage & msg) override virtual
Implements FairMQMessage.
Definition at line 180 of file FairMQMessageNN.cxx.
References fMessage, fSize, GetMessage(), FairMQMessage::GetSize(), and LOG.
void FairMQMessageNN::Copy (const FairMQMessagePtr & msg) override
Definition at line 204 of file FairMQMessageNN.cxx.
References fMessage, fSize, GetMessage(), and LOG.
void * FairMQMessageNN::GetData () const override virtual
Implements FairMQMessage.
Definition at line 143 of file FairMQMessageNN.cxx.
References fMessage.
void * FairMQMessageNN::GetMessage () const private
Definition at line 138 of file FairMQMessageNN.cxx.
References fMessage.
Referenced by Copy(), and FairMQSocketNN::SendImpl().
size_t FairMQMessageNN::GetSize () const override virtual
Implements FairMQMessage.
Definition at line 148 of file FairMQMessageNN.cxx.
References fSize.
FairMQ::Transport FairMQMessageNN::GetType () const override virtual
Implements FairMQMessage.
Definition at line 175 of file FairMQMessageNN.cxx.
References fTransportType.
FairMQMessageNN FairMQMessageNN::operator= (const FairMQMessageNN &) delete
void FairMQMessageNN::Rebuild () override virtual
Implements FairMQMessage.
Definition at line 99 of file FairMQMessageNN.cxx.
References CloseMessage(), and fReceiving.
void FairMQMessageNN::Rebuild (const size_t size) override virtual
Implements FairMQMessage.
Definition at line 105 of file FairMQMessageNN.cxx.
References CloseMessage(), fMessage, fReceiving, fSize, and LOG.
void FairMQMessageNN::Rebuild (void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr) override virtual
Implements FairMQMessage.
Definition at line 117 of file FairMQMessageNN.cxx.
References CloseMessage(), fMessage, fReceiving, fSize, and LOG.
void FairMQMessageNN::SetMessage (void * data, const size_t size) private
Definition at line 169 of file FairMQMessageNN.cxx.
References fMessage, and fSize.
Referenced by FairMQSocketNN::ReceiveImpl().
bool FairMQMessageNN::SetUsedSize (const size_t size) override virtual
Implements FairMQMessage.
Definition at line 153 of file FairMQMessageNN.cxx.
References fMessage, fSize, and LOG.
Friends And Related Function Documentation
friend class FairMQSocketNN friend
Definition at line 29 of file FairMQMessageNN.h.
Member Data Documentation
size_t FairMQMessageNN::fHint private
Definition at line 59 of file FairMQMessageNN.h.
Referenced by FairMQSocketNN::SendImpl().
void* FairMQMessageNN::fMessage private
Definition at line 57 of file FairMQMessageNN.h.
Referenced by CloseMessage(), Copy(), FairMQMessageNN(), GetData(), GetMessage(), Rebuild(), SetMessage(), and SetUsedSize().
bool FairMQMessageNN::fReceiving private
Definition at line 60 of file FairMQMessageNN.h.
Referenced by Rebuild(), FairMQSocketNN::ReceiveImpl(), and ~FairMQMessageNN().
FairMQUnmanagedRegion* FairMQMessageNN::fRegionPtr private
Definition at line 61 of file FairMQMessageNN.h.
Referenced by FairMQSocketNN::SendImpl().
size_t FairMQMessageNN::fSize private
Definition at line 58 of file FairMQMessageNN.h.
Referenced by CloseMessage(), Copy(), FairMQMessageNN(), GetSize(), Rebuild(), SetMessage(), and SetUsedSize().
FairMQ::Transport FairMQMessageNN::fTransportType = FairMQ::Transport::NN static private
Definition at line 62 of file FairMQMessageNN.h.
Referenced by GetType().
The documentation for this class was generated from the following files:
FairMQMessageNN.h
FairMQMessageNN.cxx