FairRroot: fair::mq::EventManager Class Reference
fair::mq::EventManager Class Reference
Manages event callbacks from different subscribers.
#include <fairmq/EventManager.h>
Public Types
template<typename E , typename... Args>
using Signal = boost::signals2::signal< void(typename E::KeyType, Args...)>
Public Member Functions
template<typename E , typename... Args>
auto Subscribe (const std::string &subscriber, std::function< void(typename E::KeyType, Args...)> callback) -> void
template<typename E , typename... Args>
auto Unsubscribe (const std::string &subscriber) -> void
template<typename E , typename... Args>
auto Emit (typename E::KeyType key, Args...args) const -> void
Private Types
using SignalsKey = std::pair< std::type_index, std::type_index >
using SignalsValue = boost::any
using SignalsMap = std::unordered_map< SignalsKey, SignalsValue, boost::hash< SignalsKey >>
using ConnectionsKey = std::pair< std::string, SignalsKey >
using ConnectionsValue = boost::signals2::connection
using ConnectionsMap = std::unordered_map< ConnectionsKey, ConnectionsValue, boost::hash< ConnectionsKey >>
Private Member Functions
template<typename E , typename... Args>
auto GetSignal (const SignalsKey &key) const -> std::shared_ptr< Signal< E, Args...>>
Private Attributes
SignalsMap fSignals
ConnectionsMap fConnections
std::mutex fMutex
Detailed Description
Manages event callbacks from different subscribers.
The event manager stores a set of callbacks and associates them with events depending on the callback signature. The first callback argument must be of a special key type determined by the event type.
Callbacks can be subscribed/unsubscribed based on a subscriber id, the event type, and the callback signature.
Events can be emitted based on event type and callback signature.
The event manager is thread-safe.
Definition at line 53 of file EventManager.h.
Member Typedef Documentation
using fair::mq::EventManager::ConnectionsKey = std::pair<std::string, SignalsKey> private
Definition at line 117 of file EventManager.h.
using fair::mq::EventManager::ConnectionsMap = std::unordered_map<ConnectionsKey, ConnectionsValue, boost::hash<ConnectionsKey>> private
Definition at line 120 of file EventManager.h.
using fair::mq::EventManager::ConnectionsValue = boost::signals2::connection private
Definition at line 119 of file EventManager.h.
template<typename E , typename... Args> using fair::mq::EventManager::Signal = boost::signals2::signal<void(typename E::KeyType, Args...)>
Definition at line 62 of file EventManager.h.
using fair::mq::EventManager::SignalsKey = std::pair<std::type_index, std::type_index> private
Definition at line 111 of file EventManager.h.
using fair::mq::EventManager::SignalsMap = std::unordered_map<SignalsKey, SignalsValue, boost::hash<SignalsKey>> private
Definition at line 114 of file EventManager.h.
using fair::mq::EventManager::SignalsValue = boost::any private
Definition at line 113 of file EventManager.h.
Member Function Documentation
template<typename E , typename... Args> auto fair::mq::EventManager::Emit (typename E::KeyType key, Args... args) const -> void inline
Definition at line 101 of file EventManager.h.
References GetSignal().
Referenced by FairMQProgOptions::EmitUpdate(), FairMQProgOptions::SetValue(), and FairMQProgOptions::UpdateValue().
template<typename E , typename... Args> auto fair::mq::EventManager::GetSignal (const SignalsKey & key) const -> std::shared_ptr<Signal<E, Args...>> inline private
Definition at line 126 of file EventManager.h.
Referenced by Emit(), and Subscribe().
template<typename E , typename... Args> auto fair::mq::EventManager::Subscribe (const std::string & subscriber, std::function< void(typename E::KeyType, Args...)> callback) -> void inline
Definition at line 65 of file EventManager.h.
References fConnections, fMutex, and GetSignal().
Referenced by fair::mq::DeviceRunner::AddHook(), FairMQProgOptions::Subscribe(), FairMQProgOptions::SubscribeAsString(), fair::mq::StateMachine::SubscribeToStateChange(), and fair::mq::StateMachine::SubscribeToStateQueued().
template<typename E , typename... Args> auto fair::mq::EventManager::Unsubscribe (const std::string & subscriber) -> void inline
Definition at line 87 of file EventManager.h.
References fConnections, and fMutex.
Referenced by fair::mq::DeviceRunner::RemoveHook(), FairMQProgOptions::Unsubscribe(), FairMQProgOptions::UnsubscribeAsString(), fair::mq::StateMachine::UnsubscribeFromStateChange(), and fair::mq::StateMachine::UnsubscribeFromStateQueued().
Member Data Documentation
ConnectionsMap fair::mq::EventManager::fConnections private
Definition at line 121 of file EventManager.h.
Referenced by Subscribe(), and Unsubscribe().
std::mutex fair::mq::EventManager::fMutex mutable private
Definition at line 123 of file EventManager.h.
Referenced by Subscribe(), and Unsubscribe().
SignalsMap fair::mq::EventManager::fSignals mutable private
Definition at line 115 of file EventManager.h.
The documentation for this class was generated from the following file:
EventManager.h