FairRroot: SegmentManager Class Reference
SegmentManager Class Reference
#include <ShmChunk.h>
Public Member Functions
void InitializeSegment (const std::string &op, const std::string &name, const size_t size=0)
bipc::managed_shared_memory * Segment () const
Static Public Member Functions
static SegmentManager & Instance ()
Private Member Functions
SegmentManager ()
Private Attributes
bipc::managed_shared_memory * fSegment
Detailed Description
ShmChunk.h
Since
2016-04-08
Author
A. Rybalchenko
Definition at line 28 of file ShmChunk.h.
Constructor & Destructor Documentation
SegmentManager::SegmentManager () inline private
Definition at line 112 of file ShmChunk.h.
Member Function Documentation
void SegmentManager::InitializeSegment (const std::string & op, const std::string & name, const size_t size = 0) inline
Definition at line 37 of file ShmChunk.h.
References fSegment, and LOG.
Referenced by FairMQShmPrototypeSink::Init(), and FairMQShmPrototypeSampler::Init().
static SegmentManager& SegmentManager::Instance () inline static
Definition at line 31 of file ShmChunk.h.
Referenced by FairMQShmPrototypeSink::Init(), FairMQShmPrototypeSampler::Init(), FairMQShmPrototypeSink::Log(), FairMQShmPrototypeSampler::Log(), FairMQShmPrototypeSink::Run(), and FairMQShmPrototypeSampler::Run().
bipc::managed_shared_memory* SegmentManager::Segment () const inline
Definition at line 98 of file ShmChunk.h.
References fSegment, and LOG.
Referenced by FairMQShmPrototypeSink::Init(), FairMQShmPrototypeSampler::Init(), FairMQShmPrototypeSink::Log(), FairMQShmPrototypeSampler::Log(), FairMQShmPrototypeSink::Run(), and FairMQShmPrototypeSampler::Run().
Member Data Documentation
bipc::managed_shared_memory* SegmentManager::fSegment private
Definition at line 116 of file ShmChunk.h.
Referenced by InitializeSegment(), and Segment().
The documentation for this class was generated from the following file:
ShmChunk.h