FairRroot: FairMQSocketNN Class Reference
FairMQSocketNN Class Reference
#include <FairMQSocketNN.h>
Public Member Functions
FairMQSocketNN (const std::string &type, const std::string &name, const std::string &id="")
FairMQSocketNN (const FairMQSocketNN &)=delete
FairMQSocketNN operator= (const FairMQSocketNN &)=delete
std::string GetId () override
bool Bind (const std::string &address) override
void Connect (const std::string &address) override
int Send (FairMQMessagePtr &msg, const int timeout=0) override
int Receive (FairMQMessagePtr &msg, const int timeout=0) override
int64_t Send (std::vector< std::unique_ptr< FairMQMessage >> &msgVec, const int timeout=0) override
int64_t Receive (std::vector< std::unique_ptr< FairMQMessage >> &msgVec, const int timeout=0) override
int TrySend (FairMQMessagePtr &msg) override
int TryReceive (FairMQMessagePtr &msg) override
int64_t TrySend (std::vector< std::unique_ptr< FairMQMessage >> &msgVec) override
int64_t TryReceive (std::vector< std::unique_ptr< FairMQMessage >> &msgVec) override
void * GetSocket () const override
int GetSocket (int nothing) const override
void Close () override
void SetOption (const std::string &option, const void *value, size_t valueSize) override
void GetOption (const std::string &option, void *value, size_t *valueSize) override
unsigned long GetBytesTx () const override
unsigned long GetBytesRx () const override
unsigned long GetMessagesTx () const override
unsigned long GetMessagesRx () const override
bool SetSendTimeout (const int timeout, const std::string &address, const std::string &method) override
int GetSendTimeout () const override
bool SetReceiveTimeout (const int timeout, const std::string &address, const std::string &method) override
int GetReceiveTimeout () const override
~FairMQSocketNN () override
Static Public Member Functions
static void Interrupt ()
static void Resume ()
static int GetConstant (const std::string &constant)
Private Member Functions
int SendImpl (FairMQMessagePtr &msg, const int flags, const int timeout)
int ReceiveImpl (FairMQMessagePtr &msg, const int flags, const int timeout)
int64_t SendImpl (std::vector< std::unique_ptr< FairMQMessage >> &msgVec, const int flags, const int timeout)
int64_t ReceiveImpl (std::vector< std::unique_ptr< FairMQMessage >> &msgVec, const int flags, const int timeout)
Private Attributes
int fSocket
std::string fId
std::atomic< unsigned long > fBytesTx
std::atomic< unsigned long > fBytesRx
std::atomic< unsigned long > fMessagesTx
std::atomic< unsigned long > fMessagesRx
int fSndTimeout
int fRcvTimeout
Static Private Attributes
static std::atomic< bool > fInterrupted
Detailed Description
Definition at line 18 of file FairMQSocketNN.h.
Constructor & Destructor Documentation
FairMQSocketNN::FairMQSocketNN (const std::string & type, const std::string & name, const std::string & id = "")
FairMQSocketNN::FairMQSocketNN (const FairMQSocketNN &) delete
FairMQSocketNN::~FairMQSocketNN () override
Definition at line 598 of file FairMQSocketNN.cxx.
Member Function Documentation
bool FairMQSocketNN::Bind (const std::string & address) override virtual
Implements FairMQSocket.
Definition at line 97 of file FairMQSocketNN.cxx.
References LOG.
void FairMQSocketNN::Close () override virtual
Implements FairMQSocket.
Definition at line 432 of file FairMQSocketNN.cxx.
void FairMQSocketNN::Connect (const std::string & address) override virtual
Implements FairMQSocket.
Definition at line 110 of file FairMQSocketNN.cxx.
References LOG.
unsigned long FairMQSocketNN::GetBytesRx () const override virtual
Implements FairMQSocket.
Definition at line 495 of file FairMQSocketNN.cxx.
unsigned long FairMQSocketNN::GetBytesTx () const override virtual
Implements FairMQSocket.
Definition at line 490 of file FairMQSocketNN.cxx.
int FairMQSocketNN::GetConstant (const std::string & constant) static
Definition at line 544 of file FairMQSocketNN.cxx.
References LOG.
string FairMQSocketNN::GetId () override virtual
Implements FairMQSocket.
Definition at line 92 of file FairMQSocketNN.cxx.
unsigned long FairMQSocketNN::GetMessagesRx () const override virtual
Implements FairMQSocket.
Definition at line 505 of file FairMQSocketNN.cxx.
unsigned long FairMQSocketNN::GetMessagesTx () const override virtual
Implements FairMQSocket.
Definition at line 500 of file FairMQSocketNN.cxx.
void FairMQSocketNN::GetOption (const std::string & option, void * value, size_t * valueSize) override virtual
Implements FairMQSocket.
Definition at line 481 of file FairMQSocketNN.cxx.
References LOG.
int FairMQSocketNN::GetReceiveTimeout () const override virtual
Implements FairMQSocket.
Definition at line 539 of file FairMQSocketNN.cxx.
int FairMQSocketNN::GetSendTimeout () const override virtual
Implements FairMQSocket.
Definition at line 522 of file FairMQSocketNN.cxx.
void * FairMQSocketNN::GetSocket () const override virtual
Implements FairMQSocket.
Definition at line 447 of file FairMQSocketNN.cxx.
int FairMQSocketNN::GetSocket (int nothing) const override virtual
Implements FairMQSocket.
Definition at line 452 of file FairMQSocketNN.cxx.
void FairMQSocketNN::Interrupt () static
Definition at line 437 of file FairMQSocketNN.cxx.
Referenced by FairMQTransportFactoryNN::Interrupt().
FairMQSocketNN FairMQSocketNN::operator= (const FairMQSocketNN &) delete
int FairMQSocketNN::Receive (FairMQMessagePtr & msg, const int timeout = 0) override virtual
Implements FairMQSocket.
Definition at line 122 of file FairMQSocketNN.cxx.
int64_t FairMQSocketNN::Receive (std::vector< std::unique_ptr< FairMQMessage >> & msgVec, const int timeout = 0) override virtual
Implements FairMQSocket.
int FairMQSocketNN::ReceiveImpl (FairMQMessagePtr & msg, const int flags, const int timeout) private
Definition at line 200 of file FairMQSocketNN.cxx.
References FairMQMessageNN::fReceiving, LOG, and FairMQMessageNN::SetMessage().
int64_t FairMQSocketNN::ReceiveImpl (std::vector< std::unique_ptr< FairMQMessage >> & msgVec, const int flags, const int timeout) private
void FairMQSocketNN::Resume () static
Definition at line 442 of file FairMQSocketNN.cxx.
Referenced by FairMQTransportFactoryNN::Resume().
int FairMQSocketNN::Send (FairMQMessagePtr & msg, const int timeout = 0) override virtual
Implements FairMQSocket.
Definition at line 121 of file FairMQSocketNN.cxx.
int64_t FairMQSocketNN::Send (std::vector< std::unique_ptr< FairMQMessage >> & msgVec, const int timeout = 0) override virtual
Implements FairMQSocket.
int FairMQSocketNN::SendImpl (FairMQMessagePtr & msg, const int flags, const int timeout) private
Definition at line 131 of file FairMQSocketNN.cxx.
References FairMQMessageNN::fHint, FairMQMessageNN::fRegionPtr, FairMQMessageNN::GetMessage(), and LOG.
int64_t FairMQSocketNN::SendImpl (std::vector< std::unique_ptr< FairMQMessage >> & msgVec, const int flags, const int timeout) private
void FairMQSocketNN::SetOption (const std::string & option, const void * value, size_t valueSize) override virtual
Implements FairMQSocket.
Definition at line 457 of file FairMQSocketNN.cxx.
References LOG.
bool FairMQSocketNN::SetReceiveTimeout (const int timeout, const std::string & address, const std::string & method) override virtual
Implements FairMQSocket.
Definition at line 527 of file FairMQSocketNN.cxx.
References LOG.
bool FairMQSocketNN::SetSendTimeout (const int timeout, const std::string & address, const std::string & method) override virtual
Implements FairMQSocket.
Definition at line 510 of file FairMQSocketNN.cxx.
References LOG.
int FairMQSocketNN::TryReceive (FairMQMessagePtr & msg) override virtual
Implements FairMQSocket.
Definition at line 127 of file FairMQSocketNN.cxx.
int64_t FairMQSocketNN::TryReceive (std::vector< std::unique_ptr< FairMQMessage >> & msgVec) override virtual
Implements FairMQSocket.
int FairMQSocketNN::TrySend (FairMQMessagePtr & msg) override virtual
Implements FairMQSocket.
Definition at line 126 of file FairMQSocketNN.cxx.
int64_t FairMQSocketNN::TrySend (std::vector< std::unique_ptr< FairMQMessage >> & msgVec) override virtual
Implements FairMQSocket.
Member Data Documentation
std::atomic<unsigned long> FairMQSocketNN::fBytesRx private
Definition at line 69 of file FairMQSocketNN.h.
std::atomic<unsigned long> FairMQSocketNN::fBytesTx private
Definition at line 68 of file FairMQSocketNN.h.
std::string FairMQSocketNN::fId private
Definition at line 67 of file FairMQSocketNN.h.
atomic< bool > FairMQSocketNN::fInterrupted static private
Definition at line 73 of file FairMQSocketNN.h.
std::atomic<unsigned long> FairMQSocketNN::fMessagesRx private
Definition at line 71 of file FairMQSocketNN.h.
std::atomic<unsigned long> FairMQSocketNN::fMessagesTx private
Definition at line 70 of file FairMQSocketNN.h.
int FairMQSocketNN::fRcvTimeout private
Definition at line 76 of file FairMQSocketNN.h.
int FairMQSocketNN::fSndTimeout private
Definition at line 75 of file FairMQSocketNN.h.
int FairMQSocketNN::fSocket private
Definition at line 66 of file FairMQSocketNN.h.
The documentation for this class was generated from the following files:
FairMQSocketNN.h
FairMQSocketNN.cxx