FairRoot: FairMbsStreamSource Class Reference
FairMbsStreamSource Class Reference
#include <FairMbsStreamSource.h>
Public Member Functions
FairMbsStreamSource (TString tServerName)
FairMbsStreamSource (const FairMbsStreamSource &source)
virtual ~FairMbsStreamSource ()
virtual Bool_t Init ()
virtual Int_t ReadEvent (UInt_t=0)
virtual void Close ()
const char * GetServerName () const
void AddUnpacker (FairUnpack *unpacker)
const TObjArray * GetUnpackers () const
virtual void SetParUnpackers ()
virtual Bool_t InitUnpackers ()
virtual Bool_t ReInitUnpackers ()
void Reset ()
virtual Source_Type GetSourceType ()
virtual Bool_t ActivateObject (TObject **, const char *)
virtual Bool_t ActivateObjectAny (void **, const std::type_info &, const char *)
virtual Int_t CheckMaxEventNo (Int_t=0)
virtual void ReadBranchEvent (const char *)
virtual void ReadBranchEvent (const char *, Int_t)
virtual void FillEventHeader (FairEventHeader *feh)
void SetRunId (Int_t runId)
Int_t GetRunId () const
Protected Member Functions
Bool_t Unpack (Int_t *data, Int_t size, Short_t type, Short_t subType, Short_t procId, Short_t subCrate, Short_t control)
Protected Attributes
TObjArray * fUnpackers
Int_t fRunId
Private Member Functions
Bool_t ConnectToServer ()
FairMbsStreamSource & operator= (const FairMbsStreamSource &)
Private Attributes
TString fServerName
s_evt_channel * fxInputChannel
s_ve10_1 * fxEvent
s_bufhe * fxBuffer
Int_t * fxEventData
s_ves10_1 * fxSubEvent
Detailed Description
Definition at line 25 of file FairMbsStreamSource.h.
Constructor & Destructor Documentation
FairMbsStreamSource() [1/2]
FairMbsStreamSource::FairMbsStreamSource (TString tServerName)
Definition at line 15 of file FairMbsStreamSource.cxx.
FairMbsStreamSource() [2/2]
FairMbsStreamSource::FairMbsStreamSource (const FairMbsStreamSource & source)
Definition at line 27 of file FairMbsStreamSource.cxx.
~FairMbsStreamSource()
FairMbsStreamSource::~FairMbsStreamSource () virtual
Definition at line 39 of file FairMbsStreamSource.cxx.
Member Function Documentation
ActivateObject()
virtual Bool_t FairSource::ActivateObject (TObject ** , const char *) inline virtual inherited
Reimplemented in FairFileSource, FairMixedSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 39 of file FairSource.h.
Referenced by FairRootManager::ActivateBranch(), FairMQPixelSampler::InitTask(), and FairRootManager::UpdateBranches().
ActivateObjectAny()
virtual Bool_t FairSource::ActivateObjectAny (void ** , const std::type_info & , const char *) inline virtual inherited
Reimplemented in FairFileSource.
Definition at line 40 of file FairSource.h.
Referenced by FairRootManager::InitObjectAs().
AddUnpacker()
void FairOnlineSource::AddUnpacker (FairUnpack * unpacker) inline inherited
Definition at line 32 of file FairOnlineSource.h.
References FairOnlineSource::fUnpackers.
Referenced by unpack_mbs().
CheckMaxEventNo()
virtual Int_t FairSource::CheckMaxEventNo (Int_t = 0) inline virtual inherited
Check the maximum event number we can run to
Reimplemented in FairMixedSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 51 of file FairSource.h.
Referenced by FairRootManager::CheckMaxEventNo(), and FairMQPixelSampler::InitTask().
Close()
void FairMbsStreamSource::Close () virtual
Implements FairMbsSource.
Definition at line 141 of file FairMbsStreamSource.cxx.
References f_evt_error(), f_evt_get_close(), and fxInputChannel.
ConnectToServer()
Bool_t FairMbsStreamSource::ConnectToServer () private
Definition at line 54 of file FairMbsStreamSource.cxx.
References f_evt_error(), f_evt_get_open(), fServerName, fxInputChannel, GETEVT__STREAM, and GETEVT__SUCCESS.
Referenced by Init().
FillEventHeader()
void FairSource::FillEventHeader (FairEventHeader * feh) virtual inherited
Reimplemented in FairMixedSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 39 of file FairSource.cxx.
References FairSource::fRunId, and FairEventHeader::SetRunId().
Referenced by FairRootManager::FillEventHeader(), FairRootManager::GetRunId(), FairRootManager::ReadBranchEvent(), FairRootManager::ReadEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
GetRunId()
Int_t FairSource::GetRunId () const inline inherited
Definition at line 58 of file FairSource.h.
References FairSource::fRunId.
GetServerName()
const char* FairMbsStreamSource::GetServerName () const inline
Definition at line 36 of file FairMbsStreamSource.h.
References fServerName.
GetSourceType()
virtual Source_Type FairOnlineSource::GetSourceType () inline virtual inherited
Implements FairSource.
Definition at line 47 of file FairOnlineSource.h.
References kONLINE.
GetUnpackers()
const TObjArray* FairOnlineSource::GetUnpackers () const inline inherited
Definition at line 33 of file FairOnlineSource.h.
References FairOnlineSource::fUnpackers.
Init()
Bool_t FairMbsStreamSource::Init () virtual
Implements FairMbsSource.
Definition at line 44 of file FairMbsStreamSource.cxx.
References ConnectToServer().
InitUnpackers()
Bool_t FairOnlineSource::InitUnpackers () virtual inherited
Implements FairSource.
Definition at line 31 of file FairOnlineSource.cxx.
References FairOnlineSource::fUnpackers, and FairOnlineSource::Init().
operator=()
FairMbsStreamSource& FairMbsStreamSource::operator= (const FairMbsStreamSource &) private
ReadBranchEvent() [1/2]
virtual void FairSource::ReadBranchEvent (const char *) inline virtual inherited
Read the tree entry on one branch
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 53 of file FairSource.h.
Referenced by FairRootManager::ReadBranchEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
ReadBranchEvent() [2/2]
virtual void FairSource::ReadBranchEvent (const char * , Int_t) inline virtual inherited
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 54 of file FairSource.h.
ReadEvent()
Int_t FairMbsStreamSource::ReadEvent (UInt_t = 0) virtual
Implements FairMbsSource.
Definition at line 85 of file FairMbsStreamSource.cxx.
References f_evt_error(), f_evt_get_event(), f_evt_get_subevent(), fxBuffer, fxEvent, fxEventData, fxInputChannel, fxSubEvent, GETEVT__SUCCESS, s_ves10_1::h_control, s_ves10_1::h_subcrate, s_ves10_1::i_procid, s_ves10_1::i_subtype, s_ves10_1::i_type, and FairMbsSource::Unpack().
ReInitUnpackers()
Bool_t FairOnlineSource::ReInitUnpackers () virtual inherited
Implements FairSource.
Definition at line 40 of file FairOnlineSource.cxx.
References FairOnlineSource::fUnpackers.
Reset()
void FairOnlineSource::Reset () virtual inherited
Implements FairSource.
Definition at line 55 of file FairOnlineSource.cxx.
References FairOnlineSource::fUnpackers.
SetParUnpackers()
void FairOnlineSource::SetParUnpackers () virtual inherited
Implements FairSource.
Definition at line 49 of file FairOnlineSource.cxx.
References FairOnlineSource::fUnpackers.
SetRunId()
void FairSource::SetRunId (Int_t runId) inline inherited
Definition at line 57 of file FairSource.h.
References FairSource::fRunId.
Referenced by FairRunOnline::Init().
Unpack()
Bool_t FairMbsSource::Unpack (Int_t * data, Int_t size, Short_t type, Short_t subType, Short_t procId, Short_t subCrate, Short_t control) protected inherited
Definition at line 29 of file FairMbsSource.cxx.
References FairUnpack::DoUnpack(), FairOnlineSource::fUnpackers, FairUnpack::GetControl(), FairUnpack::GetProcId(), FairUnpack::GetSubCrate(), FairUnpack::GetSubType(), and FairUnpack::GetType().
Referenced by FairLmdSource::Close(), FairLmdSource::OpenNextFile(), ReadEvent(), FairRemoteSource::ReadEvent(), and FairLmdSource::ReadEvent().
Member Data Documentation
fRunId
Int_t FairSource::fRunId protected inherited
Definition at line 61 of file FairSource.h.
Referenced by FairSource::FillEventHeader(), FairSource::GetRunId(), and FairSource::SetRunId().
fServerName
TString FairMbsStreamSource::fServerName private
Definition at line 41 of file FairMbsStreamSource.h.
Referenced by ConnectToServer(), and GetServerName().
fUnpackers
TObjArray* FairOnlineSource::fUnpackers protected inherited
Definition at line 50 of file FairOnlineSource.h.
Referenced by FairOnlineSource::AddUnpacker(), FairOnlineSource::GetUnpackers(), FairOnlineSource::InitUnpackers(), FairOnlineSource::ReInitUnpackers(), FairOnlineSource::Reset(), FairOnlineSource::SetParUnpackers(), FairMbsSource::Unpack(), and FairOnlineSource::~FairOnlineSource().
fxBuffer
s_bufhe* FairMbsStreamSource::fxBuffer private
Definition at line 45 of file FairMbsStreamSource.h.
Referenced by ReadEvent().
fxEvent
s_ve10_1* FairMbsStreamSource::fxEvent private
Definition at line 44 of file FairMbsStreamSource.h.
Referenced by ReadEvent().
fxEventData
Int_t* FairMbsStreamSource::fxEventData private
Definition at line 46 of file FairMbsStreamSource.h.
Referenced by ReadEvent().
fxInputChannel
s_evt_channel* FairMbsStreamSource::fxInputChannel private
Definition at line 43 of file FairMbsStreamSource.h.
Referenced by Close(), ConnectToServer(), and ReadEvent().
fxSubEvent
s_ves10_1* FairMbsStreamSource::fxSubEvent private
Definition at line 47 of file FairMbsStreamSource.h.
Referenced by ReadEvent().
The documentation for this class was generated from the following files:
FairMbsStreamSource.h
FairMbsStreamSource.cxx