FairRroot: PixelDigiSource Class Reference
PixelDigiSource Class Reference
#include <PixelDigiSource.h>
Public Member Functions
PixelDigiSource (TString inputFileName="test.dat")
virtual ~PixelDigiSource ()
Bool_t Init ()
Int_t ReadEvent (UInt_t i=0)
void Close ()
void Reset ()
virtual Source_Type GetSourceType ()
virtual void SetParUnpackers ()
virtual Bool_t InitUnpackers ()
virtual Bool_t ReInitUnpackers ()
virtual Int_t CheckMaxEventNo (Int_t EvtEnd=0)
virtual void FillEventHeader (FairEventHeader *feh)
void SetInputFileName (TString tstr)
virtual Bool_t ActivateObject (TObject **obj, const char *BrName)
virtual Bool_t ActivateObjectAny (void **, const std::type_info &, const char *)
virtual void ReadBranchEvent (const char *)
virtual void ReadBranchEvent (const char *, Int_t)
void SetRunId (Int_t runId)
Int_t GetRunId () const
Private Member Functions
PixelDigiSource (const PixelDigiSource &)
PixelDigiSource & operator= (const PixelDigiSource &)
Private Attributes
PixelEventHeader * fEventHeader
TClonesArray * fDigis
Int_t fNDigis
Int_t fTNofEvents
Int_t fTNofDigis
TString fInputFileName
std::ifstream fInputFile
Int_t fCurrentEntryNo
Int_t fRunId
Int_t fMCEntryNo
Int_t fPartNo
Detailed Description
Definition at line 32 of file PixelDigiSource.h.
Constructor & Destructor Documentation
PixelDigiSource::PixelDigiSource (TString inputFileName = "test.dat")
Definition at line 32 of file PixelDigiSource.cxx.
References LOG.
PixelDigiSource::~PixelDigiSource () virtual
Definition at line 51 of file PixelDigiSource.cxx.
PixelDigiSource::PixelDigiSource (const PixelDigiSource &) private
Member Function Documentation
Bool_t PixelDigiSource::ActivateObject (TObject ** obj, const char * BrName) virtual
Reimplemented from FairSource.
Definition at line 149 of file PixelDigiSource.cxx.
References fDigis, and fEventHeader.
virtual Bool_t FairSource::ActivateObjectAny (void ** , const std::type_info & , const char *) inline virtual inherited
Reimplemented in FairFileSource.
Definition at line 40 of file FairSource.h.
Referenced by FairRootManager::InitObjectAs().
Int_t PixelDigiSource::CheckMaxEventNo (Int_t EvtEnd = 0) virtual
Check the maximum event number we can run to
Reimplemented from FairSource.
Definition at line 175 of file PixelDigiSource.cxx.
void PixelDigiSource::Close () virtual
Implements FairSource.
Definition at line 162 of file PixelDigiSource.cxx.
References fInputFile.
void PixelDigiSource::FillEventHeader (FairEventHeader * feh) virtual
Reimplemented from FairSource.
Definition at line 182 of file PixelDigiSource.cxx.
References fMCEntryNo, fPartNo, and fRunId.
Int_t FairSource::GetRunId () const inline inherited
Definition at line 58 of file FairSource.h.
References FairSource::fRunId.
virtual Source_Type PixelDigiSource::GetSourceType () inline virtual
Implements FairSource.
Definition at line 44 of file PixelDigiSource.h.
References kFILE.
Bool_t PixelDigiSource::Init () virtual
Implements FairSource.
Definition at line 57 of file PixelDigiSource.cxx.
References fDigis, fEventHeader, fInputFile, fInputFileName, FairRootManager::Instance(), LOG, and FairRootManager::Register().
virtual Bool_t PixelDigiSource::InitUnpackers () inline virtual
Implements FairSource.
Definition at line 48 of file PixelDigiSource.h.
PixelDigiSource& PixelDigiSource::operator= (const PixelDigiSource &) private
virtual void FairSource::ReadBranchEvent (const char *) inline virtual inherited
Read the tree entry on one branch
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 53 of file FairSource.h.
Referenced by FairRootManager::ReadBranchEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
virtual void FairSource::ReadBranchEvent (const char * , Int_t) inline virtual inherited
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 54 of file FairSource.h.
Int_t PixelDigiSource::ReadEvent (UInt_t i = 0) virtual
Implements FairSource.
Definition at line 96 of file PixelDigiSource.cxx.
References fCurrentEntryNo, fDigis, fEventHeader, fInputFile, fMCEntryNo, fNDigis, fPartNo, fRunId, LOG, ReadIntFromString(), FairEventHeader::SetMCEntryNumber(), PixelEventHeader::SetPartNo(), and FairEventHeader::SetRunId().
virtual Bool_t PixelDigiSource::ReInitUnpackers () inline virtual
Implements FairSource.
Definition at line 50 of file PixelDigiSource.h.
void PixelDigiSource::Reset () virtual
Implements FairSource.
Definition at line 169 of file PixelDigiSource.cxx.
void PixelDigiSource::SetInputFileName (TString tstr) inline
Definition at line 57 of file PixelDigiSource.h.
References fInputFileName.
Referenced by run_dAsciiSource().
virtual void PixelDigiSource::SetParUnpackers () inline virtual
Implements FairSource.
Definition at line 46 of file PixelDigiSource.h.
void FairSource::SetRunId (Int_t runId) inline inherited
Definition at line 57 of file FairSource.h.
References FairSource::fRunId.
Referenced by FairRunOnline::Init().
Member Data Documentation
Int_t PixelDigiSource::fCurrentEntryNo private
Definition at line 72 of file PixelDigiSource.h.
Referenced by ReadEvent().
TClonesArray* PixelDigiSource::fDigis private
Definition at line 63 of file PixelDigiSource.h.
Referenced by ActivateObject(), Init(), and ReadEvent().
PixelEventHeader* PixelDigiSource::fEventHeader private
Definition at line 62 of file PixelDigiSource.h.
Referenced by ActivateObject(), Init(), and ReadEvent().
std::ifstream PixelDigiSource::fInputFile private
Definition at line 70 of file PixelDigiSource.h.
Referenced by Close(), Init(), and ReadEvent().
TString PixelDigiSource::fInputFileName private
Definition at line 69 of file PixelDigiSource.h.
Referenced by Init(), and SetInputFileName().
Int_t PixelDigiSource::fMCEntryNo private
Definition at line 75 of file PixelDigiSource.h.
Referenced by FillEventHeader(), and ReadEvent().
Int_t PixelDigiSource::fNDigis private
Output array of PixelDigi
Definition at line 64 of file PixelDigiSource.h.
Referenced by ReadEvent().
Int_t PixelDigiSource::fPartNo private
Definition at line 76 of file PixelDigiSource.h.
Referenced by FillEventHeader(), and ReadEvent().
Int_t PixelDigiSource::fRunId private
Definition at line 74 of file PixelDigiSource.h.
Referenced by FillEventHeader(), and ReadEvent().
Int_t PixelDigiSource::fTNofDigis private
Definition at line 67 of file PixelDigiSource.h.
Int_t PixelDigiSource::fTNofEvents private
Definition at line 66 of file PixelDigiSource.h.
The documentation for this class was generated from the following files:
PixelDigiSource.h
PixelDigiSource.cxx