FairRoot: FairMixedSource Class Reference
FairMixedSource Class Reference
#include <FairMixedSource.h>
Public Member Functions
FairMixedSource (TFile *f, const char *Title="InputRootFile", UInt_t identifier=0)
FairMixedSource (const TString *RootFileName, const char *Title="InputRootFile", UInt_t identifier=0)
FairMixedSource (const TString RootFileName, const Int_t signalId, const char *Title="InputRootFile", UInt_t identifier=0)
virtual ~FairMixedSource ()
Bool_t Init ()
Int_t ReadEvent (UInt_t i=0)
void Close ()
void Reset ()
virtual Source_Type GetSourceType ()
virtual void SetParUnpackers ()
virtual Bool_t InitUnpackers ()
virtual Bool_t ReInitUnpackers ()
virtual Int_t CheckMaxEventNo (Int_t EvtEnd=0)
void ReadBranchEvent (const char *BrName)
void ReadBranchEvent (const char *BrName, Int_t Entry)
void FillEventHeader (FairEventHeader *feh)
const TFile * GetRootFile ()
virtual Bool_t ActivateObject (TObject **obj, const char *BrName)
void ReadBKEvent (UInt_t i=0)
void SetSignalFile (TString name, UInt_t identifier)
void SetBackgroundFile (TString name)
void AddSignalFile (TString name, UInt_t identifier)
void AddBackgroundFile (TString name)
TChain * GetBGChain ()
TChain * GetSignalChainNo (UInt_t i)
Bool_t OpenBackgroundChain ()
Bool_t OpenSignalChain ()
void BGWindowWidthNo (UInt_t background, UInt_t Signalid)
void BGWindowWidthTime (Double_t background, UInt_t Signalid)
void SetEventTimeInterval (Double_t min, Double_t max)
void SetEventMeanTime (Double_t mean)
void SetBeamTime (Double_t beamTime, Double_t gapTime)
void SetEventTime ()
Double_t GetDeltaEventTime ()
void SetFileHeader (FairFileHeader *f)
Double_t GetEventTime ()
Bool_t CompareBranchList (TFile *fileHandle, TString inputLevel)
TObjArray * GetListOfFolders ()
TFolder * GetBranchDescriptionFolder ()
UInt_t GetEntries ()
void SetEvtHeaderNew (Bool_t Status)
Bool_t IsEvtHeaderNew ()
virtual Bool_t ActivateObjectAny (void **, const std::type_info &, const char *)
void SetRunId (Int_t runId)
Int_t GetRunId () const
Protected Attributes
Int_t fRunId
Private Member Functions
FairMixedSource (const FairMixedSource &)
FairMixedSource & operator= (const FairMixedSource &)
Private Attributes
FairRootManager * fRootManager
TString fInputTitle
TFile * fRootFile
std::list< TString > fFriendFileList
std::list< TString > fInputChainList
std::map< TString, TChain * > fFriendTypeList
std::map< TString, std::list< TString > *> fCheckInputBranches
std::list< TString > fInputLevel
std::map< TString, std::multimap< TString, TArrayI > > fRunIdInfoAll
TObjArray * fListFolder
FairRuntimeDb * fRtdb
TFolder * fCbmout
TFolder * fCbmroot
UInt_t fSourceIdentifier
UInt_t fNoOfEntries
Bool_t IsInitialized
FairMCEventHeader * fMCHeader
FairEventHeader * fEvtHeader
FairEventHeader * fOutHeader
FairFileHeader * fFileHeader
Bool_t fEventTimeInMCHeader
Bool_t fEvtHeaderIsNew
UInt_t fCurrentEntryNo
UInt_t fTimeforEntryNo
UInt_t fNoOfBGEntries
std::map< UInt_t, UInt_t > fCurrentEntry
Double_t fEventTimeMin
Double_t fEventTimeMax
Double_t fEventTime
Double_t fBeamTime
Double_t fGapTime
Double_t fEventMeanTime
TF1 * fTimeProb
std::map< UInt_t, Double_t > fSignalBGN
Bool_t fSBRatiobyN
Bool_t fSBRatiobyT
UInt_t fActualSignalIdentifier
UInt_t fNoOfSignals
std::list< TString > * fSignalChainList
TChain * fBackgroundChain
std::map< UInt_t, TChain * > fSignalTypeList
Detailed Description
Definition at line 35 of file FairMixedSource.h.
Constructor & Destructor Documentation
FairMixedSource() [1/4]
FairMixedSource::FairMixedSource (TFile * f, const char * Title = "InputRootFile", UInt_t identifier = 0)
Definition at line 37 of file FairMixedSource.cxx.
References fRootFile, fRootManager, and FairRootManager::Instance().
FairMixedSource() [2/4]
FairMixedSource::FairMixedSource (const TString * RootFileName, const char * Title = "InputRootFile", UInt_t identifier = 0)
Definition at line 89 of file FairMixedSource.cxx.
References fRootFile, fRootManager, and FairRootManager::Instance().
FairMixedSource() [3/4]
FairMixedSource::FairMixedSource (const TString RootFileName, const Int_t signalId, const char * Title = "InputRootFile", UInt_t identifier = 0)
Definition at line 141 of file FairMixedSource.cxx.
References fRootFile, fRootManager, FairRootManager::Instance(), SetBackgroundFile(), and SetSignalFile().
~FairMixedSource()
FairMixedSource::~FairMixedSource () virtual
Definition at line 202 of file FairMixedSource.cxx.
FairMixedSource() [4/4]
FairMixedSource::FairMixedSource (const FairMixedSource &) private
Member Function Documentation
ActivateObject()
Bool_t FairMixedSource::ActivateObject (TObject ** obj, const char * BrName) virtual
Add a friend file (input) by name)
Reimplemented from FairSource.
Definition at line 618 of file FairMixedSource.cxx.
References fBackgroundChain, and fSignalTypeList.
Referenced by Init().
ActivateObjectAny()
virtual Bool_t FairSource::ActivateObjectAny (void ** , const std::type_info & , const char *) inline virtual inherited
Reimplemented in FairFileSource.
Definition at line 40 of file FairSource.h.
Referenced by FairRootManager::InitObjectAs().
AddBackgroundFile()
void FairMixedSource::AddBackgroundFile (TString name)
Definition at line 525 of file FairMixedSource.cxx.
References fBackgroundChain.
Referenced by FairRunAna::AddBackgroundFile().
AddSignalFile()
void FairMixedSource::AddSignalFile (TString name, UInt_t identifier)
Add signal file to input
Parameters
name : signal file name
identifier : Unsigned integer which identify the signal file to which this signal should be added
Definition at line 491 of file FairMixedSource.cxx.
References SetSignalFile().
Referenced by FairRunAna::AddSignalFile(), create_digis_mixed(), and FairRunAna::SetSignalFile().
BGWindowWidthNo()
void FairMixedSource::BGWindowWidthNo (UInt_t background, UInt_t Signalid)
Set the signal to background ratio in event units
Parameters
background : Number of background Events for one signal
Signalid : Signal file Id, used when adding (setting) the signal file
Definition at line 647 of file FairMixedSource.cxx.
References fSBRatiobyN, fSBRatiobyT, and fSignalBGN.
Referenced by FairRunAna::BGWindowWidthNo().
BGWindowWidthTime()
void FairMixedSource::BGWindowWidthTime (Double_t background, UInt_t Signalid)
Set the signal to background rate in time units
Parameters
background : Time of background Events before one signal
Signalid : Signal file Id, used when adding (setting) the signal file
convert to number of event by dividing by the mean time
Definition at line 663 of file FairMixedSource.cxx.
References fEventMeanTime, fEventTimeInMCHeader, fSBRatiobyN, fSBRatiobyT, and fSignalBGN.
Referenced by FairRunAna::BGWindowWidthTime().
CheckMaxEventNo()
Int_t FairMixedSource::CheckMaxEventNo (Int_t EvtEnd = 0) virtual
Check the maximum event number we can run to
Reimplemented from FairSource.
Definition at line 687 of file FairMixedSource.cxx.
References fBackgroundChain, fSignalBGN, and fSignalTypeList.
Close()
void FairMixedSource::Close () virtual
Implements FairSource.
Definition at line 395 of file FairMixedSource.cxx.
CompareBranchList()
Bool_t FairMixedSource::CompareBranchList (TFile * fileHandle, TString inputLevel)
Add ROOT file to input, the file will be chained to already added files
Definition at line 415 of file FairMixedSource.cxx.
References fCheckInputBranches.
Referenced by Init(), and OpenSignalChain().
FillEventHeader()
void FairMixedSource::FillEventHeader (FairEventHeader * feh) virtual
Reimplemented from FairSource.
Definition at line 403 of file FairMixedSource.cxx.
References fCurrentEntryNo, fOutHeader, FairEventHeader::GetEventTime(), FairEventHeader::GetInputFileId(), FairEventHeader::GetMCEntryNumber(), FairEventHeader::GetRunId(), FairEventHeader::SetEventTime(), FairEventHeader::SetInputFileId(), FairEventHeader::SetMCEntryNumber(), and FairEventHeader::SetRunId().
GetBGChain()
TChain* FairMixedSource::GetBGChain () inline
Definition at line 87 of file FairMixedSource.h.
References fBackgroundChain.
GetBranchDescriptionFolder()
TFolder* FairMixedSource::GetBranchDescriptionFolder () inline
Definition at line 119 of file FairMixedSource.h.
References fCbmroot.
GetDeltaEventTime()
Double_t FairMixedSource::GetDeltaEventTime ()
Definition at line 776 of file FairMixedSource.cxx.
References fEventTimeMax, fEventTimeMin, and fTimeProb.
Referenced by SetEventTime().
GetEntries()
UInt_t FairMixedSource::GetEntries () inline
Definition at line 120 of file FairMixedSource.h.
References fNoOfEntries.
GetEventTime()
Double_t FairMixedSource::GetEventTime ()
Definition at line 792 of file FairMixedSource.cxx.
References fCurrentEntryNo, fEventTime, fEventTimeInMCHeader, fEvtHeader, fEvtHeaderIsNew, fMCHeader, fTimeforEntryNo, FairEventHeader::GetEventTime(), FairMCEventHeader::GetT(), and SetEventTime().
Referenced by ReadEvent().
GetListOfFolders()
TObjArray* FairMixedSource::GetListOfFolders () inline
Set the input tree when running on PROOF worker
Definition at line 118 of file FairMixedSource.h.
References fListFolder.
GetRootFile()
const TFile* FairMixedSource::GetRootFile () inline
Definition at line 66 of file FairMixedSource.h.
References fRootFile.
GetRunId()
Int_t FairSource::GetRunId () const inline inherited
Definition at line 58 of file FairSource.h.
References FairSource::fRunId.
GetSignalChainNo()
TChain * FairMixedSource::GetSignalChainNo (UInt_t i)
Definition at line 498 of file FairMixedSource.cxx.
References fNoOfSignals, and fSignalTypeList.
GetSourceType()
virtual Source_Type FairMixedSource::GetSourceType () inline virtual
Implements FairSource.
Definition at line 49 of file FairMixedSource.h.
References kFILE.
Init()
Bool_t FairMixedSource::Init () virtual
Implements FairSource.
Definition at line 205 of file FairMixedSource.cxx.
References ActivateObject(), FairRootManager::AddBranchToList(), CompareBranchList(), fBackgroundChain, fCbmroot, fCheckInputBranches, fEvtHeader, fInputChainList, fInputLevel, fInputTitle, fListFolder, fMCHeader, fNoOfEntries, fOutHeader, fRootFile, fSBRatiobyN, fSBRatiobyT, FairRootManager::GetFolderName(), FairEventHeader::GetRunId(), FairMCEventHeader::GetRunID(), FairRootManager::GetTreeName(), FairRootManager::Instance(), IsInitialized, FairRootManager::SetInChain(), FairRootManager::SetListOfFolders(), and FairEventHeader::SetRunId().
InitUnpackers()
virtual Bool_t FairMixedSource::InitUnpackers () inline virtual
Implements FairSource.
Definition at line 53 of file FairMixedSource.h.
IsEvtHeaderNew()
Bool_t FairMixedSource::IsEvtHeaderNew () inline
Definition at line 127 of file FairMixedSource.h.
References fEvtHeaderIsNew.
OpenBackgroundChain()
Bool_t FairMixedSource::OpenBackgroundChain ()
Definition at line 547 of file FairMixedSource.cxx.
References FairRootManager::AddBranchToList(), fCbmroot, fCheckInputBranches, fInputLevel, fListFolder, fRootFile, FairRootManager::GetFolderName(), and FairRootManager::Instance().
OpenSignalChain()
Bool_t FairMixedSource::OpenSignalChain ()
Definition at line 598 of file FairMixedSource.cxx.
References CompareBranchList(), and fSignalTypeList.
operator=()
FairMixedSource& FairMixedSource::operator= (const FairMixedSource &) private
ReadBKEvent()
void FairMixedSource::ReadBKEvent (UInt_t i = 0)
Definition at line 636 of file FairMixedSource.cxx.
References fBackgroundChain.
ReadBranchEvent() [1/2]
void FairMixedSource::ReadBranchEvent (const char * BrName) virtual
Read the tree entry on one branch
fill the object with content if the other branches in this tree entry were already read
Reimplemented from FairSource.
Definition at line 822 of file FairMixedSource.cxx.
References fEvtHeader, fSignalTypeList, FairEventHeader::GetInputFileId(), and FairEventHeader::GetMCEntryNumber().
ReadBranchEvent() [2/2]
void FairMixedSource::ReadBranchEvent (const char * BrName, Int_t Entry) virtual
Read specific tree entry on one branch
fill the object with content if the other branches in this tree entry were already read
Reimplemented from FairSource.
Definition at line 834 of file FairMixedSource.cxx.
References fEvtHeader, fSignalTypeList, and FairEventHeader::GetInputFileId().
ReadEvent()
Int_t FairMixedSource::ReadEvent (UInt_t i = 0) virtual
Implements FairSource.
Definition at line 343 of file FairMixedSource.cxx.
References fBackgroundChain, fCurrentEntry, fCurrentEntryNo, fOutHeader, fSBRatiobyN, fSBRatiobyT, fSignalBGN, fSignalTypeList, GetEventTime(), FairEventHeader::SetEventTime(), SetEventTime(), FairEventHeader::SetInputFileId(), and FairEventHeader::SetMCEntryNumber().
ReInitUnpackers()
virtual Bool_t FairMixedSource::ReInitUnpackers () inline virtual
Implements FairSource.
Definition at line 55 of file FairMixedSource.h.
Reset()
void FairMixedSource::Reset () virtual
Implements FairSource.
Definition at line 398 of file FairMixedSource.cxx.
SetBackgroundFile()
void FairMixedSource::SetBackgroundFile (TString name)
Set the input background file by name
Definition at line 510 of file FairMixedSource.cxx.
References fCurrentEntry, and fRootFile.
Referenced by FairMixedSource(), and FairRunAna::SetBackgroundFile().
SetBeamTime()
void FairMixedSource::SetBeamTime (Double_t beamTime, Double_t gapTime)
Set the repetition time of the beam when it can interact (beamTime) and when no interaction happen (gapTime). The total repetition time is beamTime + gapTime
Definition at line 749 of file FairMixedSource.cxx.
References fBeamTime, and fGapTime.
Referenced by FairRunAna::SetBeamTime().
SetEventMeanTime()
void FairMixedSource::SetEventMeanTime (Double_t mean)
Set the mean time for the event in ns
Definition at line 720 of file FairMixedSource.cxx.
References fEventMeanTime, fEventTimeInMCHeader, and fTimeProb.
Referenced by FairRunAna::SetEventMeanTime().
SetEventTime()
void FairMixedSource::SetEventTime ()
Definition at line 757 of file FairMixedSource.cxx.
References fBeamTime, fCurrentEntryNo, fEventTime, fGapTime, fTimeforEntryNo, and GetDeltaEventTime().
Referenced by GetEventTime(), and ReadEvent().
SetEventTimeInterval()
void FairMixedSource::SetEventTimeInterval (Double_t min, Double_t max)
Set the min and max limit for event time in ns
Definition at line 739 of file FairMixedSource.cxx.
References fEventMeanTime, fEventTimeInMCHeader, fEventTimeMax, and fEventTimeMin.
Referenced by FairRunAna::SetEventTimeInterval().
SetEvtHeaderNew()
void FairMixedSource::SetEvtHeaderNew (Bool_t Status) inline
Set the status of the EvtHeader
Parameters
Status True: The header was creatged in this session and has to be filled FALSE: We use an existing header from previous data level
Definition at line 126 of file FairMixedSource.h.
References fEvtHeaderIsNew.
SetFileHeader()
void FairMixedSource::SetFileHeader (FairFileHeader * f) inline
Definition at line 112 of file FairMixedSource.h.
References fFileHeader.
SetParUnpackers()
virtual void FairMixedSource::SetParUnpackers () inline virtual
Implements FairSource.
Definition at line 51 of file FairMixedSource.h.
SetRunId()
void FairSource::SetRunId (Int_t runId) inline inherited
Definition at line 57 of file FairSource.h.
References FairSource::fRunId.
Referenced by FairRunOnline::Init().
SetSignalFile()
void FairMixedSource::SetSignalFile (TString name, UInt_t identifier)
Set the input signal file
Parameters
name : signal file name
identifier : Unsigned integer which identify the signal file
Set a signal file of certain type (identifier) if already exist add the file to the chain
Definition at line 465 of file FairMixedSource.cxx.
References fActualSignalIdentifier, fCurrentEntry, fNoOfSignals, fSignalTypeList, FairRootManager::GetFolderName(), FairRootManager::GetTreeName(), FairRootManager::Instance(), and FairRootManager::SetInChain().
Referenced by AddSignalFile(), and FairMixedSource().
Member Data Documentation
fActualSignalIdentifier
UInt_t FairMixedSource::fActualSignalIdentifier private
Actual identifier of the added signals, this is used to identify how many signals are added
Definition at line 211 of file FairMixedSource.h.
Referenced by SetSignalFile().
fBackgroundChain
TChain* FairMixedSource::fBackgroundChain private
Chain containing the background
Definition at line 217 of file FairMixedSource.h.
Referenced by ActivateObject(), AddBackgroundFile(), CheckMaxEventNo(), GetBGChain(), Init(), ReadBKEvent(), and ReadEvent().
fBeamTime
Double_t FairMixedSource::fBeamTime private
Time of particles in beam (ns)
Definition at line 195 of file FairMixedSource.h.
Referenced by SetBeamTime(), and SetEventTime().
fCbmout
TFolder* FairMixedSource::fCbmout private
folder structure of output
Definition at line 149 of file FairMixedSource.h.
fCbmroot
TFolder* FairMixedSource::fCbmroot private
folder structure of input
Definition at line 151 of file FairMixedSource.h.
Referenced by GetBranchDescriptionFolder(), Init(), and OpenBackgroundChain().
fCheckInputBranches
std::map<TString, std::list<TString>* > FairMixedSource::fCheckInputBranches private
Definition at line 141 of file FairMixedSource.h.
Referenced by CompareBranchList(), Init(), and OpenBackgroundChain().
fCurrentEntry
std::map<UInt_t, UInt_t> FairMixedSource::fCurrentEntry private
Definition at line 186 of file FairMixedSource.h.
Referenced by ReadEvent(), SetBackgroundFile(), and SetSignalFile().
fCurrentEntryNo
UInt_t FairMixedSource::fCurrentEntryNo private
for internal use, to return the same event time for the same entry
Definition at line 180 of file FairMixedSource.h.
Referenced by FillEventHeader(), GetEventTime(), ReadEvent(), and SetEventTime().
fEventMeanTime
Double_t FairMixedSource::fEventMeanTime private
EventMean time used (P(t)=1/fEventMeanTime*Exp(-t/fEventMeanTime)
Definition at line 199 of file FairMixedSource.h.
Referenced by BGWindowWidthTime(), SetEventMeanTime(), and SetEventTimeInterval().
fEventTime
Double_t FairMixedSource::fEventTime private
Time of event since th start (ns)
Definition at line 193 of file FairMixedSource.h.
Referenced by GetEventTime(), and SetEventTime().
fEventTimeInMCHeader
Bool_t FairMixedSource::fEventTimeInMCHeader private
This is true if the event time used, came from simulation
Definition at line 172 of file FairMixedSource.h.
Referenced by BGWindowWidthTime(), GetEventTime(), SetEventMeanTime(), and SetEventTimeInterval().
fEventTimeMax
Double_t FairMixedSource::fEventTimeMax private
max time for one Event (ns)
Definition at line 191 of file FairMixedSource.h.
Referenced by GetDeltaEventTime(), and SetEventTimeInterval().
fEventTimeMin
Double_t FairMixedSource::fEventTimeMin private
min time for one event (ns)
Definition at line 189 of file FairMixedSource.h.
Referenced by GetDeltaEventTime(), and SetEventTimeInterval().
fEvtHeader
FairEventHeader* FairMixedSource::fEvtHeader private
Event Header
Definition at line 163 of file FairMixedSource.h.
Referenced by GetEventTime(), Init(), and ReadBranchEvent().
fEvtHeaderIsNew
Bool_t FairMixedSource::fEvtHeaderIsNew private
This flag is true if the event header was created in this session otherwise it is false which means the header was created in a previous data level and used here (e.g. in the digi)
Definition at line 177 of file FairMixedSource.h.
Referenced by GetEventTime(), IsEvtHeaderNew(), and SetEvtHeaderNew().
fFileHeader
FairFileHeader* FairMixedSource::fFileHeader private
File Header
Definition at line 169 of file FairMixedSource.h.
Referenced by SetFileHeader().
fFriendFileList
std::list<TString> FairMixedSource::fFriendFileList private
List of all files added with AddFriend
Definition at line 138 of file FairMixedSource.h.
fFriendTypeList
std::map<TString, TChain*> FairMixedSource::fFriendTypeList private
Definition at line 140 of file FairMixedSource.h.
fGapTime
Double_t FairMixedSource::fGapTime private
Time without particles in beam (gap) (ns)
Definition at line 197 of file FairMixedSource.h.
Referenced by SetBeamTime(), and SetEventTime().
fInputChainList
std::list<TString> FairMixedSource::fInputChainList private
Definition at line 139 of file FairMixedSource.h.
Referenced by Init().
fInputLevel
std::list<TString> FairMixedSource::fInputLevel private
Definition at line 142 of file FairMixedSource.h.
Referenced by Init(), and OpenBackgroundChain().
fInputTitle
TString FairMixedSource::fInputTitle private
Title of input source, could be input, background or signal
Definition at line 134 of file FairMixedSource.h.
Referenced by Init().
fListFolder
TObjArray* FairMixedSource::fListFolder private
list of folders from all input (and friends) files
Definition at line 145 of file FairMixedSource.h.
Referenced by GetListOfFolders(), Init(), and OpenBackgroundChain().
fMCHeader
FairMCEventHeader* FairMixedSource::fMCHeader private
MC Event header
Definition at line 160 of file FairMixedSource.h.
Referenced by GetEventTime(), and Init().
fNoOfBGEntries
UInt_t FairMixedSource::fNoOfBGEntries private
Definition at line 184 of file FairMixedSource.h.
fNoOfEntries
UInt_t FairMixedSource::fNoOfEntries private
No of Entries in this source
Definition at line 155 of file FairMixedSource.h.
Referenced by GetEntries(), and Init().
fNoOfSignals
UInt_t FairMixedSource::fNoOfSignals private
Total number of signals added (Types and not files!)
Definition at line 213 of file FairMixedSource.h.
Referenced by GetSignalChainNo(), and SetSignalFile().
fOutHeader
FairEventHeader* FairMixedSource::fOutHeader private
Output Event Header
Definition at line 166 of file FairMixedSource.h.
Referenced by FillEventHeader(), Init(), and ReadEvent().
fRootFile
TFile* FairMixedSource::fRootFile private
ROOT file
Definition at line 136 of file FairMixedSource.h.
Referenced by FairMixedSource(), GetRootFile(), Init(), OpenBackgroundChain(), and SetBackgroundFile().
fRootManager
FairRootManager* FairMixedSource::fRootManager private
IO manager
Definition at line 131 of file FairMixedSource.h.
Referenced by FairMixedSource().
fRtdb
FairRuntimeDb* FairMixedSource::fRtdb private
RuntimeDb
Definition at line 147 of file FairMixedSource.h.
fRunId
Int_t FairSource::fRunId protected inherited
Definition at line 61 of file FairSource.h.
Referenced by FairSource::FillEventHeader(), FairSource::GetRunId(), and FairSource::SetRunId().
fRunIdInfoAll
std::map<TString, std::multimap<TString, TArrayI> > FairMixedSource::fRunIdInfoAll private
Definition at line 143 of file FairMixedSource.h.
fSBRatiobyN
Bool_t FairMixedSource::fSBRatiobyN private
Definition at line 206 of file FairMixedSource.h.
Referenced by BGWindowWidthNo(), BGWindowWidthTime(), Init(), and ReadEvent().
fSBRatiobyT
Bool_t FairMixedSource::fSBRatiobyT private
Definition at line 208 of file FairMixedSource.h.
Referenced by BGWindowWidthNo(), BGWindowWidthTime(), Init(), and ReadEvent().
fSignalBGN
std::map<UInt_t, Double_t> FairMixedSource::fSignalBGN private
holds the SB ratio by number
Definition at line 204 of file FairMixedSource.h.
Referenced by BGWindowWidthNo(), BGWindowWidthTime(), CheckMaxEventNo(), and ReadEvent().
fSignalChainList
std::list<TString>* FairMixedSource::fSignalChainList private
list of chains which has to be created for the different signals
Definition at line 215 of file FairMixedSource.h.
fSignalTypeList
std::map<UInt_t, TChain*> FairMixedSource::fSignalTypeList private
Definition at line 218 of file FairMixedSource.h.
Referenced by ActivateObject(), CheckMaxEventNo(), GetSignalChainNo(), OpenSignalChain(), ReadBranchEvent(), ReadEvent(), and SetSignalFile().
fSourceIdentifier
UInt_t FairMixedSource::fSourceIdentifier private
Definition at line 153 of file FairMixedSource.h.
fTimeforEntryNo
UInt_t FairMixedSource::fTimeforEntryNo private
for internal use, to return the same event time for the same entry
Definition at line 182 of file FairMixedSource.h.
Referenced by GetEventTime(), and SetEventTime().
fTimeProb
TF1* FairMixedSource::fTimeProb private
used to generate random numbers for event time;
Definition at line 201 of file FairMixedSource.h.
Referenced by GetDeltaEventTime(), and SetEventMeanTime().
IsInitialized
Bool_t FairMixedSource::IsInitialized private
Initialization flag, true if initialized
Definition at line 157 of file FairMixedSource.h.
Referenced by Init().
The documentation for this class was generated from the following files:
FairMixedSource.h
FairMixedSource.cxx