FairRroot: fair::mq::PluginServices Class Reference
fair::mq::PluginServices Class Reference
Facilitates communication between devices and plugins.
#include <fairmq/PluginServices.h>
Classes
struct DeviceControlError
struct InvalidStateError
struct PropertyNotFoundError
Public Types
enum DeviceState : int {
DeviceState::Ok, DeviceState::Error, DeviceState::Idle, DeviceState::InitializingDevice,
DeviceState::DeviceReady, DeviceState::InitializingTask, DeviceState::Ready, DeviceState::Running,
DeviceState::Paused, DeviceState::ResettingTask, DeviceState::ResettingDevice, DeviceState::Exiting
}
See https://github.com/FairRootGroup/FairRoot/blob/dev/fairmq/docs/Device.md#13-state-machine.
enum DeviceStateTransition : int {
DeviceStateTransition::InitDevice, DeviceStateTransition::InitTask, DeviceStateTransition::Run, DeviceStateTransition::Pause,
DeviceStateTransition::Resume, DeviceStateTransition::Stop, DeviceStateTransition::ResetTask, DeviceStateTransition::ResetDevice,
DeviceStateTransition::End, DeviceStateTransition::ErrorFound
}
Public Member Functions
PluginServices ()=delete
PluginServices (FairMQProgOptions *config, std::shared_ptr< FairMQDevice > device)
PluginServices (const PluginServices &)=delete
PluginServices operator= (const PluginServices &)=delete
auto GetCurrentDeviceState () const -> DeviceState
auto TakeDeviceControl (const std::string &controller) -> void
Become device controller.
auto StealDeviceControl (const std::string &controller) -> void
Become device controller by force.
auto ReleaseDeviceControl (const std::string &controller) -> void
Release device controller role.
auto GetDeviceController () const -> boost::optional< std::string >
Get current device controller.
auto WaitForReleaseDeviceControl () -> void
Block until control is released.
auto ChangeDeviceState (const std::string &controller, const DeviceStateTransition next) -> void
Request a device state transition.
auto SubscribeToDeviceStateChange (const std::string &subscriber, std::function< void(DeviceState)> callback) -> void
Subscribe with a callback to device state changes.
auto UnsubscribeFromDeviceStateChange (const std::string &subscriber) -> void
Unsubscribe from device state changes.
auto PropertyExists (const std::string &key) const -> bool
template<typename T >
auto SetProperty (const std::string &key, T val) -> void
Set config property.
template<typename T >
auto GetProperty (const std::string &key) const -> T
Read config property.
auto GetPropertyAsString (const std::string &key) const -> std::string
Read config property as string.
auto GetChannelInfo () const -> std::unordered_map< std::string, int >
auto GetPropertyKeys () const -> std::vector< std::string >
Discover the list of property keys.
template<typename T >
auto SubscribeToPropertyChange (const std::string &subscriber, std::function< void(const std::string &key, T)> callback) const -> void
Subscribe to property updates of type T.
template<typename T >
auto UnsubscribeFromPropertyChange (const std::string &subscriber) -> void
Unsubscribe from property updates of type T.
auto SubscribeToPropertyChangeAsString (const std::string &subscriber, std::function< void(const std::string &key, std::string)> callback) const -> void
Subscribe to property updates.
auto UnsubscribeFromPropertyChangeAsString (const std::string &subscriber) -> void
Unsubscribe from property updates that convert to string.
Static Public Member Functions
static auto ToDeviceState (const std::string &state) -> DeviceState
Convert string to DeviceState.
static auto ToDeviceStateTransition (const std::string &transition) -> DeviceStateTransition
Convert string to DeviceStateTransition.
static auto ToStr (DeviceState state) -> std::string
Convert DeviceState to string.
static auto ToStr (DeviceStateTransition transition) -> std::string
Convert DeviceStateTransition to string.
Static Public Attributes
static const std::unordered_map< std::string, DeviceState > fkDeviceStateStrMap
static const std::unordered_map< DeviceState, std::string, tools::HashEnum< DeviceState > > fkStrDeviceStateMap
static const std::unordered_map< std::string, DeviceStateTransition > fkDeviceStateTransitionStrMap
static const std::unordered_map< DeviceStateTransition, std::string, tools::HashEnum< DeviceStateTransition > > fkStrDeviceStateTransitionMap
static const std::unordered_map< FairMQDevice::State, DeviceState, tools::HashEnum< FairMQDevice::State > > fkDeviceStateMap
static const std::unordered_map< DeviceStateTransition, FairMQDevice::Event, tools::HashEnum< DeviceStateTransition > > fkDeviceStateTransitionMap
Private Attributes
FairMQProgOptions * fConfig
std::shared_ptr< FairMQDevice > fDevice
boost::optional< std::string > fDeviceController
std::mutex fDeviceControllerMutex
std::condition_variable fReleaseDeviceControlCondition
Friends
auto operator<< (std::ostream &os, const DeviceState &state) -> std::ostream &
auto operator<< (std::ostream &os, const DeviceStateTransition &transition) -> std::ostream &
Detailed Description
Facilitates communication between devices and plugins.
Configuration interface
Control interface
Definition at line 37 of file PluginServices.h.
Member Enumeration Documentation
enum fair::mq::PluginServices::DeviceState : int strong
See https://github.com/FairRootGroup/FairRoot/blob/dev/fairmq/docs/Device.md#13-state-machine.
Enumerator
Ok
Error
Idle
InitializingDevice
DeviceReady
InitializingTask
Ready
Running
Paused
ResettingTask
ResettingDevice
Exiting
Definition at line 54 of file PluginServices.h.
enum fair::mq::PluginServices::DeviceStateTransition : int strong
Enumerator
InitDevice
InitTask
Run
Pause
Resume
Stop
ResetTask
ResetDevice
End
ErrorFound
Definition at line 70 of file PluginServices.h.
Constructor & Destructor Documentation
fair::mq::PluginServices::PluginServices () delete
fair::mq::PluginServices::PluginServices (FairMQProgOptions * config, std::shared_ptr< FairMQDevice > device) inline
Definition at line 41 of file PluginServices.h.
fair::mq::PluginServices::PluginServices (const PluginServices &) delete
Member Function Documentation
auto PluginServices::ChangeDeviceState (const std::string & controller, const DeviceStateTransition next) -> void
Request a device state transition.
Parameters
controller id
next state transition
Exceptions
fair::mq::PluginServices::DeviceControlError if control role is not currently owned by passed controller id.
The state transition may not happen immediately, but when the current state evaluates the pending transition event and terminates. In other words, the device states are scheduled cooperatively. If the device control role has not been taken yet, calling this function will take over control implicitely.
Definition at line 93 of file PluginServices.cxx.
References fair::mq::tools::ToString().
Referenced by fair::mq::Plugin::ChangeDeviceState().
auto fair::mq::PluginServices::GetChannelInfo () const -> std::unordered_map<std::string, int> inline
Definition at line 220 of file PluginServices.h.
References fConfig, and FairMQProgOptions::GetChannelInfo().
Referenced by fair::mq::Plugin::GetChannelInfo().
auto fair::mq::PluginServices::GetCurrentDeviceState () const -> DeviceState inline
Returns
current device state
Definition at line 112 of file PluginServices.h.
References fDevice, and fkDeviceStateMap.
Referenced by fair::mq::Plugin::GetCurrentDeviceState(), and SetProperty().
auto PluginServices::GetDeviceController () const -> boost::optional<std::string>
Get current device controller.
Definition at line 158 of file PluginServices.cxx.
template<typename T > auto fair::mq::PluginServices::GetProperty (const std::string & key) const -> T inline
Read config property.
Parameters
key
Returns
config property value
TODO Currently, if a non-existing key is requested and a default constructed object is returned. This behaviour will be changed in the future to throw an exception in that case to provide a proper sentinel.
Definition at line 201 of file PluginServices.h.
References fConfig, FairProgOptions::GetValue(), PropertyExists(), and fair::mq::tools::ToString().
Referenced by fair::mq::Plugin::GetProperty().
auto fair::mq::PluginServices::GetPropertyAsString (const std::string & key) const -> std::string inline
Read config property as string.
Parameters
key
Returns
config property value converted to string
If a type is not supported, the user can provide support by overloading the ostream operator for this type
Definition at line 213 of file PluginServices.h.
References fConfig, FairProgOptions::GetStringValue(), PropertyExists(), and fair::mq::tools::ToString().
Referenced by fair::mq::Plugin::GetPropertyAsString().
auto fair::mq::PluginServices::GetPropertyKeys () const -> std::vector<std::string> inline
Discover the list of property keys.
Returns
list of property keys
Definition at line 224 of file PluginServices.h.
References fConfig, and FairProgOptions::GetPropertyKeys().
Referenced by fair::mq::Plugin::GetPropertyKeys().
PluginServices fair::mq::PluginServices::operator= (const PluginServices &) delete
auto fair::mq::PluginServices::PropertyExists (const std::string & key) const -> bool inline
Definition at line 170 of file PluginServices.h.
References FairProgOptions::Count(), and fConfig.
Referenced by GetProperty(), GetPropertyAsString(), and fair::mq::Plugin::PropertyExists().
auto PluginServices::ReleaseDeviceControl (const std::string & controller) -> void
Release device controller role.
Parameters
controller id
Exceptions
fair::mq::PluginServices::DeviceControlError if passed controller id is not the current device controller.
Definition at line 140 of file PluginServices.cxx.
References fair::mq::tools::ToString().
Referenced by fair::mq::Plugin::ReleaseDeviceControl().
template<typename T > auto fair::mq::PluginServices::SetProperty (const std::string & key, T val) -> void inline
Set config property.
Parameters
key
val
Exceptions
fair::mq::PluginServices::InvalidStateError if method is called in unsupported device states
Setting a config property will store the value in the FairMQ internal config store and notify any subscribers about the update. It is property dependent, if the call to this method will have an immediate, delayed or any effect at all.
Definition at line 180 of file PluginServices.h.
References fConfig, GetCurrentDeviceState(), InitializingDevice, FairMQProgOptions::SetValue(), and fair::mq::tools::ToString().
Referenced by fair::mq::Plugin::SetProperty().
auto PluginServices::StealDeviceControl (const std::string & controller) -> void
Become device controller by force.
Parameters
controller id
Take over device controller privileges by force. Does not trigger the ReleaseDeviceControl condition! This function is intended to implement override/emergency control functionality (e.g. device shutdown on SIGINT).
Definition at line 133 of file PluginServices.cxx.
Referenced by fair::mq::Plugin::StealDeviceControl().
auto fair::mq::PluginServices::SubscribeToDeviceStateChange (const std::string & subscriber, std::function< void(DeviceState)> callback) -> void inline
Subscribe with a callback to device state changes.
Parameters
subscriber id
callback The callback will be called at the beginning of a new state. The callback is called from the thread the state is running in.
Definition at line 156 of file PluginServices.h.
References fDevice, and fkDeviceStateMap.
Referenced by fair::mq::Plugin::SubscribeToDeviceStateChange().
template<typename T > auto fair::mq::PluginServices::SubscribeToPropertyChange (const std::string & subscriber, std::function< void(const std::string &key, T)> callback) const -> void inline
Subscribe to property updates of type T.
Parameters
subscriber
callback function
Subscribe to property changes with a callback to monitor property changes in an event based fashion.
Definition at line 232 of file PluginServices.h.
References fConfig, and FairMQProgOptions::Subscribe().
Referenced by fair::mq::Plugin::SubscribeToPropertyChange().
auto fair::mq::PluginServices::SubscribeToPropertyChangeAsString (const std::string & subscriber, std::function< void(const std::string &key, std::string)> callback) const -> void inline
Subscribe to property updates.
Parameters
subscriber
callback function
Subscribe to property changes with a callback to monitor property changes in an event based fashion. Will convert the property to string.
Definition at line 247 of file PluginServices.h.
References fConfig, and FairMQProgOptions::SubscribeAsString().
Referenced by fair::mq::Plugin::SubscribeToPropertyChangeAsString().
auto PluginServices::TakeDeviceControl (const std::string & controller) -> void
Become device controller.
Parameters
controller id
Exceptions
fair::mq::PluginServices::DeviceControlError if there is already a device controller.
Only one plugin can succeed to take control over device state transitions at a time.
Definition at line 112 of file PluginServices.cxx.
References fair::mq::tools::ToString().
Referenced by fair::mq::Plugin::TakeDeviceControl().
static auto fair::mq::PluginServices::ToDeviceState (const std::string & state) -> DeviceState inline static
Convert string to DeviceState.
Parameters
state to convert
Returns
DeviceState enum entry
Exceptions
std::out_of_range if a string cannot be resolved to a DeviceState
Definition at line 90 of file PluginServices.h.
References fkDeviceStateStrMap, and fair::state.
Referenced by fair::mq::Plugin::ToDeviceState().
static auto fair::mq::PluginServices::ToDeviceStateTransition (const std::string & transition) -> DeviceStateTransition inline static
Convert string to DeviceStateTransition.
Parameters
transition to convert
Returns
DeviceStateTransition enum entry
Exceptions
std::out_of_range if a string cannot be resolved to a DeviceStateTransition
Definition at line 96 of file PluginServices.h.
References fkDeviceStateTransitionStrMap.
Referenced by fair::mq::Plugin::ToDeviceStateTransition().
static auto fair::mq::PluginServices::ToStr (DeviceState state) -> std::string inline static
Convert DeviceState to string.
Parameters
state to convert
Returns
string representation of DeviceState enum entry
Definition at line 101 of file PluginServices.h.
References fkStrDeviceStateMap, and fair::state.
Referenced by fair::mq::Plugin::ToStr().
static auto fair::mq::PluginServices::ToStr (DeviceStateTransition transition) -> std::string inline static
Convert DeviceStateTransition to string.
Parameters
transition to convert
Returns
string representation of DeviceStateTransition enum entry
Definition at line 106 of file PluginServices.h.
References fkStrDeviceStateTransitionMap.
auto fair::mq::PluginServices::UnsubscribeFromDeviceStateChange (const std::string & subscriber) -> void inline
Unsubscribe from device state changes.
Parameters
subscriber id
Definition at line 165 of file PluginServices.h.
References fDevice.
Referenced by fair::mq::Plugin::UnsubscribeFromDeviceStateChange().
template<typename T > auto fair::mq::PluginServices::UnsubscribeFromPropertyChange (const std::string & subscriber) -> void inline
Unsubscribe from property updates of type T.
Parameters
subscriber
Definition at line 240 of file PluginServices.h.
References fConfig, and FairMQProgOptions::Unsubscribe().
Referenced by fair::mq::Plugin::UnsubscribeFromPropertyChange().
auto fair::mq::PluginServices::UnsubscribeFromPropertyChangeAsString (const std::string & subscriber) -> void inline
Unsubscribe from property updates that convert to string.
Parameters
subscriber
Definition at line 254 of file PluginServices.h.
References fConfig, and FairMQProgOptions::UnsubscribeAsString().
Referenced by fair::mq::Plugin::UnsubscribeFromPropertyChangeAsString().
auto PluginServices::WaitForReleaseDeviceControl () -> void
Block until control is released.
Definition at line 165 of file PluginServices.cxx.
Friends And Related Function Documentation
auto operator<< (std::ostream & os, const DeviceState & state) -> std::ostream& friend
Definition at line 108 of file PluginServices.h.
auto operator<< (std::ostream & os, const DeviceStateTransition & transition) -> std::ostream& friend
Definition at line 109 of file PluginServices.h.
Member Data Documentation
FairMQProgOptions* fair::mq::PluginServices::fConfig private
Definition at line 265 of file PluginServices.h.
Referenced by GetChannelInfo(), GetProperty(), GetPropertyAsString(), GetPropertyKeys(), PropertyExists(), SetProperty(), SubscribeToPropertyChange(), SubscribeToPropertyChangeAsString(), UnsubscribeFromPropertyChange(), and UnsubscribeFromPropertyChangeAsString().
std::shared_ptr<FairMQDevice> fair::mq::PluginServices::fDevice private
Definition at line 266 of file PluginServices.h.
Referenced by GetCurrentDeviceState(), SubscribeToDeviceStateChange(), and UnsubscribeFromDeviceStateChange().
boost::optional<std::string> fair::mq::PluginServices::fDeviceController private
Definition at line 267 of file PluginServices.h.
std::mutex fair::mq::PluginServices::fDeviceControllerMutex mutable private
Definition at line 268 of file PluginServices.h.
const std::unordered_map< FairMQDevice::State, PluginServices::DeviceState, fair::mq::tools::HashEnum< FairMQDevice::State > > PluginServices::fkDeviceStateMap static
Initial value:
= {
    {FairMQDevice::OK,                  DeviceState::Ok},
    {FairMQDevice::Error,               DeviceState::Error},
    {FairMQDevice::IDLE,                DeviceState::Idle},
    {FairMQDevice::INITIALIZING_DEVICE, DeviceState::InitializingDevice},
    {FairMQDevice::DEVICE_READY,        DeviceState::DeviceReady},
    {FairMQDevice::INITIALIZING_TASK,   DeviceState::InitializingTask},
    {FairMQDevice::READY,               DeviceState::Ready},
    {FairMQDevice::RUNNING,             DeviceState::Running},
    {FairMQDevice::PAUSED,              DeviceState::Paused},
    {FairMQDevice::RESETTING_TASK,      DeviceState::ResettingTask},
    {FairMQDevice::RESETTING_DEVICE,    DeviceState::ResettingDevice},
    {FairMQDevice::EXITING,             DeviceState::Exiting}
}
Definition at line 261 of file PluginServices.h.
Referenced by GetCurrentDeviceState(), and SubscribeToDeviceStateChange().
const std::unordered_map< std::string, PluginServices::DeviceState > PluginServices::fkDeviceStateStrMap static
Initial value:
= {
    {"OK",                  DeviceState::Ok},
    {"ERROR",               DeviceState::Error},
    {"IDLE",                DeviceState::Idle},
    {"INITIALIZING DEVICE", DeviceState::InitializingDevice},
    {"DEVICE READY",        DeviceState::DeviceReady},
    {"INITIALIZING TASK",   DeviceState::InitializingTask},
    {"READY",               DeviceState::Ready},
    {"RUNNING",             DeviceState::Running},
    {"PAUSED",              DeviceState::Paused},
    {"RESETTING TASK",      DeviceState::ResettingTask},
    {"RESETTING DEVICE",    DeviceState::ResettingDevice},
    {"EXITING",             DeviceState::Exiting}
}
Definition at line 257 of file PluginServices.h.
Referenced by ToDeviceState().
const std::unordered_map< PluginServices::DeviceStateTransition, FairMQDevice::Event, tools::HashEnum< PluginServices::DeviceStateTransition > > PluginServices::fkDeviceStateTransitionMap static
Initial value:
= {
    {DeviceStateTransition::InitDevice,  FairMQDevice::INIT_DEVICE},
    {DeviceStateTransition::InitTask,    FairMQDevice::INIT_TASK},
    {DeviceStateTransition::Run,         FairMQDevice::RUN},
    {DeviceStateTransition::Pause,       FairMQDevice::PAUSE},
    {DeviceStateTransition::Resume,      FairMQDevice::RUN},
    {DeviceStateTransition::Stop,        FairMQDevice::STOP},
    {DeviceStateTransition::ResetTask,   FairMQDevice::RESET_TASK},
    {DeviceStateTransition::ResetDevice, FairMQDevice::RESET_DEVICE},
    {DeviceStateTransition::End,         FairMQDevice::END},
    {DeviceStateTransition::ErrorFound,  FairMQDevice::ERROR_FOUND}
}
Definition at line 262 of file PluginServices.h.
const std::unordered_map< std::string, PluginServices::DeviceStateTransition > PluginServices::fkDeviceStateTransitionStrMap static
Initial value:
= {
    {"INIT DEVICE",  DeviceStateTransition::InitDevice},
    {"INIT TASK",    DeviceStateTransition::InitTask},
    {"RUN",          DeviceStateTransition::Run},
    {"PAUSE",        DeviceStateTransition::Pause},
    {"RESUME",       DeviceStateTransition::Resume},
    {"STOP",         DeviceStateTransition::Stop},
    {"RESET TASK",   DeviceStateTransition::ResetTask},
    {"RESET DEVICE", DeviceStateTransition::ResetDevice},
    {"END",          DeviceStateTransition::End},
    {"ERROR FOUND",  DeviceStateTransition::ErrorFound},
}
Definition at line 259 of file PluginServices.h.
Referenced by ToDeviceStateTransition().
const std::unordered_map< PluginServices::DeviceState, std::string, tools::HashEnum< PluginServices::DeviceState > > PluginServices::fkStrDeviceStateMap static
Initial value:
= {
    {DeviceState::Ok,                 "OK"},
    {DeviceState::Error,              "ERROR"},
    {DeviceState::Idle,               "IDLE"},
    {DeviceState::InitializingDevice, "INITIALIZING DEVICE"},
    {DeviceState::DeviceReady,        "DEVICE READY"},
    {DeviceState::InitializingTask,   "INITIALIZING TASK"},
    {DeviceState::Ready,              "READY"},
    {DeviceState::Running,            "RUNNING"},
    {DeviceState::Paused,             "PAUSED"},
    {DeviceState::ResettingTask,      "RESETTING TASK"},
    {DeviceState::ResettingDevice,    "RESETTING DEVICE"},
    {DeviceState::Exiting,            "EXITING"}
}
Definition at line 258 of file PluginServices.h.
Referenced by ToStr().
const std::unordered_map< PluginServices::DeviceStateTransition, std::string, tools::HashEnum< PluginServices::DeviceStateTransition > > PluginServices::fkStrDeviceStateTransitionMap static
Initial value:
= {
    {DeviceStateTransition::InitDevice,  "INIT DEVICE"},
    {DeviceStateTransition::InitTask,    "INIT TASK"},
    {DeviceStateTransition::Run,         "RUN"},
    {DeviceStateTransition::Pause,       "PAUSE"},
    {DeviceStateTransition::Resume,      "RESUME"},
    {DeviceStateTransition::Stop,        "STOP"},
    {DeviceStateTransition::ResetTask,   "RESET TASK"},
    {DeviceStateTransition::ResetDevice, "RESET DEVICE"},
    {DeviceStateTransition::End,         "END"},
    {DeviceStateTransition::ErrorFound,  "ERROR FOUND"},
}
Definition at line 260 of file PluginServices.h.
Referenced by ToStr().
std::condition_variable fair::mq::PluginServices::fReleaseDeviceControlCondition private
Definition at line 269 of file PluginServices.h.
The documentation for this class was generated from the following files:
PluginServices.h
PluginServices.cxx