FairRroot: FairGeoIo Class Reference
FairGeoIo Class Reference abstract
#include <FairGeoIo.h>
Public Member Functions
virtual Bool_t open (const char *, const Text_t *status="in")=0
virtual void close ()=0
virtual void print ()=0
virtual Bool_t isOpen ()=0
virtual Bool_t isWritable ()=0
virtual Bool_t read (FairGeoMedia *)=0
virtual Bool_t read (FairGeoSet *, FairGeoMedia *)=0
virtual Bool_t write (FairGeoMedia *)=0
virtual Bool_t write (FairGeoSet *)=0
virtual Bool_t readGeomConfig (FairGeoInterface *)=0
virtual Bool_t setSimulRefRun (const char *)=0
virtual Bool_t setHistoryDate (const char *)=0
Detailed Description
Abstract base class for geometry I/O
Author
Ilse Koenig
Definition at line 23 of file FairGeoIo.h.
Member Function Documentation
virtual void FairGeoIo::close () pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
virtual Bool_t FairGeoIo::isOpen () pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
Referenced by FairGeoInterface::connectInput(), FairGeoInterface::connectOutput(), FairGeoInterface::writeMedia(), and FairGeoInterface::writeSet().
virtual Bool_t FairGeoIo::isWritable () pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
Referenced by FairGeoInterface::connectOutput().
virtual Bool_t FairGeoIo::open (const char * , const Text_t * status = "in") pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
Referenced by FairGeoInterface::connectInput(), FairGeoInterface::connectOutput(), FairGeoInterface::writeMedia(), and FairGeoInterface::writeSet().
virtual void FairGeoIo::print () pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
virtual Bool_t FairGeoIo::read (FairGeoMedia *) pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
Referenced by FairGeoInterface::readMedia(), and FairGeoInterface::readSet().
virtual Bool_t FairGeoIo::read (FairGeoSet * , FairGeoMedia *) pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
virtual Bool_t FairGeoIo::readGeomConfig (FairGeoInterface *) pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
Referenced by FairGeoInterface::createGeometry(), FairGeoInterface::readAll(), and FairGeoInterface::readGeomConfig().
virtual Bool_t FairGeoIo::setHistoryDate (const char *) pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
Referenced by FairGeoAsciiIo::readGeomConfig().
virtual Bool_t FairGeoIo::setSimulRefRun (const char *) pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
Referenced by FairGeoAsciiIo::readGeomConfig().
virtual Bool_t FairGeoIo::write (FairGeoMedia *) pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
Referenced by FairGeoInterface::writeMedia(), and FairGeoInterface::writeSet().
virtual Bool_t FairGeoIo::write (FairGeoSet *) pure virtual
Implemented in FairGeoOldAsciiIo, and FairGeoAsciiIo.
The documentation for this class was generated from the following file:
FairGeoIo.h