FairRoot: FairCave Class Reference
FairCave Class Reference
#include <FairCave.h>
Public Member Functions
FairCave (const char *name, const char *Title="Exp Cave")
FairCave ()
virtual ~FairCave ()
virtual void ConstructGeometry ()
virtual FairModule * CloneModule () const
virtual void Print (Option_t *) const
virtual void SetGeometryFileName (TString fname, TString geoVer="0")
virtual TString GetGeometryFileName ()
virtual TString GetGeometryFileVer ()
virtual void ConstructOpGeometry ()
virtual void ConstructRootGeometry (TGeoMatrix *shiftM=NULL)
virtual void ConstructASCIIGeometry ()
template<class T , class U >
void ConstructASCIIGeometry (T dataType1, TString containerName="", U datatype2=NULL)
virtual void ModifyGeometry ()
virtual void ConstructGDMLGeometry (TGeoMatrix *)
virtual void SetSpecialPhysicsCuts ()
virtual void BeginWorkerRun () const
virtual void FinishWorkerRun () const
virtual Bool_t CheckIfSensitive (std::string name)
virtual void ExpandNode (TGeoNode *Node)
virtual void ExpandNodeForGDML (TGeoNode *)
virtual Int_t getVolId (const TString &) const
Int_t GetModId ()
void SetVerboseLevel (Int_t level)
Bool_t IsActive ()
void SetModId (Int_t id)
void SetMotherVolume (TString volName)
void ProcessNodes (TList *aList)
virtual void SetParContainers ()
virtual void InitParContainers ()
TList * GetListOfGeoPar ()
FairVolume * getFairVolume (FairGeoNode *fNode)
void AddSensitiveVolume (TGeoVolume *v)
Public Attributes
TString fMotherVolumeName
Static Public Attributes
static thread_local FairVolumeList * vList =0
static thread_local Int_t fNbOfVolumes =0
static thread_local TRefArray * svList =0
static thread_local TArrayI * volNumber =0
Protected Attributes
TString fgeoVer
TString fgeoName
Int_t fModId
Bool_t fActive
Int_t fNbOfSensitiveVol
Int_t fVerboseLevel
TList * flGeoPar
Bool_t fGeoSaved
list of Detector Geometry parameters
TVirtualMC * fMC
flag for initialisation
Private Member Functions
FairCave (const FairCave &rhs)
Private Attributes
Double_t world [3]
Detailed Description
Definition at line 15 of file FairCave.h.
Constructor & Destructor Documentation
FairCave() [1/3]
FairCave::FairCave (const char * name, const char * Title = "Exp Cave")
Definition at line 78 of file FairCave.cxx.
References world.
FairCave() [2/3]
FairCave::FairCave ()
Definition at line 70 of file FairCave.cxx.
Referenced by CloneModule().
~FairCave()
FairCave::~FairCave () virtual
Definition at line 74 of file FairCave.cxx.
FairCave() [3/3]
FairCave::FairCave (const FairCave & rhs) private
Definition at line 62 of file FairCave.cxx.
References world.
Member Function Documentation
AddSensitiveVolume()
void FairModule::AddSensitiveVolume (TGeoVolume * v) inherited
Definition at line 298 of file FairModule.cxx.
References FairVolumeList::addVolume(), FairVolumeList::findObject(), FairModule::fModId, FairModule::fNbOfSensitiveVol, FairModule::fNbOfVolumes, FairVolume::setModId(), FairVolume::SetModule(), FairModule::svList, and FairModule::vList.
Referenced by FairDetector::DefineSensitiveVolumes(), and FairModule::ExpandNode().
BeginWorkerRun()
virtual void FairModule::BeginWorkerRun () const inline virtual inherited
Init worker run (used in MT mode only)
Definition at line 85 of file FairModule.h.
CheckIfSensitive()
Bool_t FairModule::CheckIfSensitive (std::string name) virtual inherited
Set the sensitivity flag for volumes, called from ConstructASCIIRootGeometry(), and has to be implimented for detectors which use ConstructASCIIRootGeometry() to build the geometry
Reimplemented in FairTutorialDet4, and FairMagnet.
Definition at line 563 of file FairModule.cxx.
Referenced by FairDetector::DefineSensitiveVolumes(), and FairModule::ExpandNode().
CloneModule()
FairModule * FairCave::CloneModule () const virtual
Clone this object (used in MT mode only)
Reimplemented from FairModule.
Definition at line 86 of file FairCave.cxx.
References FairCave().
ConstructASCIIGeometry() [1/2]
void FairModule::ConstructASCIIGeometry () virtual inherited
construct geometry from standard ASSCII files (Hades Format)
Reimplemented in FairTutorialDet4, and FairMagnet.
Definition at line 557 of file FairModule.cxx.
ConstructASCIIGeometry() [2/2]
template<class T , class U > void FairModule::ConstructASCIIGeometry (T dataType1, TString containerName = "", U datatype2 = NULL) inherited
template function to construct geometry. to be used in derived classes.
Definition at line 161 of file FairModule.h.
References FairGeoInterface::addGeoModule(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairModule::GetGeometryFileName(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairGeoLoader::Instance(), FairRun::Instance(), FairGeoNode::isSensitive(), par, FairModule::ProcessNodes(), FairGeoInterface::readSet(), FairParSet::setChanged(), and FairParSet::setInputVersion().
ConstructGDMLGeometry()
void FairModule::ConstructGDMLGeometry (TGeoMatrix * posrot) virtual inherited
construct geometry from GDML files
Definition at line 505 of file FairModule.cxx.
References gLogger, and MESSAGE_ORIGIN.
ConstructGeometry()
virtual void FairCave::ConstructGeometry () virtual
method called from the MC application to construct the geometry, has to be implimented by user
Reimplemented from FairModule.
ConstructOpGeometry()
void FairModule::ConstructOpGeometry () virtual inherited
method called from the MC application to set optical geometry properties
Definition at line 68 of file FairModule.cxx.
Referenced by FairMCApplication::ConstructOpGeometry().
ConstructRootGeometry()
void FairModule::ConstructRootGeometry (TGeoMatrix * shiftM = NULL) virtual inherited
construct geometry from root files (TGeo)
Construct the detector geometry from ROOT files, possible inputs are:
A TGeoVolume as a mother (master) volume containing the detector geometry
A TGeoManager with the detector geometry
A TGeoVolume as a mother or Master volume which is the output of the CAD2ROOT geometry, in this case the materials are not proprely defined and had to be reset In all cases we have to check that the material properties are the same or is the materials defined in the current simulation session
loop inside the delivered root file and try to fine a TGeoManager object the first TGeoManager found will be read
in case a TGeoManager was found get the top most volume and the node
The file does not contain any TGeoManager, so we assume to have a file with a TGeoVolume try to look for a TGeoVolume inside the file
Everything is OK, we have a TGeoVolume and now we add it to the simulation TGeoManager
Force rebuilding of voxels
To avoid having different names of the default matrices because we could have get the volume from another TGeoManager, we reset the default matrix name
Now we can remove the matrix so that the new geomanager will rebuild it properly
Now we can add the node to the existing cave
correction from O. Merle: in case of a TGeoVolume (v1) set the material properly
now go through the herachy and set the materials properly, this is important becase the CAD converter produce TGeoVolumes with materials that have only names and no properties
Definition at line 333 of file FairModule.cxx.
References FairModule::AssignMediumAtImport(), FairModule::ExpandNode(), FairModule::fMotherVolumeName, FairModule::GetGeometryFileName(), and FairModule::SetDefaultMatrixName().
Referenced by FairMagnet::ConstructGeometry(), and FairTutorialDet4::ConstructGeometry().
ExpandNode()
void FairModule::ExpandNode (TGeoNode * Node) virtual inherited
called from ConstructRootGeometry()
Definition at line 570 of file FairModule.cxx.
References FairModule::AddSensitiveVolume(), FairModule::AssignMediumAtImport(), FairModule::CheckIfSensitive(), and FairModule::SetDefaultMatrixName().
Referenced by FairModule::ConstructRootGeometry().
ExpandNodeForGDML()
void FairModule::ExpandNodeForGDML (TGeoNode * curNode) virtual inherited
called from ConstructGDMLGeometry()
Definition at line 513 of file FairModule.cxx.
FinishWorkerRun()
virtual void FairModule::FinishWorkerRun () const inline virtual inherited
Finish worker run (used in MT mode only)
Definition at line 87 of file FairModule.h.
getFairVolume()
FairVolume * FairModule::getFairVolume (FairGeoNode * fNode) inherited
Definition at line 318 of file FairModule.cxx.
References FairVolumeList::At(), FairVolumeList::getEntries(), FairVolume::getGeoNode(), and FairModule::vList.
GetGeometryFileName()
virtual TString FairModule::GetGeometryFileName () inline virtual inherited
Get the Geometry file name
Definition at line 64 of file FairModule.h.
References FairModule::fgeoName.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairMagnet::ConstructGeometry(), FairTestDetector::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet4::ConstructGeometry(), FairModule::ConstructRootGeometry(), and FairTutorialDet4::Initialize().
GetGeometryFileVer()
virtual TString FairModule::GetGeometryFileVer () inline virtual inherited
Get the geometry file version if used
Definition at line 66 of file FairModule.h.
References FairModule::fgeoVer.
GetListOfGeoPar()
TList* FairModule::GetListOfGeoPar () inline inherited
return the geo parameter of this detector/module
Definition at line 122 of file FairModule.h.
References FairModule::flGeoPar.
GetModId()
Int_t FairModule::GetModId () inline inherited
return the detector/Module id (which was set in the sim macro for the detector)
Definition at line 103 of file FairModule.h.
References FairModule::fModId.
Referenced by FairMCApplication::ConstructGeometry(), and FairDetector::Initialize().
getVolId()
virtual Int_t FairModule::getVolId (const TString &) const inline virtual inherited
return the MC id of a volume named vname
Definition at line 101 of file FairModule.h.
InitParContainers()
virtual void FairModule::InitParContainers () inline virtual inherited
Initialize everything which has to be done before the construction and modification of the geometry. Mostly this is needed to read data from the parameter containers.
Reimplemented in FairTutorialDet4.
Definition at line 120 of file FairModule.h.
Referenced by FairMCApplication::ConstructGeometry().
IsActive()
Bool_t FairModule::IsActive () inline inherited
return the detector status
Definition at line 107 of file FairModule.h.
References FairModule::fActive.
Referenced by FairMCApplication::FairMCApplication(), FairMCApplication::InitGeometry(), and FairMCApplication::operator=().
ModifyGeometry()
virtual void FairModule::ModifyGeometry () inline virtual inherited
Modify the geometry for the simulation run using methods of the Root geometry package
Reimplemented in FairTutorialDet4, and Pixel.
Definition at line 76 of file FairModule.h.
Referenced by FairMCApplication::ConstructGeometry().
Print()
virtual void FairModule::Print (Option_t *) const inline virtual inherited
Print method should be implemented in detector or module
Definition at line 60 of file FairModule.h.
ProcessNodes()
void FairModule::ProcessNodes (TList * aList) inherited
called from ConstuctASCIIGeometry
Definition at line 259 of file FairModule.cxx.
References FairVolumeList::addVolume(), FairGeoNode::calcLabTransform(), FairModule::fActive, FairModule::fModId, FairModule::fNbOfSensitiveVol, FairModule::fNbOfVolumes, FairRuntimeDb::getContainer(), FairGeoNode::getCopyNo(), FairGeoVolume::getMCid(), FairGeoNode::getMotherNode(), FairRun::GetRuntimeDb(), FairGeoNode::getTruncName(), FairRun::Instance(), FairGeoNode::isSensitive(), par, FairVolume::setCopyNo(), FairVolume::setGeoNode(), FairVolume::setModId(), FairVolume::SetModule(), FairVolume::setMotherCopyNo(), FairVolume::setMotherId(), FairVolume::setRealName(), FairModule::svList, and FairModule::vList.
Referenced by FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), and FairTutorialDet4::SetSensitiveVolumes().
SetGeometryFileName()
void FairModule::SetGeometryFileName (TString fname, TString geoVer = "0") virtual inherited
Set the geometry file name o be used
Definition at line 207 of file FairModule.cxx.
References FairModule::fgeoName.
Referenced by getDevice(), run_bg(), run_rad(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), run_tutorial2(), run_tutorial4(), and TEST().
SetModId()
void FairModule::SetModId (Int_t id) inline inherited
set the detector/module id
Definition at line 109 of file FairModule.h.
References FairModule::fModId.
Referenced by FairRunSim::AddModule().
SetMotherVolume()
void FairModule::SetMotherVolume (TString volName) inline inherited
Set the name of the mother volume to which a new geometry is added. This function is needed for geometries which are defined as ROOT geometry manager.
Definition at line 113 of file FairModule.h.
References FairModule::fMotherVolumeName.
SetParContainers()
virtual void FairModule::SetParContainers () inline virtual inherited
Set the parameter containers
Reimplemented in FairTutorialDet4.
Definition at line 117 of file FairModule.h.
Referenced by FairMCApplication::SetParTask().
SetSpecialPhysicsCuts()
virtual void FairModule::SetSpecialPhysicsCuts () inline virtual inherited
custom settings of processes and cuts for media to be forwarded to the detector simulation
Reimplemented in FairTutorialDet4, Pixel, FairRutherford, FairTutorialDet1, FairTutorialDet2, FairTestDetector, NewDetector, and NewDetector.
Definition at line 81 of file FairModule.h.
Referenced by FairMCApplication::InitGeometry().
SetVerboseLevel()
void FairModule::SetVerboseLevel (Int_t level) inline inherited
Set the verbose level in this detector
Definition at line 105 of file FairModule.h.
References FairModule::fVerboseLevel.
Member Data Documentation
fActive
Bool_t FairModule::fActive protected inherited
Definition at line 150 of file FairModule.h.
Referenced by FairModule::IsActive(), FairModule::operator=(), and FairModule::ProcessNodes().
fgeoName
TString FairModule::fgeoName protected inherited
Definition at line 148 of file FairModule.h.
Referenced by FairModule::GetGeometryFileName(), FairModule::operator=(), and FairModule::SetGeometryFileName().
fGeoSaved
Bool_t FairModule::fGeoSaved protected inherited
list of Detector Geometry parameters
Definition at line 154 of file FairModule.h.
Referenced by FairDetector::FairDetector(), FairModule::operator=(), and FairDetector::SaveGeoParams().
fgeoVer
TString FairModule::fgeoVer protected inherited
Definition at line 147 of file FairModule.h.
Referenced by FairModule::GetGeometryFileVer(), and FairModule::operator=().
flGeoPar
TList* FairModule::flGeoPar protected inherited
Definition at line 153 of file FairModule.h.
Referenced by FairDetector::FairDetector(), FairModule::GetListOfGeoPar(), FairModule::operator=(), FairDetector::SaveGeoParams(), and FairDetector::~FairDetector().
fMC
TVirtualMC* FairModule::fMC protected inherited
flag for initialisation
Definition at line 155 of file FairModule.h.
Referenced by FairModule::FairModule(), and FairDetector::Initialize().
fModId
Int_t FairModule::fModId protected inherited
Definition at line 149 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::GetModId(), FairModule::operator=(), FairModule::ProcessNodes(), and FairModule::SetModId().
fMotherVolumeName
TString FairModule::fMotherVolumeName inherited
Definition at line 132 of file FairModule.h.
Referenced by FairModule::ConstructRootGeometry(), FairModule::operator=(), and FairModule::SetMotherVolume().
fNbOfSensitiveVol
Int_t FairModule::fNbOfSensitiveVol protected inherited
Definition at line 151 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::operator=(), and FairModule::ProcessNodes().
fNbOfVolumes
thread_local Int_t FairModule::fNbOfVolumes =0 static inherited
total number of volumes in a simulaion session
Definition at line 127 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), and FairModule::ProcessNodes().
fVerboseLevel
Int_t FairModule::fVerboseLevel protected inherited
Definition at line 152 of file FairModule.h.
Referenced by FairModule::operator=(), and FairModule::SetVerboseLevel().
svList
thread_local TRefArray * FairModule::svList =0 static inherited
list of all sensitive volumes in a simulaion session
Definition at line 129 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::FairModule(), FairMCApplication::InitGeometry(), FairDetector::Initialize(), and FairModule::ProcessNodes().
vList
thread_local FairVolumeList * FairModule::vList =0 static inherited
list of volumes in a simulation session
Definition at line 125 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::FairModule(), FairModule::getFairVolume(), and FairModule::ProcessNodes().
volNumber
thread_local TArrayI * FairModule::volNumber =0 static inherited
Definition at line 131 of file FairModule.h.
world
Double_t FairCave::world[3] private
Definition at line 27 of file FairCave.h.
Referenced by FairCave().
The documentation for this class was generated from the following files:
FairCave.h
FairCave.cxx