FairRroot: FairMQProgOptions Class Reference
FairMQProgOptions Class Reference
#include <FairMQProgOptions.h>
Classes
struct MQKey
Public Member Functions
FairMQProgOptions ()
virtual ~FairMQProgOptions ()
int ParseAll (const std::vector< std::string > &cmdLineArgs, bool allowUnregistered)
int ParseAll (const int argc, char const *const *argv, bool allowUnregistered=false) override
FairMQMap GetFairMQMap () const
std::unordered_map< std::string, int > GetChannelInfo () const
template<typename T >
int UpdateValue (const std::string &key, T val)
template<typename T >
int SetValue (const std::string &key, T val)
template<typename T >
void Subscribe (const std::string &subscriber, std::function< void(typename fair::mq::PropertyChange::KeyType, T)> func)
template<typename T >
void Unsubscribe (const std::string &subscriber)
void SubscribeAsString (const std::string &subscriber, std::function< void(typename fair::mq::PropertyChange::KeyType, std::string)> func)
void UnsubscribeAsString (const std::string &subscriber)
int UpdateChannelMap (const FairMQMap &map)
auto GetPropertyKeys () const -> std::vector< std::string >
int AddToCmdLineOptions (const po::options_description optDesc, bool visible=true)
Add option descriptions.
po::options_description & GetCmdLineOptions ()
template<typename T >
T GetValue (const std::string &key) const
std::string GetStringValue (const std::string &key)
int Count (const std::string &key) const
template<typename T >
T ConvertTo (const std::string &strValue)
const po::variables_map & GetVarMap () const
int ParseCmdLine (const int argc, char const *const *argv, bool allowUnregistered=false)
void ParseDefaults ()
virtual int PrintOptions ()
virtual int PrintOptionsRaw ()
Protected Types
using FairMQMap = std::unordered_map< std::string, std::vector< FairMQChannel >>
Protected Member Functions
int ImmediateOptions () override
void InitOptionDescription ()
void UpdateMQValues ()
int Store (const FairMQMap &channels)
template<typename T >
void UpdateVarMap (const std::string &key, const T &val)
template<typename T >
void Replace (std::map< std::string, po::variable_value > &vm, const std::string &key, const T &val)
Protected Attributes
po::options_description fMQCmdOptions
po::options_description fMQParserOptions
FairMQMap fFairMQMap
std::unordered_map< std::string, int > fChannelInfo
std::map< std::string, MQKey > fMQKeyMap
po::variables_map fVarMap
po::options_description fGeneralOptions
po::options_description fAllOptions
std::mutex fConfigMutex
Private Member Functions
template<typename T >
void EmitUpdate (const std::string &key, T val)
int UpdateChannelMap (const std::string &channelName, int index, const std::string &member, const std::string &val)
int UpdateChannelMap (const std::string &channelName, int index, const std::string &member, int val)
template<typename T >
int UpdateChannelMap (const std::string &, int, const std::string &, T)
void UpdateChannelInfo ()
Private Attributes
fair::mq::EventManager fEvents
Detailed Description
Definition at line 41 of file FairMQProgOptions.h.
Member Typedef Documentation
using FairMQProgOptions::FairMQMap = std::unordered_map<std::string, std::vector<FairMQChannel>> protected
Definition at line 44 of file FairMQProgOptions.h.
Constructor & Destructor Documentation
FairMQProgOptions::FairMQProgOptions ()
Definition at line 25 of file FairMQProgOptions.cxx.
References InitOptionDescription(), and FairProgOptions::ParseDefaults().
FairMQProgOptions::~FairMQProgOptions () virtual
Definition at line 37 of file FairMQProgOptions.cxx.
Member Function Documentation
int FairProgOptions::AddToCmdLineOptions (const po::options_description optDesc, bool visible = true) inherited
Add option descriptions.
Definition at line 47 of file FairProgOptions.cxx.
References FairProgOptions::fAllOptions.
Referenced by InitOptionDescription(), and main().
template<typename T > T FairProgOptions::ConvertTo (const std::string & strValue) inline inherited
Definition at line 110 of file FairProgOptions.h.
References LOG.
int FairProgOptions::Count (const std::string & key) const inline inherited
Definition at line 101 of file FairProgOptions.h.
References FairProgOptions::fConfigMutex, and FairProgOptions::fVarMap.
Referenced by fair::mq::PluginServices::PropertyExists().
template<typename T > void FairMQProgOptions::EmitUpdate (const std::string & key, T val) inline private
Definition at line 188 of file FairMQProgOptions.h.
References fair::mq::EventManager::Emit(), fEvents, and FairProgOptions::GetStringValue().
std::unordered_map<std::string, int> FairMQProgOptions::GetChannelInfo () const inline
Definition at line 60 of file FairMQProgOptions.h.
References fChannelInfo.
Referenced by fair::mq::PluginServices::GetChannelInfo().
po::options_description & FairProgOptions::GetCmdLineOptions () inherited
Definition at line 53 of file FairProgOptions.cxx.
References FairProgOptions::fAllOptions.
Referenced by main().
FairMQMap FairMQProgOptions::GetFairMQMap () const inline
Definition at line 55 of file FairMQProgOptions.h.
References fFairMQMap.
Referenced by main(), and FairMQDevice::SetConfig().
auto FairProgOptions::GetPropertyKeys () const -> std::vector<std::string> inline inherited
Definition at line 41 of file FairProgOptions.h.
References FairProgOptions::fConfigMutex, and FairProgOptions::fVarMap.
Referenced by fair::mq::PluginServices::GetPropertyKeys().
std::string FairProgOptions::GetStringValue (const std::string & key) inline inherited
Definition at line 80 of file FairProgOptions.h.
References FairProgOptions::fConfigMutex, FairProgOptions::fVarMap, and LOG.
Referenced by EmitUpdate(), fair::mq::PluginServices::GetPropertyAsString(), SetValue(), testJSON2(), testXML2(), and UpdateValue().
template<typename T > T FairProgOptions::GetValue (const std::string & key) const inline inherited
Definition at line 61 of file FairProgOptions.h.
References FairProgOptions::fConfigMutex, FairProgOptions::fVarMap, and LOG.
Referenced by FairMQDevice::CreateOwnConfig(), getDevice(), fair::mq::PluginServices::GetProperty(), Ex1Processor::Init(), Ex2Processor::Init(), Ex1Sampler::Init(), FairMQEx9aFileSinkBin::Init(), FairMQShmPrototypeSampler::Init(), Ex2Sampler::Init(), Ex1Sink::Init(), FairMQEx9FileSink::Init(), FairMQEx9FileSinkBin::Init(), Ex2Sink::Init(), FairTestDetectorFileSink< TIn, TPayloadIn >::Init(), FairMQExampleMTSampler1::InitTask(), FairMQExampleMTSampler2::InitTask(), FairMQExample1Sink::InitTask(), FairMQExample2Sink::InitTask(), FairMQExample4Sink::InitTask(), FairMQExample5Server::InitTask(), FairMQExample8Sampler::InitTask(), FairMQExampleMTSink::InitTask(), FairMQMultiplier::InitTask(), FairMQExample4Sampler::InitTask(), FairMQExampleRegionSampler::InitTask(), FairMQExampleRegionSink::InitTask(), FairMQExample6Sink::InitTask(), FairMQExample7Client::InitTask(), FairMQExample1Sampler::InitTask(), FairMQExample2Sampler::InitTask(), FairMQProxy::InitTask(), FairMQExample5Client::InitTask(), FairMQExample6Sampler::InitTask(), FairMQMerger::InitTask(), FairMQSplitter::InitTask(), ParameterMQServer::InitTask(), FairMQProcessor< Task >::InitTask(), FairMQSink::InitTask(), FairMQBenchmarkSampler::InitTask(), FairMQEx9SamplerBin::InitTask(), FairMQEx9Sampler::InitTask(), FairMQEx9aSamplerBin::InitTask(), FairMQUnpacker< UnpackerType, SerializationType >::InitTask(), FairMQSampler< Task >::InitTask(), FairMQLmdSampler::InitTask(), FairMQDevice::InitWrapper(), main(), FairMQDevice::SetConfig(), RootOutFileManager< DataType >::SetFileProperties(), testJSON1(), testJSON2(), testXML1(), and testXML2().
const po::variables_map& FairProgOptions::GetVarMap () const inline inherited
Definition at line 125 of file FairProgOptions.h.
References FairProgOptions::fVarMap.
Referenced by main().
int FairMQProgOptions::ImmediateOptions () override protected virtual
Implements FairProgOptions.
Definition at line 212 of file FairMQProgOptions.cxx.
References FairProgOptions::fAllOptions, FairProgOptions::fVarMap, and FairProgOptions::PrintOptionsRaw().
void FairMQProgOptions::InitOptionDescription () protected
Definition at line 229 of file FairMQProgOptions.cxx.
References FairProgOptions::AddToCmdLineOptions(), fMQCmdOptions, and fMQParserOptions.
Referenced by FairMQProgOptions().
int FairMQProgOptions::ParseAll (const std::vector< std::string > & cmdLineArgs, bool allowUnregistered)
Referenced by FairMQDevice::CreateOwnConfig(), and main().
int FairMQProgOptions::ParseAll (const int argc, char const *const * argv, bool allowUnregistered = false) override virtual
Implements FairProgOptions.
Definition at line 53 of file FairMQProgOptions.cxx.
References fMQParserOptions, FairProgOptions::fVarMap, fair::Logger::InitFileSink(), LOG, FairProgOptions::ParseCmdLine(), FairProgOptions::PrintOptions(), fair::Logger::SetConsoleColor(), fair::Logger::SetConsoleSeverity(), fair::Logger::SetVerbosity(), and Store().
int FairProgOptions::ParseCmdLine (const int argc, char const *const * argv, bool allowUnregistered = false) inherited
Definition at line 58 of file FairProgOptions.cxx.
References FairProgOptions::fAllOptions, FairProgOptions::fVarMap, and FairProgOptions::ImmediateOptions().
Referenced by ParseAll().
void FairProgOptions::ParseDefaults () inherited
Definition at line 85 of file FairProgOptions.cxx.
References FairProgOptions::fAllOptions, and FairProgOptions::fVarMap.
Referenced by FairMQProgOptions().
int FairProgOptions::PrintOptions () virtual inherited
Definition at line 100 of file FairProgOptions.cxx.
References FairProgOptions::fVarMap, FairProgOptions::GetVariableValueInfo(), LOG, and FairProgOptions::Max().
Referenced by ParseAll().
int FairProgOptions::PrintOptionsRaw () virtual inherited
Definition at line 153 of file FairProgOptions.cxx.
References FairProgOptions::fAllOptions, FairProgOptions::fVarMap, FairProgOptions::GetVariableValueInfo(), fair::mq::VarValInfo::type, and fair::mq::VarValInfo::value.
Referenced by ImmediateOptions().
template<typename T > void FairProgOptions::Replace (std::map< std::string, po::variable_value > & vm, const std::string & key, const T & val) inline protected inherited
Definition at line 155 of file FairProgOptions.h.
Referenced by FairProgOptions::UpdateVarMap().
template<typename T > int FairMQProgOptions::SetValue (const std::string & key, T val) inline
Definition at line 100 of file FairMQProgOptions.h.
References fair::mq::EventManager::Emit(), FairProgOptions::fConfigMutex, fEvents, fMQKeyMap, FairProgOptions::GetStringValue(), and UpdateChannelMap().
Referenced by FairMQDevice::AttachChannel(), and fair::mq::PluginServices::SetProperty().
int FairMQProgOptions::Store (const FairMQMap & channels) protected
Definition at line 140 of file FairMQProgOptions.cxx.
References fFairMQMap, UpdateChannelInfo(), and UpdateMQValues().
Referenced by ParseAll().
template<typename T > void FairMQProgOptions::Subscribe (const std::string & subscriber, std::function< void(typename fair::mq::PropertyChange::KeyType, T)> func) inline
Definition at line 126 of file FairMQProgOptions.h.
References FairProgOptions::fConfigMutex, fEvents, and fair::mq::EventManager::Subscribe().
Referenced by main(), and fair::mq::PluginServices::SubscribeToPropertyChange().
void FairMQProgOptions::SubscribeAsString (const std::string & subscriber, std::function< void(typename fair::mq::PropertyChange::KeyType, std::string)> func) inline
Definition at line 144 of file FairMQProgOptions.h.
References FairProgOptions::fConfigMutex, fEvents, and fair::mq::EventManager::Subscribe().
Referenced by fair::mq::PluginServices::SubscribeToPropertyChangeAsString().
template<typename T > void FairMQProgOptions::Unsubscribe (const std::string & subscriber) inline
Definition at line 137 of file FairMQProgOptions.h.
References FairProgOptions::fConfigMutex, fEvents, and fair::mq::EventManager::Unsubscribe().
Referenced by main(), and fair::mq::PluginServices::UnsubscribeFromPropertyChange().
void FairMQProgOptions::UnsubscribeAsString (const std::string & subscriber) inline
Definition at line 151 of file FairMQProgOptions.h.
References FairProgOptions::fConfigMutex, fEvents, and fair::mq::EventManager::Unsubscribe().
Referenced by fair::mq::PluginServices::UnsubscribeFromPropertyChangeAsString().
void FairMQProgOptions::UpdateChannelInfo () private
Definition at line 157 of file FairMQProgOptions.cxx.
References fChannelInfo, and fFairMQMap.
Referenced by Store(), and UpdateChannelMap().
int FairMQProgOptions::UpdateChannelMap (const FairMQMap & map)
Definition at line 149 of file FairMQProgOptions.cxx.
References fFairMQMap, UpdateChannelInfo(), and UpdateMQValues().
Referenced by SetValue(), and UpdateValue().
int FairMQProgOptions::UpdateChannelMap (const std::string & channelName, int index, const std::string & member, const std::string & val) private
int FairMQProgOptions::UpdateChannelMap (const std::string & channelName, int index, const std::string & member, int val) private
template<typename T > int FairMQProgOptions::UpdateChannelMap (const std::string & , int , const std::string & , T) inline private
Definition at line 201 of file FairMQProgOptions.h.
void FairMQProgOptions::UpdateMQValues () protected
Definition at line 168 of file FairMQProgOptions.cxx.
References fFairMQMap, and fMQKeyMap.
Referenced by Store(), and UpdateChannelMap().
template<typename T > int FairMQProgOptions::UpdateValue (const std::string & key, T val) inline
Definition at line 66 of file FairMQProgOptions.h.
References fair::mq::EventManager::Emit(), FairProgOptions::fConfigMutex, fEvents, fMQKeyMap, FairProgOptions::fVarMap, FairProgOptions::GetStringValue(), LOG, and UpdateChannelMap().
Referenced by main().
template<typename T > void FairProgOptions::UpdateVarMap (const std::string & key, const T & val) inline protected inherited
Definition at line 149 of file FairProgOptions.h.
References FairProgOptions::Replace().
Member Data Documentation
po::options_description FairProgOptions::fAllOptions protected inherited
Definition at line 141 of file FairProgOptions.h.
Referenced by FairProgOptions::AddToCmdLineOptions(), FairProgOptions::FairProgOptions(), FairProgOptions::GetCmdLineOptions(), ImmediateOptions(), FairProgOptions::ParseCmdLine(), FairProgOptions::ParseDefaults(), and FairProgOptions::PrintOptionsRaw().
std::unordered_map<std::string, int> FairMQProgOptions::fChannelInfo protected
Definition at line 174 of file FairMQProgOptions.h.
Referenced by GetChannelInfo(), and UpdateChannelInfo().
std::mutex FairProgOptions::fConfigMutex mutable protected inherited
Definition at line 143 of file FairProgOptions.h.
Referenced by FairProgOptions::Count(), FairProgOptions::GetPropertyKeys(), FairProgOptions::GetStringValue(), FairProgOptions::GetValue(), SetValue(), Subscribe(), SubscribeAsString(), Unsubscribe(), UnsubscribeAsString(), and UpdateValue().
fair::mq::EventManager FairMQProgOptions::fEvents private
Definition at line 208 of file FairMQProgOptions.h.
Referenced by EmitUpdate(), SetValue(), Subscribe(), SubscribeAsString(), Unsubscribe(), UnsubscribeAsString(), and UpdateValue().
FairMQMap FairMQProgOptions::fFairMQMap protected
Definition at line 171 of file FairMQProgOptions.h.
Referenced by GetFairMQMap(), Store(), UpdateChannelInfo(), UpdateChannelMap(), and UpdateMQValues().
po::options_description FairProgOptions::fGeneralOptions protected inherited
Definition at line 140 of file FairProgOptions.h.
Referenced by FairProgOptions::FairProgOptions().
po::options_description FairMQProgOptions::fMQCmdOptions protected
Definition at line 169 of file FairMQProgOptions.h.
Referenced by InitOptionDescription().
std::map<std::string, MQKey> FairMQProgOptions::fMQKeyMap protected
Definition at line 176 of file FairMQProgOptions.h.
Referenced by SetValue(), UpdateMQValues(), and UpdateValue().
po::options_description FairMQProgOptions::fMQParserOptions protected
Definition at line 170 of file FairMQProgOptions.h.
Referenced by InitOptionDescription(), and ParseAll().
po::variables_map FairProgOptions::fVarMap protected inherited
Definition at line 137 of file FairProgOptions.h.
Referenced by FairProgOptions::Count(), FairProgOptions::GetPropertyKeys(), FairProgOptions::GetStringValue(), FairProgOptions::GetValue(), FairProgOptions::GetVarMap(), ImmediateOptions(), ParseAll(), FairProgOptions::ParseCmdLine(), FairProgOptions::ParseDefaults(), FairProgOptions::PrintOptions(), FairProgOptions::PrintOptionsRaw(), and UpdateValue().
The documentation for this class was generated from the following files:
FairMQProgOptions.h
FairMQProgOptions.cxx