FairRoot: FairDetParRootFileIo Class Reference
FairDetParRootFileIo Class Reference
#include <FairDetParRootFileIo.h>
Public Member Functions
FairDetParRootFileIo (FairParRootFile *f)
virtual ~FairDetParRootFileIo ()
virtual Bool_t read (FairParSet *)
Int_t write (FairParSet *)
void setInputNumber (Int_t n)
Int_t getInputNumber ()
virtual Bool_t init (FairParSet *)
Protected Member Functions
Int_t findInputVersion (Text_t *contName)
Int_t getMaxVersion (Text_t *contName)
TObject * findContainer (Text_t *contName, Int_t version)
Protected Attributes
FairParRootFile * pFile
Int_t inputNumber
Private Member Functions
FairDetParRootFileIo (const FairDetParRootFileIo &)
FairDetParRootFileIo & operator= (const FairDetParRootFileIo &)
Detailed Description
Definition at line 21 of file FairDetParRootFileIo.h.
Constructor & Destructor Documentation
FairDetParRootFileIo() [1/2]
FairDetParRootFileIo::FairDetParRootFileIo (FairParRootFile * f)
~FairDetParRootFileIo()
virtual FairDetParRootFileIo::~FairDetParRootFileIo () inline virtual
Definition at line 27 of file FairDetParRootFileIo.h.
FairDetParRootFileIo() [2/2]
FairDetParRootFileIo::FairDetParRootFileIo (const FairDetParRootFileIo &) private
Member Function Documentation
findContainer()
TObject * FairDetParRootFileIo::findContainer (Text_t * contName, Int_t version) protected
Definition at line 133 of file FairDetParRootFileIo.cxx.
References FairParRootFile::cd(), and pFile.
findInputVersion()
Int_t FairDetParRootFileIo::findInputVersion (Text_t * contName) protected
Definition at line 112 of file FairDetParRootFileIo.cxx.
References FairRuntimeDb::getCurrentRun(), FairParVersion::getInputVersion(), FairRtdbRun::getParVersion(), FairParVersion::getRootVersion(), FairParRootFile::getRun(), FairDetParIo::inputNumber, FairRuntimeDb::instance(), and pFile.
Referenced by read().
getInputNumber()
Int_t FairDetParIo::getInputNumber () inline inherited
Definition at line 29 of file FairDetParIo.h.
References FairDetParIo::inputNumber.
getMaxVersion()
Int_t FairDetParRootFileIo::getMaxVersion (Text_t * contName) protected
Definition at line 101 of file FairDetParRootFileIo.cxx.
References FairParRootFile::GetKey(), and pFile.
Referenced by write().
init()
virtual Bool_t FairDetParIo::init (FairParSet *) inline virtual inherited
Reimplemented in FairGenericParAsciiFileIo, and FairGenericParRootFileIo.
Definition at line 32 of file FairDetParIo.h.
Referenced by ClassImp().
operator=()
FairDetParRootFileIo& FairDetParRootFileIo::operator= (const FairDetParRootFileIo &) private
read()
Bool_t FairDetParRootFileIo::read (FairParSet * pPar) virtual
Definition at line 51 of file FairDetParRootFileIo.cxx.
References FairParSet::clear(), findInputVersion(), FairParSet::getInputVersion(), FairParSet::GetName(), FairDetParIo::inputNumber, FairParSet::setChanged(), and FairParSet::setInputVersion().
Referenced by FairGenericParRootFileIo::init().
setInputNumber()
void FairDetParIo::setInputNumber (Int_t n) inline inherited
Definition at line 26 of file FairDetParIo.h.
References FairDetParIo::inputNumber.
Referenced by FairParIo::setInputNumber().
write()
Int_t FairDetParRootFileIo::write (FairParSet * pPar) virtual
Reimplemented from FairDetParIo.
Definition at line 82 of file FairDetParRootFileIo.cxx.
References FairParRootFile::cd(), getMaxVersion(), FairParSet::GetName(), FairRuntimeDb::instance(), FairParRootFile::IsWritable(), pFile, FairParSet::setChanged(), and FairRuntimeDb::setVersionsChanged().
Member Data Documentation
inputNumber
Int_t FairDetParIo::inputNumber protected inherited
Definition at line 20 of file FairDetParIo.h.
Referenced by findInputVersion(), FairDetParIo::getInputNumber(), read(), and FairDetParIo::setInputNumber().
pFile
FairParRootFile* FairDetParRootFileIo::pFile protected
Definition at line 24 of file FairDetParRootFileIo.h.
Referenced by findContainer(), findInputVersion(), getMaxVersion(), FairGenericParRootFileIo::init(), and write().
The documentation for this class was generated from the following files:
FairDetParRootFileIo.h
FairDetParRootFileIo.cxx