FairRoot: FairConstPar Class Reference
FairConstPar Class Reference
#include <FairConstPar.h>
Public Member Functions
FairConstPar (const char *name, const char *title, const char *context)
FairConstPar ()
~FairConstPar ()
void putParams (FairParamList *list)
Bool_t getParams (FairParamList *list)
void SetParameters (FairField *field)
Double_t GetBx () const
Double_t GetBy () const
Double_t GetBz () const
Int_t GetType () const
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
void MapName (TString &name)
Double_t GetPositionX () const
Double_t GetPositionY () const
Double_t GetPositionZ () const
Double_t GetScale () const
virtual void printParams ()
Bool_t init (FairParIo *inp)
virtual Bool_t init ()
Int_t write (FairParIo *output)
virtual Int_t write ()
void fill (UInt_t)
void store (UInt_t)
virtual const char * GetName () const
virtual const char * GetTitle () const
virtual void clear ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setOwnership (Bool_t flag=kTRUE)
Bool_t isOwned ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Member Functions
ClassDef (FairConstPar, 1)
ClassDef (FairMapPar, 1)
Protected Attributes
Double_t fBx
Double_t fBy
Double_t fBz
Int_t fType
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
TString fMapName
Double_t fPosX
Double_t fPosY
Double_t fPosZ
Double_t fScale
TString fName
TString fTitle
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
Bool_t owned
flag is kTRUE if parameters have changed
TString paramContext
if flag is KTRUE FairDB has the par. class ownership
TString author
TString description
FairLogger * fLogger
Detailed Description
Definition at line 26 of file FairConstPar.h.
Constructor & Destructor Documentation
FairConstPar() [1/2]
FairConstPar::FairConstPar (const char * name, const char * title, const char * context)
Standard constructor
Definition at line 18 of file FairConstPar.cxx.
References FairMapPar::fType.
FairConstPar() [2/2]
FairConstPar::FairConstPar ()
default constructor
Definition at line 27 of file FairConstPar.cxx.
References FairMapPar::fType.
~FairConstPar()
FairConstPar::~FairConstPar ()
Destructor
Definition at line 36 of file FairConstPar.cxx.
Member Function Documentation
ClassDef() [1/2]
FairConstPar::ClassDef (FairConstPar , 1) protected
ClassDef() [2/2]
FairMapPar::ClassDef (FairMapPar , 1) protected inherited
clear()
virtual void FairParSet::clear (void) inline virtual inherited
Reimplemented in FairTutorialDet2DigiPar, FairBaseParSet, FairGeoParSet, FairRutherfordGeoPar, FairTutorialDet1GeoPar, FairTestDetectorGeoPar, FairMQExParamsParOne, PixelDigiPar, PixelGeoPar, FairTutorialDet2GeoPar, NewDetectorGeoPar, NewDetectorGeoPar, FairGeoPassivePar, FairTutorialDet4MisalignPar, FairTutorialDet4GeoPar, and NewParameterContainer.
Definition at line 45 of file FairParSet.h.
Referenced by FairDetParRootFileIo::read().
copyComment()
void FairParSet::copyComment (FairParSet & r) inline inherited
Definition at line 76 of file FairParSet.h.
References FairParSet::author, FairParSet::description, FairParSet::getAuthor(), and FairParSet::getDescription().
fill()
void FairParGenericSet::fill (UInt_t) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 32 of file FairParGenericSet.h.
getAuthor()
const char* FairParSet::getAuthor () const inline inherited
Definition at line 71 of file FairParSet.h.
References FairParSet::author.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
GetBx()
Double_t FairConstPar::GetBx () const inline
Definition at line 47 of file FairConstPar.h.
References fBx.
Referenced by FairConstField::FairConstField().
GetBy()
Double_t FairConstPar::GetBy () const inline
Definition at line 51 of file FairConstPar.h.
References fBy.
Referenced by FairConstField::FairConstField().
GetBz()
Double_t FairConstPar::GetBz () const inline
Definition at line 55 of file FairConstPar.h.
References fBz.
Referenced by FairConstField::FairConstField().
getDescription()
const char* FairParSet::getDescription () const inline inherited
Definition at line 74 of file FairParSet.h.
References FairParSet::description.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
getDetectorName()
const char* FairParSet::getDetectorName () inline inherited
Definition at line 48 of file FairParSet.h.
References FairParSet::detName.
getInputVersion()
Int_t FairParSet::getInputVersion (Int_t i) inline inherited
Definition at line 54 of file FairParSet.h.
References FairParSet::versions.
Referenced by FairRuntimeDb::findOutputVersion(), FairDetParRootFileIo::read(), and FairRuntimeDb::writeContainer().
GetName()
virtual const char* FairParSet::GetName () const inline virtual inherited
Definition at line 38 of file FairParSet.h.
References FairParSet::fName.
Referenced by FairRuntimeDb::addContainer(), FairRuntimeDb::addRun(), FairRuntimeDb::findOutputVersion(), FairGenericParAsciiFileIo::init(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), FairRuntimeDb::initContainers(), FairParSet::print(), FairRuntimeDb::print(), FairParGenericSet::printParams(), FairDetParRootFileIo::read(), FairGenericParAsciiFileIo::write(), FairDetParRootFileIo::write(), FairParSet::write(), FairRuntimeDb::writeContainer(), FairGenericParAsciiFileIo::writeGenericSet(), and FairRuntimeDb::~FairRuntimeDb().
getParamContext()
const char* FairParSet::getParamContext () const inline inherited
Definition at line 68 of file FairParSet.h.
References FairParSet::paramContext.
Referenced by FairGenericParAsciiFileIo::writeGenericSet().
getParams()
Bool_t FairConstPar::getParams (FairParamList * list) virtual
Get parameters
Implements FairParGenericSet.
Definition at line 60 of file FairConstPar.cxx.
References fBx, fBy, fBz, FairParamList::fill(), FairMapPar::fType, FairMapPar::fXmax, FairMapPar::fXmin, FairMapPar::fYmax, FairMapPar::fYmin, FairMapPar::fZmax, and FairMapPar::fZmin.
GetPositionX()
Double_t FairMapPar::GetPositionX () const inline inherited
Definition at line 71 of file FairMapPar.h.
References FairMapPar::fPosX.
GetPositionY()
Double_t FairMapPar::GetPositionY () const inline inherited
Definition at line 75 of file FairMapPar.h.
References FairMapPar::fPosY.
GetPositionZ()
Double_t FairMapPar::GetPositionZ () const inline inherited
Definition at line 79 of file FairMapPar.h.
References FairMapPar::fPosZ.
GetScale()
Double_t FairMapPar::GetScale () const inline inherited
Definition at line 83 of file FairMapPar.h.
References FairMapPar::fScale.
GetTitle()
virtual const char* FairParSet::GetTitle () const inline virtual inherited
Definition at line 39 of file FairParSet.h.
References FairParSet::fTitle.
Referenced by FairRuntimeDb::print().
GetType()
Int_t FairMapPar::GetType () const inline inherited
Accessors
Definition at line 39 of file FairMapPar.h.
References FairMapPar::fType.
Referenced by FairConstField::FairConstField().
GetXmax()
Double_t FairMapPar::GetXmax () const inline inherited
Definition at line 47 of file FairMapPar.h.
References FairMapPar::fXmax.
Referenced by FairConstField::FairConstField().
GetXmin()
Double_t FairMapPar::GetXmin () const inline inherited
Definition at line 43 of file FairMapPar.h.
References FairMapPar::fXmin.
Referenced by FairConstField::FairConstField().
GetYmax()
Double_t FairMapPar::GetYmax () const inline inherited
Definition at line 55 of file FairMapPar.h.
References FairMapPar::fYmax.
Referenced by FairConstField::FairConstField().
GetYmin()
Double_t FairMapPar::GetYmin () const inline inherited
Definition at line 51 of file FairMapPar.h.
References FairMapPar::fYmin.
Referenced by FairConstField::FairConstField().
GetZmax()
Double_t FairMapPar::GetZmax () const inline inherited
Definition at line 63 of file FairMapPar.h.
References FairMapPar::fZmax.
Referenced by FairConstField::FairConstField().
GetZmin()
Double_t FairMapPar::GetZmin () const inline inherited
Definition at line 59 of file FairMapPar.h.
References FairMapPar::fZmin.
Referenced by FairConstField::FairConstField().
hasChanged()
Bool_t FairParSet::hasChanged () inline inherited
Definition at line 66 of file FairParSet.h.
References FairParSet::changed.
Referenced by FairRuntimeDb::findOutputVersion(), and FairRuntimeDb::writeContainer().
init() [1/2]
Bool_t FairParGenericSet::init (FairParIo * inp) virtual inherited
Reimplemented from FairParSet.
init() [2/2]
Bool_t FairParSet::init () virtual inherited
Definition at line 46 of file FairParSet.cxx.
References FairRuntimeDb::getFirstInput(), FairParSet::GetName(), FairRuntimeDb::getSecondInput(), FairRuntimeDb::instance(), and FairParSet::setInputVersion().
Referenced by FairRuntimeDb::initContainers().
isOwned()
Bool_t FairParSet::isOwned () inline inherited
Definition at line 63 of file FairParSet.h.
References FairParSet::owned.
Referenced by FairRuntimeDb::~FairRuntimeDb().
isStatic()
Bool_t FairParSet::isStatic () inline inherited
Definition at line 60 of file FairParSet.h.
References FairParSet::status.
Referenced by FairRuntimeDb::initContainers(), and FairRuntimeDb::resetInputVersions().
MapName()
void FairMapPar::MapName (TString & name) inline inherited
Definition at line 67 of file FairMapPar.h.
References FairMapPar::fMapName.
print()
void FairParSet::print () virtual inherited
Reimplemented in FairMQExParamsParOne.
Definition at line 84 of file FairParSet.cxx.
References FairParSet::author, FairParSet::changed, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParSet::status, and FairParSet::versions.
Referenced by create_digis(), create_digis_mixed(), read_digis(), and FairRuntimeDb::writeContainer().
printParams()
void FairParGenericSet::printParams () virtual inherited
Definition at line 59 of file FairParGenericSet.cxx.
References FairParSet::author, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParamList::print(), and FairParGenericSet::putParams().
Referenced by PixelFindHitsTask::Init(), and read_digis().
putParams()
void FairConstPar::putParams (FairParamList * list) virtual
Implements FairParGenericSet.
Definition at line 40 of file FairConstPar.cxx.
References FairParamList::add(), fBx, fBy, fBz, FairMapPar::fType, FairMapPar::fXmax, FairMapPar::fXmin, FairMapPar::fYmax, FairMapPar::fYmin, FairMapPar::fZmax, and FairMapPar::fZmin.
resetInputVersions()
void FairParSet::resetInputVersions () inherited
Definition at line 99 of file FairParSet.cxx.
References FairParSet::changed, FairParSet::status, and FairParSet::versions.
Referenced by FairMQExParamsParOne::clear(), FairTutorialDet2DigiPar::clear(), and FairRuntimeDb::resetInputVersions().
setAuthor()
void FairParSet::setAuthor (const char * s) inline inherited
Definition at line 70 of file FairParSet.h.
References FairParSet::author.
Referenced by FairDetParAsciiFileIo::readComment().
setChanged()
void FairParSet::setChanged (Bool_t flag = kTRUE) inline inherited
Definition at line 65 of file FairParSet.h.
References FairParSet::changed.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), create_digis(), create_digis_mixed(), FairConstField::FillParContainer(), for(), FairRunOnline::Init(), FairRunSim::Init(), FairTutorialDet4::Initialize(), FairDetParRootFileIo::read(), read_digis(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), FairTutorialDet4::SetSensitiveVolumes(), FairDetParRootFileIo::write(), FairRuntimeDb::writeContainer(), and FairGenericParAsciiFileIo::writeGenericSet().
setDescription()
void FairParSet::setDescription (const char * s) inline inherited
Definition at line 73 of file FairParSet.h.
References FairParSet::description.
Referenced by FairDetParAsciiFileIo::readComment(), and FairMQSimDevice::UpdateParameterServer().
setInputVersion()
void FairParSet::setInputVersion (Int_t v = -1, Int_t i = 0) inline inherited
Definition at line 51 of file FairParSet.h.
References FairParSet::versions.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), create_digis(), create_digis_mixed(), FairConstField::FillParContainer(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), FairTutorialDet4::Initialize(), FairDetParRootFileIo::read(), read_digis(), FairTutorialDet2::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), and FairTutorialDet4::SetSensitiveVolumes().
setOwnership()
void FairParSet::setOwnership (Bool_t flag = kTRUE) inline inherited
Definition at line 62 of file FairParSet.h.
References FairParSet::owned.
SetParameters()
void FairConstPar::SetParameters (FairField * field)
Set parameters from FairField
Definition at line 108 of file FairConstPar.cxx.
References fBx, fBy, fBz, FairMapPar::fMapName, FairMapPar::fPosX, FairMapPar::fPosY, FairMapPar::fPosZ, FairMapPar::fScale, FairMapPar::fType, FairMapPar::fXmax, FairMapPar::fXmin, FairMapPar::fYmax, FairMapPar::fYmin, FairMapPar::fZmax, FairMapPar::fZmin, FairConstField::GetBx(), FairConstField::GetBy(), FairConstField::GetBz(), FairField::GetType(), FairConstField::GetXmax(), FairConstField::GetXmin(), FairConstField::GetYmax(), FairConstField::GetYmin(), FairConstField::GetZmax(), and FairConstField::GetZmin().
Referenced by FairConstField::FillParContainer().
setStatic()
void FairParSet::setStatic (Bool_t flag = kTRUE) inline inherited
Definition at line 59 of file FairParSet.h.
References FairParSet::status.
Referenced by FairRuntimeDb::setContainersStatic().
store()
void FairParGenericSet::store (UInt_t) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 33 of file FairParGenericSet.h.
write() [1/2]
Int_t FairParGenericSet::write (FairParIo * output) virtual inherited
Reimplemented from FairParSet.
Definition at line 50 of file FairParGenericSet.cxx.
References FairParIo::getDetParIo(), and FairDetParIo::write().
write() [2/2]
Int_t FairParSet::write () virtual inherited
Definition at line 72 of file FairParSet.cxx.
References FairParSet::GetName(), FairRuntimeDb::getOutput(), and FairRuntimeDb::instance().
Referenced by FairRuntimeDb::writeContainer().
Member Data Documentation
author
TString FairParSet::author protected inherited
Definition at line 29 of file FairParSet.h.
Referenced by FairParSet::copyComment(), FairParSet::getAuthor(), FairParSet::operator=(), FairParSet::print(), FairParGenericSet::printParams(), and FairParSet::setAuthor().
changed
Bool_t FairParSet::changed protected inherited
static flag
Definition at line 26 of file FairParSet.h.
Referenced by FairParSet::hasChanged(), FairParSet::operator=(), FairParSet::print(), FairParSet::resetInputVersions(), and FairParSet::setChanged().
description
TString FairParSet::description protected inherited
Definition at line 30 of file FairParSet.h.
Referenced by FairParSet::copyComment(), FairParSet::getDescription(), FairParSet::operator=(), FairParSet::print(), FairParGenericSet::printParams(), and FairParSet::setDescription().
detName
TString FairParSet::detName protected inherited
Definition at line 23 of file FairParSet.h.
Referenced by FairMQExParamsParOne::FairMQExParamsParOne(), FairTutorialDet2DigiPar::FairTutorialDet2DigiPar(), FairParSet::getDetectorName(), and FairParSet::operator=().
fBx
Double_t FairConstPar::fBx protected
Field values in [kG]
Definition at line 62 of file FairConstPar.h.
Referenced by GetBx(), getParams(), putParams(), and SetParameters().
fBy
Double_t FairConstPar::fBy protected
Definition at line 62 of file FairConstPar.h.
Referenced by GetBy(), getParams(), putParams(), and SetParameters().
fBz
Double_t FairConstPar::fBz protected
Definition at line 62 of file FairConstPar.h.
Referenced by GetBz(), getParams(), putParams(), and SetParameters().
fLogger
FairLogger* FairParSet::fLogger protected inherited
Fair Logger
Definition at line 32 of file FairParSet.h.
Referenced by FairParSet::operator=().
fMapName
TString FairMapPar::fMapName protected inherited
Field map name in case of field map
Definition at line 103 of file FairMapPar.h.
Referenced by FairMapPar::MapName(), and SetParameters().
fName
TString FairParSet::fName protected inherited
Definition at line 21 of file FairParSet.h.
Referenced by ClassImp(), FairBaseContFact::FairBaseContFact(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), FairParSet::GetName(), MyPassiveContFact::MyPassiveContFact(), FairParSet::operator=(), and PixelContFact::PixelContFact().
fPosX
Double_t FairMapPar::fPosX protected inherited
Field centre position for field map
Definition at line 106 of file FairMapPar.h.
Referenced by FairMapPar::GetPositionX(), and SetParameters().
fPosY
Double_t FairMapPar::fPosY protected inherited
Definition at line 106 of file FairMapPar.h.
Referenced by FairMapPar::GetPositionY(), and SetParameters().
fPosZ
Double_t FairMapPar::fPosZ protected inherited
Definition at line 106 of file FairMapPar.h.
Referenced by FairMapPar::GetPositionZ(), and SetParameters().
fScale
Double_t FairMapPar::fScale protected inherited
Scaling factor for field map
Definition at line 109 of file FairMapPar.h.
Referenced by FairMapPar::GetScale(), and SetParameters().
fTitle
TString FairParSet::fTitle protected inherited
Definition at line 22 of file FairParSet.h.
Referenced by FairBaseContFact::FairBaseContFact(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), FairParSet::GetTitle(), MyPassiveContFact::MyPassiveContFact(), FairParSet::operator=(), and PixelContFact::PixelContFact().
fType
Int_t FairMapPar::fType protected inherited
Field type 0 = constant field 1 = field map 2 = field map sym2 (symmetries in x and y) 3 = field map sym3 (symmetries in x, y and z)
Definition at line 95 of file FairMapPar.h.
Referenced by FairConstPar(), getParams(), FairMapPar::GetType(), putParams(), and SetParameters().
fXmax
Double_t FairMapPar::fXmax protected inherited
Definition at line 98 of file FairMapPar.h.
Referenced by getParams(), FairMapPar::GetXmax(), putParams(), and SetParameters().
fXmin
Double_t FairMapPar::fXmin protected inherited
Field limits in case of constant field
Definition at line 98 of file FairMapPar.h.
Referenced by getParams(), FairMapPar::GetXmin(), putParams(), and SetParameters().
fYmax
Double_t FairMapPar::fYmax protected inherited
Definition at line 99 of file FairMapPar.h.
Referenced by getParams(), FairMapPar::GetYmax(), putParams(), and SetParameters().
fYmin
Double_t FairMapPar::fYmin protected inherited
Definition at line 99 of file FairMapPar.h.
Referenced by getParams(), FairMapPar::GetYmin(), putParams(), and SetParameters().
fZmax
Double_t FairMapPar::fZmax protected inherited
Definition at line 100 of file FairMapPar.h.
Referenced by getParams(), FairMapPar::GetZmax(), putParams(), and SetParameters().
fZmin
Double_t FairMapPar::fZmin protected inherited
Definition at line 100 of file FairMapPar.h.
Referenced by getParams(), FairMapPar::GetZmin(), putParams(), and SetParameters().
owned
Bool_t FairParSet::owned protected inherited
flag is kTRUE if parameters have changed
Definition at line 27 of file FairParSet.h.
Referenced by FairParSet::isOwned(), FairParSet::operator=(), and FairParSet::setOwnership().
paramContext
TString FairParSet::paramContext protected inherited
if flag is KTRUE FairDB has the par. class ownership
Definition at line 28 of file FairParSet.h.
Referenced by FairParSet::getParamContext(), FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
status
Bool_t FairParSet::status protected inherited
versions of container in the 2 possible inputs
Definition at line 25 of file FairParSet.h.
Referenced by FairMQExParamsParOne::clear(), FairTutorialDet2DigiPar::clear(), FairParSet::isStatic(), FairParSet::operator=(), FairParSet::print(), FairParSet::resetInputVersions(), and FairParSet::setStatic().
versions
Int_t FairParSet::versions[3] protected inherited
name of the detector the container belongs to
Definition at line 24 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::getInputVersion(), FairParSet::operator=(), FairParSet::print(), FairParSet::resetInputVersions(), and FairParSet::setInputVersion().
The documentation for this class was generated from the following files:
FairConstPar.h
FairConstPar.cxx