FairRroot: MySorterTask Class Reference
MySorterTask Class Reference
#include <MySorterTask.h>
Public Member Functions
MySorterTask ()
MySorterTask (const char *name)
MySorterTask (Int_t numberOfCells, Double_t widthOfCells, TString inputBranch, TString outputBranch, TString folderName)
virtual ~MySorterTask ()
virtual void AddNewDataToTClonesArray (FairTimeStamp *data)
virtual FairRingSorter * InitSorter (Int_t numberOfCells, Double_t widthOfCells) const
ClassDef (MySorterTask, 1)
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void Exec (Option_t *opt)
virtual void FinishEvent ()
virtual void FinishTask ()
virtual void SetParContainers ()
void SetPersistance (Bool_t p=kTRUE)
Bool_t GetPersistance ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
ClassDef (FairRingSorterTask, 2)
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
FairRingSorter * fSorter
Bool_t fPersistance
Bool_t fDigiPixelMCInfo
Int_t fNumberOfCells
Double_t fWidthOfCells
TString fInputBranch
TClonesArray * fInputArray
TString fOutputBranch
TString fFolder
TClonesArray * fOutputArray
Int_t fEntryNr
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Detailed Description
Definition at line 21 of file MySorterTask.h.
Constructor & Destructor Documentation
MySorterTask::MySorterTask ()
Definition at line 20 of file MySorterTask.cxx.
MySorterTask::MySorterTask (const char * name) inline
Definition at line 26 of file MySorterTask.h.
MySorterTask::MySorterTask (Int_t numberOfCells, Double_t widthOfCells, TString inputBranch, TString outputBranch, TString folderName) inline
Definition at line 29 of file MySorterTask.h.
MySorterTask::~MySorterTask () virtual
Definition at line 25 of file MySorterTask.cxx.
Member Function Documentation
void MySorterTask::AddNewDataToTClonesArray (FairTimeStamp * data) virtual
Reimplemented from FairRingSorterTask.
Definition at line 29 of file MySorterTask.cxx.
References FairRingSorterTask::fOutputBranch, FairTask::fVerbose, FairRootManager::GetTClonesArray(), and FairRootManager::Instance().
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
MySorterTask::ClassDef (MySorterTask , 1)
FairRingSorterTask::ClassDef (FairRingSorterTask , 2) protected inherited
void FairRingSorterTask::Exec (Option_t * opt) virtual inherited
Virtual method Exec
Definition at line 60 of file FairRingSorterTask.cxx.
References FairRingSorter::AddElement(), FairRingSorterTask::AddNewDataToTClonesArray(), FairRingSorter::DeleteOutputData(), FairRingSorterTask::fEntryNr, FairRingSorterTask::fInputArray, FairRingSorterTask::fInputBranch, FairRingSorterTask::fOutputArray, FairRingSorterTask::fOutputBranch, FairRingSorterTask::fSorter, FairTask::fVerbose, FairRootManager::GetEmptyTClonesArray(), FairRingSorter::GetOutputData(), FairRootManager::GetTClonesArray(), FairTimeStamp::GetTimeStamp(), FairRootManager::Instance(), and FairMultiLinkedData_Interface::SetEntryNr().
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), LOG, FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), LOG, FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
virtual void FairTask::Finish () inline protected virtual inherited
Action at end of run. For this task and all of the subtasks. To be implemented in the derived class.
Reimplemented in PixelAltFindHits, FairEventBuilderManager, PixelFindHits, PixelFitTracks, PixelDigitize, PixelFindTracks, PixelAltDigiWriteToRootVector, FairBoxSetDraw, PixelDigiWriteToBinFile, PixelDigiWriteToFile, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet4PointDraw, FairPrintFairLinks, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 132 of file FairTask.h.
Referenced by FairTask::FinishTask().
void FairRingSorterTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 102 of file FairRingSorterTask.cxx.
References FairRingSorterTask::fOutputArray.
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
void FairRingSorterTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented from FairTask.
Definition at line 107 of file FairRingSorterTask.cxx.
References FairRingSorter::AddElement(), FairRingSorterTask::AddNewDataToTClonesArray(), FairRingSorter::DeleteOutputData(), FairRingSorterTask::fInputArray, FairRingSorterTask::fInputBranch, FairRingSorterTask::fOutputArray, FairRingSorterTask::fOutputBranch, FairRingSorterTask::fSorter, FairTask::fVerbose, FairRootManager::GetEmptyTClonesArray(), FairRingSorter::GetOutputData(), FairRootManager::GetTClonesArray(), FairRootManager::Instance(), FairRootManager::SetLastFill(), and FairRingSorter::WriteOutAll().
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
Bool_t FairRingSorterTask::GetPersistance () inline inherited
Definition at line 97 of file FairRingSorterTask.h.
References FairRingSorterTask::fPersistance.
InitStatus FairRingSorterTask::Init () virtual inherited
Virtual method Init
Reimplemented from FairTask.
Definition at line 36 of file FairRingSorterTask.cxx.
References FairRingSorterTask::fFolder, FairRingSorterTask::fInputArray, FairRingSorterTask::fInputBranch, FairRingSorterTask::fNumberOfCells, FairRingSorterTask::fOutputArray, FairRingSorterTask::fOutputBranch, FairRingSorterTask::fPersistance, FairRingSorterTask::fSorter, FairTask::fVerbose, FairRingSorterTask::fWidthOfCells, FairRootManager::GetTClonesArray(), FairRingSorterTask::InitSorter(), FairRootManager::Instance(), kFATAL, kSUCCESS, and FairRootManager::Register().
FairRingSorter * MySorterTask::InitSorter (Int_t numberOfCells, Double_t widthOfCells) const virtual
Reimplemented from FairRingSorterTask.
Definition at line 40 of file MySorterTask.cxx.
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, LOG, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
InitStatus FairRingSorterTask::ReInit () virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 25 of file FairRingSorterTask.cxx.
References kSUCCESS.
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, LOG, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
virtual void FairRingSorterTask::SetParContainers () inline virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 94 of file FairRingSorterTask.h.
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
void FairRingSorterTask::SetPersistance (Bool_t p = kTRUE) inline inherited
Definition at line 96 of file FairRingSorterTask.h.
References FairRingSorterTask::fPersistance.
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
Bool_t FairRingSorterTask::fDigiPixelMCInfo protected inherited
switch to turn on/off storing additional MC Info of Digis
Definition at line 108 of file FairRingSorterTask.h.
Int_t FairRingSorterTask::fEntryNr protected inherited
Definition at line 118 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec().
TString FairRingSorterTask::fFolder protected inherited
Definition at line 116 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Init().
TClonesArray* FairRingSorterTask::fInputArray protected inherited
Definition at line 113 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), and FairRingSorterTask::Init().
TString FairRingSorterTask::fInputBranch protected inherited
Input array of PndSdsPixelDigis
Definition at line 112 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), and FairRingSorterTask::Init().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
Int_t FairRingSorterTask::fNumberOfCells protected inherited
Definition at line 109 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Init().
TClonesArray* FairRingSorterTask::fOutputArray protected inherited
Definition at line 117 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec(), FairRingSorterTask::FinishEvent(), FairRingSorterTask::FinishTask(), and FairRingSorterTask::Init().
TString FairRingSorterTask::fOutputBranch protected inherited
Output array of sorted PndSdsDigis
Definition at line 115 of file FairRingSorterTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), AddNewDataToTClonesArray(), FairRingSorterTask::AddNewDataToTClonesArray(), FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), and FairRingSorterTask::Init().
Bool_t FairRingSorterTask::fPersistance protected inherited
switch to turn on/off storing the arrays to a file
Definition at line 106 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::GetPersistance(), FairRingSorterTask::Init(), and FairRingSorterTask::SetPersistance().
FairRingSorter* FairRingSorterTask::fSorter protected inherited
Definition at line 104 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Exec(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), and FairRingSorterTask::~FairRingSorterTask().
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
Double_t FairRingSorterTask::fWidthOfCells protected inherited
Definition at line 110 of file FairRingSorterTask.h.
Referenced by FairRingSorterTask::Init().
The documentation for this class was generated from the following files:
MySorterTask.h
MySorterTask.cxx