FairRoot: FairRingSorterTask Class Reference
FairRingSorterTask Class Reference
#include <FairRingSorterTask.h>
Public Member Functions
FairRingSorterTask ()
FairRingSorterTask (const char *name)
FairRingSorterTask (Int_t numberOfCells, Double_t widthOfCells, TString inputBranch, TString outputBranch, TString folderName)
virtual ~FairRingSorterTask ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void Exec (Option_t *opt)
virtual void FinishEvent ()
virtual void FinishTask ()
virtual void SetParContainers ()
void SetPersistance (Bool_t p=kTRUE)
Bool_t GetPersistance ()
virtual void AddNewDataToTClonesArray (FairTimeStamp *data)
virtual FairRingSorter * InitSorter (Int_t numberOfCells, Double_t widthOfCells) const
void InitTask ()
void ReInitTask ()
void SetParTask ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
FairRingSorterTask (const FairRingSorterTask &)
FairRingSorterTask & operator= (const FairRingSorterTask &)
ClassDef (FairRingSorterTask, 2)
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
FairRingSorter * fSorter
Bool_t fPersistance
Bool_t fDigiPixelMCInfo
Int_t fNumberOfCells
Double_t fWidthOfCells
TString fInputBranch
TClonesArray * fInputArray
TString fOutputBranch
TString fFolder
TClonesArray * fOutputArray
Int_t fEntryNr
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Detailed Description
Definition at line 26 of file FairRingSorterTask.h.
Constructor & Destructor Documentation
FairRingSorterTask() [1/4]
FairRingSorterTask::FairRingSorterTask () inline
Default constructor
Definition at line 31 of file FairRingSorterTask.h.
References FairTask::SetVerbose().
FairRingSorterTask() [2/4]
FairRingSorterTask::FairRingSorterTask (const char * name) inline
Named constructor
Definition at line 48 of file FairRingSorterTask.h.
References FairTask::SetVerbose().
FairRingSorterTask() [3/4]
FairRingSorterTask::FairRingSorterTask (Int_t numberOfCells, Double_t widthOfCells, TString inputBranch, TString outputBranch, TString folderName) inline
Definition at line 64 of file FairRingSorterTask.h.
References FairTask::SetVerbose().
~FairRingSorterTask()
virtual FairRingSorterTask::~FairRingSorterTask () inline virtual
Destructor
Definition at line 81 of file FairRingSorterTask.h.
References fSorter.
FairRingSorterTask() [4/4]
FairRingSorterTask::FairRingSorterTask (const FairRingSorterTask &) protected
Member Function Documentation
AddNewDataToTClonesArray()
void FairRingSorterTask::AddNewDataToTClonesArray (FairTimeStamp * data) virtual
Reimplemented in FairTestDetectorDigiSorterTask, and MySorterTask.
Definition at line 93 of file FairRingSorterTask.cxx.
References fOutputBranch, FairRootManager::GetTClonesArray(), and FairRootManager::Instance().
Referenced by Exec(), and FinishTask().
CheckInputPersistance()
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
ClassDef()
FairRingSorterTask::ClassDef (FairRingSorterTask , 2) protected
Exec()
void FairRingSorterTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 60 of file FairRingSorterTask.cxx.
References FairRingSorter::AddElement(), AddNewDataToTClonesArray(), FairRingSorter::DeleteOutputData(), fEntryNr, fInputArray, fInputBranch, fOutputArray, fOutputBranch, fSorter, FairTask::fVerbose, FairRootManager::GetEmptyTClonesArray(), FairRingSorter::GetOutputData(), FairRootManager::GetTClonesArray(), FairTimeStamp::GetTimeStamp(), FairRootManager::Instance(), and FairMultiLinkedData_Interface::SetEntryNr().
ExecuteTask()
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
ExecuteTasks()
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
Finish()
virtual void FairTask::Finish () inline protected virtual inherited
Action at end of run. For this task and all of the subtasks. To be implemented in the derived class.
Reimplemented in PixelAltFindHits, FairEventBuilderManager, PixelFindHits, PixelDigitize, PixelFitTracks, PixelFindTracks, PixelAltDigiWriteToRootVector, FairBoxSetDraw, PixelDigiWriteToBinFile, PixelDigiWriteToFile, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet4PointDraw, FairPrintFairLinks, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 132 of file FairTask.h.
Referenced by FairTask::FinishTask().
FinishEvent()
void FairRingSorterTask::FinishEvent () virtual
Action at end of event. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 102 of file FairRingSorterTask.cxx.
References fOutputArray.
FinishEvents()
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
FinishTask()
void FairRingSorterTask::FinishTask () virtual
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented from FairTask.
Definition at line 107 of file FairRingSorterTask.cxx.
References FairRingSorter::AddElement(), AddNewDataToTClonesArray(), FairRingSorter::DeleteOutputData(), fInputArray, fInputBranch, fOutputArray, fOutputBranch, fSorter, FairTask::fVerbose, FairRootManager::GetEmptyTClonesArray(), FairRingSorter::GetOutputData(), FairRootManager::GetTClonesArray(), FairRootManager::Instance(), FairRootManager::SetLastFill(), and FairRingSorter::WriteOutAll().
FinishTasks()
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
GetPersistance()
Bool_t FairRingSorterTask::GetPersistance () inline
Definition at line 97 of file FairRingSorterTask.h.
References fPersistance.
Init()
InitStatus FairRingSorterTask::Init () virtual
Virtual method Init
Reimplemented from FairTask.
Definition at line 36 of file FairRingSorterTask.cxx.
References fFolder, fInputArray, fInputBranch, fNumberOfCells, fOutputArray, fOutputBranch, fPersistance, fSorter, FairTask::fVerbose, fWidthOfCells, FairRootManager::GetTClonesArray(), InitSorter(), FairRootManager::Instance(), kFATAL, kSUCCESS, and FairRootManager::Register().
InitSorter()
FairRingSorter * FairRingSorterTask::InitSorter (Int_t numberOfCells, Double_t widthOfCells) const virtual
Reimplemented in FairTestDetectorDigiSorterTask, and MySorterTask.
Definition at line 30 of file FairRingSorterTask.cxx.
Referenced by Init().
InitTask()
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
InitTasks()
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
IsOutputBranchPersistent()
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
operator=()
FairRingSorterTask& FairRingSorterTask::operator= (const FairRingSorterTask &) protected
ReInit()
InitStatus FairRingSorterTask::ReInit () virtual
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 25 of file FairRingSorterTask.cxx.
References kSUCCESS.
ReInitTask()
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
ReInitTasks()
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
SetInputPersistance()
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
SetOutputBranchPersistent()
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
SetParContainers()
virtual void FairRingSorterTask::SetParContainers () inline virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 94 of file FairRingSorterTask.h.
SetParTask()
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
SetParTasks()
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
SetPersistance()
void FairRingSorterTask::SetPersistance (Bool_t p = kTRUE) inline
Definition at line 96 of file FairRingSorterTask.h.
References fPersistance.
SetStreamProcessing()
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
SetVerbose()
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
fDigiPixelMCInfo
Bool_t FairRingSorterTask::fDigiPixelMCInfo protected
switch to turn on/off storing additional MC Info of Digis
Definition at line 108 of file FairRingSorterTask.h.
fEntryNr
Int_t FairRingSorterTask::fEntryNr protected
Definition at line 118 of file FairRingSorterTask.h.
Referenced by Exec().
fFolder
TString FairRingSorterTask::fFolder protected
Definition at line 116 of file FairRingSorterTask.h.
Referenced by Init().
fInputArray
TClonesArray* FairRingSorterTask::fInputArray protected
Definition at line 113 of file FairRingSorterTask.h.
Referenced by Exec(), FinishTask(), and Init().
fInputBranch
TString FairRingSorterTask::fInputBranch protected
Input array of PndSdsPixelDigis
Definition at line 112 of file FairRingSorterTask.h.
Referenced by Exec(), FinishTask(), and Init().
fInputPersistance
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
fLogger
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
fNumberOfCells
Int_t FairRingSorterTask::fNumberOfCells protected
Definition at line 109 of file FairRingSorterTask.h.
Referenced by Init().
fOutputArray
TClonesArray* FairRingSorterTask::fOutputArray protected
Definition at line 117 of file FairRingSorterTask.h.
Referenced by Exec(), FinishEvent(), FinishTask(), and Init().
fOutputBranch
TString FairRingSorterTask::fOutputBranch protected
Output array of sorted PndSdsDigis
Definition at line 115 of file FairRingSorterTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), AddNewDataToTClonesArray(), Exec(), FinishTask(), and Init().
fPersistance
Bool_t FairRingSorterTask::fPersistance protected
switch to turn on/off storing the arrays to a file
Definition at line 106 of file FairRingSorterTask.h.
Referenced by GetPersistance(), Init(), and SetPersistance().
fSorter
FairRingSorter* FairRingSorterTask::fSorter protected
Definition at line 104 of file FairRingSorterTask.h.
Referenced by Exec(), FinishTask(), Init(), and ~FairRingSorterTask().
fStreamProcessing
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
fVerbose
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FinishTask(), Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
fWidthOfCells
Double_t FairRingSorterTask::fWidthOfCells protected
Definition at line 110 of file FairRingSorterTask.h.
Referenced by Init().
The documentation for this class was generated from the following files:
FairRingSorterTask.h
FairRingSorterTask.cxx