FairRroot: fair::mq::plugins::DDS Class Reference
fair::mq::plugins::DDS Class Reference
#include <DDS.h>
Public Types
using ProgOptions = boost::optional< boost::program_options::options_description >
using Version = tools::Version
using DeviceState = fair::mq::PluginServices::DeviceState
using DeviceStateTransition = fair::mq::PluginServices::DeviceStateTransition
Public Member Functions
DDS (const std::string name, const Plugin::Version version, const std::string maintainer, const std::string homepage, PluginServices *pluginServices)
~DDS ()
auto GetName () const -> const std::string &
auto GetVersion () const -> const Version
auto GetMaintainer () const -> const std::string &
auto GetHomepage () const -> const std::string &
auto ToDeviceState (const std::string &state) const -> DeviceState
auto ToDeviceStateTransition (const std::string &transition) const -> DeviceStateTransition
auto ToStr (DeviceState state) const -> std::string
auto ToStr (DeviceStateTransition transition) const -> std::string
auto GetCurrentDeviceState () const -> DeviceState
auto TakeDeviceControl () -> void
auto StealDeviceControl () -> void
auto ReleaseDeviceControl () -> void
auto ChangeDeviceState (const DeviceStateTransition next) -> void
auto SubscribeToDeviceStateChange (std::function< void(DeviceState)> callback) -> void
auto UnsubscribeFromDeviceStateChange () -> void
auto PropertyExists (const std::string &key) -> int
template<typename T >
auto SetProperty (const std::string &key, T val) -> void
template<typename T >
auto GetProperty (const std::string &key) const -> T
auto GetPropertyAsString (const std::string &key) const -> std::string
auto GetChannelInfo () const -> std::unordered_map< std::string, int >
auto GetPropertyKeys () const -> std::vector< std::string >
template<typename T >
auto SubscribeToPropertyChange (std::function< void(const std::string &key, T newValue)> callback) -> void
template<typename T >
auto UnsubscribeFromPropertyChange () -> void
auto SubscribeToPropertyChangeAsString (std::function< void(const std::string &key, std::string newValue)> callback) -> void
auto UnsubscribeFromPropertyChangeAsString () -> void
Static Public Member Functions
static auto NoProgramOptions () -> ProgOptions
Private Member Functions
auto HandleControl () -> void
auto WaitForNextState () -> DeviceState
auto FillChannelContainers () -> void
auto SubscribeForConnectingChannels () -> void
auto PublishBoundChannels () -> void
auto SubscribeForCustomCommands () -> void
auto HeartbeatSender () -> void
Private Attributes
dds::intercom_api::CIntercomService fService
dds::intercom_api::CCustomCmd fDDSCustomCmd
dds::intercom_api::CKeyValue fDDSKeyValue
std::unordered_map< std::string, std::vector< std::string > > fBindingChans
std::unordered_map< std::string, DDSConfig > fConnectingChans
std::unordered_map< std::string, int > fI
std::unordered_map< std::string, IofN > fIofN
std::mutex fStopMutex
std::condition_variable fStopCondition
const std::set< std::string > fCommands
std::thread fControllerThread
std::queue< DeviceState > fEvents
std::mutex fEventsMutex
std::condition_variable fNewEvent
std::atomic< bool > fDeviceTerminationRequested
std::set< uint64_t > fHeartbeatSubscribers
std::mutex fHeartbeatSubscriberMutex
std::set< uint64_t > fStateChangeSubscribers
std::mutex fStateChangeSubscriberMutex
std::thread fHeartbeatThread
std::chrono::milliseconds fHeartbeatInterval
Detailed Description
Definition at line 61 of file DDS.h.
Member Typedef Documentation
using fair::mq::Plugin::DeviceState = fair::mq::PluginServices::DeviceState inherited
Definition at line 71 of file Plugin.h.
using fair::mq::Plugin::DeviceStateTransition = fair::mq::PluginServices::DeviceStateTransition inherited
Definition at line 72 of file Plugin.h.
using fair::mq::Plugin::ProgOptions = boost::optional<boost::program_options::options_description> inherited
Definition at line 41 of file Plugin.h.
using fair::mq::Plugin::Version = tools::Version inherited
Definition at line 43 of file Plugin.h.
Constructor & Destructor Documentation
fair::mq::plugins::DDS::DDS (const std::string name, const Plugin::Version version, const std::string maintainer, const std::string homepage, PluginServices * pluginServices)
Definition at line 33 of file DDS.cxx.
fair::mq::plugins::DDS::~DDS ()
Definition at line 420 of file DDS.cxx.
References fControllerThread, and fHeartbeatThread.
Member Function Documentation
auto fair::mq::Plugin::ChangeDeviceState (const DeviceStateTransition next) -> void inline inherited
Definition at line 81 of file Plugin.h.
References fair::mq::PluginServices::ChangeDeviceState(), fair::mq::Plugin::fkName, and fair::mq::Plugin::fPluginServices.
auto fair::mq::plugins::DDS::FillChannelContainers () -> void private
Definition at line 159 of file DDS.cxx.
References fair::debug, fair::error, LOG, and fair::mq::tools::ToString().
auto fair::mq::Plugin::GetChannelInfo () const -> std::unordered_map<std::string, int> inline inherited
Definition at line 93 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetChannelInfo().
auto fair::mq::Plugin::GetCurrentDeviceState () const -> DeviceState inline inherited
Definition at line 77 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetCurrentDeviceState().
auto fair::mq::Plugin::GetHomepage () const -> const std::string& inline inherited
Definition at line 56 of file Plugin.h.
References fair::mq::Plugin::fkHomepage.
auto fair::mq::Plugin::GetMaintainer () const -> const std::string& inline inherited
Definition at line 55 of file Plugin.h.
References fair::mq::Plugin::fkMaintainer.
auto fair::mq::Plugin::GetName () const -> const std::string& inline inherited
Definition at line 53 of file Plugin.h.
References fair::mq::Plugin::fkName.
template<typename T > auto fair::mq::Plugin::GetProperty (const std::string & key) const -> T inline inherited
Definition at line 91 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetProperty().
auto fair::mq::Plugin::GetPropertyAsString (const std::string & key) const -> std::string inline inherited
Definition at line 92 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetPropertyAsString().
auto fair::mq::Plugin::GetPropertyKeys () const -> std::vector<std::string> inline inherited
Definition at line 94 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetPropertyKeys().
auto fair::mq::Plugin::GetVersion () const -> const Version inline inherited
Definition at line 54 of file Plugin.h.
References fair::mq::Plugin::fkVersion.
auto fair::mq::plugins::DDS::HandleControl () -> void private
Definition at line 66 of file DDS.cxx.
References fair::debug, fair::DEBUG, fair::error, and LOG.
auto fair::mq::plugins::DDS::HeartbeatSender () -> void private
Definition at line 303 of file DDS.cxx.
static auto fair::mq::Plugin::NoProgramOptions () -> ProgOptions inline static inherited
Definition at line 67 of file Plugin.h.
auto fair::mq::Plugin::PropertyExists (const std::string & key) -> int inline inherited
Definition at line 87 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::PropertyExists().
auto fair::mq::plugins::DDS::PublishBoundChannels () -> void private
Definition at line 293 of file DDS.cxx.
References fair::debug, and LOG.
auto fair::mq::Plugin::ReleaseDeviceControl () -> void inline inherited
Definition at line 80 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ReleaseDeviceControl().
template<typename T > auto fair::mq::Plugin::SetProperty (const std::string & key, T val) -> void inline inherited
Definition at line 89 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SetProperty().
auto fair::mq::Plugin::StealDeviceControl () -> void inline inherited
Definition at line 79 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::StealDeviceControl().
auto fair::mq::plugins::DDS::SubscribeForConnectingChannels () -> void private
Definition at line 229 of file DDS.cxx.
References fair::debug, fair::error, and LOG.
auto fair::mq::plugins::DDS::SubscribeForCustomCommands () -> void private
Definition at line 323 of file DDS.cxx.
References fair::debug, fair::info, LOG, fair::state, and fair::warn.
auto fair::mq::Plugin::SubscribeToDeviceStateChange (std::function< void(DeviceState)> callback) -> void inline inherited
Definition at line 82 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToDeviceStateChange().
Referenced by fair::mq::test::DummyPlugin::DummyPlugin().
template<typename T > auto fair::mq::Plugin::SubscribeToPropertyChange (std::function< void(const std::string &key, T newValue)> callback) -> void inline inherited
Definition at line 96 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToPropertyChange().
auto fair::mq::Plugin::SubscribeToPropertyChangeAsString (std::function< void(const std::string &key, std::string newValue)> callback) -> void inline inherited
Definition at line 99 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToPropertyChangeAsString().
auto fair::mq::Plugin::TakeDeviceControl () -> void inline inherited
Definition at line 78 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::TakeDeviceControl().
auto fair::mq::Plugin::ToDeviceState (const std::string & state) const -> DeviceState inline inherited
Definition at line 73 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, fair::state, and fair::mq::PluginServices::ToDeviceState().
auto fair::mq::Plugin::ToDeviceStateTransition (const std::string & transition) const -> DeviceStateTransition inline inherited
Definition at line 74 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ToDeviceStateTransition().
auto fair::mq::Plugin::ToStr (DeviceState state) const -> std::string inline inherited
Definition at line 75 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, fair::state, and fair::mq::PluginServices::ToStr().
auto fair::mq::Plugin::ToStr (DeviceStateTransition transition) const -> std::string inline inherited
Definition at line 76 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ToStr().
auto fair::mq::Plugin::UnsubscribeFromDeviceStateChange () -> void inline inherited
Definition at line 83 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromDeviceStateChange().
Referenced by fair::mq::test::DummyPlugin::DummyPlugin().
template<typename T > auto fair::mq::Plugin::UnsubscribeFromPropertyChange () -> void inline inherited
Definition at line 98 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromPropertyChange().
auto fair::mq::Plugin::UnsubscribeFromPropertyChangeAsString () -> void inline inherited
Definition at line 100 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromPropertyChangeAsString().
auto fair::mq::plugins::DDS::WaitForNextState () -> DeviceState private
Definition at line 407 of file DDS.cxx.
Member Data Documentation
std::unordered_map<std::string, std::vector<std::string> > fair::mq::plugins::DDS::fBindingChans private
Definition at line 83 of file DDS.h.
const std::set<std::string> fair::mq::plugins::DDS::fCommands private
Definition at line 92 of file DDS.h.
std::unordered_map<std::string, DDSConfig> fair::mq::plugins::DDS::fConnectingChans private
Definition at line 84 of file DDS.h.
std::thread fair::mq::plugins::DDS::fControllerThread private
Definition at line 94 of file DDS.h.
Referenced by ~DDS().
dds::intercom_api::CCustomCmd fair::mq::plugins::DDS::fDDSCustomCmd private
Definition at line 80 of file DDS.h.
dds::intercom_api::CKeyValue fair::mq::plugins::DDS::fDDSKeyValue private
Definition at line 81 of file DDS.h.
std::atomic<bool> fair::mq::plugins::DDS::fDeviceTerminationRequested private
Definition at line 99 of file DDS.h.
std::queue<DeviceState> fair::mq::plugins::DDS::fEvents private
Definition at line 95 of file DDS.h.
std::mutex fair::mq::plugins::DDS::fEventsMutex private
Definition at line 96 of file DDS.h.
std::chrono::milliseconds fair::mq::plugins::DDS::fHeartbeatInterval private
Definition at line 107 of file DDS.h.
std::mutex fair::mq::plugins::DDS::fHeartbeatSubscriberMutex private
Definition at line 102 of file DDS.h.
std::set<uint64_t> fair::mq::plugins::DDS::fHeartbeatSubscribers private
Definition at line 101 of file DDS.h.
std::thread fair::mq::plugins::DDS::fHeartbeatThread private
Definition at line 106 of file DDS.h.
Referenced by ~DDS().
std::unordered_map<std::string, int> fair::mq::plugins::DDS::fI private
Definition at line 86 of file DDS.h.
std::unordered_map<std::string, IofN> fair::mq::plugins::DDS::fIofN private
Definition at line 87 of file DDS.h.
std::condition_variable fair::mq::plugins::DDS::fNewEvent private
Definition at line 97 of file DDS.h.
dds::intercom_api::CIntercomService fair::mq::plugins::DDS::fService private
Definition at line 79 of file DDS.h.
std::mutex fair::mq::plugins::DDS::fStateChangeSubscriberMutex private
Definition at line 104 of file DDS.h.
std::set<uint64_t> fair::mq::plugins::DDS::fStateChangeSubscribers private
Definition at line 103 of file DDS.h.
std::condition_variable fair::mq::plugins::DDS::fStopCondition private
Definition at line 90 of file DDS.h.
std::mutex fair::mq::plugins::DDS::fStopMutex private
Definition at line 89 of file DDS.h.
The documentation for this class was generated from the following files:
DDS.h
DDS.cxx