FairRoot: VerbosityLevelTest Class Reference
VerbosityLevelTest Class Reference
#include <_TestFairLogger.h>
Protected Member Functions
VerbosityLevelTest ()
virtual void SetUp ()
VerbosityLevelTest ()
virtual void SetUp ()
virtual void SetUp ()
virtual void TearDown ()
virtual void TearDown ()
void SetOutFileName ()
void SetOutFileName ()
void SetFairLoggerDefaultValues ()
void SetFairLoggerDefaultValues ()
void SetFairLoggerDefaultValues ()
void LogNoArguments ()
void LogNoArguments ()
void LogNoArguments (FairLogger *fLogger, std::string OutputString)
std::vector< std::string > CreateExpectedOutputNoArguments (std::string logLevel, std::string outStr)
std::vector< std::string > CreateExpectedOutputNoArguments (std::string loglevel, std::string outStr)
std::vector< std::string > CreateExpectedOutputNoArguments (std::string loglevel, std::string outString, std::string filename="")
std::vector< std::string > CreateExpectedLogLevels (std::string loglevel)
std::vector< std::string > CreateExpectedLogLevels (std::string loglevel)
std::vector< std::string > CreateExpectedLogLevels (std::string loglevel)
void CheckScreenOutput (std::vector< std::string > v)
void CheckScreenOutput (std::vector< std::string > v)
void CheckScreenOutput (FairCaptureOutput handler, std::vector< std::string > v)
void CheckFileOutput (std::vector< std::string > v, FairTestOutputHandler _handler)
void CheckFileOutput (std::vector< std::string > v, FairTestOutputHandler _handler)
void CheckFileOutput (FairTestOutputHandler handler, std::vector< std::string > v)
std::vector< std::string > ReadLinesFromFile (std::string fileName)
bool CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verbosity, std::string resultString)
bool CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verbosity, std::string resultString)
bool CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verboseLevel, std::string resultString)
Protected Attributes
std::string fVerbosityLevel
std::string verbosityLevel
std::string fLogLevelSettingToTest
std::string fOutputString
std::string fOutFileName
FairLogger * fLogger
FairCaptureOutputNew fHandler
std::string logLevelSettingToTest
std::string OutputString
FairCaptureOutput handler
Detailed Description
Definition at line 235 of file _TestFairLogger.h.
Constructor & Destructor Documentation
VerbosityLevelTest() [1/2]
VerbosityLevelTest::VerbosityLevelTest () inline protected
Definition at line 238 of file _TestFairLogger.h.
VerbosityLevelTest() [2/2]
VerbosityLevelTest::VerbosityLevelTest () inline protected
Definition at line 217 of file _TestFairLoggerNew.h.
Member Function Documentation
CheckFileOutput() [1/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckFileOutput (std::vector< std::string > v, FairTestOutputHandler _handler) inline protected inherited
Definition at line 144 of file _TestFairLoggerNew.h.
References FairTestOutputHandler::GetCaptureLine(), and FairTestOutputHandler::GetNumberOfLines().
CheckFileOutput() [2/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckFileOutput (std::vector< std::string > v, FairTestOutputHandler _handler) inline protected inherited
Definition at line 146 of file _TestFairLogger.h.
References FairTestOutputHandler::GetCaptureLine(), and FairTestOutputHandler::GetNumberOfLines().
CheckFileOutput() [3/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckFileOutput (FairTestOutputHandler handler, std::vector< std::string > v) inline protected inherited
Definition at line 151 of file _TestFairTools.cxx.
References _TestFairLoggerBase< T >::handler.
CheckScreenOutput() [1/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckScreenOutput (std::vector< std::string > v) inline protected inherited
Definition at line 130 of file _TestFairLoggerNew.h.
References _TestFairLoggerBase< T >::fHandler, FairCaptureOutputNew::GetCaptureLine(), and FairCaptureOutputNew::GetNumberOfLines().
CheckScreenOutput() [2/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckScreenOutput (std::vector< std::string > v) inline protected inherited
Definition at line 132 of file _TestFairLogger.h.
References _TestFairLoggerBase< T >::fHandler, FairCaptureOutputNew::GetCaptureLine(), and FairCaptureOutputNew::GetNumberOfLines().
CheckScreenOutput() [3/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckScreenOutput (FairCaptureOutput handler, std::vector< std::string > v) inline protected inherited
Definition at line 139 of file _TestFairTools.cxx.
References _TestFairLoggerBase< T >::handler.
CheckVerboseOutput() [1/3]
bool _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verbosity, std::string resultString) inline protected inherited
Definition at line 158 of file _TestFairLoggerNew.h.
CheckVerboseOutput() [2/3]
bool _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verboseLevel, std::string resultString) inline protected inherited
Definition at line 163 of file _TestFairTools.cxx.
CheckVerboseOutput() [3/3]
bool _TestFairLoggerBase< testing::TestWithParam< const char *> >::CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verbosity, std::string resultString) inline protected inherited
Definition at line 178 of file _TestFairLogger.h.
CreateExpectedLogLevels() [1/3]
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char *> >::CreateExpectedLogLevels (std::string loglevel) inline protected inherited
Definition at line 122 of file _TestFairLoggerNew.h.
References TestLogs.
CreateExpectedLogLevels() [2/3]
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char *> >::CreateExpectedLogLevels (std::string loglevel) inline protected inherited
Definition at line 124 of file _TestFairLogger.h.
References TestLogs.
CreateExpectedLogLevels() [3/3]
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char *> >::CreateExpectedLogLevels (std::string loglevel) inline protected inherited
Definition at line 130 of file _TestFairTools.cxx.
References TestLogs.
CreateExpectedOutputNoArguments() [1/3]
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char *> >::CreateExpectedOutputNoArguments (std::string loglevel, std::string outString, std::string filename = "") inline protected inherited
Definition at line 94 of file _TestFairTools.cxx.
References LogString.
CreateExpectedOutputNoArguments() [2/3]
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char *> >::CreateExpectedOutputNoArguments (std::string loglevel, std::string outStr) inline protected inherited
Definition at line 102 of file _TestFairLoggerNew.h.
References LogString.
CreateExpectedOutputNoArguments() [3/3]
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char *> >::CreateExpectedOutputNoArguments (std::string logLevel, std::string outStr) inline protected inherited
Definition at line 104 of file _TestFairLogger.h.
References LogString.
LogNoArguments() [1/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::LogNoArguments (FairLogger * fLogger, std::string OutputString) inline protected inherited
Definition at line 82 of file _TestFairTools.cxx.
References FairLogger::Debug(), FairLogger::Debug1(), FairLogger::Debug2(), FairLogger::Debug3(), FairLogger::Debug4(), FairLogger::Error(), _TestFairLoggerBase< T >::fLogger, FairLogger::Info(), MESSAGE_ORIGIN, _TestFairLoggerBase< T >::OutputString, and FairLogger::Warning().
LogNoArguments() [2/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::LogNoArguments () inline protected inherited
Definition at line 89 of file _TestFairLoggerNew.h.
References _TestFairLoggerBase< T >::fOutputString.
LogNoArguments() [3/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::LogNoArguments () inline protected inherited
Definition at line 91 of file _TestFairLogger.h.
References FairLogger::Debug(), FairLogger::Debug1(), FairLogger::Debug2(), FairLogger::Debug3(), FairLogger::Debug4(), FairLogger::Error(), _TestFairLoggerBase< T >::fLogger, _TestFairLoggerBase< T >::fOutputString, FairLogger::Info(), MESSAGE_ORIGIN, and FairLogger::Warning().
ReadLinesFromFile()
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char *> >::ReadLinesFromFile (std::string fileName) inline protected inherited
Definition at line 160 of file _TestFairLogger.h.
SetFairLoggerDefaultValues() [1/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetFairLoggerDefaultValues () inline protected inherited
Definition at line 74 of file _TestFairTools.cxx.
References _TestFairLoggerBase< T >::fLogger, FairLogger::SetLogFileLevel(), FairLogger::SetLogScreenLevel(), FairLogger::SetLogToFile(), FairLogger::SetLogToScreen(), and FairLogger::SetLogVerbosityLevel().
SetFairLoggerDefaultValues() [2/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetFairLoggerDefaultValues () inline protected inherited
Definition at line 79 of file _TestFairLoggerNew.h.
References gLogger.
SetFairLoggerDefaultValues() [3/3]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetFairLoggerDefaultValues () inline protected inherited
Definition at line 81 of file _TestFairLogger.h.
References _TestFairLoggerBase< T >::fLogger, FairLogger::SetLogFileLevel(), FairLogger::SetLogScreenLevel(), FairLogger::SetLogToFile(), FairLogger::SetLogToScreen(), FairLogger::SetLogVerbosityLevel(), and FairLogger::SetScreenStreamToCerr().
Referenced by LogLevelTest::SetUp(), and SetUp().
SetOutFileName() [1/2]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetOutFileName () inline protected inherited
Definition at line 70 of file _TestFairLoggerNew.h.
References _TestFairLoggerBase< T >::fOutFileName.
SetOutFileName() [2/2]
void _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetOutFileName () inline protected inherited
Definition at line 72 of file _TestFairLogger.h.
References _TestFairLoggerBase< T >::fOutFileName.
Referenced by LogLevelTest::SetUp(), and SetUp().
SetUp() [1/3]
virtual void VerbosityLevelTest::SetUp () inline protected virtual
Reimplemented from _TestFairLoggerBase< testing::TestWithParam< const char *> >.
Definition at line 206 of file _TestFairTools.cxx.
References _TestFairLoggerBase< testing::TestWithParam< const char *> >::fLogger, FairLogger::GetLogger(), _TestFairLoggerBase< testing::TestWithParam< const char *> >::logLevelSettingToTest, _TestFairLoggerBase< testing::TestWithParam< const char *> >::OutputString, _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetFairLoggerDefaultValues(), and verbosityLevel.
SetUp() [2/3]
virtual void VerbosityLevelTest::SetUp () inline protected virtual
Reimplemented from _TestFairLoggerBase< testing::TestWithParam< const char *> >.
Definition at line 221 of file _TestFairLoggerNew.h.
References _TestFairLoggerBase< testing::TestWithParam< const char *> >::fLogLevelSettingToTest, _TestFairLoggerBase< testing::TestWithParam< const char *> >::fOutputString, fVerbosityLevel, _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetFairLoggerDefaultValues(), and _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetOutFileName().
SetUp() [3/3]
virtual void VerbosityLevelTest::SetUp () inline protected virtual
Reimplemented from _TestFairLoggerBase< testing::TestWithParam< const char *> >.
Definition at line 242 of file _TestFairLogger.h.
References fVerbosityLevel, _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetFairLoggerDefaultValues(), and _TestFairLoggerBase< testing::TestWithParam< const char *> >::SetOutFileName().
TearDown() [1/2]
virtual void _TestFairLoggerBase< testing::TestWithParam< const char *> >::TearDown () inline protected virtual inherited
Definition at line 67 of file _TestFairLoggerNew.h.
TearDown() [2/2]
virtual void _TestFairLoggerBase< testing::TestWithParam< const char *> >::TearDown () inline protected virtual inherited
Definition at line 69 of file _TestFairLogger.h.
Member Data Documentation
fHandler
FairCaptureOutputNew _TestFairLoggerBase< testing::TestWithParam< const char *> >::fHandler protected inherited
Definition at line 47 of file _TestFairLogger.h.
fLogger
FairLogger * _TestFairLoggerBase< testing::TestWithParam< const char *> >::fLogger protected inherited
Definition at line 46 of file _TestFairLogger.h.
Referenced by LogLevelTest::SetUp(), and SetUp().
fLogLevelSettingToTest
std::string _TestFairLoggerBase< testing::TestWithParam< const char *> >::fLogLevelSettingToTest protected inherited
Definition at line 43 of file _TestFairLogger.h.
Referenced by LogLevelTest::SetUp(), and SetUp().
fOutFileName
std::string _TestFairLoggerBase< testing::TestWithParam< const char *> >::fOutFileName protected inherited
Definition at line 45 of file _TestFairLogger.h.
fOutputString
std::string _TestFairLoggerBase< testing::TestWithParam< const char *> >::fOutputString protected inherited
Definition at line 44 of file _TestFairLogger.h.
Referenced by LogLevelTest::SetUp(), and SetUp().
fVerbosityLevel
std::string VerbosityLevelTest::fVerbosityLevel protected
Definition at line 249 of file _TestFairLogger.h.
Referenced by SetUp().
handler
FairCaptureOutput _TestFairLoggerBase< testing::TestWithParam< const char *> >::handler protected inherited
Definition at line 56 of file _TestFairTools.cxx.
logLevelSettingToTest
std::string _TestFairLoggerBase< testing::TestWithParam< const char *> >::logLevelSettingToTest protected inherited
Definition at line 53 of file _TestFairTools.cxx.
Referenced by LogLevelTest::SetUp(), and SetUp().
OutputString
std::string _TestFairLoggerBase< testing::TestWithParam< const char *> >::OutputString protected inherited
Definition at line 54 of file _TestFairTools.cxx.
Referenced by LogLevelTest::SetUp(), and SetUp().
verbosityLevel
std::string VerbosityLevelTest::verbosityLevel protected
Definition at line 213 of file _TestFairTools.cxx.
Referenced by SetUp().
The documentation for this class was generated from the following files:
_TestFairLogger.h
_TestFairLoggerNew.h
_TestFairTools.cxx