FairRoot: FairSink Class Reference
FairSink Class Reference abstract
#include <FairSink.h>
Classes
struct TypeAddressPair
Public Member Functions
FairSink ()
FairSink (const FairSink &sink)
virtual ~FairSink ()
virtual Bool_t InitSink ()=0
virtual void Close ()=0
virtual void Reset ()=0
virtual Sink_Type GetSinkType ()=0
virtual TString GetFileName ()
void SetRunId (Int_t runId)
Int_t GetRunId () const
virtual void SetOutTree (TTree *fTree)=0
virtual void Fill ()=0
virtual Int_t Write (const char *name=0, Int_t option=0, Int_t bufsize=0)=0
virtual void RegisterImpl (const char *, const char *, void *)=0
virtual void RegisterAny (const char *brname, const std::type_info &oi, const std::type_info &pi, void *obj)=0
virtual void WriteFolder ()=0
virtual bool CreatePersistentBranchesAny ()=0
virtual void WriteObject (TObject *f, const char *, Int_t option=0)=0
virtual void WriteGeometry ()=0
Protected Attributes
Int_t fRunId
TFolder * fOutFolder
std::map< std::string, std::unique_ptr< TypeAddressPair const > > fPersistentBranchesMap
Detailed Description
Definition at line 25 of file FairSink.h.
Constructor & Destructor Documentation
FairSink() [1/2]
FairSink::FairSink ()
Definition at line 21 of file FairSink.cxx.
FairSink() [2/2]
FairSink::FairSink (const FairSink & sink)
Definition at line 28 of file FairSink.cxx.
~FairSink()
FairSink::~FairSink () virtual
Definition at line 35 of file FairSink.cxx.
Member Function Documentation
Close()
virtual void FairSink::Close () pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::CloseSink().
CreatePersistentBranchesAny()
virtual bool FairSink::CreatePersistentBranchesAny () pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Fill()
virtual void FairSink::Fill () pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::Fill(), and FairRootManager::LastFill().
GetFileName()
virtual TString FairSink::GetFileName () inline virtual
Reimplemented in FairRootFileSink.
Definition at line 37 of file FairSink.h.
Referenced by FairRun::SetSink().
GetRunId()
Int_t FairSink::GetRunId () const inline
Definition at line 40 of file FairSink.h.
References fRunId.
GetSinkType()
virtual Sink_Type FairSink::GetSinkType () pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
InitSink()
virtual Bool_t FairSink::InitSink () pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::InitSink().
RegisterAny()
virtual void FairSink::RegisterAny (const char * brname, const std::type_info & oi, const std::type_info & pi, void * obj) pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::RegisterAny().
RegisterImpl()
virtual void FairSink::RegisterImpl (const char * , const char * , void *) pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::RegisterImpl().
Reset()
virtual void FairSink::Reset () pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
SetOutTree()
virtual void FairSink::SetOutTree (TTree * fTree) pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
SetRunId()
void FairSink::SetRunId (Int_t runId) inline
Definition at line 39 of file FairSink.h.
References fRunId.
Write()
virtual Int_t FairSink::Write (const char * name = 0, Int_t option = 0, Int_t bufsize = 0) pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::Write().
WriteFolder()
virtual void FairSink::WriteFolder () pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::WriteFolder().
WriteGeometry()
virtual void FairSink::WriteGeometry () pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::WriteGeometry().
WriteObject()
virtual void FairSink::WriteObject (TObject * f, const char * , Int_t option = 0) pure virtual
Implemented in FairRootFileSink, and FairOnlineSink.
Referenced by FairRootManager::WriteFileHeader(), and FairRootManager::WriteFolder().
Member Data Documentation
fOutFolder
TFolder* FairSink::fOutFolder protected
folder structure of output
Definition at line 68 of file FairSink.h.
Referenced by FairRootFileSink::InitSink(), FairRootFileSink::RegisterImpl(), FairRootFileSink::TruncateBranchNames(), and FairRootFileSink::WriteFolder().
fPersistentBranchesMap
std::map<std::string, std::unique_ptr<TypeAddressPair const> > FairSink::fPersistentBranchesMap protected
A map of branchnames to typeinformation + memory address; used for branches registered to bes stored; use of ptr here since type_info cannot be copied
Definition at line 72 of file FairSink.h.
Referenced by FairRootFileSink::CreatePersistentBranchesAny(), and FairRootFileSink::RegisterAny().
fRunId
Int_t FairSink::fRunId protected
Definition at line 65 of file FairSink.h.
Referenced by GetRunId(), and SetRunId().
The documentation for this class was generated from the following files:
FairSink.h
FairSink.cxx