FairRoot: PixelTrack Class Reference
PixelTrack Class Reference
#include <PixelTrack.h>
Public Member Functions
PixelTrack ()
PixelTrack (Double_t x0, Double_t ax, Double_t y0, Double_t ay, Double_t x0e, Double_t axe, Double_t y0e, Double_t aye)
void SetX0 (Double_t x0)
void SetAX (Double_t ax)
void SetY0 (Double_t y0)
void SetAY (Double_t ay)
void SetX0Err (Double_t x0e)
void SetAXErr (Double_t axe)
void SetY0Err (Double_t y0e)
void SetAYERr (Double_t aye)
Double_t GetX0 ()
Double_t GetAX ()
Double_t GetY0 ()
Double_t GetAY ()
Double_t GetX0Err ()
Double_t GetAXErr ()
Double_t GetY0Err ()
Double_t GetAYErr ()
void AddHitIndex (Int_t hitIndex)
Int_t GetNofHits ()
Int_t GetHitIndex (Int_t ihit)
virtual ~PixelTrack ()
template<class Archive >
void serialize (Archive &ar, const unsigned int)
Double_t GetTimeStamp () const
Double_t GetTimeStampError () const
void SetTimeStamp (Double_t t)
void SetTimeStampError (Double_t t)
virtual Int_t Compare (const TObject *obj) const
virtual std::ostream & PrintTimeInfo (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
virtual bool operator< (const FairTimeStamp *rValue) const
std::set< FairLink > GetLinks () const
returns stored links as FairLinks
Int_t GetNLinks () const
returns the number of stored links
FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
FairLink GetEntryNr () const
FairMultiLinkedData * GetPointerToLinks () const
std::vector< FairLink > GetSortedMCTracks ()
void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
void SetLink (FairLink link)
Sets the Links with a single FairLink.
void SetInsertHistory (Bool_t val)
void SetEntryNr (FairLink val)
void SetPointerToLinks (FairMultiLinkedData *links)
void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
void AddInterfaceData (FairMultiLinkedData_Interface *data)
void ResetLinks ()
std::ostream & PrintLinkInfo (std::ostream &out=std::cout) const
Output.
Protected Member Functions
ClassDef (FairTimeStamp, 4)
ClassDef (FairMultiLinkedData_Interface, 5)
FairMultiLinkedData * CreateFairMultiLinkedData ()
Protected Attributes
Double_t fTimeStamp
Double_t fTimeStampError
FairMultiLinkedData * fLink
Private Member Functions
ClassDef (PixelTrack, 1)
Private Attributes
Double_t fX0
Double_t fAX
Double_t fY0
Double_t fAY
Double_t fX0Err
Double_t fAXErr
Double_t fY0Err
Double_t fAYErr
std::vector< Int_t > fHitIndices
Friends
class boost::serialization::access
Detailed Description
Definition at line 24 of file PixelTrack.h.
Constructor & Destructor Documentation
PixelTrack() [1/2]
PixelTrack::PixelTrack ()
Default constructor
Definition at line 19 of file PixelTrack.cxx.
PixelTrack() [2/2]
PixelTrack::PixelTrack (Double_t x0, Double_t ax, Double_t y0, Double_t ay, Double_t x0e, Double_t axe, Double_t y0e, Double_t aye)
Constructor
Definition at line 33 of file PixelTrack.cxx.
~PixelTrack()
PixelTrack::~PixelTrack () virtual
Destructor
Definition at line 48 of file PixelTrack.cxx.
Member Function Documentation
AddHitIndex()
void PixelTrack::AddHitIndex (Int_t hitIndex) inline
Definition at line 53 of file PixelTrack.h.
References fHitIndices.
Referenced by PixelFitTracks::Exec(), and PixelFindTracks::Exec().
AddInterfaceData()
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) inherited
Definition at line 172 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
Referenced by FairTestDetectorTimeRecoTask::Exec().
AddLink()
void FairMultiLinkedData_Interface::AddLink (FairLink link) inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
AddLinks()
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 155 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
ClassDef() [1/3]
PixelTrack::ClassDef (PixelTrack , 1) private
ClassDef() [2/3]
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
ClassDef() [3/3]
FairTimeStamp::ClassDef (FairTimeStamp , 4) protected inherited
Error on time stamp
Compare()
virtual Int_t FairTimeStamp::Compare (const TObject * obj) const inline virtual inherited
Definition at line 48 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
CreateFairMultiLinkedData()
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 59 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
equal()
virtual bool FairTimeStamp::equal (FairTimeStamp * data) inline virtual inherited
Reimplemented in FairTestDetectorDigi, and MyDigi.
Definition at line 62 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
GetAX()
Double_t PixelTrack::GetAX () inline
Definition at line 45 of file PixelTrack.h.
References fAX.
Referenced by PixelFitTracks::Exec().
GetAXErr()
Double_t PixelTrack::GetAXErr () inline
Definition at line 49 of file PixelTrack.h.
References fAXErr.
Referenced by PixelFitTracks::Exec().
GetAY()
Double_t PixelTrack::GetAY () inline
Definition at line 47 of file PixelTrack.h.
References fAY.
Referenced by PixelFitTracks::Exec().
GetAYErr()
Double_t PixelTrack::GetAYErr () inline
Definition at line 51 of file PixelTrack.h.
References fAYErr.
Referenced by PixelFitTracks::Exec().
GetEntryNr()
FairLink FairMultiLinkedData_Interface::GetEntryNr () const inherited
Definition at line 101 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetEntryNr(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorTimeRecoTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
GetHitIndex()
Int_t PixelTrack::GetHitIndex (Int_t ihit) inline
Definition at line 55 of file PixelTrack.h.
References fHitIndices.
Referenced by PixelFitTracks::Exec().
GetLink()
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const inherited
returns the FairLink at the given position
Definition at line 91 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetLinks()
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const inherited
returns stored links as FairLinks
Definition at line 72 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetLinksWithType()
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const inherited
returns all FairLinks with the corresponding type
Definition at line 111 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetNLinks()
Int_t FairMultiLinkedData_Interface::GetNLinks () const inherited
returns the number of stored links
Definition at line 82 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetNofHits()
Int_t PixelTrack::GetNofHits () inline
Definition at line 54 of file PixelTrack.h.
References fHitIndices.
Referenced by PixelFitTracks::Exec().
GetPointerToLinks()
FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairPrintFairLinks::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::GetSortedMCTracks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::PrintLinkInfo(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
GetSortedMCTracks()
std::vector< FairLink > FairMultiLinkedData_Interface::GetSortedMCTracks () inherited
Definition at line 121 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::GetSortedMCTracks().
GetTimeStamp()
Double_t FairTimeStamp::GetTimeStamp () const inline inherited
Accessors
Definition at line 43 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by StopTime::Call(), TimeGap::Call(), FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), FairRingSorterTask::Exec(), FairTSBufferFunctional::GetData(), FairTimeStampPointDraw::GetValue(), FairTimeStamp::operator<(), FairWriteoutBuffer::PrintData(), FairWriteoutBuffer::PrintStartTimeMap(), FairTimeStamp::PrintTimeInfo(), and FairTestDetectorDigi::ToString().
GetTimeStampError()
Double_t FairTimeStamp::GetTimeStampError () const inline inherited
Definition at line 44 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and FairTimeStamp::PrintTimeInfo().
GetX0()
Double_t PixelTrack::GetX0 () inline
Definition at line 44 of file PixelTrack.h.
References fX0.
Referenced by PixelFitTracks::Exec().
GetX0Err()
Double_t PixelTrack::GetX0Err () inline
Definition at line 48 of file PixelTrack.h.
References fX0Err.
Referenced by PixelFitTracks::Exec().
GetY0()
Double_t PixelTrack::GetY0 () inline
Definition at line 46 of file PixelTrack.h.
References fY0.
Referenced by PixelFitTracks::Exec().
GetY0Err()
Double_t PixelTrack::GetY0Err () inline
Definition at line 50 of file PixelTrack.h.
References fY0Err.
Referenced by PixelFitTracks::Exec().
IsSortable()
virtual Bool_t FairTimeStamp::IsSortable () const inline virtual inherited
Definition at line 60 of file FairTimeStamp.h.
operator<()
virtual bool FairTimeStamp::operator< (const FairTimeStamp * rValue) const inline virtual inherited
Definition at line 71 of file FairTimeStamp.h.
References FairTimeStamp::GetTimeStamp().
PrintLinkInfo()
std::ostream& FairMultiLinkedData_Interface::PrintLinkInfo (std::ostream & out = std::cout) const inline inherited
Output.
Definition at line 66 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::PrintLinkInfo().
Referenced by FairTimeStamp::PrintTimeInfo().
PrintTimeInfo()
std::ostream & FairTimeStamp::PrintTimeInfo (std::ostream & out = std::cout) const virtual inherited
Definition at line 12 of file FairTimeStamp.cxx.
References FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), and FairMultiLinkedData_Interface::PrintLinkInfo().
ResetLinks()
void FairMultiLinkedData_Interface::ResetLinks () inherited
Definition at line 193 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
serialize()
template<class Archive > void PixelTrack::serialize (Archive & ar, const unsigned int) inline
Definition at line 61 of file PixelTrack.h.
SetAX()
void PixelTrack::SetAX (Double_t ax) inline
Definition at line 36 of file PixelTrack.h.
References fAX.
SetAXErr()
void PixelTrack::SetAXErr (Double_t axe) inline
Definition at line 40 of file PixelTrack.h.
References fAXErr.
SetAY()
void PixelTrack::SetAY (Double_t ay) inline
Definition at line 38 of file PixelTrack.h.
References fAY.
SetAYERr()
void PixelTrack::SetAYERr (Double_t aye) inline
Definition at line 42 of file PixelTrack.h.
References fAYErr.
SetEntryNr()
void FairMultiLinkedData_Interface::SetEntryNr (FairLink val) inherited
Definition at line 147 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetEntryNr().
Referenced by FairRingSorterTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetInsertHistory()
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) inherited
Definition at line 186 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetLink()
void FairMultiLinkedData_Interface::SetLink (FairLink link) inherited
Sets the Links with a single FairLink.
Definition at line 139 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetector::AddHit(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
SetLinks()
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 131 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetPointerToLinks()
void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline inherited
Definition at line 55 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
SetTimeStamp()
void FairTimeStamp::SetTimeStamp (Double_t t) inline inherited
Modifiers
Definition at line 46 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and MyHit::MyHit().
SetTimeStampError()
void FairTimeStamp::SetTimeStampError (Double_t t) inline inherited
Definition at line 47 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and MyHit::MyHit().
SetX0()
void PixelTrack::SetX0 (Double_t x0) inline
Definition at line 35 of file PixelTrack.h.
References fX0.
SetX0Err()
void PixelTrack::SetX0Err (Double_t x0e) inline
Definition at line 39 of file PixelTrack.h.
References fX0Err.
SetY0()
void PixelTrack::SetY0 (Double_t y0) inline
Definition at line 37 of file PixelTrack.h.
References fY0.
SetY0Err()
void PixelTrack::SetY0Err (Double_t y0e) inline
Definition at line 41 of file PixelTrack.h.
References fY0Err.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 67 of file PixelTrack.h.
Member Data Documentation
fAX
Double_t PixelTrack::fAX private
Definition at line 70 of file PixelTrack.h.
Referenced by GetAX(), and SetAX().
fAXErr
Double_t PixelTrack::fAXErr private
Definition at line 74 of file PixelTrack.h.
Referenced by GetAXErr(), and SetAXErr().
fAY
Double_t PixelTrack::fAY private
Definition at line 72 of file PixelTrack.h.
Referenced by GetAY(), and SetAY().
fAYErr
Double_t PixelTrack::fAYErr private
Definition at line 76 of file PixelTrack.h.
Referenced by GetAYErr(), and SetAYERr().
fHitIndices
std::vector<Int_t> PixelTrack::fHitIndices private
Definition at line 78 of file PixelTrack.h.
Referenced by AddHitIndex(), GetHitIndex(), and GetNofHits().
fLink
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
fTimeStamp
Double_t FairTimeStamp::fTimeStamp protected inherited
Definition at line 89 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStamp(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStamp().
fTimeStampError
Double_t FairTimeStamp::fTimeStampError protected inherited
Time of digit or Hit [ns]
Definition at line 90 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStampError(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStampError().
fX0
Double_t PixelTrack::fX0 private
Definition at line 69 of file PixelTrack.h.
Referenced by GetX0(), and SetX0().
fX0Err
Double_t PixelTrack::fX0Err private
Definition at line 73 of file PixelTrack.h.
Referenced by GetX0Err(), and SetX0Err().
fY0
Double_t PixelTrack::fY0 private
Definition at line 71 of file PixelTrack.h.
Referenced by GetY0(), and SetY0().
fY0Err
Double_t PixelTrack::fY0Err private
Definition at line 75 of file PixelTrack.h.
Referenced by GetY0Err(), and SetY0Err().
The documentation for this class was generated from the following files:
PixelTrack.h
PixelTrack.cxx