FairRoot: FairBoxSetDraw Class Reference
FairBoxSetDraw Class Reference abstract
#include <FairBoxSetDraw.h>
Public Member Functions
FairBoxSetDraw ()
FairBoxSetDraw (const char *name, Int_t iVerbose=1)
virtual ~FairBoxSetDraw ()
virtual Double_t GetTimeWindowPlus ()
virtual Double_t GetTimeWindowMinus ()
virtual void SetVerbose (Int_t iVerbose)
virtual void SetBoxDimensions (Double_t x, Double_t y, Double_t z)
virtual void SetTimeWindowMinus (Double_t val)
virtual void SetTimeWindowPlus (Double_t val)
virtual void SetStartTime (Double_t val)
virtual void UseEventTimeAsStartTime (Bool_t val=kTRUE)
virtual void Exec (Option_t *option)
FairBoxSet * CreateBoxSet ()
void Reset ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Finish ()
virtual TVector3 GetVector (TObject *obj)=0
virtual Int_t GetValue (TObject *obj, Int_t i)
virtual void AddBoxes (FairBoxSet *set, TObject *obj, Int_t i=0)
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
TClonesArray * fList
FairEventManager * fEventManager
FairRootManager * fManager
FairBoxSet * fq
Double_t fX
Double_t fY
Double_t fZ
Double_t fTimeWindowPlus
Double_t fTimeWindowMinus
Double_t fStartTime
Bool_t fUseEventTime
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Private Member Functions
FairBoxSetDraw (const FairBoxSetDraw &)
FairBoxSetDraw & operator= (const FairBoxSetDraw &)
ClassDef (FairBoxSetDraw, 1)
Private Attributes
BinaryFunctor * fStartFunctor
BinaryFunctor * fStopFunctor
Detailed Description
Definition at line 41 of file FairBoxSetDraw.h.
Constructor & Destructor Documentation
FairBoxSetDraw() [1/3]
FairBoxSetDraw::FairBoxSetDraw ()
Default constructor
Definition at line 37 of file FairBoxSetDraw.cxx.
FairBoxSetDraw() [2/3]
FairBoxSetDraw::FairBoxSetDraw (const char * name, Int_t iVerbose = 1)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 60 of file FairBoxSetDraw.cxx.
~FairBoxSetDraw()
FairBoxSetDraw::~FairBoxSetDraw () virtual
Destructor
Definition at line 181 of file FairBoxSetDraw.cxx.
FairBoxSetDraw() [3/3]
FairBoxSetDraw::FairBoxSetDraw (const FairBoxSetDraw &) private
Member Function Documentation
AddBoxes()
void FairBoxSetDraw::AddBoxes (FairBoxSet * set, TObject * obj, Int_t i = 0) protected virtual
Definition at line 142 of file FairBoxSetDraw.cxx.
References fVerbose, GetValue(), and GetVector().
Referenced by Exec().
CheckInputPersistance()
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
ClassDef()
FairBoxSetDraw::ClassDef (FairBoxSetDraw , 1) private
CreateBoxSet()
FairBoxSet * FairBoxSetDraw::CreateBoxSet ()
Definition at line 158 of file FairBoxSetDraw.cxx.
References fq, fX, fY, and fZ.
Referenced by Exec().
Exec()
void FairBoxSetDraw::Exec (Option_t * option) virtual
Executed task
Definition at line 108 of file FairBoxSetDraw.cxx.
References AddBoxes(), CreateBoxSet(), fEventManager, fList, fq, fStartFunctor, fStartTime, fStopFunctor, fTimeWindowMinus, fTimeWindowPlus, fUseEventTime, fVerbose, FairRootManager::GetData(), FairRootManager::GetEventTime(), FairRunAna::Instance(), FairRootManager::Instance(), and Reset().
ExecuteTask()
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
ExecuteTasks()
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
Finish()
void FairBoxSetDraw::Finish () protected virtual
Action after each event
Reimplemented from FairTask.
Definition at line 191 of file FairBoxSetDraw.cxx.
FinishEvent()
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
FinishEvents()
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
FinishTask()
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
FinishTasks()
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
GetTimeWindowMinus()
virtual Double_t FairBoxSetDraw::GetTimeWindowMinus () inline virtual
Definition at line 60 of file FairBoxSetDraw.h.
References fTimeWindowMinus.
Referenced by FairBoxSet::GetTimeWindowMinus().
GetTimeWindowPlus()
virtual Double_t FairBoxSetDraw::GetTimeWindowPlus () inline virtual
Definition at line 59 of file FairBoxSetDraw.h.
References fTimeWindowPlus.
Referenced by FairBoxSet::GetTimeWindowPlus().
GetValue()
Int_t FairBoxSetDraw::GetValue (TObject * obj, Int_t i) protected virtual
Reimplemented in FairTimeStampPointDraw.
Definition at line 153 of file FairBoxSetDraw.cxx.
Referenced by AddBoxes().
GetVector()
virtual TVector3 FairBoxSetDraw::GetVector (TObject * obj) protected pure virtual
Implemented in FairHitDraw, and FairTimeStampPointDraw.
Referenced by AddBoxes().
Init()
InitStatus FairBoxSetDraw::Init () protected virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 79 of file FairBoxSetDraw.cxx.
References fEventManager, fList, fManager, fq, fStartFunctor, fStopFunctor, fVerbose, FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), kERROR, and kSUCCESS.
InitTask()
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
InitTasks()
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
IsOutputBranchPersistent()
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
operator=()
FairBoxSetDraw& FairBoxSetDraw::operator= (const FairBoxSetDraw &) private
ReInit()
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, PixelAltFindHits, PixelFindHits, PixelDigitize, PixelFitTracks, FairRingSorterTask, PixelFindTracks, PixelAltDigiWriteToRootVector, PixelDigiWriteToBinFile, PixelDigiWriteToFile, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 120 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
ReInitTask()
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
ReInitTasks()
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
Reset()
void FairBoxSetDraw::Reset ()
Definition at line 195 of file FairBoxSetDraw.cxx.
References fEventManager, and fq.
Referenced by Exec().
SetBoxDimensions()
virtual void FairBoxSetDraw::SetBoxDimensions (Double_t x, Double_t y, Double_t z) inline virtual
Definition at line 64 of file FairBoxSetDraw.h.
References fX, fY, and fZ.
SetInputPersistance()
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
SetOutputBranchPersistent()
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
SetParContainers()
void FairBoxSetDraw::SetParContainers () protected virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 185 of file FairBoxSetDraw.cxx.
SetParTask()
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
SetParTasks()
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
SetStartTime()
virtual void FairBoxSetDraw::SetStartTime (Double_t val) inline virtual
Definition at line 72 of file FairBoxSetDraw.h.
References fStartTime.
SetStreamProcessing()
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
SetTimeWindowMinus()
void FairBoxSetDraw::SetTimeWindowMinus (Double_t val) virtual
Definition at line 170 of file FairBoxSetDraw.cxx.
References fTimeWindowMinus.
Referenced by FairBoxSet::SetTimeWindowMinus().
SetTimeWindowPlus()
void FairBoxSetDraw::SetTimeWindowPlus (Double_t val) virtual
Definition at line 175 of file FairBoxSetDraw.cxx.
References fTimeWindowPlus.
Referenced by FairBoxSet::SetTimeWindowPlus().
SetVerbose()
virtual void FairBoxSetDraw::SetVerbose (Int_t iVerbose) inline virtual
Set verbosity level. For this task and all of the subtasks.
Definition at line 63 of file FairBoxSetDraw.h.
References fVerbose.
UseEventTimeAsStartTime()
virtual void FairBoxSetDraw::UseEventTimeAsStartTime (Bool_t val = kTRUE) inline virtual
Definition at line 73 of file FairBoxSetDraw.h.
References fUseEventTime.
Member Data Documentation
fEventManager
FairEventManager* FairBoxSetDraw::fEventManager protected
Definition at line 95 of file FairBoxSetDraw.h.
Referenced by Exec(), Init(), and Reset().
fInputPersistance
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
fList
TClonesArray* FairBoxSetDraw::fList protected
Definition at line 94 of file FairBoxSetDraw.h.
Referenced by Exec(), and Init().
fLogger
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
fManager
FairRootManager* FairBoxSetDraw::fManager protected
Definition at line 96 of file FairBoxSetDraw.h.
Referenced by Init().
fq
FairBoxSet* FairBoxSetDraw::fq protected
Definition at line 97 of file FairBoxSetDraw.h.
Referenced by CreateBoxSet(), Exec(), Init(), and Reset().
fStartFunctor
BinaryFunctor* FairBoxSetDraw::fStartFunctor private
Definition at line 109 of file FairBoxSetDraw.h.
Referenced by Exec(), and Init().
fStartTime
Double_t FairBoxSetDraw::fStartTime protected
Definition at line 102 of file FairBoxSetDraw.h.
Referenced by Exec(), and SetStartTime().
fStopFunctor
BinaryFunctor* FairBoxSetDraw::fStopFunctor private
Definition at line 110 of file FairBoxSetDraw.h.
Referenced by Exec(), and Init().
fStreamProcessing
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
fTimeWindowMinus
Double_t FairBoxSetDraw::fTimeWindowMinus protected
Definition at line 101 of file FairBoxSetDraw.h.
Referenced by Exec(), GetTimeWindowMinus(), and SetTimeWindowMinus().
fTimeWindowPlus
Double_t FairBoxSetDraw::fTimeWindowPlus protected
Definition at line 100 of file FairBoxSetDraw.h.
Referenced by Exec(), GetTimeWindowPlus(), and SetTimeWindowPlus().
fUseEventTime
Bool_t FairBoxSetDraw::fUseEventTime protected
Definition at line 103 of file FairBoxSetDraw.h.
Referenced by Exec(), and UseEventTimeAsStartTime().
fVerbose
Int_t FairBoxSetDraw::fVerbose protected
Definition at line 84 of file FairBoxSetDraw.h.
Referenced by AddBoxes(), Exec(), Init(), and SetVerbose().
fX
Double_t FairBoxSetDraw::fX protected
Definition at line 98 of file FairBoxSetDraw.h.
Referenced by CreateBoxSet(), and SetBoxDimensions().
fY
Double_t FairBoxSetDraw::fY protected
Definition at line 98 of file FairBoxSetDraw.h.
Referenced by CreateBoxSet(), and SetBoxDimensions().
fZ
Double_t FairBoxSetDraw::fZ protected
Definition at line 98 of file FairBoxSetDraw.h.
Referenced by CreateBoxSet(), and SetBoxDimensions().
The documentation for this class was generated from the following files:
FairBoxSetDraw.h
FairBoxSetDraw.cxx