FairRoot: FairMBSRawItem Class Reference
FairMBSRawItem Class Reference
#include <FairMBSRawItem.h>
Public Member Functions
FairMBSRawItem ()
FairMBSRawItem (UShort_t sam, UShort_t gtb, UShort_t tacAddr, UShort_t tacCh, UShort_t cal, UShort_t clock, UShort_t tacData, UShort_t qdcData)
FairMBSRawItem (const FairMBSRawItem &)
virtual ~FairMBSRawItem ()
const UShort_t & GetSam () const
const UShort_t & GetGtb () const
const UShort_t & GetTacCh () const
const UShort_t & GetTacAddr () const
const UShort_t & GetCal () const
const UShort_t & GetClock () const
const UShort_t & GetTacData () const
const UShort_t & GetQdcData () const
Protected Attributes
UShort_t fSam
UShort_t fGtb
UShort_t fTacAddr
UShort_t fTacCh
UShort_t fCal
UShort_t fClock
UShort_t fTacData
UShort_t fQdcData
Detailed Description
An example class for raw data object of a detector.
Definition at line 17 of file FairMBSRawItem.h.
Constructor & Destructor Documentation
FairMBSRawItem() [1/3]
FairMBSRawItem::FairMBSRawItem ()
Default Constructor.
Definition at line 11 of file FairMBSRawItem.cxx.
FairMBSRawItem() [2/3]
FairMBSRawItem::FairMBSRawItem (UShort_t sam, UShort_t gtb, UShort_t tacAddr, UShort_t tacCh, UShort_t cal, UShort_t clock, UShort_t tacData, UShort_t qdcData)
Standard Constructor.
Parameters
sam a SAM value
gtb a GTB value
tacAddr TAC module address
tacCh TAC channel number
cal calibration bit
clock clock data
tacData TAC data
qdcData QDC data
Definition at line 24 of file FairMBSRawItem.cxx.
FairMBSRawItem() [3/3]
FairMBSRawItem::FairMBSRawItem (const FairMBSRawItem & right)
Definition at line 44 of file FairMBSRawItem.cxx.
~FairMBSRawItem()
virtual FairMBSRawItem::~FairMBSRawItem () inline virtual
Definition at line 44 of file FairMBSRawItem.h.
Member Function Documentation
GetCal()
const UShort_t& FairMBSRawItem::GetCal () const inline
Definition at line 64 of file FairMBSRawItem.h.
References fCal.
GetClock()
const UShort_t& FairMBSRawItem::GetClock () const inline
Definition at line 68 of file FairMBSRawItem.h.
References fClock.
Referenced by FairMBSTask::Exec().
GetGtb()
const UShort_t& FairMBSRawItem::GetGtb () const inline
Definition at line 52 of file FairMBSRawItem.h.
References fGtb.
GetQdcData()
const UShort_t& FairMBSRawItem::GetQdcData () const inline
Definition at line 76 of file FairMBSRawItem.h.
References fQdcData.
Referenced by FairMBSTask::Exec().
GetSam()
const UShort_t& FairMBSRawItem::GetSam () const inline
Definition at line 48 of file FairMBSRawItem.h.
References fSam.
GetTacAddr()
const UShort_t& FairMBSRawItem::GetTacAddr () const inline
Definition at line 60 of file FairMBSRawItem.h.
References fTacAddr.
GetTacCh()
const UShort_t& FairMBSRawItem::GetTacCh () const inline
Definition at line 56 of file FairMBSRawItem.h.
References fTacCh.
Referenced by FairMBSTask::Exec().
GetTacData()
const UShort_t& FairMBSRawItem::GetTacData () const inline
Definition at line 72 of file FairMBSRawItem.h.
References fTacData.
Referenced by FairMBSTask::Exec().
Member Data Documentation
fCal
UShort_t FairMBSRawItem::fCal protected
Calibration bit.
Definition at line 86 of file FairMBSRawItem.h.
Referenced by GetCal().
fClock
UShort_t FairMBSRawItem::fClock protected
Clock data.
Definition at line 87 of file FairMBSRawItem.h.
Referenced by GetClock().
fGtb
UShort_t FairMBSRawItem::fGtb protected
GTB value.
Definition at line 83 of file FairMBSRawItem.h.
Referenced by GetGtb().
fQdcData
UShort_t FairMBSRawItem::fQdcData protected
QDC data.
Definition at line 89 of file FairMBSRawItem.h.
Referenced by GetQdcData().
fSam
UShort_t FairMBSRawItem::fSam protected
SAM value.
Definition at line 82 of file FairMBSRawItem.h.
Referenced by GetSam().
fTacAddr
UShort_t FairMBSRawItem::fTacAddr protected
TAC module address.
Definition at line 84 of file FairMBSRawItem.h.
Referenced by GetTacAddr().
fTacCh
UShort_t FairMBSRawItem::fTacCh protected
TAC channel number.
Definition at line 85 of file FairMBSRawItem.h.
Referenced by GetTacCh().
fTacData
UShort_t FairMBSRawItem::fTacData protected
TAC data.
Definition at line 88 of file FairMBSRawItem.h.
Referenced by GetTacData().
The documentation for this class was generated from the following files:
FairMBSRawItem.h
FairMBSRawItem.cxx