FairRoot: FairMBSUnpack Class Reference
FairMBSUnpack Class Reference
#include <FairMBSUnpack.h>
Public Member Functions
FairMBSUnpack (Short_t type=94, Short_t subType=9400, Short_t procId=10, Short_t subCrate=1, Short_t control=3)
virtual ~FairMBSUnpack ()
virtual Bool_t Init ()
virtual Bool_t DoUnpack (Int_t *data, Int_t size)
virtual void Reset ()
Int_t GetNHitsTotal ()
virtual Bool_t ReInit ()
virtual void SetParContainers ()
Short_t GetType () const
Short_t GetSubType () const
Short_t GetProcId () const
Short_t GetSubCrate () const
Short_t GetControl () const
Protected Member Functions
virtual void Register ()
Private Member Functions
FairMBSUnpack (const FairMBSUnpack &)
FairMBSUnpack & operator= (const FairMBSUnpack &)
Private Attributes
TClonesArray * fRawData
Int_t fNHits
Int_t fNHitsTotal
Detailed Description
An example unpacker of MBS data.
Definition at line 19 of file FairMBSUnpack.h.
Constructor & Destructor Documentation
FairMBSUnpack() [1/2]
FairMBSUnpack::FairMBSUnpack (Short_t type = 94, Short_t subType = 9400, Short_t procId = 10, Short_t subCrate = 1, Short_t control = 3)
Standard Constructor. Input - MBS parameters of the detector.
Definition at line 22 of file FairMBSUnpack.cxx.
~FairMBSUnpack()
FairMBSUnpack::~FairMBSUnpack () virtual
Destructor.
Definition at line 31 of file FairMBSUnpack.cxx.
References fRawData.
FairMBSUnpack() [2/2]
FairMBSUnpack::FairMBSUnpack (const FairMBSUnpack &) private
Member Function Documentation
DoUnpack()
Bool_t FairMBSUnpack::DoUnpack (Int_t * data, Int_t size) virtual
Process an MBS sub-event.
Implements FairUnpack.
Definition at line 58 of file FairMBSUnpack.cxx.
References fNHits, and fNHitsTotal.
GetControl()
Short_t FairUnpack::GetControl () const inline inherited
Definition at line 38 of file FairUnpack.h.
References FairUnpack::fControl.
Referenced by FairMbsSource::Unpack().
GetNHitsTotal()
Int_t FairMBSUnpack::GetNHitsTotal () inline
Method for controling the functionality.
Definition at line 42 of file FairMBSUnpack.h.
References fNHitsTotal.
Referenced by unpack_mbs().
GetProcId()
Short_t FairUnpack::GetProcId () const inline inherited
Definition at line 36 of file FairUnpack.h.
References FairUnpack::fProcId.
Referenced by FairMbsSource::Unpack().
GetSubCrate()
Short_t FairUnpack::GetSubCrate () const inline inherited
Definition at line 37 of file FairUnpack.h.
References FairUnpack::fSubCrate.
Referenced by FairMbsSource::Unpack().
GetSubType()
Short_t FairUnpack::GetSubType () const inline inherited
Definition at line 35 of file FairUnpack.h.
References FairUnpack::fSubType.
Referenced by FairMbsSource::Unpack().
GetType()
Short_t FairUnpack::GetType () const inline inherited
Definition at line 34 of file FairUnpack.h.
References FairUnpack::fType.
Referenced by FairMbsSource::Unpack().
Init()
Bool_t FairMBSUnpack::Init () virtual
Initialization. Called once, before the event loop.
Implements FairUnpack.
Definition at line 38 of file FairMBSUnpack.cxx.
References Register().
operator=()
FairMBSUnpack& FairMBSUnpack::operator= (const FairMBSUnpack &) private
Register()
void FairMBSUnpack::Register () protected virtual
Register the output structures.
Implements FairUnpack.
Definition at line 45 of file FairMBSUnpack.cxx.
References fRawData, FairRootManager::Instance(), and FairRootManager::Register().
Referenced by Init().
ReInit()
virtual Bool_t FairUnpack::ReInit () inline virtual inherited
Definition at line 29 of file FairUnpack.h.
Reset()
void FairMBSUnpack::Reset () virtual
Clear the output structures.
Implements FairUnpack.
Definition at line 121 of file FairMBSUnpack.cxx.
References fNHits, and fRawData.
SetParContainers()
virtual void FairUnpack::SetParContainers () inline virtual inherited
Definition at line 32 of file FairUnpack.h.
Member Data Documentation
fNHits
Int_t FairMBSUnpack::fNHits private
Number of raw items in current event.
Definition at line 53 of file FairMBSUnpack.h.
Referenced by DoUnpack(), and Reset().
fNHitsTotal
Int_t FairMBSUnpack::fNHitsTotal private
Total number of raw items.
Definition at line 54 of file FairMBSUnpack.h.
Referenced by DoUnpack(), and GetNHitsTotal().
fRawData
TClonesArray* FairMBSUnpack::fRawData private
Array of output raw items.
Definition at line 52 of file FairMBSUnpack.h.
Referenced by Register(), Reset(), and ~FairMBSUnpack().
The documentation for this class was generated from the following files:
FairMBSUnpack.h
FairMBSUnpack.cxx