FairRroot: fair::mq::Plugin Class Reference
fair::mq::Plugin Class Reference
Base class for FairMQ plugins.
#include <fairmq/Plugin.h>
Public Types
using ProgOptions = boost::optional< boost::program_options::options_description >
using Version = tools::Version
using DeviceState = fair::mq::PluginServices::DeviceState
using DeviceStateTransition = fair::mq::PluginServices::DeviceStateTransition
Public Member Functions
Plugin ()=delete
Plugin (const std::string name, const Version version, const std::string maintainer, const std::string homepage, PluginServices *pluginServices)
Plugin (const Plugin &)=delete
Plugin operator= (const Plugin &)=delete
virtual ~Plugin ()
auto GetName () const -> const std::string &
auto GetVersion () const -> const Version
auto GetMaintainer () const -> const std::string &
auto GetHomepage () const -> const std::string &
auto ToDeviceState (const std::string &state) const -> DeviceState
auto ToDeviceStateTransition (const std::string &transition) const -> DeviceStateTransition
auto ToStr (DeviceState state) const -> std::string
auto ToStr (DeviceStateTransition transition) const -> std::string
auto GetCurrentDeviceState () const -> DeviceState
auto TakeDeviceControl () -> void
auto StealDeviceControl () -> void
auto ReleaseDeviceControl () -> void
auto ChangeDeviceState (const DeviceStateTransition next) -> void
auto SubscribeToDeviceStateChange (std::function< void(DeviceState)> callback) -> void
auto UnsubscribeFromDeviceStateChange () -> void
auto PropertyExists (const std::string &key) -> int
template<typename T >
auto SetProperty (const std::string &key, T val) -> void
template<typename T >
auto GetProperty (const std::string &key) const -> T
auto GetPropertyAsString (const std::string &key) const -> std::string
auto GetChannelInfo () const -> std::unordered_map< std::string, int >
auto GetPropertyKeys () const -> std::vector< std::string >
template<typename T >
auto SubscribeToPropertyChange (std::function< void(const std::string &key, T newValue)> callback) -> void
template<typename T >
auto UnsubscribeFromPropertyChange () -> void
auto SubscribeToPropertyChangeAsString (std::function< void(const std::string &key, std::string newValue)> callback) -> void
auto UnsubscribeFromPropertyChangeAsString () -> void
Static Public Member Functions
static auto NoProgramOptions () -> ProgOptions
Private Attributes
const std::string fkName
const Version fkVersion
const std::string fkMaintainer
const std::string fkHomepage
PluginServices * fPluginServices
Friends
auto operator== (const Plugin &lhs, const Plugin &rhs) -> bool
auto operator!= (const Plugin &lhs, const Plugin &rhs) -> bool
auto operator<< (std::ostream &os, const Plugin &p) -> std::ostream &
Detailed Description
Base class for FairMQ plugins.
The plugin base class encapsulates the plugin metadata.
Definition at line 38 of file Plugin.h.
Member Typedef Documentation
using fair::mq::Plugin::DeviceState = fair::mq::PluginServices::DeviceState
Definition at line 71 of file Plugin.h.
using fair::mq::Plugin::DeviceStateTransition = fair::mq::PluginServices::DeviceStateTransition
Definition at line 72 of file Plugin.h.
using fair::mq::Plugin::ProgOptions = boost::optional<boost::program_options::options_description>
Definition at line 41 of file Plugin.h.
using fair::mq::Plugin::Version = tools::Version
Definition at line 43 of file Plugin.h.
Constructor & Destructor Documentation
fair::mq::Plugin::Plugin () delete
fair::mq::Plugin::Plugin (const std::string name, const Version version, const std::string maintainer, const std::string homepage, PluginServices * pluginServices)
fair::mq::Plugin::Plugin (const Plugin &) delete
fair::mq::Plugin::~Plugin () virtual
Definition at line 24 of file Plugin.cxx.
References fair::debug, and LOG.
Member Function Documentation
auto fair::mq::Plugin::ChangeDeviceState (const DeviceStateTransition next) -> void inline
Definition at line 81 of file Plugin.h.
References fair::mq::PluginServices::ChangeDeviceState(), fkName, and fPluginServices.
auto fair::mq::Plugin::GetChannelInfo () const -> std::unordered_map<std::string, int> inline
Definition at line 93 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::GetChannelInfo().
auto fair::mq::Plugin::GetCurrentDeviceState () const -> DeviceState inline
Definition at line 77 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::GetCurrentDeviceState().
auto fair::mq::Plugin::GetHomepage () const -> const std::string& inline
Definition at line 56 of file Plugin.h.
References fkHomepage.
auto fair::mq::Plugin::GetMaintainer () const -> const std::string& inline
Definition at line 55 of file Plugin.h.
References fkMaintainer.
auto fair::mq::Plugin::GetName () const -> const std::string& inline
Definition at line 53 of file Plugin.h.
References fkName.
template<typename T > auto fair::mq::Plugin::GetProperty (const std::string & key) const -> T inline
Definition at line 91 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::GetProperty().
auto fair::mq::Plugin::GetPropertyAsString (const std::string & key) const -> std::string inline
Definition at line 92 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::GetPropertyAsString().
auto fair::mq::Plugin::GetPropertyKeys () const -> std::vector<std::string> inline
Definition at line 94 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::GetPropertyKeys().
auto fair::mq::Plugin::GetVersion () const -> const Version inline
Definition at line 54 of file Plugin.h.
References fkVersion.
static auto fair::mq::Plugin::NoProgramOptions () -> ProgOptions inline static
Definition at line 67 of file Plugin.h.
Plugin fair::mq::Plugin::operator= (const Plugin &) delete
auto fair::mq::Plugin::PropertyExists (const std::string & key) -> int inline
Definition at line 87 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::PropertyExists().
auto fair::mq::Plugin::ReleaseDeviceControl () -> void inline
Definition at line 80 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::ReleaseDeviceControl().
template<typename T > auto fair::mq::Plugin::SetProperty (const std::string & key, T val) -> void inline
Definition at line 89 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::SetProperty().
auto fair::mq::Plugin::StealDeviceControl () -> void inline
Definition at line 79 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::StealDeviceControl().
auto fair::mq::Plugin::SubscribeToDeviceStateChange (std::function< void(DeviceState)> callback) -> void inline
Definition at line 82 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::SubscribeToDeviceStateChange().
Referenced by fair::mq::test::DummyPlugin::DummyPlugin().
template<typename T > auto fair::mq::Plugin::SubscribeToPropertyChange (std::function< void(const std::string &key, T newValue)> callback) -> void inline
Definition at line 96 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::SubscribeToPropertyChange().
auto fair::mq::Plugin::SubscribeToPropertyChangeAsString (std::function< void(const std::string &key, std::string newValue)> callback) -> void inline
Definition at line 99 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::SubscribeToPropertyChangeAsString().
auto fair::mq::Plugin::TakeDeviceControl () -> void inline
Definition at line 78 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::TakeDeviceControl().
auto fair::mq::Plugin::ToDeviceState (const std::string & state) const -> DeviceState inline
Definition at line 73 of file Plugin.h.
References fPluginServices, fair::state, and fair::mq::PluginServices::ToDeviceState().
auto fair::mq::Plugin::ToDeviceStateTransition (const std::string & transition) const -> DeviceStateTransition inline
Definition at line 74 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::ToDeviceStateTransition().
auto fair::mq::Plugin::ToStr (DeviceState state) const -> std::string inline
Definition at line 75 of file Plugin.h.
References fPluginServices, fair::state, and fair::mq::PluginServices::ToStr().
auto fair::mq::Plugin::ToStr (DeviceStateTransition transition) const -> std::string inline
Definition at line 76 of file Plugin.h.
References fPluginServices, and fair::mq::PluginServices::ToStr().
auto fair::mq::Plugin::UnsubscribeFromDeviceStateChange () -> void inline
Definition at line 83 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::UnsubscribeFromDeviceStateChange().
Referenced by fair::mq::test::DummyPlugin::DummyPlugin().
template<typename T > auto fair::mq::Plugin::UnsubscribeFromPropertyChange () -> void inline
Definition at line 98 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::UnsubscribeFromPropertyChange().
auto fair::mq::Plugin::UnsubscribeFromPropertyChangeAsString () -> void inline
Definition at line 100 of file Plugin.h.
References fkName, fPluginServices, and fair::mq::PluginServices::UnsubscribeFromPropertyChangeAsString().
Friends And Related Function Documentation
auto operator!= (const Plugin & lhs, const Plugin & rhs) -> bool friend
Definition at line 59 of file Plugin.h.
auto operator<< (std::ostream & os, const Plugin & p) -> std::ostream& friend
Definition at line 60 of file Plugin.h.
auto operator== (const Plugin & lhs, const Plugin & rhs) -> bool friend
Definition at line 58 of file Plugin.h.
Member Data Documentation
const std::string fair::mq::Plugin::fkHomepage private
Definition at line 106 of file Plugin.h.
Referenced by GetHomepage().
const std::string fair::mq::Plugin::fkMaintainer private
Definition at line 105 of file Plugin.h.
Referenced by GetMaintainer().
const std::string fair::mq::Plugin::fkName private
Definition at line 103 of file Plugin.h.
Referenced by ChangeDeviceState(), GetName(), ReleaseDeviceControl(), StealDeviceControl(), SubscribeToDeviceStateChange(), SubscribeToPropertyChange(), SubscribeToPropertyChangeAsString(), TakeDeviceControl(), UnsubscribeFromDeviceStateChange(), UnsubscribeFromPropertyChange(), and UnsubscribeFromPropertyChangeAsString().
const Version fair::mq::Plugin::fkVersion private
Definition at line 104 of file Plugin.h.
Referenced by GetVersion().
PluginServices* fair::mq::Plugin::fPluginServices private
Definition at line 107 of file Plugin.h.
Referenced by ChangeDeviceState(), GetChannelInfo(), GetCurrentDeviceState(), GetProperty(), GetPropertyAsString(), GetPropertyKeys(), PropertyExists(), ReleaseDeviceControl(), SetProperty(), StealDeviceControl(), SubscribeToDeviceStateChange(), SubscribeToPropertyChange(), SubscribeToPropertyChangeAsString(), TakeDeviceControl(), ToDeviceState(), ToDeviceStateTransition(), ToStr(), UnsubscribeFromDeviceStateChange(), UnsubscribeFromPropertyChange(), and UnsubscribeFromPropertyChangeAsString().
The documentation for this class was generated from the following files:
Plugin.h
Plugin.cxx