FairRoot: FairTestDetectorDigiWriteoutBuffer Class Reference
FairTestDetectorDigiWriteoutBuffer Class Reference
#include <FairTestDetectorDigiWriteoutBuffer.h>
Public Member Functions
FairTestDetectorDigiWriteoutBuffer ()
FairTestDetectorDigiWriteoutBuffer (TString branchName, TString folderName, Bool_t persistance)
virtual ~FairTestDetectorDigiWriteoutBuffer ()
void AddNewDataToTClonesArray (FairTimeStamp *)
store the data from the FairTimeStamp pointer in a TClonesArray (you have to cast it to your type of data)
virtual double FindTimeForData (FairTimeStamp *data)
if the same data object (like a pad or a pixel) is already present in the buffer, the time of this object has to be returned otherwise -1
virtual void FillDataMap (FairTimeStamp *data, double activeTime)
add a new element in the search buffer
virtual void EraseDataFromDataMap (FairTimeStamp *data)
delete the element from the search buffer (see PndSdsDigiPixelWriteoutBuffer)
virtual void SaveDataToTree (Bool_t val=kTRUE)
virtual void ActivateBuffering (Bool_t val=kTRUE)
Bool_t IsBufferingActivated ()
virtual void FillNewData (FairTimeStamp *data, double startTime, double activeTime)
virtual Int_t GetNData ()
virtual std::vector< FairTimeStamp * > GetRemoveOldData (double time)
virtual std::vector< FairTimeStamp * > GetAllData ()
virtual void SetVerbose (Int_t val)
virtual void DeleteOldData ()
virtual void WriteOutData (double time)
virtual void WriteOutAllData ()
Protected Member Functions
ClassDef (FairTestDetectorDigiWriteoutBuffer, 1)
virtual std::vector< std::pair< double, FairTimeStamp * > > Modify (std::pair< double, FairTimeStamp *> oldData, std::pair< double, FairTimeStamp *>)
virtual void WriteOutDataDeadTimeMap (double time)
virtual void MoveDataFromStartTimeMapToDeadTimeMap (double time)
virtual void FillDataToDeadTimeMap (FairTimeStamp *data, double activeTime, double startTime)
virtual void PrintData (FairTimeStamp *data)
virtual void PrintDeadTimeMap ()
Method should be overwritten in derived classes to print the data of an object stored in the buffer.
virtual void PrintStartTimeMap ()
Protected Attributes
std::map< FairTestDetectorDigi, double > fData_map
std::multimap< double, std::pair< double, FairTimeStamp * > > fStartTime_map
std::multimap< double, FairTimeStamp * > fDeadTime_map
TString fBranchName
TString fClassName
Bool_t fTreeSave
Bool_t fActivateBuffering
Int_t fVerbose
FairLogger * fLogger
Detailed Description
Definition at line 29 of file FairTestDetectorDigiWriteoutBuffer.h.
Constructor & Destructor Documentation
FairTestDetectorDigiWriteoutBuffer() [1/2]
FairTestDetectorDigiWriteoutBuffer::FairTestDetectorDigiWriteoutBuffer ()
Definition at line 28 of file FairTestDetectorDigiWriteoutBuffer.cxx.
FairTestDetectorDigiWriteoutBuffer() [2/2]
FairTestDetectorDigiWriteoutBuffer::FairTestDetectorDigiWriteoutBuffer (TString branchName, TString folderName, Bool_t persistance)
Definition at line 36 of file FairTestDetectorDigiWriteoutBuffer.cxx.
~FairTestDetectorDigiWriteoutBuffer()
FairTestDetectorDigiWriteoutBuffer::~FairTestDetectorDigiWriteoutBuffer () virtual
Definition at line 42 of file FairTestDetectorDigiWriteoutBuffer.cxx.
Member Function Documentation
ActivateBuffering()
virtual void FairWriteoutBuffer::ActivateBuffering (Bool_t val = kTRUE) inline virtual inherited
< fActivateBuffering has to be set to kTRUE to use the buffering. Otherwise the data is directly stored in the given TClonesArray.
Definition at line 61 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fActivateBuffering.
Referenced by FairTestDetectorTimeDigiTask::Init().
AddNewDataToTClonesArray()
void FairTestDetectorDigiWriteoutBuffer::AddNewDataToTClonesArray (FairTimeStamp * data) virtual
store the data from the FairTimeStamp pointer in a TClonesArray (you have to cast it to your type of data)
Implements FairWriteoutBuffer.
Definition at line 47 of file FairTestDetectorDigiWriteoutBuffer.cxx.
References FairWriteoutBuffer::fBranchName, FairWriteoutBuffer::fVerbose, FairRootManager::GetTClonesArray(), and FairRootManager::Instance().
ClassDef()
FairTestDetectorDigiWriteoutBuffer::ClassDef (FairTestDetectorDigiWriteoutBuffer , 1) protected
DeleteOldData()
virtual void FairWriteoutBuffer::DeleteOldData () inline virtual inherited
Definition at line 82 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fBranchName, FairRootManager::GetTClonesArray(), and FairRootManager::Instance().
EraseDataFromDataMap()
void FairTestDetectorDigiWriteoutBuffer::EraseDataFromDataMap (FairTimeStamp * data) virtual
delete the element from the search buffer (see PndSdsDigiPixelWriteoutBuffer)
Implements FairWriteoutBuffer.
Definition at line 80 of file FairTestDetectorDigiWriteoutBuffer.cxx.
References fData_map.
FillDataMap()
void FairTestDetectorDigiWriteoutBuffer::FillDataMap (FairTimeStamp * data, double activeTime) virtual
add a new element in the search buffer
Implements FairWriteoutBuffer.
Definition at line 74 of file FairTestDetectorDigiWriteoutBuffer.cxx.
References fData_map.
FillDataToDeadTimeMap()
void FairWriteoutBuffer::FillDataToDeadTimeMap (FairTimeStamp * data, double activeTime, double startTime) protected virtual inherited
Definition at line 168 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::AddNewDataToTClonesArray(), FairTimeStamp::equal(), FairWriteoutBuffer::EraseDataFromDataMap(), FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fDeadTime_map, FairWriteoutBuffer::FillDataMap(), FairWriteoutBuffer::FindTimeForData(), FairWriteoutBuffer::fVerbose, and FairWriteoutBuffer::Modify().
Referenced by FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap().
FillNewData()
void FairWriteoutBuffer::FillNewData (FairTimeStamp * data, double startTime, double activeTime) virtual inherited
Fills a pointer to a data object into the buffer. StartTime gives the time when the data can influence later data, activeTime gives the time how long the data can influence later data. Both time data has to be given as an absolute time!
Definition at line 150 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::AddNewDataToTClonesArray(), FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fStartTime_map, and FairWriteoutBuffer::fVerbose.
Referenced by FairTestDetectorTimeDigiTask::Exec().
FindTimeForData()
double FairTestDetectorDigiWriteoutBuffer::FindTimeForData (FairTimeStamp * data) virtual
if the same data object (like a pad or a pixel) is already present in the buffer, the time of this object has to be returned otherwise -1
Implements FairWriteoutBuffer.
Definition at line 59 of file FairTestDetectorDigiWriteoutBuffer.cxx.
References fData_map.
GetAllData()
std::vector< FairTimeStamp * > FairWriteoutBuffer::GetAllData () virtual inherited
Definition at line 145 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fDeadTime_map, and FairWriteoutBuffer::GetRemoveOldData().
Referenced by FairEventBuilder::WriteOutAllDeadTimeData().
GetNData()
virtual Int_t FairWriteoutBuffer::GetNData () inline virtual inherited
Definition at line 71 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fDeadTime_map.
GetRemoveOldData()
std::vector< FairTimeStamp * > FairWriteoutBuffer::GetRemoveOldData (double time) virtual inherited
Definition at line 129 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::EraseDataFromDataMap(), FairWriteoutBuffer::fDeadTime_map, and FairWriteoutBuffer::fVerbose.
Referenced by FairWriteoutBuffer::GetAllData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
IsBufferingActivated()
Bool_t FairWriteoutBuffer::IsBufferingActivated () inline inherited
Definition at line 65 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fActivateBuffering.
Modify()
virtual std::vector<std::pair<double, FairTimeStamp*> > FairWriteoutBuffer::Modify (std::pair< double, FairTimeStamp *> oldData, std::pair< double, FairTimeStamp *>) inline protected virtual inherited
Modify defines the behavior of the buffer if data should be stored which is already in the buffer. Parameters are the old data with the active time, the new data with an active time. Modify returns than a vector with the new data which should be stored.
Definition at line 101 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
MoveDataFromStartTimeMapToDeadTimeMap()
void FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap (double time) protected virtual inherited
Definition at line 241 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::FillDataToDeadTimeMap(), and FairWriteoutBuffer::fStartTime_map.
Referenced by FairWriteoutBuffer::WriteOutAllData(), and FairWriteoutBuffer::WriteOutData().
PrintData()
virtual void FairWriteoutBuffer::PrintData (FairTimeStamp * data) inline protected virtual inherited
Definition at line 112 of file FairWriteoutBuffer.h.
References FairTimeStamp::GetTimeStamp().
Referenced by FairWriteoutBuffer::PrintDeadTimeMap().
PrintDeadTimeMap()
void FairWriteoutBuffer::PrintDeadTimeMap () protected virtual inherited
Method should be overwritten in derived classes to print the data of an object stored in the buffer.
Definition at line 266 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fDeadTime_map, and FairWriteoutBuffer::PrintData().
Referenced by FairWriteoutBuffer::WriteOutData().
PrintStartTimeMap()
void FairWriteoutBuffer::PrintStartTimeMap () protected virtual inherited
Definition at line 255 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fStartTime_map, and FairTimeStamp::GetTimeStamp().
Referenced by FairWriteoutBuffer::WriteOutData().
SaveDataToTree()
virtual void FairWriteoutBuffer::SaveDataToTree (Bool_t val = kTRUE) inline virtual inherited
< If SaveDataToTree is set the data is stored at the end of the buffering into the given TClonesArray.
Definition at line 58 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fTreeSave.
SetVerbose()
virtual void FairWriteoutBuffer::SetVerbose (Int_t val) inline virtual inherited
Definition at line 78 of file FairWriteoutBuffer.h.
References FairWriteoutBuffer::fVerbose.
WriteOutAllData()
void FairWriteoutBuffer::WriteOutAllData () virtual inherited
Definition at line 108 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fDeadTime_map, FairWriteoutBuffer::fStartTime_map, FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap(), and FairWriteoutBuffer::WriteOutData().
WriteOutData()
void FairWriteoutBuffer::WriteOutData (double time) virtual inherited
Definition at line 44 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fBranchName, FairWriteoutBuffer::fVerbose, FairRootManager::GetTClonesArray(), FairRootManager::Instance(), FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap(), FairWriteoutBuffer::PrintDeadTimeMap(), FairWriteoutBuffer::PrintStartTimeMap(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
Referenced by FairWriteoutBuffer::WriteOutAllData().
WriteOutDataDeadTimeMap()
void FairWriteoutBuffer::WriteOutDataDeadTimeMap (double time) protected virtual inherited
Definition at line 75 of file FairWriteoutBuffer.cxx.
References FairWriteoutBuffer::AddNewDataToTClonesArray(), FairWriteoutBuffer::fActivateBuffering, FairWriteoutBuffer::fBranchName, FairWriteoutBuffer::fTreeSave, FairWriteoutBuffer::fVerbose, FairWriteoutBuffer::GetRemoveOldData(), FairRootManager::GetTClonesArray(), and FairRootManager::Instance().
Referenced by FairWriteoutBuffer::WriteOutData().
Member Data Documentation
fActivateBuffering
Bool_t FairWriteoutBuffer::fActivateBuffering protected inherited
Definition at line 124 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::ActivateBuffering(), FairWriteoutBuffer::FillDataToDeadTimeMap(), FairWriteoutBuffer::FillNewData(), FairWriteoutBuffer::IsBufferingActivated(), FairEventBuilder::WriteOutAllDeadTimeData(), FairWriteoutBuffer::WriteOutData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
fBranchName
TString FairWriteoutBuffer::fBranchName protected inherited
Definition at line 121 of file FairWriteoutBuffer.h.
Referenced by MyWriteoutBuffer::AddNewDataToTClonesArray(), AddNewDataToTClonesArray(), FairWriteoutBuffer::DeleteOldData(), FairWriteoutBuffer::FairWriteoutBuffer(), FairEventBuilder::WriteOutAllDeadTimeData(), FairWriteoutBuffer::WriteOutData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
fClassName
TString FairWriteoutBuffer::fClassName protected inherited
Definition at line 122 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FairWriteoutBuffer().
fData_map
std::map<FairTestDetectorDigi, double> FairTestDetectorDigiWriteoutBuffer::fData_map protected
Definition at line 45 of file FairTestDetectorDigiWriteoutBuffer.h.
Referenced by EraseDataFromDataMap(), FillDataMap(), and FindTimeForData().
fDeadTime_map
std::multimap<double, FairTimeStamp*> FairWriteoutBuffer::fDeadTime_map protected inherited
Definition at line 119 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap(), FairWriteoutBuffer::GetAllData(), FairWriteoutBuffer::GetNData(), FairWriteoutBuffer::GetRemoveOldData(), FairWriteoutBuffer::PrintDeadTimeMap(), and FairWriteoutBuffer::WriteOutAllData().
fLogger
FairLogger* FairWriteoutBuffer::fLogger protected inherited
Definition at line 126 of file FairWriteoutBuffer.h.
fStartTime_map
std::multimap<double, std::pair<double, FairTimeStamp*> > FairWriteoutBuffer::fStartTime_map protected inherited
Definition at line 118 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FillNewData(), FairWriteoutBuffer::MoveDataFromStartTimeMapToDeadTimeMap(), FairWriteoutBuffer::PrintStartTimeMap(), and FairWriteoutBuffer::WriteOutAllData().
fTreeSave
Bool_t FairWriteoutBuffer::fTreeSave protected inherited
Definition at line 123 of file FairWriteoutBuffer.h.
Referenced by FairWriteoutBuffer::FairWriteoutBuffer(), FairWriteoutBuffer::SaveDataToTree(), FairEventBuilder::WriteOutAllDeadTimeData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
fVerbose
Int_t FairWriteoutBuffer::fVerbose protected inherited
Definition at line 125 of file FairWriteoutBuffer.h.
Referenced by MyWriteoutBuffer::AddNewDataToTClonesArray(), AddNewDataToTClonesArray(), FairWriteoutBuffer::FillDataToDeadTimeMap(), FairWriteoutBuffer::FillNewData(), FairWriteoutBuffer::GetRemoveOldData(), MyWriteoutBuffer::Modify(), FairWriteoutBuffer::SetVerbose(), FairEventBuilder::WriteOutAllDeadTimeData(), FairWriteoutBuffer::WriteOutData(), and FairWriteoutBuffer::WriteOutDataDeadTimeMap().
The documentation for this class was generated from the following files:
FairTestDetectorDigiWriteoutBuffer.h
FairTestDetectorDigiWriteoutBuffer.cxx