FairRroot: FairMQSocket Class Reference
FairMQSocket Class Reference abstract
#include <FairMQSocket.h>
Public Member Functions
FairMQSocket ()
virtual std::string GetId ()=0
virtual bool Bind (const std::string &address)=0
virtual void Connect (const std::string &address)=0
virtual int Send (FairMQMessagePtr &msg, int timeout=0)=0
virtual int Receive (FairMQMessagePtr &msg, int timeout=0)=0
virtual int64_t Send (std::vector< std::unique_ptr< FairMQMessage >> &msgVec, int timeout=0)=0
virtual int64_t Receive (std::vector< std::unique_ptr< FairMQMessage >> &msgVec, int timeout=0)=0
virtual int TrySend (FairMQMessagePtr &msg)=0
virtual int TryReceive (FairMQMessagePtr &msg)=0
virtual int64_t TrySend (std::vector< std::unique_ptr< FairMQMessage >> &msgVec)=0
virtual int64_t TryReceive (std::vector< std::unique_ptr< FairMQMessage >> &msgVec)=0
virtual void * GetSocket () const =0
virtual int GetSocket (int nothing) const =0
virtual void Close ()=0
virtual void SetOption (const std::string &option, const void *value, size_t valueSize)=0
virtual void GetOption (const std::string &option, void *value, size_t *valueSize)=0
virtual unsigned long GetBytesTx () const =0
virtual unsigned long GetBytesRx () const =0
virtual unsigned long GetMessagesTx () const =0
virtual unsigned long GetMessagesRx () const =0
virtual bool SetSendTimeout (const int timeout, const std::string &address, const std::string &method)=0
virtual int GetSendTimeout () const =0
virtual bool SetReceiveTimeout (const int timeout, const std::string &address, const std::string &method)=0
virtual int GetReceiveTimeout () const =0
virtual ~FairMQSocket ()
Detailed Description
Definition at line 18 of file FairMQSocket.h.
Constructor & Destructor Documentation
FairMQSocket::FairMQSocket () inline
Definition at line 21 of file FairMQSocket.h.
virtual FairMQSocket::~FairMQSocket () inline virtual
Definition at line 56 of file FairMQSocket.h.
Member Function Documentation
virtual bool FairMQSocket::Bind (const std::string & address) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
Referenced by FairMQDevice::BindEndpoint().
virtual void FairMQSocket::Close () pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual void FairMQSocket::Connect (const std::string & address) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
Referenced by FairMQDevice::ConnectEndpoint().
virtual unsigned long FairMQSocket::GetBytesRx () const pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual unsigned long FairMQSocket::GetBytesTx () const pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual std::string FairMQSocket::GetId () pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual unsigned long FairMQSocket::GetMessagesRx () const pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual unsigned long FairMQSocket::GetMessagesTx () const pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual void FairMQSocket::GetOption (const std::string & option, void * value, size_t * valueSize) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int FairMQSocket::GetReceiveTimeout () const pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int FairMQSocket::GetSendTimeout () const pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual void* FairMQSocket::GetSocket () const pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
Referenced by FairMQPollerNN::FairMQPollerNN(), FairMQPollerSHM::FairMQPollerSHM(), and FairMQPollerZMQ::FairMQPollerZMQ().
virtual int FairMQSocket::GetSocket (int nothing) const pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int FairMQSocket::Receive (FairMQMessagePtr & msg, int timeout = 0) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int64_t FairMQSocket::Receive (std::vector< std::unique_ptr< FairMQMessage >> & msgVec, int timeout = 0) pure virtual
Implemented in FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int FairMQSocket::Send (FairMQMessagePtr & msg, int timeout = 0) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int64_t FairMQSocket::Send (std::vector< std::unique_ptr< FairMQMessage >> & msgVec, int timeout = 0) pure virtual
Implemented in FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual void FairMQSocket::SetOption (const std::string & option, const void * value, size_t valueSize) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual bool FairMQSocket::SetReceiveTimeout (const int timeout, const std::string & address, const std::string & method) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual bool FairMQSocket::SetSendTimeout (const int timeout, const std::string & address, const std::string & method) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int FairMQSocket::TryReceive (FairMQMessagePtr & msg) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int64_t FairMQSocket::TryReceive (std::vector< std::unique_ptr< FairMQMessage >> & msgVec) pure virtual
Implemented in FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int FairMQSocket::TrySend (FairMQMessagePtr & msg) pure virtual
Implemented in fair::mq::ofi::Socket, FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
virtual int64_t FairMQSocket::TrySend (std::vector< std::unique_ptr< FairMQMessage >> & msgVec) pure virtual
Implemented in FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
The documentation for this class was generated from the following file:
FairMQSocket.h