FairRroot: ParameterMQServer Class Reference
ParameterMQServer Class Reference
#include <ParameterMQServer.h>
Public Types
enum Event {
INIT_DEVICE, internal_DEVICE_READY, INIT_TASK, internal_READY,
RUN, PAUSE, STOP, RESET_TASK,
RESET_DEVICE, internal_IDLE, END, ERROR_FOUND
}
Public Member Functions
ParameterMQServer ()
ParameterMQServer (const ParameterMQServer &)=delete
ParameterMQServer operator= (const ParameterMQServer &)=delete
virtual ~ParameterMQServer ()
virtual void Run ()
virtual void InitTask ()
void SetFirstInputName (const std::string &firstInputName)
std::string GetFirstInputName ()
void SetFirstInputType (const std::string &firstInputType)
std::string GetFirstInputType ()
void SetSecondInputName (const std::string &secondInputName)
std::string GetSecondInputName ()
void SetSecondInputType (const std::string &secondInputType)
std::string GetSecondInputType ()
void SetOutputName (const std::string &outputName)
std::string GetOutputName ()
void SetOutputType (const std::string &outputType)
std::string GetOutputType ()
void SetChannelName (const std::string &channelName)
std::string GetChannelName ()
void CatchSignals ()
Catches interrupt signals (SIGINT, SIGTERM)
virtual void LogSocketRates ()
Outputs the socket transfer rates.
void SortChannel (const std::string &name, const bool reindex=true)
void PrintChannel (const std::string &name)
template<typename Serializer , typename DataType , typename... Args>
void Serialize (FairMQMessage &msg, DataType &&data, Args &&...args) const
template<typename Deserializer , typename DataType , typename... Args>
void Deserialize (FairMQMessage &msg, DataType &&data, Args &&...args) const
int Send (FairMQMessagePtr &msg, const std::string &chan, const int i=0) const
int Send (FairMQMessagePtr &msg, const std::string &chan, const int i, int sndTimeoutInMs) const
int64_t Send (FairMQParts &parts, const std::string &chan, const int i=0) const
int64_t Send (FairMQParts &parts, const std::string &chan, const int i, int sndTimeoutInMs) const
int Receive (FairMQMessagePtr &msg, const std::string &chan, const int i=0) const
int Receive (FairMQMessagePtr &msg, const std::string &chan, const int i, int rcvTimeoutInMs) const
int64_t Receive (FairMQParts &parts, const std::string &chan, const int i=0) const
int64_t Receive (FairMQParts &parts, const std::string &chan, const int i, int rcvTimeoutInMs) const
int SendAsync (FairMQMessagePtr &msg, const std::string &chan, const int i=0) const
int64_t SendAsync (FairMQParts &parts, const std::string &chan, const int i=0) const
int ReceiveAsync (FairMQMessagePtr &msg, const std::string &chan, const int i=0) const
int64_t ReceiveAsync (FairMQParts &parts, const std::string &chan, const int i=0) const
auto Transport () const -> const FairMQTransportFactory *
Getter for default transport factory.
template<typename... Args>
FairMQMessagePtr NewMessage (Args &&...args) const
template<typename... Args>
FairMQMessagePtr NewMessageFor (const std::string &channel, int index, Args &&...args) const
template<typename T >
FairMQMessagePtr NewStaticMessage (const T &data) const
template<typename T >
FairMQMessagePtr NewStaticMessageFor (const std::string &channel, int index, const T &data) const
template<typename T >
FairMQMessagePtr NewSimpleMessage (const T &data) const
template<typename T >
FairMQMessagePtr NewSimpleMessageFor (const std::string &channel, int index, const T &data) const
FairMQUnmanagedRegionPtr NewUnmanagedRegion (const size_t size)
FairMQUnmanagedRegionPtr NewUnmanagedRegionFor (const std::string &channel, int index, const size_t size, FairMQRegionCallback callback=nullptr)
template<typename... Ts>
FairMQPollerPtr NewPoller (const Ts &...inputs)
FairMQPollerPtr NewPoller (const std::vector< const FairMQChannel * > &channels)
void WaitForInitialValidation ()
Waits for the first initialization run to finish.
std::shared_ptr< FairMQTransportFactory > AddTransport (const std::string &transport)
void SetTransport (const std::string &transport="zeromq")
void SetConfig (FairMQProgOptions &config)
const FairMQProgOptions * GetConfig () const
template<typename T >
void OnData (const std::string &channelName, bool(T::*memberFunction)(FairMQMessagePtr &msg, int index))
void OnData (const std::string &channelName, InputMsgCallback callback)
template<typename T >
void OnData (const std::string &channelName, bool(T::*memberFunction)(FairMQParts &parts, int index))
void OnData (const std::string &channelName, InputMultipartCallback callback)
const FairMQChannel & GetChannel (const std::string &channelName, const int index=0) const
virtual void RegisterChannelEndpoints ()
bool RegisterChannelEndpoint (const std::string &channelName, uint16_t minNumSubChannels=1, uint16_t maxNumSubChannels=1)
void PrintRegisteredChannels ()
void SetId (const std::string &id)
std::string GetId ()
const fair::mq::tools::Version GetVersion () const
void SetNumIoThreads (int numIoThreads)
int GetNumIoThreads () const
void SetPortRangeMin (int portRangeMin)
int GetPortRangeMin () const
void SetPortRangeMax (int portRangeMax)
int GetPortRangeMax () const
void SetNetworkInterface (const std::string &networkInterface)
std::string GetNetworkInterface () const
void SetDefaultTransport (const std::string &defaultTransport)
std::string GetDefaultTransport () const
void SetInitializationTimeoutInS (int initializationTimeoutInS)
int GetInitializationTimeoutInS () const
int GetInterfaceVersion () const
bool ChangeState (int event)
bool ChangeState (const std::string &event)
void WaitForEndOfState (int event)
void WaitForEndOfState (const std::string &event)
bool WaitForEndOfStateForMs (int event, int durationInMs)
bool WaitForEndOfStateForMs (const std::string &event, int durationInMs)
void SubscribeToStateChange (const std::string &key, std::function< void(const State)> callback)
void UnsubscribeFromStateChange (const std::string &key)
Static Public Member Functions
static bool SortSocketsByAddress (const FairMQChannel &lhs, const FairMQChannel &rhs)
Public Attributes
std::unordered_map< std::string, std::vector< FairMQChannel > > fChannels
Device channels.
FairMQProgOptions * fConfig
Program options configuration.
Protected Member Functions
virtual void Init ()
virtual void PreRun ()
virtual bool ConditionalRun ()
virtual void PostRun ()
virtual void Pause ()
virtual void ResetTask ()
virtual void Reset ()
Protected Attributes
std::shared_ptr< FairMQTransportFactory > fTransportFactory
Transport factory.
std::unordered_map< FairMQ::Transport, std::shared_ptr< FairMQTransportFactory > > fTransports
Container for transports.
std::string fId
Device ID.
int fNumIoThreads
Number of ZeroMQ I/O threads.
Private Attributes
FairRuntimeDb * fRtdb
std::string fFirstInputName
std::string fFirstInputType
std::string fSecondInputName
std::string fSecondInputType
std::string fOutputName
std::string fOutputType
std::string fChannelName
Detailed Description
Definition at line 24 of file ParameterMQServer.h.
Member Enumeration Documentation
enum FairMQStateMachine::Event inherited
Enumerator
INIT_DEVICE
internal_DEVICE_READY
INIT_TASK
internal_READY
RUN
PAUSE
STOP
RESET_TASK
RESET_DEVICE
internal_IDLE
END
ERROR_FOUND
Definition at line 571 of file FairMQStateMachine.h.
Constructor & Destructor Documentation
ParameterMQServer::ParameterMQServer ()
Definition at line 29 of file ParameterMQServer.cxx.
ParameterMQServer::ParameterMQServer (const ParameterMQServer &) delete
ParameterMQServer::~ParameterMQServer () virtual
Definition at line 162 of file ParameterMQServer.cxx.
References fRtdb.
Member Function Documentation
shared_ptr< FairMQTransportFactory > FairMQDevice::AddTransport (const std::string & transport) inherited
Adds a transport to the device if it doesn't exist
Parameters
transport Transport string ("zeromq"/"nanomsg"/"shmem")
Definition at line 749 of file FairMQDevice.cxx.
References FairMQTransportFactory::CreateTransportFactory(), FairMQDevice::fConfig, FairMQDevice::fId, FairMQDevice::fTransports, LOG, and FairMQ::TransportTypes.
Referenced by FairMQDevice::AttachChannel(), and FairMQDevice::SetTransport().
void FairMQDevice::CatchSignals () inherited
Catches interrupt signals (SIGINT, SIGTERM)
bool FairMQStateMachine::ChangeState (int event) inherited
Definition at line 32 of file FairMQStateMachine.cxx.
References FairMQStateMachine::END, FairMQStateMachine::ERROR_FOUND, FairMQStateMachine::INIT_DEVICE, FairMQStateMachine::INIT_TASK, FairMQStateMachine::internal_DEVICE_READY, FairMQStateMachine::internal_IDLE, FairMQStateMachine::internal_READY, LOG, FairMQStateMachine::PAUSE, FairMQStateMachine::RESET_DEVICE, FairMQStateMachine::RESET_TASK, FairMQStateMachine::RUN, and FairMQStateMachine::STOP.
Referenced by FairMQStateMachine::ChangeState(), FairMQDevice::InitTaskWrapper(), FairMQDevice::InitWrapper(), FairMQDevice::NewPoller(), FairMQDevice::PollForTransport(), FairMQDevice::ResetTaskWrapper(), FairMQDevice::ResetWrapper(), FairMQDevice::RunWrapper(), and FairMQDevice::SetTransport().
bool FairMQStateMachine::ChangeState (const std::string & event) inherited
Definition at line 126 of file FairMQStateMachine.cxx.
References FairMQStateMachine::ChangeState(), and FairMQStateMachine::GetEventNumber().
bool FairMQDevice::ConditionalRun () protected virtual inherited
Called during RUNNING state repeatedly until it returns false or device state changes Executed in a worker thread
Reimplemented in FairMQSampler< Task >, FairMQEx9aSamplerBin, FairMQEx9Sampler, FairMQEx9SamplerBin, FairMQExample1Sampler, FairMQExample2Sampler, FairMQExample5Client, FairMQExampleRegionSampler, FairMQExample4Sampler, FairMQExample7Client, FairMQExample8Sampler, FairMQExample3Sampler, FairMQExample6Broadcaster, FairMQExampleMTSampler1, and FairMQExampleMTSampler2.
Definition at line 723 of file FairMQDevice.cxx.
Referenced by FairMQDevice::RunWrapper().
template<typename Deserializer , typename DataType , typename... Args> void FairMQDevice::Deserialize (FairMQMessage & msg, DataType && data, Args &&... args) const inline inherited
Definition at line 81 of file FairMQDevice.h.
const FairMQChannel & FairMQDevice::GetChannel (const std::string & channelName, const int index = 0) const inherited
Definition at line 985 of file FairMQDevice.cxx.
References FairMQDevice::fChannels.
std::string ParameterMQServer::GetChannelName () inline
Definition at line 51 of file ParameterMQServer.h.
References fChannelName.
const FairMQProgOptions* FairMQDevice::GetConfig () const inline inherited
Definition at line 300 of file FairMQDevice.h.
References FairMQDevice::fConfig.
std::string FairMQDevice::GetDefaultTransport () const inline inherited
Definition at line 409 of file FairMQDevice.h.
References FairMQDevice::fDefaultTransport.
Referenced by FairMQDevice::Transport().
std::string ParameterMQServer::GetFirstInputName () inline
Definition at line 38 of file ParameterMQServer.h.
References fFirstInputName.
std::string ParameterMQServer::GetFirstInputType () inline
Definition at line 40 of file ParameterMQServer.h.
References fFirstInputType.
std::string FairMQDevice::GetId () inline inherited
Definition at line 392 of file FairMQDevice.h.
References FairMQDevice::fId.
int FairMQDevice::GetInitializationTimeoutInS () const inline inherited
Definition at line 412 of file FairMQDevice.h.
References FairMQDevice::fInitializationTimeoutInS.
int FairMQStateMachine::GetInterfaceVersion () const inherited
Definition at line 27 of file FairMQStateMachine.cxx.
References FAIRMQ_INTERFACE_VERSION.
std::string FairMQDevice::GetNetworkInterface () const inline inherited
Definition at line 406 of file FairMQDevice.h.
References FairMQDevice::fNetworkInterface.
int FairMQDevice::GetNumIoThreads () const inline inherited
Definition at line 397 of file FairMQDevice.h.
References FairMQDevice::fNumIoThreads.
std::string ParameterMQServer::GetOutputName () inline
Definition at line 46 of file ParameterMQServer.h.
References fOutputName.
std::string ParameterMQServer::GetOutputType () inline
Definition at line 48 of file ParameterMQServer.h.
References fOutputType.
int FairMQDevice::GetPortRangeMax () const inline inherited
Definition at line 403 of file FairMQDevice.h.
References FairMQDevice::fPortRangeMax.
int FairMQDevice::GetPortRangeMin () const inline inherited
Definition at line 400 of file FairMQDevice.h.
References FairMQDevice::fPortRangeMin.
std::string ParameterMQServer::GetSecondInputName () inline
Definition at line 42 of file ParameterMQServer.h.
References fSecondInputName.
std::string ParameterMQServer::GetSecondInputType () inline
Definition at line 44 of file ParameterMQServer.h.
References fSecondInputType.
const fair::mq::tools::Version FairMQDevice::GetVersion () const inline inherited
Definition at line 394 of file FairMQDevice.h.
References FairMQDevice::fVersion.
void FairMQDevice::Init () protected virtual inherited
Additional user initialization (can be overloaded in child classes). Prefer to use InitTask(). Executed in a worker thread
Reimplemented in FairTestDetectorFileSink< TIn, TPayloadIn >, Ex2Sink, FairMQEx9FileSink, FairMQEx9FileSinkBin, Ex1Sink, Ex2Sampler, FairMQEx9TaskProcessorBin< T >, FairMQEx9aTaskProcessorBin< T >, FairMQShmPrototypeSampler, FairMQEx9Merger, FairMQEx9TaskProcessor< T >, FairMQEx9aFileSinkBin, Ex1Sampler, FairMQShmPrototypeSink, Ex2Processor, fair::mq::test::Receiver, fair::mq::test::Sender, fair::mq::test::PollIn, Ex1Processor, fair::mq::test::Pub, fair::mq::test::Pull, fair::mq::test::Sub, fair::mq::test::PairRight, fair::mq::test::Rep, fair::mq::test::Req, fair::mq::test::PairLeft, fair::mq::test::PollOut, and fair::mq::test::Push.
Definition at line 218 of file FairMQDevice.cxx.
Referenced by FairMQDevice::InitWrapper().
void ParameterMQServer::InitTask () virtual
Task initialization (can be overloaded in child classes) Executed in a worker thread
Reimplemented from FairMQDevice.
Definition at line 41 of file ParameterMQServer.cxx.
References fChannelName, FairMQDevice::fConfig, fFirstInputName, fFirstInputType, fOutputName, fOutputType, fRtdb, fSecondInputName, fSecondInputType, FairProgOptions::GetValue(), FairParAsciiFileIo::open(), FairParRootFileIo::open(), parOut, FairRuntimeDb::saveOutput(), FairRuntimeDb::setFirstInput(), FairRuntimeDb::setOutput(), and FairRuntimeDb::setSecondInput().
void FairMQDevice::LogSocketRates () virtual inherited
Outputs the socket transfer rates.
Definition at line 835 of file FairMQDevice.cxx.
References FairMQDevice::fChannels, LOG, and fair::mq::tools::ToString().
Referenced by FairMQDevice::RunWrapper().
template<typename... Args> FairMQMessagePtr FairMQDevice::NewMessage (Args &&... args) const inline inherited
Definition at line 201 of file FairMQDevice.h.
References FairMQDevice::Transport().
Referenced by FairMQExampleMTSampler2::ConditionalRun(), FairMQExample8Sampler::ConditionalRun(), FairMQExample7Client::ConditionalRun(), FairMQExample4Sampler::ConditionalRun(), FairMQExample5Client::ConditionalRun(), FairMQExample1Sampler::ConditionalRun(), FairMQEx9SamplerBin::ConditionalRun(), FairMQEx9Sampler::ConditionalRun(), FairMQExample5Server::HandleData(), FairMQEx9SamplerBin::ListenForAcks(), FairMQEx9aSamplerBin::ListenForAcks(), FairMQEx9Sampler::ListenForAcks(), FairMQSampler< Task >::ListenForAcks(), FairMQEx9Merger::MergeData(), FairMQEx9aSamplerBin::ReadBinFile(), FairMQLmdSampler::ReadEvent(), FairMQEx9aSamplerBin::ReadRootFile(), fair::mq::test::TransferTimeout::Run(), fair::mq::test::PollOut::Run(), fair::mq::test::Push::Run(), fair::mq::test::Rep::Run(), fair::mq::test::Req::Run(), Ex1Processor::Run(), FairMQExample6Sampler::Run(), Run(), fair::mq::test::Pub::Run(), fair::mq::test::Sub::Run(), FairMQShmPrototypeSink::Run(), Ex2Processor::Run(), fair::mq::test::Sender::Run(), FairMQShmPrototypeSampler::Run(), fair::mq::test::Receiver::Run(), BaseMQFileSink< InputPolicy, OutputPolicy >::Run(), Ex1Sink::Run(), Ex1Sampler::Run(), Ex2Sampler::Run(), FairMQUnpacker< UnpackerType, SerializationType >::Run(), FairMQEx9aFileSinkBin::StoreData(), FairMQEx9FileSinkBin::StoreData(), and FairMQEx9FileSink::StoreData().
template<typename... Args> FairMQMessagePtr FairMQDevice::NewMessageFor (const std::string & channel, int index, Args &&... args) const inline inherited
Definition at line 207 of file FairMQDevice.h.
References FairMQDevice::fChannels.
Referenced by FairMQExampleMTSampler1::ConditionalRun(), FairMQExampleRegionSampler::ConditionalRun(), FairMQExampleMTSink::HandleData1(), FairMQExampleMTSampler1::ListenForAcks(), fair::mq::test::PairLeft::Run(), and fair::mq::test::PairRight::Run().
template<typename... Ts> FairMQPollerPtr FairMQDevice::NewPoller (const Ts &... inputs) inline inherited
Definition at line 247 of file FairMQDevice.h.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::ERROR_FOUND, FairMQDevice::fChannels, and LOG.
Referenced by FairMQExample6Sampler::Run(), and FairMQMerger::Run().
FairMQPollerPtr FairMQDevice::NewPoller (const std::vector< const FairMQChannel * > & channels) inline inherited
Definition at line 269 of file FairMQDevice.h.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::ERROR_FOUND, and LOG.
template<typename T > FairMQMessagePtr FairMQDevice::NewSimpleMessage (const T & data) const inline inherited
Definition at line 225 of file FairMQDevice.h.
References FairMQDevice::Transport().
Referenced by FairMQExample8Sampler::ConditionalRun(), FairMQExample7Client::ConditionalRun(), FairMQExample4Sampler::ConditionalRun(), and FairMQExample6Sampler::Run().
template<typename T > FairMQMessagePtr FairMQDevice::NewSimpleMessageFor (const std::string & channel, int index, const T & data) const inline inherited
Definition at line 231 of file FairMQDevice.h.
References FairMQDevice::fChannels.
Referenced by fair::mq::test::PairLeft::Run(), and fair::mq::test::PairRight::Run().
template<typename T > FairMQMessagePtr FairMQDevice::NewStaticMessage (const T & data) const inline inherited
Definition at line 213 of file FairMQDevice.h.
References FairMQDevice::Transport().
Referenced by FairMQExample2Sampler::ConditionalRun().
template<typename T > FairMQMessagePtr FairMQDevice::NewStaticMessageFor (const std::string & channel, int index, const T & data) const inline inherited
Definition at line 219 of file FairMQDevice.h.
References FairMQDevice::fChannels.
FairMQUnmanagedRegionPtr FairMQDevice::NewUnmanagedRegion (const size_t size) inline inherited
Definition at line 236 of file FairMQDevice.h.
References FairMQDevice::Transport().
FairMQUnmanagedRegionPtr FairMQDevice::NewUnmanagedRegionFor (const std::string & channel, int index, const size_t size, FairMQRegionCallback callback = nullptr) inline inherited
Definition at line 241 of file FairMQDevice.h.
References FairMQDevice::fChannels.
Referenced by FairMQExampleRegionSampler::InitTask().
template<typename T > void FairMQDevice::OnData (const std::string & channelName, bool(T::*)(FairMQMessagePtr &msg, int index) memberFunction) inline inherited
Definition at line 311 of file FairMQDevice.h.
References FairMQDevice::fDataCallbacks, FairMQDevice::fInputChannelKeys, and FairMQDevice::fMsgInputs.
Referenced by FairMQExample1Sink::FairMQExample1Sink(), FairMQExample2Sink::FairMQExample2Sink(), FairMQExample4Sink::FairMQExample4Sink(), FairMQExample5Server::FairMQExample5Server(), FairMQExample6Sink::FairMQExample6Sink(), FairMQExampleMTSink::FairMQExampleMTSink(), FairMQEx9aFileSinkBin::Init(), FairMQEx9Merger::Init(), FairMQEx9FileSink::Init(), FairMQEx9FileSinkBin::Init(), FairMQMultiplier::InitTask(), FairMQSplitter::InitTask(), and FairMQProcessor< Task >::InitTask().
void FairMQDevice::OnData (const std::string & channelName, InputMsgCallback callback) inline inherited
Definition at line 325 of file FairMQDevice.h.
References FairMQDevice::fDataCallbacks, FairMQDevice::fInputChannelKeys, and FairMQDevice::fMsgInputs.
template<typename T > void FairMQDevice::OnData (const std::string & channelName, bool(T::*)(FairMQParts &parts, int index) memberFunction) inline inherited
Definition at line 337 of file FairMQDevice.h.
References FairMQDevice::fDataCallbacks, FairMQDevice::fInputChannelKeys, and FairMQDevice::fMultipartInputs.
void FairMQDevice::OnData (const std::string & channelName, InputMultipartCallback callback) inline inherited
Definition at line 351 of file FairMQDevice.h.
References FairMQDevice::fDataCallbacks, FairMQDevice::fInputChannelKeys, and FairMQDevice::fMultipartInputs.
ParameterMQServer ParameterMQServer::operator= (const ParameterMQServer &) delete
void FairMQDevice::Pause () protected virtual inherited
Handles the PAUSE state Executed in a worker thread
Definition at line 739 of file FairMQDevice.cxx.
References LOG.
Referenced by FairMQDevice::PauseWrapper().
void FairMQDevice::PostRun () protected virtual inherited
Called in the RUNNING state once after executing the Run()/ConditionalRun() method Executed in a worker thread
Reimplemented in FairMQSampler< Task >, FairTestDetectorFileSink< TIn, TPayloadIn >, FairMQProcessor< Task >, FairMQEx9aSamplerBin, FairMQEx9Sampler, FairMQEx9SamplerBin, FairMQEx9TaskProcessorBin< T >, FairMQEx9aTaskProcessorBin< T >, FairMQEx9TaskProcessor< T >, FairMQBenchmarkSampler, and FairMQExampleMTSampler1.
Definition at line 728 of file FairMQDevice.cxx.
Referenced by FairMQDevice::RunWrapper().
void FairMQDevice::PreRun () protected virtual inherited
Called in the RUNNING state once before executing the Run()/ConditionalRun() method Executed in a worker thread
Reimplemented in FairMQSampler< Task >, FairMQEx9aSamplerBin, FairMQEx9Sampler, FairMQEx9SamplerBin, FairMQBenchmarkSampler, and FairMQExampleMTSampler1.
Definition at line 719 of file FairMQDevice.cxx.
Referenced by FairMQDevice::RunWrapper().
void FairMQDevice::PrintChannel (const std::string & name) inherited
Prints channel configuration
Parameters
name Name of the channel
Definition at line 427 of file FairMQDevice.cxx.
References FairMQDevice::fChannels, and LOG.
void FairMQDevice::PrintRegisteredChannels () inline inherited
Definition at line 376 of file FairMQDevice.h.
References FairMQDevice::fChannelRegistry.
int FairMQDevice::Receive (FairMQMessagePtr & msg, const std::string & chan, const int i = 0) const inline inherited
Definition at line 91 of file FairMQDevice.h.
References FairMQDevice::fChannels.
Referenced by FairMQExample7Client::ConditionalRun(), FairMQExample5Client::ConditionalRun(), FairMQDevice::HandleMsgInput(), FairMQDevice::HandleMultipartInput(), FairMQExampleMTSampler1::ListenForAcks(), FairMQEx9aSamplerBin::ListenForAcks(), FairMQEx9SamplerBin::ListenForAcks(), FairMQEx9Sampler::ListenForAcks(), FairMQSampler< Task >::ListenForAcks(), fair::mq::test::TransferTimeout::Run(), fair::mq::test::PairLeft::Run(), fair::mq::test::PairRight::Run(), fair::mq::test::Rep::Run(), fair::mq::test::Req::Run(), FairMQExample6Sampler::Run(), Ex1Processor::Run(), FairMQProxy::Run(), fair::mq::test::Sub::Run(), FairMQMerger::Run(), Run(), fair::mq::test::Pub::Run(), FairMQShmPrototypeSink::Run(), Ex2Processor::Run(), fair::mq::test::Receiver::Run(), BaseMQFileSink< InputPolicy, OutputPolicy >::Run(), Ex1Sink::Run(), and Ex2Sink::Run().
int FairMQDevice::Receive (FairMQMessagePtr & msg, const std::string & chan, const int i, int rcvTimeoutInMs) const inline inherited
Shorthand method to receive msg on chan at index i
Parameters
msg message reference
chan channel name
i channel index
Returns
Number of bytes that have been received. -2 If reading from the queue was not possible or timed out. In case of errors, returns -1.
Definition at line 113 of file FairMQDevice.h.
References FairMQDevice::fChannels.
int64_t FairMQDevice::Receive (FairMQParts & parts, const std::string & chan, const int i = 0) const inline inherited
Definition at line 145 of file FairMQDevice.h.
References FairMQDevice::fChannels, and FairMQParts::fParts.
int64_t FairMQDevice::Receive (FairMQParts & parts, const std::string & chan, const int i, int rcvTimeoutInMs) const inline inherited
Shorthand method to receive FairMQParts on chan at index i
Parameters
parts parts reference
chan channel name
i channel index
Returns
Number of bytes that have been received. -2 If reading from the queue was not possible or timed out. In case of errors, returns -1.
Definition at line 167 of file FairMQDevice.h.
References FairMQDevice::fChannels, and FairMQParts::fParts.
int FairMQDevice::ReceiveAsync (FairMQMessagePtr & msg, const std::string & chan, const int i = 0) const inline inherited
Shorthand method to receive msg on chan at index i without blocking
Parameters
msg message reference
chan channel name
i channel index
Returns
Number of bytes that have been received. -2 If reading from the queue was not possible or timed out. In case of errors, returns -1.
Definition at line 135 of file FairMQDevice.h.
References FairMQDevice::fChannels.
int64_t FairMQDevice::ReceiveAsync (FairMQParts & parts, const std::string & chan, const int i = 0) const inline inherited
Shorthand method to receive FairMQParts on chan at index i without blocking
Parameters
parts parts reference
chan channel name
i channel index
Returns
Number of bytes that have been received. -2 If reading from the queue was not possible or timed out. In case of errors, returns -1.
Definition at line 189 of file FairMQDevice.h.
References FairMQDevice::fChannels, and FairMQParts::fParts.
bool FairMQDevice::RegisterChannelEndpoint (const std::string & channelName, uint16_t minNumSubChannels = 1, uint16_t maxNumSubChannels = 1) inline inherited
Definition at line 366 of file FairMQDevice.h.
References FairMQDevice::fChannelRegistry, and LOG.
Referenced by FairMQMerger::RegisterChannelEndpoints().
virtual void FairMQDevice::RegisterChannelEndpoints () inline virtual inherited
Reimplemented in FairMQMerger.
Definition at line 364 of file FairMQDevice.h.
void FairMQDevice::Reset () protected virtual inherited
Resets the device (can be overloaded in child classes) Executed in a worker thread
Reimplemented in fair::mq::test::Receiver, fair::mq::test::Sender, fair::mq::test::PollIn, fair::mq::test::Pub, fair::mq::test::Pull, fair::mq::test::Sub, fair::mq::test::PairRight, fair::mq::test::Rep, fair::mq::test::Req, fair::mq::test::PairLeft, fair::mq::test::PollOut, and fair::mq::test::Push.
Definition at line 971 of file FairMQDevice.cxx.
References FairMQDevice::fChannels.
Referenced by FairMQDevice::ResetWrapper().
void FairMQDevice::ResetTask () protected virtual inherited
Resets the user task (to be overloaded in child classes) Executed in a worker thread
Reimplemented in FairMQSampler< Task >, and FairMQExampleRegionSampler.
Definition at line 958 of file FairMQDevice.cxx.
Referenced by FairMQDevice::ResetTaskWrapper().
void ParameterMQServer::Run () virtual
Runs the device (to be overloaded in child classes) Executed in a worker thread
Reimplemented from FairMQDevice.
Definition at line 99 of file ParameterMQServer.cxx.
References fChannelName, fRtdb, FairRuntimeDb::getContainer(), FairRuntimeDb::initContainers(), LOG, FairMQDevice::NewMessage(), par, FairParSet::print(), FairMQDevice::Receive(), and FairMQDevice::Send().
int FairMQDevice::Send (FairMQMessagePtr & msg, const std::string & chan, const int i = 0) const inline inherited
Definition at line 86 of file FairMQDevice.h.
References FairMQDevice::fChannels.
Referenced by FairMQExampleMTSampler2::ConditionalRun(), FairMQExampleMTSampler1::ConditionalRun(), FairMQExample8Sampler::ConditionalRun(), FairMQExample7Client::ConditionalRun(), FairMQExample4Sampler::ConditionalRun(), FairMQExampleRegionSampler::ConditionalRun(), FairMQExample5Client::ConditionalRun(), FairMQExample1Sampler::ConditionalRun(), FairMQExample2Sampler::ConditionalRun(), FairMQEx9SamplerBin::ConditionalRun(), FairMQEx9Sampler::ConditionalRun(), FairMQSampler< Task >::ConditionalRun(), FairMQExample5Server::HandleData(), FairMQExampleMTSink::HandleData1(), FairMQMultiplier::HandleMultipartData(), FairMQSplitter::HandleMultipartData(), FairMQMultiplier::HandleSingleData(), FairMQSplitter::HandleSingleData(), FairMQProcessor< Task >::InitTask(), FairMQEx9Merger::MergeData(), FairMQEx9aSamplerBin::ReadBinFile(), FairMQLmdSampler::ReadEvent(), FairMQEx9aSamplerBin::ReadRootFile(), fair::mq::test::TransferTimeout::Run(), fair::mq::test::Push::Run(), fair::mq::test::PairLeft::Run(), fair::mq::test::PollOut::Run(), fair::mq::test::Req::Run(), fair::mq::test::Rep::Run(), fair::mq::test::PairRight::Run(), Ex1Processor::Run(), FairMQProxy::Run(), FairMQExample6Sampler::Run(), Run(), fair::mq::test::Pub::Run(), fair::mq::test::Sub::Run(), FairMQMerger::Run(), Ex2Processor::Run(), fair::mq::test::Sender::Run(), FairMQShmPrototypeSampler::Run(), Ex1Sampler::Run(), Ex2Sampler::Run(), FairMQUnpacker< UnpackerType, SerializationType >::Run(), FairMQEx9aFileSinkBin::StoreData(), FairMQEx9FileSink::StoreData(), and FairMQEx9FileSinkBin::StoreData().
int FairMQDevice::Send (FairMQMessagePtr & msg, const std::string & chan, const int i, int sndTimeoutInMs) const inline inherited
Shorthand method to send msg on chan at index i
Parameters
msg message reference
chan channel name
i channel index
Returns
Number of bytes that have been queued. -2 If queueing was not possible or timed out. In case of errors, returns -1.
Definition at line 102 of file FairMQDevice.h.
References FairMQDevice::fChannels.
int64_t FairMQDevice::Send (FairMQParts & parts, const std::string & chan, const int i = 0) const inline inherited
Definition at line 140 of file FairMQDevice.h.
References FairMQDevice::fChannels, and FairMQParts::fParts.
int64_t FairMQDevice::Send (FairMQParts & parts, const std::string & chan, const int i, int sndTimeoutInMs) const inline inherited
Shorthand method to send FairMQParts on chan at index i
Parameters
parts parts reference
chan channel name
i channel index
Returns
Number of bytes that have been queued. -2 If queueing was not possible or timed out. In case of errors, returns -1.
Definition at line 156 of file FairMQDevice.h.
References FairMQDevice::fChannels, and FairMQParts::fParts.
int FairMQDevice::SendAsync (FairMQMessagePtr & msg, const std::string & chan, const int i = 0) const inline inherited
Shorthand method to send msg on chan at index i without blocking
Parameters
msg message reference
chan channel name
i channel index
Returns
Number of bytes that have been queued. -2 If queueing was not possible or timed out. In case of errors, returns -1.
Definition at line 124 of file FairMQDevice.h.
References FairMQDevice::fChannels.
int64_t FairMQDevice::SendAsync (FairMQParts & parts, const std::string & chan, const int i = 0) const inline inherited
Shorthand method to send FairMQParts on chan at index i without blocking
Parameters
parts parts reference
chan channel name
i channel index
Returns
Number of bytes that have been queued. -2 If queueing was not possible or timed out. In case of errors, returns -1.
Definition at line 178 of file FairMQDevice.h.
References FairMQDevice::fChannels, and FairMQParts::fParts.
template<typename Serializer , typename DataType , typename... Args> void FairMQDevice::Serialize (FairMQMessage & msg, DataType && data, Args &&... args) const inline inherited
Definition at line 75 of file FairMQDevice.h.
void ParameterMQServer::SetChannelName (const std::string & channelName) inline
Definition at line 50 of file ParameterMQServer.h.
References fChannelName.
void FairMQDevice::SetConfig (FairMQProgOptions & config) inherited
Definition at line 815 of file FairMQDevice.cxx.
References FairMQDevice::fChannels, FairMQDevice::fConfig, FairMQDevice::fDefaultTransport, FairMQDevice::fExternalConfig, FairMQDevice::fId, FairMQDevice::fInitializationTimeoutInS, FairMQDevice::fNetworkInterface, FairMQDevice::fNumIoThreads, FairMQDevice::fRate, FairMQProgOptions::GetFairMQMap(), FairProgOptions::GetValue(), LOG, and FairMQDevice::SetTransport().
Referenced by main().
void FairMQDevice::SetDefaultTransport (const std::string & defaultTransport) inline inherited
Definition at line 408 of file FairMQDevice.h.
References FairMQDevice::fDefaultTransport.
void ParameterMQServer::SetFirstInputName (const std::string & firstInputName) inline
Definition at line 37 of file ParameterMQServer.h.
References fFirstInputName.
void ParameterMQServer::SetFirstInputType (const std::string & firstInputType) inline
Definition at line 39 of file ParameterMQServer.h.
References fFirstInputType.
void FairMQDevice::SetId (const std::string & id) inline inherited
Definition at line 391 of file FairMQDevice.h.
References FairMQDevice::fId.
void FairMQDevice::SetInitializationTimeoutInS (int initializationTimeoutInS) inline inherited
Definition at line 411 of file FairMQDevice.h.
References FairMQDevice::fInitializationTimeoutInS.
void FairMQDevice::SetNetworkInterface (const std::string & networkInterface) inline inherited
Definition at line 405 of file FairMQDevice.h.
References FairMQDevice::fNetworkInterface.
void FairMQDevice::SetNumIoThreads (int numIoThreads) inline inherited
Definition at line 396 of file FairMQDevice.h.
References FairMQDevice::fNumIoThreads.
void ParameterMQServer::SetOutputName (const std::string & outputName) inline
Definition at line 45 of file ParameterMQServer.h.
References fOutputName.
void ParameterMQServer::SetOutputType (const std::string & outputType) inline
Definition at line 47 of file ParameterMQServer.h.
References fOutputType.
void FairMQDevice::SetPortRangeMax (int portRangeMax) inline inherited
Definition at line 402 of file FairMQDevice.h.
References FairMQDevice::fPortRangeMax.
void FairMQDevice::SetPortRangeMin (int portRangeMin) inline inherited
Definition at line 399 of file FairMQDevice.h.
References FairMQDevice::fPortRangeMin.
void ParameterMQServer::SetSecondInputName (const std::string & secondInputName) inline
Definition at line 41 of file ParameterMQServer.h.
References fSecondInputName.
void ParameterMQServer::SetSecondInputType (const std::string & secondInputType) inline
Definition at line 43 of file ParameterMQServer.h.
References fSecondInputType.
void FairMQDevice::SetTransport (const std::string & transport = "zeromq") inherited
Sets the default transport for the device
Parameters
transport Transport string ("zeromq"/"nanomsg"/"shmem")
Definition at line 794 of file FairMQDevice.cxx.
References FairMQDevice::AddTransport(), FairMQStateMachine::ChangeState(), FairMQDevice::CreateOwnConfig(), FairMQStateMachine::ERROR_FOUND, FairMQDevice::fConfig, FairMQDevice::fExternalConfig, FairMQDevice::fTransportFactory, FairMQDevice::fTransports, and LOG.
Referenced by FairMQDevice::SetConfig().
void FairMQDevice::SortChannel (const std::string & name, const bool reindex = true) inherited
Sorts a channel by address, with optional reindexing of the sorted values
Parameters
name Channel name
reindex Should reindexing be done
Definition at line 406 of file FairMQDevice.cxx.
References FairMQDevice::fChannels, LOG, FairMQDevice::SortSocketsByAddress(), and fair::mq::tools::ToString().
bool FairMQDevice::SortSocketsByAddress (const FairMQChannel & lhs, const FairMQChannel & rhs) static inherited
Implements the sort algorithm used in SortChannel()
Parameters
lhs Right hand side value for comparison
rhs Left hand side value for comparison
Definition at line 401 of file FairMQDevice.cxx.
References FairMQChannel::fAddress.
Referenced by FairMQDevice::SortChannel().
void FairMQStateMachine::SubscribeToStateChange (const std::string & key, std::function< void(const State)> callback) inherited
Definition at line 207 of file FairMQStateMachine.cxx.
auto FairMQDevice::Transport () const -> const FairMQTransportFactory* inline inherited
Getter for default transport factory.
Definition at line 195 of file FairMQDevice.h.
References FairMQDevice::fTransports, FairMQDevice::GetDefaultTransport(), and FairMQ::TransportTypes.
Referenced by FairMQDevice::NewMessage(), FairMQDevice::NewSimpleMessage(), FairMQDevice::NewStaticMessage(), and FairMQDevice::NewUnmanagedRegion().
void FairMQStateMachine::UnsubscribeFromStateChange (const std::string & key) inherited
Definition at line 211 of file FairMQStateMachine.cxx.
void FairMQStateMachine::WaitForEndOfState (int event) inherited
Definition at line 131 of file FairMQStateMachine.cxx.
References FairMQStateMachine::INIT_DEVICE, FairMQStateMachine::INIT_TASK, LOG, FairMQStateMachine::RESET_DEVICE, FairMQStateMachine::RESET_TASK, and FairMQStateMachine::RUN.
Referenced by FairMQStateMachine::WaitForEndOfState().
void FairMQStateMachine::WaitForEndOfState (const std::string & event) inherited
Definition at line 162 of file FairMQStateMachine.cxx.
References FairMQStateMachine::GetEventNumber(), and FairMQStateMachine::WaitForEndOfState().
bool FairMQStateMachine::WaitForEndOfStateForMs (int event, int durationInMs) inherited
Definition at line 167 of file FairMQStateMachine.cxx.
References FairMQStateMachine::INIT_DEVICE, FairMQStateMachine::INIT_TASK, LOG, FairMQStateMachine::RESET_DEVICE, FairMQStateMachine::RESET_TASK, and FairMQStateMachine::RUN.
Referenced by FairMQStateMachine::WaitForEndOfStateForMs().
bool FairMQStateMachine::WaitForEndOfStateForMs (const std::string & event, int durationInMs) inherited
Definition at line 202 of file FairMQStateMachine.cxx.
References FairMQStateMachine::GetEventNumber(), and FairMQStateMachine::WaitForEndOfStateForMs().
void FairMQDevice::WaitForInitialValidation () inherited
Waits for the first initialization run to finish.
Definition at line 212 of file FairMQDevice.cxx.
References FairMQDevice::fInitialValidationCondition, FairMQDevice::fInitialValidationFinished, and FairMQDevice::fInitialValidationMutex.
Member Data Documentation
std::string ParameterMQServer::fChannelName private
Definition at line 63 of file ParameterMQServer.h.
Referenced by GetChannelName(), InitTask(), Run(), and SetChannelName().
std::unordered_map<std::string, std::vector<FairMQChannel> > FairMQDevice::fChannels inherited
Device channels.
Definition at line 419 of file FairMQDevice.h.
Referenced by FairMQDevice::GetChannel(), FairMQDevice::HandleMsgInput(), FairMQMultiplier::HandleMultipartData(), FairMQDevice::HandleMultipleChannelInput(), FairMQMultiplier::HandleSingleData(), FairMQMultiplier::InitTask(), FairMQExample4Sampler::InitTask(), FairMQSplitter::InitTask(), FairMQUnpacker< UnpackerType, SerializationType >::InitTask(), FairMQDevice::InitWrapper(), FairMQDevice::LogSocketRates(), main(), FairMQDevice::NewMessageFor(), FairMQDevice::NewPoller(), FairMQDevice::NewSimpleMessageFor(), FairMQDevice::NewStaticMessageFor(), FairMQDevice::NewUnmanagedRegionFor(), FairMQDevice::PollForTransport(), FairMQDevice::PrintChannel(), FairMQDevice::Receive(), FairMQDevice::ReceiveAsync(), FairMQDevice::Reset(), FairMQExampleRegionSink::Run(), FairMQMerger::Run(), FairMQSink::Run(), FairMQBenchmarkSampler::Run(), FairMQUnpacker< UnpackerType, SerializationType >::Run(), FairMQDevice::RunWrapper(), FairMQDevice::Send(), FairMQDevice::SendAsync(), FairMQDevice::SetConfig(), and FairMQDevice::SortChannel().
FairMQProgOptions* FairMQDevice::fConfig inherited
Program options configuration.
Definition at line 420 of file FairMQDevice.h.
Referenced by FairMQDevice::AddTransport(), FairMQDevice::AttachChannel(), FairMQDevice::CreateOwnConfig(), FairMQDevice::Exit(), FairMQDevice::GetConfig(), Ex1Processor::Init(), Ex2Processor::Init(), FairMQEx9aFileSinkBin::Init(), Ex1Sampler::Init(), FairMQShmPrototypeSampler::Init(), Ex2Sampler::Init(), FairMQEx9FileSink::Init(), Ex1Sink::Init(), FairMQEx9FileSinkBin::Init(), Ex2Sink::Init(), FairTestDetectorFileSink< TIn, TPayloadIn >::Init(), FairMQExampleMTSampler1::InitTask(), FairMQExampleMTSampler2::InitTask(), FairMQExample8Sampler::InitTask(), FairMQExampleMTSink::InitTask(), FairMQExample1Sink::InitTask(), FairMQExample2Sink::InitTask(), FairMQExample4Sink::InitTask(), FairMQExample5Server::InitTask(), FairMQMultiplier::InitTask(), FairMQExample4Sampler::InitTask(), FairMQExample6Sink::InitTask(), FairMQExample7Client::InitTask(), FairMQExampleRegionSink::InitTask(), FairMQExampleRegionSampler::InitTask(), FairMQExample2Sampler::InitTask(), FairMQExample1Sampler::InitTask(), FairMQExample6Sampler::InitTask(), FairMQProxy::InitTask(), FairMQExample5Client::InitTask(), FairMQMerger::InitTask(), InitTask(), FairMQSplitter::InitTask(), FairMQProcessor< Task >::InitTask(), BaseMQFileSink< InputPolicy, OutputPolicy >::InitTask(), FairMQSink::InitTask(), FairMQEx9SamplerBin::InitTask(), FairMQBenchmarkSampler::InitTask(), FairMQEx9Sampler::InitTask(), FairMQEx9aSamplerBin::InitTask(), FairMQUnpacker< UnpackerType, SerializationType >::InitTask(), FairMQSampler< Task >::InitTask(), FairMQLmdSampler::InitTask(), FairMQDevice::InitWrapper(), FairMQDevice::SetConfig(), and FairMQDevice::SetTransport().
std::string ParameterMQServer::fFirstInputName private
Definition at line 56 of file ParameterMQServer.h.
Referenced by GetFirstInputName(), InitTask(), and SetFirstInputName().
std::string ParameterMQServer::fFirstInputType private
Definition at line 57 of file ParameterMQServer.h.
Referenced by GetFirstInputType(), InitTask(), and SetFirstInputType().
std::string FairMQDevice::fId protected inherited
Device ID.
Definition at line 423 of file FairMQDevice.h.
Referenced by FairMQDevice::AddTransport(), FairMQDevice::CreateOwnConfig(), FairMQDevice::GetId(), FairMQDevice::SetConfig(), FairMQDevice::SetId(), and FairMQDevice::~FairMQDevice().
int FairMQDevice::fNumIoThreads protected inherited
Number of ZeroMQ I/O threads.
Definition at line 425 of file FairMQDevice.h.
Referenced by FairMQDevice::CreateOwnConfig(), FairMQDevice::GetNumIoThreads(), FairMQDevice::SetConfig(), and FairMQDevice::SetNumIoThreads().
std::string ParameterMQServer::fOutputName private
Definition at line 60 of file ParameterMQServer.h.
Referenced by GetOutputName(), InitTask(), and SetOutputName().
std::string ParameterMQServer::fOutputType private
Definition at line 61 of file ParameterMQServer.h.
Referenced by GetOutputType(), InitTask(), and SetOutputType().
FairRuntimeDb* ParameterMQServer::fRtdb private
Definition at line 54 of file ParameterMQServer.h.
Referenced by InitTask(), Run(), and ~ParameterMQServer().
std::string ParameterMQServer::fSecondInputName private
Definition at line 58 of file ParameterMQServer.h.
Referenced by GetSecondInputName(), InitTask(), and SetSecondInputName().
std::string ParameterMQServer::fSecondInputType private
Definition at line 59 of file ParameterMQServer.h.
Referenced by GetSecondInputType(), InitTask(), and SetSecondInputType().
std::shared_ptr<FairMQTransportFactory> FairMQDevice::fTransportFactory protected inherited
Transport factory.
Definition at line 415 of file FairMQDevice.h.
Referenced by FairMQDevice::AttachChannel(), FairMQMultiplier::HandleMultipartData(), FairMQMultiplier::HandleSingleData(), FairMQSampler< Task >::InitTask(), FairMQDevice::InitWrapper(), FairMQProxy::Run(), FairMQMerger::Run(), and FairMQDevice::SetTransport().
std::unordered_map<FairMQ::Transport, std::shared_ptr<FairMQTransportFactory> > FairMQDevice::fTransports protected inherited
Container for transports.
Definition at line 416 of file FairMQDevice.h.
Referenced by FairMQDevice::AddTransport(), FairMQDevice::HandleMultipleTransportInput(), FairMQDevice::RunWrapper(), FairMQDevice::SetTransport(), FairMQDevice::Transport(), and FairMQDevice::Unblock().
The documentation for this class was generated from the following files:
ParameterMQServer.h
ParameterMQServer.cxx