FairRroot: FairProgOptions Class Reference
FairProgOptions Class Reference abstract
#include <FairProgOptions.h>
Public Member Functions
FairProgOptions ()
virtual ~FairProgOptions ()
auto GetPropertyKeys () const -> std::vector< std::string >
int AddToCmdLineOptions (const po::options_description optDesc, bool visible=true)
Add option descriptions.
po::options_description & GetCmdLineOptions ()
template<typename T >
T GetValue (const std::string &key) const
std::string GetStringValue (const std::string &key)
int Count (const std::string &key) const
template<typename T >
T ConvertTo (const std::string &strValue)
const po::variables_map & GetVarMap () const
int ParseCmdLine (const int argc, char const *const *argv, bool allowUnregistered=false)
void ParseDefaults ()
virtual int ParseAll (const int argc, char const *const *argv, bool allowUnregistered=false)=0
virtual int PrintOptions ()
virtual int PrintOptionsRaw ()
Protected Member Functions
virtual int ImmediateOptions ()=0
template<typename T >
void UpdateVarMap (const std::string &key, const T &val)
template<typename T >
void Replace (std::map< std::string, po::variable_value > &vm, const std::string &key, const T &val)
Protected Attributes
po::variables_map fVarMap
po::options_description fGeneralOptions
po::options_description fAllOptions
std::mutex fConfigMutex
Private Member Functions
fair::mq::VarValInfo GetVariableValueInfo (const po::variable_value &varValue)
Static Private Member Functions
static void Max (int &val, const int &comp)
Detailed Description
Definition at line 35 of file FairProgOptions.h.
Constructor & Destructor Documentation
FairProgOptions::FairProgOptions ()
Definition at line 24 of file FairProgOptions.cxx.
References fAllOptions, and fGeneralOptions.
FairProgOptions::~FairProgOptions () virtual
Definition at line 42 of file FairProgOptions.cxx.
Member Function Documentation
int FairProgOptions::AddToCmdLineOptions (const po::options_description optDesc, bool visible = true)
Add option descriptions.
Definition at line 47 of file FairProgOptions.cxx.
References fAllOptions.
Referenced by FairMQProgOptions::InitOptionDescription(), and main().
template<typename T > T FairProgOptions::ConvertTo (const std::string & strValue) inline
Definition at line 110 of file FairProgOptions.h.
References LOG.
int FairProgOptions::Count (const std::string & key) const inline
Definition at line 101 of file FairProgOptions.h.
References fConfigMutex, and fVarMap.
Referenced by fair::mq::PluginServices::PropertyExists().
po::options_description & FairProgOptions::GetCmdLineOptions ()
Definition at line 53 of file FairProgOptions.cxx.
References fAllOptions.
Referenced by main().
auto FairProgOptions::GetPropertyKeys () const -> std::vector<std::string> inline
Definition at line 41 of file FairProgOptions.h.
References fConfigMutex, and fVarMap.
Referenced by fair::mq::PluginServices::GetPropertyKeys().
std::string FairProgOptions::GetStringValue (const std::string & key) inline
Definition at line 80 of file FairProgOptions.h.
References fConfigMutex, fVarMap, and LOG.
Referenced by FairMQProgOptions::EmitUpdate(), fair::mq::PluginServices::GetPropertyAsString(), FairMQProgOptions::SetValue(), testJSON2(), testXML2(), and FairMQProgOptions::UpdateValue().
template<typename T > T FairProgOptions::GetValue (const std::string & key) const inline
Definition at line 61 of file FairProgOptions.h.
References fConfigMutex, fVarMap, and LOG.
Referenced by FairMQDevice::CreateOwnConfig(), getDevice(), fair::mq::PluginServices::GetProperty(), Ex1Processor::Init(), Ex2Processor::Init(), Ex1Sampler::Init(), FairMQEx9aFileSinkBin::Init(), FairMQShmPrototypeSampler::Init(), Ex2Sampler::Init(), Ex1Sink::Init(), FairMQEx9FileSink::Init(), FairMQEx9FileSinkBin::Init(), Ex2Sink::Init(), FairTestDetectorFileSink< TIn, TPayloadIn >::Init(), FairMQExampleMTSampler2::InitTask(), FairMQExampleMTSampler1::InitTask(), FairMQExample1Sink::InitTask(), FairMQExample2Sink::InitTask(), FairMQExample4Sink::InitTask(), FairMQExample5Server::InitTask(), FairMQExample8Sampler::InitTask(), FairMQExampleMTSink::InitTask(), FairMQMultiplier::InitTask(), FairMQExample4Sampler::InitTask(), FairMQExampleRegionSampler::InitTask(), FairMQExampleRegionSink::InitTask(), FairMQExample6Sink::InitTask(), FairMQExample7Client::InitTask(), FairMQExample1Sampler::InitTask(), FairMQExample2Sampler::InitTask(), FairMQExample5Client::InitTask(), FairMQExample6Sampler::InitTask(), FairMQProxy::InitTask(), FairMQMerger::InitTask(), ParameterMQServer::InitTask(), FairMQSplitter::InitTask(), FairMQProcessor< Task >::InitTask(), FairMQSink::InitTask(), FairMQEx9SamplerBin::InitTask(), FairMQBenchmarkSampler::InitTask(), FairMQEx9Sampler::InitTask(), FairMQEx9aSamplerBin::InitTask(), FairMQUnpacker< UnpackerType, SerializationType >::InitTask(), FairMQSampler< Task >::InitTask(), FairMQLmdSampler::InitTask(), FairMQDevice::InitWrapper(), main(), FairMQDevice::SetConfig(), RootOutFileManager< DataType >::SetFileProperties(), testJSON1(), testJSON2(), testXML1(), and testXML2().
VarValInfo FairProgOptions::GetVariableValueInfo (const po::variable_value & varValue) private
Definition at line 175 of file FairProgOptions.cxx.
Referenced by PrintOptions(), and PrintOptionsRaw().
const po::variables_map& FairProgOptions::GetVarMap () const inline
Definition at line 125 of file FairProgOptions.h.
References fVarMap.
Referenced by main().
virtual int FairProgOptions::ImmediateOptions () protected pure virtual
Implemented in FairMQProgOptions.
Referenced by ParseCmdLine().
static void FairProgOptions::Max (int & val, const int & comp) inline static private
Definition at line 163 of file FairProgOptions.h.
Referenced by PrintOptions().
virtual int FairProgOptions::ParseAll (const int argc, char const *const * argv, bool allowUnregistered = false) pure virtual
Implemented in FairMQProgOptions.
int FairProgOptions::ParseCmdLine (const int argc, char const *const * argv, bool allowUnregistered = false)
Definition at line 58 of file FairProgOptions.cxx.
References fAllOptions, fVarMap, and ImmediateOptions().
Referenced by FairMQProgOptions::ParseAll().
void FairProgOptions::ParseDefaults ()
Definition at line 85 of file FairProgOptions.cxx.
References fAllOptions, and fVarMap.
Referenced by FairMQProgOptions::FairMQProgOptions().
int FairProgOptions::PrintOptions () virtual
Definition at line 100 of file FairProgOptions.cxx.
References fVarMap, GetVariableValueInfo(), LOG, and Max().
Referenced by FairMQProgOptions::ParseAll().
int FairProgOptions::PrintOptionsRaw () virtual
Definition at line 153 of file FairProgOptions.cxx.
References fAllOptions, fVarMap, GetVariableValueInfo(), fair::mq::VarValInfo::type, and fair::mq::VarValInfo::value.
Referenced by FairMQProgOptions::ImmediateOptions().
template<typename T > void FairProgOptions::Replace (std::map< std::string, po::variable_value > & vm, const std::string & key, const T & val) inline protected
Definition at line 155 of file FairProgOptions.h.
Referenced by UpdateVarMap().
template<typename T > void FairProgOptions::UpdateVarMap (const std::string & key, const T & val) inline protected
Definition at line 149 of file FairProgOptions.h.
References Replace().
Member Data Documentation
po::options_description FairProgOptions::fAllOptions protected
Definition at line 141 of file FairProgOptions.h.
Referenced by AddToCmdLineOptions(), FairProgOptions(), GetCmdLineOptions(), FairMQProgOptions::ImmediateOptions(), ParseCmdLine(), ParseDefaults(), and PrintOptionsRaw().
std::mutex FairProgOptions::fConfigMutex mutable protected
Definition at line 143 of file FairProgOptions.h.
Referenced by Count(), GetPropertyKeys(), GetStringValue(), GetValue(), FairMQProgOptions::SetValue(), FairMQProgOptions::Subscribe(), FairMQProgOptions::SubscribeAsString(), FairMQProgOptions::Unsubscribe(), FairMQProgOptions::UnsubscribeAsString(), and FairMQProgOptions::UpdateValue().
po::options_description FairProgOptions::fGeneralOptions protected
Definition at line 140 of file FairProgOptions.h.
Referenced by FairProgOptions().
po::variables_map FairProgOptions::fVarMap protected
Definition at line 137 of file FairProgOptions.h.
Referenced by Count(), GetPropertyKeys(), GetStringValue(), GetValue(), GetVarMap(), FairMQProgOptions::ImmediateOptions(), FairMQProgOptions::ParseAll(), ParseCmdLine(), ParseDefaults(), PrintOptions(), PrintOptionsRaw(), and FairMQProgOptions::UpdateValue().
The documentation for this class was generated from the following files:
FairProgOptions.h
FairProgOptions.cxx