FairRroot: MyPayloadProto::DigiPayload Class Reference
MyPayloadProto::DigiPayload Class Reference
#include <MyPayload.pb.h>
Public Member Functions
DigiPayload ()
virtual ~DigiPayload ()
DigiPayload (const DigiPayload &from)
DigiPayload & operator= (const DigiPayload &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (DigiPayload *other)
DigiPayload * New () const PROTOBUF_FINAL
DigiPayload * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const DigiPayload &from)
void MergeFrom (const DigiPayload &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int digi_size () const
void clear_digi ()
const ::MyPayloadProto::Digi & digi (int index) const
::MyPayloadProto::Digi * mutable_digi (int index)
::MyPayloadProto::Digi * add_digi ()
::google::protobuf::RepeatedPtrField< ::MyPayloadProto::Digi > * mutable_digi ()
const ::google::protobuf::RepeatedPtrField< ::MyPayloadProto::Digi > & digi () const
bool has_bigbuffer () const
void clear_bigbuffer ()
const ::std::string & bigbuffer () const
void set_bigbuffer (const ::std::string &value)
void set_bigbuffer (const char *value)
void set_bigbuffer (const void *value, size_t size)
::std::string * mutable_bigbuffer ()
::std::string * release_bigbuffer ()
void set_allocated_bigbuffer (::std::string *bigbuffer)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const DigiPayload & default_instance ()
static const DigiPayload * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kDigiFieldNumber = 1
static const int kBigBufferFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (DigiPayload *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_bigbuffer ()
void clear_has_bigbuffer ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::MyPayloadProto::Digi > digi_
::google::protobuf::internal::ArenaStringPtr bigbuffer_
Friends
struct protobuf_MyPayload_2eproto::TableStruct
void swap (DigiPayload &a, DigiPayload &b)
Detailed Description
Definition at line 413 of file MyPayload.pb.h.
Constructor & Destructor Documentation
MyPayloadProto::DigiPayload::DigiPayload ()
virtual MyPayloadProto::DigiPayload::~DigiPayload () virtual
MyPayloadProto::DigiPayload::DigiPayload (const DigiPayload & from)
Member Function Documentation
MyPayloadProto::Digi * MyPayloadProto::DigiPayload::add_digi () inline
Definition at line 1064 of file MyPayload.pb.h.
const ::std::string & MyPayloadProto::DigiPayload::bigbuffer () const inline
Definition at line 1093 of file MyPayload.pb.h.
size_t MyPayloadProto::DigiPayload::ByteSizeLong () const
void MyPayloadProto::DigiPayload::Clear ()
void MyPayloadProto::DigiPayload::clear_bigbuffer () inline
Definition at line 1089 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::clear_digi () inline
Definition at line 1053 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::clear_has_bigbuffer () inline private
Definition at line 1086 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::CopyFrom (const ::google::protobuf::Message & from)
void MyPayloadProto::DigiPayload::CopyFrom (const DigiPayload & from)
static const DigiPayload& MyPayloadProto::DigiPayload::default_instance () static
static const ::google::protobuf::Descriptor* MyPayloadProto::DigiPayload::descriptor () static
const ::MyPayloadProto::Digi & MyPayloadProto::DigiPayload::digi (int index) const inline
Definition at line 1056 of file MyPayload.pb.h.
const ::google::protobuf::RepeatedPtrField<::MyPayloadProto::Digi > & MyPayloadProto::DigiPayload::digi () const inline
Definition at line 1074 of file MyPayload.pb.h.
int MyPayloadProto::DigiPayload::digi_size () const inline
Definition at line 1050 of file MyPayload.pb.h.
inline ::google::protobuf::Arena* MyPayloadProto::DigiPayload::GetArenaNoVirtual () const inline private
Definition at line 487 of file MyPayload.pb.h.
int MyPayloadProto::DigiPayload::GetCachedSize () const inline
Definition at line 480 of file MyPayload.pb.h.
References MyPayloadProto::Digi::_cached_size_.
::google::protobuf::Metadata MyPayloadProto::DigiPayload::GetMetadata () const
bool MyPayloadProto::DigiPayload::has_bigbuffer () const inline
Definition at line 1080 of file MyPayload.pb.h.
static const DigiPayload* MyPayloadProto::DigiPayload::internal_default_instance () inline static
Definition at line 449 of file MyPayload.pb.h.
References MyPayloadProto::_DigiPayload_default_instance_.
::google::protobuf::uint8* MyPayloadProto::DigiPayload::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void MyPayloadProto::DigiPayload::InternalSwap (DigiPayload * other) private
bool MyPayloadProto::DigiPayload::IsInitialized () const
void* MyPayloadProto::DigiPayload::MaybeArenaPtr () const inline private
Definition at line 490 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::MergeFrom (const ::google::protobuf::Message & from)
void MyPayloadProto::DigiPayload::MergeFrom (const DigiPayload & from)
bool MyPayloadProto::DigiPayload::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
std::string * MyPayloadProto::DigiPayload::mutable_bigbuffer () inline
Definition at line 1122 of file MyPayload.pb.h.
MyPayloadProto::Digi * MyPayloadProto::DigiPayload::mutable_digi (int index) inline
Definition at line 1060 of file MyPayload.pb.h.
google::protobuf::RepeatedPtrField<::MyPayloadProto::Digi > * MyPayloadProto::DigiPayload::mutable_digi () inline
Definition at line 1069 of file MyPayload.pb.h.
inline ::google::protobuf::UnknownFieldSet* MyPayloadProto::DigiPayload::mutable_unknown_fields () inline
Definition at line 442 of file MyPayload.pb.h.
DigiPayload* MyPayloadProto::DigiPayload::New () const inline
Definition at line 463 of file MyPayload.pb.h.
References New().
Referenced by New().
DigiPayload* MyPayloadProto::DigiPayload::New (::google::protobuf::Arena * arena) const
DigiPayload& MyPayloadProto::DigiPayload::operator= (const DigiPayload & from) inline
Definition at line 420 of file MyPayload.pb.h.
References MyPayloadProto::Digi::CopyFrom().
std::string * MyPayloadProto::DigiPayload::release_bigbuffer () inline
Definition at line 1127 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void MyPayloadProto::DigiPayload::set_allocated_bigbuffer (::std::string * bigbuffer) inline
Definition at line 1132 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::set_bigbuffer (const ::std::string & value) inline
Definition at line 1097 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::set_bigbuffer (const char * value) inline
Definition at line 1110 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::set_bigbuffer (const void * value, size_t size) inline
Definition at line 1116 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::set_has_bigbuffer () inline private
Definition at line 1083 of file MyPayload.pb.h.
void MyPayloadProto::DigiPayload::SetCachedSize (int size) const private
void MyPayloadProto::DigiPayload::SharedCtor () private
void MyPayloadProto::DigiPayload::SharedDtor () private
void MyPayloadProto::DigiPayload::Swap (DigiPayload * other)
const ::google::protobuf::UnknownFieldSet& MyPayloadProto::DigiPayload::unknown_fields () const inline
Definition at line 439 of file MyPayload.pb.h.
Friends And Related Function Documentation
friend struct protobuf_MyPayload_2eproto::TableStruct friend
Definition at line 538 of file MyPayload.pb.h.
void swap (DigiPayload & a, DigiPayload & b) friend
Definition at line 457 of file MyPayload.pb.h.
Member Data Documentation
int MyPayloadProto::DigiPayload::_cached_size_ mutable private
Definition at line 535 of file MyPayload.pb.h.
::google::protobuf::internal::HasBits<1> MyPayloadProto::DigiPayload::_has_bits_ private
Definition at line 534 of file MyPayload.pb.h.
::google::protobuf::internal::InternalMetadataWithArena MyPayloadProto::DigiPayload::_internal_metadata_ private
Definition at line 533 of file MyPayload.pb.h.
::google::protobuf::internal::ArenaStringPtr MyPayloadProto::DigiPayload::bigbuffer_ private
Definition at line 537 of file MyPayload.pb.h.
::google::protobuf::RepeatedPtrField< ::MyPayloadProto::Digi > MyPayloadProto::DigiPayload::digi_ private
Definition at line 536 of file MyPayload.pb.h.
const int MyPayloadProto::DigiPayload::kBigBufferFieldNumber = 2 static
Definition at line 516 of file MyPayload.pb.h.
const int MyPayloadProto::DigiPayload::kDigiFieldNumber = 1 static
Definition at line 504 of file MyPayload.pb.h.
PROTOBUF_CONSTEXPR int const MyPayloadProto::DigiPayload::kIndexInFileMessages static
Initial value:
=
    2
Definition at line 453 of file MyPayload.pb.h.
The documentation for this class was generated from the following file:
MyPayload.pb.h