FairRoot: FairRadLenPoint Class Reference
FairRadLenPoint Class Reference
#include <FairRadLenPoint.h>
Public Member Functions
FairRadLenPoint ()
FairRadLenPoint (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss, TVector3 posOut, TVector3 momOut, Float_t fA, Float_t fZ, Float_t fDensity, Float_t fRadLen)
virtual ~FairRadLenPoint ()
Float_t GetA ()
Float_t GetZm ()
Float_t GetRadLength ()
Float_t GetDensity ()
void SetA (Double_t A)
void SetZm (Double_t Z)
void SetRadLength (Double_t length)
void SetDensity (Double_t Density)
virtual void Print (const Option_t *opt) const
Double_t GetXOut () const
Double_t GetYOut () const
Double_t GetZOut () const
Double_t GetPxOut () const
Double_t GetPyOut () const
Double_t GetPzOut () const
TVector3 GetPosition () const
TVector3 GetPositionOut () const
void PositionOut (TVector3 &pos) const
void MomentumOut (TVector3 &mom) const
UInt_t GetEventID () const
Int_t GetTrackID () const
event identifier
Double_t GetPx () const
Double_t GetPy () const
Double_t GetPz () const
Double_t GetTime () const
Double_t GetLength () const
Double_t GetEnergyLoss () const
void Momentum (TVector3 &mom) const
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetEventID (UInt_t eventId)
virtual void SetTrackID (Int_t id)
void SetTime (Double_t time)
void SetLength (Double_t length)
void SetEnergyLoss (Double_t eLoss)
void SetMomentum (const TVector3 &mom)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
template<class Archive >
void serialize (Archive &ar, const unsigned int)
std::set< FairLink > GetLinks () const
returns stored links as FairLinks
Int_t GetNLinks () const
returns the number of stored links
FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
FairLink GetEntryNr () const
FairMultiLinkedData * GetPointerToLinks () const
std::vector< FairLink > GetSortedMCTracks ()
void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
void SetLink (FairLink link)
Sets the Links with a single FairLink.
void SetInsertHistory (Bool_t val)
void SetEntryNr (FairLink val)
void SetPointerToLinks (FairMultiLinkedData *links)
void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
void AddInterfaceData (FairMultiLinkedData_Interface *data)
void ResetLinks ()
std::ostream & PrintLinkInfo (std::ostream &out=std::cout) const
Output.
Protected Member Functions
FairMultiLinkedData * CreateFairMultiLinkedData ()
ClassDef (FairMultiLinkedData_Interface, 5)
Protected Attributes
Float_t fA
Float_t fZmat
Float_t fDensity
Float_t fRadLen
Double_t fXOut
Double_t fYOut
Double_t fZOut
Double_t fPxOut
Double_t fPyOut
Double_t fPzOut
Int_t fTrackID
Track index.
UInt_t fEventId
MC Event id.
Double32_t fPx
Double32_t fPy
Double32_t fPz
Momentum components [GeV].
Double32_t fTime
Time since event start [ns].
Double32_t fLength
Track length since creation [cm].
Double32_t fELoss
Energy loss at this point [GeV].
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
FairMultiLinkedData * fLink
Detailed Description
FairRadLenPoint.h
Author
M. Al-Turany
Definition at line 27 of file FairRadLenPoint.h.
Constructor & Destructor Documentation
FairRadLenPoint() [1/2]
FairRadLenPoint::FairRadLenPoint ()
Default constructor
default ctor
Definition at line 18 of file FairRadLenPoint.cxx.
FairRadLenPoint() [2/2]
FairRadLenPoint::FairRadLenPoint (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss, TVector3 posOut, TVector3 momOut, Float_t fA, Float_t fZ, Float_t fDensity, Float_t fRadLen)
std ctor
Definition at line 40 of file FairRadLenPoint.cxx.
~FairRadLenPoint()
FairRadLenPoint::~FairRadLenPoint () virtual
Destructor
Definition at line 63 of file FairRadLenPoint.cxx.
Member Function Documentation
AddInterfaceData()
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) inherited
Definition at line 172 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
Referenced by FairTestDetectorTimeRecoTask::Exec().
AddLink()
void FairMultiLinkedData_Interface::AddLink (FairLink link) inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
AddLinks()
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 155 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
ClassDef()
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
CreateFairMultiLinkedData()
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 59 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
GetA()
Float_t FairRadLenPoint::GetA () inline
Accessors
Definition at line 45 of file FairRadLenPoint.h.
References fA.
GetDensity()
Float_t FairRadLenPoint::GetDensity () inline
Definition at line 48 of file FairRadLenPoint.h.
References fDensity.
GetDetectorID()
Int_t FairMCPoint::GetDetectorID () const inline inherited
Definition at line 63 of file FairMCPoint.h.
References FairMCPoint::fDetectorID.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), FairTutorialDet4PointDraw::Exec(), PixelDigitize::Exec(), and FairTutorialDet4HitProducerIdealMisalign::Exec().
GetEnergyLoss()
Double_t FairMCPoint::GetEnergyLoss () const inline inherited
Definition at line 61 of file FairMCPoint.h.
References FairMCPoint::fELoss.
GetEntryNr()
FairLink FairMultiLinkedData_Interface::GetEntryNr () const inherited
Definition at line 101 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetEntryNr(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorTimeRecoTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
GetEventID()
UInt_t FairMCPoint::GetEventID () const inline inherited
Accessors
Definition at line 54 of file FairMCPoint.h.
References FairMCPoint::fEventId.
GetLength()
Double_t FairMCPoint::GetLength () const inline inherited
Definition at line 60 of file FairMCPoint.h.
References FairMCPoint::fLength.
GetLink()
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const inherited
returns the FairLink at the given position
Definition at line 91 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetLinks()
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const inherited
returns stored links as FairLinks
Definition at line 72 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetLinksWithType()
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const inherited
returns all FairLinks with the corresponding type
Definition at line 111 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetNLinks()
Int_t FairMultiLinkedData_Interface::GetNLinks () const inherited
returns the number of stored links
Definition at line 82 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetPointerToLinks()
FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairPrintFairLinks::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::GetSortedMCTracks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::PrintLinkInfo(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
GetPosition()
TVector3 FairRadLenPoint::GetPosition () const inline
Definition at line 68 of file FairRadLenPoint.h.
References FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
GetPositionOut()
TVector3 FairRadLenPoint::GetPositionOut () const inline
Definition at line 69 of file FairRadLenPoint.h.
References fXOut, fYOut, and fZOut.
GetPx()
Double_t FairMCPoint::GetPx () const inline inherited
Definition at line 56 of file FairMCPoint.h.
References FairMCPoint::fPx.
GetPxOut()
Double_t FairRadLenPoint::GetPxOut () const inline
Definition at line 64 of file FairRadLenPoint.h.
References fPxOut.
GetPy()
Double_t FairMCPoint::GetPy () const inline inherited
Definition at line 57 of file FairMCPoint.h.
References FairMCPoint::fPy.
GetPyOut()
Double_t FairRadLenPoint::GetPyOut () const inline
Definition at line 65 of file FairRadLenPoint.h.
References fPyOut.
GetPz()
Double_t FairMCPoint::GetPz () const inline inherited
Definition at line 58 of file FairMCPoint.h.
References FairMCPoint::fPz.
GetPzOut()
Double_t FairRadLenPoint::GetPzOut () const inline
Definition at line 66 of file FairRadLenPoint.h.
References fPzOut.
GetRadLength()
Float_t FairRadLenPoint::GetRadLength () inline
Definition at line 47 of file FairRadLenPoint.h.
References fRadLen.
GetSortedMCTracks()
std::vector< FairLink > FairMultiLinkedData_Interface::GetSortedMCTracks () inherited
Definition at line 121 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::GetSortedMCTracks().
GetTime()
Double_t FairMCPoint::GetTime () const inline inherited
Definition at line 59 of file FairMCPoint.h.
References FairMCPoint::fTime.
Referenced by FairTestDetectorDigiTask::Exec(), and FairTestDetectorTimeDigiTask::Exec().
GetTrackID()
Int_t FairMCPoint::GetTrackID () const inline inherited
event identifier
Definition at line 55 of file FairMCPoint.h.
References FairMCPoint::fTrackID.
Referenced by MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
GetX()
Double_t FairMCPoint::GetX () const inline inherited
Definition at line 64 of file FairMCPoint.h.
References FairMCPoint::fX.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4PointDraw::Exec(), PixelDigitize::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
GetXOut()
Double_t FairRadLenPoint::GetXOut () const inline
Definition at line 60 of file FairRadLenPoint.h.
References fXOut.
GetY()
Double_t FairMCPoint::GetY () const inline inherited
Definition at line 65 of file FairMCPoint.h.
References FairMCPoint::fY.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4PointDraw::Exec(), PixelDigitize::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
GetYOut()
Double_t FairRadLenPoint::GetYOut () const inline
Definition at line 61 of file FairRadLenPoint.h.
References fYOut.
GetZ()
Double_t FairMCPoint::GetZ () const inline inherited
Definition at line 66 of file FairMCPoint.h.
References FairMCPoint::fZ.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4PointDraw::Exec(), PixelDigitize::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
GetZm()
Float_t FairRadLenPoint::GetZm () inline
Definition at line 46 of file FairRadLenPoint.h.
References fZmat.
GetZOut()
Double_t FairRadLenPoint::GetZOut () const inline
Definition at line 62 of file FairRadLenPoint.h.
References fZOut.
Momentum()
void FairMCPoint::Momentum (TVector3 & mom) const inline inherited
Definition at line 62 of file FairMCPoint.h.
References FairMCPoint::fPx, FairMCPoint::fPy, and FairMCPoint::fPz.
MomentumOut()
void FairRadLenPoint::MomentumOut (TVector3 & mom) const inline
Definition at line 72 of file FairRadLenPoint.h.
References fPxOut, fPyOut, and fPzOut.
Position()
void FairMCPoint::Position (TVector3 & pos) const inline inherited
Definition at line 67 of file FairMCPoint.h.
References FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
Referenced by FairTestDetectorHitProducerSmearing::Exec().
PositionOut()
void FairRadLenPoint::PositionOut (TVector3 & pos) const inline
Definition at line 71 of file FairRadLenPoint.h.
References fXOut, fYOut, and fZOut.
Print()
void FairRadLenPoint::Print (const Option_t * opt) const virtual
Output to screen
to be implimented
Reimplemented from FairMCPoint.
Definition at line 66 of file FairRadLenPoint.cxx.
PrintLinkInfo()
std::ostream& FairMultiLinkedData_Interface::PrintLinkInfo (std::ostream & out = std::cout) const inline inherited
Output.
Definition at line 66 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::PrintLinkInfo().
Referenced by FairTimeStamp::PrintTimeInfo().
ResetLinks()
void FairMultiLinkedData_Interface::ResetLinks () inherited
Definition at line 193 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
serialize()
template<class Archive > void FairMCPoint::serialize (Archive & ar, const unsigned int) inline inherited
Definition at line 93 of file FairMCPoint.h.
References FairMCPoint::fDetectorID, FairMCPoint::fELoss, FairMCPoint::fEventId, FairMCPoint::fLength, FairMCPoint::fPx, FairMCPoint::fPy, FairMCPoint::fPz, FairMCPoint::fTime, FairMCPoint::fTrackID, FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
SetA()
void FairRadLenPoint::SetA (Double_t A) inline
Modifiers
Definition at line 52 of file FairRadLenPoint.h.
References fA.
SetDensity()
void FairRadLenPoint::SetDensity (Double_t Density) inline
Definition at line 55 of file FairRadLenPoint.h.
References fDensity.
SetDetectorID()
void FairMCPoint::SetDetectorID (Int_t detID) inline inherited
Definition at line 79 of file FairMCPoint.h.
References FairMCPoint::fDetectorID.
SetEnergyLoss()
void FairMCPoint::SetEnergyLoss (Double_t eLoss) inline inherited
Definition at line 77 of file FairMCPoint.h.
References FairMCPoint::fELoss.
SetEntryNr()
void FairMultiLinkedData_Interface::SetEntryNr (FairLink val) inherited
Definition at line 147 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetEntryNr().
Referenced by FairRingSorterTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetEventID()
void FairMCPoint::SetEventID (UInt_t eventId) inline inherited
Modifiers
Definition at line 73 of file FairMCPoint.h.
References FairMCPoint::fEventId.
SetInsertHistory()
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) inherited
Definition at line 186 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetLength()
void FairMCPoint::SetLength (Double_t length) inline inherited
Definition at line 76 of file FairMCPoint.h.
References FairMCPoint::fLength.
SetLink()
void FairMultiLinkedData_Interface::SetLink (FairLink link) inherited
Sets the Links with a single FairLink.
Definition at line 139 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetector::AddHit(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
SetLinks()
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 131 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetMomentum()
void FairMCPoint::SetMomentum (const TVector3 & mom) inline inherited
Definition at line 129 of file FairMCPoint.h.
References FairMCPoint::fPx, FairMCPoint::fPy, and FairMCPoint::fPz.
SetPointerToLinks()
void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline inherited
Definition at line 55 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
SetPosition()
void FairMCPoint::SetPosition (const TVector3 & pos) inline inherited
Definition at line 145 of file FairMCPoint.h.
References FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
SetRadLength()
void FairRadLenPoint::SetRadLength (Double_t length) inline
Definition at line 54 of file FairRadLenPoint.h.
References fRadLen.
SetTime()
void FairMCPoint::SetTime (Double_t time) inline inherited
Definition at line 75 of file FairMCPoint.h.
References FairMCPoint::fTime.
SetTrackID()
virtual void FairMCPoint::SetTrackID (Int_t id) inline virtual inherited
Definition at line 74 of file FairMCPoint.h.
References FairMCPoint::fTrackID.
Referenced by MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
SetX()
void FairMCPoint::SetX (Double_t x) inline inherited
Definition at line 80 of file FairMCPoint.h.
References FairMCPoint::fX.
SetXYZ()
void FairMCPoint::SetXYZ (Double_t x, Double_t y, Double_t z) inline inherited
Definition at line 137 of file FairMCPoint.h.
References FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
SetY()
void FairMCPoint::SetY (Double_t y) inline inherited
Definition at line 81 of file FairMCPoint.h.
References FairMCPoint::fY.
SetZ()
void FairMCPoint::SetZ (Double_t z) inline inherited
Definition at line 82 of file FairMCPoint.h.
References FairMCPoint::fZ.
SetZm()
void FairRadLenPoint::SetZm (Double_t Z) inline
Definition at line 53 of file FairRadLenPoint.h.
References fZmat.
Member Data Documentation
fA
Float_t FairRadLenPoint::fA protected
Definition at line 77 of file FairRadLenPoint.h.
Referenced by GetA(), and SetA().
fDensity
Float_t FairRadLenPoint::fDensity protected
Definition at line 79 of file FairRadLenPoint.h.
Referenced by GetDensity(), and SetDensity().
fDetectorID
Int_t FairMCPoint::fDetectorID protected inherited
Detector unique identifier.
Definition at line 120 of file FairMCPoint.h.
Referenced by FairMCPoint::GetDetectorID(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetDetectorID().
fELoss
Double32_t FairMCPoint::fELoss protected inherited
Energy loss at this point [GeV].
Definition at line 119 of file FairMCPoint.h.
Referenced by FairMCPoint::GetEnergyLoss(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetEnergyLoss().
fEventId
UInt_t FairMCPoint::fEventId protected inherited
MC Event id.
Definition at line 115 of file FairMCPoint.h.
Referenced by FairMCPoint::GetEventID(), FairMCPoint::serialize(), and FairMCPoint::SetEventID().
fLength
Double32_t FairMCPoint::fLength protected inherited
Track length since creation [cm].
Definition at line 118 of file FairMCPoint.h.
Referenced by FairMCPoint::GetLength(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetLength().
fLink
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
fPx
Double32_t FairMCPoint::fPx protected inherited
Definition at line 116 of file FairMCPoint.h.
Referenced by FairMCPoint::GetPx(), FairTestDetectorPoint::GetPxIn(), FairMCPoint::Momentum(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetMomentum().
fPxOut
Double_t FairRadLenPoint::fPxOut protected
Definition at line 83 of file FairRadLenPoint.h.
Referenced by GetPxOut(), and MomentumOut().
fPy
Double32_t FairMCPoint::fPy protected inherited
Definition at line 116 of file FairMCPoint.h.
Referenced by FairMCPoint::GetPy(), FairTestDetectorPoint::GetPyIn(), FairMCPoint::Momentum(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetMomentum().
fPyOut
Double_t FairRadLenPoint::fPyOut protected
Definition at line 83 of file FairRadLenPoint.h.
Referenced by GetPyOut(), and MomentumOut().
fPz
Double32_t FairMCPoint::fPz protected inherited
Momentum components [GeV].
Definition at line 116 of file FairMCPoint.h.
Referenced by FairMCPoint::GetPz(), FairTestDetectorPoint::GetPzIn(), FairMCPoint::Momentum(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetMomentum().
fPzOut
Double_t FairRadLenPoint::fPzOut protected
Definition at line 83 of file FairRadLenPoint.h.
Referenced by GetPzOut(), and MomentumOut().
fRadLen
Float_t FairRadLenPoint::fRadLen protected
Definition at line 80 of file FairRadLenPoint.h.
Referenced by GetRadLength(), and SetRadLength().
fTime
Double32_t FairMCPoint::fTime protected inherited
Time since event start [ns].
Definition at line 117 of file FairMCPoint.h.
Referenced by FairMCPoint::GetTime(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetTime().
fTrackID
Int_t FairMCPoint::fTrackID protected inherited
Track index.
Definition at line 114 of file FairMCPoint.h.
Referenced by FairMCPoint::GetTrackID(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetTrackID().
fX
Double32_t FairMCPoint::fX protected inherited
Definition at line 121 of file FairMCPoint.h.
Referenced by GetPosition(), FairRadMapPoint::GetPosition(), FairMCPoint::GetX(), FairTestDetectorPoint::GetXIn(), FairMCPoint::Position(), FairRutherfordPoint::Print(), PixelPoint::Print(), NewDetectorPoint::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), FairMCPoint::SetPosition(), FairMCPoint::SetX(), and FairMCPoint::SetXYZ().
fXOut
Double_t FairRadLenPoint::fXOut protected
Definition at line 82 of file FairRadLenPoint.h.
Referenced by GetPositionOut(), GetXOut(), and PositionOut().
fY
Double32_t FairMCPoint::fY protected inherited
Definition at line 121 of file FairMCPoint.h.
Referenced by GetPosition(), FairRadMapPoint::GetPosition(), FairMCPoint::GetY(), FairTestDetectorPoint::GetYIn(), FairMCPoint::Position(), FairRutherfordPoint::Print(), PixelPoint::Print(), NewDetectorPoint::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), FairMCPoint::SetPosition(), FairMCPoint::SetXYZ(), and FairMCPoint::SetY().
fYOut
Double_t FairRadLenPoint::fYOut protected
Definition at line 82 of file FairRadLenPoint.h.
Referenced by GetPositionOut(), GetYOut(), and PositionOut().
fZ
Double32_t FairMCPoint::fZ protected inherited
Position of hit [cm].
Definition at line 121 of file FairMCPoint.h.
Referenced by GetPosition(), FairRadMapPoint::GetPosition(), FairMCPoint::GetZ(), FairTestDetectorPoint::GetZIn(), FairMCPoint::Position(), FairRutherfordPoint::Print(), PixelPoint::Print(), NewDetectorPoint::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), FairMCPoint::SetPosition(), FairMCPoint::SetXYZ(), and FairMCPoint::SetZ().
fZmat
Float_t FairRadLenPoint::fZmat protected
Definition at line 78 of file FairRadLenPoint.h.
Referenced by GetZm(), and SetZm().
fZOut
Double_t FairRadLenPoint::fZOut protected
Definition at line 82 of file FairRadLenPoint.h.
Referenced by GetPositionOut(), GetZOut(), and PositionOut().
The documentation for this class was generated from the following files:
FairRadLenPoint.h
FairRadLenPoint.cxx