FairRroot: FairGeoParSet Class Reference
FairGeoParSet Class Reference
#include <FairGeoParSet.h>
Public Member Functions
FairGeoParSet (const char *name="FairGeoParSet", const char *title="Class for base parameter io", const char *context="BaseDefaultContext")
~FairGeoParSet (void)
void clear (void)
void putParams (FairParamList *)
Bool_t getParams (FairParamList *)
void SetGeoNodes (TObjArray *array)
void SetGeometry (TGeoManager *Geom)
TObjArray * GetGeoNodes ()
TGeoManager * GetGeometry ()
virtual void printParams ()
Bool_t init (FairParIo *inp)
virtual Bool_t init ()
Int_t write (FairParIo *output)
virtual Int_t write ()
void fill (UInt_t)
void store (UInt_t)
virtual const char * GetName () const
virtual const char * GetTitle () const
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setOwnership (Bool_t flag=kTRUE)
Bool_t isOwned ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Member Functions
ClassDef(FairGeoParSet, 1) private FairGeoParSet & operator= (const FairGeoParSet &)
Protected Attributes
TObjArray * fGeoNodes
List of FairGeoNodes for sensitive volumes.
TGeoManager * fGeom
Full Geometry.
TString fName
TString fTitle
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
Bool_t owned
flag is kTRUE if parameters have changed
TString paramContext
if flag is KTRUE FairDB has the par. class ownership
TString author
TString description
FairLogger * fLogger
Detailed Description
Definition at line 24 of file FairGeoParSet.h.
Constructor & Destructor Documentation
FairGeoParSet::FairGeoParSet (const char * name = "FairGeoParSet", const char * title = "Class for base parameter io", const char * context = "BaseDefaultContext")
constructor
Parameters
name : Parameter set name
title Parameter set title
context Parameter set context
FairGeoParSet::~FairGeoParSet (void)
dtor
Definition at line 30 of file FairGeoParSet.cxx.
Member Function Documentation
void FairGeoParSet::clear (void) virtual
clear
Reimplemented from FairParSet.
Definition at line 34 of file FairGeoParSet.cxx.
void FairParSet::copyComment (FairParSet & r) inline inherited
Definition at line 76 of file FairParSet.h.
References FairParSet::getAuthor(), and FairParSet::getDescription().
void FairParGenericSet::fill (UInt_t) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 32 of file FairParGenericSet.h.
const char* FairParSet::getAuthor () const inline inherited
Definition at line 71 of file FairParSet.h.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
const char* FairParSet::getDescription () const inline inherited
Definition at line 74 of file FairParSet.h.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
const char* FairParSet::getDetectorName () inline inherited
Definition at line 48 of file FairParSet.h.
TGeoManager* FairGeoParSet::GetGeometry () inline
Get the geometry (TGeoManager) used in the simulation
Definition at line 71 of file FairGeoParSet.h.
References fGeom.
Referenced by PixelFindHitsTask::Exec().
TObjArray* FairGeoParSet::GetGeoNodes () inline
Get the Geometry Nodes list used in the simulation
Definition at line 67 of file FairGeoParSet.h.
References fGeoNodes.
Referenced by FairModule::ProcessNodes().
Int_t FairParSet::getInputVersion (Int_t i) inline inherited
Definition at line 54 of file FairParSet.h.
Referenced by FairRuntimeDb::findOutputVersion(), FairDetParRootFileIo::read(), and FairRuntimeDb::writeContainer().
virtual const char* FairParSet::GetName () const inline virtual inherited
Definition at line 38 of file FairParSet.h.
Referenced by FairRuntimeDb::addContainer(), FairRuntimeDb::addRun(), FairRuntimeDb::findOutputVersion(), FairGenericParAsciiFileIo::init(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), FairRuntimeDb::initContainers(), FairParSet::print(), FairRuntimeDb::print(), FairParGenericSet::printParams(), FairDetParRootFileIo::read(), FairGenericParAsciiFileIo::write(), FairDetParRootFileIo::write(), FairParSet::write(), FairRuntimeDb::writeContainer(), FairGenericParAsciiFileIo::writeGenericSet(), and FairRuntimeDb::~FairRuntimeDb().
const char* FairParSet::getParamContext () const inline inherited
Definition at line 68 of file FairParSet.h.
Referenced by FairGenericParAsciiFileIo::writeGenericSet().
Bool_t FairGeoParSet::getParams (FairParamList * l) virtual
Fills all persistent data members from the list after reading. The function returns false, when a data member is not in the list.
Parameters
FairParamList : Parameter list to be filled
Implements FairParGenericSet.
Definition at line 48 of file FairGeoParSet.cxx.
References fGeom, fGeoNodes, and FairParamList::fillObject().
virtual const char* FairParSet::GetTitle () const inline virtual inherited
Definition at line 39 of file FairParSet.h.
Referenced by FairRuntimeDb::print().
Bool_t FairParSet::hasChanged () inline inherited
Definition at line 66 of file FairParSet.h.
References FairParSet::changed.
Referenced by FairRuntimeDb::findOutputVersion(), and FairRuntimeDb::writeContainer().
Bool_t FairParGenericSet::init (FairParIo * inp) virtual inherited
Reimplemented from FairParSet.
Bool_t FairParSet::init () virtual inherited
Definition at line 46 of file FairParSet.cxx.
References FairRuntimeDb::getFirstInput(), FairParSet::GetName(), FairRuntimeDb::getSecondInput(), FairRuntimeDb::instance(), LOG, rtdb, and FairParSet::setInputVersion().
Referenced by FairRuntimeDb::initContainers().
Bool_t FairParSet::isOwned () inline inherited
Definition at line 63 of file FairParSet.h.
References FairParSet::owned.
Referenced by FairRuntimeDb::~FairRuntimeDb().
Bool_t FairParSet::isStatic () inline inherited
Definition at line 60 of file FairParSet.h.
References FairParSet::status.
Referenced by FairRuntimeDb::initContainers(), and FairRuntimeDb::resetInputVersions().
ClassDef (FairGeoParSet,1) private FairGeoParSet& FairGeoParSet::operator= (const FairGeoParSet &) inline protected
Definition at line 83 of file FairGeoParSet.h.
void FairParSet::print () virtual inherited
Reimplemented in FairMQExample7ParOne.
Definition at line 84 of file FairParSet.cxx.
References FairParSet::author, FairParSet::changed, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParSet::status, and FairParSet::versions.
Referenced by create_digis(), create_digis_mixed(), read_digis(), ParameterMQServer::Run(), and FairRuntimeDb::writeContainer().
void FairParGenericSet::printParams () virtual inherited
Definition at line 59 of file FairParGenericSet.cxx.
References FairParSet::author, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParamList::print(), and FairParGenericSet::putParams().
Referenced by PixelFindHitsTask::Init(), and read_digis().
void FairGeoParSet::putParams (FairParamList * l) virtual
Fills all persistent data members into the list for write.
Parameters
FairParamList : Parameter list to be filled
Implements FairParGenericSet.
Definition at line 41 of file FairGeoParSet.cxx.
References FairParamList::addObject(), fGeom, and fGeoNodes.
void FairParSet::resetInputVersions () inherited
Definition at line 99 of file FairParSet.cxx.
References FairParSet::changed, FairParSet::status, and FairParSet::versions.
Referenced by FairMQExample7ParOne::clear(), FairTutorialDet2DigiPar::clear(), and FairRuntimeDb::resetInputVersions().
void FairParSet::setAuthor (const char * s) inline inherited
Definition at line 70 of file FairParSet.h.
Referenced by FairDetParAsciiFileIo::readComment().
void FairParSet::setChanged (Bool_t flag = kTRUE) inline inherited
Definition at line 65 of file FairParSet.h.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), create_digis(), create_digis_mixed(), FairConstField::FillParContainer(), for(), FairRunOnline::Init(), FairRunSim::Init(), FairTutorialDet4::Initialize(), FairDetParRootFileIo::read(), read_digis(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), FairTutorialDet4::SetSensitiveVolumes(), FairDetParRootFileIo::write(), FairRuntimeDb::writeContainer(), and FairGenericParAsciiFileIo::writeGenericSet().
void FairParSet::setDescription (const char * s) inline inherited
Definition at line 73 of file FairParSet.h.
Referenced by FairDetParAsciiFileIo::readComment().
void FairGeoParSet::SetGeometry (TGeoManager * Geom) inline
Set the Geometry (TGeoManager) used in the simulation
Parameters
Geom TGeoManager of the full geometry
Definition at line 63 of file FairGeoParSet.h.
References fGeom.
Referenced by FairRunOnline::Init(), and FairRunSim::Init().
void FairGeoParSet::SetGeoNodes (TObjArray * array) inline
Set the Geometry node list used in the simulation
Parameters
array TObjArray of Geometry nodes
Definition at line 58 of file FairGeoParSet.h.
References fGeoNodes.
void FairParSet::setInputVersion (Int_t v = -1, Int_t i = 0) inline inherited
Definition at line 51 of file FairParSet.h.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), create_digis(), create_digis_mixed(), FairConstField::FillParContainer(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), FairTutorialDet4::Initialize(), FairDetParRootFileIo::read(), read_digis(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), and FairTutorialDet4::SetSensitiveVolumes().
void FairParSet::setOwnership (Bool_t flag = kTRUE) inline inherited
Definition at line 62 of file FairParSet.h.
void FairParSet::setStatic (Bool_t flag = kTRUE) inline inherited
Definition at line 59 of file FairParSet.h.
Referenced by FairRuntimeDb::setContainersStatic().
void FairParGenericSet::store (UInt_t) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 33 of file FairParGenericSet.h.
Int_t FairParGenericSet::write (FairParIo * output) virtual inherited
Reimplemented from FairParSet.
Definition at line 50 of file FairParGenericSet.cxx.
References FairParIo::getDetParIo(), and FairDetParIo::write().
Int_t FairParSet::write () virtual inherited
Definition at line 72 of file FairParSet.cxx.
References FairParSet::GetName(), FairRuntimeDb::getOutput(), FairRuntimeDb::instance(), and LOG.
Referenced by FairRuntimeDb::writeContainer().
Member Data Documentation
TString FairParSet::author protected inherited
Definition at line 29 of file FairParSet.h.
Referenced by FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
Bool_t FairParSet::changed protected inherited
static flag
Definition at line 26 of file FairParSet.h.
Referenced by FairParSet::hasChanged(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
TString FairParSet::description protected inherited
Definition at line 30 of file FairParSet.h.
Referenced by FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
TString FairParSet::detName protected inherited
Definition at line 23 of file FairParSet.h.
Referenced by FairMQExample7ParOne::FairMQExample7ParOne(), FairTutorialDet2DigiPar::FairTutorialDet2DigiPar(), and FairParSet::operator=().
TGeoManager* FairGeoParSet::fGeom protected
Full Geometry.
Definition at line 78 of file FairGeoParSet.h.
Referenced by GetGeometry(), getParams(), putParams(), and SetGeometry().
TObjArray* FairGeoParSet::fGeoNodes protected
List of FairGeoNodes for sensitive volumes.
Definition at line 76 of file FairGeoParSet.h.
Referenced by GetGeoNodes(), getParams(), putParams(), and SetGeoNodes().
FairLogger* FairParSet::fLogger protected inherited
Fair Logger
Definition at line 32 of file FairParSet.h.
Referenced by FairParSet::operator=().
TString FairParSet::fName protected inherited
Definition at line 21 of file FairParSet.h.
Referenced by ClassImp(), FairBaseContFact::FairBaseContFact(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), MyPassiveContFact::MyPassiveContFact(), FairParSet::operator=(), and PixelContFact::PixelContFact().
TString FairParSet::fTitle protected inherited
Definition at line 22 of file FairParSet.h.
Referenced by FairBaseContFact::FairBaseContFact(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), MyPassiveContFact::MyPassiveContFact(), FairParSet::operator=(), and PixelContFact::PixelContFact().
Bool_t FairParSet::owned protected inherited
flag is kTRUE if parameters have changed
Definition at line 27 of file FairParSet.h.
Referenced by FairParSet::isOwned(), and FairParSet::operator=().
TString FairParSet::paramContext protected inherited
if flag is KTRUE FairDB has the par. class ownership
Definition at line 28 of file FairParSet.h.
Referenced by FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
Bool_t FairParSet::status protected inherited
versions of container in the 2 possible inputs
Definition at line 25 of file FairParSet.h.
Referenced by FairMQExample7ParOne::clear(), FairTutorialDet2DigiPar::clear(), FairParSet::isStatic(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
Int_t FairParSet::versions[3] protected inherited
name of the detector the container belongs to
Definition at line 24 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::operator=(), FairParSet::print(), and FairParSet::resetInputVersions().
The documentation for this class was generated from the following files:
FairGeoParSet.h
FairGeoParSet.cxx