FairRroot: PixelDigiBinSource Class Reference
PixelDigiBinSource Class Reference
#include <PixelDigiBinSource.h>
Public Member Functions
PixelDigiBinSource (TString inputFileName="test.dat")
virtual ~PixelDigiBinSource ()
Bool_t Init ()
Int_t ReadEvent (UInt_t i=0)
void Close ()
void Reset ()
virtual Source_Type GetSourceType ()
virtual void SetParUnpackers ()
virtual Bool_t InitUnpackers ()
virtual Bool_t ReInitUnpackers ()
virtual Int_t CheckMaxEventNo (Int_t EvtEnd=0)
virtual void FillEventHeader (FairEventHeader *feh)
void SetInputFileName (TString tstr)
virtual Bool_t ActivateObject (TObject **obj, const char *BrName)
virtual Bool_t ActivateObjectAny (void **, const std::type_info &, const char *)
virtual void ReadBranchEvent (const char *)
virtual void ReadBranchEvent (const char *, Int_t)
void SetRunId (Int_t runId)
Int_t GetRunId () const
Private Member Functions
PixelDigiBinSource (const PixelDigiBinSource &)
PixelDigiBinSource & operator= (const PixelDigiBinSource &)
Private Attributes
PixelEventHeader * fEventHeader
TClonesArray * fDigis
Int_t fNDigis
Int_t fTNofEvents
Int_t fTNofDigis
TString fInputFileName
std::ifstream fInputFile
Int_t fCurrentEntryNo
Int_t fRunId
Int_t fMCEntryNo
Int_t fPartNo
Detailed Description
Definition at line 32 of file PixelDigiBinSource.h.
Constructor & Destructor Documentation
PixelDigiBinSource::PixelDigiBinSource (TString inputFileName = "test.dat")
Definition at line 32 of file PixelDigiBinSource.cxx.
References LOG.
PixelDigiBinSource::~PixelDigiBinSource () virtual
Definition at line 51 of file PixelDigiBinSource.cxx.
PixelDigiBinSource::PixelDigiBinSource (const PixelDigiBinSource &) private
Member Function Documentation
Bool_t PixelDigiBinSource::ActivateObject (TObject ** obj, const char * BrName) virtual
Reimplemented from FairSource.
Definition at line 154 of file PixelDigiBinSource.cxx.
References fDigis, and fEventHeader.
virtual Bool_t FairSource::ActivateObjectAny (void ** , const std::type_info & , const char *) inline virtual inherited
Reimplemented in FairFileSource.
Definition at line 40 of file FairSource.h.
Referenced by FairRootManager::InitObjectAs().
Int_t PixelDigiBinSource::CheckMaxEventNo (Int_t EvtEnd = 0) virtual
Check the maximum event number we can run to
Reimplemented from FairSource.
Definition at line 180 of file PixelDigiBinSource.cxx.
void PixelDigiBinSource::Close () virtual
Implements FairSource.
Definition at line 167 of file PixelDigiBinSource.cxx.
References fInputFile.
void PixelDigiBinSource::FillEventHeader (FairEventHeader * feh) virtual
Reimplemented from FairSource.
Definition at line 187 of file PixelDigiBinSource.cxx.
References fMCEntryNo, fPartNo, and fRunId.
Int_t FairSource::GetRunId () const inline inherited
Definition at line 58 of file FairSource.h.
References FairSource::fRunId.
virtual Source_Type PixelDigiBinSource::GetSourceType () inline virtual
Implements FairSource.
Definition at line 44 of file PixelDigiBinSource.h.
References kFILE.
Bool_t PixelDigiBinSource::Init () virtual
Implements FairSource.
Definition at line 57 of file PixelDigiBinSource.cxx.
References fDigis, fEventHeader, fInputFile, fInputFileName, FairRootManager::Instance(), LOG, and FairRootManager::Register().
virtual Bool_t PixelDigiBinSource::InitUnpackers () inline virtual
Implements FairSource.
Definition at line 48 of file PixelDigiBinSource.h.
PixelDigiBinSource& PixelDigiBinSource::operator= (const PixelDigiBinSource &) private
virtual void FairSource::ReadBranchEvent (const char *) inline virtual inherited
Read the tree entry on one branch
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 53 of file FairSource.h.
Referenced by FairRootManager::ReadBranchEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
virtual void FairSource::ReadBranchEvent (const char * , Int_t) inline virtual inherited
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 54 of file FairSource.h.
Int_t PixelDigiBinSource::ReadEvent (UInt_t i = 0) virtual
Implements FairSource.
Definition at line 87 of file PixelDigiBinSource.cxx.
References fCurrentEntryNo, fDigis, fEventHeader, fInputFile, fMCEntryNo, fNDigis, fPartNo, fRunId, LOG, FairEventHeader::SetMCEntryNumber(), PixelEventHeader::SetPartNo(), and FairEventHeader::SetRunId().
virtual Bool_t PixelDigiBinSource::ReInitUnpackers () inline virtual
Implements FairSource.
Definition at line 50 of file PixelDigiBinSource.h.
void PixelDigiBinSource::Reset () virtual
Implements FairSource.
Definition at line 174 of file PixelDigiBinSource.cxx.
void PixelDigiBinSource::SetInputFileName (TString tstr) inline
Definition at line 57 of file PixelDigiBinSource.h.
References fInputFileName.
Referenced by run_dBinSource().
virtual void PixelDigiBinSource::SetParUnpackers () inline virtual
Implements FairSource.
Definition at line 46 of file PixelDigiBinSource.h.
void FairSource::SetRunId (Int_t runId) inline inherited
Definition at line 57 of file FairSource.h.
References FairSource::fRunId.
Referenced by FairRunOnline::Init().
Member Data Documentation
Int_t PixelDigiBinSource::fCurrentEntryNo private
Definition at line 72 of file PixelDigiBinSource.h.
Referenced by ReadEvent().
TClonesArray* PixelDigiBinSource::fDigis private
Definition at line 63 of file PixelDigiBinSource.h.
Referenced by ActivateObject(), Init(), and ReadEvent().
PixelEventHeader* PixelDigiBinSource::fEventHeader private
Definition at line 62 of file PixelDigiBinSource.h.
Referenced by ActivateObject(), Init(), and ReadEvent().
std::ifstream PixelDigiBinSource::fInputFile private
Definition at line 70 of file PixelDigiBinSource.h.
Referenced by Close(), Init(), and ReadEvent().
TString PixelDigiBinSource::fInputFileName private
Definition at line 69 of file PixelDigiBinSource.h.
Referenced by Init(), and SetInputFileName().
Int_t PixelDigiBinSource::fMCEntryNo private
Definition at line 75 of file PixelDigiBinSource.h.
Referenced by FillEventHeader(), and ReadEvent().
Int_t PixelDigiBinSource::fNDigis private
Output array of PixelDigi
Definition at line 64 of file PixelDigiBinSource.h.
Referenced by ReadEvent().
Int_t PixelDigiBinSource::fPartNo private
Definition at line 76 of file PixelDigiBinSource.h.
Referenced by FillEventHeader(), and ReadEvent().
Int_t PixelDigiBinSource::fRunId private
Definition at line 74 of file PixelDigiBinSource.h.
Referenced by FillEventHeader(), and ReadEvent().
Int_t PixelDigiBinSource::fTNofDigis private
Definition at line 67 of file PixelDigiBinSource.h.
Int_t PixelDigiBinSource::fTNofEvents private
Definition at line 66 of file PixelDigiBinSource.h.
The documentation for this class was generated from the following files:
PixelDigiBinSource.h
PixelDigiBinSource.cxx