FairRoot: FairMQSimDevice Class Reference
FairMQSimDevice Class Reference
#include <FairMQSimDevice.h>
Public Member Functions
FairMQSimDevice ()
virtual ~FairMQSimDevice ()
virtual void SendBranches ()
void SetNofEvents (int64_t nofev)
void SetTransportName (std::string str)
void SetMaterials (std::string str)
void SetMagneticField (FairField *field)
void SetDetectorArray (TObjArray *array)
void SetGenerator (FairPrimaryGenerator *primGen)
void SetStoreTraj (bool flag=true)
void SetTaskArray (TObjArray *array)
void SetFirstParameter (FairParIo *par)
void SetSecondParameter (FairParIo *par)
void SetUserConfig (const TString &Config)
void SetUserCuts (const TString &Cuts)
void SetSink (FairSink *sink)
void SetParamUpdateChannelName (TString tString)
Protected Member Functions
virtual void InitTask ()
virtual void PreRun ()
virtual void PostRun ()
virtual bool ConditionalRun ()
Private Member Functions
void UpdateParameterServer ()
void SendObject (TObject *obj, std::string chan)
FairMQSimDevice (const FairMQSimDevice &)
FairMQSimDevice & operator= (const FairMQSimDevice &)
Private Attributes
UInt_t fSimDeviceId
std::string fUpdateChannelName
FairRunSim * fRunSim
int64_t fNofEvents
std::string fTransportName
std::string fMaterialsFile
FairField * fMagneticField
TObjArray * fDetectorArray
FairPrimaryGenerator * fPrimaryGenerator
bool fStoreTrajFlag
TObjArray * fTaskArray
FairParIo * fFirstParameter
FairParIo * fSecondParameter
TString fUserConfig
TString fUserCuts
/** Macro for geant configuration*/
FairSink * fSink
/** Macro for geant cuts*/
Detailed Description
Definition at line 33 of file FairMQSimDevice.h.
Constructor & Destructor Documentation
FairMQSimDevice() [1/2]
FairMQSimDevice::FairMQSimDevice ()
Definition at line 56 of file FairMQSimDevice.cxx.
~FairMQSimDevice()
FairMQSimDevice::~FairMQSimDevice () virtual
Definition at line 219 of file FairMQSimDevice.cxx.
FairMQSimDevice() [2/2]
FairMQSimDevice::FairMQSimDevice (const FairMQSimDevice &) private
Member Function Documentation
ConditionalRun()
bool FairMQSimDevice::ConditionalRun () protected virtual
Definition at line 167 of file FairMQSimDevice.cxx.
References fNofEvents, fRunSim, fSimDeviceId, FairRunSim::Run(), and UpdateParameterServer().
InitTask()
void FairMQSimDevice::InitTask () protected virtual
Definition at line 75 of file FairMQSimDevice.cxx.
References FairRunSim::AddModule(), FairRun::AddTask(), fDetectorArray, fFirstParameter, fMagneticField, fMaterialsFile, fNofEvents, fPrimaryGenerator, fRunSim, fSecondParameter, fSimDeviceId, fSink, fStoreTrajFlag, fTaskArray, fTransportName, fUpdateChannelName, fUserConfig, fUserCuts, FairRun::GetRuntimeDb(), INFO, FairRunSim::Init(), FairPrimaryGenerator::SetEventNr(), FairRunSim::SetField(), FairRuntimeDb::setFirstInput(), FairRunSim::SetGenerator(), FairRunSim::SetMaterials(), FairRun::SetRunId(), FairRuntimeDb::setSecondInput(), FairRun::SetSink(), FairRunSim::SetStoreTraj(), FairRunSim::SetUserConfig(), and FairRunSim::SetUserCuts().
operator=()
FairMQSimDevice& FairMQSimDevice::operator= (const FairMQSimDevice &) private
PostRun()
void FairMQSimDevice::PostRun () protected virtual
Definition at line 215 of file FairMQSimDevice.cxx.
PreRun()
void FairMQSimDevice::PreRun () protected virtual
Definition at line 163 of file FairMQSimDevice.cxx.
SendBranches()
void FairMQSimDevice::SendBranches () virtual
Fill the Root tree.
Definition at line 223 of file FairMQSimDevice.cxx.
References DEBUG, fRunSim, FairRootManager::GetBranchNameList(), FairRootManager::GetObject(), FairRootManager::Instance(), and FairRunSim::StopMCRun().
Referenced by FairOnlineSink::Fill().
SendObject()
void FairMQSimDevice::SendObject (TObject * obj, std::string chan) private
Definition at line 194 of file FairMQSimDevice.cxx.
References INFO.
Referenced by UpdateParameterServer().
SetDetectorArray()
void FairMQSimDevice::SetDetectorArray (TObjArray * array) inline
Definition at line 46 of file FairMQSimDevice.h.
References fDetectorArray.
Referenced by getDevice().
SetFirstParameter()
void FairMQSimDevice::SetFirstParameter (FairParIo * par) inline
Definition at line 50 of file FairMQSimDevice.h.
References fFirstParameter, and par.
Referenced by getDevice().
SetGenerator()
void FairMQSimDevice::SetGenerator (FairPrimaryGenerator * primGen) inline
Definition at line 47 of file FairMQSimDevice.h.
References fPrimaryGenerator.
Referenced by getDevice().
SetMagneticField()
void FairMQSimDevice::SetMagneticField (FairField * field) inline
Definition at line 45 of file FairMQSimDevice.h.
References fMagneticField.
SetMaterials()
void FairMQSimDevice::SetMaterials (std::string str) inline
Definition at line 44 of file FairMQSimDevice.h.
References fMaterialsFile.
Referenced by getDevice().
SetNofEvents()
void FairMQSimDevice::SetNofEvents (int64_t nofev) inline
Definition at line 42 of file FairMQSimDevice.h.
References fNofEvents.
Referenced by getDevice().
SetParamUpdateChannelName()
void FairMQSimDevice::SetParamUpdateChannelName (TString tString) inline
Definition at line 57 of file FairMQSimDevice.h.
References fUpdateChannelName.
Referenced by getDevice().
SetSecondParameter()
void FairMQSimDevice::SetSecondParameter (FairParIo * par) inline
Definition at line 51 of file FairMQSimDevice.h.
References fSecondParameter, and par.
SetSink()
void FairMQSimDevice::SetSink (FairSink * sink) inline
Definition at line 54 of file FairMQSimDevice.h.
References fSink.
Referenced by getDevice().
SetStoreTraj()
void FairMQSimDevice::SetStoreTraj (bool flag = true) inline
Definition at line 48 of file FairMQSimDevice.h.
References fStoreTrajFlag.
Referenced by getDevice().
SetTaskArray()
void FairMQSimDevice::SetTaskArray (TObjArray * array) inline
Definition at line 49 of file FairMQSimDevice.h.
References fTaskArray.
Referenced by getDevice().
SetTransportName()
void FairMQSimDevice::SetTransportName (std::string str) inline
Definition at line 43 of file FairMQSimDevice.h.
References fTransportName.
Referenced by getDevice().
SetUserConfig()
void FairMQSimDevice::SetUserConfig (const TString & Config) inline
Definition at line 52 of file FairMQSimDevice.h.
References Config(), and fUserConfig.
SetUserCuts()
void FairMQSimDevice::SetUserCuts (const TString & Cuts) inline
Definition at line 53 of file FairMQSimDevice.h.
References fUserCuts.
UpdateParameterServer()
void FairMQSimDevice::UpdateParameterServer () private
Definition at line 175 of file FairMQSimDevice.cxx.
References fRunSim, fUpdateChannelName, FairRuntimeDb::getListOfContainers(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), SendObject(), and FairParSet::setDescription().
Referenced by ConditionalRun().
Member Data Documentation
fDetectorArray
TObjArray* FairMQSimDevice::fDetectorArray private
Definition at line 75 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetDetectorArray().
fFirstParameter
FairParIo* FairMQSimDevice::fFirstParameter private
Definition at line 79 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetFirstParameter().
fMagneticField
FairField* FairMQSimDevice::fMagneticField private
Definition at line 74 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetMagneticField().
fMaterialsFile
std::string FairMQSimDevice::fMaterialsFile private
Definition at line 73 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetMaterials().
fNofEvents
int64_t FairMQSimDevice::fNofEvents private
Definition at line 71 of file FairMQSimDevice.h.
Referenced by ConditionalRun(), InitTask(), and SetNofEvents().
fPrimaryGenerator
FairPrimaryGenerator* FairMQSimDevice::fPrimaryGenerator private
Definition at line 76 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetGenerator().
fRunSim
FairRunSim* FairMQSimDevice::fRunSim private
Definition at line 69 of file FairMQSimDevice.h.
Referenced by ConditionalRun(), InitTask(), SendBranches(), and UpdateParameterServer().
fSecondParameter
FairParIo* FairMQSimDevice::fSecondParameter private
Definition at line 80 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetSecondParameter().
fSimDeviceId
UInt_t FairMQSimDevice::fSimDeviceId private
Definition at line 66 of file FairMQSimDevice.h.
Referenced by ConditionalRun(), and InitTask().
fSink
FairSink* FairMQSimDevice::fSink private
/** Macro for geant cuts*/
Definition at line 83 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetSink().
fStoreTrajFlag
bool FairMQSimDevice::fStoreTrajFlag private
Definition at line 77 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetStoreTraj().
fTaskArray
TObjArray* FairMQSimDevice::fTaskArray private
Definition at line 78 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetTaskArray().
fTransportName
std::string FairMQSimDevice::fTransportName private
Definition at line 72 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetTransportName().
fUpdateChannelName
std::string FairMQSimDevice::fUpdateChannelName private
Definition at line 67 of file FairMQSimDevice.h.
Referenced by InitTask(), SetParamUpdateChannelName(), and UpdateParameterServer().
fUserConfig
TString FairMQSimDevice::fUserConfig private
Definition at line 81 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetUserConfig().
fUserCuts
TString FairMQSimDevice::fUserCuts private
/** Macro for geant configuration*/
Definition at line 82 of file FairMQSimDevice.h.
Referenced by InitTask(), and SetUserCuts().
The documentation for this class was generated from the following files:
FairMQSimDevice.h
FairMQSimDevice.cxx