FairRroot: MyPayloadProto::HitPayload Class Reference
MyPayloadProto::HitPayload Class Reference
#include <MyPayload.pb.h>
Public Member Functions
HitPayload ()
virtual ~HitPayload ()
HitPayload (const HitPayload &from)
HitPayload & operator= (const HitPayload &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (HitPayload *other)
HitPayload * New () const PROTOBUF_FINAL
HitPayload * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const HitPayload &from)
void MergeFrom (const HitPayload &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int hit_size () const
void clear_hit ()
const ::MyPayloadProto::Hit & hit (int index) const
::MyPayloadProto::Hit * mutable_hit (int index)
::MyPayloadProto::Hit * add_hit ()
::google::protobuf::RepeatedPtrField< ::MyPayloadProto::Hit > * mutable_hit ()
const ::google::protobuf::RepeatedPtrField< ::MyPayloadProto::Hit > & hit () const
bool has_bigbuffer () const
void clear_bigbuffer ()
const ::std::string & bigbuffer () const
void set_bigbuffer (const ::std::string &value)
void set_bigbuffer (const char *value)
void set_bigbuffer (const void *value, size_t size)
::std::string * mutable_bigbuffer ()
::std::string * release_bigbuffer ()
void set_allocated_bigbuffer (::std::string *bigbuffer)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const HitPayload & default_instance ()
static const HitPayload * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kHitFieldNumber = 1
static const int kBigBufferFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (HitPayload *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_bigbuffer ()
void clear_has_bigbuffer ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::MyPayloadProto::Hit > hit_
::google::protobuf::internal::ArenaStringPtr bigbuffer_
Friends
struct protobuf_MyPayload_2eproto::TableStruct
void swap (HitPayload &a, HitPayload &b)
Detailed Description
Definition at line 542 of file MyPayload.pb.h.
Constructor & Destructor Documentation
MyPayloadProto::HitPayload::HitPayload ()
virtual MyPayloadProto::HitPayload::~HitPayload () virtual
MyPayloadProto::HitPayload::HitPayload (const HitPayload & from)
Member Function Documentation
MyPayloadProto::Hit * MyPayloadProto::HitPayload::add_hit () inline
Definition at line 1161 of file MyPayload.pb.h.
const ::std::string & MyPayloadProto::HitPayload::bigbuffer () const inline
Definition at line 1190 of file MyPayload.pb.h.
size_t MyPayloadProto::HitPayload::ByteSizeLong () const
void MyPayloadProto::HitPayload::Clear ()
void MyPayloadProto::HitPayload::clear_bigbuffer () inline
Definition at line 1186 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::clear_has_bigbuffer () inline private
Definition at line 1183 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::clear_hit () inline
Definition at line 1150 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::CopyFrom (const ::google::protobuf::Message & from)
void MyPayloadProto::HitPayload::CopyFrom (const HitPayload & from)
static const HitPayload& MyPayloadProto::HitPayload::default_instance () static
static const ::google::protobuf::Descriptor* MyPayloadProto::HitPayload::descriptor () static
inline ::google::protobuf::Arena* MyPayloadProto::HitPayload::GetArenaNoVirtual () const inline private
Definition at line 616 of file MyPayload.pb.h.
int MyPayloadProto::HitPayload::GetCachedSize () const inline
Definition at line 609 of file MyPayload.pb.h.
References MyPayloadProto::Digi::_cached_size_.
::google::protobuf::Metadata MyPayloadProto::HitPayload::GetMetadata () const
bool MyPayloadProto::HitPayload::has_bigbuffer () const inline
Definition at line 1177 of file MyPayload.pb.h.
const ::MyPayloadProto::Hit & MyPayloadProto::HitPayload::hit (int index) const inline
Definition at line 1153 of file MyPayload.pb.h.
const ::google::protobuf::RepeatedPtrField<::MyPayloadProto::Hit > & MyPayloadProto::HitPayload::hit () const inline
Definition at line 1171 of file MyPayload.pb.h.
int MyPayloadProto::HitPayload::hit_size () const inline
Definition at line 1147 of file MyPayload.pb.h.
static const HitPayload* MyPayloadProto::HitPayload::internal_default_instance () inline static
Definition at line 578 of file MyPayload.pb.h.
References MyPayloadProto::_HitPayload_default_instance_.
::google::protobuf::uint8* MyPayloadProto::HitPayload::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void MyPayloadProto::HitPayload::InternalSwap (HitPayload * other) private
bool MyPayloadProto::HitPayload::IsInitialized () const
void* MyPayloadProto::HitPayload::MaybeArenaPtr () const inline private
Definition at line 619 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::MergeFrom (const ::google::protobuf::Message & from)
void MyPayloadProto::HitPayload::MergeFrom (const HitPayload & from)
bool MyPayloadProto::HitPayload::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
std::string * MyPayloadProto::HitPayload::mutable_bigbuffer () inline
Definition at line 1219 of file MyPayload.pb.h.
MyPayloadProto::Hit * MyPayloadProto::HitPayload::mutable_hit (int index) inline
Definition at line 1157 of file MyPayload.pb.h.
google::protobuf::RepeatedPtrField<::MyPayloadProto::Hit > * MyPayloadProto::HitPayload::mutable_hit () inline
Definition at line 1166 of file MyPayload.pb.h.
inline ::google::protobuf::UnknownFieldSet* MyPayloadProto::HitPayload::mutable_unknown_fields () inline
Definition at line 571 of file MyPayload.pb.h.
HitPayload* MyPayloadProto::HitPayload::New () const inline
Definition at line 592 of file MyPayload.pb.h.
References New().
Referenced by New().
HitPayload* MyPayloadProto::HitPayload::New (::google::protobuf::Arena * arena) const
HitPayload& MyPayloadProto::HitPayload::operator= (const HitPayload & from) inline
Definition at line 549 of file MyPayload.pb.h.
References MyPayloadProto::Digi::CopyFrom().
std::string * MyPayloadProto::HitPayload::release_bigbuffer () inline
Definition at line 1224 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void MyPayloadProto::HitPayload::set_allocated_bigbuffer (::std::string * bigbuffer) inline
Definition at line 1229 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::set_bigbuffer (const ::std::string & value) inline
Definition at line 1194 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::set_bigbuffer (const char * value) inline
Definition at line 1207 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::set_bigbuffer (const void * value, size_t size) inline
Definition at line 1213 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::set_has_bigbuffer () inline private
Definition at line 1180 of file MyPayload.pb.h.
void MyPayloadProto::HitPayload::SetCachedSize (int size) const private
void MyPayloadProto::HitPayload::SharedCtor () private
void MyPayloadProto::HitPayload::SharedDtor () private
void MyPayloadProto::HitPayload::Swap (HitPayload * other)
const ::google::protobuf::UnknownFieldSet& MyPayloadProto::HitPayload::unknown_fields () const inline
Definition at line 568 of file MyPayload.pb.h.
Friends And Related Function Documentation
friend struct protobuf_MyPayload_2eproto::TableStruct friend
Definition at line 667 of file MyPayload.pb.h.
void swap (HitPayload & a, HitPayload & b) friend
Definition at line 586 of file MyPayload.pb.h.
Member Data Documentation
int MyPayloadProto::HitPayload::_cached_size_ mutable private
Definition at line 664 of file MyPayload.pb.h.
::google::protobuf::internal::HasBits<1> MyPayloadProto::HitPayload::_has_bits_ private
Definition at line 663 of file MyPayload.pb.h.
::google::protobuf::internal::InternalMetadataWithArena MyPayloadProto::HitPayload::_internal_metadata_ private
Definition at line 662 of file MyPayload.pb.h.
::google::protobuf::internal::ArenaStringPtr MyPayloadProto::HitPayload::bigbuffer_ private
Definition at line 666 of file MyPayload.pb.h.
::google::protobuf::RepeatedPtrField< ::MyPayloadProto::Hit > MyPayloadProto::HitPayload::hit_ private
Definition at line 665 of file MyPayload.pb.h.
const int MyPayloadProto::HitPayload::kBigBufferFieldNumber = 2 static
Definition at line 645 of file MyPayload.pb.h.
const int MyPayloadProto::HitPayload::kHitFieldNumber = 1 static
Definition at line 633 of file MyPayload.pb.h.
PROTOBUF_CONSTEXPR int const MyPayloadProto::HitPayload::kIndexInFileMessages static
Initial value:
=
    3
Definition at line 582 of file MyPayload.pb.h.
The documentation for this class was generated from the following file:
MyPayload.pb.h