FairRroot: fair::mq::shmem::Manager Class Reference
fair::mq::shmem::Manager Class Reference
#include <Manager.h>
Public Member Functions
Manager (const std::string &name, size_t size)
Manager ()=delete
Manager (const Manager &)=delete
Manager operator= (const Manager &)=delete
boost::interprocess::managed_shared_memory & Segment ()
boost::interprocess::mapped_region * CreateRegion (const size_t size, const uint64_t id, FairMQRegionCallback callback)
Region * GetRemoteRegion (const uint64_t id)
void RemoveRegion (const uint64_t id)
void RemoveSegment ()
boost::interprocess::managed_shared_memory & ManagementSegment ()
Static Public Member Functions
static void Interrupt ()
static void Resume ()
Private Attributes
std::string fSessionName
std::string fSegmentName
std::string fManagementSegmentName
boost::interprocess::managed_shared_memory fSegment
boost::interprocess::managed_shared_memory fManagementSegment
Static Private Attributes
static std::unordered_map< uint64_t, Region > fRegions
Friends
struct Region
Detailed Description
Definition at line 38 of file Manager.h.
Constructor & Destructor Documentation
fair::mq::shmem::Manager::Manager (const std::string & name, size_t size)
fair::mq::shmem::Manager::Manager () delete
fair::mq::shmem::Manager::Manager (const Manager &) delete
Member Function Documentation
bipc::mapped_region * fair::mq::shmem::Manager::CreateRegion (const size_t size, const uint64_t id, FairMQRegionCallback callback)
Definition at line 57 of file Manager.cxx.
References fair::error, and LOG.
Referenced by FairMQUnmanagedRegionSHM::FairMQUnmanagedRegionSHM().
Region * fair::mq::shmem::Manager::GetRemoteRegion (const uint64_t id)
Definition at line 75 of file Manager.cxx.
Referenced by FairMQMessageSHM::CloseMessage(), and FairMQMessageSHM::GetData().
void fair::mq::shmem::Manager::Interrupt () static
Definition at line 37 of file Manager.cxx.
bipc::managed_shared_memory & fair::mq::shmem::Manager::ManagementSegment ()
Definition at line 125 of file Manager.cxx.
Referenced by FairMQUnmanagedRegionSHM::FairMQUnmanagedRegionSHM().
Manager fair::mq::shmem::Manager::operator= (const Manager &) delete
void fair::mq::shmem::Manager::RemoveRegion (const uint64_t id)
Definition at line 99 of file Manager.cxx.
Referenced by FairMQUnmanagedRegionSHM::~FairMQUnmanagedRegionSHM().
void fair::mq::shmem::Manager::RemoveSegment ()
Definition at line 104 of file Manager.cxx.
References fair::debug, and LOG.
void fair::mq::shmem::Manager::Resume () static
Definition at line 41 of file Manager.cxx.
bipc::managed_shared_memory & fair::mq::shmem::Manager::Segment ()
Definition at line 32 of file Manager.cxx.
Referenced by FairMQMessageSHM::CloseMessage(), FairMQMessageSHM::GetData(), FairMQMessageSHM::InitializeChunk(), and FairMQMessageSHM::SetUsedSize().
Friends And Related Function Documentation
friend struct Region friend
Definition at line 40 of file Manager.h.
Member Data Documentation
boost::interprocess::managed_shared_memory fair::mq::shmem::Manager::fManagementSegment private
Definition at line 68 of file Manager.h.
std::string fair::mq::shmem::Manager::fManagementSegmentName private
Definition at line 66 of file Manager.h.
std::unordered_map< uint64_t, Region > fair::mq::shmem::Manager::fRegions static private
Definition at line 69 of file Manager.h.
boost::interprocess::managed_shared_memory fair::mq::shmem::Manager::fSegment private
Definition at line 67 of file Manager.h.
std::string fair::mq::shmem::Manager::fSegmentName private
Definition at line 65 of file Manager.h.
std::string fair::mq::shmem::Manager::fSessionName private
Definition at line 64 of file Manager.h.
The documentation for this class was generated from the following files:
Manager.h
Manager.cxx