FairRroot: NewDetectorContFact Class Reference
NewDetectorContFact Class Reference
#include <NewDetectorContFact.h>
Public Member Functions
NewDetectorContFact ()
~NewDetectorContFact ()
FairParSet * createContainer (FairContainer *)
NewDetectorContFact ()
~NewDetectorContFact ()
FairParSet * createContainer (FairContainer *)
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual void activateParIo (FairParIo *)
Protected Member Functions
const char * getActualContext (const char *name)
Protected Attributes
TList * containers
FairLogger * fLogger
Private Member Functions
void setAllContainers ()
void setAllContainers ()
Detailed Description
Definition at line 15 of file NewDetector/NewDetectorContFact.h.
Constructor & Destructor Documentation
NewDetectorContFact::NewDetectorContFact ()
Constructor (called when the library is loaded)
Definition at line 20 of file NewDetector/NewDetectorContFact.cxx.
References FairRuntimeDb::addContFactory(), and FairRuntimeDb::instance().
NewDetectorContFact::~NewDetectorContFact () inline
Definition at line 21 of file NewDetector/NewDetectorContFact.h.
NewDetectorContFact::NewDetectorContFact ()
NewDetectorContFact::~NewDetectorContFact () inline
Definition at line 21 of file project_template/NewDetector/NewDetectorContFact.h.
Member Function Documentation
virtual void FairContFact::activateParIo (FairParIo *) inline virtual inherited
Definition at line 57 of file FairContFact.h.
Referenced by FairRuntimeDb::activateParIo().
Bool_t FairContFact::addContext (const char * name) inherited
Definition at line 160 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::setActualContext().
Referenced by FairRuntimeDb::addParamContext().
FairParSet * NewDetectorContFact::createContainer (FairContainer * c) virtual
Calls the constructor of the corresponding parameter container. For an actual context, which is not an empty string and not the default context of this container, the name is concatinated with the context.
Reimplemented from FairContFact.
Definition at line 45 of file NewDetector/NewDetectorContFact.cxx.
References FairContainer::getConcatName(), and FairContainer::getContext().
FairParSet* NewDetectorContFact::createContainer (FairContainer *) virtual
Reimplemented from FairContFact.
const char* FairContFact::getActualContext (const char * name) inline protected inherited
Definition at line 61 of file FairContFact.h.
FairParSet * FairContFact::getContainer (const char * name) inherited
Definition at line 172 of file FairContFact.cxx.
References FairRuntimeDb::addContainer(), FairContFact::containers, FairContFact::createContainer(), FairRuntimeDb::findContainer(), FairContainer::getActualContext(), FairContainer::getConcatName(), FairContainer::getDefaultContext(), FairRuntimeDb::instance(), rtdb, and FairContainer::setActualContext().
Referenced by FairRuntimeDb::getContainer().
void FairContFact::print () inherited
Definition at line 194 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::print().
Referenced by FairRuntimeDb::printParamContexts().
void NewDetectorContFact::setAllContainers () private
Creates the Container objects with all accepted contexts and adds them to the list of containers for the NewDetector library.
Definition at line 30 of file NewDetector/NewDetectorContFact.cxx.
References FairContainer::addContext(), and FairContFact::containers.
void NewDetectorContFact::setAllContainers () private
Member Data Documentation
TList* FairContFact::containers protected inherited
Definition at line 60 of file FairContFact.h.
Referenced by FairContFact::addContext(), FairContFact::getContainer(), FairContFact::print(), FairTutorialDet2ContFact::setAllContainers(), FairMQExample7ContFact::setAllContainers(), setAllContainers(), PixelContFact::setAllContainers(), FairTutorialDet1ContFact::setAllContainers(), FairTutorialDet4ContFact::setAllContainers(), FairTestDetectorContFact::setAllContainers(), FairRutherfordContFact::setAllContainers(), FairBaseContFact::setAllContainers(), and FairContFact::~FairContFact().
FairLogger* FairContFact::fLogger protected inherited
Fair Logger
Definition at line 65 of file FairContFact.h.
The documentation for this class was generated from the following files:
NewDetector/NewDetectorContFact.h
NewDetector/NewDetectorContFact.cxx