FairRoot: FairMQSampler< Task > Class Template Reference
FairMQSampler< Task > Class Template Reference
#include <FairMQSampler.h>
Public Member Functions
FairMQSampler ()
FairMQSampler (const FairMQSampler &)=delete
FairMQSampler operator= (const FairMQSampler &)=delete
virtual ~FairMQSampler ()
Protected Member Functions
virtual void InitTask ()
virtual void PreRun ()
virtual bool ConditionalRun ()
virtual void PostRun ()
virtual void ResetTask ()
void ListenForAcks ()
Private Attributes
FairRunAna * fFairRunAna
FairMQSamplerTask * fSamplerTask
std::chrono::high_resolution_clock::time_point fStart
std::chrono::high_resolution_clock::time_point fEnd
std::string fInputFile
std::string fParFile
std::string fBranch
std::string fOutChannelName
std::string fAckChannelName
int fNumEvents
int fChainInput
int fSentMsgs
std::thread fAckListener
Detailed Description
template<typename Task>
class FairMQSampler< Task >
FairMQSampler.h
Since
2012-09-27
Author
D. Klein, A. Rybalchenko, N. Winckler Reads simulated digis from a root file and samples the digi as a time-series UDP stream. Must be initialized with the filename to the root file and the name of the sub-detector branch, whose digis should be streamed.
The purpose of this class is to provide a data source of digis very similar to the future detector output at the point where the detector is connected to the online computing farm. For the development of online analysis algorithms, it is very important to simulate the future detector output as realistic as possible to evaluate the feasibility and quality of the various possible online analysis features.
Definition at line 55 of file FairMQSampler.h.
Constructor & Destructor Documentation
FairMQSampler() [1/2]
template<typename Task > FairMQSampler< Task >::FairMQSampler () inline
Definition at line 58 of file FairMQSampler.h.
FairMQSampler() [2/2]
template<typename Task > FairMQSampler< Task >::FairMQSampler (const FairMQSampler< Task > &) delete
~FairMQSampler()
template<typename Task > virtual FairMQSampler< Task >::~FairMQSampler () inline virtual
Definition at line 77 of file FairMQSampler.h.
Member Function Documentation
ConditionalRun()
template<typename Task > virtual bool FairMQSampler< Task >::ConditionalRun () inline protected virtual
Definition at line 151 of file FairMQSampler.h.
References FairMQSampler< Task >::fFairRunAna, FairMQSampler< Task >::fNumEvents, FairMQSampler< Task >::fOutChannelName, FairMQSampler< Task >::fSamplerTask, FairMQSampler< Task >::fSentMsgs, FairMQSamplerTask::GetPayload(), FairRunAna::RunMQ(), and FairMQSamplerTask::SetEventIndex().
InitTask()
template<typename Task > virtual void FairMQSampler< Task >::InitTask () inline protected virtual
Definition at line 81 of file FairMQSampler.h.
References FairFileSource::AddFile(), FairRun::AddTask(), FairMQSampler< Task >::fAckChannelName, FairMQSampler< Task >::fBranch, FairMQSampler< Task >::fChainInput, FairMQSampler< Task >::fFairRunAna, FairMQSampler< Task >::fInputFile, FairMQSampler< Task >::fNumEvents, FairMQSampler< Task >::fOutChannelName, FairMQSampler< Task >::fParFile, FairMQSampler< Task >::fSamplerTask, FairRootManager::GetInChain(), FairRun::GetRuntimeDb(), FairRunAna::Init(), FairRootManager::Instance(), FairParRootFileIo::open(), FairRuntimeDb::print(), FairMQSamplerTask::SetBranch(), FairRuntimeDb::setFirstInput(), FairRun::SetSink(), FairRunAna::SetSource(), and FairMQSamplerTask::SetTransport().
ListenForAcks()
template<typename Task > void FairMQSampler< Task >::ListenForAcks () inline protected
Definition at line 193 of file FairMQSampler.h.
References FairMQSampler< Task >::fAckChannelName, FairMQSampler< Task >::fEnd, FairMQSampler< Task >::fNumEvents, and FairMQSampler< Task >::fStart.
Referenced by FairMQSampler< Task >::PreRun().
operator=()
template<typename Task > FairMQSampler FairMQSampler< Task >::operator= (const FairMQSampler< Task > &) delete
PostRun()
template<typename Task > virtual void FairMQSampler< Task >::PostRun () inline protected virtual
Definition at line 171 of file FairMQSampler.h.
References FairMQSampler< Task >::fAckListener.
PreRun()
template<typename Task > virtual void FairMQSampler< Task >::PreRun () inline protected virtual
Definition at line 145 of file FairMQSampler.h.
References FairMQSampler< Task >::fAckListener, FairMQSampler< Task >::fStart, and FairMQSampler< Task >::ListenForAcks().
ResetTask()
template<typename Task > virtual void FairMQSampler< Task >::ResetTask () inline protected virtual
Definition at line 184 of file FairMQSampler.h.
References FairMQSampler< Task >::fFairRunAna, FairMQSampler< Task >::fSamplerTask, and FairRunAna::TerminateRun().
Member Data Documentation
fAckChannelName
template<typename Task > std::string FairMQSampler< Task >::fAckChannelName private
Definition at line 223 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::InitTask(), and FairMQSampler< Task >::ListenForAcks().
fAckListener
template<typename Task > std::thread FairMQSampler< Task >::fAckListener private
Definition at line 227 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::PostRun(), and FairMQSampler< Task >::PreRun().
fBranch
template<typename Task > std::string FairMQSampler< Task >::fBranch private
Definition at line 221 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::InitTask().
fChainInput
template<typename Task > int FairMQSampler< Task >::fChainInput private
Definition at line 225 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::InitTask().
fEnd
template<typename Task > std::chrono::high_resolution_clock::time_point FairMQSampler< Task >::fEnd private
Definition at line 218 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::ListenForAcks().
fFairRunAna
template<typename Task > FairRunAna* FairMQSampler< Task >::fFairRunAna private
Definition at line 215 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::ConditionalRun(), FairMQSampler< Task >::InitTask(), and FairMQSampler< Task >::ResetTask().
fInputFile
template<typename Task > std::string FairMQSampler< Task >::fInputFile private
Definition at line 219 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::InitTask().
fNumEvents
template<typename Task > int FairMQSampler< Task >::fNumEvents private
Definition at line 224 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::ConditionalRun(), FairMQSampler< Task >::InitTask(), and FairMQSampler< Task >::ListenForAcks().
fOutChannelName
template<typename Task > std::string FairMQSampler< Task >::fOutChannelName private
Definition at line 222 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::ConditionalRun(), and FairMQSampler< Task >::InitTask().
fParFile
template<typename Task > std::string FairMQSampler< Task >::fParFile private
Definition at line 220 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::InitTask().
fSamplerTask
template<typename Task > FairMQSamplerTask* FairMQSampler< Task >::fSamplerTask private
Definition at line 216 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::ConditionalRun(), FairMQSampler< Task >::InitTask(), and FairMQSampler< Task >::ResetTask().
fSentMsgs
template<typename Task > int FairMQSampler< Task >::fSentMsgs private
Definition at line 226 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::ConditionalRun().
fStart
template<typename Task > std::chrono::high_resolution_clock::time_point FairMQSampler< Task >::fStart private
Definition at line 217 of file FairMQSampler.h.
Referenced by FairMQSampler< Task >::ListenForAcks(), and FairMQSampler< Task >::PreRun().
The documentation for this class was generated from the following file:
FairMQSampler.h