FairRroot: FairMQTransportFactoryZMQ Class Reference
FairMQTransportFactoryZMQ Class Reference
#include <FairMQTransportFactoryZMQ.h>
Public Member Functions
FairMQTransportFactoryZMQ (const std::string &id="", const FairMQProgOptions *config=nullptr)
FairMQTransportFactoryZMQ (const FairMQTransportFactoryZMQ &)=delete
FairMQTransportFactoryZMQ operator= (const FairMQTransportFactoryZMQ &)=delete
~FairMQTransportFactoryZMQ () override
FairMQMessagePtr CreateMessage () const override
Create empty FairMQMessage.
FairMQMessagePtr CreateMessage (const size_t size) const override
Create new FairMQMessage of specified size.
FairMQMessagePtr CreateMessage (void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr) const override
Create new FairMQMessage with user provided buffer and size.
FairMQMessagePtr CreateMessage (FairMQUnmanagedRegionPtr &region, void *data, const size_t size, void *hint=0) const override
FairMQSocketPtr CreateSocket (const std::string &type, const std::string &name) const override
Create a socket.
FairMQPollerPtr CreatePoller (const std::vector< FairMQChannel > &channels) const override
Create a poller for a single channel (all subchannels)
FairMQPollerPtr CreatePoller (const std::vector< const FairMQChannel * > &channels) const override
Create a poller for specific channels.
FairMQPollerPtr CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> &channelsMap, const std::vector< std::string > &channelList) const override
Create a poller for specific channels (all subchannels)
FairMQPollerPtr CreatePoller (const FairMQSocket &cmdSocket, const FairMQSocket &dataSocket) const override
Create a poller for two sockets.
FairMQUnmanagedRegionPtr CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback) const override
FairMQ::Transport GetType () const override
Get transport type.
void Interrupt () override
void Resume () override
auto GetId () const -> const std::string
template<typename T >
FairMQMessagePtr NewSimpleMessage (const T &data) const
template<std::size_t N>
FairMQMessagePtr NewSimpleMessage (const char(&data)[N]) const
FairMQMessagePtr NewSimpleMessage (const std::string &str) const
template<typename T >
FairMQMessagePtr NewStaticMessage (const T &data) const
FairMQMessagePtr NewStaticMessage (const std::string &str) const
Static Public Member Functions
static auto CreateTransportFactory (const std::string &type, const std::string &id="", const FairMQProgOptions *config=nullptr) -> std::shared_ptr< FairMQTransportFactory >
static void FairMQNoCleanup (void *, void *)
template<typename T >
static void FairMQSimpleMsgCleanup (void *, void *obj)
Private Attributes
void * fContext
Static Private Attributes
static FairMQ::Transport fTransportType = FairMQ::Transport::ZMQ
Detailed Description
FairMQTransportFactoryZMQ.h
Since
2014-01-20
Author
: A. Rybalchenko
Definition at line 28 of file FairMQTransportFactoryZMQ.h.
Constructor & Destructor Documentation
FairMQTransportFactoryZMQ::FairMQTransportFactoryZMQ (const std::string & id = "", const FairMQProgOptions * config = nullptr)
FairMQTransportFactoryZMQ::FairMQTransportFactoryZMQ (const FairMQTransportFactoryZMQ &) delete
FairMQTransportFactoryZMQ::~FairMQTransportFactoryZMQ () override
Definition at line 108 of file FairMQTransportFactoryZMQ.cxx.
References fContext, and LOG.
Member Function Documentation
FairMQMessagePtr FairMQTransportFactoryZMQ::CreateMessage () const override virtual
Create empty FairMQMessage.
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 52 of file FairMQTransportFactoryZMQ.cxx.
FairMQMessagePtr FairMQTransportFactoryZMQ::CreateMessage (const size_t size) const override virtual
Create new FairMQMessage of specified size.
Parameters
size message size
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 57 of file FairMQTransportFactoryZMQ.cxx.
FairMQMessagePtr FairMQTransportFactoryZMQ::CreateMessage (void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr) const override virtual
Create new FairMQMessage with user provided buffer and size.
Parameters
data pointer to user provided buffer
size size of the user provided buffer
ffn callback, called when the message is transfered (and can be deleted)
obj optional helper pointer that can be used in the callback
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 62 of file FairMQTransportFactoryZMQ.cxx.
FairMQMessagePtr FairMQTransportFactoryZMQ::CreateMessage (FairMQUnmanagedRegionPtr & region, void * data, const size_t size, void * hint = 0) const override virtual
Implements FairMQTransportFactory.
Definition at line 67 of file FairMQTransportFactoryZMQ.cxx.
FairMQPollerPtr FairMQTransportFactoryZMQ::CreatePoller (const std::vector< FairMQChannel > & channels) const override virtual
Create a poller for a single channel (all subchannels)
Implements FairMQTransportFactory.
FairMQPollerPtr FairMQTransportFactoryZMQ::CreatePoller (const std::vector< const FairMQChannel * > & channels) const override virtual
Create a poller for specific channels.
Implements FairMQTransportFactory.
Definition at line 83 of file FairMQTransportFactoryZMQ.cxx.
FairMQPollerPtr FairMQTransportFactoryZMQ::CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> & channelsMap, const std::vector< std::string > & channelList) const override virtual
Create a poller for specific channels (all subchannels)
Implements FairMQTransportFactory.
FairMQPollerPtr FairMQTransportFactoryZMQ::CreatePoller (const FairMQSocket & cmdSocket, const FairMQSocket & dataSocket) const override virtual
Create a poller for two sockets.
Implements FairMQTransportFactory.
Definition at line 93 of file FairMQTransportFactoryZMQ.cxx.
FairMQSocketPtr FairMQTransportFactoryZMQ::CreateSocket (const std::string & type, const std::string & name) const override virtual
Create a socket.
Implements FairMQTransportFactory.
Definition at line 72 of file FairMQTransportFactoryZMQ.cxx.
References fContext, and FairMQTransportFactory::GetId().
auto FairMQTransportFactory::CreateTransportFactory (const std::string & type, const std::string & id = "", const FairMQProgOptions * config = nullptr) -> std::shared_ptr<FairMQTransportFactory> static inherited
Definition at line 30 of file FairMQTransportFactory.cxx.
References LOG, and fair::mq::tools::Uuid().
Referenced by FairMQDevice::AddTransport().
FairMQUnmanagedRegionPtr FairMQTransportFactoryZMQ::CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback) const override virtual
Implements FairMQTransportFactory.
Definition at line 98 of file FairMQTransportFactoryZMQ.cxx.
static void FairMQTransportFactory::FairMQNoCleanup (void * , void *) inline static inherited
Definition at line 81 of file FairMQTransportFactory.h.
Referenced by FairMQTransportFactory::NewStaticMessage().
template<typename T > static void FairMQTransportFactory::FairMQSimpleMsgCleanup (void * , void * obj) inline static inherited
Definition at line 86 of file FairMQTransportFactory.h.
auto FairMQTransportFactory::GetId () const -> const std::string inline inherited
Definition at line 38 of file FairMQTransportFactory.h.
References FairMQTransportFactory::fkId.
Referenced by FairMQTransportFactoryNN::CreateSocket(), FairMQTransportFactorySHM::CreateSocket(), and CreateSocket().
FairMQ::Transport FairMQTransportFactoryZMQ::GetType () const override virtual
Get transport type.
Implements FairMQTransportFactory.
Definition at line 103 of file FairMQTransportFactoryZMQ.cxx.
References fTransportType.
void FairMQTransportFactoryZMQ::Interrupt () inline override virtual
Implements FairMQTransportFactory.
Definition at line 53 of file FairMQTransportFactoryZMQ.h.
References FairMQSocketZMQ::Interrupt().
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const T & data) const inline inherited
Definition at line 92 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
template<std::size_t N> FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const char(&) data[N]) const inline inherited
Definition at line 101 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const std::string & str) const inline inherited
Definition at line 107 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const T & data) const inline inherited
Definition at line 115 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage(), and FairMQTransportFactory::FairMQNoCleanup().
FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const std::string & str) const inline inherited
Definition at line 120 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage(), and FairMQTransportFactory::FairMQNoCleanup().
FairMQTransportFactoryZMQ FairMQTransportFactoryZMQ::operator= (const FairMQTransportFactoryZMQ &) delete
void FairMQTransportFactoryZMQ::Resume () inline override virtual
Implements FairMQTransportFactory.
Definition at line 54 of file FairMQTransportFactoryZMQ.h.
References FairMQSocketZMQ::Resume().
Member Data Documentation
void* FairMQTransportFactoryZMQ::fContext private
Definition at line 58 of file FairMQTransportFactoryZMQ.h.
Referenced by CreateSocket(), and ~FairMQTransportFactoryZMQ().
FairMQ::Transport FairMQTransportFactoryZMQ::fTransportType = FairMQ::Transport::ZMQ static private
Definition at line 57 of file FairMQTransportFactoryZMQ.h.
Referenced by GetType().
The documentation for this class was generated from the following files:
FairMQTransportFactoryZMQ.h
FairMQTransportFactoryZMQ.cxx