FairRoot: FairBoxGenerator Class Reference
FairBoxGenerator Class Reference
#include <FairBoxGenerator.h>
Public Member Functions
FairBoxGenerator ()
FairBoxGenerator (Int_t pdgid, Int_t mult=1)
virtual ~FairBoxGenerator ()
void SetPDGType (Int_t pdg)
void SetMultiplicity (Int_t mult)
void SetPRange (Double32_t pmin=0, Double32_t pmax=10)
void SetPtRange (Double32_t ptmin=0, Double32_t ptmax=10)
void SetEkinRange (Double32_t kmin=0, Double32_t kmax=10)
void SetPhiRange (Double32_t phimin=0, Double32_t phimax=360)
void SetEtaRange (Double32_t etamin=-5, Double32_t etamax=7)
void SetYRange (Double32_t ymin=-5, Double32_t ymax=7)
void SetThetaRange (Double32_t thetamin=0, Double32_t thetamax=90)
void SetCosTheta ()
void SetXYZ (Double32_t x=0, Double32_t y=0, Double32_t z=0)
void SetBoxXYZ (Double32_t x1=0, Double32_t y1=0, Double32_t x2=0, Double32_t y2=0, Double32_t z=0)
void SetDebug (Bool_t debug=0)
Bool_t Init ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
FairBoxGenerator (const FairBoxGenerator &)
FairBoxGenerator & operator= (const FairBoxGenerator &)
ClassDef (FairGenerator, 1)
Private Member Functions
ClassDef (FairBoxGenerator, 4)
Private Attributes
Int_t fPDGType
Int_t fMult
Double32_t fPDGMass
Double32_t fPtMin
Double32_t fPtMax
Double32_t fPhiMin
Double32_t fPhiMax
Double32_t fEtaMin
Double32_t fEtaMax
Double32_t fYMin
Double32_t fYMax
Double32_t fPMin
Double32_t fPMax
Double32_t fThetaMin
Double32_t fThetaMax
Double32_t fX
Double32_t fY
Double32_t fZ
Double32_t fX1
Double32_t fY1
Double32_t fX2
Double32_t fY2
Double32_t fEkinMin
Double32_t fEkinMax
Bool_t fEtaRangeIsSet
Bool_t fYRangeIsSet
Bool_t fThetaRangeIsSet
Bool_t fCosThetaIsSet
Bool_t fPtRangeIsSet
Bool_t fPRangeIsSet
Bool_t fPointVtxIsSet
Bool_t fBoxVtxIsSet
Bool_t fDebug
Bool_t fEkinRangeIsSet
Detailed Description
Definition at line 43 of file FairBoxGenerator.h.
Constructor & Destructor Documentation
FairBoxGenerator() [1/3]
FairBoxGenerator::FairBoxGenerator ()
Default constructor.
Definition at line 39 of file FairBoxGenerator.cxx.
Referenced by CloneGenerator().
FairBoxGenerator() [2/3]
FairBoxGenerator::FairBoxGenerator (Int_t pdgid, Int_t mult = 1)
Constructor with PDG-ID, multiplicity
Parameters
pdgid Particle type (PDG encoding)
mult Multiplicity (default is 1)
Definition at line 53 of file FairBoxGenerator.cxx.
References SetPhiRange().
~FairBoxGenerator()
virtual FairBoxGenerator::~FairBoxGenerator () inline virtual
Destructor
Definition at line 57 of file FairBoxGenerator.h.
FairBoxGenerator() [3/3]
FairBoxGenerator::FairBoxGenerator (const FairBoxGenerator & rhs) protected
Copy constructor.
Definition at line 67 of file FairBoxGenerator.cxx.
Member Function Documentation
ClassDef() [1/2]
FairGenerator::ClassDef (FairGenerator , 1) protected inherited
ClassDef() [2/2]
FairBoxGenerator::ClassDef (FairBoxGenerator , 4) private
CloneGenerator()
FairGenerator * FairBoxGenerator::CloneGenerator () const virtual
Clone this object (used in MT mode only)
Reimplemented from FairGenerator.
Definition at line 247 of file FairBoxGenerator.cxx.
References FairBoxGenerator().
Init()
Bool_t FairBoxGenerator::Init () virtual
Initializer
Reimplemented from FairGenerator.
Definition at line 137 of file FairBoxGenerator.cxx.
References fBoxVtxIsSet, fEkinMax, fEkinMin, fEkinRangeIsSet, fEtaRangeIsSet, fPDGMass, fPDGType, fPhiMax, fPhiMin, fPMax, fPMin, fPointVtxIsSet, fPRangeIsSet, fPtRangeIsSet, fThetaRangeIsSet, and fYRangeIsSet.
operator=()
FairBoxGenerator & FairBoxGenerator::operator= (const FairBoxGenerator & rhs) protected
Definition at line 87 of file FairBoxGenerator.cxx.
References fBoxVtxIsSet, fCosThetaIsSet, fDebug, fEkinMax, fEkinMin, fEkinRangeIsSet, fEtaMax, fEtaMin, fEtaRangeIsSet, fMult, fPDGMass, fPDGType, fPhiMax, fPhiMin, fPMax, fPMin, fPointVtxIsSet, fPRangeIsSet, fPtMax, fPtMin, fPtRangeIsSet, fThetaMax, fThetaMin, fThetaRangeIsSet, fX, fX1, fX2, fY, fY1, fY2, fYMax, fYMin, fYRangeIsSet, and fZ.
ReadEvent()
Bool_t FairBoxGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Creates an event with given type and multiplicity.
Parameters
primGen pointer to the FairPrimaryGenerator
Implements FairGenerator.
Definition at line 186 of file FairBoxGenerator.cxx.
References FairPrimaryGenerator::AddTrack(), fBoxVtxIsSet, fCosThetaIsSet, fDebug, fEtaMax, fEtaMin, fEtaRangeIsSet, fMult, fPDGMass, fPDGType, fPhiMax, fPhiMin, fPMax, fPMin, fPRangeIsSet, fPtMax, fPtMin, fPtRangeIsSet, fThetaMax, fThetaMin, fThetaRangeIsSet, fX, fX1, fX2, fY, fY1, fY2, fYMax, fYMin, fYRangeIsSet, and fZ.
SetBoxXYZ()
void FairBoxGenerator::SetBoxXYZ (Double32_t x1 = 0, Double32_t y1 = 0, Double32_t x2 = 0, Double32_t y2 = 0, Double32_t z = 0) inline
Definition at line 95 of file FairBoxGenerator.h.
References fBoxVtxIsSet, fX1, fX2, fY1, fY2, and fZ.
Referenced by run_tutorial4().
SetCosTheta()
void FairBoxGenerator::SetCosTheta () inline
Definition at line 85 of file FairBoxGenerator.h.
References fCosThetaIsSet.
Referenced by run_sim(), run_sim_sep(), and run_tutorial1_mesh().
SetDebug()
void FairBoxGenerator::SetDebug (Bool_t debug = 0) inline
Definition at line 104 of file FairBoxGenerator.h.
References fDebug.
Referenced by run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), and run_tutorial1_pythia8().
SetEkinRange()
void FairBoxGenerator::SetEkinRange (Double32_t kmin = 0, Double32_t kmax = 10) inline
Definition at line 70 of file FairBoxGenerator.h.
References fEkinMax, fEkinMin, and fEkinRangeIsSet.
SetEtaRange()
void FairBoxGenerator::SetEtaRange (Double32_t etamin = -5, Double32_t etamax = 7) inline
Definition at line 76 of file FairBoxGenerator.h.
References fEtaMax, fEtaMin, and fEtaRangeIsSet.
SetMultiplicity()
void FairBoxGenerator::SetMultiplicity (Int_t mult) inline
Definition at line 62 of file FairBoxGenerator.h.
References fMult.
SetPDGType()
void FairBoxGenerator::SetPDGType (Int_t pdg) inline
Modifiers
Definition at line 60 of file FairBoxGenerator.h.
References fPDGType.
SetPhiRange()
void FairBoxGenerator::SetPhiRange (Double32_t phimin = 0, Double32_t phimax = 360) inline
Definition at line 73 of file FairBoxGenerator.h.
References fPhiMax, and fPhiMin.
Referenced by FairBoxGenerator(), getDevice(), run_bg(), run_rad(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial2(), and run_tutorial4().
SetPRange()
void FairBoxGenerator::SetPRange (Double32_t pmin = 0, Double32_t pmax = 10) inline
Definition at line 64 of file FairBoxGenerator.h.
References fPMax, fPMin, and fPRangeIsSet.
Referenced by getDevice(), run_bg(), run_rad(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial2(), and run_tutorial4().
SetPtRange()
void FairBoxGenerator::SetPtRange (Double32_t ptmin = 0, Double32_t ptmax = 10) inline
Definition at line 67 of file FairBoxGenerator.h.
References fPtMax, fPtMin, and fPtRangeIsSet.
SetThetaRange()
void FairBoxGenerator::SetThetaRange (Double32_t thetamin = 0, Double32_t thetamax = 90) inline
Definition at line 82 of file FairBoxGenerator.h.
References fThetaMax, fThetaMin, and fThetaRangeIsSet.
Referenced by getDevice(), run_bg(), run_rad(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial2(), and run_tutorial4().
SetXYZ()
void FairBoxGenerator::SetXYZ (Double32_t x = 0, Double32_t y = 0, Double32_t z = 0) inline
Definition at line 88 of file FairBoxGenerator.h.
References fPointVtxIsSet, fX, fY, and fZ.
Referenced by run_rad(), run_rutherford(), and run_sim().
SetYRange()
void FairBoxGenerator::SetYRange (Double32_t ymin = -5, Double32_t ymax = 7) inline
Definition at line 79 of file FairBoxGenerator.h.
References fYMax, fYMin, and fYRangeIsSet.
Member Data Documentation
fBoxVtxIsSet
Bool_t FairBoxGenerator::fBoxVtxIsSet private
Definition at line 145 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetBoxXYZ().
fCosThetaIsSet
Bool_t FairBoxGenerator::fCosThetaIsSet private
Definition at line 140 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetCosTheta().
fDebug
Bool_t FairBoxGenerator::fDebug private
Definition at line 146 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetDebug().
fEkinMax
Double32_t FairBoxGenerator::fEkinMax private
Definition at line 135 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), and SetEkinRange().
fEkinMin
Double32_t FairBoxGenerator::fEkinMin private
Definition at line 135 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), and SetEkinRange().
fEkinRangeIsSet
Bool_t FairBoxGenerator::fEkinRangeIsSet private
Definition at line 147 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), and SetEkinRange().
fEtaMax
Double32_t FairBoxGenerator::fEtaMax private
Definition at line 129 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetEtaRange().
fEtaMin
Double32_t FairBoxGenerator::fEtaMin private
Definition at line 129 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetEtaRange().
fEtaRangeIsSet
Bool_t FairBoxGenerator::fEtaRangeIsSet private
Definition at line 137 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetEtaRange().
fMult
Int_t FairBoxGenerator::fMult private
Definition at line 124 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetMultiplicity().
fPDGMass
Double32_t FairBoxGenerator::fPDGMass private
Definition at line 126 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), and ReadEvent().
fPDGType
Int_t FairBoxGenerator::fPDGType private
Definition at line 123 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetPDGType().
fPhiMax
Double32_t FairBoxGenerator::fPhiMax private
Definition at line 128 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetPhiRange().
fPhiMin
Double32_t FairBoxGenerator::fPhiMin private
Definition at line 128 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetPhiRange().
fPMax
Double32_t FairBoxGenerator::fPMax private
Definition at line 131 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetPRange().
fPMin
Double32_t FairBoxGenerator::fPMin private
Definition at line 131 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetPRange().
fPointVtxIsSet
Bool_t FairBoxGenerator::fPointVtxIsSet private
Definition at line 144 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), and SetXYZ().
fPRangeIsSet
Bool_t FairBoxGenerator::fPRangeIsSet private
Definition at line 143 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetPRange().
fPtMax
Double32_t FairBoxGenerator::fPtMax private
Definition at line 127 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetPtRange().
fPtMin
Double32_t FairBoxGenerator::fPtMin private
Definition at line 127 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetPtRange().
fPtRangeIsSet
Bool_t FairBoxGenerator::fPtRangeIsSet private
Definition at line 142 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetPtRange().
fThetaMax
Double32_t FairBoxGenerator::fThetaMax private
Definition at line 132 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetThetaRange().
fThetaMin
Double32_t FairBoxGenerator::fThetaMin private
Definition at line 132 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetThetaRange().
fThetaRangeIsSet
Bool_t FairBoxGenerator::fThetaRangeIsSet private
Definition at line 139 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetThetaRange().
fX
Double32_t FairBoxGenerator::fX private
Definition at line 133 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetXYZ().
fX1
Double32_t FairBoxGenerator::fX1 private
Definition at line 134 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetBoxXYZ().
fX2
Double32_t FairBoxGenerator::fX2 private
Definition at line 134 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetBoxXYZ().
fY
Double32_t FairBoxGenerator::fY private
Definition at line 133 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetXYZ().
fY1
Double32_t FairBoxGenerator::fY1 private
Definition at line 134 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetBoxXYZ().
fY2
Double32_t FairBoxGenerator::fY2 private
Definition at line 134 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetBoxXYZ().
fYMax
Double32_t FairBoxGenerator::fYMax private
Definition at line 130 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetYRange().
fYMin
Double32_t FairBoxGenerator::fYMin private
Definition at line 130 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), and SetYRange().
fYRangeIsSet
Bool_t FairBoxGenerator::fYRangeIsSet private
Definition at line 138 of file FairBoxGenerator.h.
Referenced by Init(), operator=(), ReadEvent(), and SetYRange().
fZ
Double32_t FairBoxGenerator::fZ private
Definition at line 133 of file FairBoxGenerator.h.
Referenced by operator=(), ReadEvent(), SetBoxXYZ(), and SetXYZ().
The documentation for this class was generated from the following files:
FairBoxGenerator.h
FairBoxGenerator.cxx