FairRoot: PixelFindHits Class Reference
PixelFindHits Class Reference
#include <PixelFindHits.h>
Public Member Functions
PixelFindHits ()
PixelFindHits (Int_t iVerbose)
PixelFindHits (const char *name, Int_t iVerbose)
virtual ~PixelFindHits ()
virtual void Exec (Option_t *opt)
virtual void GetParList (TList *tempList)
virtual void InitMQ (TList *tempList)
virtual void ExecMQ (TList *inputList, TList *outputList)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Private Member Functions
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
void Reset ()
virtual void Finish ()
PixelFindHits (const PixelFindHits &)
PixelFindHits & operator= (const PixelFindHits &)
ClassDef (PixelFindHits, 1)
Private Attributes
PixelDigiPar * fDigiPar
FairGeoParSet * fGeoParSet
TClonesArray * fDigis
TClonesArray * fHits
Int_t fNDigis
Int_t fNHits
Int_t fTNofEvents
Int_t fTNofDigis
Int_t fTNofHits
Int_t fFeCols
Int_t fFeRows
Int_t fMaxFEperCol
Double_t fPitchX
Double_t fPitchY
Detailed Description
Definition at line 31 of file PixelFindHits.h.
Constructor & Destructor Documentation
PixelFindHits() [1/4]
PixelFindHits::PixelFindHits ()
Default constructor
Definition at line 50 of file PixelFindHits.cxx.
PixelFindHits() [2/4]
PixelFindHits::PixelFindHits (Int_t iVerbose)
Standard constructor
Definition at line 59 of file PixelFindHits.cxx.
PixelFindHits() [3/4]
PixelFindHits::PixelFindHits (const char * name, Int_t iVerbose)
Constructor with name
Definition at line 68 of file PixelFindHits.cxx.
References Reset().
~PixelFindHits()
PixelFindHits::~PixelFindHits () virtual
Destructor
Definition at line 93 of file PixelFindHits.cxx.
References fDigiPar, fHits, and Reset().
PixelFindHits() [4/4]
PixelFindHits::PixelFindHits (const PixelFindHits &) private
Member Function Documentation
CheckInputPersistance()
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
ClassDef()
PixelFindHits::ClassDef (PixelFindHits , 1) private
Exec()
void PixelFindHits::Exec (Option_t * opt) virtual
Execution
Definition at line 104 of file PixelFindHits.cxx.
References fDigis, fFeCols, fFeRows, fMaxFEperCol, fNDigis, fNHits, fPitchX, fPitchY, fTNofDigis, fTNofEvents, fTNofHits, PixelDigi::GetCol(), PixelDigi::GetDetectorID(), PixelDigi::GetFeID(), PixelDigi::GetIndex(), PixelDigi::GetRow(), and Reset().
Referenced by ExecMQ().
ExecMQ()
void PixelFindHits::ExecMQ (TList * inputList, TList * outputList) virtual
Definition at line 208 of file PixelFindHits.cxx.
References Exec(), fDigis, and fHits.
ExecuteTask()
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
ExecuteTasks()
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
Finish()
void PixelFindHits::Finish () private virtual
Finish at the end of each event
Reimplemented from FairTask.
Definition at line 271 of file PixelFindHits.cxx.
References fHits, fTNofDigis, fTNofEvents, and fTNofHits.
FinishEvent()
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
FinishEvents()
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
FinishTask()
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
FinishTasks()
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
GetParList()
void PixelFindHits::GetParList (TList * tempList) virtual
Definition at line 176 of file PixelFindHits.cxx.
References fDigiPar.
Init()
InitStatus PixelFindHits::Init () private virtual
Intialisation
Reimplemented from FairTask.
Definition at line 220 of file PixelFindHits.cxx.
References fDigiPar, fDigis, fFeCols, fFeRows, fHits, fMaxFEperCol, fPitchX, fPitchY, PixelDigiPar::GetFECols(), PixelDigiPar::GetFERows(), PixelDigiPar::GetMaxFEperCol(), FairRootManager::GetObject(), PixelDigiPar::GetXPitch(), PixelDigiPar::GetYPitch(), FairRootManager::Instance(), kSUCCESS, and FairRootManager::Register().
InitMQ()
void PixelFindHits::InitMQ (TList * tempList) virtual
Definition at line 185 of file PixelFindHits.cxx.
References fDigiPar, fFeCols, fFeRows, fHits, fMaxFEperCol, fPitchX, fPitchY, PixelDigiPar::GetFECols(), PixelDigiPar::GetFERows(), PixelDigiPar::GetMaxFEperCol(), PixelDigiPar::GetXPitch(), and PixelDigiPar::GetYPitch().
InitTask()
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
InitTasks()
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
IsOutputBranchPersistent()
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
operator=()
PixelFindHits& PixelFindHits::operator= (const PixelFindHits &) private
ReInit()
InitStatus PixelFindHits::ReInit () private virtual
Reinitialisation
Reimplemented from FairTask.
Definition at line 254 of file PixelFindHits.cxx.
References kSUCCESS.
ReInitTask()
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
ReInitTasks()
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
Reset()
void PixelFindHits::Reset () private
Reset eventwise counters
Definition at line 264 of file PixelFindHits.cxx.
References fHits, fNDigis, and fNHits.
Referenced by Exec(), PixelFindHits(), and ~PixelFindHits().
SetInputPersistance()
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
SetOutputBranchPersistent()
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
SetParContainers()
void PixelFindHits::SetParContainers () private virtual
Get parameter containers
Reimplemented from FairTask.
Definition at line 160 of file PixelFindHits.cxx.
References fDigiPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRun::Instance().
SetParTask()
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
SetParTasks()
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
SetStreamProcessing()
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
SetVerbose()
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
fDigiPar
PixelDigiPar* PixelFindHits::fDigiPar private
Definition at line 61 of file PixelFindHits.h.
Referenced by GetParList(), Init(), InitMQ(), SetParContainers(), and ~PixelFindHits().
fDigis
TClonesArray* PixelFindHits::fDigis private
Definition at line 65 of file PixelFindHits.h.
Referenced by Exec(), ExecMQ(), and Init().
fFeCols
Int_t PixelFindHits::fFeCols private
Definition at line 75 of file PixelFindHits.h.
Referenced by Exec(), Init(), and InitMQ().
fFeRows
Int_t PixelFindHits::fFeRows private
Definition at line 76 of file PixelFindHits.h.
Referenced by Exec(), Init(), and InitMQ().
fGeoParSet
FairGeoParSet* PixelFindHits::fGeoParSet private
Definition at line 62 of file PixelFindHits.h.
fHits
TClonesArray* PixelFindHits::fHits private
Input array of PixelDigi
Definition at line 66 of file PixelFindHits.h.
Referenced by ExecMQ(), Finish(), Init(), InitMQ(), Reset(), and ~PixelFindHits().
fInputPersistance
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
fLogger
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
fMaxFEperCol
Int_t PixelFindHits::fMaxFEperCol private
Definition at line 77 of file PixelFindHits.h.
Referenced by Exec(), Init(), and InitMQ().
fNDigis
Int_t PixelFindHits::fNDigis private
Output array of PixelHit
Definition at line 68 of file PixelFindHits.h.
Referenced by Exec(), and Reset().
fNHits
Int_t PixelFindHits::fNHits private
Definition at line 69 of file PixelFindHits.h.
Referenced by Exec(), and Reset().
fPitchX
Double_t PixelFindHits::fPitchX private
Definition at line 78 of file PixelFindHits.h.
Referenced by Exec(), Init(), and InitMQ().
fPitchY
Double_t PixelFindHits::fPitchY private
Definition at line 79 of file PixelFindHits.h.
Referenced by Exec(), Init(), and InitMQ().
fStreamProcessing
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
fTNofDigis
Int_t PixelFindHits::fTNofDigis private
Definition at line 72 of file PixelFindHits.h.
Referenced by Exec(), and Finish().
fTNofEvents
Int_t PixelFindHits::fTNofEvents private
Definition at line 71 of file PixelFindHits.h.
Referenced by Exec(), and Finish().
fTNofHits
Int_t PixelFindHits::fTNofHits private
Definition at line 73 of file PixelFindHits.h.
Referenced by Exec(), and Finish().
fVerbose
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
PixelFindHits.h
PixelFindHits.cxx