FairRoot: FairXMLNode Class Reference
FairXMLNode Class Reference
#include <FairXMLNode.h>
Public Member Functions
FairXMLNode (TXMLNode *node)
FairXMLNode (TString name, TString value)
void SetValue (TString value)
void SetName (TString name)
void AddChild (FairXMLNode *node)
void AddAttrib (TString name, TString value)
Bool_t IsImport () const
Bool_t IsExport () const
Bool_t IsNull () const
Int_t GetNChildren () const
Int_t GetNAttributes () const
Int_t GetNChildren (TString name) const
Int_t GetNAttributes (TString name) const
TString GetValue () const
const char * GetName ()
const char * GetTitle () const
TString GetAttribValue (TString name, Int_t count=0) const
TString GetAttribValue (Int_t index) const
TString GetAttribTitle (Int_t index) const
TList * GetChildren () const
FairXMLNode * GetChild (TString name, Int_t count=0) const
FairXMLNode * GetChild (Int_t index) const
virtual ~FairXMLNode ()
Static Public Member Functions
static FairXMLNode * NullInstance ()
Private Types
enum EXMLMode { kModeImport, kModeExport, kModeNull }
Private Member Functions
FairXMLNode ()
Private Attributes
TList * fChildren
TList * fAttrib
Int_t fNChildren
Int_t fNAttrib
TString fValue
TString fName
EXMLMode fMode
Static Private Attributes
static FairXMLNode * fgNullInstance = NULL
Detailed Description
class for representing XML node
Definition at line 54 of file FairXMLNode.h.
Member Enumeration Documentation
EXMLMode
enum FairXMLNode::EXMLMode private
Enumerator
kModeImport
kModeExport
kModeNull
Definition at line 55 of file FairXMLNode.h.
Constructor & Destructor Documentation
FairXMLNode() [1/3]
FairXMLNode::FairXMLNode () private
Definition at line 159 of file FairXMLNode.cxx.
References fAttrib, fChildren, fMode, fName, fNAttrib, fNChildren, fValue, and kModeNull.
Referenced by FairXMLNode(), and NullInstance().
FairXMLNode() [2/3]
FairXMLNode::FairXMLNode (TXMLNode * node)
fake copy constructor
Parameters
node
Definition at line 12 of file FairXMLNode.cxx.
References FairXMLNode(), fAttrib, fChildren, fMode, fName, fNAttrib, fNChildren, fValue, and kModeImport.
FairXMLNode() [3/3]
FairXMLNode::FairXMLNode (TString name, TString value)
default constructor
Parameters
name name of node
value value of node
Definition at line 49 of file FairXMLNode.cxx.
References fAttrib, fChildren, fMode, fName, fNAttrib, fNChildren, fValue, and kModeExport.
~FairXMLNode()
FairXMLNode::~FairXMLNode () virtual
Definition at line 260 of file FairXMLNode.cxx.
References fAttrib, and fChildren.
Member Function Documentation
AddAttrib()
void FairXMLNode::AddAttrib (TString name, TString value)
add attribute to node
Parameters
name attribute name
value attribute value
Definition at line 70 of file FairXMLNode.cxx.
References fAttrib, fMode, fNAttrib, GetName(), and kModeExport.
AddChild()
void FairXMLNode::AddChild (FairXMLNode * node)
add child node to this node
Parameters
node node to add
Definition at line 59 of file FairXMLNode.cxx.
References fChildren, fMode, fNChildren, and kModeExport.
GetAttribTitle()
TString FairXMLNode::GetAttribTitle (Int_t index) const
Parameters
index index of attribute
Returns
name/title of attribute
Definition at line 232 of file FairXMLNode.cxx.
References fAttrib, fMode, fNAttrib, GetName(), and kModeNull.
Referenced by GetNAttributes().
GetAttribValue() [1/2]
TString FairXMLNode::GetAttribValue (TString name, Int_t count = 0) const
Parameters
name name of attribute
count number of attribute (if more than one have given name)
Returns
value of attribute
Definition at line 203 of file FairXMLNode.cxx.
References fAttrib, fMode, fNAttrib, FairXMLAttrib::GetName(), FairXMLAttrib::GetValue(), and kModeNull.
Referenced by FairEventManager::LoadXMLDetector(), and FairEventManager::LoadXMLSettings().
GetAttribValue() [2/2]
TString FairXMLNode::GetAttribValue (Int_t index) const
Parameters
index index of attribute
Returns
attribute value
Definition at line 224 of file FairXMLNode.cxx.
References fAttrib, fMode, fNAttrib, GetValue(), and kModeNull.
GetChild() [1/2]
FairXMLNode * FairXMLNode::GetChild (TString name, Int_t count = 0) const
search for node with given name
Parameters
name name of node
count number of node (if more than one with given name exist)
Returns
node
Definition at line 107 of file FairXMLNode.cxx.
References fChildren, fMode, fNChildren, GetName(), kModeNull, and NullInstance().
Referenced by GetNChildren(), FairEventManager::LoadXMLDetector(), and FairEventManager::LoadXMLSettings().
GetChild() [2/2]
FairXMLNode * FairXMLNode::GetChild (Int_t index) const
Parameters
index child number
Returns
child at given position
Definition at line 130 of file FairXMLNode.cxx.
References fChildren, fMode, fNChildren, kModeNull, and NullInstance().
GetChildren()
TList * FairXMLNode::GetChildren () const
Returns
list of child nodes
Definition at line 97 of file FairXMLNode.cxx.
References fChildren, fMode, and kModeNull.
GetName()
const char * FairXMLNode::GetName ()
Returns
name of this node
Definition at line 189 of file FairXMLNode.cxx.
References fMode, fName, and kModeNull.
Referenced by AddAttrib(), GetAttribTitle(), GetChild(), GetNChildren(), and FairEventManager::LoadXMLSettings().
GetNAttributes() [1/2]
Int_t FairXMLNode::GetNAttributes () const
Returns
number of attributes
Definition at line 89 of file FairXMLNode.cxx.
References fMode, fNAttrib, and kModeNull.
Referenced by GetNAttributes().
GetNAttributes() [2/2]
Int_t FairXMLNode::GetNAttributes (TString name) const
search for attribute with given name
Parameters
name name of attribute
Returns
number of attribute with given name
Definition at line 251 of file FairXMLNode.cxx.
References GetAttribTitle(), and GetNAttributes().
GetNChildren() [1/2]
Int_t FairXMLNode::GetNChildren () const
Returns
number of childen nodes
Definition at line 81 of file FairXMLNode.cxx.
References fMode, fNChildren, and kModeNull.
Referenced by GetNChildren(), FairEventManager::LoadXMLDetector(), and FairEventManager::LoadXMLSettings().
GetNChildren() [2/2]
Int_t FairXMLNode::GetNChildren (TString name) const
search for child with given name
Parameters
name name of node
Returns
number of node with given name
Definition at line 240 of file FairXMLNode.cxx.
References GetChild(), GetName(), and GetNChildren().
GetTitle()
const char * FairXMLNode::GetTitle () const
Returns
name of this node
Definition at line 276 of file FairXMLNode.cxx.
References fMode, fName, and kModeNull.
GetValue()
TString FairXMLNode::GetValue () const
Returns
value of node
Definition at line 182 of file FairXMLNode.cxx.
References fMode, fValue, and kModeNull.
Referenced by GetAttribValue().
IsExport()
Bool_t FairXMLNode::IsExport () const
Returns
true if node is exported, false otherwise
Definition at line 196 of file FairXMLNode.cxx.
References fMode, and kModeNull.
IsImport()
Bool_t FairXMLNode::IsImport () const
Returns
true if node is imported, false otherwise
Definition at line 141 of file FairXMLNode.cxx.
References fMode, and kModeImport.
IsNull()
Bool_t FairXMLNode::IsNull () const
Returns
true if node is null, false otherwise
Definition at line 146 of file FairXMLNode.cxx.
References fMode, and kModeNull.
Referenced by FairEventManager::LoadXMLSettings().
NullInstance()
FairXMLNode * FairXMLNode::NullInstance () static
Returns
instance of null node
Definition at line 151 of file FairXMLNode.cxx.
References FairXMLNode(), and fgNullInstance.
Referenced by GetChild().
SetName()
void FairXMLNode::SetName (TString name)
Parameters
name new name
Definition at line 175 of file FairXMLNode.cxx.
References fMode, fName, and kModeExport.
SetValue()
void FairXMLNode::SetValue (TString value)
Parameters
value new value
Definition at line 169 of file FairXMLNode.cxx.
References fMode, fValue, and kModeExport.
Member Data Documentation
fAttrib
TList* FairXMLNode::fAttrib private
Definition at line 61 of file FairXMLNode.h.
Referenced by AddAttrib(), FairXMLNode(), GetAttribTitle(), GetAttribValue(), and ~FairXMLNode().
fChildren
TList* FairXMLNode::fChildren private
Definition at line 60 of file FairXMLNode.h.
Referenced by AddChild(), FairXMLNode(), GetChild(), GetChildren(), and ~FairXMLNode().
fgNullInstance
FairXMLNode * FairXMLNode::fgNullInstance = NULL static private
Definition at line 64 of file FairXMLNode.h.
Referenced by NullInstance().
fMode
EXMLMode FairXMLNode::fMode private
Definition at line 65 of file FairXMLNode.h.
Referenced by AddAttrib(), AddChild(), FairXMLNode(), GetAttribTitle(), GetAttribValue(), GetChild(), GetChildren(), GetName(), GetNAttributes(), GetNChildren(), GetTitle(), GetValue(), IsExport(), IsImport(), IsNull(), SetName(), and SetValue().
fName
TString FairXMLNode::fName private
Definition at line 63 of file FairXMLNode.h.
Referenced by FairXMLNode(), GetName(), GetTitle(), and SetName().
fNAttrib
Int_t FairXMLNode::fNAttrib private
Definition at line 62 of file FairXMLNode.h.
Referenced by AddAttrib(), FairXMLNode(), GetAttribTitle(), GetAttribValue(), and GetNAttributes().
fNChildren
Int_t FairXMLNode::fNChildren private
Definition at line 62 of file FairXMLNode.h.
Referenced by AddChild(), FairXMLNode(), GetChild(), and GetNChildren().
fValue
TString FairXMLNode::fValue private
Definition at line 63 of file FairXMLNode.h.
Referenced by FairXMLNode(), GetValue(), and SetValue().
The documentation for this class was generated from the following files:
FairXMLNode.h
FairXMLNode.cxx