FairRroot: FairMQParts Class Reference
FairMQParts Class Reference
FairMQParts is a lightweight convenience wrapper around a vector of unique pointers to FairMQMessage, used for sending multi-part messages.
#include <FairMQParts.h>
Public Types
using iterator = container::iterator
using const_iterator = container::const_iterator
Public Member Functions
FairMQParts ()
Default constructor.
FairMQParts (const FairMQParts &)=delete
Copy Constructor.
FairMQParts (FairMQParts &&p)=default
Move constructor.
FairMQParts & operator= (const FairMQParts &)=delete
Assignment operator.
~FairMQParts ()
Default destructor.
void AddPart (FairMQMessage *msg)
void AddPart (std::unique_ptr< FairMQMessage > &&msg)
FairMQMessage & operator[] (const int index)
std::unique_ptr< FairMQMessage > & At (const int index)
FairMQMessage & AtRef (const int index)
int Size () const
auto begin () -> decltype(fParts.begin())
auto end () -> decltype(fParts.end())
auto cbegin () -> decltype(fParts.cbegin())
auto cend () -> decltype(fParts.cend())
Public Attributes
container fParts
Private Types
using container = std::vector< std::unique_ptr< FairMQMessage >>
Detailed Description
FairMQParts is a lightweight convenience wrapper around a vector of unique pointers to FairMQMessage, used for sending multi-part messages.
Definition at line 20 of file FairMQParts.h.
Member Typedef Documentation
using FairMQParts::const_iterator = container::const_iterator
Definition at line 79 of file FairMQParts.h.
using FairMQParts::container = std::vector<std::unique_ptr<FairMQMessage>> private
Definition at line 23 of file FairMQParts.h.
using FairMQParts::iterator = container::iterator
Definition at line 78 of file FairMQParts.h.
Constructor & Destructor Documentation
FairMQParts::FairMQParts () inline
Default constructor.
Definition at line 27 of file FairMQParts.h.
FairMQParts::FairMQParts (const FairMQParts &) delete
Copy Constructor.
FairMQParts::FairMQParts (FairMQParts && p) default
Move constructor.
FairMQParts::~FairMQParts () inline
Default destructor.
Definition at line 35 of file FairMQParts.h.
Member Function Documentation
void FairMQParts::AddPart (FairMQMessage * msg) inline
Adds part (FairMQMessage) to the container
Parameters
msg message pointer (for example created with NewMessage() method of FairMQDevice)
Definition at line 39 of file FairMQParts.h.
References fParts.
Referenced by FairMQExample8Sampler::ConditionalRun(), FairMQEx9SamplerBin::ConditionalRun(), FairMQEx9Sampler::ConditionalRun(), FairMQMultiplier::HandleMultipartData(), FairMQEx9Merger::MergeData(), FairMQEx9aSamplerBin::ReadBinFile(), FairMQLmdSampler::ReadEvent(), FairMQEx9aSamplerBin::ReadRootFile(), Ex2Processor::Run(), and Ex2Sampler::Run().
void FairMQParts::AddPart (std::unique_ptr< FairMQMessage > && msg) inline
Adds part (std::unique_ptr<FairMQMessage>&) to the container (move)
Parameters
msg unique pointer to FairMQMessage lvalue ref (move not required when passing argument) Adds part (std::unique_ptr<FairMQMessage>&) to the container (move)
msg unique pointer to FairMQMessage rvalue ref (move required when passing argument)
Definition at line 55 of file FairMQParts.h.
References fParts.
std::unique_ptr<FairMQMessage>& FairMQParts::At (const int index) inline
Get reference to unique pointer to part in the container at index (with bounds check)
Parameters
index container index
Definition at line 66 of file FairMQParts.h.
References fParts.
Referenced by FairMQExample8Sampler::ConditionalRun(), FairMQExample8Sink::HandleData(), FairMQEx9Merger::MergeData(), Ex2Processor::Run(), FairMQEx9aFileSinkBin::StoreData(), FairMQEx9FileSink::StoreData(), and FairMQEx9FileSinkBin::StoreData().
FairMQMessage& FairMQParts::AtRef (const int index) inline
Definition at line 69 of file FairMQParts.h.
References fParts.
Referenced by FairMQMultiplier::HandleMultipartData(), Ex2Processor::Run(), and Ex2Sink::Run().
auto FairMQParts::begin () -> decltype(fParts.begin()) inline
Definition at line 80 of file FairMQParts.h.
auto FairMQParts::cbegin () -> decltype(fParts.cbegin()) inline
Definition at line 82 of file FairMQParts.h.
auto FairMQParts::cend () -> decltype(fParts.cend()) inline
Definition at line 83 of file FairMQParts.h.
auto FairMQParts::end () -> decltype(fParts.end()) inline
Definition at line 81 of file FairMQParts.h.
FairMQParts& FairMQParts::operator= (const FairMQParts &) delete
Assignment operator.
FairMQMessage& FairMQParts::operator[] (const int index) inline
Get reference to part in the container at index (without bounds check)
Parameters
index container index
Definition at line 62 of file FairMQParts.h.
References fParts.
int FairMQParts::Size () const inline
Get number of parts in the container
Returns
number of parts in the container
Definition at line 73 of file FairMQParts.h.
References fParts.
Referenced by FairMQExample8Sink::HandleData(), FairMQMultiplier::HandleMultipartData(), FairMQEx9Merger::MergeData(), FairMQEx9aSamplerBin::ReadBinFile(), FairMQEx9aFileSinkBin::StoreData(), FairMQEx9FileSink::StoreData(), and FairMQEx9FileSinkBin::StoreData().
Member Data Documentation
container FairMQParts::fParts
Definition at line 75 of file FairMQParts.h.
Referenced by AddPart(), At(), AtRef(), operator[](), FairMQDevice::Receive(), FairMQChannel::Receive(), FairMQDevice::ReceiveAsync(), FairMQChannel::ReceiveAsync(), FairMQDevice::Send(), FairMQChannel::Send(), FairMQDevice::SendAsync(), FairMQChannel::SendAsync(), and Size().
The documentation for this class was generated from the following file:
FairMQParts.h