FairRoot: FairGenerator Class Reference
FairGenerator Class Reference abstract
#include <FairGenerator.h>
Public Member Functions
FairGenerator ()
FairGenerator (const char *name, const char *title="FAIR Generator")
virtual ~FairGenerator ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)=0
virtual Bool_t Init ()
virtual FairGenerator * CloneGenerator () const
Protected Member Functions
FairGenerator (const FairGenerator &)
FairGenerator & operator= (const FairGenerator &)
ClassDef (FairGenerator, 1)
Detailed Description
Definition at line 34 of file FairGenerator.h.
Constructor & Destructor Documentation
FairGenerator() [1/3]
FairGenerator::FairGenerator ()
Default constructor.
Definition at line 17 of file FairGenerator.cxx.
FairGenerator() [2/3]
FairGenerator::FairGenerator (const char * name, const char * title = "FAIR Generator")
Constructor with name and title
Definition at line 24 of file FairGenerator.cxx.
~FairGenerator()
FairGenerator::~FairGenerator () virtual
Destructor.
Definition at line 36 of file FairGenerator.cxx.
FairGenerator() [3/3]
FairGenerator::FairGenerator (const FairGenerator & rhs) protected
Copy constructor
Definition at line 30 of file FairGenerator.cxx.
Member Function Documentation
ClassDef()
FairGenerator::ClassDef (FairGenerator , 1) protected
CloneGenerator()
FairGenerator * FairGenerator::CloneGenerator () const virtual
Clone this object (used in MT mode only)
Reimplemented in FairBoxGenerator, and FairIonGenerator.
Definition at line 52 of file FairGenerator.cxx.
Referenced by FairPrimaryGenerator::ClonePrimaryGenerator().
Init()
virtual Bool_t FairGenerator::Init () inline virtual
Initialize the generator if needed
Reimplemented in FairBoxGenerator, and Pythia8Generator.
Definition at line 62 of file FairGenerator.h.
Referenced by FairPrimaryGenerator::Init().
operator=()
FairGenerator & FairGenerator::operator= (const FairGenerator & rhs) protected
Assignment operator
Definition at line 40 of file FairGenerator.cxx.
ReadEvent()
virtual Bool_t FairGenerator::ReadEvent (FairPrimaryGenerator * primGen) pure virtual
Abstract method ReadEvent must be implemented by any derived class. It has to handle the generation of input tracks (reading from input file) and the handing of the tracks to the FairPrimaryGenerator. I t is called from FairMCApplication.
Parameters
pStack The stack
Returns
kTRUE if successful, kFALSE if not
Implemented in FairEvtGenGenerator, FairBoxGenerator, Pythia6Generator, FairIonGenerator, FairParticleGenerator, FairShieldGenerator, FairUrqmdGenerator, Pythia8Generator, and FairAsciiGenerator.
Referenced by FairPrimaryGenerator::GenerateEvent().
The documentation for this class was generated from the following files:
FairGenerator.h
FairGenerator.cxx