FairRoot: FairMQLmdSampler Class Reference
FairMQLmdSampler Class Reference
#include <FairMQLmdSampler.h>
Public Member Functions
FairMQLmdSampler ()
FairMQLmdSampler (const FairMQLmdSampler &)=delete
FairMQLmdSampler operator= (const FairMQLmdSampler &)=delete
virtual ~FairMQLmdSampler ()
void AddSubEvtKey (short type, short subType, short procid, short subCrate, short control, const std::string &channelName)
void AddDir (const std::string &dir)
void AddFile (const std::string &fileName)
Protected Member Functions
void InitTask ()
void Run ()
int ReadEvent ()
bool OpenNextFile (const std::string &fileName)
void Close ()
Private Types
typedef std::tuple< short, short, short, short, short > SubEvtKey
Private Attributes
int fCurrentFile
int fNEvent
int fCurrentEvent
std::vector< std::string > fFileNames
s_evt_channel * fInputChannel
s_ve10_1 * fEvent
s_bufhe * fBuffer
int * fEventData
s_ves10_1 * fSubEvent
s_filhe * fInfoHeader
bool fStop
int fMsgCounter
std::map< SubEvtKey, std::string > fSubEventChanMap
std::string fFilename
short fType
short fSubType
short fProcId
short fSubCrate
short fControl
std::string fChanName
Detailed Description
Definition at line 37 of file FairMQLmdSampler.h.
Member Typedef Documentation
SubEvtKey
typedef std::tuple<short, short, short, short, short> FairMQLmdSampler::SubEvtKey private
Definition at line 342 of file FairMQLmdSampler.h.
Constructor & Destructor Documentation
FairMQLmdSampler() [1/2]
FairMQLmdSampler::FairMQLmdSampler () inline
Definition at line 40 of file FairMQLmdSampler.h.
FairMQLmdSampler() [2/2]
FairMQLmdSampler::FairMQLmdSampler (const FairMQLmdSampler &) delete
~FairMQLmdSampler()
virtual FairMQLmdSampler::~FairMQLmdSampler () inline virtual
Definition at line 66 of file FairMQLmdSampler.h.
Member Function Documentation
AddDir()
void FairMQLmdSampler::AddDir (const std::string & dir) inline
Definition at line 81 of file FairMQLmdSampler.h.
References AddFile().
AddFile()
void FairMQLmdSampler::AddFile (const std::string & fileName) inline
Definition at line 103 of file FairMQLmdSampler.h.
References fFileNames.
Referenced by AddDir(), and InitTask().
AddSubEvtKey()
void FairMQLmdSampler::AddSubEvtKey (short type, short subType, short procid, short subCrate, short control, const std::string & channelName) inline
Definition at line 69 of file FairMQLmdSampler.h.
References fSubEventChanMap.
Referenced by InitTask().
Close()
void FairMQLmdSampler::Close () inline protected
Definition at line 322 of file FairMQLmdSampler.h.
References f_evt_get_close(), fCurrentEvent, and fInputChannel.
Referenced by ReadEvent().
InitTask()
void FairMQLmdSampler::InitTask () inline protected
Definition at line 117 of file FairMQLmdSampler.h.
References AddFile(), AddSubEvtKey(), fChanName, fControl, fCurrentEvent, fCurrentFile, fFilename, fFileNames, fNEvent, fProcId, fSubCrate, fSubType, fType, and OpenNextFile().
OpenNextFile()
bool FairMQLmdSampler::OpenNextFile (const std::string & fileName) inline protected
Definition at line 297 of file FairMQLmdSampler.h.
References f_evt_get_open(), fInfoHeader, fInputChannel, and GETEVT__FILE.
Referenced by InitTask(), and ReadEvent().
operator=()
FairMQLmdSampler FairMQLmdSampler::operator= (const FairMQLmdSampler &) delete
ReadEvent()
int FairMQLmdSampler::ReadEvent () inline protected
Definition at line 160 of file FairMQLmdSampler.h.
References Close(), f_evt_error(), f_evt_get_event(), f_evt_get_subevent(), fBuffer, fCurrentEvent, fCurrentFile, fEvent, fEventData, fFileNames, fInputChannel, fMsgCounter, fNEvent, fStop, fSubEvent, fSubEventChanMap, GETEVT__NOMORE, GETEVT__SUCCESS, s_ves10_1::h_control, s_ves10_1::h_subcrate, s_ves10_1::i_procid, s_ves10_1::i_subtype, s_ves10_1::i_type, and OpenNextFile().
Referenced by Run().
Run()
void FairMQLmdSampler::Run () inline protected
Definition at line 148 of file FairMQLmdSampler.h.
References fMsgCounter, and ReadEvent().
Member Data Documentation
fBuffer
s_bufhe* FairMQLmdSampler::fBuffer private
Definition at line 336 of file FairMQLmdSampler.h.
Referenced by ReadEvent().
fChanName
std::string FairMQLmdSampler::fChanName private
Definition at line 351 of file FairMQLmdSampler.h.
Referenced by InitTask().
fControl
short FairMQLmdSampler::fControl private
Definition at line 350 of file FairMQLmdSampler.h.
Referenced by InitTask().
fCurrentEvent
int FairMQLmdSampler::fCurrentEvent private
Definition at line 332 of file FairMQLmdSampler.h.
Referenced by Close(), InitTask(), and ReadEvent().
fCurrentFile
int FairMQLmdSampler::fCurrentFile private
Definition at line 330 of file FairMQLmdSampler.h.
Referenced by InitTask(), and ReadEvent().
fEvent
s_ve10_1* FairMQLmdSampler::fEvent private
Definition at line 335 of file FairMQLmdSampler.h.
Referenced by ReadEvent().
fEventData
int* FairMQLmdSampler::fEventData private
Definition at line 337 of file FairMQLmdSampler.h.
Referenced by ReadEvent().
fFilename
std::string FairMQLmdSampler::fFilename private
Definition at line 345 of file FairMQLmdSampler.h.
Referenced by InitTask().
fFileNames
std::vector<std::string> FairMQLmdSampler::fFileNames private
Definition at line 333 of file FairMQLmdSampler.h.
Referenced by AddFile(), InitTask(), and ReadEvent().
fInfoHeader
s_filhe* FairMQLmdSampler::fInfoHeader private
Definition at line 339 of file FairMQLmdSampler.h.
Referenced by OpenNextFile().
fInputChannel
s_evt_channel* FairMQLmdSampler::fInputChannel private
Definition at line 334 of file FairMQLmdSampler.h.
Referenced by Close(), OpenNextFile(), and ReadEvent().
fMsgCounter
int FairMQLmdSampler::fMsgCounter private
Definition at line 341 of file FairMQLmdSampler.h.
Referenced by ReadEvent(), and Run().
fNEvent
int FairMQLmdSampler::fNEvent private
Definition at line 331 of file FairMQLmdSampler.h.
Referenced by InitTask(), and ReadEvent().
fProcId
short FairMQLmdSampler::fProcId private
Definition at line 348 of file FairMQLmdSampler.h.
Referenced by InitTask().
fStop
bool FairMQLmdSampler::fStop private
Definition at line 340 of file FairMQLmdSampler.h.
Referenced by ReadEvent().
fSubCrate
short FairMQLmdSampler::fSubCrate private
Definition at line 349 of file FairMQLmdSampler.h.
Referenced by InitTask().
fSubEvent
s_ves10_1* FairMQLmdSampler::fSubEvent private
Definition at line 338 of file FairMQLmdSampler.h.
Referenced by ReadEvent().
fSubEventChanMap
std::map<SubEvtKey, std::string> FairMQLmdSampler::fSubEventChanMap private
Definition at line 343 of file FairMQLmdSampler.h.
Referenced by AddSubEvtKey(), and ReadEvent().
fSubType
short FairMQLmdSampler::fSubType private
Definition at line 347 of file FairMQLmdSampler.h.
Referenced by InitTask().
fType
short FairMQLmdSampler::fType private
Definition at line 346 of file FairMQLmdSampler.h.
Referenced by InitTask().
The documentation for this class was generated from the following file:
FairMQLmdSampler.h