FairRroot: MyHit Class Reference
MyHit Class Reference
#include <MyHit.h>
Public Member Functions
MyHit ()
MyHit (Int_t detID, Int_t mcindex, TVector3 &pos, TVector3 &dpos)
MyHit (Int_t detID, Int_t mcindex, TVector3 &pos, TVector3 &dpos, Double_t timeStamp, Double_t timeStampError)
virtual ~MyHit ()
template<class Archive >
void serialize (Archive &ar, const unsigned int)
Double_t GetDx () const
Double_t GetDy () const
Double_t GetDz () const
Int_t GetRefIndex () const
void PositionError (TVector3 &dpos) const
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetDx (Double_t dx)
void SetDy (Double_t dy)
void SetDz (Double_t dz)
void SetDxyz (Double_t dx, Double_t dy, Double_t dz)
void SetPositionError (const TVector3 &dpos)
void SetRefIndex (Int_t index)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
virtual void Print (const Option_t *) const
Double_t GetTimeStamp () const
Double_t GetTimeStampError () const
void SetTimeStamp (Double_t t)
void SetTimeStampError (Double_t t)
virtual Int_t Compare (const TObject *obj) const
virtual std::ostream & PrintTimeInfo (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
virtual bool operator< (const FairTimeStamp *rValue) const
std::set< FairLink > GetLinks () const
returns stored links as FairLinks
Int_t GetNLinks () const
returns the number of stored links
FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
FairLink GetEntryNr () const
FairMultiLinkedData * GetPointerToLinks () const
std::vector< FairLink > GetSortedMCTracks ()
void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
void SetLink (FairLink link)
Sets the Links with a single FairLink.
void SetInsertHistory (Bool_t val)
void SetEntryNr (FairLink val)
void SetPointerToLinks (FairMultiLinkedData *links)
void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
void AddInterfaceData (FairMultiLinkedData_Interface *data)
void ResetLinks ()
std::ostream & PrintLinkInfo (std::ostream &out=std::cout) const
Output.
Protected Member Functions
ClassDef (FairHit, 3)
ClassDef (FairTimeStamp, 4)
ClassDef (FairMultiLinkedData_Interface, 5)
FairMultiLinkedData * CreateFairMultiLinkedData ()
Protected Attributes
Double32_t fDx
Double32_t fDy
Double32_t fDz
Errors of position [cm].
Int_t fRefIndex
Index of FairMCPoint for this hit.
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
Double_t fTimeStamp
Double_t fTimeStampError
FairMultiLinkedData * fLink
Private Member Functions
ClassDef (MyHit, 1)
Friends
class boost::serialization::access
Detailed Description
Definition at line 28 of file MyHit.h.
Constructor & Destructor Documentation
MyHit::MyHit ()
Default constructor
Definition at line 19 of file MyHit.cxx.
MyHit::MyHit (Int_t detID, Int_t mcindex, TVector3 & pos, TVector3 & dpos)
Constructor
Definition at line 24 of file MyHit.cxx.
MyHit::MyHit (Int_t detID, Int_t mcindex, TVector3 & pos, TVector3 & dpos, Double_t timeStamp, Double_t timeStampError)
Definition at line 29 of file MyHit.cxx.
References FairTimeStamp::SetTimeStamp(), and FairTimeStamp::SetTimeStampError().
MyHit::~MyHit () virtual
Destructor
Definition at line 36 of file MyHit.cxx.
Member Function Documentation
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) inherited
Definition at line 172 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
Referenced by FairTestDetectorTimeRecoTask::Exec().
void FairMultiLinkedData_Interface::AddLink (FairLink link) inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 155 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
MyHit::ClassDef (MyHit , 1) private
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
FairTimeStamp::ClassDef (FairTimeStamp , 4) protected inherited
Error on time stamp
FairHit::ClassDef (FairHit , 3) protected inherited
virtual Int_t FairTimeStamp::Compare (const TObject * obj) const inline virtual inherited
Definition at line 48 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 59 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
virtual bool FairTimeStamp::equal (FairTimeStamp * data) inline virtual inherited
Reimplemented in FairTestDetectorDigi, and MyDigi.
Definition at line 62 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
Int_t FairHit::GetDetectorID () const inline inherited
Definition at line 47 of file FairHit.h.
References FairHit::fDetectorID.
Referenced by PixelFindTracks::Exec(), FairTutorialDet4StraightLineFitter::IsGoodEvent(), and FairTutorialDet4MilleWriter::IsGoodEvent().
Double_t FairHit::GetDx () const inline inherited
Accessors
Definition at line 42 of file FairHit.h.
References FairHit::fDx.
Referenced by FairTutorialDet4StraightLineFitter::Exec().
Double_t FairHit::GetDy () const inline inherited
Definition at line 43 of file FairHit.h.
References FairHit::fDy.
Referenced by FairTutorialDet4StraightLineFitter::Exec(), and plots().
Double_t FairHit::GetDz () const inline inherited
Definition at line 44 of file FairHit.h.
References FairHit::fDz.
FairLink FairMultiLinkedData_Interface::GetEntryNr () const inherited
Definition at line 101 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetEntryNr(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorTimeRecoTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const inherited
returns the FairLink at the given position
Definition at line 91 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const inherited
returns stored links as FairLinks
Definition at line 72 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const inherited
returns all FairLinks with the corresponding type
Definition at line 111 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Int_t FairMultiLinkedData_Interface::GetNLinks () const inherited
returns the number of stored links
Definition at line 82 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairPrintFairLinks::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::GetSortedMCTracks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::PrintLinkInfo(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
Int_t FairHit::GetRefIndex () const inline inherited
Definition at line 45 of file FairHit.h.
References FairHit::fRefIndex.
Referenced by plots().
std::vector< FairLink > FairMultiLinkedData_Interface::GetSortedMCTracks () inherited
Definition at line 121 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::GetSortedMCTracks().
Double_t FairTimeStamp::GetTimeStamp () const inline inherited
Accessors
Definition at line 43 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by StopTime::Call(), TimeGap::Call(), FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), FairRingSorterTask::Exec(), FairTSBufferFunctional::GetData(), FairTimeStampPointDraw::GetValue(), FairTimeStamp::operator<(), FairWriteoutBuffer::PrintData(), FairWriteoutBuffer::PrintStartTimeMap(), FairTimeStamp::PrintTimeInfo(), and FairTestDetectorDigi::ToString().
Double_t FairTimeStamp::GetTimeStampError () const inline inherited
Definition at line 44 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and FairTimeStamp::PrintTimeInfo().
Double_t FairHit::GetX () const inline inherited
Definition at line 48 of file FairHit.h.
References FairHit::fX.
Referenced by FairTutorialDet4StraightLineFitter::Exec(), PixelFitTracks::Exec(), PixelFindTracks::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), plots(), FairTutorialDet4MilleWriter::StraightLineShiftX(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
Double_t FairHit::GetY () const inline inherited
Definition at line 49 of file FairHit.h.
References FairHit::fY.
Referenced by FairTutorialDet4StraightLineFitter::Exec(), PixelFitTracks::Exec(), PixelFindTracks::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), plots(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
Double_t FairHit::GetZ () const inline inherited
Definition at line 50 of file FairHit.h.
References FairHit::fZ.
Referenced by FairTutorialDet4StraightLineFitter::Exec(), PixelFitTracks::Exec(), PixelFindTracks::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), plots(), FairTutorialDet4MilleWriter::StraightLineShiftX(), and FairTutorialDet4MilleWriter::StraightLineShiftXY().
virtual Bool_t FairTimeStamp::IsSortable () const inline virtual inherited
Definition at line 60 of file FairTimeStamp.h.
virtual bool FairTimeStamp::operator< (const FairTimeStamp * rValue) const inline virtual inherited
Definition at line 71 of file FairTimeStamp.h.
References FairTimeStamp::GetTimeStamp().
void FairHit::Position (TVector3 & pos) const inline inherited
Definition at line 120 of file FairHit.h.
References FairHit::fX, FairHit::fY, and FairHit::fZ.
void FairHit::PositionError (TVector3 & dpos) const inline inherited
Definition at line 99 of file FairHit.h.
References FairHit::fDx, FairHit::fDy, and FairHit::fDz.
virtual void FairHit::Print (const Option_t *) const inline virtual inherited
Definition at line 71 of file FairHit.h.
std::ostream& FairMultiLinkedData_Interface::PrintLinkInfo (std::ostream & out = std::cout) const inline inherited
Output.
Definition at line 66 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::PrintLinkInfo().
Referenced by FairTimeStamp::PrintTimeInfo().
std::ostream & FairTimeStamp::PrintTimeInfo (std::ostream & out = std::cout) const virtual inherited
Definition at line 12 of file FairTimeStamp.cxx.
References FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), and FairMultiLinkedData_Interface::PrintLinkInfo().
void FairMultiLinkedData_Interface::ResetLinks () inherited
Definition at line 193 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
template<class Archive > void MyHit::serialize (Archive & ar, const unsigned int) inline
Definition at line 42 of file MyHit.h.
void FairHit::SetDetectorID (Int_t detID) inline inherited
Definition at line 62 of file FairHit.h.
References FairHit::fDetectorID.
void FairHit::SetDx (Double_t dx) inline inherited
Modifiers
Definition at line 56 of file FairHit.h.
References FairHit::fDx.
void FairHit::SetDxyz (Double_t dx, Double_t dy, Double_t dz) inline inherited
Definition at line 105 of file FairHit.h.
References FairHit::fDx, FairHit::fDy, and FairHit::fDz.
void FairHit::SetDy (Double_t dy) inline inherited
Definition at line 57 of file FairHit.h.
References FairHit::fDy.
void FairHit::SetDz (Double_t dz) inline inherited
Definition at line 58 of file FairHit.h.
References FairHit::fDz.
void FairMultiLinkedData_Interface::SetEntryNr (FairLink val) inherited
Definition at line 147 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetEntryNr().
Referenced by FairRingSorterTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) inherited
Definition at line 186 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
void FairMultiLinkedData_Interface::SetLink (FairLink link) inherited
Sets the Links with a single FairLink.
Definition at line 139 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetector::AddHit(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 131 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline inherited
Definition at line 55 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
void FairHit::SetPosition (const TVector3 & pos) inline inherited
Definition at line 134 of file FairHit.h.
References FairHit::fX, FairHit::fY, and FairHit::fZ.
void FairHit::SetPositionError (const TVector3 & dpos) inline inherited
Definition at line 113 of file FairHit.h.
References FairHit::fDx, FairHit::fDy, and FairHit::fDz.
void FairHit::SetRefIndex (Int_t index) inline inherited
Definition at line 61 of file FairHit.h.
References FairHit::fRefIndex.
void FairTimeStamp::SetTimeStamp (Double_t t) inline inherited
Modifiers
Definition at line 46 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and MyHit().
void FairTimeStamp::SetTimeStampError (Double_t t) inline inherited
Definition at line 47 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and MyHit().
void FairHit::SetX (Double_t x) inline inherited
Definition at line 63 of file FairHit.h.
References FairHit::fX.
void FairHit::SetXYZ (Double_t x, Double_t y, Double_t z) inline inherited
Definition at line 126 of file FairHit.h.
References FairHit::fX, FairHit::fY, and FairHit::fZ.
void FairHit::SetY (Double_t y) inline inherited
Definition at line 64 of file FairHit.h.
References FairHit::fY.
void FairHit::SetZ (Double_t z) inline inherited
Definition at line 65 of file FairHit.h.
References FairHit::fZ.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 48 of file MyHit.h.
Member Data Documentation
Int_t FairHit::fDetectorID protected inherited
Detector unique identifier.
Definition at line 92 of file FairHit.h.
Referenced by FairHit::GetDetectorID(), FairHit::serialize(), and FairHit::SetDetectorID().
Double32_t FairHit::fDx protected inherited
Definition at line 90 of file FairHit.h.
Referenced by FairHit::GetDx(), FairHit::PositionError(), FairHit::serialize(), FairHit::SetDx(), FairHit::SetDxyz(), and FairHit::SetPositionError().
Double32_t FairHit::fDy protected inherited
Definition at line 90 of file FairHit.h.
Referenced by FairHit::GetDy(), FairHit::PositionError(), FairHit::serialize(), FairHit::SetDxyz(), FairHit::SetDy(), and FairHit::SetPositionError().
Double32_t FairHit::fDz protected inherited
Errors of position [cm].
Definition at line 90 of file FairHit.h.
Referenced by FairHit::GetDz(), FairHit::PositionError(), FairHit::serialize(), FairHit::SetDxyz(), FairHit::SetDz(), and FairHit::SetPositionError().
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
Int_t FairHit::fRefIndex protected inherited
Index of FairMCPoint for this hit.
Definition at line 91 of file FairHit.h.
Referenced by FairHit::GetRefIndex(), FairHit::serialize(), and FairHit::SetRefIndex().
Double_t FairTimeStamp::fTimeStamp protected inherited
Definition at line 89 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStamp(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStamp().
Double_t FairTimeStamp::fTimeStampError protected inherited
Time of digit or Hit [ns]
Definition at line 90 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStampError(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStampError().
Double32_t FairHit::fX protected inherited
Definition at line 93 of file FairHit.h.
Referenced by FairHit::GetX(), FairHit::Position(), FairHit::serialize(), FairHit::SetPosition(), FairHit::SetX(), and FairHit::SetXYZ().
Double32_t FairHit::fY protected inherited
Definition at line 93 of file FairHit.h.
Referenced by FairHit::GetY(), FairHit::Position(), FairHit::serialize(), FairHit::SetPosition(), FairHit::SetXYZ(), and FairHit::SetY().
Double32_t FairHit::fZ protected inherited
Position of hit [cm].
Definition at line 93 of file FairHit.h.
Referenced by FairHit::GetZ(), FairHit::Position(), FairHit::serialize(), FairHit::SetPosition(), FairHit::SetXYZ(), and FairHit::SetZ().
The documentation for this class was generated from the following files:
MyHit.h
MyHit.cxx