FairRroot: PixelFindHitsTask Class Reference
PixelFindHitsTask Class Reference
#include <PixelFindHitsTask.h>
Public Member Functions
PixelFindHitsTask ()
virtual ~PixelFindHitsTask ()
void Exec (TClonesArray *digis, TClonesArray *hits)
void Exec (TList *list, TClonesArray *hits)
void Init (PixelDigiPar *digipar, FairGeoParSet *geopar)
Private Member Functions
void Reset (TClonesArray *hits)
virtual void Finish ()
PixelFindHitsTask (const PixelFindHitsTask &)
PixelFindHitsTask & operator= (const PixelFindHitsTask &)
Private Attributes
FairGeoParSet * fGeoParSet
Int_t fNDigis
Int_t fNHits
Int_t fTNofEvents
Int_t fTNofDigis
Int_t fTNofHits
Int_t fFeCols
Int_t fFeRows
Int_t fMaxFEperCol
Double_t fPitchX
Double_t fPitchY
Detailed Description
Definition at line 31 of file PixelFindHitsTask.h.
Constructor & Destructor Documentation
PixelFindHitsTask::PixelFindHitsTask ()
Default constructor
Definition at line 52 of file PixelFindHitsTask.cxx.
PixelFindHitsTask::~PixelFindHitsTask () virtual
Destructor
Definition at line 72 of file PixelFindHitsTask.cxx.
PixelFindHitsTask::PixelFindHitsTask (const PixelFindHitsTask &) private
Member Function Documentation
void PixelFindHitsTask::Exec (TClonesArray * digis, TClonesArray * hits)
Definition at line 125 of file PixelFindHitsTask.cxx.
References fFeCols, fFeRows, fGeoParSet, fMaxFEperCol, fNDigis, fNHits, fPitchX, fPitchY, fTNofDigis, fTNofEvents, fTNofHits, PixelDigi::GetCol(), PixelDigi::GetDetectorID(), PixelDigi::GetFeID(), FairGeoParSet::GetGeometry(), PixelDigi::GetIndex(), PixelDigi::GetRow(), LOG, and Reset().
void PixelFindHitsTask::Exec (TList * list, TClonesArray * hits)
Definition at line 187 of file PixelFindHitsTask.cxx.
References fFeCols, fFeRows, fGeoParSet, fMaxFEperCol, fNDigis, fNHits, fPitchX, fPitchY, fTNofDigis, fTNofEvents, fTNofHits, PixelDigi::GetCol(), PixelDigi::GetDetectorID(), PixelDigi::GetFeID(), FairGeoParSet::GetGeometry(), PixelDigi::GetIndex(), PixelDigi::GetRow(), LOG, and Reset().
void PixelFindHitsTask::Finish () private virtual
Finish at the end of each event
Definition at line 88 of file PixelFindHitsTask.cxx.
References fTNofDigis, fTNofEvents, fTNofHits, and LOG.
void PixelFindHitsTask::Init (PixelDigiPar * digipar, FairGeoParSet * geopar)
Definition at line 102 of file PixelFindHitsTask.cxx.
References fFeCols, fFeRows, fGeoParSet, fMaxFEperCol, fPitchX, fPitchY, PixelDigiPar::GetFECols(), PixelDigiPar::GetFERows(), PixelDigiPar::GetMaxFEperCol(), PixelDigiPar::GetXPitch(), PixelDigiPar::GetYPitch(), LOG, and FairParGenericSet::printParams().
PixelFindHitsTask& PixelFindHitsTask::operator= (const PixelFindHitsTask &) private
void PixelFindHitsTask::Reset (TClonesArray * hits) private
Reset eventwise counters
Definition at line 80 of file PixelFindHitsTask.cxx.
References fNDigis, and fNHits.
Referenced by Exec().
Member Data Documentation
Int_t PixelFindHitsTask::fFeCols private
Definition at line 58 of file PixelFindHitsTask.h.
Referenced by Exec(), and Init().
Int_t PixelFindHitsTask::fFeRows private
Definition at line 59 of file PixelFindHitsTask.h.
Referenced by Exec(), and Init().
FairGeoParSet* PixelFindHitsTask::fGeoParSet private
Definition at line 49 of file PixelFindHitsTask.h.
Referenced by Exec(), and Init().
Int_t PixelFindHitsTask::fMaxFEperCol private
Definition at line 60 of file PixelFindHitsTask.h.
Referenced by Exec(), and Init().
Int_t PixelFindHitsTask::fNDigis private
Definition at line 51 of file PixelFindHitsTask.h.
Referenced by Exec(), and Reset().
Int_t PixelFindHitsTask::fNHits private
Definition at line 52 of file PixelFindHitsTask.h.
Referenced by Exec(), and Reset().
Double_t PixelFindHitsTask::fPitchX private
Definition at line 61 of file PixelFindHitsTask.h.
Referenced by Exec(), and Init().
Double_t PixelFindHitsTask::fPitchY private
Definition at line 62 of file PixelFindHitsTask.h.
Referenced by Exec(), and Init().
Int_t PixelFindHitsTask::fTNofDigis private
Definition at line 55 of file PixelFindHitsTask.h.
Referenced by Exec(), and Finish().
Int_t PixelFindHitsTask::fTNofEvents private
Definition at line 54 of file PixelFindHitsTask.h.
Referenced by Exec(), and Finish().
Int_t PixelFindHitsTask::fTNofHits private
Definition at line 56 of file PixelFindHitsTask.h.
Referenced by Exec(), and Finish().
The documentation for this class was generated from the following files:
PixelFindHitsTask.h
PixelFindHitsTask.cxx