FairRroot: FairMQTransportFactory Class Reference
FairMQTransportFactory Class Reference abstract
#include <FairMQTransportFactory.h>
Public Member Functions
FairMQTransportFactory (const std::string &id)
auto GetId () const -> const std::string
virtual FairMQMessagePtr CreateMessage () const =0
Create empty FairMQMessage.
virtual FairMQMessagePtr CreateMessage (const size_t size) const =0
Create new FairMQMessage of specified size.
virtual FairMQMessagePtr CreateMessage (void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr) const =0
Create new FairMQMessage with user provided buffer and size.
virtual FairMQMessagePtr CreateMessage (FairMQUnmanagedRegionPtr &unmanagedRegion, void *data, const size_t size, void *hint=0) const =0
virtual FairMQSocketPtr CreateSocket (const std::string &type, const std::string &name) const =0
Create a socket.
virtual FairMQPollerPtr CreatePoller (const std::vector< FairMQChannel > &channels) const =0
Create a poller for a single channel (all subchannels)
virtual FairMQPollerPtr CreatePoller (const std::vector< const FairMQChannel * > &channels) const =0
Create a poller for specific channels.
virtual FairMQPollerPtr CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> &channelsMap, const std::vector< std::string > &channelList) const =0
Create a poller for specific channels (all subchannels)
virtual FairMQPollerPtr CreatePoller (const FairMQSocket &cmdSocket, const FairMQSocket &dataSocket) const =0
Create a poller for two sockets.
virtual FairMQUnmanagedRegionPtr CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback=nullptr) const =0
virtual FairMQ::Transport GetType () const =0
Get transport type.
virtual void Interrupt ()=0
virtual void Resume ()=0
virtual ~FairMQTransportFactory ()
template<typename T >
FairMQMessagePtr NewSimpleMessage (const T &data) const
template<std::size_t N>
FairMQMessagePtr NewSimpleMessage (const char(&data)[N]) const
FairMQMessagePtr NewSimpleMessage (const std::string &str) const
template<typename T >
FairMQMessagePtr NewStaticMessage (const T &data) const
FairMQMessagePtr NewStaticMessage (const std::string &str) const
Static Public Member Functions
static auto CreateTransportFactory (const std::string &type, const std::string &id="", const FairMQProgOptions *config=nullptr) -> std::shared_ptr< FairMQTransportFactory >
static void FairMQNoCleanup (void *, void *)
template<typename T >
static void FairMQSimpleMsgCleanup (void *, void *obj)
Private Attributes
const std::string fkId
Topology wide unique id.
Detailed Description
Definition at line 27 of file FairMQTransportFactory.h.
Constructor & Destructor Documentation
FairMQTransportFactory::FairMQTransportFactory (const std::string & id)
ctor
Parameters
id Topology wide unique id, usually the device id.
Definition at line 25 of file FairMQTransportFactory.cxx.
virtual FairMQTransportFactory::~FairMQTransportFactory () inline virtual
Definition at line 77 of file FairMQTransportFactory.h.
Member Function Documentation
virtual FairMQMessagePtr FairMQTransportFactory::CreateMessage () const pure virtual
Create empty FairMQMessage.
Returns
pointer to FairMQMessage
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
Referenced by NewSimpleMessage(), and NewStaticMessage().
virtual FairMQMessagePtr FairMQTransportFactory::CreateMessage (const size_t size) const pure virtual
Create new FairMQMessage of specified size.
Parameters
size message size
Returns
pointer to FairMQMessage
Implemented in FairMQTransportFactoryZMQ, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual FairMQMessagePtr FairMQTransportFactory::CreateMessage (void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr) const pure virtual
Create new FairMQMessage with user provided buffer and size.
Parameters
data pointer to user provided buffer
size size of the user provided buffer
ffn callback, called when the message is transfered (and can be deleted)
obj optional helper pointer that can be used in the callback
Returns
pointer to FairMQMessage
Implemented in FairMQTransportFactoryZMQ, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual FairMQMessagePtr FairMQTransportFactory::CreateMessage (FairMQUnmanagedRegionPtr & unmanagedRegion, void * data, const size_t size, void * hint = 0) const pure virtual
Implemented in FairMQTransportFactoryZMQ, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual FairMQPollerPtr FairMQTransportFactory::CreatePoller (const std::vector< FairMQChannel > & channels) const pure virtual
Create a poller for a single channel (all subchannels)
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
Referenced by FairMQDevice::PollForTransport().
virtual FairMQPollerPtr FairMQTransportFactory::CreatePoller (const std::vector< const FairMQChannel * > & channels) const pure virtual
Create a poller for specific channels.
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual FairMQPollerPtr FairMQTransportFactory::CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> & channelsMap, const std::vector< std::string > & channelList) const pure virtual
Create a poller for specific channels (all subchannels)
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual FairMQPollerPtr FairMQTransportFactory::CreatePoller (const FairMQSocket & cmdSocket, const FairMQSocket & dataSocket) const pure virtual
Create a poller for two sockets.
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual FairMQSocketPtr FairMQTransportFactory::CreateSocket (const std::string & type, const std::string & name) const pure virtual
Create a socket.
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
auto FairMQTransportFactory::CreateTransportFactory (const std::string & type, const std::string & id = "", const FairMQProgOptions * config = nullptr) -> std::shared_ptr<FairMQTransportFactory> static
Definition at line 30 of file FairMQTransportFactory.cxx.
References LOG, and fair::mq::tools::Uuid().
Referenced by FairMQDevice::AddTransport().
virtual FairMQUnmanagedRegionPtr FairMQTransportFactory::CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback = nullptr) const pure virtual
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
static void FairMQTransportFactory::FairMQNoCleanup (void * , void *) inline static
Definition at line 81 of file FairMQTransportFactory.h.
Referenced by NewStaticMessage().
template<typename T > static void FairMQTransportFactory::FairMQSimpleMsgCleanup (void * , void * obj) inline static
Definition at line 86 of file FairMQTransportFactory.h.
auto FairMQTransportFactory::GetId () const -> const std::string inline
Definition at line 38 of file FairMQTransportFactory.h.
References fkId.
Referenced by FairMQTransportFactoryNN::CreateSocket(), FairMQTransportFactorySHM::CreateSocket(), and FairMQTransportFactoryZMQ::CreateSocket().
virtual FairMQ::Transport FairMQTransportFactory::GetType () const pure virtual
Get transport type.
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual void FairMQTransportFactory::Interrupt () pure virtual
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const T & data) const inline
Definition at line 92 of file FairMQTransportFactory.h.
References CreateMessage().
template<std::size_t N> FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const char(&) data[N]) const inline
Definition at line 101 of file FairMQTransportFactory.h.
References CreateMessage().
FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const std::string & str) const inline
Definition at line 107 of file FairMQTransportFactory.h.
References CreateMessage().
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const T & data) const inline
Definition at line 115 of file FairMQTransportFactory.h.
References CreateMessage(), and FairMQNoCleanup().
FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const std::string & str) const inline
Definition at line 120 of file FairMQTransportFactory.h.
References CreateMessage(), and FairMQNoCleanup().
virtual void FairMQTransportFactory::Resume () pure virtual
Implemented in FairMQTransportFactoryZMQ, fair::mq::ofi::TransportFactory, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
Member Data Documentation
const std::string FairMQTransportFactory::fkId private
Topology wide unique id.
Definition at line 31 of file FairMQTransportFactory.h.
Referenced by GetId().
The documentation for this class was generated from the following files:
FairMQTransportFactory.h
FairMQTransportFactory.cxx