FairRroot: NewDetector Class Reference
NewDetector Class Reference
#include <NewDetector.h>
Public Member Functions
NewDetector (const char *Name, Bool_t Active)
NewDetector ()
virtual ~NewDetector ()
virtual void Initialize ()
virtual Bool_t ProcessHits (FairVolume *v=0)
virtual void Register ()
virtual TClonesArray * GetCollection (Int_t iColl) const
virtual void Reset ()
void ConstructGeometry ()
NewDetectorPoint * AddHit (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t time, Double_t length, Double_t eLoss)
virtual void SetSpecialPhysicsCuts ()
virtual void EndOfEvent ()
virtual void FinishPrimary ()
virtual void FinishRun ()
virtual void BeginPrimary ()
virtual void PostTrack ()
virtual void PreTrack ()
virtual void BeginEvent ()
NewDetector (const char *Name, Bool_t Active)
NewDetector ()
virtual ~NewDetector ()
virtual void Initialize ()
virtual Bool_t ProcessHits (FairVolume *v=0)
virtual void Register ()
virtual TClonesArray * GetCollection (Int_t iColl) const
virtual void Reset ()
void ConstructGeometry ()
NewDetectorPoint * AddHit (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t time, Double_t length, Double_t eLoss)
virtual void SetSpecialPhysicsCuts ()
virtual void EndOfEvent ()
virtual void FinishPrimary ()
virtual void FinishRun ()
virtual void BeginPrimary ()
virtual void PostTrack ()
virtual void PreTrack ()
virtual void BeginEvent ()
virtual void CopyClones (TClonesArray *, TClonesArray *, Int_t)
virtual void FinishEvent ()
void SaveGeoParams ()
Int_t GetDetId ()
virtual void Print (Option_t *) const
virtual void SetGeometryFileName (TString fname, TString geoVer="0")
virtual TString GetGeometryFileName ()
virtual TString GetGeometryFileVer ()
virtual void ConstructOpGeometry ()
virtual void ConstructRootGeometry (TGeoMatrix *shiftM=NULL)
virtual void ConstructASCIIGeometry ()
template<class T , class U >
void ConstructASCIIGeometry (T dataType1, TString containerName="", U datatype2=NULL)
virtual void ModifyGeometry ()
virtual void ConstructGDMLGeometry (TGeoMatrix *)
virtual FairModule * CloneModule () const
virtual void BeginWorkerRun () const
virtual void FinishWorkerRun () const
virtual Bool_t CheckIfSensitive (std::string name)
virtual void ExpandNode (TGeoNode *Node)
virtual void ExpandNodeForGDML (TGeoNode *)
virtual Int_t getVolId (const TString &) const
Int_t GetModId ()
void SetVerboseLevel (Int_t level)
Bool_t IsActive ()
void SetModId (Int_t id)
void SetMotherVolume (TString volName)
void ProcessNodes (TList *aList)
virtual void SetParContainers ()
virtual void InitParContainers ()
TList * GetListOfGeoPar ()
FairVolume * getFairVolume (FairGeoNode *fNode)
void AddSensitiveVolume (TGeoVolume *v)
Public Attributes
TString fMotherVolumeName
Static Public Attributes
static thread_local FairVolumeList * vList =0
static thread_local Int_t fNbOfVolumes =0
static thread_local TRefArray * svList =0
static thread_local TArrayI * volNumber =0
Protected Member Functions
virtual void DefineSensitiveVolumes ()
Protected Attributes
Int_t fDetId
FairLogger * fLogger
TString fgeoVer
TString fgeoName
Int_t fModId
Bool_t fActive
Int_t fNbOfSensitiveVol
Int_t fVerboseLevel
TList * flGeoPar
Bool_t fGeoSaved
list of Detector Geometry parameters
TVirtualMC * fMC
flag for initialisation
Private Member Functions
NewDetector (const NewDetector &)
NewDetector & operator= (const NewDetector &)
NewDetector (const NewDetector &)
NewDetector & operator= (const NewDetector &)
Private Attributes
Int_t fTrackID
Int_t fVolumeID
track index
TLorentzVector fPos
volume id
TLorentzVector fMom
position at entrance
Double32_t fTime
momentum at entrance
Double32_t fLength
time
Double32_t fELoss
length
TClonesArray * fNewDetectorPointCollection
energy loss
Detailed Description
Definition at line 20 of file NewDetector/NewDetector.h.
Constructor & Destructor Documentation
NewDetector::NewDetector (const char * Name, Bool_t Active)
Name : Detector Name Active: kTRUE for active detectors (ProcessHits() will be called) kFALSE for inactive detectors
Definition at line 49 of file NewDetector/NewDetector.cxx.
NewDetector::NewDetector ()
default constructor
Definition at line 36 of file NewDetector/NewDetector.cxx.
NewDetector::~NewDetector () virtual
destructor
Definition at line 62 of file NewDetector/NewDetector.cxx.
References fNewDetectorPointCollection.
NewDetector::NewDetector (const NewDetector &) private
NewDetector::NewDetector (const char * Name, Bool_t Active)
Name : Detector Name Active: kTRUE for active detectors (ProcessHits() will be called) kFALSE for inactive detectors
NewDetector::NewDetector ()
default constructor
virtual NewDetector::~NewDetector () virtual
destructor
NewDetector::NewDetector (const NewDetector &) private
Member Function Documentation
NewDetectorPoint * NewDetector::AddHit (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t time, Double_t length, Double_t eLoss)
This method is an example of how to add your own point of type NewDetectorPoint to the clones array
Definition at line 188 of file NewDetector/NewDetector.cxx.
References fNewDetectorPointCollection.
Referenced by ProcessHits().
NewDetectorPoint* NewDetector::AddHit (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t time, Double_t length, Double_t eLoss)
This method is an example of how to add your own point of type NewDetectorPoint to the clones array
void FairModule::AddSensitiveVolume (TGeoVolume * v) inherited
Definition at line 297 of file FairModule.cxx.
References FairVolumeList::addVolume(), FairVolumeList::findObject(), FairModule::fModId, FairModule::fNbOfSensitiveVol, FairModule::fNbOfVolumes, LOG, FairVolume::setModId(), FairVolume::SetModule(), FairModule::svList, and FairModule::vList.
Referenced by FairDetector::DefineSensitiveVolumes(), and FairModule::ExpandNode().
virtual void NewDetector::BeginEvent () inline virtual
Reimplemented from FairDetector.
Definition at line 78 of file NewDetector/NewDetector.h.
virtual void NewDetector::BeginEvent () inline virtual
Reimplemented from FairDetector.
Definition at line 78 of file project_template/NewDetector/NewDetector.h.
virtual void NewDetector::BeginPrimary () inline virtual
Reimplemented from FairDetector.
Definition at line 75 of file project_template/NewDetector/NewDetector.h.
virtual void NewDetector::BeginPrimary () inline virtual
Reimplemented from FairDetector.
Definition at line 75 of file NewDetector/NewDetector.h.
virtual void FairModule::BeginWorkerRun () const inline virtual inherited
Init worker run (used in MT mode only)
Definition at line 82 of file FairModule.h.
Bool_t FairModule::CheckIfSensitive (std::string name) virtual inherited
Set the sensitivity flag for volumes, called from ConstructASCIIRootGeometry(), and has to be implimented for detectors which use ConstructASCIIRootGeometry() to build the geometry
Reimplemented in FairTutorialDet4, and FairMagnet.
Definition at line 562 of file FairModule.cxx.
References LOG.
Referenced by FairDetector::DefineSensitiveVolumes(), and FairModule::ExpandNode().
FairModule * FairModule::CloneModule () const virtual inherited
Clone this object (used in MT mode only)
Reimplemented in FairTutorialDet4, FairRutherford, FairTutorialDet1, FairTutorialDet2, FairMagnet, FairPipe, FairCave, and FairTarget.
Definition at line 693 of file FairModule.cxx.
void FairModule::ConstructASCIIGeometry () virtual inherited
construct geometry from standard ASSCII files (Hades Format)
Reimplemented in FairTutorialDet4, and FairMagnet.
Definition at line 556 of file FairModule.cxx.
References LOG.
template<class T , class U > void FairModule::ConstructASCIIGeometry (T dataType1, TString containerName = "", U datatype2 = NULL) inherited
template function to construct geometry. to be used in derived classes.
Definition at line 158 of file FairModule.h.
References FairGeoInterface::addGeoModule(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairModule::GetGeometryFileName(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairGeoLoader::Instance(), FairRun::Instance(), FairGeoNode::isSensitive(), LOG, par, FairModule::ProcessNodes(), FairGeoInterface::readSet(), and rtdb.
void FairModule::ConstructGDMLGeometry (TGeoMatrix * posrot) virtual inherited
construct geometry from GDML files
Definition at line 504 of file FairModule.cxx.
References gLogger, and MESSAGE_ORIGIN.
void NewDetector::ConstructGeometry () virtual
Create the detector geometry
Reimplemented from FairModule.
void NewDetector::ConstructGeometry () virtual
Create the detector geometry
If you are using the standard ASCII input for the geometry just copy this and use it for your detector, otherwise you can implement here you own way of constructing the geometry.
Reimplemented from FairModule.
Definition at line 147 of file NewDetector/NewDetector.cxx.
References FairGeoInterface::addGeoModule(), FairGeoSet::create(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairModule::GetGeometryFileName(), NewDetectorGeoPar::GetGeoPassiveNodes(), NewDetectorGeoPar::GetGeoSensitiveNodes(), FairGeoSet::getListOfVolumes(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairGeoLoader::Instance(), FairRun::Instance(), FairGeoNode::isSensitive(), par, FairModule::ProcessNodes(), FairGeoInterface::readSet(), rtdb, FairParSet::setChanged(), FairGeoSet::setGeomFile(), and FairParSet::setInputVersion().
void FairModule::ConstructOpGeometry () virtual inherited
method called from the MC application to set optical geometry properties
Definition at line 68 of file FairModule.cxx.
References LOG.
Referenced by FairMCApplication::ConstructOpGeometry().
void FairModule::ConstructRootGeometry (TGeoMatrix * shiftM = NULL) virtual inherited
construct geometry from root files (TGeo)
Construct the detector geometry from ROOT files, possible inputs are:
A TGeoVolume as a mother (master) volume containing the detector geometry
A TGeoManager with the detector geometry
A TGeoVolume as a mother or Master volume which is the output of the CAD2ROOT geometry, in this case the materials are not proprely defined and had to be reset In all cases we have to check that the material properties are the same or is the materials defined in the current simulation session
loop inside the delivered root file and try to fine a TGeoManager object the first TGeoManager found will be read
in case a TGeoManager was found get the top most volume and the node
The file does not contain any TGeoManager, so we assume to have a file with a TGeoVolume try to look for a TGeoVolume inside the file
Everything is OK, we have a TGeoVolume and now we add it to the simulation TGeoManager
Force rebuilding of voxels
To avoid having different names of the default matrices because we could have get the volume from another TGeoManager, we reset the default matrix name
Now we can remove the matrix so that the new geomanager will rebuild it properly
Now we can add the node to the existing cave
correction from O. Merle: in case of a TGeoVolume (v1) set the material properly
now go through the herachy and set the materials properly, this is important becase the CAD converter produce TGeoVolumes with materials that have only names and no properties
Definition at line 332 of file FairModule.cxx.
References FairModule::AssignMediumAtImport(), FairModule::ExpandNode(), FairModule::fMotherVolumeName, FairModule::GetGeometryFileName(), LOG, and FairModule::SetDefaultMatrixName().
Referenced by FairMagnet::ConstructGeometry(), and FairTutorialDet4::ConstructGeometry().
virtual void FairDetector::CopyClones (TClonesArray * , TClonesArray * , Int_t) inline virtual inherited
Definition at line 72 of file FairDetector.h.
void FairDetector::DefineSensitiveVolumes () protected virtual inherited
Definition at line 87 of file FairDetector.cxx.
References FairModule::AddSensitiveVolume(), FairModule::CheckIfSensitive(), and LOG.
Referenced by FairDetector::Initialize().
void NewDetector::EndOfEvent () virtual
this is called at the end of an event
Reimplemented from FairDetector.
Definition at line 112 of file NewDetector/NewDetector.cxx.
References fNewDetectorPointCollection.
virtual void NewDetector::EndOfEvent () virtual
this is called at the end of an event
Reimplemented from FairDetector.
void FairModule::ExpandNode (TGeoNode * Node) virtual inherited
called from ConstructRootGeometry()
Definition at line 569 of file FairModule.cxx.
References FairModule::AddSensitiveVolume(), FairModule::AssignMediumAtImport(), FairModule::CheckIfSensitive(), LOG, and FairModule::SetDefaultMatrixName().
Referenced by FairModule::ConstructRootGeometry().
void FairModule::ExpandNodeForGDML (TGeoNode * curNode) virtual inherited
called from ConstructGDMLGeometry()
Definition at line 512 of file FairModule.cxx.
virtual void FairDetector::FinishEvent () inline virtual inherited
Definition at line 94 of file FairDetector.h.
virtual void NewDetector::FinishPrimary () inline virtual
Reimplemented from FairDetector.
Definition at line 73 of file project_template/NewDetector/NewDetector.h.
virtual void NewDetector::FinishPrimary () inline virtual
Reimplemented from FairDetector.
Definition at line 73 of file NewDetector/NewDetector.h.
virtual void NewDetector::FinishRun () inline virtual
Reimplemented from FairDetector.
Definition at line 74 of file NewDetector/NewDetector.h.
virtual void NewDetector::FinishRun () inline virtual
Reimplemented from FairDetector.
Definition at line 74 of file project_template/NewDetector/NewDetector.h.
virtual void FairModule::FinishWorkerRun () const inline virtual inherited
Finish worker run (used in MT mode only)
Definition at line 84 of file FairModule.h.
virtual TClonesArray* NewDetector::GetCollection (Int_t iColl) const virtual
Gets the produced collections
Implements FairDetector.
TClonesArray * NewDetector::GetCollection (Int_t iColl) const virtual
Gets the produced collections
Implements FairDetector.
Definition at line 136 of file NewDetector/NewDetector.cxx.
References fNewDetectorPointCollection.
Int_t FairDetector::GetDetId () inline inherited
Definition at line 101 of file FairDetector.h.
References FairDetector::fDetId.
FairVolume * FairModule::getFairVolume (FairGeoNode * fNode) inherited
Definition at line 317 of file FairModule.cxx.
References FairVolumeList::At(), FairVolumeList::getEntries(), FairVolume::getGeoNode(), and FairModule::vList.
virtual TString FairModule::GetGeometryFileName () inline virtual inherited
Get the Geometry file name
Definition at line 64 of file FairModule.h.
References FairModule::fgeoName.
Referenced by FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairMagnet::ConstructGeometry(), ConstructGeometry(), FairTestDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet4::ConstructGeometry(), FairModule::ConstructRootGeometry(), and FairTutorialDet4::Initialize().
virtual TString FairModule::GetGeometryFileVer () inline virtual inherited
Get the geometry file version if used
Definition at line 66 of file FairModule.h.
References FairModule::fgeoVer.
TList* FairModule::GetListOfGeoPar () inline inherited
return the geo parameter of this detector/module
Definition at line 119 of file FairModule.h.
References FairModule::flGeoPar.
Int_t FairModule::GetModId () inline inherited
return the detector/Module id (which was set in the sim macro for the detector)
Definition at line 100 of file FairModule.h.
References FairModule::fModId.
Referenced by FairMCApplication::ConstructGeometry(), and FairDetector::Initialize().
virtual Int_t FairModule::getVolId (const TString &) const inline virtual inherited
return the MC id of a volume named vname
Definition at line 98 of file FairModule.h.
virtual void NewDetector::Initialize () virtual
Initialization of the detector is done here
Reimplemented from FairDetector.
void NewDetector::Initialize () virtual
Initialization of the detector is done here
Reimplemented from FairDetector.
Definition at line 70 of file NewDetector/NewDetector.cxx.
References FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), FairDetector::Initialize(), FairRun::Instance(), par, and rtdb.
virtual void FairModule::InitParContainers () inline virtual inherited
Initialize everything which has to be done before the construction and modification of the geometry. Mostly this is needed to read data from the parameter containers.
Reimplemented in FairTutorialDet4.
Definition at line 117 of file FairModule.h.
Referenced by FairMCApplication::ConstructGeometry().
Bool_t FairModule::IsActive () inline inherited
return the detector status
Definition at line 104 of file FairModule.h.
References FairModule::fActive.
Referenced by FairMCApplication::FairMCApplication(), and FairMCApplication::operator=().
virtual void FairModule::ModifyGeometry () inline virtual inherited
Modify the geometry for the simulation run using methods of the Root geometry package
Reimplemented in FairTutorialDet4, and Pixel.
Definition at line 76 of file FairModule.h.
Referenced by FairMCApplication::ConstructGeometry().
NewDetector& NewDetector::operator= (const NewDetector &) private
NewDetector& NewDetector::operator= (const NewDetector &) private
virtual void NewDetector::PostTrack () inline virtual
Reimplemented from FairDetector.
Definition at line 76 of file NewDetector/NewDetector.h.
virtual void NewDetector::PostTrack () inline virtual
Reimplemented from FairDetector.
Definition at line 76 of file project_template/NewDetector/NewDetector.h.
virtual void NewDetector::PreTrack () inline virtual
Reimplemented from FairDetector.
Definition at line 77 of file NewDetector/NewDetector.h.
virtual void NewDetector::PreTrack () inline virtual
Reimplemented from FairDetector.
Definition at line 77 of file project_template/NewDetector/NewDetector.h.
virtual void FairModule::Print (Option_t *) const inline virtual inherited
Print method should be implemented in detector or module
Definition at line 60 of file FairModule.h.
virtual Bool_t NewDetector::ProcessHits (FairVolume * v = 0) virtual
this method is called for each step during simulation (see FairMCApplication::Stepping())
Implements FairDetector.
Bool_t NewDetector::ProcessHits (FairVolume * v = 0) virtual
this method is called for each step during simulation (see FairMCApplication::Stepping())
This method is called from the MC stepping
Implements FairDetector.
Definition at line 77 of file NewDetector/NewDetector.cxx.
References AddHit(), FairStack::AddPoint(), fELoss, fLength, fMom, fPos, fTime, fTrackID, fVolumeID, FairVolume::getMCid(), and kNewDetector.
void FairModule::ProcessNodes (TList * aList) inherited
called from ConstuctASCIIGeometry
Definition at line 259 of file FairModule.cxx.
References FairVolumeList::addVolume(), FairGeoNode::calcLabTransform(), FairModule::fActive, FairModule::fModId, FairModule::fNbOfSensitiveVol, FairModule::fNbOfVolumes, FairRuntimeDb::getContainer(), FairGeoNode::getCopyNo(), FairGeoParSet::GetGeoNodes(), FairGeoVolume::getMCid(), FairGeoNode::getMotherNode(), FairRun::GetRuntimeDb(), FairGeoNode::getTruncName(), FairRun::Instance(), FairGeoNode::isSensitive(), par, rtdb, FairVolume::setCopyNo(), FairVolume::setGeoNode(), FairVolume::setModId(), FairVolume::SetModule(), FairVolume::setMotherCopyNo(), FairVolume::setMotherId(), FairVolume::setRealName(), FairModule::svList, and FairModule::vList.
Referenced by FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), and FairTutorialDet4::SetSensitiveVolumes().
void NewDetector::Register () virtual
Registers the produced collections in FAIRRootManager.
This will create a branch in the output tree called NewDetectorPoint, setting the last parameter to kFALSE means: this collection will not be written to the file, it will exist only during the simulation.
Implements FairDetector.
Definition at line 121 of file NewDetector/NewDetector.cxx.
References fNewDetectorPointCollection, FairRootManager::Instance(), and FairRootManager::Register().
virtual void NewDetector::Register () virtual
Registers the produced collections in FAIRRootManager.
Implements FairDetector.
void NewDetector::Reset () virtual
has to be called after each event to reset the containers
Implements FairDetector.
Definition at line 142 of file NewDetector/NewDetector.cxx.
References fNewDetectorPointCollection.
virtual void NewDetector::Reset () virtual
has to be called after each event to reset the containers
Implements FairDetector.
void FairDetector::SaveGeoParams () inherited
Definition at line 138 of file FairDetector.cxx.
References FairModule::fGeoSaved, FairModule::flGeoPar, and LOG.
void FairModule::SetGeometryFileName (TString fname, TString geoVer = "0") virtual inherited
Set the geometry file name o be used
Definition at line 207 of file FairModule.cxx.
References FairModule::fgeoName, and LOG.
Referenced by run_bg(), run_rad(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), run_tutorial2(), run_tutorial4(), and TEST().
void FairModule::SetModId (Int_t id) inline inherited
set the detector/module id
Definition at line 106 of file FairModule.h.
References FairModule::fModId.
Referenced by FairRunSim::AddModule().
void FairModule::SetMotherVolume (TString volName) inline inherited
Set the name of the mother volume to which a new geometry is added. This function is needed for geometries which are defined as ROOT geometry manager.
Definition at line 110 of file FairModule.h.
References FairModule::fMotherVolumeName.
virtual void FairModule::SetParContainers () inline virtual inherited
Set the parameter containers
Reimplemented in FairTutorialDet4.
Definition at line 114 of file FairModule.h.
Referenced by FairMCApplication::SetParTask().
virtual void NewDetector::SetSpecialPhysicsCuts () inline virtual
The following methods can be implemented if you need to make any optional action in your detector during the transport.
Reimplemented from FairDetector.
Definition at line 71 of file project_template/NewDetector/NewDetector.h.
virtual void NewDetector::SetSpecialPhysicsCuts () inline virtual
The following methods can be implemented if you need to make any optional action in your detector during the transport.
Reimplemented from FairDetector.
Definition at line 71 of file NewDetector/NewDetector.h.
void FairModule::SetVerboseLevel (Int_t level) inline inherited
Set the verbose level in this detector
Definition at line 102 of file FairModule.h.
References FairModule::fVerboseLevel.
Member Data Documentation
Bool_t FairModule::fActive protected inherited
Definition at line 147 of file FairModule.h.
Referenced by FairModule::IsActive(), FairModule::operator=(), and FairModule::ProcessNodes().
Int_t FairDetector::fDetId protected inherited
Definition at line 113 of file FairDetector.h.
Referenced by FairDetector::GetDetId(), and FairDetector::operator=().
Double32_t NewDetector::fELoss private
length
Definition at line 92 of file NewDetector/NewDetector.h.
Referenced by ProcessHits().
TString FairModule::fgeoName protected inherited
Definition at line 145 of file FairModule.h.
Referenced by FairModule::GetGeometryFileName(), FairModule::operator=(), and FairModule::SetGeometryFileName().
Bool_t FairModule::fGeoSaved protected inherited
list of Detector Geometry parameters
Definition at line 151 of file FairModule.h.
Referenced by FairDetector::FairDetector(), FairModule::operator=(), and FairDetector::SaveGeoParams().
TString FairModule::fgeoVer protected inherited
Definition at line 144 of file FairModule.h.
Referenced by FairModule::GetGeometryFileVer(), and FairModule::operator=().
Double32_t NewDetector::fLength private
time
Definition at line 91 of file NewDetector/NewDetector.h.
Referenced by ProcessHits().
TList* FairModule::flGeoPar protected inherited
Definition at line 150 of file FairModule.h.
Referenced by FairDetector::FairDetector(), FairModule::GetListOfGeoPar(), FairModule::operator=(), FairDetector::SaveGeoParams(), and FairDetector::~FairDetector().
FairLogger* FairDetector::fLogger protected inherited
Definition at line 114 of file FairDetector.h.
Referenced by FairDetector::operator=().
TVirtualMC* FairModule::fMC protected inherited
flag for initialisation
Definition at line 152 of file FairModule.h.
Referenced by FairModule::FairModule(), and FairDetector::Initialize().
Int_t FairModule::fModId protected inherited
Definition at line 146 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::GetModId(), FairModule::operator=(), FairModule::ProcessNodes(), and FairModule::SetModId().
TLorentzVector NewDetector::fMom private
position at entrance
Definition at line 89 of file NewDetector/NewDetector.h.
Referenced by ProcessHits().
TString FairModule::fMotherVolumeName inherited
Definition at line 129 of file FairModule.h.
Referenced by FairModule::ConstructRootGeometry(), FairModule::operator=(), and FairModule::SetMotherVolume().
Int_t FairModule::fNbOfSensitiveVol protected inherited
Definition at line 148 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::operator=(), and FairModule::ProcessNodes().
thread_local Int_t FairModule::fNbOfVolumes =0 static inherited
total number of volumes in a simulaion session
Definition at line 124 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), and FairModule::ProcessNodes().
TClonesArray * NewDetector::fNewDetectorPointCollection private
energy loss
container for data points
Definition at line 96 of file NewDetector/NewDetector.h.
Referenced by AddHit(), EndOfEvent(), GetCollection(), Register(), Reset(), and ~NewDetector().
TLorentzVector NewDetector::fPos private
volume id
Definition at line 88 of file NewDetector/NewDetector.h.
Referenced by ProcessHits().
Double32_t NewDetector::fTime private
momentum at entrance
Definition at line 90 of file NewDetector/NewDetector.h.
Referenced by ProcessHits().
Int_t NewDetector::fTrackID private
Track information to be stored until the track leaves the active volume.
Definition at line 86 of file NewDetector/NewDetector.h.
Referenced by ProcessHits().
Int_t FairModule::fVerboseLevel protected inherited
Definition at line 149 of file FairModule.h.
Referenced by FairModule::operator=(), and FairModule::SetVerboseLevel().
Int_t NewDetector::fVolumeID private
track index
Definition at line 87 of file NewDetector/NewDetector.h.
Referenced by ProcessHits().
thread_local TRefArray * FairModule::svList =0 static inherited
list of all sensitive volumes in a simulaion session
Definition at line 126 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::FairModule(), FairMCApplication::InitGeometry(), FairDetector::Initialize(), and FairModule::ProcessNodes().
thread_local FairVolumeList * FairModule::vList =0 static inherited
list of volumes in a simulation session
Definition at line 122 of file FairModule.h.
Referenced by FairModule::AddSensitiveVolume(), FairModule::FairModule(), FairModule::getFairVolume(), and FairModule::ProcessNodes().
thread_local TArrayI * FairModule::volNumber =0 static inherited
Definition at line 128 of file FairModule.h.
The documentation for this class was generated from the following files:
NewDetector/NewDetector.h
NewDetector/NewDetector.cxx