FairRoot: FairGeoBuilder Class Reference
FairGeoBuilder Class Reference abstract
#include <FairGeoBuilder.h>
Public Member Functions
virtual ~FairGeoBuilder ()
virtual Bool_t createNode (FairGeoNode *, Int_t hadFormat=0)=0
virtual Int_t createMedium (FairGeoMedium *)=0
virtual void finalize ()
const Int_t & GetNMedia () const
void SetNMedia (const Int_t &nmed)
Protected Member Functions
FairGeoBuilder ()
FairGeoBuilder (const char *name, const char *title)
Protected Attributes
Int_t nRot
Int_t nMed
Detailed Description
abstract base class for geometry builders
Author
ilse koenig
Definition at line 22 of file FairGeoBuilder.h.
Constructor & Destructor Documentation
FairGeoBuilder() [1/2]
FairGeoBuilder::FairGeoBuilder () protected
FairGeoBuilder() [2/2]
FairGeoBuilder::FairGeoBuilder (const char * name, const char * title) protected
Definition at line 30 of file FairGeoBuilder.cxx.
~FairGeoBuilder()
virtual FairGeoBuilder::~FairGeoBuilder () inline virtual
Definition at line 31 of file FairGeoBuilder.h.
Member Function Documentation
createMedium()
virtual Int_t FairGeoBuilder::createMedium (FairGeoMedium *) pure virtual
Implemented in FairGeoRootBuilder.
Referenced by FairModule::AssignMediumAtImport(), FairPipe::ConstructGeometry(), and create_materials_from_media_file().
createNode()
virtual Bool_t FairGeoBuilder::createNode (FairGeoNode * , Int_t hadFormat = 0) pure virtual
Implemented in FairGeoRootBuilder.
Referenced by FairGeoSet::create().
finalize()
virtual void FairGeoBuilder::finalize () inline virtual
Reimplemented in FairGeoRootBuilder.
Definition at line 34 of file FairGeoBuilder.h.
Referenced by FairGeoInterface::createAll(), and FairGeoInterface::createGeometry().
GetNMedia()
const Int_t& FairGeoBuilder::GetNMedia () const inline
Definition at line 35 of file FairGeoBuilder.h.
References nMed.
Referenced by FairModule::ReAssignMediaId().
SetNMedia()
void FairGeoBuilder::SetNMedia (const Int_t & nmed) inline
Definition at line 36 of file FairGeoBuilder.h.
References nMed.
Referenced by FairModule::ReAssignMediaId().
Member Data Documentation
nMed
Int_t FairGeoBuilder::nMed protected
Definition at line 26 of file FairGeoBuilder.h.
Referenced by FairGeoRootBuilder::createMedium(), GetNMedia(), and SetNMedia().
nRot
Int_t FairGeoBuilder::nRot protected
Definition at line 25 of file FairGeoBuilder.h.
Referenced by FairGeoRootBuilder::createNode().
The documentation for this class was generated from the following files:
FairGeoBuilder.h
FairGeoBuilder.cxx