FairRroot: fair::mq::DeviceRunner Class Reference
fair::mq::DeviceRunner Class Reference
Utility class to facilitate a convenient top-level device launch/shutdown.
#include <fairmq/DeviceRunner.h>
Public Member Functions
DeviceRunner (int argc, char *const argv[])
auto Run () -> int
auto RunWithExceptionHandlers () -> int
template<typename H >
auto AddHook (std::function< void(DeviceRunner &)> hook) -> void
template<typename H >
auto RemoveHook () -> void
Public Attributes
std::vector< std::string > fRawCmdLineArgs
std::shared_ptr< PluginManager > fPluginManager
FairMQProgOptions fConfig
std::shared_ptr< FairMQDevice > fDevice
Private Attributes
EventManager fEvents
Detailed Description
Utility class to facilitate a convenient top-level device launch/shutdown.
Runs a single FairMQ device with config and plugin support.
For customization user hooks are executed at various steps during device launch/shutdown in the following sequence:
    LoadPlugins
         |
         v
SetCustomCmdLineOptions | v ModifyRawCmdLineArgs | v InstatiateDevice
Each hook has access to all members of the DeviceRunner and really only differs by the point in time it is called.
For an example usage of this class see the fairmq/runFairMQDevice.h header.
Definition at line 51 of file DeviceRunner.h.
Constructor & Destructor Documentation
DeviceRunner::DeviceRunner (int argc, char *const argv[])
Definition at line 15 of file DeviceRunner.cxx.
References fair::mq::tools::ToStrVector().
Member Function Documentation
template<typename H > auto fair::mq::DeviceRunner::AddHook (std::function< void(DeviceRunner &)> hook) -> void inline
Definition at line 60 of file DeviceRunner.h.
References fEvents, and fair::mq::EventManager::Subscribe().
Referenced by main().
template<typename H > auto fair::mq::DeviceRunner::RemoveHook () -> void inline
Definition at line 62 of file DeviceRunner.h.
References fEvents, and fair::mq::EventManager::Unsubscribe().
auto DeviceRunner::Run () -> int
Definition at line 22 of file DeviceRunner.cxx.
References fair::debug, FairMQStateMachine::END, fair::error, FAIRMQ_INTERFACE_VERSION, and LOG.
auto DeviceRunner::RunWithExceptionHandlers () -> int
Definition at line 94 of file DeviceRunner.cxx.
References fair::error, and LOG.
Member Data Documentation
FairMQProgOptions fair::mq::DeviceRunner::fConfig
Definition at line 66 of file DeviceRunner.h.
std::shared_ptr<FairMQDevice> fair::mq::DeviceRunner::fDevice
Definition at line 67 of file DeviceRunner.h.
EventManager fair::mq::DeviceRunner::fEvents private
Definition at line 70 of file DeviceRunner.h.
Referenced by AddHook(), and RemoveHook().
std::shared_ptr<PluginManager> fair::mq::DeviceRunner::fPluginManager
Definition at line 65 of file DeviceRunner.h.
std::vector<std::string> fair::mq::DeviceRunner::fRawCmdLineArgs
Definition at line 64 of file DeviceRunner.h.
The documentation for this class was generated from the following files:
DeviceRunner.h
DeviceRunner.cxx