FairRoot: FairTutorialDet4PointDraw Class Reference
FairTutorialDet4PointDraw Class Reference
#include <FairTutorialDet4PointDraw.h>
Public Member Functions
FairTutorialDet4PointDraw ()
FairTutorialDet4PointDraw (const char *name, Color_t color, Style_t mstyle)
virtual ~FairTutorialDet4PointDraw ()
virtual void Exec (Option_t *option)
void Reset ()
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Finish ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Private Member Functions
FairTutorialDet4PointDraw (const FairTutorialDet4PointDraw &)
FairTutorialDet4PointDraw & operator= (const FairTutorialDet4PointDraw &)
ClassDef (FairTutorialDet4PointDraw, 1)
Private Attributes
TClonesArray * fPointList
FairTutorialDet4GeoPar * fGeoPar
FairEventManager * fEventManager
TEvePointSet * fq
Color_t fColor
Style_t fStyle
Bool_t fGlobalCoordinates
FairTutorialDet4GeoHandler * fGeoHandler
Detailed Description
Definition at line 29 of file FairTutorialDet4PointDraw.h.
Constructor & Destructor Documentation
FairTutorialDet4PointDraw() [1/3]
FairTutorialDet4PointDraw::FairTutorialDet4PointDraw ()
Default constructor
Definition at line 26 of file FairTutorialDet4PointDraw.cxx.
FairTutorialDet4PointDraw() [2/3]
FairTutorialDet4PointDraw::FairTutorialDet4PointDraw (const char * name, Color_t color, Style_t mstyle)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 43 of file FairTutorialDet4PointDraw.cxx.
~FairTutorialDet4PointDraw()
FairTutorialDet4PointDraw::~FairTutorialDet4PointDraw () virtual
Destructor
Definition at line 145 of file FairTutorialDet4PointDraw.cxx.
FairTutorialDet4PointDraw() [3/3]
FairTutorialDet4PointDraw::FairTutorialDet4PointDraw (const FairTutorialDet4PointDraw &) private
Member Function Documentation
CheckInputPersistance()
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
ClassDef()
FairTutorialDet4PointDraw::ClassDef (FairTutorialDet4PointDraw , 1) private
Exec()
void FairTutorialDet4PointDraw::Exec (Option_t * option) virtual
Executed task
Definition at line 92 of file FairTutorialDet4PointDraw.cxx.
References fColor, fGeoHandler, fGlobalCoordinates, fPointList, fq, fStyle, FairMCPoint::GetDetectorID(), FairMCPoint::GetX(), FairMCPoint::GetY(), FairMCPoint::GetZ(), FairTutorialDet4GeoHandler::LocalToGlobal(), and Reset().
ExecuteTask()
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
ExecuteTasks()
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
Finish()
void FairTutorialDet4PointDraw::Finish () virtual
Action after each event
Reimplemented from FairTask.
Definition at line 151 of file FairTutorialDet4PointDraw.cxx.
FinishEvent()
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
FinishEvents()
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
FinishTask()
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
FinishTasks()
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
Init()
InitStatus FairTutorialDet4PointDraw::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 71 of file FairTutorialDet4PointDraw.cxx.
References fEventManager, fGeoPar, fGlobalCoordinates, fPointList, fq, FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), FairTutorialDet4GeoPar::IsGlobalCoordinateSystem(), kERROR, and kSUCCESS.
InitTask()
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
InitTasks()
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
IsOutputBranchPersistent()
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
operator=()
FairTutorialDet4PointDraw& FairTutorialDet4PointDraw::operator= (const FairTutorialDet4PointDraw &) private
ReInit()
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, PixelAltFindHits, PixelFindHits, PixelDigitize, PixelFitTracks, FairRingSorterTask, PixelFindTracks, PixelAltDigiWriteToRootVector, PixelDigiWriteToBinFile, PixelDigiWriteToFile, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 120 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
ReInitTask()
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
ReInitTasks()
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
Reset()
void FairTutorialDet4PointDraw::Reset ()
Definition at line 157 of file FairTutorialDet4PointDraw.cxx.
References fEventManager, and fq.
Referenced by Exec().
SetInputPersistance()
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
SetOutputBranchPersistent()
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
SetParContainers()
void FairTutorialDet4PointDraw::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 59 of file FairTutorialDet4PointDraw.cxx.
References fGeoPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRun::Instance().
SetParTask()
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
SetParTasks()
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
SetStreamProcessing()
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
SetVerbose()
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
fColor
Color_t FairTutorialDet4PointDraw::fColor private
Definition at line 62 of file FairTutorialDet4PointDraw.h.
Referenced by Exec().
fEventManager
FairEventManager* FairTutorialDet4PointDraw::fEventManager private
Definition at line 60 of file FairTutorialDet4PointDraw.h.
Referenced by Init(), and Reset().
fGeoHandler
FairTutorialDet4GeoHandler* FairTutorialDet4PointDraw::fGeoHandler private
Definition at line 65 of file FairTutorialDet4PointDraw.h.
Referenced by Exec().
fGeoPar
FairTutorialDet4GeoPar* FairTutorialDet4PointDraw::fGeoPar private
Definition at line 59 of file FairTutorialDet4PointDraw.h.
Referenced by Init(), and SetParContainers().
fGlobalCoordinates
Bool_t FairTutorialDet4PointDraw::fGlobalCoordinates private
Definition at line 64 of file FairTutorialDet4PointDraw.h.
Referenced by Exec(), and Init().
fInputPersistance
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
fLogger
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
fPointList
TClonesArray* FairTutorialDet4PointDraw::fPointList private
Definition at line 58 of file FairTutorialDet4PointDraw.h.
Referenced by Exec(), and Init().
fq
TEvePointSet* FairTutorialDet4PointDraw::fq private
Definition at line 61 of file FairTutorialDet4PointDraw.h.
Referenced by Exec(), Init(), and Reset().
fStreamProcessing
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
fStyle
Style_t FairTutorialDet4PointDraw::fStyle private
Definition at line 63 of file FairTutorialDet4PointDraw.h.
Referenced by Exec().
fVerbose
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairTutorialDet4PointDraw.h
FairTutorialDet4PointDraw.cxx