FairRoot: PixelDigiWriteToFile Class Reference
PixelDigiWriteToFile Class Reference
#include <PixelDigiWriteToFile.h>
Public Member Functions
PixelDigiWriteToFile ()
PixelDigiWriteToFile (Int_t iVerbose)
PixelDigiWriteToFile (const char *name, Int_t iVerbose)
virtual ~PixelDigiWriteToFile ()
virtual void Exec (Option_t *opt)
void SetOutputFileName (TString tstr)
void SetDivideLevel (Int_t idiv)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Private Member Functions
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
void Reset ()
virtual void Finish ()
PixelDigiWriteToFile (const PixelDigiWriteToFile &)
PixelDigiWriteToFile & operator= (const PixelDigiWriteToFile &)
ClassDef (PixelDigiWriteToFile, 1)
Private Attributes
TClonesArray * fDigis
TString fOutputFileName
Int_t fNofOutputFiles
std::ofstream fOutputFiles [12]
Int_t fDivideLevel
Int_t fRunId
Int_t fMCEntryNo
Int_t fPartNo
Detailed Description
Definition at line 28 of file PixelDigiWriteToFile.h.
Constructor & Destructor Documentation
PixelDigiWriteToFile() [1/4]
PixelDigiWriteToFile::PixelDigiWriteToFile ()
Default constructor
Definition at line 40 of file PixelDigiWriteToFile.cxx.
PixelDigiWriteToFile() [2/4]
PixelDigiWriteToFile::PixelDigiWriteToFile (Int_t iVerbose)
Standard constructor
Definition at line 49 of file PixelDigiWriteToFile.cxx.
PixelDigiWriteToFile() [3/4]
PixelDigiWriteToFile::PixelDigiWriteToFile (const char * name, Int_t iVerbose)
Constructor with name
Definition at line 58 of file PixelDigiWriteToFile.cxx.
References Reset().
~PixelDigiWriteToFile()
PixelDigiWriteToFile::~PixelDigiWriteToFile () virtual
Destructor
Definition at line 77 of file PixelDigiWriteToFile.cxx.
References Reset().
PixelDigiWriteToFile() [4/4]
PixelDigiWriteToFile::PixelDigiWriteToFile (const PixelDigiWriteToFile &) private
Member Function Documentation
CheckInputPersistance()
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
ClassDef()
PixelDigiWriteToFile::ClassDef (PixelDigiWriteToFile , 1) private
Exec()
void PixelDigiWriteToFile::Exec (Option_t * opt) virtual
Execution
Definition at line 83 of file PixelDigiWriteToFile.cxx.
References fDigis, fDivideLevel, fMCEntryNo, fNofOutputFiles, fOutputFiles, fRunId, PixelDigi::GetCharge(), PixelDigi::GetCol(), PixelDigi::GetDetectorID(), PixelDigi::GetFeID(), PixelDigi::GetRow(), and Reset().
ExecuteTask()
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
ExecuteTasks()
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
Finish()
void PixelDigiWriteToFile::Finish () private virtual
Finish at the end of each event
Reimplemented from FairTask.
Definition at line 195 of file PixelDigiWriteToFile.cxx.
References fNofOutputFiles, and fOutputFiles.
FinishEvent()
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
FinishEvents()
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
FinishTask()
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
FinishTasks()
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
Init()
InitStatus PixelDigiWriteToFile::Init () private virtual
Intialisation
Reimplemented from FairTask.
Definition at line 126 of file PixelDigiWriteToFile.cxx.
References fDigis, fDivideLevel, fNofOutputFiles, fOutputFileName, fOutputFiles, fRunId, FairRootManager::GetObject(), FairRootManager::GetRunId(), FairRootManager::Instance(), kFATAL, and kSUCCESS.
InitTask()
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
InitTasks()
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
IsOutputBranchPersistent()
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
operator=()
PixelDigiWriteToFile& PixelDigiWriteToFile::operator= (const PixelDigiWriteToFile &) private
ReInit()
InitStatus PixelDigiWriteToFile::ReInit () private virtual
Reinitialisation
Reimplemented from FairTask.
Definition at line 172 of file PixelDigiWriteToFile.cxx.
References fMCEntryNo, fRunId, FairRootManager::GetRunId(), FairRootManager::Instance(), kFATAL, and kSUCCESS.
ReInitTask()
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
ReInitTasks()
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
Reset()
void PixelDigiWriteToFile::Reset () private
Reset eventwise counters
Definition at line 190 of file PixelDigiWriteToFile.cxx.
Referenced by Exec(), PixelDigiWriteToFile(), and ~PixelDigiWriteToFile().
SetDivideLevel()
void PixelDigiWriteToFile::SetDivideLevel (Int_t idiv) inline
Definition at line 54 of file PixelDigiWriteToFile.h.
References fDivideLevel.
Referenced by run_digiToAscii().
SetInputPersistance()
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
SetOutputBranchPersistent()
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
SetOutputFileName()
void PixelDigiWriteToFile::SetOutputFileName (TString tstr) inline
Definition at line 52 of file PixelDigiWriteToFile.h.
References fOutputFileName.
Referenced by run_digiToAscii().
SetParContainers()
void PixelDigiWriteToFile::SetParContainers () private virtual
Get parameter containers
Reimplemented from FairTask.
Definition at line 121 of file PixelDigiWriteToFile.cxx.
SetParTask()
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
SetParTasks()
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
SetStreamProcessing()
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
SetVerbose()
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
fDigis
TClonesArray* PixelDigiWriteToFile::fDigis private
Definition at line 58 of file PixelDigiWriteToFile.h.
Referenced by Exec(), and Init().
fDivideLevel
Int_t PixelDigiWriteToFile::fDivideLevel private
Definition at line 67 of file PixelDigiWriteToFile.h.
Referenced by Exec(), Init(), and SetDivideLevel().
fInputPersistance
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
fLogger
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
fMCEntryNo
Int_t PixelDigiWriteToFile::fMCEntryNo private
Definition at line 70 of file PixelDigiWriteToFile.h.
Referenced by Exec(), and ReInit().
fNofOutputFiles
Int_t PixelDigiWriteToFile::fNofOutputFiles private
Definition at line 61 of file PixelDigiWriteToFile.h.
Referenced by Exec(), Finish(), and Init().
fOutputFileName
TString PixelDigiWriteToFile::fOutputFileName private
Input array of PixelDigi
Definition at line 60 of file PixelDigiWriteToFile.h.
Referenced by Init(), and SetOutputFileName().
fOutputFiles
std::ofstream PixelDigiWriteToFile::fOutputFiles[12] private
Definition at line 62 of file PixelDigiWriteToFile.h.
Referenced by Exec(), Finish(), and Init().
fPartNo
Int_t PixelDigiWriteToFile::fPartNo private
Definition at line 71 of file PixelDigiWriteToFile.h.
fRunId
Int_t PixelDigiWriteToFile::fRunId private
Definition at line 69 of file PixelDigiWriteToFile.h.
Referenced by Exec(), Init(), and ReInit().
fStreamProcessing
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
fVerbose
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
PixelDigiWriteToFile.h
PixelDigiWriteToFile.cxx