FairRroot: fair::mq::shmem::Monitor Class Reference
fair::mq::shmem::Monitor Class Reference
#include <Monitor.h>
Public Member Functions
Monitor (const std::string &sessionName, bool selfDestruct, bool interactive, unsigned int timeoutInMS, bool runAsDaemon, bool cleanOnExit)
Monitor (const Monitor &)=delete
Monitor operator= (const Monitor &)=delete
void CatchSignals ()
void Run ()
virtual ~Monitor ()
Static Public Member Functions
static void Cleanup (const std::string &sessionName)
static void RemoveObject (const std::string &)
static void RemoveQueue (const std::string &)
Private Member Functions
void PrintHeader ()
void PrintHelp ()
void PrintQueues ()
void MonitorHeartbeats ()
void CheckSegment ()
void Interactive ()
void SignalMonitor ()
Private Attributes
bool fSelfDestruct
bool fInteractive
bool fSeenOnce
bool fIsDaemon
bool fCleanOnExit
unsigned int fTimeoutInMS
std::string fSessionName
std::string fSegmentName
std::string fManagementSegmentName
std::string fControlQueueName
std::atomic< bool > fTerminating
std::atomic< bool > fHeartbeatTriggered
std::chrono::high_resolution_clock::time_point fLastHeartbeat
std::thread fSignalThread
boost::interprocess::managed_shared_memory fManagementSegment
std::unordered_map< std::string, std::chrono::high_resolution_clock::time_point > fDeviceHeartbeats
Detailed Description
Definition at line 26 of file Monitor.h.
Constructor & Destructor Documentation
fair::mq::shmem::Monitor::Monitor (const std::string & sessionName, bool selfDestruct, bool interactive, unsigned int timeoutInMS, bool runAsDaemon, bool cleanOnExit)
fair::mq::shmem::Monitor::Monitor (const Monitor &) delete
fair::mq::shmem::Monitor::~Monitor () virtual
Definition at line 492 of file Monitor.cxx.
Member Function Documentation
void fair::mq::shmem::Monitor::CatchSignals ()
Definition at line 83 of file Monitor.cxx.
References fair::mq::shmem::signalHandler().
Referenced by main().
void fair::mq::shmem::Monitor::CheckSegment () private
Definition at line 244 of file Monitor.cxx.
References fair::mq::shmem::DeviceCounter::fCount.
void fair::mq::shmem::Monitor::Cleanup (const std::string & sessionName) static
Definition at line 361 of file Monitor.cxx.
References fair::mq::shmem::RegionCounter::fCount.
Referenced by main().
void fair::mq::shmem::Monitor::Interactive () private
Definition at line 163 of file Monitor.cxx.
void fair::mq::shmem::Monitor::MonitorHeartbeats () private
Definition at line 129 of file Monitor.cxx.
Monitor fair::mq::shmem::Monitor::operator= (const Monitor &) delete
void fair::mq::shmem::Monitor::PrintHeader () private
Definition at line 472 of file Monitor.cxx.
void fair::mq::shmem::Monitor::PrintHelp () private
Definition at line 487 of file Monitor.cxx.
void fair::mq::shmem::Monitor::PrintQueues () private
Definition at line 421 of file Monitor.cxx.
void fair::mq::shmem::Monitor::RemoveObject (const std::string &) static
Definition at line 397 of file Monitor.cxx.
void fair::mq::shmem::Monitor::RemoveQueue (const std::string &) static
Definition at line 409 of file Monitor.cxx.
Referenced by main().
void fair::mq::shmem::Monitor::Run ()
Definition at line 109 of file Monitor.cxx.
void fair::mq::shmem::Monitor::SignalMonitor () private
Definition at line 90 of file Monitor.cxx.
Member Data Documentation
bool fair::mq::shmem::Monitor::fCleanOnExit private
Definition at line 56 of file Monitor.h.
std::string fair::mq::shmem::Monitor::fControlQueueName private
Definition at line 61 of file Monitor.h.
std::unordered_map<std::string, std::chrono::high_resolution_clock::time_point> fair::mq::shmem::Monitor::fDeviceHeartbeats private
Definition at line 67 of file Monitor.h.
std::atomic<bool> fair::mq::shmem::Monitor::fHeartbeatTriggered private
Definition at line 63 of file Monitor.h.
bool fair::mq::shmem::Monitor::fInteractive private
Definition at line 53 of file Monitor.h.
bool fair::mq::shmem::Monitor::fIsDaemon private
Definition at line 55 of file Monitor.h.
std::chrono::high_resolution_clock::time_point fair::mq::shmem::Monitor::fLastHeartbeat private
Definition at line 64 of file Monitor.h.
boost::interprocess::managed_shared_memory fair::mq::shmem::Monitor::fManagementSegment private
Definition at line 66 of file Monitor.h.
std::string fair::mq::shmem::Monitor::fManagementSegmentName private
Definition at line 60 of file Monitor.h.
bool fair::mq::shmem::Monitor::fSeenOnce private
Definition at line 54 of file Monitor.h.
std::string fair::mq::shmem::Monitor::fSegmentName private
Definition at line 59 of file Monitor.h.
bool fair::mq::shmem::Monitor::fSelfDestruct private
Definition at line 52 of file Monitor.h.
std::string fair::mq::shmem::Monitor::fSessionName private
Definition at line 58 of file Monitor.h.
std::thread fair::mq::shmem::Monitor::fSignalThread private
Definition at line 65 of file Monitor.h.
std::atomic<bool> fair::mq::shmem::Monitor::fTerminating private
Definition at line 62 of file Monitor.h.
unsigned int fair::mq::shmem::Monitor::fTimeoutInMS private
Definition at line 57 of file Monitor.h.
The documentation for this class was generated from the following files:
Monitor.h
Monitor.cxx