FairRoot: PixelEventHeader Class Reference
PixelEventHeader Class Reference
#include <PixelEventHeader.h>
Public Member Functions
PixelEventHeader ()
virtual ~PixelEventHeader ()
void SetPartNo (Int_t ipart)
Int_t GetPartNo ()
template<class Archive >
void serialize (Archive &ar, const unsigned int)
UInt_t GetRunId ()
Double_t GetEventTime ()
Int_t GetInputFileId ()
Int_t GetMCEntryNumber ()
void SetRunId (UInt_t runid)
void SetEventTime (Double_t time)
void SetInputFileId (Int_t id)
void SetMCEntryNumber (Int_t id)
virtual void Register (Bool_t Persistance=kTRUE)
Protected Attributes
UInt_t fRunId
Double_t fEventTime
Int_t fInputFileId
Int_t fMCEntryNo
Private Member Functions
ClassDef (PixelEventHeader, 1)
Private Attributes
Int_t fPartNo
Friends
class boost::serialization::access
Detailed Description
Definition at line 23 of file PixelEventHeader.h.
Constructor & Destructor Documentation
PixelEventHeader()
PixelEventHeader::PixelEventHeader ()
Default constructor
Definition at line 17 of file PixelEventHeader.cxx.
~PixelEventHeader()
PixelEventHeader::~PixelEventHeader () virtual
Destructor
Definition at line 23 of file PixelEventHeader.cxx.
Member Function Documentation
ClassDef()
PixelEventHeader::ClassDef (PixelEventHeader , 1) private
GetEventTime()
Double_t FairEventHeader::GetEventTime () inline inherited
Get the MC time for this event
Definition at line 37 of file FairEventHeader.h.
References FairEventHeader::fEventTime.
Referenced by FairMixedSource::FillEventHeader(), FairFileSource::GetEventTime(), FairMixedSource::GetEventTime(), FairRootManager::ReadBranchEvent(), FairRootManager::ReadEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
GetInputFileId()
Int_t FairEventHeader::GetInputFileId () inline inherited
Get the MC input file Id for this event
Definition at line 40 of file FairEventHeader.h.
References FairEventHeader::fInputFileId.
Referenced by FairMixedSource::FillEventHeader(), and FairMixedSource::ReadBranchEvent().
GetMCEntryNumber()
Int_t FairEventHeader::GetMCEntryNumber () inline inherited
The entry number in the original MC chain
Definition at line 43 of file FairEventHeader.h.
References FairEventHeader::fMCEntryNo.
Referenced by FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), FairMQPixelMerger::MergeData(), FairFileSource::ReadBranchEvent(), and FairMixedSource::ReadBranchEvent().
GetPartNo()
Int_t PixelEventHeader::GetPartNo () inline
Definition at line 33 of file PixelEventHeader.h.
References fPartNo.
Referenced by FairMQPixelMerger::MergeData().
GetRunId()
UInt_t FairEventHeader::GetRunId () inline inherited
Get the run ID for this run
Definition at line 34 of file FairEventHeader.h.
References FairEventHeader::fRunId.
Referenced by FairRunOnline::EventLoop(), FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), FairRootManager::GetRunId(), FairRunAnaProof::Init(), FairRunOnline::Init(), FairMixedSource::Init(), FairRunAna::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairMQPixelMerger::MergeData(), FairRunAna::Run(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
Register()
void FairEventHeader::Register (Bool_t Persistance = kTRUE) virtual inherited
Definition at line 30 of file FairEventHeader.cxx.
References FairRootManager::Instance(), and FairRootManager::Register().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunAnaProof::InitContainers(), and FairRunOnline::InitContainers().
serialize()
template<class Archive > void PixelEventHeader::serialize (Archive & ar, const unsigned int) inline
Definition at line 36 of file PixelEventHeader.h.
SetEventTime()
void FairEventHeader::SetEventTime (Double_t time) inline inherited
Set the MC time for this event
Parameters
time : time in ns
Definition at line 53 of file FairEventHeader.h.
References FairEventHeader::fEventTime.
Referenced by FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), and FairMixedSource::ReadEvent().
SetInputFileId()
void FairEventHeader::SetInputFileId (Int_t id) inline inherited
Set the Signal file Id for this event
Definition at line 56 of file FairEventHeader.h.
References FairEventHeader::fInputFileId.
Referenced by FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), and FairMixedSource::ReadEvent().
SetMCEntryNumber()
void FairEventHeader::SetMCEntryNumber (Int_t id) inline inherited
The entry number in the original MC chain
Definition at line 59 of file FairEventHeader.h.
References FairEventHeader::fMCEntryNo.
Referenced by FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), PixelDigiSource::ReadEvent(), PixelDigiBinSource::ReadEvent(), and FairMixedSource::ReadEvent().
SetPartNo()
void PixelEventHeader::SetPartNo (Int_t ipart) inline
Definition at line 32 of file PixelEventHeader.h.
References fPartNo.
Referenced by PixelDigiBinSource::ReadEvent(), and PixelDigiSource::ReadEvent().
SetRunId()
void FairEventHeader::SetRunId (UInt_t runid) inline inherited
Set the run ID for this run
Parameters
runid : unique run id
Definition at line 48 of file FairEventHeader.h.
References FairEventHeader::fRunId.
Referenced by FairSource::FillEventHeader(), FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMixedSource::Init(), PixelDigiBinSource::ReadEvent(), and PixelDigiSource::ReadEvent().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 44 of file PixelEventHeader.h.
Member Data Documentation
fEventTime
Double_t FairEventHeader::fEventTime protected inherited
Event Time
Definition at line 71 of file FairEventHeader.h.
Referenced by FairEventHeader::GetEventTime(), and FairEventHeader::SetEventTime().
fInputFileId
Int_t FairEventHeader::fInputFileId protected inherited
Input file identifier, the file description is in the File header
Definition at line 73 of file FairEventHeader.h.
Referenced by FairEventHeader::GetInputFileId(), and FairEventHeader::SetInputFileId().
fMCEntryNo
Int_t FairEventHeader::fMCEntryNo protected inherited
MC entry number from input chain
Definition at line 75 of file FairEventHeader.h.
Referenced by FairEventHeader::GetMCEntryNumber(), and FairEventHeader::SetMCEntryNumber().
fPartNo
Int_t PixelEventHeader::fPartNo private
Definition at line 42 of file PixelEventHeader.h.
Referenced by GetPartNo(), and SetPartNo().
fRunId
UInt_t FairEventHeader::fRunId protected inherited
Run Id
Definition at line 69 of file FairEventHeader.h.
Referenced by FairEventHeader::GetRunId(), and FairEventHeader::SetRunId().
The documentation for this class was generated from the following files:
PixelEventHeader.h
PixelEventHeader.cxx