FairRroot: FairMQStateMachine Class Reference
FairMQStateMachine Class Reference
#include <FairMQStateMachine.h>
Public Types
enum Event {
INIT_DEVICE, internal_DEVICE_READY, INIT_TASK, internal_READY,
RUN, PAUSE, STOP, RESET_TASK,
RESET_DEVICE, internal_IDLE, END, ERROR_FOUND
}
Public Member Functions
FairMQStateMachine ()
virtual ~FairMQStateMachine ()
int GetInterfaceVersion () const
bool ChangeState (int event)
bool ChangeState (const std::string &event)
void WaitForEndOfState (int event)
void WaitForEndOfState (const std::string &event)
bool WaitForEndOfStateForMs (int event, int durationInMs)
bool WaitForEndOfStateForMs (const std::string &event, int durationInMs)
void SubscribeToStateChange (const std::string &key, std::function< void(const State)> callback)
void UnsubscribeFromStateChange (const std::string &key)
Private Member Functions
int GetEventNumber (const std::string &event)
Detailed Description
Definition at line 568 of file FairMQStateMachine.h.
Member Enumeration Documentation
enum FairMQStateMachine::Event
Enumerator
INIT_DEVICE
internal_DEVICE_READY
INIT_TASK
internal_READY
RUN
PAUSE
STOP
RESET_TASK
RESET_DEVICE
internal_IDLE
END
ERROR_FOUND
Definition at line 571 of file FairMQStateMachine.h.
Constructor & Destructor Documentation
FairMQStateMachine::FairMQStateMachine ()
FairMQStateMachine.cxx
Since
2012-10-25
Author
D. Klein, A. Rybalchenko
Definition at line 17 of file FairMQStateMachine.cxx.
FairMQStateMachine::~FairMQStateMachine () virtual
Definition at line 22 of file FairMQStateMachine.cxx.
Member Function Documentation
bool FairMQStateMachine::ChangeState (int event)
Definition at line 32 of file FairMQStateMachine.cxx.
References END, ERROR_FOUND, INIT_DEVICE, INIT_TASK, internal_DEVICE_READY, internal_IDLE, internal_READY, LOG, PAUSE, RESET_DEVICE, RESET_TASK, RUN, and STOP.
Referenced by ChangeState(), FairMQDevice::InitTaskWrapper(), FairMQDevice::InitWrapper(), FairMQDevice::NewPoller(), FairMQDevice::PollForTransport(), FairMQDevice::ResetTaskWrapper(), FairMQDevice::ResetWrapper(), FairMQDevice::RunWrapper(), and FairMQDevice::SetTransport().
bool FairMQStateMachine::ChangeState (const std::string & event)
Definition at line 126 of file FairMQStateMachine.cxx.
References ChangeState(), and GetEventNumber().
int FairMQStateMachine::GetEventNumber (const std::string & event) private
Definition at line 220 of file FairMQStateMachine.cxx.
References END, ERROR_FOUND, INIT_DEVICE, INIT_TASK, LOG, PAUSE, RESET_DEVICE, RESET_TASK, RUN, and STOP.
Referenced by ChangeState(), WaitForEndOfState(), and WaitForEndOfStateForMs().
int FairMQStateMachine::GetInterfaceVersion () const
Definition at line 27 of file FairMQStateMachine.cxx.
References FAIRMQ_INTERFACE_VERSION.
void FairMQStateMachine::SubscribeToStateChange (const std::string & key, std::function< void(const State)> callback)
Definition at line 207 of file FairMQStateMachine.cxx.
void FairMQStateMachine::UnsubscribeFromStateChange (const std::string & key)
Definition at line 211 of file FairMQStateMachine.cxx.
void FairMQStateMachine::WaitForEndOfState (int event)
Definition at line 131 of file FairMQStateMachine.cxx.
References INIT_DEVICE, INIT_TASK, LOG, RESET_DEVICE, RESET_TASK, and RUN.
Referenced by WaitForEndOfState().
void FairMQStateMachine::WaitForEndOfState (const std::string & event)
Definition at line 162 of file FairMQStateMachine.cxx.
References GetEventNumber(), and WaitForEndOfState().
bool FairMQStateMachine::WaitForEndOfStateForMs (int event, int durationInMs)
Definition at line 167 of file FairMQStateMachine.cxx.
References INIT_DEVICE, INIT_TASK, LOG, RESET_DEVICE, RESET_TASK, and RUN.
Referenced by WaitForEndOfStateForMs().
bool FairMQStateMachine::WaitForEndOfStateForMs (const std::string & event, int durationInMs)
Definition at line 202 of file FairMQStateMachine.cxx.
References GetEventNumber(), and WaitForEndOfStateForMs().
The documentation for this class was generated from the following files:
FairMQStateMachine.h
FairMQStateMachine.cxx