FairRroot: FairMQPollerZMQ Class Reference
FairMQPollerZMQ Class Reference
#include <FairMQPollerZMQ.h>
Public Member Functions
FairMQPollerZMQ (const std::vector< FairMQChannel > &channels)
FairMQPollerZMQ (const std::vector< const FairMQChannel * > &channels)
FairMQPollerZMQ (const std::unordered_map< std::string, std::vector< FairMQChannel >> &channelsMap, const std::vector< std::string > &channelList)
FairMQPollerZMQ (const FairMQPollerZMQ &)=delete
FairMQPollerZMQ operator= (const FairMQPollerZMQ &)=delete
void SetItemEvents (zmq_pollitem_t &item, const int type)
virtual void Poll (const int timeout)
virtual bool CheckInput (const int index)
virtual bool CheckOutput (const int index)
virtual bool CheckInput (const std::string channelKey, const int index)
virtual bool CheckOutput (const std::string channelKey, const int index)
virtual ~FairMQPollerZMQ ()
Private Member Functions
FairMQPollerZMQ (const FairMQSocket &cmdSocket, const FairMQSocket &dataSocket)
Private Attributes
zmq_pollitem_t * fItems
int fNumItems
std::unordered_map< std::string, int > fOffsetMap
Friends
class FairMQChannel
class FairMQTransportFactoryZMQ
Detailed Description
Definition at line 30 of file FairMQPollerZMQ.h.
Constructor & Destructor Documentation
FairMQPollerZMQ::FairMQPollerZMQ (const std::vector< FairMQChannel > & channels)
FairMQPollerZMQ::FairMQPollerZMQ (const std::vector< const FairMQChannel * > & channels)
Definition at line 45 of file FairMQPollerZMQ.cxx.
References fItems, fNumItems, and SetItemEvents().
FairMQPollerZMQ::FairMQPollerZMQ (const std::unordered_map< std::string, std::vector< FairMQChannel >> & channelsMap, const std::vector< std::string > & channelList)
FairMQPollerZMQ::FairMQPollerZMQ (const FairMQPollerZMQ &) delete
FairMQPollerZMQ::~FairMQPollerZMQ () virtual
Definition at line 231 of file FairMQPollerZMQ.cxx.
References fItems.
FairMQPollerZMQ::FairMQPollerZMQ (const FairMQSocket & cmdSocket, const FairMQSocket & dataSocket) private
Definition at line 113 of file FairMQPollerZMQ.cxx.
References fItems, fNumItems, FairMQSocket::GetSocket(), and SetItemEvents().
Member Function Documentation
bool FairMQPollerZMQ::CheckInput (const int index) virtual
Implements FairMQPoller.
Definition at line 173 of file FairMQPollerZMQ.cxx.
References fItems.
virtual bool FairMQPollerZMQ::CheckInput (const std::string channelKey, const int index) virtual
Implements FairMQPoller.
bool FairMQPollerZMQ::CheckOutput (const int index) virtual
Implements FairMQPoller.
Definition at line 183 of file FairMQPollerZMQ.cxx.
References fItems.
virtual bool FairMQPollerZMQ::CheckOutput (const std::string channelKey, const int index) virtual
Implements FairMQPoller.
FairMQPollerZMQ FairMQPollerZMQ::operator= (const FairMQPollerZMQ &) delete
void FairMQPollerZMQ::Poll (const int timeout) virtual
Implements FairMQPoller.
Definition at line 157 of file FairMQPollerZMQ.cxx.
References fItems, and LOG.
void FairMQPollerZMQ::SetItemEvents (zmq_pollitem_t & item, const int type)
Definition at line 136 of file FairMQPollerZMQ.cxx.
References LOG.
Referenced by FairMQPollerZMQ().
Friends And Related Function Documentation
friend class FairMQChannel friend
Definition at line 32 of file FairMQPollerZMQ.h.
friend class FairMQTransportFactoryZMQ friend
Definition at line 33 of file FairMQPollerZMQ.h.
Member Data Documentation
zmq_pollitem_t* FairMQPollerZMQ::fItems private
Definition at line 56 of file FairMQPollerZMQ.h.
Referenced by CheckInput(), CheckOutput(), FairMQPollerZMQ(), Poll(), and ~FairMQPollerZMQ().
int FairMQPollerZMQ::fNumItems private
Definition at line 57 of file FairMQPollerZMQ.h.
Referenced by FairMQPollerZMQ().
std::unordered_map<std::string, int> FairMQPollerZMQ::fOffsetMap private
Definition at line 59 of file FairMQPollerZMQ.h.
The documentation for this class was generated from the following files:
FairMQPollerZMQ.h
FairMQPollerZMQ.cxx