FairRroot: PixelDigiWriteToBinFile Class Reference
PixelDigiWriteToBinFile Class Reference
#include <PixelDigiWriteToBinFile.h>
Public Member Functions
PixelDigiWriteToBinFile ()
PixelDigiWriteToBinFile (Int_t iVerbose)
PixelDigiWriteToBinFile (const char *name, Int_t iVerbose)
virtual ~PixelDigiWriteToBinFile ()
virtual void Exec (Option_t *opt)
void SetOutputFileName (TString tstr)
void SetDivideLevel (Int_t idiv)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Private Member Functions
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
void Reset ()
virtual void Finish ()
PixelDigiWriteToBinFile (const PixelDigiWriteToBinFile &)
PixelDigiWriteToBinFile & operator= (const PixelDigiWriteToBinFile &)
ClassDef (PixelDigiWriteToBinFile, 1)
Private Attributes
TClonesArray * fDigis
TString fOutputFileName
Int_t fNofOutputFiles
std::ofstream fOutputFiles [12]
Int_t fDivideLevel
Int_t fRunId
Int_t fMCEntryNo
Int_t fPartNo
Detailed Description
Definition at line 28 of file PixelDigiWriteToBinFile.h.
Constructor & Destructor Documentation
PixelDigiWriteToBinFile::PixelDigiWriteToBinFile ()
Default constructor
Definition at line 40 of file PixelDigiWriteToBinFile.cxx.
PixelDigiWriteToBinFile::PixelDigiWriteToBinFile (Int_t iVerbose)
Standard constructor
Definition at line 49 of file PixelDigiWriteToBinFile.cxx.
PixelDigiWriteToBinFile::PixelDigiWriteToBinFile (const char * name, Int_t iVerbose)
Constructor with name
Definition at line 58 of file PixelDigiWriteToBinFile.cxx.
References Reset().
PixelDigiWriteToBinFile::~PixelDigiWriteToBinFile () virtual
Destructor
Definition at line 77 of file PixelDigiWriteToBinFile.cxx.
References Reset().
PixelDigiWriteToBinFile::PixelDigiWriteToBinFile (const PixelDigiWriteToBinFile &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
PixelDigiWriteToBinFile::ClassDef (PixelDigiWriteToBinFile , 1) private
void PixelDigiWriteToBinFile::Exec (Option_t * opt) virtual
Execution
Definition at line 83 of file PixelDigiWriteToBinFile.cxx.
References fDigis, fDivideLevel, fMCEntryNo, fNofOutputFiles, fOutputFiles, fRunId, PixelDigi::GetCol(), PixelDigi::GetDetectorID(), PixelDigi::GetFeID(), PixelDigi::GetRow(), and Reset().
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), LOG, FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), LOG, FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
void PixelDigiWriteToBinFile::Finish () private virtual
Finish at the end of each event
Reimplemented from FairTask.
Definition at line 213 of file PixelDigiWriteToBinFile.cxx.
References fNofOutputFiles, and fOutputFiles.
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
InitStatus PixelDigiWriteToBinFile::Init () private virtual
Intialisation
Reimplemented from FairTask.
Definition at line 144 of file PixelDigiWriteToBinFile.cxx.
References fDigis, fDivideLevel, fNofOutputFiles, fOutputFileName, fOutputFiles, fRunId, FairRootManager::GetObject(), FairRootManager::GetRunId(), FairRootManager::Instance(), kFATAL, kSUCCESS, and LOG.
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, LOG, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
PixelDigiWriteToBinFile& PixelDigiWriteToBinFile::operator= (const PixelDigiWriteToBinFile &) private
InitStatus PixelDigiWriteToBinFile::ReInit () private virtual
Reinitialisation
Reimplemented from FairTask.
Definition at line 190 of file PixelDigiWriteToBinFile.cxx.
References fMCEntryNo, fRunId, FairRootManager::GetRunId(), FairRootManager::Instance(), kFATAL, kSUCCESS, and LOG.
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, LOG, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
void PixelDigiWriteToBinFile::Reset () private
Reset eventwise counters
Definition at line 208 of file PixelDigiWriteToBinFile.cxx.
Referenced by Exec(), PixelDigiWriteToBinFile(), and ~PixelDigiWriteToBinFile().
void PixelDigiWriteToBinFile::SetDivideLevel (Int_t idiv) inline
Definition at line 54 of file PixelDigiWriteToBinFile.h.
References fDivideLevel.
Referenced by run_digiToBin().
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
void PixelDigiWriteToBinFile::SetOutputFileName (TString tstr) inline
Definition at line 52 of file PixelDigiWriteToBinFile.h.
References fOutputFileName.
Referenced by run_digiToBin().
void PixelDigiWriteToBinFile::SetParContainers () private virtual
Get parameter containers
Reimplemented from FairTask.
Definition at line 139 of file PixelDigiWriteToBinFile.cxx.
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
TClonesArray* PixelDigiWriteToBinFile::fDigis private
Definition at line 58 of file PixelDigiWriteToBinFile.h.
Referenced by Exec(), and Init().
Int_t PixelDigiWriteToBinFile::fDivideLevel private
Definition at line 67 of file PixelDigiWriteToBinFile.h.
Referenced by Exec(), Init(), and SetDivideLevel().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
Int_t PixelDigiWriteToBinFile::fMCEntryNo private
Definition at line 70 of file PixelDigiWriteToBinFile.h.
Referenced by Exec(), and ReInit().
Int_t PixelDigiWriteToBinFile::fNofOutputFiles private
Definition at line 61 of file PixelDigiWriteToBinFile.h.
Referenced by Exec(), Finish(), and Init().
TString PixelDigiWriteToBinFile::fOutputFileName private
Input array of PixelDigi
Definition at line 60 of file PixelDigiWriteToBinFile.h.
Referenced by Init(), and SetOutputFileName().
std::ofstream PixelDigiWriteToBinFile::fOutputFiles[12] private
Definition at line 62 of file PixelDigiWriteToBinFile.h.
Referenced by Exec(), Finish(), and Init().
Int_t PixelDigiWriteToBinFile::fPartNo private
Definition at line 71 of file PixelDigiWriteToBinFile.h.
Int_t PixelDigiWriteToBinFile::fRunId private
Definition at line 69 of file PixelDigiWriteToBinFile.h.
Referenced by Exec(), Init(), and ReInit().
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
PixelDigiWriteToBinFile.h
PixelDigiWriteToBinFile.cxx