FairRroot: MyPayloadProto::Hit Class Reference
MyPayloadProto::Hit Class Reference
#include <MyPayload.pb.h>
Public Member Functions
Hit ()
virtual ~Hit ()
Hit (const Hit &from)
Hit & operator= (const Hit &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Hit *other)
Hit * New () const PROTOBUF_FINAL
Hit * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Hit &from)
void MergeFrom (const Hit &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_det_id () const
void clear_det_id ()
::google::protobuf::int32 det_id () const
void set_det_id (::google::protobuf::int32 value)
bool has_mcindex () const
void clear_mcindex ()
::google::protobuf::int32 mcindex () const
void set_mcindex (::google::protobuf::int32 value)
bool has_posx () const
void clear_posx ()
double posx () const
void set_posx (double value)
bool has_posy () const
void clear_posy ()
double posy () const
void set_posy (double value)
bool has_posz () const
void clear_posz ()
double posz () const
void set_posz (double value)
bool has_dposx () const
void clear_dposx ()
double dposx () const
void set_dposx (double value)
bool has_dposy () const
void clear_dposy ()
double dposy () const
void set_dposy (double value)
bool has_dposz () const
void clear_dposz ()
double dposz () const
void set_dposz (double value)
bool has_time_stamp () const
void clear_time_stamp ()
double time_stamp () const
void set_time_stamp (double value)
bool has_time_stamperror () const
void clear_time_stamperror ()
double time_stamperror () const
void set_time_stamperror (double value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Hit & default_instance ()
static const Hit * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kDetIdFieldNumber = 1
static const int kMcindexFieldNumber = 2
static const int kPosxFieldNumber = 3
static const int kPosyFieldNumber = 4
static const int kPoszFieldNumber = 5
static const int kDposxFieldNumber = 6
static const int kDposyFieldNumber = 7
static const int kDposzFieldNumber = 8
static const int kTimeStampFieldNumber = 9
static const int kTimeStamperrorFieldNumber = 10
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Hit *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_det_id ()
void clear_has_det_id ()
void set_has_mcindex ()
void clear_has_mcindex ()
void set_has_posx ()
void clear_has_posx ()
void set_has_posy ()
void clear_has_posy ()
void set_has_posz ()
void clear_has_posz ()
void set_has_dposx ()
void clear_has_dposx ()
void set_has_dposy ()
void clear_has_dposy ()
void set_has_dposz ()
void clear_has_dposz ()
void set_has_time_stamp ()
void clear_has_time_stamp ()
void set_has_time_stamperror ()
void clear_has_time_stamperror ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::int32 det_id_
::google::protobuf::int32 mcindex_
double posx_
double posy_
double posz_
double dposx_
double dposy_
double dposz_
double time_stamp_
double time_stamperror_
Friends
struct protobuf_MyPayload_2eproto::TableStruct
void swap (Hit &a, Hit &b)
Detailed Description
Definition at line 215 of file MyPayload.pb.h.
Constructor & Destructor Documentation
MyPayloadProto::Hit::Hit ()
virtual MyPayloadProto::Hit::~Hit () virtual
MyPayloadProto::Hit::Hit (const Hit & from)
Member Function Documentation
size_t MyPayloadProto::Hit::ByteSizeLong () const
void MyPayloadProto::Hit::Clear ()
void MyPayloadProto::Hit::clear_det_id () inline
Definition at line 815 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_dposx () inline
Definition at line 935 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_dposy () inline
Definition at line 959 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_dposz () inline
Definition at line 983 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_det_id () inline private
Definition at line 812 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_dposx () inline private
Definition at line 932 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_dposy () inline private
Definition at line 956 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_dposz () inline private
Definition at line 980 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_mcindex () inline private
Definition at line 836 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_posx () inline private
Definition at line 860 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_posy () inline private
Definition at line 884 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_posz () inline private
Definition at line 908 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_time_stamp () inline private
Definition at line 1004 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_has_time_stamperror () inline private
Definition at line 1028 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_mcindex () inline
Definition at line 839 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_posx () inline
Definition at line 863 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_posy () inline
Definition at line 887 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_posz () inline
Definition at line 911 of file MyPayload.pb.h.
void MyPayloadProto::Hit::clear_time_stamp () inline
Definition at line 1007 of file MyPayload.pb.h.
References MyPayloadProto::Digi::clear_has_time_stamp().
void MyPayloadProto::Hit::clear_time_stamperror () inline
Definition at line 1031 of file MyPayload.pb.h.
References MyPayloadProto::Digi::clear_has_time_stamperror().
void MyPayloadProto::Hit::CopyFrom (const ::google::protobuf::Message & from)
void MyPayloadProto::Hit::CopyFrom (const Hit & from)
static const Hit& MyPayloadProto::Hit::default_instance () static
static const ::google::protobuf::Descriptor* MyPayloadProto::Hit::descriptor () static
google::protobuf::int32 MyPayloadProto::Hit::det_id () const inline
Definition at line 819 of file MyPayload.pb.h.
double MyPayloadProto::Hit::dposx () const inline
Definition at line 939 of file MyPayload.pb.h.
double MyPayloadProto::Hit::dposy () const inline
Definition at line 963 of file MyPayload.pb.h.
double MyPayloadProto::Hit::dposz () const inline
Definition at line 987 of file MyPayload.pb.h.
inline ::google::protobuf::Arena* MyPayloadProto::Hit::GetArenaNoVirtual () const inline private
Definition at line 289 of file MyPayload.pb.h.
int MyPayloadProto::Hit::GetCachedSize () const inline
Definition at line 282 of file MyPayload.pb.h.
References MyPayloadProto::Digi::_cached_size_.
::google::protobuf::Metadata MyPayloadProto::Hit::GetMetadata () const
bool MyPayloadProto::Hit::has_det_id () const inline
Definition at line 806 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_dposx () const inline
Definition at line 926 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_dposy () const inline
Definition at line 950 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_dposz () const inline
Definition at line 974 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_mcindex () const inline
Definition at line 830 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_posx () const inline
Definition at line 854 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_posy () const inline
Definition at line 878 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_posz () const inline
Definition at line 902 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_time_stamp () const inline
Definition at line 998 of file MyPayload.pb.h.
bool MyPayloadProto::Hit::has_time_stamperror () const inline
Definition at line 1022 of file MyPayload.pb.h.
static const Hit* MyPayloadProto::Hit::internal_default_instance () inline static
Definition at line 251 of file MyPayload.pb.h.
References MyPayloadProto::_Hit_default_instance_.
::google::protobuf::uint8* MyPayloadProto::Hit::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void MyPayloadProto::Hit::InternalSwap (Hit * other) private
bool MyPayloadProto::Hit::IsInitialized () const
void* MyPayloadProto::Hit::MaybeArenaPtr () const inline private
Definition at line 292 of file MyPayload.pb.h.
google::protobuf::int32 MyPayloadProto::Hit::mcindex () const inline
Definition at line 843 of file MyPayload.pb.h.
void MyPayloadProto::Hit::MergeFrom (const ::google::protobuf::Message & from)
void MyPayloadProto::Hit::MergeFrom (const Hit & from)
bool MyPayloadProto::Hit::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* MyPayloadProto::Hit::mutable_unknown_fields () inline
Definition at line 244 of file MyPayload.pb.h.
Hit* MyPayloadProto::Hit::New () const inline
Definition at line 265 of file MyPayload.pb.h.
References New().
Referenced by New().
Hit* MyPayloadProto::Hit::New (::google::protobuf::Arena * arena) const
Hit& MyPayloadProto::Hit::operator= (const Hit & from) inline
Definition at line 222 of file MyPayload.pb.h.
References MyPayloadProto::Digi::CopyFrom().
double MyPayloadProto::Hit::posx () const inline
Definition at line 867 of file MyPayload.pb.h.
double MyPayloadProto::Hit::posy () const inline
Definition at line 891 of file MyPayload.pb.h.
double MyPayloadProto::Hit::posz () const inline
Definition at line 915 of file MyPayload.pb.h.
void MyPayloadProto::Hit::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void MyPayloadProto::Hit::set_det_id (::google::protobuf::int32 value) inline
Definition at line 823 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_dposx (double value) inline
Definition at line 943 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_dposy (double value) inline
Definition at line 967 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_dposz (double value) inline
Definition at line 991 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_det_id () inline private
Definition at line 809 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_dposx () inline private
Definition at line 929 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_dposy () inline private
Definition at line 953 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_dposz () inline private
Definition at line 977 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_mcindex () inline private
Definition at line 833 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_posx () inline private
Definition at line 857 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_posy () inline private
Definition at line 881 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_posz () inline private
Definition at line 905 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_time_stamp () inline private
Definition at line 1001 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_has_time_stamperror () inline private
Definition at line 1025 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_mcindex (::google::protobuf::int32 value) inline
Definition at line 847 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_posx (double value) inline
Definition at line 871 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_posy (double value) inline
Definition at line 895 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_posz (double value) inline
Definition at line 919 of file MyPayload.pb.h.
void MyPayloadProto::Hit::set_time_stamp (double value) inline
Definition at line 1015 of file MyPayload.pb.h.
References MyPayloadProto::Digi::set_has_time_stamp().
void MyPayloadProto::Hit::set_time_stamperror (double value) inline
Definition at line 1039 of file MyPayload.pb.h.
References MyPayloadProto::Digi::set_has_time_stamperror().
void MyPayloadProto::Hit::SetCachedSize (int size) const private
void MyPayloadProto::Hit::SharedCtor () private
void MyPayloadProto::Hit::SharedDtor () private
void MyPayloadProto::Hit::Swap (Hit * other)
double MyPayloadProto::Hit::time_stamp () const inline
Definition at line 1011 of file MyPayload.pb.h.
References MyPayloadProto::Digi::time_stamp_.
double MyPayloadProto::Hit::time_stamperror () const inline
Definition at line 1035 of file MyPayload.pb.h.
References MyPayloadProto::Digi::time_stamperror_.
const ::google::protobuf::UnknownFieldSet& MyPayloadProto::Hit::unknown_fields () const inline
Definition at line 241 of file MyPayload.pb.h.
Friends And Related Function Documentation
friend struct protobuf_MyPayload_2eproto::TableStruct friend
Definition at line 409 of file MyPayload.pb.h.
void swap (Hit & a, Hit & b) friend
Definition at line 259 of file MyPayload.pb.h.
Member Data Documentation
int MyPayloadProto::Hit::_cached_size_ mutable private
Definition at line 398 of file MyPayload.pb.h.
::google::protobuf::internal::HasBits<1> MyPayloadProto::Hit::_has_bits_ private
Definition at line 397 of file MyPayload.pb.h.
::google::protobuf::internal::InternalMetadataWithArena MyPayloadProto::Hit::_internal_metadata_ private
Definition at line 396 of file MyPayload.pb.h.
::google::protobuf::int32 MyPayloadProto::Hit::det_id_ private
Definition at line 399 of file MyPayload.pb.h.
double MyPayloadProto::Hit::dposx_ private
Definition at line 404 of file MyPayload.pb.h.
double MyPayloadProto::Hit::dposy_ private
Definition at line 405 of file MyPayload.pb.h.
double MyPayloadProto::Hit::dposz_ private
Definition at line 406 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kDetIdFieldNumber = 1 static
Definition at line 306 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kDposxFieldNumber = 6 static
Definition at line 341 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kDposyFieldNumber = 7 static
Definition at line 348 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kDposzFieldNumber = 8 static
Definition at line 355 of file MyPayload.pb.h.
PROTOBUF_CONSTEXPR int const MyPayloadProto::Hit::kIndexInFileMessages static
Initial value:
=
    1
Definition at line 255 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kMcindexFieldNumber = 2 static
Definition at line 313 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kPosxFieldNumber = 3 static
Definition at line 320 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kPosyFieldNumber = 4 static
Definition at line 327 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kPoszFieldNumber = 5 static
Definition at line 334 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kTimeStamperrorFieldNumber = 10 static
Definition at line 369 of file MyPayload.pb.h.
const int MyPayloadProto::Hit::kTimeStampFieldNumber = 9 static
Definition at line 362 of file MyPayload.pb.h.
::google::protobuf::int32 MyPayloadProto::Hit::mcindex_ private
Definition at line 400 of file MyPayload.pb.h.
double MyPayloadProto::Hit::posx_ private
Definition at line 401 of file MyPayload.pb.h.
double MyPayloadProto::Hit::posy_ private
Definition at line 402 of file MyPayload.pb.h.
double MyPayloadProto::Hit::posz_ private
Definition at line 403 of file MyPayload.pb.h.
double MyPayloadProto::Hit::time_stamp_ private
Definition at line 407 of file MyPayload.pb.h.
double MyPayloadProto::Hit::time_stamperror_ private
Definition at line 408 of file MyPayload.pb.h.
The documentation for this class was generated from the following file:
MyPayload.pb.h