FairRroot: FairMQPollerSHM Class Reference
FairMQPollerSHM Class Reference
#include <FairMQPollerSHM.h>
Public Member Functions
FairMQPollerSHM (const std::vector< FairMQChannel > &channels)
FairMQPollerSHM (const std::vector< const FairMQChannel * > &channels)
FairMQPollerSHM (const std::unordered_map< std::string, std::vector< FairMQChannel >> &channelsMap, const std::vector< std::string > &channelList)
FairMQPollerSHM (const FairMQPollerSHM &)=delete
FairMQPollerSHM operator= (const FairMQPollerSHM &)=delete
void SetItemEvents (zmq_pollitem_t &item, const int type)
void Poll (const int timeout) override
bool CheckInput (const int index) override
bool CheckOutput (const int index) override
bool CheckInput (const std::string channelKey, const int index) override
bool CheckOutput (const std::string channelKey, const int index) override
~FairMQPollerSHM () override
Private Member Functions
FairMQPollerSHM (const FairMQSocket &cmdSocket, const FairMQSocket &dataSocket)
Private Attributes
zmq_pollitem_t * fItems
int fNumItems
std::unordered_map< std::string, int > fOffsetMap
Friends
class FairMQChannel
class FairMQTransportFactorySHM
Detailed Description
Definition at line 22 of file FairMQPollerSHM.h.
Constructor & Destructor Documentation
FairMQPollerSHM::FairMQPollerSHM (const std::vector< FairMQChannel > & channels)
FairMQPollerSHM::FairMQPollerSHM (const std::vector< const FairMQChannel * > & channels)
FairMQPollerSHM::FairMQPollerSHM (const std::unordered_map< std::string, std::vector< FairMQChannel >> & channelsMap, const std::vector< std::string > & channelList)
FairMQPollerSHM::FairMQPollerSHM (const FairMQPollerSHM &) delete
FairMQPollerSHM::~FairMQPollerSHM () override
Definition at line 230 of file FairMQPollerSHM.cxx.
References fItems.
FairMQPollerSHM::FairMQPollerSHM (const FairMQSocket & cmdSocket, const FairMQSocket & dataSocket) private
Definition at line 112 of file FairMQPollerSHM.cxx.
References fItems, fNumItems, FairMQSocket::GetSocket(), and SetItemEvents().
Member Function Documentation
bool FairMQPollerSHM::CheckInput (const int index) override virtual
Implements FairMQPoller.
Definition at line 172 of file FairMQPollerSHM.cxx.
References fItems.
bool FairMQPollerSHM::CheckInput (const std::string channelKey, const int index) override virtual
Implements FairMQPoller.
bool FairMQPollerSHM::CheckOutput (const int index) override virtual
Implements FairMQPoller.
Definition at line 182 of file FairMQPollerSHM.cxx.
References fItems.
bool FairMQPollerSHM::CheckOutput (const std::string channelKey, const int index) override virtual
Implements FairMQPoller.
FairMQPollerSHM FairMQPollerSHM::operator= (const FairMQPollerSHM &) delete
void FairMQPollerSHM::Poll (const int timeout) override virtual
Implements FairMQPoller.
Definition at line 156 of file FairMQPollerSHM.cxx.
References fItems, and LOG.
void FairMQPollerSHM::SetItemEvents (zmq_pollitem_t & item, const int type)
Definition at line 135 of file FairMQPollerSHM.cxx.
References LOG.
Referenced by FairMQPollerSHM().
Friends And Related Function Documentation
friend class FairMQChannel friend
Definition at line 24 of file FairMQPollerSHM.h.
friend class FairMQTransportFactorySHM friend
Definition at line 25 of file FairMQPollerSHM.h.
Member Data Documentation
zmq_pollitem_t* FairMQPollerSHM::fItems private
Definition at line 48 of file FairMQPollerSHM.h.
Referenced by CheckInput(), CheckOutput(), FairMQPollerSHM(), Poll(), and ~FairMQPollerSHM().
int FairMQPollerSHM::fNumItems private
Definition at line 49 of file FairMQPollerSHM.h.
Referenced by FairMQPollerSHM().
std::unordered_map<std::string, int> FairMQPollerSHM::fOffsetMap private
Definition at line 51 of file FairMQPollerSHM.h.
The documentation for this class was generated from the following files:
FairMQPollerSHM.h
FairMQPollerSHM.cxx