FairRoot: PixelDigiPar Class Reference
PixelDigiPar Class Reference
Digitization Parameter Class for Pixel detector.
#include <PixelDigiPar.h>
Public Member Functions
PixelDigiPar (const char *name="PixelDigiParameters", const char *title="Pixel digi parameters", const char *context="TestDefaultContext")
~PixelDigiPar (void)
void clear (void)
void putParams (FairParamList *list)
Bool_t getParams (FairParamList *list)
void Print (Option_t *) const
Double_t GetXPitch () const
Double_t GetYPitch () const
Double_t GetThreshold () const
Double_t GetNoise () const
Double_t GetQCloudSigma () const
Int_t GetFECols () const
Int_t GetFERows () const
Int_t GetMaxFEperCol () const
Double_t GetClustRadius () const
Double_t GetFeBusClock () const
Double_t GetTimeStep () const
Time step of one clock cycle in ns.
Int_t GetChargeConvMethod () const
Double_t GetPixelSorterCellWidth () const
Int_t GetPixelSorterNumberOfCells () const
void SetXPitch (Double_t x)
void SetYPitch (Double_t x)
void SetThreshold (Double_t x)
void SetNoise (Double_t x)
void SetQCloudSigma (Double_t x)
void SetFECols (Int_t x)
void SetFERows (Int_t x)
void SetMaxFEperCol (Int_t x)
void SetClustRadius (Double_t x)
void SetFeBusClock (Double_t x)
void SetChargeConvMethod (Int_t x)
void SetPixelSorterCellWidth (Double_t x)
void SetPixelSorterNumberOfCells (Int_t x)
virtual void printParams ()
Bool_t init (FairParIo *inp)
virtual Bool_t init ()
Int_t write (FairParIo *output)
virtual Int_t write ()
void fill (UInt_t)
void store (UInt_t)
virtual const char * GetName () const
virtual const char * GetTitle () const
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setOwnership (Bool_t flag=kTRUE)
Bool_t isOwned ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Attributes
TString fName
TString fTitle
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
Bool_t owned
flag is kTRUE if parameters have changed
TString paramContext
if flag is KTRUE FairDB has the par. class ownership
TString author
TString description
FairLogger * fLogger
Private Member Functions
ClassDef (PixelDigiPar, 1)
Private Attributes
Int_t fFeCols
Int_t fFeRows
Int_t fMaxFEperCol
Double_t fDimX
Double_t fDimY
Double_t fRadius
Double_t fThreshold
Double_t fNoise
Double_t fCSigma
Double_t fFeBusClock
Int_t fChargeConvMethod
Double_t fPixelSorterCellWidth
Int_t fPixelSorterNumberOfCells
Detailed Description
Digitization Parameter Class for Pixel detector.
Definition at line 24 of file PixelDigiPar.h.
Constructor & Destructor Documentation
PixelDigiPar()
PixelDigiPar::PixelDigiPar (const char * name = "PixelDigiParameters", const char * title = "Pixel digi parameters", const char * context = "TestDefaultContext")
Definition at line 19 of file PixelDigiPar.cxx.
References clear().
~PixelDigiPar()
PixelDigiPar::~PixelDigiPar (void)
Definition at line 40 of file PixelDigiPar.cxx.
Member Function Documentation
ClassDef()
PixelDigiPar::ClassDef (PixelDigiPar , 1) private
clear()
void PixelDigiPar::clear (void) inline virtual
Reimplemented from FairParSet.
Definition at line 31 of file PixelDigiPar.h.
Referenced by PixelDigiPar().
copyComment()
void FairParSet::copyComment (FairParSet & r) inline inherited
Definition at line 76 of file FairParSet.h.
References FairParSet::author, FairParSet::description, FairParSet::getAuthor(), and FairParSet::getDescription().
fill()
void FairParGenericSet::fill (UInt_t) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 32 of file FairParGenericSet.h.
getAuthor()
const char* FairParSet::getAuthor () const inline inherited
Definition at line 71 of file FairParSet.h.
References FairParSet::author.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
GetChargeConvMethod()
Int_t PixelDigiPar::GetChargeConvMethod () const inline
Definition at line 48 of file PixelDigiPar.h.
References fChargeConvMethod.
GetClustRadius()
Double_t PixelDigiPar::GetClustRadius () const inline
Definition at line 45 of file PixelDigiPar.h.
References fRadius.
getDescription()
const char* FairParSet::getDescription () const inline inherited
Definition at line 74 of file FairParSet.h.
References FairParSet::description.
Referenced by FairParSet::copyComment(), and FairDetParAsciiFileIo::writeComment().
getDetectorName()
const char* FairParSet::getDetectorName () inline inherited
Definition at line 48 of file FairParSet.h.
References FairParSet::detName.
GetFeBusClock()
Double_t PixelDigiPar::GetFeBusClock () const inline
Definition at line 46 of file PixelDigiPar.h.
References fFeBusClock.
GetFECols()
Int_t PixelDigiPar::GetFECols () const inline
Definition at line 42 of file PixelDigiPar.h.
References fFeCols.
Referenced by PixelFindHitsTask::Init(), PixelDigitize::Init(), PixelFindHits::Init(), PixelAltFindHits::Init(), PixelDigitize::InitMQ(), PixelFindHits::InitMQ(), and PixelAltFindHits::InitMQ().
GetFERows()
Int_t PixelDigiPar::GetFERows () const inline
Definition at line 43 of file PixelDigiPar.h.
References fFeRows.
Referenced by PixelFindHitsTask::Init(), PixelDigitize::Init(), PixelFindHits::Init(), PixelAltFindHits::Init(), PixelDigitize::InitMQ(), PixelFindHits::InitMQ(), and PixelAltFindHits::InitMQ().
getInputVersion()
Int_t FairParSet::getInputVersion (Int_t i) inline inherited
Definition at line 54 of file FairParSet.h.
References FairParSet::versions.
Referenced by FairRuntimeDb::findOutputVersion(), FairDetParRootFileIo::read(), and FairRuntimeDb::writeContainer().
GetMaxFEperCol()
Int_t PixelDigiPar::GetMaxFEperCol () const inline
Definition at line 44 of file PixelDigiPar.h.
References fMaxFEperCol.
Referenced by PixelFindHitsTask::Init(), PixelDigitize::Init(), PixelFindHits::Init(), PixelAltFindHits::Init(), PixelDigitize::InitMQ(), PixelFindHits::InitMQ(), and PixelAltFindHits::InitMQ().
GetName()
virtual const char* FairParSet::GetName () const inline virtual inherited
Definition at line 38 of file FairParSet.h.
References FairParSet::fName.
Referenced by FairRuntimeDb::addContainer(), FairRuntimeDb::addRun(), FairRuntimeDb::findOutputVersion(), FairGenericParAsciiFileIo::init(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), FairRuntimeDb::initContainers(), FairParSet::print(), FairRuntimeDb::print(), FairParGenericSet::printParams(), FairDetParRootFileIo::read(), FairGenericParAsciiFileIo::write(), FairDetParRootFileIo::write(), FairParSet::write(), FairRuntimeDb::writeContainer(), FairGenericParAsciiFileIo::writeGenericSet(), and FairRuntimeDb::~FairRuntimeDb().
GetNoise()
Double_t PixelDigiPar::GetNoise () const inline
Definition at line 40 of file PixelDigiPar.h.
References fNoise.
getParamContext()
const char* FairParSet::getParamContext () const inline inherited
Definition at line 68 of file FairParSet.h.
References FairParSet::paramContext.
Referenced by FairGenericParAsciiFileIo::writeGenericSet().
getParams()
Bool_t PixelDigiPar::getParams (FairParamList * list) virtual
Implements FairParGenericSet.
Definition at line 69 of file PixelDigiPar.cxx.
References fChargeConvMethod, fCSigma, fDimX, fDimY, fFeBusClock, fFeCols, fFeRows, FairParamList::fill(), fMaxFEperCol, fNoise, fPixelSorterCellWidth, fPixelSorterNumberOfCells, fRadius, and fThreshold.
GetPixelSorterCellWidth()
Double_t PixelDigiPar::GetPixelSorterCellWidth () const inline
Definition at line 49 of file PixelDigiPar.h.
References fPixelSorterCellWidth.
GetPixelSorterNumberOfCells()
Int_t PixelDigiPar::GetPixelSorterNumberOfCells () const inline
Definition at line 50 of file PixelDigiPar.h.
References fPixelSorterNumberOfCells.
GetQCloudSigma()
Double_t PixelDigiPar::GetQCloudSigma () const inline
Definition at line 41 of file PixelDigiPar.h.
References fCSigma.
GetThreshold()
Double_t PixelDigiPar::GetThreshold () const inline
Definition at line 39 of file PixelDigiPar.h.
References fThreshold.
GetTimeStep()
Double_t PixelDigiPar::GetTimeStep () const inline
Time step of one clock cycle in ns.
Definition at line 47 of file PixelDigiPar.h.
References fFeBusClock.
GetTitle()
virtual const char* FairParSet::GetTitle () const inline virtual inherited
Definition at line 39 of file FairParSet.h.
References FairParSet::fTitle.
Referenced by FairRuntimeDb::print().
GetXPitch()
Double_t PixelDigiPar::GetXPitch () const inline
Definition at line 37 of file PixelDigiPar.h.
References fDimX.
Referenced by PixelFindHitsTask::Init(), PixelDigitize::Init(), PixelFindHits::Init(), PixelAltFindHits::Init(), PixelDigitize::InitMQ(), PixelFindHits::InitMQ(), and PixelAltFindHits::InitMQ().
GetYPitch()
Double_t PixelDigiPar::GetYPitch () const inline
Definition at line 38 of file PixelDigiPar.h.
References fDimY.
Referenced by PixelFindHitsTask::Init(), PixelDigitize::Init(), PixelFindHits::Init(), PixelAltFindHits::Init(), PixelDigitize::InitMQ(), PixelFindHits::InitMQ(), and PixelAltFindHits::InitMQ().
hasChanged()
Bool_t FairParSet::hasChanged () inline inherited
Definition at line 66 of file FairParSet.h.
References FairParSet::changed.
Referenced by FairRuntimeDb::findOutputVersion(), and FairRuntimeDb::writeContainer().
init() [1/2]
Bool_t FairParGenericSet::init (FairParIo * inp) virtual inherited
Reimplemented from FairParSet.
init() [2/2]
Bool_t FairParSet::init () virtual inherited
Definition at line 46 of file FairParSet.cxx.
References FairRuntimeDb::getFirstInput(), FairParSet::GetName(), FairRuntimeDb::getSecondInput(), FairRuntimeDb::instance(), and FairParSet::setInputVersion().
Referenced by FairRuntimeDb::initContainers().
isOwned()
Bool_t FairParSet::isOwned () inline inherited
Definition at line 63 of file FairParSet.h.
References FairParSet::owned.
Referenced by FairRuntimeDb::~FairRuntimeDb().
isStatic()
Bool_t FairParSet::isStatic () inline inherited
Definition at line 60 of file FairParSet.h.
References FairParSet::status.
Referenced by FairRuntimeDb::initContainers(), and FairRuntimeDb::resetInputVersions().
Print()
void PixelDigiPar::Print (Option_t *) const
Definition at line 90 of file PixelDigiPar.cxx.
References fChargeConvMethod, fCSigma, fDimX, fDimY, fFeCols, fFeRows, fMaxFEperCol, fNoise, fRadius, and fThreshold.
print()
void FairParSet::print () virtual inherited
Reimplemented in FairMQExParamsParOne.
Definition at line 84 of file FairParSet.cxx.
References FairParSet::author, FairParSet::changed, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParSet::status, and FairParSet::versions.
Referenced by create_digis(), create_digis_mixed(), read_digis(), and FairRuntimeDb::writeContainer().
printParams()
void FairParGenericSet::printParams () virtual inherited
Definition at line 59 of file FairParGenericSet.cxx.
References FairParSet::author, FairParSet::description, FairParSet::GetName(), FairParSet::paramContext, FairParamList::print(), and FairParGenericSet::putParams().
Referenced by PixelFindHitsTask::Init(), and read_digis().
putParams()
void PixelDigiPar::putParams (FairParamList * list) virtual
Implements FairParGenericSet.
Definition at line 45 of file PixelDigiPar.cxx.
References FairParamList::add(), fChargeConvMethod, fCSigma, fDimX, fDimY, fFeBusClock, fFeCols, fFeRows, fMaxFEperCol, fNoise, fPixelSorterCellWidth, fPixelSorterNumberOfCells, fRadius, and fThreshold.
resetInputVersions()
void FairParSet::resetInputVersions () inherited
Definition at line 99 of file FairParSet.cxx.
References FairParSet::changed, FairParSet::status, and FairParSet::versions.
Referenced by FairMQExParamsParOne::clear(), FairTutorialDet2DigiPar::clear(), and FairRuntimeDb::resetInputVersions().
setAuthor()
void FairParSet::setAuthor (const char * s) inline inherited
Definition at line 70 of file FairParSet.h.
References FairParSet::author.
Referenced by FairDetParAsciiFileIo::readComment().
setChanged()
void FairParSet::setChanged (Bool_t flag = kTRUE) inline inherited
Definition at line 65 of file FairParSet.h.
References FairParSet::changed.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), create_digis(), create_digis_mixed(), FairConstField::FillParContainer(), for(), FairRunOnline::Init(), FairRunSim::Init(), FairTutorialDet4::Initialize(), FairDetParRootFileIo::read(), read_digis(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), FairTutorialDet4::SetSensitiveVolumes(), FairDetParRootFileIo::write(), FairRuntimeDb::writeContainer(), and FairGenericParAsciiFileIo::writeGenericSet().
SetChargeConvMethod()
void PixelDigiPar::SetChargeConvMethod (Int_t x) inline
Definition at line 62 of file PixelDigiPar.h.
References fChargeConvMethod.
SetClustRadius()
void PixelDigiPar::SetClustRadius (Double_t x) inline
Definition at line 60 of file PixelDigiPar.h.
References fRadius.
setDescription()
void FairParSet::setDescription (const char * s) inline inherited
Definition at line 73 of file FairParSet.h.
References FairParSet::description.
Referenced by FairDetParAsciiFileIo::readComment(), and FairMQSimDevice::UpdateParameterServer().
SetFeBusClock()
void PixelDigiPar::SetFeBusClock (Double_t x) inline
Definition at line 61 of file PixelDigiPar.h.
References fFeBusClock.
SetFECols()
void PixelDigiPar::SetFECols (Int_t x) inline
Definition at line 57 of file PixelDigiPar.h.
References fFeCols.
SetFERows()
void PixelDigiPar::SetFERows (Int_t x) inline
Definition at line 58 of file PixelDigiPar.h.
References fFeRows.
setInputVersion()
void FairParSet::setInputVersion (Int_t v = -1, Int_t i = 0) inline inherited
Definition at line 51 of file FairParSet.h.
References FairParSet::versions.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), create_digis(), create_digis_mixed(), FairConstField::FillParContainer(), FairParSet::init(), FairRunOnline::Init(), FairRunSim::Init(), FairTutorialDet4::Initialize(), FairDetParRootFileIo::read(), read_digis(), FairTutorialDet2::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), and FairTutorialDet4::SetSensitiveVolumes().
SetMaxFEperCol()
void PixelDigiPar::SetMaxFEperCol (Int_t x) inline
Definition at line 59 of file PixelDigiPar.h.
References fMaxFEperCol.
SetNoise()
void PixelDigiPar::SetNoise (Double_t x) inline
Definition at line 55 of file PixelDigiPar.h.
References fNoise.
setOwnership()
void FairParSet::setOwnership (Bool_t flag = kTRUE) inline inherited
Definition at line 62 of file FairParSet.h.
References FairParSet::owned.
SetPixelSorterCellWidth()
void PixelDigiPar::SetPixelSorterCellWidth (Double_t x) inline
Definition at line 63 of file PixelDigiPar.h.
References fPixelSorterCellWidth.
SetPixelSorterNumberOfCells()
void PixelDigiPar::SetPixelSorterNumberOfCells (Int_t x) inline
Definition at line 64 of file PixelDigiPar.h.
References fPixelSorterNumberOfCells.
SetQCloudSigma()
void PixelDigiPar::SetQCloudSigma (Double_t x) inline
Definition at line 56 of file PixelDigiPar.h.
References fCSigma.
setStatic()
void FairParSet::setStatic (Bool_t flag = kTRUE) inline inherited
Definition at line 59 of file FairParSet.h.
References FairParSet::status.
Referenced by FairRuntimeDb::setContainersStatic().
SetThreshold()
void PixelDigiPar::SetThreshold (Double_t x) inline
Definition at line 54 of file PixelDigiPar.h.
References fThreshold.
SetXPitch()
void PixelDigiPar::SetXPitch (Double_t x) inline
Definition at line 52 of file PixelDigiPar.h.
References fDimX.
SetYPitch()
void PixelDigiPar::SetYPitch (Double_t x) inline
Definition at line 53 of file PixelDigiPar.h.
References fDimY.
store()
void FairParGenericSet::store (UInt_t) inline virtual inherited
Reimplemented from FairParSet.
Definition at line 33 of file FairParGenericSet.h.
write() [1/2]
Int_t FairParGenericSet::write (FairParIo * output) virtual inherited
Reimplemented from FairParSet.
Definition at line 50 of file FairParGenericSet.cxx.
References FairParIo::getDetParIo(), and FairDetParIo::write().
write() [2/2]
Int_t FairParSet::write () virtual inherited
Definition at line 72 of file FairParSet.cxx.
References FairParSet::GetName(), FairRuntimeDb::getOutput(), and FairRuntimeDb::instance().
Referenced by FairRuntimeDb::writeContainer().
Member Data Documentation
author
TString FairParSet::author protected inherited
Definition at line 29 of file FairParSet.h.
Referenced by FairParSet::copyComment(), FairParSet::getAuthor(), FairParSet::operator=(), FairParSet::print(), FairParGenericSet::printParams(), and FairParSet::setAuthor().
changed
Bool_t FairParSet::changed protected inherited
static flag
Definition at line 26 of file FairParSet.h.
Referenced by FairParSet::hasChanged(), FairParSet::operator=(), FairParSet::print(), FairParSet::resetInputVersions(), and FairParSet::setChanged().
description
TString FairParSet::description protected inherited
Definition at line 30 of file FairParSet.h.
Referenced by FairParSet::copyComment(), FairParSet::getDescription(), FairParSet::operator=(), FairParSet::print(), FairParGenericSet::printParams(), and FairParSet::setDescription().
detName
TString FairParSet::detName protected inherited
Definition at line 23 of file FairParSet.h.
Referenced by FairMQExParamsParOne::FairMQExParamsParOne(), FairTutorialDet2DigiPar::FairTutorialDet2DigiPar(), FairParSet::getDetectorName(), and FairParSet::operator=().
fChargeConvMethod
Int_t PixelDigiPar::fChargeConvMethod private
Definition at line 78 of file PixelDigiPar.h.
Referenced by GetChargeConvMethod(), getParams(), Print(), putParams(), and SetChargeConvMethod().
fCSigma
Double_t PixelDigiPar::fCSigma private
Definition at line 76 of file PixelDigiPar.h.
Referenced by getParams(), GetQCloudSigma(), Print(), putParams(), and SetQCloudSigma().
fDimX
Double_t PixelDigiPar::fDimX private
Definition at line 71 of file PixelDigiPar.h.
Referenced by getParams(), GetXPitch(), Print(), putParams(), and SetXPitch().
fDimY
Double_t PixelDigiPar::fDimY private
Definition at line 72 of file PixelDigiPar.h.
Referenced by getParams(), GetYPitch(), Print(), putParams(), and SetYPitch().
fFeBusClock
Double_t PixelDigiPar::fFeBusClock private
Definition at line 77 of file PixelDigiPar.h.
Referenced by GetFeBusClock(), getParams(), GetTimeStep(), putParams(), and SetFeBusClock().
fFeCols
Int_t PixelDigiPar::fFeCols private
Definition at line 68 of file PixelDigiPar.h.
Referenced by GetFECols(), getParams(), Print(), putParams(), and SetFECols().
fFeRows
Int_t PixelDigiPar::fFeRows private
Definition at line 69 of file PixelDigiPar.h.
Referenced by GetFERows(), getParams(), Print(), putParams(), and SetFERows().
fLogger
FairLogger* FairParSet::fLogger protected inherited
Fair Logger
Definition at line 32 of file FairParSet.h.
Referenced by FairParSet::operator=().
fMaxFEperCol
Int_t PixelDigiPar::fMaxFEperCol private
Definition at line 70 of file PixelDigiPar.h.
Referenced by GetMaxFEperCol(), getParams(), Print(), putParams(), and SetMaxFEperCol().
fName
TString FairParSet::fName protected inherited
Definition at line 21 of file FairParSet.h.
Referenced by ClassImp(), FairBaseContFact::FairBaseContFact(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), FairParSet::GetName(), MyPassiveContFact::MyPassiveContFact(), FairParSet::operator=(), and PixelContFact::PixelContFact().
fNoise
Double_t PixelDigiPar::fNoise private
Definition at line 75 of file PixelDigiPar.h.
Referenced by GetNoise(), getParams(), Print(), putParams(), and SetNoise().
fPixelSorterCellWidth
Double_t PixelDigiPar::fPixelSorterCellWidth private
Definition at line 79 of file PixelDigiPar.h.
Referenced by getParams(), GetPixelSorterCellWidth(), putParams(), and SetPixelSorterCellWidth().
fPixelSorterNumberOfCells
Int_t PixelDigiPar::fPixelSorterNumberOfCells private
Definition at line 80 of file PixelDigiPar.h.
Referenced by getParams(), GetPixelSorterNumberOfCells(), putParams(), and SetPixelSorterNumberOfCells().
fRadius
Double_t PixelDigiPar::fRadius private
Definition at line 73 of file PixelDigiPar.h.
Referenced by GetClustRadius(), getParams(), Print(), putParams(), and SetClustRadius().
fThreshold
Double_t PixelDigiPar::fThreshold private
Definition at line 74 of file PixelDigiPar.h.
Referenced by getParams(), GetThreshold(), Print(), putParams(), and SetThreshold().
fTitle
TString FairParSet::fTitle protected inherited
Definition at line 22 of file FairParSet.h.
Referenced by FairBaseContFact::FairBaseContFact(), FairPassiveContFact::FairPassiveContFact(), FairRutherfordContFact::FairRutherfordContFact(), FairTestDetectorContFact::FairTestDetectorContFact(), FairTutorialDet1ContFact::FairTutorialDet1ContFact(), FairTutorialDet4ContFact::FairTutorialDet4ContFact(), FairParSet::GetTitle(), MyPassiveContFact::MyPassiveContFact(), FairParSet::operator=(), and PixelContFact::PixelContFact().
owned
Bool_t FairParSet::owned protected inherited
flag is kTRUE if parameters have changed
Definition at line 27 of file FairParSet.h.
Referenced by FairParSet::isOwned(), FairParSet::operator=(), and FairParSet::setOwnership().
paramContext
TString FairParSet::paramContext protected inherited
if flag is KTRUE FairDB has the par. class ownership
Definition at line 28 of file FairParSet.h.
Referenced by FairParSet::getParamContext(), FairParSet::operator=(), FairParSet::print(), and FairParGenericSet::printParams().
status
Bool_t FairParSet::status protected inherited
versions of container in the 2 possible inputs
Definition at line 25 of file FairParSet.h.
Referenced by FairMQExParamsParOne::clear(), FairTutorialDet2DigiPar::clear(), FairParSet::isStatic(), FairParSet::operator=(), FairParSet::print(), FairParSet::resetInputVersions(), and FairParSet::setStatic().
versions
Int_t FairParSet::versions[3] protected inherited
name of the detector the container belongs to
Definition at line 24 of file FairParSet.h.
Referenced by FairParSet::FairParSet(), FairParSet::getInputVersion(), FairParSet::operator=(), FairParSet::print(), FairParSet::resetInputVersions(), and FairParSet::setInputVersion().
The documentation for this class was generated from the following files:
PixelDigiPar.h
PixelDigiPar.cxx