FairRoot: MyConstField Class Reference
MyConstField Class Reference
#include <MyConstField.h>
Public Member Functions
MyConstField ()
MyConstField (const char *name, Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax, Double_t bX, Double_t bY, Double_t bZ)
MyConstField (MyFieldPar *fieldPar)
virtual ~MyConstField ()
void SetFieldRegion (Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax)
void SetField (Double_t bX, Double_t bY, Double_t bZ)
virtual Double_t GetBx (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBy (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBz (Double_t x, Double_t y, Double_t z)
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
Double_t GetBx () const
Double_t GetBy () const
Double_t GetBz () const
virtual void Print ()
virtual void Init ()
Bool_t IsConst ()
Bool_t IsMap ()
Int_t GetType () const
virtual void GetFieldValue (const Double_t point[3], Double_t *bField)
void Field (const Double_t point[3], Double_t *B)
virtual void Print (Option_t *) const
virtual void GetBxyz (const Double_t[3], Double_t *)
virtual void FillParContainer ()
Protected Attributes
Int_t fType
Private Member Functions
ClassDef (MyConstField, 1)
Private Attributes
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
Double_t fBx
Double_t fBy
Double_t fBz
Detailed Description
Definition at line 34 of file MyConstField.h.
Constructor & Destructor Documentation
MyConstField() [1/3]
MyConstField::MyConstField ()
Default constructor
Definition at line 28 of file MyConstField.cxx.
References FairField::fType.
MyConstField() [2/3]
MyConstField::MyConstField (const char * name, Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax, Double_t bX, Double_t bY, Double_t bZ)
Standard constructor
Parameters
name Object name
xMin,xMax x region of field (global coordinates)
yMin,yMax y region of field (global coordinates)
zMin,zMax z region of field (global coordinates)
bX,bY,bZ Field values [kG]
Definition at line 47 of file MyConstField.cxx.
References FairField::fType.
MyConstField() [3/3]
MyConstField::MyConstField (MyFieldPar * fieldPar)
Constructor from MyFieldPar
Definition at line 70 of file MyConstField.cxx.
References fBx, fBy, fBz, FairField::fType, fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, MyFieldPar::GetBx(), MyFieldPar::GetBy(), MyFieldPar::GetBz(), MyFieldPar::GetType(), MyFieldPar::GetXmax(), MyFieldPar::GetXmin(), MyFieldPar::GetYmax(), MyFieldPar::GetYmin(), MyFieldPar::GetZmax(), and MyFieldPar::GetZmin().
~MyConstField()
MyConstField::~MyConstField () virtual
Destructor
Definition at line 105 of file MyConstField.cxx.
Member Function Documentation
ClassDef()
MyConstField::ClassDef (MyConstField , 1) private
Field()
void FairField::Field (const Double_t point[3], Double_t * B) inline inherited
Definition at line 101 of file FairField.h.
References FairField::GetFieldValue().
FillParContainer()
virtual void FairField::FillParContainer () inline virtual inherited
Fill Paramater
Reimplemented in FairConstField.
Definition at line 112 of file FairField.h.
Referenced by FairRunOnline::Init(), and FairRunSim::SetFieldContainer().
GetBx() [1/2]
Double_t MyConstField::GetBx (Double_t x, Double_t y, Double_t z) virtual
Get components of field at a given point
Parameters
x,y,z Point coordinates [cm]
Reimplemented from FairField.
Definition at line 136 of file MyConstField.cxx.
References fBx, fXmax, fYmax, and fZmax.
Referenced by MyFieldPar::SetParameters().
GetBx() [2/2]
Double_t MyConstField::GetBx () const inline
Accessors to field values
Definition at line 96 of file MyConstField.h.
References fBx.
GetBxyz()
virtual void FairField::GetBxyz (const Double_t [3], Double_t *) inline virtual inherited
Definition at line 106 of file FairField.h.
GetBy() [1/2]
Double_t MyConstField::GetBy (Double_t , Double_t , Double_t) virtual
Get y component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Reimplemented from FairField.
Definition at line 147 of file MyConstField.cxx.
References fBy, fXmax, fYmax, and fZmax.
Referenced by MyFieldPar::SetParameters().
GetBy() [2/2]
Double_t MyConstField::GetBy () const inline
Definition at line 97 of file MyConstField.h.
References fBy.
GetBz() [1/2]
Double_t MyConstField::GetBz (Double_t , Double_t , Double_t) virtual
Get z component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Reimplemented from FairField.
Definition at line 158 of file MyConstField.cxx.
References fBz, fXmax, fYmax, and fZmax.
Referenced by MyFieldPar::SetParameters().
GetBz() [2/2]
Double_t MyConstField::GetBz () const inline
Definition at line 98 of file MyConstField.h.
References fBz.
GetFieldValue()
void FairField::GetFieldValue (const Double_t point[3], Double_t * bField) virtual inherited
Get magnetic field. For use of GEANT3
Parameters
point Coordinates [cm]
bField (return) Field components [kG]
Definition at line 60 of file FairField.cxx.
References FairField::GetBx(), FairField::GetBy(), and FairField::GetBz().
Referenced by FairField::Field(), FairTrackPar::GetFieldValue(), and FairRKPropagator::OneStepRungeKutta().
GetType()
Int_t FairField::GetType () const inline inherited
Field type (0=constant, 1=map, 2=map sym2, 3 = map sym3)
Definition at line 74 of file FairField.h.
References FairField::fType.
Referenced by FairConstPar::SetParameters(), and MyFieldPar::SetParameters().
GetXmax()
Double_t MyConstField::GetXmax () const inline
Definition at line 88 of file MyConstField.h.
References fXmax.
Referenced by MyFieldPar::SetParameters().
GetXmin()
Double_t MyConstField::GetXmin () const inline
Accessors to field region
Definition at line 87 of file MyConstField.h.
References fXmin.
Referenced by MyFieldPar::SetParameters().
GetYmax()
Double_t MyConstField::GetYmax () const inline
Definition at line 90 of file MyConstField.h.
References fYmax.
Referenced by MyFieldPar::SetParameters().
GetYmin()
Double_t MyConstField::GetYmin () const inline
Definition at line 89 of file MyConstField.h.
References fYmin.
Referenced by MyFieldPar::SetParameters().
GetZmax()
Double_t MyConstField::GetZmax () const inline
Definition at line 92 of file MyConstField.h.
References fZmax.
Referenced by MyFieldPar::SetParameters().
GetZmin()
Double_t MyConstField::GetZmin () const inline
Definition at line 91 of file MyConstField.h.
References fZmin.
Referenced by MyFieldPar::SetParameters().
Init()
virtual void FairField::Init () inline virtual inherited
Intialisation. E.g. read in the field map. If needed, to be implemented in the concrete class.
Definition at line 63 of file FairField.h.
Referenced by MyFieldCreator::createFairField(), FairRunOnline::Init(), and FairRunSim::Init().
IsConst()
Bool_t FairField::IsConst () inherited
Test whether field type is Constant
Definition at line 44 of file FairField.cxx.
References FairField::fType.
IsMap()
Bool_t FairField::IsMap () inherited
Test whether field typ is Map
Definition at line 54 of file FairField.cxx.
References FairField::fType.
Print() [1/2]
void MyConstField::Print () virtual
Screen output
Definition at line 169 of file MyConstField.cxx.
References fBx, fBy, fBz, fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
Print() [2/2]
virtual void FairField::Print (Option_t *) const inline virtual inherited
Screen output. To be implemented in the concrete class.
Reimplemented in FairConstField.
Definition at line 105 of file FairField.h.
Referenced by MyFieldCreator::createFairField(), and FairGeane::Init().
SetField()
void MyConstField::SetField (Double_t bX, Double_t bY, Double_t bZ)
Set the field values
Parameters
bX,bY,bZ Field values [kG]
Definition at line 126 of file MyConstField.cxx.
References fBx, fBy, and fBz.
Referenced by run_sim().
SetFieldRegion()
void MyConstField::SetFieldRegion (Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax)
Set the field region
Parameters
xMin,xMax x region of field (global coordinates)
yMin,yMax y region of field (global coordinates)
zMin,zMax z region of field (global coordinates)
Definition at line 111 of file MyConstField.cxx.
References fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
Referenced by run_sim().
Member Data Documentation
fBx
Double_t MyConstField::fBx private
Field components inside the field region
Definition at line 116 of file MyConstField.h.
Referenced by GetBx(), MyConstField(), Print(), and SetField().
fBy
Double_t MyConstField::fBy private
Definition at line 117 of file MyConstField.h.
Referenced by GetBy(), MyConstField(), Print(), and SetField().
fBz
Double_t MyConstField::fBz private
Definition at line 118 of file MyConstField.h.
Referenced by GetBz(), MyConstField(), Print(), and SetField().
fType
Int_t FairField::fType protected inherited
Field type. 1 = constant field, 2 = field map.
Definition at line 116 of file FairField.h.
Referenced by FairConstField::FairConstField(), FairField::GetType(), FairField::IsConst(), FairField::IsMap(), and MyConstField().
fXmax
Double_t MyConstField::fXmax private
Definition at line 109 of file MyConstField.h.
Referenced by GetBx(), GetBy(), GetBz(), GetXmax(), MyConstField(), Print(), and SetFieldRegion().
fXmin
Double_t MyConstField::fXmin private
Limits of the field region
Definition at line 108 of file MyConstField.h.
Referenced by GetXmin(), MyConstField(), Print(), and SetFieldRegion().
fYmax
Double_t MyConstField::fYmax private
Definition at line 111 of file MyConstField.h.
Referenced by GetBx(), GetBy(), GetBz(), GetYmax(), MyConstField(), Print(), and SetFieldRegion().
fYmin
Double_t MyConstField::fYmin private
Definition at line 110 of file MyConstField.h.
Referenced by GetYmin(), MyConstField(), Print(), and SetFieldRegion().
fZmax
Double_t MyConstField::fZmax private
Definition at line 113 of file MyConstField.h.
Referenced by GetBx(), GetBy(), GetBz(), GetZmax(), MyConstField(), Print(), and SetFieldRegion().
fZmin
Double_t MyConstField::fZmin private
Definition at line 112 of file MyConstField.h.
Referenced by GetZmin(), MyConstField(), Print(), and SetFieldRegion().
The documentation for this class was generated from the following files:
MyConstField.h
MyConstField.cxx