FairRoot: FairDetParIo Class Reference
FairDetParIo Class Reference
#include <FairDetParIo.h>
Public Member Functions
FairDetParIo ()
virtual ~FairDetParIo ()
void setInputNumber (Int_t n)
Int_t getInputNumber ()
virtual Bool_t init (FairParSet *)
virtual Int_t write (FairParSet *)
Protected Attributes
Int_t inputNumber
Detailed Description
Definition at line 17 of file FairDetParIo.h.
Constructor & Destructor Documentation
FairDetParIo()
FairDetParIo::FairDetParIo ()
Definition at line 17 of file FairDetParIo.cxx.
~FairDetParIo()
virtual FairDetParIo::~FairDetParIo () inline virtual
Definition at line 23 of file FairDetParIo.h.
Member Function Documentation
getInputNumber()
Int_t FairDetParIo::getInputNumber () inline
Definition at line 29 of file FairDetParIo.h.
References inputNumber.
init()
virtual Bool_t FairDetParIo::init (FairParSet *) inline virtual
Reimplemented in FairGenericParAsciiFileIo, and FairGenericParRootFileIo.
Definition at line 32 of file FairDetParIo.h.
Referenced by ClassImp().
setInputNumber()
void FairDetParIo::setInputNumber (Int_t n) inline
Definition at line 26 of file FairDetParIo.h.
References inputNumber.
Referenced by FairParIo::setInputNumber().
write()
virtual Int_t FairDetParIo::write (FairParSet *) inline virtual
Reimplemented in FairDetParRootFileIo, and FairGenericParAsciiFileIo.
Definition at line 35 of file FairDetParIo.h.
Referenced by FairParGenericSet::write().
Member Data Documentation
inputNumber
Int_t FairDetParIo::inputNumber protected
Definition at line 20 of file FairDetParIo.h.
Referenced by FairDetParRootFileIo::findInputVersion(), getInputNumber(), FairDetParRootFileIo::read(), and setInputNumber().
The documentation for this class was generated from the following files:
FairDetParIo.h
FairDetParIo.cxx