FairRroot: FairMQMessageSHM Class Reference
FairMQMessageSHM Class Reference abstract
#include <FairMQMessageSHM.h>
Public Member Functions
FairMQMessageSHM (fair::mq::shmem::Manager &manager)
FairMQMessageSHM (fair::mq::shmem::Manager &manager, const size_t size)
FairMQMessageSHM (fair::mq::shmem::Manager &manager, void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr)
FairMQMessageSHM (fair::mq::shmem::Manager &manager, FairMQUnmanagedRegionPtr &region, void *data, const size_t size, void *hint=0)
FairMQMessageSHM (const FairMQMessageSHM &)=delete
FairMQMessageSHM operator= (const FairMQMessageSHM &)=delete
void Rebuild () override
void Rebuild (const size_t size) override
void Rebuild (void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr) override
void * GetData () const override
size_t GetSize () const override
bool SetUsedSize (const size_t size) override
FairMQ::Transport GetType () const override
void Copy (const FairMQMessage &msg) override
void Copy (const FairMQMessagePtr &msg) override
~FairMQMessageSHM () override
virtual void Copy (const std::unique_ptr< FairMQMessage > &msg) __attribute__((deprecated("Use 'Copy(const FairMQMessage& msg)'")))=0
Private Member Functions
bool InitializeChunk (const size_t size)
zmq_msg_t * GetMessage ()
void CloseMessage ()
Private Attributes
fair::mq::shmem::Manager & fManager
zmq_msg_t fMessage
bool fQueued
bool fMetaCreated
size_t fRegionId
fair::mq::shmem::Region * fRegionPtr
boost::interprocess::managed_shared_memory::handle_t fHandle
size_t fSize
size_t fHint
char * fLocalPtr
Static Private Attributes
static std::atomic< bool > fInterrupted
static FairMQ::Transport fTransportType = FairMQ::Transport::SHM
Friends
class FairMQSocketSHM
Detailed Description
Definition at line 25 of file FairMQMessageSHM.h.
Constructor & Destructor Documentation
FairMQMessageSHM::FairMQMessageSHM (fair::mq::shmem::Manager & manager)
Definition at line 28 of file FairMQMessageSHM.cxx.
References fMessage, fMetaCreated, and LOG.
FairMQMessageSHM::FairMQMessageSHM (fair::mq::shmem::Manager & manager, const size_t size)
Definition at line 47 of file FairMQMessageSHM.cxx.
References InitializeChunk().
FairMQMessageSHM::FairMQMessageSHM (fair::mq::shmem::Manager & manager, void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr)
Definition at line 62 of file FairMQMessageSHM.cxx.
References fLocalPtr, and InitializeChunk().
FairMQMessageSHM::FairMQMessageSHM (fair::mq::shmem::Manager & manager, FairMQUnmanagedRegionPtr & region, void * data, const size_t size, void * hint = 0)
Definition at line 88 of file FairMQMessageSHM.cxx.
References fair::mq::shmem::MetaHeader::fHandle, fHandle, fair::mq::shmem::MetaHeader::fHint, fHint, fMessage, fMetaCreated, fair::mq::shmem::MetaHeader::fRegionId, fRegionId, fair::mq::shmem::MetaHeader::fSize, and LOG.
FairMQMessageSHM::FairMQMessageSHM (const FairMQMessageSHM &) delete
FairMQMessageSHM::~FairMQMessageSHM () override
Definition at line 404 of file FairMQMessageSHM.cxx.
References CloseMessage().
Member Function Documentation
void FairMQMessageSHM::CloseMessage () private
Definition at line 338 of file FairMQMessageSHM.cxx.
References fHandle, fHint, fInterrupted, fManager, fMessage, fMetaCreated, fair::mq::shmem::Region::fQueue, fQueued, fRegionId, fRegionPtr, fSize, fair::mq::shmem::Manager::GetRemoteRegion(), LOG, and fair::mq::shmem::Manager::Segment().
Referenced by Rebuild(), and ~FairMQMessageSHM().
virtual void FairMQMessage::Copy (const std::unique_ptr< FairMQMessage > & msg) const pure virtual inherited
void FairMQMessageSHM::Copy (const FairMQMessage & msg) override virtual
Implements FairMQMessage.
Definition at line 292 of file FairMQMessageSHM.cxx.
References fHandle, FairMQMessage::GetData(), GetData(), FairMQMessage::GetSize(), InitializeChunk(), and LOG.
void FairMQMessageSHM::Copy (const FairMQMessagePtr & msg) override
Definition at line 315 of file FairMQMessageSHM.cxx.
References fHandle, GetData(), InitializeChunk(), and LOG.
void * FairMQMessageSHM::GetData () const override virtual
Implements FairMQMessage.
Definition at line 220 of file FairMQMessageSHM.cxx.
References fHandle, fLocalPtr, fManager, fair::mq::shmem::Region::fRegion, fRegionId, fRegionPtr, fair::mq::shmem::Manager::GetRemoteRegion(), and fair::mq::shmem::Manager::Segment().
Referenced by Copy().
zmq_msg_t * FairMQMessageSHM::GetMessage () private
Definition at line 215 of file FairMQMessageSHM.cxx.
References fMessage.
size_t FairMQMessageSHM::GetSize () const override virtual
Implements FairMQMessage.
Definition at line 249 of file FairMQMessageSHM.cxx.
References fSize.
Referenced by FairMQSocketSHM::SendImpl().
FairMQ::Transport FairMQMessageSHM::GetType () const override virtual
Implements FairMQMessage.
Definition at line 287 of file FairMQMessageSHM.cxx.
References fTransportType.
bool FairMQMessageSHM::InitializeChunk (const size_t size) private
Definition at line 128 of file FairMQMessageSHM.cxx.
References fair::mq::shmem::MetaHeader::fHandle, fHandle, fair::mq::shmem::MetaHeader::fHint, fHint, fInterrupted, fLocalPtr, fManager, fMessage, fMetaCreated, fair::mq::shmem::MetaHeader::fRegionId, fRegionId, fair::mq::shmem::MetaHeader::fSize, fSize, LOG, and fair::mq::shmem::Manager::Segment().
Referenced by Copy(), FairMQMessageSHM(), and Rebuild().
FairMQMessageSHM FairMQMessageSHM::operator= (const FairMQMessageSHM &) delete
void FairMQMessageSHM::Rebuild () override virtual
Implements FairMQMessage.
Definition at line 173 of file FairMQMessageSHM.cxx.
References CloseMessage(), fMessage, fMetaCreated, fQueued, and LOG.
void FairMQMessageSHM::Rebuild (const size_t size) override virtual
Implements FairMQMessage.
Definition at line 186 of file FairMQMessageSHM.cxx.
References CloseMessage(), fQueued, and InitializeChunk().
void FairMQMessageSHM::Rebuild (void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr) override virtual
Implements FairMQMessage.
Definition at line 195 of file FairMQMessageSHM.cxx.
References CloseMessage(), fLocalPtr, fQueued, and InitializeChunk().
bool FairMQMessageSHM::SetUsedSize (const size_t size) override virtual
Implements FairMQMessage.
Definition at line 254 of file FairMQMessageSHM.cxx.
References fLocalPtr, fManager, fMessage, fair::mq::shmem::MetaHeader::fSize, fSize, LOG, and fair::mq::shmem::Manager::Segment().
Friends And Related Function Documentation
friend class FairMQSocketSHM friend
Definition at line 27 of file FairMQMessageSHM.h.
Member Data Documentation
boost::interprocess::managed_shared_memory::handle_t FairMQMessageSHM::fHandle private
Definition at line 63 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), Copy(), FairMQMessageSHM(), GetData(), and InitializeChunk().
size_t FairMQMessageSHM::fHint private
Definition at line 65 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), FairMQMessageSHM(), and InitializeChunk().
atomic< bool > FairMQMessageSHM::fInterrupted static private
Definition at line 59 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), InitializeChunk(), FairMQSocketSHM::Interrupt(), and FairMQSocketSHM::Resume().
char* FairMQMessageSHM::fLocalPtr mutable private
Definition at line 66 of file FairMQMessageSHM.h.
Referenced by FairMQMessageSHM(), GetData(), InitializeChunk(), Rebuild(), and SetUsedSize().
fair::mq::shmem::Manager& FairMQMessageSHM::fManager private
Definition at line 55 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), GetData(), InitializeChunk(), and SetUsedSize().
zmq_msg_t FairMQMessageSHM::fMessage private
Definition at line 56 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), FairMQMessageSHM(), GetMessage(), InitializeChunk(), Rebuild(), and SetUsedSize().
bool FairMQMessageSHM::fMetaCreated private
Definition at line 58 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), FairMQMessageSHM(), InitializeChunk(), and Rebuild().
bool FairMQMessageSHM::fQueued private
Definition at line 57 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), and Rebuild().
size_t FairMQMessageSHM::fRegionId private
Definition at line 61 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), FairMQMessageSHM(), GetData(), and InitializeChunk().
fair::mq::shmem::Region* FairMQMessageSHM::fRegionPtr mutable private
Definition at line 62 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), and GetData().
size_t FairMQMessageSHM::fSize private
Definition at line 64 of file FairMQMessageSHM.h.
Referenced by CloseMessage(), GetSize(), InitializeChunk(), and SetUsedSize().
FairMQ::Transport FairMQMessageSHM::fTransportType = FairMQ::Transport::SHM static private
Definition at line 60 of file FairMQMessageSHM.h.
Referenced by GetType().
The documentation for this class was generated from the following files:
FairMQMessageSHM.h
FairMQMessageSHM.cxx