FairRoot: Ex2Processor Class Reference
Ex2Processor Class Reference
#include <Ex2Processor.h>
Public Member Functions
Ex2Processor ()
Ex2Processor (const Ex2Processor &)
Ex2Processor & operator= (const Ex2Processor &)
virtual ~Ex2Processor ()
Protected Member Functions
virtual void Init ()
virtual void Run ()
void Exec (TClonesArray *digis, TClonesArray *hits)
Private Attributes
TClonesArray * fInput
TClonesArray * fOutput
int fNumMsgs
Detailed Description
Definition at line 17 of file Ex2Processor.h.
Constructor & Destructor Documentation
Ex2Processor() [1/2]
Ex2Processor::Ex2Processor () inline
Definition at line 20 of file Ex2Processor.h.
Ex2Processor() [2/2]
Ex2Processor::Ex2Processor (const Ex2Processor &)
~Ex2Processor()
virtual Ex2Processor::~Ex2Processor () inline virtual
Definition at line 30 of file Ex2Processor.h.
Member Function Documentation
Exec()
void Ex2Processor::Exec (TClonesArray * digis, TClonesArray * hits) inline protected
Definition at line 79 of file Ex2Processor.h.
References FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), MyDigi::GetX(), MyDigi::GetY(), MyDigi::GetZ(), FairTimeStamp::SetTimeStamp(), FairTimeStamp::SetTimeStampError(), and MyDigi::SetXYZ().
Referenced by Run().
Init()
virtual void Ex2Processor::Init () inline protected virtual
Definition at line 33 of file Ex2Processor.h.
References fNumMsgs, and fOutput.
operator=()
Ex2Processor& Ex2Processor::operator= (const Ex2Processor &)
Run()
virtual void Ex2Processor::Run () inline protected virtual
Definition at line 39 of file Ex2Processor.h.
References Exec(), fInput, fNumMsgs, and fOutput.
Member Data Documentation
fInput
TClonesArray* Ex2Processor::fInput private
Definition at line 101 of file Ex2Processor.h.
Referenced by Run().
fNumMsgs
int Ex2Processor::fNumMsgs private
Definition at line 103 of file Ex2Processor.h.
Referenced by Init(), and Run().
fOutput
TClonesArray* Ex2Processor::fOutput private
Definition at line 102 of file Ex2Processor.h.
Referenced by Init(), and Run().
The documentation for this class was generated from the following file:
Ex2Processor.h