FairRroot: FairMQTransportFactoryNN Class Reference
FairMQTransportFactoryNN Class Reference
#include <FairMQTransportFactoryNN.h>
Public Member Functions
FairMQTransportFactoryNN (const std::string &id="", const FairMQProgOptions *config=nullptr)
~FairMQTransportFactoryNN () override
FairMQMessagePtr CreateMessage () const override
Create empty FairMQMessage.
FairMQMessagePtr CreateMessage (const size_t size) const override
Create new FairMQMessage of specified size.
FairMQMessagePtr CreateMessage (void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr) const override
Create new FairMQMessage with user provided buffer and size.
FairMQMessagePtr CreateMessage (FairMQUnmanagedRegionPtr &region, void *data, const size_t size, void *hint=0) const override
FairMQSocketPtr CreateSocket (const std::string &type, const std::string &name) const override
Create a socket.
FairMQPollerPtr CreatePoller (const std::vector< FairMQChannel > &channels) const override
Create a poller for a single channel (all subchannels)
FairMQPollerPtr CreatePoller (const std::vector< const FairMQChannel * > &channels) const override
Create a poller for specific channels.
FairMQPollerPtr CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> &channelsMap, const std::vector< std::string > &channelList) const override
Create a poller for specific channels (all subchannels)
FairMQPollerPtr CreatePoller (const FairMQSocket &cmdSocket, const FairMQSocket &dataSocket) const override
Create a poller for two sockets.
FairMQUnmanagedRegionPtr CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback) const override
FairMQ::Transport GetType () const override
Get transport type.
void Interrupt () override
void Resume () override
auto GetId () const -> const std::string
template<typename T >
FairMQMessagePtr NewSimpleMessage (const T &data) const
template<std::size_t N>
FairMQMessagePtr NewSimpleMessage (const char(&data)[N]) const
FairMQMessagePtr NewSimpleMessage (const std::string &str) const
template<typename T >
FairMQMessagePtr NewStaticMessage (const T &data) const
FairMQMessagePtr NewStaticMessage (const std::string &str) const
Static Public Member Functions
static auto CreateTransportFactory (const std::string &type, const std::string &id="", const FairMQProgOptions *config=nullptr) -> std::shared_ptr< FairMQTransportFactory >
static void FairMQNoCleanup (void *, void *)
template<typename T >
static void FairMQSimpleMsgCleanup (void *, void *obj)
Static Private Attributes
static FairMQ::Transport fTransportType = FairMQ::Transport::NN
Detailed Description
Definition at line 22 of file FairMQTransportFactoryNN.h.
Constructor & Destructor Documentation
FairMQTransportFactoryNN::FairMQTransportFactoryNN (const std::string & id = "", const FairMQProgOptions * config = nullptr)
Definition at line 17 of file FairMQTransportFactoryNN.cxx.
References LOG.
FairMQTransportFactoryNN::~FairMQTransportFactoryNN () override
Definition at line 78 of file FairMQTransportFactoryNN.cxx.
Member Function Documentation
FairMQMessagePtr FairMQTransportFactoryNN::CreateMessage () const override virtual
Create empty FairMQMessage.
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 23 of file FairMQTransportFactoryNN.cxx.
FairMQMessagePtr FairMQTransportFactoryNN::CreateMessage (const size_t size) const override virtual
Create new FairMQMessage of specified size.
Parameters
size message size
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 28 of file FairMQTransportFactoryNN.cxx.
FairMQMessagePtr FairMQTransportFactoryNN::CreateMessage (void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr) const override virtual
Create new FairMQMessage with user provided buffer and size.
Parameters
data pointer to user provided buffer
size size of the user provided buffer
ffn callback, called when the message is transfered (and can be deleted)
obj optional helper pointer that can be used in the callback
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 33 of file FairMQTransportFactoryNN.cxx.
FairMQMessagePtr FairMQTransportFactoryNN::CreateMessage (FairMQUnmanagedRegionPtr & region, void * data, const size_t size, void * hint = 0) const override virtual
Implements FairMQTransportFactory.
Definition at line 38 of file FairMQTransportFactoryNN.cxx.
FairMQPollerPtr FairMQTransportFactoryNN::CreatePoller (const std::vector< FairMQChannel > & channels) const override virtual
Create a poller for a single channel (all subchannels)
Implements FairMQTransportFactory.
FairMQPollerPtr FairMQTransportFactoryNN::CreatePoller (const std::vector< const FairMQChannel * > & channels) const override virtual
Create a poller for specific channels.
Implements FairMQTransportFactory.
Definition at line 53 of file FairMQTransportFactoryNN.cxx.
FairMQPollerPtr FairMQTransportFactoryNN::CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> & channelsMap, const std::vector< std::string > & channelList) const override virtual
Create a poller for specific channels (all subchannels)
Implements FairMQTransportFactory.
FairMQPollerPtr FairMQTransportFactoryNN::CreatePoller (const FairMQSocket & cmdSocket, const FairMQSocket & dataSocket) const override virtual
Create a poller for two sockets.
Implements FairMQTransportFactory.
Definition at line 63 of file FairMQTransportFactoryNN.cxx.
FairMQSocketPtr FairMQTransportFactoryNN::CreateSocket (const std::string & type, const std::string & name) const override virtual
Create a socket.
Implements FairMQTransportFactory.
Definition at line 43 of file FairMQTransportFactoryNN.cxx.
References FairMQTransportFactory::GetId().
auto FairMQTransportFactory::CreateTransportFactory (const std::string & type, const std::string & id = "", const FairMQProgOptions * config = nullptr) -> std::shared_ptr<FairMQTransportFactory> static inherited
Definition at line 30 of file FairMQTransportFactory.cxx.
References LOG, and fair::mq::tools::Uuid().
Referenced by FairMQDevice::AddTransport().
FairMQUnmanagedRegionPtr FairMQTransportFactoryNN::CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback) const override virtual
Implements FairMQTransportFactory.
Definition at line 68 of file FairMQTransportFactoryNN.cxx.
static void FairMQTransportFactory::FairMQNoCleanup (void * , void *) inline static inherited
Definition at line 81 of file FairMQTransportFactory.h.
Referenced by FairMQTransportFactory::NewStaticMessage().
template<typename T > static void FairMQTransportFactory::FairMQSimpleMsgCleanup (void * , void * obj) inline static inherited
Definition at line 86 of file FairMQTransportFactory.h.
auto FairMQTransportFactory::GetId () const -> const std::string inline inherited
Definition at line 38 of file FairMQTransportFactory.h.
References FairMQTransportFactory::fkId.
Referenced by CreateSocket(), FairMQTransportFactorySHM::CreateSocket(), and FairMQTransportFactoryZMQ::CreateSocket().
FairMQ::Transport FairMQTransportFactoryNN::GetType () const override virtual
Get transport type.
Implements FairMQTransportFactory.
Definition at line 73 of file FairMQTransportFactoryNN.cxx.
References fTransportType.
void FairMQTransportFactoryNN::Interrupt () inline override virtual
Implements FairMQTransportFactory.
Definition at line 44 of file FairMQTransportFactoryNN.h.
References FairMQSocketNN::Interrupt().
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const T & data) const inline inherited
Definition at line 92 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
template<std::size_t N> FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const char(&) data[N]) const inline inherited
Definition at line 101 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const std::string & str) const inline inherited
Definition at line 107 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const T & data) const inline inherited
Definition at line 115 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage(), and FairMQTransportFactory::FairMQNoCleanup().
FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const std::string & str) const inline inherited
Definition at line 120 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage(), and FairMQTransportFactory::FairMQNoCleanup().
void FairMQTransportFactoryNN::Resume () inline override virtual
Implements FairMQTransportFactory.
Definition at line 45 of file FairMQTransportFactoryNN.h.
References FairMQSocketNN::Resume().
Member Data Documentation
FairMQ::Transport FairMQTransportFactoryNN::fTransportType = FairMQ::Transport::NN static private
Definition at line 48 of file FairMQTransportFactoryNN.h.
Referenced by GetType().
The documentation for this class was generated from the following files:
FairMQTransportFactoryNN.h
FairMQTransportFactoryNN.cxx