FairRroot: FairMQPollerNN Class Reference
FairMQPollerNN Class Reference
#include <FairMQPollerNN.h>
Public Member Functions
FairMQPollerNN (const std::vector< FairMQChannel > &channels)
FairMQPollerNN (const std::vector< const FairMQChannel * > &channels)
FairMQPollerNN (const std::unordered_map< std::string, std::vector< FairMQChannel >> &channelsMap, const std::vector< std::string > &channelList)
FairMQPollerNN (const FairMQPollerNN &)=delete
FairMQPollerNN operator= (const FairMQPollerNN &)=delete
void SetItemEvents (nn_pollfd &item, const int type)
virtual void Poll (const int timeout)
virtual bool CheckInput (const int index)
virtual bool CheckOutput (const int index)
virtual bool CheckInput (const std::string channelKey, const int index)
virtual bool CheckOutput (const std::string channelKey, const int index)
virtual ~FairMQPollerNN ()
Private Member Functions
FairMQPollerNN (const FairMQSocket &cmdSocket, const FairMQSocket &dataSocket)
Private Attributes
nn_pollfd * fItems
int fNumItems
std::unordered_map< std::string, int > fOffsetMap
Friends
class FairMQChannel
class FairMQTransportFactoryNN
Detailed Description
Definition at line 29 of file FairMQPollerNN.h.
Constructor & Destructor Documentation
FairMQPollerNN::FairMQPollerNN (const std::vector< FairMQChannel > & channels)
FairMQPollerNN::FairMQPollerNN (const std::vector< const FairMQChannel * > & channels)
FairMQPollerNN::FairMQPollerNN (const std::unordered_map< std::string, std::vector< FairMQChannel >> & channelsMap, const std::vector< std::string > & channelList)
FairMQPollerNN::FairMQPollerNN (const FairMQPollerNN &) delete
FairMQPollerNN::~FairMQPollerNN () virtual
Definition at line 225 of file FairMQPollerNN.cxx.
References fItems.
FairMQPollerNN::FairMQPollerNN (const FairMQSocket & cmdSocket, const FairMQSocket & dataSocket) private
Definition at line 109 of file FairMQPollerNN.cxx.
References fItems, fNumItems, FairMQSocket::GetSocket(), and SetItemEvents().
Member Function Documentation
bool FairMQPollerNN::CheckInput (const int index) virtual
Implements FairMQPoller.
Definition at line 167 of file FairMQPollerNN.cxx.
References fItems.
virtual bool FairMQPollerNN::CheckInput (const std::string channelKey, const int index) virtual
Implements FairMQPoller.
bool FairMQPollerNN::CheckOutput (const int index) virtual
Implements FairMQPoller.
Definition at line 177 of file FairMQPollerNN.cxx.
References fItems.
virtual bool FairMQPollerNN::CheckOutput (const std::string channelKey, const int index) virtual
Implements FairMQPoller.
FairMQPollerNN FairMQPollerNN::operator= (const FairMQPollerNN &) delete
void FairMQPollerNN::Poll (const int timeout) virtual
Implements FairMQPoller.
Definition at line 151 of file FairMQPollerNN.cxx.
References fItems, and LOG.
void FairMQPollerNN::SetItemEvents (nn_pollfd & item, const int type)
Definition at line 130 of file FairMQPollerNN.cxx.
References LOG.
Referenced by FairMQPollerNN().
Friends And Related Function Documentation
friend class FairMQChannel friend
Definition at line 31 of file FairMQPollerNN.h.
friend class FairMQTransportFactoryNN friend
Definition at line 32 of file FairMQPollerNN.h.
Member Data Documentation
nn_pollfd* FairMQPollerNN::fItems private
Definition at line 55 of file FairMQPollerNN.h.
Referenced by CheckInput(), CheckOutput(), FairMQPollerNN(), Poll(), and ~FairMQPollerNN().
int FairMQPollerNN::fNumItems private
Definition at line 56 of file FairMQPollerNN.h.
Referenced by FairMQPollerNN().
std::unordered_map<std::string, int> FairMQPollerNN::fOffsetMap private
Definition at line 58 of file FairMQPollerNN.h.
The documentation for this class was generated from the following files:
FairMQPollerNN.h
FairMQPollerNN.cxx