FairRroot: FairMBSUnpacker Class Reference
FairMBSUnpacker Class Reference
#include <FairMBSUnpacker.h>
Public Member Functions
FairMBSUnpacker (Short_t type=94, Short_t subType=9400, Short_t procId=10, Short_t subCrate=1, Short_t control=3)
virtual ~FairMBSUnpacker ()
virtual Bool_t Init ()
virtual Bool_t DoUnpack (Int_t *data, Int_t size)
virtual void Reset ()
Int_t GetNHitsTotal ()
TClonesArray * GetOutputData ()
virtual Bool_t ReInit ()
virtual void SetParContainers ()
Short_t GetType () const
Short_t GetSubType () const
Short_t GetProcId () const
Short_t GetSubCrate () const
Short_t GetControl () const
Protected Member Functions
virtual void Register ()
Private Member Functions
FairMBSUnpacker (const FairMBSUnpacker &)
Copy Constructor.
FairMBSUnpacker operator= (const FairMBSUnpacker &)
Private Attributes
TClonesArray * fRawData
Int_t fNHits
Int_t fNHitsTotal
Detailed Description
An example unpacker of MBS data.
Definition at line 19 of file FairMBSUnpacker.h.
Constructor & Destructor Documentation
FairMBSUnpacker::FairMBSUnpacker (Short_t type = 94, Short_t subType = 9400, Short_t procId = 10, Short_t subCrate = 1, Short_t control = 3)
Standard Constructor. Input - MBS parameters of the detector.
Definition at line 20 of file FairMBSUnpacker.cxx.
FairMBSUnpacker::~FairMBSUnpacker () virtual
Destructor.
Definition at line 29 of file FairMBSUnpacker.cxx.
References fRawData, and LOG.
FairMBSUnpacker::FairMBSUnpacker (const FairMBSUnpacker &) private
Copy Constructor.
Member Function Documentation
Bool_t FairMBSUnpacker::DoUnpack (Int_t * data, Int_t size) virtual
Process an MBS sub-event.
Implements FairUnpack.
Definition at line 42 of file FairMBSUnpacker.cxx.
References fNHits, fNHitsTotal, and LOG.
Short_t FairUnpack::GetControl () const inline inherited
Definition at line 38 of file FairUnpack.h.
References FairUnpack::fControl.
Referenced by FairMbsSource::Unpack().
Int_t FairMBSUnpacker::GetNHitsTotal () inline
Method for controling the functionality.
Definition at line 42 of file FairMBSUnpacker.h.
References fNHitsTotal.
TClonesArray* FairMBSUnpacker::GetOutputData () inline
Definition at line 47 of file FairMBSUnpacker.h.
References fRawData.
Short_t FairUnpack::GetProcId () const inline inherited
Definition at line 36 of file FairUnpack.h.
References FairUnpack::fProcId.
Referenced by FairMbsSource::Unpack().
Short_t FairUnpack::GetSubCrate () const inline inherited
Definition at line 37 of file FairUnpack.h.
References FairUnpack::fSubCrate.
Referenced by FairMbsSource::Unpack().
Short_t FairUnpack::GetSubType () const inline inherited
Definition at line 35 of file FairUnpack.h.
References FairUnpack::fSubType.
Referenced by FairMbsSource::Unpack().
Short_t FairUnpack::GetType () const inline inherited
Definition at line 34 of file FairUnpack.h.
References FairUnpack::fType.
Referenced by FairMbsSource::Unpack().
Bool_t FairMBSUnpacker::Init () virtual
Initialization. Called once, before the event loop.
Implements FairUnpack.
Definition at line 36 of file FairMBSUnpacker.cxx.
FairMBSUnpacker FairMBSUnpacker::operator= (const FairMBSUnpacker &) private
virtual void FairMBSUnpacker::Register () inline protected virtual
Register the output structures.
Implements FairUnpack.
Definition at line 54 of file FairMBSUnpacker.h.
virtual Bool_t FairUnpack::ReInit () inline virtual inherited
Definition at line 29 of file FairUnpack.h.
void FairMBSUnpacker::Reset () virtual
Clear the output structures.
Implements FairUnpack.
Definition at line 102 of file FairMBSUnpacker.cxx.
References fNHits, fRawData, and LOG.
virtual void FairUnpack::SetParContainers () inline virtual inherited
Definition at line 32 of file FairUnpack.h.
Member Data Documentation
Int_t FairMBSUnpacker::fNHits private
Number of raw items in current event.
Definition at line 58 of file FairMBSUnpacker.h.
Referenced by DoUnpack(), and Reset().
Int_t FairMBSUnpacker::fNHitsTotal private
Total number of raw items.
Definition at line 59 of file FairMBSUnpacker.h.
Referenced by DoUnpack(), and GetNHitsTotal().
TClonesArray* FairMBSUnpacker::fRawData private
Array of output raw items.
Definition at line 57 of file FairMBSUnpacker.h.
Referenced by GetOutputData(), Reset(), and ~FairMBSUnpacker().
The documentation for this class was generated from the following files:
FairMBSUnpacker.h
FairMBSUnpacker.cxx