FairRroot: MyPayloadProto::Digi Class Reference
MyPayloadProto::Digi Class Reference
#include <MyPayload.pb.h>
Public Member Functions
Digi ()
virtual ~Digi ()
Digi (const Digi &from)
Digi & operator= (const Digi &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Digi *other)
Digi * New () const PROTOBUF_FINAL
Digi * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Digi &from)
void MergeFrom (const Digi &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_x () const
void clear_x ()
::google::protobuf::int32 x () const
void set_x (::google::protobuf::int32 value)
bool has_y () const
void clear_y ()
::google::protobuf::int32 y () const
void set_y (::google::protobuf::int32 value)
bool has_time_stamp () const
void clear_time_stamp ()
double time_stamp () const
void set_time_stamp (double value)
bool has_time_stamperror () const
void clear_time_stamperror ()
double time_stamperror () const
void set_time_stamperror (double value)
bool has_z () const
void clear_z ()
::google::protobuf::int32 z () const
void set_z (::google::protobuf::int32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Digi & default_instance ()
static const Digi * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kXFieldNumber = 1
static const int kYFieldNumber = 2
static const int kTimeStampFieldNumber = 4
static const int kTimeStamperrorFieldNumber = 5
static const int kZFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Digi *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_z ()
void clear_has_z ()
void set_has_time_stamp ()
void clear_has_time_stamp ()
void set_has_time_stamperror ()
void clear_has_time_stamperror ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::int32 x_
::google::protobuf::int32 y_
double time_stamp_
double time_stamperror_
::google::protobuf::int32 z_
Friends
struct protobuf_MyPayload_2eproto::TableStruct
void swap (Digi &a, Digi &b)
Detailed Description
Definition at line 67 of file MyPayload.pb.h.
Constructor & Destructor Documentation
MyPayloadProto::Digi::Digi ()
virtual MyPayloadProto::Digi::~Digi () virtual
MyPayloadProto::Digi::Digi (const Digi & from)
Member Function Documentation
size_t MyPayloadProto::Digi::ByteSizeLong () const
void MyPayloadProto::Digi::Clear ()
void MyPayloadProto::Digi::clear_has_time_stamp () inline private
Definition at line 760 of file MyPayload.pb.h.
Referenced by clear_time_stamp(), and MyPayloadProto::Hit::clear_time_stamp().
void MyPayloadProto::Digi::clear_has_time_stamperror () inline private
Definition at line 784 of file MyPayload.pb.h.
Referenced by clear_time_stamperror(), and MyPayloadProto::Hit::clear_time_stamperror().
void MyPayloadProto::Digi::clear_has_x () inline private
Definition at line 688 of file MyPayload.pb.h.
Referenced by clear_x().
void MyPayloadProto::Digi::clear_has_y () inline private
Definition at line 712 of file MyPayload.pb.h.
Referenced by clear_y().
void MyPayloadProto::Digi::clear_has_z () inline private
Definition at line 736 of file MyPayload.pb.h.
Referenced by clear_z().
void MyPayloadProto::Digi::clear_time_stamp () inline
Definition at line 763 of file MyPayload.pb.h.
References clear_has_time_stamp().
void MyPayloadProto::Digi::clear_time_stamperror () inline
Definition at line 787 of file MyPayload.pb.h.
References clear_has_time_stamperror().
void MyPayloadProto::Digi::clear_x () inline
Definition at line 691 of file MyPayload.pb.h.
References clear_has_x().
void MyPayloadProto::Digi::clear_y () inline
Definition at line 715 of file MyPayload.pb.h.
References clear_has_y().
void MyPayloadProto::Digi::clear_z () inline
Definition at line 739 of file MyPayload.pb.h.
References clear_has_z().
void MyPayloadProto::Digi::CopyFrom (const ::google::protobuf::Message & from)
Referenced by operator=(), MyPayloadProto::Hit::operator=(), MyPayloadProto::DigiPayload::operator=(), and MyPayloadProto::HitPayload::operator=().
void MyPayloadProto::Digi::CopyFrom (const Digi & from)
static const Digi& MyPayloadProto::Digi::default_instance () static
static const ::google::protobuf::Descriptor* MyPayloadProto::Digi::descriptor () static
inline ::google::protobuf::Arena* MyPayloadProto::Digi::GetArenaNoVirtual () const inline private
Definition at line 141 of file MyPayload.pb.h.
int MyPayloadProto::Digi::GetCachedSize () const inline
Definition at line 134 of file MyPayload.pb.h.
References _cached_size_.
::google::protobuf::Metadata MyPayloadProto::Digi::GetMetadata () const
bool MyPayloadProto::Digi::has_time_stamp () const inline
Definition at line 754 of file MyPayload.pb.h.
bool MyPayloadProto::Digi::has_time_stamperror () const inline
Definition at line 778 of file MyPayload.pb.h.
bool MyPayloadProto::Digi::has_x () const inline
Definition at line 682 of file MyPayload.pb.h.
bool MyPayloadProto::Digi::has_y () const inline
Definition at line 706 of file MyPayload.pb.h.
bool MyPayloadProto::Digi::has_z () const inline
Definition at line 730 of file MyPayload.pb.h.
static const Digi* MyPayloadProto::Digi::internal_default_instance () inline static
Definition at line 103 of file MyPayload.pb.h.
References MyPayloadProto::_Digi_default_instance_.
::google::protobuf::uint8* MyPayloadProto::Digi::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void MyPayloadProto::Digi::InternalSwap (Digi * other) private
bool MyPayloadProto::Digi::IsInitialized () const
void* MyPayloadProto::Digi::MaybeArenaPtr () const inline private
Definition at line 144 of file MyPayload.pb.h.
void MyPayloadProto::Digi::MergeFrom (const ::google::protobuf::Message & from)
void MyPayloadProto::Digi::MergeFrom (const Digi & from)
bool MyPayloadProto::Digi::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* MyPayloadProto::Digi::mutable_unknown_fields () inline
Definition at line 96 of file MyPayload.pb.h.
References _internal_metadata_.
Digi* MyPayloadProto::Digi::New () const inline
Definition at line 117 of file MyPayload.pb.h.
References New().
Referenced by New().
Digi* MyPayloadProto::Digi::New (::google::protobuf::Arena * arena) const
Digi& MyPayloadProto::Digi::operator= (const Digi & from) inline
Definition at line 74 of file MyPayload.pb.h.
References CopyFrom().
void MyPayloadProto::Digi::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void MyPayloadProto::Digi::set_has_time_stamp () inline private
Definition at line 757 of file MyPayload.pb.h.
Referenced by set_time_stamp(), and MyPayloadProto::Hit::set_time_stamp().
void MyPayloadProto::Digi::set_has_time_stamperror () inline private
Definition at line 781 of file MyPayload.pb.h.
Referenced by set_time_stamperror(), and MyPayloadProto::Hit::set_time_stamperror().
void MyPayloadProto::Digi::set_has_x () inline private
Definition at line 685 of file MyPayload.pb.h.
Referenced by set_x().
void MyPayloadProto::Digi::set_has_y () inline private
Definition at line 709 of file MyPayload.pb.h.
Referenced by set_y().
void MyPayloadProto::Digi::set_has_z () inline private
Definition at line 733 of file MyPayload.pb.h.
Referenced by set_z().
void MyPayloadProto::Digi::set_time_stamp (double value) inline
Definition at line 771 of file MyPayload.pb.h.
References set_has_time_stamp().
void MyPayloadProto::Digi::set_time_stamperror (double value) inline
Definition at line 795 of file MyPayload.pb.h.
References set_has_time_stamperror().
void MyPayloadProto::Digi::set_x (::google::protobuf::int32 value) inline
Definition at line 699 of file MyPayload.pb.h.
References set_has_x().
void MyPayloadProto::Digi::set_y (::google::protobuf::int32 value) inline
Definition at line 723 of file MyPayload.pb.h.
References set_has_y().
void MyPayloadProto::Digi::set_z (::google::protobuf::int32 value) inline
Definition at line 747 of file MyPayload.pb.h.
References set_has_z().
void MyPayloadProto::Digi::SetCachedSize (int size) const private
void MyPayloadProto::Digi::SharedCtor () private
void MyPayloadProto::Digi::SharedDtor () private
void MyPayloadProto::Digi::Swap (Digi * other)
double MyPayloadProto::Digi::time_stamp () const inline
Definition at line 767 of file MyPayload.pb.h.
References time_stamp_.
double MyPayloadProto::Digi::time_stamperror () const inline
Definition at line 791 of file MyPayload.pb.h.
References time_stamperror_.
const ::google::protobuf::UnknownFieldSet& MyPayloadProto::Digi::unknown_fields () const inline
Definition at line 93 of file MyPayload.pb.h.
References _internal_metadata_.
google::protobuf::int32 MyPayloadProto::Digi::x () const inline
Definition at line 695 of file MyPayload.pb.h.
References x_.
google::protobuf::int32 MyPayloadProto::Digi::y () const inline
Definition at line 719 of file MyPayload.pb.h.
References y_.
google::protobuf::int32 MyPayloadProto::Digi::z () const inline
Definition at line 743 of file MyPayload.pb.h.
References z_.
Friends And Related Function Documentation
friend struct protobuf_MyPayload_2eproto::TableStruct friend
Definition at line 211 of file MyPayload.pb.h.
void swap (Digi & a, Digi & b) friend
Definition at line 111 of file MyPayload.pb.h.
Member Data Documentation
int MyPayloadProto::Digi::_cached_size_ mutable private
Definition at line 205 of file MyPayload.pb.h.
Referenced by GetCachedSize(), MyPayloadProto::Hit::GetCachedSize(), MyPayloadProto::DigiPayload::GetCachedSize(), and MyPayloadProto::HitPayload::GetCachedSize().
::google::protobuf::internal::HasBits<1> MyPayloadProto::Digi::_has_bits_ private
Definition at line 204 of file MyPayload.pb.h.
::google::protobuf::internal::InternalMetadataWithArena MyPayloadProto::Digi::_internal_metadata_ private
Definition at line 203 of file MyPayload.pb.h.
Referenced by mutable_unknown_fields(), and unknown_fields().
PROTOBUF_CONSTEXPR int const MyPayloadProto::Digi::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 107 of file MyPayload.pb.h.
const int MyPayloadProto::Digi::kTimeStamperrorFieldNumber = 5 static
Definition at line 179 of file MyPayload.pb.h.
const int MyPayloadProto::Digi::kTimeStampFieldNumber = 4 static
Definition at line 172 of file MyPayload.pb.h.
const int MyPayloadProto::Digi::kXFieldNumber = 1 static
Definition at line 158 of file MyPayload.pb.h.
const int MyPayloadProto::Digi::kYFieldNumber = 2 static
Definition at line 165 of file MyPayload.pb.h.
const int MyPayloadProto::Digi::kZFieldNumber = 3 static
Definition at line 186 of file MyPayload.pb.h.
double MyPayloadProto::Digi::time_stamp_ private
Definition at line 208 of file MyPayload.pb.h.
Referenced by time_stamp(), and MyPayloadProto::Hit::time_stamp().
double MyPayloadProto::Digi::time_stamperror_ private
Definition at line 209 of file MyPayload.pb.h.
Referenced by time_stamperror(), and MyPayloadProto::Hit::time_stamperror().
::google::protobuf::int32 MyPayloadProto::Digi::x_ private
Definition at line 206 of file MyPayload.pb.h.
Referenced by x().
::google::protobuf::int32 MyPayloadProto::Digi::y_ private
Definition at line 207 of file MyPayload.pb.h.
Referenced by y().
::google::protobuf::int32 MyPayloadProto::Digi::z_ private
Definition at line 210 of file MyPayload.pb.h.
Referenced by z().
The documentation for this class was generated from the following file:
MyPayload.pb.h