FairRoot: FairMCPoint Class Reference
FairMCPoint Class Reference
#include <FairMCPoint.h>
Public Member Functions
FairMCPoint ()
FairMCPoint (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss, UInt_t EventId=0)
virtual ~FairMCPoint ()
UInt_t GetEventID () const
Int_t GetTrackID () const
event identifier
Double_t GetPx () const
Double_t GetPy () const
Double_t GetPz () const
Double_t GetTime () const
Double_t GetLength () const
Double_t GetEnergyLoss () const
void Momentum (TVector3 &mom) const
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetEventID (UInt_t eventId)
virtual void SetTrackID (Int_t id)
void SetTime (Double_t time)
void SetLength (Double_t length)
void SetEnergyLoss (Double_t eLoss)
void SetMomentum (const TVector3 &mom)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
virtual void Print (const Option_t *opt=0) const
template<class Archive >
void serialize (Archive &ar, const unsigned int)
std::set< FairLink > GetLinks () const
returns stored links as FairLinks
Int_t GetNLinks () const
returns the number of stored links
FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
FairLink GetEntryNr () const
FairMultiLinkedData * GetPointerToLinks () const
std::vector< FairLink > GetSortedMCTracks ()
void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
void SetLink (FairLink link)
Sets the Links with a single FairLink.
void SetInsertHistory (Bool_t val)
void SetEntryNr (FairLink val)
void SetPointerToLinks (FairMultiLinkedData *links)
void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
void AddInterfaceData (FairMultiLinkedData_Interface *data)
void ResetLinks ()
std::ostream & PrintLinkInfo (std::ostream &out=std::cout) const
Output.
Protected Member Functions
FairMultiLinkedData * CreateFairMultiLinkedData ()
ClassDef (FairMultiLinkedData_Interface, 5)
Protected Attributes
Int_t fTrackID
Track index.
UInt_t fEventId
MC Event id.
Double32_t fPx
Double32_t fPy
Double32_t fPz
Momentum components [GeV].
Double32_t fTime
Time since event start [ns].
Double32_t fLength
Track length since creation [cm].
Double32_t fELoss
Energy loss at this point [GeV].
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
FairMultiLinkedData * fLink
Friends
class boost::serialization::access
Detailed Description
FairMCPoint.h This is the base class for all MC Points generated by the transport of tracks through active detectors.
Definition at line 27 of file FairMCPoint.h.
Constructor & Destructor Documentation
FairMCPoint() [1/2]
FairMCPoint::FairMCPoint ()
Default constructor
Definition at line 12 of file FairMCPoint.cxx.
FairMCPoint() [2/2]
FairMCPoint::FairMCPoint (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss, UInt_t EventId = 0)
Constructor with arguments
Parameters
trackID Index of MCTrack
detID Detector ID
pos Point coordinates [cm]
mom Momentum of track at MCPoint [GeV]
tof Time since event start [ns]
length Track length since creation [cm]
eLoss Energy deposit [GeV]
EventId MC event id
Definition at line 36 of file FairMCPoint.cxx.
~FairMCPoint()
FairMCPoint::~FairMCPoint () virtual
Destructor
Definition at line 57 of file FairMCPoint.cxx.
Member Function Documentation
AddInterfaceData()
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) inherited
Definition at line 172 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
Referenced by FairTestDetectorTimeRecoTask::Exec().
AddLink()
void FairMultiLinkedData_Interface::AddLink (FairLink link) inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
AddLinks()
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 155 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
ClassDef()
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
CreateFairMultiLinkedData()
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 59 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
GetDetectorID()
Int_t FairMCPoint::GetDetectorID () const inline
Definition at line 63 of file FairMCPoint.h.
References fDetectorID.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), FairTutorialDet4PointDraw::Exec(), PixelDigitize::Exec(), and FairTutorialDet4HitProducerIdealMisalign::Exec().
GetEnergyLoss()
Double_t FairMCPoint::GetEnergyLoss () const inline
Definition at line 61 of file FairMCPoint.h.
References fELoss.
GetEntryNr()
FairLink FairMultiLinkedData_Interface::GetEntryNr () const inherited
Definition at line 101 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetEntryNr(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorTimeRecoTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
GetEventID()
UInt_t FairMCPoint::GetEventID () const inline
Accessors
Definition at line 54 of file FairMCPoint.h.
References fEventId.
GetLength()
Double_t FairMCPoint::GetLength () const inline
Definition at line 60 of file FairMCPoint.h.
References fLength.
GetLink()
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const inherited
returns the FairLink at the given position
Definition at line 91 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetLinks()
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const inherited
returns stored links as FairLinks
Definition at line 72 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetLinksWithType()
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const inherited
returns all FairLinks with the corresponding type
Definition at line 111 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetNLinks()
Int_t FairMultiLinkedData_Interface::GetNLinks () const inherited
returns the number of stored links
Definition at line 82 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetPointerToLinks()
FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairPrintFairLinks::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::GetSortedMCTracks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::PrintLinkInfo(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
GetPx()
Double_t FairMCPoint::GetPx () const inline
Definition at line 56 of file FairMCPoint.h.
References fPx.
GetPy()
Double_t FairMCPoint::GetPy () const inline
Definition at line 57 of file FairMCPoint.h.
References fPy.
GetPz()
Double_t FairMCPoint::GetPz () const inline
Definition at line 58 of file FairMCPoint.h.
References fPz.
GetSortedMCTracks()
std::vector< FairLink > FairMultiLinkedData_Interface::GetSortedMCTracks () inherited
Definition at line 121 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::GetSortedMCTracks().
GetTime()
Double_t FairMCPoint::GetTime () const inline
Definition at line 59 of file FairMCPoint.h.
References fTime.
Referenced by FairTestDetectorDigiTask::Exec(), and FairTestDetectorTimeDigiTask::Exec().
GetTrackID()
Int_t FairMCPoint::GetTrackID () const inline
event identifier
Definition at line 55 of file FairMCPoint.h.
References fTrackID.
Referenced by MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
GetX()
Double_t FairMCPoint::GetX () const inline
Definition at line 64 of file FairMCPoint.h.
References fX.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4PointDraw::Exec(), PixelDigitize::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
GetY()
Double_t FairMCPoint::GetY () const inline
Definition at line 65 of file FairMCPoint.h.
References fY.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4PointDraw::Exec(), PixelDigitize::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
GetZ()
Double_t FairMCPoint::GetZ () const inline
Definition at line 66 of file FairMCPoint.h.
References fZ.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4PointDraw::Exec(), PixelDigitize::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
Momentum()
void FairMCPoint::Momentum (TVector3 & mom) const inline
Definition at line 62 of file FairMCPoint.h.
References fPx, fPy, and fPz.
Position()
void FairMCPoint::Position (TVector3 & pos) const inline
Definition at line 67 of file FairMCPoint.h.
References fX, fY, and fZ.
Referenced by FairTestDetectorHitProducerSmearing::Exec().
Print()
void FairMCPoint::Print (const Option_t * opt = 0) const virtual
Output to screen
Reimplemented in FairRadLenPoint, FairRadMapPoint, FairTutorialDet2Point, FairTestDetectorPoint, FairTutorialDet1Point, FairTutorialDet4Point, PixelPoint, FairRutherfordPoint, NewDetectorPoint, and NewDetectorPoint.
Definition at line 59 of file FairMCPoint.cxx.
References fDetectorID, fELoss, fLength, fPx, fPy, fPz, fTime, fTrackID, fX, fY, and fZ.
PrintLinkInfo()
std::ostream& FairMultiLinkedData_Interface::PrintLinkInfo (std::ostream & out = std::cout) const inline inherited
Output.
Definition at line 66 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::PrintLinkInfo().
Referenced by FairTimeStamp::PrintTimeInfo().
ResetLinks()
void FairMultiLinkedData_Interface::ResetLinks () inherited
Definition at line 193 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
serialize()
template<class Archive > void FairMCPoint::serialize (Archive & ar, const unsigned int) inline
Definition at line 93 of file FairMCPoint.h.
References fDetectorID, fELoss, fEventId, fLength, fPx, fPy, fPz, fTime, fTrackID, fX, fY, and fZ.
SetDetectorID()
void FairMCPoint::SetDetectorID (Int_t detID) inline
Definition at line 79 of file FairMCPoint.h.
References fDetectorID.
SetEnergyLoss()
void FairMCPoint::SetEnergyLoss (Double_t eLoss) inline
Definition at line 77 of file FairMCPoint.h.
References fELoss.
SetEntryNr()
void FairMultiLinkedData_Interface::SetEntryNr (FairLink val) inherited
Definition at line 147 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetEntryNr().
Referenced by FairRingSorterTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetEventID()
void FairMCPoint::SetEventID (UInt_t eventId) inline
Modifiers
Definition at line 73 of file FairMCPoint.h.
References fEventId.
SetInsertHistory()
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) inherited
Definition at line 186 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetLength()
void FairMCPoint::SetLength (Double_t length) inline
Definition at line 76 of file FairMCPoint.h.
References fLength.
SetLink()
void FairMultiLinkedData_Interface::SetLink (FairLink link) inherited
Sets the Links with a single FairLink.
Definition at line 139 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetector::AddHit(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
SetLinks()
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 131 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetMomentum()
void FairMCPoint::SetMomentum (const TVector3 & mom) inline
Definition at line 129 of file FairMCPoint.h.
References fPx, fPy, and fPz.
SetPointerToLinks()
void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline inherited
Definition at line 55 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
SetPosition()
void FairMCPoint::SetPosition (const TVector3 & pos) inline
Definition at line 145 of file FairMCPoint.h.
References fX, fY, and fZ.
SetTime()
void FairMCPoint::SetTime (Double_t time) inline
Definition at line 75 of file FairMCPoint.h.
References fTime.
SetTrackID()
virtual void FairMCPoint::SetTrackID (Int_t id) inline virtual
Definition at line 74 of file FairMCPoint.h.
References fTrackID.
Referenced by MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
SetX()
void FairMCPoint::SetX (Double_t x) inline
Definition at line 80 of file FairMCPoint.h.
References fX.
SetXYZ()
void FairMCPoint::SetXYZ (Double_t x, Double_t y, Double_t z) inline
Definition at line 137 of file FairMCPoint.h.
References fX, fY, and fZ.
SetY()
void FairMCPoint::SetY (Double_t y) inline
Definition at line 81 of file FairMCPoint.h.
References fY.
SetZ()
void FairMCPoint::SetZ (Double_t z) inline
Definition at line 82 of file FairMCPoint.h.
References fZ.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 112 of file FairMCPoint.h.
Member Data Documentation
fDetectorID
Int_t FairMCPoint::fDetectorID protected
Detector unique identifier.
Definition at line 120 of file FairMCPoint.h.
Referenced by GetDetectorID(), PixelPoint::Print(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), FairTutorialDet4Point::Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), and SetDetectorID().
fELoss
Double32_t FairMCPoint::fELoss protected
Energy loss at this point [GeV].
Definition at line 119 of file FairMCPoint.h.
Referenced by GetEnergyLoss(), PixelPoint::Print(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), FairTutorialDet4Point::Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), and SetEnergyLoss().
fEventId
UInt_t FairMCPoint::fEventId protected
MC Event id.
Definition at line 115 of file FairMCPoint.h.
Referenced by GetEventID(), serialize(), and SetEventID().
fLength
Double32_t FairMCPoint::fLength protected
Track length since creation [cm].
Definition at line 118 of file FairMCPoint.h.
Referenced by GetLength(), PixelPoint::Print(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), FairTutorialDet4Point::Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), and SetLength().
fLink
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
fPx
Double32_t FairMCPoint::fPx protected
Definition at line 116 of file FairMCPoint.h.
Referenced by GetPx(), FairTestDetectorPoint::GetPxIn(), Momentum(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), and SetMomentum().
fPy
Double32_t FairMCPoint::fPy protected
Definition at line 116 of file FairMCPoint.h.
Referenced by GetPy(), FairTestDetectorPoint::GetPyIn(), Momentum(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), and SetMomentum().
fPz
Double32_t FairMCPoint::fPz protected
Momentum components [GeV].
Definition at line 116 of file FairMCPoint.h.
Referenced by GetPz(), FairTestDetectorPoint::GetPzIn(), Momentum(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), and SetMomentum().
fTime
Double32_t FairMCPoint::fTime protected
Time since event start [ns].
Definition at line 117 of file FairMCPoint.h.
Referenced by GetTime(), PixelPoint::Print(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), FairTutorialDet4Point::Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), and SetTime().
fTrackID
Int_t FairMCPoint::fTrackID protected
Track index.
Definition at line 114 of file FairMCPoint.h.
Referenced by GetTrackID(), PixelPoint::Print(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), FairTutorialDet4Point::Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), and SetTrackID().
fX
Double32_t FairMCPoint::fX protected
Definition at line 121 of file FairMCPoint.h.
Referenced by FairRadLenPoint::GetPosition(), FairRadMapPoint::GetPosition(), GetX(), FairTestDetectorPoint::GetXIn(), Position(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), SetPosition(), SetX(), and SetXYZ().
fY
Double32_t FairMCPoint::fY protected
Definition at line 121 of file FairMCPoint.h.
Referenced by FairRadLenPoint::GetPosition(), FairRadMapPoint::GetPosition(), GetY(), FairTestDetectorPoint::GetYIn(), Position(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), SetPosition(), SetXYZ(), and SetY().
fZ
Double32_t FairMCPoint::fZ protected
Position of hit [cm].
Definition at line 121 of file FairMCPoint.h.
Referenced by FairRadLenPoint::GetPosition(), FairRadMapPoint::GetPosition(), GetZ(), FairTestDetectorPoint::GetZIn(), Position(), PixelPoint::Print(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTutorialDet2Point::Print(), Print(), serialize(), SetPosition(), SetXYZ(), and SetZ().
The documentation for this class was generated from the following files:
FairMCPoint.h
FairMCPoint.cxx