FairRoot: FairMultiLinkedData Class Reference
FairMultiLinkedData Class Reference
#include <FairMultiLinkedData.h>
Public Member Functions
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual FairLink GetEntryNr () const
gives back the entryNr
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
virtual std::vector< FairLink > GetSortedMCTracks ()
Gives you a list of all FairLinks pointing to a "MCTrack" sorted by their weight.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetInsertHistory (Bool_t val)
Toggles if history of a link is inserted or not.
Bool_t GetInsertHistory () const
virtual void SetEntryNr (FairLink entry)
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void InsertHistory (FairLink link)
Adds the FairLinks of the inserted link to the set of links of this object.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
std::ostream & PrintLinkInfo (std::ostream &out=std::cout) const
Output.
Protected Member Functions
virtual void SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t, Float_t)
ClassDef (FairMultiLinkedData, 4)
Protected Attributes
std::set< FairLink > fLinks
FairLink fEntryNr
Bool_t fPersistanceCheck
Bool_t fInsertHistory
Int_t fVerbose
Int_t fDefaultType
Friends
std::ostream & operator<< (std::ostream &out, const FairMultiLinkedData &data)
Output.
Detailed Description
FairMultiLinkedData.h
Date
Dec 7, 2009
Author
T.Stockmanns t.sto.nosp@m.ckma.nosp@m.nns@f.nosp@m.z-ju.nosp@m.elich.nosp@m..de
Definition at line 30 of file FairMultiLinkedData.h.
Constructor & Destructor Documentation
FairMultiLinkedData() [1/4]
FairMultiLinkedData::FairMultiLinkedData ()
Default constructor.
Definition at line 28 of file FairMultiLinkedData.cxx.
FairMultiLinkedData() [2/4]
FairMultiLinkedData::FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck = kTRUE)
Constructor.
Definition at line 40 of file FairMultiLinkedData.cxx.
FairMultiLinkedData() [3/4]
FairMultiLinkedData::FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId = -1, Int_t evtId = -1, Bool_t persistanceCheck = kTRUE, Bool_t bypass = kFALSE, Float_t mult = 1.0)
Constructor.
Definition at line 51 of file FairMultiLinkedData.cxx.
References FairRootManager::Instance(), and SimpleAddLinks().
FairMultiLinkedData() [4/4]
FairMultiLinkedData::FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId = -1, Int_t evtId = -1, Bool_t persistanceCheck = kTRUE, Bool_t bypass = kFALSE, Float_t mult = 1.0)
Constructor.
Definition at line 65 of file FairMultiLinkedData.cxx.
References SimpleAddLinks().
~FairMultiLinkedData()
virtual FairMultiLinkedData::~FairMultiLinkedData () inline virtual
Definition at line 38 of file FairMultiLinkedData.h.
Member Function Documentation
AddAllWeights()
void FairMultiLinkedData::AddAllWeights (Double_t weight) virtual
Adds weight to all Links.
Definition at line 328 of file FairMultiLinkedData.cxx.
References fLinks, FairLink::GetWeight(), and FairLink::SetWeight().
Referenced by FairMCDataCrawler::GetNextStage(), and FairMCMatch::GetNextStage().
AddLink()
void FairMultiLinkedData::AddLink (FairLink link, Bool_t bypass = kFALSE, Float_t mult = 1.0) virtual
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
Definition at line 116 of file FairMultiLinkedData.cxx.
References AddLinks(), FairRootManager::CheckBranch(), fInsertHistory, fPersistanceCheck, fVerbose, FairRootManager::GetBranchName(), FairLink::GetIndex(), FairRootManager::GetMCTrackBranchId(), GetNLinks(), FairRootManager::GetObject(), FairLink::GetType(), FairLink::GetWeight(), InsertHistory(), InsertLink(), FairRootManager::Instance(), and FairLink::SetWeight().
Referenced by FairMultiLinkedData_Interface::AddLink(), AddLinks(), FairMCDataCrawler::AddToFinalStage(), FairMCMatch::AddToFinalStage(), FairMCMatch::FindStagesPointingToLinks(), FairMCMatch::GetMCInfoForwardSingle(), FairMCObject::PosInList(), FairMCObject::SetEntry(), and SetLink().
AddLinks()
void FairMultiLinkedData::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
Definition at line 106 of file FairMultiLinkedData.cxx.
References AddLink(), GetLinks(), FairLink::GetWeight(), and FairLink::SetWeight().
Referenced by AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMCMatch::FindLinksToStage(), FairMCMatch::FindStagesPointingToLink(), FairMCObject::GetLinksWithType(), and SetLinks().
ClassDef()
FairMultiLinkedData::ClassDef (FairMultiLinkedData , 4) protected
DeleteLink() [1/2]
virtual void FairMultiLinkedData::DeleteLink (FairLink link) inline virtual
Deletes a link ouf of fLinks.
Definition at line 77 of file FairMultiLinkedData.h.
References DeleteLink(), FairLink::GetIndex(), and FairLink::GetType().
Referenced by DeleteLink().
DeleteLink() [2/2]
void FairMultiLinkedData::DeleteLink (Int_t type, Int_t index) virtual
Deletes a link ouf of fLinks.
Definition at line 267 of file FairMultiLinkedData.cxx.
GetData()
TObject * FairMultiLinkedData::GetData (FairLink & myLink)
Get the TObject the Link is pointing to.
Definition at line 301 of file FairMultiLinkedData.cxx.
References FairRootManager::CheckBranch(), FairRootManager::GetBranchName(), FairLink::GetIndex(), FairRootManager::GetObject(), FairLink::GetType(), and FairRootManager::Instance().
GetDefaultType()
virtual Int_t FairMultiLinkedData::GetDefaultType () inline virtual
Definition at line 47 of file FairMultiLinkedData.h.
References fDefaultType.
GetEntryNr()
virtual FairLink FairMultiLinkedData::GetEntryNr () const inline virtual
gives back the entryNr
Definition at line 41 of file FairMultiLinkedData.h.
References fEntryNr.
Referenced by FairMultiLinkedData_Interface::GetEntryNr(), and PrintLinkInfo().
GetInsertHistory()
Bool_t FairMultiLinkedData::GetInsertHistory () const inline
Definition at line 54 of file FairMultiLinkedData.h.
References fInsertHistory.
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface().
GetLink()
FairLink FairMultiLinkedData::GetLink (Int_t pos) const virtual
returns the FairLink at the given position
Definition at line 78 of file FairMultiLinkedData.cxx.
References fLinks.
Referenced by FairMCMatch::CreateArtificialStage(), FairMCMatch::FindStagesPointingToLinks(), FairMultiLinkedData_Interface::GetLink(), FairMCDataCrawler::GetNextStage(), FairMCMatch::GetNextStage(), and PrintLinkInfo().
GetLinks()
virtual std::set<FairLink> FairMultiLinkedData::GetLinks () const inline virtual
returns stored links as FairLinks
Definition at line 40 of file FairMultiLinkedData.h.
References fLinks.
Referenced by AddLinks(), FairMultiLinkedData_Interface::GetLinks(), GetSortedMCTracks(), InsertHistory(), and FairMCObject::SetEntry().
GetLinksWithType()
FairMultiLinkedData FairMultiLinkedData::GetLinksWithType (Int_t type) const virtual
Gives you a list of links which contain the given type.
Definition at line 276 of file FairMultiLinkedData.cxx.
References fLinks, and InsertLink().
Referenced by FairMultiLinkedData_Interface::GetLinksWithType(), and GetSortedMCTracks().
GetNLinks()
virtual Int_t FairMultiLinkedData::GetNLinks () const inline virtual
returns the number of stored links
Definition at line 42 of file FairMultiLinkedData.h.
References fLinks.
Referenced by AddLink(), FairMCMatch::CreateArtificialStage(), FairMCMatch::FindStagesPointingToLinks(), FairMCDataCrawler::GetNextStage(), FairMCMatch::GetNextStage(), FairMultiLinkedData_Interface::GetNLinks(), and PrintLinkInfo().
GetPersistanceCheck()
Bool_t FairMultiLinkedData::GetPersistanceCheck () inline
Returns the value of PersistanceCheck.
Definition at line 48 of file FairMultiLinkedData.h.
References fPersistanceCheck.
GetSortedMCTracks()
std::vector< FairLink > FairMultiLinkedData::GetSortedMCTracks () virtual
Gives you a list of all FairLinks pointing to a "MCTrack" sorted by their weight.
Definition at line 292 of file FairMultiLinkedData.cxx.
References GetLinks(), GetLinksWithType(), FairRootManager::Instance(), and LargerWeight().
Referenced by FairMultiLinkedData_Interface::GetSortedMCTracks().
GetVerbose()
Int_t FairMultiLinkedData::GetVerbose () inline
Returns the verbosity level.
Definition at line 49 of file FairMultiLinkedData.h.
References fVerbose.
InsertHistory()
void FairMultiLinkedData::InsertHistory (FairLink link) virtual
Adds the FairLinks of the inserted link to the set of links of this object.
Definition at line 200 of file FairMultiLinkedData.cxx.
References fVerbose, FairRootManager::GetBranchName(), FairLink::GetEntry(), FairRootManager::GetEntryNr(), FairLink::GetIndex(), GetLinks(), FairRootManager::GetMCTrackBranchId(), FairRootManager::GetObject(), FairLink::GetType(), InsertLink(), and FairRootManager::Instance().
Referenced by AddLink().
InsertLink()
void FairMultiLinkedData::InsertLink (FairLink link) virtual
Inserts a link into the list of links without persistance checking.
Definition at line 182 of file FairMultiLinkedData.cxx.
References FairLink::AddWeight(), fLinks, FairLink::GetType(), FairLink::GetWeight(), and FairLinkManager::Instance().
Referenced by AddLink(), GetLinksWithType(), and InsertHistory().
IsLinkInList() [1/2]
virtual Bool_t FairMultiLinkedData::IsLinkInList (FairLink link) inline virtual
Test if a given link is in fLinks.
Definition at line 72 of file FairMultiLinkedData.h.
References FairLink::GetIndex(), FairLink::GetType(), and IsLinkInList().
Referenced by IsLinkInList().
IsLinkInList() [2/2]
Bool_t FairMultiLinkedData::IsLinkInList (Int_t type, Int_t index) virtual
Same as IsLinkInList(FairLink) just with type and index given separately.
Definition at line 250 of file FairMultiLinkedData.cxx.
References LinkPosInList().
LinkPosInList() [1/2]
virtual Int_t FairMultiLinkedData::LinkPosInList (FairLink link) inline virtual
returns position of link in fLinks. If it is not in the list -1 is returned
Definition at line 74 of file FairMultiLinkedData.h.
References FairLink::GetIndex(), FairLink::GetType(), and LinkPosInList().
Referenced by IsLinkInList(), and LinkPosInList().
LinkPosInList() [2/2]
Int_t FairMultiLinkedData::LinkPosInList (Int_t type, Int_t index) virtual
Same as LinkPosInList(FairLink)
Definition at line 258 of file FairMultiLinkedData.cxx.
References fLinks.
MultiplyAllWeights()
void FairMultiLinkedData::MultiplyAllWeights (Double_t weight) virtual
Multiplies all Links with weight.
Definition at line 339 of file FairMultiLinkedData.cxx.
References fLinks, FairLink::GetWeight(), and FairLink::SetWeight().
Referenced by FairMCMatch::GetMCInfoBackwardSingle(), FairMCDataCrawler::GetNextStage(), and FairMCMatch::GetNextStage().
PrintLinkInfo()
std::ostream& FairMultiLinkedData::PrintLinkInfo (std::ostream & out = std::cout) const inline
Output.
Definition at line 84 of file FairMultiLinkedData.h.
References GetEntryNr(), GetLink(), GetNLinks(), and FairLink::PrintLinkInfo().
Referenced by FairMultiLinkedData_Interface::PrintLinkInfo().
Reset()
virtual void FairMultiLinkedData::Reset () inline virtual
Definition at line 80 of file FairMultiLinkedData.h.
References ResetLinks().
Referenced by FairMCMatch::ClearFinalStage().
ResetLinks()
virtual void FairMultiLinkedData::ResetLinks () inline virtual
Clears fLinks.
Definition at line 81 of file FairMultiLinkedData.h.
References fLinks.
Referenced by FairMCDataCrawler::GetInfo(), Reset(), and FairMultiLinkedData_Interface::ResetLinks().
SetAllWeights()
void FairMultiLinkedData::SetAllWeights (Double_t weight) virtual
Sets a common weight for Links.
Definition at line 317 of file FairMultiLinkedData.cxx.
References fLinks, and FairLink::SetWeight().
SetDefaultType()
virtual void FairMultiLinkedData::SetDefaultType (Int_t type) inline virtual
Definition at line 50 of file FairMultiLinkedData.h.
References fDefaultType.
SetEntryNr()
virtual void FairMultiLinkedData::SetEntryNr (FairLink entry) inline virtual
Definition at line 56 of file FairMultiLinkedData.h.
References fEntryNr.
Referenced by FairMultiLinkedData_Interface::SetEntryNr().
SetInsertHistory()
virtual void FairMultiLinkedData::SetInsertHistory (Bool_t val) inline virtual
Toggles if history of a link is inserted or not.
Definition at line 53 of file FairMultiLinkedData.h.
References fInsertHistory.
Referenced by FairMultiLinkedData_Interface::SetInsertHistory().
SetLink()
void FairMultiLinkedData::SetLink (FairLink link, Bool_t bypass = kFALSE, Float_t mult = 1.0) virtual
Sets the Links with a single FairLink.
Definition at line 97 of file FairMultiLinkedData.cxx.
References AddLink(), fLinks, FairLink::GetWeight(), and FairLink::SetWeight().
Referenced by FairMCMatch::CreateArtificialStage(), and FairMultiLinkedData_Interface::SetLink().
SetLinks()
void FairMultiLinkedData::SetLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 90 of file FairMultiLinkedData.cxx.
References AddLinks(), and fLinks.
Referenced by FairMCMatch::GetMCInfoBackwardSingle(), FairMCMatch::GetMCInfoForwardSingle(), and FairMultiLinkedData_Interface::SetLinks().
SetPersistanceCheck()
virtual void FairMultiLinkedData::SetPersistanceCheck (Bool_t check) inline virtual
Controls if a persistance check of a link is done or not.
Definition at line 51 of file FairMultiLinkedData.h.
References fPersistanceCheck.
Referenced by FairMCObject::AdoptSize(), FairMCMatch::CreateArtificialStage(), FairMCEntry::FairMCEntry(), FairMCMatch::FairMCMatch(), FairMCMatch::FindLinksToStage(), FairMCMatch::FindStagesPointingToLink(), FairMCMatch::FindStagesPointingToLinks(), FairMCMatch::GetMCInfoForwardSingle(), FairMCObject::PosInList(), and FairMCObject::SetEntry().
SetVerbose()
virtual void FairMultiLinkedData::SetVerbose (Int_t level) inline virtual
Sets the verbosity level.
Definition at line 52 of file FairMultiLinkedData.h.
References fVerbose.
SimpleAddLinks()
virtual void FairMultiLinkedData::SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t , Float_t) inline protected virtual
Definition at line 107 of file FairMultiLinkedData.h.
References fLinks.
Referenced by FairMultiLinkedData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const FairMultiLinkedData & data) friend
Output.
Definition at line 95 of file FairMultiLinkedData.h.
Member Data Documentation
fDefaultType
Int_t FairMultiLinkedData::fDefaultType protected
Definition at line 112 of file FairMultiLinkedData.h.
Referenced by GetDefaultType(), and SetDefaultType().
fEntryNr
FairLink FairMultiLinkedData::fEntryNr protected
Definition at line 102 of file FairMultiLinkedData.h.
Referenced by GetEntryNr(), and SetEntryNr().
fInsertHistory
Bool_t FairMultiLinkedData::fInsertHistory protected
Definition at line 104 of file FairMultiLinkedData.h.
Referenced by AddLink(), GetInsertHistory(), and SetInsertHistory().
fLinks
std::set<FairLink> FairMultiLinkedData::fLinks protected
Definition at line 101 of file FairMultiLinkedData.h.
Referenced by AddAllWeights(), GetLink(), GetLinks(), GetLinksWithType(), GetNLinks(), InsertLink(), LinkPosInList(), MultiplyAllWeights(), FairMCEntry::RemoveType(), ResetLinks(), SetAllWeights(), SetLink(), SetLinks(), and SimpleAddLinks().
fPersistanceCheck
Bool_t FairMultiLinkedData::fPersistanceCheck protected
Definition at line 103 of file FairMultiLinkedData.h.
Referenced by AddLink(), GetPersistanceCheck(), and SetPersistanceCheck().
fVerbose
Int_t FairMultiLinkedData::fVerbose protected
Definition at line 105 of file FairMultiLinkedData.h.
Referenced by AddLink(), GetVerbose(), InsertHistory(), and SetVerbose().
The documentation for this class was generated from the following files:
FairMultiLinkedData.h
FairMultiLinkedData.cxx