FairRroot: FairMQTransportFactorySHM Class Reference
FairMQTransportFactorySHM Class Reference
#include <FairMQTransportFactorySHM.h>
Public Member Functions
FairMQTransportFactorySHM (const std::string &id="", const FairMQProgOptions *config=nullptr)
FairMQTransportFactorySHM (const FairMQTransportFactorySHM &)=delete
FairMQTransportFactorySHM operator= (const FairMQTransportFactorySHM &)=delete
FairMQMessagePtr CreateMessage () const override
Create empty FairMQMessage.
FairMQMessagePtr CreateMessage (const size_t size) const override
Create new FairMQMessage of specified size.
FairMQMessagePtr CreateMessage (void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr) const override
Create new FairMQMessage with user provided buffer and size.
FairMQMessagePtr CreateMessage (FairMQUnmanagedRegionPtr &region, void *data, const size_t size, void *hint=0) const override
FairMQSocketPtr CreateSocket (const std::string &type, const std::string &name) const override
Create a socket.
FairMQPollerPtr CreatePoller (const std::vector< FairMQChannel > &channels) const override
Create a poller for a single channel (all subchannels)
FairMQPollerPtr CreatePoller (const std::vector< const FairMQChannel * > &channels) const override
Create a poller for specific channels.
FairMQPollerPtr CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> &channelsMap, const std::vector< std::string > &channelList) const override
Create a poller for specific channels (all subchannels)
FairMQPollerPtr CreatePoller (const FairMQSocket &cmdSocket, const FairMQSocket &dataSocket) const override
Create a poller for two sockets.
FairMQUnmanagedRegionPtr CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback=nullptr) const override
FairMQ::Transport GetType () const override
Get transport type.
void Interrupt () override
void Resume () override
~FairMQTransportFactorySHM () override
auto GetId () const -> const std::string
template<typename T >
FairMQMessagePtr NewSimpleMessage (const T &data) const
template<std::size_t N>
FairMQMessagePtr NewSimpleMessage (const char(&data)[N]) const
FairMQMessagePtr NewSimpleMessage (const std::string &str) const
template<typename T >
FairMQMessagePtr NewStaticMessage (const T &data) const
FairMQMessagePtr NewStaticMessage (const std::string &str) const
Static Public Member Functions
static auto CreateTransportFactory (const std::string &type, const std::string &id="", const FairMQProgOptions *config=nullptr) -> std::shared_ptr< FairMQTransportFactory >
static void FairMQNoCleanup (void *, void *)
template<typename T >
static void FairMQSimpleMsgCleanup (void *, void *obj)
Private Member Functions
void SendHeartbeats ()
void StartMonitor ()
Private Attributes
std::string fDeviceId
std::string fSessionName
void * fContext
std::thread fHeartbeatThread
std::atomic< bool > fSendHeartbeats
std::unique_ptr< boost::interprocess::named_mutex > fShMutex
fair::mq::shmem::DeviceCounter * fDeviceCounter
std::unique_ptr< fair::mq::shmem::Manager > fManager
Static Private Attributes
static FairMQ::Transport fTransportType = FairMQ::Transport::SHM
Detailed Description
Definition at line 29 of file FairMQTransportFactorySHM.h.
Constructor & Destructor Documentation
FairMQTransportFactorySHM::FairMQTransportFactorySHM (const std::string & id = "", const FairMQProgOptions * config = nullptr)
FairMQTransportFactorySHM::FairMQTransportFactorySHM (const FairMQTransportFactorySHM &) delete
FairMQTransportFactorySHM::~FairMQTransportFactorySHM () override
Definition at line 261 of file FairMQTransportFactorySHM.cxx.
References fair::mq::shmem::DeviceCounter::fCount, fDeviceCounter, fHeartbeatThread, fManager, fSendHeartbeats, fShMutex, and LOG.
Member Function Documentation
FairMQMessagePtr FairMQTransportFactorySHM::CreateMessage () const override virtual
Create empty FairMQMessage.
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 210 of file FairMQTransportFactorySHM.cxx.
References fManager.
FairMQMessagePtr FairMQTransportFactorySHM::CreateMessage (const size_t size) const override virtual
Create new FairMQMessage of specified size.
Parameters
size message size
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 215 of file FairMQTransportFactorySHM.cxx.
References fManager.
FairMQMessagePtr FairMQTransportFactorySHM::CreateMessage (void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr) const override virtual
Create new FairMQMessage with user provided buffer and size.
Parameters
data pointer to user provided buffer
size size of the user provided buffer
ffn callback, called when the message is transfered (and can be deleted)
obj optional helper pointer that can be used in the callback
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 220 of file FairMQTransportFactorySHM.cxx.
References fManager.
FairMQMessagePtr FairMQTransportFactorySHM::CreateMessage (FairMQUnmanagedRegionPtr & region, void * data, const size_t size, void * hint = 0) const override virtual
Implements FairMQTransportFactory.
Definition at line 225 of file FairMQTransportFactorySHM.cxx.
References fManager.
FairMQPollerPtr FairMQTransportFactorySHM::CreatePoller (const std::vector< FairMQChannel > & channels) const override virtual
Create a poller for a single channel (all subchannels)
Implements FairMQTransportFactory.
FairMQPollerPtr FairMQTransportFactorySHM::CreatePoller (const std::vector< const FairMQChannel * > & channels) const override virtual
Create a poller for specific channels.
Implements FairMQTransportFactory.
Definition at line 241 of file FairMQTransportFactorySHM.cxx.
FairMQPollerPtr FairMQTransportFactorySHM::CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> & channelsMap, const std::vector< std::string > & channelList) const override virtual
Create a poller for specific channels (all subchannels)
Implements FairMQTransportFactory.
FairMQPollerPtr FairMQTransportFactorySHM::CreatePoller (const FairMQSocket & cmdSocket, const FairMQSocket & dataSocket) const override virtual
Create a poller for two sockets.
Implements FairMQTransportFactory.
Definition at line 251 of file FairMQTransportFactorySHM.cxx.
FairMQSocketPtr FairMQTransportFactorySHM::CreateSocket (const std::string & type, const std::string & name) const override virtual
Create a socket.
Implements FairMQTransportFactory.
Definition at line 230 of file FairMQTransportFactorySHM.cxx.
References fManager, and FairMQTransportFactory::GetId().
auto FairMQTransportFactory::CreateTransportFactory (const std::string & type, const std::string & id = "", const FairMQProgOptions * config = nullptr) -> std::shared_ptr<FairMQTransportFactory> static inherited
Definition at line 30 of file FairMQTransportFactory.cxx.
References LOG, and fair::mq::tools::Uuid().
Referenced by FairMQDevice::AddTransport().
FairMQUnmanagedRegionPtr FairMQTransportFactorySHM::CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback = nullptr) const override virtual
Implements FairMQTransportFactory.
Definition at line 256 of file FairMQTransportFactorySHM.cxx.
References fManager.
static void FairMQTransportFactory::FairMQNoCleanup (void * , void *) inline static inherited
Definition at line 81 of file FairMQTransportFactory.h.
Referenced by FairMQTransportFactory::NewStaticMessage().
template<typename T > static void FairMQTransportFactory::FairMQSimpleMsgCleanup (void * , void * obj) inline static inherited
Definition at line 86 of file FairMQTransportFactory.h.
auto FairMQTransportFactory::GetId () const -> const std::string inline inherited
Definition at line 38 of file FairMQTransportFactory.h.
References FairMQTransportFactory::fkId.
Referenced by FairMQTransportFactoryNN::CreateSocket(), CreateSocket(), and FairMQTransportFactoryZMQ::CreateSocket().
FairMQ::Transport FairMQTransportFactorySHM::GetType () const override virtual
Get transport type.
Implements FairMQTransportFactory.
Definition at line 312 of file FairMQTransportFactorySHM.cxx.
References fTransportType.
void FairMQTransportFactorySHM::Interrupt () inline override virtual
Implements FairMQTransportFactory.
Definition at line 52 of file FairMQTransportFactorySHM.h.
References FairMQSocketSHM::Interrupt().
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const T & data) const inline inherited
Definition at line 92 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
template<std::size_t N> FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const char(&) data[N]) const inline inherited
Definition at line 101 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const std::string & str) const inline inherited
Definition at line 107 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const T & data) const inline inherited
Definition at line 115 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage(), and FairMQTransportFactory::FairMQNoCleanup().
FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const std::string & str) const inline inherited
Definition at line 120 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage(), and FairMQTransportFactory::FairMQNoCleanup().
FairMQTransportFactorySHM FairMQTransportFactorySHM::operator= (const FairMQTransportFactorySHM &) delete
void FairMQTransportFactorySHM::Resume () inline override virtual
Implements FairMQTransportFactory.
Definition at line 53 of file FairMQTransportFactorySHM.h.
References FairMQSocketSHM::Resume().
void FairMQTransportFactorySHM::SendHeartbeats () private
Definition at line 184 of file FairMQTransportFactorySHM.cxx.
References fDeviceId, fSendHeartbeats, and LOG.
void FairMQTransportFactorySHM::StartMonitor () private
Definition at line 146 of file FairMQTransportFactorySHM.cxx.
References fManager, and LOG.
Member Data Documentation
void* FairMQTransportFactorySHM::fContext private
Definition at line 64 of file FairMQTransportFactorySHM.h.
fair::mq::shmem::DeviceCounter* FairMQTransportFactorySHM::fDeviceCounter private
Definition at line 68 of file FairMQTransportFactorySHM.h.
Referenced by ~FairMQTransportFactorySHM().
std::string FairMQTransportFactorySHM::fDeviceId private
Definition at line 62 of file FairMQTransportFactorySHM.h.
Referenced by SendHeartbeats().
std::thread FairMQTransportFactorySHM::fHeartbeatThread private
Definition at line 65 of file FairMQTransportFactorySHM.h.
Referenced by ~FairMQTransportFactorySHM().
std::unique_ptr<fair::mq::shmem::Manager> FairMQTransportFactorySHM::fManager private
Definition at line 69 of file FairMQTransportFactorySHM.h.
Referenced by CreateMessage(), CreateSocket(), CreateUnmanagedRegion(), StartMonitor(), and ~FairMQTransportFactorySHM().
std::atomic<bool> FairMQTransportFactorySHM::fSendHeartbeats private
Definition at line 66 of file FairMQTransportFactorySHM.h.
Referenced by SendHeartbeats(), and ~FairMQTransportFactorySHM().
std::string FairMQTransportFactorySHM::fSessionName private
Definition at line 63 of file FairMQTransportFactorySHM.h.
std::unique_ptr<boost::interprocess::named_mutex> FairMQTransportFactorySHM::fShMutex private
Definition at line 67 of file FairMQTransportFactorySHM.h.
Referenced by ~FairMQTransportFactorySHM().
FairMQ::Transport FairMQTransportFactorySHM::fTransportType = FairMQ::Transport::SHM static private
Definition at line 61 of file FairMQTransportFactorySHM.h.
Referenced by GetType().
The documentation for this class was generated from the following files:
FairMQTransportFactorySHM.h
FairMQTransportFactorySHM.cxx