FairRroot: fair::mq::plugins::Control Class Reference
fair::mq::plugins::Control Class Reference
#include <Control.h>
Public Types
using ProgOptions = boost::optional< boost::program_options::options_description >
using Version = tools::Version
using DeviceState = fair::mq::PluginServices::DeviceState
using DeviceStateTransition = fair::mq::PluginServices::DeviceStateTransition
Public Member Functions
Control (const std::string name, const Plugin::Version version, const std::string maintainer, const std::string homepage, PluginServices *pluginServices)
~Control ()
auto GetName () const -> const std::string &
auto GetVersion () const -> const Version
auto GetMaintainer () const -> const std::string &
auto GetHomepage () const -> const std::string &
auto ToDeviceState (const std::string &state) const -> DeviceState
auto ToDeviceStateTransition (const std::string &transition) const -> DeviceStateTransition
auto ToStr (DeviceState state) const -> std::string
auto ToStr (DeviceStateTransition transition) const -> std::string
auto GetCurrentDeviceState () const -> DeviceState
auto TakeDeviceControl () -> void
auto StealDeviceControl () -> void
auto ReleaseDeviceControl () -> void
auto ChangeDeviceState (const DeviceStateTransition next) -> void
auto SubscribeToDeviceStateChange (std::function< void(DeviceState)> callback) -> void
auto UnsubscribeFromDeviceStateChange () -> void
auto PropertyExists (const std::string &key) -> int
template<typename T >
auto SetProperty (const std::string &key, T val) -> void
template<typename T >
auto GetProperty (const std::string &key) const -> T
auto GetPropertyAsString (const std::string &key) const -> std::string
auto GetChannelInfo () const -> std::unordered_map< std::string, int >
auto GetPropertyKeys () const -> std::vector< std::string >
template<typename T >
auto SubscribeToPropertyChange (std::function< void(const std::string &key, T newValue)> callback) -> void
template<typename T >
auto UnsubscribeFromPropertyChange () -> void
auto SubscribeToPropertyChangeAsString (std::function< void(const std::string &key, std::string newValue)> callback) -> void
auto UnsubscribeFromPropertyChangeAsString () -> void
Static Public Member Functions
static auto NoProgramOptions () -> ProgOptions
Private Member Functions
auto InteractiveMode () -> void
auto PrintInteractiveHelp () -> void
auto StaticMode () -> void
auto WaitForNextState () -> DeviceState
auto SignalHandler (int signal) -> void
auto RunShutdownSequence () -> void
auto RunStartupSequence () -> void
auto EmptyEventQueue () -> void
Private Attributes
std::thread fControllerThread
std::thread fSignalHandlerThread
std::queue< DeviceState > fEvents
std::mutex fEventsMutex
std::condition_variable fNewEvent
std::atomic< bool > fDeviceTerminationRequested
Detailed Description
Definition at line 28 of file Control.h.
Member Typedef Documentation
using fair::mq::Plugin::DeviceState = fair::mq::PluginServices::DeviceState inherited
Definition at line 71 of file Plugin.h.
using fair::mq::Plugin::DeviceStateTransition = fair::mq::PluginServices::DeviceStateTransition inherited
Definition at line 72 of file Plugin.h.
using fair::mq::Plugin::ProgOptions = boost::optional<boost::program_options::options_description> inherited
Definition at line 41 of file Plugin.h.
using fair::mq::Plugin::Version = tools::Version inherited
Definition at line 43 of file Plugin.h.
Constructor & Destructor Documentation
fair::mq::plugins::Control::Control (const std::string name, const Plugin::Version version, const std::string maintainer, const std::string homepage, PluginServices * pluginServices)
Definition at line 36 of file Control.cxx.
fair::mq::plugins::Control::~Control ()
Definition at line 335 of file Control.cxx.
References fControllerThread, and fSignalHandlerThread.
Member Function Documentation
auto fair::mq::Plugin::ChangeDeviceState (const DeviceStateTransition next) -> void inline inherited
Definition at line 81 of file Plugin.h.
References fair::mq::PluginServices::ChangeDeviceState(), fair::mq::Plugin::fkName, and fair::mq::Plugin::fPluginServices.
auto fair::mq::plugins::Control::EmptyEventQueue () -> void private
Definition at line 329 of file Control.cxx.
auto fair::mq::Plugin::GetChannelInfo () const -> std::unordered_map<std::string, int> inline inherited
Definition at line 93 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetChannelInfo().
auto fair::mq::Plugin::GetCurrentDeviceState () const -> DeviceState inline inherited
Definition at line 77 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetCurrentDeviceState().
auto fair::mq::Plugin::GetHomepage () const -> const std::string& inline inherited
Definition at line 56 of file Plugin.h.
References fair::mq::Plugin::fkHomepage.
auto fair::mq::Plugin::GetMaintainer () const -> const std::string& inline inherited
Definition at line 55 of file Plugin.h.
References fair::mq::Plugin::fkMaintainer.
auto fair::mq::Plugin::GetName () const -> const std::string& inline inherited
Definition at line 53 of file Plugin.h.
References fair::mq::Plugin::fkName.
template<typename T > auto fair::mq::Plugin::GetProperty (const std::string & key) const -> T inline inherited
Definition at line 91 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetProperty().
auto fair::mq::Plugin::GetPropertyAsString (const std::string & key) const -> std::string inline inherited
Definition at line 92 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetPropertyAsString().
auto fair::mq::Plugin::GetPropertyKeys () const -> std::vector<std::string> inline inherited
Definition at line 94 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetPropertyKeys().
auto fair::mq::Plugin::GetVersion () const -> const Version inline inherited
Definition at line 54 of file Plugin.h.
References fair::mq::Plugin::fkVersion.
auto fair::mq::plugins::Control::InteractiveMode () -> void private
Definition at line 96 of file Control.cxx.
References fair::debug, fair::info, and LOG.
static auto fair::mq::Plugin::NoProgramOptions () -> ProgOptions inline static inherited
Definition at line 67 of file Plugin.h.
auto fair::mq::plugins::Control::PrintInteractiveHelp () -> void private
Definition at line 198 of file Control.cxx.
References fair::info, and LOG.
auto fair::mq::Plugin::PropertyExists (const std::string & key) -> int inline inherited
Definition at line 87 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::PropertyExists().
auto fair::mq::Plugin::ReleaseDeviceControl () -> void inline inherited
Definition at line 80 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ReleaseDeviceControl().
auto fair::mq::plugins::Control::RunShutdownSequence () -> void private
Definition at line 276 of file Control.cxx.
Referenced by SignalHandler().
auto fair::mq::plugins::Control::RunStartupSequence () -> void private
Definition at line 310 of file Control.cxx.
template<typename T > auto fair::mq::Plugin::SetProperty (const std::string & key, T val) -> void inline inherited
Definition at line 89 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SetProperty().
auto fair::mq::plugins::Control::SignalHandler (int signal) -> void private
Definition at line 245 of file Control.cxx.
References fair::info, LOG, RunShutdownSequence(), and fair::warn.
auto fair::mq::plugins::Control::StaticMode () -> void private
Definition at line 217 of file Control.cxx.
References fair::debug, and LOG.
auto fair::mq::Plugin::StealDeviceControl () -> void inline inherited
Definition at line 79 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::StealDeviceControl().
auto fair::mq::Plugin::SubscribeToDeviceStateChange (std::function< void(DeviceState)> callback) -> void inline inherited
Definition at line 82 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToDeviceStateChange().
Referenced by fair::mq::test::DummyPlugin::DummyPlugin().
template<typename T > auto fair::mq::Plugin::SubscribeToPropertyChange (std::function< void(const std::string &key, T newValue)> callback) -> void inline inherited
Definition at line 96 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToPropertyChange().
auto fair::mq::Plugin::SubscribeToPropertyChangeAsString (std::function< void(const std::string &key, std::string newValue)> callback) -> void inline inherited
Definition at line 99 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToPropertyChangeAsString().
auto fair::mq::Plugin::TakeDeviceControl () -> void inline inherited
Definition at line 78 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::TakeDeviceControl().
auto fair::mq::Plugin::ToDeviceState (const std::string & state) const -> DeviceState inline inherited
Definition at line 73 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, fair::state, and fair::mq::PluginServices::ToDeviceState().
auto fair::mq::Plugin::ToDeviceStateTransition (const std::string & transition) const -> DeviceStateTransition inline inherited
Definition at line 74 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ToDeviceStateTransition().
auto fair::mq::Plugin::ToStr (DeviceState state) const -> std::string inline inherited
Definition at line 75 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, fair::state, and fair::mq::PluginServices::ToStr().
auto fair::mq::Plugin::ToStr (DeviceStateTransition transition) const -> std::string inline inherited
Definition at line 76 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ToStr().
auto fair::mq::Plugin::UnsubscribeFromDeviceStateChange () -> void inline inherited
Definition at line 83 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromDeviceStateChange().
Referenced by fair::mq::test::DummyPlugin::DummyPlugin().
template<typename T > auto fair::mq::Plugin::UnsubscribeFromPropertyChange () -> void inline inherited
Definition at line 98 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromPropertyChange().
auto fair::mq::Plugin::UnsubscribeFromPropertyChangeAsString () -> void inline inherited
Definition at line 100 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromPropertyChangeAsString().
auto fair::mq::plugins::Control::WaitForNextState () -> DeviceState private
Definition at line 204 of file Control.cxx.
Member Data Documentation
std::thread fair::mq::plugins::Control::fControllerThread private
Definition at line 45 of file Control.h.
Referenced by ~Control().
std::atomic<bool> fair::mq::plugins::Control::fDeviceTerminationRequested private
Definition at line 50 of file Control.h.
std::queue<DeviceState> fair::mq::plugins::Control::fEvents private
Definition at line 47 of file Control.h.
std::mutex fair::mq::plugins::Control::fEventsMutex private
Definition at line 48 of file Control.h.
std::condition_variable fair::mq::plugins::Control::fNewEvent private
Definition at line 49 of file Control.h.
std::thread fair::mq::plugins::Control::fSignalHandlerThread private
Definition at line 46 of file Control.h.
Referenced by ~Control().
The documentation for this class was generated from the following files:
Control.h
Control.cxx