FairRoot: FairMCPointDraw Class Reference
FairMCPointDraw Class Reference
#include <FairMCPointDraw.h>
Public Member Functions
FairMCPointDraw ()
FairMCPointDraw (const char *name, Color_t color, Style_t mstyle, Int_t iVerbose=1)
virtual ~FairMCPointDraw ()
void SetVerbose (Int_t iVerbose)
virtual void Exec (Option_t *option)
void Reset ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
TVector3 GetVector (TObject *obj)
ClassDef (FairMCPointDraw, 1)
virtual TObject * GetValue (TObject *obj, Int_t i)
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Finish ()
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
TClonesArray * fPointList
FairEventManager * fEventManager
TEvePointSet * fq
Color_t fColor
Style_t fStyle
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Detailed Description
Definition at line 25 of file FairMCPointDraw.h.
Constructor & Destructor Documentation
FairMCPointDraw() [1/2]
FairMCPointDraw::FairMCPointDraw ()
Definition at line 23 of file FairMCPointDraw.cxx.
FairMCPointDraw() [2/2]
FairMCPointDraw::FairMCPointDraw (const char * name, Color_t color, Style_t mstyle, Int_t iVerbose = 1) inline
Definition at line 29 of file FairMCPointDraw.h.
~FairMCPointDraw()
FairMCPointDraw::~FairMCPointDraw () virtual
Definition at line 29 of file FairMCPointDraw.cxx.
Member Function Documentation
CheckInputPersistance()
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
ClassDef()
FairMCPointDraw::ClassDef (FairMCPointDraw , 1) protected
Exec()
void FairPointSetDraw::Exec (Option_t * option) virtual inherited
Executed task
Definition at line 80 of file FairPointSetDraw.cxx.
References FairPointSetDraw::fColor, FairPointSetDraw::fPointList, FairPointSetDraw::fq, FairPointSetDraw::fStyle, FairPointSetDraw::GetValue(), FairPointSetDraw::GetVector(), and FairPointSetDraw::Reset().
ExecuteTask()
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
ExecuteTasks()
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
Finish()
void FairPointSetDraw::Finish () protected virtual inherited
Action after each event
Reimplemented from FairTask.
Definition at line 122 of file FairPointSetDraw.cxx.
FinishEvent()
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
FinishEvents()
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
FinishTask()
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
FinishTasks()
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
GetValue()
TObject * FairPointSetDraw::GetValue (TObject * obj, Int_t i) protected virtual inherited
Definition at line 106 of file FairPointSetDraw.cxx.
Referenced by FairPointSetDraw::Exec().
GetVector()
TVector3 FairMCPointDraw::GetVector (TObject * obj) protected virtual
Implements FairPointSetDraw.
Definition at line 34 of file FairMCPointDraw.cxx.
References FairMCPoint::GetX(), FairMCPoint::GetY(), and FairMCPoint::GetZ().
Init()
InitStatus FairPointSetDraw::Init () protected virtual inherited
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 62 of file FairPointSetDraw.cxx.
References FairPointSetDraw::fEventManager, FairPointSetDraw::fPointList, FairPointSetDraw::fq, FairPointSetDraw::fVerbose, FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), and kSUCCESS.
InitTask()
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
InitTasks()
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
IsOutputBranchPersistent()
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
ReInit()
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, PixelAltFindHits, PixelFindHits, PixelDigitize, PixelFitTracks, FairRingSorterTask, PixelFindTracks, PixelAltDigiWriteToRootVector, PixelDigiWriteToBinFile, PixelDigiWriteToFile, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 120 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
ReInitTask()
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
ReInitTasks()
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
Reset()
void FairPointSetDraw::Reset () inherited
Definition at line 126 of file FairPointSetDraw.cxx.
References FairPointSetDraw::fEventManager, and FairPointSetDraw::fq.
Referenced by FairPointSetDraw::Exec().
SetInputPersistance()
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
SetOutputBranchPersistent()
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
SetParContainers()
void FairPointSetDraw::SetParContainers () protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 116 of file FairPointSetDraw.cxx.
SetParTask()
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
SetParTasks()
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
SetStreamProcessing()
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
SetVerbose()
void FairPointSetDraw::SetVerbose (Int_t iVerbose) inline inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 53 of file FairPointSetDraw.h.
References FairPointSetDraw::fVerbose.
Member Data Documentation
fColor
Color_t FairPointSetDraw::fColor protected inherited
Definition at line 70 of file FairPointSetDraw.h.
Referenced by FairPointSetDraw::Exec().
fEventManager
FairEventManager* FairPointSetDraw::fEventManager protected inherited
Definition at line 68 of file FairPointSetDraw.h.
Referenced by FairPointSetDraw::Init(), and FairPointSetDraw::Reset().
fInputPersistance
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
fLogger
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
fPointList
TClonesArray* FairPointSetDraw::fPointList protected inherited
Definition at line 67 of file FairPointSetDraw.h.
Referenced by FairPointSetDraw::Exec(), and FairPointSetDraw::Init().
fq
TEvePointSet* FairPointSetDraw::fq protected inherited
Definition at line 69 of file FairPointSetDraw.h.
Referenced by FairPointSetDraw::Exec(), FairPointSetDraw::Init(), and FairPointSetDraw::Reset().
fStreamProcessing
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
fStyle
Style_t FairPointSetDraw::fStyle protected inherited
Definition at line 71 of file FairPointSetDraw.h.
Referenced by FairPointSetDraw::Exec().
fVerbose
Int_t FairPointSetDraw::fVerbose protected inherited
Definition at line 62 of file FairPointSetDraw.h.
Referenced by FairHitPointSetDraw::GetVector(), FairPointSetDraw::Init(), and FairPointSetDraw::SetVerbose().
The documentation for this class was generated from the following files:
FairMCPointDraw.h
FairMCPointDraw.cxx