FairRroot: PixelFindTracks Class Reference
PixelFindTracks Class Reference
#include <PixelFindTracks.h>
Public Member Functions
PixelFindTracks ()
PixelFindTracks (Int_t iVerbose)
PixelFindTracks (const char *name, Int_t iVerbose)
virtual ~PixelFindTracks ()
virtual void Exec (Option_t *opt)
virtual void GetParList (TList *tempList)
virtual void InitMQ (TList *tempList)
virtual void ExecMQ (TList *inputList, TList *outputList)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Private Member Functions
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
void Reset ()
virtual void Finish ()
PixelFindTracks (const PixelFindTracks &)
PixelFindTracks & operator= (const PixelFindTracks &)
ClassDef (PixelFindTracks, 1)
Private Attributes
PixelDigiPar * fDigiPar
TClonesArray * fHits
TClonesArray * fTracks
Int_t fTNofEvents
Int_t fNHits
Int_t fTNofHits
Int_t fNTracks
Int_t fTNofTracks
TH2F * fhDist2D
Detailed Description
Definition at line 29 of file PixelFindTracks.h.
Constructor & Destructor Documentation
PixelFindTracks::PixelFindTracks ()
Default constructor
Definition at line 45 of file PixelFindTracks.cxx.
PixelFindTracks::PixelFindTracks (Int_t iVerbose)
Standard constructor
Definition at line 54 of file PixelFindTracks.cxx.
PixelFindTracks::PixelFindTracks (const char * name, Int_t iVerbose)
Constructor with name
Definition at line 63 of file PixelFindTracks.cxx.
References Reset().
PixelFindTracks::~PixelFindTracks () virtual
Destructor
Definition at line 82 of file PixelFindTracks.cxx.
References fDigiPar, fTracks, and Reset().
PixelFindTracks::PixelFindTracks (const PixelFindTracks &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
PixelFindTracks::ClassDef (PixelFindTracks , 1) private
void PixelFindTracks::Exec (Option_t * opt) virtual
Execution
Definition at line 93 of file PixelFindTracks.cxx.
References PixelTrack::AddHitIndex(), fhDist2D, fHits, fNHits, fNTracks, fTNofEvents, fTNofHits, fTNofTracks, FairHit::GetDetectorID(), FairHit::GetX(), FairHit::GetY(), FairHit::GetZ(), LOG, and Reset().
Referenced by ExecMQ().
void PixelFindTracks::ExecMQ (TList * inputList, TList * outputList) virtual
Definition at line 196 of file PixelFindTracks.cxx.
References Exec(), fHits, and fTracks.
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), LOG, FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), LOG, FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
void PixelFindTracks::Finish () private virtual
Finish at the end of each event
Reimplemented from FairTask.
Definition at line 250 of file PixelFindTracks.cxx.
References fhDist2D, fTNofEvents, fTNofHits, fTNofTracks, fTracks, and LOG.
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
void PixelFindTracks::GetParList (TList * tempList) virtual
Definition at line 175 of file PixelFindTracks.cxx.
References fDigiPar.
InitStatus PixelFindTracks::Init () private virtual
Intialisation
Reimplemented from FairTask.
Definition at line 208 of file PixelFindTracks.cxx.
References fhDist2D, fHits, fTracks, FairRootManager::GetObject(), FairRootManager::Instance(), kSUCCESS, LOG, and FairRootManager::Register().
void PixelFindTracks::InitMQ (TList * tempList) virtual
Definition at line 184 of file PixelFindTracks.cxx.
References fDigiPar, fhDist2D, fTracks, and LOG.
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, LOG, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
PixelFindTracks& PixelFindTracks::operator= (const PixelFindTracks &) private
InitStatus PixelFindTracks::ReInit () private virtual
Reinitialisation
Reimplemented from FairTask.
Definition at line 233 of file PixelFindTracks.cxx.
References kSUCCESS.
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, LOG, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
void PixelFindTracks::Reset () private
Reset eventwise counters
Definition at line 243 of file PixelFindTracks.cxx.
References fNHits, fNTracks, and fTracks.
Referenced by Exec(), PixelFindTracks(), and ~PixelFindTracks().
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
void PixelFindTracks::SetParContainers () private virtual
Get parameter containers
Reimplemented from FairTask.
Definition at line 159 of file PixelFindTracks.cxx.
References fDigiPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), FairRun::Instance(), and LOG.
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
PixelDigiPar* PixelFindTracks::fDigiPar private
Definition at line 60 of file PixelFindTracks.h.
Referenced by GetParList(), InitMQ(), SetParContainers(), and ~PixelFindTracks().
TH2F* PixelFindTracks::fhDist2D private
Definition at line 73 of file PixelFindTracks.h.
Referenced by Exec(), Finish(), Init(), and InitMQ().
TClonesArray* PixelFindTracks::fHits private
Definition at line 62 of file PixelFindTracks.h.
Referenced by Exec(), ExecMQ(), and Init().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
Int_t PixelFindTracks::fNHits private
Definition at line 67 of file PixelFindTracks.h.
Referenced by Exec(), and Reset().
Int_t PixelFindTracks::fNTracks private
Definition at line 70 of file PixelFindTracks.h.
Referenced by Exec(), and Reset().
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
Int_t PixelFindTracks::fTNofEvents private
Output array of PixelTrack
Definition at line 65 of file PixelFindTracks.h.
Referenced by Exec(), and Finish().
Int_t PixelFindTracks::fTNofHits private
Definition at line 68 of file PixelFindTracks.h.
Referenced by Exec(), and Finish().
Int_t PixelFindTracks::fTNofTracks private
Definition at line 71 of file PixelFindTracks.h.
Referenced by Exec(), and Finish().
TClonesArray* PixelFindTracks::fTracks private
Input array of PixelHit
Definition at line 63 of file PixelFindTracks.h.
Referenced by ExecMQ(), Finish(), Init(), InitMQ(), Reset(), and ~PixelFindTracks().
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
PixelFindTracks.h
PixelFindTracks.cxx