FairRroot: fair::mq::PluginManager Class Reference
fair::mq::PluginManager Class Reference
manages and owns plugin instances
#include <fairmq/PluginManager.h>
Classes
struct BadSearchPath
struct PluginInstantiationError
struct PluginLoadError
struct ProgramOptionsParseError
Public Types
using PluginFactory = std::shared_ptr< fair::mq::Plugin >(PluginServices &)
Public Member Functions
PluginManager ()
auto SetSearchPaths (const std::vector< boost::filesystem::path > &) -> void
auto AppendSearchPath (const boost::filesystem::path &) -> void
auto PrependSearchPath (const boost::filesystem::path &) -> void
auto SearchPaths () const -> const std::vector< boost::filesystem::path > &
auto LoadPlugin (const std::string &pluginName) -> void
auto LoadPlugins (const std::vector< std::string > &pluginNames) -> void
auto InstantiatePlugins () -> void
auto ForEachPlugin (std::function< void(Plugin &)> func) -> void
auto ForEachPluginProgOptions (std::function< void(boost::program_options::options_description)> func) const -> void
template<typename... Args>
auto EmplacePluginServices (Args &&...args) -> void
auto WaitForPluginsToReleaseDeviceControl () -> void
Static Public Member Functions
static auto ProgramOptions () -> boost::program_options::options_description
static auto MakeFromCommandLineOptions (const std::vector< std::string >) -> std::shared_ptr< PluginManager >
static auto LibPrefix () -> const std::string &
Private Member Functions
auto LoadPluginPrelinkedDynamic (const std::string &pluginName) -> void
auto LoadPluginDynamic (const std::string &pluginName) -> void
auto LoadPluginStatic (const std::string &pluginName) -> void
template<typename... Args>
auto LoadSymbols (const std::string &pluginName, Args &&...args) -> void
auto InstantiatePlugin (const std::string &pluginName) -> void
Static Private Member Functions
static auto ValidateSearchPath (const boost::filesystem::path &) -> void
Private Attributes
std::vector< boost::filesystem::path > fSearchPaths
std::map< std::string, std::function< PluginFactory > > fPluginFactories
std::map< std::string, std::shared_ptr< Plugin > > fPlugins
std::vector< std::string > fPluginOrder
std::map< std::string, boost::program_options::options_description > fPluginProgOptions
std::unique_ptr< PluginServices > fPluginServices
Static Private Attributes
static const std::string fgkLibPrefix = "FairMQPlugin_"
Detailed Description
manages and owns plugin instances
The plugin manager is responsible for the whole plugin lifecycle. It facilitates two plugin mechanisms: A prelinked dynamic plugins (shared libraries) B dynamic plugins (shared libraries) C static plugins (builtin)
Definition at line 48 of file PluginManager.h.
Member Typedef Documentation
using fair::mq::PluginManager::PluginFactory = std::shared_ptr<fair::mq::Plugin>(PluginServices&)
Definition at line 51 of file PluginManager.h.
Constructor & Destructor Documentation
fair::mq::PluginManager::PluginManager ()
Definition at line 30 of file PluginManager.cxx.
Member Function Documentation
auto fair::mq::PluginManager::AppendSearchPath (const boost::filesystem::path &) -> void
Definition at line 53 of file PluginManager.cxx.
template<typename... Args> auto fair::mq::PluginManager::EmplacePluginServices (Args &&... args) -> void inline
Definition at line 77 of file PluginManager.h.
References fPluginServices.
auto fair::mq::PluginManager::ForEachPlugin (std::function< void(Plugin &)> func) -> void inline
Definition at line 73 of file PluginManager.h.
References fPluginOrder, and fPlugins.
auto fair::mq::PluginManager::ForEachPluginProgOptions (std::function< void(boost::program_options::options_description)> func) const -> void inline
Definition at line 74 of file PluginManager.h.
References fPluginProgOptions.
auto fair::mq::PluginManager::InstantiatePlugin (const std::string & pluginName) -> void private
Definition at line 213 of file PluginManager.cxx.
References fPluginFactories(), and fPlugins().
Referenced by LoadSymbols().
auto fair::mq::PluginManager::InstantiatePlugins () -> void
Definition at line 221 of file PluginManager.cxx.
References fPluginOrder(), and fair::mq::tools::ToString().
static auto fair::mq::PluginManager::LibPrefix () -> const std::string& inline static
Definition at line 71 of file PluginManager.h.
References fgkLibPrefix.
auto fair::mq::PluginManager::LoadPlugin (const std::string & pluginName) -> void
Definition at line 123 of file PluginManager.cxx.
Referenced by LoadPlugins().
auto fair::mq::PluginManager::LoadPluginDynamic (const std::string & pluginName) -> void private
Definition at line 164 of file PluginManager.cxx.
References fPluginFactories(), fPluginOrder(), and fair::mq::tools::ToString().
auto fair::mq::PluginManager::LoadPluginPrelinkedDynamic (const std::string & pluginName) -> void private
Definition at line 147 of file PluginManager.cxx.
References fPluginFactories(), fPluginOrder(), and fair::mq::tools::ToString().
auto fair::mq::PluginManager::LoadPlugins (const std::vector< std::string > & pluginNames) -> void inline
Definition at line 62 of file PluginManager.h.
References LoadPlugin().
auto fair::mq::PluginManager::LoadPluginStatic (const std::string & pluginName) -> void private
Definition at line 196 of file PluginManager.cxx.
References fPluginFactories(), fPluginOrder(), and fair::mq::tools::ToString().
template<typename... Args> auto fair::mq::PluginManager::LoadSymbols (const std::string & pluginName, Args &&... args) -> void inline private
Definition at line 88 of file PluginManager.h.
References fPluginFactories, fPluginProgOptions, InstantiatePlugin(), and fair::mq::tools::ToString().
auto fair::mq::PluginManager::MakeFromCommandLineOptions (const std::vector< std::string >) -> std::shared_ptr<PluginManager> static
Definition at line 83 of file PluginManager.cxx.
References fair::error, and fair::mq::tools::ToString().
auto fair::mq::PluginManager::PrependSearchPath (const boost::filesystem::path &) -> void
Definition at line 59 of file PluginManager.cxx.
auto fair::mq::PluginManager::ProgramOptions () -> boost::program_options::options_description static
Definition at line 65 of file PluginManager.cxx.
auto fair::mq::PluginManager::SearchPaths () const -> const std::vector<boost::filesystem::path>& inline
Definition at line 58 of file PluginManager.h.
References fSearchPaths.
auto fair::mq::PluginManager::SetSearchPaths (const std::vector< boost::filesystem::path > &) -> void
Definition at line 47 of file PluginManager.cxx.
auto fair::mq::PluginManager::ValidateSearchPath (const boost::filesystem::path &) -> void static private
Definition at line 40 of file PluginManager.cxx.
References fair::mq::tools::ToString().
auto fair::mq::PluginManager::WaitForPluginsToReleaseDeviceControl () -> void inline
Definition at line 79 of file PluginManager.h.
References fPluginServices.
Member Data Documentation
const std::string fair::mq::PluginManager::fgkLibPrefix = "FairMQPlugin_" static private
Definition at line 112 of file PluginManager.h.
Referenced by LibPrefix().
std::map<std::string, std::function<PluginFactory> > fair::mq::PluginManager::fPluginFactories private
Definition at line 114 of file PluginManager.h.
Referenced by LoadSymbols().
std::vector<std::string> fair::mq::PluginManager::fPluginOrder private
Definition at line 116 of file PluginManager.h.
Referenced by ForEachPlugin().
std::map<std::string, boost::program_options::options_description> fair::mq::PluginManager::fPluginProgOptions private
Definition at line 117 of file PluginManager.h.
Referenced by ForEachPluginProgOptions(), and LoadSymbols().
std::map<std::string, std::shared_ptr<Plugin> > fair::mq::PluginManager::fPlugins private
Definition at line 115 of file PluginManager.h.
Referenced by ForEachPlugin().
std::unique_ptr<PluginServices> fair::mq::PluginManager::fPluginServices private
Definition at line 118 of file PluginManager.h.
Referenced by EmplacePluginServices(), and WaitForPluginsToReleaseDeviceControl().
std::vector<boost::filesystem::path> fair::mq::PluginManager::fSearchPaths private
Definition at line 113 of file PluginManager.h.
Referenced by SearchPaths().
The documentation for this class was generated from the following files:
PluginManager.h
PluginManager.cxx