FairRoot: FairEventHeader Class Reference
FairEventHeader Class Reference
#include <FairEventHeader.h>
Public Member Functions
FairEventHeader ()
UInt_t GetRunId ()
Double_t GetEventTime ()
Int_t GetInputFileId ()
Int_t GetMCEntryNumber ()
void SetRunId (UInt_t runid)
void SetEventTime (Double_t time)
void SetInputFileId (Int_t id)
void SetMCEntryNumber (Int_t id)
virtual ~FairEventHeader ()
virtual void Register (Bool_t Persistance=kTRUE)
Protected Attributes
UInt_t fRunId
Double_t fEventTime
Int_t fInputFileId
Int_t fMCEntryNo
Detailed Description
Event Header Class
Author
D.Bertini d.ber.nosp@m.tini.nosp@m.@gsi..nosp@m.de
M.Al-Turany m.al-.nosp@m.tura.nosp@m.ny@gs.nosp@m.i.de
Definition at line 25 of file FairEventHeader.h.
Constructor & Destructor Documentation
FairEventHeader()
FairEventHeader::FairEventHeader ()
Default constructor
Definition at line 18 of file FairEventHeader.cxx.
~FairEventHeader()
FairEventHeader::~FairEventHeader () virtual
Destructor
Definition at line 27 of file FairEventHeader.cxx.
Member Function Documentation
GetEventTime()
Double_t FairEventHeader::GetEventTime () inline
Get the MC time for this event
Definition at line 37 of file FairEventHeader.h.
References fEventTime.
Referenced by FairMixedSource::FillEventHeader(), FairFileSource::GetEventTime(), FairMixedSource::GetEventTime(), FairRootManager::ReadBranchEvent(), FairRootManager::ReadEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
GetInputFileId()
Int_t FairEventHeader::GetInputFileId () inline
Get the MC input file Id for this event
Definition at line 40 of file FairEventHeader.h.
References fInputFileId.
Referenced by FairMixedSource::FillEventHeader(), and FairMixedSource::ReadBranchEvent().
GetMCEntryNumber()
Int_t FairEventHeader::GetMCEntryNumber () inline
The entry number in the original MC chain
Definition at line 43 of file FairEventHeader.h.
References fMCEntryNo.
Referenced by FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), FairMQPixelMerger::MergeData(), FairFileSource::ReadBranchEvent(), and FairMixedSource::ReadBranchEvent().
GetRunId()
UInt_t FairEventHeader::GetRunId () inline
Get the run ID for this run
Definition at line 34 of file FairEventHeader.h.
References fRunId.
Referenced by FairRunOnline::EventLoop(), FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), FairRootManager::GetRunId(), FairRunAnaProof::Init(), FairMixedSource::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairMQPixelMerger::MergeData(), FairRunAna::Run(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
Register()
void FairEventHeader::Register (Bool_t Persistance = kTRUE) virtual
Definition at line 30 of file FairEventHeader.cxx.
References FairRootManager::Instance(), and FairRootManager::Register().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunAnaProof::InitContainers(), and FairRunOnline::InitContainers().
SetEventTime()
void FairEventHeader::SetEventTime (Double_t time) inline
Set the MC time for this event
Parameters
time : time in ns
Definition at line 53 of file FairEventHeader.h.
References fEventTime.
Referenced by FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), and FairMixedSource::ReadEvent().
SetInputFileId()
void FairEventHeader::SetInputFileId (Int_t id) inline
Set the Signal file Id for this event
Definition at line 56 of file FairEventHeader.h.
References fInputFileId.
Referenced by FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), and FairMixedSource::ReadEvent().
SetMCEntryNumber()
void FairEventHeader::SetMCEntryNumber (Int_t id) inline
The entry number in the original MC chain
Definition at line 59 of file FairEventHeader.h.
References fMCEntryNo.
Referenced by FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), PixelDigiBinSource::ReadEvent(), PixelDigiSource::ReadEvent(), and FairMixedSource::ReadEvent().
SetRunId()
void FairEventHeader::SetRunId (UInt_t runid) inline
Set the run ID for this run
Parameters
runid : unique run id
Definition at line 48 of file FairEventHeader.h.
References fRunId.
Referenced by FairSource::FillEventHeader(), FairFileSource::FillEventHeader(), FairMixedSource::FillEventHeader(), FairRunAnaProof::Init(), FairRunAna::Init(), FairMixedSource::Init(), FairRunOnline::Init(), PixelDigiSource::ReadEvent(), and PixelDigiBinSource::ReadEvent().
Member Data Documentation
fEventTime
Double_t FairEventHeader::fEventTime protected
Event Time
Definition at line 71 of file FairEventHeader.h.
Referenced by GetEventTime(), and SetEventTime().
fInputFileId
Int_t FairEventHeader::fInputFileId protected
Input file identifier, the file description is in the File header
Definition at line 73 of file FairEventHeader.h.
Referenced by GetInputFileId(), and SetInputFileId().
fMCEntryNo
Int_t FairEventHeader::fMCEntryNo protected
MC entry number from input chain
Definition at line 75 of file FairEventHeader.h.
Referenced by GetMCEntryNumber(), and SetMCEntryNumber().
fRunId
UInt_t FairEventHeader::fRunId protected
Run Id
Definition at line 69 of file FairEventHeader.h.
Referenced by GetRunId(), and SetRunId().
The documentation for this class was generated from the following files:
FairEventHeader.h
FairEventHeader.cxx