FairRoot: FairRun Class Reference
FairRun Class Reference abstract
#include <FairRun.h>
Public Member Functions
FairRun (Bool_t isMaster=kTRUE)
virtual ~FairRun ()
virtual void AddTask (FairTask *t)
virtual void StoreTaskNames (const FairTask *t)
virtual void SetTask (FairTask *t)
virtual void Init ()=0
virtual FairField * GetField ()=0
virtual void Run (Int_t NStart=0, Int_t NStop=0)=0
void SetEventHeader (FairEventHeader *EvHeader)
FairRuntimeDb * GetRuntimeDb (void)
void SetSink (FairSink *tempSink)
FairSink * GetSink ()
Int_t GetRunId ()
void SetRunId (UInt_t runId)
FairEventHeader * GetEventHeader ()
Bool_t IsAna ()
FairTask * GetTask (const char *taskName)
FairTask * GetMainTask ()
Int_t GetNTasks ()
void CreateGeometryFile (const char *geofile)
void SetWriteRunInfoFile (Bool_t write)
void SetGenerateRunInfo (Bool_t write)
Bool_t GetWriteRunInfoFile ()
Bool_t IsRunInfoGenerated ()
void SetUseFairLinks (Bool_t val)
Bool_t GetIsMaster () const
void MarkFill (Bool_t flag)
TString GetOptions ()
void SetOptions (const TString &s)
virtual void SetOutputFile (const char *fname)
virtual void SetOutputFile (TFile *f)
void SetOutputFileName (const TString &name)
TFile * GetOutputFile ()
void SetUserOutputFileName (const TString &name)
TString GetUserOutputFileName () const
Static Public Member Functions
static FairRun * Instance ()
Protected Attributes
FairRuntimeDb * fRtdb
FairTask * fTask
FairRootManager * fRootManager
FairSink * fSink
TString fUserOutputFileName
TString fOptions
UInt_t fRunId
Bool_t fAna
FairEventHeader * fEvtHeader
FairFileHeader * fFileHeader
Bool_t fGenerateRunInfo
Bool_t fIsMaster
Bool_t fMarkFill
Static Protected Attributes
static TMCThreadLocal FairRun * fRunInstance = 0
Private Member Functions
FairRun (const FairRun &M)
FairRun & operator= (const FairRun &)
Private Attributes
Int_t fNTasks
Detailed Description
Configure the Simuation or Analysis
Author
M. Al-Turany D. Bertini
Version
0.1
Since
12.01.04
Definition at line 33 of file FairRun.h.
Constructor & Destructor Documentation
FairRun() [1/2]
FairRun::FairRun (Bool_t isMaster = kTRUE)
default ctor
Definition at line 40 of file FairRun.cxx.
References fRootManager, fRunInstance, and FairRootManager::Instance().
~FairRun()
FairRun::~FairRun () virtual
default dtor
Definition at line 67 of file FairRun.cxx.
References fEvtHeader, fRtdb, and fTask.
FairRun() [2/2]
FairRun::FairRun (const FairRun & M) private
Member Function Documentation
AddTask()
void FairRun::AddTask (FairTask * t) virtual
Add a FAIRTask to the simulation or analysis
Definition at line 79 of file FairRun.cxx.
References fTask, and StoreTaskNames().
Referenced by FairEventManager::AddTask(), create_digis(), create_digis_mixed(), FairMQSimDevice::InitTask(), FairMQSampler< Task >::InitTask(), run_dAsciiSource(), run_dBinSource(), run_digi(), run_digi_timebased(), run_digiToAscii(), run_digiToBin(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_hits(), run_hits_sep(), run_reco(), run_reco_timebased(), run_tracks(), and unpack_mbs().
CreateGeometryFile()
void FairRun::CreateGeometryFile (const char * geofile)
Create a new file and save the TGeoManager to it
Definition at line 112 of file FairRun.cxx.
References FairRootManager::CreateGeometryFile(), and fRootManager.
Referenced by run_rad(), run_rutherford(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), and run_tutorial4().
GetEventHeader()
FairEventHeader * FairRun::GetEventHeader ()
Get the detector specific run header
Definition at line 124 of file FairRun.cxx.
References fEvtHeader.
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), and FairRunOnline::InitContainers().
GetField()
virtual FairField* FairRun::GetField () pure virtual
Implemented in FairRunAna, FairRunSim, and FairRunOnline.
GetIsMaster()
Bool_t FairRun::GetIsMaster () const inline
Definition at line 153 of file FairRun.h.
References fIsMaster.
GetMainTask()
FairTask* FairRun::GetMainTask () inline
Get Main Task
Definition at line 124 of file FairRun.h.
References fTask.
GetNTasks()
Int_t FairRun::GetNTasks () inline
Return the number of Tasks added to this Run
Definition at line 130 of file FairRun.h.
References fNTasks.
GetOptions()
TString FairRun::GetOptions () inline
Definition at line 159 of file FairRun.h.
References fOptions.
GetOutputFile()
TFile * FairRun::GetOutputFile ()
Definition at line 184 of file FairRun.cxx.
References FairRootFileSink::GetRootFile(), GetSink(), kFILESINK, and WARNING.
Referenced by plots().
GetRunId()
Int_t FairRun::GetRunId () inline
return the run ID for the actul run
Definition at line 96 of file FairRun.h.
References fRunId.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), Pixel::ConstructGeometry(), NewDetector::ConstructGeometry(), create_digis(), create_digis_mixed(), FairConstField::FillParContainer(), FairMCApplication::InitGeometry(), read_digis(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairTutorialDet4::SetSensitiveVolumes(), and FairMQSimDevice::UpdateParameterServer().
GetRuntimeDb()
FairRuntimeDb* FairRun::GetRuntimeDb (void) inline
return a pointer to the RuntimeDB
Definition at line 76 of file FairRun.h.
References fRtdb.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), create_digis(), create_digis_mixed(), eventDisplay(), FairConstField::FillParContainer(), FairRunAnaProof::Init(), FairRunAna::Init(), FairAnaSelector::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), NewDetector::Initialize(), FairTestDetector::Initialize(), FairTutorialDet4::Initialize(), FairMQSimDevice::InitTask(), FairMQSampler< Task >::InitTask(), plots(), FairModule::ProcessNodes(), read_digis(), FairTutorialDet2Digitizer::ReInit(), FairTutorialDet4HitProducerIdealMisalign::ReInit(), run_bg(), run_dAsciiSource(), run_dBinSource(), run_digi(), run_digi_timebased(), run_digiToAscii(), run_digiToBin(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_hits(), run_hits_sep(), run_rad(), run_reco(), run_reco_timebased(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tracks(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), run_tutorial2(), run_tutorial4(), FairTutorialDet2Digitizer::SetParContainers(), FairTutorialDet4PointDraw::SetParContainers(), FairTutorialDet4HitProducerIdealMisalign::SetParContainers(), FairTutorialDet4::SetParContainers(), PixelFindTracks::SetParContainers(), PixelDigitize::SetParContainers(), PixelFitTracks::SetParContainers(), PixelFindHits::SetParContainers(), PixelAltFindHits::SetParContainers(), FairEventBuilderManager::SetParContainers(), MyFieldCreator::SetParm(), FairMCApplication::SetParTask(), FairTutorialDet2::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairTutorialDet4::SetSensitiveVolumes(), unpack_mbs(), and FairMQSimDevice::UpdateParameterServer().
GetSink()
FairSink* FairRun::GetSink () inline
return a pointer to the sink
Definition at line 90 of file FairRun.h.
References fSink.
Referenced by GetOutputFile().
GetTask()
FairTask * FairRun::GetTask (const char * taskName)
Get task by name
Definition at line 117 of file FairRun.cxx.
References fTask.
GetUserOutputFileName()
TString FairRun::GetUserOutputFileName () const
Definition at line 201 of file FairRun.cxx.
References fUserOutputFileName.
Referenced by FairMCApplication::CloneForWorker(), and FairMCApplication::InitOnWorker().
GetWriteRunInfoFile()
Bool_t FairRun::GetWriteRunInfoFile ()
Definition at line 146 of file FairRun.cxx.
References fGenerateRunInfo.
Init()
virtual void FairRun::Init () pure virtual
Initialize the Simulation or analysis
Implemented in FairRunSim, FairRunAna, FairRunOnline, and FairRunAnaProof.
Instance()
FairRun * FairRun::Instance () static
static instance
Definition at line 35 of file FairRun.cxx.
References fRunInstance.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairLinkManager::FairLinkManager(), FairConstField::FillParContainer(), FairRootManager::GetFolderName(), NewDetector::Initialize(), FairTestDetector::Initialize(), FairTutorialDet4::Initialize(), FairMCApplication::InitTasks(), FairModule::ProcessNodes(), FairTutorialDet4PointDraw::SetParContainers(), FairTutorialDet4::SetParContainers(), PixelFindTracks::SetParContainers(), PixelFitTracks::SetParContainers(), PixelDigitize::SetParContainers(), PixelFindHits::SetParContainers(), PixelAltFindHits::SetParContainers(), FairMCApplication::SetParTask(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), and FairTutorialDet4::SetSensitiveVolumes().
IsAna()
Bool_t FairRun::IsAna () inline
return true for Anaylsis session
Definition at line 113 of file FairRun.h.
References fAna.
Referenced by FairRootManager::GetFolderName().
IsRunInfoGenerated()
Bool_t FairRun::IsRunInfoGenerated () inline
Definition at line 147 of file FairRun.h.
References fGenerateRunInfo.
MarkFill()
void FairRun::MarkFill (Bool_t flag) inline
Definition at line 156 of file FairRun.h.
References fMarkFill.
operator=()
FairRun& FairRun::operator= (const FairRun &) inline private
Definition at line 189 of file FairRun.h.
Run()
virtual void FairRun::Run (Int_t NStart = 0, Int_t NStop = 0) pure virtual
run the analysis or simulation
Implemented in FairRunSim, FairRunAnaProof, FairRunAna, and FairRunOnline.
SetEventHeader()
void FairRun::SetEventHeader (FairEventHeader * EvHeader) inline
Set the experiment dependent run header for each run
Definition at line 70 of file FairRun.h.
References fEvtHeader.
Referenced by run_dAsciiSource(), and run_dBinSource().
SetGenerateRunInfo()
void FairRun::SetGenerateRunInfo (Bool_t write) inline
Definition at line 141 of file FairRun.h.
References fGenerateRunInfo.
Referenced by run_digi(), run_reco(), and run_sim().
SetOptions()
void FairRun::SetOptions (const TString & s) inline
Definition at line 162 of file FairRun.h.
References fOptions.
SetOutputFile() [1/2]
void FairRun::SetOutputFile (const char * fname) virtual
Set the output file name for analysis or simulation
Definition at line 155 of file FairRun.cxx.
References fRootManager, fSink, fUserOutputFileName, FairRootManager::SetSink(), and WARNING.
Referenced by run_sim().
SetOutputFile() [2/2]
void FairRun::SetOutputFile (TFile * f) virtual
Set the output file for analysis or simulation
Definition at line 165 of file FairRun.cxx.
References fRootManager, fSink, fUserOutputFileName, FairRootManager::SetSink(), and WARNING.
SetOutputFileName()
void FairRun::SetOutputFileName (const TString & name)
Set the output file name without creating the file
Definition at line 175 of file FairRun.cxx.
References fRootManager, fSink, fUserOutputFileName, FairRootManager::SetSink(), and WARNING.
SetRunId()
void FairRun::SetRunId (UInt_t runId) inline
Set the Run ID
Definition at line 103 of file FairRun.h.
References fRunId.
Referenced by FairMQSimDevice::InitTask().
SetSink()
void FairRun::SetSink (FairSink * tempSink) inline
Set the sink
Definition at line 82 of file FairRun.h.
References fRootManager, fSink, fUserOutputFileName, FairSink::GetFileName(), and FairRootManager::SetSink().
Referenced by create_digis(), create_digis_mixed(), eventDisplay(), FairAnaSelector::Init(), FairMCApplication::InitOnWorker(), FairMQSimDevice::InitTask(), FairMQSampler< Task >::InitTask(), plots(), read_digis(), run_bg(), run_dAsciiSource(), run_dBinSource(), run_digi(), run_digi_timebased(), run_digiToAscii(), run_digiToBin(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_hits(), run_hits_sep(), run_rad(), run_reco(), run_reco_timebased(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tracks(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), run_tutorial2(), run_tutorial4(), and unpack_mbs().
SetTask()
void FairRun::SetTask (FairTask * t) virtual
Definition at line 100 of file FairRun.cxx.
References fFileHeader, fNTasks, fTask, FairFileHeader::GetListOfTasks(), and StoreTaskNames().
Referenced by FairAnaSelector::Init().
SetUseFairLinks()
void FairRun::SetUseFairLinks (Bool_t val)
Definition at line 132 of file FairRun.cxx.
References fRootManager, and FairRootManager::SetUseFairLinks().
Referenced by run_digi(), run_digi_timebased(), run_reco(), run_reco_timebased(), and run_sim().
SetUserOutputFileName()
void FairRun::SetUserOutputFileName (const TString & name)
New functions which allow to postpone creating a new Sink in MT to be kept after clean-up of deprecated functions above
Definition at line 195 of file FairRun.cxx.
References fUserOutputFileName.
Referenced by FairMCApplication::CloneForWorker().
SetWriteRunInfoFile()
void FairRun::SetWriteRunInfoFile (Bool_t write)
Definition at line 138 of file FairRun.cxx.
References fGenerateRunInfo.
Referenced by run_rutherford().
StoreTaskNames()
void FairRun::StoreTaskNames (const FairTask * t) virtual
Definition at line 85 of file FairRun.cxx.
References FairFileHeader::AddTaskClassName(), fFileHeader, and fNTasks.
Referenced by AddTask(), and SetTask().
Member Data Documentation
fAna
Bool_t FairRun::fAna protected
true for Anaylsis session
Definition at line 213 of file FairRun.h.
Referenced by FairRunAna::FairRunAna(), FairRunAnaProof::FairRunAnaProof(), FairRunOnline::FairRunOnline(), and IsAna().
fEvtHeader
FairEventHeader* FairRun::fEvtHeader protected
MC Event Header
Definition at line 215 of file FairRun.h.
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), GetEventHeader(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), SetEventHeader(), and ~FairRun().
fFileHeader
FairFileHeader* FairRun::fFileHeader protected
File Header
Definition at line 217 of file FairRun.h.
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), SetTask(), and StoreTaskNames().
fGenerateRunInfo
Bool_t FairRun::fGenerateRunInfo protected
true if RunInfo file should be written
Definition at line 219 of file FairRun.h.
Referenced by GetWriteRunInfoFile(), IsRunInfoGenerated(), FairRunAna::Run(), FairRunAna::RunEventReco(), SetGenerateRunInfo(), and SetWriteRunInfoFile().
fIsMaster
Bool_t FairRun::fIsMaster protected
true if on master
Definition at line 221 of file FairRun.h.
Referenced by GetIsMaster().
fMarkFill
Bool_t FairRun::fMarkFill protected
Definition at line 223 of file FairRun.h.
Referenced by FairRunOnline::Fill(), FairRunAna::Fill(), and MarkFill().
fNTasks
Int_t FairRun::fNTasks private
Number of Tasks added
Definition at line 193 of file FairRun.h.
Referenced by GetNTasks(), SetTask(), and StoreTaskNames().
fOptions
TString FairRun::fOptions protected
Options for derived classes, to be set & parsed by user
Definition at line 209 of file FairRun.h.
Referenced by GetOptions(), and SetOptions().
fRootManager
FairRootManager* FairRun::fRootManager protected
IO manager
Definition at line 203 of file FairRun.h.
Referenced by CreateGeometryFile(), FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairRun(), FairRunOnline::FairRunOnline(), FairRunOnline::Fill(), FairRunAna::Fill(), FairRunOnline::Finish(), FairRunOnline::GetSource(), FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairRunSim::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairRunAna::Run(), FairRunOnline::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), FairRunAna::RunWithTimeStamps(), SetOutputFile(), SetOutputFileName(), SetSink(), FairRunOnline::SetSource(), FairRunAna::SetSource(), FairRunAnaProof::SetSource(), SetUseFairLinks(), and FairRunAna::TerminateRun().
fRtdb
FairRuntimeDb* FairRun::fRtdb protected
RuntimeDb
Definition at line 199 of file FairRun.h.
Referenced by GetRuntimeDb(), FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairRunSim::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairRunOnline::Reinit(), FairRunAna::Reinit(), FairRunAnaProof::RunOnProof(), and ~FairRun().
fRunId
UInt_t FairRun::fRunId protected
Run Id
Definition at line 211 of file FairRun.h.
Referenced by FairRunOnline::EventLoop(), FairRunOnline::getRunId(), GetRunId(), FairRunAna::getRunId(), FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairRunSim::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), and SetRunId().
fRunInstance
TMCThreadLocal FairRun * FairRun::fRunInstance = 0 static protected
static pointer to this run
Definition at line 197 of file FairRun.h.
Referenced by FairRun(), and Instance().
fSink
FairSink* FairRun::fSink protected
Output sink
Definition at line 205 of file FairRun.h.
Referenced by GetSink(), SetOutputFile(), SetOutputFileName(), and SetSink().
fTask
FairTask* FairRun::fTask protected
Tasks used
Definition at line 201 of file FairRun.h.
Referenced by AddTask(), FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairRunOnline::Finish(), GetMainTask(), GetTask(), FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairRunSim::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAnaProof::RunOnProof(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), SetTask(), FairRunAna::TerminateRun(), and ~FairRun().
fUserOutputFileName
TString FairRun::fUserOutputFileName protected
Output file name set by user
Definition at line 207 of file FairRun.h.
Referenced by GetUserOutputFileName(), SetOutputFile(), SetOutputFileName(), SetSink(), and SetUserOutputFileName().
The documentation for this class was generated from the following files:
FairRun.h
FairRun.cxx