FairRoot: FairMbsSource Class Reference
FairMbsSource Class Reference abstract
#include <FairMbsSource.h>
Public Member Functions
FairMbsSource ()
FairMbsSource (const FairMbsSource &source)
virtual ~FairMbsSource ()
virtual Bool_t Init ()=0
virtual Int_t ReadEvent (UInt_t=0)=0
virtual void Close ()=0
void AddUnpacker (FairUnpack *unpacker)
const TObjArray * GetUnpackers () const
virtual void SetParUnpackers ()
virtual Bool_t InitUnpackers ()
virtual Bool_t ReInitUnpackers ()
void Reset ()
virtual Source_Type GetSourceType ()
virtual Bool_t ActivateObject (TObject **, const char *)
virtual Bool_t ActivateObjectAny (void **, const std::type_info &, const char *)
virtual Int_t CheckMaxEventNo (Int_t=0)
virtual void ReadBranchEvent (const char *)
virtual void ReadBranchEvent (const char *, Int_t)
virtual void FillEventHeader (FairEventHeader *feh)
void SetRunId (Int_t runId)
Int_t GetRunId () const
Protected Member Functions
Bool_t Unpack (Int_t *data, Int_t size, Short_t type, Short_t subType, Short_t procId, Short_t subCrate, Short_t control)
Protected Attributes
TObjArray * fUnpackers
Int_t fRunId
Detailed Description
Definition at line 25 of file FairMbsSource.h.
Constructor & Destructor Documentation
FairMbsSource() [1/2]
FairMbsSource::FairMbsSource ()
Definition at line 21 of file FairMbsSource.cxx.
FairMbsSource() [2/2]
FairMbsSource::FairMbsSource (const FairMbsSource & source)
Definition at line 23 of file FairMbsSource.cxx.
~FairMbsSource()
FairMbsSource::~FairMbsSource () virtual
Definition at line 26 of file FairMbsSource.cxx.
Member Function Documentation
ActivateObject()
virtual Bool_t FairSource::ActivateObject (TObject ** , const char *) inline virtual inherited
Reimplemented in FairFileSource, FairMixedSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 39 of file FairSource.h.
Referenced by FairRootManager::ActivateBranch(), FairMQPixelSampler::InitTask(), and FairRootManager::UpdateBranches().
ActivateObjectAny()
virtual Bool_t FairSource::ActivateObjectAny (void ** , const std::type_info & , const char *) inline virtual inherited
Reimplemented in FairFileSource.
Definition at line 40 of file FairSource.h.
Referenced by FairRootManager::InitObjectAs().
AddUnpacker()
void FairOnlineSource::AddUnpacker (FairUnpack * unpacker) inline inherited
Definition at line 32 of file FairOnlineSource.h.
References FairOnlineSource::fUnpackers.
Referenced by unpack_mbs().
CheckMaxEventNo()
virtual Int_t FairSource::CheckMaxEventNo (Int_t = 0) inline virtual inherited
Check the maximum event number we can run to
Reimplemented in FairMixedSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 51 of file FairSource.h.
Referenced by FairRootManager::CheckMaxEventNo(), and FairMQPixelSampler::InitTask().
Close()
virtual void FairMbsSource::Close () pure virtual
Implements FairOnlineSource.
Implemented in FairLmdSource, FairMbsStreamSource, and FairRemoteSource.
FillEventHeader()
void FairSource::FillEventHeader (FairEventHeader * feh) virtual inherited
Reimplemented in FairMixedSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 39 of file FairSource.cxx.
References FairSource::fRunId, and FairEventHeader::SetRunId().
Referenced by FairRootManager::FillEventHeader(), FairRootManager::GetRunId(), FairRootManager::ReadBranchEvent(), FairRootManager::ReadEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
GetRunId()
Int_t FairSource::GetRunId () const inline inherited
Definition at line 58 of file FairSource.h.
References FairSource::fRunId.
GetSourceType()
virtual Source_Type FairOnlineSource::GetSourceType () inline virtual inherited
Implements FairSource.
Definition at line 47 of file FairOnlineSource.h.
References kONLINE.
GetUnpackers()
const TObjArray* FairOnlineSource::GetUnpackers () const inline inherited
Definition at line 33 of file FairOnlineSource.h.
References FairOnlineSource::fUnpackers.
Init()
virtual Bool_t FairMbsSource::Init () pure virtual
Implements FairOnlineSource.
Implemented in FairLmdSource, FairMbsStreamSource, and FairRemoteSource.
InitUnpackers()
Bool_t FairOnlineSource::InitUnpackers () virtual inherited
Implements FairSource.
Definition at line 31 of file FairOnlineSource.cxx.
References FairOnlineSource::fUnpackers, and FairOnlineSource::Init().
ReadBranchEvent() [1/2]
virtual void FairSource::ReadBranchEvent (const char *) inline virtual inherited
Read the tree entry on one branch
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 53 of file FairSource.h.
Referenced by FairRootManager::ReadBranchEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
ReadBranchEvent() [2/2]
virtual void FairSource::ReadBranchEvent (const char * , Int_t) inline virtual inherited
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 54 of file FairSource.h.
ReadEvent()
virtual Int_t FairMbsSource::ReadEvent (UInt_t = 0) pure virtual
Implements FairOnlineSource.
Implemented in FairLmdSource, FairMbsStreamSource, and FairRemoteSource.
ReInitUnpackers()
Bool_t FairOnlineSource::ReInitUnpackers () virtual inherited
Implements FairSource.
Definition at line 40 of file FairOnlineSource.cxx.
References FairOnlineSource::fUnpackers.
Reset()
void FairOnlineSource::Reset () virtual inherited
Implements FairSource.
Definition at line 55 of file FairOnlineSource.cxx.
References FairOnlineSource::fUnpackers.
SetParUnpackers()
void FairOnlineSource::SetParUnpackers () virtual inherited
Implements FairSource.
Definition at line 49 of file FairOnlineSource.cxx.
References FairOnlineSource::fUnpackers.
SetRunId()
void FairSource::SetRunId (Int_t runId) inline inherited
Definition at line 57 of file FairSource.h.
References FairSource::fRunId.
Referenced by FairRunOnline::Init().
Unpack()
Bool_t FairMbsSource::Unpack (Int_t * data, Int_t size, Short_t type, Short_t subType, Short_t procId, Short_t subCrate, Short_t control) protected
Definition at line 29 of file FairMbsSource.cxx.
References FairUnpack::DoUnpack(), FairOnlineSource::fUnpackers, FairUnpack::GetControl(), FairUnpack::GetProcId(), FairUnpack::GetSubCrate(), FairUnpack::GetSubType(), and FairUnpack::GetType().
Referenced by FairLmdSource::Close(), FairLmdSource::OpenNextFile(), FairRemoteSource::ReadEvent(), FairMbsStreamSource::ReadEvent(), and FairLmdSource::ReadEvent().
Member Data Documentation
fRunId
Int_t FairSource::fRunId protected inherited
Definition at line 61 of file FairSource.h.
Referenced by FairSource::FillEventHeader(), FairSource::GetRunId(), and FairSource::SetRunId().
fUnpackers
TObjArray* FairOnlineSource::fUnpackers protected inherited
Definition at line 50 of file FairOnlineSource.h.
Referenced by FairOnlineSource::AddUnpacker(), FairOnlineSource::GetUnpackers(), FairOnlineSource::InitUnpackers(), FairOnlineSource::ReInitUnpackers(), FairOnlineSource::Reset(), FairOnlineSource::SetParUnpackers(), Unpack(), and FairOnlineSource::~FairOnlineSource().
The documentation for this class was generated from the following files:
FairMbsSource.h
FairMbsSource.cxx