FairRoot: Ex1Processor Class Reference
Ex1Processor Class Reference
#include <Ex1Processor.h>
Public Member Functions
Ex1Processor ()
Ex1Processor (const Ex1Processor &)
Ex1Processor & operator= (const Ex1Processor &)
virtual ~Ex1Processor ()
Protected Member Functions
virtual void Init ()
virtual void Run ()
void Exec (TClonesArray *digis, TClonesArray *hits)
Private Attributes
TClonesArray * fInput
TClonesArray * fOutput
int fNumMsgs
Detailed Description
Definition at line 12 of file Ex1Processor.h.
Constructor & Destructor Documentation
Ex1Processor() [1/2]
Ex1Processor::Ex1Processor () inline
Definition at line 15 of file Ex1Processor.h.
Ex1Processor() [2/2]
Ex1Processor::Ex1Processor (const Ex1Processor &)
~Ex1Processor()
virtual Ex1Processor::~Ex1Processor () inline virtual
Definition at line 24 of file Ex1Processor.h.
Member Function Documentation
Exec()
void Ex1Processor::Exec (TClonesArray * digis, TClonesArray * hits) inline protected
Definition at line 63 of file Ex1Processor.h.
References FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), MyDigi::GetX(), MyDigi::GetY(), MyDigi::GetZ(), FairTimeStamp::SetTimeStamp(), FairTimeStamp::SetTimeStampError(), and MyDigi::SetXYZ().
Referenced by Run().
Init()
virtual void Ex1Processor::Init () inline protected virtual
Definition at line 27 of file Ex1Processor.h.
References fNumMsgs, and fOutput.
operator=()
Ex1Processor& Ex1Processor::operator= (const Ex1Processor &)
Run()
virtual void Ex1Processor::Run () inline protected virtual
Definition at line 33 of file Ex1Processor.h.
References Exec(), fInput, fNumMsgs, and fOutput.
Member Data Documentation
fInput
TClonesArray* Ex1Processor::fInput private
Definition at line 84 of file Ex1Processor.h.
Referenced by Run().
fNumMsgs
int Ex1Processor::fNumMsgs private
Definition at line 86 of file Ex1Processor.h.
Referenced by Init(), and Run().
fOutput
TClonesArray* Ex1Processor::fOutput private
Definition at line 85 of file Ex1Processor.h.
Referenced by Init(), and Run().
The documentation for this class was generated from the following file:
Ex1Processor.h