FairRoot: PixelContFact Class Reference
PixelContFact Class Reference
#include <PixelContFact.h>
Public Member Functions
PixelContFact ()
~PixelContFact ()
FairParSet * createContainer (FairContainer *)
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual void activateParIo (FairParIo *)
Protected Member Functions
const char * getActualContext (const char *name)
Protected Attributes
TList * containers
FairLogger * fLogger
Private Member Functions
void setAllContainers ()
Detailed Description
Definition at line 16 of file PixelContFact.h.
Constructor & Destructor Documentation
PixelContFact()
PixelContFact::PixelContFact ()
Constructor (called when the library is loaded)
Definition at line 24 of file PixelContFact.cxx.
References FairRuntimeDb::addContFactory(), FairParSet::fName, FairParSet::fTitle, FairRuntimeDb::instance(), and setAllContainers().
~PixelContFact()
PixelContFact::~PixelContFact () inline
Definition at line 22 of file PixelContFact.h.
Member Function Documentation
activateParIo()
virtual void FairContFact::activateParIo (FairParIo *) inline virtual inherited
Definition at line 57 of file FairContFact.h.
Referenced by FairRuntimeDb::activateParIo().
addContext()
Bool_t FairContFact::addContext (const char * name) inherited
Definition at line 160 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::setActualContext().
Referenced by FairRuntimeDb::addParamContext().
createContainer()
FairParSet * PixelContFact::createContainer (FairContainer * c) virtual
Calls the constructor of the corresponding parameter container. For an actual context, which is not an empty string and not the default context of this container, the name is concatinated with the context.
Reimplemented from FairContFact.
Definition at line 57 of file PixelContFact.cxx.
References FairContainer::getConcatName(), and FairContainer::getContext().
getActualContext()
const char* FairContFact::getActualContext (const char * name) inline protected inherited
Definition at line 61 of file FairContFact.h.
References FairContFact::containers.
getContainer()
FairParSet * FairContFact::getContainer (const char * name) inherited
Definition at line 172 of file FairContFact.cxx.
References FairRuntimeDb::addContainer(), FairContFact::containers, FairContFact::createContainer(), FairRuntimeDb::findContainer(), FairContainer::getActualContext(), FairContainer::getConcatName(), FairContainer::getDefaultContext(), FairRuntimeDb::instance(), and FairContainer::setActualContext().
Referenced by FairRuntimeDb::getContainer().
print()
void FairContFact::print () inherited
Definition at line 194 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::print().
Referenced by FairRuntimeDb::printParamContexts().
setAllContainers()
void PixelContFact::setAllContainers () private
Creates the Container objects with all accepted contexts and adds them to the list of containers for the Pixel library.
Definition at line 34 of file PixelContFact.cxx.
References FairContainer::addContext(), and FairContFact::containers.
Referenced by PixelContFact().
Member Data Documentation
containers
TList* FairContFact::containers protected inherited
Definition at line 60 of file FairContFact.h.
Referenced by FairContFact::addContext(), FairContFact::getActualContext(), FairContFact::getContainer(), FairContFact::print(), NewDetectorContFact::setAllContainers(), FairTutorialDet2ContFact::setAllContainers(), FairMQExParamsContFact::setAllContainers(), setAllContainers(), FairRutherfordContFact::setAllContainers(), FairTestDetectorContFact::setAllContainers(), FairTutorialDet1ContFact::setAllContainers(), FairTutorialDet4ContFact::setAllContainers(), FairPassiveContFact::setAllContainers(), FairBaseContFact::setAllContainers(), MyPassiveContFact::setAllContainers(), and FairContFact::~FairContFact().
fLogger
FairLogger* FairContFact::fLogger protected inherited
Fair Logger
Definition at line 65 of file FairContFact.h.
The documentation for this class was generated from the following files:
PixelContFact.h
PixelContFact.cxx