FairRroot: fair::mq::test::Dummy2Plugin Class Reference
fair::mq::test::Dummy2Plugin Class Reference
#include <dummy2.h>
Public Types
using ProgOptions = boost::optional< boost::program_options::options_description >
using Version = tools::Version
using DeviceState = fair::mq::PluginServices::DeviceState
using DeviceStateTransition = fair::mq::PluginServices::DeviceStateTransition
Public Member Functions
Dummy2Plugin (const std::string name, const Version version, const std::string maintainer, const std::string homepage, PluginServices *pluginServices)
auto GetName () const -> const std::string &
auto GetVersion () const -> const Version
auto GetMaintainer () const -> const std::string &
auto GetHomepage () const -> const std::string &
auto ToDeviceState (const std::string &state) const -> DeviceState
auto ToDeviceStateTransition (const std::string &transition) const -> DeviceStateTransition
auto ToStr (DeviceState state) const -> std::string
auto ToStr (DeviceStateTransition transition) const -> std::string
auto GetCurrentDeviceState () const -> DeviceState
auto TakeDeviceControl () -> void
auto StealDeviceControl () -> void
auto ReleaseDeviceControl () -> void
auto ChangeDeviceState (const DeviceStateTransition next) -> void
auto SubscribeToDeviceStateChange (std::function< void(DeviceState)> callback) -> void
auto UnsubscribeFromDeviceStateChange () -> void
auto PropertyExists (const std::string &key) -> int
template<typename T >
auto SetProperty (const std::string &key, T val) -> void
template<typename T >
auto GetProperty (const std::string &key) const -> T
auto GetPropertyAsString (const std::string &key) const -> std::string
auto GetChannelInfo () const -> std::unordered_map< std::string, int >
auto GetPropertyKeys () const -> std::vector< std::string >
template<typename T >
auto SubscribeToPropertyChange (std::function< void(const std::string &key, T newValue)> callback) -> void
template<typename T >
auto UnsubscribeFromPropertyChange () -> void
auto SubscribeToPropertyChangeAsString (std::function< void(const std::string &key, std::string newValue)> callback) -> void
auto UnsubscribeFromPropertyChangeAsString () -> void
Static Public Member Functions
static auto NoProgramOptions () -> ProgOptions
Detailed Description
Definition at line 21 of file dummy2.h.
Member Typedef Documentation
using fair::mq::Plugin::DeviceState = fair::mq::PluginServices::DeviceState inherited
Definition at line 71 of file Plugin.h.
using fair::mq::Plugin::DeviceStateTransition = fair::mq::PluginServices::DeviceStateTransition inherited
Definition at line 72 of file Plugin.h.
using fair::mq::Plugin::ProgOptions = boost::optional<boost::program_options::options_description> inherited
Definition at line 41 of file Plugin.h.
using fair::mq::Plugin::Version = tools::Version inherited
Definition at line 43 of file Plugin.h.
Constructor & Destructor Documentation
fair::mq::test::Dummy2Plugin::Dummy2Plugin (const std::string name, const Version version, const std::string maintainer, const std::string homepage, PluginServices * pluginServices) inline
Definition at line 25 of file dummy2.h.
Member Function Documentation
auto fair::mq::Plugin::ChangeDeviceState (const DeviceStateTransition next) -> void inline inherited
Definition at line 81 of file Plugin.h.
References fair::mq::PluginServices::ChangeDeviceState(), fair::mq::Plugin::fkName, and fair::mq::Plugin::fPluginServices.
auto fair::mq::Plugin::GetChannelInfo () const -> std::unordered_map<std::string, int> inline inherited
Definition at line 93 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetChannelInfo().
auto fair::mq::Plugin::GetCurrentDeviceState () const -> DeviceState inline inherited
Definition at line 77 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetCurrentDeviceState().
auto fair::mq::Plugin::GetHomepage () const -> const std::string& inline inherited
Definition at line 56 of file Plugin.h.
References fair::mq::Plugin::fkHomepage.
auto fair::mq::Plugin::GetMaintainer () const -> const std::string& inline inherited
Definition at line 55 of file Plugin.h.
References fair::mq::Plugin::fkMaintainer.
auto fair::mq::Plugin::GetName () const -> const std::string& inline inherited
Definition at line 53 of file Plugin.h.
References fair::mq::Plugin::fkName.
template<typename T > auto fair::mq::Plugin::GetProperty (const std::string & key) const -> T inline inherited
Definition at line 91 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetProperty().
auto fair::mq::Plugin::GetPropertyAsString (const std::string & key) const -> std::string inline inherited
Definition at line 92 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetPropertyAsString().
auto fair::mq::Plugin::GetPropertyKeys () const -> std::vector<std::string> inline inherited
Definition at line 94 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::GetPropertyKeys().
auto fair::mq::Plugin::GetVersion () const -> const Version inline inherited
Definition at line 54 of file Plugin.h.
References fair::mq::Plugin::fkVersion.
static auto fair::mq::Plugin::NoProgramOptions () -> ProgOptions inline static inherited
Definition at line 67 of file Plugin.h.
auto fair::mq::Plugin::PropertyExists (const std::string & key) -> int inline inherited
Definition at line 87 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::PropertyExists().
auto fair::mq::Plugin::ReleaseDeviceControl () -> void inline inherited
Definition at line 80 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ReleaseDeviceControl().
template<typename T > auto fair::mq::Plugin::SetProperty (const std::string & key, T val) -> void inline inherited
Definition at line 89 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SetProperty().
auto fair::mq::Plugin::StealDeviceControl () -> void inline inherited
Definition at line 79 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::StealDeviceControl().
auto fair::mq::Plugin::SubscribeToDeviceStateChange (std::function< void(DeviceState)> callback) -> void inline inherited
Definition at line 82 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToDeviceStateChange().
Referenced by fair::mq::test::DummyPlugin::DummyPlugin().
template<typename T > auto fair::mq::Plugin::SubscribeToPropertyChange (std::function< void(const std::string &key, T newValue)> callback) -> void inline inherited
Definition at line 96 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToPropertyChange().
auto fair::mq::Plugin::SubscribeToPropertyChangeAsString (std::function< void(const std::string &key, std::string newValue)> callback) -> void inline inherited
Definition at line 99 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::SubscribeToPropertyChangeAsString().
auto fair::mq::Plugin::TakeDeviceControl () -> void inline inherited
Definition at line 78 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::TakeDeviceControl().
auto fair::mq::Plugin::ToDeviceState (const std::string & state) const -> DeviceState inline inherited
Definition at line 73 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, fair::state, and fair::mq::PluginServices::ToDeviceState().
auto fair::mq::Plugin::ToDeviceStateTransition (const std::string & transition) const -> DeviceStateTransition inline inherited
Definition at line 74 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ToDeviceStateTransition().
auto fair::mq::Plugin::ToStr (DeviceState state) const -> std::string inline inherited
Definition at line 75 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, fair::state, and fair::mq::PluginServices::ToStr().
auto fair::mq::Plugin::ToStr (DeviceStateTransition transition) const -> std::string inline inherited
Definition at line 76 of file Plugin.h.
References fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::ToStr().
auto fair::mq::Plugin::UnsubscribeFromDeviceStateChange () -> void inline inherited
Definition at line 83 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromDeviceStateChange().
Referenced by fair::mq::test::DummyPlugin::DummyPlugin().
template<typename T > auto fair::mq::Plugin::UnsubscribeFromPropertyChange () -> void inline inherited
Definition at line 98 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromPropertyChange().
auto fair::mq::Plugin::UnsubscribeFromPropertyChangeAsString () -> void inline inherited
Definition at line 100 of file Plugin.h.
References fair::mq::Plugin::fkName, fair::mq::Plugin::fPluginServices, and fair::mq::PluginServices::UnsubscribeFromPropertyChangeAsString().
The documentation for this class was generated from the following file:
dummy2.h