FairRoot: FairUnpack Class Reference
FairUnpack Class Reference abstract
#include <FairUnpack.h>
Public Member Functions
FairUnpack (Short_t type, Short_t subType, Short_t procId, Short_t subCrate, Short_t control)
virtual ~FairUnpack ()
virtual Bool_t Init ()=0
virtual Bool_t ReInit ()
virtual Bool_t DoUnpack (Int_t *data, Int_t size)=0
virtual void Reset ()=0
virtual void SetParContainers ()
Short_t GetType () const
Short_t GetSubType () const
Short_t GetProcId () const
Short_t GetSubCrate () const
Short_t GetControl () const
Protected Member Functions
virtual void Register ()=0
Private Attributes
Short_t fType
Short_t fSubType
Short_t fProcId
Short_t fSubCrate
Short_t fControl
Detailed Description
Definition at line 21 of file FairUnpack.h.
Constructor & Destructor Documentation
FairUnpack()
FairUnpack::FairUnpack (Short_t type, Short_t subType, Short_t procId, Short_t subCrate, Short_t control)
Definition at line 17 of file FairUnpack.cxx.
~FairUnpack()
FairUnpack::~FairUnpack () virtual
Definition at line 29 of file FairUnpack.cxx.
Member Function Documentation
DoUnpack()
virtual Bool_t FairUnpack::DoUnpack (Int_t * data, Int_t size) pure virtual
Implemented in FairMBSUnpack, and FairMBSUnpacker.
Referenced by FairMbsSource::Unpack().
GetControl()
Short_t FairUnpack::GetControl () const inline
Definition at line 38 of file FairUnpack.h.
References fControl.
Referenced by FairMbsSource::Unpack().
GetProcId()
Short_t FairUnpack::GetProcId () const inline
Definition at line 36 of file FairUnpack.h.
References fProcId.
Referenced by FairMbsSource::Unpack().
GetSubCrate()
Short_t FairUnpack::GetSubCrate () const inline
Definition at line 37 of file FairUnpack.h.
References fSubCrate.
Referenced by FairMbsSource::Unpack().
GetSubType()
Short_t FairUnpack::GetSubType () const inline
Definition at line 35 of file FairUnpack.h.
References fSubType.
Referenced by FairMbsSource::Unpack().
GetType()
Short_t FairUnpack::GetType () const inline
Definition at line 34 of file FairUnpack.h.
References fType.
Referenced by FairMbsSource::Unpack().
Init()
virtual Bool_t FairUnpack::Init () pure virtual
Implemented in FairMBSUnpack, and FairMBSUnpacker.
Register()
virtual void FairUnpack::Register () protected pure virtual
Implemented in FairMBSUnpacker, and FairMBSUnpack.
ReInit()
virtual Bool_t FairUnpack::ReInit () inline virtual
Definition at line 29 of file FairUnpack.h.
Reset()
virtual void FairUnpack::Reset () pure virtual
Implemented in FairMBSUnpack, and FairMBSUnpacker.
SetParContainers()
virtual void FairUnpack::SetParContainers () inline virtual
Definition at line 32 of file FairUnpack.h.
Member Data Documentation
fControl
Short_t FairUnpack::fControl private
Definition at line 45 of file FairUnpack.h.
Referenced by GetControl().
fProcId
Short_t FairUnpack::fProcId private
Definition at line 43 of file FairUnpack.h.
Referenced by GetProcId().
fSubCrate
Short_t FairUnpack::fSubCrate private
Definition at line 44 of file FairUnpack.h.
Referenced by GetSubCrate().
fSubType
Short_t FairUnpack::fSubType private
Definition at line 42 of file FairUnpack.h.
Referenced by GetSubType().
fType
Short_t FairUnpack::fType private
Definition at line 41 of file FairUnpack.h.
Referenced by GetType().
The documentation for this class was generated from the following files:
FairUnpack.h
FairUnpack.cxx