FairRoot: FairEventManager Class Reference
FairEventManager Class Reference
#include <FairEventManager.h>
Public Member Functions
FairEventManager ()
virtual ~FairEventManager ()
virtual void SetXMLConfig (TString xml_config)
virtual void Open ()
virtual void GotoEvent (Int_t event)
virtual void NextEvent ()
virtual void PrevEvent ()
virtual void Close ()
virtual void DisplaySettings ()
virtual Int_t Color (Int_t pdg)
void AddTask (FairTask *t)
virtual void Init (Int_t visopt=1, Int_t vislvl=3, Int_t maxvisnds=10000)
virtual Int_t GetCurrentEvent ()
virtual void SetPriOnly (Bool_t Pri)
virtual Bool_t IsPriOnly ()
virtual void SelectPDG (Int_t PDG)
virtual Int_t GetCurrentPDG ()
virtual void SetMaxEnergy (Float_t max)
virtual void SetMinEnergy (Float_t min)
virtual void SetEvtMaxEnergy (Float_t max)
virtual void SetEvtMinEnergy (Float_t min)
virtual Float_t GetEvtMaxEnergy ()
virtual Float_t GetEvtMinEnergy ()
virtual Float_t GetMaxEnergy ()
virtual Float_t GetMinEnergy ()
virtual void SetRPhiPlane (Double_t a, Double_t b, Double_t c, Double_t d)
virtual void SetRhoZPlane (Double_t a, Double_t b, Double_t c, Double_t d)
void UpdateEditor ()
virtual void AddParticlesToPdgDataBase (Int_t pdg=0)
ClassDef (FairEventManager, 1)
Static Public Member Functions
static FairEventManager * Instance ()
Protected Member Functions
TEveViewer * GetRPhiView () const
TEveViewer * GetRhoZView () const
TEveViewer * GetMultiView () const
TEveViewer * GetMultiRPhiView () const
TEveViewer * GetMultiRhoZView () const
TEveScene * GetRhoZScene () const
TEveScene * GetRPhiScene () const
TEveProjectionManager * GetRhoZProjManager () const
TEveProjectionManager * GetRPhiProjManager () const
TEveProjectionAxes * GetRPhiAxes () const
TEveProjectionAxes * GetRhoZAxes () const
virtual void LoadXMLSettings ()
void LoadXMLDetector (TGeoNode *node, FairXMLNode *xml, Int_t depth=0)
Int_t StringToColor (TString color) const
Private Member Functions
FairEventManager (const FairEventManager &)
FairEventManager & operator= (const FairEventManager &)
void SetViewers (TEveViewer *RPhi, TEveViewer *RhoZ)
Private Attributes
FairRootManager * fRootManager
Int_t fEntry
FairRunAna * fRunAna
TGListTreeItem * fEvent
Bool_t fPriOnly
Int_t fCurrentPDG
Float_t fMinEnergy
Float_t fMaxEnergy
Float_t fEvtMinEnergy
Float_t fEvtMaxEnergy
Double_t fRPhiPlane [4]
Double_t fRhoZPlane [4]
TEveViewer * fRPhiView
TEveViewer * fRhoZView
TEveViewer * fMultiView
TEveViewer * fMultiRPhiView
TEveViewer * fMultiRhoZView
TEveScene * fRPhiScene
TEveScene * fRhoZScene
TEveProjectionManager * fRPhiProjManager
TEveProjectionManager * fRhoZProjManager
TEveProjectionAxes * fAxesPhi
TEveProjectionAxes * fAxesRho
TString fXMLConfig
std::map< int, int > fPDGToColor
Static Private Attributes
static FairEventManager * fgRinstance
Detailed Description
Definition at line 32 of file FairEventManager.h.
Constructor & Destructor Documentation
FairEventManager() [1/2]
FairEventManager::FairEventManager ()
Definition at line 49 of file FairEventManager.cxx.
~FairEventManager()
FairEventManager::~FairEventManager () virtual
Definition at line 211 of file FairEventManager.cxx.
FairEventManager() [2/2]
FairEventManager::FairEventManager (const FairEventManager &) private
Member Function Documentation
AddParticlesToPdgDataBase()
void FairEventManager::AddParticlesToPdgDataBase (Int_t pdg = 0) virtual
Definition at line 260 of file FairEventManager.cxx.
AddTask()
void FairEventManager::AddTask (FairTask * t) inline
Definition at line 46 of file FairEventManager.h.
References FairRun::AddTask(), and fRunAna.
Referenced by eventDisplay().
ClassDef()
FairEventManager::ClassDef (FairEventManager , 1)
Close()
void FairEventManager::Close () virtual
Definition at line 238 of file FairEventManager.cxx.
Color()
Int_t FairEventManager::Color (Int_t pdg) virtual
Definition at line 251 of file FairEventManager.cxx.
References fPDGToColor.
Referenced by FairMCTracks::Exec(), FairMCStack::Exec(), FairMCTracks::GetTrGroup(), and FairMCStack::GetTrGroup().
DisplaySettings()
void FairEventManager::DisplaySettings () virtual
Definition at line 245 of file FairEventManager.cxx.
GetCurrentEvent()
virtual Int_t FairEventManager::GetCurrentEvent () inline virtual
Definition at line 48 of file FairEventManager.h.
References fEntry.
Referenced by FairBoxSetEditor::TimeWindow().
GetCurrentPDG()
virtual Int_t FairEventManager::GetCurrentPDG () inline virtual
Definition at line 52 of file FairEventManager.h.
References fCurrentPDG.
Referenced by FairMCTracks::Exec(), and FairMCStack::Exec().
GetEvtMaxEnergy()
virtual Float_t FairEventManager::GetEvtMaxEnergy () inline virtual
Definition at line 57 of file FairEventManager.h.
References fEvtMaxEnergy.
Referenced by FairMCTracks::Init(), FairMCStack::Init(), and FairEventManagerEditor::SelectEvent().
GetEvtMinEnergy()
virtual Float_t FairEventManager::GetEvtMinEnergy () inline virtual
Definition at line 58 of file FairEventManager.h.
References fEvtMinEnergy.
Referenced by FairMCTracks::Init(), FairMCStack::Init(), and FairEventManagerEditor::SelectEvent().
GetMaxEnergy()
virtual Float_t FairEventManager::GetMaxEnergy () inline virtual
Definition at line 59 of file FairEventManager.h.
References fMaxEnergy.
Referenced by FairMCTracks::Exec(), and FairMCStack::Exec().
GetMinEnergy()
virtual Float_t FairEventManager::GetMinEnergy () inline virtual
Definition at line 60 of file FairEventManager.h.
References fMinEnergy.
Referenced by FairMCTracks::Exec(), and FairMCStack::Exec().
GetMultiRhoZView()
TEveViewer* FairEventManager::GetMultiRhoZView () const inline protected
Definition at line 71 of file FairEventManager.h.
References fMultiRhoZView.
GetMultiRPhiView()
TEveViewer* FairEventManager::GetMultiRPhiView () const inline protected
Definition at line 70 of file FairEventManager.h.
References fMultiRPhiView.
GetMultiView()
TEveViewer* FairEventManager::GetMultiView () const inline protected
Definition at line 69 of file FairEventManager.h.
References fMultiView.
GetRhoZAxes()
TEveProjectionAxes* FairEventManager::GetRhoZAxes () const inline protected
Definition at line 77 of file FairEventManager.h.
References fAxesRho.
GetRhoZProjManager()
TEveProjectionManager* FairEventManager::GetRhoZProjManager () const inline protected
Definition at line 74 of file FairEventManager.h.
References fRhoZProjManager.
GetRhoZScene()
TEveScene* FairEventManager::GetRhoZScene () const inline protected
Definition at line 72 of file FairEventManager.h.
References fRhoZScene.
GetRhoZView()
TEveViewer* FairEventManager::GetRhoZView () const inline protected
Definition at line 68 of file FairEventManager.h.
References fRhoZView.
GetRPhiAxes()
TEveProjectionAxes* FairEventManager::GetRPhiAxes () const inline protected
Definition at line 76 of file FairEventManager.h.
References fAxesPhi.
GetRPhiProjManager()
TEveProjectionManager* FairEventManager::GetRPhiProjManager () const inline protected
Definition at line 75 of file FairEventManager.h.
References fRPhiProjManager.
GetRPhiScene()
TEveScene* FairEventManager::GetRPhiScene () const inline protected
Definition at line 73 of file FairEventManager.h.
References fRPhiScene.
GetRPhiView()
TEveViewer* FairEventManager::GetRPhiView () const inline protected
Definition at line 67 of file FairEventManager.h.
References fRPhiView.
GotoEvent()
void FairEventManager::GotoEvent (Int_t event) virtual
Definition at line 220 of file FairEventManager.cxx.
References fEntry, fRunAna, and FairRunAna::Run().
Referenced by FairEventManagerEditor::SelectEvent(), and FairBoxSetEditor::TimeWindow().
Init()
void FairEventManager::Init (Int_t visopt = 1, Int_t vislvl = 3, Int_t maxvisnds = 10000) virtual
Definition at line 129 of file FairEventManager.cxx.
References fAxesPhi, fAxesRho, fEvent, fMultiRhoZView, fMultiRPhiView, fMultiView, fRhoZProjManager, fRhoZScene, fRhoZView, fRPhiProjManager, fRPhiScene, fRPhiView, fRunAna, fXMLConfig, FairRunAna::Init(), LoadXMLSettings(), and SetViewers().
Referenced by eventDisplay().
Instance()
static FairEventManager* FairEventManager::Instance () static
Referenced by FairTutorialDet4PointDraw::Init(), FairMCTracks::Init(), FairMCStack::Init(), FairPointSetDraw::Init(), FairBoxSetDraw::Init(), and FairBoxSetEditor::TimeWindow().
IsPriOnly()
virtual Bool_t FairEventManager::IsPriOnly () inline virtual
Definition at line 50 of file FairEventManager.h.
References fPriOnly.
Referenced by FairMCTracks::Exec(), and FairMCStack::Exec().
LoadXMLDetector()
void FairEventManager::LoadXMLDetector (TGeoNode * node, FairXMLNode * xml, Int_t depth = 0) protected
Definition at line 381 of file FairEventManager.cxx.
References FairXMLNode::GetAttribValue(), FairXMLNode::GetChild(), FairXMLNode::GetNChildren(), and StringToColor().
Referenced by LoadXMLSettings().
LoadXMLSettings()
void FairEventManager::LoadXMLSettings () protected virtual
Definition at line 353 of file FairEventManager.cxx.
References fPDGToColor, fXMLConfig, FairXMLNode::GetAttribValue(), FairXMLNode::GetChild(), FairXMLNode::GetName(), FairXMLNode::GetNChildren(), FairXMLNode::IsNull(), LoadXMLDetector(), and StringToColor().
Referenced by Init().
NextEvent()
void FairEventManager::NextEvent () virtual
Definition at line 226 of file FairEventManager.cxx.
References fEntry, fRunAna, and FairRunAna::Run().
Open()
void FairEventManager::Open () virtual
Definition at line 215 of file FairEventManager.cxx.
operator=()
FairEventManager& FairEventManager::operator= (const FairEventManager &) private
PrevEvent()
void FairEventManager::PrevEvent () virtual
Definition at line 232 of file FairEventManager.cxx.
References fEntry, fRunAna, and FairRunAna::Run().
SelectPDG()
virtual void FairEventManager::SelectPDG (Int_t PDG) inline virtual
Definition at line 51 of file FairEventManager.h.
References fCurrentPDG.
Referenced by FairEventManagerEditor::SelectPDG().
SetEvtMaxEnergy()
virtual void FairEventManager::SetEvtMaxEnergy (Float_t max) inline virtual
Definition at line 55 of file FairEventManager.h.
References fEvtMaxEnergy.
Referenced by FairMCTracks::Exec(), and FairMCStack::Exec().
SetEvtMinEnergy()
virtual void FairEventManager::SetEvtMinEnergy (Float_t min) inline virtual
Definition at line 56 of file FairEventManager.h.
References fEvtMinEnergy.
Referenced by FairMCTracks::Exec(), and FairMCStack::Exec().
SetMaxEnergy()
virtual void FairEventManager::SetMaxEnergy (Float_t max) inline virtual
Definition at line 53 of file FairEventManager.h.
References fMaxEnergy.
Referenced by FairEventManagerEditor::Init(), and FairEventManagerEditor::MaxEnergy().
SetMinEnergy()
virtual void FairEventManager::SetMinEnergy (Float_t min) inline virtual
Definition at line 54 of file FairEventManager.h.
References fMinEnergy.
Referenced by FairEventManagerEditor::MinEnergy().
SetPriOnly()
virtual void FairEventManager::SetPriOnly (Bool_t Pri) inline virtual
Definition at line 49 of file FairEventManager.h.
References fPriOnly.
Referenced by FairEventManagerEditor::DoVizPri().
SetRhoZPlane()
void FairEventManager::SetRhoZPlane (Double_t a, Double_t b, Double_t c, Double_t d) virtual
Definition at line 345 of file FairEventManager.cxx.
References fRhoZPlane.
SetRPhiPlane()
void FairEventManager::SetRPhiPlane (Double_t a, Double_t b, Double_t c, Double_t d) virtual
Definition at line 337 of file FairEventManager.cxx.
References fRPhiPlane.
SetViewers()
void FairEventManager::SetViewers (TEveViewer * RPhi, TEveViewer * RhoZ) private
Definition at line 305 of file FairEventManager.cxx.
References fRhoZPlane, fRhoZScene, fRPhiPlane, and fRPhiScene.
Referenced by Init().
SetXMLConfig()
virtual void FairEventManager::SetXMLConfig (TString xml_config) inline virtual
Definition at line 38 of file FairEventManager.h.
References fXMLConfig.
StringToColor()
Int_t FairEventManager::StringToColor (TString color) const protected
Definition at line 420 of file FairEventManager.cxx.
Referenced by LoadXMLDetector(), and LoadXMLSettings().
UpdateEditor()
void FairEventManager::UpdateEditor ()
Definition at line 206 of file FairEventManager.cxx.
Member Data Documentation
fAxesPhi
TEveProjectionAxes* FairEventManager::fAxesPhi private
Definition at line 103 of file FairEventManager.h.
Referenced by GetRPhiAxes(), and Init().
fAxesRho
TEveProjectionAxes* FairEventManager::fAxesRho private
Definition at line 104 of file FairEventManager.h.
Referenced by GetRhoZAxes(), and Init().
fCurrentPDG
Int_t FairEventManager::fCurrentPDG private
Definition at line 87 of file FairEventManager.h.
Referenced by GetCurrentPDG(), and SelectPDG().
fEntry
Int_t FairEventManager::fEntry private
Definition at line 83 of file FairEventManager.h.
Referenced by GetCurrentEvent(), GotoEvent(), NextEvent(), and PrevEvent().
fEvent
TGListTreeItem* FairEventManager::fEvent private
Definition at line 85 of file FairEventManager.h.
Referenced by Init().
fEvtMaxEnergy
Float_t FairEventManager::fEvtMaxEnergy private
Definition at line 91 of file FairEventManager.h.
Referenced by GetEvtMaxEnergy(), and SetEvtMaxEnergy().
fEvtMinEnergy
Float_t FairEventManager::fEvtMinEnergy private
Definition at line 90 of file FairEventManager.h.
Referenced by GetEvtMinEnergy(), and SetEvtMinEnergy().
fgRinstance
FairEventManager* FairEventManager::fgRinstance static private
Definition at line 106 of file FairEventManager.h.
fMaxEnergy
Float_t FairEventManager::fMaxEnergy private
Definition at line 89 of file FairEventManager.h.
Referenced by GetMaxEnergy(), and SetMaxEnergy().
fMinEnergy
Float_t FairEventManager::fMinEnergy private
Definition at line 88 of file FairEventManager.h.
Referenced by GetMinEnergy(), and SetMinEnergy().
fMultiRhoZView
TEveViewer* FairEventManager::fMultiRhoZView private
Definition at line 98 of file FairEventManager.h.
Referenced by GetMultiRhoZView(), and Init().
fMultiRPhiView
TEveViewer* FairEventManager::fMultiRPhiView private
Definition at line 97 of file FairEventManager.h.
Referenced by GetMultiRPhiView(), and Init().
fMultiView
TEveViewer* FairEventManager::fMultiView private
Definition at line 96 of file FairEventManager.h.
Referenced by GetMultiView(), and Init().
fPDGToColor
std::map<int,int> FairEventManager::fPDGToColor private
Definition at line 106 of file FairEventManager.h.
Referenced by Color(), and LoadXMLSettings().
fPriOnly
Bool_t FairEventManager::fPriOnly private
Definition at line 86 of file FairEventManager.h.
Referenced by IsPriOnly(), and SetPriOnly().
fRhoZPlane
Double_t FairEventManager::fRhoZPlane[4] private
Definition at line 93 of file FairEventManager.h.
Referenced by SetRhoZPlane(), and SetViewers().
fRhoZProjManager
TEveProjectionManager* FairEventManager::fRhoZProjManager private
Definition at line 102 of file FairEventManager.h.
Referenced by GetRhoZProjManager(), and Init().
fRhoZScene
TEveScene* FairEventManager::fRhoZScene private
Definition at line 100 of file FairEventManager.h.
Referenced by GetRhoZScene(), Init(), and SetViewers().
fRhoZView
TEveViewer* FairEventManager::fRhoZView private
Definition at line 95 of file FairEventManager.h.
Referenced by GetRhoZView(), and Init().
fRootManager
FairRootManager* FairEventManager::fRootManager private
Definition at line 82 of file FairEventManager.h.
fRPhiPlane
Double_t FairEventManager::fRPhiPlane[4] private
Definition at line 92 of file FairEventManager.h.
Referenced by SetRPhiPlane(), and SetViewers().
fRPhiProjManager
TEveProjectionManager* FairEventManager::fRPhiProjManager private
Definition at line 101 of file FairEventManager.h.
Referenced by GetRPhiProjManager(), and Init().
fRPhiScene
TEveScene* FairEventManager::fRPhiScene private
Definition at line 99 of file FairEventManager.h.
Referenced by GetRPhiScene(), Init(), and SetViewers().
fRPhiView
TEveViewer* FairEventManager::fRPhiView private
Definition at line 94 of file FairEventManager.h.
Referenced by GetRPhiView(), and Init().
fRunAna
FairRunAna* FairEventManager::fRunAna private
Definition at line 84 of file FairEventManager.h.
Referenced by AddTask(), GotoEvent(), Init(), NextEvent(), and PrevEvent().
fXMLConfig
TString FairEventManager::fXMLConfig private
Definition at line 105 of file FairEventManager.h.
Referenced by Init(), LoadXMLSettings(), and SetXMLConfig().
The documentation for this class was generated from the following files:
FairEventManager.h
FairEventManager.cxx