FairRoot: FairMonitor Class Reference
FairMonitor Class Reference
#include <FairMonitor.h>
Public Member Functions
void EnableMonitor (Bool_t tempBool=kTRUE, TString fileName="")
Bool_t IsRunning ()
void StartMonitoring (const TTask *tTask, const char *identStr)
void StopMonitoring (const TTask *tTask, const char *identStr)
void StartTimer (const TTask *tTask, const char *identStr)
void StopTimer (const TTask *tTask, const char *identStr)
void StartMemoryMonitor (const TTask *tTask, const char *identStr)
void StopMemoryMonitor (const TTask *tTask, const char *identStr)
void RecordInfo (const TTask *tTask, const char *identStr, Double_t value)
void RecordRegister (const char *name, const char *folderName, Bool_t toFile)
void RecordGetting (const char *name)
void SetCurrentTask (TTask *tTask)
virtual void Print (Option_t *option="") const
virtual void Draw (Option_t *option="")
void PrintTask (TString specString) const
void PrintTask (TTask *tempTask, Int_t taskLevel=0) const
void DrawHist (TString specString)
TList * GetHistList ()
void StoreHistograms ()
Static Public Member Functions
static FairMonitor * GetMonitor ()
Private Member Functions
FairMonitor ()
~FairMonitor ()
FairMonitor (const FairMonitor &)
FairMonitor & operator= (const FairMonitor &)
void GetTaskMap (TTask *tempTask)
void AnalyzeObjectMap (TTask *tempTask)
Private Attributes
Bool_t fRunMonitor
Double_t fRunTime
Double_t fRunMem
std::map< TString, TStopwatch > fTimerMap
std::map< TString, Int_t > fMemoryMap
TList * fHistList
TCanvas * fCanvas
Int_t fNoTaskRequired
Int_t fNoTaskCreated
TTask * fCurrentTask
TString fOutputFileName
std::multimap< TString, TString > fTaskRequired
std::multimap< TString, TString > fTaskCreated
std::multimap< TString, TString > fTaskCreatedTemp
std::map< TString, Int_t > fObjectMap
std::map< TString, Int_t > fTaskMap
std::map< TString, std::pair< Double_t, Double_t > > fObjectPos
std::map< TString, std::pair< Double_t, Double_t > > fTaskPos
Static Private Attributes
static FairMonitor * instance = NULL
Detailed Description
Definition at line 30 of file FairMonitor.h.
Constructor & Destructor Documentation
FairMonitor() [1/2]
FairMonitor::FairMonitor () private
Definition at line 45 of file FairMonitor.cxx.
Referenced by GetMonitor().
~FairMonitor()
FairMonitor::~FairMonitor () private
Definition at line 69 of file FairMonitor.cxx.
FairMonitor() [2/2]
FairMonitor::FairMonitor (const FairMonitor &) private
Member Function Documentation
AnalyzeObjectMap()
void FairMonitor::AnalyzeObjectMap (TTask * tempTask) private
Definition at line 676 of file FairMonitor.cxx.
References fObjectMap, fTaskCreated, fTaskCreatedTemp, fTaskMap, and fTaskRequired.
Referenced by Draw().
Draw()
void FairMonitor::Draw (Option_t * option = "") virtual
Definition at line 360 of file FairMonitor.cxx.
References AnalyzeObjectMap(), fCanvas, fHistList, fObjectMap, fObjectPos, fRunMonitor, fRunTime, fTaskCreated, fTaskCreatedTemp, fTaskMap, fTaskPos, fTaskRequired, and GetTaskMap().
Referenced by StoreHistograms().
DrawHist()
void FairMonitor::DrawHist (TString specString)
Definition at line 575 of file FairMonitor.cxx.
References fHistList, and fRunMonitor.
EnableMonitor()
void FairMonitor::EnableMonitor (Bool_t tempBool = kTRUE, TString fileName = "") inline
Definition at line 35 of file FairMonitor.h.
References fOutputFileName, and fRunMonitor.
GetHistList()
TList* FairMonitor::GetHistList () inline
Definition at line 67 of file FairMonitor.h.
References fHistList.
GetMonitor()
FairMonitor * FairMonitor::GetMonitor () static
Definition at line 75 of file FairMonitor.cxx.
References FairMonitor(), and instance.
Referenced by FairTask::ExecuteTask(), FairTask::ExecuteTasks(), FairRootManager::GetObject(), FairTask::InitTask(), FairRootManager::LastFill(), FairRootManager::Register(), and FairRootManager::RegisterImpl().
GetTaskMap()
void FairMonitor::GetTaskMap (TTask * tempTask) private
Definition at line 655 of file FairMonitor.cxx.
References fTaskMap.
Referenced by Draw().
IsRunning()
Bool_t FairMonitor::IsRunning () inline
Definition at line 36 of file FairMonitor.h.
References fRunMonitor.
operator=()
FairMonitor& FairMonitor::operator= (const FairMonitor &) private
Print()
void FairMonitor::Print (Option_t * option = "") const virtual
Definition at line 318 of file FairMonitor.cxx.
References fRunMonitor, fRunTime, and PrintTask().
PrintTask() [1/2]
void FairMonitor::PrintTask (TString specString) const
Definition at line 334 of file FairMonitor.cxx.
References fHistList, and fRunMonitor.
Referenced by Print(), and PrintTask().
PrintTask() [2/2]
void FairMonitor::PrintTask (TTask * tempTask, Int_t taskLevel = 0) const
Definition at line 227 of file FairMonitor.cxx.
References fHistList, fRunMonitor, fRunTime, INFO, and PrintTask().
RecordGetting()
void FairMonitor::RecordGetting (const char * name)
Definition at line 212 of file FairMonitor.cxx.
References fCurrentTask, fNoTaskRequired, fRunMonitor, and fTaskRequired.
Referenced by FairRootManager::GetObject().
RecordInfo()
void FairMonitor::RecordInfo (const TTask * tTask, const char * identStr, Double_t value)
Definition at line 166 of file FairMonitor.cxx.
References fHistList, and fRunMonitor.
Referenced by StopMemoryMonitor(), and StopTimer().
RecordRegister()
void FairMonitor::RecordRegister (const char * name, const char * folderName, Bool_t toFile)
Definition at line 192 of file FairMonitor.cxx.
References fCurrentTask, fNoTaskCreated, fRunMonitor, fTaskCreated, and fTaskCreatedTemp.
Referenced by FairRootManager::Register(), and FairRootManager::RegisterImpl().
SetCurrentTask()
void FairMonitor::SetCurrentTask (TTask * tTask) inline
Definition at line 58 of file FairMonitor.h.
References fCurrentTask.
Referenced by FairTask::InitTask().
StartMemoryMonitor()
void FairMonitor::StartMemoryMonitor (const TTask * tTask, const char * identStr)
Definition at line 126 of file FairMonitor.cxx.
References fMemoryMap, fRunMonitor, and FairSystemInfo::GetCurrentMemory().
Referenced by StartMonitoring().
StartMonitoring()
void FairMonitor::StartMonitoring (const TTask * tTask, const char * identStr) inline
Definition at line 38 of file FairMonitor.h.
References StartMemoryMonitor(), and StartTimer().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
StartTimer()
void FairMonitor::StartTimer (const TTask * tTask, const char * identStr)
Definition at line 85 of file FairMonitor.cxx.
References fRunMonitor, and fTimerMap.
Referenced by StartMonitoring().
StopMemoryMonitor()
void FairMonitor::StopMemoryMonitor (const TTask * tTask, const char * identStr)
Definition at line 144 of file FairMonitor.cxx.
References fMemoryMap, fRunMem, fRunMonitor, FairSystemInfo::GetCurrentMemory(), and RecordInfo().
Referenced by StopMonitoring().
StopMonitoring()
void FairMonitor::StopMonitoring (const TTask * tTask, const char * identStr) inline
Definition at line 42 of file FairMonitor.h.
References StopMemoryMonitor(), and StopTimer().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
StopTimer()
void FairMonitor::StopTimer (const TTask * tTask, const char * identStr)
Definition at line 102 of file FairMonitor.cxx.
References fRunMonitor, fRunTime, fTimerMap, and RecordInfo().
Referenced by StopMonitoring().
StoreHistograms()
void FairMonitor::StoreHistograms ()
Definition at line 621 of file FairMonitor.cxx.
References Draw(), fCanvas, fHistList, fOutputFileName, and fRunMonitor.
Referenced by FairRootManager::LastFill().
Member Data Documentation
fCanvas
TCanvas* FairMonitor::fCanvas private
Definition at line 87 of file FairMonitor.h.
Referenced by Draw(), and StoreHistograms().
fCurrentTask
TTask* FairMonitor::fCurrentTask private
Definition at line 92 of file FairMonitor.h.
Referenced by RecordGetting(), RecordRegister(), and SetCurrentTask().
fHistList
TList* FairMonitor::fHistList private
Definition at line 86 of file FairMonitor.h.
Referenced by Draw(), DrawHist(), GetHistList(), PrintTask(), RecordInfo(), and StoreHistograms().
fMemoryMap
std::map<TString, Int_t> FairMonitor::fMemoryMap private
Definition at line 84 of file FairMonitor.h.
Referenced by StartMemoryMonitor(), and StopMemoryMonitor().
fNoTaskCreated
Int_t FairMonitor::fNoTaskCreated private
Definition at line 90 of file FairMonitor.h.
Referenced by RecordRegister().
fNoTaskRequired
Int_t FairMonitor::fNoTaskRequired private
Definition at line 89 of file FairMonitor.h.
Referenced by RecordGetting().
fObjectMap
std::map<TString, Int_t> FairMonitor::fObjectMap private
Definition at line 100 of file FairMonitor.h.
Referenced by AnalyzeObjectMap(), and Draw().
fObjectPos
std::map<TString, std::pair<Double_t, Double_t> > FairMonitor::fObjectPos private
Definition at line 103 of file FairMonitor.h.
Referenced by Draw().
fOutputFileName
TString FairMonitor::fOutputFileName private
Definition at line 94 of file FairMonitor.h.
Referenced by EnableMonitor(), and StoreHistograms().
fRunMem
Double_t FairMonitor::fRunMem private
Definition at line 81 of file FairMonitor.h.
Referenced by StopMemoryMonitor().
fRunMonitor
Bool_t FairMonitor::fRunMonitor private
Definition at line 78 of file FairMonitor.h.
Referenced by Draw(), DrawHist(), EnableMonitor(), IsRunning(), Print(), PrintTask(), RecordGetting(), RecordInfo(), RecordRegister(), StartMemoryMonitor(), StartTimer(), StopMemoryMonitor(), StopTimer(), and StoreHistograms().
fRunTime
Double_t FairMonitor::fRunTime private
Definition at line 80 of file FairMonitor.h.
Referenced by Draw(), Print(), PrintTask(), and StopTimer().
fTaskCreated
std::multimap<TString, TString> FairMonitor::fTaskCreated private
Definition at line 97 of file FairMonitor.h.
Referenced by AnalyzeObjectMap(), Draw(), and RecordRegister().
fTaskCreatedTemp
std::multimap<TString, TString> FairMonitor::fTaskCreatedTemp private
Definition at line 98 of file FairMonitor.h.
Referenced by AnalyzeObjectMap(), Draw(), and RecordRegister().
fTaskMap
std::map<TString, Int_t> FairMonitor::fTaskMap private
Definition at line 101 of file FairMonitor.h.
Referenced by AnalyzeObjectMap(), Draw(), and GetTaskMap().
fTaskPos
std::map<TString, std::pair<Double_t, Double_t> > FairMonitor::fTaskPos private
Definition at line 104 of file FairMonitor.h.
Referenced by Draw().
fTaskRequired
std::multimap<TString, TString> FairMonitor::fTaskRequired private
Definition at line 96 of file FairMonitor.h.
Referenced by AnalyzeObjectMap(), Draw(), and RecordGetting().
fTimerMap
std::map<TString, TStopwatch> FairMonitor::fTimerMap private
Definition at line 83 of file FairMonitor.h.
Referenced by StartTimer(), and StopTimer().
instance
FairMonitor * FairMonitor::instance = NULL static private
Definition at line 72 of file FairMonitor.h.
Referenced by GetMonitor().
The documentation for this class was generated from the following files:
FairMonitor.h
FairMonitor.cxx