FairRroot: fair::mq::ofi::Context Class Reference
fair::mq::ofi::Context Class Reference
Transport-wide context.
#include <fairmq/ofi/Context.h>
Classes
struct Address
Public Member Functions
Context (int numberIoThreads=2)
~Context ()
auto CreateOfiEndpoint () -> fid_ep *
auto CreateOfiCompletionQueue (Direction dir) -> fid_cq *
auto GetZmqVersion () const -> std::string
auto GetOfiApiVersion () const -> std::string
auto GetPbVersion () const -> std::string
auto GetBoostVersion () const -> std::string
auto GetZmqContext () const -> void *
auto GetIoContext () -> boost::asio::io_service &
auto InsertAddressVector (sockaddr_in address) -> fi_addr_t
auto AddressVectorLookup (fi_addr_t address) -> sockaddr_in
auto InitOfi (ConnectionType type, Address address) -> void
Static Public Member Functions
static auto ConvertAddress (std::string address) -> Address
static auto ConvertAddress (Address address) -> sockaddr_in
static auto ConvertAddress (sockaddr_in address) -> Address
static auto VerifyAddress (const std::string &address) -> Address
Private Member Functions
auto OpenOfiFabric () -> void
auto OpenOfiEventQueue () -> void
auto OpenOfiDomain () -> void
auto OpenOfiAddressVector () -> void
auto InitThreadPool (int numberIoThreads) -> void
Private Attributes
void * fZmqContext
fi_info * fOfiInfo
fid_fabric * fOfiFabric
fid_domain * fOfiDomain
fid_av * fOfiAddressVector
fid_eq * fOfiEventQueue
boost::asio::io_service fIoContext
boost::asio::io_service::work fIoWork
std::vector< std::thread > fThreadPool
Detailed Description
Transport-wide context.
Todo:
TODO insert long description
Definition at line 38 of file Context.h.
Constructor & Destructor Documentation
fair::mq::ofi::Context::Context (int numberIoThreads = 2)
Definition at line 38 of file Context.cxx.
References fZmqContext, InitThreadPool(), and fair::mq::tools::ToString().
fair::mq::ofi::Context::~Context ()
Definition at line 68 of file Context.cxx.
References fair::error, fIoContext, fOfiAddressVector, fOfiDomain, fOfiEventQueue, fOfiFabric, fThreadPool, fZmqContext, and LOG.
Member Function Documentation
auto fair::mq::ofi::Context::AddressVectorLookup (fi_addr_t address) -> sockaddr_in
Definition at line 309 of file Context.cxx.
auto fair::mq::ofi::Context::ConvertAddress (std::string address) -> Address static
Definition at line 314 of file Context.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Context::ConvertAddress (Address address) -> sockaddr_in static
Definition at line 332 of file Context.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Context::ConvertAddress (sockaddr_in address) -> Address static
Definition at line 343 of file Context.cxx.
auto fair::mq::ofi::Context::CreateOfiCompletionQueue (Direction dir) -> fid_cq*
Definition at line 275 of file Context.cxx.
References fair::mq::ofi::Receive, and fair::mq::tools::ToString().
auto fair::mq::ofi::Context::CreateOfiEndpoint () -> fid_ep*
Definition at line 252 of file Context.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Context::GetBoostVersion () const -> std::string
Definition at line 122 of file Context.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Context::GetIoContext () -> boost::asio::io_service& inline
Definition at line 51 of file Context.h.
References fIoContext.
auto fair::mq::ofi::Context::GetOfiApiVersion () const -> std::string
Definition at line 109 of file Context.cxx.
auto fair::mq::ofi::Context::GetPbVersion () const -> std::string
Definition at line 117 of file Context.cxx.
auto fair::mq::ofi::Context::GetZmqContext () const -> void* inline
Definition at line 50 of file Context.h.
References fZmqContext.
auto fair::mq::ofi::Context::GetZmqVersion () const -> std::string
Definition at line 102 of file Context.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Context::InitOfi (ConnectionType type, Address address) -> void
Definition at line 127 of file Context.cxx.
References fair::mq::ofi::Bind, fair::debug, LOG, and fair::mq::tools::ToString().
auto fair::mq::ofi::Context::InitThreadPool (int numberIoThreads) -> void private
Definition at line 55 of file Context.cxx.
References fair::debug, and LOG.
Referenced by Context().
auto fair::mq::ofi::Context::InsertAddressVector (sockaddr_in address) -> fi_addr_t
Definition at line 298 of file Context.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Context::OpenOfiAddressVector () -> void private
Definition at line 226 of file Context.cxx.
References fair::debug, LOG, and fair::mq::tools::ToString().
auto fair::mq::ofi::Context::OpenOfiDomain () -> void private
Definition at line 198 of file Context.cxx.
References fair::debug, LOG, and fair::mq::tools::ToString().
auto fair::mq::ofi::Context::OpenOfiEventQueue () -> void private
Definition at line 212 of file Context.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Context::OpenOfiFabric () -> void private
Definition at line 183 of file Context.cxx.
References fair::debug, LOG, and fair::mq::tools::ToString().
auto fair::mq::ofi::Context::VerifyAddress (const std::string & address) -> Address static
Definition at line 348 of file Context.cxx.
Member Data Documentation
boost::asio::io_service fair::mq::ofi::Context::fIoContext private
Definition at line 73 of file Context.h.
Referenced by GetIoContext(), and ~Context().
boost::asio::io_service::work fair::mq::ofi::Context::fIoWork private
Definition at line 74 of file Context.h.
fid_av* fair::mq::ofi::Context::fOfiAddressVector private
Definition at line 71 of file Context.h.
Referenced by ~Context().
fid_domain* fair::mq::ofi::Context::fOfiDomain private
Definition at line 70 of file Context.h.
Referenced by ~Context().
fid_eq* fair::mq::ofi::Context::fOfiEventQueue private
Definition at line 72 of file Context.h.
Referenced by ~Context().
fid_fabric* fair::mq::ofi::Context::fOfiFabric private
Definition at line 69 of file Context.h.
Referenced by ~Context().
fi_info* fair::mq::ofi::Context::fOfiInfo private
Definition at line 68 of file Context.h.
std::vector<std::thread> fair::mq::ofi::Context::fThreadPool private
Definition at line 75 of file Context.h.
Referenced by ~Context().
void* fair::mq::ofi::Context::fZmqContext private
Definition at line 67 of file Context.h.
Referenced by Context(), GetZmqContext(), and ~Context().
The documentation for this class was generated from the following files:
Context.h
Context.cxx