FairRoot: PixelDigi Class Reference
PixelDigi Class Reference
#include <PixelDigi.h>
Public Member Functions
PixelDigi ()
PixelDigi (Int_t index, Int_t detID, Int_t feID, Int_t col, Int_t row, Double_t charge, Double_t timestamp=-1)
virtual ~PixelDigi ()
void SetIndex (Int_t in)
void SetDetectorID (Int_t det)
void SetFeID (Int_t fe)
void SetCharge (Double_t ch)
void SetCol (Int_t col)
void SetRow (Int_t row)
Int_t GetIndex ()
Int_t GetDetectorID ()
Int_t GetFeID ()
Double_t GetCharge ()
Int_t GetCol ()
Int_t GetRow ()
Double_t GetTimeStamp () const
Double_t GetTimeStampError () const
void SetTimeStamp (Double_t t)
void SetTimeStampError (Double_t t)
virtual Int_t Compare (const TObject *obj) const
virtual std::ostream & PrintTimeInfo (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
virtual bool operator< (const FairTimeStamp *rValue) const
template<class Archive >
void serialize (Archive &ar, const unsigned int)
std::set< FairLink > GetLinks () const
returns stored links as FairLinks
Int_t GetNLinks () const
returns the number of stored links
FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
FairLink GetEntryNr () const
FairMultiLinkedData * GetPointerToLinks () const
std::vector< FairLink > GetSortedMCTracks ()
void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
void SetLink (FairLink link)
Sets the Links with a single FairLink.
void SetInsertHistory (Bool_t val)
void SetEntryNr (FairLink val)
void SetPointerToLinks (FairMultiLinkedData *links)
void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
void AddInterfaceData (FairMultiLinkedData_Interface *data)
void ResetLinks ()
std::ostream & PrintLinkInfo (std::ostream &out=std::cout) const
Output.
Protected Member Functions
ClassDef (FairTimeStamp, 4)
ClassDef (FairMultiLinkedData_Interface, 5)
FairMultiLinkedData * CreateFairMultiLinkedData ()
Protected Attributes
Double_t fTimeStamp
Double_t fTimeStampError
FairMultiLinkedData * fLink
Private Member Functions
ClassDef (PixelDigi, 1)
Private Attributes
Int_t fPointIndex
Int_t fDetectorID
Int_t fFeID
Double_t fCharge
Int_t fCol
Int_t fRow
Detailed Description
Definition at line 22 of file PixelDigi.h.
Constructor & Destructor Documentation
PixelDigi() [1/2]
PixelDigi::PixelDigi ()
Definition at line 18 of file PixelDigi.cxx.
PixelDigi() [2/2]
PixelDigi::PixelDigi (Int_t index, Int_t detID, Int_t feID, Int_t col, Int_t row, Double_t charge, Double_t timestamp = -1)
Parameters
index position of PixelPoint in TClonesArray
detID detector ID (from/for PixelPoint/Hit)
SensorID Sensor ID from digitization scheme
feID front end ID
charge deposited charge in electrons
Definition at line 29 of file PixelDigi.cxx.
~PixelDigi()
PixelDigi::~PixelDigi () virtual
Definition at line 40 of file PixelDigi.cxx.
Member Function Documentation
AddInterfaceData()
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) inherited
Definition at line 172 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
Referenced by FairTestDetectorTimeRecoTask::Exec().
AddLink()
void FairMultiLinkedData_Interface::AddLink (FairLink link) inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorRecoTask::Exec(), and FairTestDetectorTimeRecoTask::Exec().
AddLinks()
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 155 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
ClassDef() [1/3]
PixelDigi::ClassDef (PixelDigi , 1) private
ClassDef() [2/3]
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
ClassDef() [3/3]
FairTimeStamp::ClassDef (FairTimeStamp , 4) protected inherited
Error on time stamp
Compare()
virtual Int_t FairTimeStamp::Compare (const TObject * obj) const inline virtual inherited
Definition at line 48 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
CreateFairMultiLinkedData()
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 59 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
equal()
virtual bool FairTimeStamp::equal (FairTimeStamp * data) inline virtual inherited
Reimplemented in FairTestDetectorDigi, and MyDigi.
Definition at line 62 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, FairTimeStamp::fTimeStampError, FairTimeStamp::GetTimeStamp(), and FairTimeStamp::GetTimeStampError().
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
GetCharge()
Double_t PixelDigi::GetCharge () inline
Definition at line 47 of file PixelDigi.h.
References fCharge.
Referenced by PixelDigitize::ActivatePixel(), FairMQPixelSamplerBin::ConditionalRun(), and PixelDigiWriteToFile::Exec().
GetCol()
Int_t PixelDigi::GetCol () inline
Definition at line 48 of file PixelDigi.h.
References fCol.
Referenced by PixelDigitize::ActivatePixel(), FairMQPixelSamplerBin::ConditionalRun(), PixelFindHitsTask::Exec(), PixelDigiWriteToBinFile::Exec(), PixelDigiWriteToFile::Exec(), PixelAltDigiWriteToRootVector::Exec(), PixelFindHits::Exec(), and PixelAltFindHits::Exec().
GetDetectorID()
Int_t PixelDigi::GetDetectorID () inline
Definition at line 45 of file PixelDigi.h.
References fDetectorID.
Referenced by PixelDigitize::ActivatePixel(), FairMQPixelSamplerBin::ConditionalRun(), PixelFindHitsTask::Exec(), PixelDigiWriteToBinFile::Exec(), PixelDigiWriteToFile::Exec(), PixelAltDigiWriteToRootVector::Exec(), PixelFindHits::Exec(), and PixelAltFindHits::Exec().
GetEntryNr()
FairLink FairMultiLinkedData_Interface::GetEntryNr () const inherited
Definition at line 101 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetEntryNr(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairTestDetectorTimeRecoTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
GetFeID()
Int_t PixelDigi::GetFeID () inline
Definition at line 46 of file PixelDigi.h.
References fFeID.
Referenced by PixelDigitize::ActivatePixel(), FairMQPixelSamplerBin::ConditionalRun(), PixelFindHitsTask::Exec(), PixelDigiWriteToBinFile::Exec(), PixelDigiWriteToFile::Exec(), PixelAltDigiWriteToRootVector::Exec(), PixelFindHits::Exec(), and PixelAltFindHits::Exec().
GetIndex()
Int_t PixelDigi::GetIndex () inline
Definition at line 44 of file PixelDigi.h.
References fPointIndex.
Referenced by PixelFindHitsTask::Exec(), PixelFindHits::Exec(), and PixelAltFindHits::Exec().
GetLink()
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const inherited
returns the FairLink at the given position
Definition at line 91 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetLinks()
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const inherited
returns stored links as FairLinks
Definition at line 72 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetLinksWithType()
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const inherited
returns all FairLinks with the corresponding type
Definition at line 111 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetNLinks()
Int_t FairMultiLinkedData_Interface::GetNLinks () const inherited
returns the number of stored links
Definition at line 82 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
GetPointerToLinks()
FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairPrintFairLinks::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::GetSortedMCTracks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::PrintLinkInfo(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
GetRow()
Int_t PixelDigi::GetRow () inline
Definition at line 49 of file PixelDigi.h.
References fRow.
Referenced by PixelDigitize::ActivatePixel(), FairMQPixelSamplerBin::ConditionalRun(), PixelFindHitsTask::Exec(), PixelDigiWriteToBinFile::Exec(), PixelDigiWriteToFile::Exec(), PixelAltDigiWriteToRootVector::Exec(), PixelFindHits::Exec(), and PixelAltFindHits::Exec().
GetSortedMCTracks()
std::vector< FairLink > FairMultiLinkedData_Interface::GetSortedMCTracks () inherited
Definition at line 121 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::GetSortedMCTracks().
GetTimeStamp()
Double_t FairTimeStamp::GetTimeStamp () const inline inherited
Accessors
Definition at line 43 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by StopTime::Call(), TimeGap::Call(), FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), FairRingSorterTask::Exec(), FairTSBufferFunctional::GetData(), FairTimeStampPointDraw::GetValue(), FairTimeStamp::operator<(), FairWriteoutBuffer::PrintData(), FairWriteoutBuffer::PrintStartTimeMap(), FairTimeStamp::PrintTimeInfo(), and FairTestDetectorDigi::ToString().
GetTimeStampError()
Double_t FairTimeStamp::GetTimeStampError () const inline inherited
Definition at line 44 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and FairTimeStamp::PrintTimeInfo().
IsSortable()
virtual Bool_t FairTimeStamp::IsSortable () const inline virtual inherited
Definition at line 60 of file FairTimeStamp.h.
operator<()
virtual bool FairTimeStamp::operator< (const FairTimeStamp * rValue) const inline virtual inherited
Definition at line 71 of file FairTimeStamp.h.
References FairTimeStamp::GetTimeStamp().
PrintLinkInfo()
std::ostream& FairMultiLinkedData_Interface::PrintLinkInfo (std::ostream & out = std::cout) const inline inherited
Output.
Definition at line 66 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::PrintLinkInfo().
Referenced by FairTimeStamp::PrintTimeInfo().
PrintTimeInfo()
std::ostream & FairTimeStamp::PrintTimeInfo (std::ostream & out = std::cout) const virtual inherited
Definition at line 12 of file FairTimeStamp.cxx.
References FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), and FairMultiLinkedData_Interface::PrintLinkInfo().
ResetLinks()
void FairMultiLinkedData_Interface::ResetLinks () inherited
Definition at line 193 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
serialize()
template<class Archive > void FairTimeStamp::serialize (Archive & ar, const unsigned int) inline inherited
Definition at line 79 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp, and FairTimeStamp::fTimeStampError.
SetCharge()
void PixelDigi::SetCharge (Double_t ch) inline
Definition at line 40 of file PixelDigi.h.
References fCharge.
Referenced by PixelDigitize::ActivatePixel().
SetCol()
void PixelDigi::SetCol (Int_t col) inline
Definition at line 41 of file PixelDigi.h.
References fCol.
SetDetectorID()
void PixelDigi::SetDetectorID (Int_t det) inline
Definition at line 38 of file PixelDigi.h.
References fDetectorID.
SetEntryNr()
void FairMultiLinkedData_Interface::SetEntryNr (FairLink val) inherited
Definition at line 147 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetEntryNr().
Referenced by FairRingSorterTask::Exec(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetFeID()
void PixelDigi::SetFeID (Int_t fe) inline
Definition at line 39 of file PixelDigi.h.
References fFeID.
SetIndex()
void PixelDigi::SetIndex (Int_t in) inline
Definition at line 37 of file PixelDigi.h.
References fPointIndex.
SetInsertHistory()
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) inherited
Definition at line 186 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetLink()
void FairMultiLinkedData_Interface::SetLink (FairLink link) inherited
Sets the Links with a single FairLink.
Definition at line 139 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetector::AddHit(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
SetLinks()
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 131 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
SetPointerToLinks()
void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline inherited
Definition at line 55 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
SetRow()
void PixelDigi::SetRow (Int_t row) inline
Definition at line 42 of file PixelDigi.h.
References fRow.
SetTimeStamp()
void FairTimeStamp::SetTimeStamp (Double_t t) inline inherited
Modifiers
Definition at line 46 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStamp.
Referenced by FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and MyHit::MyHit().
SetTimeStampError()
void FairTimeStamp::SetTimeStampError (Double_t t) inline inherited
Definition at line 47 of file FairTimeStamp.h.
References FairTimeStamp::fTimeStampError.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorRecoTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), Ex1Processor::Exec(), Ex2Processor::Exec(), and MyHit::MyHit().
Member Data Documentation
fCharge
Double_t PixelDigi::fCharge private
Definition at line 55 of file PixelDigi.h.
Referenced by GetCharge(), and SetCharge().
fCol
Int_t PixelDigi::fCol private
Definition at line 56 of file PixelDigi.h.
Referenced by GetCol(), and SetCol().
fDetectorID
Int_t PixelDigi::fDetectorID private
Definition at line 53 of file PixelDigi.h.
Referenced by GetDetectorID(), and SetDetectorID().
fFeID
Int_t PixelDigi::fFeID private
Definition at line 54 of file PixelDigi.h.
Referenced by GetFeID(), and SetFeID().
fLink
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
fPointIndex
Int_t PixelDigi::fPointIndex private
Definition at line 49 of file PixelDigi.h.
Referenced by GetIndex(), and SetIndex().
fRow
Int_t PixelDigi::fRow private
Definition at line 57 of file PixelDigi.h.
Referenced by GetRow(), and SetRow().
fTimeStamp
Double_t FairTimeStamp::fTimeStamp protected inherited
Definition at line 89 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStamp(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStamp().
fTimeStampError
Double_t FairTimeStamp::fTimeStampError protected inherited
Time of digit or Hit [ns]
Definition at line 90 of file FairTimeStamp.h.
Referenced by FairTimeStamp::Compare(), FairTimeStamp::equal(), FairTimeStamp::GetTimeStampError(), FairTimeStamp::serialize(), and FairTimeStamp::SetTimeStampError().
The documentation for this class was generated from the following files:
PixelDigi.h
PixelDigi.cxx