FairRoot: FairSystemInfo Class Reference
FairSystemInfo Class Reference
#include <FairSystemInfo.h>
Public Member Functions
FairSystemInfo ()
virtual ~FairSystemInfo ()
Float_t GetMaxMemory ()
size_t GetCurrentMemory ()
Detailed Description
Definition at line 21 of file FairSystemInfo.h.
Constructor & Destructor Documentation
FairSystemInfo()
FairSystemInfo::FairSystemInfo () inline
Definition at line 24 of file FairSystemInfo.h.
~FairSystemInfo()
virtual FairSystemInfo::~FairSystemInfo () inline virtual
Definition at line 25 of file FairSystemInfo.h.
Member Function Documentation
GetCurrentMemory()
size_t FairSystemInfo::GetCurrentMemory ()
Returns the current resident set size (physical memory use) measured in bytes, or zero if the value cannot be determined on this OS.
Definition at line 51 of file FairSystemInfo.cxx.
Referenced by FairMonitor::StartMemoryMonitor(), and FairMonitor::StopMemoryMonitor().
GetMaxMemory()
Float_t FairSystemInfo::GetMaxMemory ()
Definition at line 32 of file FairSystemInfo.cxx.
Referenced by create_digis(), create_digis_mixed(), Create_Tutorial4_Geometry(), plots(), read_digis(), run_bg(), run_dAsciiSource(), run_dBinSource(), run_digi(), run_digi_timebased(), run_digiToAscii(), run_digiToBin(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_hits(), run_hits_sep(), run_rad(), run_reco(), run_reco_timebased(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tracks(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), run_tutorial2(), and run_tutorial4().
The documentation for this class was generated from the following files:
FairSystemInfo.h
FairSystemInfo.cxx