FairRoot: FairRootFileSink Class Reference
FairRootFileSink Class Reference
#include <FairRootFileSink.h>
Public Member Functions
FairRootFileSink (TFile *f, const char *Title="OutputRootFile")
FairRootFileSink (const TString *RootFileName, const char *Title="OutputRootFile")
FairRootFileSink (const TString RootFileName, const char *Title="OutputRootFile")
virtual ~FairRootFileSink ()
virtual Bool_t InitSink ()
virtual void Close ()
virtual void Reset ()
virtual Sink_Type GetSinkType ()
virtual void FillEventHeader (FairEventHeader *feh)
virtual TFile * OpenRootFile (TString fileName="")
TFile * GetRootFile ()
virtual TString GetFileName ()
virtual void SetOutTree (TTree *fTree)
TTree * GetOutTree ()
virtual void Fill ()
virtual Int_t Write (const char *name=0, Int_t option=0, Int_t bufsize=0)
virtual void RegisterImpl (const char *, const char *, void *)
virtual void RegisterAny (const char *brname, const std::type_info &oi, const std::type_info &pi, void *obj)
virtual void WriteFolder ()
virtual bool CreatePersistentBranchesAny ()
virtual void WriteObject (TObject *f, const char *, Int_t option=0)
virtual void WriteGeometry ()
void SetRunId (Int_t runId)
Int_t GetRunId () const
Protected Attributes
Int_t fRunId
TFolder * fOutFolder
std::map< std::string, std::unique_ptr< TypeAddressPair const > > fPersistentBranchesMap
Private Member Functions
FairRootFileSink (const FairRootFileSink &)
FairRootFileSink operator= (const FairRootFileSink &)
void TruncateBranchNames ()
void TruncateBranchNames (TBranch *b, TString ffn)
Private Attributes
TString fOutputTitle
TFile * fRootFile
TTree * fOutTree
TObjArray * fListFolder
TFolder * fCbmout
Bool_t fIsInitialized
FairFileHeader * fFileHeader
Detailed Description
Definition at line 31 of file FairRootFileSink.h.
Constructor & Destructor Documentation
FairRootFileSink() [1/4]
FairRootFileSink::FairRootFileSink (TFile * f, const char * Title = "OutputRootFile")
Definition at line 41 of file FairRootFileSink.cxx.
References DEBUG, FATAL, and fRootFile.
FairRootFileSink() [2/4]
FairRootFileSink::FairRootFileSink (const TString * RootFileName, const char * Title = "OutputRootFile")
Definition at line 59 of file FairRootFileSink.cxx.
References DEBUG, FATAL, and fRootFile.
FairRootFileSink() [3/4]
FairRootFileSink::FairRootFileSink (const TString RootFileName, const char * Title = "OutputRootFile")
Definition at line 78 of file FairRootFileSink.cxx.
References DEBUG, FATAL, and fRootFile.
~FairRootFileSink()
FairRootFileSink::~FairRootFileSink () virtual
Definition at line 97 of file FairRootFileSink.cxx.
FairRootFileSink() [4/4]
FairRootFileSink::FairRootFileSink (const FairRootFileSink &) private
Member Function Documentation
Close()
void FairRootFileSink::Close () virtual
Implements FairSink.
Definition at line 243 of file FairRootFileSink.cxx.
References fRootFile.
CreatePersistentBranchesAny()
bool FairRootFileSink::CreatePersistentBranchesAny () virtual
Implements FairSink.
Definition at line 313 of file FairRootFileSink.cxx.
References impl::demangle(), FATAL, fOutTree, FairSink::fPersistentBranchesMap, and INFO.
Referenced by WriteFolder().
Fill()
void FairRootFileSink::Fill () virtual
Implements FairSink.
Definition at line 359 of file FairRootFileSink.cxx.
References fOutTree, and INFO.
FillEventHeader()
void FairRootFileSink::FillEventHeader (FairEventHeader * feh) virtual
Definition at line 259 of file FairRootFileSink.cxx.
GetFileName()
virtual TString FairRootFileSink::GetFileName () inline virtual
Reimplemented from FairSink.
Definition at line 50 of file FairRootFileSink.h.
References fRootFile.
GetOutTree()
TTree* FairRootFileSink::GetOutTree () inline
Definition at line 53 of file FairRootFileSink.h.
References fOutTree.
Referenced by FairRootManager::GetOutTree().
GetRootFile()
TFile* FairRootFileSink::GetRootFile () inline
Definition at line 49 of file FairRootFileSink.h.
References fRootFile.
Referenced by FairRootManager::GetOutFile(), and FairRun::GetOutputFile().
GetRunId()
Int_t FairSink::GetRunId () const inline inherited
Definition at line 40 of file FairSink.h.
References FairSink::fRunId.
GetSinkType()
virtual Sink_Type FairRootFileSink::GetSinkType () inline virtual
Implements FairSink.
Definition at line 44 of file FairRootFileSink.h.
References kFILESINK.
InitSink()
Bool_t FairRootFileSink::InitSink () virtual
Check if a simulation run!
Implements FairSink.
Definition at line 110 of file FairRootFileSink.cxx.
References fIsInitialized, FairSink::fOutFolder, fRootFile, FairRootManager::GetFolderName(), and INFO.
OpenRootFile()
TFile * FairRootFileSink::OpenRootFile (TString fileName = "") virtual
Definition at line 103 of file FairRootFileSink.cxx.
operator=()
FairRootFileSink FairRootFileSink::operator= (const FairRootFileSink &) private
RegisterAny()
void FairRootFileSink::RegisterAny (const char * brname, const std::type_info & oi, const std::type_info & pi, void * obj) virtual
Implements FairSink.
Definition at line 281 of file FairRootFileSink.cxx.
References FairSink::fPersistentBranchesMap.
RegisterImpl()
void FairRootFileSink::RegisterImpl (const char * name, const char * folderName, void * obj) virtual
Implements FairSink.
Definition at line 266 of file FairRootFileSink.cxx.
References FairSink::fOutFolder.
Reset()
void FairRootFileSink::Reset () virtual
Implements FairSink.
Definition at line 253 of file FairRootFileSink.cxx.
SetOutTree()
virtual void FairRootFileSink::SetOutTree (TTree * fTree) inline virtual
Implements FairSink.
Definition at line 52 of file FairRootFileSink.h.
References fOutTree.
SetRunId()
void FairSink::SetRunId (Int_t runId) inline inherited
Definition at line 39 of file FairSink.h.
References FairSink::fRunId.
TruncateBranchNames() [1/2]
void FairRootFileSink::TruncateBranchNames () private
If a object is created in a folder the corresponding branch in the tree is crated with a wrong name. The name of the branch is created as follows mainFolder.subFolder.nameOfStoredObject e.g. cbmroot.Event.ExampleClass. The name which is wanted is only nameOfStoredObject e.g. ExampleClass. This is corrected in this function If the folder does not exist don't do anything
correct branch names in all folders below the main output folder
Create TString with the part of the branch name which should be removed. This is mainFolderName.folderName. e.g. cbmroot.Event. This part of the branch name is obsolete, so it is removed from the branch name.
Correct name of all branches and leaves which correspond to the subfolder. To do so loop over all branches and check if the branch corresponds with the folder. If it corresponds correct the branch names of all sub branches. Only correct branch names for up to now uncorrected branches.
Definition at line 134 of file FairRootFileSink.cxx.
References FairSink::fOutFolder, and fOutTree.
Referenced by TruncateBranchNames(), and WriteFolder().
TruncateBranchNames() [2/2]
void FairRootFileSink::TruncateBranchNames (TBranch * b, TString ffn) private
Get the branch name from the branch object, remove common and wrong part of the name and and set branch name to the new corrected name. This has to be done recursivly for all subbranches/leaves Remove wrong part of branch name
Definition at line 215 of file FairRootFileSink.cxx.
References DEBUG, and TruncateBranchNames().
Write()
Int_t FairRootFileSink::Write (const char * name = 0, Int_t option = 0, Int_t bufsize = 0) virtual
Writes the tree in the file.
Get the file handle to the current output file from the tree. If ROOT splits the file (due to the size of the file) the file handle fOutFile is lost and the program crash while writing the last part of the last file.
Implements FairSink.
Definition at line 369 of file FairRootFileSink.cxx.
References DEBUG, fOutTree, fRootFile, and INFO.
WriteFolder()
void FairRootFileSink::WriteFolder () virtual
Implements FairSink.
Definition at line 287 of file FairRootFileSink.cxx.
References CreatePersistentBranchesAny(), FairSink::fOutFolder, fOutTree, fRootFile, FairRootManager::GetFolderName(), FairRootManager::GetTreeName(), and TruncateBranchNames().
WriteGeometry()
void FairRootFileSink::WriteGeometry () virtual
Implements FairSink.
Definition at line 352 of file FairRootFileSink.cxx.
References fRootFile.
WriteObject()
void FairRootFileSink::WriteObject (TObject * f, const char * name, Int_t option = 0) virtual
Implements FairSink.
Definition at line 345 of file FairRootFileSink.cxx.
References fRootFile.
Member Data Documentation
fCbmout
TFolder* FairRootFileSink::fCbmout private
folder structure of output
Definition at line 79 of file FairRootFileSink.h.
fFileHeader
FairFileHeader* FairRootFileSink::fFileHeader private
File Header
Definition at line 91 of file FairRootFileSink.h.
fIsInitialized
Bool_t FairRootFileSink::fIsInitialized private
Initialization flag, true if initialized
Definition at line 81 of file FairRootFileSink.h.
Referenced by InitSink().
fListFolder
TObjArray* FairRootFileSink::fListFolder private
list of folders from all input (and friends) files
Definition at line 77 of file FairRootFileSink.h.
fOutFolder
TFolder* FairSink::fOutFolder protected inherited
folder structure of output
Definition at line 68 of file FairSink.h.
Referenced by InitSink(), RegisterImpl(), TruncateBranchNames(), and WriteFolder().
fOutputTitle
TString FairRootFileSink::fOutputTitle private
Title of input sink, could be input, background or signal
Definition at line 71 of file FairRootFileSink.h.
fOutTree
TTree* FairRootFileSink::fOutTree private
Output Tree
Definition at line 75 of file FairRootFileSink.h.
Referenced by CreatePersistentBranchesAny(), Fill(), GetOutTree(), SetOutTree(), TruncateBranchNames(), Write(), and WriteFolder().
fPersistentBranchesMap
std::map<std::string, std::unique_ptr<TypeAddressPair const> > FairSink::fPersistentBranchesMap protected inherited
A map of branchnames to typeinformation + memory address; used for branches registered to bes stored; use of ptr here since type_info cannot be copied
Definition at line 72 of file FairSink.h.
Referenced by CreatePersistentBranchesAny(), and RegisterAny().
fRootFile
TFile* FairRootFileSink::fRootFile private
ROOT file
Definition at line 73 of file FairRootFileSink.h.
Referenced by Close(), FairRootFileSink(), GetFileName(), GetRootFile(), InitSink(), Write(), WriteFolder(), WriteGeometry(), and WriteObject().
fRunId
Int_t FairSink::fRunId protected inherited
Definition at line 65 of file FairSink.h.
Referenced by FairSink::GetRunId(), and FairSink::SetRunId().
The documentation for this class was generated from the following files:
FairRootFileSink.h
FairRootFileSink.cxx