FairRroot: PndMCTrackEnumAssociator Class Reference
PndMCTrackEnumAssociator Class Reference
#include <FairMCTrackEnumAssociator.h>
Public Member Functions
PndMCTrackEnumAssociator (const char *name, const char *title="PND Task")
PndMCTrackEnumAssociator ()
virtual ~PndMCTrackEnumAssociator ()
virtual InitStatus Init ()
virtual void Exec (Option_t *option)
void Register ()
Int_t GetMvdHitPixels (Int_t index)
Int_t GetMvdHitStrips (Int_t index)
Int_t GetSttHits (Int_t index)
Int_t GetGemHits (Int_t index)
Int_t GetFtsHits (Int_t index)
void SetTrackInBranchName (const TString &name)
void SetTrackOutBranchName (const TString &name)
void SetOption (Option_t *option=" ")
void SetVerbose (Bool_t verb)
void SetPersistence (Bool_t pers)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
TString fTrackInBranchName
TString fTrackOutBranchName
Name of the input TCA.
TClonesArray * fTpcInput
Name of the output TCA.
TClonesArray * fSttHitInput
pointers to TPC TCA
TClonesArray * fMvdMCArray
pointers to STT Hit TCA
TClonesArray * fMvdStripHitArray
TClonesArray * fMvdPixelHitArray
TClonesArray * fMvdStripClusterArray
TClonesArray * fMvdPixelClusterArray
TClonesArray * fMvdStripDigiArray
TClonesArray * fMvdPixelDigiArray
TClonesArray * fGemMCArray
TClonesArray * fGemInput
pointers to GEMPoint TCA
TClonesArray * fFtsMCArray
pointers to GEMHit TCA
TClonesArray * fFtsInput
pointers to FtsPoint TCA
TClonesArray * fTrackIDArray
pointers to FtsHit TCA
TClonesArray * fTrackArray
pointers to PndTrackID (output)
Bool_t fVerbose
pointers to PndTrack (input)
Bool_t fPersistence
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Detailed Description
Definition at line 28 of file FairMCTrackEnumAssociator.h.
Constructor & Destructor Documentation
PndMCTrackEnumAssociator::PndMCTrackEnumAssociator (const char * name, const char * title = "PND Task")
PndMCTrackEnumAssociator::PndMCTrackEnumAssociator ()
virtual PndMCTrackEnumAssociator::~PndMCTrackEnumAssociator () virtual
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
virtual void PndMCTrackEnumAssociator::Exec (Option_t * option) virtual
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), LOG, FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), LOG, FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
virtual void FairTask::Finish () inline protected virtual inherited
Action at end of run. For this task and all of the subtasks. To be implemented in the derived class.
Reimplemented in PixelAltFindHits, FairEventBuilderManager, PixelFindHits, PixelFitTracks, PixelDigitize, PixelFindTracks, PixelAltDigiWriteToRootVector, FairBoxSetDraw, PixelDigiWriteToBinFile, PixelDigiWriteToFile, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet4PointDraw, FairPrintFairLinks, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 132 of file FairTask.h.
Referenced by FairTask::FinishTask().
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
Int_t PndMCTrackEnumAssociator::GetFtsHits (Int_t index)
Int_t PndMCTrackEnumAssociator::GetGemHits (Int_t index)
Int_t PndMCTrackEnumAssociator::GetMvdHitPixels (Int_t index)
Int_t PndMCTrackEnumAssociator::GetMvdHitStrips (Int_t index)
Int_t PndMCTrackEnumAssociator::GetSttHits (Int_t index)
virtual InitStatus PndMCTrackEnumAssociator::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, LOG, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
void PndMCTrackEnumAssociator::Register ()
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, PixelAltFindHits, PixelFindHits, PixelFitTracks, FairRingSorterTask, PixelDigitize, PixelFindTracks, PixelAltDigiWriteToRootVector, PixelDigiWriteToBinFile, PixelDigiWriteToFile, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 120 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, LOG, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
void PndMCTrackEnumAssociator::SetOption (Option_t * option = " ") inline
Definition at line 52 of file FairMCTrackEnumAssociator.h.
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
virtual void FairTask::SetParContainers () inline protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented in FairRingSorterTask, FairEventBuilderManager, PixelAltFindHits, FairBoxSetDraw, PixelFindHits, PixelFitTracks, PixelDigitize, PixelFindTracks, PixelAltDigiWriteToRootVector, PixelDigiWriteToBinFile, PixelDigiWriteToFile, FairPointSetDraw, FairMCStack, FairMCTracks, FairTutorialDet4HitProducerIdealMisalign, FairMCMatchSelectorTask, FairTutorialDet4PointDraw, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairMCMatchLoaderTask, FairTutorialDet4StraightLineFitter, NewTask, FairPrintFairLinks, and FairTestDetectorHitProducerSmearing.
Definition at line 126 of file FairTask.h.
Referenced by FairTask::SetParTask().
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
void PndMCTrackEnumAssociator::SetPersistence (Bool_t pers) inline
Definition at line 55 of file FairMCTrackEnumAssociator.h.
References fPersistence.
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
void PndMCTrackEnumAssociator::SetTrackInBranchName (const TString & name) inline
Definition at line 49 of file FairMCTrackEnumAssociator.h.
References fTrackInBranchName.
void PndMCTrackEnumAssociator::SetTrackOutBranchName (const TString & name) inline
Definition at line 50 of file FairMCTrackEnumAssociator.h.
References fTrackOutBranchName.
void PndMCTrackEnumAssociator::SetVerbose (Bool_t verb) inline
Definition at line 54 of file FairMCTrackEnumAssociator.h.
References fVerbose.
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
TClonesArray* PndMCTrackEnumAssociator::fFtsInput protected
pointers to FtsPoint TCA
Definition at line 74 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fFtsMCArray protected
pointers to GEMHit TCA
Definition at line 73 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fGemInput protected
pointers to GEMPoint TCA
Definition at line 72 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fGemMCArray protected
Definition at line 71 of file FairMCTrackEnumAssociator.h.
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
TClonesArray* PndMCTrackEnumAssociator::fMvdMCArray protected
pointers to STT Hit TCA
Definition at line 64 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fMvdPixelClusterArray protected
Definition at line 68 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fMvdPixelDigiArray protected
Definition at line 70 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fMvdPixelHitArray protected
Definition at line 66 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fMvdStripClusterArray protected
Definition at line 67 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fMvdStripDigiArray protected
Definition at line 69 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fMvdStripHitArray protected
Definition at line 65 of file FairMCTrackEnumAssociator.h.
Bool_t PndMCTrackEnumAssociator::fPersistence protected
Definition at line 80 of file FairMCTrackEnumAssociator.h.
Referenced by SetPersistence().
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
TClonesArray* PndMCTrackEnumAssociator::fSttHitInput protected
pointers to TPC TCA
Definition at line 63 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fTpcInput protected
Name of the output TCA.
Definition at line 62 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fTrackArray protected
pointers to PndTrackID (output)
Definition at line 77 of file FairMCTrackEnumAssociator.h.
TClonesArray* PndMCTrackEnumAssociator::fTrackIDArray protected
pointers to FtsHit TCA
Definition at line 76 of file FairMCTrackEnumAssociator.h.
TString PndMCTrackEnumAssociator::fTrackInBranchName protected
Definition at line 55 of file FairMCTrackEnumAssociator.h.
Referenced by SetTrackInBranchName().
TString PndMCTrackEnumAssociator::fTrackOutBranchName protected
Name of the input TCA.
Definition at line 60 of file FairMCTrackEnumAssociator.h.
Referenced by SetTrackOutBranchName().
Bool_t PndMCTrackEnumAssociator::fVerbose protected
pointers to PndTrack (input)
Definition at line 79 of file FairMCTrackEnumAssociator.h.
Referenced by SetVerbose().
The documentation for this class was generated from the following file:
FairMCTrackEnumAssociator.h