FairRoot: FairSource Class Reference
FairSource Class Reference abstract
#include <FairSource.h>
Public Member Functions
FairSource ()
FairSource (const FairSource &source)
virtual ~FairSource ()
virtual Bool_t Init ()=0
virtual Int_t ReadEvent (UInt_t=0)=0
virtual void Close ()=0
virtual void Reset ()=0
virtual Bool_t ActivateObject (TObject **, const char *)
virtual Bool_t ActivateObjectAny (void **, const std::type_info &, const char *)
virtual Source_Type GetSourceType ()=0
virtual void SetParUnpackers ()=0
virtual Bool_t InitUnpackers ()=0
virtual Bool_t ReInitUnpackers ()=0
virtual Int_t CheckMaxEventNo (Int_t=0)
virtual void ReadBranchEvent (const char *)
virtual void ReadBranchEvent (const char *, Int_t)
virtual void FillEventHeader (FairEventHeader *feh)
void SetRunId (Int_t runId)
Int_t GetRunId () const
Protected Attributes
Int_t fRunId
Detailed Description
Definition at line 26 of file FairSource.h.
Constructor & Destructor Documentation
FairSource() [1/2]
FairSource::FairSource ()
Definition at line 21 of file FairSource.cxx.
FairSource() [2/2]
FairSource::FairSource (const FairSource & source)
Definition at line 28 of file FairSource.cxx.
~FairSource()
FairSource::~FairSource () virtual
Definition at line 35 of file FairSource.cxx.
Member Function Documentation
ActivateObject()
virtual Bool_t FairSource::ActivateObject (TObject ** , const char *) inline virtual
Reimplemented in FairFileSource, FairMixedSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 39 of file FairSource.h.
Referenced by FairRootManager::ActivateBranch(), FairMQPixelSampler::InitTask(), and FairRootManager::UpdateBranches().
ActivateObjectAny()
virtual Bool_t FairSource::ActivateObjectAny (void ** , const std::type_info & , const char *) inline virtual
Reimplemented in FairFileSource.
Definition at line 40 of file FairSource.h.
Referenced by FairRootManager::InitObjectAs().
CheckMaxEventNo()
virtual Int_t FairSource::CheckMaxEventNo (Int_t = 0) inline virtual
Check the maximum event number we can run to
Reimplemented in FairMixedSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 51 of file FairSource.h.
Referenced by FairRootManager::CheckMaxEventNo(), and FairMQPixelSampler::InitTask().
Close()
virtual void FairSource::Close () pure virtual
Implemented in FairLmdSource, FairMixedSource, FairFileSource, PixelDigiBinSource, PixelDigiSource, FairOnlineSource, FairMbsSource, FairMbsStreamSource, and FairRemoteSource.
Referenced by FairRunOnline::Finish().
FillEventHeader()
void FairSource::FillEventHeader (FairEventHeader * feh) virtual
Reimplemented in FairMixedSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 39 of file FairSource.cxx.
References fRunId, and FairEventHeader::SetRunId().
Referenced by FairRootManager::FillEventHeader(), FairRootManager::GetRunId(), FairRootManager::ReadBranchEvent(), FairRootManager::ReadEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
GetRunId()
Int_t FairSource::GetRunId () const inline
Definition at line 58 of file FairSource.h.
References fRunId.
GetSourceType()
virtual Source_Type FairSource::GetSourceType () pure virtual
Implemented in FairMixedSource, FairOnlineSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Referenced by FairRunOnline::Init().
Init()
virtual Bool_t FairSource::Init () pure virtual
Implemented in FairLmdSource, FairMixedSource, FairFileSource, PixelDigiBinSource, PixelDigiSource, FairOnlineSource, FairMbsSource, FairMbsStreamSource, and FairRemoteSource.
Referenced by FairRootManager::InitSource(), and FairMQPixelSampler::InitTask().
InitUnpackers()
virtual Bool_t FairSource::InitUnpackers () pure virtual
Implemented in FairMixedSource, FairFileSource, PixelDigiBinSource, PixelDigiSource, and FairOnlineSource.
Referenced by FairRunOnline::Init().
ReadBranchEvent() [1/2]
virtual void FairSource::ReadBranchEvent (const char *) inline virtual
Read the tree entry on one branch
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 53 of file FairSource.h.
Referenced by FairRootManager::ReadBranchEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
ReadBranchEvent() [2/2]
virtual void FairSource::ReadBranchEvent (const char * , Int_t) inline virtual
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 54 of file FairSource.h.
ReadEvent()
virtual Int_t FairSource::ReadEvent (UInt_t = 0) pure virtual
Implemented in FairLmdSource, FairMixedSource, FairFileSource, PixelDigiBinSource, PixelDigiSource, FairOnlineSource, FairMbsSource, FairMbsStreamSource, and FairRemoteSource.
Referenced by FairMQPixelSampler::ConditionalRun(), and FairRootManager::ReadEvent().
ReInitUnpackers()
virtual Bool_t FairSource::ReInitUnpackers () pure virtual
Implemented in FairMixedSource, FairFileSource, PixelDigiBinSource, PixelDigiSource, and FairOnlineSource.
Referenced by FairRunOnline::EventLoop().
Reset()
virtual void FairSource::Reset () pure virtual
Implemented in FairMixedSource, FairOnlineSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Referenced by FairRootManager::ReadBranchEvent(), and FairRootManager::ReadEvent().
SetParUnpackers()
virtual void FairSource::SetParUnpackers () pure virtual
Implemented in FairMixedSource, FairFileSource, PixelDigiBinSource, PixelDigiSource, and FairOnlineSource.
Referenced by FairRunOnline::Init().
SetRunId()
void FairSource::SetRunId (Int_t runId) inline
Definition at line 57 of file FairSource.h.
References fRunId.
Referenced by FairRunOnline::Init().
Member Data Documentation
fRunId
Int_t FairSource::fRunId protected
Definition at line 61 of file FairSource.h.
Referenced by FillEventHeader(), GetRunId(), and SetRunId().
The documentation for this class was generated from the following files:
FairSource.h
FairSource.cxx