FairRoot: FairField Class Reference
FairField Class Reference
#include <FairField.h>
Public Member Functions
FairField ()
FairField (const char *name, const char *title="FAIR Magnetic Field")
FairField & operator= (const FairField &)
virtual ~FairField ()
virtual void Init ()
Bool_t IsConst ()
Bool_t IsMap ()
Int_t GetType () const
virtual Double_t GetBx (Double_t, Double_t, Double_t)
virtual Double_t GetBy (Double_t, Double_t, Double_t)
virtual Double_t GetBz (Double_t, Double_t, Double_t)
virtual void GetFieldValue (const Double_t point[3], Double_t *bField)
void Field (const Double_t point[3], Double_t *B)
virtual void Print (Option_t *) const
virtual void GetBxyz (const Double_t[3], Double_t *)
virtual void FillParContainer ()
Protected Attributes
Int_t fType
Private Member Functions
FairField (const FairField &)
ClassDef (FairField, 4)
Detailed Description
FairField.h
Author
M.Al-Turany <m.al/turany.de>
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e
Since
06.01.2004 .0
Abstract base class for magnetic fields in FAIR Concrete field should implement the pure virtual methods GetBx, GetBy and GetBz and/or GetBxyz
Note: Field values should be returned in kG (thanks to GEANT3)
Definition at line 42 of file FairField.h.
Constructor & Destructor Documentation
FairField() [1/3]
FairField::FairField ()
Default constructor
Definition at line 17 of file FairField.cxx.
FairField() [2/3]
FairField::FairField (const char * name, const char * title = "FAIR Magnetic Field")
Constructor with name and title
Definition at line 27 of file FairField.cxx.
~FairField()
FairField::~FairField () virtual
Destructor
Definition at line 38 of file FairField.cxx.
FairField() [3/3]
FairField::FairField (const FairField &) private
Member Function Documentation
ClassDef()
FairField::ClassDef (FairField , 4) private
Field()
void FairField::Field (const Double_t point[3], Double_t * B) inline
Definition at line 101 of file FairField.h.
References GetFieldValue().
FillParContainer()
virtual void FairField::FillParContainer () inline virtual
Fill Paramater
Reimplemented in FairConstField.
Definition at line 112 of file FairField.h.
Referenced by FairRunOnline::Init(), and FairRunSim::SetFieldContainer().
GetBx()
virtual Double_t FairField::GetBx (Double_t , Double_t , Double_t) inline virtual
Get x component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Reimplemented in MyConstField, and FairConstField.
Definition at line 80 of file FairField.h.
Referenced by GetFieldValue().
GetBxyz()
virtual void FairField::GetBxyz (const Double_t [3], Double_t *) inline virtual
Definition at line 106 of file FairField.h.
GetBy()
virtual Double_t FairField::GetBy (Double_t , Double_t , Double_t) inline virtual
Get y component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Reimplemented in MyConstField, and FairConstField.
Definition at line 86 of file FairField.h.
Referenced by GetFieldValue().
GetBz()
virtual Double_t FairField::GetBz (Double_t , Double_t , Double_t) inline virtual
Get z component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Reimplemented in MyConstField, and FairConstField.
Definition at line 91 of file FairField.h.
Referenced by GetFieldValue().
GetFieldValue()
void FairField::GetFieldValue (const Double_t point[3], Double_t * bField) virtual
Get magnetic field. For use of GEANT3
Parameters
point Coordinates [cm]
bField (return) Field components [kG]
Definition at line 60 of file FairField.cxx.
References GetBx(), GetBy(), and GetBz().
Referenced by Field(), FairTrackPar::GetFieldValue(), and FairRKPropagator::OneStepRungeKutta().
GetType()
Int_t FairField::GetType () const inline
Field type (0=constant, 1=map, 2=map sym2, 3 = map sym3)
Definition at line 74 of file FairField.h.
References fType.
Referenced by FairConstPar::SetParameters(), and MyFieldPar::SetParameters().
Init()
virtual void FairField::Init () inline virtual
Intialisation. E.g. read in the field map. If needed, to be implemented in the concrete class.
Definition at line 63 of file FairField.h.
Referenced by MyFieldCreator::createFairField(), FairRunOnline::Init(), and FairRunSim::Init().
IsConst()
Bool_t FairField::IsConst ()
Test whether field type is Constant
Definition at line 44 of file FairField.cxx.
References fType.
IsMap()
Bool_t FairField::IsMap ()
Test whether field typ is Map
Definition at line 54 of file FairField.cxx.
References fType.
operator=()
FairField& FairField::operator= (const FairField &) inline
Definition at line 54 of file FairField.h.
Print()
virtual void FairField::Print (Option_t *) const inline virtual
Screen output. To be implemented in the concrete class.
Reimplemented in FairConstField.
Definition at line 105 of file FairField.h.
Referenced by MyFieldCreator::createFairField(), and FairGeane::Init().
Member Data Documentation
fType
Int_t FairField::fType protected
Field type. 1 = constant field, 2 = field map.
Definition at line 116 of file FairField.h.
Referenced by FairConstField::FairConstField(), GetType(), IsConst(), IsMap(), and MyConstField::MyConstField().
The documentation for this class was generated from the following files:
FairField.h
FairField.cxx