FairRroot: fair::Logger Class Reference
fair::Logger Class Reference
#include <Logger.h>
Public Member Functions
Logger (Severity severity, const std::string &file, const std::string &line, const std::string &func)
Logger & Log ()
template<typename T >
Logger & operator<< (const T &t)
Logger & operator<< (const char *cptr)
Logger & operator<< (char *cptr)
Logger & operator<< (std::ios_base &(*manip)(std::ios_base &))
Logger & operator<< (std::ostream &(*manip)(std::ostream &))
virtual ~Logger () noexcept(false)
Static Public Member Functions
static void SetConsoleSeverity (const Severity severity)
static void SetConsoleSeverity (const std::string &severityStr)
static void SetFileSeverity (const Severity severity)
static void SetFileSeverity (const std::string &severityStr)
static void SetCustomSeverity (const std::string &key, const Severity severity)
static void SetCustomSeverity (const std::string &key, const std::string &severityStr)
static bool Logging (const Severity severity)
static void SetVerbosity (const Verbosity verbosity)
static void SetVerbosity (const std::string &verbosityStr)
static void SetConsoleColor (const bool colored=true)
static void InitFileSink (const Severity severity, const std::string &filename, bool customizeName=true)
static void InitFileSink (const std::string &severityStr, const std::string &filename, bool customizeName=true)
static void RemoveFileSink ()
static std::string SeverityName (Severity)
static std::string VerbosityName (Verbosity)
static void OnFatal (std::function< void()> func)
static void AddCustomSink (const std::string &key, Severity severity, std::function< void(const std::string &content, const LogMetaData &metadata)> sink)
static void AddCustomSink (const std::string &key, const std::string &severityStr, std::function< void(const std::string &content, const LogMetaData &metadata)> sink)
static void RemoveCustomSink (const std::string &key)
Static Public Attributes
static const std::unordered_map< std::string, Verbosity > fVerbosityMap
static const std::unordered_map< std::string, Severity > fSeverityMap
static const std::array< std::string, 12 > fSeverityNames
static const std::array< std::string, 4 > fVerbosityNames
Private Member Functions
bool LoggingToConsole () const
bool LoggingToFile () const
bool LoggingCustom (const Severity) const
Static Private Member Functions
static void UpdateMinSeverity ()
Private Attributes
LogMetaData fMetaData
std::ostringstream fContent
std::ostringstream fColorOut
std::ostringstream fBWOut
Static Private Attributes
static const std::string fProcessName = "?"
static bool fColored = false
static std::fstream fFileStream
static Severity fConsoleSeverity = Severity::info
static Severity fFileSeverity = Severity::nolog
static Severity fMinSeverity = Severity::info
static Verbosity fVerbosity = Verbosity::low
static std::function< void()> fFatalCallback
static std::unordered_map< std::string, std::pair< Severity, std::function< void(const std::string &content, const LogMetaData &metadata)> > > fCustomSinks
static std::mutex fMtx
Detailed Description
Definition at line 112 of file Logger.h.
Constructor & Destructor Documentation
fair::Logger::Logger (Severity severity, const std::string & file, const std::string & line, const std::string & func)
Definition at line 222 of file Logger.cxx.
fair::Logger::~Logger () virtual noexcept
Definition at line 540 of file Logger.cxx.
Member Function Documentation
static void fair::Logger::AddCustomSink (const std::string & key, Severity severity, std::function< void(const std::string &content, const LogMetaData &metadata)> sink) static
static void fair::Logger::AddCustomSink (const std::string & key, const std::string & severityStr, std::function< void(const std::string &content, const LogMetaData &metadata)> sink) static
static void fair::Logger::InitFileSink (const Severity severity, const std::string & filename, bool customizeName = true) static
Referenced by FairLogger::OpenLogFile(), and FairMQProgOptions::ParseAll().
static void fair::Logger::InitFileSink (const std::string & severityStr, const std::string & filename, bool customizeName = true) static
Logger & fair::Logger::Log ()
Definition at line 473 of file Logger.cxx.
References fair::endColor(), and fair::startColor().
bool fair::Logger::Logging (const Severity severity) static
Definition at line 307 of file Logger.cxx.
Referenced by FairLogger::IsLogNeeded(), and main().
bool fair::Logger::LoggingCustom (const Severity severity) const private
Definition at line 421 of file Logger.cxx.
bool fair::Logger::LoggingToConsole () const private
Definition at line 407 of file Logger.cxx.
bool fair::Logger::LoggingToFile () const private
Definition at line 414 of file Logger.cxx.
void fair::Logger::OnFatal (std::function< void()> func) static
Definition at line 428 of file Logger.cxx.
Referenced by FairLogger::FairLogger().
template<typename T > Logger& fair::Logger::operator<< (const T & t) inline
Definition at line 150 of file Logger.h.
References fContent.
Logger& fair::Logger::operator<< (const char * cptr) inline
Definition at line 157 of file Logger.h.
References fContent.
Logger& fair::Logger::operator<< (char * cptr) inline
Definition at line 166 of file Logger.h.
References fContent.
Logger& fair::Logger::operator<< (std::ios_base &(*)(std::ios_base &) manip)
Logger& fair::Logger::operator<< (std::ostream &(*)(std::ostream &) manip)
void fair::Logger::RemoveCustomSink (const std::string & key) static
Definition at line 460 of file Logger.cxx.
void fair::Logger::RemoveFileSink () static
Definition at line 398 of file Logger.cxx.
Referenced by FairLogger::CloseLogFile().
void fair::Logger::SetConsoleColor (const bool colored = true) static
Definition at line 341 of file Logger.cxx.
Referenced by FairMQProgOptions::ParseAll(), and FairLogger::SetColoredLog().
void fair::Logger::SetConsoleSeverity (const Severity severity) static
Definition at line 237 of file Logger.cxx.
Referenced by FairMQProgOptions::ParseAll(), FairLogger::SetLogScreenLevel(), and FairLogger::SetLogToScreen().
static void fair::Logger::SetConsoleSeverity (const std::string & severityStr) static
static void fair::Logger::SetCustomSeverity (const std::string & key, const Severity severity) static
static void fair::Logger::SetCustomSeverity (const std::string & key, const std::string & severityStr) static
void fair::Logger::SetFileSeverity (const Severity severity) static
Definition at line 256 of file Logger.cxx.
Referenced by FairLogger::SetLogFileLevel(), and FairLogger::SetLogToFile().
static void fair::Logger::SetFileSeverity (const std::string & severityStr) static
void fair::Logger::SetVerbosity (const Verbosity verbosity) static
Definition at line 323 of file Logger.cxx.
Referenced by FairMQProgOptions::ParseAll(), and FairLogger::SetLogVerbosityLevel().
static void fair::Logger::SetVerbosity (const std::string & verbosityStr) static
string fair::Logger::SeverityName (Severity severity) static
Definition at line 212 of file Logger.cxx.
void fair::Logger::UpdateMinSeverity () static private
Definition at line 294 of file Logger.cxx.
string fair::Logger::VerbosityName (Verbosity verbosity) static
Definition at line 217 of file Logger.cxx.
Member Data Documentation
std::ostringstream fair::Logger::fBWOut private
Definition at line 189 of file Logger.h.
bool fair::Logger::fColored = false static private
Definition at line 191 of file Logger.h.
std::ostringstream fair::Logger::fColorOut private
Definition at line 188 of file Logger.h.
Severity fair::Logger::fConsoleSeverity = Severity::info static private
Definition at line 194 of file Logger.h.
std::ostringstream fair::Logger::fContent private
Definition at line 187 of file Logger.h.
Referenced by operator<<().
unordered_map< string, pair< Severity, function< void(const string &content, const LogMetaData &metadata)> > > fair::Logger::fCustomSinks static private
Definition at line 201 of file Logger.h.
function< void()> fair::Logger::fFatalCallback static private
Definition at line 200 of file Logger.h.
Severity fair::Logger::fFileSeverity = Severity::nolog static private
Definition at line 195 of file Logger.h.
fstream fair::Logger::fFileStream static private
Definition at line 192 of file Logger.h.
LogMetaData fair::Logger::fMetaData private
Definition at line 185 of file Logger.h.
Severity fair::Logger::fMinSeverity = Severity::info static private
Definition at line 196 of file Logger.h.
mutex fair::Logger::fMtx static private
Definition at line 202 of file Logger.h.
const string fair::Logger::fProcessName = "?" static private
Definition at line 190 of file Logger.h.
const unordered_map< string, Severity > fair::Logger::fSeverityMap static
Initial value:
=
{
    { "nolog",   Severity::nolog   },
    { "NOLOG",   Severity::nolog   },
    { "error",   Severity::error   },
    { "ERROR",   Severity::error   },
    { "warn",    Severity::warn    },
    { "WARN",    Severity::warn    },
    { "warning", Severity::warning },
    { "WARNING", Severity::warning },
    { "state",   Severity::state   },
    { "STATE",   Severity::state   },
    { "info",    Severity::info    },
    { "INFO",    Severity::info    },
    { "debug",   Severity::debug   },
    { "DEBUG",   Severity::debug   },
    { "trace",   Severity::trace   },
    { "TRACE",   Severity::trace   },
    { "debug1",  Severity::debug1  },
    { "DEBUG1",  Severity::debug1  },
    { "debug2",  Severity::debug2  },
    { "DEBUG2",  Severity::debug2  },
    { "debug3",  Severity::debug3  },
    { "DEBUG3",  Severity::debug3  },
    { "debug4",  Severity::debug4  },
    { "DEBUG4",  Severity::debug4  }
}
Definition at line 178 of file Logger.h.
const array< string, 12 > fair::Logger::fSeverityNames static
Initial value:
=
{
    {
        "NOLOG",
        "FATAL",
        "ERROR",
        "WARN",
        "STATE",
        "INFO",
        "DEBUG",
        "DEBUG1",
        "DEBUG2",
        "DEBUG3",
        "DEBUG4",
        "TRACE"
    }
}
Definition at line 179 of file Logger.h.
Verbosity fair::Logger::fVerbosity = Verbosity::low static private
Definition at line 198 of file Logger.h.
const unordered_map< string, Verbosity > fair::Logger::fVerbosityMap static
Initial value:
=
{
    { "veryhigh", Verbosity::veryhigh },
    { "high",     Verbosity::high     },
    { "medium",   Verbosity::medium   },
    { "low",      Verbosity::low      },
    { "VERYHIGH", Verbosity::veryhigh },
    { "HIGH",     Verbosity::high     },
    { "MEDIUM",   Verbosity::medium   },
    { "LOW",      Verbosity::low      }
}
Definition at line 177 of file Logger.h.
const array< string, 4 > fair::Logger::fVerbosityNames static
Initial value:
=
{
    {
        "low",
        "medium",
        "high",
        "veryhigh"
    }
}
Definition at line 180 of file Logger.h.
The documentation for this class was generated from the following files:
Logger.h
Logger.cxx