FairRoot: PixelAltFindHits Class Reference
PixelAltFindHits Class Reference
#include <PixelAltFindHits.h>
Public Member Functions
PixelAltFindHits ()
PixelAltFindHits (Int_t iVerbose)
PixelAltFindHits (const char *name, Int_t iVerbose)
virtual ~PixelAltFindHits ()
virtual void Exec (Option_t *opt)
virtual void GetParList (TList *tempList)
virtual void InitMQ (TList *tempList)
virtual void ExecMQ (TList *inputList, TList *outputList)
virtual void ExecMQ (PixelPayload::Digi *digiPalVector, int nofDigis, PixelPayload::Hit *hitPalVector, int &nofHits)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Private Member Functions
Int_t FindHit (Int_t detId, Int_t feId, Int_t col, Int_t row, Int_t index, Double_t &posX, Double_t &posY, Double_t &posZ, Double_t &errX, Double_t &errY, Double_t &errZ)
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
void Reset ()
virtual void Finish ()
PixelAltFindHits (const PixelAltFindHits &)
PixelAltFindHits & operator= (const PixelAltFindHits &)
ClassDef (PixelAltFindHits, 1)
Private Attributes
PixelDigiPar * fDigiPar
FairGeoParSet * fGeoParSet
TClonesArray * fDigis
TClonesArray * fHits
Int_t fNDigis
Int_t fNHits
Int_t fTNofEvents
Int_t fTNofDigis
Int_t fTNofHits
Int_t fFeCols
Int_t fFeRows
Int_t fMaxFEperCol
Double_t fPitchX
Double_t fPitchY
Detailed Description
Definition at line 33 of file PixelAltFindHits.h.
Constructor & Destructor Documentation
PixelAltFindHits() [1/4]
PixelAltFindHits::PixelAltFindHits ()
Default constructor
Definition at line 50 of file PixelAltFindHits.cxx.
PixelAltFindHits() [2/4]
PixelAltFindHits::PixelAltFindHits (Int_t iVerbose)
Standard constructor
Definition at line 59 of file PixelAltFindHits.cxx.
PixelAltFindHits() [3/4]
PixelAltFindHits::PixelAltFindHits (const char * name, Int_t iVerbose)
Constructor with name
Definition at line 68 of file PixelAltFindHits.cxx.
References Reset().
~PixelAltFindHits()
PixelAltFindHits::~PixelAltFindHits () virtual
Destructor
Definition at line 93 of file PixelAltFindHits.cxx.
References fDigiPar, fHits, and Reset().
PixelAltFindHits() [4/4]
PixelAltFindHits::PixelAltFindHits (const PixelAltFindHits &) private
Member Function Documentation
CheckInputPersistance()
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
ClassDef()
PixelAltFindHits::ClassDef (PixelAltFindHits , 1) private
Exec()
void PixelAltFindHits::Exec (Option_t * opt) virtual
Execution
Definition at line 104 of file PixelAltFindHits.cxx.
References fDigis, FindHit(), fNDigis, fNHits, fTNofDigis, fTNofEvents, fTNofHits, PixelDigi::GetCol(), PixelDigi::GetDetectorID(), PixelDigi::GetFeID(), PixelDigi::GetIndex(), PixelDigi::GetRow(), and Reset().
Referenced by ExecMQ().
ExecMQ() [1/2]
void PixelAltFindHits::ExecMQ (TList * inputList, TList * outputList) virtual
Definition at line 226 of file PixelAltFindHits.cxx.
References Exec(), fDigis, and fHits.
ExecMQ() [2/2]
void PixelAltFindHits::ExecMQ (PixelPayload::Digi * digiPalVector, int nofDigis, PixelPayload::Hit * hitPalVector, int & nofHits) virtual
Definition at line 238 of file PixelAltFindHits.cxx.
References PixelPayload::Digi::fDetectorID, PixelPayload::Hit::fDetectorID, and FindHit().
ExecuteTask()
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
ExecuteTasks()
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
FindHit()
Int_t PixelAltFindHits::FindHit (Int_t detId, Int_t feId, Int_t col, Int_t row, Int_t index, Double_t & posX, Double_t & posY, Double_t & posZ, Double_t & errX, Double_t & errY, Double_t & errZ) private
Definition at line 140 of file PixelAltFindHits.cxx.
References fFeCols, fFeRows, fMaxFEperCol, fPitchX, and fPitchY.
Referenced by Exec(), and ExecMQ().
Finish()
void PixelAltFindHits::Finish () private virtual
Finish at the end of each event
Reimplemented from FairTask.
Definition at line 313 of file PixelAltFindHits.cxx.
References fHits, fTNofDigis, fTNofEvents, and fTNofHits.
FinishEvent()
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
FinishEvents()
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
FinishTask()
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
FinishTasks()
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
GetParList()
void PixelAltFindHits::GetParList (TList * tempList) virtual
Definition at line 194 of file PixelAltFindHits.cxx.
References fDigiPar.
Init()
InitStatus PixelAltFindHits::Init () private virtual
Intialisation
Reimplemented from FairTask.
Definition at line 262 of file PixelAltFindHits.cxx.
References fDigiPar, fDigis, fFeCols, fFeRows, fHits, fMaxFEperCol, fPitchX, fPitchY, PixelDigiPar::GetFECols(), PixelDigiPar::GetFERows(), PixelDigiPar::GetMaxFEperCol(), FairRootManager::GetObject(), PixelDigiPar::GetXPitch(), PixelDigiPar::GetYPitch(), FairRootManager::Instance(), kSUCCESS, and FairRootManager::Register().
InitMQ()
void PixelAltFindHits::InitMQ (TList * tempList) virtual
Definition at line 203 of file PixelAltFindHits.cxx.
References fDigiPar, fFeCols, fFeRows, fHits, fMaxFEperCol, fPitchX, fPitchY, PixelDigiPar::GetFECols(), PixelDigiPar::GetFERows(), PixelDigiPar::GetMaxFEperCol(), PixelDigiPar::GetXPitch(), and PixelDigiPar::GetYPitch().
InitTask()
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
InitTasks()
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
IsOutputBranchPersistent()
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
operator=()
PixelAltFindHits& PixelAltFindHits::operator= (const PixelAltFindHits &) private
ReInit()
InitStatus PixelAltFindHits::ReInit () private virtual
Reinitialisation
Reimplemented from FairTask.
Definition at line 296 of file PixelAltFindHits.cxx.
References kSUCCESS.
ReInitTask()
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
ReInitTasks()
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
Reset()
void PixelAltFindHits::Reset () private
Reset eventwise counters
Definition at line 306 of file PixelAltFindHits.cxx.
References fHits, fNDigis, and fNHits.
Referenced by Exec(), PixelAltFindHits(), and ~PixelAltFindHits().
SetInputPersistance()
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
SetOutputBranchPersistent()
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
SetParContainers()
void PixelAltFindHits::SetParContainers () private virtual
Get parameter containers
Reimplemented from FairTask.
Definition at line 178 of file PixelAltFindHits.cxx.
References fDigiPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRun::Instance().
SetParTask()
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
SetParTasks()
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
SetStreamProcessing()
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
SetVerbose()
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
fDigiPar
PixelDigiPar* PixelAltFindHits::fDigiPar private
Definition at line 67 of file PixelAltFindHits.h.
Referenced by GetParList(), Init(), InitMQ(), SetParContainers(), and ~PixelAltFindHits().
fDigis
TClonesArray* PixelAltFindHits::fDigis private
Definition at line 71 of file PixelAltFindHits.h.
Referenced by Exec(), ExecMQ(), and Init().
fFeCols
Int_t PixelAltFindHits::fFeCols private
Definition at line 81 of file PixelAltFindHits.h.
Referenced by FindHit(), Init(), and InitMQ().
fFeRows
Int_t PixelAltFindHits::fFeRows private
Definition at line 82 of file PixelAltFindHits.h.
Referenced by FindHit(), Init(), and InitMQ().
fGeoParSet
FairGeoParSet* PixelAltFindHits::fGeoParSet private
Definition at line 68 of file PixelAltFindHits.h.
fHits
TClonesArray* PixelAltFindHits::fHits private
Input array of PixelDigi
Definition at line 72 of file PixelAltFindHits.h.
Referenced by ExecMQ(), Finish(), Init(), InitMQ(), Reset(), and ~PixelAltFindHits().
fInputPersistance
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
fLogger
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
fMaxFEperCol
Int_t PixelAltFindHits::fMaxFEperCol private
Definition at line 83 of file PixelAltFindHits.h.
Referenced by FindHit(), Init(), and InitMQ().
fNDigis
Int_t PixelAltFindHits::fNDigis private
Output array of PixelHit
Definition at line 74 of file PixelAltFindHits.h.
Referenced by Exec(), and Reset().
fNHits
Int_t PixelAltFindHits::fNHits private
Definition at line 75 of file PixelAltFindHits.h.
Referenced by Exec(), and Reset().
fPitchX
Double_t PixelAltFindHits::fPitchX private
Definition at line 84 of file PixelAltFindHits.h.
Referenced by FindHit(), Init(), and InitMQ().
fPitchY
Double_t PixelAltFindHits::fPitchY private
Definition at line 85 of file PixelAltFindHits.h.
Referenced by FindHit(), Init(), and InitMQ().
fStreamProcessing
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
fTNofDigis
Int_t PixelAltFindHits::fTNofDigis private
Definition at line 78 of file PixelAltFindHits.h.
Referenced by Exec(), and Finish().
fTNofEvents
Int_t PixelAltFindHits::fTNofEvents private
Definition at line 77 of file PixelAltFindHits.h.
Referenced by Exec(), and Finish().
fTNofHits
Int_t PixelAltFindHits::fTNofHits private
Definition at line 79 of file PixelAltFindHits.h.
Referenced by Exec(), and Finish().
fVerbose
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
PixelAltFindHits.h
PixelAltFindHits.cxx