FairRroot: FairMQExample7ContFact Class Reference
FairMQExample7ContFact Class Reference
#include <FairMQExample7ContFact.h>
Public Member Functions
FairMQExample7ContFact ()
~FairMQExample7ContFact ()
FairParSet * createContainer (FairContainer *)
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual void activateParIo (FairParIo *)
Protected Member Functions
const char * getActualContext (const char *name)
Protected Attributes
TList * containers
FairLogger * fLogger
Private Member Functions
void setAllContainers ()
Detailed Description
Definition at line 15 of file FairMQExample7ContFact.h.
Constructor & Destructor Documentation
FairMQExample7ContFact::FairMQExample7ContFact ()
Definition at line 17 of file FairMQExample7ContFact.cxx.
References FairRuntimeDb::addContFactory(), FairRuntimeDb::instance(), and setAllContainers().
FairMQExample7ContFact::~FairMQExample7ContFact () inline
Definition at line 22 of file FairMQExample7ContFact.h.
Member Function Documentation
virtual void FairContFact::activateParIo (FairParIo *) inline virtual inherited
Definition at line 57 of file FairContFact.h.
Referenced by FairRuntimeDb::activateParIo().
Bool_t FairContFact::addContext (const char * name) inherited
Definition at line 160 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::setActualContext().
Referenced by FairRuntimeDb::addParamContext().
FairParSet * FairMQExample7ContFact::createContainer (FairContainer * container) virtual
Reimplemented from FairContFact.
Definition at line 33 of file FairMQExample7ContFact.cxx.
References FairContainer::getConcatName(), and FairContainer::getContext().
const char* FairContFact::getActualContext (const char * name) inline protected inherited
Definition at line 61 of file FairContFact.h.
FairParSet * FairContFact::getContainer (const char * name) inherited
Definition at line 172 of file FairContFact.cxx.
References FairRuntimeDb::addContainer(), FairContFact::containers, FairContFact::createContainer(), FairRuntimeDb::findContainer(), FairContainer::getActualContext(), FairContainer::getConcatName(), FairContainer::getDefaultContext(), FairRuntimeDb::instance(), rtdb, and FairContainer::setActualContext().
Referenced by FairRuntimeDb::getContainer().
void FairContFact::print () inherited
Definition at line 194 of file FairContFact.cxx.
References FairContFact::containers, and FairContainer::print().
Referenced by FairRuntimeDb::printParamContexts().
void FairMQExample7ContFact::setAllContainers () private
Definition at line 25 of file FairMQExample7ContFact.cxx.
References FairContainer::addContext(), and FairContFact::containers.
Referenced by FairMQExample7ContFact().
Member Data Documentation
TList* FairContFact::containers protected inherited
Definition at line 60 of file FairContFact.h.
Referenced by FairContFact::addContext(), FairContFact::getContainer(), FairContFact::print(), FairTutorialDet2ContFact::setAllContainers(), setAllContainers(), NewDetectorContFact::setAllContainers(), PixelContFact::setAllContainers(), FairTutorialDet1ContFact::setAllContainers(), FairTutorialDet4ContFact::setAllContainers(), FairTestDetectorContFact::setAllContainers(), FairRutherfordContFact::setAllContainers(), FairBaseContFact::setAllContainers(), and FairContFact::~FairContFact().
FairLogger* FairContFact::fLogger protected inherited
Fair Logger
Definition at line 65 of file FairContFact.h.
The documentation for this class was generated from the following files:
FairMQExample7ContFact.h
FairMQExample7ContFact.cxx