FairRroot: FairOnlineSource Class Reference
FairOnlineSource Class Reference abstract
#include <FairOnlineSource.h>
Public Member Functions
FairOnlineSource ()
FairOnlineSource (const FairOnlineSource &source)
virtual ~FairOnlineSource ()
void AddUnpacker (FairUnpack *unpacker)
const TObjArray * GetUnpackers () const
virtual Bool_t Init ()=0
virtual Int_t ReadEvent (UInt_t=0)=0
virtual void Close ()=0
virtual void SetParUnpackers ()
virtual Bool_t InitUnpackers ()
virtual Bool_t ReInitUnpackers ()
void Reset ()
virtual Source_Type GetSourceType ()
virtual Bool_t ActivateObject (TObject **, const char *)
virtual Bool_t ActivateObjectAny (void **, const std::type_info &, const char *)
virtual Int_t CheckMaxEventNo (Int_t=0)
virtual void ReadBranchEvent (const char *)
virtual void ReadBranchEvent (const char *, Int_t)
virtual void FillEventHeader (FairEventHeader *feh)
void SetRunId (Int_t runId)
Int_t GetRunId () const
Protected Attributes
TObjArray * fUnpackers
Int_t fRunId
Private Member Functions
FairOnlineSource & operator= (const FairOnlineSource &)
Detailed Description
Definition at line 25 of file FairOnlineSource.h.
Constructor & Destructor Documentation
FairOnlineSource::FairOnlineSource ()
Definition at line 21 of file FairOnlineSource.cxx.
FairOnlineSource::FairOnlineSource (const FairOnlineSource & source)
Definition at line 23 of file FairOnlineSource.cxx.
FairOnlineSource::~FairOnlineSource () virtual
Definition at line 26 of file FairOnlineSource.cxx.
References fUnpackers.
Member Function Documentation
virtual Bool_t FairSource::ActivateObject (TObject ** , const char *) inline virtual inherited
Reimplemented in FairFileSource, FairMixedSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 39 of file FairSource.h.
Referenced by FairRootManager::ActivateBranch(), FairMQEx9Sampler::InitTask(), and FairRootManager::UpdateBranches().
virtual Bool_t FairSource::ActivateObjectAny (void ** , const std::type_info & , const char *) inline virtual inherited
Reimplemented in FairFileSource.
Definition at line 40 of file FairSource.h.
Referenced by FairRootManager::InitObjectAs().
void FairOnlineSource::AddUnpacker (FairUnpack * unpacker) inline
Definition at line 32 of file FairOnlineSource.h.
References fUnpackers.
Referenced by unpack_mbs().
virtual Int_t FairSource::CheckMaxEventNo (Int_t = 0) inline virtual inherited
Check the maximum event number we can run to
Reimplemented in FairMixedSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 51 of file FairSource.h.
Referenced by FairRootManager::CheckMaxEventNo(), and FairMQEx9Sampler::InitTask().
virtual void FairOnlineSource::Close () pure virtual
Implements FairSource.
Implemented in FairLmdSource, FairMbsSource, FairMbsStreamSource, and FairRemoteSource.
void FairSource::FillEventHeader (FairEventHeader * feh) virtual inherited
Reimplemented in FairMixedSource, FairFileSource, PixelDigiBinSource, and PixelDigiSource.
Definition at line 39 of file FairSource.cxx.
References FairSource::fRunId, and FairEventHeader::SetRunId().
Referenced by FairRootManager::FillEventHeader(), FairRootManager::GetRunId(), FairRootManager::ReadBranchEvent(), FairRootManager::ReadEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
Int_t FairSource::GetRunId () const inline inherited
Definition at line 58 of file FairSource.h.
References FairSource::fRunId.
virtual Source_Type FairOnlineSource::GetSourceType () inline virtual
Implements FairSource.
Definition at line 47 of file FairOnlineSource.h.
References kONLINE.
const TObjArray* FairOnlineSource::GetUnpackers () const inline
Definition at line 33 of file FairOnlineSource.h.
References fUnpackers.
virtual Bool_t FairOnlineSource::Init () pure virtual
Implements FairSource.
Implemented in FairLmdSource, FairMbsSource, FairMbsStreamSource, and FairRemoteSource.
Referenced by InitUnpackers().
Bool_t FairOnlineSource::InitUnpackers () virtual
Implements FairSource.
Definition at line 31 of file FairOnlineSource.cxx.
References fUnpackers, and Init().
FairOnlineSource& FairOnlineSource::operator= (const FairOnlineSource &) private
virtual void FairSource::ReadBranchEvent (const char *) inline virtual inherited
Read the tree entry on one branch
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 53 of file FairSource.h.
Referenced by FairRootManager::ReadBranchEvent(), and FairRootManager::ReadNonTimeBasedEventFromBranches().
virtual void FairSource::ReadBranchEvent (const char * , Int_t) inline virtual inherited
Reimplemented in FairMixedSource, and FairFileSource.
Definition at line 54 of file FairSource.h.
virtual Int_t FairOnlineSource::ReadEvent (UInt_t = 0) pure virtual
Implements FairSource.
Implemented in FairLmdSource, FairMbsSource, FairMbsStreamSource, and FairRemoteSource.
Bool_t FairOnlineSource::ReInitUnpackers () virtual
Implements FairSource.
Definition at line 40 of file FairOnlineSource.cxx.
References fUnpackers.
void FairOnlineSource::Reset () virtual
Implements FairSource.
Definition at line 55 of file FairOnlineSource.cxx.
References fUnpackers.
void FairOnlineSource::SetParUnpackers () virtual
Implements FairSource.
Definition at line 49 of file FairOnlineSource.cxx.
References fUnpackers.
void FairSource::SetRunId (Int_t runId) inline inherited
Definition at line 57 of file FairSource.h.
References FairSource::fRunId.
Referenced by FairRunOnline::Init().
Member Data Documentation
Int_t FairSource::fRunId protected inherited
Definition at line 61 of file FairSource.h.
Referenced by FairSource::FillEventHeader(), FairSource::GetRunId(), and FairSource::SetRunId().
TObjArray* FairOnlineSource::fUnpackers protected
Definition at line 50 of file FairOnlineSource.h.
Referenced by AddUnpacker(), GetUnpackers(), InitUnpackers(), ReInitUnpackers(), Reset(), SetParUnpackers(), FairMbsSource::Unpack(), and ~FairOnlineSource().
The documentation for this class was generated from the following files:
FairOnlineSource.h
FairOnlineSource.cxx