FairRroot: fair::mq::ofi::Socket Class Reference
fair::mq::ofi::Socket Class Reference abstract
#include <fairmq/ofi/Socket.h>
Public Member Functions
Socket (Context &factory, const std::string &type, const std::string &name, const std::string &id="")
Socket (const Socket &)=delete
Socket operator= (const Socket &)=delete
auto GetId () -> std::string
auto Bind (const std::string &address) -> bool override
auto Connect (const std::string &address) -> void override
auto Send (MessagePtr &msg, int timeout=0) -> int override
auto Receive (MessagePtr &msg, int timeout=0) -> int override
auto Send (std::vector< MessagePtr > &msgVec, int timeout=0) -> int64_t override
auto Receive (std::vector< MessagePtr > &msgVec, int timeout=0) -> int64_t override
auto TrySend (MessagePtr &msg) -> int override
auto TryReceive (MessagePtr &msg) -> int override
auto TrySend (std::vector< MessagePtr > &msgVec) -> int64_t override
auto TryReceive (std::vector< MessagePtr > &msgVec) -> int64_t override
auto GetSocket () const -> void *override
auto GetSocket (int nothing) const -> int override
auto Close () -> void override
auto SetOption (const std::string &option, const void *value, size_t valueSize) -> void override
auto GetOption (const std::string &option, void *value, size_t *valueSize) -> void override
auto GetBytesTx () const -> unsigned long override
auto GetBytesRx () const -> unsigned long override
auto GetMessagesTx () const -> unsigned long override
auto GetMessagesRx () const -> unsigned long override
auto SetSendTimeout (const int timeout, const std::string &address, const std::string &method) -> bool override
auto GetSendTimeout () const -> int override
auto SetReceiveTimeout (const int timeout, const std::string &address, const std::string &method) -> bool override
auto GetReceiveTimeout () const -> int override
~Socket () override
virtual int64_t Send (std::vector< std::unique_ptr< FairMQMessage >> &msgVec, int timeout=0)=0
virtual int64_t Receive (std::vector< std::unique_ptr< FairMQMessage >> &msgVec, int timeout=0)=0
virtual int64_t TrySend (std::vector< std::unique_ptr< FairMQMessage >> &msgVec)=0
virtual int64_t TryReceive (std::vector< std::unique_ptr< FairMQMessage >> &msgVec)=0
Static Public Member Functions
static auto GetConstant (const std::string &constant) -> int
Private Member Functions
auto SendImpl (MessagePtr &msg, const int flags, const int timeout) -> int
auto ReceiveImpl (MessagePtr &msg, const int flags, const int timeout) -> int
auto SendImpl (std::vector< MessagePtr > &msgVec, const int flags, const int timeout) -> int64_t
auto ReceiveImpl (std::vector< MessagePtr > &msgVec, const int flags, const int timeout) -> int64_t
auto InitDataEndpoint () -> void
auto WaitForControlPeer () -> void
auto AnnounceDataAddress () -> void
auto SendControlMessage (std::unique_ptr< ControlMessage > ctrl) -> void
auto ReceiveControlMessage () -> std::unique_ptr< ControlMessage >
auto ProcessDataAddressAnnouncement (std::unique_ptr< ControlMessage > ctrl) -> void
auto ConnectControlSocket (Context::Address address) -> void
auto BindControlSocket (Context::Address address) -> void
Private Attributes
void * fControlSocket
void * fMonitorSocket
fid_ep * fDataEndpoint
fid_cq * fDataCompletionQueueTx
fid_cq * fDataCompletionQueueRx
std::string fId
std::atomic< unsigned long > fBytesTx
std::atomic< unsigned long > fBytesRx
std::atomic< unsigned long > fMessagesTx
std::atomic< unsigned long > fMessagesRx
Context & fContext
fi_addr_t fRemoteDataAddr
sockaddr_in fLocalDataAddr
bool fWaitingForControlPeer
boost::asio::io_service::strand fIoStrand
int fSndTimeout
int fRcvTimeout
Detailed Description
Todo:
TODO insert long description
Definition at line 35 of file Socket.h.
Constructor & Destructor Documentation
fair::mq::ofi::Socket::Socket (Context & factory, const std::string & type, const std::string & name, const std::string & id = "")
fair::mq::ofi::Socket::Socket (const Socket &) delete
fair::mq::ofi::Socket::~Socket () override
Definition at line 782 of file Socket.cxx.
References fair::error, and LOG.
Member Function Documentation
auto fair::mq::ofi::Socket::AnnounceDataAddress () -> void private
Definition at line 183 of file Socket.cxx.
References fair::debug, LOG, and fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::Bind (const std::string & address) -> bool override virtual
Implements FairMQSocket.
Definition at line 89 of file Socket.cxx.
auto fair::mq::ofi::Socket::BindControlSocket (Context::Address address) -> void private
Definition at line 119 of file Socket.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::Close () -> void override virtual
Implements FairMQSocket.
Definition at line 581 of file Socket.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::Connect (const std::string & address) -> void override virtual
Implements FairMQSocket.
Definition at line 110 of file Socket.cxx.
auto fair::mq::ofi::Socket::ConnectControlSocket (Context::Address address) -> void private
Definition at line 129 of file Socket.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::GetBytesRx () const -> unsigned long inline override virtual
Implements FairMQSocket.
Definition at line 66 of file Socket.h.
References fBytesRx.
auto fair::mq::ofi::Socket::GetBytesTx () const -> unsigned long inline override virtual
Implements FairMQSocket.
Definition at line 65 of file Socket.h.
References fBytesTx.
auto fair::mq::ofi::Socket::GetConstant (const std::string & constant) -> int static
Definition at line 732 of file Socket.cxx.
auto fair::mq::ofi::Socket::GetId () -> std::string inline virtual
Implements FairMQSocket.
Definition at line 42 of file Socket.h.
References fId.
auto fair::mq::ofi::Socket::GetMessagesRx () const -> unsigned long inline override virtual
Implements FairMQSocket.
Definition at line 68 of file Socket.h.
References fMessagesRx.
auto fair::mq::ofi::Socket::GetMessagesTx () const -> unsigned long inline override virtual
Implements FairMQSocket.
Definition at line 67 of file Socket.h.
References fMessagesTx.
auto fair::mq::ofi::Socket::GetOption (const std::string & option, void * value, size_t * valueSize) -> void override virtual
Implements FairMQSocket.
Definition at line 615 of file Socket.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::GetReceiveTimeout () const -> int override virtual
Implements FairMQSocket.
Definition at line 726 of file Socket.cxx.
auto fair::mq::ofi::Socket::GetSendTimeout () const -> int override virtual
Implements FairMQSocket.
Definition at line 671 of file Socket.cxx.
auto fair::mq::ofi::Socket::GetSocket () const -> void* inline override virtual
Implements FairMQSocket.
Definition at line 57 of file Socket.h.
References fControlSocket.
auto fair::mq::ofi::Socket::GetSocket (int nothing) const -> int inline override virtual
Implements FairMQSocket.
Definition at line 58 of file Socket.h.
auto fair::mq::ofi::Socket::InitDataEndpoint () -> void private
Definition at line 151 of file Socket.cxx.
References fair::mq::tools::ToString().
Socket fair::mq::ofi::Socket::operator= (const Socket &) delete
auto fair::mq::ofi::Socket::ProcessDataAddressAnnouncement (std::unique_ptr< ControlMessage > ctrl) -> void private
Definition at line 137 of file Socket.cxx.
References fair::debug, and LOG.
virtual int64_t FairMQSocket::Receive (std::vector< std::unique_ptr< FairMQMessage >> & msgVec, int timeout = 0) pure virtual inherited
Implemented in FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
auto fair::mq::ofi::Socket::Receive (MessagePtr & msg, int timeout = 0) -> int override virtual
Implements FairMQSocket.
Definition at line 292 of file Socket.cxx.
auto fair::mq::ofi::Socket::Receive (std::vector< MessagePtr > & msgVec, int timeout = 0) -> int64_t override
Definition at line 294 of file Socket.cxx.
auto fair::mq::ofi::Socket::ReceiveControlMessage () -> std::unique_ptr<ControlMessage> private
Definition at line 231 of file Socket.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::ReceiveImpl (MessagePtr & msg, const int flags, const int timeout) -> int private
Definition at line 355 of file Socket.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::ReceiveImpl (std::vector< MessagePtr > & msgVec, const int flags, const int timeout) -> int64_t private
virtual int64_t FairMQSocket::Send (std::vector< std::unique_ptr< FairMQMessage >> & msgVec, int timeout = 0) pure virtual inherited
Implemented in FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
auto fair::mq::ofi::Socket::Send (MessagePtr & msg, int timeout = 0) -> int override virtual
Implements FairMQSocket.
Definition at line 291 of file Socket.cxx.
auto fair::mq::ofi::Socket::Send (std::vector< MessagePtr > & msgVec, int timeout = 0) -> int64_t override
Definition at line 293 of file Socket.cxx.
auto fair::mq::ofi::Socket::SendControlMessage (std::unique_ptr< ControlMessage > ctrl) -> void private
Definition at line 212 of file Socket.cxx.
References fair::mq::ofi::free_string(), and fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::SendImpl (MessagePtr & msg, const int flags, const int timeout) -> int private
Definition at line 301 of file Socket.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::SendImpl (std::vector< MessagePtr > & msgVec, const int flags, const int timeout) -> int64_t private
auto fair::mq::ofi::Socket::SetOption (const std::string & option, const void * value, size_t valueSize) -> void override virtual
Implements FairMQSocket.
Definition at line 608 of file Socket.cxx.
References fair::mq::tools::ToString().
auto fair::mq::ofi::Socket::SetReceiveTimeout (const int timeout, const std::string & address, const std::string & method) -> bool override virtual
Implements FairMQSocket.
Definition at line 677 of file Socket.cxx.
auto fair::mq::ofi::Socket::SetSendTimeout (const int timeout, const std::string & address, const std::string & method) -> bool override virtual
Implements FairMQSocket.
Definition at line 622 of file Socket.cxx.
virtual int64_t FairMQSocket::TryReceive (std::vector< std::unique_ptr< FairMQMessage >> & msgVec) pure virtual inherited
Implemented in FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
auto fair::mq::ofi::Socket::TryReceive (MessagePtr & msg) -> int override virtual
Implements FairMQSocket.
Definition at line 297 of file Socket.cxx.
auto fair::mq::ofi::Socket::TryReceive (std::vector< MessagePtr > & msgVec) -> int64_t override
Definition at line 299 of file Socket.cxx.
virtual int64_t FairMQSocket::TrySend (std::vector< std::unique_ptr< FairMQMessage >> & msgVec) pure virtual inherited
Implemented in FairMQSocketSHM, FairMQSocketZMQ, and FairMQSocketNN.
auto fair::mq::ofi::Socket::TrySend (MessagePtr & msg) -> int override virtual
Implements FairMQSocket.
Definition at line 296 of file Socket.cxx.
auto fair::mq::ofi::Socket::TrySend (std::vector< MessagePtr > & msgVec) -> int64_t override
Definition at line 298 of file Socket.cxx.
auto fair::mq::ofi::Socket::WaitForControlPeer () -> void private
Definition at line 253 of file Socket.cxx.
References fair::debug, LOG, and fair::mq::tools::ToString().
Member Data Documentation
std::atomic<unsigned long> fair::mq::ofi::Socket::fBytesRx private
Definition at line 87 of file Socket.h.
Referenced by GetBytesRx().
std::atomic<unsigned long> fair::mq::ofi::Socket::fBytesTx private
Definition at line 86 of file Socket.h.
Referenced by GetBytesTx().
Context& fair::mq::ofi::Socket::fContext private
Definition at line 90 of file Socket.h.
void* fair::mq::ofi::Socket::fControlSocket private
Definition at line 80 of file Socket.h.
Referenced by GetSocket().
fid_cq* fair::mq::ofi::Socket::fDataCompletionQueueRx private
Definition at line 84 of file Socket.h.
fid_cq* fair::mq::ofi::Socket::fDataCompletionQueueTx private
Definition at line 83 of file Socket.h.
fid_ep* fair::mq::ofi::Socket::fDataEndpoint private
Definition at line 82 of file Socket.h.
std::string fair::mq::ofi::Socket::fId private
Definition at line 85 of file Socket.h.
Referenced by GetId().
boost::asio::io_service::strand fair::mq::ofi::Socket::fIoStrand private
Definition at line 94 of file Socket.h.
sockaddr_in fair::mq::ofi::Socket::fLocalDataAddr private
Definition at line 92 of file Socket.h.
std::atomic<unsigned long> fair::mq::ofi::Socket::fMessagesRx private
Definition at line 89 of file Socket.h.
Referenced by GetMessagesRx().
std::atomic<unsigned long> fair::mq::ofi::Socket::fMessagesTx private
Definition at line 88 of file Socket.h.
Referenced by GetMessagesTx().
void* fair::mq::ofi::Socket::fMonitorSocket private
Definition at line 81 of file Socket.h.
int fair::mq::ofi::Socket::fRcvTimeout private
Definition at line 97 of file Socket.h.
fi_addr_t fair::mq::ofi::Socket::fRemoteDataAddr private
Definition at line 91 of file Socket.h.
int fair::mq::ofi::Socket::fSndTimeout private
Definition at line 96 of file Socket.h.
bool fair::mq::ofi::Socket::fWaitingForControlPeer private
Definition at line 93 of file Socket.h.
The documentation for this class was generated from the following files:
Socket.h
Socket.cxx