FairRoot: PixelFitTracks Class Reference
PixelFitTracks Class Reference
#include <PixelFitTracks.h>
Public Member Functions
PixelFitTracks ()
PixelFitTracks (Int_t iVerbose)
PixelFitTracks (const char *name, Int_t iVerbose)
virtual ~PixelFitTracks ()
virtual void Exec (Option_t *opt)
virtual void GetParList (TList *tempList)
virtual void InitMQ (TList *tempList)
virtual void ExecMQ (TList *inputList, TList *outputList)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
virtual void ExecuteTask (Option_t *option="0")
void SetOutputBranchPersistent (TString, Bool_t)
Bool_t IsOutputBranchPersistent (TString)
void SetStreamProcessing (Bool_t val=kTRUE)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
virtual void ExecuteTasks (Option_t *option)
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Bool_t fStreamProcessing
Private Member Functions
Double_t LinearRegression (Int_t nval, Double_t xval[], Double_t yval[], Double_t &valA0, Double_t &errA0, Double_t &valA1, Double_t &errA1)
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
void Reset ()
virtual void Finish ()
PixelFitTracks (const PixelFitTracks &)
PixelFitTracks & operator= (const PixelFitTracks &)
ClassDef (PixelFitTracks, 1)
Private Attributes
PixelDigiPar * fDigiPar
TClonesArray * fHits
TClonesArray * fTracks
TClonesArray * fFitTracks
Int_t fTNofEvents
Int_t fNHits
Int_t fNTracks
Int_t fTNofTracks
Int_t fNFitTracks
Int_t fTNofFitTracks
Detailed Description
Definition at line 28 of file PixelFitTracks.h.
Constructor & Destructor Documentation
PixelFitTracks() [1/4]
PixelFitTracks::PixelFitTracks ()
Default constructor
Definition at line 43 of file PixelFitTracks.cxx.
PixelFitTracks() [2/4]
PixelFitTracks::PixelFitTracks (Int_t iVerbose)
Standard constructor
Definition at line 52 of file PixelFitTracks.cxx.
PixelFitTracks() [3/4]
PixelFitTracks::PixelFitTracks (const char * name, Int_t iVerbose)
Constructor with name
Definition at line 61 of file PixelFitTracks.cxx.
References Reset().
~PixelFitTracks()
PixelFitTracks::~PixelFitTracks () virtual
Destructor
Definition at line 81 of file PixelFitTracks.cxx.
References fDigiPar, fFitTracks, and Reset().
PixelFitTracks() [4/4]
PixelFitTracks::PixelFitTracks (const PixelFitTracks &) private
Member Function Documentation
CheckInputPersistance()
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 85 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
ClassDef()
PixelFitTracks::ClassDef (PixelFitTracks , 1) private
Exec()
void PixelFitTracks::Exec (Option_t * opt) virtual
Execution
Definition at line 92 of file PixelFitTracks.cxx.
References PixelTrack::AddHitIndex(), fHits, fNFitTracks, fNHits, fNTracks, fTNofEvents, fTNofFitTracks, fTNofTracks, fTracks, PixelTrack::GetAX(), PixelTrack::GetAXErr(), PixelTrack::GetAY(), PixelTrack::GetAYErr(), PixelTrack::GetHitIndex(), PixelTrack::GetNofHits(), FairHit::GetX(), PixelTrack::GetX0(), PixelTrack::GetX0Err(), FairHit::GetY(), PixelTrack::GetY0(), PixelTrack::GetY0Err(), FairHit::GetZ(), LinearRegression(), and Reset().
Referenced by ExecMQ().
ExecMQ()
void PixelFitTracks::ExecMQ (TList * inputList, TList * outputList) virtual
Definition at line 223 of file PixelFitTracks.cxx.
References Exec(), fFitTracks, fHits, and fTracks.
ExecuteTask()
void FairTask::ExecuteTask (Option_t * option = "0") virtual inherited
Definition at line 143 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
ExecuteTasks()
void FairTask::ExecuteTasks (Option_t * option) protected virtual inherited
Definition at line 185 of file FairTask.cxx.
References FairTask::ExecuteTasks(), FairMonitor::GetMonitor(), FairMonitor::StartMonitoring(), and FairMonitor::StopMonitoring().
Referenced by FairTask::ExecuteTask(), and FairTask::ExecuteTasks().
Finish()
void PixelFitTracks::Finish () private virtual
Finish at the end of each event
Reimplemented from FairTask.
Definition at line 278 of file PixelFitTracks.cxx.
References fFitTracks, fTNofEvents, fTNofFitTracks, and fTNofTracks.
FinishEvent()
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 103 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAnaProof::RunOneEvent(), FairRunAna::RunOnTBData(), and FairRunAna::RunTSBuffers().
FinishEvents()
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 257 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
FinishTask()
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks. Method used internally in FairRoot.
Reimplemented in FairRingSorterTask, and FairMBSTask.
Definition at line 110 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunOnTBData(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
FinishTasks()
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 248 of file FairTask.cxx.
References FairTask::FinishTask().
Referenced by FairTask::FinishTask().
GetParList()
void PixelFitTracks::GetParList (TList * tempList) virtual
Definition at line 203 of file PixelFitTracks.cxx.
References fDigiPar.
Init()
InitStatus PixelFitTracks::Init () private virtual
Intialisation
Reimplemented from FairTask.
Definition at line 236 of file PixelFitTracks.cxx.
References fFitTracks, fHits, fTracks, FairRootManager::GetObject(), FairRootManager::Instance(), kSUCCESS, and FairRootManager::Register().
InitMQ()
void PixelFitTracks::InitMQ (TList * tempList) virtual
Definition at line 212 of file PixelFitTracks.cxx.
References fDigiPar, and fFitTracks.
InitTask()
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 62 of file FairTask.cxx.
References FairMonitor::GetMonitor(), FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and FairMonitor::SetCurrentTask().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
InitTasks()
void FairTask::InitTasks () protected inherited
Recursive intialisation of subtasks at begin of run
Definition at line 134 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
IsOutputBranchPersistent()
Bool_t FairTask::IsOutputBranchPersistent (TString branchName) inherited
Check if the branch with the given name is persistent. If the branch is not in the map, the default return value is true.
Definition at line 270 of file FairTask.cxx.
References FairTask::fOutputPersistance.
LinearRegression()
Double_t PixelFitTracks::LinearRegression (Int_t nval, Double_t xval[], Double_t yval[], Double_t & valA0, Double_t & errA0, Double_t & valA1, Double_t & errA1) private
Definition at line 158 of file PixelFitTracks.cxx.
Referenced by Exec().
operator=()
PixelFitTracks& PixelFitTracks::operator= (const PixelFitTracks &) private
ReInit()
InitStatus PixelFitTracks::ReInit () private virtual
Reinitialisation
Reimplemented from FairTask.
Definition at line 261 of file PixelFitTracks.cxx.
References kSUCCESS.
ReInitTask()
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 79 of file FairTask.cxx.
References kERROR, kFATAL, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::EventLoop(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
ReInitTasks()
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 226 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
Reset()
void PixelFitTracks::Reset () private
Reset eventwise counters
Definition at line 271 of file PixelFitTracks.cxx.
References fFitTracks, fNFitTracks, fNHits, and fNTracks.
Referenced by Exec(), PixelFitTracks(), and ~PixelFitTracks().
SetInputPersistance()
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 83 of file FairTask.h.
References FairTask::fInputPersistance.
SetOutputBranchPersistent()
void FairTask::SetOutputBranchPersistent (TString branchName, Bool_t persistence) inherited
Set persistency of branch with given name true or false In case is is set to false the branch will not be written to the output.
Definition at line 265 of file FairTask.cxx.
References FairTask::fOutputPersistance.
SetParContainers()
void PixelFitTracks::SetParContainers () private virtual
Get parameter containers
Reimplemented from FairTask.
Definition at line 187 of file PixelFitTracks.cxx.
References fDigiPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRun::Instance().
SetParTask()
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks. Method used internally in FairRoot.
Definition at line 94 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
SetParTasks()
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 237 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
SetStreamProcessing()
void FairTask::SetStreamProcessing (Bool_t val = kTRUE) inline inherited
Definition at line 102 of file FairTask.h.
References FairTask::fStreamProcessing.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init().
SetVerbose()
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 121 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
Member Data Documentation
fDigiPar
PixelDigiPar* PixelFitTracks::fDigiPar private
Definition at line 58 of file PixelFitTracks.h.
Referenced by GetParList(), InitMQ(), SetParContainers(), and ~PixelFitTracks().
fFitTracks
TClonesArray* PixelFitTracks::fFitTracks private
Input array of PixelTrack
Definition at line 62 of file PixelFitTracks.h.
Referenced by ExecMQ(), Finish(), Init(), InitMQ(), Reset(), and ~PixelFitTracks().
fHits
TClonesArray* PixelFitTracks::fHits private
Definition at line 60 of file PixelFitTracks.h.
Referenced by Exec(), ExecMQ(), and Init().
fInputPersistance
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
fLogger
FairLogger* FairTask::fLogger protected inherited
Definition at line 108 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), NewTask::NewTask(), NewTask::ReInit(), NewTask::SetParContainers(), and NewTask::~NewTask().
fNFitTracks
Int_t PixelFitTracks::fNFitTracks private
Definition at line 71 of file PixelFitTracks.h.
Referenced by Exec(), and Reset().
fNHits
Int_t PixelFitTracks::fNHits private
Definition at line 66 of file PixelFitTracks.h.
Referenced by Exec(), and Reset().
fNTracks
Int_t PixelFitTracks::fNTracks private
Definition at line 68 of file PixelFitTracks.h.
Referenced by Exec(), and Reset().
fStreamProcessing
Bool_t FairTask::fStreamProcessing protected inherited
Definition at line 109 of file FairTask.h.
Referenced by FairTestDetectorRecoTask::Exec(), and FairTask::SetStreamProcessing().
fTNofEvents
Int_t PixelFitTracks::fTNofEvents private
Output array of PixelTrack
Definition at line 64 of file PixelFitTracks.h.
Referenced by Exec(), and Finish().
fTNofFitTracks
Int_t PixelFitTracks::fTNofFitTracks private
Definition at line 72 of file PixelFitTracks.h.
Referenced by Exec(), and Finish().
fTNofTracks
Int_t PixelFitTracks::fTNofTracks private
Definition at line 69 of file PixelFitTracks.h.
Referenced by Exec(), and Finish().
fTracks
TClonesArray* PixelFitTracks::fTracks private
Input array of PixelHit
Definition at line 61 of file PixelFitTracks.h.
Referenced by Exec(), ExecMQ(), and Init().
fVerbose
Int_t FairTask::fVerbose protected inherited
Definition at line 106 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
PixelFitTracks.h
PixelFitTracks.cxx