FairRroot: fair::mq::ofi::TransportFactory Class Reference
fair::mq::ofi::TransportFactory Class Reference abstract
FairMQ transport factory for the ofi transport (implemented with ZeroMQ + libfabric)
#include <fairmq/ofi/TransportFactory.h>
Public Member Functions
TransportFactory (const std::string &id="", const FairMQProgOptions *config=nullptr)
TransportFactory (const TransportFactory &)=delete
TransportFactory operator= (const TransportFactory &)=delete
auto CreateMessage () const -> MessagePtr override
Create empty FairMQMessage.
auto CreateMessage (const std::size_t size) const -> MessagePtr override
auto CreateMessage (void *data, const std::size_t size, fairmq_free_fn *ffn, void *hint=nullptr) const -> MessagePtr override
auto CreateMessage (UnmanagedRegionPtr &region, void *data, const std::size_t size, void *hint=nullptr) const -> MessagePtr override
auto CreateSocket (const std::string &type, const std::string &name) const -> SocketPtr override
Create a socket.
auto CreatePoller (const std::vector< FairMQChannel > &channels) const -> PollerPtr override
Create a poller for a single channel (all subchannels)
auto CreatePoller (const std::vector< const FairMQChannel * > &channels) const -> PollerPtr override
Create a poller for specific channels.
auto CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> &channelsMap, const std::vector< std::string > &channelList) const -> PollerPtr override
Create a poller for specific channels (all subchannels)
auto CreatePoller (const FairMQSocket &cmdSocket, const FairMQSocket &dataSocket) const -> PollerPtr override
Create a poller for two sockets.
auto CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback=nullptr) const -> UnmanagedRegionPtr override
auto GetType () const -> Transport override
Get transport type.
void Interrupt () override
void Resume () override
auto GetId () const -> const std::string
virtual FairMQMessagePtr CreateMessage (const size_t size) const =0
Create new FairMQMessage of specified size.
virtual FairMQMessagePtr CreateMessage (void *data, const size_t size, fairmq_free_fn *ffn, void *hint=nullptr) const =0
Create new FairMQMessage with user provided buffer and size.
virtual FairMQMessagePtr CreateMessage (FairMQUnmanagedRegionPtr &unmanagedRegion, void *data, const size_t size, void *hint=0) const =0
template<typename T >
FairMQMessagePtr NewSimpleMessage (const T &data) const
template<std::size_t N>
FairMQMessagePtr NewSimpleMessage (const char(&data)[N]) const
FairMQMessagePtr NewSimpleMessage (const std::string &str) const
template<typename T >
FairMQMessagePtr NewStaticMessage (const T &data) const
FairMQMessagePtr NewStaticMessage (const std::string &str) const
Static Public Member Functions
static auto CreateTransportFactory (const std::string &type, const std::string &id="", const FairMQProgOptions *config=nullptr) -> std::shared_ptr< FairMQTransportFactory >
static void FairMQNoCleanup (void *, void *)
template<typename T >
static void FairMQSimpleMsgCleanup (void *, void *obj)
Private Attributes
Context fContext
Detailed Description
FairMQ transport factory for the ofi transport (implemented with ZeroMQ + libfabric)
Todo:
TODO insert long description
Definition at line 29 of file TransportFactory.h.
Constructor & Destructor Documentation
fair::mq::ofi::TransportFactory::TransportFactory (const std::string & id = "", const FairMQProgOptions * config = nullptr)
fair::mq::ofi::TransportFactory::TransportFactory (const TransportFactory &) delete
Member Function Documentation
auto fair::mq::ofi::TransportFactory::CreateMessage () const -> MessagePtr override virtual
Create empty FairMQMessage.
Returns
pointer to FairMQMessage
Implements FairMQTransportFactory.
Definition at line 39 of file TransportFactory.cxx.
auto fair::mq::ofi::TransportFactory::CreateMessage (const std::size_t size) const -> MessagePtr override
auto fair::mq::ofi::TransportFactory::CreateMessage (void * data, const std::size_t size, fairmq_free_fn * ffn, void * hint = nullptr) const -> MessagePtr override
auto fair::mq::ofi::TransportFactory::CreateMessage (UnmanagedRegionPtr & region, void * data, const std::size_t size, void * hint = nullptr) const -> MessagePtr override
virtual FairMQMessagePtr FairMQTransportFactory::CreateMessage (const size_t size) const pure virtual inherited
Create new FairMQMessage of specified size.
Parameters
size message size
Returns
pointer to FairMQMessage
Implemented in FairMQTransportFactoryZMQ, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual FairMQMessagePtr FairMQTransportFactory::CreateMessage (void * data, const size_t size, fairmq_free_fn * ffn, void * hint = nullptr) const pure virtual inherited
Create new FairMQMessage with user provided buffer and size.
Parameters
data pointer to user provided buffer
size size of the user provided buffer
ffn callback, called when the message is transfered (and can be deleted)
obj optional helper pointer that can be used in the callback
Returns
pointer to FairMQMessage
Implemented in FairMQTransportFactoryZMQ, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
virtual FairMQMessagePtr FairMQTransportFactory::CreateMessage (FairMQUnmanagedRegionPtr & unmanagedRegion, void * data, const size_t size, void * hint = 0) const pure virtual inherited
Implemented in FairMQTransportFactoryZMQ, FairMQTransportFactorySHM, and FairMQTransportFactoryNN.
auto fair::mq::ofi::TransportFactory::CreatePoller (const std::vector< FairMQChannel > & channels) const -> PollerPtr override virtual
Create a poller for a single channel (all subchannels)
Implements FairMQTransportFactory.
auto fair::mq::ofi::TransportFactory::CreatePoller (const std::vector< const FairMQChannel * > & channels) const -> PollerPtr override virtual
Create a poller for specific channels.
Implements FairMQTransportFactory.
auto fair::mq::ofi::TransportFactory::CreatePoller (const std::unordered_map< std::string, std::vector< FairMQChannel >> & channelsMap, const std::vector< std::string > & channelList) const -> PollerPtr override virtual
Create a poller for specific channels (all subchannels)
Implements FairMQTransportFactory.
auto fair::mq::ofi::TransportFactory::CreatePoller (const FairMQSocket & cmdSocket, const FairMQSocket & dataSocket) const -> PollerPtr override virtual
Create a poller for two sockets.
Implements FairMQTransportFactory.
Definition at line 79 of file TransportFactory.cxx.
auto fair::mq::ofi::TransportFactory::CreateSocket (const std::string & type, const std::string & name) const -> SocketPtr override virtual
Create a socket.
Implements FairMQTransportFactory.
Definition at line 59 of file TransportFactory.cxx.
auto FairMQTransportFactory::CreateTransportFactory (const std::string & type, const std::string & id = "", const FairMQProgOptions * config = nullptr) -> std::shared_ptr<FairMQTransportFactory> static inherited
Definition at line 30 of file FairMQTransportFactory.cxx.
References LOG, and fair::mq::tools::Uuid().
Referenced by FairMQDevice::AddTransport().
auto fair::mq::ofi::TransportFactory::CreateUnmanagedRegion (const size_t size, FairMQRegionCallback callback = nullptr) const -> UnmanagedRegionPtr override virtual
Implements FairMQTransportFactory.
Definition at line 84 of file TransportFactory.cxx.
static void FairMQTransportFactory::FairMQNoCleanup (void * , void *) inline static inherited
Definition at line 81 of file FairMQTransportFactory.h.
Referenced by FairMQTransportFactory::NewStaticMessage().
template<typename T > static void FairMQTransportFactory::FairMQSimpleMsgCleanup (void * , void * obj) inline static inherited
Definition at line 86 of file FairMQTransportFactory.h.
auto FairMQTransportFactory::GetId () const -> const std::string inline inherited
Definition at line 38 of file FairMQTransportFactory.h.
References FairMQTransportFactory::fkId.
Referenced by FairMQTransportFactoryNN::CreateSocket(), FairMQTransportFactorySHM::CreateSocket(), and FairMQTransportFactoryZMQ::CreateSocket().
auto fair::mq::ofi::TransportFactory::GetType () const -> Transport override virtual
Get transport type.
Implements FairMQTransportFactory.
Definition at line 89 of file TransportFactory.cxx.
void fair::mq::ofi::TransportFactory::Interrupt () inline override virtual
Implements FairMQTransportFactory.
Definition at line 52 of file TransportFactory.h.
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const T & data) const inline inherited
Definition at line 92 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
template<std::size_t N> FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const char(&) data[N]) const inline inherited
Definition at line 101 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
FairMQMessagePtr FairMQTransportFactory::NewSimpleMessage (const std::string & str) const inline inherited
Definition at line 107 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage().
template<typename T > FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const T & data) const inline inherited
Definition at line 115 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage(), and FairMQTransportFactory::FairMQNoCleanup().
FairMQMessagePtr FairMQTransportFactory::NewStaticMessage (const std::string & str) const inline inherited
Definition at line 120 of file FairMQTransportFactory.h.
References FairMQTransportFactory::CreateMessage(), and FairMQTransportFactory::FairMQNoCleanup().
TransportFactory fair::mq::ofi::TransportFactory::operator= (const TransportFactory &) delete
void fair::mq::ofi::TransportFactory::Resume () inline override virtual
Implements FairMQTransportFactory.
Definition at line 53 of file TransportFactory.h.
Member Data Documentation
Context fair::mq::ofi::TransportFactory::fContext mutable private
Definition at line 56 of file TransportFactory.h.
The documentation for this class was generated from the following files:
TransportFactory.h
TransportFactory.cxx