FairRoot: create_digis_mixed.C File Reference
create_digis_mixed.C File Reference
Functions
void create_digis_mixed ()
Function Documentation
create_digis_mixed()
void create_digis_mixed ()
for each ~20 entries background 1 entry from signal chain 1 will be read
for each ~30 entries background 1 entry from signal chain 2 will be read
Set the event mean time, event time will be a random number generated from (1/T)exp(-x/T)
each ~100 ns background 1 entry from signal chain 1 will be read
each ~60 ns background 1 entry from signal chain 2 will be read
Definition at line 1 of file create_digis_mixed.C.
References FairMixedSource::AddSignalFile(), FairRun::AddTask(), FairRunAna::BGWindowWidthTime(), FairRuntimeDb::getContainer(), FairSystemInfo::GetMaxMemory(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairRunAna::Init(), FairParAsciiFileIo::open(), FairParRootFileIo::open(), FairParSet::print(), FairRuntimeDb::print(), FairRunAna::Run(), FairRuntimeDb::saveOutput(), FairParSet::setChanged(), FairRunAna::SetEventMeanTime(), FairRuntimeDb::setFirstInput(), FairParSet::setInputVersion(), FairRuntimeDb::setOutput(), FairRuntimeDb::setSecondInput(), FairRun::SetSink(), and FairRunAna::SetSource().