FairRoot: g4Config.C File Reference
examples/common/gconfig/g4Config.C File Reference
Functions
void Config ()
Function Documentation
Config()
void Config ()
Create the run configuration In constructor user has to specify the geometry input and select geometry navigation via the following options:
geomVMCtoGeant4 - geometry defined via VMC, G4 native navigation
geomVMCtoRoot - geometry defined via VMC, Root navigation
geomRoot - geometry defined via Root, Root navigation
geomRootToGeant4 - geometry defined via Root, G4 native navigation
geomGeant4 - geometry defined via Geant4, G4 native navigation
The second argument in the constructor selects physics list:
emStandard - standard em physics (default)
emStandard+optical - standard em physics + optical physics
XYZ - selected hadron physics list (XYZ = LHEP, QGSP, ...)
XYZ+optical - selected hadron physics list + optical physics
The third argument activates the special processes in the TG4SpecialPhysicsList, which implement VMC features:
stepLimiter - step limiter (default)
specialCuts - VMC cuts
specialControls - VMC controls for activation/inactivation selected processes
stackPopper - stackPopper process When more than one options are selected, they should be separated with '+' character: eg. stepLimit+specialCuts.
Create the G4 VMC
create the Specific stack
Customise Geant4 setting (verbose level, global range cut, ..)
Definition at line 9 of file examples/common/gconfig/g4Config.C.
References FairRunSim::Instance(), FairRunSim::IsMT(), FairStack::SetMinPoints(), and FairStack::StoreSecondaries().