FairRoot: run_sim.C File Reference
examples/advanced/Tutorial3/macro/run_sim.C File Reference
Functions
void run_sim (Int_t nEvents=100, TString mcEngine="TGeant3")
Function Documentation
run_sim()
void run_sim (Int_t nEvents = 100, TString mcEngine = "TGeant3")
Definition at line 8 of file examples/advanced/Tutorial3/macro/run_sim.C.
References FairPrimaryGenerator::AddGenerator(), FairRunSim::AddModule(), FairRun::CreateGeometryFile(), FairSystemInfo::GetMaxMemory(), FairRun::GetRuntimeDb(), FairRunSim::Init(), kParameterMerged, FairParRootFileIo::open(), FairRuntimeDb::print(), FairRunSim::Run(), FairRuntimeDb::saveOutput(), FairBoxGenerator::SetCosTheta(), FairConstField::SetField(), FairRunSim::SetField(), FairConstField::SetFieldRegion(), FairRun::SetGenerateRunInfo(), FairRunSim::SetGenerator(), FairModule::SetGeometryFileName(), FairRunSim::SetMaterials(), FairRuntimeDb::setOutput(), FairBoxGenerator::SetPhiRange(), FairBoxGenerator::SetPRange(), FairRun::SetSink(), FairRunSim::SetStoreTraj(), FairBoxGenerator::SetThetaRange(), and FairRun::SetUseFairLinks().