FairRroot: eventDisplay.C File Reference
examples/simulation/rutherford/macros/eventDisplay.C File Reference
Functions
eventDisplay (TString mcEngine="TGeant3")
Function Documentation
eventDisplay (TString mcEngine = "TGeant3")
Definition at line 8 of file examples/simulation/rutherford/macros/eventDisplay.C.
References FairEventManager::AddTask(), FairRun::GetRuntimeDb(), FairEventManager::Init(), FairParRootFileIo::open(), rtdb, FairRuntimeDb::setFirstInput(), FairRun::SetOutputFile(), and FairRunAna::SetSource().