FairRoot: FairCuda.h File Reference
FairCuda.h File Reference
#include "../cuda_imp/HitTrk.h"
#include "Rtypes.h"
#include "TObject.h"
#include "iostream.h"
#include "TMatrixD.h"
Classes
class FairCuda
Functions
void IncrementArray (Int_t device)
void DeviceInfo ()
void CudaFilter (TMatrixD *h, TMatrixD *fM, TMatrixD *pull, TMatrixD *fH, TMatrixD *preC, TMatrixD *prea, TMatrixD *av, TMatrixD *curC, TMatrixD *fV, TMatrixD *fR, TMatrixD *fResVec, double *fDeltaChi2)
void CircleFitG (Double_t X[HIT], Double_t Y[HIT], Double_t Z[HIT], Double_t Zerr[HIT], Double_t *Mx, Double_t *My, Double_t *M0, Double_t result[8])
void CircleFitGAllD (Double_t X[TRK *HIT], Double_t Y[TRK *HIT], Double_t Z[TRK *HIT], Double_t Zerr[TRK *HIT], Double_t Mx[TRK], Double_t My[TRK], Double_t M0[TRK], Double_t result[8 *TRK])
void CircleFitGAllF (Float_t X[TRK *HIT], Float_t Y[TRK *HIT], Float_t Z[TRK *HIT], Float_t Zerr[TRK *HIT], Float_t Mx[TRK], Float_t My[TRK], Float_t M0[TRK], Float_t result[8 *TRK])
void CircleFitGF (Float_t X[HIT], Float_t Y[HIT], Float_t Z[HIT], Float_t Zerr[HIT], Float_t *Mx, Float_t *My, Float_t *M0, Float_t result[8])
Function Documentation
CircleFitG()
void CircleFitG (Double_t X[HIT], Double_t Y[HIT], Double_t Z[HIT], Double_t Zerr[HIT], Double_t * Mx, Double_t * My, Double_t * M0, Double_t result[8])
Referenced by FairCuda::CircleFit().
CircleFitGAllD()
void CircleFitGAllD (Double_t X[TRK *HIT], Double_t Y[TRK *HIT], Double_t Z[TRK *HIT], Double_t Zerr[TRK *HIT], Double_t Mx[TRK], Double_t My[TRK], Double_t M0[TRK], Double_t result[8 *TRK])
Referenced by FairCuda::CircleFitAllD().
CircleFitGAllF()
void CircleFitGAllF (Float_t X[TRK *HIT], Float_t Y[TRK *HIT], Float_t Z[TRK *HIT], Float_t Zerr[TRK *HIT], Float_t Mx[TRK], Float_t My[TRK], Float_t M0[TRK], Float_t result[8 *TRK])
Referenced by FairCuda::CircleFitAllF().
CircleFitGF()
void CircleFitGF (Float_t X[HIT], Float_t Y[HIT], Float_t Z[HIT], Float_t Zerr[HIT], Float_t * Mx, Float_t * My, Float_t * M0, Float_t result[8])
Referenced by FairCuda::CircleFitF().
CudaFilter()
void CudaFilter (TMatrixD * h, TMatrixD * fM, TMatrixD * pull, TMatrixD * fH, TMatrixD * preC, TMatrixD * prea, TMatrixD * av, TMatrixD * curC, TMatrixD * fV, TMatrixD * fR, TMatrixD * fResVec, double * fDeltaChi2)
Referenced by FairCuda::Filter().
DeviceInfo()
void DeviceInfo ()
Referenced by FairCuda::DeviceInfo_().
IncrementArray()
void IncrementArray (Int_t device)
Referenced by FairCuda::IncrementArray_().