FairRroot: fill_parameters.C File Reference
fill_parameters.C File Reference
Functions
parOut open ("mqexample7_param.root")
rtdb setOutput (parOut)
for (Int_t i=0;i< 100;i++)
rtdb saveOutput ()
rtdb print ()
Variables
FairRuntimeDb * rtdb = FairRuntimeDb::instance()
Bool_t kParameterMerged = kTRUE
FairParRootFileIo * parOut = new FairParRootFileIo(kParameterMerged)
FairMQExample7ParOne * par = static_cast<FairMQExample7ParOne*>(rtdb->getContainer("FairMQExample7ParOne"))
Function Documentation
for ()
Definition at line 13 of file fill_parameters.C.
References FairRuntimeDb::addRun(), FairParSet::setChanged(), FairMQExample7ParOne::SetValue(), and FairRuntimeDb::writeContainers().
parOut open ("mqexample7_param.root")
Referenced by FairRunIdGenerator::get_random_fd().
rtdb print ()
rtdb saveOutput ()
rtdb setOutput (parOut)
Variable Documentation
Bool_t kParameterMerged = kTRUE
Definition at line 4 of file fill_parameters.C.
Referenced by run_bg(), run_rad(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), run_tutorial2(), run_tutorial4(), and unpack_mbs().
FairMQExample7ParOne* par = static_cast<FairMQExample7ParOne*>(rtdb->getContainer("FairMQExample7ParOne"))
Definition at line 11 of file fill_parameters.C.
Referenced by ClassImp(), FairMQExample7Client::ConditionalRun(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), FairGeoRootBuilder::createNode(), FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), FairRunAnaProof::InitContainers(), FairRunOnline::InitContainers(), NewDetector::Initialize(), FairTutorialDet4::Initialize(), FairModule::ProcessNodes(), FairGeoOldAsciiIo::read(), ParameterMQServer::Run(), FairTutorialDet2::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), and FairTutorialDet4::SetSensitiveVolumes().
FairParRootFileIo* parOut = new FairParRootFileIo(kParameterMerged)
Definition at line 5 of file fill_parameters.C.
Referenced by ParameterMQServer::InitTask(), run_bg(), run_rad(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), run_tutorial2(), run_tutorial4(), and unpack_mbs().
FairRuntimeDb* rtdb = FairRuntimeDb::instance()
Definition at line 2 of file fill_parameters.C.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), NewDetector::ConstructGeometry(), Pixel::ConstructGeometry(), create_digis(), create_digis_mixed(), eventDisplay(), FairConstField::FillParContainer(), FairContFact::getContainer(), FairParSet::init(), FairAnaSelector::Init(), NewDetector::Initialize(), FairTestDetector::Initialize(), FairTutorialDet4::Initialize(), FairMQSampler< Task >::InitTask(), plots(), FairModule::ProcessNodes(), read_digis(), FairTutorialDet2Digitizer::ReInit(), FairTutorialDet4HitProducerIdealMisalign::ReInit(), run_bg(), run_dAsciiSource(), run_dBinSource(), run_digi(), run_digi_timebased(), run_digiToAscii(), run_digiToBin(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_hits(), run_hits_sep(), run_rad(), run_reco(), run_reco_timebased(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tracks(), run_tutorial1(), run_tutorial1_mesh(), run_tutorial1_pythia6(), run_tutorial1_pythia8(), run_tutorial1_urqmd(), run_tutorial2(), run_tutorial4(), FairTutorialDet2Digitizer::SetParContainers(), FairTutorialDet4PointDraw::SetParContainers(), FairTutorialDet4HitProducerIdealMisalign::SetParContainers(), FairTutorialDet4::SetParContainers(), FairTutorialDet2::SetSensitiveVolumes(), FairRutherford::SetSensitiveVolumes(), FairTutorialDet1::SetSensitiveVolumes(), FairTutorialDet4::SetSensitiveVolumes(), and unpack_mbs().