FairRroot: loggerTest.cxx File Reference
loggerTest.cxx File Reference
#include <Logger.h>
#include <iostream>
#include <vector>
#include <thread>
Functions
void printEverySeverity ()
void printAllVerbositiesWithSeverity (Severity sev)
void silentlyPrintAllVerbositiesWithSeverity (Severity sev)
int main ()
Function Documentation
int main ()
Definition at line 70 of file loggerTest.cxx.
References fair::LogMetaData::file, fair::LogMetaData::func, fair::info, fair::LogMetaData::line, LOG, LOG_IF, fair::Logger::Logging(), printAllVerbositiesWithSeverity(), printEverySeverity(), fair::LogMetaData::process_name, fair::LogMetaData::severity, fair::LogMetaData::severity_name, silentlyPrintAllVerbositiesWithSeverity(), fair::LogMetaData::timestamp, and fair::LogMetaData::us.
void printAllVerbositiesWithSeverity (Severity sev)
Definition at line 38 of file loggerTest.cxx.
References printEverySeverity().
Referenced by main().
void printEverySeverity ()
Definition at line 21 of file loggerTest.cxx.
References fair::debug, fair::debug1, fair::debug2, fair::debug3, fair::debug4, fair::error, fair::info, LOG, fair::nolog, fair::state, fair::trace, and fair::warn.
Referenced by main(), printAllVerbositiesWithSeverity(), and silentlyPrintAllVerbositiesWithSeverity().
void silentlyPrintAllVerbositiesWithSeverity (Severity sev)
Definition at line 56 of file loggerTest.cxx.
References printEverySeverity().
Referenced by main().