FairRroot: fair::mq::test Namespace Reference
fair::mq::test Namespace Reference
Classes
class Dummy2Plugin
class DummyPlugin
class PairLeft
class PairRight
struct PluginServices
class PollIn
class PollOut
class Pub
class Pull
class Push
class Receiver
class Rep
class Req
class Sender
class Sub
class TestVersion
class TransferTimeout
Functions
auto DummyPluginProgramOptions () -> Plugin::ProgOptions
auto control (std::shared_ptr< FairMQDevice > device) -> void
Variables
string runTestDevice = "/Users/turany/development/FairRoot/build/bin/testhelper_runTestDevice"
string mqConfig = "/Users/turany/development/FairRoot/build/bin/testsuite_FairMQ.IOPatterns_config.json"
Path to test device executable.
Function Documentation
auto fair::mq::test::control (std::shared_ptr< FairMQDevice > device) -> void inline
Definition at line 25 of file Fixture.h.
References FairMQStateMachine::END, FairMQStateMachine::INIT_DEVICE, and FairMQStateMachine::RESET_DEVICE.
Referenced by FairGeoOldAsciiIo::read(), FairMbsSource::Unpack(), unpack_mbs(), and fair::mq::test::PluginServices::~PluginServices().
auto fair::mq::test::DummyPluginProgramOptions () -> Plugin::ProgOptions
Definition at line 52 of file dummy.h.
Variable Documentation
std::string fair::mq::test::mqConfig = "/Users/turany/development/FairRoot/build/bin/testsuite_FairMQ.IOPatterns_config.json"
Path to test device executable.
Definition at line 26 of file build/fairmq/test/protocols/runner.cxx.
std::string fair::mq::test::runTestDevice = "/Users/turany/development/FairRoot/build/bin/testhelper_runTestDevice"
Definition at line 25 of file build/fairmq/test/protocols/runner.cxx.