FairRroot: fair::mq::parser::Helper Namespace Reference
fair::mq::parser::Helper Namespace Reference
Functions
void PrintDeviceList (const boost::property_tree::ptree &tree)
void DeviceParser (const boost::property_tree::ptree &tree, FairMQMap &channelMap, const string &deviceId)
void ChannelParser (const boost::property_tree::ptree &tree, FairMQMap &channelMap)
void SocketParser (const boost::property_tree::ptree &tree, vector< FairMQChannel > &channelList, const string &channelName, const FairMQChannel &commonChannel)
void PrintPropertyTree (const boost::property_tree::ptree &tree, int level)
void DeviceParser (const boost::property_tree::ptree &tree, FairMQMap &channelMap, const std::string &deviceId)
void SocketParser (const boost::property_tree::ptree &tree, std::vector< FairMQChannel > &channelList, const std::string &channelName, const FairMQChannel &commonChannel)
Function Documentation
void fair::mq::parser::Helper::ChannelParser (const boost::property_tree::ptree & tree, FairMQMap & channelMap)
Definition at line 133 of file FairMQParser.cxx.
References fair::debug, LOG, SocketParser(), and FairMQChannel::UpdateType().
Referenced by DeviceParser().
void fair::mq::parser::Helper::DeviceParser (const boost::property_tree::ptree & tree, FairMQMap & channelMap, const std::string & deviceId)
void fair::mq::parser::Helper::DeviceParser (const boost::property_tree::ptree & tree, FairMQMap & channelMap, const string & deviceId)
Definition at line 92 of file FairMQParser.cxx.
References ChannelParser(), fair::debug, and LOG.
Referenced by fair::mq::parser::ptreeToMQMap().
void fair::mq::parser::Helper::PrintDeviceList (const boost::property_tree::ptree & tree)
Definition at line 65 of file FairMQParser.cxx.
References fair::debug, and LOG.
void fair::mq::parser::Helper::PrintPropertyTree (const boost::property_tree::ptree & tree, int level)
Definition at line 263 of file FairMQParser.cxx.
void fair::mq::parser::Helper::SocketParser (const boost::property_tree::ptree & tree, std::vector< FairMQChannel > & channelList, const std::string & channelName, const FairMQChannel & commonChannel)
void fair::mq::parser::Helper::SocketParser (const boost::property_tree::ptree & tree, vector< FairMQChannel > & channelList, const string & channelName, const FairMQChannel & commonChannel)
Definition at line 195 of file FairMQParser.cxx.
References fair::debug, FairMQChannel::GetAddress(), FairMQChannel::GetMethod(), FairMQChannel::GetRateLogging(), FairMQChannel::GetRcvBufSize(), FairMQChannel::GetRcvKernelSize(), FairMQChannel::GetSndBufSize(), FairMQChannel::GetSndKernelSize(), FairMQChannel::GetTransport(), FairMQChannel::GetType(), LOG, FairMQChannel::UpdateAddress(), FairMQChannel::UpdateMethod(), FairMQChannel::UpdateRateLogging(), FairMQChannel::UpdateRcvBufSize(), FairMQChannel::UpdateRcvKernelSize(), FairMQChannel::UpdateSndBufSize(), FairMQChannel::UpdateSndKernelSize(), FairMQChannel::UpdateTransport(), and FairMQChannel::UpdateType().
Referenced by ChannelParser().