var namespaceTestDetectorProto_1_1protobuf__FairTestDetectorPayload__2eproto =
[
    [ "TableStruct", "structTestDetectorProto_1_1protobuf__FairTestDetectorPayload__2eproto_1_1TableStruct.html", "structTestDetectorProto_1_1protobuf__FairTestDetectorPayload__2eproto_1_1TableStruct" ]
];