FairRroot: TestDetectorFlat Namespace Reference
TestDetectorFlat Namespace Reference
Classes
struct DigiBuilder
struct DigiPayloadBuilder
struct FLATBUFFERS_FINAL_CLASS
struct HitBuilder
struct HitPayloadBuilder
Functions
flatbuffers::Offset< Digi > CreateDigi (flatbuffers::FlatBufferBuilder &_fbb, int32_t x=0, int32_t y=0, int32_t z=0, double timestamp=0.0, double timestampError=0.0)
flatbuffers::Offset< DigiPayload > CreateDigiPayload (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< Digi >>> digis=0)
flatbuffers::Offset< DigiPayload > CreateDigiPayloadDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< flatbuffers::Offset< Digi >> *digis=nullptr)
const TestDetectorFlat::DigiPayload * GetDigiPayload (const void *buf)
bool VerifyDigiPayloadBuffer (flatbuffers::Verifier &verifier)
void FinishDigiPayloadBuffer (flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset< TestDetectorFlat::DigiPayload > root)
flatbuffers::Offset< Hit > CreateHit (flatbuffers::FlatBufferBuilder &_fbb, int32_t detID=0, int32_t mcIndex=0, double x=0.0, double y=0.0, double z=0.0, double dx=0.0, double dy=0.0, double dz=0.0, double timestamp=0.0, double timestampError=0.0)
flatbuffers::Offset< HitPayload > CreateHitPayload (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< Hit >>> hits=0)
flatbuffers::Offset< HitPayload > CreateHitPayloadDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< flatbuffers::Offset< Hit >> *hits=nullptr)
const TestDetectorFlat::HitPayload * GetHitPayload (const void *buf)
bool VerifyHitPayloadBuffer (flatbuffers::Verifier &verifier)
void FinishHitPayloadBuffer (flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset< TestDetectorFlat::HitPayload > root)
Function Documentation
flatbuffers::Offset<Digi> TestDetectorFlat::CreateDigi (flatbuffers::FlatBufferBuilder & _fbb, int32_t x = 0, int32_t y = 0, int32_t z = 0, double timestamp = 0.0, double timestampError = 0.0) inline
Definition at line 79 of file FairTestDetectorPayloadDigi_generated.h.
References TestDetectorFlat::DigiBuilder::add_timestamp(), TestDetectorFlat::DigiBuilder::add_timestampError(), TestDetectorFlat::DigiBuilder::add_x(), TestDetectorFlat::DigiBuilder::add_y(), TestDetectorFlat::DigiBuilder::add_z(), and TestDetectorFlat::DigiBuilder::Finish().
flatbuffers::Offset<DigiPayload> TestDetectorFlat::CreateDigiPayload (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< Digi >>> digis = 0) inline
Definition at line 129 of file FairTestDetectorPayloadDigi_generated.h.
References TestDetectorFlat::DigiPayloadBuilder::add_digis(), and TestDetectorFlat::DigiPayloadBuilder::Finish().
Referenced by CreateDigiPayloadDirect().
flatbuffers::Offset<DigiPayload> TestDetectorFlat::CreateDigiPayloadDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< flatbuffers::Offset< Digi >> * digis = nullptr) inline
Definition at line 137 of file FairTestDetectorPayloadDigi_generated.h.
References CreateDigiPayload().
flatbuffers::Offset<Hit> TestDetectorFlat::CreateHit (flatbuffers::FlatBufferBuilder & _fbb, int32_t detID = 0, int32_t mcIndex = 0, double x = 0.0, double y = 0.0, double z = 0.0, double dx = 0.0, double dy = 0.0, double dz = 0.0, double timestamp = 0.0, double timestampError = 0.0) inline
Definition at line 119 of file FairTestDetectorPayloadHit_generated.h.
References TestDetectorFlat::HitBuilder::add_detID(), TestDetectorFlat::HitBuilder::add_dx(), TestDetectorFlat::HitBuilder::add_dy(), TestDetectorFlat::HitBuilder::add_dz(), TestDetectorFlat::HitBuilder::add_mcIndex(), TestDetectorFlat::HitBuilder::add_timestamp(), TestDetectorFlat::HitBuilder::add_timestampError(), TestDetectorFlat::HitBuilder::add_x(), TestDetectorFlat::HitBuilder::add_y(), TestDetectorFlat::HitBuilder::add_z(), and TestDetectorFlat::HitBuilder::Finish().
flatbuffers::Offset<HitPayload> TestDetectorFlat::CreateHitPayload (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< Hit >>> hits = 0) inline
Definition at line 179 of file FairTestDetectorPayloadHit_generated.h.
References TestDetectorFlat::HitPayloadBuilder::add_hits(), and TestDetectorFlat::HitPayloadBuilder::Finish().
Referenced by CreateHitPayloadDirect().
flatbuffers::Offset<HitPayload> TestDetectorFlat::CreateHitPayloadDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< flatbuffers::Offset< Hit >> * hits = nullptr) inline
Definition at line 187 of file FairTestDetectorPayloadHit_generated.h.
References CreateHitPayload().
void TestDetectorFlat::FinishDigiPayloadBuffer (flatbuffers::FlatBufferBuilder & fbb, flatbuffers::Offset< TestDetectorFlat::DigiPayload > root) inline
Definition at line 154 of file FairTestDetectorPayloadDigi_generated.h.
void TestDetectorFlat::FinishHitPayloadBuffer (flatbuffers::FlatBufferBuilder & fbb, flatbuffers::Offset< TestDetectorFlat::HitPayload > root) inline
Definition at line 204 of file FairTestDetectorPayloadHit_generated.h.
const TestDetectorFlat::DigiPayload* TestDetectorFlat::GetDigiPayload (const void * buf) inline
Definition at line 145 of file FairTestDetectorPayloadDigi_generated.h.
const TestDetectorFlat::HitPayload* TestDetectorFlat::GetHitPayload (const void * buf) inline
Definition at line 195 of file FairTestDetectorPayloadHit_generated.h.
bool TestDetectorFlat::VerifyDigiPayloadBuffer (flatbuffers::Verifier & verifier) inline
Definition at line 149 of file FairTestDetectorPayloadDigi_generated.h.
bool TestDetectorFlat::VerifyHitPayloadBuffer (flatbuffers::Verifier & verifier) inline
Definition at line 199 of file FairTestDetectorPayloadHit_generated.h.