FairRroot: fair::mq::tools Namespace Reference
fair::mq::tools Namespace Reference
Classes
struct execute_result
struct HashEnum
struct Version
Functions
template<typename T , typename... Args>
std::unique_ptr< T > make_unique (Args &&...args)
int getHostIPs (std::map< std::string, std::string > &addressMap)
std::string getInterfaceIP (std::string interface)
std::string getDefaultRouteNetworkInterface ()
execute_result execute (std::string cmd, std::string prefix="")
template<typename... T>
auto ToString (T &&...t) -> std::string
concatenates a variable number of args with the << operator via a stringstream
auto ToStrVector (const int argc, char *const argv[], const bool dropProgramName=true) -> std::vector< std::string >
convert command line arguments from main function to vector of strings
std::string Uuid ()
std::size_t UuidHash ()
Function Documentation
execute_result fair::mq::tools::execute (std::string cmd, std::string prefix = "") inline
Execute given command in forked process and capture stdout output and exit code.
Parameters
[in] cmd Command to execute
[in] log_prefix How to prefix each captured output line with
Returns
Captured stdout output and exit code
Definition at line 40 of file Process.h.
References fair::mq::tools::execute_result::console_out, and fair::mq::tools::execute_result::exit_code.
std::string fair::mq::tools::getDefaultRouteNetworkInterface () inline
Definition at line 92 of file Network.h.
References fair::debug, fair::error, and LOG.
Referenced by FairMQDevice::InitWrapper().
int fair::mq::tools::getHostIPs (std::map< std::string, std::string > & addressMap) inline
Definition at line 39 of file Network.h.
Referenced by getInterfaceIP().
std::string fair::mq::tools::getInterfaceIP (std::string interface) inline
Definition at line 76 of file Network.h.
References fair::error, getHostIPs(), and LOG.
Referenced by FairMQDevice::InitWrapper().
template<typename T , typename... Args> std::unique_ptr<T> fair::mq::tools::make_unique (Args &&... args)
Definition at line 25 of file CppSTL.h.
template<typename... T> auto fair::mq::tools::ToString (T &&... t) -> std::string
concatenates a variable number of args with the << operator via a stringstream
Parameters
t objects to be concatenated
Returns
concatenated string
Definition at line 28 of file Strings.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), FairTestDetectorDigiWriteoutBuffer::AddNewDataToTClonesArray(), fair::mq::ofi::Socket::AnnounceDataAddress(), fair::mq::ofi::Socket::BindControlSocket(), FairMQDevice::BindEndpoint(), fair::mq::PluginServices::ChangeDeviceState(), fair::mq::ofi::Socket::Close(), fair::mq::ofi::Socket::ConnectControlSocket(), fair::mq::ofi::Context::Context(), fair::mq::ofi::Context::ConvertAddress(), fair::mq::ofi::Context::CreateOfiCompletionQueue(), fair::mq::ofi::Context::CreateOfiEndpoint(), fair::mq::plugins::DDS::FillChannelContainers(), fair::mq::ofi::Context::GetBoostVersion(), fair::mq::ofi::Socket::GetOption(), fair::mq::PluginServices::GetProperty(), fair::mq::PluginServices::GetPropertyAsString(), fair::mq::ofi::Context::GetZmqVersion(), fair::mq::ofi::Socket::InitDataEndpoint(), fair::mq::ofi::Context::InitOfi(), FairMQDevice::InitWrapper(), fair::mq::ofi::Context::InsertAddressVector(), fair::mq::PluginManager::InstantiatePlugins(), fair::mq::PluginManager::LoadPluginDynamic(), fair::mq::PluginManager::LoadPluginPrelinkedDynamic(), fair::mq::PluginManager::LoadPluginStatic(), fair::mq::PluginManager::LoadSymbols(), FairMQDevice::LogSocketRates(), fair::mq::PluginManager::MakeFromCommandLineOptions(), fair::mq::ofi::Context::OpenOfiAddressVector(), fair::mq::ofi::Context::OpenOfiDomain(), fair::mq::ofi::Context::OpenOfiEventQueue(), fair::mq::ofi::Context::OpenOfiFabric(), fair::mq::ofi::Poller::Poll(), fair::mq::ofi::Socket::ReceiveControlMessage(), fair::mq::ofi::Socket::ReceiveImpl(), fair::mq::PluginServices::ReleaseDeviceControl(), fair::mq::ofi::Socket::SendControlMessage(), fair::mq::ofi::Socket::SendImpl(), fair::mq::ofi::Socket::SetOption(), fair::mq::PluginServices::SetProperty(), FairMQDevice::SortChannel(), fair::mq::PluginServices::TakeDeviceControl(), fair::mq::StateMachine::Transition(), fair::mq::PluginManager::ValidateSearchPath(), and fair::mq::ofi::Socket::WaitForControlPeer().
auto fair::mq::tools::ToStrVector (const int argc, char *const argv[], const bool dropProgramName = true) -> std::vector<std::string> inline
convert command line arguments from main function to vector of strings
Definition at line 36 of file Strings.h.
Referenced by fair::mq::DeviceRunner::DeviceRunner().
std::string fair::mq::tools::Uuid () inline
Definition at line 27 of file Unique.h.
Referenced by FairMQTransportFactory::CreateTransportFactory(), and main().
std::size_t fair::mq::tools::UuidHash () inline
Definition at line 35 of file Unique.h.
Referenced by main().