var NAVTREE =
[
  [ "FairRoot", "index.html", [
    [ "Alignment Module in FairRoot", "d6/db4/md__Users_turany_development_FairRoot_alignment_readme.html", null ],
    [ "event", "dc/d64/md__Users_turany_development_FairRoot_base_event_README.html", null ],
    [ "field", "d8/dd7/md__Users_turany_development_FairRoot_base_field_README.html", null ],
    [ "Message Queue", "d8/dfe/md__Users_turany_development_FairRoot_base_MQ_README.html", null ],
    [ "base", "da/dda/md__Users_turany_development_FairRoot_base_README.html", null ],
    [ "sim", "d2/df9/md__Users_turany_development_FairRoot_base_sim_README.html", null ],
    [ "source", "d6/d51/md__Users_turany_development_FairRoot_base_source_README.html", null ],
    [ "steer", "d1/d1a/md__Users_turany_development_FairRoot_base_steer_README.html", null ],
    [ "cmake", "d7/dc7/md__Users_turany_development_FairRoot_cmake_README.html", null ],
    [ "datamatch", "df/d57/md__Users_turany_development_FairRoot_datamatch_README.html", null ],
    [ "Generating Doxygen documentation", "d6/de6/md__Users_turany_development_FairRoot_doxygen_README.html", null ],
    [ "eventdisplay", "d4/dca/md__Users_turany_development_FairRoot_eventdisplay_README.html", null ],
    [ "MBS Tutorial", "dd/d30/md__Users_turany_development_FairRoot_examples_advanced_MbsTutorial_README.html", null ],
    [ "Advanced examples", "d2/d88/md__Users_turany_development_FairRoot_examples_advanced_README.html", null ],
    [ "Tutorial 3 - Message Queue part", "d1/d82/md__Users_turany_development_FairRoot_examples_advanced_Tutorial3_MQ_README.html", null ],
    [ "Data Format", "d0/d76/md__Users_turany_development_FairRoot_examples_advanced_Tutorial3_MQ_run_README.html", null ],
    [ "Tutorial3", "dc/db6/md__Users_turany_development_FairRoot_examples_advanced_Tutorial3_README.html", null ],
    [ "common", "d2/d03/md__Users_turany_development_FairRoot_examples_common_README.html", null ],
    [ "MQ tutorial : Lmd Sampler", "d4/d40/md__Users_turany_development_FairRoot_examples_MQ_Lmd_README.html", null ],
    [ "Example 7: Communicating with ParameterMQServer", "d0/d91/md__Users_turany_development_FairRoot_examples_MQ_parameters_README.html", null ],
    [ "Move from root to FairMQ continued", "d5/d42/md__Users_turany_development_FairRoot_examples_MQ_pixelAlternative_README.html", null ],
    [ "Move from root to FairMQ", "de/d90/md__Users_turany_development_FairRoot_examples_MQ_pixelDetector_README.html", null ],
    [ "MC simulations in FairMQ", "df/d95/md__Users_turany_development_FairRoot_examples_MQ_pixelSimSplit_README.html", null ],
    [ "FairMQ Examples", "d6/db0/md__Users_turany_development_FairRoot_examples_MQ_README.html", null ],
    [ "Serialization Examples", "d0/d7d/md__Users_turany_development_FairRoot_examples_MQ_serialization_README.html", null ],
    [ "Examples", "dc/db6/md__Users_turany_development_FairRoot_examples_README.html", null ],
    [ "Examples", "df/d6b/md__Users_turany_development_FairRoot_examples_simulation_README.html", null ],
    [ "Tutorial1:", "da/d06/md__Users_turany_development_FairRoot_examples_simulation_Tutorial1_README.html", null ],
    [ "Tutorial2", "df/d33/md__Users_turany_development_FairRoot_examples_simulation_Tutorial2_README.html", null ],
    [ "Tutorial4", "d7/daa/md__Users_turany_development_FairRoot_examples_simulation_Tutorial4_README.html", null ],
    [ "MC Step Logger", "d8/dfd/md__Users_turany_development_FairRoot_fairtools_MCStepLogger_README.html", null ],
    [ "fairtools", "d2/db0/md__Users_turany_development_FairRoot_fairtools_README.html", null ],
    [ "geane", "df/dea/md__Users_turany_development_FairRoot_geane_README.html", null ],
    [ "generators", "dc/dc0/md__Users_turany_development_FairRoot_generators_README.html", null ],
    [ "geobase", "db/df9/md__Users_turany_development_FairRoot_geobase_README.html", null ],
    [ "MbsAPI", "d0/d7c/md__Users_turany_development_FairRoot_MbsAPI_README.html", null ],
    [ "parbase", "dd/d5f/md__Users_turany_development_FairRoot_parbase_README.html", null ],
    [ "ParameterMQServer", "df/d44/md__Users_turany_development_FairRoot_parmq_README.html", null ],
    [ "scripts", "d5/db3/md__Users_turany_development_FairRoot_scripts_README.html", null ],
    [ "templates", "d9/dd8/md__Users_turany_development_FairRoot_templates_README.html", null ],
    [ "test", "de/d14/md__Users_turany_development_FairRoot_test_README.html", null ],
    [ "trackbase", "d4/d71/md__Users_turany_development_FairRoot_trackbase_README.html", null ],
    [ "Namespaces", null, [
      [ "Namespace List", "namespaces.html", "namespaces" ],
      [ "Namespace Members", "namespacemembers.html", [
        [ "All", "namespacemembers.html", "namespacemembers_dup" ],
        [ "Functions", "namespacemembers_func.html", "namespacemembers_func" ],
        [ "Variables", "namespacemembers_vars.html", null ],
        [ "Typedefs", "namespacemembers_type.html", null ]
      ] ]
    ] ],
    [ "Classes", null, [
      [ "Class List", "annotated.html", "annotated" ],
      [ "Class Index", "classes.html", null ],
      [ "Class Hierarchy", "hierarchy.html", "hierarchy" ],
      [ "Class Members", "functions.html", [
        [ "All", "functions.html", "functions_dup" ],
        [ "Functions", "functions_func.html", "functions_func" ],
        [ "Variables", "functions_vars.html", "functions_vars" ],
        [ "Typedefs", "functions_type.html", null ],
        [ "Enumerations", "functions_enum.html", null ],
        [ "Enumerator", "functions_eval.html", null ],
        [ "Related Functions", "functions_rela.html", null ]
      ] ]
    ] ],
    [ "Files", null, [
      [ "File List", "files.html", "files" ],
      [ "File Members", "globals.html", [
        [ "All", "globals.html", "globals_dup" ],
        [ "Functions", "globals_func.html", "globals_func" ],
        [ "Variables", "globals_vars.html", null ],
        [ "Typedefs", "globals_type.html", null ],
        [ "Enumerations", "globals_enum.html", null ],
        [ "Enumerator", "globals_eval.html", null ],
        [ "Macros", "globals_defs.html", "globals_defs" ]
      ] ]
    ] ]
  ] ]
];

var NAVTREEINDEX =
[
"annotated.html",
"d0/d6c/classFairRootManager.html#a5ea0291b93286afa616c1123d3fd2c8f",
"d0/dc1/NewDetector__stl__containers_2NewDetectorGeoPar_8cxx.html#adb8c9b1e596f279b958d11641e2129bf",
"d1/d22/xbuild_2examples_2simulation_2Tutorial1_2src_2G____Tutorial1_8cxx.html#ac6b1de1be2e7189183eec176e8e9da2f",
"d1/d8e/xbuild_2examples_2advanced_2Tutorial3_2FairTestDetectorPayloadHit__generated_8h.html#a5982512330d3514e0037331ce8010765",
"d1/de3/classFairMCMatchLoaderTask.html#a159508c2287455582fd3b46fd902d012",
"d2/d60/classFairFileSource.html#a3f5fefa8e2ff796d740862ccd525c432",
"d2/d88/classFairWriteoutBuffer.html#aa4ef1b37628687d60fabb0e96c883e19",
"d2/df9/FairTestDetectorGeoPar_8h_source.html",
"d3/d61/classFairStack.html#a2efb116aaf4a4a52a59eec9028a2efe4",
"d3/dac/xbuild_2geane_2G____Geane_8cxx.html#a103d9f389ee705e8cba5d2ddc87ac03c",
"d4/d03/classFairMQPixelTaskProcessorBin.html#a4312633162d9cfaafbe2f64124ea6950",
"d4/d79/classFairGeoAsciiIo.html#a985fe15a0b87347cb6af55d9ec2a49b1",
"d4/df6/FairTimeStampPointDraw_8cxx.html#afa6ddf29ac95e8f97e9bcaa3d960659a",
"d5/d52/classFairGeoPcon.html#a12323828e47db2ededfb21a00d338e22",
"d5/d9e/classFairMQPixelMerger.html#add3b86b4fafcd3bf3520fd1c222fb6ba",
"d6/d0c/classFairDetector.html#a24f05fefbef13070d8fddb47b82940fc",
"d6/d73/FairTrajFilter_8h.html",
"d6/db4/FairGeoTarget_8cxx_source.html",
"d6/de6/classTestDetectorProto_1_1HitPayload.html#ace3429876f4a9c3499676cf1f40cb14e",
"d7/d5d/classPixelFitTracks.html",
"d7/db6/structTestDetectorFlat_1_1FLATBUFFERS__FINAL__CLASS.html#a76c210c26ec6695fda85fec4375d27a1",
"d8/d2e/FairTestDetectorDigiSorterTask_8cxx_source.html",
"d8/daf/classFairMCSplitEventHeader.html#a97d4769a6bfe50d97f0e96c76f2aae26",
"d8/df1/classFairMultiLinkedData__Interface.html#a94ba4360f4c094275d0986455a50561a",
"d9/d4c/classFairMCMatchCreatorTask.html#a1c0d76b77a89c48d884127b45f38cf81",
"d9/d93/classFairTutorialDet4StraightLineFitter.html#a4dc173b84bb60c2fd0def604a5489426",
"da/d0b/xbuild_2trackbase_2G____TrkBase_8cxx.html#a71bd71db45f07d59f6ed8fede824b658",
"da/d5b/classFairTestDetectorDigi.html#a5f234acf5ae9b54e8a56c37c75ac66c7",
"da/df3/FairPrintFairLinks_8h.html",
"db/d6d/classMyProjStack.html#addb8e7e360734128daf4e96581286f08",
"db/d89/buildx_2examples_2simulation_2Tutorial4_2src_2G____Tutorial4_8cxx.html#ab28bca06958781959c30b28a78f752ef",
"db/dfe/FairSink_8cxx_source.html",
"dc/d50/classFairTrajFilter.html#a6b7745dbb480794e8fd38ad4302a3e2e",
"dc/ddd/classFairField.html#aca6f36773450e05aff57e8dc80e5dfac",
"dd/d59/classFairTutorialDet1.html#a2356eaea5b732e73a7bf4118d31cbd30",
"dd/d8f/classFairMCEventHeader.html#a8e3db74943a3b74eb397d4034b6d96a4",
"dd/dd6/project__stl__containers_2MyProjData_2MyProjMCTrack_8h_source.html",
"de/d0e/project__stl__containers_2passive_2MyPassiveContFact_8h.html",
"de/d55/classPythia8Generator.html#a0e02d13911bdc97f07817b0e5435fba4",
"de/da5/PixelHit_8cxx.html",
"de/df4/buildx_2examples_2advanced_2Tutorial3_2FairTestDetectorPayload_8pb_8h.html#ab3b37dfc79fb9da80f5acc02fb56bae8",
"df/d48/FairRunAnaProof_8cxx.html",
"df/dbe/classFairGeoSphe.html#a9c467a8992435a935d941f1540bd57c7",
"df/dea/md__Users_turany_development_FairRoot_geane_README.html",
"dir_e28a4c5016971a8267350b49e7ac6dd4.html"
];

var SYNCONMSG = 'click to disable panel synchronisation';
var SYNCOFFMSG = 'click to enable panel synchronisation';