FairRroot: plots.C File Reference
plots.C File Reference
Functions
plots (Int_t nEvents=1000, Int_t iout=1, TString mcEngine="TGeant3")
Function Documentation
plots (Int_t nEvents = 1000, Int_t iout = 1, TString mcEngine = "TGeant3")
Definition at line 8 of file plots.C.
References FairRunAna::AddFriend(), FairHit::GetDy(), FairSystemInfo::GetMaxMemory(), FairRun::GetOutputFile(), FairHit::GetRefIndex(), FairRun::GetRuntimeDb(), FairHit::GetX(), FairHit::GetY(), FairHit::GetZ(), FairParRootFileIo::open(), rtdb, FairRuntimeDb::setFirstInput(), FairRun::SetOutputFile(), and FairRunAna::SetSource().