FairRroot: PluginManager.cxx File Reference
PluginManager.cxx File Reference
#include <fairmq/PluginManager.h>
#include <fairmq/Tools.h>
#include <boost/program_options.hpp>
#include <algorithm>
#include <iterator>
#include <memory>
#include <sstream>
#include <string>
#include <utility>
Functions
fPluginFactories ()
fPlugins ()
fPluginOrder ()
fPluginProgOptions ()
fPluginServices ()
Function Documentation
fPluginFactories ()
Referenced by fair::mq::PluginManager::InstantiatePlugin(), fair::mq::PluginManager::LoadPluginDynamic(), fair::mq::PluginManager::LoadPluginPrelinkedDynamic(), and fair::mq::PluginManager::LoadPluginStatic().
fPluginOrder ()
Referenced by fair::mq::PluginManager::InstantiatePlugins(), fair::mq::PluginManager::LoadPluginDynamic(), fair::mq::PluginManager::LoadPluginPrelinkedDynamic(), and fair::mq::PluginManager::LoadPluginStatic().
fPluginProgOptions ()
fPlugins ()
Referenced by fair::mq::PluginManager::InstantiatePlugin().
fPluginServices ()
Definition at line 36 of file PluginManager.cxx.