FairRoot: read_parameters.C File Reference
read_parameters.C File Reference
Functions
parOut open ("mq_ex_params.root")
rtdb setFirstInput (parOut)
for (Int_t i=0;i< 100;i++)
Variables
Bool_t kParameterMerged = kTRUE
FairParRootFileIo * parOut = new FairParRootFileIo(kParameterMerged)
FairMQExParamsParOne * par = static_cast<FairMQExParamsParOne*>(rtdb->getContainer("FairMQExParamsParOne"))
Function Documentation
for()
for ()
Definition at line 13 of file read_parameters.C.
References FairRuntimeDb::initContainers(), par, and FairMQExParamsParOne::print().
open()
parOut open ("mq_ex_params.root")
setFirstInput()
rtdb setFirstInput (parOut)
Variable Documentation
kParameterMerged
Bool_t kParameterMerged = kTRUE
Definition at line 4 of file read_parameters.C.
par
FairMQExParamsParOne* par = static_cast<FairMQExParamsParOne*>(rtdb->getContainer("FairMQExParamsParOne"))
Definition at line 11 of file read_parameters.C.
Referenced by for().
parOut
FairParRootFileIo* parOut = new FairParRootFileIo(kParameterMerged)
Definition at line 5 of file read_parameters.C.