FairRoot: run_tutorial1_pythia6.C File Reference
run_tutorial1_pythia6.C File Reference
Functions
void run_tutorial1_pythia6 (Int_t nEvents=10, TString mcEngine="TGeant3")
Function Documentation
run_tutorial1_pythia6()
void run_tutorial1_pythia6 (Int_t nEvents = 10, TString mcEngine = "TGeant3")
Definition at line 8 of file run_tutorial1_pythia6.C.
References FairPrimaryGenerator::AddGenerator(), FairRunSim::AddModule(), FairRun::CreateGeometryFile(), FairSystemInfo::GetMaxMemory(), FairRun::GetRuntimeDb(), FairRunSim::Init(), kParameterMerged, FairParRootFileIo::open(), parOut, FairRuntimeDb::print(), FairRunSim::Run(), FairRuntimeDb::saveOutput(), FairBoxGenerator::SetDebug(), FairRunSim::SetGenerator(), FairModule::SetGeometryFileName(), FairRunSim::SetMaterials(), FairRuntimeDb::setOutput(), FairBoxGenerator::SetPhiRange(), FairBoxGenerator::SetPRange(), FairRunSim::SetPythiaDecayer(), FairRun::SetSink(), and FairBoxGenerator::SetThetaRange().