FairRroot: run_reco_timebased.C File Reference
run_reco_timebased.C File Reference
Functions
void run_reco_timebased (TString mcEngine="TGeant3")
Function Documentation
void run_reco_timebased (TString mcEngine = "TGeant3")
Definition at line 8 of file run_reco_timebased.C.
References FairRun::AddTask(), FairLogger::GetLogger(), FairSystemInfo::GetMaxMemory(), FairRun::GetRuntimeDb(), FairRunAna::Init(), FairParRootFileIo::open(), rtdb, FairRunAna::Run(), FairRunAna::RunWithTimeStamps(), FairRuntimeDb::setFirstInput(), FairLogger::SetLogFileName(), FairRun::SetOutputFile(), and FairRun::SetUseFairLinks().