FairRroot: run_sim_sep.C File Reference
run_sim_sep.C File Reference
Functions
void run_sim_sep (Int_t fileId, Int_t nEvents=1000, TString mcEngine="TGeant3")
Function Documentation
void run_sim_sep (Int_t fileId, Int_t nEvents = 1000, TString mcEngine = "TGeant3")
Definition at line 1 of file run_sim_sep.C.
References FairPrimaryGenerator::AddGenerator(), FairRunSim::AddModule(), FairRun::CreateGeometryFile(), FairSystemInfo::GetMaxMemory(), FairRun::GetRuntimeDb(), FairRunSim::Init(), kParameterMerged, FairParRootFileIo::open(), FairRuntimeDb::print(), rtdb, FairRunSim::Run(), FairRuntimeDb::saveOutput(), FairBoxGenerator::SetCosTheta(), FairConstField::SetField(), FairRunSim::SetField(), FairConstField::SetFieldRegion(), FairRunSim::SetGenerator(), FairModule::SetGeometryFileName(), FairRunSim::SetMaterials(), FairRuntimeDb::setOutput(), FairRun::SetOutputFile(), FairBoxGenerator::SetPhiRange(), FairBoxGenerator::SetPRange(), FairRunSim::SetStoreTraj(), and FairBoxGenerator::SetThetaRange().