FairRroot: run_DiReOne.C File Reference
run_DiReOne.C File Reference
Functions
void run_DiReOne (TString mcEngine="TGeant3")
Function Documentation
void run_DiReOne (TString mcEngine = "TGeant3")
Definition at line 1 of file run_DiReOne.C.
References FairRun::AddTask(), FairLogger::GetLogger(), FairSystemInfo::GetMaxMemory(), FairRun::GetRuntimeDb(), FairRunAna::Init(), FairParRootFileIo::open(), rtdb, FairRunAna::Run(), FairRuntimeDb::setFirstInput(), FairLogger::SetLogVerbosityLevel(), FairRun::SetOutputFile(), and FairRunAna::SetSource().