FairRroot: run_sg1.C File Reference
run_sg1.C File Reference
Functions
void run_sg1 (Int_t nEvents=20)
Function Documentation
void run_sg1 (Int_t nEvents = 20)
Definition at line 1 of file run_sg1.C.
References FairPrimaryGenerator::AddGenerator(), FairRunSim::AddModule(), FairSystemInfo::GetMaxMemory(), FairRun::GetRuntimeDb(), FairRunSim::Init(), kParameterMerged, FairParRootFileIo::open(), parOut, FairRuntimeDb::print(), rtdb, FairRunSim::Run(), FairRuntimeDb::saveOutput(), FairRunSim::SetGenerator(), FairModule::SetGeometryFileName(), FairRunSim::SetMaterials(), FairRuntimeDb::setOutput(), FairRun::SetOutputFile(), FairBoxGenerator::SetPhiRange(), FairBoxGenerator::SetPRange(), and FairBoxGenerator::SetThetaRange().