FairRroot: run_dBinSource.C File Reference
run_dBinSource.C File Reference
Functions
void run_dBinSource (TString mcEngine="TGeant3")
Function Documentation
void run_dBinSource (TString mcEngine = "TGeant3")
Definition at line 8 of file run_dBinSource.C.
References FairRun::AddTask(), FairSystemInfo::GetMaxMemory(), FairRun::GetRuntimeDb(), FairRunAna::Init(), FairParAsciiFileIo::open(), FairParRootFileIo::open(), rtdb, FairRunAna::Run(), FairRun::SetEventHeader(), FairRuntimeDb::setFirstInput(), PixelDigiBinSource::SetInputFileName(), FairRun::SetOutputFile(), FairRuntimeDb::setSecondInput(), and FairRunAna::SetSource().