FairRroot: run_rad.C File Reference
run_rad.C File Reference
Functions
void run_rad (Int_t nEvents=100, TString mcEngine="TGeant3")
Function Documentation
void run_rad (Int_t nEvents = 100, TString mcEngine = "TGeant3")
Definition at line 8 of file run_rad.C.
References FairPrimaryGenerator::AddGenerator(), FairRunSim::AddModule(), FairRun::CreateGeometryFile(), FairLogger::GetLogger(), FairSystemInfo::GetMaxMemory(), FairRun::GetRuntimeDb(), FairRunSim::Init(), FairTrajFilter::Instance(), kParameterMerged, FairParRootFileIo::open(), parOut, FairRuntimeDb::print(), rtdb, FairRunSim::Run(), FairRuntimeDb::saveOutput(), FairRunSim::SetGenerator(), FairModule::SetGeometryFileName(), FairLogger::SetLogFileName(), FairLogger::SetLogToFile(), FairLogger::SetLogToScreen(), FairLogger::SetLogVerbosityLevel(), FairRunSim::SetMaterials(), FairRuntimeDb::setOutput(), FairRun::SetOutputFile(), FairBoxGenerator::SetPhiRange(), FairBoxGenerator::SetPRange(), FairRunSim::SetRadLenRegister(), FairTrajFilter::SetStorePrimaries(), FairTrajFilter::SetStoreSecondaries(), FairRunSim::SetStoreTraj(), FairBoxGenerator::SetThetaRange(), and FairBoxGenerator::SetXYZ().