FairRroot: runConfigEx.cxx File Reference
runConfigEx.cxx File Reference
#include "FairMQLogger.h"
#include "FairMQProgOptions.h"
#include "FairMQDevice.h"
#include <exception>
#include <string>
#include <vector>
#include <unordered_map>
Classes
class MyDevice
Typedefs
using FairMQMap = unordered_map< string, vector< FairMQChannel >>
Functions
void MyCallBack (MyDevice &d, double val)
int main (int argc, char **argv)
Typedef Documentation
using FairMQMap = unordered_map<string, vector<FairMQChannel>>
Definition at line 25 of file runConfigEx.cxx.
Function Documentation
int main (int argc, char ** argv)
Definition at line 62 of file runConfigEx.cxx.
References FairMQDevice::fChannels, FairProgOptions::GetCmdLineOptions(), MyDevice::GetRate(), FairProgOptions::GetValue(), LOG, FairMQProgOptions::ParseAll(), FairMQDevice::SetConfig(), MyDevice::SetRate(), FairMQProgOptions::Subscribe(), FairMQProgOptions::Unsubscribe(), and FairMQProgOptions::UpdateValue().
void MyCallBack (MyDevice & d, double val)
Definition at line 56 of file runConfigEx.cxx.
References MyDevice::Print(), and MyDevice::SetRate().