FairRroot: runFairMQDevice.h File Reference
runFairMQDevice.h File Reference
#include <fairmq/DeviceRunner.h>
#include <boost/program_options.hpp>
#include <memory>
#include <string>
Typedefs
using FairMQDevicePtr = FairMQDevice *
Functions
FairMQDevicePtr getDevice (const FairMQProgOptions &config)
void addCustomOptions (boost::program_options::options_description &)
int main (int argc, char *argv[])
Typedef Documentation
using FairMQDevicePtr = FairMQDevice*
Definition at line 14 of file runFairMQDevice.h.
Function Documentation
void addCustomOptions (boost::program_options::options_description &)
Referenced by main().
FairMQDevicePtr getDevice (const FairMQProgOptions & config)
Definition at line 21 of file runExampleRegionSampler.cxx.
References FairProgOptions::GetValue(), BaseMQFileSink< InputPolicy, OutputPolicy >::InitInputData(), and LOG.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 22 of file runFairMQDevice.h.
References addCustomOptions(), fair::mq::DeviceRunner::AddHook(), getDevice(), and LOG.