FairRroot: runMonitor.cxx File Reference
runMonitor.cxx File Reference
#include <fairmq/shmem/Monitor.h>
#include <boost/program_options.hpp>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <iostream>
#include <string>
Functions
static void daemonize ()
int main (int argc, char **argv)
Function Documentation
static void daemonize () static
Definition at line 24 of file runMonitor.cxx.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 66 of file runMonitor.cxx.
References fair::mq::shmem::Monitor::CatchSignals(), fair::mq::shmem::Monitor::Cleanup(), daemonize(), and fair::mq::shmem::Monitor::RemoveQueue().