FairRroot: TestDetectorFlat::DigiBuilder Struct Reference
TestDetectorFlat::DigiBuilder Struct Reference
#include <FairTestDetectorPayloadDigi_generated.h>
Public Member Functions
void add_x (int32_t x)
void add_y (int32_t y)
void add_z (int32_t z)
void add_timestamp (double timestamp)
void add_timestampError (double timestampError)
DigiBuilder (flatbuffers::FlatBufferBuilder &_fbb)
DigiBuilder & operator= (const DigiBuilder &)
flatbuffers::Offset< Digi > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 49 of file FairTestDetectorPayloadDigi_generated.h.
Constructor & Destructor Documentation
TestDetectorFlat::DigiBuilder::DigiBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline
Definition at line 67 of file FairTestDetectorPayloadDigi_generated.h.
Member Function Documentation
void TestDetectorFlat::DigiBuilder::add_timestamp (double timestamp) inline
Definition at line 61 of file FairTestDetectorPayloadDigi_generated.h.
Referenced by TestDetectorFlat::CreateDigi().
void TestDetectorFlat::DigiBuilder::add_timestampError (double timestampError) inline
Definition at line 64 of file FairTestDetectorPayloadDigi_generated.h.
Referenced by TestDetectorFlat::CreateDigi().
void TestDetectorFlat::DigiBuilder::add_x (int32_t x) inline
Definition at line 52 of file FairTestDetectorPayloadDigi_generated.h.
Referenced by TestDetectorFlat::CreateDigi().
void TestDetectorFlat::DigiBuilder::add_y (int32_t y) inline
Definition at line 55 of file FairTestDetectorPayloadDigi_generated.h.
Referenced by TestDetectorFlat::CreateDigi().
void TestDetectorFlat::DigiBuilder::add_z (int32_t z) inline
Definition at line 58 of file FairTestDetectorPayloadDigi_generated.h.
Referenced by TestDetectorFlat::CreateDigi().
flatbuffers::Offset<Digi> TestDetectorFlat::DigiBuilder::Finish () inline
Definition at line 72 of file FairTestDetectorPayloadDigi_generated.h.
Referenced by TestDetectorFlat::CreateDigi().
DigiBuilder& TestDetectorFlat::DigiBuilder::operator= (const DigiBuilder &)
Member Data Documentation
flatbuffers::FlatBufferBuilder& TestDetectorFlat::DigiBuilder::fbb_
Definition at line 50 of file FairTestDetectorPayloadDigi_generated.h.
flatbuffers::uoffset_t TestDetectorFlat::DigiBuilder::start_
Definition at line 51 of file FairTestDetectorPayloadDigi_generated.h.
The documentation for this struct was generated from the following file:
FairTestDetectorPayloadDigi_generated.h