FairRroot: SerializerEx2 Struct Reference
SerializerEx2 Struct Reference
#include <SerializerExample2.h>
Public Member Functions
void Serialize (FairMQMessage &msg, TClonesArray *input)
void Deserialize (FairMQMessage &msg, Ex2Header *&header)
void Deserialize (FairMQMessage &msg, TClonesArray *&output)
Detailed Description
Definition at line 41 of file SerializerExample2.h.
Member Function Documentation
void SerializerEx2::Deserialize (FairMQMessage & msg, Ex2Header *& header) inline
Definition at line 50 of file SerializerExample2.h.
References FairMQMessage::GetData().
void SerializerEx2::Deserialize (FairMQMessage & msg, TClonesArray *& output) inline
Definition at line 55 of file SerializerExample2.h.
References FairMQMessage::GetData(), and FairMQMessage::GetSize().
void SerializerEx2::Serialize (FairMQMessage & msg, TClonesArray * input) inline
Definition at line 43 of file SerializerExample2.h.
References free_tmessage(), and FairMQMessage::Rebuild().
The documentation for this struct was generated from the following file:
SerializerExample2.h