FairRroot: TestDetectorFlat::HitBuilder Struct Reference
TestDetectorFlat::HitBuilder Struct Reference
#include <FairTestDetectorPayloadHit_generated.h>
Public Member Functions
void add_detID (int32_t detID)
void add_mcIndex (int32_t mcIndex)
void add_x (double x)
void add_y (double y)
void add_z (double z)
void add_dx (double dx)
void add_dy (double dy)
void add_dz (double dz)
void add_timestamp (double timestamp)
void add_timestampError (double timestampError)
HitBuilder (flatbuffers::FlatBufferBuilder &_fbb)
HitBuilder & operator= (const HitBuilder &)
flatbuffers::Offset< Hit > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 74 of file FairTestDetectorPayloadHit_generated.h.
Constructor & Destructor Documentation
TestDetectorFlat::HitBuilder::HitBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline
Definition at line 107 of file FairTestDetectorPayloadHit_generated.h.
Member Function Documentation
void TestDetectorFlat::HitBuilder::add_detID (int32_t detID) inline
Definition at line 77 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_dx (double dx) inline
Definition at line 92 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_dy (double dy) inline
Definition at line 95 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_dz (double dz) inline
Definition at line 98 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_mcIndex (int32_t mcIndex) inline
Definition at line 80 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_timestamp (double timestamp) inline
Definition at line 101 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_timestampError (double timestampError) inline
Definition at line 104 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_x (double x) inline
Definition at line 83 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_y (double y) inline
Definition at line 86 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
void TestDetectorFlat::HitBuilder::add_z (double z) inline
Definition at line 89 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
flatbuffers::Offset<Hit> TestDetectorFlat::HitBuilder::Finish () inline
Definition at line 112 of file FairTestDetectorPayloadHit_generated.h.
Referenced by TestDetectorFlat::CreateHit().
HitBuilder& TestDetectorFlat::HitBuilder::operator= (const HitBuilder &)
Member Data Documentation
flatbuffers::FlatBufferBuilder& TestDetectorFlat::HitBuilder::fbb_
Definition at line 75 of file FairTestDetectorPayloadHit_generated.h.
flatbuffers::uoffset_t TestDetectorFlat::HitBuilder::start_
Definition at line 76 of file FairTestDetectorPayloadHit_generated.h.
The documentation for this struct was generated from the following file:
FairTestDetectorPayloadHit_generated.h