FairRroot: fair::mq::fsm::FairMQFSM Struct Reference
fair::mq::fsm::FairMQFSM Struct Reference
#include <FairMQStateMachine.h>
Classes
struct DEVICE_READY_FSM
struct DeviceReadyFct
struct ERROR_FSM
struct ErrorFoundFct
struct EXITING_FSM
struct ExitingFct
struct IDLE_FSM
struct IdleFct
struct InitDeviceFct
struct INITIALIZING_DEVICE_FSM
struct INITIALIZING_TASK_FSM
struct InitTaskFct
struct InternalStopFct
struct OK_FSM
struct PAUSED_FSM
struct PauseFct
struct READY_FSM
struct ReadyFct
struct ResetDeviceFct
struct ResetTaskFct
struct RESETTING_DEVICE_FSM
struct RESETTING_TASK_FSM
struct ResumeFct
struct RunFct
struct RUNNING_FSM
struct StopFct
struct transition_table
Public Types
enum State {
OK, Error, IDLE, INITIALIZING_DEVICE,
DEVICE_READY, INITIALIZING_TASK, READY, RUNNING,
PAUSED, RESETTING_TASK, RESETTING_DEVICE, EXITING
}
using initial_state = boost::mpl::vector< IDLE_FSM, OK_FSM >
Public Member Functions
FairMQFSM ()
virtual ~FairMQFSM ()
template<typename Event , typename FSM >
void on_entry (Event const &, FSM &fsm)
template<typename Event , typename FSM >
void on_exit (Event const &, FSM &)
template<typename FSM , typename Event >
void no_transition (Event const &e, FSM &, int state)
std::string GetCurrentStateName () const
int GetCurrentState () const
bool CheckCurrentState (int state) const
bool CheckCurrentState (std::string state) const
virtual void InitWrapper ()
virtual void InitTaskWrapper ()
virtual void RunWrapper ()
virtual void PauseWrapper ()
virtual void ResetWrapper ()
virtual void ResetTaskWrapper ()
virtual void Exit ()
virtual void Unblock ()
bool Terminated ()
Static Public Member Functions
static std::string GetStateName (const int state)
Protected Member Functions
void CallStateChangeCallbacks (const State state) const
Protected Attributes
std::atomic< State > fState
std::mutex fChangeStateMutex
std::function< void(void)> fWork
std::condition_variable fWorkAvailableCondition
std::condition_variable fWorkDoneCondition
std::mutex fWorkMutex
bool fWorkerTerminated
bool fWorkActive
bool fWorkAvailable
boost::signals2::signal< void(const State)> fStateChangeSignal
std::unordered_map< std::string, boost::signals2::connection > fStateChangeSignalsMap
std::atomic< bool > fTerminationRequested
Private Member Functions
void Worker ()
Private Attributes
std::thread fWorkerThread
Detailed Description
Definition at line 77 of file FairMQStateMachine.h.
Member Typedef Documentation
using fair::mq::fsm::FairMQFSM::initial_state = boost::mpl::vector<IDLE_FSM, OK_FSM>
Definition at line 132 of file FairMQStateMachine.h.
Member Enumeration Documentation
enum fair::mq::fsm::FairMQFSM::State
Enumerator
OK
Error
IDLE
INITIALIZING_DEVICE
DEVICE_READY
INITIALIZING_TASK
READY
RUNNING
PAUSED
RESETTING_TASK
RESETTING_DEVICE
EXITING
Definition at line 414 of file FairMQStateMachine.h.
Constructor & Destructor Documentation
fair::mq::fsm::FairMQFSM::FairMQFSM () inline
Definition at line 80 of file FairMQStateMachine.h.
virtual fair::mq::fsm::FairMQFSM::~FairMQFSM () inline virtual
Definition at line 96 of file FairMQStateMachine.h.
Member Function Documentation
void fair::mq::fsm::FairMQFSM::CallStateChangeCallbacks (const State state) const inline protected
Definition at line 512 of file FairMQStateMachine.h.
References fStateChangeSignal.
Referenced by Worker().
bool fair::mq::fsm::FairMQFSM::CheckCurrentState (int state) const inline
Definition at line 471 of file FairMQStateMachine.h.
References fState.
bool fair::mq::fsm::FairMQFSM::CheckCurrentState (std::string state) const inline
Definition at line 475 of file FairMQStateMachine.h.
References GetCurrentStateName().
virtual void fair::mq::fsm::FairMQFSM::Exit () inline virtual
Definition at line 487 of file FairMQStateMachine.h.
int fair::mq::fsm::FairMQFSM::GetCurrentState () const inline
Definition at line 467 of file FairMQStateMachine.h.
References fState.
std::string fair::mq::fsm::FairMQFSM::GetCurrentStateName () const inline
Definition at line 463 of file FairMQStateMachine.h.
References fState, and GetStateName().
Referenced by CheckCurrentState().
static std::string fair::mq::fsm::FairMQFSM::GetStateName (const int state) inline static
Definition at line 430 of file FairMQStateMachine.h.
References DEVICE_READY, Error, EXITING, IDLE, INITIALIZING_DEVICE, INITIALIZING_TASK, OK, PAUSED, READY, RESETTING_DEVICE, RESETTING_TASK, and RUNNING.
Referenced by GetCurrentStateName().
virtual void fair::mq::fsm::FairMQFSM::InitTaskWrapper () inline virtual
Definition at line 482 of file FairMQStateMachine.h.
Referenced by fair::mq::fsm::FairMQFSM::InitTaskFct::operator()().
virtual void fair::mq::fsm::FairMQFSM::InitWrapper () inline virtual
Definition at line 481 of file FairMQStateMachine.h.
Referenced by fair::mq::fsm::FairMQFSM::InitDeviceFct::operator()().
template<typename FSM , typename Event > void fair::mq::fsm::FairMQFSM::no_transition (Event const & e, FSM & , int state) inline
Definition at line 387 of file FairMQStateMachine.h.
References LOG.
template<typename Event , typename FSM > void fair::mq::fsm::FairMQFSM::on_entry (Event const & , FSM & fsm) inline
Definition at line 100 of file FairMQStateMachine.h.
References fState, IDLE, LOG, fair::state, and Worker().
template<typename Event , typename FSM > void fair::mq::fsm::FairMQFSM::on_exit (Event const & , FSM &) inline
Definition at line 111 of file FairMQStateMachine.h.
References LOG, and fair::state.
virtual void fair::mq::fsm::FairMQFSM::PauseWrapper () inline virtual
Definition at line 484 of file FairMQStateMachine.h.
Referenced by fair::mq::fsm::FairMQFSM::PauseFct::operator()().
virtual void fair::mq::fsm::FairMQFSM::ResetTaskWrapper () inline virtual
Definition at line 486 of file FairMQStateMachine.h.
Referenced by fair::mq::fsm::FairMQFSM::ResetTaskFct::operator()().
virtual void fair::mq::fsm::FairMQFSM::ResetWrapper () inline virtual
Definition at line 485 of file FairMQStateMachine.h.
Referenced by fair::mq::fsm::FairMQFSM::ResetDeviceFct::operator()().
virtual void fair::mq::fsm::FairMQFSM::RunWrapper () inline virtual
Definition at line 483 of file FairMQStateMachine.h.
Referenced by fair::mq::fsm::FairMQFSM::RunFct::operator()(), and fair::mq::fsm::FairMQFSM::ResumeFct::operator()().
bool fair::mq::fsm::FairMQFSM::Terminated () inline
Definition at line 490 of file FairMQStateMachine.h.
References fTerminationRequested.
virtual void fair::mq::fsm::FairMQFSM::Unblock () inline virtual
Definition at line 488 of file FairMQStateMachine.h.
void fair::mq::fsm::FairMQFSM::Worker () inline private
Definition at line 521 of file FairMQStateMachine.h.
References CallStateChangeCallbacks(), and fWork.
Referenced by on_entry().
Member Data Documentation
std::mutex fair::mq::fsm::FairMQFSM::fChangeStateMutex protected
Definition at line 497 of file FairMQStateMachine.h.
std::atomic<State> fair::mq::fsm::FairMQFSM::fState protected
Definition at line 496 of file FairMQStateMachine.h.
Referenced by CheckCurrentState(), GetCurrentState(), GetCurrentStateName(), and on_entry().
boost::signals2::signal<void(const State)> fair::mq::fsm::FairMQFSM::fStateChangeSignal protected
Definition at line 508 of file FairMQStateMachine.h.
Referenced by CallStateChangeCallbacks().
std::unordered_map<std::string, boost::signals2::connection> fair::mq::fsm::FairMQFSM::fStateChangeSignalsMap protected
Definition at line 509 of file FairMQStateMachine.h.
std::atomic<bool> fair::mq::fsm::FairMQFSM::fTerminationRequested protected
Definition at line 510 of file FairMQStateMachine.h.
Referenced by Terminated().
std::function<void(void)> fair::mq::fsm::FairMQFSM::fWork protected
Definition at line 500 of file FairMQStateMachine.h.
Referenced by Worker().
bool fair::mq::fsm::FairMQFSM::fWorkActive protected
Definition at line 505 of file FairMQStateMachine.h.
bool fair::mq::fsm::FairMQFSM::fWorkAvailable protected
Definition at line 506 of file FairMQStateMachine.h.
std::condition_variable fair::mq::fsm::FairMQFSM::fWorkAvailableCondition protected
Definition at line 501 of file FairMQStateMachine.h.
std::condition_variable fair::mq::fsm::FairMQFSM::fWorkDoneCondition protected
Definition at line 502 of file FairMQStateMachine.h.
bool fair::mq::fsm::FairMQFSM::fWorkerTerminated protected
Definition at line 504 of file FairMQStateMachine.h.
std::thread fair::mq::fsm::FairMQFSM::fWorkerThread private
Definition at line 554 of file FairMQStateMachine.h.
std::mutex fair::mq::fsm::FairMQFSM::fWorkMutex protected
Definition at line 503 of file FairMQStateMachine.h.
The documentation for this struct was generated from the following file:
FairMQStateMachine.h