FairRroot: SerializerEx2Boost Struct Reference
SerializerEx2Boost Struct Reference
#include <SerializerExample2.h>
Public Types
using BoostBinArchIn = boost::archive::binary_iarchive
using BoostBinArchOut = boost::archive::binary_oarchive
Public Member Functions
void Serialize (FairMQMessage &msg, const Ex2Header &header)
void Deserialize (FairMQMessage &msg, Ex2Header &header)
void Serialize (FairMQMessage &msg, TClonesArray *input)
void Deserialize (FairMQMessage &msg, TClonesArray *input)
void Deserialize (FairMQMessage &msg, std::vector< MyHit > &input)
void Serialize (FairMQMessage &msg, const std::vector< MyHit > &DataVector)
Detailed Description
Definition at line 79 of file SerializerExample2.h.
Member Typedef Documentation
using SerializerEx2Boost::BoostBinArchIn = boost::archive::binary_iarchive
Definition at line 81 of file SerializerExample2.h.
using SerializerEx2Boost::BoostBinArchOut = boost::archive::binary_oarchive
Definition at line 82 of file SerializerExample2.h.
Member Function Documentation
void SerializerEx2Boost::Deserialize (FairMQMessage & msg, Ex2Header & header) inline
Definition at line 96 of file SerializerExample2.h.
References FairMQMessage::GetData(), and FairMQMessage::GetSize().
Referenced by Deserialize().
void SerializerEx2Boost::Deserialize (FairMQMessage & msg, TClonesArray * input) inline
Definition at line 123 of file SerializerExample2.h.
References Deserialize(), and LOG.
void SerializerEx2Boost::Deserialize (FairMQMessage & msg, std::vector< MyHit > & input) inline
Definition at line 144 of file SerializerExample2.h.
References FairMQMessage::GetData(), and FairMQMessage::GetSize().
void SerializerEx2Boost::Serialize (FairMQMessage & msg, const Ex2Header & header) inline
Definition at line 84 of file SerializerExample2.h.
References FairMQMessage::Rebuild().
Referenced by Serialize().
void SerializerEx2Boost::Serialize (FairMQMessage & msg, TClonesArray * input) inline
Definition at line 107 of file SerializerExample2.h.
References Serialize().
void SerializerEx2Boost::Serialize (FairMQMessage & msg, const std::vector< MyHit > & DataVector) inline
Definition at line 156 of file SerializerExample2.h.
References FairMQMessage::GetData(), and FairMQMessage::Rebuild().
The documentation for this struct was generated from the following file:
SerializerExample2.h