FairRroot: testMQoptions1.cxx File Reference
testMQoptions1.cxx File Reference
#include <iostream>
#include <string>
#include "boost/program_options.hpp"
#include "FairMQLogger.h"
#include "FairMQParser.h"
#include "FairMQProgOptions.h"
Functions
int testXML1 (FairMQProgOptions *config)
std
int testXML2 (FairMQProgOptions *config)
int testJSON1 (FairMQProgOptions *config)
int testJSON2 (FairMQProgOptions *config)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 89 of file testMQoptions1.cxx.
References FairProgOptions::AddToCmdLineOptions(), FairProgOptions::GetValue(), FairProgOptions::GetVarMap(), LOG, FairMQProgOptions::ParseAll(), testJSON1(), testJSON2(), testXML1(), and testXML2().
int testJSON1 (FairMQProgOptions * config)
Definition at line 53 of file testMQoptions1.cxx.
References FairProgOptions::GetValue(), and LOG.
Referenced by main().
int testJSON2 (FairMQProgOptions * config)
Definition at line 70 of file testMQoptions1.cxx.
References FairProgOptions::GetStringValue(), FairProgOptions::GetValue(), and LOG.
Referenced by main().
int testXML1 (FairMQProgOptions * config)
std
boost FairRoot/FairMQ
Definition at line 14 of file testMQoptions1.cxx.
References FairProgOptions::GetValue(), and LOG.
Referenced by main().
int testXML2 (FairMQProgOptions * config)
Definition at line 33 of file testMQoptions1.cxx.
References FairProgOptions::GetStringValue(), FairProgOptions::GetValue(), and LOG.
Referenced by main().