FairRoot: test.cxx File Reference
test.cxx File Reference
#include "FairLogger.h"
#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <vector>
#include <algorithm>
#include <numeric>
#include <unistd.h>
#include "TStopwatch.h"
Functions
void logToPrintf (int iterations)
void logToCout (int iterations)
void logToCerr (int iterations)
void logToLoggerPrintf (int iterations)
void logToLoggerCout (int iterations)
void logToLoggerCoutTest (int iterations)
void logTo (int)
void setSyncOutput (bool decision)
void PrintHelpAndExit ()
void doCalculation (std::vector< Double_t > rtime, std::vector< Double_t > ctime)
int main (int argc, char *argv[])
Function Documentation
doCalculation()
void doCalculation (std::vector< Double_t > rtime, std::vector< Double_t > ctime)
Definition at line 119 of file test.cxx.
Referenced by main().
logTo()
void logTo (int)
Definition at line 90 of file test.cxx.
logToCerr()
void logToCerr (int iterations)
Definition at line 56 of file test.cxx.
Referenced by main().
logToCout()
void logToCout (int iterations)
Definition at line 48 of file test.cxx.
Referenced by main().
logToLoggerCout()
void logToLoggerCout (int iterations)
Definition at line 73 of file test.cxx.
Referenced by main().
logToLoggerCoutTest()
void logToLoggerCoutTest (int iterations)
Definition at line 81 of file test.cxx.
Referenced by main().
logToLoggerPrintf()
void logToLoggerPrintf (int iterations)
Definition at line 64 of file test.cxx.
References gLogger, and MESSAGE_ORIGIN.
Referenced by main().
logToPrintf()
void logToPrintf (int iterations)
Definition at line 40 of file test.cxx.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 158 of file test.cxx.
References doCalculation(), logToCerr(), logToCout(), logToLoggerCout(), logToLoggerCoutTest(), logToLoggerPrintf(), logToPrintf(), PrintHelpAndExit(), and setSyncOutput().
PrintHelpAndExit()
void PrintHelpAndExit ()
Definition at line 105 of file test.cxx.
Referenced by main().
setSyncOutput()
void setSyncOutput (bool decision)
Definition at line 100 of file test.cxx.
Referenced by main().