FairRroot: unpack_mbs.C File Reference
unpack_mbs.C File Reference
Functions
void unpack_mbs ()
Function Documentation
void unpack_mbs ()
Definition at line 2 of file unpack_mbs.C.
References FairRunOnline::ActivateHttpServer(), FairLmdSource::AddFile(), FairRun::AddTask(), FairOnlineSource::AddUnpacker(), fair::mq::test::control(), FairMBSUnpack::GetNHitsTotal(), FairRun::GetRuntimeDb(), FairRunOnline::Init(), kParameterMerged, FairParRootFileIo::open(), parOut, FairRuntimeDb::print(), rtdb, FairRunOnline::Run(), FairRuntimeDb::saveOutput(), FairRunOnline::SetAutoFinish(), FairRuntimeDb::setOutput(), and FairRun::SetOutputFile().