FairRoot: _GTestFairToolsNew.cxx File Reference
_GTestFairToolsNew.cxx File Reference
#include "FairLogger.h"
#include "FairCaptureOutput.h"
#include "FairTestOutputHandler.h"
#include "gtest/gtest.h"
#include "gtest/gtest-spi.h"
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <algorithm>
#include <boost/regex.hpp>
Classes
class _TestFairLoggerBase< T >
class FairToolsTest
class LogLevelTest
class VerbosityLevelTest
Functions
TEST (FairToolsTestFatal, TestFatalError)
TEST_F (FairToolsTest, CheckDefaultSettings)
TEST_F (FairToolsTest, CheckOutputOnlyToFile)
TEST_F (FairToolsTest, CheckWrongLogLevelSettings)
TEST_F (FairToolsTest, CheckVerbosityLevelSettings)
TEST_F (FairToolsTest, testScreenAndFileOutputWithoutArgument)
TEST_P (LogLevelTest, testAllLogLevelsToScreenAndFile)
INSTANTIATE_TEST_CASE_P (TestAllLogLevels, LogLevelTest,::testing::ValuesIn(TestLogs))
TEST_P (VerbosityLevelTest, testAllVerbosityLevelsToScreenAndFile)
INSTANTIATE_TEST_CASE_P (TestAllVerbosityLevels, VerbosityLevelTest,::testing::ValuesIn(VerbosityLevelArray))
Variables
static const char *const LogString []
static const char *const TestLogs []
static const char *const VerbosityLevelArray [] = { "LOW", "MEDIUM", "HIGH"}
Function Documentation
INSTANTIATE_TEST_CASE_P (TestAllLogLevels , LogLevelTest , ::testing:: ValuesInTestLogs)
INSTANTIATE_TEST_CASE_P (TestAllVerbosityLevels , VerbosityLevelTest , ::testing:: ValuesInVerbosityLevelArray)
TEST (FairToolsTestFatal , TestFatalError)
Definition at line 35 of file _GTestFairToolsNew.cxx.
References FairLogger::endl(), FATAL, gLogger, LOG, and FairLogger::SetScreenStreamToCerr().
 {
   gLogger->SetScreenStreamToCerr(true);
   EXPECT_DEATH(LOG(FATAL) << "This is a fatal problem" << FairLogger::endl,
                "FATAL");
   // TODO: check if cored dump is written to file
 }
TEST_F (FairToolsTest , CheckDefaultSettings)
Definition at line 206 of file _GTestFairToolsNew.cxx.
 {
   handler.BeginCapture();
   LogNoArguments();
   handler.EndCapture();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
 }
TEST_F (FairToolsTest , CheckOutputOnlyToFile)
Definition at line 219 of file _GTestFairToolsNew.cxx.
References gLogger, FairLogger::SetLogFileName(), FairLogger::SetLogToFile(), and FairLogger::SetLogToScreen().
 {
   handler.BeginCapture();
   char fileName[25];
   tmpnam(fileName);
   gLogger->SetLogFileName(fileName);
   gLogger->SetLogToFile(true);
   gLogger->SetLogToScreen(false);
   LogNoArguments();
   handler.EndCapture();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   FairTestOutputHandler outputhandler(fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckFileOutput(v, outputhandler);
   }
 }
TEST_F (FairToolsTest , CheckWrongLogLevelSettings)
Definition at line 240 of file _GTestFairToolsNew.cxx.
References gLogger, FairLogger::SetLogScreenLevel(), FairLogger::SetLogToFile(), and FairLogger::SetLogToScreen().
 {
   gLogger->SetLogToFile(false);
   gLogger->SetLogToScreen(true);
   handler.BeginCapture();
   gLogger->SetLogScreenLevel("BLA");
   LogNoArguments();
   handler.EndCapture();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   std::string outString="[ERROR  ] Log level \"BLA\" not supported. Use default level \"INFO\".";
   std::vector<std::string>::iterator it;
   it = v.begin();
   it = v.insert ( it , outString );
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
 }
TEST_F (FairToolsTest , CheckVerbosityLevelSettings)
Definition at line 263 of file _GTestFairToolsNew.cxx.
References gLogger, FairLogger::SetLogToFile(), FairLogger::SetLogToScreen(), and FairLogger::SetLogVerbosityLevel().
 {
   gLogger->SetLogToFile(false);
   gLogger->SetLogToScreen(true);
   handler.BeginCapture();
   gLogger->SetLogVerbosityLevel("BLA");
   LogNoArguments();
   handler.EndCapture();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   std::string outString="[ERROR  ] Verbosity level \"BLA\" not supported. Use default level \"LOW\".";
   std::vector<std::string>::iterator it;
   it = v.begin();
   it = v.insert ( it , outString );
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
 }
TEST_F (FairToolsTest , testScreenAndFileOutputWithoutArgument)
Definition at line 288 of file _GTestFairToolsNew.cxx.
References gLogger, FairLogger::SetLogFileName(), FairLogger::SetLogToFile(), and FairLogger::SetLogToScreen().
 {
   handler.BeginCapture();
   char fileName[25];
   tmpnam(fileName);
   gLogger->SetLogFileName(fileName);
   gLogger->SetLogToScreen(true);
   gLogger->SetLogToFile(true);
   LogNoArguments();
   handler.EndCapture();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString, fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
   v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   FairTestOutputHandler outputhandler(fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckFileOutput(v, outputhandler);
   }
 }
TEST_P (LogLevelTest , testAllLogLevelsToScreenAndFile)
Definition at line 317 of file _GTestFairToolsNew.cxx.
References gLogger, FairLogger::SetLogFileLevel(), FairLogger::SetLogFileName(), FairLogger::SetLogScreenLevel(), FairLogger::SetLogToFile(), and FairLogger::SetLogToScreen().
 {
   gLogger->SetLogFileLevel(logLevelSettingToTest.c_str());
   gLogger->SetLogScreenLevel(logLevelSettingToTest.c_str());
   handler.BeginCapture();
   char fileName[25];
   tmpnam(fileName);
   gLogger->SetLogFileName(fileName);
   gLogger->SetLogToScreen(true);
   gLogger->SetLogToFile(true);
   LogNoArguments();
   handler.EndCapture();
   std::vector<std::string> v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString, fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckScreenOutput(v);
   }
   v = CreateExpectedOutputNoArguments(logLevelSettingToTest, OutputString);
   FairTestOutputHandler outputhandler(fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     CheckFileOutput(v, outputhandler);
   }
 }
TEST_P (VerbosityLevelTest , testAllVerbosityLevelsToScreenAndFile)
Definition at line 351 of file _GTestFairToolsNew.cxx.
References FairTestOutputHandler::GetCaptureLine(), gLogger, FairLogger::SetLogFileName(), FairLogger::SetLogToFile(), FairLogger::SetLogToScreen(), and FairLogger::SetLogVerbosityLevel().
 {
   gLogger->SetLogVerbosityLevel(verbosityLevel.c_str());
   handler.BeginCapture();
   char fileName[25];
   tmpnam(fileName);
   gLogger->SetLogFileName(fileName);
   gLogger->SetLogToScreen(true);
   gLogger->SetLogToFile(true);
   LogNoArguments();
   handler.EndCapture();
   std::vector<std::string> v = CreateExpectedLogLevels(logLevelSettingToTest);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     int Lines = v.size();
     for (int i = 0; i < Lines; ++i) {
       EXPECT_TRUE( CheckVerboseOutput( v[i], OutputString, verbosityLevel, handler.GetCaptureLine(i) ) );
     }
   }
   FairTestOutputHandler outputhandler(fileName);
   {
     SCOPED_TRACE(logLevelSettingToTest);
     int Lines = v.size();
     for (int i = 0; i < Lines; ++i) {
       EXPECT_TRUE( CheckVerboseOutput( v[i], OutputString, verbosityLevel, outputhandler.GetCaptureLine(i) ) );
     }
   }
 }
Variable Documentation
const char* const LogString[] static
Initial value:
= { "FATAL  ", "ERROR  ", "WARNING",
                                       "INFO   ", "DEBUG  ", "DEBUG1 ",
                                       "DEBUG2 ", "DEBUG3 ", "DEBUG4 "
                                       }
Definition at line 21 of file _GTestFairToolsNew.cxx.
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedOutputNoArguments().
const char* const TestLogs[] static
Initial value:
= { "ERROR", "WARNING",
                                        "INFO", "DEBUG", "DEBUG1",
                                        "DEBUG2", "DEBUG3", "DEBUG4"
                                      }
Definition at line 27 of file _GTestFairToolsNew.cxx.
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedLogLevels().
const char* const VerbosityLevelArray[] = { "LOW", "MEDIUM", "HIGH"} static
Definition at line 32 of file _GTestFairToolsNew.cxx.