FairRoot: FairMCMatchCreatorTask Class Reference
FairMCMatchCreatorTask Class Reference abstract
#include <FairMCMatchCreatorTask.h>
Public Member Functions
FairMCMatchCreatorTask ()
virtual ~FairMCMatchCreatorTask ()
virtual void SetParContainers ()
void SetPersistance (Bool_t pers)
Bool_t GetPersistance ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
virtual void Finish ()
virtual void InitDataStages ()=0
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
FairMCMatch * fMCMatch
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
InitStatus InitBranches ()
void Register ()
void Reset ()
void ProduceHits ()
FairMCMatchCreatorTask (const FairMCMatchCreatorTask &)
FairMCMatchCreatorTask & operator= (const FairMCMatchCreatorTask &)
ClassDef (FairMCMatchCreatorTask, 1)
Private Attributes
std::map< std::string, TClonesArray * > fBranches
Bool_t fPersistance
TClonesArray * fMCLink
Int_t fEventNr
Detailed Description
Definition at line 34 of file FairMCMatchCreatorTask.h.
Constructor & Destructor Documentation
FairMCMatchCreatorTask::FairMCMatchCreatorTask ()
Default constructor
Definition at line 28 of file FairMCMatchCreatorTask.cxx.
   : FairTask("Creates FairMCMatch"),
     fMCMatch(NULL),
     fBranches(),
     fPersistance(kTRUE),
     fMCLink(NULL),
     fEventNr(0)
 {
 }
FairMCMatchCreatorTask::~FairMCMatchCreatorTask () virtual
Destructor
Definition at line 41 of file FairMCMatchCreatorTask.cxx.
 {
 }
FairMCMatchCreatorTask::FairMCMatchCreatorTask (const FairMCMatchCreatorTask &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairMCMatchCreatorTask::ClassDef (FairMCMatchCreatorTask , 1) private
void FairMCMatchCreatorTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 104 of file FairMCMatchCreatorTask.cxx.
References FairMCMatch::ClearMCList(), fBranches, fMCLink, fMCMatch, fPersistance, FairTask::fVerbose, FairMCStage::GetBranchName(), FairMCStage::GetFill(), FairMCStage::GetLoaded(), FairMCObject::GetMCLink(), FairMCMatch::GetMCStage(), FairMCObject::GetNEntries(), FairMCMatch::GetNMCStages(), FairMCObject::GetStageId(), FairMCMatch::LoadInMCLists(), FairMCMatch::Print(), FairMCMatch::SetElements(), and FairMCStage::SetLoaded().
 {
   if (!fMCLink) { Fatal("Exec", "No fMCLinkDet"); }
   fMCLink->Delete();
   fMCMatch->ClearMCList();
   fMCMatch->LoadInMCLists(fMCLink);
   for (int i = 0; i < fMCMatch->GetNMCStages(); i++) {
     if (fMCMatch->GetMCStage(i)->GetFill() == kTRUE && fMCMatch->GetMCStage(i)->GetLoaded() == kFALSE) {
       TClonesArray* clArray = fBranches[fMCMatch->GetMCStage(i)->GetBranchName()];
       for (int j = 0; j < clArray->GetEntries(); j++) {
         FairMultiLinkedData* myData = (FairMultiLinkedData*)clArray->At(j);
         fMCMatch->SetElements(fMCMatch->GetMCStage(i)->GetStageId(), j, myData);
       }
       if (fMCMatch->GetMCStage(i)->GetNEntries() > 0) {
         fMCMatch->GetMCStage(i)->SetLoaded(kTRUE);
       }
     }
   }
   int i = 0;
   if (fPersistance) {
     for (int index = 0; index < fMCMatch->GetNMCStages(); index++) {
       FairMCStage myStage(*(fMCMatch->GetMCStage(index)));
       for (int indStage = 0; indStage < myStage.GetNEntries(); indStage++) {
         FairMCEntry myLink(myStage.GetMCLink(indStage));
         new((*fMCLink)[i]) FairMCEntry(myLink.GetLinks(), myLink.GetSource(), myLink.GetPos());
         i++;
       }
     }
   }
   if (fVerbose > 0) {
     fMCMatch->Print();
     std::cout << std::endl;
   }
 }
void FairMCMatchCreatorTask::Finish () virtual
Action after each event. To be implemented in the derived class
Reimplemented from FairTask.
Definition at line 145 of file FairMCMatchCreatorTask.cxx.
 {
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
Bool_t FairMCMatchCreatorTask::GetPersistance () inline
Definition at line 48 of file FairMCMatchCreatorTask.h.
References fPersistance.
 {return fPersistance;}
InitStatus FairMCMatchCreatorTask::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 46 of file FairMCMatchCreatorTask.cxx.
References fMCLink, fMCMatch, InitBranches(), InitDataStages(), FairRootManager::Instance(), kFATAL, and FairRootManager::Register().
 {
   fMCMatch = new FairMCMatch("FairMCMatch", "FairMCMatch");
   InitDataStages();
   InitStatus status = InitBranches();
   FairRootManager* ioman = FairRootManager::Instance();
   if (!ioman) {
     std::cout << "-E- FairMCMatchCreatorTask::Init: "
               << "RootManager not instantiated!" << std::endl;
     return kFATAL;
   }
   fMCLink = new TClonesArray("FairMCEntry");
   ioman->Register("MCLink", "MCInfo", fMCLink, kTRUE);
   ioman->Register("MCMatch", "MCInfo", fMCMatch, kFALSE);
   std::cout << "-I- FairMCMatchCreatorTask::Init: Initialization successfull" << std::endl;
   return status;
 }
InitStatus FairMCMatchCreatorTask::InitBranches () private
Definition at line 72 of file FairMCMatchCreatorTask.cxx.
References fBranches, fMCMatch, FairMCStage::GetBranchName(), FairMCMatch::GetMCStage(), FairMCMatch::GetNMCStages(), FairRootManager::GetObject(), FairRootManager::Instance(), kFATAL, kSUCCESS, and FairMCStage::SetFill().
Referenced by Init().
 {
   // Get RootManager
   FairRootManager* ioman = FairRootManager::Instance();
   if (!ioman) {
     std::cout << "-E- FairMCMatchCreatorTask::Init: "
               << "RootManager not instantiated!" << std::endl;
     return kFATAL;
   }
   int NStages = fMCMatch->GetNMCStages();
   for (int i = NStages-1; i > -1; i--) {
     TClonesArray* myBranch = (TClonesArray*)ioman->GetObject(fMCMatch->GetMCStage(i)->GetBranchName().c_str());
     if (!myBranch)  {
       //std::cout << "NMCStages: " << fMCMatch->GetNMCStages() << std::endl;
       std::cout << "-W- FairMCMatchCreatorTask::Init: "<< "No "<<fMCMatch->GetMCStage(i)->GetBranchName() << " array!" << std::endl;
       fMCMatch->GetMCStage(i)->SetFill(kFALSE); //RemoveStage(fMCMatch->GetMCStage(i)->GetStageId());
       continue;
     } else { fMCMatch->GetMCStage(i)->SetFill(kTRUE); }
     fBranches[fMCMatch->GetMCStage(i)->GetBranchName()] = myBranch;
   }
   return kSUCCESS;
 }
virtual void FairMCMatchCreatorTask::InitDataStages () pure virtual
Referenced by Init().
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairMCMatchCreatorTask& FairMCMatchCreatorTask::operator= (const FairMCMatchCreatorTask &) private
void FairMCMatchCreatorTask::ProduceHits () private
void FairMCMatchCreatorTask::Register () private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairMCMatchCreatorTask::Reset () private
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairMCMatchCreatorTask::SetParContainers () virtual
Virtual method Init
Reimplemented from FairTask.
Definition at line 99 of file FairMCMatchCreatorTask.cxx.
 {
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairMCMatchCreatorTask::SetPersistance (Bool_t pers) inline
Definition at line 47 of file FairMCMatchCreatorTask.h.
References fPersistance.
 {fPersistance = pers;}
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
std::map<std::string, TClonesArray*> FairMCMatchCreatorTask::fBranches private
Definition at line 65 of file FairMCMatchCreatorTask.h.
Referenced by Exec(), and InitBranches().
Int_t FairMCMatchCreatorTask::fEventNr private
Definition at line 68 of file FairMCMatchCreatorTask.h.
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
TClonesArray* FairMCMatchCreatorTask::fMCLink private
Definition at line 67 of file FairMCMatchCreatorTask.h.
Referenced by Exec(), and Init().
FairMCMatch* FairMCMatchCreatorTask::fMCMatch protected
Definition at line 61 of file FairMCMatchCreatorTask.h.
Referenced by Exec(), Init(), and InitBranches().
Bool_t FairMCMatchCreatorTask::fPersistance private
Definition at line 66 of file FairMCMatchCreatorTask.h.
Referenced by Exec(), GetPersistance(), and SetPersistance().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairMCMatchCreatorTask.h
FairMCMatchCreatorTask.cxx