FairRroot: runExampleServer.cxx File Reference
runExampleServer.cxx File Reference
#include <iostream>
#include <csignal>
#include "FairMQLogger.h"
#include "FairMQExampleServer.h"
#include "FairMQTransportFactoryZMQ.h"
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
int main (int argc, char **argv)
Variables
FairMQExampleServer server
Function Documentation
int main (int argc, char ** argv)
Definition at line 52 of file runExampleServer.cxx.
References FairMQStateMachine::BIND, FairMQStateMachine::ChangeState(), FairMQStateMachine::CONNECT, FairMQStateMachine::END, FairMQStateMachine::fRunningCondition, FairMQStateMachine::fRunningFinished, FairMQStateMachine::fRunningMutex, FairMQDevice::Id, INFO, FairMQStateMachine::INIT, FairMQDevice::InputAddress, FairMQDevice::InputMethod, FairMQDevice::InputRcvBufSize, FairMQDevice::InputSndBufSize, FairMQDevice::InputSocketType, LOG, FairMQDevice::NumInputs, FairMQDevice::NumIoThreads, FairMQDevice::NumOutputs, FairMQStateMachine::RUN, s_catch_signals(), FairMQStateMachine::SETINPUT, FairMQStateMachine::SETOUTPUT, FairMQDevice::SetProperty(), FairMQDevice::SetTransport(), and FairMQStateMachine::STOP.
 {
     s_catch_signals();
     LOG(INFO) << "PID: " << getpid();
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     server.SetTransport(transportFactory);
     server.SetProperty(FairMQExampleServer::Id, "server");
     server.SetProperty(FairMQExampleServer::NumIoThreads, 1);
     server.SetProperty(FairMQExampleServer::NumInputs, 1);
     server.SetProperty(FairMQExampleServer::NumOutputs, 0);
     server.ChangeState(FairMQExampleServer::INIT);
     server.SetProperty(FairMQExampleServer::InputSocketType, "rep", 0);
     server.SetProperty(FairMQExampleServer::InputSndBufSize, 10000, 0);
     server.SetProperty(FairMQExampleServer::InputRcvBufSize, 10000, 0);
     server.SetProperty(FairMQExampleServer::InputMethod, "bind", 0);
     server.SetProperty(FairMQExampleServer::InputAddress, "tcp://*:5005", 0);
     server.ChangeState(FairMQExampleServer::SETOUTPUT);
     server.ChangeState(FairMQExampleServer::SETINPUT);
     server.ChangeState(FairMQExampleServer::BIND);
     server.ChangeState(FairMQExampleServer::CONNECT);
     LOG(INFO) << "Listening for requests!";
     server.ChangeState(FairMQExampleServer::RUN);
     // wait until the running thread has finished processing.
     boost::unique_lock<boost::mutex> lock(server.fRunningMutex);
     while (!server.fRunningFinished)
     {
         server.fRunningCondition.wait(lock);
     }
     server.ChangeState(FairMQExampleServer::STOP);
     server.ChangeState(FairMQExampleServer::END);
     return 0;
 }
static void s_catch_signals (void) static
Definition at line 42 of file runExampleServer.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 31 of file runExampleServer.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, and FairMQStateMachine::STOP.
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     server.ChangeState(FairMQExampleServer::STOP);
     server.ChangeState(FairMQExampleServer::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
FairMQExampleServer server
Definition at line 29 of file runExampleServer.cxx.