FairRroot: FairMCStage Class Reference
FairMCStage Class Reference
#include <FairMCStage.h>
Public Member Functions
FairMCStage ()
FairMCStage (Int_t id, std::string fileName, std::string branchName, Double_t weight=1.0)
FairMCStage (const FairMCStage &mcStage)
FairMCStage & operator= (const FairMCStage &result)
virtual ~FairMCStage ()
void SetBranchName (std::string branchName)
void SetFileName (std::string fileName)
void SetWeight (Double_t weight)
void SetLoaded (Bool_t loaded)
void SetFill (Bool_t fill)
std::string GetBranchName (void) const
std::string GetFileName (void) const
Double_t GetWeight (void) const
Bool_t GetLoaded (void) const
Bool_t GetFill (void) const
virtual void ClearEntries ()
virtual void Print (std::ostream &out)
void SetStageId (Int_t type)
void SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index)
void SetEntry (FairMultiLinkedData *data, int index)
void SetEntry (FairMCEntry link)
void SetStage (std::vector< FairMCEntry > stage)
void SetLink (FairLink link, int index)
void AddLink (FairLink link, int index)
FairMCEntry GetEntry (int index) const
FairLink GetSingleLink (int entryIndex, int linkIndex) const
Int_t GetStageId (void) const
FairMCEntry GetMCLink (Int_t index)
int GetNEntries () const
int GetNLinks (int entryIndex) const
std::vector< FairMCEntry > GetEntryVector () const
FairMultiLinkedData PosInList (std::pair< int, int > link)
FairMultiLinkedData PosInList (FairLink link)
FairMultiLinkedData GetLinksWithType (Int_t type)
void RemoveType (Int_t type)
Private Member Functions
ClassDef (FairMCStage, 1)
Private Attributes
std::string fBranchName
std::string fFileName
Double_t fWeight
Bool_t fLoaded
indicates if this stage was loaded already from a Link file
Bool_t fFill
indicates if a corresponding DataFile with FairLinks exists to fill this stage
Friends
std::ostream & operator<< (std::ostream &out, const FairMCStage &stage)
Detailed Description
Definition at line 26 of file FairMCStage.h.
Constructor & Destructor Documentation
FairMCStage::FairMCStage ()
Definition at line 19 of file FairMCStage.cxx.
   : FairMCObject(),
     fFileName(""),
     fBranchName(""),
     fWeight(1.0),
     fLoaded(kFALSE),
     fFill(kFALSE)
 {
 }
FairMCStage::FairMCStage (Int_t id, std::string fileName, std::string branchName, Double_t weight = 1.0)
Definition at line 33 of file FairMCStage.cxx.
   : FairMCObject(id),
     fFileName(fileName),
     fBranchName(branchName),
     fWeight(weight),
     fLoaded(kFALSE),
     fFill(kFALSE)
 {
 }
FairMCStage::FairMCStage (const FairMCStage & mcStage) inline
Definition at line 32 of file FairMCStage.h.
       : FairMCObject(mcStage),
         fBranchName(mcStage.fBranchName),
         fFileName(mcStage.fFileName),
         fWeight(mcStage.fWeight),
         fLoaded(mcStage.fLoaded),
         fFill(mcStage.fFill) {
     }
FairMCStage::~FairMCStage () virtual
Definition at line 29 of file FairMCStage.cxx.
 {
 }
Member Function Documentation
void FairMCObject::AddLink (FairLink link, int index) inherited
Definition at line 66 of file FairMCObject.cxx.
References FairMCObject::AdoptSize(), and FairMCObject::fStage.
Referenced by FairMCObject::SetLink().
 {
   AdoptSize(index);
   fStage[index].AddLink(link);
 }
FairMCStage::ClassDef (FairMCStage , 1) private
virtual void FairMCStage::ClearEntries () inline virtual
Reimplemented from FairMCObject.
Definition at line 71 of file FairMCStage.h.
References FairMCObject::ClearEntries(), and fLoaded.
{
       FairMCObject::ClearEntries();
       fLoaded = kFALSE;
     }
std::string FairMCStage::GetBranchName (void) const inline
Definition at line 65 of file FairMCStage.h.
References fBranchName.
Referenced by FairMCMatchCreatorTask::Exec(), and FairMCMatchCreatorTask::InitBranches().
 {return fBranchName;}
FairMCEntry FairMCObject::GetEntry (int index) const inline inherited
Definition at line 73 of file FairMCObject.h.
References FairMCObject::fStage.
 {return fStage[index];}
std::vector<FairMCEntry> FairMCObject::GetEntryVector () const inline inherited
Definition at line 84 of file FairMCObject.h.
References FairMCObject::fStage.
 {return fStage;}
std::string FairMCStage::GetFileName (void) const inline
Definition at line 66 of file FairMCStage.h.
References fFileName.
 {return fFileName;}
Bool_t FairMCStage::GetFill (void) const inline
Definition at line 69 of file FairMCStage.h.
References fFill.
Referenced by FairMCMatchCreatorTask::Exec().
 {return fFill;}
FairMultiLinkedData FairMCObject::GetLinksWithType (Int_t type) inline inherited
Definition at line 89 of file FairMCObject.h.
References FairMultiLinkedData::AddLinks(), FairMCObject::GetMCLink(), and FairMCObject::GetNEntries().
{
       FairMultiLinkedData result;
       for (int i = 0; i < GetNEntries(); i++) {
         result.AddLinks(GetMCLink(i).GetLinksWithType(type));
       }
       return result;
     }
Bool_t FairMCStage::GetLoaded (void) const inline
Definition at line 68 of file FairMCStage.h.
References fLoaded.
Referenced by FairMCMatchCreatorTask::Exec().
 {return fLoaded;}
FairMCEntry FairMCObject::GetMCLink (Int_t index) inline inherited
Definition at line 80 of file FairMCObject.h.
References FairMCObject::fStage.
Referenced by FairMCMatchCreatorTask::Exec(), and FairMCObject::GetLinksWithType().
 {return fStage.at(index);}
int FairMCObject::GetNEntries () const inline inherited
Definition at line 82 of file FairMCObject.h.
References FairMCObject::fStage.
Referenced by FairMCMatchCreatorTask::Exec(), FairMCObject::GetLinksWithType(), FairMCMatch::GetMCInfoBackward(), and FairMCMatch::GetMCInfoForward().
 {return fStage.size();}
int FairMCObject::GetNLinks (int entryIndex) const inline inherited
Definition at line 83 of file FairMCObject.h.
References FairMCObject::fStage.
 {return fStage.at(entryIndex).GetNLinks();}
FairLink FairMCObject::GetSingleLink (int entryIndex, int linkIndex) const inline inherited
Definition at line 74 of file FairMCObject.h.
References FairMCObject::fStage.
{
       return fStage.at(entryIndex).GetLink(linkIndex);
     }
Int_t FairMCObject::GetStageId (void) const inline inherited
Definition at line 78 of file FairMCObject.h.
References FairMCObject::fStageId.
Referenced by FairMCObject::AdoptSize(), FairMCMatchCreatorTask::Exec(), FairMCMatch::GetMCInfoForward(), and FairMCObject::PosInList().
 {return fStageId;}
Double_t FairMCStage::GetWeight (void) const inline
Definition at line 67 of file FairMCStage.h.
References fWeight.
Referenced by FairMCMatch::GetMCInfoBackward(), and FairMCMatch::GetNextStage().
 {return fWeight;}
FairMCStage& FairMCStage::operator= (const FairMCStage & result) inline
Definition at line 41 of file FairMCStage.h.
References fBranchName, fFileName, fFill, fLoaded, fWeight, and FairMCObject::operator=().
{
       if (this == &result) { return *this; }
       FairMCObject::operator=(result);
       fBranchName = result.fBranchName;
       fFileName = result.fFileName;
       fWeight = result.fWeight;
       fLoaded = result.fLoaded;
       fFill = result.fFill;
       return *this;
     }
FairMultiLinkedData FairMCObject::PosInList (std::pair< int, int > link) inherited
FairMultiLinkedData FairMCObject::PosInList (FairLink link) inherited
Definition at line 85 of file FairMCObject.cxx.
References FairMultiLinkedData::AddLink(), FairMCObject::fStage, FairLink::GetIndex(), FairMCObject::GetStageId(), FairLink::GetType(), and FairMultiLinkedData::SetPersistanceCheck().
 {
   FairMultiLinkedData result;
   result.SetPersistanceCheck(kFALSE);
   for (int i = 0; i < fStage.size(); i++) {
     if (fStage[i].IsLinkInList(link.GetType(), link.GetIndex())) {
       result.AddLink(FairLink(GetStageId(), i));
     }
   }
   return result;
 }
virtual void FairMCStage::Print (std::ostream & out) inline virtual
Reimplemented from FairMCObject.
Definition at line 76 of file FairMCStage.h.
 {out << *this;}
void FairMCObject::RemoveType (Int_t type) inherited
Definition at line 97 of file FairMCObject.cxx.
References FairMCObject::fStage.
 {
   for (int i = 0; i < fStage.size(); i++) {
     fStage[i].RemoveType(type);
   }
 }
void FairMCStage::SetBranchName (std::string branchName) inline
Definition at line 59 of file FairMCStage.h.
References fBranchName.
 { fBranchName = branchName; }
void FairMCObject::SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index) inherited
Definition at line 40 of file FairMCObject.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData::SetPersistanceCheck(), and FairMCEntry::SetPos().
Referenced by FairMCMatch::GetMCInfoBackward(), and FairMCMatch::GetMCInfoForward().
 {
   FairMCEntry myEntry;
   myEntry.SetPos(index);
   myEntry.SetPersistanceCheck(kFALSE);
   for (int i = 0; i < type.size(); i++) {
     myEntry.AddLink(FairLink(type[i],link[i]));
   }
   SetEntry(myEntry);
 }
void FairMCObject::SetEntry (FairMultiLinkedData * data, int index) inherited
Definition at line 51 of file FairMCObject.cxx.
References FairMCObject::AdoptSize(), FairMCObject::fStage, and FairMultiLinkedData::GetLinks().
 {
   AdoptSize(index);
   fStage[index].SetLinks(data->GetLinks());
 }
void FairMCObject::SetEntry (FairMCEntry link) inherited
Definition at line 30 of file FairMCObject.cxx.
References FairMCObject::AdoptSize(), FairMCObject::fStage, and FairMCEntry::GetPos().
 {
   if (entry.GetPos() < 0) {
     std::cout << "-E- FairMCObject::SetEntry(FairMCEntry): pos " << entry.GetPos() << std::endl;
     return;
   }
   AdoptSize(entry.GetPos());
   fStage[entry.GetPos()] = entry;
 }
void FairMCStage::SetFileName (std::string fileName) inline
Definition at line 60 of file FairMCStage.h.
References fFileName.
 { fFileName = fileName; }
void FairMCStage::SetFill (Bool_t fill) inline
Definition at line 63 of file FairMCStage.h.
References fFill.
Referenced by FairMCMatchCreatorTask::InitBranches().
 { fFill = fill; }
void FairMCObject::SetLink (FairLink link, int index) inherited
Definition at line 57 of file FairMCObject.cxx.
References FairMCObject::AddLink(), and FairMCObject::fStage.
 {
   if (index < fStage.size()) {
     fStage[index].ResetLinks();
   }
   AddLink(link, index);
 }
void FairMCStage::SetLoaded (Bool_t loaded) inline
Definition at line 62 of file FairMCStage.h.
References fLoaded.
Referenced by FairMCMatchCreatorTask::Exec().
 { fLoaded = loaded; }
void FairMCObject::SetStage (std::vector< FairMCEntry > stage) inline inherited
Definition at line 69 of file FairMCObject.h.
References FairMCObject::fStage.
 {fStage = stage;}
void FairMCObject::SetStageId (Int_t type) inline inherited
Definition at line 63 of file FairMCObject.h.
References FairMCObject::fStageId.
 {fStageId = type;}
void FairMCStage::SetWeight (Double_t weight) inline
Definition at line 61 of file FairMCStage.h.
References fWeight.
Referenced by FairMCMatch::SetCommonWeightStages(), and FairMCMatchSelectorTask::SetWeights().
 { fWeight = weight; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const FairMCStage & stage) friend
Definition at line 78 of file FairMCStage.h.
{
       out << stage.GetStageId() << ": " << stage.GetBranchName() << " // " <<  stage.GetFileName() << std::endl; //" with weight: " << stage.GetWeight() << std::endl;
       ((FairMCObject)stage).Print(out);
       return out;
     }
Member Data Documentation
std::string FairMCStage::fBranchName private
Definition at line 85 of file FairMCStage.h.
Referenced by GetBranchName(), operator=(), and SetBranchName().
std::string FairMCStage::fFileName private
Definition at line 86 of file FairMCStage.h.
Referenced by GetFileName(), operator=(), and SetFileName().
Bool_t FairMCStage::fFill private
indicates if a corresponding DataFile with FairLinks exists to fill this stage
Definition at line 89 of file FairMCStage.h.
Referenced by GetFill(), operator=(), and SetFill().
Bool_t FairMCStage::fLoaded private
indicates if this stage was loaded already from a Link file
Definition at line 88 of file FairMCStage.h.
Referenced by ClearEntries(), GetLoaded(), operator=(), and SetLoaded().
Double_t FairMCStage::fWeight private
Definition at line 87 of file FairMCStage.h.
Referenced by GetWeight(), operator=(), and SetWeight().
The documentation for this class was generated from the following files:
FairMCStage.h
FairMCStage.cxx