FairRroot: FairParAsciiFileIo Class Reference
FairParAsciiFileIo Class Reference
#include <FairParAsciiFileIo.h>
Public Member Functions
FairParAsciiFileIo ()
~FairParAsciiFileIo ()
Bool_t open (const Text_t *fname, const Text_t *status="in")
Bool_t open (const TList *fnamelist, const Text_t *status="in")
void close ()
Bool_t check ()
void print ()
fstream * getFile ()
virtual FairDetParIo * getDetParIo (const Text_t *)
virtual void setDetParIo (FairDetParIo *)
virtual void setDetParIo (Text_t *)
virtual void removeDetParIo (Text_t *)
void setInputNumber (Int_t)
const char * getFilename ()
virtual void readVersions (FairRtdbRun *)
virtual void cd ()
void setAutoWritable (Bool_t f=kTRUE)
Bool_t isAutoWritable ()
Protected Attributes
fstream * file
TList * detParIoList
Bool_t autoWritable
TString filename
Private Member Functions
FairParAsciiFileIo (const FairParAsciiFileIo &)
FairParAsciiFileIo & operator= (const FairParAsciiFileIo &)
Detailed Description
Definition at line 20 of file FairParAsciiFileIo.h.
Constructor & Destructor Documentation
FairParAsciiFileIo::FairParAsciiFileIo ()
FairParAsciiFileIo::~FairParAsciiFileIo ()
Definition at line 51 of file FairParAsciiFileIo.cxx.
References close().
 {
   // default destructor closes an open file and deletes list of I/Os
   close();
 }
FairParAsciiFileIo::FairParAsciiFileIo (const FairParAsciiFileIo &) private
Member Function Documentation
virtual void FairParIo::cd () inline virtual inherited
Reimplemented in FairParRootFileIo.
Definition at line 54 of file FairParIo.h.
Referenced by FairRuntimeDb::closeFirstInput(), FairRuntimeDb::closeSecondInput(), FairRuntimeDb::getOutput(), FairRuntimeDb::getSecondInput(), and FairRuntimeDb::writeVersions().
 {;}
Bool_t FairParAsciiFileIo::check () inline virtual
Reimplemented from FairParIo.
Definition at line 45 of file FairParAsciiFileIo.h.
Referenced by print().
                    {
       if (file) { return (file->rdbuf()->is_open()==1); }
       else { return kFALSE; }
     }
void FairParAsciiFileIo::close () virtual
Reimplemented from FairParIo.
Definition at line 114 of file FairParAsciiFileIo.cxx.
References FairParIo::detParIoList, file, and FairParIo::filename.
Referenced by open(), and ~FairParAsciiFileIo().
 {
   // closes the file and deletes the detector I/Os
   if (file) {
     file->close();
     delete file;
     file=0;
     filename="";
   }
   if (detParIoList) { detParIoList->Delete(); }
 }
FairDetParIo * FairParIo::getDetParIo (const Text_t * detName) virtual inherited
Definition at line 69 of file FairParIo.cxx.
Referenced by FairRuntimeDb::activateParIo(), and FairParGenericSet::write().
 {
   // returns pointer to input/output class for a detector
   //std::cout << " DetParIO # " << detName << detParIoList->GetEntries()  <<  std::endl;
   return ((FairDetParIo*)detParIoList->FindObject(detName));
 }
fstream * FairParAsciiFileIo::getFile ()
Definition at line 141 of file FairParAsciiFileIo.cxx.
References file.
 {
   // returns the file pointer
   return file;
 }
const char* FairParIo::getFilename () inline inherited
Definition at line 36 of file FairParIo.h.
Referenced by FairRunAnaProof::RunOnProof().
 {return filename.Data();}
Bool_t FairParIo::isAutoWritable () inline inherited
Definition at line 58 of file FairParIo.h.
References FairParIo::autoWritable.
Referenced by FairRuntimeDb::closeOutput(), and FairRuntimeDb::writeContainer().
 {return autoWritable;}
Bool_t FairParAsciiFileIo::open (const Text_t * fname, const Text_t * status = "in")
Definition at line 57 of file FairParAsciiFileIo.cxx.
References FairRuntimeDb::activateParIo(), close(), file, FairParIo::filename, and FairRuntimeDb::instance().
Referenced by create_digis(), create_digis_mixed(), FairAnaSelector::Init(), open(), read_digis(), run_reco(), and run_tutorial4().
 {
   // opens file
   // if a file is already open, this file will be closed
   // activates detector I/Os
   close();
   if (!((strcmp(status,"in")==0) || (strcmp(status,"out")==0))) {
     cout<<"Put the right stream option for file "<<fname
         <<"\n  writing state : out\n   reading state : in  \nopen  aborted \n";
     return kFALSE;
   }
   file=new fstream();
   if(strcmp(status,"in")==0) {file->open( fname, ios::in);};
   if(strcmp(status,"out")==0) {file->open( fname, ios::out);};
   filebuf* buf = file->rdbuf();
   if (file && (buf->is_open()==1)) {
     filename=fname;
     FairRuntimeDb::instance()->activateParIo(this);
     return kTRUE;
   }
   cerr << "-E- Could not open input file " << fname << endl;
   Fatal("open","Could not open input file");
   return kFALSE;
 }
Bool_t FairParAsciiFileIo::open (const TList * fnamelist, const Text_t * status = "in")
Definition at line 82 of file FairParAsciiFileIo.cxx.
References FairLogger::endl(), FATAL, LOG, and open().
 {
   TString outFileName = gSystem->WorkingDirectory();
   outFileName += "/all_";
   Int_t pid = gSystem->GetPid();
   outFileName += pid;
   outFileName += ".par";
   TString catCommand = "cat ";
   TObjString* string;
   TListIter myIter(fnamelist);
   while((string = (TObjString*)myIter.Next())) {
     // check if the file exist
     // if file exist return value is false
     if ( gSystem->AccessPathName(string->GetString())) {
       LOG(FATAL) << "Parameter file " << string->GetString() << " does not exist." << FairLogger::endl;
     }
     //    cout <<  string->GetString() <<endl;
     catCommand += string->GetString();
     catCommand += " ";
   }
   catCommand += "> ";
   catCommand += outFileName;
   //  cout <<"CAT: "<<catCommand.Data()<<endl;
   gSystem->Exec(catCommand);
   return open(outFileName, status);
 }
FairParAsciiFileIo& FairParAsciiFileIo::operator= (const FairParAsciiFileIo &) private
void FairParAsciiFileIo::print () virtual
Reimplemented from FairParIo.
Definition at line 126 of file FairParAsciiFileIo.cxx.
References check(), FairParIo::detParIoList, and FairParIo::filename.
 {
   // prints information about the file and the detector I/Os
   if (check()) {
     cout<<"Ascii I/O "<<filename<<" is open\n";
     TIter next(detParIoList);
     FairDetParIo* io;
     cout<<"detector I/Os: ";
     while ((io=(FairDetParIo*)next())) {
       cout<<" "<<io->GetName();
     }
     cout<<'\n';
   } else { cout<<"No file open\n"; }
 }
virtual void FairParIo::readVersions (FairRtdbRun *) inline virtual inherited
Reimplemented in FairParTSQLIo, and FairParRootFileIo.
Definition at line 50 of file FairParIo.h.
Referenced by FairRuntimeDb::initContainers().
 {;}
void FairParIo::removeDetParIo (Text_t * detName) virtual inherited
Definition at line 76 of file FairParIo.cxx.
 {
   // removes input/output class for a detector
   TObject* p=detParIoList->FindObject(detName);
   if (p) {
     delete p;
     p=0;
   }
 }
void FairParIo::setAutoWritable (Bool_t f = kTRUE) inline inherited
Definition at line 57 of file FairParIo.h.
 {autoWritable=f;}
void FairParIo::setDetParIo (FairDetParIo * detParIo) virtual inherited
Definition at line 51 of file FairParIo.cxx.
Referenced by FairRuntimeDb::activateParIo().
 {
   // stores pointer of the input/output class for a detector
   // used for I/O from ROOT file or Ascii file
   Text_t* detName=(char*)detParIo->GetName();
   if (!detParIoList->FindObject(detName)) { detParIoList->Add(detParIo); }
 }
virtual void FairParIo::setDetParIo (Text_t *) inline virtual inherited
Reimplemented in FairParTSQLIo.
Definition at line 41 of file FairParIo.h.
 {;}
void FairParIo::setInputNumber (Int_t num) inherited
Definition at line 59 of file FairParIo.cxx.
References FairDetParIo::setInputNumber().
Referenced by FairRuntimeDb::setFirstInput(), and FairRuntimeDb::setSecondInput().
 {
   // sets in all detector I/Os the number of the input
   TIter next(detParIoList);
   FairDetParIo* io;
   while ((io=(FairDetParIo*)next())) {
     io->setInputNumber(num);
   }
 }
Member Data Documentation
Bool_t FairParIo::autoWritable protected inherited
Definition at line 24 of file FairParIo.h.
Referenced by FairParIo::isAutoWritable().
TList* FairParIo::detParIoList protected inherited
Definition at line 23 of file FairParIo.h.
Referenced by FairParTSQLIo::activateDetIo(), close(), FairParRootFileIo::close(), print(), FairParRootFileIo::print(), FairParTSQLIo::print(), and FairParTSQLIo::setDetParIo().
fstream* FairParAsciiFileIo::file protected
Definition at line 23 of file FairParAsciiFileIo.h.
Referenced by close(), getFile(), and open().
TString FairParIo::filename protected inherited
Definition at line 25 of file FairParIo.h.
Referenced by close(), open(), FairParRootFileIo::open(), and print().
The documentation for this class was generated from the following files:
FairParAsciiFileIo.h
FairParAsciiFileIo.cxx