FairRroot: sampler::Content Class Reference
sampler::Content Class Reference
#include <payload.pb.h>
Public Member Functions
Content ()
virtual ~Content ()
Content (const Content &from)
Content & operator= (const Content &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Content *other)
Content * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Content &from)
void MergeFrom (const Content &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_a () const
void clear_a ()
double a () const
void set_a (double value)
bool has_b () const
void clear_b ()
double b () const
void set_b (double value)
bool has_x () const
void clear_x ()
inline::google::protobuf::int32 x () const
void set_x (::google::protobuf::int32 value)
bool has_y () const
void clear_y ()
inline::google::protobuf::int32 y () const
void set_y (::google::protobuf::int32 value)
bool has_z () const
void clear_z ()
inline::google::protobuf::int32 z () const
void set_z (::google::protobuf::int32 value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const Content & default_instance ()
Static Public Attributes
static const int kAFieldNumber = 1
static const int kBFieldNumber = 2
static const int kXFieldNumber = 3
static const int kYFieldNumber = 4
static const int kZFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_a ()
void clear_has_a ()
void set_has_b ()
void clear_has_b ()
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_z ()
void clear_has_z ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
double a_
double b_
::google::protobuf::int32 x_
::google::protobuf::int32 y_
::google::protobuf::int32 z_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(5+31)/32]
Static Private Attributes
static Content * default_instance_ = NULL
Friends
void protobuf_AddDesc_payload_2eproto ()
void protobuf_AssignDesc_payload_2eproto ()
void protobuf_ShutdownFile_payload_2eproto ()
Detailed Description
Definition at line 48 of file payload.pb.h.
Constructor & Destructor Documentation
Content::Content ()
Definition at line 137 of file payload.pb.cc.
References SharedCtor().
Referenced by New().
   : ::google::protobuf::Message() {
   SharedCtor();
 }
Content::~Content () virtual
Definition at line 161 of file payload.pb.cc.
References SharedDtor().
                   {
   SharedDtor();
 }
Content::Content (const Content & from)
Definition at line 145 of file payload.pb.cc.
References MergeFrom(), and SharedCtor().
   : ::google::protobuf::Message() {
   SharedCtor();
   MergeFrom(from);
 }
Member Function Documentation
double Content::a () const inline
Definition at line 274 of file payload.pb.h.
References a_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return a_;
 }
double Content::b () const inline
Definition at line 296 of file payload.pb.h.
References b_.
Referenced by MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return b_;
 }
int Content::ByteSize () const
Definition at line 371 of file payload.pb.cc.
References _cached_size_, _has_bits_, has_a(), has_b(), has_x(), has_y(), has_z(), unknown_fields(), x(), y(), and z().
{
   int total_size = 0;
   if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     // optional double a = 1;
     if (has_a()) {
       total_size += 1 + 8;
     }
     // optional double b = 2;
     if (has_b()) {
       total_size += 1 + 8;
     }
     // optional int32 x = 3;
     if (has_x()) {
       total_size += 1 +
         ::google::protobuf::internal::WireFormatLite::Int32Size(
           this->x());
     }
     // optional int32 y = 4;
     if (has_y()) {
       total_size += 1 +
         ::google::protobuf::internal::WireFormatLite::Int32Size(
           this->y());
     }
     // optional int32 z = 5;
     if (has_z()) {
       total_size += 1 +
         ::google::protobuf::internal::WireFormatLite::Int32Size(
           this->z());
     }
   }
   if (!unknown_fields().empty()) {
     total_size +=
       ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
         unknown_fields());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void Content::Clear ()
Definition at line 191 of file payload.pb.cc.
References _has_bits_, a_, b_, mutable_unknown_fields(), x_, y_, and z_.
Referenced by CopyFrom().
                     {
   if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     a_ = 0;
     b_ = 0;
     x_ = 0;
     y_ = 0;
     z_ = 0;
   }
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
   mutable_unknown_fields()->Clear();
 }
void Content::clear_a () inline
Definition at line 270 of file payload.pb.h.
References a_, and clear_has_a().
{
   a_ = 0;
   clear_has_a();
 }
void Content::clear_b () inline
Definition at line 292 of file payload.pb.h.
References b_, and clear_has_b().
{
   b_ = 0;
   clear_has_b();
 }
void Content::clear_has_a () inline private
Definition at line 267 of file payload.pb.h.
References _has_bits_.
Referenced by clear_a().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void Content::clear_has_b () inline private
Definition at line 289 of file payload.pb.h.
References _has_bits_.
Referenced by clear_b().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void Content::clear_has_x () inline private
Definition at line 311 of file payload.pb.h.
References _has_bits_.
Referenced by clear_x().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void Content::clear_has_y () inline private
Definition at line 333 of file payload.pb.h.
References _has_bits_.
Referenced by clear_y().
{
   _has_bits_[0] &= ~0x00000008u;
 }
void Content::clear_has_z () inline private
Definition at line 355 of file payload.pb.h.
References _has_bits_.
Referenced by clear_z().
{
   _has_bits_[0] &= ~0x00000010u;
 }
void Content::clear_x () inline
Definition at line 314 of file payload.pb.h.
References clear_has_x(), and x_.
{
   x_ = 0;
   clear_has_x();
 }
void Content::clear_y () inline
Definition at line 336 of file payload.pb.h.
References clear_has_y(), and y_.
{
   y_ = 0;
   clear_has_y();
 }
void Content::clear_z () inline
Definition at line 358 of file payload.pb.h.
References clear_has_z(), and z_.
{
   z_ = 0;
   clear_has_z();
 }
void Content::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 452 of file payload.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void Content::CopyFrom (const Content & from)
Definition at line 458 of file payload.pb.cc.
References Clear(), and MergeFrom().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Content & Content::default_instance () static
Definition at line 180 of file payload.pb.cc.
References default_instance_, and protobuf_AddDesc_payload_2eproto.
{
   if (default_instance_ == NULL) protobuf_AddDesc_payload_2eproto();
   return *default_instance_;
 }
const ::google::protobuf::Descriptor * Content::descriptor () static
Definition at line 175 of file payload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   return Content_descriptor_;
 }
int sampler::Content::GetCachedSize () const inline
Definition at line 89 of file payload.pb.h.
References _cached_size_.
 { return _cached_size_; }
google::protobuf::Metadata Content::GetMetadata () const
Definition at line 482 of file payload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::Metadata metadata;
   metadata.descriptor = Content_descriptor_;
   metadata.reflection = Content_reflection_;
   return metadata;
 }
bool Content::has_a () const inline
Definition at line 261 of file payload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool Content::has_b () const inline
Definition at line 283 of file payload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool Content::has_x () const inline
Definition at line 305 of file payload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool Content::has_y () const inline
Definition at line 327 of file payload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool Content::has_z () const inline
Definition at line 349 of file payload.pb.h.
References _has_bits_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
void Content::InitAsDefaultInstance () private
Definition at line 142 of file payload.pb.cc.
Referenced by sampler::protobuf_AddDesc_payload_2eproto().
{
 }
bool Content::IsInitialized () const
Definition at line 464 of file payload.pb.cc.
{
   return true;
 }
void Content::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 418 of file payload.pb.cc.
Referenced by Content(), and CopyFrom().
{
   GOOGLE_CHECK_NE(&from, this);
   const Content* source =
     ::google::protobuf::internal::dynamic_cast_if_available<const Content*>(
       &from);
   if (source == NULL) {
     ::google::protobuf::internal::ReflectionOps::Merge(from, this);
   } else {
     MergeFrom(*source);
   }
 }
void Content::MergeFrom (const Content & from)
Definition at line 430 of file payload.pb.cc.
References _has_bits_, a(), b(), has_a(), has_b(), has_x(), has_y(), has_z(), mutable_unknown_fields(), set_a(), set_b(), set_x(), set_y(), set_z(), unknown_fields(), x(), y(), and z().
{
   GOOGLE_CHECK_NE(&from, this);
   if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
     if (from.has_a()) {
       set_a(from.a());
     }
     if (from.has_b()) {
       set_b(from.b());
     }
     if (from.has_x()) {
       set_x(from.x());
     }
     if (from.has_y()) {
       set_y(from.y());
     }
     if (from.has_z()) {
       set_z(from.z());
     }
   }
   mutable_unknown_fields()->MergeFrom(from.unknown_fields());
 }
bool Content::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 203 of file payload.pb.cc.
References a_, b_, DO_, mutable_unknown_fields(), set_has_a(), set_has_b(), set_has_x(), set_has_y(), set_has_z(), x_, y_, and z_.
{
 #define DO_(EXPRESSION) if (!(EXPRESSION)) return false
   ::google::protobuf::uint32 tag;
   while ((tag = input->ReadTag()) != 0) {
     switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
       // optional double a = 1;
       case 1: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &a_)));
           set_has_a();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(17)) goto parse_b;
         break;
       }
       // optional double b = 2;
       case 2: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          parse_b:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                  input, &b_)));
           set_has_b();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(24)) goto parse_x;
         break;
       }
       // optional int32 x = 3;
       case 3: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          parse_x:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, &x_)));
           set_has_x();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(32)) goto parse_y;
         break;
       }
       // optional int32 y = 4;
       case 4: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          parse_y:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, &y_)));
           set_has_y();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(40)) goto parse_z;
         break;
       }
       // optional int32 z = 5;
       case 5: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          parse_z:
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                    ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, &z_)));
           set_has_z();
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectAtEnd()) return true;
         break;
       }
       default: {
       handle_uninterpreted:
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
           return true;
         }
         DO_(::google::protobuf::internal::WireFormat::SkipField(
               input, tag, mutable_unknown_fields()));
         break;
       }
     }
   }
   return true;
 #undef DO_
 }
inline ::google::protobuf::UnknownFieldSet* sampler::Content::mutable_unknown_fields () inline
Definition at line 64 of file payload.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
{
     return &_unknown_fields_;
   }
Content * Content::New () const
Definition at line 187 of file payload.pb.cc.
References Content().
{
   return new Content;
 }
Content& sampler::Content::operator= (const Content & from) inline
Definition at line 55 of file payload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
void Content::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 304 of file payload.pb.cc.
References a(), b(), has_a(), has_b(), has_x(), has_y(), has_z(), unknown_fields(), x(), y(), and z().
{
   // optional double a = 1;
   if (has_a()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->a(), output);
   }
   // optional double b = 2;
   if (has_b()) {
     ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->b(), output);
   }
   // optional int32 x = 3;
   if (has_x()) {
     ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->x(), output);
   }
   // optional int32 y = 4;
   if (has_y()) {
     ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->y(), output);
   }
   // optional int32 z = 5;
   if (has_z()) {
     ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->z(), output);
   }
   if (!unknown_fields().empty()) {
     ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
         unknown_fields(), output);
   }
 }
google::protobuf::uint8 * Content::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 337 of file payload.pb.cc.
References a(), b(), has_a(), has_b(), has_x(), has_y(), has_z(), unknown_fields(), x(), y(), and z().
{
   // optional double a = 1;
   if (has_a()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->a(), target);
   }
   // optional double b = 2;
   if (has_b()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->b(), target);
   }
   // optional int32 x = 3;
   if (has_x()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->x(), target);
   }
   // optional int32 y = 4;
   if (has_y()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->y(), target);
   }
   // optional int32 z = 5;
   if (has_z()) {
     target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->z(), target);
   }
   if (!unknown_fields().empty()) {
     target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
         unknown_fields(), target);
   }
   return target;
 }
void Content::set_a (double value) inline
Definition at line 277 of file payload.pb.h.
References a_, and set_has_a().
Referenced by MergeFrom(), and FairMQProtoSampler::Run().
{
   set_has_a();
   a_ = value;
 }
void Content::set_b (double value) inline
Definition at line 299 of file payload.pb.h.
References b_, and set_has_b().
Referenced by MergeFrom(), and FairMQProtoSampler::Run().
{
   set_has_b();
   b_ = value;
 }
void Content::set_has_a () inline private
Definition at line 264 of file payload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_a().
{
   _has_bits_[0] |= 0x00000001u;
 }
void Content::set_has_b () inline private
Definition at line 286 of file payload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_b().
{
   _has_bits_[0] |= 0x00000002u;
 }
void Content::set_has_x () inline private
Definition at line 308 of file payload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_x().
{
   _has_bits_[0] |= 0x00000004u;
 }
void Content::set_has_y () inline private
Definition at line 330 of file payload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_y().
{
   _has_bits_[0] |= 0x00000008u;
 }
void Content::set_has_z () inline private
Definition at line 352 of file payload.pb.h.
References _has_bits_.
Referenced by MergePartialFromCodedStream(), and set_z().
{
   _has_bits_[0] |= 0x00000010u;
 }
void Content::set_x (::google::protobuf::int32 value) inline
Definition at line 321 of file payload.pb.h.
References set_has_x(), and x_.
Referenced by MergeFrom(), and FairMQProtoSampler::Run().
{
   set_has_x();
   x_ = value;
 }
void Content::set_y (::google::protobuf::int32 value) inline
Definition at line 343 of file payload.pb.h.
References set_has_y(), and y_.
Referenced by MergeFrom(), and FairMQProtoSampler::Run().
{
   set_has_y();
   y_ = value;
 }
void Content::set_z (::google::protobuf::int32 value) inline
Definition at line 365 of file payload.pb.h.
References set_has_z(), and z_.
Referenced by MergeFrom(), and FairMQProtoSampler::Run().
{
   set_has_z();
   z_ = value;
 }
void Content::SetCachedSize (int size) const private
Definition at line 170 of file payload.pb.cc.
References _cached_size_.
{
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
 }
void Content::SharedCtor () private
Definition at line 151 of file payload.pb.cc.
References _cached_size_, _has_bits_, a_, b_, x_, y_, and z_.
Referenced by Content().
{
   _cached_size_ = 0;
   a_ = 0;
   b_ = 0;
   x_ = 0;
   y_ = 0;
   z_ = 0;
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
 }
void Content::SharedDtor () private
Definition at line 165 of file payload.pb.cc.
References default_instance_.
Referenced by ~Content().
{
   if (this != default_instance_) {
   }
 }
void Content::Swap (Content * other)
Definition at line 469 of file payload.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, a_, b_, x_, y_, and z_.
{
   if (other != this) {
     std::swap(a_, other->a_);
     std::swap(b_, other->b_);
     std::swap(x_, other->x_);
     std::swap(y_, other->y_);
     std::swap(z_, other->z_);
     std::swap(_has_bits_[0], other->_has_bits_[0]);
     _unknown_fields_.Swap(&other->_unknown_fields_);
     std::swap(_cached_size_, other->_cached_size_);
   }
 }
const ::google::protobuf::UnknownFieldSet& sampler::Content::unknown_fields () const inline
Definition at line 60 of file payload.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
     return _unknown_fields_;
   }
google::protobuf::int32 Content::x () const inline
Definition at line 318 of file payload.pb.h.
References x_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return x_;
 }
google::protobuf::int32 Content::y () const inline
Definition at line 340 of file payload.pb.h.
References y_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return y_;
 }
google::protobuf::int32 Content::z () const inline
Definition at line 362 of file payload.pb.h.
References z_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return z_;
 }
Friends And Related Function Documentation
void protobuf_AddDesc_payload_2eproto () friend
Definition at line 100 of file payload.pb.cc.
Referenced by default_instance().
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\rpayload.proto\022\007sampler\"@\n\007Content\022\t\n\001a"
     "\030\001 \001(\001\022\t\n\001b\030\002 \001(\001\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022"
     "\t\n\001z\030\005 \001(\005\")\n\007Payload\022\036\n\004data\030\001 \003(\0132\020.sa"
     "mpler.Content", 133);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "payload.proto", &protobuf_RegisterTypes);
   Content::default_instance_ = new Content();
   Payload::default_instance_ = new Payload();
   Content::default_instance_->InitAsDefaultInstance();
   Payload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_payload_2eproto);
 }
void protobuf_AssignDesc_payload_2eproto () friend
Definition at line 33 of file payload.pb.cc.
{
   protobuf_AddDesc_payload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "payload.proto");
   GOOGLE_CHECK(file != NULL);
   Content_descriptor_ = file->message_type(0);
   static const int Content_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, a_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, b_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, z_),
   };
   Content_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Content_descriptor_,
       Content::default_instance_,
       Content_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Content));
   Payload_descriptor_ = file->message_type(1);
   static const int Payload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, data_),
   };
   Payload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Payload_descriptor_,
       Payload::default_instance_,
       Payload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Payload));
 }
void protobuf_ShutdownFile_payload_2eproto () friend
Definition at line 93 of file payload.pb.cc.
{
   delete Content::default_instance_;
   delete Content_reflection_;
   delete Payload::default_instance_;
   delete Payload_reflection_;
 }
Member Data Documentation
int sampler::Content::_cached_size_ mutable private
Definition at line 158 of file payload.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 sampler::Content::_has_bits_[(5+31)/32] private
Definition at line 159 of file payload.pb.h.
Referenced by ByteSize(), Clear(), clear_has_a(), clear_has_b(), clear_has_x(), clear_has_y(), clear_has_z(), has_a(), has_b(), has_x(), has_y(), has_z(), MergeFrom(), set_has_a(), set_has_b(), set_has_x(), set_has_y(), set_has_z(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet sampler::Content::_unknown_fields_ private
Definition at line 150 of file payload.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
double sampler::Content::a_ private
Definition at line 152 of file payload.pb.h.
Referenced by a(), Clear(), clear_a(), MergePartialFromCodedStream(), set_a(), SharedCtor(), and Swap().
double sampler::Content::b_ private
Definition at line 153 of file payload.pb.h.
Referenced by b(), Clear(), clear_b(), MergePartialFromCodedStream(), set_b(), SharedCtor(), and Swap().
Content * Content::default_instance_ = NULL static private
Definition at line 166 of file payload.pb.h.
Referenced by default_instance(), sampler::protobuf_AddDesc_payload_2eproto(), sampler::protobuf_AssignDesc_payload_2eproto(), sampler::protobuf_ShutdownFile_payload_2eproto(), and SharedDtor().
const int Content::kAFieldNumber = 1 static
Definition at line 105 of file payload.pb.h.
const int Content::kBFieldNumber = 2 static
Definition at line 112 of file payload.pb.h.
const int Content::kXFieldNumber = 3 static
Definition at line 119 of file payload.pb.h.
const int Content::kYFieldNumber = 4 static
Definition at line 126 of file payload.pb.h.
const int Content::kZFieldNumber = 5 static
Definition at line 133 of file payload.pb.h.
::google::protobuf::int32 sampler::Content::x_ private
Definition at line 154 of file payload.pb.h.
Referenced by Clear(), clear_x(), MergePartialFromCodedStream(), set_x(), SharedCtor(), Swap(), and x().
::google::protobuf::int32 sampler::Content::y_ private
Definition at line 155 of file payload.pb.h.
Referenced by Clear(), clear_y(), MergePartialFromCodedStream(), set_y(), SharedCtor(), Swap(), and y().
::google::protobuf::int32 sampler::Content::z_ private
Definition at line 156 of file payload.pb.h.
Referenced by Clear(), clear_z(), MergePartialFromCodedStream(), set_z(), SharedCtor(), Swap(), and z().
The documentation for this class was generated from the following files:
payload.pb.h
payload.pb.cc