FairRroot: FairMQPoller Class Reference
FairMQPoller Class Reference abstract
#include <FairMQPoller.h>
Public Member Functions
virtual void Poll (int timeout)=0
virtual bool CheckInput (int index)=0
virtual bool CheckOutput (int index)=0
virtual ~FairMQPoller ()
Detailed Description
FairMQPoller.h
Since
2014-01-23
Author
A. Rybalchenko
Definition at line 18 of file FairMQPoller.h.
Constructor & Destructor Documentation
virtual FairMQPoller::~FairMQPoller () inline virtual
Definition at line 25 of file FairMQPoller.h.
 {};
Member Function Documentation
virtual bool FairMQPoller::CheckInput (int index) pure virtual
Implemented in FairMQPollerNN, and FairMQPollerZMQ.
Referenced by FairMQMerger::Run(), and GenericMerger< MergerPolicy, InputPolicy, OutputPolicy >::Run().
virtual bool FairMQPoller::CheckOutput (int index) pure virtual
Implemented in FairMQPollerNN, and FairMQPollerZMQ.
virtual void FairMQPoller::Poll (int timeout) pure virtual
Implemented in FairMQPollerNN, and FairMQPollerZMQ.
Referenced by FairMQMerger::Run(), and GenericMerger< MergerPolicy, InputPolicy, OutputPolicy >::Run().
The documentation for this class was generated from the following file:
FairMQPoller.h