FairRoot: FairMQMessage Class Reference
FairMQMessage Class Reference abstract
#include <FairMQMessage.h>
Public Member Functions
virtual void Rebuild ()=0
virtual void Rebuild (size_t size)=0
virtual void Rebuild (void *data, size_t size, fairmq_free_fn *ffn=NULL, void *hint=NULL)=0
virtual void * GetMessage ()=0
virtual void * GetData ()=0
virtual size_t GetSize ()=0
virtual void SetMessage (void *data, size_t size)=0
virtual void CloseMessage ()=0
virtual void Copy (FairMQMessage *msg)=0
virtual ~FairMQMessage ()
Detailed Description
Definition at line 22 of file FairMQMessage.h.
Constructor & Destructor Documentation
virtual FairMQMessage::~FairMQMessage () inline virtual
Definition at line 37 of file FairMQMessage.h.
 {};
Member Function Documentation
virtual void FairMQMessage::CloseMessage () pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
Referenced by BoostSerializer< DataType, BoostArchiveOut >::CloseMessage(), BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::CloseMessage(), FairMQProcessor::ReceivePart(), FairMQProcessor::Run(), GenericProcessor< InputPolicy, OutputPolicy, TaskPolicy >::Run(), and FairMQProcessor::SendPart().
virtual void FairMQMessage::Copy (FairMQMessage * msg) pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
Referenced by FairMQBenchmarkSampler::Run().
virtual void* FairMQMessage::GetData () pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
Referenced by BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg(), RootDeSerializer::DoDeSerialization(), BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DoDeSerialization(), MyDigiSerializer< PodType, DigiType >::DoSerialization(), MyHitSerializer< PodType, HitType >::DoSerialization(), BoostSerializer< DataType, BoostArchiveOut >::DoSerialization(), BinaryBaseClassSerializer< PodType >::GetPayload(), FairMQExampleServer::Run(), FairMQProtoSink::Run(), FairMQExampleClient::Run(), FairMQProtoSampler::Run(), FairMQBinSampler::Run(), TriviallyCopyableDataSaver< TPayload >::Write(), and BoostDataSaver< TPayload, TArchiveIn, TArchiveOut >::Write().
virtual void* FairMQMessage::GetMessage () pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
Referenced by FairMQMessageNN::Copy(), FairMQMessageZMQ::Copy(), FairMQSocketZMQ::Receive(), FairMQSocketZMQ::Send(), and FairMQSocketNN::Send().
virtual size_t FairMQMessage::GetSize () pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
Referenced by FairMQMessageNN::Copy(), BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DeSerializeMsg(), RootDeSerializer::DoDeSerialization(), BoostDeSerializer< DataType, TContainer, BoostArchiveIn >::DoDeSerialization(), BinaryBaseClassSerializer< PodType >::GetPayload(), FairMQExampleServer::Run(), FairMQProtoSink::Run(), FairMQBinSink::Run(), FairMQExampleClient::Run(), TriviallyCopyableDataSaver< TPayload >::Write(), and BoostDataSaver< TPayload, TArchiveIn, TArchiveOut >::Write().
virtual void FairMQMessage::Rebuild () pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
Referenced by MyDigiSerializer< PodType, DigiType >::DoSerialization(), MyHitSerializer< PodType, HitType >::DoSerialization(), RootSerializer::DoSerialization(), and BoostSerializer< DataType, BoostArchiveOut >::DoSerialization().
virtual void FairMQMessage::Rebuild (size_t size) pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
virtual void FairMQMessage::Rebuild (void * data, size_t size, fairmq_free_fn * ffn = NULL, void * hint = NULL) pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
virtual void FairMQMessage::SetMessage (void * data, size_t size) pure virtual
Implemented in FairMQMessageZMQ, and FairMQMessageNN.
Referenced by FairMQSocketNN::Receive().
The documentation for this class was generated from the following file:
FairMQMessage.h