FairRoot: FairMCDataCrawler Class Reference
FairMCDataCrawler Class Reference abstract
#include <FairMCDataCrawler.h>
Public Member Functions
FairMCDataCrawler ()
virtual ~FairMCDataCrawler ()
FairMultiLinkedData GetInfo (FairMultiLinkedData startLink, TString stopStage)
FairMultiLinkedData GetInfo (FairMultiLinkedData startLink, Int_t stopStageId)
FairMultiLinkedData * GetEntry (Int_t fileId, Int_t eventNr, Int_t type, Int_t index)
FairMultiLinkedData * GetEntry (FairLink link)
void SetStoreIntermediate (Bool_t val=kTRUE)
void SetStoreAllEndpoints (Bool_t val=kTRUE)
void Init ()
void SetVerbose (Int_t val)
virtual void InitDataObjects ()=0
Protected Attributes
FairRootManager * fIoman
Private Member Functions
void GetNextStage (FairMultiLinkedData &startEntry, Int_t stopStage)
void AddToFinalStage (FairLink link, Float_t mult)
void ClearFinalStage ()
FairMCDataCrawler (const FairMCDataCrawler &)
FairMCDataCrawler & operator= (const FairMCDataCrawler &)
ClassDef (FairMCDataCrawler, 1)
Private Attributes
FairMultiLinkedData fFinalStage
Int_t fUltimateStage
last stage in link chain. Here all recursive operations must stop.
Int_t fVerbose
Bool_t fStoreAllEndpoints
true if non-stop-stage data is stored in results
Bool_t fStoreIntermediate
true if all intermediate steps should be stored
Detailed Description
Definition at line 28 of file FairMCDataCrawler.h.
Constructor & Destructor Documentation
FairMCDataCrawler::FairMCDataCrawler ()
Definition at line 26 of file FairMCDataCrawler.cxx.
   : fIoman(FairRootManager::Instance()),
     fFinalStage(),
     fUltimateStage(0),
     fVerbose(0),
     fStoreAllEndpoints(kTRUE),
     fStoreIntermediate(kTRUE)
 {
 }
FairMCDataCrawler::~FairMCDataCrawler () virtual
Definition at line 36 of file FairMCDataCrawler.cxx.
 {
 }
FairMCDataCrawler::FairMCDataCrawler (const FairMCDataCrawler &) private
Member Function Documentation
void FairMCDataCrawler::AddToFinalStage (FairLink link, Float_t mult) private
Definition at line 243 of file FairMCDataCrawler.cxx.
References FairMultiLinkedData::AddLink(), and fFinalStage.
Referenced by GetNextStage().
 {
   fFinalStage.AddLink(hitPair, false, mult);
 }
FairMCDataCrawler::ClassDef (FairMCDataCrawler , 1) private
void FairMCDataCrawler::ClearFinalStage () private
FairMultiLinkedData * FairMCDataCrawler::GetEntry (Int_t fileId, Int_t eventNr, Int_t type, Int_t index)
Definition at line 130 of file FairMCDataCrawler.cxx.
Referenced by GetNextStage().
 {
   return GetEntry(FairLink(fileId, eventNr, type, index));
 }
FairMultiLinkedData * FairMCDataCrawler::GetEntry (FairLink link)
Definition at line 125 of file FairMCDataCrawler.cxx.
References FairRootManager::GetCloneOfLinkData(), and FairRootManager::Instance().
 {
   return (FairMultiLinkedData*)FairRootManager::Instance()->GetCloneOfLinkData(link);
 }
FairMultiLinkedData FairMCDataCrawler::GetInfo (FairMultiLinkedData startLink, TString stopStage)
Definition at line 107 of file FairMCDataCrawler.cxx.
References fIoman, and FairRootManager::GetBranchId().
 {
   return GetInfo(startLink, fIoman->GetBranchId(stopStage));
 }
FairMultiLinkedData FairMCDataCrawler::GetInfo (FairMultiLinkedData startLink, Int_t stopStageId)
Definition at line 112 of file FairMCDataCrawler.cxx.
References fFinalStage, fIoman, fVerbose, FairRootManager::GetBranchName(), GetNextStage(), and FairMultiLinkedData::ResetLinks().
 {
   fFinalStage.ResetLinks();
   if (fVerbose > 1) {
     std::cout << "-------------------------------------" << std::endl;
     std::cout << "StartLink: " << startLink;
   }
   if (fVerbose > 1) { std::cout << "StopStageLink: " << fIoman->GetBranchName(stopStageId) << std::endl; }
   GetNextStage(startLink, stopStageId);
   if (fVerbose > 1) { std::cout << "FinalStage: " << fFinalStage << std::endl; }
   return fFinalStage;
 }
void FairMCDataCrawler::GetNextStage (FairMultiLinkedData & startEntry, Int_t stopStage) private
Definition at line 135 of file FairMCDataCrawler.cxx.
References FairMultiLinkedData::AddAllWeights(), AddToFinalStage(), fFinalStage, fStoreAllEndpoints, fStoreIntermediate, fUltimateStage, fVerbose, FairRootManager::GetBranchId(), GetEntry(), FairMultiLinkedData::GetLink(), FairMultiLinkedData::GetNLinks(), FairLink::GetType(), FairLink::GetWeight(), FairRootManager::Instance(), FairMultiLinkedData::MultiplyAllWeights(), and FairLink::Print().
Referenced by GetInfo().
 {
   FairMultiLinkedData* tempStage;
   for (int i = 0; i < startStage.GetNLinks(); i++) {
     FairLink actualLink = startStage.GetLink(i);
 //    if (fVerbose > 0) { std::cout << "Actual Link: " << actualLink << std::endl; }
     if (actualLink.GetType() < 0) {
       if (fStoreAllEndpoints) { AddToFinalStage(actualLink, 1); }
       if (fVerbose > 2) {
         std::cout << "ActualLink.Type < 0" << std::endl;
         std::cout << "FinalStage: " << fFinalStage << std::endl;
         std::cout << "---------------------" << std::endl;
       }
       if (fVerbose > 1) {
         std::cout << std::endl;
       }
     } else if (actualLink.GetType() == stopStage) {
       AddToFinalStage(actualLink, 1);
       if (fVerbose > 2) {
         std::cout << "ActualLink.Type == stopStage" << std::endl;
         std::cout << "FinalStage: " << fFinalStage << std::endl;
         std::cout << "---------------------" << std::endl;
       }
       if (fVerbose > 1) {
         std::cout << std::endl;
       }
     } else if (actualLink.GetType() == fUltimateStage) {
       if (fStoreAllEndpoints) { AddToFinalStage(actualLink, 1); }
       if (fVerbose > 2) {
         std::cout << "ActualLink.Type == UltimateStage" << std::endl;
         std::cout << "FinalStage: " << fFinalStage << std::endl;
         std::cout << "---------------------" << std::endl;
       }
       if (fVerbose > 1) {
         std::cout << std::endl;
       }
     } else if (actualLink.GetType() == FairRootManager::Instance()->GetBranchId("EventHeader.")) {
       if (fStoreAllEndpoints) { AddToFinalStage(actualLink, 1); }
       if (fVerbose > 2) {
         std::cout << "ActualLink.Type == EventHeader" << std::endl;
         std::cout << "FinalStage: " << fFinalStage << std::endl;
         std::cout << "---------------------" << std::endl;
       }
       if (fVerbose > 1) {
         std::cout << std::endl;
       }
     } else {
       tempStage = GetEntry(actualLink);
       if (tempStage == 0) {
         if (fStoreAllEndpoints) { AddToFinalStage(actualLink, 1); }
         if (fVerbose > 2) {
           std::cout << "TempStage == 0" << std::endl;
           std::cout << "FinalStage: " << fFinalStage << std::endl;
           std::cout << "---------------------" << std::endl;
         }
         if (fVerbose > 1) {
           std::cout << std::endl;
         }
         continue;
       }
       if (fVerbose > 0) {
 //        std::cout << "TempStage Start";
         std::cout << " // ";
         actualLink.Print();
         std::cout << " --> " << *tempStage;
       }
       if (tempStage->GetNLinks() == 0) {
         if (fStoreAllEndpoints) { AddToFinalStage(actualLink,1); }
         if (fVerbose > 0) {
           std::cout << "tempStage->GetNLinks == 0" << std::endl;
           std::cout << "FinalStage: " << fFinalStage << std::endl;
           std::cout << "---------------------" << std::endl;
         }
       } else {
         if(fStoreIntermediate) { AddToFinalStage(actualLink, 1); }
         double tempStageWeight = 1;
         double startLinkWeight = startStage.GetLink(i).GetWeight();
         if (fVerbose > 2) {
           //std::cout << "Tempstage " << tempStage.GetSource() << ": weight " << tempStageWeight << std::endl;
           std::cout << "StartLinkWeight " << startLinkWeight << std::endl;
         }
         //std::cout << " StageWeight: " << tempStageWeight << " startLinkWeight: " << startLinkWeight;
         tempStage->MultiplyAllWeights(tempStageWeight);
         if ((tempStageWeight * startLinkWeight) == 0) {
           tempStage->MultiplyAllWeights(tempStageWeight);
           tempStage->AddAllWeights(startLinkWeight/startStage.GetNLinks());
           if (fVerbose > 2) {
             std::cout << " NLinks: " << tempStage->GetNLinks() << " ";
             std::cout << "AddAllWeights: " << startLinkWeight/startStage.GetNLinks() << std::endl;
           }
         } else {
           tempStage->MultiplyAllWeights(startLinkWeight);
           if (fVerbose > 2) {
             std::cout << "MultiplyAllWeights: " << startLinkWeight << std::endl;
           }
         }
       }
       //      if (fVerbose > 0)
       //        std::cout<< "TempStage Stop: " << *tempStage << std::endl;
       GetNextStage(*tempStage, stopStage);
     }
   }
 }
void FairMCDataCrawler::Init ()
Definition at line 40 of file FairMCDataCrawler.cxx.
References InitDataObjects().
 {
   InitDataObjects();
   /*
   fIoman->GetObject("MVDPoint");
   fIoman->GetObject("MVDStripDigis");
   fIoman->GetObject("MVDPixelDigis");
   fIoman->GetObject("MVDHitsPixel");
   fIoman->GetObject("MVDHitsStrip");
   fIoman->GetObject("MVDPixelClusterCand");
   fIoman->GetObject("MVDStripClusterCand");
   fIoman->GetObject("MVDSortedStripDigis");
   fIoman->GetObject("MVDSortedPixelDigis");
   fIoman->GetObject("EmcCluster");
   fIoman->GetObject("EmcBump");
   fIoman->GetObject("EmcDigi");
   fIoman->GetObject("EmcHit");
   fIoman->GetObject("EmcPoint");
   fIoman->GetObject("EmcRecoHit");
   fIoman->GetObject("EmcSharedDigi");
   fIoman->GetObject("EmcWaveform");
   fIoman->GetObject("STTPoint");
   fIoman->GetObject("STTHit");
   fIoman->GetObject("SttHelixHit");
   fIoman->GetObject("STTTrack");
   fIoman->GetObject("STTTrackCand");
   fIoman->GetObject("FairTpcPoint");
   fIoman->GetObject("FairTpcPrimaryCluster");
   fIoman->GetObject("FairTpcDriftedElectron");
   fIoman->GetObject("FairTpcAvalanche");
   fIoman->GetObject("FairTpcSignal");
   fIoman->GetObject("FairTpcDigi");
   fIoman->GetObject("FairTpcCluster");
   fIoman->GetObject("GEMPoint");
   fIoman->GetObject("GEMDigi");
   fIoman->GetObject("GEMHit");
   fIoman->GetObject("FairDchPoint");
   fIoman->GetObject("FairDchDigi");
   fIoman->GetObject("PndDchCylinderHit");
   fIoman->GetObject("MdtPoint");
   fIoman->GetObject("MdtHit");
   fIoman->GetObject("MdtTrk");
   fIoman->GetObject("LheHit");
   fIoman->GetObject("LheCandidate");
   fIoman->GetObject("LheTrack");
   fIoman->GetObject("MVDIdealTrackCand");
   fIoman->GetObject("MVDRiemannTrackCand");
   fIoman->GetObject("PndTrack");
   fIoman->GetObject("LheGenTrack");
   fIoman->GetObject("PidChargedCand");
   fIoman->GetObject("PidNeutralCand");
   */
 }
virtual void FairMCDataCrawler::InitDataObjects () pure virtual
Referenced by Init().
FairMCDataCrawler& FairMCDataCrawler::operator= (const FairMCDataCrawler &) private
void FairMCDataCrawler::SetStoreAllEndpoints (Bool_t val = kTRUE) inline
Definition at line 41 of file FairMCDataCrawler.h.
References fStoreAllEndpoints.
 {fStoreAllEndpoints = val;}
void FairMCDataCrawler::SetStoreIntermediate (Bool_t val = kTRUE) inline
Definition at line 40 of file FairMCDataCrawler.h.
References fStoreIntermediate.
 {fStoreIntermediate = val;}
void FairMCDataCrawler::SetVerbose (Int_t val) inline
Definition at line 45 of file FairMCDataCrawler.h.
References fVerbose.
 {fVerbose = val;};
Member Data Documentation
FairMultiLinkedData FairMCDataCrawler::fFinalStage private
Definition at line 54 of file FairMCDataCrawler.h.
Referenced by AddToFinalStage(), GetInfo(), and GetNextStage().
FairRootManager* FairMCDataCrawler::fIoman protected
Definition at line 51 of file FairMCDataCrawler.h.
Referenced by GetInfo().
Bool_t FairMCDataCrawler::fStoreAllEndpoints private
true if non-stop-stage data is stored in results
Definition at line 58 of file FairMCDataCrawler.h.
Referenced by GetNextStage(), and SetStoreAllEndpoints().
Bool_t FairMCDataCrawler::fStoreIntermediate private
true if all intermediate steps should be stored
Definition at line 59 of file FairMCDataCrawler.h.
Referenced by GetNextStage(), and SetStoreIntermediate().
Int_t FairMCDataCrawler::fUltimateStage private
last stage in link chain. Here all recursive operations must stop.
Definition at line 55 of file FairMCDataCrawler.h.
Referenced by GetNextStage().
Int_t FairMCDataCrawler::fVerbose private
Definition at line 57 of file FairMCDataCrawler.h.
Referenced by GetInfo(), GetNextStage(), and SetVerbose().
The documentation for this class was generated from the following files:
FairMCDataCrawler.h
FairMCDataCrawler.cxx