FairRroot: FairModule Class Reference
FairModule Class Reference
#include <FairModule.h>
Public Member Functions
FairModule ()
FairModule (const char *Name, const char *title, Bool_t Active=kFALSE)
virtual ~FairModule ()
virtual void Print (Option_t *option="") const
virtual void SetGeometryFileName (TString fname, TString geoVer="0")
virtual TString GetGeometryFileName ()
virtual TString GetGeometryFileVer ()
virtual void ConstructGeometry ()
virtual void ConstructOpGeometry ()
virtual void ConstructRootGeometry ()
virtual void ConstructASCIIGeometry ()
virtual void ModifyGeometry ()
virtual void ConstructGDMLGeometry (TGeoMatrix *)
virtual FairModule * CloneModule () const
virtual void BeginWorkerRun () const
virtual void FinishWorkerRun () const
template<class T , class U >
void ConstructASCIIGeometry (T dataType1, TString containerName="", U datatype2=NULL)
virtual Bool_t CheckIfSensitive (std::string name)
virtual void ExpandNode (TGeoNode *Node)
virtual void ExpandNodeForGDML (TGeoNode *)
virtual Int_t getVolId (const TString &vname) const
Int_t GetModId ()
void SetVerboseLevel (Int_t level)
Bool_t IsActive ()
void SetModId (Int_t id)
void SetMotherVolume (TString volName)
void ProcessNodes (TList *aList)
virtual void SetParContainers ()
virtual void InitParContainers ()
TList * GetListOfGeoPar ()
FairVolume * getFairVolume (FairGeoNode *fNode)
void AddSensitiveVolume (TGeoVolume *v)
Public Attributes
TString fMotherVolumeName
Static Public Attributes
static FairVolumeList * vList =0
static Int_t fNbOfVolumes =0
static TRefArray * svList =0
static TArrayI * volNumber =0
Protected Member Functions
FairModule (const FairModule &)
FairModule & operator= (const FairModule &)
Protected Attributes
TString fgeoVer
TString fgeoName
Int_t fModId
Bool_t fActive
Int_t fNbOfSensitiveVol
Int_t fVerboseLevel
TList * flGeoPar
Bool_t kGeoSaved
list of Detector Geometry parameters
Private Member Functions
void SetDefaultMatrixName (TGeoMatrix *matrix)
void AssignMediumAtImport (TGeoVolume *v)
void ReAssignMediaId ()
void swap (FairModule &other) throw ()
Detailed Description
Base class for constructing all detecors and passive volumes
Author
M. Al-Turany, Denis Bertini
Version
1.0
Since
01.04.08 M.Al-Turany Add methods to construct geometry via ROOT files Add some documentation
Changelog: 29.02.2012 [O.Merle] Fixed missing material assignment for top volume. ... and please - add some documentation to your code.
Definition at line 49 of file FairModule.h.
Constructor & Destructor Documentation
FairModule::FairModule ()
default ctor
Definition at line 122 of file FairModule.cxx.
   : TNamed(),
     fMotherVolumeName(""),
     fgeoVer("Not defined"),
     fgeoName("Not defined"),
     fModId(-1),
     fActive(kFALSE),
     fNbOfSensitiveVol(0),
     fVerboseLevel(0),
     flGeoPar(0),
     kGeoSaved(kFALSE)
 {
 }
FairModule::FairModule (const char * Name, const char * title, Bool_t Active = kFALSE)
Standard ctor
Definition at line 77 of file FairModule.cxx.
References svList, and vList.
   :TNamed(Name, title),
    fMotherVolumeName(""),
    fgeoVer("Not defined"),
    fgeoName("Not defined"),
    fModId(-1),
    fActive(Active),
    fNbOfSensitiveVol(0),
    fVerboseLevel(0),
    flGeoPar(0),
    kGeoSaved(kFALSE)
 {
   if(!svList) { svList=new TRefArray(); }
   if(!vList) { vList=new FairVolumeList(); }
 }
FairModule::~FairModule () virtual
default dtor
Definition at line 72 of file FairModule.cxx.
 {
 }
FairModule::FairModule (const FairModule & rhs) protected
Definition at line 95 of file FairModule.cxx.
   :TNamed(rhs),
    fMotherVolumeName(rhs.fMotherVolumeName),
    fgeoVer(rhs.fgeoVer),
    fgeoName(rhs.fgeoName),
    fModId(rhs.fModId),
    fActive(rhs.fActive),
    fNbOfSensitiveVol(rhs.fNbOfSensitiveVol),
    fVerboseLevel(rhs.fVerboseLevel),
    flGeoPar(0),
    kGeoSaved(rhs.kGeoSaved)
 {
    // Do not change anything in global fields (svList. vList)
   // TO DO - add when we know what type is the elements of flGeoPar
   //flGeoPar=new TObjArray();
   //TIter it = rhs.flGeoPar->MakeIterator();
   // Copy parameters
   //TObject* obj;
   //while((obj=it->Next())) {
   //  flGeoPar->Add(...);
   //}
 }
Member Function Documentation
void FairModule::AddSensitiveVolume (TGeoVolume * v)
Definition at line 281 of file FairModule.cxx.
References FairVolumeList::addVolume(), DEBUG2, FairLogger::endl(), FairVolumeList::findObject(), fModId, fNbOfSensitiveVol, fNbOfVolumes, LOG, FairVolume::setModId(), FairVolume::SetModule(), svList, and vList.
Referenced by ExpandNode().
 {
   LOG(DEBUG2)<<"AddSensitiveVolume " << v->GetName() << FairLogger::endl;
   // Only register volumes which are not already registered
   // Otherwise the stepping will be slowed down
   if( ! vList->findObject(v->GetName() ) ) {
     FairVolume*  volume = NULL;
     volume = new FairVolume(v->GetName(), fNbOfVolumes++);
     vList->addVolume(volume);
     volume->setModId(fModId);
     volume->SetModule(this);
     svList->Add(volume);
     fNbOfSensitiveVol++;
   }
 }
void FairModule::AssignMediumAtImport (TGeoVolume * v) private
Assign medium to the the volume v, this has to be done in all cases: case 1: For CAD converted volumes they have no mediums (only names) case 2: TGeoVolumes, we need to be sure that the material is defined in this session
The Material is not defined in the TGeoManager, we try to create one if we have enough information about it
Material is already available in the TGeoManager and we can set it
Definition at line 585 of file FairModule.cxx.
References FairGeoBuilder::createMedium(), FairLogger::endl(), FATAL, FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairGeoInterface::getMedia(), FairGeoMedia::getMedium(), FairGeoLoader::Instance(), and LOG.
Referenced by ConstructRootGeometry(), and ExpandNode().
 {
   FairGeoMedia* Media       = FairGeoLoader::Instance()->getGeoInterface()->getMedia();
   FairGeoBuilder* geobuild  = FairGeoLoader::Instance()->getGeoBuilder();
   TGeoMedium* med1=v->GetMedium();
   if(med1) {
     // In newer ROOT version also a TGeoVolumeAssembly has a material and medium.
     // This medium is called dummy and is automatically set when the geometry is constructed.
     // Since this material and medium is neither in the TGeoManager (at this point) nor in our
     // ASCII file we have to create it the same way it is done in TGeoVolume::CreateDummyMedium()
     // In the end the new medium and material has to be added to the TGeomanager, because this is
     // not done automatically when using the default constructor. For all other constructors the
     // newly created medium or material is added to the TGeomanger.
     // Create the medium and material only the first time.
     TString medName = (TString)(med1->GetName());
     if ( medName.EqualTo("dummy") && NULL == gGeoManager->GetMedium(medName) ) {
       TGeoMaterial *dummyMaterial = new TGeoMaterial();
       dummyMaterial->SetName("dummy");
       TGeoMedium* dummyMedium = new TGeoMedium();
       dummyMedium->SetName("dummy");
       dummyMedium->SetMaterial(dummyMaterial);
       gGeoManager->GetListOfMedia()->Add(dummyMedium);
       gGeoManager->AddMaterial(dummyMaterial);
     }
     TGeoMaterial* mat1=v->GetMaterial();
     TGeoMaterial* newMat = gGeoManager->GetMaterial(mat1->GetName());
     if( newMat==0) {
       FairGeoMedium* FairMedium=Media->getMedium(mat1->GetName());
       if (!FairMedium) {
         LOG(FATAL)<<"Material "<< mat1->GetName() << "is not defined in ASCII file nor in Root file." << FairLogger::endl;
         //     FairMedium=new FairGeoMedium(mat1->GetName());
         //      Media->addMedium(FairMedium);
       } else {
         Int_t nmed=geobuild->createMedium(FairMedium);
         v->SetMedium(gGeoManager->GetMedium(nmed));
         gGeoManager->SetAllIndex();
       }
     } else {
       TGeoMedium* med2= gGeoManager->GetMedium(mat1->GetName());
       v->SetMedium(med2);
     }
   } else {
     if (strcmp(v->ClassName(),"TGeoVolumeAssembly") != 0) {
       //[R.K.-3.3.08]  // When there is NO material defined, set it to avoid conflicts in Geant
       LOG(FATAL)<<"The volume "<< v->GetName() << "has no medium information and not an Assembly so we have to quit"<<FairLogger::endl;
     }
   }
 }
virtual void FairModule::BeginWorkerRun () const inline virtual
Init worker run (used in MT mode only)
Definition at line 81 of file FairModule.h.
 {;}
Bool_t FairModule::CheckIfSensitive (std::string name) virtual
Set the sensitivity flag for volumes, called from ConstructASCIIRootGeometry(), and has to be implimented for detectors which use ConstructASCIIRootGeometry() to build the geometry
Reimplemented in FairTutorialDet4, and FairMagnet.
Definition at line 520 of file FairModule.cxx.
References FairLogger::endl(), LOG, and WARNING.
Referenced by ExpandNode().
 {
   LOG(WARNING)<<"The method CheckIfSensitive has to be implemented in the detector class which inherits from FairModule"<<FairLogger::endl;
   return kFALSE;
 }
FairModule * FairModule::CloneModule () const virtual
Clone this object (used in MT mode only)
Definition at line 651 of file FairModule.cxx.
 {
   Fatal("CloneModule","Has to be overriden in multi-threading applications.");
   return 0;
 }
void FairModule::ConstructASCIIGeometry () virtual
construct geometry from standard ASSCII files (Hades Format)
Reimplemented in FairTutorialDet4, and FairMagnet.
Definition at line 514 of file FairModule.cxx.
References FairLogger::endl(), LOG, and WARNING.
 {
   LOG(WARNING)<<"The method ConstructASCIIGeometry has to be implemented in the detector class which inherits from FairModule"<<FairLogger::endl;
 }
template<class T , class U > void FairModule::ConstructASCIIGeometry (T dataType1, TString containerName = "", U datatype2 = NULL)
template function to construct geometry. to be used in derived classes.
Definition at line 156 of file FairModule.h.
References FairGeoInterface::addGeoModule(), FairLogger::endl(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), GetGeometryFileName(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), INFO, FairGeoLoader::Instance(), FairRun::Instance(), FairGeoNode::isSensitive(), LOG, ProcessNodes(), and FairGeoInterface::readSet().
 {
   FairGeoLoader* loader=FairGeoLoader::Instance();
   FairGeoInterface* GeoInterface =loader->getGeoInterface();
   T* MGeo=new T();
   MGeo->print();
   MGeo->setGeomFile(GetGeometryFileName());
   GeoInterface->addGeoModule(MGeo);
   Bool_t rc = GeoInterface->readSet(MGeo);
   if ( rc ) { MGeo->create(loader->getGeoBuilder()); }
   TList* volList = MGeo->getListOfVolumes();
   // store geo parameter
   FairRun* fRun = FairRun::Instance();
   FairRuntimeDb* rtdb= FairRun::Instance()->GetRuntimeDb();
   dataType1 = *MGeo;
   if ( "" != containerName) {
     LOG(INFO) << "Add GeoNodes for "<< MGeo->getDescription()
               << " to container " << containerName << FairLogger::endl;
     //    U par=(U)(rtdb->getContainer(containerName));
     U*      par=(U*)(rtdb->getContainer(containerName));
     TObjArray* fSensNodes = par->GetGeoSensitiveNodes();
     TObjArray* fPassNodes = par->GetGeoPassiveNodes();
     TListIter iter(volList);
     FairGeoNode* node   = NULL;
     FairGeoVolume* aVol=NULL;
     while( (node = (FairGeoNode*)iter.Next()) ) {
       aVol = dynamic_cast<FairGeoVolume*> ( node );
       if ( node->isSensitive()  ) {
         fSensNodes->AddLast( aVol );
       } else {
         fPassNodes->AddLast( aVol );
       }
     }
     ProcessNodes( volList );
     par->setChanged();
     par->setInputVersion(fRun->GetRunId(),1);
   }
 }
void FairModule::ConstructGDMLGeometry (TGeoMatrix * posrot) virtual
construct geometry from GDML files
Definition at line 462 of file FairModule.cxx.
References FairLogger::Error(), FairLogger::Fatal(), gLogger, and MESSAGE_ORIGIN.
 {
     gLogger->Error(MESSAGE_ORIGIN," Could not construct magnet geometry from gdml file. ");
     gLogger->Error(MESSAGE_ORIGIN," The used ROOT version does not support gdml. ");
     gLogger->Error(MESSAGE_ORIGIN," Please recompile ROOT with gdml support. ");
     gLogger->Fatal(MESSAGE_ORIGIN," Stop execution at this point. ");
 }
void FairModule::ConstructGeometry () virtual
method called from the MC application to construct the geometry, has to be implimented by user
Reimplemented in FairTutorialDet4, FairRutherford, FairTutorialDet1, FairTutorialDet2, FairTestDetector, NewDetector, NewDetector, MyCave, MyMagnet, MyPipe, FairMagnet, FairPipe, FairCave, and FairTarget.
Definition at line 62 of file FairModule.cxx.
References FairLogger::endl(), LOG, and WARNING.
Referenced by FairMCApplication::ConstructGeometry().
 {
   LOG(WARNING)<<"The method ConstructGeometry has to be implemented in the detector class which inherits from FairModule"<<FairLogger::endl;
 }
void FairModule::ConstructOpGeometry () virtual
method called from the MC application to set optical geometry properties
Definition at line 67 of file FairModule.cxx.
References DEBUG2, FairLogger::endl(), and LOG.
Referenced by FairMCApplication::ConstructOpGeometry().
 {
   LOG(DEBUG2)<<"The method ConstructOpGeometry has to be implemented in the detector class which inherits from FairModule"<<FairLogger::endl;;
 }
void FairModule::ConstructRootGeometry () virtual
construct geometry from root files (TGeo)
Construct the detector geometry from ROOT files, possible inputs are:
A TGeoVolume as a mother (master) volume containing the detector geometry
A TGeoManager with the detector geometry
A TGeoVolume as a mother or Master volume which is the output of the CAD2ROOT geometry, in this case the materials are not proprely defined and had to be reset In all cases we have to check that the material properties are the same or is the materials defined in the current simulation session
loop inside the delivered root file and try to fine a TGeoManager object the first TGeoManager found will be read
in case a TGeoManager was found get the top most volume and the node
The file does not contain any TGeoManager, so we assume to have a file with a TGeoVolume try to look for a TGeoVolume inside the file
Every thing is OK, we have a TGeoVolume and now we add it to the simulation TGeoManager
force rebuilding of voxels
To avoid having different names of the default matrices because we could have get the volume from another TGeoManager, we reset the default matrix name
NOw we can remove the matrix so that the new geomanager will rebuild it properly
Now we can add the node to the existing cave
correction from O. Merle: in case of a TGeoVolume (v1) set the material properly
now go through the herachy and set the materials properly, this is important becase the CAD converter produce TGeoVolumes with materials that have only names and no properties
Definition at line 315 of file FairModule.cxx.
References AssignMediumAtImport(), FairLogger::endl(), ExpandNode(), FATAL, fMotherVolumeName, GetGeometryFileName(), LOG, and SetDefaultMatrixName().
Referenced by FairMagnet::ConstructGeometry(), and FairTutorialDet4::ConstructGeometry().
 {
   TGeoManager* OldGeo=gGeoManager;
   TGeoManager* NewGeo=0;
   TGeoVolume* volume=0;;
   TFile* f=new TFile(GetGeometryFileName().Data());
   TList* l= f->GetListOfKeys();
   TKey* key;
   TIter next( l);
   TGeoNode* n=0;
   TGeoVolume* v1=0;
   while ((key = (TKey*)next())) {
     if (strcmp(key->GetClassName(),"TGeoManager") != 0) { continue; }
     gGeoManager=0;
     NewGeo = (TGeoManager*)key->ReadObj();
     break;
   }
   if (NewGeo!=0) {
     NewGeo->cd();
     volume=(TGeoVolume*)NewGeo->GetNode(0)->GetDaughter(0)->GetVolume();
     v1=volume->MakeCopyVolume(volume->GetShape());
     // n=NewGeo->GetTopNode();
     n=v1->GetNode(0);
     //  NewGeo=0;
     // delete NewGeo; //move it to the end of the method
   } else {
     key=(TKey*) l->At(0);  //Get the first key in the list
     volume=dynamic_cast<TGeoVolume*> (key->ReadObj());
     if(volume!=0) { n=volume->GetNode(0); }
     if(n!=0) { v1=n->GetVolume(); }
   }
   if(v1==0) {
     LOG(FATAL)<<"Could not find any geometry in file " << GetGeometryFileName().Data() << FairLogger::endl;
   } else {
     gGeoManager=OldGeo;
     gGeoManager->cd();
     // If AddToVolume is empty add the volume to the top volume Cave
     // If it is defined check if the volume exists and if it exists add the volume from the root file
     // to the already existing volume
     TGeoVolume* Cave=NULL;
     if ( 0 == fMotherVolumeName.Length() ) {
       Cave= gGeoManager->GetTopVolume();
     } else {
       Cave = gGeoManager->GetVolume(fMotherVolumeName);
     }
     if(Cave!=NULL) {
       gGeoManager->AddVolume(v1);
       TGeoVoxelFinder* voxels = v1->GetVoxels();
       if (voxels) { voxels->SetNeedRebuild(); }
       // else { fLogger->Fatal(MESSAGE_ORIGIN, "\033[5m\033[31mFairModule::ConstructRootGeometry(): could not find voxels  \033[0m"); }
       TGeoMatrix* M = n->GetMatrix();
       SetDefaultMatrixName(M);
       gGeoManager->GetListOfMatrices()->Remove(M);
       TGeoHMatrix* global = gGeoManager->GetHMatrix();
       gGeoManager->GetListOfMatrices()->Remove(global); //Remove the Identity matrix
       Cave->AddNode(v1,0, M);
       AssignMediumAtImport(v1);
       ExpandNode(n);
       if(NewGeo!=0) { delete NewGeo; }
       delete f;
     } else {
       LOG(FATAL)<<"Could not find the given mother volume "<< fMotherVolumeName.Data() << " where the geomanger should be added."<<FairLogger::endl;
     }
   }
 }
void FairModule::ExpandNode (TGeoNode * Node) virtual
called from ConstructRootGeometry()
Definition at line 527 of file FairModule.cxx.
References AddSensitiveVolume(), AssignMediumAtImport(), CheckIfSensitive(), DEBUG2, FairLogger::endl(), LOG, and SetDefaultMatrixName().
Referenced by ConstructRootGeometry().
 {
   //FairGeoLoader* geoLoad = FairGeoLoader::Instance();
   //FairGeoInterface* geoFace = geoLoad->getGeoInterface();
   //FairGeoMedia* Media =  geoFace->getMedia();
   //FairGeoBuilder* geobuild=geoLoad->getGeoBuilder();
   TGeoMatrix* Matrix =fN->GetMatrix();
   if(gGeoManager->GetListOfMatrices()->FindObject(Matrix)) { gGeoManager->GetListOfMatrices()->Remove(Matrix); }
   TGeoVolume* v1=fN->GetVolume();
   TObjArray* NodeList=v1->GetNodes();
   for (Int_t Nod=0; Nod<NodeList->GetEntriesFast(); Nod++) {
     TGeoNode* fNode =(TGeoNode*)NodeList->At(Nod);
     TGeoMatrix* M =fNode->GetMatrix();
     //M->SetDefaultName();
     SetDefaultMatrixName(M);
     if(fNode->GetNdaughters()>0) { ExpandNode(fNode); }
     TGeoVolume* v= fNode->GetVolume();
     AssignMediumAtImport(v);
     if (!gGeoManager->FindVolumeFast(v->GetName())) {
       LOG(DEBUG2)<<"Register Volume " << v->GetName()<<FairLogger::endl;
       v->RegisterYourself();
     }
     if ( (this->InheritsFrom("FairDetector")) && CheckIfSensitive(v->GetName())) {
       LOG(DEBUG2)<<"Sensitive Volume "<< v->GetName() << FairLogger::endl;
       AddSensitiveVolume(v);
     }
   }
 }
void FairModule::ExpandNodeForGDML (TGeoNode * curNode) virtual
called from ConstructGDMLGeometry()
Definition at line 470 of file FairModule.cxx.
 {
 }
virtual void FairModule::FinishWorkerRun () const inline virtual
Finish worker run (used in MT mode only)
Definition at line 83 of file FairModule.h.
 {;}
FairVolume * FairModule::getFairVolume (FairGeoNode * fNode)
Definition at line 300 of file FairModule.cxx.
References FairVolumeList::At(), FairVolumeList::getEntries(), FairVolume::getGeoNode(), and vList.
 {
   FairVolume* fv;
   FairVolume*  fvol=0;
   for(Int_t i=0; i<vList->getEntries(); i++) {
     fv=vList->At(i);
     if((fv->getGeoNode())==fN) {
       fvol=fv;
       return fvol;
       break;
     }
   }
   return fvol;
 }
virtual TString FairModule::GetGeometryFileName () inline virtual
Get the Geometry file name
Definition at line 63 of file FairModule.h.
References fgeoName.
Referenced by FairMagnet::ConstructASCIIGeometry(), ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairMagnet::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet4::ConstructGeometry(), and ConstructRootGeometry().
 {return  fgeoName ;}
virtual TString FairModule::GetGeometryFileVer () inline virtual
Get the geometry file version if used
Definition at line 65 of file FairModule.h.
References fgeoVer.
 {return   fgeoVer ;}
TList* FairModule::GetListOfGeoPar () inline
return the geo parameter of this detector/module
Definition at line 118 of file FairModule.h.
References flGeoPar.
 { return flGeoPar;}
Int_t FairModule::GetModId () inline
return the detector/Module id (which was set in the sim macro for the detector)
Definition at line 99 of file FairModule.h.
References fModId.
Referenced by FairMCApplication::ConstructGeometry(), and FairDetector::Initialize().
 {return fModId;}
virtual Int_t FairModule::getVolId (const TString & vname) const inline virtual
return the MC id of a volume named vname
Definition at line 97 of file FairModule.h.
 {return 0;}
virtual void FairModule::InitParContainers () inline virtual
Initialize everything which has to be done before the construction and modification of the geometry. Mostly this is needed to read data from the parameter containers.
Reimplemented in FairTutorialDet4.
Definition at line 116 of file FairModule.h.
 {;}
Bool_t FairModule::IsActive () inline
return the detector status
Definition at line 103 of file FairModule.h.
References fActive.
Referenced by FairMCApplication::FairMCApplication(), and FairMCApplication::operator=().
 {return fActive;}
virtual void FairModule::ModifyGeometry () inline virtual
Modify the geometry for the simulation run using methods of the Root geometry package
Reimplemented in FairTutorialDet4.
Definition at line 75 of file FairModule.h.
 {;}
FairModule & FairModule::operator= (const FairModule & rhs) protected
Definition at line 138 of file FairModule.cxx.
References fActive, fgeoName, fgeoVer, flGeoPar, fModId, fMotherVolumeName, fNbOfSensitiveVol, fVerboseLevel, kGeoSaved, and operator=().
Referenced by FairDetector::operator=().
 {
   // check assignment to self
   if (this == &rhs) return *this;
   // base class assignment
   TNamed::operator=(rhs);
   // assignment operator
   fMotherVolumeName = rhs.fMotherVolumeName;
   fgeoVer = rhs.fgeoVer;
   fgeoName = rhs.fgeoName;
   fModId = rhs.fModId;
   fActive = rhs.fActive;
   fNbOfSensitiveVol = rhs.fNbOfSensitiveVol;
   fVerboseLevel = rhs.fVerboseLevel;
   flGeoPar = 0;
   kGeoSaved = rhs.kGeoSaved;
   // TO DO - add when we know what type is the elements of flGeoPar
   //flGeoPar=new TObjArray();
   //TIter it = rhs.flGeoPar->MakeIterator();
   // copy parameters
   //TObject* obj;
   //while((obj=it->Next())) {
   //  flGeoPar->Add(...);
   //}
   return *this;
 }
virtual void FairModule::Print (Option_t * option = "") const inline virtual
Print method should be implemented in detector or module
Definition at line 59 of file FairModule.h.
 {;}
void FairModule::ProcessNodes (TList * aList)
called from ConstuctASCIIGeometry
Definition at line 243 of file FairModule.cxx.
References FairVolumeList::addVolume(), FairGeoNode::calcLabTransform(), fActive, fModId, fNbOfSensitiveVol, fNbOfVolumes, FairRuntimeDb::getContainer(), FairGeoNode::getCopyNo(), FairGeoParSet::GetGeoNodes(), FairGeoVolume::getMCid(), FairGeoNode::getMotherNode(), FairRun::GetRuntimeDb(), FairGeoNode::getTruncName(), FairRun::Instance(), FairGeoNode::isSensitive(), FairVolume::setCopyNo(), FairVolume::setGeoNode(), FairVolume::setModId(), FairVolume::SetModule(), FairVolume::setMotherCopyNo(), FairVolume::setMotherId(), FairVolume::setRealName(), svList, and vList.
Referenced by FairMagnet::ConstructASCIIGeometry(), ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), and FairRutherford::ConstructGeometry().
 {
   TListIter iter(aList);
   FairGeoNode* node   = NULL;
   FairGeoNode* MotherNode =NULL;
   FairVolume*  volume = NULL;
   FairRuntimeDb* rtdb= FairRun::Instance()->GetRuntimeDb();
   FairGeoParSet* par=(FairGeoParSet*)(rtdb->getContainer("FairGeoParSet"));
   TObjArray* fNodes = par->GetGeoNodes();
   while( (node = (FairGeoNode*)iter.Next()) ) {
     node->calcLabTransform();
     MotherNode=node->getMotherNode();
     volume = new FairVolume( node->getTruncName(), fNbOfVolumes++);
     volume->setRealName(node->GetName());
     vList->addVolume(volume);
     volume->setGeoNode(node);
     volume->setCopyNo(  node->getCopyNo());
     if(MotherNode!=0) {
       volume->setMotherId(node->getMCid());
       volume->setMotherCopyNo(MotherNode->getCopyNo());
     }
     FairGeoVolume* aVol=NULL;
     if ( node->isSensitive() && fActive ) {
       volume->setModId(fModId);
       volume->SetModule(this);
       svList->Add(volume);
       aVol = dynamic_cast<FairGeoVolume*> ( node );
       fNodes->AddLast( aVol );
       fNbOfSensitiveVol++;
     }
   }
 }
void FairModule::ReAssignMediaId () private
called from ConstructGDMLGeometry. Changes default ID created by TGDMLParse
Definition at line 476 of file FairModule.cxx.
References FairGeoLoader::getGeoBuilder(), FairGeoBuilder::GetNMedia(), FairGeoLoader::Instance(), and FairGeoBuilder::SetNMedia().
 {
     // Initialise pointer to GeoBuilder
     FairGeoBuilder* geoBuilder = FairGeoLoader::Instance()->getGeoBuilder();
     // Get list of TGeo media
     TList* media = gGeoManager->GetListOfMedia();
     // Loop over new media which are not in GeoBase and shift the ID
     TGeoMedium* med;
     TGeoMedium* med2;
     for(Int_t i = geoBuilder->GetNMedia(); i < media->GetEntries(); i++)
     {
         med = (TGeoMedium*) media->At(i);
         med->SetId(i+1);
     }
     // Change GeoBase medium index
     geoBuilder->SetNMedia(media->GetEntries());
     // Revove dublicated materials
     TList* materials = gGeoManager->GetListOfMaterials();
     TIter next1(materials);
     // map for existing materials
     std::map<TString, Bool_t> mapMatName;
     TGeoMaterial* mat;
     while( (mat = (TGeoMaterial*)next1()) )
     {
         // If material exist - delete dublicated. If not - set the flag
         if(mapMatName[mat->GetName()])
         {
             materials->Remove(mat);
         }
         else
         {
             mapMatName[mat->GetName()] = kTRUE;
         }
     }
 }
void FairModule::SetDefaultMatrixName (TGeoMatrix * matrix) private
Re-implimented from ROOT: TGeoMatrix::SetDefaultName()
Definition at line 557 of file FairModule.cxx.
Referenced by ConstructRootGeometry(), and ExpandNode().
 {
   // Copied from root TGeoMatrix::SetDefaultName() and modified (memory leak)
   // If no name was supplied in the ctor, the type of transformation is checked.
   // A letter will be prepended to the name :
   //   t - translation
   //   r - rotation
   //   s - scale
   //   c - combi (translation + rotation)
   //   g - general (tr+rot+scale)
   // The index of the transformation in gGeoManager list of transformations will
   // be appended.
   if (!gGeoManager) { return; }
   if (strlen(matrix->GetName())) { return; }
   char type = 'n';
   if (matrix->IsTranslation()) { type = 't'; }
   if (matrix->IsRotation()) { type = 'r'; }
   if (matrix->IsScale()) { type = 's'; }
   if (matrix->IsCombi()) { type = 'c'; }
   if (matrix->IsGeneral()) { type = 'g'; }
   TObjArray* matrices = gGeoManager->GetListOfMatrices();
   Int_t index = 0;
   if (matrices) { index =matrices->GetEntriesFast() - 1; }
   matrix->SetName(Form("%c%i", type, index));
 }
void FairModule::SetGeometryFileName (TString fname, TString geoVer = "0") virtual
Set the geometry file name o be used
Definition at line 189 of file FairModule.cxx.
References DEBUG, FairLogger::endl(), FATAL, fgeoName, and LOG.
Referenced by run_bg(), run_rad(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial2(), run_tutorial4(), and TEST().
 {
   // If absolute path is given as argument, try to find it there.
   // If the file don't exist break. Don't look anywhere else.
   if ( fname.BeginsWith("/") ) {
     if ( gSystem->AccessPathName(fname.Data()) ) {
       LOG(FATAL) << fName << ": geometry file " << fname
                  << " not found in absolut path!"
                  << FairLogger::endl;
       fgeoName = "";
     } // file not found
     fgeoName = fname;
     LOG(DEBUG) << fName << ": using geometry file "
                << fgeoName << FairLogger::endl;
     return;
   }
   // If GEOMPATH is set, try to find the file there.
   // If there is no such file go on to look in the default location.
   TString userPath = getenv("GEOMPATH");
   if ( ! userPath.IsNull() ) {
     if ( ! userPath.EndsWith("/") ) {
       userPath += "/";
     }
     fgeoName = userPath + fname;
     if ( ! gSystem->AccessPathName(fgeoName.Data()) ) {
       LOG(DEBUG) << fName << ": using geometry file " << fgeoName
                  << FairLogger::endl;
       return;
     }
     LOG(DEBUG) << fName << ": geometry file " << fname
                << " not found in GEOMPATH "
                << userPath << FairLogger::endl;
   }
   // Look in the standard path
   fgeoName = getenv("VMCWORKDIR");
   fgeoName += "/geometry/" + fname;
   if ( ! gSystem->AccessPathName(fgeoName.Data()) ) {
     LOG(DEBUG) << fName << ": using geometry file "
                << fgeoName << FairLogger::endl;
     return;
   }
   // File not found
   LOG(FATAL) << fName << ": geometry file " << fname
              << " not found in standard path "
              << FairLogger::endl;
   fgeoName = "";
   return;
 }
void FairModule::SetModId (Int_t id) inline
set the detector/module id
Definition at line 105 of file FairModule.h.
References fModId.
Referenced by FairRunSim::AddModule().
 {fModId=id;}
void FairModule::SetMotherVolume (TString volName) inline
Set the name of the mother volume to which a new geometry is added. This function is needed for geometries which are defined as ROOT geometry manager.
Definition at line 109 of file FairModule.h.
References fMotherVolumeName.
 {fMotherVolumeName=volName;}
virtual void FairModule::SetParContainers () inline virtual
Set the parameter containers
Reimplemented in FairTutorialDet4.
Definition at line 113 of file FairModule.h.
Referenced by FairMCApplication::SetParTask().
 {;}
void FairModule::SetVerboseLevel (Int_t level) inline
Set the verbose level in this detector
Definition at line 101 of file FairModule.h.
References fVerboseLevel.
 {fVerboseLevel=level;}
void FairModule::swap (FairModule & other) throw () private
Member Data Documentation
Bool_t FairModule::fActive protected
Definition at line 146 of file FairModule.h.
Referenced by IsActive(), operator=(), and ProcessNodes().
TString FairModule::fgeoName protected
Definition at line 144 of file FairModule.h.
Referenced by GetGeometryFileName(), operator=(), and SetGeometryFileName().
TString FairModule::fgeoVer protected
Definition at line 143 of file FairModule.h.
Referenced by GetGeometryFileVer(), and operator=().
TList* FairModule::flGeoPar protected
Definition at line 149 of file FairModule.h.
Referenced by FairDetector::FairDetector(), GetListOfGeoPar(), operator=(), FairDetector::SaveGeoParams(), and FairDetector::~FairDetector().
Int_t FairModule::fModId protected
Definition at line 145 of file FairModule.h.
Referenced by AddSensitiveVolume(), GetModId(), operator=(), ProcessNodes(), and SetModId().
TString FairModule::fMotherVolumeName
Definition at line 128 of file FairModule.h.
Referenced by ConstructRootGeometry(), operator=(), and SetMotherVolume().
Int_t FairModule::fNbOfSensitiveVol protected
Definition at line 147 of file FairModule.h.
Referenced by AddSensitiveVolume(), operator=(), and ProcessNodes().
Int_t FairModule::fNbOfVolumes =0 static
total number of volumes in a simulaion session
Definition at line 123 of file FairModule.h.
Referenced by AddSensitiveVolume(), and ProcessNodes().
Int_t FairModule::fVerboseLevel protected
Definition at line 148 of file FairModule.h.
Referenced by operator=(), and SetVerboseLevel().
Bool_t FairModule::kGeoSaved protected
list of Detector Geometry parameters
Definition at line 150 of file FairModule.h.
Referenced by FairDetector::FairDetector(), operator=(), and FairDetector::SaveGeoParams().
TRefArray * FairModule::svList =0 static
list of all sensitive volumes in a simulaion session
Definition at line 125 of file FairModule.h.
Referenced by AddSensitiveVolume(), FairMCApplication::ConstructGeometry(), FairModule(), FairDetector::Initialize(), and ProcessNodes().
FairVolumeList * FairModule::vList =0 static
list of volumes in a simulation session
Definition at line 121 of file FairModule.h.
Referenced by AddSensitiveVolume(), FairModule(), getFairVolume(), and ProcessNodes().
TArrayI * FairModule::volNumber =0 static
Definition at line 127 of file FairModule.h.
The documentation for this class was generated from the following files:
FairModule.h
FairModule.cxx