FairRroot: FairTestDetectorHitProducerSmearing Class Reference
FairTestDetectorHitProducerSmearing Class Reference
#include <FairTestDetectorHitProducerSmearing.h>
Public Member Functions
FairTestDetectorHitProducerSmearing ()
~FairTestDetectorHitProducerSmearing ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void Exec (Option_t *opt)
virtual void SetParContainers ()
virtual void Finish ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairTestDetectorHitProducerSmearing (const FairTestDetectorHitProducerSmearing &)
FairTestDetectorHitProducerSmearing operator= (const FairTestDetectorHitProducerSmearing &)
ClassDef (FairTestDetectorHitProducerSmearing, 1)
Private Attributes
TClonesArray * fPointsArray
TClonesArray * fHitsArray
Detailed Description
Definition at line 17 of file FairTestDetectorHitProducerSmearing.h.
Constructor & Destructor Documentation
FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing ()
Default constructor
Definition at line 22 of file FairTestDetectorHitProducerSmearing.cxx.
References FairLogger::Debug(), FairTask::fLogger, and MESSAGE_ORIGIN.
     : FairTask("FairTestDetectorHitProducerSmearing")
     , fPointsArray(NULL)
     , fHitsArray(new TClonesArray("FairTestDetectorHit", 100))
 {
     fLogger->Debug(MESSAGE_ORIGIN, "Defaul Constructor of FairTestDetectorHitProducerSmearing");
 }
FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing ()
Destructor
Definition at line 31 of file FairTestDetectorHitProducerSmearing.cxx.
References FairLogger::Debug(), fHitsArray, FairTask::fLogger, and MESSAGE_ORIGIN.
 {
     fLogger->Debug(MESSAGE_ORIGIN, "Destructor of FairTestDetectorHitProducerSmearing");
     fHitsArray->Delete();
     delete fHitsArray;
 }
FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing (const FairTestDetectorHitProducerSmearing &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTestDetectorHitProducerSmearing::ClassDef (FairTestDetectorHitProducerSmearing , 1) private
void FairTestDetectorHitProducerSmearing::Exec (Option_t * opt) virtual
Executed for each event.
Definition at line 87 of file FairTestDetectorHitProducerSmearing.cxx.
References FairLogger::Debug(), fHitsArray, FairTask::fLogger, fPointsArray, FairMCPoint::GetDetectorID(), MESSAGE_ORIGIN, and FairMCPoint::Position().
 {
     fLogger->Debug(MESSAGE_ORIGIN, "Exec of FairTestDetectorHitProducerSmearing");
     fHitsArray->Delete();
     // fill the map
     FairTestDetectorPoint* point = NULL;
     FairTestDetectorHit* hit = NULL;
     for (int iPoint = 0; iPoint < fPointsArray->GetEntriesFast(); iPoint++)
     {
         point = (FairTestDetectorPoint*)fPointsArray->At(iPoint);
         if (!point)
         {
             continue;
         }
         TVector3 position;
         point->Position(position);
         TVector3 dposition;
         // simulate the detector response: smear position with gaussians
         dposition.SetXYZ(0.05, 0.05, 0.);
         position.SetXYZ(gRandom->Gaus(position.X(), 0.05), gRandom->Gaus(position.Y(), 0.05), position.Z());
         hit = new ((*fHitsArray)[iPoint]) FairTestDetectorHit(point->GetDetectorID(), iPoint, position, dposition);
     }
 }
void FairTestDetectorHitProducerSmearing::Finish () virtual
Finish task called at the end of the run
Reimplemented from FairTask.
Definition at line 118 of file FairTestDetectorHitProducerSmearing.cxx.
References FairLogger::Debug(), FairTask::fLogger, and MESSAGE_ORIGIN.
 {
     fLogger->Debug(MESSAGE_ORIGIN, "Finish of FairTestDetectorHitProducerSmearing");
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
InitStatus FairTestDetectorHitProducerSmearing::Init () virtual
Initiliazation of task at the beginning of a run
Reimplemented from FairTask.
Definition at line 53 of file FairTestDetectorHitProducerSmearing.cxx.
References FairLogger::Debug(), FairLogger::Error(), fHitsArray, FairTask::fLogger, fPointsArray, FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kSUCCESS, MESSAGE_ORIGIN, and FairRootManager::Register().
 {
     fLogger->Debug(MESSAGE_ORIGIN, "Initilization of FairTestDetectorHitProducerSmearing");
     // Get a handle from the IO manager
     FairRootManager* ioman = FairRootManager::Instance();
     // Get a pointer to the previous already existing data level
     fPointsArray = (TClonesArray*)ioman->GetObject("FairTestDetectorPoint");
     if (!fPointsArray)
     {
         fLogger->Error(MESSAGE_ORIGIN, "No InputDataLevelName array!\n FairTestDetectorHitProducerSmearing will be inactive");
         return kERROR;
     }
     // Create the TClonesArray for the output data and register
     // it in the IO manager
     ioman->Register("FairTestDetectorHit", "FairTestDetectorHit", fHitsArray, kTRUE);
     // Do whatever else is needed at the initilization stage
     // Create histograms to be filled
     // initialize variables
     return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairTestDetectorHitProducerSmearing FairTestDetectorHitProducerSmearing::operator= (const FairTestDetectorHitProducerSmearing &) private
InitStatus FairTestDetectorHitProducerSmearing::ReInit () virtual
ReInitiliazation of task when the runID changes
Reimplemented from FairTask.
Definition at line 80 of file FairTestDetectorHitProducerSmearing.cxx.
References FairLogger::Debug(), FairTask::fLogger, kSUCCESS, and MESSAGE_ORIGIN.
 {
     fLogger->Debug(MESSAGE_ORIGIN, "Initilization of FairTestDetectorHitProducerSmearing");
     return kSUCCESS;
 }
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairTestDetectorHitProducerSmearing::SetParContainers () virtual
Load the parameter container from the runtime database
Reimplemented from FairTask.
Definition at line 39 of file FairTestDetectorHitProducerSmearing.cxx.
References FairLogger::Debug(), FairTask::fLogger, and MESSAGE_ORIGIN.
 {
     fLogger->Debug(MESSAGE_ORIGIN, "SetParContainers of FairTestDetectorHitProducerSmearing");
     // Load all necessary parameter containers from the runtime data base
     /*
     FairRunAna* ana = FairRunAna::Instance();
     FairRuntimeDb* rtdb=ana->GetRuntimeDb();
     <FairTestDetectorHitProducerSmearingDataMember> = (<ClassPointer>*)
       (rtdb->getContainer("<ContainerName>"));
     */
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
TClonesArray* FairTestDetectorHitProducerSmearing::fHitsArray private
Output array to new data level
Definition at line 46 of file FairTestDetectorHitProducerSmearing.h.
Referenced by Exec(), Init(), and ~FairTestDetectorHitProducerSmearing().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), ~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
TClonesArray* FairTestDetectorHitProducerSmearing::fPointsArray private
Input array from previous already existing data level
Definition at line 43 of file FairTestDetectorHitProducerSmearing.h.
Referenced by Exec(), and Init().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairMCTracks::Exec(), FairMCStack::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairMCTracks::Init(), FairMCStack::Init(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairTestDetectorHitProducerSmearing.h
FairTestDetectorHitProducerSmearing.cxx