FairRoot: runFileSinkBin.cxx File Reference
Tutorial7/run/runFileSinkBin.cxx File Reference
#include <iostream>
#include <csignal>
#include "boost/program_options.hpp"
#include "zeromq/FairMQTransportFactoryZMQ.h"
#include "FairMQLogger.h"
#include "GenericFileSink.h"
#include "RootOutFileManager.h"
#include "MyHit.h"
#include "MyHitSerializer.h"
Classes
struct DeviceOptions
Typedefs
typedef MyHit THit
typedef MyHitDeSerializer_t TInputPolicy
typedef RootOutFileManager< THit > TOutputPolicy
typedef GenericFileSink< TInputPolicy, TOutputPolicy > TSink
typedef struct DeviceOptions DeviceOptions_t
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
bool parse_cmd_line (int _argc, char *_argv[], DeviceOptions *_options)
int main (int argc, char **argv)
Variables
TSink filesink
Typedef Documentation
typedef struct DeviceOptions DeviceOptions_t
typedef MyHit THit
Definition at line 48 of file Tutorial7/run/runFileSinkBin.cxx.
typedef MyHitDeSerializer_t TInputPolicy
Definition at line 49 of file Tutorial7/run/runFileSinkBin.cxx.
typedef RootOutFileManager<THit> TOutputPolicy
Definition at line 51 of file Tutorial7/run/runFileSinkBin.cxx.
typedef GenericFileSink<TInputPolicy,TOutputPolicy> TSink
Definition at line 52 of file Tutorial7/run/runFileSinkBin.cxx.
Function Documentation
int main (int argc, char ** argv)
Definition at line 170 of file Tutorial7/run/runFileSinkBin.cxx.
References FairMQStateMachine::BIND, DeviceOptions::branchname, FairMQStateMachine::ChangeState(), DeviceOptions::classname, FairMQStateMachine::CONNECT, FairMQStateMachine::END, ERROR, DeviceOptions::filename, DeviceOptions::fileoption, FairMQStateMachine::fRunningCondition, FairMQStateMachine::fRunningFinished, FairMQStateMachine::fRunningMutex, FairMQDevice::Id, DeviceOptions::id, INFO, FairMQStateMachine::INIT, FairMQDevice::InputAddress, DeviceOptions::inputAddress, DeviceOptions::inputBufSize, FairMQDevice::InputMethod, DeviceOptions::inputMethod, FairMQDevice::InputRcvBufSize, FairMQDevice::InputSocketType, DeviceOptions::inputSocketType, DeviceOptions::ioThreads, MQLOG, FairMQDevice::NumInputs, FairMQDevice::NumIoThreads, FairMQDevice::NumOutputs, parse_cmd_line(), FairMQStateMachine::RUN, s_catch_signals(), FairMQStateMachine::SETINPUT, FairMQStateMachine::SETOUTPUT, FairMQDevice::SetProperty(), FairMQDevice::SetTransport(), FairMQStateMachine::STOP, DeviceOptions::treename, and DeviceOptions::useTClonesArray.
 {
     s_catch_signals();
     DeviceOptions_t options;
     try
     {
         if (!parse_cmd_line(argc, argv, &options))
             return 0;
     }
     catch (exception& e)
     {
         MQLOG(ERROR) << e.what();
         return 1;
     }
     MQLOG(INFO) << "PID: " << getpid();
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     filesink.SetTransport(transportFactory);
     filesink.SetProperty(TSink::Id, options.id);
     filesink.SetProperty(TSink::NumIoThreads, options.ioThreads);
     filesink.SetProperty(TSink::NumInputs, 1);
     filesink.SetProperty(TSink::NumOutputs, 0);
     filesink.InitInputContainer( options.classname.c_str() );
     filesink.SetFileProperties(options.filename,options.treename,options.branchname,options.classname,
                                                 options.fileoption,options.useTClonesArray);
     filesink.ChangeState(TSink::INIT);
     filesink.SetProperty(TSink::InputSocketType, options.inputSocketType);
     filesink.SetProperty(TSink::InputRcvBufSize, options.inputBufSize);
     filesink.SetProperty(TSink::InputMethod, options.inputMethod);
     filesink.SetProperty(TSink::InputAddress, options.inputAddress);
     filesink.ChangeState(TSink::SETOUTPUT);
     filesink.ChangeState(TSink::SETINPUT);
     filesink.ChangeState(TSink::BIND);
     filesink.ChangeState(TSink::CONNECT);
     filesink.ChangeState(TSink::RUN);
     // wait until the running thread has finished processing.
     boost::unique_lock<boost::mutex> lock(filesink.fRunningMutex);
     while (!filesink.fRunningFinished)
     {
         filesink.fRunningCondition.wait(lock);
     }
     filesink.ChangeState(TSink::STOP);
     filesink.ChangeState(TSink::END);
     return 0;
 }
bool parse_cmd_line (int _argc, char * _argv[], DeviceOptions * _options) inline
Definition at line 98 of file Tutorial7/run/runFileSinkBin.cxx.
References DeviceOptions::branchname, DeviceOptions::classname, DeviceOptions::filename, DeviceOptions::fileoption, DeviceOptions::id, INFO, DeviceOptions::inputAddress, DeviceOptions::inputBufSize, DeviceOptions::inputMethod, DeviceOptions::inputSocketType, DeviceOptions::ioThreads, MQLOG, DeviceOptions::treename, and DeviceOptions::useTClonesArray.
Referenced by main().
 {
     if (_options == NULL)
         throw std::runtime_error("Internal error: options' container is empty.");
     namespace bpo = boost::program_options;
     bpo::options_description desc("Options");
     desc.add_options()
         ("id", bpo::value<string>()->required(), "Device ID")
         ("io-threads", bpo::value<int>()->default_value(1), "Number of I/O threads")
         ("input-socket-type", bpo::value<string>()->required(), "Input socket type: sub/pull")
         ("input-buff-size", bpo::value<int>()->required(), "Input buffer size in number of messages (ZeroMQ)/bytes(nanomsg)")
         ("input-method", bpo::value<string>()->required(), "Input method: bind/connect")
         ("input-address", bpo::value<string>()->required(), "Input address, e.g.: \"tcp://*:5555\"")
         ("input-file", bpo::value<string>()->required(), "Prefix of the output file")
         ("tree", bpo::value<string>()->required(), "Name of the tree (for root file output)")
         ("branch", bpo::value<string>()->required(), "Name of the branch (for root file output)")
         ("class-name", bpo::value<string>()->required(), "Name of the payload class")
         ("file-option", bpo::value<string>()->default_value("RECREATE"), "Root file option : UPDATE, RECREATE etc.")
         ("use-TClonesArray", bpo::value<bool>()->default_value(true), "Method used to store data in root file")
         ("help", "Print help messages");
     bpo::variables_map vm;
     bpo::store(bpo::parse_command_line(_argc, _argv, desc), vm);
     if ( vm.count("help") )
     {
         MQLOG(INFO) << "FairMQ File Sink" << endl << desc;
         return false;
     }
     bpo::notify(vm);
     if ( vm.count("id") )
         _options->id = vm["id"].as<string>();
     if ( vm.count("io-threads") )
         _options->ioThreads = vm["io-threads"].as<int>();
     if ( vm.count("input-socket-type") )
         _options->inputSocketType = vm["input-socket-type"].as<string>();
     if ( vm.count("input-buff-size") )
         _options->inputBufSize = vm["input-buff-size"].as<int>();
     if ( vm.count("input-method") )
         _options->inputMethod = vm["input-method"].as<string>();
     if ( vm.count("input-address") )
         _options->inputAddress = vm["input-address"].as<string>();
     if ( vm.count("input-file") )
         _options->filename = vm["input-file"].as<string>();
     if ( vm.count("tree") )
         _options->treename = vm["tree"].as<string>();
     if ( vm.count("branch") )
         _options->branchname = vm["branch"].as<string>();
     if ( vm.count("class-name") )
         _options->classname = vm["class-name"].as<string>();
     if ( vm.count("file-option") )
         _options->fileoption = vm["file-option"].as<string>();
     if ( vm.count("use-TClonesArray") )
         _options->useTClonesArray = vm["use-TClonesArray"].as<bool>();
     return true;
 }
static void s_catch_signals (void) static
Definition at line 67 of file Tutorial7/run/runFileSinkBin.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 56 of file Tutorial7/run/runFileSinkBin.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, and FairMQStateMachine::STOP.
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     filesink.ChangeState(TSink::STOP);
     filesink.ChangeState(TSink::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
TSink filesink
Definition at line 54 of file Tutorial7/run/runFileSinkBin.cxx.