FairRoot: FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut > Class Template Reference
FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut > Class Template Reference
#include <FairTestDetectorMQRecoTask.h>
Public Member Functions
FairTestDetectorMQRecoTask ()
FairTestDetectorMQRecoTask (Int_t verbose)
virtual ~FairTestDetectorMQRecoTask ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt="0")
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
FairTestDetectorMQRecoTask ()
FairTestDetectorMQRecoTask (Int_t verbose)
virtual ~FairTestDetectorMQRecoTask ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt="0")
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
void SetSendPart (boost::function< void()>)
void SetReceivePart (boost::function< bool()>)
FairMQMessage * GetPayload ()
void SetPayload (FairMQMessage *msg)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
FairMQMessage * fPayload
boost::function< void()> SendPart
boost::function< bool()> ReceivePart
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairTestDetectorMQRecoTask (const FairTestDetectorMQRecoTask &)
Copy Constructor.
FairTestDetectorMQRecoTask operator= (const FairTestDetectorMQRecoTask &)
Private Attributes
FairTestDetectorRecoTask * fRecoTask
vector< TIn > fDigiVector
vector< TOut > fHitVector
bool fHasBoostSerialization
FairRuntimeDb * fRtdb
std::vector< TIn > fDigiVector
std::vector< TOut > fHitVector
FairDbMQParMgr * fParMgr
Friends
class boost::serialization::access
Detailed Description
template<typename TIn, typename TOut, typename TPayloadIn, typename TPayloadOut>
class FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >
Definition at line 49 of file Tutorial3/reconstruction/FairTestDetectorMQRecoTask.h.
Constructor & Destructor Documentation
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::FairTestDetectorMQRecoTask ()
Default constructor
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::FairTestDetectorMQRecoTask (Int_t verbose)
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > virtual FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::~FairTestDetectorMQRecoTask () virtual
Destructor
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::FairTestDetectorMQRecoTask (const FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut > &) private
Copy Constructor.
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::FairTestDetectorMQRecoTask ()
Default constructor
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::FairTestDetectorMQRecoTask (Int_t verbose)
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > virtual FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::~FairTestDetectorMQRecoTask () virtual
Destructor
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > virtual void FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Exec (Option_t * opt = "0") virtual
Virtual method Exec
Reimplemented from FairMQProcessorTask.
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > virtual void FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Exec (Option_t * opt = "0") virtual
Virtual method Exec
Reimplemented from FairMQProcessorTask.
virtual void FairTask::Finish () inline protected virtual inherited
Action after each event. To be implemented in the derived class
Reimplemented in FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairMCMatchLoaderTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, FairDbTutAccessRtdbTask, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 111 of file FairTask.h.
Referenced by FairTask::FinishTask(), and FairTask::FinishTasks().
 { };
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
FairMQMessage * FairMQProcessorTask::GetPayload () inherited
Definition at line 45 of file FairMQProcessorTask.cxx.
References FairMQProcessorTask::fPayload.
Referenced by FairMQProcessor::ReceivePart(), FairMQProcessor::Run(), and FairMQProcessor::SendPart().
 {
   return fPayload;
 }
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > virtual InitStatus FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init () virtual
Virtual method Init
Reimplemented from FairTask.
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > virtual InitStatus FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::Init () virtual
Virtual method Init
Reimplemented from FairTask.
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::InitTasks(), and FairTask::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairTestDetectorMQRecoTask FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::operator= (const FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut > &) private
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > template<class Archive > void FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::serialize (Archive & ar, const unsigned int version) inline
Definition at line 67 of file Tutorial3/reconstruction/FairTestDetectorMQRecoTask.h.
     {
         ar& fDigiVector;
         ar& fHitVector;
     }
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > template<class Archive > void FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::serialize (Archive & ar, const unsigned int version) inline
Definition at line 77 of file Tutorial6/reco/FairTestDetectorMQRecoTask.h.
References FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fDigiVector, and FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fHitVector.
     {
         ar& fDigiVector;
         ar& fHitVector;
     }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
virtual void FairTask::SetParContainers () inline protected virtual inherited
Intialise parameter containers. To be implemented in the derived class.
Reimplemented in FairRingSorterTask, FairEventBuilderManager, FairBoxSetDraw, FairPointSetDraw, FairMCStack, FairMCTracks, FairTutorialDet4HitProducerIdealMisalign, FairMCMatchSelectorTask, FairMCMatchCreatorTask, FairTutorialDet2Digitizer, FairTutorialDet4MilleWriter, FairMCMatchLoaderTask, FairTutorialDet4StraightLineFitter, NewTask, FairDbTutAccessRtdbTask, and FairTestDetectorHitProducerSmearing.
Definition at line 107 of file FairTask.h.
Referenced by FairTask::SetParTask().
 { };
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunOnline::Init(), FairRunAna::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairMQProcessorTask::SetPayload (FairMQMessage * msg) inherited
Definition at line 50 of file FairMQProcessorTask.cxx.
References ERROR, FairMQProcessorTask::fPayload, and LOG.
Referenced by FairMQProcessor::ReceivePart(), and FairMQProcessor::Run().
 {
     if(msg)
     {
         fPayload = msg;
     }
     else
     {
         LOG(ERROR) << "FairMQMessage uninitialized or bad format";
     }
 }
void FairMQProcessorTask::SetReceivePart (boost::function< bool()> callback) inherited
Definition at line 40 of file FairMQProcessorTask.cxx.
References FairMQProcessorTask::ReceivePart.
Referenced by FairMQProcessor::Init().
 {
     ReceivePart = callback;
 }
void FairMQProcessorTask::SetSendPart (boost::function< void()> callback) inherited
Definition at line 34 of file FairMQProcessorTask.cxx.
References FairMQProcessorTask::SendPart.
Referenced by FairMQProcessor::Init().
 {
     SendPart = callback;
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Friends And Related Function Documentation
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > boost::serialization::access friend
Definition at line 76 of file Tutorial3/reconstruction/FairTestDetectorMQRecoTask.h.
Member Data Documentation
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > vector<TIn> FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fDigiVector private
Definition at line 77 of file Tutorial3/reconstruction/FairTestDetectorMQRecoTask.h.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::serialize().
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > std::vector<TIn> FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fDigiVector private
Definition at line 88 of file Tutorial6/reco/FairTestDetectorMQRecoTask.h.
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > bool FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fHasBoostSerialization private
Definition at line 79 of file Tutorial3/reconstruction/FairTestDetectorMQRecoTask.h.
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > vector<TOut> FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fHitVector private
Definition at line 78 of file Tutorial3/reconstruction/FairTestDetectorMQRecoTask.h.
Referenced by FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::serialize().
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > std::vector<TOut> FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fHitVector private
Definition at line 89 of file Tutorial6/reco/FairTestDetectorMQRecoTask.h.
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by NewTask::Exec(), NewTask::Finish(), NewTask::Init(), FairTask::InitTask(), NewTask::NewTask(), NewTask::ReInit(), FairTask::ReInitTask(), NewTask::SetParContainers(), and NewTask::~NewTask().
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairDbMQParMgr* FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fParMgr private
Definition at line 94 of file Tutorial6/reco/FairTestDetectorMQRecoTask.h.
FairMQMessage* FairMQProcessorTask::fPayload protected inherited
Definition at line 40 of file FairMQProcessorTask.h.
Referenced by FairMQProcessorTask::GetPayload(), and FairMQProcessorTask::SetPayload().
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairTestDetectorRecoTask * FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fRecoTask private
Definition at line 74 of file Tutorial3/reconstruction/FairTestDetectorMQRecoTask.h.
template<typename TIn , typename TOut , typename TPayloadIn , typename TPayloadOut > FairRuntimeDb* FairTestDetectorMQRecoTask< TIn, TOut, TPayloadIn, TPayloadOut >::fRtdb private
Definition at line 85 of file Tutorial6/reco/FairTestDetectorMQRecoTask.h.
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
boost::function<bool()> FairMQProcessorTask::ReceivePart protected inherited
Definition at line 42 of file FairMQProcessorTask.h.
Referenced by FairMQProcessorTask::SetReceivePart().
boost::function<void()> FairMQProcessorTask::SendPart protected inherited
Definition at line 41 of file FairMQProcessorTask.h.
Referenced by FairMQProcessorTask::SetSendPart().
The documentation for this class was generated from the following file:
Tutorial3/reconstruction/FairTestDetectorMQRecoTask.h