FairRroot: FairCuda Class Reference
FairCuda Class Reference
#include <FairCuda.h>
Public Member Functions
FairCuda ()
virtual ~FairCuda ()
void IncrementArray_ (Int_t device)
void DeviceInfo_ ()
void Filter (TMatrixD *h, TMatrixD *fM, TMatrixD *pull, TMatrixD *fH, TMatrixD *preC, TMatrixD *prea, TMatrixD *av, TMatrixD *curC, TMatrixD *fV, TMatrixD *fR, TMatrixD *fResVec, double *fDeltaChi2)
void CircleFit (Double_t X[HIT], Double_t Y[HIT], Double_t Z[HIT], Double_t Zerr[HIT], Double_t *Mx, Double_t *My, Double_t *M0, Double_t result[8])
void CircleFitAllD (Double_t X[TRK *HIT], Double_t Y[TRK *HIT], Double_t Z[TRK *HIT], Double_t Zerr[TRK *HIT], Double_t Mx[TRK], Double_t My[TRK], Double_t M0[TRK], Double_t result[8 *TRK])
void CircleFitAllF (Float_t X[TRK *HIT], Float_t Y[TRK *HIT], Float_t Z[TRK *HIT], Float_t Zerr[TRK *HIT], Float_t Mx[TRK], Float_t My[TRK], Float_t M0[TRK], Float_t result[8 *TRK])
void CircleFitF (Float_t X[HIT], Float_t Y[HIT], Float_t Z[HIT], Float_t Zerr[HIT], Float_t *Mx, Float_t *My, Float_t *M0, Float_t result[8])
Detailed Description
Definition at line 36 of file FairCuda.h.
Constructor & Destructor Documentation
FairCuda::FairCuda () inline
Definition at line 39 of file FairCuda.h.
 {;}
virtual FairCuda::~FairCuda () inline virtual
Definition at line 40 of file FairCuda.h.
 {;}
Member Function Documentation
void FairCuda::CircleFit (Double_t X[HIT], Double_t Y[HIT], Double_t Z[HIT], Double_t Zerr[HIT], Double_t * Mx, Double_t * My, Double_t * M0, Double_t result[8]) inline
Definition at line 51 of file FairCuda.h.
References CircleFitG().
{
       //  printf("\n Cuda  Mx = %f  My = %f\n ", Mx[0], My[0]);
       return CircleFitG(X,Y,Z,Zerr,Mx,My,M0,result);
     }
void FairCuda::CircleFitAllD (Double_t X[TRK *HIT], Double_t Y[TRK *HIT], Double_t Z[TRK *HIT], Double_t Zerr[TRK *HIT], Double_t Mx[TRK], Double_t My[TRK], Double_t M0[TRK], Double_t result[8 *TRK]) inline
Definition at line 57 of file FairCuda.h.
References CircleFitGAllD().
{
       //    printf("\n Fair Cuda  : Call GPU function \n ");
       return CircleFitGAllD(X,Y,Z,Zerr,Mx,My,M0,result);
 //       printf("\n Fair Cuda  : Back to Application \n ");
     }
void FairCuda::CircleFitAllF (Float_t X[TRK *HIT], Float_t Y[TRK *HIT], Float_t Z[TRK *HIT], Float_t Zerr[TRK *HIT], Float_t Mx[TRK], Float_t My[TRK], Float_t M0[TRK], Float_t result[8 *TRK]) inline
Definition at line 64 of file FairCuda.h.
References CircleFitGAllF().
{
 //       printf("\n Fair Cuda  : Call GPU function \n ");
       return CircleFitGAllF(X,Y,Z,Zerr,Mx,My,M0,result);
 //       printf("\n Fair Cuda  : Back to Application \n ");
     }
void FairCuda::CircleFitF (Float_t X[HIT], Float_t Y[HIT], Float_t Z[HIT], Float_t Zerr[HIT], Float_t * Mx, Float_t * My, Float_t * M0, Float_t result[8]) inline
Definition at line 73 of file FairCuda.h.
References CircleFitGF().
{
       //  printf("\n Cuda  Mx = %f  My = %f\n ", Mx[0], My[0]);
       return CircleFitGF(X,Y,Z,Zerr,Mx,My,M0,result);
     }
void FairCuda::DeviceInfo_ () inline
Definition at line 43 of file FairCuda.h.
References DeviceInfo().
Referenced by cuda_info().
 {return DeviceInfo();}
void FairCuda::Filter (TMatrixD * h, TMatrixD * fM, TMatrixD * pull, TMatrixD * fH, TMatrixD * preC, TMatrixD * prea, TMatrixD * av, TMatrixD * curC, TMatrixD * fV, TMatrixD * fR, TMatrixD * fResVec, double * fDeltaChi2) inline
Definition at line 46 of file FairCuda.h.
References CudaFilter().
{
       return CudaFilter(h,fM, pull, fH, preC, prea,av,curC, fV, fR,fResVec,fDeltaChi2);
     }
void FairCuda::IncrementArray_ (Int_t device) inline
Definition at line 42 of file FairCuda.h.
References IncrementArray().
 {return IncrementArray(device);}
The documentation for this class was generated from the following file:
FairCuda.h