FairRroot: FairCave.cxx File Reference
FairCave.cxx File Reference
#include "FairCave.h"
#include "FairGeoCave.h"
#include "FairGeoInterface.h"
#include "FairGeoLoader.h"
#include "FairGeoNode.h"
#include "FairGeoPassivePar.h"
#include "FairGeoVolume.h"
#include "FairRun.h"
#include "FairRuntimeDb.h"
#include "TList.h"
#include "TObjArray.h"
#include "TString.h"
#include <stddef.h>
Functions
ClassImp (FairCave) void FairCave
Function Documentation
ClassImp (FairCave)
Definition at line 26 of file FairCave.cxx.
References FairGeoInterface::addGeoModule(), FairGeoSet::create(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairGeoPassivePar::GetGeoPassiveNodes(), FairGeoPassivePar::GetGeoSensitiveNodes(), FairGeoSet::getListOfVolumes(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairGeoLoader::Instance(), FairRun::Instance(), FairGeoNode::isSensitive(), FairGeoInterface::readSet(), FairParSet::setChanged(), FairGeoSet::setGeomFile(), and FairParSet::setInputVersion().
 {
   FairGeoLoader* loader=FairGeoLoader::Instance();
   FairGeoInterface* GeoInterface =loader->getGeoInterface();
   FairGeoCave* MGeo=new FairGeoCave();
   MGeo->setGeomFile(GetGeometryFileName());
   GeoInterface->addGeoModule(MGeo);
   Bool_t rc = GeoInterface->readSet(MGeo);
   if ( rc ) { MGeo->create(loader->getGeoBuilder()); }
   TList* volList = MGeo->getListOfVolumes();
   // store geo parameter
   FairRun* fRun = FairRun::Instance();
   FairRuntimeDb* rtdb= FairRun::Instance()->GetRuntimeDb();
   FairGeoPassivePar* par=(FairGeoPassivePar*)(rtdb->getContainer("FairGeoPassivePar"));
   TObjArray* fSensNodes = par->GetGeoSensitiveNodes();
   TObjArray* fPassNodes = par->GetGeoPassiveNodes();
   TListIter iter(volList);
   FairGeoNode* node   = NULL;
   FairGeoVolume* aVol=NULL;
   while( (node = (FairGeoNode*)iter.Next()) ) {
     aVol = dynamic_cast<FairGeoVolume*> ( node );
     if ( node->isSensitive()  ) {
       fSensNodes->AddLast( aVol );
     } else {
       fPassNodes->AddLast( aVol );
     }
   }
   par->setChanged();
   par->setInputVersion(fRun->GetRunId(),1);
 }