FairRoot: MyFieldCreator Class Reference
MyFieldCreator Class Reference
#include <MyFieldCreator.h>
Public Member Functions
MyFieldCreator ()
virtual ~MyFieldCreator ()
virtual FairField * createFairField ()
virtual void SetParm ()
ClassDef (MyFieldCreator, 1)
Static Public Member Functions
static FairFieldFactory * Instance ()
Protected Attributes
MyFieldPar * fFieldPar
FairFieldFactory * fCreator
Static Protected Attributes
static FairFieldFactory * fgRinstance = 0
Private Member Functions
MyFieldCreator (const MyFieldCreator &)
MyFieldCreator & operator= (const MyFieldCreator &)
Detailed Description
Definition at line 24 of file MyFieldCreator.h.
Constructor & Destructor Documentation
MyFieldCreator::MyFieldCreator ()
Definition at line 29 of file MyFieldCreator.cxx.
References FairFieldFactory::fCreator.
   :FairFieldFactory(),
    fFieldPar(NULL)
 {
         fCreator=this;
 }
MyFieldCreator::~MyFieldCreator () virtual
Definition at line 36 of file MyFieldCreator.cxx.
 {
 }
MyFieldCreator::MyFieldCreator (const MyFieldCreator &) private
Member Function Documentation
MyFieldCreator::ClassDef (MyFieldCreator , 1)
FairField * MyFieldCreator::createFairField () virtual
Reimplemented from FairFieldFactory.
Definition at line 48 of file MyFieldCreator.cxx.
References FairField(), fFieldPar, fType, and MyFieldPar::GetType().
 {
   FairField *fMagneticField=0;
   if ( ! fFieldPar ) {
     cerr << "-E-  No field parameters available!"
          << endl;
   }else{
         // Instantiate correct field type
         Int_t fType = fFieldPar->GetType();
         if      ( fType == 0 ) fMagneticField = new MyConstField(fFieldPar);
     else cerr << "-W- FairRunAna::GetField: Unknown field type " << fType
                 << endl;
         cout << "New field at " << fMagneticField << ", type " << fType << endl;
         // Initialise field
         if ( fMagneticField ) {
                 fMagneticField->Init();
                 fMagneticField->Print();
         }
   }
   return fMagneticField;
 }
FairFieldFactory * FairFieldFactory::Instance () static inherited
Definition at line 30 of file FairFieldFactory.cxx.
References FairFieldFactory::fgRinstance.
Referenced by FairRunAnaProof::Init(), and FairRunAna::Init().
 {
   return fgRinstance;
 }
MyFieldCreator& MyFieldCreator::operator= (const MyFieldCreator &) private
void MyFieldCreator::SetParm () virtual
Reimplemented from FairFieldFactory.
Definition at line 40 of file MyFieldCreator.cxx.
References fFieldPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRunAna::Instance().
 {
   FairRunAna *Run = FairRunAna::Instance();
   FairRuntimeDb *RunDB = Run->GetRuntimeDb();
   fFieldPar = (MyFieldPar*) RunDB->getContainer("MyFieldPar");
 }
Member Data Documentation
FairFieldFactory* FairFieldFactory::fCreator protected inherited
Definition at line 38 of file FairFieldFactory.h.
Referenced by FairFieldFactory::createFairField(), MyFieldCreator(), and FairFieldFactory::SetParm().
MyFieldPar* MyFieldCreator::fFieldPar protected
Definition at line 35 of file MyFieldCreator.h.
Referenced by createFairField(), and SetParm().
FairFieldFactory * FairFieldFactory::fgRinstance = 0 static protected inherited
Definition at line 39 of file FairFieldFactory.h.
Referenced by FairFieldFactory::FairFieldFactory(), and FairFieldFactory::Instance().
The documentation for this class was generated from the following files:
MyFieldCreator.h
MyFieldCreator.cxx