/* Generated by Together */

#include "CbmDoubleHit.h"

CbmDoubleHit::CbmDoubleHit():
  fRefIndex(-1),
  fDetectorID(-1),
  fPosition_in(),
  fPositionError_in(),
  fPosition_out(),
  fPositionError_out()
{

}

CbmDoubleHit::~CbmDoubleHit(){

}

ClassImp(CbmDoubleHit)


