/* Generated by Together */

#include "FairDoubleHit.h"

FairDoubleHit::FairDoubleHit():
  fRefIndex(-1),
  fDetectorID(-1),
  fPosition_in(),
  fPositionError_in(),
  fPosition_out(),
  fPositionError_out()
{

}

FairDoubleHit::~FairDoubleHit()
{

}

ClassImp(FairDoubleHit)


