FairRoot: FairLogger Class Reference
FairLogger Class Reference
#include <FairLogger.h>
Public Member Functions
void SetLogFileName (const char *name)
void SetLogToScreen (Bool_t log1)
void SetLogToFile (Bool_t log1)
void SetColoredLog (Bool_t log1)
void SetLogFileLevel (const char *level)
void SetLogScreenLevel (const char *level)
void SetLogVerbosityLevel (const char *vlevel)
Bool_t IsLogNeeded (FairLogLevel logLevel)
void Fatal (const char *file, const char *line, const char *func, const char *format,...)
void Error (const char *file, const char *line, const char *func, const char *format,...)
void Warning (const char *file, const char *line, const char *func, const char *format,...)
void Info (const char *file, const char *line, const char *func, const char *format,...)
void Debug (const char *file, const char *line, const char *func, const char *format,...)
void Debug1 (const char *file, const char *line, const char *func, const char *format,...)
void Debug2 (const char *file, const char *line, const char *func, const char *format,...)
void Debug3 (const char *file, const char *line, const char *func, const char *format,...)
void Debug4 (const char *file, const char *line, const char *func, const char *format,...)
FairLogger & GetOutputStream (FairLogLevel level, const char *file, const char *line, const char *func)
std::ostream & GetNullStream (FairLogLevel level)
void SetScreenStreamToCerr (bool errorStream)
template<class T >
FairLogger & operator<< (const T &t)
Stream an object to the output stream.
FairLogger & operator<< (std::ostream &(*manip)(std::ostream &))
Pass the ios_base manipulators.
Static Public Member Functions
static FairLogger * GetLogger ()
static std::ostream & endl (std::ostream &)
End of the line.
static std::ostream & flush (std::ostream &)
Flush the streams.
Private Member Functions
FairLogger ()
FairLogger (const FairLogger &)
FairLogger operator= (const FairLogger &)
~FairLogger ()
void Log (FairLogLevel level, const char *file, const char *line, const char *, const char *format, va_list arglist)
void LogFatalMessage (std::ostream &strm)
void OpenLogFile ()
void CloseLogFile ()
FairLogLevel ConvertToLogLevel (const char *level) const
FairLogVerbosityLevel ConvertToLogVerbosityLevel (const char *level) const
void GetTime ()
void SetMinLogLevel ()
const char * ConvertLogLevelToString (FairLogLevel level) const
Private Attributes
const char * fLogFileName
Bool_t fLogToScreen
Bool_t fLogToFile
Bool_t fLogColored
FairLogLevel fLogFileLevel
FairLogLevel fLogScreenLevel
FairLogVerbosityLevel fLogVerbosityLevel
Int_t fBufferSize
Int_t fBufferSizeNeeded
std::vector< char > fDynamicBuffer
char * fBufferPointer
char fTimeBuffer [fgkTimeBufferLength]
FairLogLevel fMinLogLevel
FairLogLevel fLevel
std::ostream * fScreenStream
std::ostream * fFileStream
std::ostream * fNullStream
Bool_t fLogFileOpen
Bool_t fIsNewLine
Static Private Attributes
static FairLogger * instance = NULL
static const int fgkTimeBufferLength = 80
Detailed Description
Definition at line 81 of file FairLogger.h.
Constructor & Destructor Documentation
FairLogger::FairLogger () private
Definition at line 33 of file FairLogger.cxx.
Referenced by GetLogger().
   :
   fLogFileName(""),
   fLogToScreen(kTRUE),
   fLogToFile(kFALSE),
   fLogColored(kFALSE),
   fLogFileLevel(INFO),
   fLogScreenLevel(INFO),
   fLogVerbosityLevel(verbosityLOW),
   fBufferSize(1024),
   fBufferSizeNeeded(-1),
   fDynamicBuffer(fBufferSize),
   fBufferPointer(&fDynamicBuffer[0]),
   fMinLogLevel(INFO),
   fLevel(INFO),
   fScreenStream(&std::cout),
   fFileStream(NULL),
   fNullStream(new std::ostream(0)),
   fLogFileOpen(kFALSE),
   fIsNewLine(kTRUE)
 {
 }
FairLogger::FairLogger (const FairLogger &) private
FairLogger::~FairLogger () private
Definition at line 56 of file FairLogger.cxx.
References CloseLogFile().
 {
   CloseLogFile();
 }
Member Function Documentation
void FairLogger::CloseLogFile () private
Definition at line 227 of file FairLogger.cxx.
References fFileStream.
Referenced by OpenLogFile(), SetLogFileName(), and ~FairLogger().
 {
   std::ofstream* tmp =NULL;
   if (fFileStream) {
     tmp = dynamic_cast<std::ofstream*>(fFileStream);
     if (tmp) {
       tmp->close();
     }
   }
   delete tmp;
 }
const char* FairLogger::ConvertLogLevelToString (FairLogLevel level) const inline private
Definition at line 203 of file FairLogger.h.
References LogLevelString.
     { return LogLevelString[level]; }
FairLogLevel FairLogger::ConvertToLogLevel (const char * level) const private
Definition at line 270 of file FairLogger.cxx.
References DEBUG, DEBUG1, DEBUG2, DEBUG3, DEBUG4, endl(), ERROR, FATAL, INFO, LOG, and WARNING.
Referenced by SetLogFileLevel(), and SetLogScreenLevel().
 {
   // Convert string to upper case
   // Return the according log level
   // in case the level is not known return info level
   TString level = levelc;
   level.ToUpper();
   if (level == "FATAL") { return FATAL; }
   if (level == "ERROR") { return ERROR; }
   if (level == "WARNING") { return WARNING; }
   if (level == "INFO") { return INFO; }
   if (level == "DEBUG") { return DEBUG; }
   if (level == "DEBUG1") { return DEBUG1; }
   if (level == "DEBUG2") { return DEBUG2; }
   if (level == "DEBUG3") { return DEBUG3; }
   if (level == "DEBUG4") { return DEBUG4; }
   LOG(ERROR)<<"Log level \""<<level<<"\" not supported. Use default level \"INFO\"."<<FairLogger::endl;
   return INFO;
 }
FairLogVerbosityLevel FairLogger::ConvertToLogVerbosityLevel (const char * level) const private
Definition at line 290 of file FairLogger.cxx.
References endl(), ERROR, LOG, verbosityHIGH, verbosityLOW, and verbosityMEDIUM.
Referenced by SetLogVerbosityLevel().
 {
   // Convert string to upper case
   // Return the according log verbosity level
   // in case the level is not known return low verbosity level
   TString vlevel = vlevelc;
   vlevel.ToUpper();
   if (vlevel == "HIGH") { return verbosityHIGH; }
   if (vlevel == "MEDIUM") { return verbosityMEDIUM; }
   if (vlevel == "LOW") { return verbosityLOW; }
   LOG(ERROR)<<"Verbosity level \""<<vlevel<<"\" not supported. Use default level \"LOW\"."<<FairLogger::endl;
   return verbosityLOW;
 }
void FairLogger::Debug (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 111 of file FairLogger.cxx.
References DEBUG, IsLogNeeded(), and Log().
Referenced by FairRuntimeDb::addContFactory(), FairLinkManager::AddIgnoreType(), FairLinkManager::AddIncludeType(), NewTask::Exec(), MyProjStack::FillTrackArray(), NewTask::Finish(), MyProjStack::GetParticle(), NewTask::Init(), _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments(), NewTask::NewTask(), FairRunInfo::PrintInfo(), NewTask::ReInit(), NewTask::SetParContainers(), MyProjStack::UpdateTrackIndex(), FairRuntimeDb::writeContainer(), FairRunInfo::WriteHistosToFile(), FairLinkManager::~FairLinkManager(), and NewTask::~NewTask().
 {
   if (IsLogNeeded(DEBUG)) {
     va_list ap;
     va_start(ap, format);
     Log(DEBUG, file, line, func, format, ap);
     va_end(ap);
   }
 }
void FairLogger::Debug1 (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 122 of file FairLogger.cxx.
References DEBUG1, IsLogNeeded(), and Log().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments().
 {
   if (IsLogNeeded(DEBUG1)) {
     va_list ap;
     va_start(ap, format);
     Log(DEBUG1, file, line, func, format, ap);
     va_end(ap);
   }
 }
void FairLogger::Debug2 (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 133 of file FairLogger.cxx.
References DEBUG2, IsLogNeeded(), and Log().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments().
 {
   if (IsLogNeeded(DEBUG2)) {
     va_list ap;
     va_start(ap, format);
     Log(DEBUG2, file, line, func, format, ap);
     va_end(ap);
   }
 }
void FairLogger::Debug3 (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 144 of file FairLogger.cxx.
References DEBUG3, IsLogNeeded(), and Log().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments().
 {
   if (IsLogNeeded(DEBUG3)) {
     va_list ap;
     va_start(ap, format);
     Log(DEBUG3, file, line, func, format, ap);
     va_end(ap);
   }
 }
void FairLogger::Debug4 (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 155 of file FairLogger.cxx.
References DEBUG4, IsLogNeeded(), and Log().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments().
 {
   if (IsLogNeeded(DEBUG4)) {
     va_list ap;
     va_start(ap, format);
     Log(DEBUG4, file, line, func, format, ap);
     va_end(ap);
   }
 }
std::ostream & FairLogger::endl (std::ostream & strm) static
End of the line.
Definition at line 417 of file FairLogger.cxx.
References FATAL, fFileStream, fIsNewLine, fLevel, fLogColored, fLogFileLevel, fLogScreenLevel, fLogToFile, fLogToScreen, flush(), fScreenStream, and LogFatalMessage().
Referenced by FairRootManager::ActivateBranch(), FairRootManager::ActivateBranchInInTree(), FairRootManager::AddBackgroundFile(), FairRunAna::AddBackgroundFile(), FairMCApplication::AddDecayModes(), FairLmdSource::AddFile(), FairRunAna::AddFriend(), FairFileSource::AddFriendsToChain(), FairMCApplication::AddIons(), FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), FairTestDetectorDigiWriteoutBuffer::AddNewDataToTClonesArray(), FairMCApplication::AddParticles(), FairLmdSource::AddPath(), FairModule::AddSensitiveVolume(), FairRunAna::AddSignalFile(), FairVolumeList::addVolume(), FairModule::AssignMediumAtImport(), FairAnaSelector::Begin(), FairRootManager::BGWindowWidthNo(), FairRootManager::BGWindowWidthTime(), FairRunSim::CheckFlukaExec(), FairFileSource::CheckFriendChains(), FairModule::CheckIfSensitive(), FairRootManager::CheckMaxEventNo(), FairUrqmdGenerator::CheckReturnValue(), FairMCApplication::CloneForWorker(), FairMbsStreamSource::Close(), FairAsciiGenerator::CloseInput(), FairShieldGenerator::CloseInput(), FairEvtGenGenerator::CloseInput(), FairMbsStreamSource::ConnectToServer(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTutorialDet4::ConstructGeometry(), FairModule::ConstructGeometry(), FairModule::ConstructOpGeometry(), FairModule::ConstructRootGeometry(), ConvertToLogLevel(), ConvertToLogVerbosityLevel(), FairFileSource::CreateNewFriendChain(), FairTestDetectorTimeDigiTask::Exec(), FairTestDetectorTimeRecoTask::Exec(), FairTestDetectorHitProducerSmearing::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTutorialDet2Digitizer::Exec(), FairMCTracks::Exec(), FairMCStack::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairModule::ExpandNode(), FairAsciiGenerator::FairAsciiGenerator(), FairConstField::FairConstField(), FairEvtGenGenerator::FairEvtGenGenerator(), FairFileSource::FairFileSource(), FairIonGenerator::FairIonGenerator(), FairMCApplication::FairMCApplication(), FairRunAnaProof::FairRunAnaProof(), FairRunOnline::FairRunOnline(), FairShieldGenerator::FairShieldGenerator(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4MilleWriter::FairTutorialDet4MilleWriter(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairUrqmdGenerator::FairUrqmdGenerator(), FillParContainer(), FairStack::FillTrackArray(), FairTestDetectorHitProducerSmearing::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTutorialDet4MilleWriter::Finish(), FairMCApplication::FinishRun(), FairMCApplication::FinishWorkerRun(), FairRootManager::ForceFill(), FairPrimaryGenerator::GenerateEvent(), GetBx(), GetBxyz(), GetBy(), GetBz(), FairTrackParam::GetCovariance(), FairStack::GetCurrentTrack(), FairRootManager::GetDeltaEventTime(), FairRootManager::GetEmptyTClonesArray(), FairRootManager::GetEventTime(), FairMCTrack::GetNPoints(), FairRootManager::GetObject(), FairRootManager::GetObjectFromInTree(), FairTutorialDet2DigiPar::getParams(), FairStack::GetParticle(), FairRootManager::GetSignalChainNo(), FairRootManager::GetTClonesArray(), FairVolumeList::getVolume(), FairRun::GetWriteRunInfoFile(), FairTestDetectorHitProducerSmearing::Init(), FairTestDetectorTimeDigiTask::Init(), FairTestDetectorTimeRecoTask::Init(), FairRunAnaProof::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTutorialDet4MilleWriter::Init(), FairFileSource::Init(), FairTutorialDet2Digitizer::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairAnaSelector::Init(), FairTutorialDet4HitProducerIdealMisalign::Init(), FairMCTracks::Init(), FairMCStack::Init(), FairRunSim::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairMCApplication::InitForWorker(), FairMCApplication::InitGeometry(), FairMCApplication::InitMC(), FairTutorialDet4::InitParContainers(), FairMCApplication::InitTasks(), Log(), _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments(), logToLoggerCout(), logToLoggerCoutTest(), FairTutorialDet4::ModifyGeometry(), FairTutorialDet4::ModifyGeometryByFullPath(), FairTutorialDet4::ModifyGeometryBySymlink(), FairTutorialDet4GeoHandler::NavigateTo(), FairAnaSelector::Notify(), FairParAsciiFileIo::open(), FairLmdSource::OpenNextFile(), FairRootManager::OpenOutFile(), FairRootManager::OpenSignalChain(), FairMCApplication::operator=(), FairStack::PopPrimaryForTracking(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet4Point::Print(), FairTutorialDet2Point::Print(), FairTrackParam::Print(), MyProjMCTrack::Print(), FairMCTrack::Print(), FairMCPoint::Print(), FairConstField::Print(), FairStack::Print(), FairFileSource::PrintFriendList(), FairTutorialDet2DigiPar::printparams(), FairTutorialDet1::ProcessHits(), FairTutorialDet2DigiPar::putParams(), FairGeoMedia::read(), FairRootManager::ReadBKEvent(), FairUrqmdGenerator::ReadConversionTable(), FairMbsStreamSource::ReadEvent(), FairLmdSource::ReadEvent(), FairUrqmdGenerator::ReadEvent(), FairAsciiGenerator::ReadEvent(), FairShieldGenerator::ReadEvent(), FairIonGenerator::ReadEvent(), FairEvtGenGenerator::ReadEvent(), FairRootManager::ReadEvent(), FairRootManager::ReadMixedEvent(), FairRootManager::Register(), FairRootManager::RegisterWriteoutBuffer(), FairTestDetectorHitProducerSmearing::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTutorialDet4MilleWriter::ReInit(), FairTutorialDet2Digitizer::ReInit(), FairRunAna::RunMixed(), FairRunAna::RunOnLmdFiles(), FairRunAnaProof::RunOnProof(), FairRunAna::RunWithTimeStamps(), FairRunAna::SetBackgroundFile(), FairRootManager::SetBackgroundFile(), FairRunOnline::SetContainerStatic(), FairRunAna::SetContainerStatic(), FairTrackParam::SetCovariance(), FairRootManager::SetEventTime(), FairModule::SetGeometryFileName(), FairRunAna::SetGeomFile(), FairRunSim::SetGeoModel(), SetLogFileName(), FairRunSim::SetMaterials(), FairRunSim::SetMCConfig(), FairRunAna::SetMixAllInputs(), FairMCTrack::SetNPoints(), FairTestDetectorHitProducerSmearing::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTutorialDet2Digitizer::SetParContainers(), FairTutorialDet4MilleWriter::SetParContainers(), FairTutorialDet4HitProducerIdealMisalign::SetParContainers(), FairTutorialDet4::SetParContainers(), FairRunAna::SetSignalFile(), FairRootManager::SetSignalFile(), FairRun::SetWriteRunInfoFile(), FairUrqmdGenerator::SkipEvents(), FairAnaSelector::SlaveBegin(), FairAnaSelector::SlaveTerminate(), FairMCApplication::StopRun(), FairTutorialDet4MilleWriter::StraightLineShiftX(), FairTutorialDet4MilleWriter::StraightLineShiftXY(), FairAnaSelector::Terminate(), TEST(), FairMbsSource::Unpack(), FairStack::UpdateTrackIndex(), FairRootManager::Write(), FairRootManager::~FairRootManager(), FairRun::~FairRun(), FairRunSim::~FairRunSim(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4::~FairTutorialDet4(), FairTutorialDet4MilleWriter::~FairTutorialDet4MilleWriter(), and FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter().
 {
   gLogger->fIsNewLine = kTRUE;
   if ( (gLogger->fLogToScreen && gLogger->fLevel <= gLogger->fLogScreenLevel) ) {
     if (gLogger->fLogColored) {
       *(gLogger->fScreenStream) << "\33[00;30m" << std::endl;
     } else {
       *(gLogger->fScreenStream) << std::endl;
     }
   }
   if (gLogger->fLogToFile &&
       gLogger->fLevel <= gLogger->fLogFileLevel) {
     *(gLogger->fFileStream) << std::endl;
   }
   if (gLogger->fLevel == FATAL) {
     flush(strm);
     gLogger->LogFatalMessage(strm);
   }
   return strm;
 }
void FairLogger::Error (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 78 of file FairLogger.cxx.
References ERROR, IsLogNeeded(), and Log().
Referenced by FairModule::ConstructGDMLGeometry(), FairParamList::fill(), FairParamList::fillObject(), FairParSet::init(), _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments(), and FairParSet::write().
 {
   if (IsLogNeeded(ERROR)) {
     va_list ap;
     va_start(ap, format);
     Log(ERROR, file, line, func, format, ap);
     va_end(ap);
   }
 }
void FairLogger::Fatal (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 69 of file FairLogger.cxx.
References FATAL, and Log().
Referenced by FairModule::ConstructGDMLGeometry(), MyProjStack::FillTrackArray(), FairTask::InitTask(), MyProjStack::PopPrimaryForTracking(), FairTask::ReInitTask(), FairMockVirtualMC::StopExecution(), TEST(), and MyProjStack::UpdateTrackIndex().
 {
   va_list ap;
   va_start(ap, format);
   Log(FATAL, file, line, func, format, ap);
   va_end(ap);
 }
std::ostream & FairLogger::flush (std::ostream & strm) static
Flush the streams.
Definition at line 442 of file FairLogger.cxx.
References fFileStream, fLogToFile, fLogToScreen, and fScreenStream.
Referenced by endl(), and LogFatalMessage().
 {
   if (gLogger->fLogToScreen) {
     *(gLogger->fScreenStream) << std::flush;
   }
   if (gLogger->fLogToFile) {
     *(gLogger->fFileStream) << std::flush;
   }
   return strm;
 }
FairLogger * FairLogger::GetLogger () static
Definition at line 61 of file FairLogger.cxx.
References FairLogger(), and instance.
Referenced by FairLinkManager::FairLinkManager(), _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetUp(), LogLevelTest::SetUp(), VerbosityLevelTest::SetUp(), and TEST().
 {
   if (!instance) {
     instance = new FairLogger();
   }
   return instance;
 }
std::ostream& FairLogger::GetNullStream (FairLogLevel level) inline
Definition at line 146 of file FairLogger.h.
References fLevel, and fNullStream.
{
       fLevel=level;
       return *fNullStream;
     }
FairLogger & FairLogger::GetOutputStream (FairLogLevel level, const char * file, const char * line, const char * func)
Definition at line 328 of file FairLogger.cxx.
References FATAL, fFileStream, fIsNewLine, fLevel, fLogColored, fLogFileLevel, fLogFileOpen, fLogScreenLevel, fLogToFile, fLogToScreen, fLogVerbosityLevel, fScreenStream, fTimeBuffer, GetTime(), LogLevelColor, LogLevelString, OpenLogFile(), verbosityHIGH, and verbosityMEDIUM.
Referenced by Log().
 {
   fLevel = level;
   if (level == FATAL) {
     fLogToScreen = true;
     fLogVerbosityLevel = verbosityHIGH;
     fLogColored = true;
   }
   if (fIsNewLine) {
     if ( (fLogToScreen && level <= fLogScreenLevel) ) {
       if ( fLogColored ) {
         *fScreenStream << LogLevelColor[level];
       }
       *fScreenStream << "[" << std::setw(7) << std::left << LogLevelString[level] <<"] ";
       if ( fLogVerbosityLevel == verbosityHIGH ) {
         GetTime();
         *fScreenStream << fTimeBuffer;
       }
       if ( fLogVerbosityLevel <= verbosityMEDIUM ) {
         TString bla(file);
         Ssiz_t pos = bla.Last('/');
         TString s2(bla(pos+1, bla.Length()));
         TString s3 = s2 + "::" + func + ":" + line;
         *fScreenStream << "[" << s3 <<"] ";
       }
     }
     if ( fLogToFile && level <= fLogFileLevel ) {
       if(!fLogFileOpen) {
         OpenLogFile();
       }
       *fFileStream << "[" << std::setw(7) << std::left << LogLevelString[level] <<"] ";
       if ( fLogVerbosityLevel == verbosityHIGH ) {
         GetTime();
         *fFileStream << fTimeBuffer;
       }
       if ( fLogVerbosityLevel <= verbosityMEDIUM ) {
         TString bla(file);
         Ssiz_t pos = bla.Last('/');
         TString s2(bla(pos+1, bla.Length()));
         TString s3 = s2 + "::" + func + ":" + line;
         *fFileStream << "[" << s3 <<"] ";
       }
     }
     fIsNewLine = kFALSE;
   }
   return *this;
 }
void FairLogger::GetTime () private
Definition at line 304 of file FairLogger.cxx.
References fTimeBuffer.
Referenced by GetOutputStream(), and LogFatalMessage().
 {
   time_t rawtime;
   struct tm* timeinfo;
   time(&rawtime);
   timeinfo = localtime(&rawtime);
   strftime(fTimeBuffer, 80, "[%d.%m.%Y %X] ", timeinfo);
 }
void FairLogger::Info (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 100 of file FairLogger.cxx.
References INFO, IsLogNeeded(), and Log().
Referenced by FairIon::FairIon(), _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments(), logToLoggerPrintf(), FairTrackPar::Print(), FairDetector::SaveGeoParams(), and FairRuntimeDb::writeContainer().
 {
   if (IsLogNeeded(INFO)) {
     va_list ap;
     va_start(ap, format);
     Log(INFO, file, line, func, format, ap);
     va_end(ap);
   }
 }
Bool_t FairLogger::IsLogNeeded (FairLogLevel logLevel)
Definition at line 319 of file FairLogger.cxx.
References fMinLogLevel.
Referenced by Debug(), Debug1(), Debug2(), Debug3(), Debug4(), Error(), Info(), FairStack::Print(), and Warning().
 {
   if (logLevel <= fMinLogLevel) {
     return true;
   } else {
     return false;
   }
 }
void FairLogger::Log (FairLogLevel level, const char * file, const char * line, const char * func, const char * format, va_list arglist) private
Definition at line 166 of file FairLogger.cxx.
References endl(), fBufferPointer, fBufferSize, fBufferSizeNeeded, fDynamicBuffer, fLevel, fLogFileOpen, fLogToFile, GetOutputStream(), and OpenLogFile().
Referenced by Debug(), Debug1(), Debug2(), Debug3(), Debug4(), Error(), Fatal(), Info(), and Warning().
 {
   // If the format string together with the argument list was used once it can't
   // be used another time. Don't know why but if we do so the arguments are not
   // correct any longer and the program may crash (On Mac OSX). Even if it does
   // not crash it does not work as expected.
   // To vercome the problem the output is written to a buffer which then can be
   // used several times.
   if(fLogToFile && !fLogFileOpen) {
     OpenLogFile();
   }
   fLevel = level;
   while (1) {
     fBufferSizeNeeded = vsnprintf(fBufferPointer, fBufferSize, format, arglist);
     // Try to vsnprintf into our buffer.
     //    int needed = vsnprintf (buf, size, fmt, ap);
     // NB. C99 (which modern Linux and OS X follow) says vsnprintf
     // failure returns the length it would have needed.  But older
     // glibc and current Windows return -1 for failure, i.e., not
     // telling us how much was needed.
     if (fBufferSizeNeeded <= (int)fBufferSize && fBufferSizeNeeded >= 0) {
       // It fit fine so we're done.
       GetOutputStream(level, file, line, func) <<
           std::string(fBufferPointer, (size_t) fBufferSizeNeeded)<<
           " " << FairLogger::endl;
       break;
     }
     // vsnprintf reported that it wanted to write more characters
     // than we allotted.  So try again using a dynamic buffer.  This
     // doesn't happen very often if we chose our initial size well.
     fBufferSize = (fBufferSizeNeeded > 0)
                   ? (fBufferSizeNeeded+1) : (fBufferSize*2);
     fDynamicBuffer.resize (fBufferSize);
   }
 }
void FairLogger::LogFatalMessage (std::ostream & strm) private
Definition at line 453 of file FairLogger.cxx.
References FATAL, fFileStream, fLogToFile, flush(), fScreenStream, fTimeBuffer, GetTime(), LogLevelColor, and LogLevelString.
Referenced by endl().
 {
   // Since Fatal indicates a fatal error it is maybe usefull to have
   // system information from the incident. Since the output on the screen
   // does not help the noraml user, the stderr is redirected into a special
   // core dump file for later usage.
   // Fatal also indicates a problem which is so severe that the process should
   // not go on, so the process is aborted.
   *fScreenStream << LogLevelColor[FATAL];
   *fScreenStream << "[" << std::setw(7) << std::left << LogLevelString[FATAL] <<"] ";
   GetTime();
   *fScreenStream << fTimeBuffer;
   *fScreenStream <<  "We stop the execution of the process at this point.\n";
   if ( fLogToFile ) {
     *fFileStream << "[" << std::setw(7) << std::left << LogLevelString[FATAL] <<"] ";
     *fFileStream << fTimeBuffer;
     *fFileStream <<  "We stop the execution of the process at this point.\n";
   }
   if (gSystem) {
     TString corefile = "core_dump_";
     Int_t PID = gSystem->GetPid();
     corefile += PID;
     *fScreenStream << LogLevelColor[FATAL];
     *fScreenStream << "[" << std::setw(7) << std::left << LogLevelString[FATAL] <<"] ";
     GetTime();
     *fScreenStream << fTimeBuffer;
     *fScreenStream << "For later analysis we write a core dump to " <<
                    corefile << " \n";
     if ( fLogToFile ) {
       *fFileStream << "[" << std::setw(7) << std::left << LogLevelString[FATAL] <<"] ";
       *fFileStream << fTimeBuffer;
       *fFileStream << "For later analysis we write a core dump to" <<
                    corefile << "\n";
     }
     *(gLogger->fScreenStream) << "\33[00;30m" << std::endl;
     flush(strm);
     freopen(corefile, "w", stderr);
     gSystem->StackTrace();
     fclose(stderr);
     gSystem->Abort(1);
   } else {
     abort();
   }
 }
void FairLogger::OpenLogFile () private
Definition at line 239 of file FairLogger.cxx.
References CloseLogFile(), fFileStream, fLogFileName, and fLogFileOpen.
Referenced by GetOutputStream(), Log(), and SetLogFileName().
 {
   // Check if the log file name is set. If not use a default logfile with
   // the name FairLogfile_<pid>.log. <pid> is the pid of the runing job.
   TString logfile = fLogFileName;
   if (logfile.IsNull()) {
     Int_t PID = gSystem->GetPid();
     logfile = "FairLogfile_";
     logfile += PID;
     logfile += ".log";
   }
   // Check if filename contains a full path. If not create logfile
   // in the current directory.
   // TODO(F.U.): Check if the path exists and is writeable.
   if (!logfile.Contains('/')) {
     logfile = "./" + logfile;
   }
   if (fFileStream) {
     CloseLogFile();
     delete fFileStream;
     fFileStream = NULL;
   }
   fFileStream = new std::ofstream(logfile.Data());
   fLogFileOpen = kTRUE;
 }
template<class T > FairLogger& FairLogger::operator<< (const T & t) inline
Stream an object to the output stream.
Definition at line 155 of file FairLogger.h.
References fFileStream, fLevel, fLogFileLevel, fLogScreenLevel, fLogToFile, fLogToScreen, and fScreenStream.
{
       if (fLogToScreen && fLevel <= fLogScreenLevel) {
         *(fScreenStream) << t;
       }
       if (fLogToFile && fLevel <= fLogFileLevel) {
         *(fFileStream) << t;
       }
       return *this;
     }
FairLogger & FairLogger::operator<< (std::ostream &(*)(std::ostream &) manip)
Pass the ios_base manipulators.
Definition at line 404 of file FairLogger.cxx.
References fFileStream, fLevel, fLogFileLevel, fLogScreenLevel, fLogToFile, fLogToScreen, and fScreenStream.
 {
   if (fLogToScreen && (fLevel <= fLogScreenLevel || fLevel <= fLogFileLevel) ) {
     *(fScreenStream) << manip;
   }
   if (fLogToFile && !fLogToScreen && (fLevel <= fLogScreenLevel || fLevel <= fLogFileLevel) ) {
     *(fFileStream) << manip;
   }
   return *this;
 }
FairLogger FairLogger::operator= (const FairLogger &) private
void FairLogger::SetColoredLog (Bool_t log1) inline
Definition at line 102 of file FairLogger.h.
References fLogColored.
 { fLogColored = log1; }
void FairLogger::SetLogFileLevel (const char * level) inline
Definition at line 104 of file FairLogger.h.
References ConvertToLogLevel(), fLogFileLevel, and SetMinLogLevel().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues(), SetLogToFile(), and TEST_P().
{
       fLogFileLevel = ConvertToLogLevel(level);
       SetMinLogLevel();
     }
void FairLogger::SetLogFileName (const char * name)
Definition at line 210 of file FairLogger.cxx.
References CloseLogFile(), endl(), ERROR, fFileStream, fLogFileName, LOG, and OpenLogFile().
Referenced by TEST_F(), and TEST_P().
 {
   if (fFileStream) {
     CloseLogFile();
     delete fFileStream;
     fFileStream = NULL;
     if( remove(fLogFileName) != 0 ) {
       LOG(ERROR)<<"Could not delete log file "<< fLogFileName << "." << FairLogger::endl;
     }
   }
   fLogFileName = name;
   OpenLogFile();
 }
void FairLogger::SetLogScreenLevel (const char * level) inline
Definition at line 109 of file FairLogger.h.
References ConvertToLogLevel(), fLogScreenLevel, and SetMinLogLevel().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues(), SetLogToScreen(), TEST(), TEST_F(), and TEST_P().
{
       fLogScreenLevel = ConvertToLogLevel(level);
       SetMinLogLevel();
     }
void FairLogger::SetLogToFile (Bool_t log1) inline
Definition at line 95 of file FairLogger.h.
References fLogToFile, and SetLogFileLevel().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues(), TEST_F(), and TEST_P().
{
       fLogToFile = log1;
       if (!fLogToFile) {
         SetLogFileLevel("FATAL");
       }
     }
void FairLogger::SetLogToScreen (Bool_t log1) inline
Definition at line 88 of file FairLogger.h.
References fLogToScreen, and SetLogScreenLevel().
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues(), TEST_F(), and TEST_P().
{
       fLogToScreen = log1;
       if (!fLogToScreen) {
         SetLogScreenLevel("FATAL");
       }
     }
void FairLogger::SetLogVerbosityLevel (const char * vlevel) inline
Definition at line 114 of file FairLogger.h.
References ConvertToLogVerbosityLevel(), and fLogVerbosityLevel.
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues(), TEST_F(), and TEST_P().
{
       fLogVerbosityLevel = ConvertToLogVerbosityLevel(vlevel);
     }
void FairLogger::SetMinLogLevel () private
Definition at line 314 of file FairLogger.cxx.
References fLogFileLevel, fLogScreenLevel, and fMinLogLevel.
Referenced by SetLogFileLevel(), and SetLogScreenLevel().
 {
   fMinLogLevel = (fLogScreenLevel <= fLogFileLevel) ? fLogFileLevel : fLogScreenLevel;
 }
void FairLogger::SetScreenStreamToCerr (bool errorStream)
Definition at line 520 of file FairLogger.cxx.
References fScreenStream.
Referenced by _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues(), and TEST().
 {
   if(errorStream) {
     fScreenStream = &std::cerr;
   } else {
     fScreenStream = &std::cout;
   }
 }
void FairLogger::Warning (const char * file, const char * line, const char * func, const char * format, ...)
Definition at line 89 of file FairLogger.cxx.
References IsLogNeeded(), Log(), and WARNING.
Referenced by FairParamList::fillObject(), MyProjStack::GetCurrentTrack(), and _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments().
 {
   if (IsLogNeeded(WARNING)) {
     va_list ap;
     va_start(ap, format);
     Log(WARNING, file, line, func, format, ap);
     va_end(ap);
   }
 }
Member Data Documentation
char* FairLogger::fBufferPointer private
Definition at line 216 of file FairLogger.h.
Referenced by Log().
Int_t FairLogger::fBufferSize private
Definition at line 213 of file FairLogger.h.
Referenced by Log().
Int_t FairLogger::fBufferSizeNeeded private
Definition at line 214 of file FairLogger.h.
Referenced by Log().
std::vector<char> FairLogger::fDynamicBuffer private
Definition at line 215 of file FairLogger.h.
Referenced by Log().
std::ostream* FairLogger::fFileStream private
Definition at line 223 of file FairLogger.h.
Referenced by CloseLogFile(), endl(), flush(), GetOutputStream(), LogFatalMessage(), OpenLogFile(), operator<<(), and SetLogFileName().
const int FairLogger::fgkTimeBufferLength = 80 static private
Definition at line 218 of file FairLogger.h.
Bool_t FairLogger::fIsNewLine private
Definition at line 226 of file FairLogger.h.
Referenced by endl(), and GetOutputStream().
FairLogLevel FairLogger::fLevel private
Definition at line 221 of file FairLogger.h.
Referenced by endl(), GetNullStream(), GetOutputStream(), Log(), and operator<<().
Bool_t FairLogger::fLogColored private
Definition at line 209 of file FairLogger.h.
Referenced by endl(), GetOutputStream(), and SetColoredLog().
FairLogLevel FairLogger::fLogFileLevel private
Definition at line 210 of file FairLogger.h.
Referenced by endl(), GetOutputStream(), operator<<(), SetLogFileLevel(), and SetMinLogLevel().
const char* FairLogger::fLogFileName private
Definition at line 206 of file FairLogger.h.
Referenced by OpenLogFile(), and SetLogFileName().
Bool_t FairLogger::fLogFileOpen private
Definition at line 225 of file FairLogger.h.
Referenced by GetOutputStream(), Log(), and OpenLogFile().
FairLogLevel FairLogger::fLogScreenLevel private
Definition at line 211 of file FairLogger.h.
Referenced by endl(), GetOutputStream(), operator<<(), SetLogScreenLevel(), and SetMinLogLevel().
Bool_t FairLogger::fLogToFile private
Definition at line 208 of file FairLogger.h.
Referenced by endl(), flush(), GetOutputStream(), Log(), LogFatalMessage(), operator<<(), and SetLogToFile().
Bool_t FairLogger::fLogToScreen private
Definition at line 207 of file FairLogger.h.
Referenced by endl(), flush(), GetOutputStream(), operator<<(), and SetLogToScreen().
FairLogVerbosityLevel FairLogger::fLogVerbosityLevel private
Definition at line 212 of file FairLogger.h.
Referenced by GetOutputStream(), and SetLogVerbosityLevel().
FairLogLevel FairLogger::fMinLogLevel private
Definition at line 220 of file FairLogger.h.
Referenced by IsLogNeeded(), and SetMinLogLevel().
std::ostream* FairLogger::fNullStream private
Definition at line 224 of file FairLogger.h.
Referenced by GetNullStream().
std::ostream* FairLogger::fScreenStream private
Definition at line 222 of file FairLogger.h.
Referenced by endl(), flush(), GetOutputStream(), LogFatalMessage(), operator<<(), and SetScreenStreamToCerr().
char FairLogger::fTimeBuffer[fgkTimeBufferLength] private
Definition at line 219 of file FairLogger.h.
Referenced by GetOutputStream(), GetTime(), and LogFatalMessage().
FairLogger * FairLogger::instance = NULL static private
Definition at line 181 of file FairLogger.h.
Referenced by GetLogger().
The documentation for this class was generated from the following files:
FairLogger.h
FairLogger.cxx