FairRoot: FairTSBufferFunctional Class Reference
FairTSBufferFunctional Class Reference
A class to access time ordered data in a root branch.
#include <FairTSBufferFunctional.h>
Public Member Functions
FairTSBufferFunctional (TString branchName, TTree *sourceTree, BinaryFunctor *stopFunction, BinaryFunctor *startFunction=0)
virtual ~FairTSBufferFunctional ()
TClonesArray * GetData (Double_t stopParameter)
TClonesArray * GetData (Double_t startParameter, Double_t stopParameter)
Int_t GetBranchIndex ()
void SetStartFunction (BinaryFunctor *function)
void SetStopFunction (BinaryFunctor *function)
Bool_t AllDataProcessed ()
Bool_t TimeOut ()
Int_t FindStartIndex (Double_t startParameter)
Private Member Functions
void ReadInNextFilledEntry ()
Int_t ReadInPreviousFilledEntry (Int_t startEntry)
void ReadInNextEntry ()
void ReadInEntry (Int_t number)
void AbsorbDataBufferArray ()
FairTSBufferFunctional (const FairTSBufferFunctional &)
FairTSBufferFunctional & operator= (const FairTSBufferFunctional &)
ClassDef (FairTSBufferFunctional, 0)
Private Attributes
TClonesArray * fOutputArray
TClonesArray * fBufferArray
TClonesArray * fInputArray
BinaryFunctor * fStartFunction
BinaryFunctor * fStopFunction
TBranch * fBranch
Int_t fBranchIndex
Int_t fStartIndex
Int_t fVerbose
Detailed Description
A class to access time ordered data in a root branch.
In the constructor of the class one has to give the branch name of the data, the tree the data is stored in and a BinaryFunctor which contains the method how the data should be extracted. Several example functors already exists. To extract the data one has to call GetData with a parameter which fits to the selected functor. GetData returns a TClonesArray which contains the data.
Be careful! The buffer runs through the time ordered data in one time direction only. This means that you cannot request data which is older than the data you have requested before.
Addition: This is not true anymore. GetData(Double_t, Double_t) is able to get also data which is older but this only works if you request a fixed time via StopTime functor. For other functors the behavior is unpredictable.
Created on: Feb 18, 201 Author: stockman
Definition at line 153 of file FairTSBufferFunctional.h.
Constructor & Destructor Documentation
FairTSBufferFunctional::FairTSBufferFunctional (TString branchName, TTree * sourceTree, BinaryFunctor * stopFunction, BinaryFunctor * startFunction = 0)
Definition at line 24 of file FairTSBufferFunctional.cxx.
References fBranch, fBufferArray, fInputArray, fOutputArray, FairRootManager::GetObject(), and FairRootManager::Instance().
   :TObject(),
    fOutputArray(NULL),
    fBufferArray(NULL),
    fInputArray(NULL),
    fStartFunction(startFunction),
    fStopFunction (stopFunction),
    fBranch(NULL),
    fBranchIndex(-1),
    fStartIndex(-1),
    fVerbose(0)
 {
   fBranch = sourceTree->GetBranch(branchName.Data());
   if (fBranch == 0) {
     std::cout << "-E- FairTSBufferFunctional::FairTSBufferFunctional Branch " << branchName << " does not exist!" << std::endl;
   }
   FairRootManager* ioman = FairRootManager::Instance();
   fInputArray = (TClonesArray*)ioman->GetObject(branchName.Data());
   fBufferArray = new TClonesArray(fInputArray->GetClass()->GetName());
   fOutputArray = new TClonesArray(fInputArray->GetClass()->GetName());
 }
virtual FairTSBufferFunctional::~FairTSBufferFunctional () inline virtual
Definition at line 159 of file FairTSBufferFunctional.h.
 {};
FairTSBufferFunctional::FairTSBufferFunctional (const FairTSBufferFunctional &) private
Member Function Documentation
void FairTSBufferFunctional::AbsorbDataBufferArray () private
Definition at line 233 of file FairTSBufferFunctional.cxx.
References fBufferArray, fInputArray, and fVerbose.
Referenced by GetData().
 {
   if (fInputArray->GetEntriesFast() > 0) {
     if (fVerbose > 1) {
       std::cout << "-I- FairTSBufferFunctional::ReadInNextFilledEntry: Absorb InputArray into Buffer" << std::endl;
     }
     fBufferArray->AbsorbObjects(fInputArray, 0, fInputArray->GetEntries() - 1);
   }
 }
Bool_t FairTSBufferFunctional::AllDataProcessed ()
Definition at line 267 of file FairTSBufferFunctional.cxx.
References fBranch, fBranchIndex, fBufferArray, and fOutputArray.
 {
   if (fBranchIndex + 1 >= fBranch->GetEntries()) {
     if(fBufferArray->GetEntriesFast() == 0) {
       if (fOutputArray->GetEntriesFast() == 0) {
         return kTRUE;
       } else { return kFALSE; }
     } else { return kFALSE; }
   } else { return kFALSE; }
 }
FairTSBufferFunctional::ClassDef (FairTSBufferFunctional , 0) private
Int_t FairTSBufferFunctional::FindStartIndex (Double_t startParameter)
Definition at line 145 of file FairTSBufferFunctional.cxx.
References fBranchIndex, fInputArray, fStartFunction, ReadInEntry(), ReadInNextFilledEntry(), and ReadInPreviousFilledEntry().
Referenced by GetData().
 {
   FairTimeStamp* dataPoint;
   Int_t tempIndex = fBranchIndex;
   Bool_t runBackwards = kTRUE;
   Int_t previousIndex = -1;
   Int_t previousBranchIndex = -1;
   ReadInEntry(tempIndex); //< Get Data out of Tree
   while (fInputArray->GetEntries() == 0 && tempIndex > 0) { //< If the entry of the tree was empty read in previous entries until you find one which is filled
     tempIndex--;
     ReadInEntry(tempIndex);
   }
   if (fInputArray->GetEntries() == 0) {         //If the previous entries in the tree are also empty run in the forward direction
     ReadInNextFilledEntry();
     runBackwards = kFALSE;
   }
   if (fInputArray->GetEntries() == 0) {         //If there is still no data the branch is empty!
     std::cout << "-I- FairTSBufferFunctional::FindStartIndex: All entries are empty!" << std::endl;
     return -1;
   }
   fBranchIndex = tempIndex;
   //Now we have data or FindStartIndex already returned -1
   dataPoint = (FairTimeStamp*)fInputArray->Last();
   //std::cout << "DataPoint: " << *dataPoint << std::endl;
   while(!(*fStartFunction)(dataPoint, startParameter)) {
     //std::cout << "DataPoint Search Entry: " << fBranchIndex << ": " << *dataPoint << std::endl;
     ReadInNextFilledEntry();
     if (fInputArray->GetEntries() != 0) {
       dataPoint = (FairTimeStamp*)fInputArray->Last();
     } else {
       return -1;
     }
   }
   //Now you have data where the last element in the array does not fit to your request
   Int_t startPos = fInputArray->GetEntries() - 1;
   while ((*fStartFunction)(dataPoint, startParameter)) {
     //std::cout << "DataPoint Search in Entry: " << fBranchIndex << ": " << *dataPoint << std::endl;
     previousIndex = startPos;
     previousBranchIndex = fBranchIndex;
     startPos--;
     if (startPos == -1) {
       fBranchIndex = ReadInPreviousFilledEntry(fBranchIndex);
       startPos = fInputArray->GetEntries() - 1;
       if (startPos < 0) {
         if (fBranchIndex == 0) {
           return 0;
         }
         return -1;
       }
     }
     dataPoint = (FairTimeStamp*)fInputArray->At(startPos);
   }
   fBranchIndex = previousBranchIndex;
   return previousIndex;
 }
Int_t FairTSBufferFunctional::GetBranchIndex () inline
Definition at line 162 of file FairTSBufferFunctional.h.
References fBranchIndex.
Referenced by GetData().
 {return fBranchIndex;}
TClonesArray * FairTSBufferFunctional::GetData (Double_t stopParameter)
Definition at line 47 of file FairTSBufferFunctional.cxx.
References AbsorbDataBufferArray(), fBranch, fBranchIndex, fBufferArray, fInputArray, fOutputArray, fStopFunction, fVerbose, FairTimeStamp::GetTimeStamp(), ReadInNextEntry(), and ReadInNextFilledEntry().
Referenced by GetData().
 {
   Double_t actualTime = 0.;
   int posBuffer = 0;
   if (fStopFunction == 0) {                 //no function is given ==> read in data in traditional way event by event
     ReadInNextEntry();
     fOutputArray->AbsorbObjects((TClonesArray*)fInputArray, 0, fInputArray->GetEntriesFast() - 1);
     return fOutputArray;
   }
   if (fVerbose > 1) {
     std::cout << "-I- FairTSBufferFunctional::GetData for stopParameter: " << stopParameter << std::endl;
   }
   //if the BufferArray is empty fill it
   if (fBufferArray->GetEntriesFast() == 0) {
     if (fVerbose > 1) {
       std::cout << "-I- FairTSBufferFunctional::GetData fBufferArray is empty: Read in Data" << std::endl;
     }
     ReadInNextFilledEntry();
     AbsorbDataBufferArray();
   }
   //if the BufferArray is still empty you have reached the end of your data set
   if (fVerbose > 1) {
     std::cout << "-I- FairTSBufferFunctional::GetData fBufferArray->GetEntriesFast(): " << fBufferArray->GetEntriesFast() << std::endl;
   }
   FairTimeStamp* dataPoint = (FairTimeStamp*)fBufferArray->Last();
   if (dataPoint == 0) {
     if (fVerbose > 0) {
       std::cout << "-I- FairTSBufferFunctional::GetData dataPoint is empty ==> All Data read in" << std::endl;
     }
     return fOutputArray;
   }
   dataPoint = (FairTimeStamp*)fBufferArray->First();
   while (!(*fStopFunction)(dataPoint, stopParameter)) {     //check if you have reached end of requested data
     posBuffer++;
     //if you have reached the end of the BufferArray fill it with new data from tree
     if (posBuffer == fBufferArray->GetEntriesFast()) {
       ReadInNextFilledEntry();
       AbsorbDataBufferArray();
     }
     //if you are still at the end of the BufferArray than break (no new data in tree)
     if (posBuffer == fBufferArray->GetEntriesFast()) {
       break;
     }
     dataPoint = (FairTimeStamp*)fBufferArray->At(posBuffer);
     if (fVerbose > 1) {
       std::cout << posBuffer << " TimeStampData: " << dataPoint->GetTimeStamp() << std::endl;
     }
   }
   if (fVerbose > 1) {
     std::cout << "-I- FairTSBufferFunctional::GetData Index for Absorb: " << posBuffer << " BufferArray size: " << fBufferArray->GetEntriesFast() << std::endl;
   }
   if (posBuffer < fBufferArray->GetEntriesFast() && posBuffer > 0) {
     if (fVerbose > 1) {
       std::cout << "-I- FairTSBufferFunctional::GetData absorb BufferArray up to posBuffer " << posBuffer << " into fOutputArray" << std::endl;
     }
     fOutputArray->AbsorbObjects(fBufferArray, 0, posBuffer - 1);
     posBuffer = 0;
     return fOutputArray;
   }
   if (fVerbose > 1) {
     std::cout << "Index: " << posBuffer << " BranchIndex: " << fBranchIndex << " NBranch " << fBranch->GetEntries() << std::endl;
   }
   if (posBuffer >= fBufferArray->GetEntriesFast() && posBuffer != 0 && fBranchIndex + 1 >= fBranch->GetEntries()) {
     if (fVerbose > 1) {
       std::cout << "-I- FairTSBufferFunctional::GetData end of data reached. Send the rest to the OutputArray!" << std::endl;
     }
     fOutputArray->AbsorbObjects(fBufferArray, 0, fBufferArray->GetEntries() - 1);
   }
   if (fVerbose > 1) {
     std::cout << "-I- FairTSBufferFunctional::GetData: Read in up to entry: " << fBranchIndex << " with actualTime " << actualTime << " and requested stopParameter " << stopParameter << std::endl;
   }
   return fOutputArray;
 }
TClonesArray * FairTSBufferFunctional::GetData (Double_t startParameter, Double_t stopParameter)
Definition at line 131 of file FairTSBufferFunctional.cxx.
References fBranchIndex, fBufferArray, FindStartIndex(), fInputArray, fStartFunction, GetBranchIndex(), GetData(), and ReadInEntry().
 {
   if (fStartFunction != 0) {
     fBufferArray->Clear();
     Int_t startIndex = FindStartIndex(startParameter);
     std::cout << "StartIndex: " << startIndex << "/" << GetBranchIndex() << std::endl;
     if (startIndex > -1) {
       ReadInEntry(fBranchIndex);
       fBufferArray->AbsorbObjects(fInputArray, startIndex, fInputArray->GetEntries() -1);
     }
   }
   return GetData(stopParameter);
 }
FairTSBufferFunctional& FairTSBufferFunctional::operator= (const FairTSBufferFunctional &) private
void FairTSBufferFunctional::ReadInEntry (Int_t number) private
Definition at line 251 of file FairTSBufferFunctional.cxx.
References fBranch, fInputArray, fVerbose, and FairRootManager::Instance().
Referenced by FindStartIndex(), GetData(), ReadInNextEntry(), ReadInNextFilledEntry(), and ReadInPreviousFilledEntry().
 {
   fInputArray->Delete();
   if (number < fBranch->GetEntries()) {
     fBranch->GetEntry(number);
     for (int i = 0; i < fInputArray->GetEntriesFast(); i++) {
       ((FairTimeStamp*) fInputArray->At(i))->SetEntryNr(FairLink(0, number, FairRootManager::Instance()->GetBranchId(fBranch->GetName()), i, 1));
     }
     if (fVerbose > 1)
       std::cout
           << "-I- FairTSBufferFunctional::ReadInEntry BranchIndex: "
           << number << " Entries: "
           << fInputArray->GetEntriesFast() << std::endl;
   }
 }
void FairTSBufferFunctional::ReadInNextEntry () private
Definition at line 243 of file FairTSBufferFunctional.cxx.
References fBranch, fBranchIndex, and ReadInEntry().
Referenced by GetData().
 {
   if (fBranchIndex + 1 < fBranch->GetEntries()) {
     fBranchIndex++;
     ReadInEntry(fBranchIndex);
   }
 }
void FairTSBufferFunctional::ReadInNextFilledEntry () private
Definition at line 208 of file FairTSBufferFunctional.cxx.
References fBranch, fBranchIndex, fInputArray, fVerbose, and ReadInEntry().
Referenced by FindStartIndex(), and GetData().
 {
   fInputArray->Delete();
   if (fVerbose > 1) {
     std::cout << "-I- FairTSBufferFunctional::ReadInNextFilledEntry: Entries in InputArray " << fInputArray->GetEntriesFast() << " Branch Entries: " << fBranch->GetEntries() << std::endl;
   }
   while (fInputArray->GetEntriesFast() == 0 && fBranchIndex + 1 < fBranch->GetEntries()) {
     fBranchIndex++;
     ReadInEntry(fBranchIndex);
   }
 }
Int_t FairTSBufferFunctional::ReadInPreviousFilledEntry (Int_t startEntry) private
Definition at line 221 of file FairTSBufferFunctional.cxx.
References fInputArray, and ReadInEntry().
Referenced by FindStartIndex().
 {
   Int_t tempIndex = startEntry;
   fInputArray->Delete();
   while (fInputArray->GetEntriesFast() == 0 && tempIndex > 0) {
     tempIndex--;
     ReadInEntry(tempIndex);
   }
   return tempIndex;
 }
void FairTSBufferFunctional::SetStartFunction (BinaryFunctor * function) inline
Definition at line 163 of file FairTSBufferFunctional.h.
References fStartFunction.
 {fStartFunction=function;}
void FairTSBufferFunctional::SetStopFunction (BinaryFunctor * function) inline
Definition at line 164 of file FairTSBufferFunctional.h.
References fStopFunction.
 {fStopFunction = function;}
Bool_t FairTSBufferFunctional::TimeOut () inline
Definition at line 167 of file FairTSBufferFunctional.h.
References fStartFunction, fStopFunction, and BinaryFunctor::TimeOut().
                      {
       Bool_t stopTimeOut = fStopFunction->TimeOut();
       Bool_t startTimeOut = kTRUE;
       if (fStartFunction != 0) {
         startTimeOut = fStartFunction->TimeOut();
 //        if (startTimeOut == kTRUE && stopTimeOut == kFALSE){
 //          fStartFunction->ResetTimeOut();
 //        }
 //        else if (startTimeOut == kFALSE && stopTimeOut == kTRUE){
 //          fStopFunction->ResetTimeOut();
 //        }
       }
       return (stopTimeOut && startTimeOut);
     }
Member Data Documentation
TBranch* FairTSBufferFunctional::fBranch private
Definition at line 199 of file FairTSBufferFunctional.h.
Referenced by AllDataProcessed(), FairTSBufferFunctional(), GetData(), ReadInEntry(), ReadInNextEntry(), and ReadInNextFilledEntry().
Int_t FairTSBufferFunctional::fBranchIndex private
Definition at line 200 of file FairTSBufferFunctional.h.
Referenced by AllDataProcessed(), FindStartIndex(), GetBranchIndex(), GetData(), ReadInNextEntry(), and ReadInNextFilledEntry().
TClonesArray* FairTSBufferFunctional::fBufferArray private
Definition at line 193 of file FairTSBufferFunctional.h.
Referenced by AbsorbDataBufferArray(), AllDataProcessed(), FairTSBufferFunctional(), and GetData().
TClonesArray* FairTSBufferFunctional::fInputArray private
Definition at line 194 of file FairTSBufferFunctional.h.
Referenced by AbsorbDataBufferArray(), FairTSBufferFunctional(), FindStartIndex(), GetData(), ReadInEntry(), ReadInNextFilledEntry(), and ReadInPreviousFilledEntry().
TClonesArray* FairTSBufferFunctional::fOutputArray private
Definition at line 192 of file FairTSBufferFunctional.h.
Referenced by AllDataProcessed(), FairTSBufferFunctional(), and GetData().
BinaryFunctor* FairTSBufferFunctional::fStartFunction private
Definition at line 196 of file FairTSBufferFunctional.h.
Referenced by FindStartIndex(), GetData(), SetStartFunction(), and TimeOut().
Int_t FairTSBufferFunctional::fStartIndex private
Definition at line 201 of file FairTSBufferFunctional.h.
BinaryFunctor* FairTSBufferFunctional::fStopFunction private
Definition at line 197 of file FairTSBufferFunctional.h.
Referenced by GetData(), SetStopFunction(), and TimeOut().
Int_t FairTSBufferFunctional::fVerbose private
Definition at line 203 of file FairTSBufferFunctional.h.
Referenced by AbsorbDataBufferArray(), GetData(), ReadInEntry(), and ReadInNextFilledEntry().
The documentation for this class was generated from the following files:
FairTSBufferFunctional.h
FairTSBufferFunctional.cxx