FairRroot: FairTutorialDet2Digitizer Class Reference
FairTutorialDet2Digitizer Class Reference
#include <FairTutorialDet2Digitizer.h>
Public Member Functions
FairTutorialDet2Digitizer ()
FairTutorialDet2Digitizer (const char *name, const char *title="FAIR Task")
virtual ~FairTutorialDet2Digitizer ()
virtual InitStatus ReInit ()
virtual InitStatus Init ()
virtual void SetParContainers ()
virtual void Exec (Option_t *option)
virtual void Finish ()
void Register ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairTutorialDet2Digitizer (const FairTutorialDet2Digitizer &)
FairTutorialDet2Digitizer & operator= (const FairTutorialDet2Digitizer &)
Private Attributes
TClonesArray * fTutorialDetPoints
FairTutorialDet2DigiPar * fDigiPar
Tutorial Det MC points.
Detailed Description
Definition at line 27 of file FairTutorialDet2Digitizer.h.
Constructor & Destructor Documentation
FairTutorialDet2Digitizer::FairTutorialDet2Digitizer ()
Default constructor
Definition at line 36 of file FairTutorialDet2Digitizer.cxx.
   : FairTask("TutorialDetDigitizer", 0),
     fTutorialDetPoints(NULL),
     fDigiPar(NULL)
 {
 }
FairTutorialDet2Digitizer::FairTutorialDet2Digitizer (const char * name, const char * title = "FAIR Task")
Standard constructor
Definition at line 45 of file FairTutorialDet2Digitizer.cxx.
   : FairTask(name, 0),
     fTutorialDetPoints(NULL),
     fDigiPar(NULL)
 {
 }
FairTutorialDet2Digitizer::~FairTutorialDet2Digitizer () virtual
Destructor
Definition at line 54 of file FairTutorialDet2Digitizer.cxx.
 {
   //    FairRootManager *ioman =FairRootManager::Instance();
   //ioman->Write();
   //fDigiCollection->Clear("C");
   //delete fDigiCollection;
 }
FairTutorialDet2Digitizer::FairTutorialDet2Digitizer (const FairTutorialDet2Digitizer &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
void FairTutorialDet2Digitizer::Exec (Option_t * option) virtual
Executed task
Definition at line 131 of file FairTutorialDet2Digitizer.cxx.
 {
   // Here we print something
   cout <<" I am in FairTutorialDet2Digitizer::Exec" << endl;
   /*
   fNHits = 0;
   FairTutorialDet2Point *pt=NULL;
   Int_t nentries = fTutorialDetPoints->GetEntriesFast();
   Double_t ELoss;       // total energy loss
   for (int j=0; j < nentries; j++ ) {
     pt = (FairTutorialDet2Point*) fTutorialDetPoints->At(j);
     if(NULL == pt) continue;
   //        Double_t x_mean = (pt->GetXIn()+pt->GetXOut())/2.;
   //        Double_t y_mean = (pt->GetYIn()+pt->GetYOut())/2.;
   //        Double_t z_mean = (pt->GetZIn()+pt->GetZOut())/2.;
         Double_t x_mean = pt->GetXOut();
         Double_t y_mean = pt->GetYOut();
         Double_t z_mean = pt->GetZOut();
         gGeoManager->FindNode(x_mean, y_mean, z_mean);
         TString path = gGeoManager->GetPath();
         Int_t ID =  gGeoManager->GetCurrentNodeId();
         TGeoNode *curnode = gGeoManager->GetCurrentNode();
         TGeoVolume *curvol = gGeoManager->GetCurrentVolume();
         TGeoMaterial *curmat =curvol->GetMedium()->GetMaterial();
         const Double_t *global_point = gGeoManager->GetCurrentPoint();
         Double_t local_point[3];  // global_point[3];
         gGeoManager->MasterToLocal(global_point, local_point);
         TGeoHMatrix *matrix = gGeoManager->GetCurrentMatrix();
         TGeoBBox *shape = (TGeoBBox*)curvol->GetShape();
         Float_t sizex = shape->GetDX();
         Float_t sizey = shape->GetDY();
         Float_t sizez = shape->GetDZ();
   //        cout <<"x_in: " << pt->GetXIn() << endl;
   // cout <<"x_mean: " << x_mean << endl;
         //cout <<"x_out: " << pt->GetXOut() << endl;
         //cout <<"y: " << y_mean << endl;
         //cout <<"z_in: " << pt->GetZIn() << endl;
         //cout <<"z_mean: " << z_mean << endl;
   //        cout <<"z_out: " << pt->GetZOut() << endl;
         if (matrix->IsRotation()){
           cout <<"Module is rotated" << endl;
   } else {
           cout <<"Module is not rotated" << endl;
   }
     }
   */
 }
void FairTutorialDet2Digitizer::Finish () virtual
Finish task
Reimplemented from FairTask.
Definition at line 208 of file FairTutorialDet2Digitizer.cxx.
 {
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
InitStatus FairTutorialDet2Digitizer::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 99 of file FairTutorialDet2Digitizer.cxx.
References FairLogger::endl(), ERROR, FATAL, fTutorialDetPoints, FairRootManager::GetObject(), INFO, FairRootManager::Instance(), kERROR, kSUCCESS, and LOG.
 {
   LOG(INFO) << " FairTutorialDet2Digitizer :: Init() " << FairLogger::endl;
   FairRootManager* ioman = FairRootManager::Instance();
   if ( ! ioman ) {
     LOG(FATAL) << "No FairRootManager" << FairLogger::endl;
     return kERROR;
   } else {
     fTutorialDetPoints=(TClonesArray*)
                        ioman->GetObject("TutorialDetPoint");
     if ( ! fTutorialDetPoints ) {
       LOG(ERROR) << "No TutorialDetPoints array!" << FairLogger::endl;
       LOG(ERROR) << "Task will be inactive" << FairLogger::endl;
       return kERROR;
     }
     //fListStack = (TClonesArray*)ioman->GetObject("MCTrack");
     //fDigiCollection = new TClonesArray("FairTrdDigi", 100);
     //ioman->Register("TRDDigi","TRD Digis",fDigiCollection,kTRUE);
     return kSUCCESS;
   }
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
FairTutorialDet2Digitizer& FairTutorialDet2Digitizer::operator= (const FairTutorialDet2Digitizer &) private
void FairTutorialDet2Digitizer::Register ()
Definition at line 214 of file FairTutorialDet2Digitizer.cxx.
 {
   //FairRootManager::Instance()->Register("TrdDigi","Trd Digi", fDigiCollection, kTRUE);
 }
InitStatus FairTutorialDet2Digitizer::ReInit () virtual
Initialisation
Reimplemented from FairTask.
Definition at line 82 of file FairTutorialDet2Digitizer.cxx.
References FairLogger::endl(), fDigiPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), INFO, FairRunAna::Instance(), kSUCCESS, and LOG.
 {
   LOG(INFO) << " FairTutorialDet2Digitizer :: ReInit() " << FairLogger::endl;
   FairRunAna* ana = FairRunAna::Instance();
   FairRuntimeDb* rtdb=ana->GetRuntimeDb();
   fDigiPar = (FairTutorialDet2DigiPar*)
              (rtdb->getContainer("FairTutorialDet2DigiPar"));
   return kSUCCESS;
 }
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairTutorialDet2Digitizer::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 65 of file FairTutorialDet2Digitizer.cxx.
References FairLogger::endl(), fDigiPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), INFO, FairRunAna::Instance(), LOG, and FairTutorialDet2DigiPar::printparams().
 {
   LOG(INFO) << "FairTutorialDet2Digitizer :: SetParContainers() " << FairLogger::endl;
   // Get Base Container
   FairRunAna* ana = FairRunAna::Instance();
   FairRuntimeDb* rtdb=ana->GetRuntimeDb();
   fDigiPar = (FairTutorialDet2DigiPar*)
              (rtdb->getContainer("FairTutorialDet2DigiPar"));
   fDigiPar->printparams();
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
Member Data Documentation
FairTutorialDet2DigiPar* FairTutorialDet2Digitizer::fDigiPar private
Tutorial Det MC points.
Definition at line 66 of file FairTutorialDet2Digitizer.h.
Referenced by ReInit(), and SetParContainers().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
TClonesArray* FairTutorialDet2Digitizer::fTutorialDetPoints private
Definition at line 62 of file FairTutorialDet2Digitizer.h.
Referenced by Init().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
The documentation for this class was generated from the following files:
FairTutorialDet2Digitizer.h
FairTutorialDet2Digitizer.cxx