FairRroot: FairGeoLoader Class Reference
FairGeoLoader Class Reference
#include <FairGeoLoader.h>
Public Member Functions
FairGeoLoader (const char *Name, const char *title)
FairGeoLoader ()
virtual ~FairGeoLoader ()
FairGeoInterface * getGeoInterface ()
FairGeoBuilder * getGeoBuilder ()
Static Public Member Functions
static FairGeoLoader * Instance ()
Private Member Functions
FairGeoLoader (const FairGeoLoader &)
FairGeoLoader & operator= (const FairGeoLoader &)
Private Attributes
FairGeoInterface * fInterface
/**Singleton instance*/
FairGeoBuilder * fGeoBuilder
/** Hades Geometry Interface*/
Static Private Attributes
static FairGeoLoader * fgInstance =0
Detailed Description
New Geometry Loader, this loader handel the Hades geometry description
Author
Ilse koenig
M. Al-Turany
Definition at line 30 of file FairGeoLoader.h.
Constructor & Destructor Documentation
FairGeoLoader::FairGeoLoader (const char * Name, const char * title)
Definition at line 45 of file FairGeoLoader.cxx.
References fGeoBuilder, fgInstance, fInterface, and FairGeoInterface::setGeomBuilder().
   :TNamed(Name,title),
    fInterface(NULL),
    fGeoBuilder(NULL)
 {
   if (fgInstance) {
     Fatal("FairGeoLoader", "Singleton instance already exists.");
     return;
   }
   fgInstance = this;
   fInterface= new FairGeoInterface;
   if ( strncmp(Name,"TGeo",4) == 0 ) {
     TGeoManager* geom = new TGeoManager("FAIRGeom", "FAIR geometry");
     fGeoBuilder=new FairGeoRootBuilder("TGeo builder","geometry builder");
     ((FairGeoRootBuilder*)fGeoBuilder)->setGeoManager(geom);
   } else if ( strncmp(Name,"G3Native",8) == 0) {
     cout << "-I- FairGeoLoader() : Native G3 Geometry is used: This option is not supported any more!" << endl;
     exit(0);
     //        gGeoManager = NULL;
     //        fGeoBuilder=new FairGeoG3Builder("G3 builder","geometry builder");
   }
   fInterface->setGeomBuilder(fGeoBuilder);
 }
FairGeoLoader::FairGeoLoader ()
Definition at line 37 of file FairGeoLoader.cxx.
References fgInstance.
   :TNamed(),
    fInterface(NULL),
    fGeoBuilder(NULL)
 {
   fgInstance=this;
 }
FairGeoLoader::~FairGeoLoader () virtual
Definition at line 71 of file FairGeoLoader.cxx.
References fInterface.
 {
   delete fInterface;
 }
FairGeoLoader::FairGeoLoader (const FairGeoLoader &) private
Member Function Documentation
FairGeoBuilder* FairGeoLoader::getGeoBuilder () inline
Definition at line 37 of file FairGeoLoader.h.
References fGeoBuilder.
Referenced by FairModule::AssignMediumAtImport(), ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairPipe::ConstructGeometry(), FairTestDetector::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), and FairModule::ReAssignMediaId().
 {return   fGeoBuilder; }
FairGeoInterface* FairGeoLoader::getGeoInterface () inline
Definition at line 36 of file FairGeoLoader.h.
References fInterface.
Referenced by FairModule::AssignMediumAtImport(), ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairPipe::ConstructGeometry(), FairTestDetector::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairMCApplication::ConstructOpGeometry(), FairGeoPipe::create(), and FairRunSim::Init().
 {return fInterface;}
FairGeoLoader * FairGeoLoader::Instance () static
static access method
Definition at line 32 of file FairGeoLoader.cxx.
References fgInstance.
Referenced by FairModule::AssignMediumAtImport(), ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairPipe::ConstructGeometry(), FairTestDetector::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairMCApplication::ConstructOpGeometry(), FairGeoPipe::create(), and FairModule::ReAssignMediaId().
 {
   return fgInstance;
 }
FairGeoLoader& FairGeoLoader::operator= (const FairGeoLoader &) private
Member Data Documentation
FairGeoBuilder* FairGeoLoader::fGeoBuilder private
/** Hades Geometry Interface*/
Definition at line 46 of file FairGeoLoader.h.
Referenced by FairGeoLoader(), and getGeoBuilder().
FairGeoLoader * FairGeoLoader::fgInstance =0 static private
Definition at line 44 of file FairGeoLoader.h.
Referenced by FairGeoLoader(), and Instance().
FairGeoInterface* FairGeoLoader::fInterface private
/**Singleton instance*/
Definition at line 45 of file FairGeoLoader.h.
Referenced by FairGeoLoader(), getGeoInterface(), and ~FairGeoLoader().
The documentation for this class was generated from the following files:
FairGeoLoader.h
FairGeoLoader.cxx