FairRoot: DigiToHitTask_TCA< DigiType, HitType > Class Template Reference
DigiToHitTask_TCA< DigiType, HitType > Class Template Reference
#include <DigiToHitTask.h>
Public Member Functions
DigiToHitTask_TCA ()
virtual ~DigiToHitTask_TCA ()
void InitTask (const std::string &ClassName)
void InitContainer (const char *ClassName)
void InitContainer (TClonesArray *array)
void ExecuteTask (TClonesArray *inputdata)
TClonesArray * GetOutputData ()
Protected Member Functions
template<typename T = DigiType, enable_if_AllowedType< T > = 0>
void ProcessDigi (const DigiType &Digi, TVector3 &pos, TVector3 &dpos, Double_t &t, Double_t &t_err)
template<typename T = DigiType, enable_if_AllowedPodType< T > = 0>
void ProcessDigi (const DigiType &Digi, TVector3 &pos, TVector3 &dpos, Double_t &t, Double_t &t_err)
template<typename T = HitType, enable_if_AllowedType< T > = 0>
void FillHit (HitType &Hit, const Int_t &detID, const Int_t &MCIndex, const TVector3 &pos, const TVector3 &dpos, const Double_t &t, const Double_t &t_err)
template<typename T = HitType, enable_if_AllowedPodType< T > = 0>
void FillHit (HitType &Hit, const Int_t &detID, const Int_t &MCIndex, const TVector3 &pos, const TVector3 &dpos, const Double_t &t, const Double_t &t_err)
Protected Attributes
TClonesArray * fOutputContainer
std::string fTaskName
Int_t fDetID
Int_t fMCIndex
Detailed Description
template<typename DigiType, typename HitType>
class DigiToHitTask_TCA< DigiType, HitType >
Definition at line 83 of file DigiToHitTask.h.
Constructor & Destructor Documentation
template<typename DigiType , typename HitType > DigiToHitTask_TCA< DigiType, HitType >::DigiToHitTask_TCA () inline
Definition at line 94 of file DigiToHitTask.h.
                         :
         BaseDigiToHitTask<DigiType,HitType>(),
         fOutputContainer(nullptr)
     {}
template<typename DigiType , typename HitType > virtual DigiToHitTask_TCA< DigiType, HitType >::~DigiToHitTask_TCA () inline virtual
Definition at line 99 of file DigiToHitTask.h.
     {}
Member Function Documentation
template<typename DigiType , typename HitType > void DigiToHitTask_TCA< DigiType, HitType >::ExecuteTask (TClonesArray * inputdata) inline
Definition at line 118 of file DigiToHitTask.h.
References BaseDigiToHitTask< DigiType, HitType >::fDetID, BaseDigiToHitTask< DigiType, HitType >::fMCIndex, DigiToHitTask_TCA< DigiType, HitType >::fOutputContainer, and BaseDigiToHitTask< DigiType, HitType >::ProcessDigi().
     {
         //HitType Hit;
         fOutputContainer->Delete();
         for(unsigned int idigi(0);idigi<inputdata->GetEntriesFast();idigi++)
         {
             TVector3 pos;
             TVector3 dpos;
             Double_t timestamp=0;
             Double_t timestampErr=0;
             DigiType* digi = (DigiType*)inputdata->At(idigi);
             ProcessDigi(*digi, pos, dpos, timestamp, timestampErr);
             //FillHit(Hit,fDetID,fMCIndex, pos, dpos, timestamp, timestampErr);
             HitType* hit = new ((*fOutputContainer)[idigi]) HitType(fDetID, fMCIndex, pos, dpos);
             hit->SetTimeStamp(digi->GetTimeStamp());
             hit->SetTimeStampError(digi->GetTimeStampError());
             //fOutputContainer.push_back(Hit);
         }
     }
template<typename DigiType , typename HitType > template<typename T = HitType, enable_if_AllowedType< T > = 0> void BaseDigiToHitTask< DigiType, HitType >::FillHit (HitType & Hit, const Int_t & detID, const Int_t & MCIndex, const TVector3 & pos, const TVector3 & dpos, const Double_t & t, const Double_t & t_err) inline protected inherited
Definition at line 122 of file BaseDigiToHitTask.h.
Referenced by DigiToHitTask< DigiType, HitType >::ExecuteTask().
         {
             Hit.SetDetectorID(detID);
             Hit.SetRefIndex(MCIndex);
             Hit.SetPosition(pos);
             Hit.SetPositionError(dpos);
             Hit.SetTimeStamp(t);
             Hit.SetTimeStampError(t_err);
         }
template<typename DigiType , typename HitType > template<typename T = HitType, enable_if_AllowedPodType< T > = 0> void BaseDigiToHitTask< DigiType, HitType >::FillHit (HitType & Hit, const Int_t & detID, const Int_t & MCIndex, const TVector3 & pos, const TVector3 & dpos, const Double_t & t, const Double_t & t_err) inline protected inherited
Definition at line 133 of file BaseDigiToHitTask.h.
         {
             Hit.detID=detID;
             Hit.mcindex=MCIndex;
             Hit.fTimeStamp=t;
             Hit.fTimeStampError=t_err;
             Hit.posX=pos.X();
             Hit.posY=pos.Y();
             Hit.posZ=pos.Z();
             Hit.dposX=dpos.X();
             Hit.dposY=dpos.Y();
             Hit.dposZ=dpos.Z();
         }
template<typename DigiType , typename HitType > TClonesArray* DigiToHitTask_TCA< DigiType, HitType >::GetOutputData () inline
Definition at line 140 of file DigiToHitTask.h.
References DigiToHitTask_TCA< DigiType, HitType >::fOutputContainer.
     {
         return fOutputContainer;
     }
template<typename DigiType , typename HitType > void DigiToHitTask_TCA< DigiType, HitType >::InitContainer (const char * ClassName) inline
Definition at line 108 of file DigiToHitTask.h.
References DigiToHitTask_TCA< DigiType, HitType >::fOutputContainer.
Referenced by DigiToHitTask_TCA< DigiType, HitType >::InitTask().
     {
         fOutputContainer = new TClonesArray(ClassName);
     }
template<typename DigiType , typename HitType > void DigiToHitTask_TCA< DigiType, HitType >::InitContainer (TClonesArray * array) inline
Definition at line 113 of file DigiToHitTask.h.
References DigiToHitTask_TCA< DigiType, HitType >::fOutputContainer.
     {
         fOutputContainer = array;
     }
template<typename DigiType , typename HitType > void DigiToHitTask_TCA< DigiType, HitType >::InitTask (const std::string & ClassName) inline
Definition at line 103 of file DigiToHitTask.h.
References DigiToHitTask_TCA< DigiType, HitType >::InitContainer().
     {
         InitContainer(ClassName.c_str());
     }
template<typename DigiType , typename HitType > template<typename T = DigiType, enable_if_AllowedType< T > = 0> void BaseDigiToHitTask< DigiType, HitType >::ProcessDigi (const DigiType & Digi, TVector3 & pos, TVector3 & dpos, Double_t & t, Double_t & t_err) inline protected inherited
Definition at line 104 of file BaseDigiToHitTask.h.
Referenced by DigiToHitTask< DigiType, HitType >::ExecuteTask(), and DigiToHitTask_TCA< DigiType, HitType >::ExecuteTask().
         {
             pos.SetXYZ(Digi.GetX() + 0.5, Digi.GetY() + 0.5, Digi.GetZ() + 0.5);
             dpos.SetXYZ(1 / TMath::Sqrt(12), 1 / TMath::Sqrt(12), 1 / TMath::Sqrt(12));
             t=Digi.GetTimeStamp();
             t_err=Digi.GetTimeStampError();
         }
template<typename DigiType , typename HitType > template<typename T = DigiType, enable_if_AllowedPodType< T > = 0> void BaseDigiToHitTask< DigiType, HitType >::ProcessDigi (const DigiType & Digi, TVector3 & pos, TVector3 & dpos, Double_t & t, Double_t & t_err) inline protected inherited
Definition at line 113 of file BaseDigiToHitTask.h.
         {
             pos.SetXYZ(Digi.fX + 0.5, Digi.fY + 0.5, Digi.fZ + 0.5);
             dpos.SetXYZ(1 / TMath::Sqrt(12), 1 / TMath::Sqrt(12), 1 / TMath::Sqrt(12));
             t=Digi.fTimeStamp;
             t_err=Digi.fTimeStampError;
         }
Member Data Documentation
template<typename DigiType , typename HitType > Int_t BaseDigiToHitTask< DigiType, HitType >::fDetID protected inherited
Definition at line 100 of file BaseDigiToHitTask.h.
Referenced by DigiToHitTask< DigiType, HitType >::ExecuteTask(), and DigiToHitTask_TCA< DigiType, HitType >::ExecuteTask().
template<typename DigiType , typename HitType > Int_t BaseDigiToHitTask< DigiType, HitType >::fMCIndex protected inherited
Definition at line 101 of file BaseDigiToHitTask.h.
Referenced by DigiToHitTask< DigiType, HitType >::ExecuteTask(), and DigiToHitTask_TCA< DigiType, HitType >::ExecuteTask().
template<typename DigiType , typename HitType > TClonesArray* DigiToHitTask_TCA< DigiType, HitType >::fOutputContainer protected
Definition at line 147 of file DigiToHitTask.h.
Referenced by DigiToHitTask_TCA< DigiType, HitType >::ExecuteTask(), DigiToHitTask_TCA< DigiType, HitType >::GetOutputData(), and DigiToHitTask_TCA< DigiType, HitType >::InitContainer().
template<typename DigiType , typename HitType > std::string BaseDigiToHitTask< DigiType, HitType >::fTaskName protected inherited
Definition at line 99 of file BaseDigiToHitTask.h.
The documentation for this class was generated from the following file:
DigiToHitTask.h