FairRroot: FairTestDetectorGeo Class Reference
FairTestDetectorGeo Class Reference
#include <FairTestDetectorGeo.h>
Public Member Functions
FairTestDetectorGeo ()
~FairTestDetectorGeo ()
const char * getModuleName (Int_t)
const char * getEleName (Int_t)
Int_t getModNumInMod (const TString &)
void setShapes (FairGeoShapes *s)
void setMasterNodes (TList *m)
void setGeomFile (const char *filename)
const char * getGeomFile ()
Int_t getMaxSectors (void)
Int_t getMaxModules (void)
Int_t getMaxKeepinVolumes (void)
void setModules (Int_t, Int_t *)
Int_t * getModules (void)
Int_t getModule (Int_t, Int_t)
FairGeoNode * getVolume (const char *name)
FairGeoNode * getMasterNode (const char *name)
TList * getListOfVolumes ()
FairGeoShapes * getShapes ()
void setAuthor (TString &s)
void setDescription (TString &s)
TString & getAuthor ()
TString & getDescription ()
virtual const char * getKeepinName (Int_t, Int_t)
virtual Int_t getSecNumInMod (const TString &)
virtual Bool_t read (fstream &, FairGeoMedia *)
virtual void addRefNodes ()
virtual void write (fstream &)
virtual void print ()
virtual Bool_t create (FairGeoBuilder *)
void compare (FairGeoSet &)
Protected Member Functions
void readInout (fstream &)
void readTransform (fstream &, FairGeoTransform &)
Bool_t readVolumeParams (fstream &, FairGeoMedia *, FairGeoNode *, TList *l=0)
Bool_t readKeepIn (fstream &, FairGeoMedia *, TString &)
Bool_t readModule (fstream &, FairGeoMedia *, TString &, TString &, Bool_t a=kFALSE)
Protected Attributes
char modName [20]
char eleName [20]
Int_t hadesGeo
TList * volumes
TList * masterNodes
Int_t maxSectors
Int_t maxKeepinVolumes
Int_t maxModules
TArrayI * modules
FairGeoShapes * pShapes
TString geoFile
TString author
TString description
Detailed Description
Definition at line 16 of file FairTestDetectorGeo.h.
Constructor & Destructor Documentation
FairTestDetectorGeo::FairTestDetectorGeo ()
FairTestDetectorGeo::~FairTestDetectorGeo () inline
Definition at line 24 of file FairTestDetectorGeo.h.
     {
     }
Member Function Documentation
virtual void FairGeoSet::addRefNodes () inline virtual inherited
Reimplemented in MyGeoCave, and FairGeoCave.
Definition at line 95 of file FairGeoSet.h.
 {}
void FairGeoSet::compare (FairGeoSet & rset) inherited
Definition at line 412 of file FairGeoSet.cxx.
References FairGeoNode::compare(), FairGeoSet::getListOfVolumes(), FairGeoSet::getVolume(), and FairGeoSet::volumes.
 {
   // Compares the geometry parameters and print a diagnose
   if (fName.CompareTo(rset.GetName())!=0) {
     Error("compare","Sets have different type");
     return;
   }
   TListIter iter(volumes);
   FairGeoNode* volu;
   Int_t n=0, nnf=0, nDiff=0;
   cout<<"name\t mother medium shape  points    pos    rot\n";
   cout<<"------------------------------------------------\n";
   while((volu=(FairGeoNode*)iter.Next())) {
     n++;
     FairGeoNode* rNode=rset.getVolume(volu->GetName());
     if (!rNode) { nnf++; }
     else if (volu->compare(*rNode)>0) { nDiff++; }
   }
   cout<<"Number of volumes in first list:             "<<n<<'\n';
   cout<<"Number of different volumes:                 "<<nDiff<<endl;
   cout<<"Number of volumes not found in second list:  "<<nnf<<'\n';
   TList* rlist=rset.getListOfVolumes();
   if (rlist->GetSize()!=(n-nnf)) {
     nnf=0;
     TListIter riter(rlist);
     while((volu=(FairGeoNode*)riter.Next())) {
       FairGeoNode* rNode=getVolume(volu->GetName());
       if (!rNode) { nnf++; }
     }
   } else { nnf=0; }
   cout<<"Number of additional volumes in second list: "<<nnf<<'\n';
 }
Bool_t FairGeoSet::create (FairGeoBuilder * builder) virtual inherited
Reimplemented in FairGeoPipe.
Definition at line 386 of file FairGeoSet.cxx.
References FairGeoBuilder::createNode(), FairGeoNode::getCenterPosition(), FairGeoSet::getMasterNode(), FairGeoNode::getRootVolume(), FairGeoSet::hadesGeo, FairGeoNode::isActive(), FairGeoNode::isRefNode(), FairGeoNode::isTopNode(), FairGeoNode::setCenterPosition(), FairGeoNode::setRootVolume(), and FairGeoSet::volumes.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairGeoPipe::create(), FairGeoInterface::createAll(), FairGeoInterface::createGeometry(), and FairGeoInterface::createSet().
 {
   // Creates the geometry
   if (!builder) { return kFALSE; }
   TListIter iter(volumes);
   FairGeoNode* volu;
   Bool_t rc=kTRUE;
   while((volu=(FairGeoNode*)iter.Next())&&rc) {
     if (volu->isActive()) {
       if (hadesGeo == 1) { rc=builder->createNode(volu, hadesGeo); }
       else { rc=builder->createNode(volu) ; }
       if (rc) {
         if (volu->isTopNode()||volu->isRefNode()) {
           FairGeoNode* n=getMasterNode(volu->GetName());
           if (n) {
             n->setCenterPosition(volu->getCenterPosition());
             n->setRootVolume(volu->getRootVolume());
           }
         }
       } else { Error("create","Creation of %s failed!",volu->GetName()); }
     }
   }
   return rc;
 }
TString& FairGeoSet::getAuthor () inline inherited
Definition at line 87 of file FairGeoSet.h.
References FairGeoSet::author.
 {return author;}
TString& FairGeoSet::getDescription () inline inherited
Definition at line 88 of file FairGeoSet.h.
References FairGeoSet::description.
 {return description;}
const char * FairTestDetectorGeo::getEleName (Int_t m) virtual
Returns the element name of Det number m
Reimplemented from FairGeoSet.
Definition at line 39 of file FairTestDetectorGeo.cxx.
References eleName.
 {
     sprintf(eleName, "torino%i", m + 1);
     return eleName;
 }
const char* FairGeoSet::getGeomFile () inline inherited
Definition at line 74 of file FairGeoSet.h.
Referenced by FairGeoInterface::print(), and FairGeoInterface::readSet().
 { return geoFile.Data(); }
virtual const char* FairGeoSet::getKeepinName (Int_t , Int_t) inline virtual inherited
Definition at line 89 of file FairGeoSet.h.
Referenced by FairGeoSet::read().
 {return 0;}
TList* FairGeoSet::getListOfVolumes () inline inherited
Definition at line 83 of file FairGeoSet.h.
References FairGeoSet::volumes.
Referenced by ClassImp(), FairGeoSet::compare(), FairMagnet::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), FairRutherford::ConstructGeometry(), and FairGeoOldAsciiIo::read().
 {return volumes;}
FairGeoNode* FairGeoSet::getMasterNode (const char * name) inline inherited
Definition at line 82 of file FairGeoSet.h.
Referenced by FairGeoSet::create(), FairGeoOldAsciiIo::read(), and FairGeoSet::readVolumeParams().
 {return (FairGeoNode*)masterNodes->FindObject(name);}
Int_t FairGeoSet::getMaxKeepinVolumes (void) inline inherited
Definition at line 77 of file FairGeoSet.h.
References FairGeoSet::maxKeepinVolumes.
 {return maxKeepinVolumes;}
Int_t FairGeoSet::getMaxModules (void) inline inherited
Definition at line 76 of file FairGeoSet.h.
References FairGeoSet::maxModules.
Referenced by FairGeoAsciiIo::readDetectorSetup().
 {return maxModules;}
Int_t FairGeoSet::getMaxSectors (void) inline inherited
Definition at line 75 of file FairGeoSet.h.
References FairGeoSet::maxSectors.
 {return maxSectors;}
Int_t FairTestDetectorGeo::getModNumInMod (const TString & name) inline virtual
returns the module index from module name ?? in name[??] has to be the length of the detector name in the .geo file. For example if all nodes in this file starts with newdetector ?? has to be 11.
Reimplemented from FairGeoSet.
Definition at line 33 of file FairTestDetectorGeo.h.
 {
     return (Int_t)(name[6] - '0') - 1; //
 }
Int_t FairGeoSet::getModule (Int_t s, Int_t m) inherited
Definition at line 94 of file FairGeoSet.cxx.
References FairGeoSet::maxModules, FairGeoSet::maxSectors, and FairGeoSet::modules.
Referenced by FairGeoSet::read(), and FairGeoSet::readModule().
 {
   // Returns 1, if the module is not explicitly set inactive
   // (in this case it returns 0)
   // May be called with s=-1 for detectors not belonging to a sector
   if (!modules) { return 1; }
   if (m<maxModules&&s<0) { return (*modules)[m]; }
   if (m<maxModules&&s<maxSectors) { return (*modules)[(s*maxModules+m)]; }
   return 0;
 }
const char * FairTestDetectorGeo::getModuleName (Int_t m) virtual
Returns the module name of FairTestDetector number m Setting FairTestDetector here means that all modules names in the ASCII file should start with FairTestDetector otherwise they will not be constructed
Reimplemented from FairGeoSet.
Definition at line 28 of file FairTestDetectorGeo.cxx.
References modName.
 {
     sprintf(modName, "torino%i", m + 1);
     return modName;
 }
Int_t * FairGeoSet::getModules (void) inherited
Definition at line 87 of file FairGeoSet.cxx.
References FairGeoSet::modules.
 {
   // Returns a linear array of all modules
   if (modules) { return modules->GetArray(); }
   return 0;
 }
virtual Int_t FairGeoSet::getSecNumInMod (const TString &) inline virtual inherited
Definition at line 92 of file FairGeoSet.h.
Referenced by FairGeoSet::readModule().
 {return -1;}
FairGeoShapes* FairGeoSet::getShapes () inline inherited
Definition at line 84 of file FairGeoSet.h.
References FairGeoSet::pShapes.
Referenced by FairGeoOldAsciiIo::read().
 {return pShapes;}
FairGeoNode* FairGeoSet::getVolume (const char * name) inline inherited
Definition at line 81 of file FairGeoSet.h.
Referenced by FairGeoSet::compare(), FairGeoPipe::create(), FairGeoOldAsciiIo::read(), and FairGeoSet::readVolumeParams().
 {return (FairGeoNode*)volumes->FindObject(name);}
void FairGeoSet::print () virtual inherited
Reimplemented in MyGeoCave, and FairGeoCave.
Definition at line 355 of file FairGeoSet.cxx.
References FairGeoSet::author, FairGeoSet::description, FairGeoNode::print(), and FairGeoSet::volumes.
 {
   // Prints the geometry
   if (!author.IsNull()) { cout<<"//Author:      "<<author<<'\n'; }
   if (!description.IsNull()) { cout<<"//Description: "<<description<<'\n'; }
   if (!description.IsNull()) {
     cout<<"//----------------------------------------------------------\n";
   }
   cout.setf(ios::fixed,ios::floatfield);
   TListIter iter(volumes);
   FairGeoNode* volu;
   while((volu=(FairGeoNode*)iter.Next())) {
     volu->print();
   }
 }
Bool_t FairGeoSet::read (fstream & fin, FairGeoMedia * media) virtual inherited
Reimplemented in MyGeoCave, and FairGeoCave.
Definition at line 105 of file FairGeoSet.cxx.
References FairGeoSet::getEleName(), FairGeoSet::getKeepinName(), FairGeoSet::getModule(), FairGeoSet::getModuleName(), FairGeoSet::maxKeepinVolumes, FairGeoSet::maxModules, FairGeoSet::maxSectors, FairGeoSet::readKeepIn(), and FairGeoSet::readModule().
Referenced by FairGeoAsciiIo::read().
 {
   // Reads the geometry from file
   Int_t s1=-1,s2=0;
   if (maxSectors>0) {
     s1=0;
     s2=maxSectors;
   }
   Bool_t rc=kTRUE;
   for (Int_t s=s1; s<s2&&rc; s++) {
     for (Int_t k=0; k<maxKeepinVolumes&&rc; k++) {
       TString keepinName=getKeepinName(s,k);
       rc=readKeepIn(fin,media,keepinName);
     }
   }
   for (Int_t m=0; m<maxModules&&rc; m++) {
     Bool_t containsActiveModule=kFALSE;
     for (Int_t s=s1; s<s2; s++) {
       if (getModule(s,m)) { containsActiveModule=kTRUE; }
     }
     TString modName=getModuleName(m);
     TString eleName=getEleName(m);
     rc=readModule(fin,media,modName,eleName,containsActiveModule);
   }
   return rc;
 }
void FairGeoSet::readInout (fstream & fin) protected inherited
Definition at line 132 of file FairGeoSet.cxx.
Referenced by FairGeoSet::readKeepIn(), and FairGeoSet::readModule().
 {
   // Reads the inout flag (in old files)
   char c=' ';
   do {
     c=fin.get();
   } while (c==' ' || c=='\n');
   if (c!='0'&&c!='1') { fin.putback(c); }
   else do {
       c=fin.get();
     } while (c!='\n');
   return;
 }
Bool_t FairGeoSet::readKeepIn (fstream & fin, FairGeoMedia * media, TString & name) protected inherited
Definition at line 263 of file FairGeoSet.cxx.
References kFairGeoKeepin, FairGeoSet::readInout(), FairGeoSet::readVolumeParams(), FairGeoNode::setVolumeType(), and FairGeoSet::volumes.
Referenced by FairGeoSet::read().
 {
   // Reads the keepin volume from file
   fin.clear();
   fin.seekg(0, ios::beg);
   FairGeoNode* volu=0;
   Bool_t rc=kTRUE;
   TList refVolumes;
   const Int_t maxbuf=256;
   char buf[maxbuf];
   while(rc && !volu && !fin.eof()) {
     fin>>buf;
     if (buf[0]=='/') { fin.getline(buf,maxbuf); }
     else if (!fin.eof()) {
       if (strcmp(buf,name)==0) {
         volu=new FairGeoNode;
         volu->SetName(buf);
         volu->setVolumeType(kFairGeoKeepin);
         readInout(fin);
         rc=readVolumeParams(fin,media,volu,&refVolumes);
       } else {
         do {
           fin.getline(buf,maxbuf);
         } while(!fin.eof()&&buf[0]!='/');
       }
     }
   }
   if (rc) { volumes->Add(volu); }
   else {
     delete volu;
     volu=0;
   }
   refVolumes.Delete();
   return rc;
 }
Bool_t FairGeoSet::readModule (fstream & fin, FairGeoMedia * media, TString & modName, TString & eleName, Bool_t a = kFALSE) protected inherited
Definition at line 299 of file FairGeoSet.cxx.
References FairGeoSet::getModNumInMod(), FairGeoSet::getModule(), FairGeoSet::getSecNumInMod(), kFairGeoElement, kFairGeoModule, FairGeoSet::readInout(), FairGeoSet::readVolumeParams(), FairGeoNode::setActive(), FairGeoNode::setVolumeType(), and FairGeoSet::volumes.
Referenced by FairGeoSet::read().
 {
   // Reads the whole geometry of a module from file
   const Int_t maxbuf=256;
   Text_t buf[maxbuf];
   fin.clear();
   fin.seekg(0,ios::beg);
   FairGeoNode* volu=0;
   Bool_t rc=kTRUE;
   TList refVolumes;
   TString name;
   while(rc && !fin.eof()) {
     fin>>buf;
     if (buf[0]=='/') { fin.getline(buf,maxbuf); }
     else if (!fin.eof()) {
       //TString name(buf);
       name=buf;
       if (name.BeginsWith(modName)) {
         volu=new FairGeoNode;
         volu->SetName(buf);
         volu->setVolumeType(kFairGeoModule);
         Int_t a=getModule(getSecNumInMod(buf),getModNumInMod(buf));
         if (a>0) { volu->setActive(kTRUE); }
         else { volu->setActive(kFALSE); }
         readInout(fin);
         rc=readVolumeParams(fin,media,volu,&refVolumes);
         if (rc) { volumes->Add(volu); }
         else {
           Error("readModule","Failed for module %s\n",volu->GetName());
           delete volu;
           volu=0;
         }
       } else if (!eleName.IsNull()&&name.BeginsWith(eleName)) {
         volu=new FairGeoNode;
         volu->SetName(buf);
         volu->setVolumeType(kFairGeoElement);
         volu->setActive(containsActiveMod);
         rc=readVolumeParams(fin,media,volu,&refVolumes);
         if (rc) { volumes->Add(volu); }
         else {
           Error("readModule","Failed for %s\n",volu->GetName());
           delete volu;
           volu=0;
         }
       } else {
         do {
           fin.getline(buf,maxbuf);
         } while(!fin.eof()&&buf[0]!='/');
       }
     }
   }
   refVolumes.Delete();
   return rc;
 }
void FairGeoSet::readTransform (fstream & fin, FairGeoTransform & tf) protected inherited
Definition at line 146 of file FairGeoSet.cxx.
References FairGeoTransform::setRotMatrix(), and FairGeoTransform::setTransVector().
Referenced by FairGeoSet::readVolumeParams().
 {
   // Reads the transformation from file
   Double_t r[9], t[3];
   fin>>t[0]>>t[1]>>t[2];
   for(Int_t i=0; i<9; i++) { fin>>r[i]; }
   tf.setRotMatrix(r);
   tf.setTransVector(t);
 }
Bool_t FairGeoSet::readVolumeParams (fstream & fin, FairGeoMedia * media, FairGeoNode * volu, TList * l = 0) protected inherited
Definition at line 156 of file FairGeoSet.cxx.
References FairGeoVolume::createPoints(), FairGeoSet::getMasterNode(), FairGeoMedia::getMedium(), FairGeoNode::getMedium(), FairGeoVolume::getNumPoints(), FairGeoVolume::getPoint(), FairGeoNode::getShapePointer(), FairGeoVolume::getTransform(), FairGeoSet::getVolume(), FairGeoSet::hadesGeo, FairGeoNode::isActive(), FairGeoNode::isKeepin(), FairGeoNode::isModule(), FairGeoSet::FairGeoCopyNode::pNode, FairGeoSet::pShapes, FairGeoBasicShape::readPoints(), FairGeoSet::readTransform(), FairGeoShapes::selectShape(), FairGeoNode::setActive(), FairGeoNode::setCopyNode(), FairGeoNode::setMedium(), FairGeoNode::setMother(), FairGeoVolume::setPoint(), and FairGeoNode::setShape().
Referenced by FairGeoSet::readKeepIn(), and FairGeoSet::readModule().
 {
   // Reads the volume definition from file
 //  Int_t hadgeo =  1;
   if (volu==0||media==0||refVolumes==0) { return kFALSE; }
   const Int_t maxbuf=256;
   char buf[maxbuf];
   TString name(volu->GetName());
   Int_t nameLength=name.Length();
   Bool_t isCopy=kFALSE;
   fin>>buf;
   FairGeoNode* mother=0;
   FairGeoCopyNode* refNode=0;
   TString refName;
   if (volu->isKeepin()) { mother=getMasterNode(buf); }
   else if (volu->isModule()) {
     mother=getMasterNode(buf);
     if (!mother) { mother=getVolume(buf); }
     if (volu->isActive()&&mother) { mother->setActive(); }
   } else {
     mother=getVolume(buf);
     if (!mother) { mother=getMasterNode(buf); }
   }
   volu->setMother(mother);
   if (!mother) { Warning("readVolumeParams","Mother volume %s not found!",buf); }
   if ( hadesGeo == 1 ) {
     //  cout << " read copies in Hades format " << endl;
     if (nameLength>4) {
       char c;
       do {
         c=fin.get();
       } while (c==' ' || c=='\n');
       Int_t i=(Int_t)c ;
       fin.putback(c);
       if (!isalpha(i)) { isCopy=kTRUE; }
       refName=name(0,4);
       refNode=(FairGeoCopyNode*)refVolumes->FindObject(refName);
       if (!refNode) {
         if (isCopy) { return kFALSE; }
         refVolumes->Add(new FairGeoCopyNode(refName.Data(),volu));
       } else {
         FairGeoNode* cn=refNode->pNode;
         volu->setCopyNode(cn);
         volu->setMedium(cn->getMedium());
         volu->setShape(cn->getShapePointer());
         Int_t n=cn->getNumPoints();
         volu->createPoints(n);
         for (Int_t k=0; k<n; k++) { volu->setPoint(k,*(cn->getPoint(k))); }
       }
     }
   } else {
     // cbm format
     Ssiz_t l=name.Last('#');
     if (l>0) {
       char c;
       do {
         c=fin.get();
       } while (c==' ' || c=='\n');
       Int_t i=(Int_t)c;
       fin.putback(c);
       if (!isalpha(i)) { isCopy=kTRUE; }
       refName=name(0,l);
       refNode=(FairGeoCopyNode*)refVolumes->FindObject(refName);
       if (!refNode) {
         if (isCopy) { return kFALSE; }
         refVolumes->Add(new FairGeoCopyNode(refName.Data(),volu));
       } else {
         FairGeoNode* cn=refNode->pNode;
         volu->setCopyNode(cn);
         volu->setMedium(cn->getMedium());
         volu->setShape(cn->getShapePointer());
         Int_t n=cn->getNumPoints();
         volu->createPoints(n);
         for (Int_t k=0; k<n; k++) { volu->setPoint(k,*(cn->getPoint(k))); }
       }
     }
   }
   if (!isCopy) {
     fin>>buf;
     FairGeoBasicShape* sh=pShapes->selectShape(buf);
     if (sh) { volu->setShape(sh); }
     else { return kFALSE; }
     fin>>buf;
     FairGeoMedium* medium=media->getMedium(buf);
     if (!medium) {
       Error("readVolumeParams","Medium %s not found in list of media",buf);
       return kFALSE;
     }
     volu->setMedium(medium);
     Int_t n=0;
     fin.getline(buf,maxbuf); // to read the end of line
     if (sh) { n=sh->readPoints(&fin,volu); }
     if (n<=0) { return kFALSE; }
   }
   readTransform(fin,volu->getTransform());
   return kTRUE;
 }
void FairGeoSet::setAuthor (TString & s) inline inherited
Definition at line 85 of file FairGeoSet.h.
 {author=s;}
void FairGeoSet::setDescription (TString & s) inline inherited
Definition at line 86 of file FairGeoSet.h.
 {description=s;}
void FairGeoSet::setGeomFile (const char * filename) inline inherited
Definition at line 73 of file FairGeoSet.h.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), FairRutherford::ConstructGeometry(), and FairTutorialDet1::ConstructGeometry().
 {geoFile=filename;}
void FairGeoSet::setMasterNodes (TList * m) inline inherited
Definition at line 72 of file FairGeoSet.h.
Referenced by FairGeoInterface::addGeoModule().
 {masterNodes=m;}
void FairGeoSet::setModules (Int_t s, Int_t * m) inherited
Definition at line 72 of file FairGeoSet.cxx.
References FairGeoSet::maxModules, FairGeoSet::maxSectors, and FairGeoSet::modules.
Referenced by FairGeoAsciiIo::readDetectorSetup().
 {
   // Stores the modules given in 'm' as active modules in sector 's'
   // May be called with s=-1 for detectors not belonging to a sector
   if (!modules) {
     if (maxSectors==0&&maxModules>0) { modules=new TArrayI(maxModules); }
     if (maxSectors>0&&maxModules>0) { modules=new TArrayI(maxSectors*maxModules); }
   }
   Int_t sec=0;
   if (s>0) { sec=s; }
   for(Int_t i=0; i<maxModules; i++) {
     if (modules) { modules->AddAt(m[i],(sec*maxModules+i)); }
   }
 }
void FairGeoSet::setShapes (FairGeoShapes * s) inline inherited
Definition at line 71 of file FairGeoSet.h.
Referenced by FairGeoInterface::addGeoModule().
 {pShapes=s;}
void FairGeoSet::write (fstream & fout) virtual inherited
Reimplemented in MyGeoCave, and FairGeoCave.
Definition at line 371 of file FairGeoSet.cxx.
References FairGeoSet::author, FairGeoSet::description, FairGeoSet::volumes, and FairGeoNode::write().
Referenced by FairGeoAsciiIo::write().
 {
   // Writes the volumes to file
   if (!author.IsNull()) { fout<<"//Author:      "<<author<<'\n'; }
   if (!description.IsNull()) { fout<<"//Description: "<<description<<'\n'; }
   fout<<"//----------------------------------------------------------\n";
   fout.setf(ios::fixed,ios::floatfield);
   TListIter iter(volumes);
   FairGeoNode* volu;
   Bool_t rc=kTRUE;
   while((volu=(FairGeoNode*)iter.Next())&&rc) {
     rc=volu->write(fout);
   }
 }
Member Data Documentation
TString FairGeoSet::author protected inherited
name of geometry input file or Oracle
Definition at line 60 of file FairGeoSet.h.
Referenced by FairGeoSet::getAuthor(), FairGeoSet::print(), and FairGeoSet::write().
TString FairGeoSet::description protected inherited
author of the media version
Definition at line 61 of file FairGeoSet.h.
Referenced by FairGeoSet::getDescription(), FairGeoSet::print(), and FairGeoSet::write().
char FairTestDetectorGeo::eleName[20] protected
Definition at line 21 of file FairTestDetectorGeo.h.
Referenced by getEleName().
TString FairGeoSet::geoFile protected inherited
pointer to the class FairGeoShapes
Definition at line 59 of file FairGeoSet.h.
Int_t FairGeoSet::hadesGeo protected inherited
Definition at line 35 of file FairGeoSet.h.
Referenced by FairGeoSet::create(), and FairGeoSet::readVolumeParams().
TList* FairGeoSet::masterNodes protected inherited
list of volumes
Definition at line 53 of file FairGeoSet.h.
Int_t FairGeoSet::maxKeepinVolumes protected inherited
maximum number of sectors (-1 for detectors outside any sector)
Definition at line 55 of file FairGeoSet.h.
Referenced by FairGeoSet::getMaxKeepinVolumes(), and FairGeoSet::read().
Int_t FairGeoSet::maxModules protected inherited
maximum number of keepin volumes per sector
Definition at line 56 of file FairGeoSet.h.
Referenced by FairGeoSet::getMaxModules(), FairGeoSet::getModule(), FairGeoSet::read(), and FairGeoSet::setModules().
Int_t FairGeoSet::maxSectors protected inherited
pointer to list of mother volumes from other detector parts
Definition at line 54 of file FairGeoSet.h.
Referenced by FairGeoSet::getMaxSectors(), FairGeoSet::getModule(), FairGeoSet::read(), and FairGeoSet::setModules().
char FairTestDetectorGeo::modName[20] protected
Definition at line 20 of file FairTestDetectorGeo.h.
Referenced by getModuleName().
TArrayI* FairGeoSet::modules protected inherited
maximum number of modules per sector
Definition at line 57 of file FairGeoSet.h.
Referenced by FairGeoSet::getModule(), FairGeoSet::getModules(), FairGeoSet::setModules(), and FairGeoSet::~FairGeoSet().
FairGeoShapes* FairGeoSet::pShapes protected inherited
Module's array.
Definition at line 58 of file FairGeoSet.h.
Referenced by FairGeoSet::getShapes(), and FairGeoSet::readVolumeParams().
TList* FairGeoSet::volumes protected inherited
Definition at line 52 of file FairGeoSet.h.
Referenced by FairGeoSet::compare(), FairGeoSet::create(), FairGeoSet::getListOfVolumes(), FairGeoSet::print(), FairGeoSet::readKeepIn(), FairGeoSet::readModule(), FairGeoSet::write(), and FairGeoSet::~FairGeoSet().
The documentation for this class was generated from the following files:
FairTestDetectorGeo.h
FairTestDetectorGeo.cxx