FairRoot: LogLevelTest Class Reference
LogLevelTest Class Reference
Protected Member Functions
virtual void SetUp ()
virtual void SetUp ()
virtual void SetUp ()
void SetFairLoggerDefaultValues ()
void SetFairLoggerDefaultValues ()
void SetFairLoggerDefaultValues ()
void LogNoArguments ()
void LogNoArguments ()
void LogNoArguments (FairLogger *fLogger, std::string OutputString)
std::vector< std::string > CreateExpectedOutputNoArguments (std::string loglevel, std::string outString, std::string filename="")
std::vector< std::string > CreateExpectedOutputNoArguments (std::string loglevel, std::string outString, std::string filename="")
std::vector< std::string > CreateExpectedOutputNoArguments (std::string loglevel, std::string outString, std::string filename="")
std::vector< std::string > CreateExpectedLogLevels (std::string loglevel)
std::vector< std::string > CreateExpectedLogLevels (std::string loglevel)
std::vector< std::string > CreateExpectedLogLevels (std::string loglevel)
void CheckScreenOutput (std::vector< std::string > v)
void CheckScreenOutput (std::vector< std::string > v)
void CheckScreenOutput (FairCaptureOutput handler, std::vector< std::string > v)
std::vector< std::string > ReadLinesFromFile (std::string fileName)
void CheckFileOutput (std::vector< std::string > v, std::string fileName)
void CheckFileOutput (std::vector< std::string > v, FairTestOutputHandler _handler)
void CheckFileOutput (FairTestOutputHandler handler, std::vector< std::string > v)
bool CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verboseLevel, std::string resultString)
bool CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verboseLevel, std::string resultString)
bool CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verboseLevel, std::string resultString)
Protected Attributes
std::string logLevelSettingToTest
std::string OutputString
FairLogger * fLogger
FairTestNewOutputHandler handler
FairCaptureOutput handler
Detailed Description
Definition at line 206 of file _GTestFairTools.cxx.
Member Function Documentation
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckFileOutput (std::vector< std::string > v, FairTestOutputHandler _handler) inline protected inherited
Definition at line 143 of file _GTestFairToolsNew.cxx.
References FairTestOutputHandler::GetCaptureLine(), and FairTestOutputHandler::GetNumberOfLines().
{
       int noLines = _handler.GetNumberOfLines();
       int expectedNumberOfLines = v.size();
       EXPECT_EQ(expectedNumberOfLines,noLines);
       int minLines = std::min(expectedNumberOfLines,noLines);
       for (int i = 0; i < minLines; ++i) {
         EXPECT_EQ( v[i], _handler.GetCaptureLine(i) );
       }
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckFileOutput (FairTestOutputHandler handler, std::vector< std::string > v) inline protected inherited
Definition at line 150 of file _TestFairTools.cxx.
References FairTestOutputHandler::GetCaptureLine(), and FairTestOutputHandler::GetNumberOfLines().
{
       int noLines = handler.GetNumberOfLines();
       int expectedNumberOfLines = v.size();
       EXPECT_EQ(expectedNumberOfLines,noLines);
       int minLines = std::min(expectedNumberOfLines,noLines);
       for (int i = 0; i < minLines; ++i) {
         EXPECT_EQ( v[i], handler.GetCaptureLine(i) );
       }
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckFileOutput (std::vector< std::string > v, std::string fileName) inline protected inherited
Definition at line 165 of file _GTestFairTools.cxx.
References _TestFairLoggerBase< T >::ReadLinesFromFile().
{
       std::vector<std::string> fileInfo;
       fileInfo=ReadLinesFromFile(fileName);
       int noLines = fileInfo.size();
       int expectedNumberOfLines = v.size();
       EXPECT_EQ(expectedNumberOfLines,noLines);
       int minLines = std::min(expectedNumberOfLines,noLines);
       for (int i = 0; i < minLines; ++i) {
         EXPECT_EQ( v[i], fileInfo[i] );
       }
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckScreenOutput (std::vector< std::string > v) inline protected inherited
Definition at line 131 of file _GTestFairToolsNew.cxx.
References FairCaptureOutput::GetCaptureLine(), and FairCaptureOutput::GetNumberOfLines().
{
       int noLines = handler.GetNumberOfLines();
       int expectedNumberOfLines = v.size();
       EXPECT_EQ(expectedNumberOfLines,noLines);
       int minLines = std::min(expectedNumberOfLines,noLines);
       for (int i = 0; i < minLines; ++i) {
         EXPECT_EQ( v[i], handler.GetCaptureLine(i) );
       }
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckScreenOutput (std::vector< std::string > v) inline protected inherited
Definition at line 137 of file _GTestFairTools.cxx.
References FairTestNewOutputHandler::GetCaptureLine(), and FairTestNewOutputHandler::GetNumberOfLines().
{
       int noLines = handler.GetNumberOfLines();
       int expectedNumberOfLines = v.size();
       EXPECT_EQ(expectedNumberOfLines,noLines);
       int minLines = std::min(expectedNumberOfLines,noLines);
       for (int i = 0; i < minLines; ++i) {
         EXPECT_EQ( v[i], handler.GetCaptureLine(i) );
       }
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckScreenOutput (FairCaptureOutput handler, std::vector< std::string > v) inline protected inherited
Definition at line 138 of file _TestFairTools.cxx.
References FairCaptureOutput::GetCaptureLine(), and FairCaptureOutput::GetNumberOfLines().
{
       int noLines = handler.GetNumberOfLines();
       int expectedNumberOfLines = v.size();
       EXPECT_EQ(expectedNumberOfLines,noLines);
       int minLines = std::min(expectedNumberOfLines,noLines);
       for (int i = 0; i < minLines; ++i) {
         EXPECT_EQ( v[i], handler.GetCaptureLine(i) );
       }
     }
bool _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verboseLevel, std::string resultString) inline protected inherited
Definition at line 155 of file _GTestFairToolsNew.cxx.
{
       // Example Output for logging level INFO and different verbosity levels
       // verbosity Level:Output
       // LOW    :[INFO   ] I am here.
       // MEDIUM :[INFO   ] [_TestFairTools.cxx::LogNoArguments:78] I am here.
       // HIGH   :[INFO   ] [05.12.2011 12:00:10] [_TestFairTools.cxx::LogNoArguments:78] I am here.
       std::string regexString = "\\[" + logLevel + "[ ]*][ ]";
       if (verboseLevel.compare("HIGH") == 0) {
         regexString = regexString + "\\[\\d{2}\\.\\d{2}\\.\\d{4}[ ]\\d{2}:\\d{2}:\\d{2}][ ]";
         regexString = regexString + "\\[.*::.*:\\d{2}][ ]";
       }
       if (verboseLevel.compare("MEDIUM") == 0) {
         regexString = regexString + "\\[.*::.*:\\d{2}][ ]";
       }
       regexString = regexString + outputString + ".*";
       const boost::regex e(regexString);
       return regex_match(resultString, e);
     }
bool _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verboseLevel, std::string resultString) inline protected inherited
Definition at line 162 of file _TestFairTools.cxx.
{
       // Example Output for logging level INFO and different verbosity levels
       // verbosity Level:Output
       // LOW    :[INFO   ] I am here.
       // MEDIUM :[INFO   ] [_TestFairTools.cxx::LogNoArguments:78] I am here.
       // HIGH   :[INFO   ] [05.12.2011 12:00:10] [_TestFairTools.cxx::LogNoArguments:78] I am here.
       std::string regexString = "\\[" + logLevel + "[ ]*][ ]";
       if (verboseLevel.compare("HIGH") == 0) {
         regexString = regexString + "\\[\\d{2}\\.\\d{2}\\.\\d{4}[ ]\\d{2}:\\d{2}:\\d{2}][ ]";
         regexString = regexString + "\\[.*::.*:\\d{2}][ ]";
       }
       if (verboseLevel.compare("MEDIUM") == 0) {
         regexString = regexString + "\\[.*::.*:\\d{2}][ ]";
       }
       regexString = regexString + outputString + ".*";
       const boost::regex e(regexString);
       return regex_match(resultString, e);
     }
bool _TestFairLoggerBase< testing::TestWithParam< const char * > >::CheckVerboseOutput (std::string logLevel, std::string outputString, std::string verboseLevel, std::string resultString) inline protected inherited
Definition at line 179 of file _GTestFairTools.cxx.
{
       // Example Output for logging level INFO and different verbosity levels
       // verbosity Level:Output
       // LOW    :[INFO   ] I am here.
       // MEDIUM :[INFO   ] [_TestFairTools.cxx::LogNoArguments:78] I am here.
       // HIGH   :[INFO   ] [05.12.2011 12:00:10] [_TestFairTools.cxx::LogNoArguments:78] I am here.
       std::string regexString = "\\[" + logLevel + "[ ]*][ ]";
       if (verboseLevel.compare("HIGH") == 0) {
         regexString = regexString + "\\[\\d{2}\\.\\d{2}\\.\\d{4}[ ]\\d{2}:\\d{2}:\\d{2}][ ]";
         regexString = regexString + "\\[.*::.*:\\d{2}][ ]";
       }
       if (verboseLevel.compare("MEDIUM") == 0) {
         regexString = regexString + "\\[.*::.*:\\d{2}][ ]";
       }
       regexString = regexString + outputString + ".*";
       const boost::regex e(regexString);
       return regex_match(resultString, e);
     }
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedLogLevels (std::string loglevel) inline protected inherited
Definition at line 122 of file _GTestFairToolsNew.cxx.
References TestLogs.
{
       std::vector<std::string> levelNames(TestLogs, TestLogs+8);
       std::vector<std::string>::iterator position =
         std::find(levelNames.begin(), levelNames.end(), loglevel);
       levelNames.erase(position+1, levelNames.end());
       return levelNames;
     }
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedLogLevels (std::string loglevel) inline protected inherited
Definition at line 128 of file _GTestFairTools.cxx.
References TestLogs.
{
       std::vector<std::string> levelNames(TestLogs, TestLogs+8);
       std::vector<std::string>::iterator position =
         std::find(levelNames.begin(), levelNames.end(), loglevel);
       levelNames.erase(position+1, levelNames.end());
       return levelNames;
     }
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedLogLevels (std::string loglevel) inline protected inherited
Definition at line 129 of file _TestFairTools.cxx.
References TestLogs.
{
       std::vector<std::string> levelNames(TestLogs, TestLogs+8);
       std::vector<std::string>::iterator position =
         std::find(levelNames.begin(), levelNames.end(), loglevel);
       levelNames.erase(position+1, levelNames.end());
       return levelNames;
     }
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedOutputNoArguments (std::string loglevel, std::string outString, std::string filename = "") inline protected inherited
Definition at line 91 of file _GTestFairToolsNew.cxx.
References LogString.
{
       //Put blanks to the string to have all strings the same length
       int size = loglevel.size();
       int maxsize = 7; // length of string "WARNING"
       for (int i=size; i<maxsize; i++) {
         loglevel += " ";
       }
       std::vector<std::string> levelNames(LogString, LogString+9);
       std::vector<std::string>::iterator position =
         std::find(levelNames.begin(), levelNames.end(), loglevel);
       levelNames.erase(position+1, levelNames.end());
       levelNames.erase(levelNames.begin()); // don't use FATAL loglevel in this test
       std::vector<std::string> retVal;
       std::string fullOutputString;
       std::vector<std::string>::iterator iter;
       for ( iter = levelNames.begin();
             iter < levelNames.end();
             iter++) {
         fullOutputString = "[" + *iter + "] " + outString;
         retVal.push_back(fullOutputString);
       }
       return retVal;
     }
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedOutputNoArguments (std::string loglevel, std::string outString, std::string filename = "") inline protected inherited
Definition at line 93 of file _TestFairTools.cxx.
References LogString.
{
       //Put blanks to the string to have all strings the same length
       int size = loglevel.size();
       int maxsize = 7; // length of string "WARNING"
       for (int i=size; i<maxsize; i++) {
         loglevel += " ";
       }
       std::vector<std::string> levelNames(LogString, LogString+9);
       std::vector<std::string>::iterator position =
         std::find(levelNames.begin(), levelNames.end(), loglevel);
       levelNames.erase(position+1, levelNames.end());
       levelNames.erase(levelNames.begin()); // don't use FATAL loglevel in this test
       std::vector<std::string> retVal;
       std::string fullOutputString;
       if ( filename.compare("") != 0) {
         fullOutputString = "[INFO   ] Openning log file: " + filename;
         retVal.push_back(fullOutputString);
         retVal.push_back(" ");
       }
       std::vector<std::string>::iterator iter;
       for ( iter = levelNames.begin();
             iter < levelNames.end();
             iter++) {
         fullOutputString = "[" + *iter + "] " + outString + " ";
         retVal.push_back(fullOutputString);
       }
       return retVal;
     }
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char * > >::CreateExpectedOutputNoArguments (std::string loglevel, std::string outString, std::string filename = "") inline protected inherited
Definition at line 97 of file _GTestFairTools.cxx.
References LogString.
{
       //Put blanks to the string to have all strings the same length
       int size = loglevel.size();
       int maxsize = 7; // length of string "WARNING"
       for (int i=size; i<maxsize; i++) {
         loglevel += " ";
       }
       std::vector<std::string> levelNames(LogString, LogString+9);
       std::vector<std::string>::iterator position =
         std::find(levelNames.begin(), levelNames.end(), loglevel);
       levelNames.erase(position+1, levelNames.end());
       levelNames.erase(levelNames.begin()); // don't use FATAL loglevel in this test
       std::vector<std::string> retVal;
       std::string fullOutputString;
       std::vector<std::string>::iterator iter;
       for ( iter = levelNames.begin();
             iter < levelNames.end();
             iter++) {
         fullOutputString = "[" + *iter + "] " + outString + " ";
         retVal.push_back(fullOutputString);
       }
       return retVal;
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments () inline protected inherited
Definition at line 79 of file _GTestFairToolsNew.cxx.
References DEBUG, DEBUG1, DEBUG2, DEBUG3, DEBUG4, FairLogger::endl(), ERROR, INFO, LOG, and WARNING.
{
       // Log same message for all log levels
       LOG(ERROR) << OutputString.c_str() << FairLogger::endl;
       LOG(WARNING) << OutputString.c_str() << FairLogger::endl;
       LOG(INFO) << OutputString.c_str() << FairLogger::endl;
       LOG(DEBUG) << OutputString.c_str() << FairLogger::endl;
       LOG(DEBUG1) << OutputString.c_str() << FairLogger::endl;
       LOG(DEBUG2) << OutputString.c_str() << FairLogger::endl;
       LOG(DEBUG3) << OutputString.c_str() << FairLogger::endl;
       LOG(DEBUG4) << OutputString.c_str() << FairLogger::endl;
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments (FairLogger * fLogger, std::string OutputString) inline protected inherited
Definition at line 81 of file _TestFairTools.cxx.
References FairLogger::Debug(), FairLogger::Debug1(), FairLogger::Debug2(), FairLogger::Debug3(), FairLogger::Debug4(), FairLogger::Error(), FairLogger::Info(), MESSAGE_ORIGIN, and FairLogger::Warning().
{
       // Log same message for all log levels
       fLogger->Error(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Warning(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Info(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug1(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug2(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug3(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug4(MESSAGE_ORIGIN, OutputString.c_str());
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::LogNoArguments () inline protected inherited
Definition at line 84 of file _GTestFairTools.cxx.
References FairLogger::Debug(), FairLogger::Debug1(), FairLogger::Debug2(), FairLogger::Debug3(), FairLogger::Debug4(), FairLogger::Error(), FairLogger::Info(), MESSAGE_ORIGIN, and FairLogger::Warning().
{
       // Log same message for all log levels
       fLogger->Error(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Warning(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Info(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug1(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug2(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug3(MESSAGE_ORIGIN, OutputString.c_str());
       fLogger->Debug4(MESSAGE_ORIGIN, OutputString.c_str());
     }
std::vector<std::string> _TestFairLoggerBase< testing::TestWithParam< const char * > >::ReadLinesFromFile (std::string fileName) inline protected inherited
Definition at line 149 of file _GTestFairTools.cxx.
{
       std::vector<std::string> list;
       std::string line;
       std::ifstream myfile (fileName.c_str());
       if (myfile.is_open()) {
         while ( getline (myfile,line) ) {
           list.push_back(line);
         }
         myfile.close();
       }
       return list;
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues () inline protected inherited
Definition at line 70 of file _GTestFairToolsNew.cxx.
References gLogger, FairLogger::SetLogFileLevel(), FairLogger::SetLogScreenLevel(), FairLogger::SetLogToFile(), FairLogger::SetLogToScreen(), FairLogger::SetLogVerbosityLevel(), and FairLogger::SetScreenStreamToCerr().
{
       gLogger->SetLogToScreen(true);
       gLogger->SetLogToFile(false);
       gLogger->SetLogFileLevel("INFO");
       gLogger->SetLogScreenLevel("INFO");
       gLogger->SetLogVerbosityLevel("LOW");
       gLogger->SetScreenStreamToCerr(true);
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues () inline protected inherited
Definition at line 73 of file _TestFairTools.cxx.
References FairLogger::SetLogFileLevel(), FairLogger::SetLogScreenLevel(), FairLogger::SetLogToFile(), FairLogger::SetLogToScreen(), and FairLogger::SetLogVerbosityLevel().
{
       fLogger->SetLogToScreen(true);
       fLogger->SetLogToFile(false);
       fLogger->SetLogFileLevel("INFO");
       fLogger->SetLogScreenLevel("INFO");
       fLogger->SetLogVerbosityLevel("LOW");
     }
void _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues () inline protected inherited
Definition at line 75 of file _GTestFairTools.cxx.
References FairLogger::SetLogFileLevel(), FairLogger::SetLogScreenLevel(), FairLogger::SetLogToFile(), FairLogger::SetLogToScreen(), FairLogger::SetLogVerbosityLevel(), and FairLogger::SetScreenStreamToCerr().
Referenced by SetUp(), and VerbosityLevelTest::SetUp().
{
       fLogger->SetLogToScreen(true);
       fLogger->SetLogToFile(false);
       fLogger->SetLogFileLevel("INFO");
       fLogger->SetLogScreenLevel("INFO");
       fLogger->SetLogVerbosityLevel("LOW");
       fLogger->SetScreenStreamToCerr(true);
     }
virtual void LogLevelTest::SetUp () inline protected virtual
Reimplemented from _TestFairLoggerBase< testing::TestWithParam< const char * > >.
Definition at line 186 of file _GTestFairToolsNew.cxx.
References _TestFairLoggerBase< testing::TestWithParam< const char * > >::logLevelSettingToTest, _TestFairLoggerBase< testing::TestWithParam< const char * > >::OutputString, and _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues().
{
       logLevelSettingToTest=GetParam();
       OutputString = "I am here.";
       SetFairLoggerDefaultValues();
     }
virtual void LogLevelTest::SetUp () inline protected virtual
Reimplemented from _TestFairLoggerBase< testing::TestWithParam< const char * > >.
Definition at line 193 of file _TestFairTools.cxx.
References _TestFairLoggerBase< testing::TestWithParam< const char * > >::fLogger, FairLogger::GetLogger(), _TestFairLoggerBase< testing::TestWithParam< const char * > >::logLevelSettingToTest, _TestFairLoggerBase< testing::TestWithParam< const char * > >::OutputString, and _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues().
{
       logLevelSettingToTest=GetParam();
       OutputString = "I am here.";
       fLogger = FairLogger::GetLogger();
       SetFairLoggerDefaultValues();
     }
virtual void LogLevelTest::SetUp () inline protected virtual
Reimplemented from _TestFairLoggerBase< testing::TestWithParam< const char * > >.
Definition at line 210 of file _GTestFairTools.cxx.
References _TestFairLoggerBase< testing::TestWithParam< const char * > >::fLogger, FairLogger::GetLogger(), _TestFairLoggerBase< testing::TestWithParam< const char * > >::logLevelSettingToTest, _TestFairLoggerBase< testing::TestWithParam< const char * > >::OutputString, and _TestFairLoggerBase< testing::TestWithParam< const char * > >::SetFairLoggerDefaultValues().
{
       logLevelSettingToTest=GetParam();
       OutputString = "I am here.";
       fLogger = FairLogger::GetLogger();
       SetFairLoggerDefaultValues();
     }
Member Data Documentation
FairLogger* _TestFairLoggerBase< testing::TestWithParam< const char * > >::fLogger protected inherited
Definition at line 55 of file _GTestFairTools.cxx.
Referenced by SetUp(), and VerbosityLevelTest::SetUp().
FairCaptureOutput _TestFairLoggerBase< testing::TestWithParam< const char * > >::handler protected inherited
Definition at line 53 of file _GTestFairToolsNew.cxx.
FairTestNewOutputHandler _TestFairLoggerBase< testing::TestWithParam< const char * > >::handler protected inherited
Definition at line 56 of file _GTestFairTools.cxx.
std::string _TestFairLoggerBase< testing::TestWithParam< const char * > >::logLevelSettingToTest protected inherited
Definition at line 53 of file _GTestFairTools.cxx.
Referenced by SetUp(), and VerbosityLevelTest::SetUp().
std::string _TestFairLoggerBase< testing::TestWithParam< const char * > >::OutputString protected inherited
Definition at line 54 of file _GTestFairTools.cxx.
Referenced by SetUp(), and VerbosityLevelTest::SetUp().
The documentation for this class was generated from the following files:
_GTestFairTools.cxx
_GTestFairToolsNew.cxx
_TestFairTools.cxx