FairRoot: fLmd.h File Reference
fLmd.h File Reference
#include <stdio.h>
#include "sMbs.h"
#include "f_stccomm.h"
Classes
struct sLmdControl
Macros
#define LMD__SUCCESS 0
#define LMD__FAILURE 1
#define LMD__CLOSE_ERR 3
#define GETLMD__NOFILE 2
#define GETLMD__NOLMDFILE 4
#define GETLMD__EOFILE 5
#define GETLMD__NOMORE 6
#define GETLMD__NOBUFFER 7
#define GETLMD__TOOBIG 8
#define GETLMD__OUTOF_RANGE 9
#define GETLMD__SIZE_ERROR 10
#define LMD__TIMEOUT 50
#define PUTLMD__FILE_EXIST 101
#define PUTLMD__TOOBIG 102
#define PUTLMD__OPEN_ERR 103
#define PUTLMD__EXCEED 104
#define PORT__TRANS 6000
#define PORT__STREAM 6002
Functions
sLmdControl * fLmdAllocateControl ()
uint32_t fLmdPutOpen (sLmdControl *, char *, sMbsFileHeader *, uint32_t, uint32_t, uint32_t, uint32_t)
uint32_t fLmdPutElement (sLmdControl *, sMbsHeader *)
uint32_t fLmdPutBuffer (sLmdControl *, sMbsHeader *, uint32_t)
uint32_t fLmdPutClose (sLmdControl *)
uint32_t fLmdConnectMbs (sLmdControl *, char *, uint32_t, uint32_t *)
uint32_t fLmdInitMbs (sLmdControl *, char *, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t)
uint32_t fLmdGetMbsBuffer (sLmdControl *, sMbsBufferHeader *, uint32_t, uint32_t *, uint32_t *)
uint32_t fLmdGetMbsEvent (sLmdControl *, sMbsHeader **)
uint32_t fLmdCloseMbs (sLmdControl *)
uint32_t fLmdGetOpen (sLmdControl *, char *, sMbsFileHeader *, uint32_t, uint32_t)
uint32_t fLmdGetBuffer (sLmdControl *, sMbsHeader *, uint32_t, uint32_t *, uint32_t *)
int32_t fLmdReadBuffer (sLmdControl *, char *, uint32_t)
uint32_t fLmdGetElement (sLmdControl *, uint32_t, sMbsHeader **)
uint32_t fLmdGetClose (sLmdControl *)
void fLmdPrintBufferHeader (uint32_t, sMbsBufferHeader *)
void fLmdPrintFileHeader (uint32_t, sMbsFileHeader *)
void fLmdPrintHeader (uint32_t, sMbsHeader *)
void fLmdPrintEvent (uint32_t, sMbsEventHeader *)
void fLmdPrintControl (uint32_t, sLmdControl *)
void fLmdVerbose (sLmdControl *, uint32_t)
void fLmdSwap4 (uint32_t *, uint32_t)
void fLmdSwap8 (uint64_t *, uint32_t)
void fLmdSetWrittenEndian (sLmdControl *, uint32_t)
uint32_t fLmdGetWrittenEndian (sLmdControl *)
uint32_t fLmdGetSwap (sLmdControl *)
uint64_t fLmdGetBytesWritten (sLmdControl *)
Macro Definition Documentation
#define GETLMD__EOFILE 5
Definition at line 24 of file fLmd.h.
Referenced by f_evt_get_event(), fLmdGetBuffer(), and fLmdGetElement().
#define GETLMD__NOBUFFER 7
Definition at line 26 of file fLmd.h.
Referenced by f_evt_get_event(), and fLmdGetElement().
#define GETLMD__NOFILE 2
Definition at line 22 of file fLmd.h.
Referenced by fLmdGetOpen().
#define GETLMD__NOLMDFILE 4
Definition at line 23 of file fLmd.h.
Referenced by fLmdGetBuffer(), fLmdGetOpen(), and fLmdOffsetRead().
#define GETLMD__NOMORE 6
Definition at line 25 of file fLmd.h.
Referenced by f_evt_get_event(), and fLmdGetElement().
#define GETLMD__OUTOF_RANGE 9
Definition at line 28 of file fLmd.h.
Referenced by fLmdGetElement().
#define GETLMD__SIZE_ERROR 10
Definition at line 29 of file fLmd.h.
Referenced by fLmdGetElement().
#define GETLMD__TOOBIG 8
Definition at line 27 of file fLmd.h.
Referenced by fLmdGetElement().
#define LMD__CLOSE_ERR 3
Definition at line 21 of file fLmd.h.
Referenced by fLmdGetClose().
#define LMD__FAILURE 1
Definition at line 20 of file fLmd.h.
Referenced by fLmdConnectMbs(), fLmdGetBuffer(), fLmdGetMbsBuffer(), fLmdInitMbs(), fLmdOffsetWrite(), fLmdPutBuffer(), fLmdPutClose(), and fLmdPutElement().
#define LMD__SUCCESS 0
Definition at line 19 of file fLmd.h.
Referenced by fLmdCleanup(), fLmdConnectMbs(), fLmdGetBuffer(), fLmdGetClose(), fLmdGetElement(), fLmdGetMbsBuffer(), fLmdGetMbsEvent(), fLmdGetOpen(), fLmdInitMbs(), fLmdOffsetRead(), fLmdOffsetSet(), fLmdOffsetWrite(), fLmdPutBuffer(), fLmdPutClose(), fLmdPutElement(), and fLmdPutOpen().
#define LMD__TIMEOUT 50
Definition at line 30 of file fLmd.h.
Referenced by f_evt_get_event(), and fLmdGetMbsBuffer().
#define PORT__STREAM 6002
Definition at line 36 of file fLmd.h.
Referenced by fLmdCloseMbs(), fLmdConnectMbs(), and fLmdGetMbsBuffer().
#define PORT__TRANS 6000
Definition at line 35 of file fLmd.h.
Referenced by fLmdConnectMbs().
#define PUTLMD__EXCEED 104
Definition at line 34 of file fLmd.h.
Referenced by fLmdPutBuffer(), and fLmdPutElement().
#define PUTLMD__FILE_EXIST 101
Definition at line 31 of file fLmd.h.
Referenced by fLmdPutOpen().
#define PUTLMD__OPEN_ERR 103
Definition at line 33 of file fLmd.h.
Referenced by fLmdPutOpen().
#define PUTLMD__TOOBIG 102
Definition at line 32 of file fLmd.h.
Referenced by fLmdPutElement().
Function Documentation
sLmdControl* fLmdAllocateControl ()
Definition at line 888 of file fLmd.c.
Referenced by f_evt_get_open(), and f_evt_put_open().
 {
   sLmdControl* x;
   x=(sLmdControl*)malloc(sizeof(sLmdControl));
   memset(x,0,sizeof(sLmdControl));
   return(x);
 }
uint32_t fLmdCloseMbs (sLmdControl *)
Definition at line 411 of file fLmd.c.
References f_stc_close(), f_stc_write(), fLmdCleanup(), sLmdControl::iPort, sLmdControl::iTCP, sLmdControl::iTCPowner, sLmdControl::pMbsFileHeader, PORT__STREAM, and sLmdControl::pTCP.
Referenced by f_evt_get_close().
 {
   int32_t stat;
   const char cClose[12] = "CLOSE";
   // send request buffer for stream server
   if(pLmdControl->iPort == PORT__STREAM) {
     stat=f_stc_write(cClose,12,pLmdControl->iTCP);
   }
   stat=f_stc_close(pLmdControl->pTCP);
   pLmdControl->pMbsFileHeader = NULL; // was reference only
   if(pLmdControl->iTCPowner==0) { pLmdControl->pTCP=NULL; } // was reference only
   fLmdCleanup(pLmdControl);
   return(stat);
 }
uint32_t fLmdConnectMbs (sLmdControl * , char * , uint32_t , uint32_t *)
Definition at line 330 of file fLmd.c.
References sLmdControl::cFile, f_stc_connectserver(), f_stc_read(), fLmdCleanup(), fLmdSwap4(), sMbsTransportInfo::iBuffers, sLmdControl::iBufferWords, sMbsTransportInfo::iEndian, sLmdControl::iInternBuffer, sMbsTransportInfo::iMaxBytes, sLmdControl::iPort, sMbsTransportInfo::iStreams, sLmdControl::iSwap, sLmdControl::iTCP, sLmdControl::iTCPowner, LMD__FAILURE, LMD__GET_EVENTS, LMD__SUCCESS, sLmdControl::pBuffer, PORT__STREAM, PORT__TRANS, sLmdControl::pTCP, and STC__SUCCESS.
 {
   int32_t stat;
   sMbsTransportInfo sMbs;
   if(iPort == 0) { pLmdControl->iPort=PORT__TRANS; }
   else { pLmdControl->iPort=iPort; }
   memset(pLmdControl,0,sizeof(sLmdControl));
   pLmdControl->pTCP=(struct s_tcpcomm*)malloc(sizeof(struct s_tcpcomm));
   pLmdControl->iTCPowner=1;
   if(pLmdControl->iPort==PORT__TRANS) {
     printf("fLmdConnectMbs: Connect to transport server %s port %d\n",Nodename,pLmdControl->iPort);
   }
   if(pLmdControl->iPort==PORT__STREAM) {
     printf("fLmdConnectMbs: Connect to stream server %s port %d\n",Nodename,pLmdControl->iPort);
   }
   stat=f_stc_connectserver(Nodename,pLmdControl->iPort,&pLmdControl->iTCP,pLmdControl->pTCP);
   if (stat != STC__SUCCESS) {
     printf ("fLmdConnectMbs: Error connect to %s \n",Nodename);
     fLmdCleanup(pLmdControl);
     return(LMD__FAILURE);
   }
   stat=f_stc_read((int32_t*)&sMbs, sizeof(sMbsTransportInfo),pLmdControl->iTCP,3);
   if (stat != STC__SUCCESS) {
     printf ("fLmdConnectMbs: Error read info from %s \n",Nodename);
     fLmdCleanup(pLmdControl);
     return(LMD__FAILURE);
   }
   if(sMbs.iEndian != 1) { pLmdControl->iSwap=1; }
   if(pLmdControl->iSwap) { fLmdSwap4((uint32_t*)&sMbs,sizeof(sMbsTransportInfo)/4); }
   if(sMbs.iBuffers > 1) {
     printf("fLmdConnectMbs: Event spanning not supported!\n");
     fLmdCleanup(pLmdControl);
     return(LMD__FAILURE);
   }
   if(sMbs.iStreams > 0) {
     printf("fLmdConnectMbs: MBS not in DABC mode!\n");
     fLmdCleanup(pLmdControl);
     return(LMD__FAILURE);
   }
   strcpy(pLmdControl->cFile,Nodename);
   if(iBufferBytes == LMD__GET_EVENTS) { // use internal buffer for fLmdGetMbsEvent
     pLmdControl->pBuffer = (int16_t*) malloc(sMbs.iMaxBytes);
     pLmdControl->iBufferWords=sMbs.iMaxBytes/2;
     pLmdControl->iInternBuffer=1;
   } else {
     *iBufferBytes=sMbs.iMaxBytes;
   }
   return(LMD__SUCCESS);
 }
uint32_t fLmdGetBuffer (sLmdControl * , sMbsHeader * , uint32_t , uint32_t * , uint32_t *)
Definition at line 603 of file fLmd.c.
References sLmdControl::cFile, fLmdOffsetElements(), fLmdReadBuffer(), fLmdSwap4(), GETLMD__EOFILE, GETLMD__NOLMDFILE, sLmdControl::iBufferWords, sLmdControl::iBytes, sLmdControl::iElements, sMbsFileHeader::iElements, sLmdControl::iLeftWords, sMbsFileHeader::iMaxWords, sLmdControl::iOffsetEntries, sLmdControl::iSwap, sMbsHeader::iType, sMbsHeader::iWords, LMD__FAILURE, LMD__SUCCESS, LMD__TYPE_FILE_INDEX_101_2, sLmdControl::pBuffer, sLmdControl::pMbsFileHeader, and sLmdControl::pMbsHeader.
 {
   sMbsHeader* pm;
   uint32_t elem=0,leftBytes=0, used, elem_sz;//, *ps, *pd, i,ii, size=0;
   int32_t iReturn;
   if(iBytes < pLmdControl->pMbsFileHeader->iMaxWords) {
     printf("fLmdGetBuffer: %s buffer size %d too small for %d bytes\n",
            pLmdControl->cFile,iBytes,pLmdControl->pMbsFileHeader->iMaxWords);
     return(LMD__FAILURE);
   }
   if(pMbsHeader == NULL) {
     printf("fLmdGetBuffer: Need buffer to read\n");
     return(LMD__FAILURE);
   }
   *iBytesUsed=0;
   *iElements=0;
   if(pLmdControl->iElements == pLmdControl->pMbsFileHeader->iElements) { return(GETLMD__EOFILE); }
   // Offset table
   if(pLmdControl->iOffsetEntries) { // use offsets to read elements fitting in buffer
     fLmdOffsetElements(pLmdControl,iBytes, &elem, &used);
     //printf("Read %d bytes of %d, elements %d\n",used,iBytes,elem);
     iReturn=fLmdReadBuffer(pLmdControl,(char*)pMbsHeader,used);
     if(iReturn <= 0) {
       printf("fLmdGetBuffer: EOF: %s\n",pLmdControl->cFile);
       return(GETLMD__EOFILE);
     }
     if(iReturn!=used) {
       printf("fLmdGetBuffer: LMD read error: unexpected EOF: %s %u %u\n",
              pLmdControl->cFile, iReturn, used);
       return(GETLMD__NOLMDFILE);
     }
     *iBytesUsed=used;
     *iElements=elem;
     if(pLmdControl->iSwap) { fLmdSwap4((uint32_t*)pMbsHeader,iReturn/4); }
     pLmdControl->iBytes+=iReturn;
     return(LMD__SUCCESS);
   }
   // no offset table
   // do we have fragment stored?
   leftBytes = pLmdControl->iLeftWords*2;
   if(leftBytes>0) {
     if (leftBytes > iBytes) {
       printf("fLmdGetBuffer: stored piece of data (%u) larger than provided buffer (%u)\n",
              leftBytes, iBytes);
       return(LMD__FAILURE);
     }
     if (pLmdControl->pMbsHeader==0) {
       printf("fLmdGetBuffer: Internal error pMbsHeader==0\n");
       return(LMD__FAILURE);
     }
     memcpy(pMbsHeader, pLmdControl->pMbsHeader, leftBytes);
   }
   iReturn = fLmdReadBuffer(pLmdControl,(char*)pMbsHeader+leftBytes, iBytes-leftBytes);
   if(iReturn <= 0) {
     printf("fLmdGetBuffer: EOF: %s\n",pLmdControl->cFile);
     if (leftBytes>0) {
       printf("fLmdGetBuffer: EOF while we have some rest data (%u)\n", leftBytes);
     } else {
       return(GETLMD__EOFILE);
     }
   }
   if(iReturn > (iBytes-leftBytes)) {
     printf("fLmdGetBuffer: LMD read error %s - too many bytes read %u wants %u",
            pLmdControl->cFile, iReturn, iBytes-leftBytes);
     return(GETLMD__NOLMDFILE);
   }
   if(pLmdControl->iSwap) { fLmdSwap4((uint32_t*)pMbsHeader+leftBytes/4,iReturn/4); }
   pLmdControl->iBytes += iReturn;
   leftBytes += iReturn; // thats what is in the buffer
   // step through buffer to get number of elements and size
   pm=pMbsHeader;
   while(leftBytes >=8) {
     if(pm->iType == LMD__TYPE_FILE_INDEX_101_2) { break; } // file index is last
     elem_sz = (pm->iWords+4)*2;
     if(elem_sz > leftBytes) { break; } // pm valid but incomplete data
     *iBytesUsed += elem_sz;
     *iElements += 1;
     pLmdControl->iElements++;
     pm = (sMbsHeader*)((char*)pm + elem_sz);
     leftBytes -= elem_sz;
   }
   //printf("Read %d bytes of %d, elements %d\n",*iBytesUsed,iBytes,*iElements);
   // fragment left? copy to internal buffer
   if(leftBytes>0) {
     if(leftBytes > pLmdControl->iBufferWords*2) {
       printf("fLmdGetBuffer: ERROR: internal buffer overflow. Needed:%d available:%d\n",
              leftBytes,pLmdControl->iBufferWords*2);
       return(LMD__FAILURE);
     } else {
       memcpy(pLmdControl->pBuffer,pm,leftBytes);
     }
   }
   pLmdControl->iLeftWords = leftBytes/2;
   if (pLmdControl->iLeftWords>0) {
     pLmdControl->pMbsHeader = (sMbsHeader*)pLmdControl->pBuffer;
   } else {
     pLmdControl->pMbsHeader = 0;
   }
   return(LMD__SUCCESS);
 }
uint64_t fLmdGetBytesWritten (sLmdControl *)
Definition at line 825 of file fLmd.c.
References sLmdControl::iBufferWords, sLmdControl::iBytes, sLmdControl::iElements, sLmdControl::iLeftWords, sLmdControl::iOffsetSize, sLmdControl::pOffset4, and sLmdControl::pOffset8.
 {
   uint64_t bytes;
   bytes=pLmdControl->iBytes;
   // add pending data size in current buffer
   if(pLmdControl->iBufferWords > pLmdControl->iLeftWords) {
     bytes += (pLmdControl->iBufferWords - pLmdControl->iLeftWords)*2;
   }
   // add table size which will be written at close
   if ((pLmdControl->pOffset4!=NULL)||(pLmdControl->pOffset8!=NULL)) {
     bytes += (pLmdControl->iElements+1)*pLmdControl->iOffsetSize;
   }
   return(bytes);
 }
uint32_t fLmdGetClose (sLmdControl *)
Definition at line 797 of file fLmd.c.
References sLmdControl::fFile, fLmdCleanup(), LMD__CLOSE_ERR, and LMD__SUCCESS.
Referenced by f_evt_get_close(), fLmdGetOpen(), and fLmdPutClose().
 {
   fLmdCleanup(pLmdControl); // cleanup except fFile
   if(fclose(pLmdControl->fFile)!=0) {
     pLmdControl->fFile=NULL;
     return(LMD__CLOSE_ERR);
   }
   pLmdControl->fFile=NULL;
   return(LMD__SUCCESS);
 }
uint32_t fLmdGetElement (sLmdControl * , uint32_t , sMbsHeader **)
Definition at line 718 of file fLmd.c.
References sLmdControl::cFile, sLmdControl::fFile, fLmdOffsetGet(), fLmdReadBuffer(), fLmdSwap4(), GETLMD__EOFILE, GETLMD__NOBUFFER, GETLMD__NOMORE, GETLMD__OUTOF_RANGE, GETLMD__SIZE_ERROR, GETLMD__TOOBIG, sLmdControl::iBufferWords, sLmdControl::iBytes, sLmdControl::iElements, sMbsFileHeader::iElements, sLmdControl::iLeftWords, sLmdControl::iOffsetEntries, sLmdControl::iSwap, sMbsHeader::iWords, LMD__NO_INDEX, LMD__SUCCESS, sLmdControl::pBuffer, sLmdControl::pMbsFileHeader, and sLmdControl::pMbsHeader.
Referenced by f_evt_get_event().
 {
   sMbsHeader* pM;
   uint32_t i, evsz;//, *ps, *pd;
   int32_t iReturn;
   *event=NULL;
   if(iEvent == LMD__NO_INDEX) {
     if(pLmdControl->pBuffer==NULL) { return(GETLMD__NOBUFFER); } // internal buffer needed
     if(pLmdControl->pMbsFileHeader->iElements==0) { return(GETLMD__NOMORE); }
     // check if we need to read extra data
     if ((pLmdControl->iLeftWords < 4) ||
         (pLmdControl->pMbsHeader == 0) ||
         (pLmdControl->pMbsHeader->iWords+4 > pLmdControl->iLeftWords)) {
       // first copy old data, if it exists
       if (pLmdControl->iLeftWords > 0) {
         memmove(pLmdControl->pBuffer, pLmdControl->pMbsHeader, pLmdControl->iLeftWords*2);
 //                printf("copy to the begin rest %u bytes", pLmdControl->iLeftWords*2);
       }
       // second, try to read more bytes
       iReturn = fLmdReadBuffer(pLmdControl,
                                (char*)(pLmdControl->pBuffer+pLmdControl->iLeftWords),
                                (pLmdControl->iBufferWords-pLmdControl->iLeftWords)*2);
       if(iReturn <= 0) { printf("fLmdGetElement: EOF\n"); return(GETLMD__EOFILE); }
       if(pLmdControl->iSwap) { fLmdSwap4((uint32_t*)(pLmdControl->pBuffer+pLmdControl->iLeftWords),iReturn/4); }
       pLmdControl->iBytes += iReturn;
       pLmdControl->pMbsHeader=(sMbsHeader*)pLmdControl->pBuffer;
       pLmdControl->iLeftWords += iReturn/2;
     }
     // check if read buffer enough for event
     evsz = (pLmdControl->pMbsHeader->iWords + 4) * 2;
     if (evsz > pLmdControl->iLeftWords*2) {
       printf ("fLmdGetElement: Error, full element %u does not fit in buffer %u",
               evsz, pLmdControl->iLeftWords*2);
       return (GETLMD__TOOBIG);
     }
     pLmdControl->pMbsFileHeader->iElements--;
     pM = pLmdControl->pMbsHeader;
     pLmdControl->pMbsHeader = (sMbsHeader*) ((char*) pM + evsz);
     pLmdControl->iLeftWords -= evsz/2;
     pLmdControl->iElements++;
     *event=pM;
     return(LMD__SUCCESS);
   }
   // get indexed event
   if(pLmdControl->iOffsetEntries) {
     if(iEvent >= pLmdControl->iOffsetEntries) { return(GETLMD__OUTOF_RANGE); }
     fseeko64(pLmdControl->fFile,fLmdOffsetGet(pLmdControl,iEvent-1)*4,SEEK_SET);
     i=(fLmdOffsetGet(pLmdControl,iEvent)-fLmdOffsetGet(pLmdControl,iEvent-1));
     iReturn=fLmdReadBuffer(pLmdControl,(char*)pLmdControl->pBuffer,i*4);
     if(iReturn <= 0) {printf("fLmdGetElement: EOF\n"); return(GETLMD__EOFILE);}
     if(iReturn!=(i*4)) {
       printf("fLmdGetBuffer: LMD read error: unexpected EOF: %s\n",pLmdControl->cFile);
       return(GETLMD__EOFILE);
     }
     if(pLmdControl->iSwap) { fLmdSwap4((uint32_t*)pLmdControl->pBuffer,iReturn/4); }
     pLmdControl->pMbsHeader=(sMbsHeader*)pLmdControl->pBuffer;
     if((pLmdControl->pMbsHeader->iWords+4) != i*2) {
       printf("fLmdGetElement: Error Event %d: size from table is %d, header %d\n",
              iEvent,i/2,pLmdControl->pMbsHeader->iWords+4);
       return(GETLMD__SIZE_ERROR);
     }
     pLmdControl->iBytes+=iReturn;
     *event=pLmdControl->pMbsHeader;
     return(LMD__SUCCESS);
   } else { return(GETLMD__NOMORE); }
   // return zero if no more events
 }
uint32_t fLmdGetMbsBuffer (sLmdControl * , sMbsBufferHeader * , uint32_t , uint32_t * , uint32_t *)
Definition at line 450 of file fLmd.c.
References sLmdControl::cFile, f_stc_read(), f_stc_write(), fLmdSwap4(), sLmdControl::iBufferWords, sLmdControl::iBytes, sMbsBufferHeader::iElements, sLmdControl::iLeftWords, sMbsBufferHeader::iMaxWords, sLmdControl::iPort, sLmdControl::iSwap, sLmdControl::iTCP, sLmdControl::iTcpTimeout, sMbsBufferHeader::iType, sMbsBufferHeader::iUsedWords, LMD__FAILURE, LMD__SUCCESS, LMD__TIMEOUT, sLmdControl::pBuffer, sLmdControl::pMbsFileHeader, PORT__STREAM, STC__SUCCESS, and STC__TIMEOUT.
Referenced by fLmdGetMbsEvent().
 {
 //  sMbsHeader* pm;
   sMbsBufferHeader* pBuf;
   uint32_t usedBytes=0,leftBytes=0;//, *ps, *pd, i,ii, elem=0, size=0;
   int32_t iReturn;
   const char cRequest[12] = "GETEVT";
   leftBytes=iBytes;
   pBuf=pBuffer;
   if(pBuf == NULL) {
     pBuf=(sMbsBufferHeader*)pLmdControl->pBuffer;  // internal buffer
     leftBytes=pLmdControl->iBufferWords*2; // size of this buffer
   }
   if(pBuf == NULL) {
     printf("fLmdGetMbsBuffer: Need buffer to read\n");
     return(LMD__FAILURE);
   }
   if(leftBytes < sizeof(sMbsBufferHeader)) {
     printf("fLmdGetMbsBuffer: %s buffer size %d too small for %lx bytes\n",
            pLmdControl->cFile,leftBytes,sizeof(sMbsBufferHeader));
     return(LMD__FAILURE);
   }
   // send request buffer for stream server
   if(pLmdControl->iPort == PORT__STREAM) {
     iReturn=f_stc_write(cRequest,12,pLmdControl->iTCP);
   }
   iReturn=f_stc_read((int32_t*)pBuf,sizeof(sMbsBufferHeader),pLmdControl->iTCP,pLmdControl->iTcpTimeout);
   if(iReturn == STC__TIMEOUT) { return(LMD__TIMEOUT); }
   if(iReturn != STC__SUCCESS) { return(LMD__FAILURE); }
   if(pLmdControl->iSwap) { fLmdSwap4((uint32_t*)pBuf,sizeof(sMbsBufferHeader)/4); }
   if(leftBytes < (sizeof(sMbsBufferHeader)+2*pBuf->iUsedWords)) {
     printf("fLmdGetMbsBuffer: %s buffer size %d too small for %lx bytes\n",
            pLmdControl->cFile,leftBytes,sizeof(sMbsBufferHeader)+2*pBuf->iMaxWords);
     return(LMD__FAILURE);
   }
   usedBytes=pBuf->iUsedWords*2;
   if((pBuf->iType&0xffff) == 100) {
     iReturn=f_stc_read((int32_t*)(pBuf+1),usedBytes,pLmdControl->iTCP,-1);
   }
   if(iReturn == STC__TIMEOUT) { return(LMD__TIMEOUT); }
   if(iReturn != STC__SUCCESS) { return(LMD__FAILURE); }
   if(pLmdControl->iSwap) { fLmdSwap4((uint32_t*)(pBuf+1),usedBytes/4); }
   if(iBytesUsed != NULL) { *iBytesUsed =usedBytes+sizeof(sMbsBufferHeader); }
   if(iElements  != NULL) { *iElements  =pBuf->iElements; }
   pLmdControl->iBytes += usedBytes;
   pLmdControl->iLeftWords = usedBytes/2; // without header
   pLmdControl->pMbsFileHeader = (sMbsFileHeader*)pBuf;
   return(LMD__SUCCESS);
 }
uint32_t fLmdGetMbsEvent (sLmdControl * , sMbsHeader **)
Definition at line 427 of file fLmd.c.
References fLmdGetMbsBuffer(), sLmdControl::iElements, sLmdControl::iLeftWords, sMbsHeader::iWords, LMD__SUCCESS, sLmdControl::pBuffer, and sLmdControl::pMbsHeader.
Referenced by f_evt_get_event().
 {
   uint32_t stat;
   sMbsHeader* pM;
   *event=NULL;
   if(pLmdControl->iLeftWords == 0) { // get new buffer
     stat=fLmdGetMbsBuffer(pLmdControl,NULL,0,NULL,NULL);
     if(stat != LMD__SUCCESS) {
       return(stat);
     }
     // first event behind header:
     pLmdControl->pMbsHeader=(sMbsHeader*)(pLmdControl->pBuffer+sizeof(sMbsBufferHeader)/2);
   }
   pM=pLmdControl->pMbsHeader; // current to be returned
   pLmdControl->iLeftWords -= (pLmdControl->pMbsHeader->iWords+4);
   pLmdControl->pMbsHeader =
     (sMbsHeader*)((int16_t*)pLmdControl->pMbsHeader +
                   pLmdControl->pMbsHeader->iWords+4);
   pLmdControl->iElements++;
   *event=pM;
   return(LMD__SUCCESS);
 }
uint32_t fLmdGetOpen (sLmdControl * , char * , sMbsFileHeader * , uint32_t , uint32_t)
Definition at line 510 of file fLmd.c.
References sLmdControl::cFile, sLmdControl::cHeader, sLmdControl::fFile, fLmdCleanup(), fLmdGetClose(), fLmdOffsetRead(), fLmdPrintFileHeader(), fLmdReadBuffer(), fLmdSwap4(), fLmdSwap8(), GETLMD__NOFILE, GETLMD__NOLMDFILE, sLmdControl::iBufferWords, sLmdControl::iBytes, sMbsFileHeader::iEndian, sLmdControl::iInternHeader, sLmdControl::iLeftWords, sMbsFileHeader::iMaxWords, sLmdControl::iOffsetSize, sMbsFileHeader::iOffsetSize, sLmdControl::iSwap, sMbsFileHeader::iTableOffset, sMbsFileHeader::iType, sMbsFileHeader::iUsedWords, LMD__INDEX, LMD__INTERNAL_HEADER, LMD__SUCCESS, LMD__TYPE_FILE_HEADER_101_1, sLmdControl::pBuffer, sLmdControl::pMbsFileHeader, and sLmdControl::pMbsHeader.
Referenced by f_evt_get_open().
 {
   int32_t iReturn;
   uint32_t bufferBytes=0;//,l=0,i,h[12];
 //  lmdoff_t to;
   memset(pLmdControl,0,sizeof(sLmdControl));
   if(pBuffHead == LMD__INTERNAL_HEADER) {
     pLmdControl->pMbsFileHeader= (sMbsFileHeader*)malloc(sizeof(sMbsFileHeader));
     pLmdControl->iInternHeader=1;
   } else {
     pLmdControl->pMbsFileHeader= pBuffHead;
     pLmdControl->iInternHeader=0;
   }
   memset(pLmdControl->pMbsFileHeader,0,sizeof(sMbsFileHeader));
   // copy file name to control structure
   strcpy(pLmdControl->cFile,Filename);
   if((pLmdControl->fFile=(FILE*)fopen64(Filename,"r"))== NULL) {
     printf("fLmdGetOpen: File not found: %s\n",Filename);
     fLmdCleanup(pLmdControl);
     return(GETLMD__NOFILE);
   }
   /* read header */
   iReturn=fLmdReadBuffer(pLmdControl,
                          (char*)pLmdControl->pMbsFileHeader,
                          sizeof(sMbsFileHeader));
   if(iReturn!=sizeof(sMbsFileHeader)) {
     printf("fLmdGetOpen: LMD format error: no LMD file: %s\n",Filename);
     fLmdGetClose(pLmdControl);
     return(GETLMD__NOLMDFILE);
   }
   // check type and subtype, and endian
   if(pLmdControl->pMbsFileHeader->iEndian != 1) { pLmdControl->iSwap=1; }
   if(pLmdControl->iSwap) {
     printf("do swap !!!\n");
     fLmdSwap4((uint32_t*)pLmdControl->pMbsFileHeader,sizeof(sMbsFileHeader)/4);
     fLmdSwap8((uint64_t*)&pLmdControl->pMbsFileHeader->iTableOffset,1);
   }
   if(pLmdControl->pMbsFileHeader->iType != LMD__TYPE_FILE_HEADER_101_1) {
     printf("fLmdGetOpen: LMD format error: no LMD file: %s, type is %0x\n",
            Filename,pLmdControl->pMbsFileHeader->iType);
     fLmdGetClose(pLmdControl);
     return(GETLMD__NOLMDFILE);
   }
   if((iUseOffset == LMD__INDEX)&&(pLmdControl->pMbsFileHeader->iTableOffset > 0)) {
     // printf("fLmdGetOpen: use table in file: %s\n",Filename);
     pLmdControl->iOffsetSize=pLmdControl->pMbsFileHeader->iOffsetSize;
     iReturn=fLmdOffsetRead(pLmdControl); // read offset table
     if(iReturn != LMD__SUCCESS) {
       printf("fLmdGetOpen: Index format error: %s\n",Filename);
       fLmdGetClose(pLmdControl);
       return(iReturn);
     }
   }
   pLmdControl->iBytes+=iReturn;
   // more of header?
   if(pLmdControl->pMbsFileHeader->iUsedWords > 0) {
     // Read this additional information without swapping.
     // Could be mostly strings. Caller must know.
     pLmdControl->cHeader=malloc(pLmdControl->pMbsFileHeader->iUsedWords*2);
     iReturn=fLmdReadBuffer(pLmdControl,pLmdControl->cHeader,
                            pLmdControl->pMbsFileHeader->iUsedWords*2 );
     if(iReturn!=pLmdControl->pMbsFileHeader->iUsedWords*2) {
       printf("fLmdGetOpen: LMD format error: no LMD file: %s\n",Filename);
       fLmdGetClose(pLmdControl);
       return(GETLMD__NOLMDFILE);
     }
   }
   bufferBytes=iBytes;
   if(bufferBytes < pLmdControl->pMbsFileHeader->iMaxWords*2) {
     bufferBytes=pLmdControl->pMbsFileHeader->iMaxWords*2;
   }
   fLmdPrintFileHeader(1,pLmdControl->pMbsFileHeader);
   pLmdControl->pBuffer=(int16_t*)malloc(bufferBytes);
   pLmdControl->iBufferWords=bufferBytes/2; // will be increased if necessary
   printf("fLmdGetOpen: %s words %u\n", Filename, pLmdControl->iBufferWords);
   pLmdControl->iLeftWords = 0; // buffer empty, read with first fLmdGetElement
   pLmdControl->pMbsHeader = NULL;
   return(LMD__SUCCESS);
 }
uint32_t fLmdGetSwap (sLmdControl *)
Definition at line 864 of file fLmd.c.
References sLmdControl::iSwap.
 {
   if(pLmdControl != NULL) {
     return(pLmdControl->iSwap);
   } else { return(-1); }
 }
uint32_t fLmdGetWrittenEndian (sLmdControl *)
Definition at line 880 of file fLmd.c.
References sMbsFileHeader::iWrittenEndian, LMD__ENDIAN_UNKNOWN, and sLmdControl::pMbsFileHeader.
 {
   if(pLmdControl->pMbsFileHeader != NULL) {
     return(pLmdControl->pMbsFileHeader->iWrittenEndian);
   } else { printf("fLmdGetWrittenEndian: No file header allocated!"); }
   return(LMD__ENDIAN_UNKNOWN);
 }
uint32_t fLmdInitMbs (sLmdControl * , char * , uint32_t , uint32_t , uint32_t , uint32_t , uint32_t)
Definition at line 386 of file fLmd.c.
References sLmdControl::cFile, sLmdControl::iBufferWords, sLmdControl::iInternBuffer, sLmdControl::iPort, sLmdControl::iTCP, sLmdControl::iTCPowner, sLmdControl::iTcpTimeout, LMD__FAILURE, LMD__SUCCESS, sLmdControl::pBuffer, sLmdControl::pTCP, and s_tcpcomm::socket.
Referenced by f_evt_get_open().
 {
 //  int32_t stat;
   if(iBuffers > 1) {printf("fLmdInitMbs: Event spanning not supported!\n"); return(LMD__FAILURE);}
   if(iStreams > 0) {printf("fLmdInitMbs: MBS not in DABC mode!\n"); return(LMD__FAILURE);}
   pLmdControl->iPort=iPort;
   strcpy(pLmdControl->cFile,Nodename);
   if(pLmdControl->pBuffer == NULL) { pLmdControl->pBuffer= (int16_t*) malloc(iMaxBytes); }
   pLmdControl->iBufferWords=iMaxBytes/2;
   pLmdControl->iInternBuffer=1;
   pLmdControl->iTCP=pLmdControl->pTCP->socket;
   pLmdControl->iTcpTimeout=iTimeout;
   pLmdControl->iTCPowner=0;
   return(LMD__SUCCESS);
 }
void fLmdPrintBufferHeader (uint32_t , sMbsBufferHeader *)
Definition at line 1077 of file fLmd.c.
References sMbsBufferHeader::iBuffer, sMbsBufferHeader::iElements, sMbsBufferHeader::iMaxWords, sMbsBufferHeader::iTimeSpecNanoSec, sMbsBufferHeader::iTimeSpecSec, sMbsBufferHeader::iType, and sMbsBufferHeader::iUsedWords.
 {
   if(iVerbose) {
     if(pMbsBufferHeader) {
       printf("BfHd: # %d, DataWords:%d Type:%08x Elements:%d sec:%d.%d MaxWords:%d\n",
              pMbsBufferHeader->iBuffer,
              pMbsBufferHeader->iUsedWords,
              pMbsBufferHeader->iType,
              pMbsBufferHeader->iElements,
              pMbsBufferHeader->iTimeSpecSec,
              pMbsBufferHeader->iTimeSpecNanoSec/1000,
              pMbsBufferHeader->iMaxWords);
     }
   }
 }
void fLmdPrintControl (uint32_t , sLmdControl *)
Definition at line 1135 of file fLmd.c.
References sLmdControl::cFile, fLmdPrintEvent(), fLmdPrintFileHeader(), sLmdControl::iBufferWords, sLmdControl::iBytes, sLmdControl::iElements, sLmdControl::iLeftWords, sLmdControl::pMbsFileHeader, and sLmdControl::pMbsHeader.
 {
   if(iVerbose) {
     printf("Ctrl: file:%s words:%d left:%d bytes read:%lld elements:%d\n",
            pLmdControl->cFile,
            pLmdControl->iBufferWords,
            pLmdControl->iLeftWords,
            pLmdControl->iBytes,
            pLmdControl->iElements
           );
     fLmdPrintFileHeader(iVerbose,pLmdControl->pMbsFileHeader);
     fLmdPrintEvent(iVerbose,(sMbsEventHeader*)pLmdControl->pMbsHeader);
   }
 }
void fLmdPrintEvent (uint32_t , sMbsEventHeader *)
Definition at line 1122 of file fLmd.c.
References sMbsEventHeader::iEventNumber, sMbsEventHeader::iTrigger, sMbsEventHeader::iType, and sMbsEventHeader::iWords.
Referenced by fLmdPrintControl().
 {
   if(iVerbose) {
     if(pMbsEventHeader) {
       printf("EvHd: words:%6d type:%08x trigger:%2d #:%4d\n",
              pMbsEventHeader->iWords,
              pMbsEventHeader->iType,
              pMbsEventHeader->iTrigger>>16,
              pMbsEventHeader->iEventNumber);
     }
   }
 }
void fLmdPrintFileHeader (uint32_t , sMbsFileHeader *)
Definition at line 1093 of file fLmd.c.
References sMbsFileHeader::iElements, sMbsFileHeader::iMaxWords, sMbsFileHeader::iOffsetSize, sMbsFileHeader::iTableOffset, sMbsFileHeader::iTimeSpecNanoSec, sMbsFileHeader::iTimeSpecSec, sMbsFileHeader::iType, and sMbsFileHeader::iUsedWords.
Referenced by fLmdGetOpen(), and fLmdPrintControl().
 {
   if(iVerbose) {
     if(pMbsFileHeader) {
       printf("FiHd: DataWords:%d Type:%d.%d Elements:%d sec:%d.%d MaxWords:%d Index: %llx[%d]\n",
              pMbsFileHeader->iUsedWords,
              pMbsFileHeader->iType&0xffff,
              pMbsFileHeader->iType>>16,
              pMbsFileHeader->iElements,
              pMbsFileHeader->iTimeSpecSec,
              pMbsFileHeader->iTimeSpecNanoSec/1000,
              pMbsFileHeader->iMaxWords,
              pMbsFileHeader->iTableOffset,
              pMbsFileHeader->iOffsetSize);
     }
   }
 }
void fLmdPrintHeader (uint32_t , sMbsHeader *)
Definition at line 1111 of file fLmd.c.
References sMbsHeader::iType, and sMbsHeader::iWords.
 {
   if(iVerbose) {
     if(pMbsHeader) {
       printf("ElHd: words:%d type:%08x\n",
              pMbsHeader->iWords,
              pMbsHeader->iType);
     }
   }
 }
uint32_t fLmdPutBuffer (sLmdControl * , sMbsHeader * , uint32_t)
Definition at line 246 of file fLmd.c.
References fLmdOffsetSet(), fLmdWriteBuffer(), sLmdControl::iBytes, sLmdControl::iElements, sMbsFileHeader::iElements, sMbsFileHeader::iMaxWords, sLmdControl::iOffsetEntries, sLmdControl::iOffsetSize, sMbsHeader::iWords, LMD__FAILURE, LMD__SUCCESS, sLmdControl::pMbsFileHeader, and PUTLMD__EXCEED.
Referenced by f_evt_put_buffer().
 {
   sMbsHeader* pH;
   uint32_t Bytes=0,TotalBytes=0,i, elements;
   int64_t fileleft,used;
   int32_t iReturn;
   // check if total buffer fits in file
   if(pLmdControl->iOffsetEntries && (pLmdControl->iOffsetSize == 4)) {
     pH=pHeader; // SL 16.11.2009 - pH was not initialized in this branch
     elements=pLmdControl->iElements+Items+2;
     used=pLmdControl->iBytes/4;
     fileleft=0xffffffff - used - (4+elements); // size of table
     for(i=0; i<Items; i++) {
       Bytes = (4+pH->iWords)*2;
       TotalBytes += Bytes;
       pH=(sMbsHeader*)((int16_t*)pH + Bytes/2);
     }
     if((int64_t)TotalBytes/4 > fileleft) {
       printf("fLmdPutElement: File size exceed\n");
       return(PUTLMD__EXCEED);
     }
     Bytes=0;
     TotalBytes=0;
   }
   pH=pHeader;
   for(i=0; i<Items; i++) {
     pLmdControl->iElements++;
     Bytes = (4+pH->iWords)*2;
     TotalBytes += Bytes;
     if(pLmdControl->iOffsetEntries) { fLmdOffsetSet(pLmdControl,Bytes/4); }
     if((pH->iWords+4) > pLmdControl->pMbsFileHeader->iMaxWords) {
       pLmdControl->pMbsFileHeader->iMaxWords=pH->iWords+4;
     }
     pH=(sMbsHeader*)((int16_t*)pH+Bytes/2);
   }
   iReturn=fLmdWriteBuffer(pLmdControl,(char*)pHeader,TotalBytes);
   pLmdControl->iBytes+=iReturn;
   if(iReturn != TotalBytes) { return(LMD__FAILURE); }
   else {
     pLmdControl->pMbsFileHeader->iElements += Items;
     return(LMD__SUCCESS);
   }
 }
uint32_t fLmdPutClose (sLmdControl *)
Definition at line 296 of file fLmd.c.
References sLmdControl::fFile, fLmdCleanup(), fLmdGetClose(), fLmdOffsetWrite(), fLmdWriteBuffer(), sLmdControl::iBufferWords, sLmdControl::iBytes, sLmdControl::iLeftWords, sLmdControl::iOffsetEntries, sMbsFileHeader::iTableOffset, LMD__FAILURE, LMD__SUCCESS, sLmdControl::pBuffer, and sLmdControl::pMbsFileHeader.
Referenced by f_evt_put_close().
 {
   int32_t iReturn;//,i;
 //  lmdoff_t current,c;
   if(pLmdControl->iBufferWords > pLmdControl->iLeftWords) { // write last buffer
     iReturn=fLmdWriteBuffer(pLmdControl, (char*)pLmdControl->pBuffer,
                             (pLmdControl->iBufferWords-pLmdControl->iLeftWords)*2);
     pLmdControl->iBytes+=iReturn;
     if(iReturn != (pLmdControl->iBufferWords-pLmdControl->iLeftWords)*2) {
       printf("fLmdPutClose: Error writing last buffer. Closing file.\n");
       // rewind file and rewrite header
       rewind(pLmdControl->fFile);  /* rewind file, rewrite header */
       fLmdWriteBuffer(pLmdControl, (char*)pLmdControl->pMbsFileHeader,
                       sizeof(sMbsFileHeader));
       fLmdCleanup(pLmdControl);
       return(LMD__FAILURE);
     }
   }
   if(pLmdControl->iOffsetEntries)
     if(fLmdOffsetWrite(pLmdControl) != LMD__SUCCESS) {
       pLmdControl->pMbsFileHeader->iTableOffset=0;  // table could not be written
     }
   // rewind file and rewrite header
   rewind(pLmdControl->fFile);  /* rewind file, rewrite header */
   fLmdWriteBuffer(pLmdControl, (char*)pLmdControl->pMbsFileHeader,
                   sizeof(sMbsFileHeader));
   return(fLmdGetClose(pLmdControl));
 }
uint32_t fLmdPutElement (sLmdControl * , sMbsHeader *)
Definition at line 185 of file fLmd.c.
References fLmdOffsetSet(), fLmdWriteBuffer(), sLmdControl::iBufferWords, sLmdControl::iBytes, sLmdControl::iElements, sMbsFileHeader::iElements, sLmdControl::iLeftWords, sMbsFileHeader::iMaxWords, sLmdControl::iOffsetEntries, sLmdControl::iOffsetSize, sMbsHeader::iWords, LMD__FAILURE, LMD__SUCCESS, sLmdControl::pBuffer, sLmdControl::pMbsFileHeader, sLmdControl::pMbsHeader, PUTLMD__EXCEED, and PUTLMD__TOOBIG.
Referenced by f_evt_put_event().
 {
   uint32_t* ps, *pd, i, elements;
   int64_t fileleft,used;
   int32_t iReturn;
   // enough space left?
   if(pLmdControl->iOffsetEntries && (pLmdControl->iOffsetSize == 4)) {
     elements=pLmdControl->iElements+2;
     used=pLmdControl->iBytes/4;
     fileleft=0xffffffff - used - (4+elements); // size of table
     if((int64_t)(pHeader->iWords/2+2) > fileleft) {
       printf("fLmdPutElement: File size exceed\n");
       return(PUTLMD__EXCEED);
     }
   }
   // save largest size in header
   if((pHeader->iWords+4) > pLmdControl->pMbsFileHeader->iMaxWords) {
     pLmdControl->pMbsFileHeader->iMaxWords=pHeader->iWords+4;
   }
   // no buffer, write element directly
   if(pLmdControl->iBufferWords == 0) {
     pLmdControl->pMbsHeader=pHeader;
     iReturn=fLmdWriteBuffer(pLmdControl,(char*)pHeader,(pHeader->iWords+4)*2);
     pLmdControl->iBytes+=iReturn;
     if(iReturn != (pHeader->iWords+4)*2) {
       printf("fLmdPutElement: Write error \n");
       return(LMD__FAILURE);
     }
     pLmdControl->pMbsFileHeader->iElements++;
     pLmdControl->iElements++;
     if(pLmdControl->iOffsetEntries) { fLmdOffsetSet(pLmdControl,iReturn/4); }
     return(LMD__SUCCESS);
   } // end no buffer
   if((pHeader->iWords+4) > pLmdControl->iLeftWords) { // flash buffer to file
     iReturn=fLmdWriteBuffer(pLmdControl, (char*)pLmdControl->pBuffer,
                             (pLmdControl->iBufferWords-pLmdControl->iLeftWords)*2);
     pLmdControl->iBytes+=iReturn;
     if(iReturn != (pLmdControl->iBufferWords-pLmdControl->iLeftWords)*2) { return(LMD__FAILURE); }
     pLmdControl->iLeftWords=pLmdControl->iBufferWords; // buffer free
   }
   if((pHeader->iWords+4) > pLmdControl->iLeftWords) { // element too big for buffer
     printf("fLmdPutElement: Element too big: %d words\n",pHeader->iWords+4);
     return(PUTLMD__TOOBIG);
   }
   // copy to buffer
   ps=(uint32_t*)pHeader;
   pd=(uint32_t*)pLmdControl->pBuffer+(pLmdControl->iBufferWords-pLmdControl->iLeftWords)/2;
   iReturn=(pHeader->iWords+4)/2; // here 32b words
   for(i=0; i<iReturn; i++) { *pd++ = *ps++; }
   pLmdControl->pMbsFileHeader->iElements++;
   pLmdControl->iElements++;
   pLmdControl->iLeftWords -= (pHeader->iWords+4);
   if(pLmdControl->iOffsetEntries) { fLmdOffsetSet(pLmdControl,iReturn); }
   return(LMD__SUCCESS);
 }
uint32_t fLmdPutOpen (sLmdControl * , char * , sMbsFileHeader * , uint32_t , uint32_t , uint32_t , uint32_t)
Definition at line 113 of file fLmd.c.
References sLmdControl::cFile, sLmdControl::fFile, fLmdCleanup(), fLmdOffsetResize(), fLmdWriteBuffer(), sLmdControl::iBufferWords, sLmdControl::iBytes, sMbsFileHeader::iEndian, sLmdControl::iInternBuffer, sLmdControl::iInternHeader, sLmdControl::iLeftWords, sLmdControl::iOffsetSize, sMbsFileHeader::iOffsetSize, sMbsFileHeader::iTimeSpecNanoSec, sMbsFileHeader::iTimeSpecSec, sMbsFileHeader::iType, sMbsFileHeader::iUsedWords, LMD__INDEX, LMD__LARGE_FILE, LMD__NO_OVERWRITE, LMD__STANDARD_HEADER, LMD__SUCCESS, LMD__TYPE_FILE_HEADER_101_1, sLmdControl::pBuffer, sLmdControl::pMbsFileHeader, PUTLMD__FILE_EXIST, and PUTLMD__OPEN_ERR.
Referenced by f_evt_put_open().
 {
   int32_t iReturn;
   struct timespec clock;
   memset(pLmdControl,0,sizeof(sLmdControl));
   // allocate header or take extern
   if(pBuffHead == LMD__STANDARD_HEADER) {
     pLmdControl->pMbsFileHeader= (sMbsFileHeader*)malloc(sizeof(sMbsFileHeader));
     memset(pLmdControl->pMbsFileHeader,0,sizeof(sMbsFileHeader));
     pLmdControl->iInternHeader=1;
   } else {
     pLmdControl->pMbsFileHeader= pBuffHead;
     pLmdControl->iInternHeader=0;
   }
   clock_gettime(CLOCK_REALTIME,&clock);
   pLmdControl->pMbsFileHeader->iTimeSpecSec=clock.tv_sec;
   pLmdControl->pMbsFileHeader->iTimeSpecNanoSec=clock.tv_nsec;
   pLmdControl->pMbsFileHeader->iType=LMD__TYPE_FILE_HEADER_101_1;
   pLmdControl->pMbsFileHeader->iEndian=1;
   strcpy(pLmdControl->cFile,Filename);
   // optionally allocate buffer
   if(iBytes > 0) {
     pLmdControl->pBuffer=(int16_t*)malloc(iBytes);
     pLmdControl->iInternBuffer=1;
   }
   pLmdControl->iBufferWords=iBytes/2;
   pLmdControl->iLeftWords=iBytes/2;
   // open file
   if(iOver == LMD__NO_OVERWRITE) { // do not overwrite
     if((pLmdControl->fFile=(FILE*)fopen64(Filename,"r") )!=NULL) {
       printf("fLmdPutOpen: File exists: %s\n",Filename);
       fLmdCleanup(pLmdControl);
       fclose(pLmdControl->fFile);
       return(PUTLMD__FILE_EXIST);
     }
   }
   if((pLmdControl->fFile=(FILE*)fopen64(Filename,"w+") )== NULL) {
     printf("fLmdPutOpen: Error open file %s\n",Filename);
     fLmdCleanup(pLmdControl);
     return(PUTLMD__OPEN_ERR);
   }
   if(iLargeFile == LMD__LARGE_FILE) { pLmdControl->iOffsetSize=8; }
   else { pLmdControl->iOffsetSize=4; }
   pLmdControl->pMbsFileHeader->iOffsetSize=pLmdControl->iOffsetSize;
   // write header
   iReturn=fLmdWriteBuffer(pLmdControl,(char*)pLmdControl->pMbsFileHeader,
                           (pLmdControl->pMbsFileHeader->iUsedWords)*2+sizeof(sMbsFileHeader));
   pLmdControl->iBytes+=iReturn;
   if(iUseOffset == LMD__INDEX) { fLmdOffsetResize(pLmdControl,iReturn/4); } // create and set first value
   printf("fLmdPutOpen: %s. Bytes:%d over:%d table:%d large:%d.\n",
          Filename,iBytes,iOver,iUseOffset,iLargeFile);
   return(LMD__SUCCESS);
 }
int32_t fLmdReadBuffer (sLmdControl * , char * , uint32_t)
Definition at line 808 of file fLmd.c.
References sLmdControl::fFile.
Referenced by fLmdGetBuffer(), fLmdGetElement(), fLmdGetOpen(), and fLmdOffsetRead().
 {
   int32_t IObytes;
   IObytes=(int32_t)fread(buffer,1,bytes,pLmdControl->fFile);
   //if(IObytes < bytes) printf("Read %s: request %d bytes, got %d\n",pLmdControl->cFile,bytes,IObytes);
   return(IObytes);
 }
void fLmdSetWrittenEndian (sLmdControl * , uint32_t)
Definition at line 872 of file fLmd.c.
References sMbsFileHeader::iWrittenEndian, and sLmdControl::pMbsFileHeader.
 {
   if(pLmdControl->pMbsFileHeader != NULL) {
     pLmdControl->pMbsFileHeader->iWrittenEndian=iE;
   } else { printf("fLmdSetWrittenEndian: No file header allocated!"); }
 }
void fLmdSwap4 (uint32_t * , uint32_t)
Definition at line 1150 of file fLmd.c.
Referenced by fLmdConnectMbs(), fLmdGetBuffer(), fLmdGetElement(), fLmdGetMbsBuffer(), fLmdGetOpen(), and fLmdOffsetRead().
 {
   uint32_t i, *pp;
   pp=array;
   for(i=0; i<items; i++) {
     //printf("Swap 4 %08x ",*pp);
     *pp =
       (*pp >> 24) +
       ((*pp >>  8)&0x0000ff00) +
       ((*pp <<  8)&0x00ff0000) +
       (*pp << 24);
     //printf("to %08x \n",*pp);
     pp++;
   }
 }
void fLmdSwap8 (uint64_t * , uint32_t)
Definition at line 1166 of file fLmd.c.
Referenced by fLmdGetOpen(), and fLmdOffsetRead().
 {
   uint64_t* pp;
   uint32_t i;//,x;
   pp=array;
   for(i=0; i<items; i++) {
     //printf("Swap 8 %016llx ",*pp);
     *pp = (*pp << 32) + (*pp >> 32);
     //printf("to %016llx\n",*pp,*(pp+1));
     pp++;
   }
 }
void fLmdVerbose (sLmdControl * , uint32_t)