FairRroot: runSink.cxx File Reference
runSink.cxx File Reference
#include <iostream>
#include <csignal>
#include "boost/program_options.hpp"
#include "FairMQLogger.h"
#include "FairMQSink.h"
#include "FairMQTransportFactoryZMQ.h"
Classes
struct DeviceOptions
Typedefs
typedef struct DeviceOptions DeviceOptions_t
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
bool parse_cmd_line (int _argc, char *_argv[], DeviceOptions *_options)
int main (int argc, char **argv)
Variables
FairMQSink sink
Typedef Documentation
typedef struct DeviceOptions DeviceOptions_t
Function Documentation
int main (int argc, char ** argv)
Definition at line 112 of file runSink.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, ERROR, FairMQStateMachine::fRunningCondition, FairMQStateMachine::fRunningFinished, FairMQStateMachine::fRunningMutex, FairMQDevice::Id, DeviceOptions::id, INFO, FairMQStateMachine::INIT, FairMQDevice::InputAddress, DeviceOptions::inputAddress, DeviceOptions::inputBufSize, FairMQDevice::InputMethod, DeviceOptions::inputMethod, FairMQDevice::InputRcvBufSize, FairMQDevice::InputSocketType, DeviceOptions::inputSocketType, DeviceOptions::ioThreads, LOG, FairMQDevice::NumInputs, FairMQDevice::NumIoThreads, FairMQDevice::NumOutputs, parse_cmd_line(), FairMQStateMachine::RUN, s_catch_signals(), FairMQStateMachine::SETINPUT, FairMQStateMachine::SETOUTPUT, FairMQDevice::SetProperty(), FairMQDevice::SetTransport(), and FairMQStateMachine::STOP.
 {
     s_catch_signals();
     DeviceOptions_t options;
     try
     {
         if (!parse_cmd_line(argc, argv, &options))
             return 0;
     }
     catch (exception& e)
     {
         LOG(ERROR) << e.what();
         return 1;
     }
     LOG(INFO) << "PID: " << getpid();
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     sink.SetTransport(transportFactory);
     sink.SetProperty(FairMQSink::Id, options.id);
     sink.SetProperty(FairMQSink::NumIoThreads, options.ioThreads);
     sink.SetProperty(FairMQSink::NumInputs, 1);
     sink.SetProperty(FairMQSink::NumOutputs, 0);
     sink.ChangeState(FairMQSink::INIT);
     sink.SetProperty(FairMQSink::InputSocketType, options.inputSocketType);
     sink.SetProperty(FairMQSink::InputRcvBufSize, options.inputBufSize);
     sink.SetProperty(FairMQSink::InputMethod, options.inputMethod);
     sink.SetProperty(FairMQSink::InputAddress, options.inputAddress);
     sink.ChangeState(FairMQSink::SETOUTPUT);
     sink.ChangeState(FairMQSink::SETINPUT);
     sink.ChangeState(FairMQSink::RUN);
     // wait until the running thread has finished processing.
     boost::unique_lock<boost::mutex> lock(sink.fRunningMutex);
     while (!sink.fRunningFinished)
     {
         sink.fRunningCondition.wait(lock);
     }
     sink.ChangeState(FairMQSink::STOP);
     sink.ChangeState(FairMQSink::END);
     return 0;
 }
bool parse_cmd_line (int _argc, char * _argv[], DeviceOptions * _options) inline
Definition at line 64 of file runSink.cxx.
References DeviceOptions::id, INFO, DeviceOptions::inputAddress, DeviceOptions::inputBufSize, DeviceOptions::inputMethod, DeviceOptions::inputSocketType, DeviceOptions::ioThreads, and LOG.
Referenced by main().
 {
     if (_options == NULL)
         throw std::runtime_error("Internal error: options' container is empty.");
     namespace bpo = boost::program_options;
     bpo::options_description desc("Options");
     desc.add_options()
         ("id", bpo::value<string>()->required(), "Device ID")
         ("io-threads", bpo::value<int>()->default_value(1), "Number of I/O threads")
         ("input-socket-type", bpo::value<string>()->required(), "Input socket type: sub/pull")
         ("input-buff-size", bpo::value<int>()->required(), "Input buffer size in number of messages (ZeroMQ)/bytes(nanomsg)")
         ("input-method", bpo::value<string>()->required(), "Input method: bind/connect")
         ("input-address", bpo::value<string>()->required(), "Input address, e.g.: \"tcp://*:5555\"")
         ("help", "Print help messages");
     bpo::variables_map vm;
     bpo::store(bpo::parse_command_line(_argc, _argv, desc), vm);
     if ( vm.count("help") )
     {
         LOG(INFO) << "FairMQ Sink" << endl << desc;
         return false;
     }
     bpo::notify(vm);
     if ( vm.count("id") )
         _options->id = vm["id"].as<string>();
     if ( vm.count("io-threads") )
         _options->ioThreads = vm["io-threads"].as<int>();
     if ( vm.count("input-socket-type") )
         _options->inputSocketType = vm["input-socket-type"].as<string>();
     if ( vm.count("input-buff-size") )
         _options->inputBufSize = vm["input-buff-size"].as<int>();
     if ( vm.count("input-method") )
         _options->inputMethod = vm["input-method"].as<string>();
     if ( vm.count("input-address") )
         _options->inputAddress = vm["input-address"].as<string>();
     return true;
 }
static void s_catch_signals (void) static
Definition at line 44 of file runSink.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 33 of file runSink.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, and FairMQStateMachine::STOP.
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     sink.ChangeState(FairMQSink::STOP);
     sink.ChangeState(FairMQSink::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
FairMQSink sink
Definition at line 31 of file runSink.cxx.