FairRroot: TimeGap Class Reference
TimeGap Class Reference
#include <FairTSBufferFunctional.h>
Public Member Functions
TimeGap ()
bool Call (FairTimeStamp *a, double b)
virtual bool operator() (FairTimeStamp *a, double b)
virtual bool TimeOut ()
virtual void ResetTimeOut ()
Private Attributes
double fOldTime
Detailed Description
Returns you all the data between two time gaps of a given length.
Definition at line 103 of file FairTSBufferFunctional.h.
Constructor & Destructor Documentation
TimeGap::TimeGap () inline
Definition at line 106 of file FairTSBufferFunctional.h.
 :fOldTime(-1.) {};
Member Function Documentation
bool TimeGap::Call (FairTimeStamp * a, double b) inline virtual
b : TimeGap: All data between two time gaps which are larger than TimeGap are returned
Implements BinaryFunctor.
Definition at line 112 of file FairTSBufferFunctional.h.
References fOldTime, and FairTimeStamp::GetTimeStamp().
{
       double aTime = a->GetTimeStamp();
       if (fOldTime < 0) {
         fOldTime = aTime;
         return false;
       }
       if (aTime - fOldTime > b) {
         fOldTime = aTime;
         return true;
       } else {
         fOldTime = aTime;
         return false;
       }
     };
virtual bool BinaryFunctor::operator() (FairTimeStamp * a, double b) inline virtual inherited
Definition at line 41 of file FairTSBufferFunctional.h.
References BinaryFunctor::Call().
 {return Call(a,b);};
virtual void BinaryFunctor::ResetTimeOut () inline virtual inherited
Reimplemented in StopTime.
Definition at line 44 of file FairTSBufferFunctional.h.
 {};
virtual bool BinaryFunctor::TimeOut () inline virtual inherited
Reimplemented in StopTime.
Definition at line 43 of file FairTSBufferFunctional.h.
Referenced by FairTSBufferFunctional::TimeOut().
 {return false;}
Member Data Documentation
double TimeGap::fOldTime private
Definition at line 126 of file FairTSBufferFunctional.h.
Referenced by Call().
The documentation for this class was generated from the following file:
FairTSBufferFunctional.h