# - Try to find GEANT4 data files
#


MESSAGE(STATUS "Looking for GEANT4 DATA files...")

FIND_PATH(GEANT4_DATA NAMES G4PII  PATHS
  ${SIMPATH}/transport/data/geant4/
  ${SIMPATH}/share/data/geant4
  NO_DEFAULT_PATH
)

FIND_PATH(G4LEDATA NAMES README  PATHS
  ${GEANT4_DATA}/G4EMLOW/
  NO_DEFAULT_PATH
)
SET(G4LEDATA ${G4LEDATA})

FIND_PATH(G4LEVELGAMMADATA  NAMES README-LevelGammaData PATHS
  ${GEANT4_DATA}/PhotonEvaporation/
  NO_DEFAULT_PATH
)
SET(G4LEVELGAMMADATA   ${G4LEVELGAMMADATA})


FIND_PATH(G4NeutronHPCrossSections NAMES README  PATHS
  ${GEANT4_DATA}/G4NDL/
  NO_DEFAULT_PATH
)
SET(G4NeutronHPCrossSections ${G4NeutronHPCrossSections})
SET(G4NEUTRONHPDATA ${G4NeutronHPCrossSections})


FIND_PATH(G4NEUTRONXSDATA NAMES cap1  PATHS
  ${GEANT4_DATA}/G4NEUTRONXS/
  NO_DEFAULT_PATH
)
SET(G4NEUTRONXSDATA ${G4NEUTRONXSDATA})


FIND_PATH(G4PIIDATA NAMES PIXE_DataLibrary.pdf PATHS
  ${GEANT4_DATA}/G4PII/
  NO_DEFAULT_PATH
)
SET(G4PIIDATA ${G4PIIDATA})


FIND_PATH(G4RADIOACTIVEDATA NAMES README_RDM PATHS
  ${GEANT4_DATA}/RadioactiveDecay/
  NO_DEFAULT_PATH
)
SET(G4RADIOACTIVEDATA ${G4RADIOACTIVEDATA})


FIND_PATH(G4REALSURFACEDATA NAMES EtchedTiO.dat PATHS
  ${GEANT4_DATA}/RealSurface/
  NO_DEFAULT_PATH
)
SET(G4REALSURFACEDATA  ${G4REALSURFACEDATA})


