FairRroot: FairGenericParRootFileIo Class Reference
FairGenericParRootFileIo Class Reference
#include <FairGenericParRootFileIo.h>
Public Member Functions
FairGenericParRootFileIo (FairParRootFile *f=0)
~FairGenericParRootFileIo ()
Bool_t init (FairParSet *)
virtual Bool_t read (FairParSet *)
Int_t write (FairParSet *)
void setInputNumber (Int_t n)
Int_t getInputNumber ()
Protected Member Functions
Int_t findInputVersion (Text_t *contName)
Int_t getMaxVersion (Text_t *contName)
TObject * findContainer (Text_t *contName, Int_t version)
Protected Attributes
FairParRootFile * pFile
Int_t inputNumber
Detailed Description
Definition at line 18 of file FairGenericParRootFileIo.h.
Constructor & Destructor Documentation
FairGenericParRootFileIo::FairGenericParRootFileIo (FairParRootFile * f = 0)
FairGenericParRootFileIo::~FairGenericParRootFileIo () inline
Definition at line 22 of file FairGenericParRootFileIo.h.
 {}
Member Function Documentation
TObject * FairDetParRootFileIo::findContainer (Text_t * contName, Int_t version) protected inherited
Definition at line 133 of file FairDetParRootFileIo.cxx.
References FairParRootFile::cd(), and FairDetParRootFileIo::pFile.
{
   // finds the parameter container given by its name with a special version in
   // the ROOT file (returns 0 if not successful)
   // This funtion uses internally the ROOT function FindObject(Text_t*), which
   // creates a new object. The calling function must therefore delete the
   // object after usage!
   Text_t cn[80];
   sprintf(cn, "%s;%i", name, vers);
   pFile->cd();
   TObject *p = gROOT->FindObject(cn);
   return p;
 }
Int_t FairDetParRootFileIo::findInputVersion (Text_t * contName) protected inherited
Definition at line 112 of file FairDetParRootFileIo.cxx.
References FairRuntimeDb::getCurrentRun(), FairParVersion::getInputVersion(), FairRtdbRun::getParVersion(), FairParVersion::getRootVersion(), FairParRootFile::getRun(), FairDetParIo::inputNumber, FairRuntimeDb::instance(), and FairDetParRootFileIo::pFile.
Referenced by FairDetParRootFileIo::read().
{
   // finds the input version to initialize the container given by name;
   // returns -1 if the version cannot be determined
   FairParVersion *currVers =
       FairRuntimeDb::instance()->getCurrentRun()->getParVersion(name);
   Int_t v = currVers->getInputVersion(inputNumber);
   if (v > 0) {
     return v;
   } // predefined
   FairRtdbRun *r = pFile->getRun();
   // cout << "-I- FairDetParRootFileIo::findInputVersion " << r << endl;
   if (!r) {
     return -1;
   } // run not in ROOT file
   FairParVersion *vers = r->getParVersion(name);
   if (!vers) {
     return -1;
   } // container not in ROOT file
   return vers->getRootVersion();
 }
Int_t FairDetParIo::getInputNumber () inline inherited
Definition at line 29 of file FairDetParIo.h.
References FairDetParIo::inputNumber.
 {return inputNumber;}
Int_t FairDetParRootFileIo::getMaxVersion (Text_t * contName) protected inherited
Definition at line 101 of file FairDetParRootFileIo.cxx.
References FairParRootFile::GetKey(), and FairDetParRootFileIo::pFile.
Referenced by FairDetParRootFileIo::write().
{
   // returns the maximum version of the container given by name in the ROOT
   // file (return -1 if not found)
   TKey *key = pFile->GetKey(name);
   if (key) {
     return key->GetCycle();
   } else {
     return -1;
   }
 }
Bool_t FairGenericParRootFileIo::init (FairParSet * pPar) virtual
Reimplemented from FairDetParIo.
Definition at line 34 of file FairGenericParRootFileIo.cxx.
References FairDetParRootFileIo::pFile, and FairDetParRootFileIo::read().
 {
   // calls FairDetParRootFileIo"::read(FairParSet*)
   if (!pFile) { return kFALSE; }
   return FairDetParRootFileIo::read(pPar);
 }
Bool_t FairDetParRootFileIo::read (FairParSet * pPar) virtual inherited
Definition at line 51 of file FairDetParRootFileIo.cxx.
References FairParSet::clear(), FairDetParRootFileIo::findInputVersion(), FairParSet::getInputVersion(), FairParSet::GetName(), FairDetParIo::inputNumber, FairParSet::setChanged(), and FairParSet::setInputVersion().
Referenced by init().
{
   // generic read function for parameter containers
   Text_t *name = (char *)pPar->GetName();
   Int_t version = findInputVersion(name);
   // cout << "-I- FairDetParRootFileIo#  " << name << " : " << version <<  endl;
   if (version <= 0) {
     pPar->setInputVersion(-1, inputNumber);
     return kFALSE;
   }
   if (pPar->getInputVersion(inputNumber) == version &&
       pPar->getInputVersion(inputNumber) != -1) {
     return kTRUE;
   }
   TKey *key = dynamic_cast<TKey *>(gDirectory->GetKey(name, version));
   if (key) {
     pPar->clear();
     key->Read(pPar);
     pPar->setInputVersion(version, inputNumber);
     pPar->setChanged();
     cout << "Container " << pPar->GetName() << " initialized from ROOT file."
          << endl;
     return kTRUE;
   }
   pPar->setInputVersion(-1, inputNumber);
   return kFALSE;
 }
void FairDetParIo::setInputNumber (Int_t n) inline inherited
Definition at line 26 of file FairDetParIo.h.
Referenced by FairParIo::setInputNumber().
 {inputNumber=n;}
Int_t FairDetParRootFileIo::write (FairParSet * pPar) virtual inherited
Reimplemented from FairDetParIo.
Definition at line 82 of file FairDetParRootFileIo.cxx.
References FairParRootFile::cd(), FairDetParRootFileIo::getMaxVersion(), FairParSet::GetName(), FairRuntimeDb::instance(), FairParRootFile::IsWritable(), FairDetParRootFileIo::pFile, FairParSet::setChanged(), and FairRuntimeDb::setVersionsChanged().
{
   // writes a parameter container to the ROOT file and returns the new version
   // number (returns -1 if the file is not writable)
   if (pFile) {
     pFile->cd();
     if (pFile->IsWritable()) {
       Text_t *name = (char *)pPar->GetName();
       pPar->Write(name);
       pPar->setChanged(kFALSE);
       FairRuntimeDb::instance()->setVersionsChanged(kTRUE);
       return getMaxVersion(name);
     } else {
       Error(":write", "Output is not writable");
     }
   }
   Error(":write", "No output open");
   return -1;
 }
Member Data Documentation
Int_t FairDetParIo::inputNumber protected inherited
Definition at line 20 of file FairDetParIo.h.
Referenced by FairDetParRootFileIo::findInputVersion(), FairDetParIo::getInputNumber(), and FairDetParRootFileIo::read().
FairParRootFile* FairDetParRootFileIo::pFile protected inherited
Definition at line 24 of file FairDetParRootFileIo.h.
Referenced by FairDetParRootFileIo::findContainer(), FairDetParRootFileIo::findInputVersion(), FairDetParRootFileIo::getMaxVersion(), init(), and FairDetParRootFileIo::write().
The documentation for this class was generated from the following files:
FairGenericParRootFileIo.h
FairGenericParRootFileIo.cxx