FairRroot: FairTutorialDet4MilleWriter Class Reference
FairTutorialDet4MilleWriter Class Reference
#include <FairTutorialDet4MilleWriter.h>
Public Member Functions
FairTutorialDet4MilleWriter ()
~FairTutorialDet4MilleWriter ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void Exec (Option_t *opt)
virtual void SetParContainers ()
virtual void Finish ()
void SetWriteAscii (Bool_t val)
void SetVersion (Int_t val)
void SetFileName (TString val)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
void ExecVersion1 (Option_t *opt)
void StraightLineShiftX (Option_t *opt)
void StraightLineShiftXY (Option_t *opt)
Bool_t IsGoodEvent ()
FairTutorialDet4MilleWriter (const FairTutorialDet4MilleWriter &)
FairTutorialDet4MilleWriter operator= (const FairTutorialDet4MilleWriter &)
ClassDef (FairTutorialDet4MilleWriter, 1)
Private Attributes
TClonesArray * fTracks
TClonesArray * fHits
Mille * fMille
Bool_t fWriteAscii
Int_t fVersion
TString fFileName
Detailed Description
Definition at line 19 of file FairTutorialDet4MilleWriter.h.
Constructor & Destructor Documentation
FairTutorialDet4MilleWriter::FairTutorialDet4MilleWriter ()
Default constructor
Definition at line 23 of file FairTutorialDet4MilleWriter.cxx.
References DEBUG, FairLogger::endl(), and LOG.
   :FairTask("FairTutorialDet4MilleWriter"),
    fTracks(),
    fHits(),
    fMille(NULL),
    fWriteAscii(kFALSE),
    fVersion(1),
    fFileName("mp2tst")
 {
   LOG(DEBUG) << "Default Constructor of FairTutorialDet4MilleWriter" << FairLogger::endl;
 }
FairTutorialDet4MilleWriter::~FairTutorialDet4MilleWriter ()
Constructor with parameters (Optional) Destructor
Definition at line 36 of file FairTutorialDet4MilleWriter.cxx.
References DEBUG, FairLogger::endl(), and LOG.
 {
   LOG(DEBUG) << "Destructor of FairTutorialDet4MilleWriter" << FairLogger::endl;
 }
FairTutorialDet4MilleWriter::FairTutorialDet4MilleWriter (const FairTutorialDet4MilleWriter &) private
Output array to new data level
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairTutorialDet4MilleWriter::ClassDef (FairTutorialDet4MilleWriter , 1) private
void FairTutorialDet4MilleWriter::Exec (Option_t * opt) virtual
Executed for each event.
Definition at line 99 of file FairTutorialDet4MilleWriter.cxx.
References fVersion, IsGoodEvent(), StraightLineShiftX(), and StraightLineShiftXY().
 {
   if (IsGoodEvent()) {
     if (1 == fVersion) { StraightLineShiftX(option); }
     if (2 == fVersion) { StraightLineShiftXY(option); }
   }
 }
void FairTutorialDet4MilleWriter::ExecVersion1 (Option_t * opt) private
void FairTutorialDet4MilleWriter::Finish () virtual
Finish task called at the end of the run
Reimplemented from FairTask.
Definition at line 293 of file FairTutorialDet4MilleWriter.cxx.
References DEBUG, FairLogger::endl(), and LOG.
 {
   LOG(DEBUG) << "Finish of FairTutorialDet4MilleWriter" << FairLogger::endl;
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
InitStatus FairTutorialDet4MilleWriter::Init () virtual
Initiliazation of task at the beginning of a run
Reimplemented from FairTask.
Definition at line 56 of file FairTutorialDet4MilleWriter.cxx.
References DEBUG, FairLogger::endl(), ERROR, fFileName, fHits, fMille, fTracks, fWriteAscii, FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kSUCCESS, and LOG.
 {
   LOG(DEBUG) << "Initilization of FairTutorialDet4MilleWriter" << FairLogger::endl;
   // Get a handle from the IO manager
   FairRootManager* ioman = FairRootManager::Instance();
   // Get a pointer to the previous already existing data level
   fTracks = (TClonesArray*) ioman->GetObject("TutorialDetTrack");
   if ( ! fTracks ) {
     LOG(ERROR) << "No InputDataLevelName array!\n FairTutorialDet4MilleWriter will be inactive" << FairLogger::endl;
     return kERROR;
   }
   // Get a pointer to the previous already existing data level
   fHits = (TClonesArray*) ioman->GetObject("TutorialDetHit");
   if ( ! fHits ) {
     LOG(ERROR) << "No InputDataLevelName array!\n FairTutorialDet4MilleWriter will be inactive" << FairLogger::endl;
     return kERROR;
   }
   //Open MillePede Output file
   if (fWriteAscii) {
     fFileName += ".ascii";
     fMille = new Mille(fFileName, false, true); // write human readable ascii file
   } else {
     fFileName += ".bin";
     fMille = new Mille(fFileName, true, false); // write binary file needed by pede
   }
   return kSUCCESS;
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
Bool_t FairTutorialDet4MilleWriter::IsGoodEvent () private
Definition at line 107 of file FairTutorialDet4MilleWriter.cxx.
References fHits, and FairHit::GetDetectorID().
Referenced by Exec().
 {
   // Check if each for the event there is maximum 1 hit per detector
   // station. In the moment we create tracks with all hits in the
   // event, so we have to check for this.
   // In the end the algorithm should be able to work also with
   // missing hits in some stations
   FairTutorialDet4Hit* hit;
   std::set<Int_t> detIdSet;
   std::set<Int_t>::iterator it;
   Int_t nHits = fHits->GetEntriesFast();
   for (Int_t iHit=0; iHit<nHits; ++iHit) {
     hit = (FairTutorialDet4Hit*) fHits->At(iHit);
     Int_t detId = hit->GetDetectorID();
     it = detIdSet.find(detId);
     if ( it == detIdSet.end() ) {
       detIdSet.insert(detId);
     } else {
       // find hit in already used detector station
       // this is not a good event
       return kFALSE;
     }
   }
   return kTRUE;
 }
FairTutorialDet4MilleWriter FairTutorialDet4MilleWriter::operator= (const FairTutorialDet4MilleWriter &) private
InitStatus FairTutorialDet4MilleWriter::ReInit () virtual
ReInitiliazation of task when the runID changes
Reimplemented from FairTask.
Definition at line 92 of file FairTutorialDet4MilleWriter.cxx.
References DEBUG, FairLogger::endl(), kSUCCESS, and LOG.
 {
   LOG(DEBUG) << "Initilization of FairTutorialDet4MilleWriter" << FairLogger::endl;
   return kSUCCESS;
 }
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairTutorialDet4MilleWriter::SetFileName (TString val) inline
Definition at line 54 of file FairTutorialDet4MilleWriter.h.
References fFileName.
 {fFileName = val;}
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairTutorialDet4MilleWriter::SetParContainers () virtual
Load the parameter container from the runtime database
Reimplemented from FairTask.
Definition at line 42 of file FairTutorialDet4MilleWriter.cxx.
References DEBUG, FairLogger::endl(), and LOG.
 {
   LOG(DEBUG) << "SetParContainers of FairTutorialDet4MilleWriter" << FairLogger::endl;
   // Load all necessary parameter containers from the runtime data base
   /*
   FairRunAna* ana = FairRunAna::Instance();
   FairRuntimeDb* rtdb=ana->GetRuntimeDb();
   <FairTutorialDet4MilleWriterDataMember> = (<ClassPointer>*)
     (rtdb->getContainer("<ContainerName>"));
   */
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairTask::SetVerbose (Int_t iVerbose) inherited
Set verbosity level. For this task and all of the subtasks.
Definition at line 116 of file FairTask.cxx.
References FairTask::fVerbose, and FairTask::SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and FairTask::SetVerbose().
 {
   fVerbose = iVerbose;
   TIter next(GetListOfTasks());
   FairTask* task;
   while((task=dynamic_cast <FairTask*> (next()))) { task->SetVerbose(iVerbose); }
 }
void FairTutorialDet4MilleWriter::SetVersion (Int_t val) inline
Definition at line 52 of file FairTutorialDet4MilleWriter.h.
References fVersion.
 {fVersion = val;}
void FairTutorialDet4MilleWriter::SetWriteAscii (Bool_t val) inline
Definition at line 50 of file FairTutorialDet4MilleWriter.h.
References fWriteAscii.
 {fWriteAscii = val;}
void FairTutorialDet4MilleWriter::StraightLineShiftX (Option_t * opt) private
Definition at line 134 of file FairTutorialDet4MilleWriter.cxx.
References DEBUG, Mille::end(), FairLogger::endl(), fHits, fMille, fTracks, FairTrackParam::GetTx(), FairHit::GetX(), FairTrackParam::GetX(), FairHit::GetZ(), LOG, and Mille::mille().
Referenced by Exec().
 {
   const Int_t nLC = 2; // number of local parameters
   // two for track x-coordinate
   // x(z) = a1*z + a2
   // dx(z)/da1 = z
   // dx(z)/da2 = 1
   const Int_t nGL = 1; // number of global parameters per point
   // taken from millepede 1 dim example
   Float_t sigma = 0.1;
   Float_t* derLC = new Float_t[nLC]; // array of derivatives for local parameters
   Float_t* derGL = new Float_t[nGL]; // array of derivatives for global parameters
   Int_t* label = new Int_t[nGL]; // array of labels
   for (Int_t help = 0; help < nGL; help++) {
     derGL[help] = 0;
   }
   for (Int_t help = 0; help < nLC; help++) {
     derLC[help] = 0;
   }
   FairTrackParam* track = (FairTrackParam*) fTracks->At(0);
   //Extract Track parameters
   Double_t OffX = track->GetX();
   Double_t SlopeX = track->GetTx();
   Double_t residual;
   FairTutorialDet4Hit* hit;
   Int_t nHits = fHits->GetEntriesFast();
   for (Int_t iHit=0; iHit<nHits; ++iHit) {
     hit = (FairTutorialDet4Hit*) fHits->At(iHit);
     Float_t Z = hit->GetZ();
     Float_t hitX = hit->GetX();
     Float_t fitX = OffX + SlopeX * Z;
     LOG(DEBUG)<<"hitX, fitX: "<< hitX<<" ,"<<fitX<<FairLogger::endl;
     label[0] = iHit+1;
     derGL[0] = -1;
     derLC[0] = 1;
     derLC[1] = Z;
     residual = fitX - hitX;
     LOG(DEBUG)<<"ResidualX: "<< residual<<FairLogger::endl;
     //call to Mille Writer
     fMille->mille(nLC,derLC,nGL,derGL,label,residual,sigma);
   }
   fMille->end();
   delete[] derLC;
   delete[] derGL;
   delete[] label;
 }
void FairTutorialDet4MilleWriter::StraightLineShiftXY (Option_t * opt) private
Definition at line 203 of file FairTutorialDet4MilleWriter.cxx.
References DEBUG, Mille::end(), FairLogger::endl(), fHits, fMille, fTracks, FairTrackParam::GetTx(), FairTrackParam::GetTy(), FairHit::GetX(), FairTrackParam::GetX(), FairHit::GetY(), FairTrackParam::GetY(), FairHit::GetZ(), LOG, and Mille::mille().
Referenced by Exec().
 {
   const Int_t nLC = 4; // number of local parameters
   // two for track x-coordinate
   // x(z) = a1*z + a2
   // dx(z)/da1 = z
   // dx(z)/da2 = 1
   const Int_t nGL = 2; // number of global parameters per point
   // taken from millepede 1 dim example
   Float_t sigma = 0.1;
   Float_t* derLC = new Float_t[nLC]; // array of derivatives for local parameters
   Float_t* derGL = new Float_t[nGL]; // array of derivatives for global parameters
   Int_t* label = new Int_t[nGL]; // array of labels
   for (Int_t help = 0; help < nGL; help++) {
     derGL[help] = 0;
   }
   for (Int_t help = 0; help < nLC; help++) {
     derLC[help] = 0;
   }
   FairTrackParam* track = (FairTrackParam*) fTracks->At(0);
   //Extract Track parameters
   Double_t OffX = track->GetX();
   Double_t SlopeX = track->GetTx();
   Double_t OffY = track->GetY();
   Double_t SlopeY = track->GetTy();
   Double_t residual;
   FairTutorialDet4Hit* hit;
   Int_t nHits = fHits->GetEntriesFast();
   for (Int_t iHit=0; iHit<nHits; ++iHit) {
     hit = (FairTutorialDet4Hit*) fHits->At(iHit);
     Float_t Z = hit->GetZ();
     Float_t hitX = hit->GetX();
     Float_t fitX = OffX + SlopeX * Z;
     Float_t hitY = hit->GetY();
     Float_t fitY = OffY + SlopeY * Z;
     LOG(DEBUG)<<"hitX, fitX: "<< hitX<<" ,"<<fitX<<FairLogger::endl;
     label[0] = iHit+1;
     label[1] = iHit+101;
     derGL[0] = -1;
     derGL[1] = 0;
     derLC[0] = 1;
     derLC[1] = Z;
     derLC[2] = 0;
     derLC[3] = 0;
     residual = fitX - hitX;
     LOG(DEBUG)<<"ResidualX: "<< residual<<FairLogger::endl;
     //call to Mille Writer
     fMille->mille(nLC,derLC,nGL,derGL,label,residual,sigma);
     derGL[0] = 0;
     derGL[1] = -1;
     derLC[0] = 0;
     derLC[1] = 0;
     derLC[2] = 1;
     derLC[3] = Z;
     residual = fitY - hitY;
     LOG(DEBUG)<<"ResidualX: "<< residual<<FairLogger::endl;
     //call to Mille Writer
     fMille->mille(nLC,derLC,nGL,derGL,label,residual,sigma);
   }
   fMille->end();
   delete[] derLC;
   delete[] derGL;
   delete[] label;
 }
Member Data Documentation
TString FairTutorialDet4MilleWriter::fFileName private
Definition at line 76 of file FairTutorialDet4MilleWriter.h.
Referenced by Init(), and SetFileName().
TClonesArray* FairTutorialDet4MilleWriter::fHits private
Input array from previous already existing data level
Definition at line 68 of file FairTutorialDet4MilleWriter.h.
Referenced by Init(), IsGoodEvent(), StraightLineShiftX(), and StraightLineShiftXY().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
Mille* FairTutorialDet4MilleWriter::fMille private
Definition at line 70 of file FairTutorialDet4MilleWriter.h.
Referenced by Init(), StraightLineShiftX(), and StraightLineShiftXY().
TClonesArray* FairTutorialDet4MilleWriter::fTracks private
Input array from previous already existing data level
Definition at line 65 of file FairTutorialDet4MilleWriter.h.
Referenced by Init(), StraightLineShiftX(), and StraightLineShiftXY().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
Int_t FairTutorialDet4MilleWriter::fVersion private
Definition at line 74 of file FairTutorialDet4MilleWriter.h.
Referenced by Exec(), and SetVersion().
Bool_t FairTutorialDet4MilleWriter::fWriteAscii private
Definition at line 72 of file FairTutorialDet4MilleWriter.h.
Referenced by Init(), and SetWriteAscii().
The documentation for this class was generated from the following files:
FairTutorialDet4MilleWriter.h
FairTutorialDet4MilleWriter.cxx