FairRroot: FairGenericStack Class Reference
FairGenericStack Class Reference
#include <FairGenericStack.h>
Public Member Functions
FairGenericStack ()
FairGenericStack (Int_t size)
virtual ~FairGenericStack ()
virtual void PushTrack (Int_t toBeDone, Int_t parentID, Int_t pdgCode, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t time, Double_t polx, Double_t poly, Double_t polz, TMCProcess proc, Int_t &ntr, Double_t weight, Int_t is)
virtual void PushTrack (Int_t toBeDone, Int_t parentID, Int_t pdgCode, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t time, Double_t polx, Double_t poly, Double_t polz, TMCProcess proc, Int_t &ntr, Double_t weight, Int_t is, Int_t secondparentID)
virtual TParticle * PopNextTrack (Int_t &iTrack)
virtual TParticle * PopPrimaryForTracking (Int_t iPrim)
void AddParticle (TParticle *part)
virtual void FillTrackArray ()
virtual void UpdateTrackIndex (TRefArray *detArray=0)
void SetDetArrayList (TRefArray *detArray)
virtual void Reset ()
virtual void Register ()
virtual void Print (Option_t *option="") const
virtual void SetCurrentTrack (Int_t iTrack)
virtual Int_t GetNtrack () const
virtual Int_t GetNprimary () const
virtual TParticle * GetCurrentTrack () const
virtual Int_t GetCurrentTrackNumber () const
virtual Int_t GetCurrentParentTrackNumber () const
virtual TParticle * GetParticle (Int_t trackID) const
virtual TClonesArray * GetListOfParticles ()
virtual FairGenericStack * CloneStack () const
Protected Member Functions
FairGenericStack (const FairGenericStack &)
FairGenericStack & operator= (const FairGenericStack &)
Protected Attributes
FairLogger * fLogger
TRefArray * fDetList
TIterator * fDetIter
Int_t fVerbose
Detailed Description
Definition at line 37 of file FairGenericStack.h.
Constructor & Destructor Documentation
FairGenericStack::FairGenericStack ()
Default constructor
Definition at line 17 of file FairGenericStack.cxx.
   : TVirtualMCStack(),
     fLogger(FairLogger::GetLogger()),
     fDetList(0),
     fDetIter(0),
     fVerbose(1)
 {
 }
FairGenericStack::FairGenericStack (Int_t size)
Destructor with estimated array size
Definition at line 27 of file FairGenericStack.cxx.
   : TVirtualMCStack(),
     fLogger(FairLogger::GetLogger()),
     fDetList(0),
     fDetIter(0),
     fVerbose(1)
 {
 }
FairGenericStack::~FairGenericStack () virtual
Destructor
Definition at line 37 of file FairGenericStack.cxx.
 {
 }
FairGenericStack::FairGenericStack (const FairGenericStack & rhs) protected
Copy constructor
Definition at line 42 of file FairGenericStack.cxx.
   : TVirtualMCStack(rhs),
     fLogger(0),
     fDetList(0),
     fDetIter(0),
     fVerbose(rhs.fVerbose)
 {
 }
Member Function Documentation
void FairGenericStack::AddParticle (TParticle * part)
Add a TParticle to the fParticles array
Definition at line 104 of file FairGenericStack.cxx.
 {
 }
FairGenericStack * FairGenericStack::CloneStack () const virtual
Clone this object (used in MT mode only)
Reimplemented in FairStack.
Definition at line 177 of file FairGenericStack.cxx.
Referenced by FairMCApplication::operator=().
 {
   Fatal("CloneStack","Has to be overriden in multi-threading applications.");
   return 0;
 }
void FairGenericStack::FillTrackArray () virtual
Fill the MCTrack output array, applying filter criteria
Reimplemented in FairStack, and MyProjStack.
Definition at line 115 of file FairGenericStack.cxx.
Referenced by FairMCApplication::FinishEvent().
 {
 }
Int_t FairGenericStack::GetCurrentParentTrackNumber () const virtual
Reimplemented in FairStack, and MyProjStack.
Definition at line 170 of file FairGenericStack.cxx.
 {
   return 0;
 }
TParticle * FairGenericStack::GetCurrentTrack () const virtual
Reimplemented in FairStack, and MyProjStack.
Definition at line 158 of file FairGenericStack.cxx.
Referenced by FairMCApplication::PreTrack().
 {
   return NULL;
 }
Int_t FairGenericStack::GetCurrentTrackNumber () const virtual
Reimplemented in FairStack, and MyProjStack.
Definition at line 164 of file FairGenericStack.cxx.
 {
   return 0;
 }
virtual TClonesArray* FairGenericStack::GetListOfParticles () inline virtual
Reimplemented in FairStack, and MyProjStack.
Definition at line 156 of file FairGenericStack.h.
 { return NULL; }
Int_t FairGenericStack::GetNprimary () const virtual
Reimplemented in FairStack, and MyProjStack.
Definition at line 152 of file FairGenericStack.cxx.
 {
   return 0;
 }
Int_t FairGenericStack::GetNtrack () const virtual
Accessors
Reimplemented in FairStack, and MyProjStack.
Definition at line 146 of file FairGenericStack.cxx.
 {
   return 0;
 }
virtual TParticle* FairGenericStack::GetParticle (Int_t trackID) const inline virtual
Reimplemented in FairStack, and MyProjStack.
Definition at line 154 of file FairGenericStack.h.
 { return NULL; }
FairGenericStack & FairGenericStack::operator= (const FairGenericStack & rhs) protected
Assignment operator
Definition at line 53 of file FairGenericStack.cxx.
References fDetIter, fDetList, fLogger, fVerbose, and operator=().
 {
   // check assignment to self
   if (this == &rhs) return *this;
   // base class assignment
   TVirtualMCStack::operator=(rhs);
   // assignment oiperator
   fLogger = 0;
   fDetList = 0;
   fDetIter = 0;
   fVerbose = rhs.fVerbose;
   return *this;
 }
TParticle * FairGenericStack::PopNextTrack (Int_t & iTrack) virtual
Virtual method PopNextTrack. Gets next particle for tracking from the stack.
Parameters
iTrack index of popped track
Returns
Pointer to the TParticle of the track
Reimplemented in FairStack, and MyProjStack.
Definition at line 92 of file FairGenericStack.cxx.
 {
   return 0;
 }
TParticle * FairGenericStack::PopPrimaryForTracking (Int_t iPrim) virtual
Virtual method PopPrimaryForTracking. Gets primary particle by index for tracking from stack.
Parameters
iPrim index of primary particle
Returns
Pointer to the TParticle of the track
Reimplemented in FairStack, and MyProjStack.
Definition at line 98 of file FairGenericStack.cxx.
 {
   return 0;
 }
void FairGenericStack::Print (Option_t * option = "") const virtual
Output to screen
Parameters
iVerbose 0=events summary, 1=track info
Definition at line 136 of file FairGenericStack.cxx.
 {
 }
void FairGenericStack::PushTrack (Int_t toBeDone, Int_t parentID, Int_t pdgCode, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t time, Double_t polx, Double_t poly, Double_t polz, TMCProcess proc, Int_t & ntr, Double_t weight, Int_t is) virtual
Virtual method PushTrack. Add a TParticle to the stack.
Parameters
toBeDone Flag for tracking
parentID Index of mother particle
pdgCode Particle type (PDG encoding)
px,py,pz Momentum components at start vertex [GeV]
e Total energy at start vertex [GeV]
vx,vy,vz Coordinates of start vertex [cm]
time Start time of track [s]
polx,poly,polz Polarisation vector
proc Production mechanism (VMC encoding)
ntr Track number (filled by the stack)
weight Particle weight
is Generation status code (whatever that means)
Reimplemented in FairStack, and MyProjStack.
Definition at line 72 of file FairGenericStack.cxx.
Referenced by FairPrimaryGenerator::AddTrack().
 {
 }
void FairGenericStack::PushTrack (Int_t toBeDone, Int_t parentID, Int_t pdgCode, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t time, Double_t polx, Double_t poly, Double_t polz, TMCProcess proc, Int_t & ntr, Double_t weight, Int_t is, Int_t secondparentID) virtual
Virtual method PushTrack. Add a TParticle to the stack.
Parameters
toBeDone Flag for tracking
parentID Index of mother particle
pdgCode Particle type (PDG encoding)
px,py,pz Momentum components at start vertex [GeV]
e Total energy at start vertex [GeV]
vx,vy,vz Coordinates of start vertex [cm]
time Start time of track [s]
polx,poly,polz Polarisation vector
proc Production mechanism (VMC encoding)
ntr Track number (filled by the stack)
weight Particle weight
is Generation status code (whatever that means)
secondparentID used fot the index of mother of primery in the list
Reimplemented in FairStack, and MyProjStack.
Definition at line 82 of file FairGenericStack.cxx.
 {
 }
void FairGenericStack::Register () virtual
Register the MCTrack array to the Root Manager
Reimplemented in FairStack, and MyProjStack.
Definition at line 131 of file FairGenericStack.cxx.
Referenced by FairMCApplication::InitGeometry(), and FairMCApplication::RegisterStack().
 {
 }
void FairGenericStack::Reset () virtual
Resets arrays and stack and deletes particles and tracks
Reimplemented in FairStack, and MyProjStack.
Definition at line 126 of file FairGenericStack.cxx.
Referenced by FairMCApplication::FinishEvent().
 {
 }
void FairGenericStack::SetCurrentTrack (Int_t iTrack) virtual
Modifiers
Reimplemented in FairStack, and MyProjStack.
Definition at line 141 of file FairGenericStack.cxx.
 {
 }
void FairGenericStack::SetDetArrayList (TRefArray * detArray)
Set the list of detectors to be used for filltering the stack
Definition at line 108 of file FairGenericStack.cxx.
References fDetIter, and fDetList.
Referenced by FairMCApplication::RunMC().
 {
   fDetList=detArray;
   if(fDetList!=0) { fDetIter=fDetList->MakeIterator(); }
 }
void FairGenericStack::UpdateTrackIndex (TRefArray * detArray = 0) virtual
Update the track index in the MCTracks and MCPoints
Reimplemented in FairStack, and MyProjStack.
Definition at line 120 of file FairGenericStack.cxx.
Referenced by FairMCApplication::FinishEvent().
 {
 }
Member Data Documentation
TIterator* FairGenericStack::fDetIter protected
Iterator for the detector list
Definition at line 174 of file FairGenericStack.h.
Referenced by operator=(), SetDetArrayList(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
TRefArray* FairGenericStack::fDetList protected
List of detectors registering hits in the simulation
Definition at line 171 of file FairGenericStack.h.
Referenced by operator=(), SetDetArrayList(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
FairLogger* FairGenericStack::fLogger protected
Fair Logger
Definition at line 168 of file FairGenericStack.h.
Referenced by operator=().
Int_t FairGenericStack::fVerbose protected
Verbosity level
Definition at line 177 of file FairGenericStack.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
FairGenericStack.h
FairGenericStack.cxx