FairRroot: FairRunAnaProof Class Reference
FairRunAnaProof Class Reference
#include <FairRunAnaProof.h>
Public Member Functions
virtual ~FairRunAnaProof ()
FairRunAnaProof (const char *proofName="")
void Init ()
void Run (Int_t NStart, Int_t NStop)
void RunOneEvent (Long64_t entry)
void RunOnProof (Int_t NStart, Int_t NStop)
void SetInTree (TTree *tempTree)
TProof * GetProof ()
void SetRunOnProofWorker (Bool_t tb=kTRUE)
void SetProofParName (TString parName)
void SetOutputDirectory (TString dirName)
void SetProofOutputStatus (TString outStat)
void AddFriend (TString fName)
void Run (Double_t delta_t)
void Run (Long64_t entry)
void RunEventReco (Int_t NStart, Int_t NStop)
void RunMixed (Int_t NStart, Int_t NStop)
void RunTSBuffers ()
void DummyRun (Int_t NStart, Int_t NStop)
void RunMQ (Long64_t entry)
void RunOnLmdFiles (UInt_t NStart=0, UInt_t NStop=0)
void TerminateRun ()
void SetSignalFile (TString name, UInt_t identifier)
void SetBackgroundFile (TString name)
void AddBackgroundFile (TString name)
void AddSignalFile (TString name, UInt_t identifier)
void SetInputFile (TString fname)
void AddFile (TString name)
void Reinit (UInt_t runId)
UInt_t getRunId ()
FairField * GetField ()
void SetField (FairField *ffield)
void SetGeomFile (const char *GeoFileName)
TFile * GetGeoFile ()
void InitContainers ()
void SetContainerStatic (Bool_t tempBool=kTRUE)
Bool_t GetContainerStatic ()
void RunWithTimeStamps ()
Bool_t IsTimeStamp ()
void CompressData ()
void SetEventTimeInterval (Double_t min, Double_t max)
void SetEventMeanTime (Double_t mean)
void BGWindowWidthNo (UInt_t background, UInt_t Signalid)
void BGWindowWidthTime (Double_t background, UInt_t Signalid)
void StopProcessingLMD (void)
Bool_t GetLMDProcessingStatus (void)
void SetMixAllInputs (Bool_t Status)
virtual void AddTask (FairTask *t)
virtual void SetTask (FairTask *t)
void SetOutputFile (const char *fname)
void SetOutputFile (TFile *f)
void SetEventHeader (FairEventHeader *EvHeader)
FairRuntimeDb * GetRuntimeDb (void)
TFile * GetOutputFile ()
Int_t GetRunId ()
void SetRunId (UInt_t runId)
FairEventHeader * GetEventHeader ()
Bool_t IsAna ()
FairTask * GetTask (const char *taskName)
FairTask * GetMainTask ()
Int_t GetNTasks ()
void CreateGeometryFile (const char *geofile)
void SetWriteRunInfoFile (Bool_t write)
void SetGenerateRunInfo (Bool_t write)
Bool_t GetWriteRunInfoFile ()
Bool_t IsRunInfoGenerated ()
void SetUseFairLinks (Bool_t val)
Bool_t GetIsMaster () const
Static Public Member Functions
static FairRunAnaProof * Instance ()
Protected Attributes
TProof * fProof
Bool_t fRunOnProofWorker
TString fProofServerName
TString fProofParName
TString fOutputDirectory
TString fProofOutputStatus
Bool_t fIsInitialized
TFile * fInputGeoFile
Bool_t fLoadGeo
FairEventHeader * fEvtHeader
FairMCEventHeader * fMCHeader
Bool_t fStatic
FairField * fField
Bool_t fTimeStamps
Bool_t fInFileIsOpen
Bool_t fMixedInput
Double_t fEventTimeMin
Double_t fEventTimeMax
Double_t fEventTime
Double_t fEventMeanTime
TF1 * fTimeProb
Bool_t fFinishProcessingLMDFile
FairLogger * fLogger
FairRuntimeDb * fRtdb
FairTask * fTask
const char * fOutname
FairRootManager * fRootManager
TFile * fOutFile
UInt_t fRunId
Bool_t fAna
FairEventHeader * fEvHead
FairFileHeader * fFileHeader
Bool_t fGenerateRunInfo
Bool_t fIsMaster
Static Protected Attributes
static FairRunAnaProof * fRAPInstance = 0
static FairRunAna * fgRinstance = 0
static TMCThreadLocal FairRun * fRunInstance = 0
Detailed Description
Configure and manage the Analysis on proof
Author
R. Karabowicz
Version
0.1
Since
30.04.2013
Definition at line 22 of file FairRunAnaProof.h.
Constructor & Destructor Documentation
FairRunAnaProof::~FairRunAnaProof () virtual
Definition at line 79 of file FairRunAnaProof.cxx.
 {
 }
FairRunAnaProof::FairRunAnaProof (const char * proofName = "")
Definition at line 51 of file FairRunAnaProof.cxx.
References FairLogger::endl(), FairRun::fAna, fProof, fProofServerName, fRAPInstance, fRunOnProofWorker, INFO, and LOG.
   :FairRunAna(),
    fProof(NULL),
    fRunOnProofWorker(kFALSE),
    fProofServerName(proofName),
    fProofParName("$VMCWORKDIR/gconfig/libFairRoot.par"),
    fOutputDirectory(""),
    fProofOutputStatus("copy")
 {
   if ( strcmp(proofName,"RunOnProofWorker") == 0 ) {
     fRunOnProofWorker = kTRUE;
   }
   else {
     LOG(INFO) << "+++++++ T P R O O F +++++++++++++++++++++++++++++++++" << FairLogger::endl;
     LOG(INFO) << "creating TProof* proof = TProof::Open(\"" << fProofServerName.Data()
          << "\");" << FairLogger::endl;
     TProof::AddEnvVar("LOCALDATASERVER","file://");
     //    TProof* proof = TProof::Open("lite:///?workers=1");
     fProof = TProof::Open(fProofServerName.Data());
     LOG(INFO) << "+++++++ C R E A T E D +++++++++++++++++++++++++++++++" << FairLogger::endl;
   }
   fRAPInstance=this;
   fAna=kTRUE;
 }
Member Function Documentation
void FairRunAna::AddBackgroundFile (TString name) inherited
Add input background file by name
Definition at line 745 of file FairRunAna.cxx.
References FairRootManager::AddBackgroundFile(), FairLogger::Fatal(), FairRun::fLogger, FairRunAna::fMixedInput, FairRun::fRootManager, and MESSAGE_ORIGIN.
 {
   if (fMixedInput) {
     fRootManager->AddBackgroundFile(name);
   } else {
     fLogger->Fatal(MESSAGE_ORIGIN," Background can be added only if mixed mode is used");
   }
 }
void FairRunAna::AddFile (TString name) inherited
Add a file to input chain
Definition at line 783 of file FairRunAna.cxx.
References FairRootManager::AddFile(), and FairRun::fRootManager.
Referenced by run_DiReLo(), and run_DiRePr().
 {
   fRootManager->AddFile(name);
 }
void FairRunAna::AddFriend (TString fName) inherited
Add a friend file (input) by name)
Definition at line 766 of file FairRunAna.cxx.
References FairRootManager::AddFriend(), FairLogger::Fatal(), FairRunAna::fIsInitialized, FairRun::fLogger, FairRun::fRootManager, and MESSAGE_ORIGIN.
Referenced by plots().
 {
   if (fIsInitialized) {
     fLogger->Fatal(MESSAGE_ORIGIN, "AddFriend has to be set before Run::Init !");
   } else {
     fRootManager->AddFriend(Name);
   }
 }
void FairRunAna::AddSignalFile (TString name, UInt_t identifier) inherited
Add signal file to input
Parameters
name : signal file name
identifier : Unsigned integer which identify the signal file to which this signal should be added
Definition at line 754 of file FairRunAna.cxx.
References FairRootManager::AddSignalFile(), FairLogger::Fatal(), FairRun::fLogger, FairRunAna::fMixedInput, FairRun::fRootManager, and MESSAGE_ORIGIN.
 {
   if (fMixedInput) {
     if (identifier==0) {
       fLogger->Fatal(MESSAGE_ORIGIN," ----- Identifier 0 is reserved for background files! please use other value ------ ");
     }
     fRootManager->AddSignalFile(name, identifier);
   } else {
     fLogger->Fatal(MESSAGE_ORIGIN," Signal can be added only if mixed mode is used");
   }
 }
void FairRun::AddTask (FairTask * t) virtual inherited
Add a FAIRTask to the simulation or analysis
Definition at line 108 of file FairRun.cxx.
References FairFileHeader::AddTaskClassName(), FairRun::fFileHeader, FairRun::fNTasks, and FairRun::fTask.
Referenced by FairEventManager::AddTask(), create_digis(), create_digis_mixed(), run_digi(), run_digi_timebased(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_reco(), and run_reco_timebased().
 {
   fTask->Add(t);
   fNTasks++;
   fFileHeader->AddTaskClassName(t->ClassName());
 }
void FairRunAna::BGWindowWidthNo (UInt_t background, UInt_t Signalid) inherited
Set the signal to background ratio in event units
Parameters
background : Number of background Events for one signal
Signalid : Signal file Id, used when adding (setting) the signal file here we just forward the call to the FairRootManager
Definition at line 830 of file FairRunAna.cxx.
References FairRootManager::BGWindowWidthNo(), and FairRun::fRootManager.
 {
   fRootManager->BGWindowWidthNo(background, Signalid);
 }
void FairRunAna::BGWindowWidthTime (Double_t background, UInt_t Signalid) inherited
Set the signal to background rate in time units
Parameters
background : Time of background Events before one signal
Signalid : Signal file Id, used when adding (setting) the signal file here we just forward the call to the FairRootManager
Definition at line 835 of file FairRunAna.cxx.
References FairRootManager::BGWindowWidthTime(), and FairRun::fRootManager.
Referenced by create_digis_mixed().
 {
   fRootManager->BGWindowWidthTime(background, Signalid);
 }
void FairRunAna::CompressData () inherited
Definition at line 805 of file FairRunAna.cxx.
References FairRun::fRootManager, and FairRootManager::SetCompressData().
 {
   fRootManager->SetCompressData(kTRUE);
 }
void FairRun::CreateGeometryFile (const char * geofile) inherited
Create a new file and save the TGeoManager to it
Definition at line 122 of file FairRun.cxx.
References FairRootManager::CreateGeometryFile(), and FairRun::fRootManager.
Referenced by run_rad(), run_rutherford(), run_sim(), run_sim_sep(), run_tutorial1(), and run_tutorial4().
 {
   fRootManager->CreateGeometryFile(geofile);
 }
void FairRunAna::DummyRun (Int_t NStart, Int_t NStop) inherited
the dummy run does not check the evt header or the parameters!!
This methode is just for testing, if you are not sure about what you do, don't use it
Definition at line 690 of file FairRunAna.cxx.
References FairRootManager::Fill(), FairTask::FinishTask(), FairRun::fRootManager, FairRun::fTask, and FairRootManager::Write().
Referenced by FairRunAna::Run().
 {
   for (int i=Ev_start; i< Ev_end; i++) {
     fTask->ExecuteTask("");
     fRootManager->Fill();
   }
   fTask->FinishTask();
   fRootManager->Write();
 }
Bool_t FairRunAna::GetContainerStatic () inline inherited
Definition at line 114 of file FairRunAna.h.
References FairRunAna::fStatic.
Referenced by FairAnaSelector::Init().
 { return fStatic; };
FairEventHeader * FairRun::GetEventHeader () inherited
Get the detector specific run header
Definition at line 134 of file FairRun.cxx.
References FairRun::fEvHead.
Referenced by FairRunOnline::EventLoop(), Init(), FairRunAna::Init(), FairRunOnline::Init(), and FairRunOnline::InitContainers().
 {
   if ( NULL == fEvHead ) {
     fEvHead = new FairEventHeader();
   }
   return fEvHead;
 }
FairField* FairRunAna::GetField () inline virtual inherited
Get the magnetic field
Implements FairRun.
Definition at line 93 of file FairRunAna.h.
References FairRunAna::fField.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairGeane::Init(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
{
       return fField;
     }
TFile* FairRunAna::GetGeoFile () inline inherited
Return a pointer to the geometry file
Definition at line 103 of file FairRunAna.h.
References FairRunAna::fInputGeoFile.
{
       return fInputGeoFile;
     }
Bool_t FairRun::GetIsMaster () const inline inherited
Definition at line 151 of file FairRun.h.
References FairRun::fIsMaster.
 { return fIsMaster;}
Bool_t FairRunAna::GetLMDProcessingStatus (void) inline inherited
Get the status of lmd file proccessing
Definition at line 145 of file FairRunAna.h.
References FairRunAna::fFinishProcessingLMDFile.
{
       return fFinishProcessingLMDFile;
     }
FairTask* FairRun::GetMainTask () inline inherited
Get Main Task
Definition at line 122 of file FairRun.h.
References FairRun::fTask.
{
       return fTask;
     }
Int_t FairRun::GetNTasks () inline inherited
Return the number of Tasks added to this Run
Definition at line 128 of file FairRun.h.
References FairRun::fNTasks.
{
       return fNTasks;
     }
TFile* FairRun::GetOutputFile () inline inherited
return a pointer to the output file
Definition at line 88 of file FairRun.h.
References FairRun::fOutFile.
Referenced by plots().
{
       return fOutFile;
     }
TProof* FairRunAnaProof::GetProof () inline
GetProof
Definition at line 47 of file FairRunAnaProof.h.
References fProof.
{
       return fProof;
     }
UInt_t FairRunAna::getRunId () inline inherited
Definition at line 89 of file FairRunAna.h.
References FairRun::fRunId.
Referenced by ClassImp(), and FairEventManagerEditor::Init().
{
       return fRunId;
     }
Int_t FairRun::GetRunId () inline inherited
return the run ID for the actul run
Definition at line 94 of file FairRun.h.
References FairRun::fRunId.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), create_digis(), create_digis_mixed(), FairConstField::FillParContainer(), FairMCApplication::InitGeometry(), and read_digis().
                       {
       return ((Int_t) fRunId);
     }
FairRuntimeDb* FairRun::GetRuntimeDb (void) inline inherited
return a pointer to the RuntimeDB
Definition at line 82 of file FairRun.h.
References FairRun::fRtdb.
Referenced by ClassImp(), FairMagnet::ConstructASCIIGeometry(), FairModule::ConstructASCIIGeometry(), FairTutorialDet4::ConstructASCIIGeometry(), FairTarget::ConstructGeometry(), FairPipe::ConstructGeometry(), FairTutorialDet2::ConstructGeometry(), NewDetector::ConstructGeometry(), FairTestDetector::ConstructGeometry(), FairRutherford::ConstructGeometry(), FairTutorialDet1::ConstructGeometry(), create_digis(), create_digis_mixed(), eventDisplay(), FairConstField::FillParContainer(), Init(), FairRunAna::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), NewDetector::Initialize(), FairTestDetector::Initialize(), FairTutorialDet2::Initialize(), FairRutherford::Initialize(), FairTutorialDet1::Initialize(), FairTutorialDet4::Initialize(), plots(), FairModule::ProcessNodes(), read_digis(), FairTutorialDet2Digitizer::ReInit(), FairTutorialDet4HitProducerIdealMisalign::ReInit(), run_bg(), run_digi(), run_digi_timebased(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_rad(), run_reco(), run_reco_timebased(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial2(), run_tutorial4(), FairTutorialDet2Digitizer::SetParContainers(), FairTutorialDet4HitProducerIdealMisalign::SetParContainers(), FairTutorialDet4::SetParContainers(), FairEventBuilderManager::SetParContainers(), MyFieldCreator::SetParm(), and FairMCApplication::SetParTask().
{
       return fRtdb;
     }
FairTask * FairRun::GetTask (const char * taskName) inherited
Get task by name
Definition at line 127 of file FairRun.cxx.
References FairRun::fTask.
 {
   TList* taskList = fTask->GetListOfTasks();
   TObject* task = taskList->FindObject(taskName);
   return dynamic_cast<FairTask*>(task);
 }
Bool_t FairRun::GetWriteRunInfoFile () inherited
Definition at line 156 of file FairRun.cxx.
References FairLogger::endl(), FairRun::fGenerateRunInfo, LOG, and WARNING.
 {
   LOG(WARNING) << "Function FairRun::GetWriteRunInfoFile() is depcrecated and will vanish in future versions of FairRoot.\n";
   LOG(WARNING) << "Please use FairRun::IsRunInfoGenerated() instead." << FairLogger::endl;
   return fGenerateRunInfo;
 }
void FairRunAnaProof::Init () virtual
initialize the run manager
Set the IO Manager to run with time stamps
Reimplemented from FairRunAna.
Definition at line 85 of file FairRunAnaProof.cxx.
References FairRuntimeDb::addRun(), FairFieldFactory::createFairField(), FairLogger::endl(), FairLogger::Fatal(), FairRunAna::fEvtHeader, FairRunAna::fField, FairRun::fFileHeader, FairRunAna::fInFileIsOpen, FairRunAna::fInputGeoFile, FairRunAna::fIsInitialized, FairRunAna::fLoadGeo, FairRun::fLogger, FairRunAna::fMCHeader, FairRunAna::fMixedInput, FairRun::fOutFile, FairRun::fRootManager, FairRun::fRtdb, FairRun::fRunId, fRunOnProofWorker, FairRun::fTask, FairRunAna::fTimeStamps, FairRunIdGenerator::generateId(), FairRuntimeDb::getContainer(), FairRun::GetEventHeader(), FairRootManager::GetInChain(), FairRootManager::GetInFile(), FairRootManager::GetObject(), FairEventHeader::GetRunId(), FairMCEventHeader::GetRunID(), FairRun::GetRuntimeDb(), FairLogger::Info(), FairTrajFilter::Init(), FairRuntimeDb::initContainers(), FairRootManager::InitSource(), FairTask::InitTask(), FairFieldFactory::Instance(), FairTrajFilter::Instance(), LOG, MESSAGE_ORIGIN, FairRootManager::OpenBackgroundChain(), FairRootManager::OpenSignalChain(), FairRootManager::ReadBKEvent(), FairRootManager::ReadEvent(), FairEventHeader::Register(), FairRootManager::RunWithTimeStamps(), FairRootManager::SetEvtHeaderNew(), FairRootManager::SetOutTree(), FairFieldFactory::SetParm(), FairTask::SetParTask(), FairFileHeader::SetRunId(), FairEventHeader::SetRunId(), FairRootManager::TruncateBranchNames(), WARNING, FairRootManager::WriteFileHeader(), and FairRootManager::WriteFolder().
Referenced by run_DiRePr().
 {
   fInFileIsOpen = fRootManager->InitSource();
   if (fIsInitialized) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Error Init is already called before!");
     exit(-1);
   } else {
     fIsInitialized=kTRUE;
   }
   if ( !fRunOnProofWorker ) {
     // Open the input file and add other input files added by AddFile to the
     // input chain. Do a check if the added files are of the same type
     // as the the input file. Same type means check if they contain the
     // same branch.
     if ( fMixedInput) {
       Bool_t openBKChain = fRootManager->OpenBackgroundChain();
       if (!openBKChain) {
         fLogger->Fatal(MESSAGE_ORIGIN, "Could not open background Chain!");
       }
       fRootManager->OpenSignalChain();
     }
   }
   //Load Geometry from user file
   if (fLoadGeo) {
     if (fInputGeoFile!=0) { //First check if the user has a separate Geo file!
       TIter next(fInputGeoFile->GetListOfKeys());
       TKey* key;
       while ((key = (TKey*)next())) {
         if (strcmp(key->GetClassName(),"TGeoManager") != 0) {
           continue;
         }
         gGeoManager = (TGeoManager*)key->ReadObj();
         break;
       }
     }
   } else {
 //    FairGeoParSet* geopar=dynamic_cast<FairGeoParSet*>(fRtdb->getContainer("FairGeoParSet"));
     fRtdb->getContainer("FairGeoParSet");
   }
   if (fInFileIsOpen) {
     if ( fRunOnProofWorker ) {
       if (fLoadGeo && gGeoManager==0) {
         fRootManager->GetInFile()->Get("FAIRGeom");
       }
     } else {
       // Add all friend files defined by AddFriend to the correct chain
 //      fRootManager->AddFriendsToChain();
       if (fLoadGeo && gGeoManager==0) {
         // Check if the geometry in the first file of the Chain
         fRootManager->GetInChain()->GetFile()->Get("FAIRGeom");
       }
       //check that the geometry was loaded if not try all connected files!
       if (fLoadGeo && gGeoManager==0) {
         fLogger->Info(MESSAGE_ORIGIN, "Geometry was not found in the input file we will look in the friends if any!" );
         TFile* currentfile= gFile;
         TFile* nextfile=0;
         TSeqCollection* fileList=gROOT->GetListOfFiles();
         for (Int_t k=0; k<fileList->GetEntries(); k++) {
           nextfile=(TFile*)fileList->At(k);
           if (nextfile) {
             nextfile->Get("FAIRGeom");
           }
           if (gGeoManager) {
             break;
           }
         }
         gFile=currentfile;
       }
     }
   } else if (fMixedInput) {
   } else { //  if(fInputFile )
     // NO input file but there is a geometry file
     if (fLoadGeo) {
       if (fInputGeoFile!=0) { //First check if the user has a separate Geo file!
         TIter next(fInputGeoFile->GetListOfKeys());
         TKey* key;
         while ((key = (TKey*)next())) {
           if (strcmp(key->GetClassName(),"TGeoManager") != 0) {
             continue;
           }
           gGeoManager = (TGeoManager*)key->ReadObj();
           break;
         }
       }
     }
   }
   //Init the Chain ptr
   //  fcurrent = fChainList.begin();
 // fOutFile = fRootManager->OpenOutFile(fOutname);
   if ( !fRunOnProofWorker ) {
     LOG(WARNING) << "QUITTING, CAUSE IT'S not running on proof worker" << FairLogger::endl;
     return;
   }
   gROOT->GetListOfBrowsables()->Add(fTask);
   // Init the RTDB containers
   fRtdb= GetRuntimeDb();
   FairBaseParSet* par=(FairBaseParSet*)
                       (fRtdb->getContainer("FairBaseParSet"));
   if (fTimeStamps) {
     fRootManager->RunWithTimeStamps();
   }
   // Assure that basic info is there for the run
   if (par && fInFileIsOpen) {
     fLogger->Info(MESSAGE_ORIGIN,"Parameter and input file are available, Assure that basic info is there for the run!");
     fRootManager->ReadEvent(0);
     fEvtHeader = (FairEventHeader*)fRootManager->GetObject("EventHeader.");
     fMCHeader = (FairMCEventHeader*)fRootManager->GetObject("MCEventHeader.");
     if (fEvtHeader ==0) {
       fEvtHeader=GetEventHeader();
       if ( fMCHeader == 0 ) {
         LOG(WARNING) << "Neither EventHeader nor MCEventHeader not available! Setting fRunId to 0." << FairLogger::endl;
       }
       else {
         fRunId = fMCHeader->GetRunID();
       }
       fEvtHeader->SetRunId(fRunId);
       fRootManager->SetEvtHeaderNew(kTRUE);
     } else {
       fRunId = fEvtHeader->GetRunId();
     }
     //Copy the Event Header Info to Output
     fEvtHeader->Register();
     // Init the containers in Tasks
     fRtdb->initContainers(fRunId);
     fTask->SetParTask();
     fRtdb->initContainers( fRunId );
     if (gGeoManager==0) {
     }
     //  fRootManager->SetBranchNameList(par->GetBranchNameList());
   } else if (fMixedInput) {
     fLogger->Info(MESSAGE_ORIGIN,"Initializing for Mixed input");
     //For mixed input we have to set containers to static becauser of the different run ids
     //fRtdb->setContainersStatic(kTRUE);
     fEvtHeader = (FairEventHeader*)fRootManager->GetObject("EventHeader.");
     fMCHeader = (FairMCEventHeader*)fRootManager->GetObject("MCEventHeader.");
     if (fEvtHeader ==0) {
       fEvtHeader=GetEventHeader();
       fRunId = fMCHeader->GetRunID();
       fEvtHeader->SetRunId(fRunId);
       fRootManager->SetEvtHeaderNew(kTRUE);
     }
     fRootManager->ReadBKEvent(0);
     //Copy the Event Header Info to Output
     fEvtHeader->Register();
     fRunId = fEvtHeader->GetRunId();
     // Init the containers in Tasks
     fRtdb->initContainers(fRunId);
     /*   if (gGeoManager==0) {
          fLogger->Info(MESSAGE_ORIGIN,"Read the Geometry from Parameter file");
           FairGeoParSet* geopar=dynamic_cast<FairGeoParSet*>(fRtdb->getContainer("FairGeoParSet"));
        }
        if (gGeoManager==0) {
          fLogger->Fatal(MESSAGE_ORIGIN,"Could not Read the Geometry from Parameter file");
        }
      */
     fTask->SetParTask();
     fRtdb->initContainers( fRunId );
   } else {
     fLogger->Info(MESSAGE_ORIGIN,"Initializing without input file or Mixed input");
     FairEventHeader* evt = GetEventHeader();
     evt->Register();
     FairRunIdGenerator genid;
     fRunId = genid.generateId();
     fRtdb->addRun(fRunId);
     evt->SetRunId( fRunId);
     fTask->SetParTask();
     fRtdb->initContainers( fRunId );
   }
   FairFieldFactory* fieldfact= FairFieldFactory::Instance();
   if (fieldfact) {
     fieldfact->SetParm();
   }
   fRtdb->initContainers(fRunId);
   fFileHeader->SetRunId(fRunId);
   // create a field
   // <DB>
   // Add test for external FairField settings
   if (fieldfact && !fField) {
     fField= fieldfact->createFairField();
   }
   // Now call the User initialize for Tasks
   fTask->InitTask();
   // if the vis manager is available then initialize it!
   FairTrajFilter* fTrajFilter = FairTrajFilter::Instance();
   if (fTrajFilter) {
     fTrajFilter->Init();
   }
   // create the output tree after tasks initialisation
   fOutFile->cd();
   TTree* outTree =new TTree("cbmsim", "/cbmout", 99);
   fRootManager->TruncateBranchNames(outTree, "cbmout");
   fRootManager->SetOutTree(outTree);
   fRootManager->WriteFolder();
   fRootManager->WriteFileHeader(fFileHeader);
 }
void FairRunAna::InitContainers () inherited
Initialization of parameter container is set to static, i.e: the run id is is not checked anymore after initializationInit containers executed on PROOF, which is part of Init when running locally
Definition at line 329 of file FairRunAna.cxx.
References FairRunAna::fEvtHeader, FairRunAna::fInFileIsOpen, FairRunAna::fMCHeader, FairRun::fRootManager, FairRun::fRtdb, FairRun::fRunId, FairRun::fTask, FairRuntimeDb::getContainer(), FairRootManager::GetObjectFromInTree(), FairEventHeader::GetRunId(), FairMCEventHeader::GetRunID(), FairRun::GetRuntimeDb(), FairRuntimeDb::initContainers(), FairRootManager::ReadEvent(), FairEventHeader::Register(), FairTask::ReInitTask(), FairRootManager::SetEvtHeaderNew(), and FairEventHeader::SetRunId().
Referenced by FairAnaSelector::Init().
 {
   fRtdb= GetRuntimeDb();
   FairBaseParSet* par=dynamic_cast<FairBaseParSet*>
                       (fRtdb->getContainer("FairBaseParSet"));
   if (par && fInFileIsOpen) {
     fRootManager->ReadEvent(0);
     fEvtHeader = dynamic_cast<FairEventHeader*>(fRootManager->GetObjectFromInTree("EventHeader."));
     fMCHeader  = dynamic_cast<FairMCEventHeader*>(fRootManager->GetObjectFromInTree("MCEventHeader."));
     if ( fMCHeader != 0 ) {
       fRunId = fMCHeader->GetRunID();
       fEvtHeader->SetRunId(fRunId); // should i do it?
       fRootManager->SetEvtHeaderNew(kTRUE);
     } else {
       fRunId = fEvtHeader->GetRunId();
     }
     //Copy the Event Header Info to Output
     fEvtHeader->Register();
     // Init the containers in Tasks
     fRtdb->initContainers(fRunId);
     fTask->ReInitTask();
     //    fTask->SetParTask();
     fRtdb->initContainers( fRunId );
     if (gGeoManager==0) {
       //   par->GetGeometry();
     }
   }
 }
FairRunAnaProof * FairRunAnaProof::Instance () static
Definition at line 43 of file FairRunAnaProof.cxx.
References fRAPInstance.
 {
   return fRAPInstance;
 }
Bool_t FairRun::IsAna () inline inherited
return true for Anaylsis session
Definition at line 111 of file FairRun.h.
References FairRun::fAna.
Referenced by FairRootManager::OpenOutFile().
{
       return fAna;
     }
Bool_t FairRun::IsRunInfoGenerated () inline inherited
Definition at line 145 of file FairRun.h.
References FairRun::fGenerateRunInfo.
 { return fGenerateRunInfo;}
Bool_t FairRunAna::IsTimeStamp () inline inherited
Definition at line 116 of file FairRunAna.h.
References FairRunAna::fTimeStamps.
{
       return fTimeStamps;
     }
void FairRunAna::Reinit (UInt_t runId) inherited
Definition at line 776 of file FairRunAna.cxx.
References FairRun::fRtdb, and FairRuntimeDb::initContainers().
Referenced by FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and RunOneEvent().
 {
   // reinit procedure
   fRtdb->initContainers( runId );
 }
void FairRunAnaProof::Run (Int_t NStart, Int_t NStop) virtual
Run from event number NStart to event number NStop
Reimplemented from FairRunAna.
Definition at line 325 of file FairRunAnaProof.cxx.
References RunOnProof().
Referenced by run_DiRePr().
 {
   RunOnProof(Ev_start,Ev_end);
   return;
 }
void FairRunAna::Run (Double_t delta_t) inherited
Run over the whole input file with timpe window delta_t as unit (entry)
Definition at line 572 of file FairRunAna.cxx.
References FairRootManager::DeleteOldWriteoutBufferData(), FairRootManager::Fill(), FairTask::FinishEvent(), FairTask::FinishTask(), FairRun::fRootManager, FairRun::fTask, FairTrajFilter::Instance(), FairRootManager::LastFill(), FairRootManager::ReadNextEvent(), FairTrajFilter::Reset(), FairRootManager::StoreAllWriteoutBufferData(), and FairRootManager::Write().
 {
   while (fRootManager->ReadNextEvent(delta_t)==kTRUE) {
     fTask->ExecuteTask("");
     fRootManager->Fill();
     fRootManager->DeleteOldWriteoutBufferData();
     fTask->FinishEvent();
     if (NULL !=  FairTrajFilter::Instance()) {
       FairTrajFilter::Instance()->Reset();
     }
   }
   fRootManager->StoreAllWriteoutBufferData();
   fTask->FinishTask();
   fRootManager->LastFill();
   fRootManager->Write();
 }
void FairRunAna::Run (Long64_t entry) inherited
Run for the given single entry
Definition at line 617 of file FairRunAna.cxx.
References FairRootManager::DeleteOldWriteoutBufferData(), FairRunAna::fEvtHeader, FairRootManager::Fill(), FairTask::FinishTask(), FairRun::fRootManager, FairRun::fRunId, FairRunAna::fStatic, FairRun::fTask, FairEventHeader::GetRunId(), FairRootManager::LastFill(), FairRootManager::ReadEvent(), FairRunAna::Reinit(), FairTask::ReInitTask(), and FairRootManager::Write().
 {
   UInt_t tmpId =0;
   fRootManager->ReadEvent(entry);
   tmpId = fEvtHeader->GetRunId();
   if ( tmpId != fRunId ) {
     fRunId = tmpId;
     if ( !fStatic ) {
       Reinit( fRunId );
       fTask->ReInitTask();
     }
   }
   fTask->ExecuteTask("");
   fTask->FinishTask();
   fRootManager->Fill();
   fRootManager->DeleteOldWriteoutBufferData();
   fRootManager->LastFill();
   fRootManager->Write();
 }
void FairRunAna::RunEventReco (Int_t NStart, Int_t NStop) inherited
Run event reconstruction from event number NStart to event number NStop
if we have simulation files then they have MC Event Header and the Run Id is in it, any way it would be better to make FairMCEventHeader a subclass of FairEvtHeader.
Definition at line 496 of file FairRunAna.cxx.
References FairRunAna::fEvtHeader, FairRun::fGenerateRunInfo, FairTask::FinishEvent(), FairTask::FinishTask(), FairRunAna::fMCHeader, FairRun::fRootManager, FairRun::fRunId, FairRunAna::fRunInfo, FairRunAna::fStatic, FairRun::fTask, FairRootManager::GetEventTime(), FairRootManager::GetInChain(), FairEventHeader::GetRunId(), FairMCEventHeader::GetRunID(), FairTrajFilter::Instance(), FairRootManager::IsEvtHeaderNew(), FairRootManager::LastFill(), FairRootManager::ReadEvent(), FairRunAna::Reinit(), FairTask::ReInitTask(), FairRunInfo::Reset(), FairTrajFilter::Reset(), FairRunInfo::StoreInfo(), FairRootManager::StoreWriteoutBufferData(), FairRootManager::Write(), and FairRunInfo::WriteInfo().
 {
   UInt_t tmpId =0;
   if (Ev_end==0) {
     if (Ev_start==0) {
       Ev_end=Int_t((fRootManager->GetInChain())->GetEntries());
     } else {
       Ev_end =  Ev_start;
       if ( Ev_end > ((fRootManager->GetInChain())->GetEntries()) ) {
         Ev_end = (Int_t) (fRootManager->GetInChain())->GetEntries();
       }
       Ev_start=0;
     }
   } else {
     Int_t fileEnd=(fRootManager->GetInChain())->GetEntries();
     if (Ev_end > fileEnd) {
       cout << "-------------------Warning---------------------------" << endl;
       cout << " -W FairRunAna : File has less events than requested!!" << endl;
       cout << " File contains : " << fileEnd  << " Events" << endl;
       cout << " Requested number of events = " <<  Ev_end <<  " Events"<< endl;
       cout << " The number of events is set to " << fileEnd << " Events"<< endl;
       cout << "-----------------------------------------------------" << endl;
       Ev_end = fileEnd;
     }
   }
   if (fGenerateRunInfo) {
     fRunInfo.Reset();
   }
   for (int i=Ev_start; i< Ev_end; i++) {
     fRootManager->ReadEvent(i);
     if (fRootManager->IsEvtHeaderNew()) {
       tmpId = fMCHeader->GetRunID();
     } else {
       tmpId = fEvtHeader->GetRunId();
     }
     if ( tmpId != fRunId ) {
       fRunId = tmpId;
       if ( !fStatic ) {
         Reinit( fRunId );
         fTask->ReInitTask();
       }
     }
     //FairMCEventHeader* header = dynamic_cast<FairMCEventHeader*>(fRootManager->GetObject("MCEventHeader.");
     //    std::cout << "WriteoutBufferData with time: " << fRootManager->GetEventTime();
     fRootManager->StoreWriteoutBufferData(fRootManager->GetEventTime());
     fTask->ExecuteTask("");
     // fRootManager->Fill();
     fTask->FinishEvent();
     if (fGenerateRunInfo) {
       fRunInfo.StoreInfo();
     }
     if (NULL !=  FairTrajFilter::Instance()) {
       FairTrajFilter::Instance()->Reset();
     }
   }
   fTask->FinishTask();
   if (fGenerateRunInfo) {
     fRunInfo.WriteInfo();
   }
   fRootManager->LastFill();
   fRootManager->Write();
 }
void FairRunAna::RunMixed (Int_t NStart, Int_t NStop) inherited
Run from event number NStart to event number NStop over mixed input files
Definition at line 365 of file FairRunAna.cxx.
References FairRootManager::CheckMaxEventNo(), FairLogger::Debug(), FairRootManager::DeleteOldWriteoutBufferData(), FairRootManager::Fill(), FairTask::FinishEvent(), FairTask::FinishTask(), FairRun::fLogger, FairRun::fRootManager, FairRun::fTask, FairRootManager::GetEventTime(), FairTrajFilter::Instance(), FairRootManager::LastFill(), MESSAGE_ORIGIN, FairRootManager::ReadEvent(), FairTrajFilter::Reset(), FairRootManager::StoreAllWriteoutBufferData(), FairRootManager::StoreWriteoutBufferData(), and FairRootManager::Write().
Referenced by FairRunAna::Run().
 {
   fLogger->Debug(MESSAGE_ORIGIN,"Running in mixed mode");
   Int_t MaxAllowed=fRootManager->CheckMaxEventNo(Ev_end);
   if (Ev_end==0) {
     if (Ev_start==0) {
       Ev_end=MaxAllowed;
     } else {
       Ev_end =  Ev_start;
       if ( Ev_end > MaxAllowed ) {
         Ev_end = MaxAllowed;
       }
       Ev_start=0;
     }
   } else {
     if (Ev_end > MaxAllowed) {
       Ev_end=MaxAllowed;
     }
   }
   for (int i=Ev_start; i< Ev_end; i++) {
     fRootManager->ReadEvent(i);
     fRootManager->StoreWriteoutBufferData(fRootManager->GetEventTime());
     fLogger->Debug(MESSAGE_ORIGIN,"------Event is read , now execute the tasks--------");
     fTask->ExecuteTask("");
     fLogger->Debug(MESSAGE_ORIGIN,"------ Tasks executed, now fill the tree  --------");
     fRootManager->Fill();
     fRootManager->DeleteOldWriteoutBufferData();
     fTask->FinishEvent();
     if (NULL !=  FairTrajFilter::Instance()) {
       FairTrajFilter::Instance()->Reset();
     }
   }
   fTask->FinishTask();
   fRootManager->StoreAllWriteoutBufferData();
   fRootManager->LastFill();
   fRootManager->Write();
 }
void FairRunAna::RunMQ (Long64_t entry) inherited
This methode is only needed and used with ZeroMQ it read a certain event and call the task exec, but no output is written
Parameters
entry : entry number in the tree
This methode is only needed and used with ZeroMQ it read a certain event and call the task exec, but no output is written
Definition at line 594 of file FairRunAna.cxx.
References FairRunAna::fEvtHeader, FairTask::FinishTask(), FairRun::fRootManager, FairRun::fRunId, FairRunAna::fStatic, FairRun::fTask, FairEventHeader::GetRunId(), FairRootManager::ReadEvent(), FairRunAna::Reinit(), and FairTask::ReInitTask().
 {
   UInt_t tmpId =0;
   fRootManager->ReadEvent(entry);
   tmpId = fEvtHeader->GetRunId();
   if ( tmpId != fRunId ) {
     fRunId = tmpId;
     if ( !fStatic ) {
       Reinit( fRunId );
       fTask->ReInitTask();
     }
   }
   fTask->ExecuteTask("");
   fTask->FinishTask();
 }
void FairRunAnaProof::RunOneEvent (Long64_t entry)
Run for one event, used on PROOF nodes
Definition at line 333 of file FairRunAnaProof.cxx.
References FairRootManager::DeleteOldWriteoutBufferData(), FairRunAna::fEvtHeader, FairRootManager::Fill(), FairTask::FinishEvent(), FairRun::fRootManager, FairRun::fRunId, FairRunAna::fStatic, FairRun::fTask, FairRunAna::fTimeStamps, FairRootManager::GetEventTime(), FairEventHeader::GetRunId(), FairRootManager::ReadEvent(), FairRunAna::Reinit(), FairTask::ReInitTask(), FairRunAna::RunTSBuffers(), and FairRootManager::StoreWriteoutBufferData().
Referenced by FairAnaSelector::Process().
 {
   if (fTimeStamps) {
     RunTSBuffers();
   } else {
     UInt_t tmpId =0;
     fRootManager->ReadEvent(entry);
     tmpId = fEvtHeader->GetRunId();
     if ( tmpId != fRunId ) {
       fRunId = tmpId;
       if ( !fStatic ) {
         Reinit( fRunId );
         fTask->ReInitTask();
       }
     }
     fRootManager->StoreWriteoutBufferData(fRootManager->GetEventTime());
     fTask->ExecuteTask("");
     fRootManager->Fill();
     fRootManager->DeleteOldWriteoutBufferData();
     fTask->FinishEvent();
   }
 }
void FairRunAna::RunOnLmdFiles (UInt_t NStart = 0, UInt_t NStop = 0) inherited
Run on a list of lmd files
Same result like break
Definition at line 666 of file FairRunAna.cxx.
References FairRunAna::fFinishProcessingLMDFile, FairRootManager::Fill(), FairTask::FinishTask(), FairRun::fLogger, FairRun::fRootManager, FairRun::fTask, FairLogger::Info(), MESSAGE_ORIGIN, and FairRootManager::Write().
 {
   if(NStart==0 && NStop==0) {
     NStart=0;
     NStop=1000000000;
     fLogger->Info(MESSAGE_ORIGIN," Maximum number of event is set to 1E9");
   }
   for (UInt_t i=NStart; i< NStop; i++) {
     if ( fFinishProcessingLMDFile ) {
       i = NStop;
     }
     fTask->ExecuteTask("");
     fRootManager->Fill();
   }
   fTask->FinishTask();
   fRootManager->Write();
 }
void FairRunAnaProof::RunOnProof (Int_t NStart, Int_t NStop)
Run on proof from event NStart to event NStop
Definition at line 359 of file FairRunAnaProof.cxx.
References FairRootManager::CloseOutFile(), FairLogger::endl(), fOutputDirectory, fProof, fProofOutputStatus, FairRun::fRootManager, FairRun::fRtdb, FairRunAna::fStatic, FairRun::fTask, FairParIo::getFilename(), FairRuntimeDb::getFirstInput(), FairRootManager::GetInChain(), FairRootManager::GetOutFile(), FairRuntimeDb::getSecondInput(), INFO, and LOG.
Referenced by Run().
 {
 //  FairAnaSelector* proofSelector = new FairAnaSelector();
   TChain* inChain = (TChain*)fRootManager->GetInChain();
   TString par1File = "";
   TString par2File = "";
   if ( fRtdb->getFirstInput () ) {
     par1File = fRtdb->getFirstInput ()->getFilename();
   }
   if ( fRtdb->getSecondInput() ) {
     par2File = fRtdb->getSecondInput()->getFilename();
   }
   TString outDir = (fOutputDirectory.Length()>1?fOutputDirectory.Data():gSystem->WorkingDirectory());
   TString outFile = fRootManager->GetOutFile()->GetName();
   fRootManager->CloseOutFile();
   fProof->AddInput(fTask);
   fProof->AddInput(new TNamed("FAIRRUNANA_fContainerStatic",(fStatic?"kTRUE":"kFALSE")));
   fProof->AddInput(new TNamed("FAIRRUNANA_fProofOutputStatus",fProofOutputStatus.Data()));
   fProof->AddInput(new TNamed("FAIRRUNANA_fOutputDirectory",outDir.Data()));
   fProof->AddInput(new TNamed("FAIRRUNANA_fOutputFileName",outFile.Data()));
   fProof->AddInput(new TNamed("FAIRRUNANA_fParInput1FName",par1File.Data()));
   fProof->AddInput(new TNamed("FAIRRUNANA_fParInput2FName",par2File.Data()));
   // uploading packages not needed, as the libraries are in the rootmap now
   // fProof->ClearPackages();
   // fProof->UploadPackage(fProofParName.Data());
   // fProof->EnablePackage(fProofParName.Data());
   Int_t nofChainEntries = inChain->GetEntries();
   LOG(INFO) << "FairRunAnaProof::RunOnProof(): The chain seems to have " << nofChainEntries << " entries." << FairLogger::endl;
   TObjArray* listOfFiles = inChain->GetListOfFiles();
   LOG(INFO) << "FairRunAnaProof::RunOnProof(): There are " << listOfFiles->GetEntries() << " files in the chain." << FairLogger::endl;
   inChain->SetProof();
   Int_t nofEventsToAnalyze = NStop-NStart;
   if ( nofEventsToAnalyze <= 0 ) {
     LOG(INFO) << "You requested to analyze events from " << NStart << " to " << NStop << " that is " << nofEventsToAnalyze << " events!!!" << FairLogger::endl;
     nofEventsToAnalyze = nofChainEntries-NStart;
     LOG(INFO) << "It will be changed to analyze all events from " << NStart << " to the end of chain (" << nofChainEntries << "), that is to analyze " << nofEventsToAnalyze << " events." << FairLogger::endl;
   }
   LOG(INFO) << "FairRunAnaProof::RunOnProof(): Starting inChain->Process(\"FairAnaSelector\",\"\","
        << nofEventsToAnalyze << "," << NStart << ")" << FairLogger::endl;
   inChain->Process("FairAnaSelector","",nofEventsToAnalyze,NStart);
   LOG(INFO) << "FairRunAnaProof::RunOnProof(): inChain->Process DONE" << FairLogger::endl;
   return;
 }
void FairRunAna::RunTSBuffers () inherited
Run over all TSBuffers until the data is processed
Definition at line 639 of file FairRunAna.cxx.
References FairRootManager::AllDataProcessed(), FairRootManager::DeleteOldWriteoutBufferData(), FairRootManager::Fill(), FairTask::FinishEvent(), FairTask::FinishTask(), FairRun::fRootManager, FairRun::fTask, FairRootManager::GetInTree(), FairTrajFilter::Instance(), FairRootManager::LastFill(), FairRootManager::ReadEvent(), FairTrajFilter::Reset(), FairRootManager::StoreAllWriteoutBufferData(), and FairRootManager::Write().
Referenced by FairRunAna::Run(), and RunOneEvent().
 {
   Int_t globalEvent = 0;
   bool firstRun = true;
   while (firstRun || fRootManager->AllDataProcessed() == kFALSE) {
     firstRun = false;
     TTree *InTree= fRootManager->GetInTree();
     if (globalEvent < InTree->GetEntriesFast()) { //this step is necessary to load in all data which is not read in via TSBuffers
       fRootManager->ReadEvent(globalEvent++);
     }
     fTask->ExecuteTask("");
     fRootManager->Fill();
     fRootManager->DeleteOldWriteoutBufferData();
     fTask->FinishEvent();
     if (NULL !=  FairTrajFilter::Instance()) {
       FairTrajFilter::Instance()->Reset();
     }
   }
   fRootManager->StoreAllWriteoutBufferData();
   fTask->FinishTask();
   fRootManager->LastFill();
   fRootManager->Write();
 }
void FairRunAna::RunWithTimeStamps () inherited
Definition at line 789 of file FairRunAna.cxx.
References FairLogger::Fatal(), FairRunAna::fIsInitialized, FairRun::fLogger, FairRun::fRootManager, FairRunAna::fTimeStamps, MESSAGE_ORIGIN, FairRootManager::RunWithTimeStamps(), and FairLogger::Warning().
Referenced by run_reco_timebased().
 {
   if (ROOT_VERSION_CODE >= ROOT_VERSION(5,29,1)) {
     if (fIsInitialized) {
       fLogger->Warning(MESSAGE_ORIGIN, "RunWithTimeStamps has to be set before Run::Init !");
       exit(-1);
     } else {
       fTimeStamps=kTRUE;
       fRootManager->RunWithTimeStamps();
     }
   } else {
     fLogger->Fatal(MESSAGE_ORIGIN, "RunWithTimeStamps need at least ROOT version 5.29.1") ;
   }
 }
void FairRunAna::SetBackgroundFile (TString name) inherited
Set the input background file by name
Definition at line 738 of file FairRunAna.cxx.
References FairRun::fLogger, FairRunAna::fMixedInput, FairRun::fRootManager, FairLogger::Info(), MESSAGE_ORIGIN, and FairRootManager::SetBackgroundFile().
Referenced by create_digis_mixed().
 {
   fMixedInput=kTRUE;
   fRootManager->SetBackgroundFile(name);
   fLogger->Info(MESSAGE_ORIGIN," ----- Mixed input mode will be used ------ ");
 }//_____________________________________________________________________________
void FairRunAna::SetContainerStatic (Bool_t tempBool = kTRUE) inherited
Definition at line 820 of file FairRunAna.cxx.
References FairRun::fLogger, FairRunAna::fStatic, FairLogger::Info(), and MESSAGE_ORIGIN.
 {
   fStatic=tempBool;
   if ( fStatic ) {
     fLogger->Info(MESSAGE_ORIGIN, "Parameter Cont. initialisation is static");
   } else {
     fLogger->Info(MESSAGE_ORIGIN, "Parameter Cont. initialisation is NOT static");
   }
 }
void FairRun::SetEventHeader (FairEventHeader * EvHeader) inline inherited
Set the experiment dependent run header for each run
Definition at line 76 of file FairRun.h.
References FairRun::fEvHead.
{
       fEvHead=EvHeader;
     }
void FairRunAna::SetEventMeanTime (Double_t mean) inherited
Set the mean time for the event in ns
Definition at line 815 of file FairRunAna.cxx.
References FairRun::fRootManager, and FairRootManager::SetEventMeanTime().
Referenced by create_digis_mixed(), and run_digi_timebased().
 {
   fRootManager->SetEventMeanTime(mean);
 }
void FairRunAna::SetEventTimeInterval (Double_t min, Double_t max) inherited
Set the min and max limit for event time in ns
Definition at line 810 of file FairRunAna.cxx.
References FairRun::fRootManager, and FairRootManager::SetEventTimeInterval().
 {
   fRootManager->SetEventTimeInterval(min,max);
 }
void FairRunAna::SetField (FairField * ffield) inline inherited
Set the magnetic Field
Definition at line 97 of file FairRunAna.h.
References FairRunAna::fField.
{
       fField=ffield ;
     }
void FairRun::SetGenerateRunInfo (Bool_t write) inline inherited
Definition at line 139 of file FairRun.h.
References FairRun::fGenerateRunInfo.
 { fGenerateRunInfo = write;}
void FairRunAna::SetGeomFile (const char * GeoFileName) inherited
Set external geometry file
Definition at line 107 of file FairRunAna.cxx.
References FairLogger::Error(), FairLogger::Fatal(), FairRunAna::fInputGeoFile, FairRunAna::fIsInitialized, FairRunAna::fLoadGeo, FairRun::fLogger, FairLogger::Info(), and MESSAGE_ORIGIN.
 {
   if (fIsInitialized) {
     fLogger->Fatal(MESSAGE_ORIGIN, "Geometry file has to be set before Run::Init !") ;
     exit(-1);
   } else {
     TFile* CurrentFile=gFile;
     fInputGeoFile= new TFile(GeoFileName);
     if (fInputGeoFile->IsZombie()) {
       fLogger->Error(MESSAGE_ORIGIN, "Error opening Geometry Input file");
       fInputGeoFile=0;
     }
     fLogger->Info(MESSAGE_ORIGIN, " Opening Geometry input file: %s ", GeoFileName);
     fLoadGeo=kTRUE;
     gFile=CurrentFile;
   }
 }
void FairRunAna::SetInputFile (TString fname) inherited
Set the input file by name
Definition at line 721 of file FairRunAna.cxx.
References FairRunAna::fMixedInput, FairRun::fRootManager, and FairRootManager::SetInputFile().
Referenced by create_digis(), eventDisplay(), plots(), read_digis(), run_digi(), run_digi_timebased(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_reco(), and run_reco_timebased().
 {
   if (!fMixedInput) {
     fRootManager->SetInputFile(name);
   }
 }
void FairRunAnaProof::SetInTree (TTree * tempTree) inline
set the input tree of fRootManager when running on PROOF worker
Definition at line 42 of file FairRunAnaProof.h.
References FairRun::fRootManager, and FairRootManager::SetInTree().
Referenced by FairAnaSelector::Init().
{
       fRootManager->SetInTree (tempTree);
     }
void FairRunAna::SetMixAllInputs (Bool_t Status) inherited
This method will simply forward the call to the FairRootManager, if true all inputs are mixed, i.e: each read event will take one entry from each input and put them in one big event and send it to the next step
Definition at line 841 of file FairRunAna.cxx.
References FairRun::fLogger, FairRun::fRootManager, FairLogger::Info(), MESSAGE_ORIGIN, and FairRootManager::SetMixAllInputs().
 {
    fLogger->Info(MESSAGE_ORIGIN, "Mixing for all input is choosed, in this mode one event per input file is read per step");
    fRootManager->SetMixAllInputs(Status);
 }
void FairRunAnaProof::SetOutputDirectory (TString dirName) inline
Set directory for storing output files
Definition at line 60 of file FairRunAnaProof.h.
References fOutputDirectory.
{
       fOutputDirectory = dirName;
     }
void FairRun::SetOutputFile (const char * fname) inherited
Set the output file name for analysis or simulation
Definition at line 87 of file FairRun.cxx.
References FairRun::fOutFile, FairRun::fOutname, FairRun::fRootManager, and FairRootManager::OpenOutFile().
Referenced by FairMCApplication::CloneForWorker(), create_digis(), create_digis_mixed(), eventDisplay(), plots(), read_digis(), run_bg(), run_digi(), run_digi_timebased(), run_DiReLo(), run_DiReOne(), run_DiRePr(), run_rad(), run_reco(), run_reco_timebased(), run_rutherford(), run_sg(), run_sg1(), run_sim(), run_sim_sep(), run_tutorial1(), run_tutorial2(), and run_tutorial4().
 {
   fOutname=fname;
   if (fRootManager) fOutFile = fRootManager->OpenOutFile(fOutname);
 }
void FairRun::SetOutputFile (TFile * f) inherited
Set the output file for analysis or simulation
Definition at line 96 of file FairRun.cxx.
References FairRun::fOutFile, FairRun::fOutname, FairRun::fRootManager, and FairRootManager::OpenOutFile().
 {
   if (! fRootManager) return;
   fOutname=f->GetName();
   fRootManager->OpenOutFile(f);
   fOutFile = f;
 }
void FairRunAnaProof::SetProofOutputStatus (TString outStat) inline
Set PROOF output status, possibilities: "copy","merge","dataset"
Definition at line 64 of file FairRunAnaProof.h.
References fProofOutputStatus.
{
       fProofOutputStatus = outStat;
     }
void FairRunAnaProof::SetProofParName (TString parName) inline
Set PROOF ARchive (PAR) file name
Definition at line 56 of file FairRunAnaProof.h.
References fProofParName.
{
       fProofParName = parName;
     }
void FairRun::SetRunId (UInt_t runId) inline inherited
Set the Run ID
Definition at line 101 of file FairRun.h.
References FairRun::fRunId.
         {
           fRunId = runId;
     }
void FairRunAnaProof::SetRunOnProofWorker (Bool_t tb = kTRUE) inline
To be set to kTRUE only when running on PROOF worker, only by TSelector
Definition at line 52 of file FairRunAnaProof.h.
References fRunOnProofWorker.
{
       fRunOnProofWorker = tb;
     }
void FairRunAna::SetSignalFile (TString name, UInt_t identifier) inherited
Set the input signal file
Parameters
name : signal file name
identifier : Unsigned integer which identify the signal file
Definition at line 728 of file FairRunAna.cxx.
References FairRootManager::AddSignalFile(), FairLogger::Fatal(), FairRun::fLogger, FairRunAna::fMixedInput, FairRun::fRootManager, FairLogger::Info(), and MESSAGE_ORIGIN.
Referenced by create_digis_mixed().
 {
   fMixedInput=kTRUE;
   if (identifier==0) {
     fLogger->Fatal(MESSAGE_ORIGIN," ----- Identifier 0 is reserved for background files! please use other value ------ ");
   }
   fRootManager->AddSignalFile(name, identifier);
   fLogger->Info(MESSAGE_ORIGIN," ----- Mixed input mode will be used ------ ");
 }
void FairRun::SetTask (FairTask * t) virtual inherited
Definition at line 115 of file FairRun.cxx.
References FairFileHeader::AddTaskClassName(), FairRun::fFileHeader, and FairRun::fTask.
 {
   if ( fTask ) { delete fTask; }
   fTask = t;
   fFileHeader->AddTaskClassName(t->ClassName());
 }
void FairRun::SetUseFairLinks (Bool_t val) inherited
Definition at line 142 of file FairRun.cxx.
References FairRun::fRootManager, and FairRootManager::SetUseFairLinks().
 {
         fRootManager->SetUseFairLinks(val);
 }
void FairRun::SetWriteRunInfoFile (Bool_t write) inherited
Definition at line 148 of file FairRun.cxx.
References FairLogger::endl(), FairRun::fGenerateRunInfo, LOG, and WARNING.
Referenced by run_rutherford().
 {
   LOG(WARNING) << "Function FairRun::SetWriteRunInfoFile(Bool_t) is depcrecated and will vanish in future versions of FairRoot.\n";
   LOG(WARNING) << "Please use FairRun::SetGenerateRunInfo(Bool_t) instead." << FairLogger::endl;
   fGenerateRunInfo = write;
 }
void FairRunAna::StopProcessingLMD (void) inline inherited
Set the flag for proccessing lmd files
Definition at line 141 of file FairRunAna.h.
References FairRunAna::fFinishProcessingLMDFile.
{
       fFinishProcessingLMDFile = kTRUE;
     }
void FairRunAna::TerminateRun () inherited
finish tasks, write output
Definition at line 705 of file FairRunAna.cxx.
References FairRootManager::CloseOutFile(), FairTask::FinishTask(), FairRun::fRootManager, FairRun::fTask, FairRootManager::GetOutFile(), FairRootManager::LastFill(), FairRootManager::StoreAllWriteoutBufferData(), and FairRootManager::Write().
Referenced by FairAnaSelector::SlaveTerminate().
 {
   fRootManager->StoreAllWriteoutBufferData();
   fTask->FinishTask();
   gDirectory->SetName(fRootManager->GetOutFile()->GetName());
   //  fRunInfo.WriteInfo(); // CRASHES due to file ownership i guess...
   //   cout << ">>> SlaveTerminate fRootManager->GetInChain()->Print()" << endl;
   //   fRootManager->GetInChain()->Print();
   //   cout << ">>>------------------------------------------------<<<" << endl;
   fRootManager->LastFill();
   fRootManager->Write();
   fRootManager->CloseOutFile();
 }
Member Data Documentation
Bool_t FairRun::fAna protected inherited
true for Anaylsis session
Definition at line 184 of file FairRun.h.
Referenced by FairRunAna::FairRunAna(), FairRunAnaProof(), FairRunOnline::FairRunOnline(), and FairRun::IsAna().
Double_t FairRunAna::fEventMeanTime protected inherited
EventMean time used (P(t)=1/fEventMeanTime*Exp(-t/fEventMeanTime)
Definition at line 186 of file FairRunAna.h.
Double_t FairRunAna::fEventTime protected inherited
Time of event since th start (ns)
Definition at line 184 of file FairRunAna.h.
Double_t FairRunAna::fEventTimeMax protected inherited
max time for one Event (ns)
Definition at line 182 of file FairRunAna.h.
Double_t FairRunAna::fEventTimeMin protected inherited
min time for one event (ns)
Definition at line 180 of file FairRunAna.h.
FairEventHeader* FairRun::fEvHead protected inherited
MC Event Header
Definition at line 186 of file FairRun.h.
Referenced by FairRun::GetEventHeader(), FairRun::SetEventHeader(), and FairRun::~FairRun().
FairEventHeader* FairRunAna::fEvtHeader protected inherited
Definition at line 170 of file FairRunAna.h.
Referenced by Init(), FairRunAna::Init(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and RunOneEvent().
FairField* FairRunAna::fField protected inherited
Definition at line 174 of file FairRunAna.h.
Referenced by FairRunAna::GetField(), Init(), FairRunAna::Init(), FairRunAna::SetField(), and FairRunAna::~FairRunAna().
FairFileHeader* FairRun::fFileHeader protected inherited
File Header
Definition at line 188 of file FairRun.h.
Referenced by FairRun::AddTask(), FairRun::FairRun(), Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), and FairRun::SetTask().
Bool_t FairRunAna::fFinishProcessingLMDFile protected inherited
Flag for proccessing lmd-files
Definition at line 190 of file FairRunAna.h.
Referenced by FairRunAna::GetLMDProcessingStatus(), FairRunAna::RunOnLmdFiles(), and FairRunAna::StopProcessingLMD().
Bool_t FairRun::fGenerateRunInfo protected inherited
true if RunInfo file should be written
Definition at line 190 of file FairRun.h.
Referenced by FairRun::GetWriteRunInfoFile(), FairRun::IsRunInfoGenerated(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRun::SetGenerateRunInfo(), and FairRun::SetWriteRunInfoFile().
FairRunAna * FairRunAna::fgRinstance = 0 static protected inherited
Definition at line 168 of file FairRunAna.h.
Referenced by FairRunAna::FairRunAna(), and FairRunAna::Instance().
Bool_t FairRunAna::fInFileIsOpen protected inherited
Definition at line 176 of file FairRunAna.h.
Referenced by Init(), FairRunAna::Init(), FairRunAna::InitContainers(), and FairRunAna::Run().
TFile* FairRunAna::fInputGeoFile protected inherited
Definition at line 167 of file FairRunAna.h.
Referenced by FairRunAna::GetGeoFile(), Init(), FairRunAna::Init(), and FairRunAna::SetGeomFile().
Bool_t FairRunAna::fIsInitialized protected inherited
This variable became true after Init is called
Definition at line 166 of file FairRunAna.h.
Referenced by FairRunAna::AddFriend(), Init(), FairRunAna::Init(), FairRunAna::RunWithTimeStamps(), and FairRunAna::SetGeomFile().
Bool_t FairRun::fIsMaster protected inherited
true if on master
Definition at line 192 of file FairRun.h.
Referenced by FairRun::GetIsMaster().
Bool_t FairRunAna::fLoadGeo protected inherited
Definition at line 169 of file FairRunAna.h.
Referenced by Init(), FairRunAna::Init(), and FairRunAna::SetGeomFile().
FairLogger* FairRun::fLogger protected inherited
Fair Logger
Definition at line 164 of file FairRun.h.
Referenced by FairRunAna::AddBackgroundFile(), FairRunAna::AddFriend(), FairRunAna::AddSignalFile(), FairRunSim::CheckFlukaExec(), Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), FairRunAna::RunMixed(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunWithTimeStamps(), FairRunAna::SetBackgroundFile(), FairRunOnline::SetContainerStatic(), FairRunAna::SetContainerStatic(), FairRunAna::SetGeomFile(), FairRunSim::SetGeoModel(), FairRunSim::SetMaterials(), FairRunSim::SetMCConfig(), FairRunAna::SetMixAllInputs(), FairRunAna::SetSignalFile(), FairRun::~FairRun(), and FairRunSim::~FairRunSim().
FairMCEventHeader* FairRunAna::fMCHeader protected inherited
Definition at line 171 of file FairRunAna.h.
Referenced by Init(), FairRunAna::Init(), FairRunAna::InitContainers(), FairRunAna::Run(), and FairRunAna::RunEventReco().
Bool_t FairRunAna::fMixedInput protected inherited
True if signal and background mixing is used
Definition at line 178 of file FairRunAna.h.
Referenced by FairRunAna::AddBackgroundFile(), FairRunAna::AddSignalFile(), Init(), FairRunAna::Init(), FairRunAna::Run(), FairRunAna::SetBackgroundFile(), FairRunAna::SetInputFile(), and FairRunAna::SetSignalFile().
TFile* FairRun::fOutFile protected inherited
Output file
Definition at line 180 of file FairRun.h.
Referenced by FairRun::GetOutputFile(), Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunOnline::Run(), and FairRun::SetOutputFile().
const char* FairRun::fOutname protected inherited
Output file name
Definition at line 176 of file FairRun.h.
Referenced by FairRun::SetOutputFile().
TString FairRunAnaProof::fOutputDirectory protected
Output directory
Definition at line 80 of file FairRunAnaProof.h.
Referenced by RunOnProof(), and SetOutputDirectory().
TProof* FairRunAnaProof::fProof protected
PROOF
Definition at line 72 of file FairRunAnaProof.h.
Referenced by FairRunAnaProof(), GetProof(), and RunOnProof().
TString FairRunAnaProof::fProofOutputStatus protected
Output status indicator: "copy","merge","dataset"
Definition at line 82 of file FairRunAnaProof.h.
Referenced by RunOnProof(), and SetProofOutputStatus().
TString FairRunAnaProof::fProofParName protected
PROOF ARchive (PAR) file name
Definition at line 78 of file FairRunAnaProof.h.
Referenced by SetProofParName().
TString FairRunAnaProof::fProofServerName protected
PROOF server name
Definition at line 76 of file FairRunAnaProof.h.
Referenced by FairRunAnaProof().
FairRunAnaProof * FairRunAnaProof::fRAPInstance = 0 static protected
Definition at line 69 of file FairRunAnaProof.h.
Referenced by FairRunAnaProof(), and Instance().
FairRootManager* FairRun::fRootManager protected inherited
IO manager
Definition at line 178 of file FairRun.h.
Referenced by FairRunAna::AddBackgroundFile(), FairRunAna::AddFile(), FairRunAna::AddFriend(), FairRunAna::AddSignalFile(), FairRunAna::BGWindowWidthNo(), FairRunAna::BGWindowWidthTime(), FairRunAna::CompressData(), FairRun::CreateGeometryFile(), FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairRun::FairRun(), FairRunOnline::Finish(), Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunOnline::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), RunOneEvent(), FairRunAna::RunOnLmdFiles(), RunOnProof(), FairRunAna::RunTSBuffers(), FairRunAna::RunWithTimeStamps(), FairRunAna::SetBackgroundFile(), FairRunAna::SetEventMeanTime(), FairRunAna::SetEventTimeInterval(), FairRunAna::SetInputFile(), SetInTree(), FairRunAna::SetMixAllInputs(), FairRun::SetOutputFile(), FairRunAna::SetSignalFile(), FairRun::SetUseFairLinks(), FairRunAna::TerminateRun(), and FairRun::~FairRun().
FairRuntimeDb* FairRun::fRtdb protected inherited
RuntimeDb
Definition at line 172 of file FairRun.h.
Referenced by FairRun::GetRuntimeDb(), Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunOnline::Reinit(), FairRunAna::Reinit(), RunOnProof(), and FairRun::~FairRun().
UInt_t FairRun::fRunId protected inherited
Run Id
Definition at line 182 of file FairRun.h.
Referenced by FairRunOnline::EventLoop(), FairRunOnline::getRunId(), FairRunAna::getRunId(), FairRun::GetRunId(), Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), RunOneEvent(), and FairRun::SetRunId().
TMCThreadLocal FairRun * FairRun::fRunInstance = 0 static protected inherited
static pointer to this run
Definition at line 167 of file FairRun.h.
Referenced by FairRun::FairRun(), and FairRun::Instance().
Bool_t FairRunAnaProof::fRunOnProofWorker protected
executing on PROOF worker
Definition at line 74 of file FairRunAnaProof.h.
Referenced by FairRunAnaProof(), Init(), and SetRunOnProofWorker().
Bool_t FairRunAna::fStatic protected inherited
true for static initialisation of parameters
Definition at line 173 of file FairRunAna.h.
Referenced by FairRunAna::GetContainerStatic(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), RunOneEvent(), RunOnProof(), and FairRunAna::SetContainerStatic().
FairTask* FairRun::fTask protected inherited
Tasks used
Definition at line 174 of file FairRun.h.
Referenced by FairRun::AddTask(), FairRunAna::DummyRun(), FairRunOnline::EventLoop(), FairRunOnline::Finish(), FairRun::GetMainTask(), FairRun::GetTask(), Init(), FairRunAna::Init(), FairRunOnline::Init(), FairRunSim::Init(), FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), RunOneEvent(), FairRunAna::RunOnLmdFiles(), RunOnProof(), FairRunAna::RunTSBuffers(), FairRun::SetTask(), FairRunAna::TerminateRun(), and FairRun::~FairRun().
TF1* FairRunAna::fTimeProb protected inherited
used to generate random numbers for event time;
Definition at line 188 of file FairRunAna.h.
Bool_t FairRunAna::fTimeStamps protected inherited
Definition at line 175 of file FairRunAna.h.
Referenced by Init(), FairRunAna::Init(), FairRunAna::IsTimeStamp(), FairRunAna::Run(), RunOneEvent(), and FairRunAna::RunWithTimeStamps().
The documentation for this class was generated from the following files:
FairRunAnaProof.h
FairRunAnaProof.cxx