FairRoot: FairContFact Class Reference
FairContFact Class Reference
#include <FairContFact.h>
Public Member Functions
FairContFact ()
virtual ~FairContFact ()
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual FairParSet * createContainer (FairContainer *)
virtual void activateParIo (FairParIo *)
Protected Member Functions
const char * getActualContext (const char *name)
ClassDef(FairContFact, 0) private FairContFact & operator= (const FairContFact &)
Protected Attributes
TList * containers
FairLogger * fLogger
Detailed Description
Definition at line 48 of file FairContFact.h.
Constructor & Destructor Documentation
FairContFact::FairContFact ()
Definition at line 143 of file FairContFact.cxx.
   : TNamed(),
     containers(new TList),
     fLogger(FairLogger::GetLogger())
 {
   // Constructor creates a list to store objects of type FairContainer
   //  containers=new TList;
 }
FairContFact::~FairContFact () virtual
Definition at line 152 of file FairContFact.cxx.
References containers.
 {
   // Destructor deletes the container list and its elements
   containers->Delete();
   delete containers;
 }
Member Function Documentation
virtual void FairContFact::activateParIo (FairParIo *) inline virtual
Definition at line 57 of file FairContFact.h.
Referenced by FairRuntimeDb::activateParIo().
 {}
Bool_t FairContFact::addContext (const char * name)
Definition at line 159 of file FairContFact.cxx.
References containers, and FairContainer::setActualContext().
Referenced by FairRuntimeDb::addParamContext().
 {
   // Set the actual context in all containers, which accept this context
   FairContainer* c=0;
   Bool_t found=kFALSE;
   TIter next(containers);
   while ((c=(FairContainer*)next())) {
     if (c->setActualContext(name)) { found=kTRUE; }
   }
   return found;
 }
virtual FairParSet* FairContFact::createContainer (FairContainer *) inline virtual
Reimplemented in FairDbTutContFact, FairDbTutContFact2, FairBaseContFact, MyPassiveContFact, FairTestDetectorContFact, FairTestDetectorContFact, FairPassiveContFact, FairRutherfordContFact, FairTutorialDet1ContFact, FairTutorialDet4ContFact, FairTutorialDet2ContFact, NewDetectorContFact, and NewDetectorContFact.
Definition at line 56 of file FairContFact.h.
Referenced by getContainer().
 {return 0;}
const char* FairContFact::getActualContext (const char * name) inline protected
Definition at line 61 of file FairContFact.h.
{
       return ((FairContainer*)containers->FindObject(name))->getActualContext();
     }
FairParSet * FairContFact::getContainer (const char * name)
Definition at line 171 of file FairContFact.cxx.
References FairRuntimeDb::addContainer(), containers, createContainer(), FairRuntimeDb::findContainer(), FairContainer::getActualContext(), FairContainer::getConcatName(), FairContainer::getDefaultContext(), FairRuntimeDb::instance(), and FairContainer::setActualContext().
Referenced by FairRuntimeDb::getContainer().
 {
   // Returns the pointer to the parameter container in the runtime database
   // If this parameter container does not yet exit, it calls the function
   // createContainer(FairContainer*), which is implemented in the derived classes
   // and calls the corresponding constructor. Then the pointer it added in the
   // runtime database.
   FairContainer* c=(FairContainer*)(containers->FindObject(name));
   FairParSet* cont=0;
   if (c) {
     TString cn=c->getConcatName();
     FairRuntimeDb* rtdb = FairRuntimeDb::instance();
     if (!(cont=rtdb->findContainer(c->getConcatName().Data()))) {
       if (strlen(c->getActualContext())==0) { c->setActualContext(c->getDefaultContext()); }
       cont=createContainer(c);
       if (cont) { rtdb->addContainer(cont); }
     }
   }
   return cont;
 }
ClassDef (FairContFact,0) private FairContFact& FairContFact::operator= (const FairContFact &) protected
void FairContFact::print ()
Definition at line 193 of file FairContFact.cxx.
References containers, and FairContainer::print().
Referenced by FairRuntimeDb::printParamContexts().
 {
   // Loops over all containers in the list and calls their print() function
   cout<<"---------------------------------------------------------------------------"<<"\n";
   cout<<GetName()<<":  "<<GetTitle()<<"\n";
   cout<<"---------------------------------------------------------------------------"<<"\n";
   FairContainer* c;
   TIter next(containers);
   while ((c=(FairContainer*)next())) { c->print(); }
 }
Member Data Documentation
TList* FairContFact::containers protected
Definition at line 60 of file FairContFact.h.
Referenced by addContext(), getContainer(), print(), FairTutorialDet2ContFact::setAllContainers(), NewDetectorContFact::setAllContainers(), FairTutorialDet4ContFact::setAllContainers(), FairTutorialDet1ContFact::setAllContainers(), FairRutherfordContFact::setAllContainers(), FairTestDetectorContFact::setAllContainers(), FairBaseContFact::setAllContainers(), and ~FairContFact().
FairLogger* FairContFact::fLogger protected
Fair Logger
Definition at line 65 of file FairContFact.h.
The documentation for this class was generated from the following files:
FairContFact.h
FairContFact.cxx