FairRroot: FairRtdbRun Class Reference
FairRtdbRun Class Reference
#include <FairRtdbRun.h>
Public Member Functions
FairRtdbRun ()
name of the reference run for initialization
FairRtdbRun (const Text_t *name, const Text_t *refName="")
FairRtdbRun (Int_t r, Int_t rr=-1)
FairRtdbRun (FairRtdbRun &run)
~FairRtdbRun ()
UInt_t getRunId (void)
void addParVersion (FairParVersion *pv)
FairParVersion * getParVersion (const Text_t *name)
TList * getParVersions ()
const Text_t * getRefRun ()
void setRefRun (Text_t *s)
void setRefRun (Int_t r)
void resetInputVersions ()
void resetOutputVersions ()
void print ()
void write (fstream &)
Protected Attributes
TList * parVersions
TString refRun
Private Member Functions
FairRtdbRun & operator= (const FairRtdbRun &)
Detailed Description
Definition at line 47 of file FairRtdbRun.h.
Constructor & Destructor Documentation
FairRtdbRun::FairRtdbRun ()
name of the reference run for initialization
Definition at line 86 of file FairRtdbRun.cxx.
   :TNamed(),
    parVersions(NULL),
    refRun("")
 {
   // default Constructor
   // parVersions has to be set to zero otherwise the
   // root file is not browsable
 }
FairRtdbRun::FairRtdbRun (const Text_t * name, const Text_t * refName = "")
Definition at line 50 of file FairRtdbRun.cxx.
   : TNamed(name,"run parameters"),
     parVersions(new TList()),
     refRun(refName)
 {
   // constructor with the run id and reference run as strings
   //  parVersions=new TList();
   //  refRun=refName;
 }
FairRtdbRun::FairRtdbRun (Int_t r, Int_t rr = -1)
Definition at line 60 of file FairRtdbRun.cxx.
References setRefRun().
   :TNamed(),
    parVersions(new TList()),
    refRun("")
 {
   char name[255];
   sprintf(name,"%i",r);
   SetName(name);
   setRefRun(rr);
 }
FairRtdbRun::FairRtdbRun (FairRtdbRun & run)
Definition at line 72 of file FairRtdbRun.cxx.
References getParVersions(), and parVersions.
   :TNamed(run),
    parVersions(new TList()),
    refRun(run.refRun)
 {
   // copy constructor
   TList* lv=run.getParVersions();
   TIter next(lv);
   FairParVersion* pv;
   while ((pv=(FairParVersion*)next())) {
     parVersions->Add(pv);
   }
 }
FairRtdbRun::~FairRtdbRun ()
Definition at line 96 of file FairRtdbRun.cxx.
References parVersions.
 {
   // destructor
   if (parVersions) {
     parVersions->Delete();
     delete  parVersions;
     parVersions=0;
   }
 }
Member Function Documentation
void FairRtdbRun::addParVersion (FairParVersion * pv)
Definition at line 106 of file FairRtdbRun.cxx.
References parVersions.
Referenced by FairRuntimeDb::addContainer(), and FairRuntimeDb::addRun().
 {
   // adds a container version object to the list
   parVersions->Add(pv);
 }
FairParVersion * FairRtdbRun::getParVersion (const Text_t * name)
Definition at line 112 of file FairRtdbRun.cxx.
References parVersions.
Referenced by FairRuntimeDb::addContainer(), FairDetParRootFileIo::findInputVersion(), FairRuntimeDb::findOutputVersion(), FairRuntimeDb::setInputVersion(), FairRuntimeDb::setRootOutputVersion(), and FairRuntimeDb::writeContainer().
 {
   // return a container version object called by the name of
   // the container
   return (FairParVersion*)parVersions->FindObject(name);
 }
TList* FairRtdbRun::getParVersions () inline
Definition at line 61 of file FairRtdbRun.h.
References parVersions.
Referenced by FairRtdbRun().
 {return parVersions;}
const Text_t* FairRtdbRun::getRefRun () inline
Definition at line 62 of file FairRtdbRun.h.
Referenced by FairRuntimeDb::initContainers(), and FairRuntimeDb::writeContainers().
 {return refRun.Data();}
UInt_t FairRtdbRun::getRunId (void) inline
Definition at line 78 of file FairRtdbRun.h.
Referenced by FairRuntimeDb::initContainers().
 {
   UInt_t r;
   sscanf(GetName(),"%i",&r);
   return r;
 }
FairRtdbRun& FairRtdbRun::operator= (const FairRtdbRun &) private
void FairRtdbRun::print ()
Definition at line 137 of file FairRtdbRun.cxx.
References FairParVersion::getInputVersion(), FairParVersion::getRootVersion(), and parVersions.
Referenced by FairRuntimeDb::print().
 {
   // prints the list of container versions for this run
   cout<<"run: "<<GetName()<<'\n';
   FairParVersion* v;
   TIter next(parVersions);
   while ((v=(FairParVersion*)next())) {
     cout.setf(ios::left,ios::adjustfield);
     cout<<"  "<<setw(45)<<v->GetName();
     cout.setf(ios::right,ios::adjustfield);
     cout<<setw(11)<<v->getInputVersion(1)
         <<setw(11)<<v->getInputVersion(2)
         <<setw(11)<<v->getRootVersion()<<'\n';
   }
 }
void FairRtdbRun::resetInputVersions ()
Definition at line 119 of file FairRtdbRun.cxx.
References parVersions, and FairParVersion::resetInputVersions().
Referenced by FairRuntimeDb::resetInputVersions().
 {
   TIter next(parVersions);
   FairParVersion* v;
   while ((v=(FairParVersion*)next())) {
     v->resetInputVersions();
   }
 }
void FairRtdbRun::resetOutputVersions ()
Definition at line 128 of file FairRtdbRun.cxx.
References parVersions, and FairParVersion::setRootVersion().
Referenced by FairRuntimeDb::resetOutputVersions().
 {
   TIter next(parVersions);
   FairParVersion* v;
   while ((v=(FairParVersion*)next())) {
     v->setRootVersion(0);
   }
 }
void FairRtdbRun::setRefRun (Text_t * s) inline
Definition at line 63 of file FairRtdbRun.h.
Referenced by FairRtdbRun(), and FairRuntimeDb::initContainers().
 {refRun=s;}
void FairRtdbRun::setRefRun (Int_t r) inline
Definition at line 85 of file FairRtdbRun.h.
References refRun.
 {
   if (r==-1) { refRun=""; }
   else {
     char name[255];
     sprintf(name,"%i",r);
     refRun=name;
   }
 }
void FairRtdbRun::write (fstream & fout)
Definition at line 153 of file FairRtdbRun.cxx.
References FairParVersion::getInputVersion(), FairParVersion::getRootVersion(), and parVersions.
 {
   // writes the list of container versions for this run to fstream
   fout<<"run: "<<GetName()<<'\n';
   FairParVersion* v;
   TIter next(parVersions);
   while ((v=(FairParVersion*)next())) {
     fout.setf(ios::left,ios::adjustfield);
     fout<<"  "<<setw(45)<<v->GetName();
     fout.setf(ios::right,ios::adjustfield);
     fout<<setw(11)<<v->getInputVersion(1)
         <<setw(11)<<v->getInputVersion(2)
         <<setw(11)<<v->getRootVersion()<<'\n';
   }
 }
Member Data Documentation
TList* FairRtdbRun::parVersions protected
Definition at line 50 of file FairRtdbRun.h.
Referenced by addParVersion(), FairRtdbRun(), getParVersion(), getParVersions(), print(), resetInputVersions(), resetOutputVersions(), write(), and ~FairRtdbRun().
TString FairRtdbRun::refRun protected
Definition at line 51 of file FairRtdbRun.h.
Referenced by setRefRun().
The documentation for this class was generated from the following files:
FairRtdbRun.h
FairRtdbRun.cxx