FairRoot: FairTutorialDet4Point Class Reference
FairTutorialDet4Point Class Reference
#include <FairTutorialDet4Point.h>
Public Member Functions
FairTutorialDet4Point ()
FairTutorialDet4Point (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss)
virtual ~FairTutorialDet4Point ()
virtual void Print (const Option_t *opt) const
UInt_t GetEventID () const
Int_t GetTrackID () const
event identifier
Double_t GetPx () const
Double_t GetPy () const
Double_t GetPz () const
Double_t GetTime () const
Double_t GetLength () const
Double_t GetEnergyLoss () const
void Momentum (TVector3 &mom)
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetEventID (UInt_t eventId)
virtual void SetTrackID (Int_t id)
void SetTime (Double_t time)
void SetLength (Double_t length)
void SetEnergyLoss (Double_t eLoss)
void SetMomentum (const TVector3 &mom)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
std::ostream & Print (std::ostream &out=std::cout) const
Output.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
returns all FairLinks with the corresponding type
virtual FairLink GetEntryNr () const
virtual FairMultiLinkedData * GetPointerToLinks () const
virtual void SetLinks (FairMultiLinkedData links)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link)
Sets the Links with a single FairLink.
virtual void SetInsertHistory (Bool_t val)
virtual void SetEntryNr (FairLink val)
virtual void SetPointerToLinks (FairMultiLinkedData *links)
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
virtual void AddLink (FairLink link)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
virtual void AddInterfaceData (FairMultiLinkedData_Interface *data)
virtual void ResetLinks ()
Protected Member Functions
FairMultiLinkedData * CreateFairMultiLinkedData ()
ClassDef (FairMultiLinkedData_Interface, 5)
Protected Attributes
Int_t fTrackID
Track index.
UInt_t fEventId
MC Event id.
Double32_t fPx
Double32_t fPy
Double32_t fPz
Momentum components [GeV].
Double32_t fTime
Time since event start [ns].
Double32_t fLength
Track length since creation [cm].
Double32_t fELoss
Energy loss at this point [GeV].
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
Int_t fVerbose
FairMultiLinkedData * fLink
Detailed Description
Definition at line 16 of file FairTutorialDet4Point.h.
Constructor & Destructor Documentation
FairTutorialDet4Point::FairTutorialDet4Point ()
Default constructor
Definition at line 13 of file FairTutorialDet4Point.cxx.
   : FairMCPoint()
 {
 }
FairTutorialDet4Point::FairTutorialDet4Point (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss)
Constructor with arguments
Parameters
trackID Index of MCTrack
detID Detector ID
pos Ccoordinates at entrance to active volume [cm]
mom Momentum of track at entrance [GeV]
tof Time since event start [ns]
length Track length since creation [cm]
eLoss Energy deposit [GeV]
Definition at line 20 of file FairTutorialDet4Point.cxx.
   : FairMCPoint(trackID, detID, pos, mom, tof, length, eLoss)
 {
 }
FairTutorialDet4Point::~FairTutorialDet4Point () virtual
Copy constructor Destructor
Definition at line 30 of file FairTutorialDet4Point.cxx.
 { }
Member Function Documentation
void FairMultiLinkedData_Interface::AddInterfaceData (FairMultiLinkedData_Interface * data) virtual inherited
Definition at line 163 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairLink::GetType(), and FairMultiLinkedData_Interface::SetInsertHistory().
 {
         SetInsertHistory(kFALSE); //todo add previous history value
         if (data->GetEntryNr().GetType() != -1)
                 AddLink(data->GetEntryNr());
         else
                 std::cout
                                 << "-E- FairMultiLinkedData_Interface::AddInterfaceData EntryNr == "
                                 << data->GetEntryNr() << std::endl;
         if (data->GetPointerToLinks() != 0) {
                 AddLinks(*data->GetPointerToLinks());
         }
         SetInsertHistory(kTRUE);
 }
void FairMultiLinkedData_Interface::AddLink (FairLink link) virtual inherited
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise.
Definition at line 154 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLink(link);
         }
 }
void FairMultiLinkedData_Interface::AddLinks (FairMultiLinkedData links, Float_t mult = 1.0) virtual inherited
Adds a List of FairLinks (FairMultiLinkedData_Interface) to fLinks.
Definition at line 146 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::AddLinks(), FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->AddLinks(links, mult);
         }
 }
FairMultiLinkedData_Interface::ClassDef (FairMultiLinkedData_Interface , 5) protected inherited
FairMultiLinkedData * FairMultiLinkedData_Interface::CreateFairMultiLinkedData () protected inherited
Definition at line 62 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::fLink, and FairRootManager::Instance().
Referenced by FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
 {
         if (FairRootManager::Instance()->GetUseFairLinks()){
                 if (fLink == 0){
                         fLink = new FairMultiLinkedData();
                 }
                 return fLink;
         }
         return 0;
 }
Int_t FairMCPoint::GetDetectorID () const inline inherited
Definition at line 65 of file FairMCPoint.h.
References FairMCPoint::fDetectorID.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), and FairTutorialDet4HitProducerIdealMisalign::Exec().
 { return fDetectorID;             };
Double_t FairMCPoint::GetEnergyLoss () const inline inherited
Definition at line 63 of file FairMCPoint.h.
References FairMCPoint::fELoss.
 { return fELoss; }
FairLink FairMultiLinkedData_Interface::GetEntryNr () const virtual inherited
Reimplemented in FairTimeStamp.
Definition at line 102 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetEntryNr(), and FairMultiLinkedData_Interface::GetPointerToLinks().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
 {
         if (GetPointerToLinks() != 0) {
                 return GetPointerToLinks()->GetEntryNr();
         } else {
                 FairLink emptyLink;
                 return emptyLink;
         }
 }
UInt_t FairMCPoint::GetEventID () const inline inherited
Accessors
Definition at line 56 of file FairMCPoint.h.
References FairMCPoint::fEventId.
 { return fEventId; }
Double_t FairMCPoint::GetLength () const inline inherited
Definition at line 62 of file FairMCPoint.h.
References FairMCPoint::fLength.
 { return fLength; }
FairLink FairMultiLinkedData_Interface::GetLink (Int_t pos) const virtual inherited
returns the FairLink at the given position
Definition at line 92 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLink(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLink(pos);
         } else {
                 FairLink emptyLink;
                 return emptyLink;
         }
 }
std::set< FairLink > FairMultiLinkedData_Interface::GetLinks () const virtual inherited
returns stored links as FairLinks
Definition at line 73 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinks();
         } else {
                 std::set<FairLink> emptySet;
                 return emptySet;
         }
 }
FairMultiLinkedData FairMultiLinkedData_Interface::GetLinksWithType (Int_t type) const virtual inherited
returns all FairLinks with the corresponding type
Definition at line 112 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetLinksWithType(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetLinksWithType(type);
         } else {
                 FairMultiLinkedData emptyLinks;
                 return emptyLinks;
         }
 }
Int_t FairMultiLinkedData_Interface::GetNLinks () const virtual inherited
returns the number of stored links
Definition at line 83 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData::GetNLinks(), and FairMultiLinkedData_Interface::GetPointerToLinks().
 {
         if (GetPointerToLinks() != 0){
                 return GetPointerToLinks()->GetNLinks();
         } else {
                 return 0;
         }
 }
virtual FairMultiLinkedData* FairMultiLinkedData_Interface::GetPointerToLinks () const inline virtual inherited
Definition at line 47 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
Referenced by FairMultiLinkedData_Interface::AddInterfaceData(), FairMultiLinkedData_Interface::AddLink(), FairMultiLinkedData_Interface::AddLinks(), FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), FairMultiLinkedData_Interface::GetEntryNr(), FairMultiLinkedData_Interface::GetLink(), FairMultiLinkedData_Interface::GetLinks(), FairMultiLinkedData_Interface::GetLinksWithType(), FairMultiLinkedData_Interface::GetNLinks(), FairMultiLinkedData_Interface::operator=(), FairMultiLinkedData_Interface::Print(), FairMultiLinkedData_Interface::ResetLinks(), FairMultiLinkedData_Interface::SetEntryNr(), FairMultiLinkedData_Interface::SetInsertHistory(), FairMultiLinkedData_Interface::SetLink(), and FairMultiLinkedData_Interface::SetLinks().
 {       return fLink;}
Double_t FairMCPoint::GetPx () const inline inherited
Definition at line 58 of file FairMCPoint.h.
References FairMCPoint::fPx.
 { return fPx; }
Double_t FairMCPoint::GetPy () const inline inherited
Definition at line 59 of file FairMCPoint.h.
References FairMCPoint::fPy.
 { return fPy; }
Double_t FairMCPoint::GetPz () const inline inherited
Definition at line 60 of file FairMCPoint.h.
References FairMCPoint::fPz.
 { return fPz; }
Double_t FairMCPoint::GetTime () const inline inherited
Definition at line 61 of file FairMCPoint.h.
References FairMCPoint::fTime.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), and FairTutorialDet4HitProducerIdealMisalign::Exec().
 { return fTime; }
Int_t FairMCPoint::GetTrackID () const inline inherited
event identifier
Definition at line 57 of file FairMCPoint.h.
References FairMCPoint::fTrackID.
Referenced by FairTutorialDet4HitProducerIdealMisalign::Exec(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
 { return fTrackID; }
Double_t FairMCPoint::GetX () const inline inherited
Definition at line 66 of file FairMCPoint.h.
References FairMCPoint::fX.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
 { return fX;                      };
Double_t FairMCPoint::GetY () const inline inherited
Definition at line 67 of file FairMCPoint.h.
References FairMCPoint::fY.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
 { return fY;                      };
Double_t FairMCPoint::GetZ () const inline inherited
Definition at line 68 of file FairMCPoint.h.
References FairMCPoint::fZ.
Referenced by FairTestDetectorDigiTask::Exec(), FairTestDetectorTimeDigiTask::Exec(), FairTutorialDet4HitProducerIdealMisalign::Exec(), FairMCPointDraw::GetVector(), and FairTimeStampPointDraw::GetVector().
 { return fZ;                      };
void FairMCPoint::Momentum (TVector3 & mom) inline inherited
Definition at line 64 of file FairMCPoint.h.
References FairMCPoint::fPx, FairMCPoint::fPy, and FairMCPoint::fPz.
 { mom.SetXYZ(fPx, fPy, fPz); }
void FairMCPoint::Position (TVector3 & pos) const inline inherited
Definition at line 140 of file FairMCPoint.h.
References FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
Referenced by FairTestDetectorHitProducerSmearing::Exec().
 {
   pos.SetXYZ(fX, fY, fZ);
 }
void FairTutorialDet4Point::Print (const Option_t * opt) const virtual
Output to screen
Reimplemented from FairMCPoint.
Definition at line 34 of file FairTutorialDet4Point.cxx.
References FairLogger::endl(), FairMCPoint::fDetectorID, FairMCPoint::fELoss, FairMCPoint::fLength, FairMCPoint::fPx, FairMCPoint::fPy, FairMCPoint::fPz, FairMCPoint::fTime, FairMCPoint::fTrackID, FairMCPoint::fX, FairMCPoint::fY, FairMCPoint::fZ, INFO, and LOG.
 {
   LOG(INFO) << "-I- FairTutorialDet4Point: TutorialDet point for track "
             << fTrackID
             << " in detector " << fDetectorID << FairLogger::endl;
   LOG(INFO) << "    Position (" << fX << ", " << fY << ", " << fZ
             << ") cm" << FairLogger::endl;
   LOG(INFO) << "    Momentum (" << fPx << ", " << fPy << ", " << fPz
             << ") GeV" << FairLogger::endl;
   LOG(INFO) << "    Time " << fTime << " ns,  Length " << fLength
             << " cm,  Energy loss " << fELoss*1.0e06 << " keV"
             << FairLogger::endl;
 }
std::ostream& FairMultiLinkedData_Interface::Print (std::ostream & out = std::cout) const inline inherited
Output.
Definition at line 64 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::Print().
Referenced by FairTimeStamp::Print().
void FairMultiLinkedData_Interface::ResetLinks () virtual inherited
Definition at line 185 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::ResetLinks().
 {
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->ResetLinks();
         }
 }
template<class Archive > void FairMCPoint::serialize (Archive & ar, const unsigned int version) inline inherited
Definition at line 95 of file FairMCPoint.h.
References FairMCPoint::fDetectorID, FairMCPoint::fELoss, FairMCPoint::fEventId, FairMCPoint::fLength, FairMCPoint::fPx, FairMCPoint::fPy, FairMCPoint::fPz, FairMCPoint::fTime, FairMCPoint::fTrackID, FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
     {
         //ar & boost::serialization::base_object<FairMultiLinkedData>(*this);
         ar & fTrackID;
         ar & fEventId;
         ar & fDetectorID;
         ar & fX;
         ar & fY;
         ar & fZ;
         ar & fPx;
         ar & fPy;
         ar & fPz;
         ar & fTime;
         ar & fLength;
         ar & fELoss;
     }
void FairMCPoint::SetDetectorID (Int_t detID) inline inherited
Definition at line 81 of file FairMCPoint.h.
References FairMCPoint::fDetectorID.
 { fDetectorID = detID; }
void FairMCPoint::SetEnergyLoss (Double_t eLoss) inline inherited
Definition at line 79 of file FairMCPoint.h.
References FairMCPoint::fELoss.
 { fELoss = eLoss; }
void FairMultiLinkedData_Interface::SetEntryNr (FairLink val) virtual inherited
Reimplemented in FairTimeStamp.
Definition at line 138 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetEntryNr().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0) {
                 GetPointerToLinks()->SetEntryNr(val);
         }
 }
void FairMCPoint::SetEventID (UInt_t eventId) inline inherited
Modifiers
Definition at line 75 of file FairMCPoint.h.
References FairMCPoint::fEventId.
 { fEventId = eventId; }
void FairMultiLinkedData_Interface::SetInsertHistory (Bool_t val) virtual inherited
Definition at line 178 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetInsertHistory().
Referenced by FairMultiLinkedData_Interface::AddInterfaceData().
 {
         if (GetPointerToLinks() != 0) {
                 GetPointerToLinks()->SetInsertHistory(val);
         }
 }
void FairMCPoint::SetLength (Double_t length) inline inherited
Definition at line 78 of file FairMCPoint.h.
References FairMCPoint::fLength.
 { fLength = length; }
void FairMultiLinkedData_Interface::SetLink (FairLink link) virtual inherited
Sets the Links with a single FairLink.
Definition at line 130 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLink().
Referenced by FairTestDetectorTimeRecoTask::Exec(), MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLink(link);
         }
 }
void FairMultiLinkedData_Interface::SetLinks (FairMultiLinkedData links) virtual inherited
Sets the links as vector of FairLink.
Parameters
type as Int_t gives one type of source data for all indices
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
type as vector<Int_t> gives the type of source data (TClonesArray)
links as vector<Int_t> gives the vector of indices at which position in the TClonesArray the source data is stored
Definition at line 122 of file FairMultiLinkedData_Interface.cxx.
References FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), and FairMultiLinkedData::SetLinks().
Referenced by FairMultiLinkedData_Interface::FairMultiLinkedData_Interface(), and FairMultiLinkedData_Interface::operator=().
 {
         CreateFairMultiLinkedData();
         if (GetPointerToLinks() != 0){
                 GetPointerToLinks()->SetLinks(links);
         }
 }
void FairMCPoint::SetMomentum (const TVector3 & mom) inline inherited
Definition at line 134 of file FairMCPoint.h.
References FairMCPoint::fPx, FairMCPoint::fPy, and FairMCPoint::fPz.
 {
   fPx = mom.Px();
   fPy = mom.Py();
   fPz = mom.Pz();
 }
virtual void FairMultiLinkedData_Interface::SetPointerToLinks (FairMultiLinkedData * links) inline virtual inherited
Definition at line 53 of file FairMultiLinkedData_Interface.h.
References FairMultiLinkedData_Interface::fLink.
 {fLink = links;}
void FairMCPoint::SetPosition (const TVector3 & pos) inline inherited
Definition at line 154 of file FairMCPoint.h.
References FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
 {
   fX = pos.X();
   fY = pos.Y();
   fZ = pos.Z();
 }
void FairMCPoint::SetTime (Double_t time) inline inherited
Definition at line 77 of file FairMCPoint.h.
References FairMCPoint::fTime.
 { fTime = time; }
virtual void FairMCPoint::SetTrackID (Int_t id) inline virtual inherited
Definition at line 76 of file FairMCPoint.h.
References FairMCPoint::fTrackID.
Referenced by MyProjStack::UpdateTrackIndex(), and FairStack::UpdateTrackIndex().
 { fTrackID = id;}
void FairMCPoint::SetX (Double_t x) inline inherited
Definition at line 82 of file FairMCPoint.h.
References FairMCPoint::fX.
 { fX = x; }
void FairMCPoint::SetXYZ (Double_t x, Double_t y, Double_t z) inline inherited
Definition at line 146 of file FairMCPoint.h.
References FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
 {
   fX = x;
   fY = y;
   fZ = z;
 }
void FairMCPoint::SetY (Double_t y) inline inherited
Definition at line 83 of file FairMCPoint.h.
References FairMCPoint::fY.
 { fY = y; }
void FairMCPoint::SetZ (Double_t z) inline inherited
Definition at line 84 of file FairMCPoint.h.
References FairMCPoint::fZ.
 { fZ = z; }
Member Data Documentation
Int_t FairMCPoint::fDetectorID protected inherited
Detector unique identifier.
Definition at line 125 of file FairMCPoint.h.
Referenced by FairMCPoint::GetDetectorID(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetDetectorID().
Double32_t FairMCPoint::fELoss protected inherited
Energy loss at this point [GeV].
Definition at line 124 of file FairMCPoint.h.
Referenced by FairMCPoint::GetEnergyLoss(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetEnergyLoss().
UInt_t FairMCPoint::fEventId protected inherited
MC Event id.
Definition at line 120 of file FairMCPoint.h.
Referenced by FairMCPoint::GetEventID(), FairMCPoint::serialize(), and FairMCPoint::SetEventID().
Double32_t FairMCPoint::fLength protected inherited
Track length since creation [cm].
Definition at line 123 of file FairMCPoint.h.
Referenced by FairMCPoint::GetLength(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetLength().
FairMultiLinkedData* FairMultiLinkedData_Interface::fLink protected inherited
Definition at line 79 of file FairMultiLinkedData_Interface.h.
Referenced by FairMultiLinkedData_Interface::CreateFairMultiLinkedData(), FairMultiLinkedData_Interface::GetPointerToLinks(), FairMultiLinkedData_Interface::SetPointerToLinks(), and FairMultiLinkedData_Interface::~FairMultiLinkedData_Interface().
Double32_t FairMCPoint::fPx protected inherited
Definition at line 121 of file FairMCPoint.h.
Referenced by FairMCPoint::GetPx(), FairTestDetectorPoint::GetPxIn(), FairMCPoint::Momentum(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTestDetectorPoint::Print(), Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetMomentum().
Double32_t FairMCPoint::fPy protected inherited
Definition at line 121 of file FairMCPoint.h.
Referenced by FairMCPoint::GetPy(), FairTestDetectorPoint::GetPyIn(), FairMCPoint::Momentum(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTestDetectorPoint::Print(), Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetMomentum().
Double32_t FairMCPoint::fPz protected inherited
Momentum components [GeV].
Definition at line 121 of file FairMCPoint.h.
Referenced by FairMCPoint::GetPz(), FairTestDetectorPoint::GetPzIn(), FairMCPoint::Momentum(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTestDetectorPoint::Print(), Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetMomentum().
Double32_t FairMCPoint::fTime protected inherited
Time since event start [ns].
Definition at line 122 of file FairMCPoint.h.
Referenced by FairMCPoint::GetTime(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetTime().
Int_t FairMCPoint::fTrackID protected inherited
Track index.
Definition at line 119 of file FairMCPoint.h.
Referenced by FairMCPoint::GetTrackID(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), Print(), FairTutorialDet1Point::Print(), FairTestDetectorPoint::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), and FairMCPoint::SetTrackID().
Int_t FairMultiLinkedData_Interface::fVerbose protected inherited
Definition at line 78 of file FairMultiLinkedData_Interface.h.
Double32_t FairMCPoint::fX protected inherited
Definition at line 126 of file FairMCPoint.h.
Referenced by FairRadLenPoint::GetPosition(), FairRadMapPoint::GetPosition(), FairMCPoint::GetX(), FairTestDetectorPoint::GetXIn(), FairMCPoint::Position(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), FairMCPoint::SetPosition(), FairMCPoint::SetX(), and FairMCPoint::SetXYZ().
Double32_t FairMCPoint::fY protected inherited
Definition at line 126 of file FairMCPoint.h.
Referenced by FairRadLenPoint::GetPosition(), FairRadMapPoint::GetPosition(), FairMCPoint::GetY(), FairTestDetectorPoint::GetYIn(), FairMCPoint::Position(), NewDetectorPoint::Print(), FairRutherfordPoint::Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), FairMCPoint::SetPosition(), FairMCPoint::SetXYZ(), and FairMCPoint::SetY().
Double32_t FairMCPoint::fZ protected inherited
Position of hit [cm].
Definition at line 126 of file FairMCPoint.h.
Referenced by FairMCPoint::GetZ(), FairTestDetectorPoint::GetZIn(), FairMCPoint::Position(), FairRutherfordPoint::Print(), NewDetectorPoint::Print(), Print(), FairTestDetectorPoint::Print(), FairTutorialDet1Point::Print(), FairTutorialDet2Point::Print(), FairMCPoint::Print(), FairMCPoint::serialize(), FairMCPoint::SetPosition(), FairMCPoint::SetXYZ(), and FairMCPoint::SetZ().
The documentation for this class was generated from the following files:
FairTutorialDet4Point.h
FairTutorialDet4Point.cxx