FairRroot: FairGeoRootBuilder Class Reference
FairGeoRootBuilder Class Reference
#include <FairGeoRootBuilder.h>
Public Member Functions
FairGeoRootBuilder ()
FairGeoRootBuilder (const char *, const char *)
~FairGeoRootBuilder ()
void setGeoManager (TGeoManager *me)
Bool_t createNode (FairGeoNode *, Int_t hadFormat=0)
Int_t createMedium (FairGeoMedium *)
void finalize ()
void checkOverlaps (Double_t ovlp=0.0001)
const Int_t & GetNMedia () const
void SetNMedia (const Int_t &nmed)
Protected Attributes
TGeoManager * geoManager
Int_t nRot
Int_t nMed
Private Member Functions
FairGeoRootBuilder (const FairGeoRootBuilder &)
FairGeoRootBuilder & operator= (const FairGeoRootBuilder &)
Detailed Description
class to create geometry in ROOT
Author
M. Al-Turany
Definition at line 23 of file FairGeoRootBuilder.h.
Constructor & Destructor Documentation
FairGeoRootBuilder::FairGeoRootBuilder (const FairGeoRootBuilder &) private
FairGeoRootBuilder::FairGeoRootBuilder ()
FairGeoRootBuilder::FairGeoRootBuilder (const char * name, const char * title)
Definition at line 44 of file FairGeoRootBuilder.cxx.
   : FairGeoBuilder(name,title),
     geoManager(NULL)
 {
   // Constructor
 }
FairGeoRootBuilder::~FairGeoRootBuilder () inline
Definition at line 33 of file FairGeoRootBuilder.h.
 {}
Member Function Documentation
void FairGeoRootBuilder::checkOverlaps (Double_t ovlp = 0.0001)
Definition at line 186 of file FairGeoRootBuilder.cxx.
References geoManager.
 {
   // Checks the geometry for overlaps and extrusions wit a default precision of 1 micron
   if (geoManager) {
     geoManager->CheckOverlaps(ovlp,"SAME");
     geoManager->PrintOverlaps();
   }
 }
Int_t FairGeoRootBuilder::createMedium (FairGeoMedium * med) virtual
Implements FairGeoBuilder.
Definition at line 136 of file FairGeoRootBuilder.cxx.
References geoManager, FairGeoMedium::getComponent(), FairGeoMedium::getDensity(), FairGeoMedium::getMediumPar(), FairGeoMedium::getNComponents(), FairGeoMedium::getRadiationLength(), FairGeoMedium::getWeightFac(), FairGeoBuilder::nMed, and FairGeoMedium::setMediumIndex().
Referenced by createNode().
 {
   // Creates the medium
   if (!geoManager&&!med) { return 0; }
   Int_t nComp=med->getNComponents();
   Int_t weightFac=med->getWeightFac();
   TGeoMaterial* material=0;
   Double_t p[3];
   if (nComp==1) {
     med->getComponent(0,p);
     material=new TGeoMaterial(med->GetName(),p[0],p[1],med->getDensity(),
                               med->getRadiationLength());
     // Interaction length not defined!!!!!!
   } else {
     material=new TGeoMixture(med->GetName(),nComp,med->getDensity());
     Double_t sumWeights=0.;
     if (weightFac<0) {
       for(Int_t i=0; i<nComp; i++) {
         med->getComponent(i,p);
         sumWeights+=p[0]*p[2];
       }
     }
     for(Int_t i=0; i<nComp; i++) {
       med->getComponent(i,p);
       if (weightFac>0) {
         ((TGeoMixture*)material)->DefineElement(i,p[0],p[1],p[2]);
       } else {
         ((TGeoMixture*)material)->DefineElement(i,p[0],p[1],p[0]*p[2]/sumWeights);
       }
     }
   }
   nMed++;
   med->setMediumIndex(nMed);
   Double_t mp[10];
   med->getMediumPar(mp);
   TGeoMedium* medium=new TGeoMedium(med->GetName(),nMed,material,mp);
   if (medium) { return nMed; }
   else { return 0; }
 }
Bool_t FairGeoRootBuilder::createNode (FairGeoNode * volu, Int_t hadFormat = 0) virtual
Implements FairGeoBuilder.
Definition at line 51 of file FairGeoRootBuilder.cxx.
References createMedium(), geoManager, FairGeoNode::getCopyNo(), FairGeoNode::getCopyNode(), FairGeoNode::getMedium(), FairGeoMedium::getMediumIndex(), FairGeoNode::getMotherNode(), FairGeoNode::getParameters(), FairGeoNode::getPosition(), FairGeoNode::getRootVolume(), FairGeoTransform::getRotMatrix(), FairGeoVolume::getShape(), FairGeoTransform::getTransVector(), FairGeoVector::getX(), FairGeoVector::getY(), FairGeoVector::getZ(), FairGeoNode::isModule(), FairGeoNode::isTopNode(), FairGeoBuilder::nRot, FairGeoNode::setCreated(), FairGeoVolume::setHadFormat(), and FairGeoNode::setRootVolume().
 {
   // Creates the volume
   if (!geoManager||!volu) { return kFALSE; }
   //  volu->print();
   TString nodeName= volu->GetName();
   if ( hadFormat == 1 ) {
     volu->setHadFormat( hadFormat );
     nodeName=nodeName(0,4);
   } else {
     nodeName = (volu->GetName());
     Ssiz_t l=nodeName.Last('#');
     if (l>0) { nodeName=nodeName(0,l); }
   }
   FairGeoNode* mother=volu->getMotherNode();
   if (!mother&&!volu->isTopNode()) {
     Error("createNode","Mother volume of %s not found\n",volu->GetName());
     return kFALSE;
   }
   TGeoVolume* rv=0;
   FairGeoNode* cv=volu->getCopyNode();
 //  if (cv) cout<<"Copy of "<<cv->GetName()<<endl;
   if (cv) { rv=cv->getRootVolume(); }
   if (!rv) {
     FairGeoMedium* lmedium=volu->getMedium();
     Int_t lnMed=lmedium->getMediumIndex();
     if (lnMed<=0) { lnMed=createMedium(lmedium); }
     if (lnMed<=0) { return kFALSE; }
     TArrayD* par=volu->getParameters();
     //for (Int_t k=0;k<par->GetSize();k++) cout<<par->At(k)<<" ";
     // cout<<endl;
     //cout << "Create Volume of Shape " << volu->getShape() << endl;
     if (volu->getShape().Contains("TORUS")) { // Torus is missing in the TGeoManager::Volume
       // this should solve the problem tell it is implimented in root
       TGeoMedium* medium =geoManager->GetMedium(lnMed);
       rv = geoManager->MakeTorus(nodeName.Data(),medium,par->At(0),par->At(1),par->At(2),par->At(3),par->At(4));
       // cout << "Create Torus" << nodeName.Data() << endl;
     } else if (volu->getShape().Contains("ASSEMBLY")) {
       rv=geoManager->MakeVolumeAssembly(nodeName.Data());
     } else {
       rv=geoManager->Volume(nodeName.Data(),volu->getShape().Data(),
                             lnMed,par->GetArray(),par->GetSize());
     }
     volu->setCreated();
     if (volu->isModule()&&cv) {
       cv->setCreated();
       cv->setRootVolume(rv);
       cv->getPosition();
     }
   }
   if (!rv) { return kFALSE; }
   volu->setRootVolume(rv);
   if (volu->isTopNode()) { geoManager->SetTopVolume(rv); }
   else {
     FairGeoTransform* trans=volu->getPosition();
     const FairGeoRotation& rot=trans->getRotMatrix();
     const FairGeoVector& pos=trans->getTransVector();
     TGeoMatrix* tr=0;
     if (((FairGeoRotation&)rot).isUnitMatrix()) {
       tr=new TGeoTranslation(pos.getX(),pos.getY(),pos.getZ());
     } else {
       nRot++;
       char b[10];
       sprintf(b,"R%i",nRot);
       TGeoRotation* r=new TGeoRotation(b);
       Double_t a[9];
       for (Int_t i=0; i<9; i++) { a[i]=rot(i); }
       r->SetMatrix(a);
       tr=new TGeoCombiTrans(pos.getX(),pos.getY(),pos.getZ(),r);
     }
     TGeoVolume* mo=mother->getRootVolume();
     if (!mo) { return kFALSE; }
     mo->AddNode(rv,volu->getCopyNo(),tr);
   }
   return kTRUE;
 }
void FairGeoRootBuilder::finalize () virtual
Reimplemented from FairGeoBuilder.
Definition at line 176 of file FairGeoRootBuilder.cxx.
References geoManager.
 {
   // Closes the geometry input in ROOT and draws the cave
   if (geoManager) {
     geoManager->CloseGeometry();
     geoManager->SetVisLevel(5);
     geoManager->GetTopVolume()->Draw();
   }
 }
const Int_t& FairGeoBuilder::GetNMedia () const inline inherited
Definition at line 35 of file FairGeoBuilder.h.
References FairGeoBuilder::nMed.
Referenced by FairModule::ReAssignMediaId().
 { return nMed; }
FairGeoRootBuilder& FairGeoRootBuilder::operator= (const FairGeoRootBuilder &) private
void FairGeoRootBuilder::setGeoManager (TGeoManager * me) inline
Definition at line 34 of file FairGeoRootBuilder.h.
 {geoManager=me;}
void FairGeoBuilder::SetNMedia (const Int_t & nmed) inline inherited
Definition at line 36 of file FairGeoBuilder.h.
Referenced by FairModule::ReAssignMediaId().
 { nMed = nmed; }
Member Data Documentation
TGeoManager* FairGeoRootBuilder::geoManager protected
Definition at line 29 of file FairGeoRootBuilder.h.
Referenced by checkOverlaps(), createMedium(), createNode(), and finalize().
Int_t FairGeoBuilder::nMed protected inherited
Definition at line 26 of file FairGeoBuilder.h.
Referenced by createMedium(), and FairGeoBuilder::GetNMedia().
Int_t FairGeoBuilder::nRot protected inherited
Definition at line 25 of file FairGeoBuilder.h.
Referenced by createNode().
The documentation for this class was generated from the following files:
FairGeoRootBuilder.h
FairGeoRootBuilder.cxx