FairRoot: FairGeoMedia Class Reference
FairGeoMedia Class Reference
#include <FairGeoMedia.h>
Public Member Functions
FairGeoMedia ()
~FairGeoMedia ()
void setInputFile (const char *file)
const char * getInputFile ()
void addMedium (FairGeoMedium *m)
FairGeoMedium * getMedium (const char *)
TList * getListOfMedia ()
void read (std::fstream &)
void print ()
void list ()
void write (std::fstream &)
void setAuthor (TString &s)
void setDescription (TString &s)
TString & getAuthor ()
TString & getDescription ()
Private Member Functions
FairGeoMedia (const FairGeoMedia &)
FairGeoMedia & operator= (const FairGeoMedia &)
Private Attributes
TList * media
TString inputFile
TString author
TString description
Detailed Description
Class for materials and media
Author
Ilse koenig
Definition at line 26 of file FairGeoMedia.h.
Constructor & Destructor Documentation
FairGeoMedia::FairGeoMedia ()
description of the version
FairGeoMedia::~FairGeoMedia ()
Definition at line 41 of file FairGeoMedia.cxx.
References media.
 {
   // Destructor
   if (media) {
     media->Delete();
     delete media;
     media=0;
   }
 }
FairGeoMedia::FairGeoMedia (const FairGeoMedia &) private
Member Function Documentation
void FairGeoMedia::addMedium (FairGeoMedium * m)
Definition at line 57 of file FairGeoMedia.cxx.
References media.
Referenced by FairGeoCave::read(), MyGeoCave::read(), and FairGeoOldAsciiIo::read().
 {
   // Adds a medium to the list of media
   media->Add(m);
 }
TString& FairGeoMedia::getAuthor () inline
Definition at line 47 of file FairGeoMedia.h.
References author.
 {return author;}
TString& FairGeoMedia::getDescription () inline
Definition at line 48 of file FairGeoMedia.h.
References description.
 {return description;}
const char* FairGeoMedia::getInputFile () inline
Definition at line 37 of file FairGeoMedia.h.
References inputFile.
Referenced by FairGeoInterface::readMedia().
 { return inputFile; }
TList* FairGeoMedia::getListOfMedia () inline
Definition at line 40 of file FairGeoMedia.h.
References media.
Referenced by FairMCApplication::ConstructOpGeometry().
 {return media;}
FairGeoMedium * FairGeoMedia::getMedium (const char * mediumName)
Definition at line 51 of file FairGeoMedia.cxx.
References media.
Referenced by FairModule::AssignMediumAtImport(), FairPipe::ConstructGeometry(), FairGeoCave::read(), MyGeoCave::read(), FairGeoOldAsciiIo::read(), and FairGeoSet::readVolumeParams().
 {
   // Returns the medium with name mediumName
   return (FairGeoMedium*)media->FindObject(mediumName);
 }
void FairGeoMedia::list ()
Definition at line 63 of file FairGeoMedia.cxx.
References media.
Referenced by FairGeoInterface::print().
 {
   // Lists all media
   cout<<"********************************************************************\n";
   cout<<"List of media:\n";
   TListIter iter(media);
   FairGeoMedium* medium;
   while((medium=(FairGeoMedium*)iter.Next())) {
     cout<<"  "<<medium->GetName()<<"\n";
   }
 }
FairGeoMedia& FairGeoMedia::operator= (const FairGeoMedia &) private
void FairGeoMedia::print ()
Definition at line 75 of file FairGeoMedia.cxx.
References author, description, FairGeoMedium::getAutoFlag(), media, and FairGeoMedium::print().
 {
   // Prints the media
   if (!author.IsNull()) { cout<<"//Author:      "<<author<<'\n'; }
   if (!description.IsNull()) { cout<<"//Description: "<<description<<'\n'; }
   cout<<"//----------------------------------------------------------\n";
   TListIter iter(media);
   FairGeoMedium* medium;
   Int_t i=0;
   while((medium=(FairGeoMedium*)iter.Next())) {
     if (medium->getAutoFlag()!=0) {
       medium->print();
       i++;
     }
   }
   if (i!=media->GetSize()) {
     iter.Reset();
     cout<<"//----------------------------------------------\n";
     cout<<"AUTONULL\n";
     cout<<"//----------------------------------------------\n";
     while((medium=(FairGeoMedium*)iter.Next())) {
       if (medium->getAutoFlag()==0) { medium->print(); }
     }
   }
 }
void FairGeoMedia::read (std::fstream & fin)
Definition at line 101 of file FairGeoMedia.cxx.
References FairLogger::endl(), INFO, LOG, media, and FairGeoMedium::read().
Referenced by FairGeoAsciiIo::read().
 {
   // Reads the media from file
   LOG(INFO) << "FairGeoMedia: Read media " << FairLogger::endl;
   const Int_t maxBuf=256;
   char buf[maxBuf];
   Int_t autoflag=1;
   while(!fin.eof()) {
     fin>>buf;
     if (buf[0]=='\0' || buf[0]=='/') { fin.getline(buf,maxBuf); }
     else if (fin.eof()) { break; }
     else {
       TString eleName(buf);
       if (eleName.CompareTo("AUTONULL")!=0) {
         FairGeoMedium* medium=new FairGeoMedium(eleName);
         medium->read(fin,autoflag);
         media->Add(medium);
       } else { autoflag=0; }
     }
   }
 }
void FairGeoMedia::setAuthor (TString & s) inline
Definition at line 45 of file FairGeoMedia.h.
 {author=s;}
void FairGeoMedia::setDescription (TString & s) inline
Definition at line 46 of file FairGeoMedia.h.
 {description=s;}
void FairGeoMedia::setInputFile (const char * file) inline
Definition at line 36 of file FairGeoMedia.h.
Referenced by FairGeoInterface::setMediaFile().
 { inputFile=file; }
void FairGeoMedia::write (std::fstream & fout)
Definition at line 123 of file FairGeoMedia.cxx.
References author, description, FairGeoMedium::getAutoFlag(), media, and FairGeoMedium::write().
Referenced by FairGeoAsciiIo::write().
 {
   // Writes the media to file
   if (!author.IsNull()) { fout<<"//Author:      "<<author<<'\n'; }
   if (!description.IsNull()) { fout<<"//Description: "<<description<<'\n'; }
   fout<<"//----------------------------------------------------------\n";
   TListIter iter(media);
   FairGeoMedium* medium;
   Int_t i=0;
   while((medium=(FairGeoMedium*)iter.Next())) {
     if (medium->getAutoFlag()!=0) {
       medium->write(fout);
       i++;
     }
   }
   if (i!=media->GetSize()) {
     iter.Reset();
     fout<<"//----------------------------------------------\n";
     fout<<"AUTONULL\n";
     fout<<"//----------------------------------------------\n";
     while((medium=(FairGeoMedium*)iter.Next())) {
       if (medium->getAutoFlag()==0) { medium->write(fout); }
     }
   }
 }
Member Data Documentation
TString FairGeoMedia::author private
name of input file or Oracle
Definition at line 31 of file FairGeoMedia.h.
Referenced by getAuthor(), print(), and write().
TString FairGeoMedia::description private
author of the media version
Definition at line 32 of file FairGeoMedia.h.
Referenced by getDescription(), print(), and write().
TString FairGeoMedia::inputFile private
list of media
Definition at line 30 of file FairGeoMedia.h.
Referenced by getInputFile().
TList* FairGeoMedia::media private
Definition at line 29 of file FairGeoMedia.h.
Referenced by addMedium(), getListOfMedia(), getMedium(), list(), print(), read(), write(), and ~FairGeoMedia().
The documentation for this class was generated from the following files:
FairGeoMedia.h
FairGeoMedia.cxx