FairRroot: FairMCResult Class Reference
FairMCResult Class Reference
#include <FairMCResult.h>
Public Member Functions
FairMCResult ()
FairMCResult (Int_t start, Int_t stop)
FairMCResult (const FairMCResult &result)
FairMCResult & operator= (const FairMCResult &result)
virtual ~FairMCResult ()
void SetStartType (Int_t start)
void SetStopType (Int_t stop)
Int_t GetStartType (void) const
Int_t GetStopType (void) const
virtual void Print (std::ostream &out=std::cout)
void SetStageId (Int_t type)
void SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index)
void SetEntry (FairMultiLinkedData *data, int index)
void SetEntry (FairMCEntry link)
void SetStage (std::vector< FairMCEntry > stage)
void SetLink (FairLink link, int index)
void AddLink (FairLink link, int index)
FairMCEntry GetEntry (int index) const
FairLink GetSingleLink (int entryIndex, int linkIndex) const
Int_t GetStageId (void) const
FairMCEntry GetMCLink (Int_t index)
int GetNEntries () const
int GetNLinks (int entryIndex) const
std::vector< FairMCEntry > GetEntryVector () const
FairMultiLinkedData PosInList (std::pair< int, int > link)
FairMultiLinkedData PosInList (FairLink link)
FairMultiLinkedData GetLinksWithType (Int_t type)
void RemoveType (Int_t type)
virtual void ClearEntries ()
Private Member Functions
ClassDef (FairMCResult, 2)
Private Attributes
Int_t fStartType
Int_t fStopType
Friends
std::ostream & operator<< (std::ostream &out, const FairMCResult &result)
Detailed Description
Definition at line 27 of file FairMCResult.h.
Constructor & Destructor Documentation
FairMCResult::FairMCResult ()
Definition at line 19 of file FairMCResult.cxx.
   : FairMCObject(),
     fStartType(-1),
     fStopType(-1)
 {
 }
FairMCResult::FairMCResult (Int_t start, Int_t stop)
Definition at line 30 of file FairMCResult.cxx.
   : FairMCObject(),
     fStartType(start),
     fStopType(stop)
 {
 }
FairMCResult::FairMCResult (const FairMCResult & result) inline
Definition at line 33 of file FairMCResult.h.
       : FairMCObject(result.GetStartType(), result.GetEntryVector()),
         fStartType(result.GetStartType()),
         fStopType(result.GetStopType()) {
     }
FairMCResult::~FairMCResult () virtual
Definition at line 26 of file FairMCResult.cxx.
 {
 }
Member Function Documentation
void FairMCObject::AddLink (FairLink link, int index) inherited
Definition at line 66 of file FairMCObject.cxx.
References FairMCObject::AdoptSize(), and FairMCObject::fStage.
Referenced by FairMCObject::SetLink().
 {
   AdoptSize(index);
   fStage[index].AddLink(link);
 }
FairMCResult::ClassDef (FairMCResult , 2) private
virtual void FairMCObject::ClearEntries () inline virtual inherited
Reimplemented in FairMCStage.
Definition at line 99 of file FairMCObject.h.
References FairMCObject::fStage.
Referenced by FairMCStage::ClearEntries().
 {fStage.clear();}
FairMCEntry FairMCObject::GetEntry (int index) const inline inherited
Definition at line 73 of file FairMCObject.h.
References FairMCObject::fStage.
 {return fStage[index];}
std::vector<FairMCEntry> FairMCObject::GetEntryVector () const inline inherited
Definition at line 84 of file FairMCObject.h.
References FairMCObject::fStage.
 {return fStage;}
FairMultiLinkedData FairMCObject::GetLinksWithType (Int_t type) inline inherited
Definition at line 89 of file FairMCObject.h.
References FairMultiLinkedData::AddLinks(), FairMCObject::GetMCLink(), and FairMCObject::GetNEntries().
{
       FairMultiLinkedData result;
       for (int i = 0; i < GetNEntries(); i++) {
         result.AddLinks(GetMCLink(i).GetLinksWithType(type));
       }
       return result;
     }
FairMCEntry FairMCObject::GetMCLink (Int_t index) inline inherited
Definition at line 80 of file FairMCObject.h.
References FairMCObject::fStage.
Referenced by FairMCMatchCreatorTask::Exec(), and FairMCObject::GetLinksWithType().
 {return fStage.at(index);}
int FairMCObject::GetNEntries () const inline inherited
Definition at line 82 of file FairMCObject.h.
References FairMCObject::fStage.
Referenced by FairMCMatchCreatorTask::Exec(), FairMCObject::GetLinksWithType(), FairMCMatch::GetMCInfoBackward(), and FairMCMatch::GetMCInfoForward().
 {return fStage.size();}
int FairMCObject::GetNLinks (int entryIndex) const inline inherited
Definition at line 83 of file FairMCObject.h.
References FairMCObject::fStage.
 {return fStage.at(entryIndex).GetNLinks();}
FairLink FairMCObject::GetSingleLink (int entryIndex, int linkIndex) const inline inherited
Definition at line 74 of file FairMCObject.h.
References FairMCObject::fStage.
{
       return fStage.at(entryIndex).GetLink(linkIndex);
     }
Int_t FairMCObject::GetStageId (void) const inline inherited
Definition at line 78 of file FairMCObject.h.
References FairMCObject::fStageId.
Referenced by FairMCObject::AdoptSize(), FairMCMatchCreatorTask::Exec(), FairMCMatch::GetMCInfoForward(), and FairMCObject::PosInList().
 {return fStageId;}
Int_t FairMCResult::GetStartType (void) const inline
Definition at line 56 of file FairMCResult.h.
References fStartType.
 {return fStartType;}
Int_t FairMCResult::GetStopType (void) const inline
Definition at line 57 of file FairMCResult.h.
References fStopType.
 {return fStopType;}
FairMCResult& FairMCResult::operator= (const FairMCResult & result) inline
Definition at line 40 of file FairMCResult.h.
References fStartType, fStopType, and FairMCObject::operator=().
{
       if (this == &result) { return *this; }
       FairMCObject::operator=(result);
       fStartType = result.fStartType;
       fStopType = result.fStopType;
       return *this;
     }
FairMultiLinkedData FairMCObject::PosInList (std::pair< int, int > link) inherited
FairMultiLinkedData FairMCObject::PosInList (FairLink link) inherited
Definition at line 85 of file FairMCObject.cxx.
References FairMultiLinkedData::AddLink(), FairMCObject::fStage, FairLink::GetIndex(), FairMCObject::GetStageId(), FairLink::GetType(), and FairMultiLinkedData::SetPersistanceCheck().
 {
   FairMultiLinkedData result;
   result.SetPersistanceCheck(kFALSE);
   for (int i = 0; i < fStage.size(); i++) {
     if (fStage[i].IsLinkInList(link.GetType(), link.GetIndex())) {
       result.AddLink(FairLink(GetStageId(), i));
     }
   }
   return result;
 }
virtual void FairMCResult::Print (std::ostream & out = std::cout) inline virtual
Reimplemented from FairMCObject.
Definition at line 59 of file FairMCResult.h.
 { out << *this;}
void FairMCObject::RemoveType (Int_t type) inherited
Definition at line 97 of file FairMCObject.cxx.
References FairMCObject::fStage.
 {
   for (int i = 0; i < fStage.size(); i++) {
     fStage[i].RemoveType(type);
   }
 }
void FairMCObject::SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index) inherited
Definition at line 40 of file FairMCObject.cxx.
References FairMultiLinkedData::AddLink(), FairMultiLinkedData::SetPersistanceCheck(), and FairMCEntry::SetPos().
Referenced by FairMCMatch::GetMCInfoBackward(), and FairMCMatch::GetMCInfoForward().
 {
   FairMCEntry myEntry;
   myEntry.SetPos(index);
   myEntry.SetPersistanceCheck(kFALSE);
   for (int i = 0; i < type.size(); i++) {
     myEntry.AddLink(FairLink(type[i],link[i]));
   }
   SetEntry(myEntry);
 }
void FairMCObject::SetEntry (FairMultiLinkedData * data, int index) inherited
Definition at line 51 of file FairMCObject.cxx.
References FairMCObject::AdoptSize(), FairMCObject::fStage, and FairMultiLinkedData::GetLinks().
 {
   AdoptSize(index);
   fStage[index].SetLinks(data->GetLinks());
 }
void FairMCObject::SetEntry (FairMCEntry link) inherited
Definition at line 30 of file FairMCObject.cxx.
References FairMCObject::AdoptSize(), FairMCObject::fStage, and FairMCEntry::GetPos().
 {
   if (entry.GetPos() < 0) {
     std::cout << "-E- FairMCObject::SetEntry(FairMCEntry): pos " << entry.GetPos() << std::endl;
     return;
   }
   AdoptSize(entry.GetPos());
   fStage[entry.GetPos()] = entry;
 }
void FairMCObject::SetLink (FairLink link, int index) inherited
Definition at line 57 of file FairMCObject.cxx.
References FairMCObject::AddLink(), and FairMCObject::fStage.
 {
   if (index < fStage.size()) {
     fStage[index].ResetLinks();
   }
   AddLink(link, index);
 }
void FairMCObject::SetStage (std::vector< FairMCEntry > stage) inline inherited
Definition at line 69 of file FairMCObject.h.
References FairMCObject::fStage.
 {fStage = stage;}
void FairMCObject::SetStageId (Int_t type) inline inherited
Definition at line 63 of file FairMCObject.h.
References FairMCObject::fStageId.
 {fStageId = type;}
void FairMCResult::SetStartType (Int_t start) inline
Definition at line 53 of file FairMCResult.h.
References fStartType.
 {fStartType = start;}
void FairMCResult::SetStopType (Int_t stop) inline
Definition at line 54 of file FairMCResult.h.
References fStopType.
 {fStopType = stop;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const FairMCResult & result) friend
Definition at line 61 of file FairMCResult.h.
{
       out << "MC Link from: " << result.GetStartType() << " to "  << result.GetStopType() << ":" << std::endl;
       ((FairMCObject)result).Print(out);
       return out;
     }
Member Data Documentation
Int_t FairMCResult::fStartType private
Definition at line 69 of file FairMCResult.h.
Referenced by GetStartType(), operator=(), and SetStartType().
Int_t FairMCResult::fStopType private
Definition at line 70 of file FairMCResult.h.
Referenced by GetStopType(), operator=(), and SetStopType().
The documentation for this class was generated from the following files:
FairMCResult.h
FairMCResult.cxx