FairRroot: runTestDetectorProcessorBin.cxx File Reference
Tutorial6/run/runTestDetectorProcessorBin.cxx File Reference
#include <iostream>
#include <csignal>
#include "FairMQLogger.h"
#include "FairMQProcessor.h"
#include "zeromq/FairMQTransportFactoryZMQ.h"
#include "FairTestDetectorMQRecoTask.h"
#include "FairTestDetectorHit.h"
#include "FairTestDetectorDigi.h"
#include "FairTestDetectorPayload.h"
Typedefs
typedef FairTestDetectorDigi TDigi
typedef FairTestDetectorHit THit
typedef TestDetectorPayload::Digi TPayloadIn
typedef TestDetectorPayload::Hit TPayloadOut
typedef
FairTestDetectorMQRecoTask
< TDigi, THit, TPayloadIn,
TPayloadOut > TProcessorTask
Functions
static void s_signal_handler (int signal)
static void s_catch_signals (void)
int main (int argc, char **argv)
Variables
FairMQProcessor processor
Typedef Documentation
typedef FairTestDetectorDigi TDigi
Definition at line 38 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.
typedef FairTestDetectorHit THit
Definition at line 39 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.
typedef TestDetectorPayload::Digi TPayloadIn
Definition at line 40 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.
typedef TestDetectorPayload::Hit TPayloadOut
Definition at line 41 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.
typedef FairTestDetectorMQRecoTask<TDigi, THit, TPayloadIn, TPayloadOut> TProcessorTask
Definition at line 42 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.
Function Documentation
int main (int argc, char ** argv)
Definition at line 68 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.
References FairMQStateMachine::BIND, FairMQStateMachine::ChangeState(), FairMQStateMachine::CONNECT, FairMQStateMachine::END, ERROR, FairMQDevice::Id, INFO, FairMQStateMachine::INIT, FairMQDevice::InputAddress, FairMQDevice::InputMethod, FairMQDevice::InputRcvBufSize, FairMQDevice::InputSocketType, LOG, FairMQDevice::NumInputs, FairMQDevice::NumIoThreads, FairMQDevice::NumOutputs, FairMQDevice::OutputAddress, FairMQDevice::OutputMethod, FairMQDevice::OutputSndBufSize, FairMQDevice::OutputSocketType, FairMQStateMachine::RUN, s_catch_signals(), FairMQStateMachine::SETINPUT, FairMQStateMachine::SETOUTPUT, FairMQDevice::SetProperty(), FairMQProcessor::SetTask(), FairMQDevice::SetTransport(), and FairMQStateMachine::STOP.
 {
     if (argc != 12)
     {
         cout << "Usage: testDetectorProcessor \tID processorTask numIoTreads\n"
              << "\t\tinputSocketType inputRcvBufSize inputMethod inputAddress\n"
              << "\t\toutputSocketType outputSndBufSize outputMethod outputAddress\n" << endl;
         return 1;
     }
     s_catch_signals();
     LOG(INFO) << "PID: " << getpid();
 #ifdef NANOMSG
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryNN();
 #else
     FairMQTransportFactory* transportFactory = new FairMQTransportFactoryZMQ();
 #endif
     processor.SetTransport(transportFactory);
     int i = 1;
     processor.SetProperty(FairMQProcessor::Id, argv[i]);
     ++i;
     if (strcmp(argv[i], "FairTestDetectorMQRecoTask") == 0)
     {
         TProcessorTask* task = new TProcessorTask();
         processor.SetTask(task);
     }
     else
     {
         LOG(ERROR) << "task not supported.";
         exit(1);
     }
     ++i;
     int numIoThreads;
     stringstream(argv[i]) >> numIoThreads;
     processor.SetProperty(FairMQProcessor::NumIoThreads, numIoThreads);
     ++i;
     processor.SetProperty(FairMQProcessor::NumInputs, 1);
     processor.SetProperty(FairMQProcessor::NumOutputs, 1);
     processor.ChangeState(FairMQProcessor::INIT);
     processor.SetProperty(FairMQProcessor::InputSocketType, argv[i], 0);
     ++i;
     int inputRcvBufSize;
     stringstream(argv[i]) >> inputRcvBufSize;
     processor.SetProperty(FairMQProcessor::InputRcvBufSize, inputRcvBufSize, 0);
     ++i;
     processor.SetProperty(FairMQProcessor::InputMethod, argv[i], 0);
     ++i;
     processor.SetProperty(FairMQProcessor::InputAddress, argv[i], 0);
     ++i;
     processor.SetProperty(FairMQProcessor::OutputSocketType, argv[i], 0);
     ++i;
     int outputSndBufSize;
     stringstream(argv[i]) >> outputSndBufSize;
     processor.SetProperty(FairMQProcessor::OutputSndBufSize, outputSndBufSize, 0);
     ++i;
     processor.SetProperty(FairMQProcessor::OutputMethod, argv[i], 0);
     ++i;
     processor.SetProperty(FairMQProcessor::OutputAddress, argv[i], 0);
     ++i;
     processor.ChangeState(FairMQProcessor::SETOUTPUT);
     processor.ChangeState(FairMQProcessor::SETINPUT);
     processor.ChangeState(FairMQProcessor::BIND);
     processor.ChangeState(FairMQProcessor::CONNECT);
     processor.ChangeState(FairMQProcessor::RUN);
     char ch;
     cin.get(ch);
     processor.ChangeState(FairMQProcessor::STOP);
     processor.ChangeState(FairMQProcessor::END);
     return 0;
 }
static void s_catch_signals (void) static
Definition at line 57 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.
References s_signal_handler().
Referenced by main().
 {
     struct sigaction action;
     action.sa_handler = s_signal_handler;
     action.sa_flags = 0;
     sigemptyset(&action.sa_mask);
     sigaction(SIGINT, &action, NULL);
     sigaction(SIGTERM, &action, NULL);
 }
static void s_signal_handler (int signal) static
Definition at line 46 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.
References FairMQStateMachine::ChangeState(), FairMQStateMachine::END, and FairMQStateMachine::STOP.
Referenced by s_catch_signals().
 {
     cout << endl << "Caught signal " << signal << endl;
     processor.ChangeState(FairMQProcessor::STOP);
     processor.ChangeState(FairMQProcessor::END);
     cout << "Shutdown complete. Bye!" << endl;
     exit(1);
 }
Variable Documentation
FairMQProcessor processor
Definition at line 44 of file Tutorial6/run/runTestDetectorProcessorBin.cxx.