FairRoot: TestDetectorProto::DigiPayload Class Reference
TestDetectorProto::DigiPayload Class Reference
#include <FairTestDetectorPayload.pb.h>
Public Member Functions
DigiPayload ()
virtual ~DigiPayload ()
DigiPayload (const DigiPayload &from)
DigiPayload & operator= (const DigiPayload &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (DigiPayload *other)
DigiPayload * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const DigiPayload &from)
void MergeFrom (const DigiPayload &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int digi_size () const
void clear_digi ()
const ::TestDetectorProto::Digi & digi (int index) const
inline::TestDetectorProto::Digi * mutable_digi (int index)
inline::TestDetectorProto::Digi * add_digi ()
const ::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Digi > & digi () const
inline::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Digi > * mutable_digi ()
DigiPayload ()
virtual ~DigiPayload ()
DigiPayload (const DigiPayload &from)
DigiPayload & operator= (const DigiPayload &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (DigiPayload *other)
DigiPayload * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const DigiPayload &from)
void MergeFrom (const DigiPayload &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int digi_size () const
void clear_digi ()
const ::TestDetectorProto::Digi & digi (int index) const
inline::TestDetectorProto::Digi * mutable_digi (int index)
inline::TestDetectorProto::Digi * add_digi ()
const ::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Digi > & digi () const
inline::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Digi > * mutable_digi ()
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const DigiPayload & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const DigiPayload & default_instance ()
Static Public Attributes
static const int kDigiFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Digi > digi_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(1+31)/32]
Static Private Attributes
static DigiPayload * default_instance_ = NULL
Friends
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
void protobuf_AddDesc_FairTestDetectorPayload_2eproto ()
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto ()
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto ()
Detailed Description
Definition at line 337 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Constructor & Destructor Documentation
TestDetectorProto::DigiPayload::DigiPayload ()
Definition at line 1119 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References SharedCtor().
Referenced by New().
   : ::google::protobuf::Message() {
   SharedCtor();
 }
TestDetectorProto::DigiPayload::~DigiPayload () virtual
Definition at line 1138 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References SharedDtor().
{
   SharedDtor();
 }
TestDetectorProto::DigiPayload::DigiPayload (const DigiPayload & from)
Definition at line 1127 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References MergeFrom(), and SharedCtor().
   : ::google::protobuf::Message() {
   SharedCtor();
   MergeFrom(from);
 }
TestDetectorProto::DigiPayload::DigiPayload ()
virtual TestDetectorProto::DigiPayload::~DigiPayload () virtual
TestDetectorProto::DigiPayload::DigiPayload (const DigiPayload & from)
Member Function Documentation
TestDetectorProto::Digi * TestDetectorProto::DigiPayload::add_digi () inline
Definition at line 863 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References digi_.
Referenced by MergePartialFromCodedStream().
{
   return digi_.Add();
 }
inline ::TestDetectorProto::Digi* TestDetectorProto::DigiPayload::add_digi ()
int TestDetectorProto::DigiPayload::ByteSize () const
int TestDetectorProto::DigiPayload::ByteSize () const
Definition at line 1241 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, digi(), digi_size(), and unknown_fields().
{
   int total_size = 0;
   // repeated .TestDetectorProto.Digi digi = 1;
   total_size += 1 * this->digi_size();
   for (int i = 0; i < this->digi_size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->digi(i));
   }
   if (!unknown_fields().empty()) {
     total_size +=
       ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
         unknown_fields());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void TestDetectorProto::DigiPayload::Clear ()
void TestDetectorProto::DigiPayload::Clear ()
Definition at line 1168 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _has_bits_, digi_, and mutable_unknown_fields().
Referenced by CopyFrom().
{
   digi_.Clear();
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
   mutable_unknown_fields()->Clear();
 }
void TestDetectorProto::DigiPayload::clear_digi () inline
Definition at line 854 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References digi_.
{
   digi_.Clear();
 }
void TestDetectorProto::DigiPayload::clear_digi () inline
void TestDetectorProto::DigiPayload::CopyFrom (const ::google::protobuf::Message & from)
void TestDetectorProto::DigiPayload::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1281 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void TestDetectorProto::DigiPayload::CopyFrom (const DigiPayload & from)
Definition at line 1287 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References Clear(), and MergeFrom().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void TestDetectorProto::DigiPayload::CopyFrom (const DigiPayload & from)
static const DigiPayload& TestDetectorProto::DigiPayload::default_instance () static
const DigiPayload & TestDetectorProto::DigiPayload::default_instance () static
Definition at line 1157 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References default_instance_, and protobuf_AddDesc_FairTestDetectorPayload_2eproto.
{
   if (default_instance_ == NULL) protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   return *default_instance_;
 }
const ::google::protobuf::Descriptor * TestDetectorProto::DigiPayload::descriptor () static
Definition at line 1152 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   return DigiPayload_descriptor_;
 }
static const ::google::protobuf::Descriptor* TestDetectorProto::DigiPayload::descriptor () static
const ::TestDetectorProto::Digi & TestDetectorProto::DigiPayload::digi (int index) const inline
Definition at line 857 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References digi_.
{
   return digi_.Get(index);
 }
const ::TestDetectorProto::Digi& TestDetectorProto::DigiPayload::digi (int index) const inline
const ::google::protobuf::RepeatedPtrField<::TestDetectorProto::Digi > & TestDetectorProto::DigiPayload::digi () const inline
Definition at line 867 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References digi_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return digi_;
 }
const ::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Digi >& TestDetectorProto::DigiPayload::digi () const inline
int TestDetectorProto::DigiPayload::digi_size () const inline
Definition at line 851 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References digi_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return digi_.size();
 }
int TestDetectorProto::DigiPayload::digi_size () const inline
int TestDetectorProto::DigiPayload::GetCachedSize () const inline
Definition at line 378 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _cached_size_.
 { return _cached_size_; }
int TestDetectorProto::DigiPayload::GetCachedSize () const inline
Definition at line 378 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _cached_size_.
 { return _cached_size_; }
::google::protobuf::Metadata TestDetectorProto::DigiPayload::GetMetadata () const
google::protobuf::Metadata TestDetectorProto::DigiPayload::GetMetadata () const
Definition at line 1307 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::Metadata metadata;
   metadata.descriptor = DigiPayload_descriptor_;
   metadata.reflection = DigiPayload_reflection_;
   return metadata;
 }
void TestDetectorProto::DigiPayload::InitAsDefaultInstance () private
Definition at line 1124 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto().
{
 }
void TestDetectorProto::DigiPayload::InitAsDefaultInstance () private
bool TestDetectorProto::DigiPayload::IsInitialized () const
bool TestDetectorProto::DigiPayload::IsInitialized () const
Definition at line 1293 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   return true;
 }
void TestDetectorProto::DigiPayload::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1263 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by CopyFrom(), and DigiPayload().
{
   GOOGLE_CHECK_NE(&from, this);
   const DigiPayload* source =
     ::google::protobuf::internal::dynamic_cast_if_available<const DigiPayload*>(
       &from);
   if (source == NULL) {
     ::google::protobuf::internal::ReflectionOps::Merge(from, this);
   } else {
     MergeFrom(*source);
   }
 }
void TestDetectorProto::DigiPayload::MergeFrom (const ::google::protobuf::Message & from)
void TestDetectorProto::DigiPayload::MergeFrom (const DigiPayload & from)
void TestDetectorProto::DigiPayload::MergeFrom (const DigiPayload & from)
Definition at line 1275 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References digi_, mutable_unknown_fields(), and unknown_fields().
{
   GOOGLE_CHECK_NE(&from, this);
   digi_.MergeFrom(from.digi_);
   mutable_unknown_fields()->MergeFrom(from.unknown_fields());
 }
bool TestDetectorProto::DigiPayload::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool TestDetectorProto::DigiPayload::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1174 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References add_digi(), DO_, and mutable_unknown_fields().
{
 #define DO_(EXPRESSION) if (!(EXPRESSION)) return false
   ::google::protobuf::uint32 tag;
   while ((tag = input->ReadTag()) != 0) {
     switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
       // repeated .TestDetectorProto.Digi digi = 1;
       case 1: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          parse_digi:
           DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                 input, add_digi()));
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(10)) goto parse_digi;
         if (input->ExpectAtEnd()) return true;
         break;
       }
       default: {
       handle_uninterpreted:
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
           return true;
         }
         DO_(::google::protobuf::internal::WireFormat::SkipField(
               input, tag, mutable_unknown_fields()));
         break;
       }
     }
   }
   return true;
 #undef DO_
 }
inline ::TestDetectorProto::Digi* TestDetectorProto::DigiPayload::mutable_digi (int index)
TestDetectorProto::Digi * TestDetectorProto::DigiPayload::mutable_digi (int index) inline
Definition at line 860 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References digi_.
{
   return digi_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::TestDetectorProto::Digi > * TestDetectorProto::DigiPayload::mutable_digi () inline
Definition at line 871 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References digi_.
{
   return &digi_;
 }
inline ::google::protobuf::RepeatedPtrField< ::TestDetectorProto::Digi >* TestDetectorProto::DigiPayload::mutable_digi ()
inline ::google::protobuf::UnknownFieldSet* TestDetectorProto::DigiPayload::mutable_unknown_fields () inline
Definition at line 353 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
{
     return &_unknown_fields_;
   }
inline ::google::protobuf::UnknownFieldSet* TestDetectorProto::DigiPayload::mutable_unknown_fields () inline
Definition at line 353 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
{
     return &_unknown_fields_;
   }
DigiPayload* TestDetectorProto::DigiPayload::New () const
DigiPayload * TestDetectorProto::DigiPayload::New () const
Definition at line 1164 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References DigiPayload().
{
   return new DigiPayload;
 }
DigiPayload& TestDetectorProto::DigiPayload::operator= (const DigiPayload & from) inline
Definition at line 344 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
DigiPayload& TestDetectorProto::DigiPayload::operator= (const DigiPayload & from) inline
Definition at line 344 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
void TestDetectorProto::DigiPayload::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1211 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References digi(), digi_size(), and unknown_fields().
{
   // repeated .TestDetectorProto.Digi digi = 1;
   for (int i = 0; i < this->digi_size(); i++) {
     ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
       1, this->digi(i), output);
   }
   if (!unknown_fields().empty()) {
     ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
         unknown_fields(), output);
   }
 }
void TestDetectorProto::DigiPayload::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
google::protobuf::uint8 * TestDetectorProto::DigiPayload::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1225 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References digi(), digi_size(), and unknown_fields().
{
   // repeated .TestDetectorProto.Digi digi = 1;
   for (int i = 0; i < this->digi_size(); i++) {
     target = ::google::protobuf::internal::WireFormatLite::
       WriteMessageNoVirtualToArray(
         1, this->digi(i), target);
   }
   if (!unknown_fields().empty()) {
     target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
         unknown_fields(), target);
   }
   return target;
 }
::google::protobuf::uint8* TestDetectorProto::DigiPayload::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
void TestDetectorProto::DigiPayload::SetCachedSize (int size) const private
void TestDetectorProto::DigiPayload::SetCachedSize (int size) const private
Definition at line 1147 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_.
{
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
 }
void TestDetectorProto::DigiPayload::SharedCtor () private
Definition at line 1133 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, and _has_bits_.
Referenced by DigiPayload().
{
   _cached_size_ = 0;
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
 }
void TestDetectorProto::DigiPayload::SharedCtor () private
void TestDetectorProto::DigiPayload::SharedDtor () private
Definition at line 1142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References default_instance_.
Referenced by ~DigiPayload().
{
   if (this != default_instance_) {
   }
 }
void TestDetectorProto::DigiPayload::SharedDtor () private
void TestDetectorProto::DigiPayload::Swap (DigiPayload * other)
void TestDetectorProto::DigiPayload::Swap (DigiPayload * other)
Definition at line 1298 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, and digi_.
{
   if (other != this) {
     digi_.Swap(&other->digi_);
     std::swap(_has_bits_[0], other->_has_bits_[0]);
     _unknown_fields_.Swap(&other->_unknown_fields_);
     std::swap(_cached_size_, other->_cached_size_);
   }
 }
const ::google::protobuf::UnknownFieldSet& TestDetectorProto::DigiPayload::unknown_fields () const inline
Definition at line 349 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
     return _unknown_fields_;
   }
const ::google::protobuf::UnknownFieldSet& TestDetectorProto::DigiPayload::unknown_fields () const inline
Definition at line 349 of file Tutorial6/streams/FairTestDetectorPayload.pb.h.
References _unknown_fields_.
{
     return _unknown_fields_;
   }
Friends And Related Function Documentation
void protobuf_AddDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
Referenced by default_instance().
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void protobuf_AddDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 153 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\035FairTestDetectorPayload.proto\022\021TestDet"
     "ectorProto\"W\n\004Digi\022\n\n\002fX\030\001 \001(\005\022\n\n\002fY\030\002 \001"
     "(\005\022\n\n\002fZ\030\003 \001(\005\022\022\n\nfTimeStamp\030\004 \001(\001\022\027\n\017fT"
     "imeStampError\030\005 \001(\001\"\251\001\n\003Hit\022\r\n\005detID\030\001 \001"
     "(\005\022\017\n\007mcindex\030\002 \001(\005\022\014\n\004posX\030\003 \001(\001\022\014\n\004pos"
     "Y\030\004 \001(\001\022\014\n\004posZ\030\005 \001(\001\022\r\n\005dposX\030\006 \001(\001\022\r\n\005"
     "dposY\030\007 \001(\001\022\r\n\005dposZ\030\010 \001(\001\022\022\n\nfTimeStamp"
     "\030\t \001(\001\022\027\n\017fTimeStampError\030\n \001(\001\"4\n\013DigiP"
     "ayload\022%\n\004digi\030\001 \003(\0132\027.TestDetectorProto"
     ".Digi\"1\n\nHitPayload\022#\n\003hit\030\001 \003(\0132\026.TestD"
     "etectorProto.Hit", 416);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "FairTestDetectorPayload.proto", &protobuf_RegisterTypes);
   Digi::default_instance_ = new Digi();
   Hit::default_instance_ = new Hit();
   DigiPayload::default_instance_ = new DigiPayload();
   HitPayload::default_instance_ = new HitPayload();
   Digi::default_instance_->InitAsDefaultInstance();
   Hit::default_instance_->InitAsDefaultInstance();
   DigiPayload::default_instance_->InitAsDefaultInstance();
   HitPayload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FairTestDetectorPayload_2eproto);
 }
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void protobuf_AssignDesc_FairTestDetectorPayload_2eproto () friend
Definition at line 39 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   protobuf_AddDesc_FairTestDetectorPayload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "FairTestDetectorPayload.proto");
   GOOGLE_CHECK(file != NULL);
   Digi_descriptor_ = file->message_type(0);
   static const int Digi_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, fz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, ftimestamperror_),
   };
   Digi_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Digi_descriptor_,
       Digi::default_instance_,
       Digi_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Digi, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Digi));
   Hit_descriptor_ = file->message_type(1);
   static const int Hit_offsets_[10] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, detid_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, mcindex_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, posz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, dposz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, ftimestamperror_),
   };
   Hit_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Hit_descriptor_,
       Hit::default_instance_,
       Hit_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Hit, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Hit));
   DigiPayload_descriptor_ = file->message_type(2);
   static const int DigiPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, digi_),
   };
   DigiPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       DigiPayload_descriptor_,
       DigiPayload::default_instance_,
       DigiPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DigiPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(DigiPayload));
   HitPayload_descriptor_ = file->message_type(3);
   static const int HitPayload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, hit_),
   };
   HitPayload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       HitPayload_descriptor_,
       HitPayload::default_instance_,
       HitPayload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HitPayload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(HitPayload));
 }
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto () friend
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
void protobuf_ShutdownFile_FairTestDetectorPayload_2eproto () friend
Definition at line 142 of file Tutorial3/data/FairTestDetectorPayload.pb.cc.
{
   delete Digi::default_instance_;
   delete Digi_reflection_;
   delete Hit::default_instance_;
   delete Hit_reflection_;
   delete DigiPayload::default_instance_;
   delete DigiPayload_reflection_;
   delete HitPayload::default_instance_;
   delete HitPayload_reflection_;
 }
Member Data Documentation
int TestDetectorProto::DigiPayload::_cached_size_ mutable private
Definition at line 410 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
google::protobuf::uint32 TestDetectorProto::DigiPayload::_has_bits_ private
Definition at line 411 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by Clear(), SharedCtor(), and Swap().
google::protobuf::UnknownFieldSet TestDetectorProto::DigiPayload::_unknown_fields_ private
Definition at line 406 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
static DigiPayload * TestDetectorProto::DigiPayload::default_instance_ = NULL static private
Definition at line 418 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by default_instance(), TestDetectorProto::protobuf_AddDesc_FairTestDetectorPayload_2eproto(), TestDetectorProto::protobuf_AssignDesc_FairTestDetectorPayload_2eproto(), TestDetectorProto::protobuf_ShutdownFile_FairTestDetectorPayload_2eproto(), and SharedDtor().
google::protobuf::RepeatedPtrField<::TestDetectorProto::Digi > TestDetectorProto::DigiPayload::digi_ private
Definition at line 408 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
Referenced by add_digi(), Clear(), clear_digi(), digi(), digi_size(), MergeFrom(), mutable_digi(), and Swap().
static const int TestDetectorProto::DigiPayload::kDigiFieldNumber = 1 static
Definition at line 394 of file Tutorial3/data/FairTestDetectorPayload.pb.h.
The documentation for this class was generated from the following files:
Tutorial3/data/FairTestDetectorPayload.pb.h
Tutorial3/data/FairTestDetectorPayload.pb.cc