FairRroot: FairMCStack Class Reference
FairMCStack Class Reference
#include <FairMCStack.h>
Public Member Functions
FairMCStack ()
FairMCStack (const char *name, Int_t iVerbose=1)
virtual ~FairMCStack ()
void SetVerbose (Int_t iVerbose)
virtual void Exec (Option_t *option)
virtual InitStatus Init ()
virtual void SetParContainers ()
virtual void Finish ()
void Reset ()
TEveTrackList * GetTrGroup (TParticle *P)
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
ClassDef (FairMCStack, 1)
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
TClonesArray * fTrackList
TEveTrackPropagator * fTrPr
FairEventManager * fEventManager
TObjArray * fEveTrList
TString fEvent
TEveTrackList * fTrList
Float_t x1 [3]
Float_t p1 [3]
Float_t ein [15]
Float_t x2 [3]
Float_t p2 [3]
TGeant3 * gMC3
Double_t MinEnergyLimit
Double_t MaxEnergyLimit
Double_t PEnergy
FairGeanePro * fPro
FairTrajFilter * fTrajFilter
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 36 of file FairMCStack.h.
Constructor & Destructor Documentation
FairMCStack::FairMCStack ()
Default constructor
Definition at line 32 of file FairMCStack.cxx.
 {
 }
FairMCStack::FairMCStack (const char * name, Int_t iVerbose = 1)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 40 of file FairMCStack.cxx.
   : FairTask(name, iVerbose),
     fEveTrList( new TObjArray(16))
 {
 }
FairMCStack::~FairMCStack () virtual
Destructor
Definition at line 216 of file FairMCStack.cxx.
 {
 }
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline inherited
Definition at line 80 of file FairTask.h.
References FairRootManager::CheckBranch(), FairTask::fInputPersistance, and FairRootManager::Instance().
{
       FairRootManager* ioman = FairRootManager::Instance();
       fInputPersistance = ioman->CheckBranch(branchName);
     }
FairMCStack::ClassDef (FairMCStack , 1) protected
void FairMCStack::Exec (Option_t * option) virtual
Executed task
Definition at line 95 of file FairMCStack.cxx.
References FairEventManager::Color(), DEBUG, DEBUG2, DEBUG3, FairLogger::endl(), fEventManager, fEveTrList, fPro, fTrackList, fTrajFilter, fTrList, fTrPr, FairEventManager::GetCurrentPDG(), FairTrajFilter::GetCurrentTrk(), FairEventManager::GetMaxEnergy(), FairEventManager::GetMinEnergy(), FairMCTrack::GetMomentum(), FairMCTrack::GetPdgCode(), FairMCTrack::GetStartVertex(), GetTrGroup(), FairEventManager::IsPriOnly(), LOG, MaxEnergyLimit, MinEnergyLimit, p1, p2, PEnergy, FairGeanePro::Propagate(), FairGeanePro::PropagateToLength(), Reset(), FairEventManager::SetEvtMaxEnergy(), FairEventManager::SetEvtMinEnergy(), x1, and x2.
 {
   if (IsActive()) {
     LOG(DEBUG) << " FairMCStack::Exec "<< FairLogger::endl;
     FairMCTrack* tr;
     const Double_t* point;
     Reset();
     for (Int_t i=0; i<fTrackList->GetEntriesFast(); i++)  {
       LOG(DEBUG2) << "FairMCStack::Exec "<< i << FairLogger::endl;
       tr=(FairMCTrack*)fTrackList->At(i);
       TVector3 Ptot = tr->GetMomentum();
       Int_t  MotherId =tr->GetMotherID();
       TVector3 Vertex =tr->GetStartVertex();
       Double_t time= tr->GetStartTime()*1e-09;
       x1[0]=Vertex.x();
       x1[1]=Vertex.y();
       x1[2]=Vertex.z();
       p1[0]=Ptot.Px();
       p1[1]=Ptot.Py();
       p1[2]=Ptot.Pz();
       //TParticle *P=(TParticle *)tr->GetParticle();
       Double_t mass=0.0;
       Double_t ene=0.0;
       TParticlePDG* fParticlePDG = TDatabasePDG::Instance()->GetParticle(tr->GetPdgCode());
       if (fParticlePDG) {
         mass    = fParticlePDG->Mass();
       }
       if ( mass >= 0 ) {
         ene  = TMath::Sqrt(mass*mass + Ptot.Mag2());
       }
       //TParticle(Int_t pdg, Int_t status, Int_t mother1, Int_t mother2, Int_t daughter1, Int_t daughter2, Double_t px, Double_t py, Double_t pz, Double_t etot, Double_t vx, Double_t vy, Double_t vz, Double_t time)
       TParticle* P =new TParticle(tr->GetPdgCode(), i, MotherId, -1, -1, -1, Ptot.Px(), Ptot.Py(),Ptot.Pz(),ene, Vertex.x(), Vertex.z(), Vertex.z(), time);
       PEnergy=P->Energy();
       MinEnergyLimit=TMath::Min(PEnergy,MinEnergyLimit) ;
       MaxEnergyLimit=TMath::Max(PEnergy,MaxEnergyLimit) ;
       LOG(DEBUG2) << "MinEnergyLimit " << MinEnergyLimit << " MaxEnergyLimit " << MaxEnergyLimit << FairLogger::endl;
       if (fEventManager->IsPriOnly() && P->GetMother(0)>-1) { continue; }
       if(fEventManager->GetCurrentPDG()!=0 && fEventManager->GetCurrentPDG()!= tr->GetPdgCode()) { continue; }
       LOG(DEBUG2) << "PEnergy " << PEnergy << " Min "  << fEventManager->GetMinEnergy() << " Max " << fEventManager->GetMaxEnergy() << FairLogger::endl;
       if( (PEnergy<fEventManager->GetMinEnergy()) || (PEnergy >fEventManager->GetMaxEnergy())) { continue; }
       //here we have to propagate
       //Int_t Np=tr->GetNpoints();
       fTrList= GetTrGroup(P);
       TEveTrack* track= new TEveTrack(P, tr->GetPdgCode(), fTrPr);
       track->SetLineColor(fEventManager->Color(tr->GetPdgCode()));
       //  Int_t GeantCode=TDatabasePDG::Instance()->ConvertPdgToGeant3(tr->GetPdgCode());
       //  gMC3->Ertrak(x1,p1,x2,p2,GeantCode,"L");
       fPro->PropagateToLength(100.0);
       fPro->Propagate(x1, p1, x2, p2,tr->GetPdgCode());
       TGeoTrack* tr1= fTrajFilter->GetCurrentTrk();
       Int_t Np=tr1->GetNpoints();
       for (Int_t n=0; n<Np; n++) {
         point=tr1->GetPoint(n);
         track->SetPoint(n,point[0],point[1],point[2]);
         TEveVector pos= TEveVector(point[0], point[1],point[2]);
         TEvePathMark* path = new TEvePathMark();
         path->fV=pos ;
         path->fTime= point[3];
         if(n==0) {
           TEveVector Mom= TEveVector(P->Px(), P->Py(),P->Pz());
           path->fP=Mom;
         }
         LOG(DEBUG3) << "Path marker added " << path << FairLogger::endl;
         track->AddPathMark(*path);
         LOG(DEBUG3) << "Path marker added " << path << FairLogger::endl;
       }
       fTrList->AddElement(track);
       LOG(DEBUG2) << "track added " << track->GetName() << FairLogger::endl;}
       /*   for (Int_t n=0; n<Np; n++){
              point=tr->GetPoint(n);
              track->SetPoint(n,point[0],point[1],point[2]);
              TEveVector pos= TEveVector(point[0], point[1],point[2]);
            TEvePathMark *path = new TEvePathMark();
          path->fV=pos ;
          path->fTime= point[3];
              if(n==0){
                  TEveVector Mom= TEveVector(P->Px(), P->Py(),P->Pz());
                  path->fP=Mom;
              }
              LOG(DEBUG3) << "Path marker added " << path << FairLogger::endl;
              track->AddPathMark(*path);
              LOG(DEBUG3) << "Path marker added " << path << FairLogger::endl;
           }
           fTrList->AddElement(track);
        LOG(DEBUG3) << "track added " << track->GetName() << FairLogger::endl;
       */
     }
     for (Int_t i=0; i<fEveTrList->GetEntriesFast(); i++) {
       TEveTrackList* TrListIn=( TEveTrackList*) fEveTrList->At(i);
       TrListIn->FindMomentumLimits(TrListIn, kFALSE);
     }
     fEventManager->SetEvtMaxEnergy(MaxEnergyLimit);
     fEventManager->SetEvtMinEnergy(MinEnergyLimit);
     gEve->Redraw3D(kFALSE);
   }
void FairMCStack::Finish () virtual
Action after each event
Reimplemented from FairTask.
Definition at line 226 of file FairMCStack.cxx.
 {
 }
void FairTask::FinishEvent () virtual inherited
Action at end of event. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 97 of file FairTask.cxx.
References FairTask::FinishEvents().
Referenced by FairRunOnline::EventLoop(), FairMCApplication::FinishEvent(), FairTask::FinishEvents(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAnaProof::RunOneEvent(), and FairRunAna::RunTSBuffers().
 {
   if ( ! fActive ) { return; }
   FinishEvents();
   //  FinishTasks();
 }
void FairTask::FinishEvents () protected inherited
Recursive FinishEvent of subtasks
Definition at line 172 of file FairTask.cxx.
References FairTask::FinishEvent().
Referenced by FairTask::FinishEvent().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishEvent(); }
 }
void FairTask::FinishTask () virtual inherited
Action at end of run. For this task and all of the subtasks.
Reimplemented in FairRingSorterTask.
Definition at line 105 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTasks().
Referenced by FairRunAna::DummyRun(), FairRunOnline::Finish(), FairMCApplication::FinishRun(), FairTask::FinishTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMixed(), FairRunAna::RunMQ(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
 {
   if ( ! fActive ) { return; }
   Finish();
   FinishTasks();
 }
void FairTask::FinishTasks () protected inherited
Recursive finish of subtasks
Definition at line 162 of file FairTask.cxx.
References FairTask::Finish(), and FairTask::FinishTask().
Referenced by FairTask::FinishTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->FinishTask(); }
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->Finish(); }
 }
TEveTrackList * FairMCStack::GetTrGroup (TParticle * P)
Definition at line 240 of file FairMCStack.cxx.
References FairEventManager::Color(), fEventManager, fEveTrList, fTrList, and fTrPr.
Referenced by Exec().
 {
   fTrList=0;
   for (Int_t i=0; i<fEveTrList->GetEntriesFast(); i++) {
     TEveTrackList* TrListIn=( TEveTrackList*) fEveTrList->At(i);
     if ( strcmp(TrListIn->GetName(),P->GetName())==0 ) {
       fTrList= TrListIn;
       break;
     }
   }
   if(fTrList ==0) {
     fTrPr=new TEveTrackPropagator();
     fTrList= new  TEveTrackList(P->GetName(),fTrPr );
     fTrList->SetMainColor(fEventManager->Color(P->GetPdgCode()));
     fEveTrList->Add(fTrList);
     gEve->AddElement( fTrList ,fEventManager );
     fTrList->SetRnrLine(kTRUE);
   }
   return fTrList;
 }
InitStatus FairMCStack::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 47 of file FairMCStack.cxx.
References DEBUG, DEBUG2, ein, FairLogger::endl(), ERROR, fEvent, fEventManager, fPro, fTrackList, fTrajFilter, FairEventManager::GetEvtMaxEnergy(), FairEventManager::GetEvtMinEnergy(), FairRootManager::GetObject(), gMC3, FairEventManager::Instance(), FairRootManager::Instance(), FairTrajFilter::Instance(), kERROR, kSUCCESS, LOG, MaxEnergyLimit, MinEnergyLimit, p1, p2, PEnergy, x1, and x2.
 {
   LOG(DEBUG) <<  "FairMCStack::Init()" << FairLogger::endl;
   FairRootManager* fManager = FairRootManager::Instance();
   fTrackList = (TClonesArray*)fManager->GetObject("MCTrack");
   if(fTrackList==0) {
     LOG(ERROR) << "FairMCStack::Init()  branch " << GetName() << " Not found! Task will be deactivated "<< FairLogger::endl;
     SetActive(kFALSE);
   }
   LOG(DEBUG2) <<  "FairMCStack::Init() get track list" << fTrackList<< FairLogger::endl;
   LOG(DEBUG2) <<  "FairMCStack::Init()  create propagator" << FairLogger::endl;
   fEventManager =FairEventManager::Instance();
   LOG(DEBUG2) <<  "FairMCStack::Init() get instance of FairEventManager " << FairLogger::endl;
   fEvent = "Current Event";
   MinEnergyLimit=fEventManager->GetEvtMinEnergy();
   MaxEnergyLimit=fEventManager->GetEvtMaxEnergy();
   PEnergy=0;
   fPro = new FairGeanePro();
   gMC3 = (TGeant3*) gMC;
   x1[0]=0;
   x1[1]=0;
   x1[2]=0;
   p1[0]=0;
   p1[1]=0;
   p1[2]=0;
   x2[0]=0;
   x2[1]=0;
   x2[2]=0;
   p2[0]=0;
   p2[1]=0;
   p2[2]=0;
   for(Int_t i=0; i<15; i++) { ein[i]=0; }
   Float_t length[1];
   length[0]=100.0;
   //gMC3->Eufill(1, ein, length);
   fTrajFilter = FairTrajFilter::Instance();
   if(IsActive()) { return kSUCCESS; }
   else { return kERROR; }
 }
void FairTask::InitTask () inherited
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 58 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, FairTask::Init(), FairTask::InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAnaProof::Init(), FairMQProcessor::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairTask::InitTasks(), and FairMCApplication::InitTasks().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = Init();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Initialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   InitTasks();
 }
void FairTask::InitTasks () protected inherited
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 129 of file FairTask.cxx.
References FairTask::InitTask().
Referenced by FairTask::InitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->InitTask(); }
 }
virtual InitStatus FairTask::ReInit () inline protected virtual inherited
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in FairEventBuilderManager, FairRingSorterTask, FairTutorialDet4HitProducerIdealMisalign, FairTutorialDet2Digitizer, FairDbTutAccessRtdbTask, FairTutorialDet4MilleWriter, FairTutorialDet4StraightLineFitter, NewTask, and FairTestDetectorHitProducerSmearing.
Definition at line 101 of file FairTask.h.
References kSUCCESS.
Referenced by FairTask::ReInitTask().
 { return kSUCCESS; };
void FairTask::ReInitTask () inherited
Reinitialisation. For this task and all of the subtasks.
Definition at line 73 of file FairTask.cxx.
References FairLogger::Fatal(), FairTask::fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, FairTask::ReInit(), and FairTask::ReInitTasks().
Referenced by FairRunOnline::InitContainers(), FairRunAna::InitContainers(), FairTask::ReInitTasks(), FairRunAna::Run(), FairRunAna::RunEventReco(), FairRunAna::RunMQ(), and FairRunAnaProof::RunOneEvent().
 {
   if ( ! fActive ) { return; }
   InitStatus tStat = ReInit();
   if ( tStat == kFATAL ) {
     fLogger->Fatal(MESSAGE_ORIGIN,"Reinitialization of Task %s failed fatally", fName.Data());
   }
   if ( tStat == kERROR ) { fActive = kFALSE; }
   ReInitTasks();
 }
void FairTask::ReInitTasks () protected inherited
Recursive reinitialisation of subtasks
Definition at line 140 of file FairTask.cxx.
References FairTask::ReInitTask().
Referenced by FairTask::ReInitTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->ReInitTask(); }
 }
void FairMCStack::Reset ()
Definition at line 231 of file FairMCStack.cxx.
References fEventManager, and fEveTrList.
Referenced by Exec().
 {
   for (Int_t i=0; i<fEveTrList->GetEntriesFast(); i++) {
     TEveTrackList*  ele=( TEveTrackList*) fEveTrList->At(i);
     gEve->RemoveElement(ele,fEventManager);
   }
   fEveTrList->Clear();
 }
void FairTask::SetInputPersistance (Bool_t val) inline inherited
Definition at line 78 of file FairTask.h.
References FairTask::fInputPersistance.
 {fInputPersistance = val;}
void FairMCStack::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 220 of file FairMCStack.cxx.
 {
 }
void FairTask::SetParTask () inherited
Set parameters. For this task and all of the subtasks.
Definition at line 88 of file FairTask.cxx.
References FairTask::SetParContainers(), and FairTask::SetParTasks().
Referenced by FairRunAnaProof::Init(), FairRunAna::Init(), FairRunOnline::Init(), FairMCApplication::SetParTask(), and FairTask::SetParTasks().
 {
   if ( ! fActive ) { return; }
   SetParContainers();
   SetParTasks();
 }
void FairTask::SetParTasks () protected inherited
Recursive parameter initialisation for subtasks
Definition at line 151 of file FairTask.cxx.
References FairTask::SetParTask().
Referenced by FairTask::SetParTask().
 {
   TIter next(GetListOfTasks());
   FairTask* task;
   while( ( task=dynamic_cast<FairTask*>(next()) ) ) { task->SetParTask(); }
 }
void FairMCStack::SetVerbose (Int_t iVerbose)
Set verbosity level. For this task and all of the subtasks.
Member Data Documentation
Float_t FairMCStack::ein[15] protected
Definition at line 79 of file FairMCStack.h.
Referenced by Init().
TString FairMCStack::fEvent protected
Definition at line 74 of file FairMCStack.h.
Referenced by Init().
FairEventManager* FairMCStack::fEventManager protected
Definition at line 72 of file FairMCStack.h.
Referenced by Exec(), GetTrGroup(), Init(), and Reset().
TObjArray* FairMCStack::fEveTrList protected
Definition at line 73 of file FairMCStack.h.
Referenced by Exec(), GetTrGroup(), and Reset().
Int_t FairTask::fInputPersistance protected inherited
Indicates if input branch is persistant.
Definition at line 89 of file FairTask.h.
Referenced by FairTask::CheckInputPersistance(), and FairTask::SetInputPersistance().
FairLogger* FairTask::fLogger protected inherited
Definition at line 90 of file FairTask.h.
Referenced by FairTestDetectorHitProducerSmearing::Exec(), NewTask::Exec(), FairTutorialDet4StraightLineFitter::Exec(), FairTestDetectorHitProducerSmearing::FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::FairTutorialDet4StraightLineFitter(), FairTestDetectorHitProducerSmearing::Finish(), NewTask::Finish(), FairTutorialDet4StraightLineFitter::Finish(), FairTestDetectorHitProducerSmearing::Init(), NewTask::Init(), FairTutorialDet4StraightLineFitter::Init(), FairTask::InitTask(), NewTask::NewTask(), FairTestDetectorHitProducerSmearing::ReInit(), NewTask::ReInit(), FairTutorialDet4StraightLineFitter::ReInit(), FairTask::ReInitTask(), FairTestDetectorHitProducerSmearing::SetParContainers(), NewTask::SetParContainers(), FairTutorialDet4StraightLineFitter::SetParContainers(), FairTestDetectorHitProducerSmearing::~FairTestDetectorHitProducerSmearing(), FairTutorialDet4StraightLineFitter::~FairTutorialDet4StraightLineFitter(), and NewTask::~NewTask().
FairGeanePro* FairMCStack::fPro protected
Definition at line 86 of file FairMCStack.h.
Referenced by Exec(), and Init().
TClonesArray* FairMCStack::fTrackList protected
Definition at line 70 of file FairMCStack.h.
Referenced by Exec(), and Init().
FairTrajFilter* FairMCStack::fTrajFilter protected
Definition at line 87 of file FairMCStack.h.
Referenced by Exec(), and Init().
TEveTrackList* FairMCStack::fTrList protected
Definition at line 75 of file FairMCStack.h.
Referenced by Exec(), and GetTrGroup().
TEveTrackPropagator* FairMCStack::fTrPr protected
Definition at line 71 of file FairMCStack.h.
Referenced by Exec(), and GetTrGroup().
Int_t FairTask::fVerbose protected inherited
Definition at line 88 of file FairTask.h.
Referenced by FairTestDetectorDigiSorterTask::AddNewDataToTClonesArray(), MySorterTask::AddNewDataToTClonesArray(), FairMCMatchCreatorTask::Exec(), FairEventBuilderManager::Exec(), FairRingSorterTask::Exec(), FairTestDetectorRecoTask::FairTestDetectorRecoTask(), FairTestDetectorTimeRecoTask::FairTestDetectorTimeRecoTask(), FairEventBuilderManager::FillEventVectors(), FairRingSorterTask::FinishTask(), FairRingSorterTask::Init(), FairMCTracks::SetVerbose(), and FairTask::SetVerbose().
TGeant3* FairMCStack::gMC3 protected
Definition at line 82 of file FairMCStack.h.
Referenced by Init().
Double_t FairMCStack::MaxEnergyLimit protected
Definition at line 84 of file FairMCStack.h.
Referenced by Exec(), and Init().
Double_t FairMCStack::MinEnergyLimit protected
Definition at line 83 of file FairMCStack.h.
Referenced by Exec(), and Init().
Float_t FairMCStack::p1[3] protected
Definition at line 78 of file FairMCStack.h.
Referenced by Exec(), and Init().
Float_t FairMCStack::p2[3] protected
Definition at line 81 of file FairMCStack.h.
Referenced by Exec(), and Init().
Double_t FairMCStack::PEnergy protected
Definition at line 85 of file FairMCStack.h.
Referenced by Exec(), and Init().
Float_t FairMCStack::x1[3] protected
Definition at line 77 of file FairMCStack.h.
Referenced by Exec(), and Init().
Float_t FairMCStack::x2[3] protected
Definition at line 80 of file FairMCStack.h.
Referenced by Exec(), and Init().
The documentation for this class was generated from the following files:
FairMCStack.h
FairMCStack.cxx