FairRoot: sampler::Payload Class Reference
sampler::Payload Class Reference
#include <payload.pb.h>
Public Member Functions
Payload ()
virtual ~Payload ()
Payload (const Payload &from)
Payload & operator= (const Payload &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Payload *other)
Payload * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Payload &from)
void MergeFrom (const Payload &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int data_size () const
void clear_data ()
const ::sampler::Content & data (int index) const
inline::sampler::Content * mutable_data (int index)
inline::sampler::Content * add_data ()
const ::google::protobuf::RepeatedPtrField< ::sampler::Content > & data () const
inline::google::protobuf::RepeatedPtrField< ::sampler::Content > * mutable_data ()
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Payload & default_instance ()
Static Public Attributes
static const int kDataFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedPtrField< ::sampler::Content > data_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(1+31)/32]
Static Private Attributes
static Payload * default_instance_ = NULL
Friends
void protobuf_AddDesc_payload_2eproto ()
void protobuf_AssignDesc_payload_2eproto ()
void protobuf_ShutdownFile_payload_2eproto ()
Detailed Description
Definition at line 170 of file payload.pb.h.
Constructor & Destructor Documentation
sampler::Payload::Payload ()
Definition at line 497 of file payload.pb.cc.
References SharedCtor().
Referenced by New().
   : ::google::protobuf::Message() {
   SharedCtor();
 }
sampler::Payload::~Payload () virtual
Definition at line 516 of file payload.pb.cc.
References SharedDtor().
                   {
   SharedDtor();
 }
sampler::Payload::Payload (const Payload & from)
Definition at line 505 of file payload.pb.cc.
References MergeFrom(), and SharedCtor().
   : ::google::protobuf::Message() {
   SharedCtor();
   MergeFrom(from);
 }
Member Function Documentation
sampler::Content * sampler::Payload::add_data () inline
Definition at line 387 of file payload.pb.h.
References data_.
Referenced by MergePartialFromCodedStream(), and FairMQProtoSampler::Run().
{
   return data_.Add();
 }
int sampler::Payload::ByteSize () const
Definition at line 619 of file payload.pb.cc.
References _cached_size_, data(), data_size(), and unknown_fields().
{
   int total_size = 0;
   // repeated .sampler.Content data = 1;
   total_size += 1 * this->data_size();
   for (int i = 0; i < this->data_size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->data(i));
   }
   if (!unknown_fields().empty()) {
     total_size +=
       ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
         unknown_fields());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void sampler::Payload::Clear ()
Definition at line 546 of file payload.pb.cc.
References _has_bits_, data_, and mutable_unknown_fields().
Referenced by CopyFrom().
                     {
   data_.Clear();
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
   mutable_unknown_fields()->Clear();
 }
void sampler::Payload::clear_data () inline
Definition at line 378 of file payload.pb.h.
References data_.
{
   data_.Clear();
 }
void sampler::Payload::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 659 of file payload.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
void sampler::Payload::CopyFrom (const Payload & from)
Definition at line 665 of file payload.pb.cc.
References Clear(), and MergeFrom().
{
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const ::sampler::Content & sampler::Payload::data (int index) const inline
Definition at line 381 of file payload.pb.h.
References data_.
{
   return data_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::sampler::Content > & sampler::Payload::data () const inline
Definition at line 391 of file payload.pb.h.
References data_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
                     {
   return data_;
 }
int sampler::Payload::data_size () const inline
Definition at line 375 of file payload.pb.h.
References data_.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
   return data_.size();
 }
const Payload & sampler::Payload::default_instance () static
Definition at line 535 of file payload.pb.cc.
References default_instance_, and protobuf_AddDesc_payload_2eproto.
{
   if (default_instance_ == NULL) protobuf_AddDesc_payload_2eproto();
   return *default_instance_;
 }
const ::google::protobuf::Descriptor * sampler::Payload::descriptor () static
Definition at line 530 of file payload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   return Payload_descriptor_;
 }
int sampler::Payload::GetCachedSize () const inline
Definition at line 211 of file payload.pb.h.
References _cached_size_.
 { return _cached_size_; }
google::protobuf::Metadata sampler::Payload::GetMetadata () const
Definition at line 685 of file payload.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::Metadata metadata;
   metadata.descriptor = Payload_descriptor_;
   metadata.reflection = Payload_reflection_;
   return metadata;
 }
void sampler::Payload::InitAsDefaultInstance () private
Definition at line 502 of file payload.pb.cc.
Referenced by sampler::protobuf_AddDesc_payload_2eproto().
{
 }
bool sampler::Payload::IsInitialized () const
Definition at line 671 of file payload.pb.cc.
{
   return true;
 }
void sampler::Payload::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 641 of file payload.pb.cc.
Referenced by CopyFrom(), and Payload().
{
   GOOGLE_CHECK_NE(&from, this);
   const Payload* source =
     ::google::protobuf::internal::dynamic_cast_if_available<const Payload*>(
       &from);
   if (source == NULL) {
     ::google::protobuf::internal::ReflectionOps::Merge(from, this);
   } else {
     MergeFrom(*source);
   }
 }
void sampler::Payload::MergeFrom (const Payload & from)
Definition at line 653 of file payload.pb.cc.
References data_, mutable_unknown_fields(), and unknown_fields().
{
   GOOGLE_CHECK_NE(&from, this);
   data_.MergeFrom(from.data_);
   mutable_unknown_fields()->MergeFrom(from.unknown_fields());
 }
bool sampler::Payload::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 552 of file payload.pb.cc.
References add_data(), DO_, and mutable_unknown_fields().
{
 #define DO_(EXPRESSION) if (!(EXPRESSION)) return false
   ::google::protobuf::uint32 tag;
   while ((tag = input->ReadTag()) != 0) {
     switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
       // repeated .sampler.Content data = 1;
       case 1: {
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          parse_data:
           DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                 input, add_data()));
         } else {
           goto handle_uninterpreted;
         }
         if (input->ExpectTag(10)) goto parse_data;
         if (input->ExpectAtEnd()) return true;
         break;
       }
       default: {
       handle_uninterpreted:
         if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
             ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
           return true;
         }
         DO_(::google::protobuf::internal::WireFormat::SkipField(
               input, tag, mutable_unknown_fields()));
         break;
       }
     }
   }
   return true;
 #undef DO_
 }
sampler::Content * sampler::Payload::mutable_data (int index) inline
Definition at line 384 of file payload.pb.h.
References data_.
{
   return data_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::sampler::Content > * sampler::Payload::mutable_data () inline
Definition at line 395 of file payload.pb.h.
References data_.
                       {
   return &data_;
 }
inline ::google::protobuf::UnknownFieldSet* sampler::Payload::mutable_unknown_fields () inline
Definition at line 186 of file payload.pb.h.
References _unknown_fields_.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
{
     return &_unknown_fields_;
   }
Payload * sampler::Payload::New () const
Definition at line 542 of file payload.pb.cc.
References Payload().
{
   return new Payload;
 }
Payload& sampler::Payload::operator= (const Payload & from) inline
Definition at line 177 of file payload.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
void sampler::Payload::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 589 of file payload.pb.cc.
References data(), data_size(), and unknown_fields().
{
   // repeated .sampler.Content data = 1;
   for (int i = 0; i < this->data_size(); i++) {
     ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
       1, this->data(i), output);
   }
   if (!unknown_fields().empty()) {
     ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
         unknown_fields(), output);
   }
 }
google::protobuf::uint8 * sampler::Payload::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 603 of file payload.pb.cc.
References data(), data_size(), and unknown_fields().
{
   // repeated .sampler.Content data = 1;
   for (int i = 0; i < this->data_size(); i++) {
     target = ::google::protobuf::internal::WireFormatLite::
       WriteMessageNoVirtualToArray(
         1, this->data(i), target);
   }
   if (!unknown_fields().empty()) {
     target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
         unknown_fields(), target);
   }
   return target;
 }
void sampler::Payload::SetCachedSize (int size) const private
Definition at line 525 of file payload.pb.cc.
References _cached_size_.
{
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
 }
void sampler::Payload::SharedCtor () private
Definition at line 511 of file payload.pb.cc.
References _cached_size_, and _has_bits_.
Referenced by Payload().
{
   _cached_size_ = 0;
   ::memset(_has_bits_, 0, sizeof(_has_bits_));
 }
void sampler::Payload::SharedDtor () private
Definition at line 520 of file payload.pb.cc.
References default_instance_.
Referenced by ~Payload().
{
   if (this != default_instance_) {
   }
 }
void sampler::Payload::Swap (Payload * other)
Definition at line 676 of file payload.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, and data_.
{
   if (other != this) {
     data_.Swap(&other->data_);
     std::swap(_has_bits_[0], other->_has_bits_[0]);
     _unknown_fields_.Swap(&other->_unknown_fields_);
     std::swap(_cached_size_, other->_cached_size_);
   }
 }
const ::google::protobuf::UnknownFieldSet& sampler::Payload::unknown_fields () const inline
Definition at line 182 of file payload.pb.h.
References _unknown_fields_.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
     return _unknown_fields_;
   }
Friends And Related Function Documentation
void protobuf_AddDesc_payload_2eproto () friend
Definition at line 100 of file payload.pb.cc.
Referenced by default_instance().
{
   static bool already_here = false;
   if (already_here) return;
   already_here = true;
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
     "\n\rpayload.proto\022\007sampler\"@\n\007Content\022\t\n\001a"
     "\030\001 \001(\001\022\t\n\001b\030\002 \001(\001\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022"
     "\t\n\001z\030\005 \001(\005\")\n\007Payload\022\036\n\004data\030\001 \003(\0132\020.sa"
     "mpler.Content", 133);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "payload.proto", &protobuf_RegisterTypes);
   Content::default_instance_ = new Content();
   Payload::default_instance_ = new Payload();
   Content::default_instance_->InitAsDefaultInstance();
   Payload::default_instance_->InitAsDefaultInstance();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_payload_2eproto);
 }
void protobuf_AssignDesc_payload_2eproto () friend
Definition at line 33 of file payload.pb.cc.
{
   protobuf_AddDesc_payload_2eproto();
   const ::google::protobuf::FileDescriptor* file =
     ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
       "payload.proto");
   GOOGLE_CHECK(file != NULL);
   Content_descriptor_ = file->message_type(0);
   static const int Content_offsets_[5] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, a_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, b_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, z_),
   };
   Content_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Content_descriptor_,
       Content::default_instance_,
       Content_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Content));
   Payload_descriptor_ = file->message_type(1);
   static const int Payload_offsets_[1] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, data_),
   };
   Payload_reflection_ =
     new ::google::protobuf::internal::GeneratedMessageReflection(
       Payload_descriptor_,
       Payload::default_instance_,
       Payload_offsets_,
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, _has_bits_[0]),
       GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Payload, _unknown_fields_),
       -1,
       ::google::protobuf::DescriptorPool::generated_pool(),
       ::google::protobuf::MessageFactory::generated_factory(),
       sizeof(Payload));
 }
void protobuf_ShutdownFile_payload_2eproto () friend
Definition at line 93 of file payload.pb.cc.
{
   delete Content::default_instance_;
   delete Content_reflection_;
   delete Payload::default_instance_;
   delete Payload_reflection_;
 }
Member Data Documentation
int sampler::Payload::_cached_size_ mutable private
Definition at line 243 of file payload.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
::google::protobuf::uint32 sampler::Payload::_has_bits_[(1+31)/32] private
Definition at line 244 of file payload.pb.h.
Referenced by Clear(), SharedCtor(), and Swap().
::google::protobuf::UnknownFieldSet sampler::Payload::_unknown_fields_ private
Definition at line 239 of file payload.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
::google::protobuf::RepeatedPtrField< ::sampler::Content > sampler::Payload::data_ private
Definition at line 241 of file payload.pb.h.
Referenced by add_data(), Clear(), clear_data(), data(), data_size(), MergeFrom(), mutable_data(), and Swap().
Payload * sampler::Payload::default_instance_ = NULL static private
Definition at line 251 of file payload.pb.h.
Referenced by default_instance(), sampler::protobuf_AddDesc_payload_2eproto(), sampler::protobuf_AssignDesc_payload_2eproto(), sampler::protobuf_ShutdownFile_payload_2eproto(), and SharedDtor().
const int sampler::Payload::kDataFieldNumber = 1 static
Definition at line 227 of file payload.pb.h.
The documentation for this class was generated from the following files:
payload.pb.h
payload.pb.cc