FairRoot: rvmove Class Reference
rvmove Class Reference
Public Member Functions
rvmove ()
rvmove (rvmove &&other)
~rvmove ()
rvmove & operator= (rvmove &&other)
Static Public Member Functions
static rvmove create ()
Public Attributes
void * ptr
char * array
Private Member Functions
rvmove (const rvmove &)
rvmove & operator= (const rvmove &)
Detailed Description
Definition at line 3 of file cxx11-test-rvalue-references.cpp.
Constructor & Destructor Documentation
rvmove::rvmove () inline
Definition at line 8 of file cxx11-test-rvalue-references.cpp.
Referenced by create().
     : ptr(0),
     array(new char[10])
    {
      ptr = this;
    }
rvmove::rvmove (rvmove && other) inline
Definition at line 15 of file cxx11-test-rvalue-references.cpp.
     : ptr(other.ptr),
     array(other.array)
    {
     other.array = 0;
     other.ptr = 0;
    }
rvmove::~rvmove () inline
Definition at line 23 of file cxx11-test-rvalue-references.cpp.
References array.
    {
     assert(((ptr != 0) && (array != 0)) || ((ptr == 0) && (array == 0)));
     delete[] array;
    }
rvmove::rvmove (const rvmove &) private
Member Function Documentation
static rvmove rvmove::create () inline static
Definition at line 39 of file cxx11-test-rvalue-references.cpp.
References rvmove().
Referenced by main().
    {
      return rvmove();
    }
rvmove& rvmove::operator= (rvmove && other) inline
Definition at line 29 of file cxx11-test-rvalue-references.cpp.
References array.
    {
      delete[] array;
      ptr = other.ptr;
      array = other.array;
      other.array = 0;
      other.ptr = 0;
      return *this;
    }
rvmove& rvmove::operator= (const rvmove &) private
Member Data Documentation
char* rvmove::array
Definition at line 6 of file cxx11-test-rvalue-references.cpp.
Referenced by operator=(), and ~rvmove().
void* rvmove::ptr
Definition at line 5 of file cxx11-test-rvalue-references.cpp.
Referenced by main().
The documentation for this class was generated from the following file:
cxx11-test-rvalue-references.cpp